.Func<@VAR_VALUE_TYPE@ (@OBJECT_NAME@::*)(@VAR_KEY_ARG_TYPE@)>(
    "Get@VAR_CAMELCASE_NAME@ByKey", &@OBJECT_NAME@::Get@VAR_CAMELCASE_NAME@)
.Func("@VAR_CAMELCASE_NAME@KeyExists", &@OBJECT_NAME@::@VAR_CAMELCASE_NAME@KeyExists)
.Func("Get@VAR_CAMELCASE_NAME@Keys", &@OBJECT_NAME@::Get@VAR_CAMELCASE_NAME@Keys)
.Func<bool (@OBJECT_NAME@::*)(@VAR_KEY_ARG_TYPE@, @VAR_VALUE_ARG_TYPE@)>(
    "Set@VAR_CAMELCASE_NAME@Entry", &@OBJECT_NAME@::Set@VAR_CAMELCASE_NAME@)
.Func("Remove@VAR_CAMELCASE_NAME@", &@OBJECT_NAME@::Remove@VAR_CAMELCASE_NAME@)
.Func("Clear@VAR_CAMELCASE_NAME@", &@OBJECT_NAME@::Clear@VAR_CAMELCASE_NAME@)
.Func("@VAR_CAMELCASE_NAME@Count", &@OBJECT_NAME@::@VAR_CAMELCASE_NAME@Count)