.Func<@VAR_VALUE_TYPE@ (@OBJECT_NAME@::*)(@VAR_KEY_ARG_TYPE@)>(
    "Get@VAR_CAMELCASE_NAME@ByKey", &@OBJECT_NAME@::Get@VAR_CAMELCASE_NAME@)
.Func<bool (@OBJECT_NAME@::*)(@VAR_KEY_ARG_TYPE@) const>(
    "@VAR_CAMELCASE_NAME@KeyExists", &@OBJECT_NAME@::@VAR_CAMELCASE_NAME@KeyExists)
.Func<bool (@OBJECT_NAME@::*)(@VAR_KEY_ARG_TYPE@, @VAR_VALUE_ARG_TYPE@)>(
    "Set@VAR_CAMELCASE_NAME@Entry", &@OBJECT_NAME@::Set@VAR_CAMELCASE_NAME@)
.Func<bool (@OBJECT_NAME@::*)(@VAR_KEY_ARG_TYPE@)>(
    "Remove@VAR_CAMELCASE_NAME@", &@OBJECT_NAME@::Remove@VAR_CAMELCASE_NAME@)
.Func<void (@OBJECT_NAME@::*)()>(
    "Clear@VAR_CAMELCASE_NAME@", &@OBJECT_NAME@::Clear@VAR_CAMELCASE_NAME@)
.Func<size_t (@OBJECT_NAME@::*)() const>(
    "@VAR_CAMELCASE_NAME@Count", &@OBJECT_NAME@::@VAR_CAMELCASE_NAME@Count)