.Func("Insert@VAR_CAMELCASE_NAME@", &@OBJECT_NAME@::Insert@VAR_CAMELCASE_NAME@)
.Func("Remove@VAR_CAMELCASE_NAME@", &@OBJECT_NAME@::Remove@VAR_CAMELCASE_NAME@)
.Func("Clear@VAR_CAMELCASE_NAME@", &@OBJECT_NAME@::Clear@VAR_CAMELCASE_NAME@)
.Func("@VAR_CAMELCASE_NAME@Count", &@OBJECT_NAME@::@VAR_CAMELCASE_NAME@Count)