COMP_hack: libcomp::Log Class Reference
libcomp::Log Class Reference
Logging interface capable of logging messages to the terminal or a file.
#include <Log.h>
Public Types
typedef void(* Hook_t)(LogComponent_t comp, Level_t level, const String &msg, void *pUserData)
Prototype of a function to be called when a log event occurs.
enum Level_t {
LOG_LEVEL_DEBUG = 0, LOG_LEVEL_INFO, LOG_LEVEL_WARNING, LOG_LEVEL_ERROR,
LOG_LEVEL_CRITICAL, LOG_LEVEL_COUNT
}
All valid log levels.
Public Member Functions
~Log ()
Deconstruct and delete the Log singleton.
void AddLogHook (Hook_t func, void *pUserData=0)
Add a log hook to the logging subsystem.
void AddLogHook (const std::function< void(LogComponent_t comp, Level_t level, const String &msg)> &func)
Add a log hook to the logging subsystem.
void AddStandardOutputHook ()
Add the built-in hook to log to standard output.
void ClearHooks ()
Remove all log hooks.
bool GetLogCompression () const
Get if the log rotation will compress logs.
bool GetLogFileTimestampsEnabled () const
Get if the log file timestamps are enabled.
Level_t GetLogLevel (LogComponent_t comp) const
Get the specified logging level for a component.
String GetLogPath () const
Get the path to the log file.
int GetLogRotationCount () const
Get the number of logs that will be rotated.
int GetLogRotationDays () const
Get the number of days until the logs will be rotated.
bool GetLogRotationEnabled () const
Get if the log rotation feature is enabled.
void LogMessage (libcomp::LogMessage *pMessage)
Log a message.
void SetLogCompression (bool enabled)
Set if the log rotation will compress logs.
void SetLogFileTimestampsEnabled (bool enabled)
Set if the log file timestamps are enabled.
void SetLogLevel (LogComponent_t comp, Level_t level)
Set the specified logging level for a component.
void SetLogPath (const String &path, bool truncate)
Set the path to the log file.
void SetLogRotationCount (int count)
Set the number of logs that will be rotated.
void SetLogRotationDays (int days)
Set the number of days until the logs will be rotated.
void SetLogRotationEnabled (bool enabled)
Set if the log rotation feature is enabled.
bool ShouldLog (LogComponent_t comp, Level_t level) const
Function to determine if a message should be logged given the provided component and log level.
Static Public Member Functions
static Log * GetSingletonPtr ()
Return a pointer to the Log singleton.
Protected Member Functions
Log ()
void LogMessage (const std::chrono::time_point< std::chrono::system_clock > &timestamp, LogComponent_t comp, Level_t level, const String &msg)
void MessageLoop ()
void RotateLogs ()
Static Protected Member Functions
static bool FileDelete (const libcomp::String &file)
static bool FileExists (const libcomp::String &file)
static bool FileMove (const libcomp::String &oldPath, const libcomp::String &newPath)
Protected Attributes
EnumMap< LogComponent_t, Level_t > mComponentLogLevels
std::unordered_map< Hook_t,
void * > mHooks
std::list< std::function< void(LogComponent_t
comp, Level_t level, const
String &msg)> > mLambdaHooks
int64_t mLastLog
bool mLogCompression
std::ofstream * mLogFile
bool mLogFileTimestampEnabled
String mLogPath
int mLogRotationCount
int mLogRotationDays
bool mLogRotationEnabled
MessageQueue
< libcomp::LogMessage * > mMessages
std::thread mThread
Detailed Description
Logging interface capable of logging messages to the terminal or a file.
The Log class is implemented as a singleton. The constructor should not be called and is protected because of this. Instead, the first call to GetSingletonPtr() will construct the object. Subsequent calls will simply return a pointer to the existing object. The object should only be deleted once at the end of the application or not at all. The method SetLogPath() will open and initialize the log file. Initialization of the log subsystem can be done with the following code:
Log::GetSingletonPtr()->SetLogPath("/var/log/my.log");
There is currently only one log file created. There is no compression or rotation of log files. The logging subsystem consists of five different log levels. Each level has a macro that saves typing of GetSingletonPtr to log a simple message. These macros are LOG_CRITICAL, LOG_ERROR, LOG_WARNING, LOG_INFO, and LOG_DEBUG. Each log level can be omitted from the log file by setting SetLogLevelEnabled.
Log hooks can be implemented to process log messages differently. All hooks must conform to the Log::Hook_t function prototype. This consists of a log level, the message, and the user data provided by the AddLogHook method. For more information on the function prototype, see the docs for Log::Hook_t and AddLogHook.
Definition at line 130 of file Log.h.
Member Typedef Documentation
typedef void(* libcomp::Log::Hook_t)(LogComponent_t comp, Level_t level, const String &msg, void *pUserData)
Prototype of a function to be called when a log event occurs.
When a log message is generated, level describes the error level of the message, msg contains the data, and pUserData is optional user defined data passed to Log::AddLogHook along with the function. See Level_t for all possible log levels.
Definition at line 153 of file Log.h.
Member Enumeration Documentation
enum libcomp::Log::Level_t
All valid log levels.
Enumerator
LOG_LEVEL_DEBUG
LOG_LEVEL_INFO
LOG_LEVEL_WARNING
LOG_LEVEL_ERROR
LOG_LEVEL_CRITICAL
LOG_LEVEL_COUNT
Definition at line 136 of file Log.h.
Constructor & Destructor Documentation
Log::~Log ()
Deconstruct and delete the Log singleton.
Definition at line 328 of file Log.cpp.
References LogMessage(), and mThread.
Log::Log () protected
Definition at line 290 of file Log.cpp.
References libcomp::General, mComponentLogLevels, MessageLoop(), mLogCompression, mLogFileTimestampEnabled, mLogRotationCount, mLogRotationDays, mLogRotationEnabled, and mThread.
Referenced by GetSingletonPtr().
Member Function Documentation
void Log::AddLogHook (Log::Hook_t func, void * pUserData = 0)
Add a log hook to the logging subsystem.
The log hook func will be called for each new log message that is enabled through SetLogLevelEnabled. The log level, message, and user data passed to this method as pUserData will be provided to the log hook function.
Parameters
func Log hook function to call.
pUserData User defined data to pass to the log hook function.
Definition at line 496 of file Log.cpp.
References mHooks.
Referenced by AddStandardOutputHook(), and TEST().
void Log::AddLogHook (const std::function< void(LogComponent_t comp, Level_t level, const String &msg)> & func)
Add a log hook to the logging subsystem.
The log hook func will be called for each new log message that is enabled through SetLogLevelEnabled. The log level and message will be provided to the log hook function.
Parameters
func Log hook function to call.
Definition at line 502 of file Log.cpp.
References mLambdaHooks.
void Log::AddStandardOutputHook ()
Add the built-in hook to log to standard output.
Definition at line 508 of file Log.cpp.
References AddLogHook(), and LogToStandardOutput().
void Log::ClearHooks ()
Remove all log hooks.
Definition at line 514 of file Log.cpp.
References mHooks, and mLambdaHooks.
Referenced by TEST().
bool Log::FileDelete (const libcomp::String & file) static protected
Definition at line 708 of file Log.cpp.
References libcomp::String::C(), and libcomp::String::Replace().
Referenced by RotateLogs().
bool Log::FileExists (const libcomp::String & file) static protected
Definition at line 699 of file Log.cpp.
References libcomp::String::C(), and libcomp::String::Replace().
Referenced by RotateLogs().
bool Log::FileMove (const libcomp::String & oldPath, const libcomp::String & newPath) static protected
Definition at line 688 of file Log.cpp.
References libcomp::String::C(), and libcomp::String::Replace().
Referenced by RotateLogs().
bool Log::GetLogCompression () const
Get if the log rotation will compress logs.
Returns
true if log rotation will compress logs.
Definition at line 564 of file Log.cpp.
References mLogCompression.
bool Log::GetLogFileTimestampsEnabled () const
Get if the log file timestamps are enabled.
Returns
true if file logging timestamps are enabled.
Definition at line 542 of file Log.cpp.
References mLogFileTimestampEnabled.
Log::Level_t Log::GetLogLevel (LogComponent_t comp) const
Get the specified logging level for a component.
Parameters
comp A logging component.
Returns
The logging level for the component.
Definition at line 521 of file Log.cpp.
References mComponentLogLevels.
String Log::GetLogPath () const
Get the path to the log file.
Returns
Path to the log file.
Definition at line 437 of file Log.cpp.
References mLogPath.
int Log::GetLogRotationCount () const
Get the number of logs that will be rotated.
Returns
Number of logs that will be rotated.
Definition at line 574 of file Log.cpp.
References mLogRotationCount.
int Log::GetLogRotationDays () const
Get the number of days until the logs will be rotated.
Returns
Number of days until the logs will be rotated.
Definition at line 584 of file Log.cpp.
References mLogRotationDays.
bool Log::GetLogRotationEnabled () const
Get if the log rotation feature is enabled.
Returns
true if log rotation is enabled.
Definition at line 554 of file Log.cpp.
References mLogRotationEnabled.
Log * Log::GetSingletonPtr () static
Return a pointer to the Log singleton.
If the singleton has not been created, this method will create the singleton first.
Returns
Pointer to the Log singleton. This method should never return a null pointer.
Definition at line 337 of file Log.cpp.
References gLogInst, and Log().
Referenced by libcomp::BaseServer::ReadConfig(), libcomp::Exception::RegisterSignalHandler(), and TEST().
void Log::LogMessage (libcomp::LogMessage * pMessage)
Log a message.
Parameters
pMessage Message to log.
Note
This function will take ownership of the message.
Definition at line 351 of file Log.cpp.
References libcomp::String::C(), libcomp::LogMessage::GetLevel(), libcomp::LogMessage::GetMsg(), and mMessages.
Referenced by MessageLoop(), and ~Log().
void Log::LogMessage (const std::chrono::time_point< std::chrono::system_clock > & timestamp, LogComponent_t comp, Log::Level_t level, const String & msg) protected
Definition at line 363 of file Log.cpp.
References libcomp::String::Arg(), libcomp::String::C(), libcomp::String::IsEmpty(), LOG_LEVEL_COUNT, libcomp::LogComponentToString(), mHooks, mLambdaHooks, mLastLog, mLogFile, mLogFileTimestampEnabled, mLogRotationDays, mLogRotationEnabled, RotateLogs(), ShouldLog(), and libcomp::String::Size().
void Log::MessageLoop () protected
Definition at line 736 of file Log.cpp.
References gLogInst, LogMessage(), mLogFile, and mMessages.
Referenced by Log().
void Log::RotateLogs () protected
Definition at line 594 of file Log.cpp.
References libcomp::String::C(), libcomp::String::Clear(), FileDelete(), FileExists(), FileMove(), libcomp::String::IsEmpty(), mLogCompression, mLogFile, mLogPath, and mLogRotationCount.
Referenced by LogMessage().
void Log::SetLogCompression (bool enabled)
Set if the log rotation will compress logs.
Parameters
enabled If log rotation will compress logs.
Definition at line 569 of file Log.cpp.
References mLogCompression.
void Log::SetLogFileTimestampsEnabled (bool enabled)
Set if the log file timestamps are enabled.
Parameters
enabled If file logging timestamps are enabled.
Definition at line 548 of file Log.cpp.
References mLogFileTimestampEnabled.
void Log::SetLogLevel (LogComponent_t comp, Level_t level)
Set the specified logging level for a component.
Parameters
comp A logging component.
level A logging level.
Definition at line 536 of file Log.cpp.
References mComponentLogLevels.
void Log::SetLogPath (const String & path, bool truncate)
Set the path to the log file.
This will open the log file and optionally truncate.
Parameters
path Path to the log file.
truncate true if the file should be truncated, false if it should append to the existing file.
Definition at line 442 of file Log.cpp.
References libcomp::String::C(), libcomp::String::Clear(), libcomp::String::IsEmpty(), mLogFile, and mLogPath.
void Log::SetLogRotationCount (int count)
Set the number of logs that will be rotated.
Parameters
count Number of logs that will be rotated.
Definition at line 579 of file Log.cpp.
References mLogRotationCount.
void Log::SetLogRotationDays (int days)
Set the number of days until the logs will be rotated.
Parameters
days Number of days until the logs will be rotated.
Definition at line 589 of file Log.cpp.
References mLogRotationDays.
void Log::SetLogRotationEnabled (bool enabled)
Set if the log rotation feature is enabled.
Parameters
enabled If log rotation is enabled.
Definition at line 559 of file Log.cpp.
References mLogRotationEnabled.
bool Log::ShouldLog (LogComponent_t comp, Level_t level) const
Function to determine if a message should be logged given the provided component and log level.
Parameters
comp Component to log.
level Level to log.
Returns
true if the message should be logged; false otherwise.
Definition at line 717 of file Log.cpp.
References mComponentLogLevels, and to_underlying().
Referenced by LogMessage().
Member Data Documentation
EnumMap<LogComponent_t, Level_t> libcomp::Log::mComponentLogLevels protected
Definition at line 413 of file Log.h.
Referenced by GetLogLevel(), Log(), SetLogLevel(), and ShouldLog().
std::unordered_map<Hook_t, void*> libcomp::Log::mHooks protected
Definition at line 407 of file Log.h.
Referenced by AddLogHook(), ClearHooks(), and LogMessage().
std::list<std::function<void(LogComponent_t comp, Level_t level, const String& msg)> > libcomp::Log::mLambdaHooks protected
Definition at line 420 of file Log.h.
Referenced by AddLogHook(), ClearHooks(), and LogMessage().
int64_t libcomp::Log::mLastLog protected
Definition at line 426 of file Log.h.
Referenced by LogMessage().
bool libcomp::Log::mLogCompression protected
Definition at line 383 of file Log.h.
Referenced by GetLogCompression(), Log(), RotateLogs(), and SetLogCompression().
std::ofstream* libcomp::Log::mLogFile protected
Definition at line 401 of file Log.h.
Referenced by LogMessage(), MessageLoop(), RotateLogs(), and SetLogPath().
bool libcomp::Log::mLogFileTimestampEnabled protected
Definition at line 371 of file Log.h.
Referenced by GetLogFileTimestampsEnabled(), Log(), LogMessage(), and SetLogFileTimestampsEnabled().
String libcomp::Log::mLogPath protected
Definition at line 365 of file Log.h.
Referenced by GetLogPath(), RotateLogs(), and SetLogPath().
int libcomp::Log::mLogRotationCount protected
Definition at line 389 of file Log.h.
Referenced by GetLogRotationCount(), Log(), RotateLogs(), and SetLogRotationCount().
int libcomp::Log::mLogRotationDays protected
Definition at line 395 of file Log.h.
Referenced by GetLogRotationDays(), Log(), LogMessage(), and SetLogRotationDays().
bool libcomp::Log::mLogRotationEnabled protected
Definition at line 377 of file Log.h.
Referenced by GetLogRotationEnabled(), Log(), LogMessage(), and SetLogRotationEnabled().
MessageQueue<libcomp::LogMessage*> libcomp::Log::mMessages protected
Definition at line 432 of file Log.h.
Referenced by LogMessage(), and MessageLoop().
std::thread libcomp::Log::mThread protected
Definition at line 438 of file Log.h.
Referenced by Log(), and ~Log().
The documentation for this class was generated from the following files:
Log.h
Log.cpp