COMP_hack: libcomp::ObjectReference< T > Class Template Reference
libcomp::ObjectReference< T > Class Template Reference
Templated class that handles references to a PersistentObject derived class that can be lazy loaded from the database when needed.
#include <ObjectReference.h>
Public Member Functions
ObjectReference ()
Create an empty reference of the templated type.
ObjectReference (const libobjgen::UUID &uuid)
Create a reference of the templated type with the UUID set.
ObjectReference (std::shared_ptr< T > ref)
Create a reference of the templated type with the pointer set.
~ObjectReference ()
Clean up the reference.
const std::shared_ptr< T > Get ()
Get the pointer to the referenced object.
const std::shared_ptr< T > Get (const std::shared_ptr< Database > &db, bool reload=false)
Get the pointer to the referenced object.
const std::shared_ptr< T > GetCurrentReference () const
Get the pointer to the referenced object but do not load from the database if it is not loaded already.
const libobjgen::UUID & GetUUID () const
Get the UUID of the reference.
bool IsNull () const
Check if there is no UUID and no reference set.
operator bool () const
Checks if the pointer is valid or a nullptr.
std::shared_ptr< T > operator-> ()
Get the pointer to the referenced object but do not load from the database if it is not loaded already.
ObjectReference & operator= (const ObjectReference &other)
Copy another reference's data after clearing the stored reference.
void SetReference (const std::shared_ptr< T > &ref)
Update the data associated to this reference.
bool SetUUID (const libobjgen::UUID &uuid)
Set the UUID of the reference.
Static Public Member Functions
static bool Unload (const libobjgen::UUID &uuid)
Clear the loaded pointer associated to a UUID when an object needs to be cleaned up.
Protected Member Functions
void ClearReference ()
Clear the data associated to this reference, setting it back to null.
const std::shared_ptr< T > GetReference () const
Get the PersistentObject reference casted to the templated type.
bool LoadReference (const std::shared_ptr< Database > &db=nullptr, bool reload=false)
Load the referenced object from the database by its UUID.
void SetReference (const libobjgen::UUID &uuid, const std::shared_ptr< PersistentObject > &ref=nullptr, bool setLoadFailure=false)
Update the data associated to this reference.
Protected Attributes
std::shared_ptr
< ObjectReferenceData > mData
Local copy of the data cached in sData.
Static Protected Attributes
static std::mutex mReferenceLock
Mutex to lock accessing the cache.
static std::unordered_map
< std::string, std::shared_ptr
< ObjectReferenceData > > sData
Static cache of non-null UUIDs to persistent objects.
static std::shared_ptr
< ObjectReferenceData > sNull
Default value of mData instantiated once to avoid newing up excess shared_ptrs.
Detailed Description
template<class T>
class libcomp::ObjectReference< T >
Templated class that handles references to a PersistentObject derived class that can be lazy loaded from the database when needed.
References to a UUID are cached between all instances of this object allowing one database load to populate all references simultaneously.
Definition at line 89 of file ObjectReference.h.
Constructor & Destructor Documentation
template<class T > libcomp::ObjectReference< T >::ObjectReference () inline
Create an empty reference of the templated type.
Definition at line 95 of file ObjectReference.h.
References libcomp::ObjectReference< T >::mData, and libcomp::ObjectReference< T >::sNull.
template<class T > libcomp::ObjectReference< T >::ObjectReference (const libobjgen::UUID & uuid) inline
Create a reference of the templated type with the UUID set.
Parameters
uuid UUID of the referenced object
Definition at line 104 of file ObjectReference.h.
References libcomp::ObjectReference< T >::mData, libcomp::ObjectReference< T >::SetUUID(), and libcomp::ObjectReference< T >::sNull.
template<class T > libcomp::ObjectReference< T >::ObjectReference (std::shared_ptr< T > ref) inline
Create a reference of the templated type with the pointer set.
Parameters
ref Pointer to the referenced object
Definition at line 114 of file ObjectReference.h.
References libcomp::ObjectReference< T >::mData, libcomp::ObjectReference< T >::SetReference(), and libcomp::ObjectReference< T >::sNull.
template<class T > libcomp::ObjectReference< T >::~ObjectReference () inline
Clean up the reference.
Definition at line 123 of file ObjectReference.h.
References libcomp::ObjectReference< T >::ClearReference().
Member Function Documentation
template<class T > void libcomp::ObjectReference< T >::ClearReference () inline protected
Clear the data associated to this reference, setting it back to null.
If the old data associated is no longer being used by another reference, clear it from the cache.
Definition at line 386 of file ObjectReference.h.
References libcomp::ObjectReference< T >::mData, libcomp::ObjectReference< T >::mReferenceLock, libcomp::ObjectReference< T >::sData, and libcomp::ObjectReference< T >::sNull.
Referenced by libcomp::ObjectReference< T >::operator=(), libcomp::ObjectReference< T >::SetReference(), and libcomp::ObjectReference< T >::~ObjectReference().
template<class T > const std::shared_ptr<T> libcomp::ObjectReference< T >::Get () inline
Get the pointer to the referenced object.
If the object is persistent and has not be loaded from the database yet this will not load it however if it is already cached at a server level, it will be cached here as well.
Returns
Pointer to the referenced object
Definition at line 144 of file ObjectReference.h.
References libcomp::ObjectReference< T >::GetReference(), and libcomp::ObjectReference< T >::LoadReference().
Referenced by libcomp::ObjectReference< T >::operator->().
template<class T > const std::shared_ptr<T> libcomp::ObjectReference< T >::Get (const std::shared_ptr< Database > & db, bool reload = false) inline
Get the pointer to the referenced object.
This will cause the reference to load from the database if the UUID is set and has not been loaded from the DB already.
Parameters
db Database to load from
reload Forces a reload from the DB if true
Returns
Pointer to the referenced object
Definition at line 159 of file ObjectReference.h.
References libcomp::ObjectReference< T >::GetReference(), and libcomp::ObjectReference< T >::LoadReference().
template<class T > const std::shared_ptr<T> libcomp::ObjectReference< T >::GetCurrentReference () const inline
Get the pointer to the referenced object but do not load from the database if it is not loaded already.
Returns
Pointer to the referenced object
Definition at line 172 of file ObjectReference.h.
References libcomp::ObjectReference< T >::GetReference().
template<class T > const std::shared_ptr<T> libcomp::ObjectReference< T >::GetReference () const inline protected
Get the PersistentObject reference casted to the templated type.
Returns
Casted pointer to the reference
Definition at line 284 of file ObjectReference.h.
References libcomp::ObjectReference< T >::mData, and libcomp::ObjectReference< T >::mReferenceLock.
Referenced by libcomp::ObjectReference< T >::Get(), libcomp::ObjectReference< T >::GetCurrentReference(), libcomp::ObjectReference< T >::LoadReference(), and libcomp::ObjectReference< T >::operator=().
template<class T > const libobjgen::UUID& libcomp::ObjectReference< T >::GetUUID () const inline
Get the UUID of the reference.
Returns
UUID of the reference
Definition at line 216 of file ObjectReference.h.
References libcomp::ObjectReference< T >::mData.
Referenced by libcomp::ObjectReference< T >::operator=().
template<class T > bool libcomp::ObjectReference< T >::IsNull () const inline
Check if there is no UUID and no reference set.
Returns
true if both are null, false if one is not
Definition at line 132 of file ObjectReference.h.
References libcomp::ObjectReference< T >::mData, and libcomp::ObjectReference< T >::sNull.
Referenced by libcomp::ObjectReference< T >::LoadReference().
template<class T > bool libcomp::ObjectReference< T >::LoadReference (const std::shared_ptr< Database > & db = nullptr, bool reload = false) inline protected
Load the referenced object from the database by its UUID.
This will do nothing if the UUID is not set, the load fails or the templated type is a generic PersistentObject. Calling this function without a DB set will pull from the PersistentObject cache instead.
Parameters
db Database to load from
reload Forces a reload from the DB if true
Returns
true on success, false on failure
Definition at line 300 of file ObjectReference.h.
References libcomp::PersistentObject::GetObjectByUUID(), libcomp::ObjectReference< T >::GetReference(), libcomp::ObjectReference< T >::IsNull(), libcomp::ObjectReference< T >::mData, and libcomp::ObjectReference< T >::SetReference().
Referenced by libcomp::ObjectReference< T >::Get().
template<class T > libcomp::ObjectReference< T >::operator bool () const inline
Checks if the pointer is valid or a nullptr.
Returns
true if the reference is set, false if it is not
Definition at line 207 of file ObjectReference.h.
References libcomp::ObjectReference< T >::mData.
template<class T > std::shared_ptr<T> libcomp::ObjectReference< T >::operator-> () inline
Get the pointer to the referenced object but do not load from the database if it is not loaded already.
Returns
Pointer to the referenced object
Definition at line 182 of file ObjectReference.h.
References libcomp::ObjectReference< T >::Get().
template<class T > ObjectReference& libcomp::ObjectReference< T >::operator= (const ObjectReference< T > & other) inline
Copy another reference's data after clearing the stored reference.
Parameters
other Other reference to copy
Definition at line 263 of file ObjectReference.h.
References libcomp::ObjectReference< T >::ClearReference(), libcomp::ObjectReference< T >::GetReference(), libcomp::ObjectReference< T >::GetUUID(), libcomp::ObjectReference< T >::SetReference(), and libcomp::ObjectReference< T >::SetUUID().
template<class T > void libcomp::ObjectReference< T >::SetReference (const std::shared_ptr< T > & ref) inline
Update the data associated to this reference.
Parameters
ref Pointer to the referenced object
Definition at line 191 of file ObjectReference.h.
References libcomp::PersistentObject::GetUUID().
Referenced by libcomp::ObjectReference< T >::LoadReference(), libcomp::ObjectReference< T >::ObjectReference(), libcomp::ObjectReference< T >::operator=(), and libcomp::ObjectReference< T >::SetUUID().
template<class T > void libcomp::ObjectReference< T >::SetReference (const libobjgen::UUID & uuid, const std::shared_ptr< PersistentObject > & ref = nullptr, bool setLoadFailure = false) inline protected
Update the data associated to this reference.
The values set can be just a UUID, just the reference or both.
Parameters
uuid UUID of the referenced object
ref Pointer to the referenced object
setLoadFailure Marks the reference to not attempt a second load if specified and the pointer passed in is null
Definition at line 338 of file ObjectReference.h.
References libcomp::ObjectReference< T >::ClearReference(), libcomp::ObjectReference< T >::mData, libcomp::ObjectReference< T >::mReferenceLock, libcomp::ObjectReference< T >::sData, and libcomp::ObjectReference< T >::sNull.
template<class T > bool libcomp::ObjectReference< T >::SetUUID (const libobjgen::UUID & uuid) inline
Set the UUID of the reference.
If the reference associated to that UUID is already cached, it will not need to be loaded. If it is not, it will need to be lazy loaded later.
Parameters
uuid UUID of the persistent object
Returns
true on success, false on failure
Definition at line 228 of file ObjectReference.h.
References libcomp::ObjectReference< T >::mData, and libcomp::ObjectReference< T >::SetReference().
Referenced by libcomp::ObjectReference< T >::ObjectReference(), and libcomp::ObjectReference< T >::operator=().
template<class T > static bool libcomp::ObjectReference< T >::Unload (const libobjgen::UUID & uuid) inline static
Clear the loaded pointer associated to a UUID when an object needs to be cleaned up.
This allows circular references in objgen schemas to not cause issues with garbage collection.
Parameters
uuid UUID of the persistent object
Returns
true if it was loaded, false if it was not
Definition at line 244 of file ObjectReference.h.
References libcomp::ObjectReference< T >::mReferenceLock, and libcomp::ObjectReference< T >::sData.
Member Data Documentation
template<class T > std::shared_ptr<ObjectReferenceData> libcomp::ObjectReference< T >::mData protected
Local copy of the data cached in sData.
Definition at line 407 of file ObjectReference.h.
Referenced by libcomp::ObjectReference< T >::ClearReference(), libcomp::ObjectReference< T >::GetReference(), libcomp::ObjectReference< T >::GetUUID(), libcomp::ObjectReference< T >::IsNull(), libcomp::ObjectReference< T >::LoadReference(), libcomp::ObjectReference< T >::ObjectReference(), libcomp::ObjectReference< T >::operator bool(), libcomp::ObjectReference< T >::SetReference(), and libcomp::ObjectReference< T >::SetUUID().
template<class T > std::mutex libcomp::ObjectReference< T >::mReferenceLock static protected
Mutex to lock accessing the cache.
Definition at line 418 of file ObjectReference.h.
Referenced by libcomp::ObjectReference< T >::ClearReference(), libcomp::ObjectReference< T >::GetReference(), libcomp::ObjectReference< T >::SetReference(), and libcomp::ObjectReference< T >::Unload().
template<class T > std::unordered_map< std::string, std::shared_ptr< ObjectReferenceData > > libcomp::ObjectReference< T >::sData static protected
Static cache of non-null UUIDs to persistent objects.
Definition at line 411 of file ObjectReference.h.
Referenced by libcomp::ObjectReference< T >::ClearReference(), libcomp::ObjectReference< T >::SetReference(), and libcomp::ObjectReference< T >::Unload().
template<class T > std::shared_ptr< ObjectReferenceData > libcomp::ObjectReference< T >::sNull static protected
Initial value:
=
    std::shared_ptr<ObjectReferenceData>(new ObjectReferenceData)
Default value of mData instantiated once to avoid newing up excess shared_ptrs.
Definition at line 415 of file ObjectReference.h.
Referenced by libcomp::ObjectReference< T >::ClearReference(), libcomp::ObjectReference< T >::IsNull(), libcomp::ObjectReference< T >::ObjectReference(), and libcomp::ObjectReference< T >::SetReference().
The documentation for this class was generated from the following file:
ObjectReference.h