COMP_hack: libcomp::Child Class Reference
libcomp::Child Class Reference
#include <Child.h>
Public Member Functions
Child (const std::string &program, const std::list< std::string > &arguments, int bootTimeout=0, bool restart=false, bool displayOutput=false)
~Child ()
int GetBootTimeout () const
std::string GetCommandLine () const
pid_t GetPID () const
void Interrupt ()
void Kill ()
bool ShouldRestart () const
bool Start (bool notify=false)
Private Attributes
std::list< std::string > mArguments
int mBootTimeout
bool mDisplayOutput
pid_t mPID
std::string mProgram
bool mRestart
Detailed Description
Definition at line 40 of file Child.h.
Constructor & Destructor Documentation
Child::Child (const std::string & program, const std::list< std::string > & arguments, int bootTimeout = 0, bool restart = false, bool displayOutput = false) explicit
Definition at line 87 of file Child.cpp.
Child::~Child ()
Definition at line 96 of file Child.cpp.
References Kill(), and mPID.
Member Function Documentation
int Child::GetBootTimeout () const
Definition at line 171 of file Child.cpp.
References mBootTimeout.
std::string Child::GetCommandLine () const
Definition at line 148 of file Child.cpp.
References mArguments, and mProgram.
Referenced by Start().
pid_t Child::GetPID () const
Definition at line 161 of file Child.cpp.
References mPID.
void Child::Interrupt ()
Definition at line 114 of file Child.cpp.
References mPID.
void Child::Kill ()
Definition at line 106 of file Child.cpp.
References mPID.
Referenced by Start(), and ~Child().
bool Child::ShouldRestart () const
Definition at line 166 of file Child.cpp.
References mRestart.
bool Child::Start (bool notify = false)
Definition at line 122 of file Child.cpp.
References CreateProcess(), GetCommandLine(), Kill(), mArguments, mDisplayOutput, mPID, and mProgram.
Member Data Documentation
std::list<std::string> libcomp::Child::mArguments private
Definition at line 60 of file Child.h.
Referenced by GetCommandLine(), and Start().
int libcomp::Child::mBootTimeout private
Definition at line 62 of file Child.h.
Referenced by GetBootTimeout().
bool libcomp::Child::mDisplayOutput private
Definition at line 64 of file Child.h.
Referenced by Start().
pid_t libcomp::Child::mPID private
Definition at line 61 of file Child.h.
Referenced by GetPID(), Interrupt(), Kill(), Start(), and ~Child().
std::string libcomp::Child::mProgram private
Definition at line 59 of file Child.h.
Referenced by GetCommandLine(), and Start().
bool libcomp::Child::mRestart private
Definition at line 63 of file Child.h.
Referenced by ShouldRestart().
The documentation for this class was generated from the following files:
Child.h
Child.cpp