COMP_hack: libcomp::Crypto::DiffieHellman Class Reference
libcomp::Crypto::DiffieHellman Class Reference
This class will perform a Diffie-Hellman-Merkle key exchange.
#include <Crypto.h>
Public Member Functions
DiffieHellman (const String &prime)
Construct a new pair using the given prime.
~DiffieHellman ()
Free the key pair.
String GeneratePublic ()
Generate and return the public key.
std::vector< char > GenerateSecret (const String &otherPublic)
Take the other side's public key and generate the shared secret.
String GetPrime () const
Get the prime used for this key.
String GetPublic () const
Get the public key for this side of the exchange.
std::vector< char > GetSecret () const
Gets the shared secret from the key exchange.
bool IsValid () const
Check if the key exchange is valid.
Static Public Member Functions
static std::shared_ptr
< Crypto::DiffieHellman > Generate ()
Generate a Diffie-Hellman key exchange with a new prime.
Static Protected Member Functions
static String BufferToHexString (const uint8_t *pBuffer, size_t bufferSize)
Convert the binary buffer to a big endian hex string.
static std::vector< uint8_t > HexStringToBuffer (const String &s)
Convert the big endian hex string to a binary buffer.
Private Attributes
DiffieHellmanPrivate * d
Private data that is specific to the libary.
Detailed Description
This class will perform a Diffie-Hellman-Merkle key exchange.
Definition at line 149 of file Crypto.h.
Constructor & Destructor Documentation
Crypto::DiffieHellman::DiffieHellman (const String & prime) explicit
Construct a new pair using the given prime.
Parameters
prime Prime number in big endian hex.
Definition at line 1368 of file src/Crypto.cpp.
References libcomp::String::Arg(), libcomp::String::C(), DH_set0_key(), DH_set0_pqg(), libcomp::String::Length(), and libcomp::Crypto::DiffieHellmanPrivate::mValid.
Crypto::DiffieHellman::~DiffieHellman ()
Free the key pair.
Definition at line 1453 of file src/Crypto.cpp.
Member Function Documentation
String Crypto::DiffieHellman::BufferToHexString (const uint8_t * pBuffer, size_t bufferSize) static protected
Convert the binary buffer to a big endian hex string.
Parameters
pBuffer Pointer to the binary buffer.
bufferSize Size in bytes of the binary buffer.
Returns
Hex string representing the binary buffer.
Definition at line 1461 of file src/Crypto.cpp.
std::shared_ptr< Crypto::DiffieHellman > Crypto::DiffieHellman::Generate () static
Generate a Diffie-Hellman key exchange with a new prime.
Note
This only works when using OpenSSL.
Returns
Generated key exchange.
Definition at line 1604 of file src/Crypto.cpp.
References DH_get0_pqg(), and GetDiffieHellmanPrime().
Referenced by libcomp::TcpServer::GenerateDiffieHellman().
String Crypto::DiffieHellman::GeneratePublic ()
Generate and return the public key.
Returns
Public key for this side of the exchange or a blank string on error.
Definition at line 1482 of file src/Crypto.cpp.
References DH_get0_pqg(), and DH_get0_pub_key().
std::vector< char > Crypto::DiffieHellman::GenerateSecret (const String & otherPublic)
Take the other side's public key and generate the shared secret.
Returns
Shared secret from the key exchange or an empty vector on error.
Definition at line 1520 of file src/Crypto.cpp.
References libcomp::String::C(), DH_get0_pqg(), and DH_get0_pub_key().
String Crypto::DiffieHellman::GetPrime () const
Get the prime used for this key.
Definition at line 1477 of file src/Crypto.cpp.
String Crypto::DiffieHellman::GetPublic () const
Get the public key for this side of the exchange.
Returns
Public key for this side of the exchange.
Definition at line 1515 of file src/Crypto.cpp.
std::vector< char > Crypto::DiffieHellman::GetSecret () const
Gets the shared secret from the key exchange.
Returns
Shared secret from the key exchange.
Definition at line 1563 of file src/Crypto.cpp.
std::vector< uint8_t > Crypto::DiffieHellman::HexStringToBuffer (const String & s) static protected
Convert the big endian hex string to a binary buffer.
Parameters
s Hex string to convert to a binary buffer
Returns
A binary buffer for the hex string.
Definition at line 1470 of file src/Crypto.cpp.
bool Crypto::DiffieHellman::IsValid () const
Check if the key exchange is valid.
This should only be needed if the prime is wrong.
Returns
true if the key exchange is valid; false otherwise.
Definition at line 1568 of file src/Crypto.cpp.
Member Data Documentation
DiffieHellmanPrivate* libcomp::Crypto::DiffieHellman::d private
Private data that is specific to the libary.
Definition at line 226 of file Crypto.h.
The documentation for this class was generated from the following files:
Crypto.h
src/Crypto.cpp