COMP_hack: libcomp::SpawnThread Class Reference
libcomp::SpawnThread Class Reference
#include <SpawnThread.h>
Public Member Functions
SpawnThread (DayCare *pJuvy, bool printDetails=true, std::function< void()> onDetain=0)
~SpawnThread ()
void QueueChild (const std::shared_ptr< Child > &child)
void RequestExit ()
void Run ()
void WaitForExit ()
Private Attributes
DayCare * mDayCare
std::function< void()> mOnDetain
bool mPrintDetails
libcomp::MessageQueue
< std::shared_ptr< Child > > mRestartQueue
std::thread * mThread
Detailed Description
Definition at line 43 of file SpawnThread.h.
Constructor & Destructor Documentation
SpawnThread::SpawnThread (DayCare * pJuvy, bool printDetails = true, std::function< void()> onDetain = 0) explicit
Definition at line 36 of file SpawnThread.cpp.
References mThread, and Run().
SpawnThread::~SpawnThread ()
Definition at line 45 of file SpawnThread.cpp.
References mThread, and QueueChild().
Member Function Documentation
void SpawnThread::QueueChild (const std::shared_ptr< Child > & child)
Definition at line 61 of file SpawnThread.cpp.
References mRestartQueue.
Referenced by libcomp::DayCare::LoadProcessDoc(), libcomp::DayCare::NotifyExit(), RequestExit(), and ~SpawnThread().
void SpawnThread::RequestExit ()
Definition at line 150 of file SpawnThread.cpp.
References QueueChild().
Referenced by libcomp::DayCare::CloseDoors().
void SpawnThread::Run ()
Definition at line 66 of file SpawnThread.cpp.
References gSelf, mDayCare, mOnDetain, mPrintDetails, mRestartQueue, and libcomp::DayCare::OrderChildren().
Referenced by SpawnThread().
void SpawnThread::WaitForExit ()
Definition at line 139 of file SpawnThread.cpp.
References mThread.
Referenced by libcomp::DayCare::WaitForExit().
Member Data Documentation
DayCare* libcomp::SpawnThread::mDayCare private
Definition at line 59 of file SpawnThread.h.
Referenced by Run().
std::function<void()> libcomp::SpawnThread::mOnDetain private
Definition at line 63 of file SpawnThread.h.
Referenced by Run().
bool libcomp::SpawnThread::mPrintDetails private
Definition at line 57 of file SpawnThread.h.
Referenced by Run().
libcomp::MessageQueue<std::shared_ptr<Child> > libcomp::SpawnThread::mRestartQueue private
Definition at line 62 of file SpawnThread.h.
Referenced by QueueChild(), and Run().
std::thread* libcomp::SpawnThread::mThread private
Definition at line 60 of file SpawnThread.h.
Referenced by SpawnThread(), WaitForExit(), and ~SpawnThread().
The documentation for this class was generated from the following files:
SpawnThread.h
SpawnThread.cpp