COMP_hack: libcomp::MemoryManager Class Reference
libcomp::MemoryManager Class Reference
This class will track memory allocations for later analysis.
#include <MemoryManager.h>
Public Member Functions
void Allocate (void *pAddress, size_t size)
Called to track an allocated a block of memory.
void Deallocate (void *pAddress)
Called to remove tracking on a memory block/.
void GetStats (uint64_t &allocationCount, size_t &heapSize)
Gets basic statistics on the memory usage.
void Setup ()
Called to setup the manager.
void Snapshot ()
Called to dump the statistics to a file.
Private Member Functions
void CollectAllocation (std::unordered_map< uint32_t, std::list< MemoryAllocation * >> &collection, rbtree_node node)
Add an allocation to the collection during the snapshot progress.
Private Attributes
uint64_t mAllocationCount
How many blocks of memory are allocated.
rbtree mAllocations
Red-black tree holding the memory allocations.
size_t mHeapSize
Size of the heap in bytes (size of all allocations).
std::mutex * mLock
Mutex to protect access to the data structure.
bool mSnapshotInProgress
Indicates that a snapshot is in progress and we should not track new allocations.
Detailed Description
This class will track memory allocations for later analysis.
Definition at line 92 of file MemoryManager.h.
Member Function Documentation
void MemoryManager::Allocate (void * pAddress, size_t size)
Called to track an allocated a block of memory.
Parameters
pAddress Address of the memory block.
size Size of the memory block.
Definition at line 445 of file MemoryManager.cpp.
References compare_tree(), libcomp::MemoryAllocation::CreateBacktrace(), mAllocationCount, mAllocations, mHeapSize, mLock, mSnapshotInProgress, libcomp::MemoryAllocation::pAddress, rbtree_insert(), libcomp::MemoryAllocation::size, and libcomp::MemoryAllocation::stamp.
Referenced by operator new(), and operator new[]().
void MemoryManager::CollectAllocation (std::unordered_map< uint32_t, std::list< MemoryAllocation * >> & collection, rbtree_node node) private
Add an allocation to the collection during the snapshot progress.
This will follow the tree until all allocations are collected. A checksum for the allocation backtrace is generated and used to group allocations made in the same code location.
Parameters
collection Collection to add the allocations to.
node Node to add to the collection (and child notes).
Definition at line 503 of file MemoryManager.cpp.
References libcomp::MemoryAllocation::allocBacktrace, libcomp::MemoryAllocation::allocBacktraceChecksum, and libcomp::MemoryAllocation::allocBacktraceCount.
Referenced by Snapshot().
void MemoryManager::Deallocate (void * pAddress)
Called to remove tracking on a memory block/.
Parameters
pAddress Address of the memory block.
Definition at line 470 of file MemoryManager.cpp.
References compare_tree(), libcomp::MemoryAllocation::FreeBacktrace(), mAllocationCount, mAllocations, mHeapSize, mLock, mSnapshotInProgress, rbtree_take(), and libcomp::MemoryAllocation::size.
Referenced by operator delete().
void MemoryManager::GetStats (uint64_t & allocationCount, size_t & heapSize)
Gets basic statistics on the memory usage.
Parameters
allocationCount How many blocks of memory are allocated.
heapSize Size of the heap in bytes (size of all allocations).
Definition at line 495 of file MemoryManager.cpp.
References mAllocationCount, mHeapSize, and mLock.
Referenced by libcomp::GetMemoryStats().
void MemoryManager::Setup ()
Called to setup the manager.
Definition at line 376 of file MemoryManager.cpp.
References mAllocationCount, mAllocations, mHeapSize, mLock, mSnapshotInProgress, and rbtree_create().
Referenced by libcomp::InitMemoryManager().
void MemoryManager::Snapshot ()
Called to dump the statistics to a file.
Definition at line 387 of file MemoryManager.cpp.
References CollectAllocation(), mAllocationCount, mAllocations, MEMORY_SNAPSHOT_FILE, mHeapSize, mLock, and mSnapshotInProgress.
Referenced by libcomp::TriggerMemorySnapshot().
Member Data Documentation
uint64_t libcomp::MemoryManager::mAllocationCount private
How many blocks of memory are allocated.
Definition at line 138 of file MemoryManager.h.
Referenced by Allocate(), Deallocate(), GetStats(), Setup(), and Snapshot().
rbtree libcomp::MemoryManager::mAllocations private
Red-black tree holding the memory allocations.
Definition at line 144 of file MemoryManager.h.
Referenced by Allocate(), Deallocate(), Setup(), and Snapshot().
size_t libcomp::MemoryManager::mHeapSize private
Size of the heap in bytes (size of all allocations).
Definition at line 141 of file MemoryManager.h.
Referenced by Allocate(), Deallocate(), GetStats(), Setup(), and Snapshot().
std::mutex* libcomp::MemoryManager::mLock private
Mutex to protect access to the data structure.
Definition at line 151 of file MemoryManager.h.
Referenced by Allocate(), Deallocate(), GetStats(), Setup(), and Snapshot().
bool libcomp::MemoryManager::mSnapshotInProgress private
Indicates that a snapshot is in progress and we should not track new allocations.
Definition at line 148 of file MemoryManager.h.
Referenced by Allocate(), Deallocate(), Setup(), and Snapshot().
The documentation for this class was generated from the following files:
MemoryManager.h
MemoryManager.cpp