COMP_hack: libcomp::TcpServer Class Reference
libcomp::TcpServer Class Reference
Listen for new TCP/IP connections.
#include <TcpServer.h>
Public Member Functions
TcpServer (const String &listenAddress, uint16_t port)
Create a TCP server to listen on a specific address and port.
virtual ~TcpServer ()
Cleanup the server and stop listening for new connections.
void RemoveConnection (std::shared_ptr< TcpConnection > &connection)
Remove a connection from the list of client connections.
virtual void ServerReady ()
Called when the server has started.
virtual int Start (bool delayReady=false)
Start a thread that listens for incoming network connections.
Static Public Member Functions
static std::shared_ptr
< Crypto::DiffieHellman > GenerateDiffieHellman ()
Generate a Diffie-Hellman key pair.
static std::shared_ptr
< Crypto::DiffieHellman > LoadDiffieHellman (const String &prime)
Create a Diffie-Helman key pair given the hex encoded prime.
Protected Member Functions
void AcceptHandler (asio::error_code errorCode, asio::ip::tcp::socket &socket)
Called to handle a new connection to the server.
virtual std::shared_ptr
< TcpConnection > CreateConnection (asio::ip::tcp::socket &socket)
Create a connection to a newly active socket.
std::shared_ptr
< Crypto::DiffieHellman > GetDiffieHellman () const
Get the Diffie-Hellman key pair used by this server.
virtual int Run ()
Main loop for the server.
void SetDiffieHellman (const std::shared_ptr< Crypto::DiffieHellman > &diffieHellman)
Set the Diffie-Hellman key pair used by this server.
Protected Attributes
std::list< std::shared_ptr
< TcpConnection > > mConnections
List of connections managed by this server.
std::mutex mConnectionsLock
Lock for the connection list.
asio::io_service mService
ASIO service used to handle network operations.
Private Attributes
asio::ip::tcp::acceptor mAcceptor
Asynchronous acceptor for new connections.
std::shared_ptr
< Crypto::DiffieHellman > mDiffieHellman
Diffie-Hellman key pair used to encrypt connections.
String mListenAddress
Address the server is listening on.
uint16_t mPort
Port the address is listening on.
std::thread mServiceThread
Thread that runs the ASIO service.
Detailed Description
Listen for new TCP/IP connections.
This class will listen for new TCP/IP connections on the given address and port. If the address specified is blank or "any" it will listen for connections on all network devices. The CreateConnection function should be overridden if a subclass of TcpConnection is required or additional setup should be performed.
Definition at line 56 of file TcpServer.h.
Constructor & Destructor Documentation
TcpServer::TcpServer (const String & listenAddress, uint16_t port)
Create a TCP server to listen on a specific address and port.
Parameters
listenAddress Listen on the specified IP address. If blank or "any" this will listen on all network adapters.
port Port to listen for incoming connections.
Definition at line 44 of file TcpServer.cpp.
TcpServer::~TcpServer () virtual
Cleanup the server and stop listening for new connections.
Definition at line 54 of file TcpServer.cpp.
Member Function Documentation
void TcpServer::AcceptHandler (asio::error_code errorCode, asio::ip::tcp::socket & socket) protected
Called to handle a new connection to the server.
This will call CreateConnection and then add the connection to the list.
Parameters
errorCode Error code of the last accept operation.
socket Socket that was bound to the new connection.
Definition at line 171 of file TcpServer.cpp.
References libcomp::String::Arg(), CreateConnection(), mAcceptor, mConnections, mConnectionsLock, and mDiffieHellman.
Referenced by Start().
std::shared_ptr< TcpConnection > TcpServer::CreateConnection (asio::ip::tcp::socket & socket) protected virtual
Create a connection to a newly active socket.
Parameters
socket A new socket connection.
Returns
Pointer to the newly created connection
Definition at line 164 of file TcpServer.cpp.
References LoadDiffieHellman(), and mDiffieHellman.
Referenced by AcceptHandler().
std::shared_ptr< Crypto::DiffieHellman > TcpServer::GenerateDiffieHellman () static
Generate a Diffie-Hellman key pair.
Returns
Generated key pair or nullptr on failure.
Definition at line 237 of file TcpServer.cpp.
References libcomp::Crypto::DiffieHellman::Generate().
Referenced by Start().
std::shared_ptr< Crypto::DiffieHellman > TcpServer::GetDiffieHellman () const protected
Get the Diffie-Hellman key pair used by this server.
Returns
Key pair or nullptr if one is not set.
Definition at line 226 of file TcpServer.cpp.
References mDiffieHellman.
Referenced by libcomp::BaseServer::Initialize().
std::shared_ptr< Crypto::DiffieHellman > TcpServer::LoadDiffieHellman (const String & prime) static
Create a Diffie-Helman key pair given the hex encoded prime.
Parameters
prime Hex encoded string representing the prime.
Returns
Generated key pair or nullptr on failure.
Definition at line 242 of file TcpServer.cpp.
Referenced by CreateConnection(), libcomp::BaseServer::Initialize(), and libcomp::EncryptedConnection::ParseClientEncryptionStart().
void TcpServer::RemoveConnection (std::shared_ptr< TcpConnection > & connection)
Remove a connection from the list of client connections.
Parameters
connection Connection to remove.
Definition at line 131 of file TcpServer.cpp.
References mConnections, and mConnectionsLock.
int TcpServer::Run () protected virtual
Main loop for the server.
Returns
Code indicating the exit status.
Reimplemented in libcomp::BaseServer.
Definition at line 143 of file TcpServer.cpp.
Referenced by Start().
void TcpServer::ServerReady () virtual
Called when the server has started.
Reimplemented in libcomp::BaseServer.
Definition at line 148 of file TcpServer.cpp.
Referenced by libcomp::BaseServer::ServerReady(), and Start().
void TcpServer::SetDiffieHellman (const std::shared_ptr< Crypto::DiffieHellman > & diffieHellman) protected
Set the Diffie-Hellman key pair used by this server.
Parameters
diffieHellman Pointer to the key pair to use.
Definition at line 231 of file TcpServer.cpp.
References mDiffieHellman.
Referenced by libcomp::BaseServer::Initialize().
int TcpServer::Start (bool delayReady = false) virtual
Start a thread that listens for incoming network connections.
This call will block until the server is stopped. This will call Run for the main loop. In the BaseServer implementation this will run a main worker thread.
See Also
BaseServer
Worker
Parameters
delayReady Optional parameter to delay ready notification to be called manually at a later point. Defaults to false.
Returns
Code indicating the exit status.
Definition at line 58 of file TcpServer.cpp.
References AcceptHandler(), libcomp::String::Arg(), GenerateDiffieHellman(), libcomp::TcpConnection::GetDiffieHellmanPrime(), libcomp::String::IsEmpty(), mAcceptor, mDiffieHellman, mListenAddress, mPort, mService, mServiceThread, Run(), ServerReady(), libcomp::String::ToLower(), and libcomp::String::ToUtf8().
Member Data Documentation
asio::ip::tcp::acceptor libcomp::TcpServer::mAcceptor private
Asynchronous acceptor for new connections.
Definition at line 158 of file TcpServer.h.
Referenced by AcceptHandler(), and Start().
std::list<std::shared_ptr<TcpConnection> > libcomp::TcpServer::mConnections protected
List of connections managed by this server.
Definition at line 151 of file TcpServer.h.
Referenced by AcceptHandler(), and RemoveConnection().
std::mutex libcomp::TcpServer::mConnectionsLock protected
Lock for the connection list.
Definition at line 148 of file TcpServer.h.
Referenced by AcceptHandler(), and RemoveConnection().
std::shared_ptr<Crypto::DiffieHellman> libcomp::TcpServer::mDiffieHellman private
Diffie-Hellman key pair used to encrypt connections.
Definition at line 164 of file TcpServer.h.
Referenced by AcceptHandler(), CreateConnection(), GetDiffieHellman(), SetDiffieHellman(), and Start().
String libcomp::TcpServer::mListenAddress private
Address the server is listening on.
Definition at line 167 of file TcpServer.h.
Referenced by Start().
uint16_t libcomp::TcpServer::mPort private
Port the address is listening on.
Definition at line 170 of file TcpServer.h.
Referenced by Start().
asio::io_service libcomp::TcpServer::mService protected
ASIO service used to handle network operations.
Definition at line 154 of file TcpServer.h.
Referenced by libcomp::BaseServer::Run(), and Start().
std::thread libcomp::TcpServer::mServiceThread private
Thread that runs the ASIO service.
Definition at line 161 of file TcpServer.h.
Referenced by Start().
The documentation for this class was generated from the following files:
TcpServer.h
TcpServer.cpp