COMP_hack: libcomp::Message::Packet Class Reference
libcomp::Message::Packet Class Reference
Message containing a packet received by an internal server or game client connection.
#include <MessagePacket.h>
Public Member Functions
Packet (const std::shared_ptr< TcpConnection > &connection, uint16_t commandCode, ReadOnlyPacket &packet)
Create the message.
virtual ~Packet ()
Cleanup the message.
virtual libcomp::String Dump () const override
Dump the message for logging.
uint16_t GetCommandCode () const
Get the received packet's command code.
std::shared_ptr< TcpConnection > GetConnection () const
Get the connection the packet came from.
const ReadOnlyPacket & GetPacket () const
Get the received packet.
virtual MessageType GetType () const
Get the message's type.
Private Attributes
uint16_t mCommandCode
The received packet's command code.
std::shared_ptr< TcpConnection > mConnection
The connection the packet came from.
ReadOnlyPacket mPacket
The received packet.
Detailed Description
Message containing a packet received by an internal server or game client connection.
See Also
ReadOnlyPacket
Definition at line 50 of file MessagePacket.h.
Constructor & Destructor Documentation
Message::Packet::Packet (const std::shared_ptr< TcpConnection > & connection, uint16_t commandCode, ReadOnlyPacket & packet)
Create the message.
Parameters
connection The connection the packet came from
commandCode Integer value representing the command code to use when deciding which ManagerPacket to use to handle the message
packet The packet received
Definition at line 34 of file MessagePacket.cpp.
Message::Packet::~Packet () virtual
Cleanup the message.
Definition at line 40 of file MessagePacket.cpp.
Member Function Documentation
libcomp::String Message::Packet::Dump () const override virtual
Dump the message for logging.
Returns
String representation of the message.
Implements libcomp::Message::Message.
Definition at line 64 of file MessagePacket.cpp.
References libcomp::String::Arg().
uint16_t Message::Packet::GetCommandCode () const
Get the received packet's command code.
Returns
The received packet's command code
Definition at line 49 of file MessagePacket.cpp.
Referenced by libcomp::ManagerPacket::ProcessMessage().
std::shared_ptr< TcpConnection > Message::Packet::GetConnection () const
Get the connection the packet came from.
Returns
The connection the packet came from
Definition at line 54 of file MessagePacket.cpp.
Referenced by libcomp::ManagerPacket::ProcessMessage().
const ReadOnlyPacket & Message::Packet::GetPacket () const
Get the received packet.
Returns
The received packet
Definition at line 44 of file MessagePacket.cpp.
Referenced by libcomp::ManagerPacket::ProcessMessage().
Message::MessageType Message::Packet::GetType () const virtual
Get the message's type.
Returns
The message's type.
Implements libcomp::Message::Message.
Definition at line 59 of file MessagePacket.cpp.
References libcomp::Message::MESSAGE_TYPE_PACKET.
Member Data Documentation
uint16_t libcomp::Message::Packet::mCommandCode private
The received packet's command code.
Definition at line 96 of file MessagePacket.h.
std::shared_ptr<TcpConnection> libcomp::Message::Packet::mConnection private
The connection the packet came from.
Definition at line 99 of file MessagePacket.h.
ReadOnlyPacket libcomp::Message::Packet::mPacket private
The received packet.
Definition at line 93 of file MessagePacket.h.
The documentation for this class was generated from the following files:
MessagePacket.h
MessagePacket.cpp