COMP_hack: libcomp::BinaryDataSet Class Reference
libcomp::BinaryDataSet Class Reference
#include <BinaryDataSet.h>
Public Member Functions
BinaryDataSet (std::function< std::shared_ptr< libcomp::Object >()> allocator, std::function< uint32_t(const std::shared_ptr< libcomp::Object > &)> mapper)
virtual ~BinaryDataSet ()
std::shared_ptr< libcomp::Object > GetObjectByID (uint32_t id) const
std::list< std::shared_ptr
< libcomp::Object > > GetObjects () const
std::string GetTabular () const
std::string GetXml () const
bool Load (std::istream &file, bool loadMore=false)
bool LoadXml (tinyxml2::XMLDocument &doc, bool loadMore=false)
bool Save (std::ostream &file) const
Protected Attributes
std::function< std::shared_ptr
< libcomp::Object >)> mObjectAllocator
std::map< uint32_t,
std::shared_ptr
< libcomp::Object > > mObjectMap
std::function< uint32_t(const
std::shared_ptr
< libcomp::Object > &)> mObjectMapper
std::list< std::shared_ptr
< libcomp::Object > > mObjects
Private Member Functions
std::list< std::string > ReadNodes (tinyxml2::XMLElement *node, int16_t dataMode) const
Detailed Description
Definition at line 45 of file BinaryDataSet.h.
Constructor & Destructor Documentation
BinaryDataSet::BinaryDataSet (std::function< std::shared_ptr< libcomp::Object >()> allocator, std::function< uint32_t(const std::shared_ptr< libcomp::Object > &)> mapper)
Definition at line 38 of file BinaryDataSet.cpp.
BinaryDataSet::~BinaryDataSet () virtual
Definition at line 45 of file BinaryDataSet.cpp.
Member Function Documentation
std::shared_ptr< libcomp::Object > BinaryDataSet::GetObjectByID (uint32_t id) const
Definition at line 202 of file BinaryDataSet.cpp.
References mObjectMap.
std::list< std::shared_ptr< libcomp::Object > > BinaryDataSet::GetObjects () const
Definition at line 197 of file BinaryDataSet.cpp.
References mObjects.
std::string BinaryDataSet::GetTabular () const
Definition at line 150 of file BinaryDataSet.cpp.
References mObjects, and ReadNodes().
std::string BinaryDataSet::GetXml () const
Definition at line 129 of file BinaryDataSet.cpp.
References mObjects.
bool BinaryDataSet::Load (std::istream & file, bool loadMore = false)
Definition at line 49 of file BinaryDataSet.cpp.
References libcomp::Object::LoadBinaryData(), mObjectAllocator, mObjectMap, mObjectMapper, and mObjects.
bool BinaryDataSet::LoadXml (tinyxml2::XMLDocument & doc, bool loadMore = false)
Definition at line 80 of file BinaryDataSet.cpp.
References mObjectAllocator, mObjectMap, mObjectMapper, and mObjects.
std::list< std::string > BinaryDataSet::ReadNodes (tinyxml2::XMLElement * node, int16_t dataMode) const private
Definition at line 215 of file BinaryDataSet.cpp.
Referenced by GetTabular().
bool BinaryDataSet::Save (std::ostream & file) const
Definition at line 75 of file BinaryDataSet.cpp.
References mObjects, and libcomp::Object::SaveBinaryData().
Member Data Documentation
std::function<std::shared_ptr<libcomp::Object>)> libcomp::BinaryDataSet::mObjectAllocator protected
Definition at line 66 of file BinaryDataSet.h.
Referenced by Load(), and LoadXml().
std::map<uint32_t, std::shared_ptr<libcomp::Object> > libcomp::BinaryDataSet::mObjectMap protected
Definition at line 76 of file BinaryDataSet.h.
Referenced by GetObjectByID(), Load(), and LoadXml().
std::function<uint32_t(const std::shared_ptr< libcomp::Object>&)> libcomp::BinaryDataSet::mObjectMapper protected
Definition at line 68 of file BinaryDataSet.h.
Referenced by Load(), and LoadXml().
std::list<std::shared_ptr<libcomp::Object> > libcomp::BinaryDataSet::mObjects protected
Definition at line 75 of file BinaryDataSet.h.
Referenced by GetObjects(), GetTabular(), GetXml(), Load(), LoadXml(), and Save().
The documentation for this class was generated from the following files:
BinaryDataSet.h
BinaryDataSet.cpp