COMP_hack: libcomp::DatabaseQuery Class Reference
libcomp::DatabaseQuery Class Reference
Database query wrapper class that contains a database specific query implementation so the pointer does not need to be worked with directly.
#include <DatabaseQuery.h>
Public Member Functions
DatabaseQuery (DatabaseQueryImpl *pImpl)
Create a new database query.
DatabaseQuery (DatabaseQueryImpl *pImpl, const String &query)
Create and prepare a new database query.
DatabaseQuery (const DatabaseQuery &other)=delete
Disable the default copy constructor.
DatabaseQuery (DatabaseQuery &&other)
Copy another database query.
~DatabaseQuery ()
Clean up the query and delete the implementation pointer.
int64_t AffectedRowCount () const
Get the count of affected rows from the last query execution.
bool Bind (size_t index, const String &value)
Bind an implementation's string column value by its index.
bool Bind (const String &name, const String &value)
Bind an implementation's string column value by its name.
bool Bind (size_t index, const std::vector< char > &value)
Bind an implementation's blob column value by its index.
bool Bind (const String &name, const std::vector< char > &value)
Bind an implementation's blob column value by its name.
bool Bind (size_t index, const libobjgen::UUID &value)
Bind an implementation's UUID column value by its index.
bool Bind (const String &name, const libobjgen::UUID &value)
Bind an implementation's UUID column value by its name.
bool Bind (size_t index, int32_t value)
Bind an implementation's 32-bit integer column value by its index.
bool Bind (const String &name, int32_t value)
Bind an implementation's 32-bit integer column value by its name.
bool Bind (size_t index, int64_t value)
Bind an implementation's 64-bit integer column value by its index.
bool Bind (const String &name, int64_t value)
Bind an implementation's 64-bit integer column value by its name.
bool Bind (size_t index, float value)
Bind an implementation's float column value by its index.
bool Bind (const String &name, float value)
Bind an implementation's float column value by its name.
bool Bind (size_t index, double value)
Bind an implementation's double column value by its index.
bool Bind (const String &name, double value)
Bind an implementation's double column value by its name.
bool Bind (size_t index, bool value)
Bind an implementation's boolean column value by its index.
bool Bind (const String &name, bool value)
Bind an implementation's boolean column value by its name.
bool Bind (size_t index, const std::unordered_map< std::string, std::vector< char >> &values)
Bind an implementation's map column value by its index.
bool Bind (const String &name, const std::unordered_map< std::string, std::vector< char >> &values)
Bind an implementation's map column value by its name.
bool Execute ()
Execute a previously prepared query implementation.
virtual bool GetRows (std::list< std::unordered_map< std::string, std::vector< char >>> &rows)
Get all of the query imementation's result's rows as bytes mapped by column name.
bool GetValue (size_t index, String &value)
Get an implementation's string column value by its index.
bool GetValue (const String &name, String &value)
Get an implementation's string column value by its name.
bool GetValue (size_t index, std::vector< char > &value)
Get an implementation's blob column value by its index.
bool GetValue (const String &name, std::vector< char > &value)
Get an implementation's blob column value by its name.
bool GetValue (size_t index, libobjgen::UUID &value)
Get an implementation's UUID column value by its index.
bool GetValue (const String &name, libobjgen::UUID &value)
Get an implementation's UUID column value by its name.
bool GetValue (size_t index, int32_t &value)
Get an implementation's 32-bit integer column value by its index.
bool GetValue (const String &name, int32_t &value)
Get an implementation's 32-bit integer column value by its name.
bool GetValue (size_t index, int64_t &value)
Get an implementation's 64-bit integer column value by its index.
bool GetValue (const String &name, int64_t &value)
Get an implementation's 64-bit integer column value by its name.
bool GetValue (size_t index, float &value)
Get an implementation's float column value by its index.
bool GetValue (const String &name, float &value)
Get an implementation's float column value by its name.
bool GetValue (size_t index, double &value)
Get an implementation's double column value by its index.
bool GetValue (const String &name, double &value)
Get an implementation's double column value by its name.
bool GetValue (size_t index, bool &value)
Get an implementation's boolean column value by its index.
bool GetValue (const String &name, bool &value)
Get an implementation's boolean column value by its name.
bool IsValid () const
Check current query implementation's state validity.
bool Next ()
Increment the query implementation's results to look at the next result set row.
DatabaseQuery & operator= (DatabaseQuery &&other)
Copy operator implementation.
bool Prepare (const String &query)
Prepare a database query implementation for execution based upon query text.
Protected Attributes
DatabaseQueryImpl * mImpl
Database specific implementation.
Detailed Description
Database query wrapper class that contains a database specific query implementation so the pointer does not need to be worked with directly.
Nearly all functions have a corresponding DatabaseQueryImpl function as well that does most of the actual work.
Definition at line 393 of file DatabaseQuery.h.
Constructor & Destructor Documentation
DatabaseQuery::DatabaseQuery (DatabaseQueryImpl * pImpl)
Create a new database query.
Parameters
pImpl Pointer to a database specific query implementation
Definition at line 72 of file DatabaseQuery.cpp.
DatabaseQuery::DatabaseQuery (DatabaseQueryImpl * pImpl, const String & query)
Create and prepare a new database query.
Parameters
pImpl Pointer to a database specific query implementation
query Query text to prepare
Definition at line 76 of file DatabaseQuery.cpp.
References Prepare().
libcomp::DatabaseQuery::DatabaseQuery (const DatabaseQuery & other) delete
Disable the default copy constructor.
Parameters
other The other query to copy
DatabaseQuery::DatabaseQuery (DatabaseQuery && other)
Copy another database query.
Parameters
other The other query to copy
Definition at line 82 of file DatabaseQuery.cpp.
DatabaseQuery::~DatabaseQuery ()
Clean up the query and delete the implementation pointer.
Definition at line 87 of file DatabaseQuery.cpp.
References mImpl.
Member Function Documentation
int64_t DatabaseQuery::AffectedRowCount () const
Get the count of affected rows from the last query execution.
Returns
Number of affected rows
Definition at line 564 of file DatabaseQuery.cpp.
References libcomp::DatabaseQueryImpl::AffectedRowCount(), and mImpl.
Referenced by libcomp::DatabaseSQLite3::ProcessExplicitUpdate(), and libcomp::DatabaseMariaDB::ProcessExplicitUpdate().
bool DatabaseQuery::Bind (size_t index, const String & value)
Bind an implementation's string column value by its index.
Parameters
index The column's index
value The value to bind
Returns
true on success, false on failure
Definition at line 129 of file DatabaseQuery.cpp.
References libcomp::DatabaseQueryImpl::Bind(), and mImpl.
Referenced by libcomp::DatabaseBindText::Bind(), libcomp::DatabaseBindBlob::Bind(), libcomp::DatabaseBindUUID::Bind(), libcomp::DatabaseBindInt::Bind(), libcomp::DatabaseBindBigInt::Bind(), libcomp::DatabaseBindFloat::Bind(), libcomp::DatabaseBindDouble::Bind(), libcomp::DatabaseBindBool::Bind(), libcomp::DatabaseSQLite3::InsertSingleObject(), libcomp::DatabaseMariaDB::InsertSingleObject(), libcomp::DatabaseSQLite3::ProcessExplicitUpdate(), libcomp::DatabaseMariaDB::ProcessExplicitUpdate(), libcomp::DatabaseSQLite3::UpdateSingleObject(), and libcomp::DatabaseMariaDB::UpdateSingleObject().
bool DatabaseQuery::Bind (const String & name, const String & value)
Bind an implementation's string column value by its name.
Parameters
name The column's name
value The value to bind
Returns
true on success, false on failure
Definition at line 141 of file DatabaseQuery.cpp.
References libcomp::DatabaseQueryImpl::Bind(), and mImpl.
bool DatabaseQuery::Bind (size_t index, const std::vector< char > & value)
Bind an implementation's blob column value by its index.
Parameters
index The column's index
value The value to bind
Returns
true on success, false on failure
Definition at line 153 of file DatabaseQuery.cpp.
References libcomp::DatabaseQueryImpl::Bind(), and mImpl.
bool DatabaseQuery::Bind (const String & name, const std::vector< char > & value)
Bind an implementation's blob column value by its name.
Parameters
name The column's name
value The value to bind
Returns
true on success, false on failure
Definition at line 165 of file DatabaseQuery.cpp.
References libcomp::DatabaseQueryImpl::Bind(), and mImpl.
bool DatabaseQuery::Bind (size_t index, const libobjgen::UUID & value)
Bind an implementation's UUID column value by its index.
Parameters
index The column's index
value The value to bind
Returns
true on success, false on failure
Definition at line 177 of file DatabaseQuery.cpp.
References libcomp::DatabaseQueryImpl::Bind(), and mImpl.
bool DatabaseQuery::Bind (const String & name, const libobjgen::UUID & value)
Bind an implementation's UUID column value by its name.
Parameters
name The column's name
value The value to bind
Returns
true on success, false on failure
Definition at line 189 of file DatabaseQuery.cpp.
References libcomp::DatabaseQueryImpl::Bind(), and mImpl.
bool DatabaseQuery::Bind (size_t index, int32_t value)
Bind an implementation's 32-bit integer column value by its index.
Parameters
index The column's index
value The value to bind
Returns
true on success, false on failure
Definition at line 201 of file DatabaseQuery.cpp.
References libcomp::DatabaseQueryImpl::Bind(), and mImpl.
bool DatabaseQuery::Bind (const String & name, int32_t value)
Bind an implementation's 32-bit integer column value by its name.
Parameters
name The column's name
value The value to bind
Returns
true on success, false on failure
Definition at line 213 of file DatabaseQuery.cpp.
References libcomp::DatabaseQueryImpl::Bind(), and mImpl.
bool DatabaseQuery::Bind (size_t index, int64_t value)
Bind an implementation's 64-bit integer column value by its index.
Parameters
index The column's index
value The value to bind
Returns
true on success, false on failure
Definition at line 225 of file DatabaseQuery.cpp.
References libcomp::DatabaseQueryImpl::Bind(), and mImpl.
bool DatabaseQuery::Bind (const String & name, int64_t value)
Bind an implementation's 64-bit integer column value by its name.
Parameters
name The column's name
value The value to bind
Returns
true on success, false on failure
Definition at line 237 of file DatabaseQuery.cpp.
References libcomp::DatabaseQueryImpl::Bind(), and mImpl.
bool DatabaseQuery::Bind (size_t index, float value)
Bind an implementation's float column value by its index.
Parameters
index The column's index
value The value to bind
Returns
true on success, false on failure
Definition at line 249 of file DatabaseQuery.cpp.
References libcomp::DatabaseQueryImpl::Bind(), and mImpl.
bool DatabaseQuery::Bind (const String & name, float value)
Bind an implementation's float column value by its name.
Parameters
name The column's name
value The value to bind
Returns
true on success, false on failure
Definition at line 261 of file DatabaseQuery.cpp.
References libcomp::DatabaseQueryImpl::Bind(), and mImpl.
bool DatabaseQuery::Bind (size_t index, double value)
Bind an implementation's double column value by its index.
Parameters
index The column's index
value The value to bind
Returns
true on success, false on failure
Definition at line 273 of file DatabaseQuery.cpp.
References libcomp::DatabaseQueryImpl::Bind(), and mImpl.
bool DatabaseQuery::Bind (const String & name, double value)
Bind an implementation's double column value by its name.
Parameters
name The column's name
value The value to bind
Returns
true on success, false on failure
Definition at line 285 of file DatabaseQuery.cpp.
References libcomp::DatabaseQueryImpl::Bind(), and mImpl.
bool DatabaseQuery::Bind (size_t index, bool value)
Bind an implementation's boolean column value by its index.
Parameters
index The column's index
value The value to bind
Returns
true on success, false on failure
Definition at line 297 of file DatabaseQuery.cpp.
References libcomp::DatabaseQueryImpl::Bind(), and mImpl.
bool DatabaseQuery::Bind (const String & name, bool value)
Bind an implementation's boolean column value by its name.
Parameters
name The column's name
value The value to bind
Returns
true on success, false on failure
Definition at line 309 of file DatabaseQuery.cpp.
References libcomp::DatabaseQueryImpl::Bind(), and mImpl.
bool DatabaseQuery::Bind (size_t index, const std::unordered_map< std::string, std::vector< char >> & values)
Bind an implementation's map column value by its index.
Parameters
index The column's index
values The value to bind
Returns
true on success, false on failure
Definition at line 333 of file DatabaseQuery.cpp.
References libcomp::DatabaseQueryImpl::Bind(), and mImpl.
bool DatabaseQuery::Bind (const String & name, const std::unordered_map< std::string, std::vector< char >> & values)
Bind an implementation's map column value by its name.
Parameters
name The column's name
values The value to bind
Returns
true on success, false on failure
Definition at line 346 of file DatabaseQuery.cpp.
References libcomp::DatabaseQueryImpl::Bind(), and mImpl.
bool DatabaseQuery::Execute ()
Execute a previously prepared query implementation.
See Also
DatabaseQuery::Prepare
Returns
true on success, false on failure
Definition at line 105 of file DatabaseQuery.cpp.
References libcomp::DatabaseQueryImpl::Execute(), and mImpl.
Referenced by libcomp::Database::Execute(), libcomp::DatabaseMariaDB::Exists(), libcomp::DatabaseSQLite3::InsertSingleObject(), libcomp::DatabaseMariaDB::InsertSingleObject(), libcomp::DatabaseSQLite3::LoadObjects(), libcomp::DatabaseMariaDB::LoadObjects(), libcomp::DatabaseSQLite3::ProcessExplicitUpdate(), libcomp::DatabaseMariaDB::ProcessExplicitUpdate(), libcomp::Database::TableHasRows(), libcomp::DatabaseSQLite3::UpdateSingleObject(), libcomp::DatabaseMariaDB::UpdateSingleObject(), libcomp::DatabaseSQLite3::VerifyAndSetupSchema(), and libcomp::DatabaseMariaDB::VerifyAndSetupSchema().
bool DatabaseQuery::GetRows (std::list< std::unordered_map< std::string, std::vector< char >>> & rows) virtual
Get all of the query imementation's result's rows as bytes mapped by column name.
Parameters
rows Output map to insert a row with each column's bytes mapped by column name
Returns
true on success, false on failure
Definition at line 551 of file DatabaseQuery.cpp.
References libcomp::DatabaseQueryImpl::GetRows(), and mImpl.
Referenced by libcomp::DatabaseMariaDB::Exists().
bool DatabaseQuery::GetValue (size_t index, String & value)
Get an implementation's string column value by its index.
Parameters
index The column's index
value Variable to bind the value to
Returns
true on success, false on failure
Definition at line 359 of file DatabaseQuery.cpp.
References libcomp::DatabaseQueryImpl::GetValue(), and mImpl.
Referenced by libcomp::Database::LoadSingleObjectFromRow(), libcomp::Database::TableHasRows(), libcomp::DatabaseSQLite3::VerifyAndSetupSchema(), and libcomp::DatabaseMariaDB::VerifyAndSetupSchema().
bool DatabaseQuery::GetValue (const String & name, String & value)
Get an implementation's string column value by its name.
Parameters
name The column's name
value Variable to bind the value to
Returns
true on success, false on failure
Definition at line 371 of file DatabaseQuery.cpp.
References libcomp::DatabaseQueryImpl::GetValue(), and mImpl.
bool DatabaseQuery::GetValue (size_t index, std::vector< char > & value)
Get an implementation's blob column value by its index.
Parameters
index The column's index
value Variable to bind the value to
Returns
true on success, false on failure
Definition at line 383 of file DatabaseQuery.cpp.
References libcomp::DatabaseQueryImpl::GetValue(), and mImpl.
bool DatabaseQuery::GetValue (const String & name, std::vector< char > & value)
Get an implementation's blob column value by its name.
Parameters
name The column's name
value Variable to bind the value to
Returns
true on success, false on failure
Definition at line 395 of file DatabaseQuery.cpp.
References libcomp::DatabaseQueryImpl::GetValue(), and mImpl.
bool DatabaseQuery::GetValue (size_t index, libobjgen::UUID & value)
Get an implementation's UUID column value by its index.
Parameters
index The column's index
value Variable to bind the value to
Returns
true on success, false on failure
Definition at line 407 of file DatabaseQuery.cpp.
References libcomp::DatabaseQueryImpl::GetValue(), and mImpl.
bool DatabaseQuery::GetValue (const String & name, libobjgen::UUID & value)
Get an implementation's UUID column value by its name.
Parameters
name The column's name
value Variable to bind the value to
Returns
true on success, false on failure
Definition at line 419 of file DatabaseQuery.cpp.
References libcomp::DatabaseQueryImpl::GetValue(), and mImpl.
bool DatabaseQuery::GetValue (size_t index, int32_t & value)
Get an implementation's 32-bit integer column value by its index.
Parameters
index The column's index
value Variable to bind the value to
Returns
true on success, false on failure
Definition at line 431 of file DatabaseQuery.cpp.
References libcomp::DatabaseQueryImpl::GetValue(), and mImpl.
bool DatabaseQuery::GetValue (const String & name, int32_t & value)
Get an implementation's 32-bit integer column value by its name.
Parameters
name The column's name
value Variable to bind the value to
Returns
true on success, false on failure
Definition at line 443 of file DatabaseQuery.cpp.
References libcomp::DatabaseQueryImpl::GetValue(), and mImpl.
bool DatabaseQuery::GetValue (size_t index, int64_t & value)
Get an implementation's 64-bit integer column value by its index.
Parameters
index The column's index
value Variable to bind the value to
Returns
true on success, false on failure
Definition at line 455 of file DatabaseQuery.cpp.
References libcomp::DatabaseQueryImpl::GetValue(), and mImpl.
bool DatabaseQuery::GetValue (const String & name, int64_t & value)
Get an implementation's 64-bit integer column value by its name.
Parameters
name The column's name
value Variable to bind the value to
Returns
true on success, false on failure
Definition at line 467 of file DatabaseQuery.cpp.
References libcomp::DatabaseQueryImpl::GetValue(), and mImpl.
bool DatabaseQuery::GetValue (size_t index, float & value)
Get an implementation's float column value by its index.
Parameters
index The column's index
value Variable to bind the value to
Returns
true on success, false on failure
Definition at line 479 of file DatabaseQuery.cpp.
References libcomp::DatabaseQueryImpl::GetValue(), and mImpl.
bool DatabaseQuery::GetValue (const String & name, float & value)
Get an implementation's float column value by its name.
Parameters
name The column's name
value Variable to bind the value to
Returns
true on success, false on failure
Definition at line 491 of file DatabaseQuery.cpp.
References libcomp::DatabaseQueryImpl::GetValue(), and mImpl.
bool DatabaseQuery::GetValue (size_t index, double & value)
Get an implementation's double column value by its index.
Parameters
index The column's index
value Variable to bind the value to
Returns
true on success, false on failure
Definition at line 503 of file DatabaseQuery.cpp.
References libcomp::DatabaseQueryImpl::GetValue(), and mImpl.
bool DatabaseQuery::GetValue (const String & name, double & value)
Get an implementation's double column value by its name.
Parameters
name The column's name
value Variable to bind the value to
Returns
true on success, false on failure
Definition at line 515 of file DatabaseQuery.cpp.
References libcomp::DatabaseQueryImpl::GetValue(), and mImpl.
bool DatabaseQuery::GetValue (size_t index, bool & value)
Get an implementation's boolean column value by its index.
Parameters
index The column's index
value Variable to bind the value to
Returns
true on success, false on failure
Definition at line 527 of file DatabaseQuery.cpp.
References libcomp::DatabaseQueryImpl::GetValue(), and mImpl.
bool DatabaseQuery::GetValue (const String & name, bool & value)
Get an implementation's boolean column value by its name.
Parameters
name The column's name
value Variable to bind the value to
Returns
true on success, false on failure
Definition at line 539 of file DatabaseQuery.cpp.
References libcomp::DatabaseQueryImpl::GetValue(), and mImpl.
bool DatabaseQuery::IsValid () const
Check current query implementation's state validity.
Returns
true on valid, false on invalid
Definition at line 321 of file DatabaseQuery.cpp.
References libcomp::DatabaseQueryImpl::IsValid(), and mImpl.
Referenced by libcomp::DatabaseSQLite3::InsertSingleObject(), libcomp::DatabaseMariaDB::InsertSingleObject(), libcomp::DatabaseSQLite3::LoadObjects(), libcomp::DatabaseMariaDB::LoadObjects(), libcomp::DatabaseSQLite3::ProcessExplicitUpdate(), libcomp::DatabaseMariaDB::ProcessExplicitUpdate(), libcomp::Database::TableHasRows(), libcomp::DatabaseSQLite3::UpdateSingleObject(), and libcomp::DatabaseMariaDB::UpdateSingleObject().
bool DatabaseQuery::Next ()
Increment the query implementation's results to look at the next result set row.
Returns
true on success, false on failure
Definition at line 117 of file DatabaseQuery.cpp.
References mImpl, and libcomp::DatabaseQueryImpl::Next().
Referenced by libcomp::DatabaseMariaDB::Exists(), libcomp::DatabaseSQLite3::LoadObjects(), libcomp::DatabaseMariaDB::LoadObjects(), libcomp::Database::TableHasRows(), libcomp::DatabaseSQLite3::VerifyAndSetupSchema(), and libcomp::DatabaseMariaDB::VerifyAndSetupSchema().
DatabaseQuery & DatabaseQuery::operator= (DatabaseQuery && other)
Copy operator implementation.
Parameters
other The other query to copy
Returns
Reference to the new DatabaseQuery
Definition at line 576 of file DatabaseQuery.cpp.
References mImpl.
bool DatabaseQuery::Prepare (const String & query)
Prepare a database query implementation for execution based upon query text.
See Also
DatabaseQuery::Execute
Parameters
query Query text to prepare
Returns
true on success, false on failure
Definition at line 93 of file DatabaseQuery.cpp.
References mImpl, and libcomp::DatabaseQueryImpl::Prepare().
Referenced by DatabaseQuery().
Member Data Documentation
DatabaseQueryImpl* libcomp::DatabaseQuery::mImpl protected
Database specific implementation.
Definition at line 755 of file DatabaseQuery.h.
Referenced by AffectedRowCount(), Bind(), Execute(), GetRows(), GetValue(), IsValid(), Next(), operator=(), Prepare(), and ~DatabaseQuery().
The documentation for this class was generated from the following files:
DatabaseQuery.h
DatabaseQuery.cpp