COMP_hack: libcomp::ArgumentParser Class Reference
libcomp::ArgumentParser Class Reference
Class to handle parsing command line arguments for an application.
#include <ArgumentParser.h>
Classes
struct Argument
Public Types
enum ArgumentType { ArgumentType::NONE, ArgumentType::OPTIONAL, ArgumentType::REQUIRED }
Public Member Functions
ArgumentParser ()
virtual ~ArgumentParser ()
std::vector< String > GetStandardArguments () const
virtual bool Parse (int argc, const char *const argv[])
Protected Member Functions
virtual bool Parse (const std::vector< String > &arguments)
virtual bool ParseStandardArguments (const std::vector< String > &arguments)
virtual void RegisterArgument (char shortName, const String &longName, ArgumentType argType, std::function< bool(Argument *, const String &)> handler)
Private Attributes
std::list< Argument * > mArgumentParsers
std::unordered_map< String,
Argument * > mLongParsers
std::unordered_map< char,
Argument * > mShortParsers
std::vector< String > mStandardArguments
Detailed Description
Class to handle parsing command line arguments for an application.
Definition at line 49 of file ArgumentParser.h.
Member Enumeration Documentation
enum libcomp::ArgumentParser::ArgumentType strong
Enumerator
NONE
OPTIONAL
REQUIRED
Definition at line 52 of file ArgumentParser.h.
Constructor & Destructor Documentation
ArgumentParser::ArgumentParser ()
Definition at line 34 of file ArgumentParser.cpp.
ArgumentParser::~ArgumentParser () virtual
Definition at line 38 of file ArgumentParser.cpp.
References mArgumentParsers, mLongParsers, and mShortParsers.
Member Function Documentation
std::vector< String > ArgumentParser::GetStandardArguments () const
Definition at line 262 of file ArgumentParser.cpp.
References mStandardArguments.
bool ArgumentParser::Parse (int argc, const char *const argv[]) virtual
Definition at line 51 of file ArgumentParser.cpp.
References libcomp::String::IsEmpty().
bool ArgumentParser::Parse (const std::vector< String > & arguments) protected virtual
Definition at line 68 of file ArgumentParser.cpp.
References libcomp::String::Arg(), libcomp::String::At(), libcomp::String::IsEmpty(), libcomp::String::Left(), libcomp::String::Length(), libcomp::String::Matches(), libcomp::String::Mid(), mLongParsers, mShortParsers, NONE, OPTIONAL, ParseStandardArguments(), REQUIRED, and libcomp::String::ToUtf8().
bool ArgumentParser::ParseStandardArguments (const std::vector< String > & arguments) protected virtual
Definition at line 254 of file ArgumentParser.cpp.
References mStandardArguments.
Referenced by Parse().
void ArgumentParser::RegisterArgument (char shortName, const String & longName, ArgumentType argType, std::function< bool(Argument *, const String &)> handler) protected virtual
Definition at line 235 of file ArgumentParser.cpp.
References libcomp::ArgumentParser::Argument::argType, libcomp::ArgumentParser::Argument::handler, libcomp::String::IsEmpty(), libcomp::ArgumentParser::Argument::longName, mArgumentParsers, mLongParsers, mShortParsers, and libcomp::ArgumentParser::Argument::shortName.
Referenced by libcomp::ServerCommandLineParser::ServerCommandLineParser().
Member Data Documentation
std::list<Argument*> libcomp::ArgumentParser::mArgumentParsers private
Definition at line 86 of file ArgumentParser.h.
Referenced by RegisterArgument(), and ~ArgumentParser().
std::unordered_map<String, Argument*> libcomp::ArgumentParser::mLongParsers private
Definition at line 85 of file ArgumentParser.h.
Referenced by Parse(), RegisterArgument(), and ~ArgumentParser().
std::unordered_map<char, Argument*> libcomp::ArgumentParser::mShortParsers private
Definition at line 84 of file ArgumentParser.h.
Referenced by Parse(), RegisterArgument(), and ~ArgumentParser().
std::vector<String> libcomp::ArgumentParser::mStandardArguments private
Definition at line 88 of file ArgumentParser.h.
Referenced by GetStandardArguments(), and ParseStandardArguments().
The documentation for this class was generated from the following files:
ArgumentParser.h
ArgumentParser.cpp