COMP_hack: libcomp::Worker Class Reference
libcomp::Worker Class Reference
Generic worker assigned to a message queue used to handle messages as they are received.
#include <Worker.h>
Public Member Functions
Worker ()
Create a new worker.
virtual ~Worker ()
Cleanup the worker.
void AddManager (const std::shared_ptr< Manager > &manager)
Add a manager to process messages.
long AssignmentCount () const
Get the number of active references to the message queue assigned to the worker.
template<typename Function , typename... Args>
bool ExecuteInWorker (Function &&f, Args &&...args) const
Executes code in the worker thread.
std::shared_ptr
< libcomp::MessageQueue
< libcomp::Message::Message * > > GetMessageQueue () const
Get the message queue assinged to the worker.
String GetWorkerName () const
Get the name for this worker.
bool IsRunning () const
Check if the worker is currently running.
virtual void Join ()
Join the thread used for asynchronous execution.
void RemoveAllManagers ()
Remove all managers from the worker.
virtual void Run (libcomp::MessageQueue< libcomp::Message::Message * > *pMessageQueue)
Wait for a message to enter the queue then handle it with the appropriate Manager configured for the worker.
void SetNextWorker (const std::weak_ptr< Worker > &nextWorker)
Set the next worker to forward messages to.
virtual void Shutdown ()
Signal that the worker should shutdown by sending a Message::Shutdown.
void Start (const libcomp::String &name, bool blocking=false)
Loop until stopped, making a call to Worker::Run.
Protected Member Functions
virtual void Cleanup ()
Clean up the worker, deleting the thread if it exists and resetting the message queue.
virtual void HandleMessage (libcomp::Message::Message *pMessage)
Handle an incoming message from the queue.
Private Attributes
EnumMultiMap
< Message::MessageType,
std::shared_ptr< Manager > > mManagers
Map of pointers to message handlers mapped by message type.
std::shared_ptr
< libcomp::MessageQueue
< libcomp::Message::Message * > > mMessageQueue
Message queue to retrieve messages from.
std::weak_ptr< Worker > mNextWorker
Next worker to forward messages to.
bool mRunning
Signifier that the worker should continue running.
std::thread * mThread
Thread used to handle asynchronous execution.
String mWorkerName
Name for this worker.
Detailed Description
Generic worker assigned to a message queue used to handle messages as they are received.
Workers can run syncronously or in their own thread and should be shutdown at the same time the executing server does.
See Also
BaseServer
Definition at line 52 of file Worker.h.
Constructor & Destructor Documentation
Worker::Worker ()
Create a new worker.
Definition at line 39 of file Worker.cpp.
Worker::~Worker () virtual
Cleanup the worker.
Definition at line 44 of file Worker.cpp.
References Cleanup().
Member Function Documentation
void Worker::AddManager (const std::shared_ptr< Manager > & manager)
Add a manager to process messages.
Parameters
manager A message manager
Definition at line 49 of file Worker.cpp.
References mManagers.
Referenced by libcomp::BaseServer::Initialize().
long Worker::AssignmentCount () const
Get the number of active references to the message queue assigned to the worker.
See Also
BaseServer::GetNextConnectionWorker
Returns
The number of active references to the message queue
Definition at line 241 of file Worker.cpp.
References mMessageQueue.
void Worker::Cleanup () protected virtual
Clean up the worker, deleting the thread if it exists and resetting the message queue.
This is called by the destructor.
Definition at line 197 of file Worker.cpp.
References mMessageQueue, and mThread.
Referenced by ~Worker().
template<typename Function , typename... Args> bool libcomp::Worker::ExecuteInWorker (Function && f, Args &&... args) const inline
Executes code in the worker thread.
Parameters
f Function (lambda) to execute in the worker thread.
args Arguments to pass to the function when it is executed.
Returns
true on success, false on failure
Definition at line 142 of file Worker.h.
References GetMessageQueue().
Referenced by libcomp::BaseServer::QueueWork().
std::shared_ptr< MessageQueue< Message::Message * > > Worker::GetMessageQueue () const
Get the message queue assinged to the worker.
Returns
Assigned message queue
Definition at line 236 of file Worker.cpp.
References mMessageQueue.
Referenced by ExecuteInWorker(), and libcomp::BaseServer::Initialize().
String Worker::GetWorkerName () const
Get the name for this worker.
Returns
Name for this worker.
Definition at line 226 of file Worker.cpp.
References mWorkerName.
void Worker::HandleMessage (libcomp::Message::Message * pMessage) protected virtual
Handle an incoming message from the queue.
Parameters
pMessage Message to handle from the queue.
Definition at line 106 of file Worker.cpp.
References libcomp::String::Arg(), libcomp::Message::Message::Dump(), libcomp::Message::Message::GetType(), mManagers, mNextWorker, mRunning, mWorkerName, and libcomp::Message::Execute::Run().
Referenced by Run().
bool Worker::IsRunning () const
Check if the worker is currently running.
Returns
true if it is running, false if it is not
Definition at line 221 of file Worker.cpp.
References mRunning.
void Worker::Join () virtual
Join the thread used for asynchronous execution.
Definition at line 189 of file Worker.cpp.
References mThread.
void Worker::RemoveAllManagers ()
Remove all managers from the worker.
Definition at line 57 of file Worker.cpp.
References mManagers.
void Worker::Run (libcomp::MessageQueue< libcomp::Message::Message * > * pMessageQueue) virtual
Wait for a message to enter the queue then handle it with the appropriate Manager configured for the worker.
Parameters
pMessageQueue Queue to check for messages
Definition at line 92 of file Worker.cpp.
References libcomp::MessageQueue< T >::DequeueAll(), HandleMessage(), and mRunning.
Referenced by Start().
void Worker::SetNextWorker (const std::weak_ptr< Worker > & nextWorker)
Set the next worker to forward messages to.
Definition at line 231 of file Worker.cpp.
References mNextWorker.
void Worker::Shutdown () virtual
Signal that the worker should shutdown by sending a Message::Shutdown.
Definition at line 184 of file Worker.cpp.
References mMessageQueue.
Referenced by libcomp::BaseServer::Shutdown().
void Worker::Start (const libcomp::String & name, bool blocking = false)
Loop until stopped, making a call to Worker::Run.
Parameters
blocking If false a new thread will be started to run this function asynchronously
Definition at line 62 of file Worker.cpp.
References libcomp::String::C(), mMessageQueue, mRunning, mThread, mWorkerName, libcomp::Exception::RegisterSignalHandler(), and Run().
Referenced by libcomp::BaseServer::Run().
Member Data Documentation
EnumMultiMap<Message::MessageType, std::shared_ptr<Manager> > libcomp::Worker::mManagers private
Map of pointers to message handlers mapped by message type.
Definition at line 187 of file Worker.h.
Referenced by AddManager(), HandleMessage(), and RemoveAllManagers().
std::shared_ptr<libcomp::MessageQueue< libcomp::Message::Message*> > libcomp::Worker::mMessageQueue private
Message queue to retrieve messages from.
Definition at line 183 of file Worker.h.
Referenced by AssignmentCount(), Cleanup(), GetMessageQueue(), Shutdown(), and Start().
std::weak_ptr<Worker> libcomp::Worker::mNextWorker private
Next worker to forward messages to.
Definition at line 179 of file Worker.h.
Referenced by HandleMessage(), and SetNextWorker().
bool libcomp::Worker::mRunning private
Signifier that the worker should continue running.
Definition at line 173 of file Worker.h.
Referenced by HandleMessage(), IsRunning(), Run(), and Start().
std::thread* libcomp::Worker::mThread private
Thread used to handle asynchronous execution.
Definition at line 190 of file Worker.h.
Referenced by Cleanup(), Join(), and Start().
String libcomp::Worker::mWorkerName private
Name for this worker.
Definition at line 176 of file Worker.h.
Referenced by GetWorkerName(), HandleMessage(), and Start().
The documentation for this class was generated from the following files:
Worker.h
Worker.cpp