COMP_hack: libcomp::DefinitionManager Class Reference
libcomp::DefinitionManager Class Reference
Manager class responsible for loading binary files that are accessible client side to use as server definitions.
#include <DefinitionManager.h>
Public Member Functions
DefinitionManager ()
Create a new DefinitionManager.
~DefinitionManager ()
Clean up the DefinitionManager.
const std::shared_ptr
< objects::MiAIData > GetAIData (uint32_t id)
Get the client-side AI definition corresponding to an ID.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::MiDevilLVUpRateData > > GetAllDevilLVUpRateData ()
Get all devil level up information records.
std::unordered_map< int16_t,
std::shared_ptr
< objects::MiEnchantData > > GetAllEnchantData ()
Get a map of all enchantment definitions by ID.
const std::unordered_map
< uint32_t, std::shared_ptr
< objects::EnchantSetData > > GetAllEnchantSetData ()
Get all enchant set definitions by ID.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::MiSynthesisData > > GetAllSynthesisData ()
Get all synthesis definitions by ID.
const std::unordered_map
< int32_t, std::shared_ptr
< objects::Tokusei > > GetAllTokuseiData ()
Get all tokusei definitions by ID.
const std::shared_ptr
< objects::MiBlendData > GetBlendData (uint32_t id)
Get the item mixing definition corresponding to an ID.
const std::shared_ptr
< objects::MiBlendExtData > GetBlendExtData (uint32_t id)
Get the item mixing extension definition corresponding to an ID.
std::unordered_map< int8_t,
std::shared_ptr
< objects::MiCHouraiData > > GetCHouraiData ()
Get the client-side hourai NPC definitions by ID.
const std::shared_ptr
< objects::MiCultureItemData > GetCultureItemData (uint32_t id)
Get the culture item definition corresponding to an ID.
const std::shared_ptr
< objects::MiDevilBookData > GetDevilBookData (uint32_t id)
Get the devil book definition corresponding to an ID.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::MiDevilBookData > > GetDevilBookData ()
Get all devil book definitions by definition ID.
const std::shared_ptr
< objects::MiDevilBoostData > GetDevilBoostData (uint32_t id)
Get the devil boost definition corresponding to an ID.
const std::shared_ptr
< objects::MiDevilBoostExtraData > GetDevilBoostExtraData (uint16_t id)
Get the devil boost extra definition corresponding to a stack ID.
const std::shared_ptr
< objects::MiDevilBoostItemData > GetDevilBoostItemData (uint32_t id)
Get the devil boost item definition corresponding to an ID.
std::list< uint16_t > GetDevilBoostLotIDs (int32_t count)
Get the list of all stack IDs in a devil boost lot or any lower lot that multiplies into supplied value (ex: 400 returns 100 and 200 lots)
std::shared_ptr
< objects::MiDevilData > GetDevilData (uint32_t id)
Get the devil definition corresponding to an ID.
const std::shared_ptr
< objects::MiDevilData > GetDevilData (const libcomp::String &name)
Get a devil definition corresponding to a name.
const std::shared_ptr
< objects::MiDevilEquipmentData > GetDevilEquipmentData (uint32_t skillID)
Get the devil equipment definition corresponding to a skill ID.
const std::shared_ptr
< objects::MiDevilEquipmentItemData > GetDevilEquipmentItemData (uint32_t itemID)
Get the devil equipment item definition corresponding to an ID.
const std::shared_ptr
< objects::MiDevilFusionData > GetDevilFusionData (uint32_t id)
Get the fusion skill definition corresponding to an ID.
std::set< uint32_t > GetDevilFusionIDsByDemonID (uint32_t demonID)
Get set of devil fusion definition IDs that have an explicit demon ID listed as a requirement.
const std::shared_ptr
< objects::MiDevilLVUpRateData > GetDevilLVUpRateData (uint32_t id)
Get the devil level up information corresponding to an ID.
const std::list< uint32_t > GetDisassembledItemIDs ()
Get all item IDs associated to disassembled items.
const std::shared_ptr
< objects::MiDisassemblyData > GetDisassemblyData (uint32_t id)
Get the item disassembly definition corresponding to an ID.
const std::shared_ptr
< objects::MiDisassemblyData > GetDisassemblyDataByItemID (uint32_t itemID)
Get the item disassembly definition corresponding to an item ID.
const std::shared_ptr
< objects::MiDisassemblyTriggerData > GetDisassemblyTriggerData (uint32_t id)
Get the item disassembly trigger definition corresponding to an ID.
const std::shared_ptr
< objects::MiDynamicMapData > GetDynamicMapData (uint32_t id)
Get the dynamic map information corresponding to an ID.
const std::shared_ptr
< objects::MiEnchantData > GetEnchantData (int16_t id)
Get the enchantment definition corresponding to an ID.
const std::shared_ptr
< objects::MiEnchantData > GetEnchantDataByDemonID (uint32_t demonID)
Get the enchantment definition corresponding to a demon ID.
const std::shared_ptr
< objects::MiEnchantData > GetEnchantDataByItemID (uint32_t itemID)
Get the enchantment definition corresponding to an item ID.
const std::shared_ptr
< objects::EnchantSetData > GetEnchantSetData (uint32_t id)
Get an enchant set by definition ID.
std::list< std::shared_ptr
< objects::EnchantSetData > > GetEnchantSetDataByEffect (int16_t effectID)
Get the enchant set information corresponding to an effect.
const std::shared_ptr
< objects::EnchantSpecialData > GetEnchantSpecialData (uint32_t id)
Get a special enchant by definition ID.
std::list< std::shared_ptr
< objects::EnchantSpecialData > > GetEnchantSpecialDataByInputItem (uint32_t itemID)
Get the special enchant information corresponding to an input item type.
const std::shared_ptr
< objects::MiEquipmentSetData > GetEquipmentSetData (uint32_t id)
Get the equipment set information corresponding to an ID.
std::list< std::shared_ptr
< objects::MiEquipmentSetData > > GetEquipmentSetDataByItem (uint32_t equipmentID)
Get the equipment set information corresponding to a piece of equipment in the set.
const std::shared_ptr
< objects::MiExchangeData > GetExchangeData (uint32_t id)
Get the item exchange data corresponding to an ID.
const std::shared_ptr
< objects::MiExpertData > GetExpertClassData (uint32_t id)
Get the character expertise information corresponding to an ID.
std::set< uint32_t > GetFunctionIDSkills (uint16_t fid) const
Get all skill definition IDs that are mapped to the supplied function ID.
const std::list< std::pair
< uint8_t, uint32_t > > GetFusionRanges (uint8_t raceID)
Get the list of fusion range level and demon ID pairs associated to the supplied demon race.
const std::shared_ptr
< objects::MiGuardianAssistData > GetGuardianAssistData (uint32_t id)
Get the guardian assist information corresponding to an ID.
const std::shared_ptr
< objects::MiGuardianLevelData > GetGuardianLevelData (uint32_t id)
Get the guardian level information corresponding to an ID.
const std::set< uint8_t > GetGuardianRaceIDs ()
Get all guardian race IDs with defined level information.
const std::shared_ptr
< objects::MiGuardianSpecialData > GetGuardianSpecialData (uint32_t id)
Get the guardian special information corresponding to an ID.
const std::shared_ptr
< objects::MiGuardianUnlockData > GetGuardianUnlockData (uint32_t id)
Get the guardian unlock information corresponding to an ID.
const std::shared_ptr
< objects::MiHNPCData > GetHNPCData (uint32_t id)
Get the human NPC definition corresponding to an ID.
const std::shared_ptr
< objects::MiItemData > GetItemData (uint32_t id)
Get the item definition corresponding to an ID.
const std::shared_ptr
< objects::MiItemData > GetItemData (const libcomp::String &name)
Get the item definition corresponding to a name.
const std::shared_ptr
< objects::MiMissionData > GetMissionData (uint32_t id)
Get the mission definition corresponding to an ID.
const std::shared_ptr
< objects::MiMitamaReunionBonusData > GetMitamaReunionBonusData (uint32_t id)
Get the mitama reunion bonus definition corresponding to an ID.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::MiMitamaReunionSetBonusData > > GetMitamaReunionSetBonusData ()
Get all mitama reunion set bonus definitions by ID.
const std::shared_ptr
< objects::MiMitamaUnionBonusData > GetMitamaUnionBonusData (uint32_t id)
Get the mitama union bonus definition corresponding to an ID.
const std::shared_ptr
< objects::MiModificationData > GetModificationData (uint32_t id)
Get the item modification definition corresponding to an ID.
const std::shared_ptr
< objects::MiModificationData > GetModificationDataByItemID (uint32_t itemID)
Get the item modification definition corresponding to an item ID.
const std::shared_ptr
< objects::MiModificationExtEffectData > GetModificationExtEffectData (uint8_t groupID, uint8_t slot, uint16_t subID)
Get the item modification extra effect definition corresponding to a group ID, slot and subID.
const std::shared_ptr
< objects::MiModificationExtRecipeData > GetModificationExtRecipeData (uint32_t id)
Get the item modification extra recipe definition corresponding to an ID.
const std::shared_ptr
< objects::MiModificationExtRecipeData > GetModificationExtRecipeDataByItemID (uint32_t itemID)
Get the item modification extra recipe definition corresponding to an item ID.
const std::shared_ptr
< objects::MiModificationTriggerData > GetModificationTriggerData (uint16_t id)
Get the item modification trigger definition corresponding to an ID.
const std::shared_ptr
< objects::MiModifiedEffectData > GetModifiedEffectData (uint16_t id)
Get the item modification effect definition corresponding to an ID.
const std::shared_ptr
< objects::MiNPCBarterConditionData > GetNPCBarterConditionData (uint16_t id)
Get the NPC barter condition definition corresponding to an ID.
const std::shared_ptr
< objects::MiNPCBarterData > GetNPCBarterData (uint16_t id)
Get the NPC barter definition corresponding to an ID.
const std::shared_ptr
< objects::MiNPCBarterGroupData > GetNPCBarterGroupData (uint16_t id)
Get the NPC barter group definition corresponding to an ID.
const std::shared_ptr
< objects::MiONPCData > GetONPCData (uint32_t id)
Get the server object NPC definition corresponding to an ID.
const std::shared_ptr
< objects::MiQuestBonusCodeData > GetQuestBonusCodeData (uint32_t id)
Get the quest bonus code definition corresponding to an ID.
const std::shared_ptr
< objects::MiQuestData > GetQuestData (uint32_t id)
Get the quest definition corresponding to an ID.
const std::shared_ptr
< objects::MiShopProductData > GetShopProductData (uint32_t id)
Get the shop product definition corresponding to an ID.
std::set< int32_t > GetSItemTokusei (uint32_t id)
Get the s-item tokusei IDs corresponding to an item ID.
const std::shared_ptr
< objects::MiSkillData > GetSkillData (uint32_t id)
Get the skill definition corresponding to an ID.
const std::unordered_map
< uint32_t, std::shared_ptr
< objects::MiSpotData > > GetSpotData (uint32_t dynamicMapID)
Get the spot data corresponding to a dynamic map ID.
const std::shared_ptr
< objects::MiSStatusData > GetSStatusData (uint32_t id)
Get the s-status definition corresponding to an ID.
const std::shared_ptr
< objects::MiStatusData > GetStatusData (uint32_t id)
Get the status definition corresponding to an ID.
const std::shared_ptr
< objects::MiSynthesisData > GetSynthesisData (uint32_t id)
Get the synthesis definition corresponding to an ID.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::MiTankData > > GetTankData ()
Get the map of all material tank item definitions by ID.
const std::shared_ptr
< objects::MiTimeLimitData > GetTimeLimitData (uint32_t id)
Get the time limit definition corresponding to an ID.
const std::shared_ptr
< objects::MiTitleData > GetTitleData (int16_t id)
Get the title definition corresponding to an ID.
std::set< int16_t > GetTitleIDs ()
Get the set of all (non-special) title IDs.
const std::shared_ptr
< objects::Tokusei > GetTokuseiData (int32_t id)
Get a tokusei by definition ID.
const std::list
< std::shared_ptr
< objects::MiTriUnionSpecialData > > GetTriUnionSpecialData (uint32_t sourceDemonTypeID)
Get the list of pointers to special fusion definitions by the ID of a source demon involved.
const std::shared_ptr
< objects::MiUraFieldTowerData > GetUraFieldTowerData (uint32_t dungeonID, uint32_t id)
Get the (Diaspora) ura field tower corresponding to an ID.
const std::shared_ptr
< objects::MiWarpPointData > GetWarpPointData (uint32_t id)
Get the warp point corresponding to an ID.
const std::shared_ptr
< objects::MiZoneData > GetZoneData (uint32_t id)
Get the zone definition corresponding to an ID.
bool LoadAllData (DataStore *pDataStore)
Load all binary data definitions.
template<class T >
bool LoadData (DataStore *pDataStore)
Load the binary data definitions of the specified type.
std::shared_ptr< objects::QmpFile > LoadQmpFile (const libcomp::String &fileName, DataStore *pDataStore)
Load the QMP file with the specified filename from the supplied datastore.
template<class T >
bool RegisterServerSideDefinition (const std::shared_ptr< T > &record)
Register a server side definition into the manager from an external source.
Private Member Functions
template<class X , class T >
std::shared_ptr< T > GetRecordByID (X id, std::unordered_map< X, std::shared_ptr< T >> &data)
Utility function to pull the templated type from a standard definition map of ID to a pointer of that type.
template<class T >
bool LoadBinaryData (DataStore *pDataStore, const libcomp::String &binaryFile, bool decrypt, uint16_t tablesExpected, std::list< std::shared_ptr< T >> &records, bool printResults=true)
Load a binary file from the specified data store location.
bool LoadBinaryDataHeader (libcomp::ObjectInStream &ois, const libcomp::String &binaryFile, uint16_t tablesExpected, uint16_t &entryCount, uint16_t &tableCount)
Load the data header containing the number of entries and tables that make up the format of the rest of the file.
void PrintLoadResult (const libcomp::String &binaryFile, bool success, uint16_t entriesExpected, size_t loadedEntries)
Utility function to print the result of loading a binary file.
Private Attributes
std::unordered_map< uint32_t,
std::shared_ptr
< objects::MiAIData > > mAIData
Map of client-side AI definitions by ID.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::MiBlendData > > mBlendData
Map of item mixing definitions by ID.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::MiBlendExtData > > mBlendExtData
Map of item mixing extension definitions by ID.
std::unordered_map< int8_t,
std::shared_ptr
< objects::MiCHouraiData > > mCHouraiData
Map of client-side hourai NPC definitions by ID.
std::unordered_map
< libcomp::String, uint32_t > mCItemNameLookup
Map of item names to IDs.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::MiCultureItemData > > mCultureItemData
Map of culture item definitions by ID.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::MiDevilBookData > > mDevilBookData
Map of devil book definitions by ID.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::MiDevilBoostData > > mDevilBoostData
Map of devil boost definitions by ID.
std::unordered_map< uint16_t,
std::shared_ptr
< objects::MiDevilBoostExtraData > > mDevilBoostExtraData
Map of devil boost extra definitions by ID.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::MiDevilBoostItemData > > mDevilBoostItemData
Map of devil boost item definitions by ID.
std::unordered_map< int32_t,
std::list< uint16_t > > mDevilBoostLots
Map of lot IDs to devil boost extra stack IDs in that lot.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::MiDevilData > > mDevilData
Map of devil definitions by ID.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::MiDevilEquipmentData > > mDevilEquipmentData
Map of devil equipment definitions by skill ID.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::MiDevilEquipmentItemData > > mDevilEquipmentItemData
Map of devil equipment definitions by item ID.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::MiDevilFusionData > > mDevilFusionData
Map of devil fusion definitions by ID.
std::unordered_map< uint32_t,
std::set< uint32_t > > mDevilFusionLookup
Map of devil fusion definition IDs mapped by demon IDs listed as explicit requirements for the skill.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::MiDevilLVUpRateData > > mDevilLVUpRateData
Map of devil level up information by growth type ID.
std::unordered_map
< libcomp::String, uint32_t > mDevilNameLookup
Map of devil names to IDs which are NOT unique across entries.
std::list< uint32_t > mDisassembledItemIDs
List of all disassembled item IDs (or "elements")
std::unordered_map< uint32_t,
std::shared_ptr
< objects::MiDisassemblyData > > mDisassemblyData
Map of item disassembly definitions by ID.
std::unordered_map< uint32_t,
uint32_t > mDisassemblyLookup
Map of item disassembly definition IDs by item ID.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::MiDisassemblyTriggerData > > mDisassemblyTriggerData
Map of item disassembly trigger definitions by ID.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::MiDynamicMapData > > mDynamicMapData
Map of dynamic map information by ID.
std::unordered_map< int16_t,
std::shared_ptr
< objects::MiEnchantData > > mEnchantData
Map of enchantment definitions by ID.
std::unordered_map< uint32_t,
int16_t > mEnchantDemonLookup
Map of enchantment IDs by demon ID.
std::unordered_map< uint32_t,
int16_t > mEnchantItemLookup
Map of enchantment IDs by item ID.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::EnchantSetData > > mEnchantSetData
Map of enchant set definitions by ID.
std::unordered_map< int16_t,
std::list< uint32_t > > mEnchantSetLookup
Map of enchant set definition IDs by effect ID.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::EnchantSpecialData > > mEnchantSpecialData
Map of enchant special definitions by ID.
std::unordered_map< uint32_t,
std::list< uint32_t > > mEnchantSpecialLookup
Map of enchant special definition IDs by input item ID.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::MiEquipmentSetData > > mEquipmentSetData
Map of equipment set information by ID.
std::unordered_map< uint32_t,
std::list< uint32_t > > mEquipmentSetLookup
Map of equipment IDs to set IDs they belong to.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::MiExchangeData > > mExchangeData
Map of item exchange data by ID.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::MiExpertData > > mExpertData
Map of character expertise information by ID.
std::unordered_map< uint16_t,
std::set< uint32_t > > mFunctionIDSkills
Map of skill function IDs to skill IDs.
std::unordered_map< uint8_t,
std::list< std::pair< uint8_t,
uint32_t > > > mFusionRanges
Map of demon race IDs to maximum fusion range levels paired with their corresponding result demon.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::MiGuardianAssistData > > mGuardianAssistData
Map of digitalize "guardian assist" information by ID.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::MiGuardianLevelData > > mGuardianLevelData
Map of digitalize "guardian level" information by ID.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::MiGuardianSpecialData > > mGuardianSpecialData
Map of digitalize "guardian special" information by ID.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::MiGuardianUnlockData > > mGuardianUnlockData
Map of digitalize "guardian unlock" information by ID.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::MiHNPCData > > mHNPCData
Map of human NPC definitions by ID.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::MiItemData > > mItemData
Map of item definitions by ID.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::MiMissionData > > mMissionData
Map of mission definitions by ID.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::MiMitamaReunionBonusData > > mMitamaReunionBonusData
Map of mitama reunion bonus definitions by ID.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::MiMitamaReunionSetBonusData > > mMitamaReunionSetBonusData
Map of mitama reunion set bonus definitions by ID.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::MiMitamaUnionBonusData > > mMitamaUnionBonusData
Map of mitama union bonus definitions by ID.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::MiModificationData > > mModificationData
Map of item modification definitions by ID.
std::unordered_map< uint8_t,
std::unordered_map< uint8_t,
std::unordered_map< uint16_t,
std::shared_ptr
< objects::MiModificationExtEffectData > > > > mModificationExtEffectData
Map of item modification extra effect definitions by their group ID, slot then sub ID.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::MiModificationExtRecipeData > > mModificationExtRecipeData
Map of item modification extra recipe definitions by ID.
std::unordered_map< uint32_t,
uint32_t > mModificationExtRecipeLookup
Map of item modification extra recipe definition IDs by item ID.
std::unordered_map< uint32_t,
uint32_t > mModificationLookup
Map of item modification definition IDs by item ID.
std::unordered_map< uint16_t,
std::shared_ptr
< objects::MiModificationTriggerData > > mModificationTriggerData
Map of item modification trigger definitions by ID.
std::unordered_map< uint16_t,
std::shared_ptr
< objects::MiModifiedEffectData > > mModifiedEffectData
Map of item modification effect definitions by ID.
std::unordered_map< uint16_t,
std::shared_ptr
< objects::MiNPCBarterConditionData > > mNPCBarterConditionData
Map of NPC barter condition definitions by ID.
std::unordered_map< uint16_t,
std::shared_ptr
< objects::MiNPCBarterData > > mNPCBarterData
Map of NPC barter definitions by ID.
std::unordered_map< uint16_t,
std::shared_ptr
< objects::MiNPCBarterGroupData > > mNPCBarterGroupData
Map of NPC barter group definitions by ID.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::MiONPCData > > mONPCData
Map of server object NPC definitions by ID.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::MiQuestBonusCodeData > > mQuestBonusCodeData
Map of quest bonus code definitions by ID.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::MiQuestData > > mQuestData
Map of quest definitions by ID.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::MiShopProductData > > mShopProductData
Map of shop product definitions by ID.
std::unordered_map< uint32_t,
std::set< int32_t > > mSItemTokusei
Map of s-item tokusei IDs by item ID.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::MiSkillData > > mSkillData
Map of skill definitions by ID.
std::unordered_map
< std::string,
std::unordered_map< uint32_t,
std::shared_ptr
< objects::MiSpotData > > > mSpotData
Map of filename to map of spots by ID.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::MiSStatusData > > mSStatusData
Map of s-status definitions by ID.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::MiStatusData > > mStatusData
Map of status definitions by ID.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::MiSynthesisData > > mSynthesisData
Map of synthesis definitions by ID.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::MiTankData > > mTankData
Map of material tank definitions by ID.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::MiTimeLimitData > > mTimeLimitData
Map of time limit definitions by ID.
std::unordered_map< int16_t,
std::shared_ptr
< objects::MiTitleData > > mTitleData
Map of title definitions by ID.
std::set< int16_t > mTitleIDs
Set of all (non-special) title IDs.
std::unordered_map< int32_t,
std::shared_ptr
< objects::Tokusei > > mTokuseiData
Map of tokusei definitions by ID.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::MiTriUnionSpecialData > > mTriUnionSpecialData
Map of special fusion definitions by ID.
std::unordered_map< uint32_t,
std::list< uint32_t > > mTriUnionSpecialDataBySourceID
Map of source demon IDs to special fusions they belong to.
std::unordered_map< uint32_t,
std::unordered_map< uint32_t,
std::shared_ptr
< objects::MiUraFieldTowerData > > > mUraFieldTowerData
Map of (Diaspora) ura field tower definitions by dungeon ID, then ID.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::MiWarpPointData > > mWarpPointData
Map of warp point definitions by ID.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::MiZoneData > > mZoneData
Map of zone definitions by ID.
Detailed Description
Manager class responsible for loading binary files that are accessible client side to use as server definitions.
Definition at line 114 of file DefinitionManager.h.
Constructor & Destructor Documentation
DefinitionManager::DefinitionManager ()
Create a new DefinitionManager.
Definition at line 116 of file DefinitionManager.cpp.
DefinitionManager::~DefinitionManager ()
Clean up the DefinitionManager.
Definition at line 120 of file DefinitionManager.cpp.
Member Function Documentation
const std::shared_ptr< objects::MiAIData > DefinitionManager::GetAIData (uint32_t id)
Get the client-side AI definition corresponding to an ID.
Parameters
id Client-side AI to retrieve
Returns
Pointer to the matching client-side AI definition, null if it does not exist
Definition at line 125 of file DefinitionManager.cpp.
References GetRecordByID(), and mAIData.
std::unordered_map< uint32_t, std::shared_ptr< objects::MiDevilLVUpRateData > > DefinitionManager::GetAllDevilLVUpRateData ()
Get all devil level up information records.
Returns
Map of devil level up information by growth type ID
Definition at line 279 of file DefinitionManager.cpp.
References mDevilLVUpRateData.
std::unordered_map< int16_t, std::shared_ptr< objects::MiEnchantData > > DefinitionManager::GetAllEnchantData ()
Get a map of all enchantment definitions by ID.
Returns
Map of all enchantment definitions by ID
Definition at line 326 of file DefinitionManager.cpp.
References mEnchantData.
const std::unordered_map< uint32_t, std::shared_ptr< objects::EnchantSetData > > DefinitionManager::GetAllEnchantSetData ()
Get all enchant set definitions by ID.
Returns
Map of all enchant set definitions by ID
Definition at line 773 of file DefinitionManager.cpp.
References mEnchantSetData.
std::unordered_map< uint32_t, std::shared_ptr< objects::MiSynthesisData > > DefinitionManager::GetAllSynthesisData ()
Get all synthesis definitions by ID.
Returns
All synthesis definitions by ID
Definition at line 658 of file DefinitionManager.cpp.
References mSynthesisData.
const std::unordered_map< int32_t, std::shared_ptr< objects::Tokusei > > DefinitionManager::GetAllTokuseiData ()
Get all tokusei definitions by ID.
Returns
Map of all tokusei definitions by ID
Definition at line 812 of file DefinitionManager.cpp.
References mTokuseiData.
const std::shared_ptr< objects::MiBlendData > DefinitionManager::GetBlendData (uint32_t id)
Get the item mixing definition corresponding to an ID.
Parameters
id Item mixing ID to retrieve
Returns
Pointer to the matching item mixing definition, null if it does not exist
Definition at line 131 of file DefinitionManager.cpp.
References GetRecordByID(), and mBlendData.
const std::shared_ptr< objects::MiBlendExtData > DefinitionManager::GetBlendExtData (uint32_t id)
Get the item mixing extension definition corresponding to an ID.
Parameters
id Item mixing extension ID to retrieve
Returns
Pointer to the matching item mixing extension definition, null if it does not exist
Definition at line 137 of file DefinitionManager.cpp.
References GetRecordByID(), and mBlendExtData.
std::unordered_map< int8_t, std::shared_ptr< objects::MiCHouraiData > > DefinitionManager::GetCHouraiData ()
Get the client-side hourai NPC definitions by ID.
Returns
Map of client-side hourai NPC definitions by ID
Definition at line 143 of file DefinitionManager.cpp.
References mCHouraiData.
const std::shared_ptr< objects::MiCultureItemData > DefinitionManager::GetCultureItemData (uint32_t id)
Get the culture item definition corresponding to an ID.
Parameters
id Culture item ID to retrieve
Returns
Pointer to the matching culture item definition, null if it does not exist
Definition at line 149 of file DefinitionManager.cpp.
References GetRecordByID(), and mCultureItemData.
const std::shared_ptr< objects::MiDevilBookData > DefinitionManager::GetDevilBookData (uint32_t id)
Get the devil book definition corresponding to an ID.
Parameters
id Devil book ID to retrieve
Returns
Pointer to the matching devil book definition, null if it does not exist
Definition at line 155 of file DefinitionManager.cpp.
References GetRecordByID(), and mDevilBookData.
std::unordered_map< uint32_t, std::shared_ptr< objects::MiDevilBookData > > DefinitionManager::GetDevilBookData ()
Get all devil book definitions by definition ID.
Returns
Map of devil book definitions by ID
Definition at line 161 of file DefinitionManager.cpp.
References mDevilBookData.
const std::shared_ptr< objects::MiDevilBoostData > DefinitionManager::GetDevilBoostData (uint32_t id)
Get the devil boost definition corresponding to an ID.
Parameters
id Devil boost ID to retrieve
Returns
Pointer to the matching devil boost definition, null if it does not exist
Definition at line 167 of file DefinitionManager.cpp.
References GetRecordByID(), and mDevilBoostData.
const std::shared_ptr< objects::MiDevilBoostExtraData > DefinitionManager::GetDevilBoostExtraData (uint16_t id)
Get the devil boost extra definition corresponding to a stack ID.
Parameters
id Devil boost extra stack ID to retrieve
Returns
Pointer to the matching devil boost extra definition, null if it does not exist
Definition at line 173 of file DefinitionManager.cpp.
References GetRecordByID(), and mDevilBoostExtraData.
const std::shared_ptr< objects::MiDevilBoostItemData > DefinitionManager::GetDevilBoostItemData (uint32_t id)
Get the devil boost item definition corresponding to an ID.
Parameters
id Devil boost item ID to retrieve
Returns
Pointer to the matching devil boost item definition, null if it does not exist
Definition at line 179 of file DefinitionManager.cpp.
References GetRecordByID(), and mDevilBoostItemData.
std::list< uint16_t > DefinitionManager::GetDevilBoostLotIDs (int32_t count)
Get the list of all stack IDs in a devil boost lot or any lower lot that multiplies into supplied value (ex: 400 returns 100 and 200 lots)
Parameters
count Boost count from a demon's benefit gauge
Returns
List of stack IDs
Definition at line 184 of file DefinitionManager.cpp.
References mDevilBoostLots.
std::shared_ptr< objects::MiDevilData > DefinitionManager::GetDevilData (uint32_t id)
Get the devil definition corresponding to an ID.
Parameters
id Devil ID to retrieve
Returns
Pointer to the matching devil definition, null if it does not exist
Definition at line 213 of file DefinitionManager.cpp.
References GetRecordByID(), and mDevilData.
Referenced by GetDevilData(), GetDevilFusionIDsByDemonID(), GetTriUnionSpecialData(), and libcomp::ScriptEngine::Using().
const std::shared_ptr< objects::MiDevilData > DefinitionManager::GetDevilData (const libcomp::String & name)
Get a devil definition corresponding to a name.
Parameters
name Devil name to retrieve
Returns
Pointer to the matching devil definition, null if it does not exist
Definition at line 219 of file DefinitionManager.cpp.
References GetDevilData(), and mDevilNameLookup.
const std::shared_ptr< objects::MiDevilEquipmentData > DefinitionManager::GetDevilEquipmentData (uint32_t skillID)
Get the devil equipment definition corresponding to a skill ID.
Parameters
id Devil equipment skill ID to retrieve
Returns
Pointer to the matching devil equipment definition, null if it does not exist
Definition at line 231 of file DefinitionManager.cpp.
References GetRecordByID(), and mDevilEquipmentData.
const std::shared_ptr< objects::MiDevilEquipmentItemData > DefinitionManager::GetDevilEquipmentItemData (uint32_t itemID)
Get the devil equipment item definition corresponding to an ID.
Parameters
id Devil equipment item ID to retrieve
Returns
Pointer to the matching devil equipment item definition, null if it does not exist
Definition at line 237 of file DefinitionManager.cpp.
References GetRecordByID(), and mDevilEquipmentItemData.
const std::shared_ptr< objects::MiDevilFusionData > DefinitionManager::GetDevilFusionData (uint32_t id)
Get the fusion skill definition corresponding to an ID.
Parameters
id Fusion skill ID to retrieve
Returns
Pointer to the matching fusion skill definition, null if it does not exist
Definition at line 243 of file DefinitionManager.cpp.
References GetRecordByID(), and mDevilFusionData.
std::set< uint32_t > DefinitionManager::GetDevilFusionIDsByDemonID (uint32_t demonID)
Get set of devil fusion definition IDs that have an explicit demon ID listed as a requirement.
Parameters
demonID Definition ID of a demon
Returns
Set of devil fusion definition IDs
Definition at line 248 of file DefinitionManager.cpp.
References GetDevilData(), and mDevilFusionLookup.
const std::shared_ptr< objects::MiDevilLVUpRateData > DefinitionManager::GetDevilLVUpRateData (uint32_t id)
Get the devil level up information corresponding to an ID.
Parameters
id Devil level up information ID to retrieve
Returns
Pointer to the matching devil level up information, null if it does not exist
Definition at line 273 of file DefinitionManager.cpp.
References GetRecordByID(), and mDevilLVUpRateData.
const std::list< uint32_t > DefinitionManager::GetDisassembledItemIDs ()
Get all item IDs associated to disassembled items.
Returns
List of all disassembled item IDs
Definition at line 308 of file DefinitionManager.cpp.
References mDisassembledItemIDs.
const std::shared_ptr< objects::MiDisassemblyData > DefinitionManager::GetDisassemblyData (uint32_t id)
Get the item disassembly definition corresponding to an ID.
Parameters
id Item disassembly ID to retrieve
Returns
Pointer to the matching item disassembly definition, null if it does not exist
Definition at line 285 of file DefinitionManager.cpp.
References GetRecordByID(), and mDisassemblyData.
const std::shared_ptr< objects::MiDisassemblyData > DefinitionManager::GetDisassemblyDataByItemID (uint32_t itemID)
Get the item disassembly definition corresponding to an item ID.
Parameters
itemID Item ID to retrieve the disassembly from
Returns
Pointer to the matching item disassembly definition, null if it does not exist
Definition at line 291 of file DefinitionManager.cpp.
References GetRecordByID(), mDisassemblyData, and mDisassemblyLookup.
const std::shared_ptr< objects::MiDisassemblyTriggerData > DefinitionManager::GetDisassemblyTriggerData (uint32_t id)
Get the item disassembly trigger definition corresponding to an ID.
Parameters
id Item disassembly trigger ID to retrieve
Returns
Pointer to the matching item disassembly trigger definition, null if it does not exist
Definition at line 303 of file DefinitionManager.cpp.
References GetRecordByID(), and mDisassemblyTriggerData.
const std::shared_ptr< objects::MiDynamicMapData > DefinitionManager::GetDynamicMapData (uint32_t id)
Get the dynamic map information corresponding to an ID.
Parameters
id Dynamic map information ID to retrieve
Returns
Pointer to the matching dynamic map information, null if it does not exist
Definition at line 314 of file DefinitionManager.cpp.
References GetRecordByID(), and mDynamicMapData.
Referenced by GetSpotData().
const std::shared_ptr< objects::MiEnchantData > DefinitionManager::GetEnchantData (int16_t id)
Get the enchantment definition corresponding to an ID.
Parameters
id Enchantment ID to retrieve
Returns
Pointer to the matching enchantment definition, null if it does not exist
Definition at line 320 of file DefinitionManager.cpp.
References GetRecordByID(), and mEnchantData.
Referenced by GetEnchantDataByDemonID(), and GetEnchantDataByItemID().
const std::shared_ptr< objects::MiEnchantData > DefinitionManager::GetEnchantDataByDemonID (uint32_t demonID)
Get the enchantment definition corresponding to a demon ID.
Parameters
demonID Demon ID to retrieve a definition from
Returns
Pointer to the matching enchantment definition, null if it does not exist
Definition at line 332 of file DefinitionManager.cpp.
References GetEnchantData(), and mEnchantDemonLookup.
const std::shared_ptr< objects::MiEnchantData > DefinitionManager::GetEnchantDataByItemID (uint32_t itemID)
Get the enchantment definition corresponding to an item ID.
Parameters
itemID Item ID to retrieve a definition from
Returns
Pointer to the matching enchantment definition, null if it does not exist
Definition at line 344 of file DefinitionManager.cpp.
References GetEnchantData(), and mEnchantItemLookup.
const std::shared_ptr< objects::EnchantSetData > DefinitionManager::GetEnchantSetData (uint32_t id)
Get an enchant set by definition ID.
Parameters
id Definition ID of an enchant set to load
Returns
Pointer to the enchant set matching the specified id
Definition at line 746 of file DefinitionManager.cpp.
References GetRecordByID(), and mEnchantSetData.
Referenced by GetEnchantSetDataByEffect().
std::list< std::shared_ptr< objects::EnchantSetData > > DefinitionManager::GetEnchantSetDataByEffect (int16_t effectID)
Get the enchant set information corresponding to an effect.
Parameters
effectID Effect ID to retrieve sets for
Returns
List of pointers to the matching enchant set information
Definition at line 752 of file DefinitionManager.cpp.
References GetEnchantSetData(), and mEnchantSetLookup.
const std::shared_ptr< objects::EnchantSpecialData > DefinitionManager::GetEnchantSpecialData (uint32_t id)
Get a special enchant by definition ID.
Parameters
id Definition ID of a special enchant to load
Returns
Pointer to the special enchant matching the specified id
Definition at line 779 of file DefinitionManager.cpp.
References GetRecordByID(), and mEnchantSpecialData.
Referenced by GetEnchantSpecialDataByInputItem().
std::list< std::shared_ptr< objects::EnchantSpecialData > > DefinitionManager::GetEnchantSpecialDataByInputItem (uint32_t itemID)
Get the special enchant information corresponding to an input item type.
Parameters
itemID Input item ID to retrieve special enchants for
Returns
List of pointers to the matching special enchant information
Definition at line 785 of file DefinitionManager.cpp.
References GetEnchantSpecialData(), and mEnchantSpecialLookup.
const std::shared_ptr< objects::MiEquipmentSetData > DefinitionManager::GetEquipmentSetData (uint32_t id)
Get the equipment set information corresponding to an ID.
Parameters
id Equipment set ID to retrieve
Returns
Pointer to the matching equipment set information, null if it does not exist
Definition at line 356 of file DefinitionManager.cpp.
References GetRecordByID(), and mEquipmentSetData.
Referenced by GetEquipmentSetDataByItem().
std::list< std::shared_ptr< objects::MiEquipmentSetData > > DefinitionManager::GetEquipmentSetDataByItem (uint32_t equipmentID)
Get the equipment set information corresponding to a piece of equipment in the set.
Parameters
equipmentID Equipment ID to retrieve sets for
Returns
List of pointers to the matching equipment set information
Definition at line 362 of file DefinitionManager.cpp.
References GetEquipmentSetData(), and mEquipmentSetLookup.
const std::shared_ptr< objects::MiExchangeData > DefinitionManager::GetExchangeData (uint32_t id)
Get the item exchange data corresponding to an ID.
Parameters
id Exchange ID to retrieve
Returns
Pointer to the matching item exchange information, null if it does not exist
Definition at line 383 of file DefinitionManager.cpp.
References GetRecordByID(), and mExchangeData.
const std::shared_ptr< objects::MiExpertData > DefinitionManager::GetExpertClassData (uint32_t id)
Get the character expertise information corresponding to an ID.
Parameters
id Expertise ID to retrieve
Returns
Pointer to the matching character expertise information, null if it does not exist
Definition at line 389 of file DefinitionManager.cpp.
References GetRecordByID(), and mExpertData.
std::set< uint32_t > DefinitionManager::GetFunctionIDSkills (uint16_t fid) const
Get all skill definition IDs that are mapped to the supplied function ID.
Parameters
fid Skill function ID
Returns
Set of skill definition IDs
Definition at line 613 of file DefinitionManager.cpp.
References mFunctionIDSkills.
const std::list< std::pair< uint8_t, uint32_t > > DefinitionManager::GetFusionRanges (uint8_t raceID)
Get the list of fusion range level and demon ID pairs associated to the supplied demon race.
Parameters
raceID Demon race ID
Returns
List of maximum fusion range level (key) and demon ID (value) pairs
Definition at line 395 of file DefinitionManager.cpp.
References mFusionRanges.
const std::shared_ptr< objects::MiGuardianAssistData > DefinitionManager::GetGuardianAssistData (uint32_t id)
Get the guardian assist information corresponding to an ID.
Parameters
id Guardian assist ID to retrieve
Returns
Pointer to the matching guardian assist information, null if it does not exist
Definition at line 407 of file DefinitionManager.cpp.
References GetRecordByID(), and mGuardianAssistData.
const std::shared_ptr< objects::MiGuardianLevelData > DefinitionManager::GetGuardianLevelData (uint32_t id)
Get the guardian level information corresponding to an ID.
Parameters
id Guardian level ID to retrieve
Returns
Pointer to the matching guardian level information, null if it does not exist
Definition at line 428 of file DefinitionManager.cpp.
References GetRecordByID(), and mGuardianLevelData.
const std::set< uint8_t > DefinitionManager::GetGuardianRaceIDs ()
Get all guardian race IDs with defined level information.
Returns
Set of all guardian race IDs
Definition at line 412 of file DefinitionManager.cpp.
References mGuardianLevelData.
const std::shared_ptr< objects::MiGuardianSpecialData > DefinitionManager::GetGuardianSpecialData (uint32_t id)
Get the guardian special information corresponding to an ID.
Parameters
id Guardian special ID to retrieve
Returns
Pointer to the matching guardian special information, null if it does not exist
Definition at line 434 of file DefinitionManager.cpp.
References GetRecordByID(), and mGuardianSpecialData.
const std::shared_ptr< objects::MiGuardianUnlockData > DefinitionManager::GetGuardianUnlockData (uint32_t id)
Get the guardian unlock information corresponding to an ID.
Parameters
id Guardian unlock ID to retrieve
Returns
Pointer to the matching guardian unlock information, null if it does not exist
Definition at line 440 of file DefinitionManager.cpp.
References GetRecordByID(), and mGuardianUnlockData.
const std::shared_ptr< objects::MiHNPCData > DefinitionManager::GetHNPCData (uint32_t id)
Get the human NPC definition corresponding to an ID.
Parameters
id Human NPC ID to retrieve
Returns
Pointer to the matching human NPC definition, null if it does not exist
Definition at line 446 of file DefinitionManager.cpp.
References GetRecordByID(), and mHNPCData.
const std::shared_ptr< objects::MiItemData > DefinitionManager::GetItemData (uint32_t id)
Get the item definition corresponding to an ID.
Parameters
id Item ID to retrieve
Returns
Pointer to the matching item definition, null if it does not exist
Definition at line 452 of file DefinitionManager.cpp.
References GetRecordByID(), and mItemData.
const std::shared_ptr< objects::MiItemData > DefinitionManager::GetItemData (const libcomp::String & name)
Get the item definition corresponding to a name.
Parameters
name Item name to retrieve
Returns
Pointer to the matching item definition, null if it does not exist
Definition at line 548 of file DefinitionManager.cpp.
References GetRecordByID(), mCItemNameLookup, and mItemData.
const std::shared_ptr< objects::MiMissionData > DefinitionManager::GetMissionData (uint32_t id)
Get the mission definition corresponding to an ID.
Parameters
id Mission ID to retrieve
Returns
Pointer to the matching mission definition, null if it does not exist
Definition at line 458 of file DefinitionManager.cpp.
References GetRecordByID(), and mMissionData.
const std::shared_ptr< objects::MiMitamaReunionBonusData > DefinitionManager::GetMitamaReunionBonusData (uint32_t id)
Get the mitama reunion bonus definition corresponding to an ID.
Parameters
id Mitama reunion bonus ID to retrieve
Returns
Pointer to the matching mitama reunion bonus definition, null if it does not exist
Definition at line 464 of file DefinitionManager.cpp.
References GetRecordByID(), and mMitamaReunionBonusData.
std::unordered_map< uint32_t, std::shared_ptr< objects::MiMitamaReunionSetBonusData > > DefinitionManager::GetMitamaReunionSetBonusData ()
Get all mitama reunion set bonus definitions by ID.
Returns
Mitama reunion set bonus definitions by ID
Definition at line 471 of file DefinitionManager.cpp.
References mMitamaReunionSetBonusData.
const std::shared_ptr< objects::MiMitamaUnionBonusData > DefinitionManager::GetMitamaUnionBonusData (uint32_t id)
Get the mitama union bonus definition corresponding to an ID.
Parameters
id Mitama union bonus ID to retrieve
Returns
Pointer to the matching mitama union bonus definition, null if it does not exist
Definition at line 477 of file DefinitionManager.cpp.
References GetRecordByID(), and mMitamaUnionBonusData.
const std::shared_ptr< objects::MiModificationData > DefinitionManager::GetModificationData (uint32_t id)
Get the item modification definition corresponding to an ID.
Parameters
id Item modification ID to retrieve
Returns
Pointer to the matching item modification definition, null if it does not exist
Definition at line 483 of file DefinitionManager.cpp.
References GetRecordByID(), and mModificationData.
const std::shared_ptr< objects::MiModificationData > DefinitionManager::GetModificationDataByItemID (uint32_t itemID)
Get the item modification definition corresponding to an item ID.
Parameters
itemID Item ID to retrieve the modification from
Returns
Pointer to the matching item modification definition, null if it does not exist
Definition at line 489 of file DefinitionManager.cpp.
References GetRecordByID(), mModificationData, and mModificationLookup.
const std::shared_ptr< objects::MiModificationExtEffectData > DefinitionManager::GetModificationExtEffectData (uint8_t groupID, uint8_t slot, uint16_t subID)
Get the item modification extra effect definition corresponding to a group ID, slot and subID.
Parameters
groupID Item modification extra effect groupID
groupID Item modification extra effect slot
groupID Item modification extra effect subID
Returns
Pointer to the matching item modification extra effect definition, null if it does not exist
Definition at line 501 of file DefinitionManager.cpp.
References GetRecordByID(), and mModificationExtEffectData.
const std::shared_ptr< objects::MiModificationExtRecipeData > DefinitionManager::GetModificationExtRecipeData (uint32_t id)
Get the item modification extra recipe definition corresponding to an ID.
Parameters
id Item modification extra recipe ID to retrieve
Returns
Pointer to the matching item modification extra recipe definition, null if it does not exist
Definition at line 518 of file DefinitionManager.cpp.
References GetRecordByID(), and mModificationExtRecipeData.
const std::shared_ptr< objects::MiModificationExtRecipeData > DefinitionManager::GetModificationExtRecipeDataByItemID (uint32_t itemID)
Get the item modification extra recipe definition corresponding to an item ID.
Parameters
itemID Item ID to retrieve the modification from
Returns
Pointer to the matching item modification extra recipe definition, null if it does not exist
Definition at line 524 of file DefinitionManager.cpp.
References GetRecordByID(), mModificationExtRecipeData, and mModificationExtRecipeLookup.
const std::shared_ptr< objects::MiModificationTriggerData > DefinitionManager::GetModificationTriggerData (uint16_t id)
Get the item modification trigger definition corresponding to an ID.
Parameters
id Item modification trigger ID to retrieve
Returns
Pointer to the matching item modification trigger definition, null if it does not exist
Definition at line 536 of file DefinitionManager.cpp.
References GetRecordByID(), and mModificationTriggerData.
const std::shared_ptr< objects::MiModifiedEffectData > DefinitionManager::GetModifiedEffectData (uint16_t id)
Get the item modification effect definition corresponding to an ID.
Parameters
id Item modification effect ID to retrieve
Returns
Pointer to the matching item modification effect definition, null if it does not exist
Definition at line 542 of file DefinitionManager.cpp.
References GetRecordByID(), and mModifiedEffectData.
const std::shared_ptr< objects::MiNPCBarterConditionData > DefinitionManager::GetNPCBarterConditionData (uint16_t id)
Get the NPC barter condition definition corresponding to an ID.
Parameters
id NPC barter condition ID to retrieve
Returns
Pointer to the matching NPC barter condition definition, null if it does not exist
Definition at line 566 of file DefinitionManager.cpp.
References GetRecordByID(), and mNPCBarterConditionData.
const std::shared_ptr< objects::MiNPCBarterData > DefinitionManager::GetNPCBarterData (uint16_t id)
Get the NPC barter definition corresponding to an ID.
Parameters
id NPC barter ID to retrieve
Returns
Pointer to the matching NPC barer definition, null if it does not exist
Definition at line 560 of file DefinitionManager.cpp.
References GetRecordByID(), and mNPCBarterData.
const std::shared_ptr< objects::MiNPCBarterGroupData > DefinitionManager::GetNPCBarterGroupData (uint16_t id)
Get the NPC barter group definition corresponding to an ID.
Parameters
id NPC barter group ID to retrieve
Returns
Pointer to the matching NPC barer group definition, null if it does not exist
Definition at line 572 of file DefinitionManager.cpp.
References GetRecordByID(), and mNPCBarterGroupData.
const std::shared_ptr< objects::MiONPCData > DefinitionManager::GetONPCData (uint32_t id)
Get the server object NPC definition corresponding to an ID.
Parameters
id Server object NPC ID to retrieve
Returns
Pointer to the matching server object NPC definition, null if it does not exist
Definition at line 578 of file DefinitionManager.cpp.
References GetRecordByID(), and mONPCData.
const std::shared_ptr< objects::MiQuestBonusCodeData > DefinitionManager::GetQuestBonusCodeData (uint32_t id)
Get the quest bonus code definition corresponding to an ID.
Parameters
id Quest bonus codeID to retrieve
Returns
Pointer to the matching quest bonus code, null if it does not exist
Definition at line 584 of file DefinitionManager.cpp.
References GetRecordByID(), and mQuestBonusCodeData.
const std::shared_ptr< objects::MiQuestData > DefinitionManager::GetQuestData (uint32_t id)
Get the quest definition corresponding to an ID.
Parameters
id Quest ID to retrieve
Returns
Pointer to the matching quest, null if it does not exist
Definition at line 590 of file DefinitionManager.cpp.
References GetRecordByID(), and mQuestData.
template<class X , class T > std::shared_ptr<T> libcomp::DefinitionManager::GetRecordByID (X id, std::unordered_map< X, std::shared_ptr< T >> & data) inline private
Utility function to pull the templated type from a standard definition map of ID to a pointer of that type.
Parameters
id ID of the definition to retrieve from the map
data Map to retrieve the data from
Returns
Pointer to the record in the map matching the supplied ID, null if it does not exist
Definition at line 978 of file DefinitionManager.h.
Referenced by GetAIData(), GetBlendData(), GetBlendExtData(), GetCultureItemData(), GetDevilBookData(), GetDevilBoostData(), GetDevilBoostExtraData(), GetDevilBoostItemData(), GetDevilData(), GetDevilEquipmentData(), GetDevilEquipmentItemData(), GetDevilFusionData(), GetDevilLVUpRateData(), GetDisassemblyData(), GetDisassemblyDataByItemID(), GetDisassemblyTriggerData(), GetDynamicMapData(), GetEnchantData(), GetEnchantSetData(), GetEnchantSpecialData(), GetEquipmentSetData(), GetExchangeData(), GetExpertClassData(), GetGuardianAssistData(), GetGuardianLevelData(), GetGuardianSpecialData(), GetGuardianUnlockData(), GetHNPCData(), GetItemData(), GetMissionData(), GetMitamaReunionBonusData(), GetMitamaUnionBonusData(), GetModificationData(), GetModificationDataByItemID(), GetModificationExtEffectData(), GetModificationExtRecipeData(), GetModificationExtRecipeDataByItemID(), GetModificationTriggerData(), GetModifiedEffectData(), GetNPCBarterConditionData(), GetNPCBarterData(), GetNPCBarterGroupData(), GetONPCData(), GetQuestBonusCodeData(), GetQuestData(), GetShopProductData(), GetSkillData(), GetSStatusData(), GetStatusData(), GetSynthesisData(), GetTimeLimitData(), GetTitleData(), GetTokuseiData(), GetUraFieldTowerData(), GetWarpPointData(), and GetZoneData().
const std::shared_ptr< objects::MiShopProductData > DefinitionManager::GetShopProductData (uint32_t id)
Get the shop product definition corresponding to an ID.
Parameters
id Shop product ID to retrieve
Returns
Pointer to the matching shop product definition, null if it does not exist
Definition at line 596 of file DefinitionManager.cpp.
References GetRecordByID(), and mShopProductData.
std::set< int32_t > DefinitionManager::GetSItemTokusei (uint32_t id)
Get the s-item tokusei IDs corresponding to an item ID.
Parameters
id Item ID to retrieve
Returns
Set of tokusei mapped to the supplied item ID
Definition at line 601 of file DefinitionManager.cpp.
References mSItemTokusei.
const std::shared_ptr< objects::MiSkillData > DefinitionManager::GetSkillData (uint32_t id)
Get the skill definition corresponding to an ID.
Parameters
id Skill ID to retrieve
Returns
Pointer to the matching skill definition, null if it does not exist
Definition at line 608 of file DefinitionManager.cpp.
References GetRecordByID(), and mSkillData.
const std::unordered_map< uint32_t, std::shared_ptr< objects::MiSpotData > > DefinitionManager::GetSpotData (uint32_t dynamicMapID)
Get the spot data corresponding to a dynamic map ID.
Parameters
dynamicMapID ID of the spot data to retrieve
Returns
Map of spot definitions by spot ID for the specified dynamic map
Definition at line 620 of file DefinitionManager.cpp.
References GetDynamicMapData(), and mSpotData.
const std::shared_ptr< objects::MiSStatusData > DefinitionManager::GetSStatusData (uint32_t id)
Get the s-status definition corresponding to an ID.
Parameters
id S-status ID to retrieve
Returns
Pointer to the matching s-status definition, null if it does not exist
Definition at line 640 of file DefinitionManager.cpp.
References GetRecordByID(), and mSStatusData.
const std::shared_ptr< objects::MiStatusData > DefinitionManager::GetStatusData (uint32_t id)
Get the status definition corresponding to an ID.
Parameters
id Status ID to retrieve
Returns
Pointer to the matching status definition, null if it does not exist
Definition at line 646 of file DefinitionManager.cpp.
References GetRecordByID(), and mStatusData.
const std::shared_ptr< objects::MiSynthesisData > DefinitionManager::GetSynthesisData (uint32_t id)
Get the synthesis definition corresponding to an ID.
Parameters
id Synthesis ID to retrieve
Returns
Pointer to the matching synthesis definition, null if it does not exist
Definition at line 652 of file DefinitionManager.cpp.
References GetRecordByID(), and mSynthesisData.
std::unordered_map< uint32_t, std::shared_ptr< objects::MiTankData > > DefinitionManager::GetTankData ()
Get the map of all material tank item definitions by ID.
Returns
Map of pointers to material tank item definitions by ID
Definition at line 664 of file DefinitionManager.cpp.
References mTankData.
const std::shared_ptr< objects::MiTimeLimitData > DefinitionManager::GetTimeLimitData (uint32_t id)
Get the time limit definition corresponding to an ID.
Parameters
id Time limit ID to retrieve
Returns
Pointer to the matching time limit definition, null if it does not exist
Definition at line 670 of file DefinitionManager.cpp.
References GetRecordByID(), and mTimeLimitData.
const std::shared_ptr< objects::MiTitleData > DefinitionManager::GetTitleData (int16_t id)
Get the title definition corresponding to an ID.
Parameters
id Title ID to retrieve
Returns
Pointer to the matching title definition, null if it does not exist
Definition at line 676 of file DefinitionManager.cpp.
References GetRecordByID(), and mTitleData.
std::set< int16_t > DefinitionManager::GetTitleIDs ()
Get the set of all (non-special) title IDs.
Returns
Set of title IDs
Definition at line 681 of file DefinitionManager.cpp.
References mTitleIDs.
const std::shared_ptr< objects::Tokusei > DefinitionManager::GetTokuseiData (int32_t id)
Get a tokusei by definition ID.
Parameters
id Definition ID of a tokusei to load
Returns
Pointer to the tokusei matching the specified id
Definition at line 806 of file DefinitionManager.cpp.
References GetRecordByID(), and mTokuseiData.
const std::list< std::shared_ptr< objects::MiTriUnionSpecialData > > DefinitionManager::GetTriUnionSpecialData (uint32_t sourceDemonTypeID)
Get the list of pointers to special fusion definitions by the ID of a source demon involved.
Parameters
sourceDemonTypeID ID of a source demon for the special fusion
Returns
List of pointers to special fusion definitions
Definition at line 687 of file DefinitionManager.cpp.
References GetDevilData(), mTriUnionSpecialData, and mTriUnionSpecialDataBySourceID.
const std::shared_ptr< objects::MiUraFieldTowerData > DefinitionManager::GetUraFieldTowerData (uint32_t dungeonID, uint32_t id)
Get the (Diaspora) ura field tower corresponding to an ID.
Parameters
id Ura field tower ID to retrieve
Returns
Pointer to the matching ura field tower information, null if it does not exist
Definition at line 722 of file DefinitionManager.cpp.
References GetRecordByID(), and mUraFieldTowerData.
const std::shared_ptr< objects::MiWarpPointData > DefinitionManager::GetWarpPointData (uint32_t id)
Get the warp point corresponding to an ID.
Parameters
id Warp point ID to retrieve
Returns
Pointer to the matching warp point information, null if it does not exist
Definition at line 734 of file DefinitionManager.cpp.
References GetRecordByID(), and mWarpPointData.
const std::shared_ptr< objects::MiZoneData > DefinitionManager::GetZoneData (uint32_t id)
Get the zone definition corresponding to an ID.
Parameters
id Zone ID to retrieve
Returns
Pointer to the matching zone definition, null if it does not exist
Definition at line 740 of file DefinitionManager.cpp.
References GetRecordByID(), and mZoneData.
Referenced by libcomp::ServerDataManager::VerifyPvPInstance().
bool DefinitionManager::LoadAllData (DataStore * pDataStore)
Load all binary data definitions.
Parameters
pDataStore Pointer to the datastore to load binary files from
Returns
true on success, false on failure
Definition at line 1880 of file DefinitionManager.cpp.
Referenced by libcomp::ScriptEngine::Using().
template<class T > bool libcomp::DefinitionManager::LoadBinaryData (DataStore * pDataStore, const libcomp::String & binaryFile, bool decrypt, uint16_t tablesExpected, std::list< std::shared_ptr< T >> & records, bool printResults = true) inline private
Load a binary file from the specified data store location.
Parameters
pDataStore Pointer to a data store location to check for the file
binaryFile Relative file path to a binary file
decrypt true if the file is encrypted and must be decrypted first, false if it can just be loaded
tablesExpected Number of tables expected in the file format
records Output list to load records into
printResults Optional parameter to disable success/fail debug messages
Returns
true if the file was loaded, false if it was not
Definition at line 869 of file DefinitionManager.h.
References libcomp::DataStore::DecryptFile(), libcomp::ObjectInStream::dynamicSizes, LoadBinaryDataHeader(), PrintLoadResult(), libcomp::DataStore::ReadFile(), and libcomp::ObjectInStream::stream.
bool DefinitionManager::LoadBinaryDataHeader (libcomp::ObjectInStream & ois, const libcomp::String & binaryFile, uint16_t tablesExpected, uint16_t & entryCount, uint16_t & tableCount) private
Load the data header containing the number of entries and tables that make up the format of the rest of the file.
Parameters
ois Binary stream of the file's contents
binaryFile Relative file path to a binary file
tablesExpected Number of tables expected in the file format. If this number does not match the tableCount result an error will be printed and will result in failure.
entryCount Output param containing the number of individual records contained in the file
tableCount Output param containing the number of dynamically sized "table" data members for each entry
Returns
true if the data header was read, false if it failed
Definition at line 2096 of file DefinitionManager.cpp.
References libcomp::String::Arg(), and libcomp::ObjectInStream::stream.
Referenced by LoadBinaryData().
template<class T > bool libcomp::DefinitionManager::LoadData (DataStore * pDataStore)
Load the binary data definitions of the specified type.
Parameters
pDataStore Pointer to the datastore to load binary file from
Returns
true on success, false on failure
std::shared_ptr< objects::QmpFile > DefinitionManager::LoadQmpFile (const libcomp::String & fileName, DataStore * pDataStore)
Load the QMP file with the specified filename from the supplied datastore.
Unlike other "load" functions on the manager, this information is not cached.
Parameters
fileName Name of the QMP file to load, including the file extension
pDataStore Pointer to the datastore to load file from
Returns
Pointer to the structure holding the parsed file information or null on failure
Definition at line 2066 of file DefinitionManager.cpp.
References libcomp::DataStore::ReadFile().
void DefinitionManager::PrintLoadResult (const libcomp::String & binaryFile, bool success, uint16_t entriesExpected, size_t loadedEntries) private
Utility function to print the result of loading a binary file.
Parameters
binaryFile Relative file path to a binary file
success true if the load succeeded, false if it failed
entriesExpected Number of entries that were supposed to be in the file according to the data header
loadedEntries NUmber of entries successfully loaded
Definition at line 2126 of file DefinitionManager.cpp.
References libcomp::String::Arg().
Referenced by LoadBinaryData().
template<class T > bool libcomp::DefinitionManager::RegisterServerSideDefinition (const std::shared_ptr< T > & record)
Register a server side definition into the manager from an external source.
Parameters
record Pointer to the record of the templated type
Returns
true if the record was registered successfully, false if it was not
Member Data Documentation
std::unordered_map<uint32_t, std::shared_ptr<objects::MiAIData> > libcomp::DefinitionManager::mAIData private
Map of client-side AI definitions by ID.
Definition at line 992 of file DefinitionManager.h.
Referenced by GetAIData().
std::unordered_map<uint32_t, std::shared_ptr<objects::MiBlendData> > libcomp::DefinitionManager::mBlendData private
Map of item mixing definitions by ID.
Definition at line 996 of file DefinitionManager.h.
Referenced by GetBlendData().
std::unordered_map<uint32_t, std::shared_ptr<objects::MiBlendExtData> > libcomp::DefinitionManager::mBlendExtData private
Map of item mixing extension definitions by ID.
Definition at line 1000 of file DefinitionManager.h.
Referenced by GetBlendExtData().
std::unordered_map<int8_t, std::shared_ptr<objects::MiCHouraiData> > libcomp::DefinitionManager::mCHouraiData private
Map of client-side hourai NPC definitions by ID.
Definition at line 1004 of file DefinitionManager.h.
Referenced by GetCHouraiData().
std::unordered_map<libcomp::String, uint32_t> libcomp::DefinitionManager::mCItemNameLookup private
Map of item names to IDs.
Definition at line 1011 of file DefinitionManager.h.
Referenced by GetItemData().
std::unordered_map<uint32_t, std::shared_ptr<objects::MiCultureItemData> > libcomp::DefinitionManager::mCultureItemData private
Map of culture item definitions by ID.
Definition at line 1008 of file DefinitionManager.h.
Referenced by GetCultureItemData().
std::unordered_map<uint32_t, std::shared_ptr<objects::MiDevilBookData> > libcomp::DefinitionManager::mDevilBookData private
Map of devil book definitions by ID.
Definition at line 1015 of file DefinitionManager.h.
Referenced by GetDevilBookData().
std::unordered_map<uint32_t, std::shared_ptr<objects::MiDevilBoostData> > libcomp::DefinitionManager::mDevilBoostData private
Map of devil boost definitions by ID.
Definition at line 1019 of file DefinitionManager.h.
Referenced by GetDevilBoostData().
std::unordered_map<uint16_t, std::shared_ptr<objects::MiDevilBoostExtraData> > libcomp::DefinitionManager::mDevilBoostExtraData private
Map of devil boost extra definitions by ID.
Definition at line 1023 of file DefinitionManager.h.
Referenced by GetDevilBoostExtraData().
std::unordered_map<uint32_t, std::shared_ptr<objects::MiDevilBoostItemData> > libcomp::DefinitionManager::mDevilBoostItemData private
Map of devil boost item definitions by ID.
Definition at line 1027 of file DefinitionManager.h.
Referenced by GetDevilBoostItemData().
std::unordered_map<int32_t, std::list<uint16_t> > libcomp::DefinitionManager::mDevilBoostLots private
Map of lot IDs to devil boost extra stack IDs in that lot.
Definition at line 1030 of file DefinitionManager.h.
Referenced by GetDevilBoostLotIDs().
std::unordered_map<uint32_t, std::shared_ptr<objects::MiDevilData> > libcomp::DefinitionManager::mDevilData private
Map of devil definitions by ID.
Definition at line 1034 of file DefinitionManager.h.
Referenced by GetDevilData().
std::unordered_map<uint32_t, std::shared_ptr<objects::MiDevilEquipmentData> > libcomp::DefinitionManager::mDevilEquipmentData private
Map of devil equipment definitions by skill ID.
Definition at line 1038 of file DefinitionManager.h.
Referenced by GetDevilEquipmentData().
std::unordered_map<uint32_t, std::shared_ptr< objects::MiDevilEquipmentItemData> > libcomp::DefinitionManager::mDevilEquipmentItemData private
Map of devil equipment definitions by item ID.
Definition at line 1042 of file DefinitionManager.h.
Referenced by GetDevilEquipmentItemData().
std::unordered_map<uint32_t, std::shared_ptr<objects::MiDevilFusionData> > libcomp::DefinitionManager::mDevilFusionData private
Map of devil fusion definitions by ID.
Definition at line 1046 of file DefinitionManager.h.
Referenced by GetDevilFusionData().
std::unordered_map<uint32_t, std::set<uint32_t> > libcomp::DefinitionManager::mDevilFusionLookup private
Map of devil fusion definition IDs mapped by demon IDs listed as explicit requirements for the skill.
Definition at line 1050 of file DefinitionManager.h.
Referenced by GetDevilFusionIDsByDemonID().
std::unordered_map<uint32_t, std::shared_ptr<objects::MiDevilLVUpRateData> > libcomp::DefinitionManager::mDevilLVUpRateData private
Map of devil level up information by growth type ID.
Definition at line 1057 of file DefinitionManager.h.
Referenced by GetAllDevilLVUpRateData(), and GetDevilLVUpRateData().
std::unordered_map<libcomp::String, uint32_t> libcomp::DefinitionManager::mDevilNameLookup private
Map of devil names to IDs which are NOT unique across entries.
Definition at line 1053 of file DefinitionManager.h.
Referenced by GetDevilData().
std::list<uint32_t> libcomp::DefinitionManager::mDisassembledItemIDs private
List of all disassembled item IDs (or "elements")
Definition at line 1071 of file DefinitionManager.h.
Referenced by GetDisassembledItemIDs().
std::unordered_map<uint32_t, std::shared_ptr<objects::MiDisassemblyData> > libcomp::DefinitionManager::mDisassemblyData private
Map of item disassembly definitions by ID.
Definition at line 1061 of file DefinitionManager.h.
Referenced by GetDisassemblyData(), and GetDisassemblyDataByItemID().
std::unordered_map<uint32_t, uint32_t> libcomp::DefinitionManager::mDisassemblyLookup private
Map of item disassembly definition IDs by item ID.
Definition at line 1064 of file DefinitionManager.h.
Referenced by GetDisassemblyDataByItemID().
std::unordered_map<uint32_t, std::shared_ptr<objects::MiDisassemblyTriggerData> > libcomp::DefinitionManager::mDisassemblyTriggerData private
Map of item disassembly trigger definitions by ID.
Definition at line 1068 of file DefinitionManager.h.
Referenced by GetDisassemblyTriggerData().
std::unordered_map<uint32_t, std::shared_ptr<objects::MiDynamicMapData> > libcomp::DefinitionManager::mDynamicMapData private
Map of dynamic map information by ID.
Definition at line 1075 of file DefinitionManager.h.
Referenced by GetDynamicMapData().
std::unordered_map<int16_t, std::shared_ptr<objects::MiEnchantData> > libcomp::DefinitionManager::mEnchantData private
Map of enchantment definitions by ID.
Definition at line 1079 of file DefinitionManager.h.
Referenced by GetAllEnchantData(), and GetEnchantData().
std::unordered_map<uint32_t, int16_t> libcomp::DefinitionManager::mEnchantDemonLookup private
Map of enchantment IDs by demon ID.
Definition at line 1082 of file DefinitionManager.h.
Referenced by GetEnchantDataByDemonID().
std::unordered_map<uint32_t, int16_t> libcomp::DefinitionManager::mEnchantItemLookup private
Map of enchantment IDs by item ID.
Definition at line 1085 of file DefinitionManager.h.
Referenced by GetEnchantDataByItemID().
std::unordered_map<uint32_t, std::shared_ptr<objects::EnchantSetData> > libcomp::DefinitionManager::mEnchantSetData private
Map of enchant set definitions by ID.
Definition at line 1266 of file DefinitionManager.h.
Referenced by GetAllEnchantSetData(), and GetEnchantSetData().
std::unordered_map<int16_t, std::list<uint32_t> > libcomp::DefinitionManager::mEnchantSetLookup private
Map of enchant set definition IDs by effect ID.
Definition at line 1269 of file DefinitionManager.h.
Referenced by GetEnchantSetDataByEffect().
std::unordered_map<uint32_t, std::shared_ptr<objects::EnchantSpecialData> > libcomp::DefinitionManager::mEnchantSpecialData private
Map of enchant special definitions by ID.
Definition at line 1273 of file DefinitionManager.h.
Referenced by GetEnchantSpecialData().
std::unordered_map<uint32_t, std::list<uint32_t> > libcomp::DefinitionManager::mEnchantSpecialLookup private
Map of enchant special definition IDs by input item ID.
Definition at line 1276 of file DefinitionManager.h.
Referenced by GetEnchantSpecialDataByInputItem().
std::unordered_map<uint32_t, std::shared_ptr<objects::MiEquipmentSetData> > libcomp::DefinitionManager::mEquipmentSetData private
Map of equipment set information by ID.
Definition at line 1089 of file DefinitionManager.h.
Referenced by GetEquipmentSetData().
std::unordered_map<uint32_t, std::list<uint32_t> > libcomp::DefinitionManager::mEquipmentSetLookup private
Map of equipment IDs to set IDs they belong to.
Definition at line 1092 of file DefinitionManager.h.
Referenced by GetEquipmentSetDataByItem().
std::unordered_map<uint32_t, std::shared_ptr<objects::MiExchangeData> > libcomp::DefinitionManager::mExchangeData private
Map of item exchange data by ID.
Definition at line 1096 of file DefinitionManager.h.
Referenced by GetExchangeData().
std::unordered_map<uint32_t, std::shared_ptr<objects::MiExpertData> > libcomp::DefinitionManager::mExpertData private
Map of character expertise information by ID.
Definition at line 1100 of file DefinitionManager.h.
Referenced by GetExpertClassData().
std::unordered_map<uint16_t, std::set<uint32_t> > libcomp::DefinitionManager::mFunctionIDSkills private
Map of skill function IDs to skill IDs.
Definition at line 1211 of file DefinitionManager.h.
Referenced by GetFunctionIDSkills().
std::unordered_map<uint8_t, std::list<std::pair<uint8_t, uint32_t> > > libcomp::DefinitionManager::mFusionRanges private
Map of demon race IDs to maximum fusion range levels paired with their corresponding result demon.
Definition at line 1105 of file DefinitionManager.h.
Referenced by GetFusionRanges().
std::unordered_map<uint32_t, std::shared_ptr<objects::MiGuardianAssistData> > libcomp::DefinitionManager::mGuardianAssistData private
Map of digitalize "guardian assist" information by ID.
Definition at line 1109 of file DefinitionManager.h.
Referenced by GetGuardianAssistData().
std::unordered_map<uint32_t, std::shared_ptr<objects::MiGuardianLevelData> > libcomp::DefinitionManager::mGuardianLevelData private
Map of digitalize "guardian level" information by ID.
Definition at line 1113 of file DefinitionManager.h.
Referenced by GetGuardianLevelData(), and GetGuardianRaceIDs().
std::unordered_map<uint32_t, std::shared_ptr<objects::MiGuardianSpecialData> > libcomp::DefinitionManager::mGuardianSpecialData private
Map of digitalize "guardian special" information by ID.
Definition at line 1117 of file DefinitionManager.h.
Referenced by GetGuardianSpecialData().
std::unordered_map<uint32_t, std::shared_ptr<objects::MiGuardianUnlockData> > libcomp::DefinitionManager::mGuardianUnlockData private
Map of digitalize "guardian unlock" information by ID.
Definition at line 1121 of file DefinitionManager.h.
Referenced by GetGuardianUnlockData().
std::unordered_map<uint32_t, std::shared_ptr<objects::MiHNPCData> > libcomp::DefinitionManager::mHNPCData private
Map of human NPC definitions by ID.
Definition at line 1125 of file DefinitionManager.h.
Referenced by GetHNPCData().
std::unordered_map<uint32_t, std::shared_ptr<objects::MiItemData> > libcomp::DefinitionManager::mItemData private
Map of item definitions by ID.
Definition at line 1129 of file DefinitionManager.h.
Referenced by GetItemData().
std::unordered_map<uint32_t, std::shared_ptr<objects::MiMissionData> > libcomp::DefinitionManager::mMissionData private
Map of mission definitions by ID.
Definition at line 1133 of file DefinitionManager.h.
Referenced by GetMissionData().
std::unordered_map<uint32_t, std::shared_ptr< objects::MiMitamaReunionBonusData> > libcomp::DefinitionManager::mMitamaReunionBonusData private
Map of mitama reunion bonus definitions by ID.
Definition at line 1137 of file DefinitionManager.h.
Referenced by GetMitamaReunionBonusData().
std::unordered_map<uint32_t, std::shared_ptr< objects::MiMitamaReunionSetBonusData> > libcomp::DefinitionManager::mMitamaReunionSetBonusData private
Map of mitama reunion set bonus definitions by ID.
Definition at line 1141 of file DefinitionManager.h.
Referenced by GetMitamaReunionSetBonusData().
std::unordered_map<uint32_t, std::shared_ptr< objects::MiMitamaUnionBonusData> > libcomp::DefinitionManager::mMitamaUnionBonusData private
Map of mitama union bonus definitions by ID.
Definition at line 1145 of file DefinitionManager.h.
Referenced by GetMitamaUnionBonusData().
std::unordered_map<uint32_t, std::shared_ptr<objects::MiModificationData> > libcomp::DefinitionManager::mModificationData private
Map of item modification definitions by ID.
Definition at line 1149 of file DefinitionManager.h.
Referenced by GetModificationData(), and GetModificationDataByItemID().
std::unordered_map<uint8_t, std::unordered_map<uint8_t, std::unordered_map<uint16_t, std::shared_ptr<objects::MiModificationExtEffectData> > > > libcomp::DefinitionManager::mModificationExtEffectData private
Map of item modification extra effect definitions by their group ID, slot then sub ID.
Because there are no unique IDs for this object, this is how the data must be identified.
Definition at line 1158 of file DefinitionManager.h.
Referenced by GetModificationExtEffectData().
std::unordered_map<uint32_t, std::shared_ptr<objects::MiModificationExtRecipeData> > libcomp::DefinitionManager::mModificationExtRecipeData private
Map of item modification extra recipe definitions by ID.
Definition at line 1162 of file DefinitionManager.h.
Referenced by GetModificationExtRecipeData(), and GetModificationExtRecipeDataByItemID().
std::unordered_map<uint32_t, uint32_t> libcomp::DefinitionManager::mModificationExtRecipeLookup private
Map of item modification extra recipe definition IDs by item ID.
Definition at line 1165 of file DefinitionManager.h.
Referenced by GetModificationExtRecipeDataByItemID().
std::unordered_map<uint32_t, uint32_t> libcomp::DefinitionManager::mModificationLookup private
Map of item modification definition IDs by item ID.
Definition at line 1152 of file DefinitionManager.h.
Referenced by GetModificationDataByItemID().
std::unordered_map<uint16_t, std::shared_ptr<objects::MiModificationTriggerData> > libcomp::DefinitionManager::mModificationTriggerData private
Map of item modification trigger definitions by ID.
Definition at line 1169 of file DefinitionManager.h.
Referenced by GetModificationTriggerData().
std::unordered_map<uint16_t, std::shared_ptr<objects::MiModifiedEffectData> > libcomp::DefinitionManager::mModifiedEffectData private
Map of item modification effect definitions by ID.
Definition at line 1173 of file DefinitionManager.h.
Referenced by GetModifiedEffectData().
std::unordered_map<uint16_t, std::shared_ptr< objects::MiNPCBarterConditionData> > libcomp::DefinitionManager::mNPCBarterConditionData private
Map of NPC barter condition definitions by ID.
Definition at line 1181 of file DefinitionManager.h.
Referenced by GetNPCBarterConditionData().
std::unordered_map<uint16_t, std::shared_ptr<objects::MiNPCBarterData> > libcomp::DefinitionManager::mNPCBarterData private
Map of NPC barter definitions by ID.
Definition at line 1177 of file DefinitionManager.h.
Referenced by GetNPCBarterData().
std::unordered_map<uint16_t, std::shared_ptr<objects::MiNPCBarterGroupData> > libcomp::DefinitionManager::mNPCBarterGroupData private
Map of NPC barter group definitions by ID.
Definition at line 1185 of file DefinitionManager.h.
Referenced by GetNPCBarterGroupData().
std::unordered_map<uint32_t, std::shared_ptr<objects::MiONPCData> > libcomp::DefinitionManager::mONPCData private
Map of server object NPC definitions by ID.
Definition at line 1189 of file DefinitionManager.h.
Referenced by GetONPCData().
std::unordered_map<uint32_t, std::shared_ptr<objects::MiQuestBonusCodeData> > libcomp::DefinitionManager::mQuestBonusCodeData private
Map of quest bonus code definitions by ID.
Definition at line 1193 of file DefinitionManager.h.
Referenced by GetQuestBonusCodeData().
std::unordered_map<uint32_t, std::shared_ptr<objects::MiQuestData> > libcomp::DefinitionManager::mQuestData private
Map of quest definitions by ID.
Definition at line 1197 of file DefinitionManager.h.
Referenced by GetQuestData().
std::unordered_map<uint32_t, std::shared_ptr<objects::MiShopProductData> > libcomp::DefinitionManager::mShopProductData private
Map of shop product definitions by ID.
Definition at line 1201 of file DefinitionManager.h.
Referenced by GetShopProductData().
std::unordered_map<uint32_t, std::set<int32_t> > libcomp::DefinitionManager::mSItemTokusei private
Map of s-item tokusei IDs by item ID.
Definition at line 1204 of file DefinitionManager.h.
Referenced by GetSItemTokusei().
std::unordered_map<uint32_t, std::shared_ptr<objects::MiSkillData> > libcomp::DefinitionManager::mSkillData private
Map of skill definitions by ID.
Definition at line 1208 of file DefinitionManager.h.
Referenced by GetSkillData().
std::unordered_map<std::string, std::unordered_map<uint32_t, std::shared_ptr<objects::MiSpotData> > > libcomp::DefinitionManager::mSpotData private
Map of filename to map of spots by ID.
Definition at line 1215 of file DefinitionManager.h.
Referenced by GetSpotData().
std::unordered_map<uint32_t, std::shared_ptr<objects::MiSStatusData> > libcomp::DefinitionManager::mSStatusData private
Map of s-status definitions by ID.
Definition at line 1219 of file DefinitionManager.h.
Referenced by GetSStatusData().
std::unordered_map<uint32_t, std::shared_ptr<objects::MiStatusData> > libcomp::DefinitionManager::mStatusData private
Map of status definitions by ID.
Definition at line 1223 of file DefinitionManager.h.
Referenced by GetStatusData().
std::unordered_map<uint32_t, std::shared_ptr<objects::MiSynthesisData> > libcomp::DefinitionManager::mSynthesisData private
Map of synthesis definitions by ID.
Definition at line 1227 of file DefinitionManager.h.
Referenced by GetAllSynthesisData(), and GetSynthesisData().
std::unordered_map<uint32_t, std::shared_ptr<objects::MiTankData> > libcomp::DefinitionManager::mTankData private
Map of material tank definitions by ID.
Definition at line 1231 of file DefinitionManager.h.
Referenced by GetTankData().
std::unordered_map<uint32_t, std::shared_ptr<objects::MiTimeLimitData> > libcomp::DefinitionManager::mTimeLimitData private
Map of time limit definitions by ID.
Definition at line 1235 of file DefinitionManager.h.
Referenced by GetTimeLimitData().
std::unordered_map<int16_t, std::shared_ptr<objects::MiTitleData> > libcomp::DefinitionManager::mTitleData private
Map of title definitions by ID.
Definition at line 1239 of file DefinitionManager.h.
Referenced by GetTitleData().
std::set<int16_t> libcomp::DefinitionManager::mTitleIDs private
Set of all (non-special) title IDs.
Definition at line 1242 of file DefinitionManager.h.
Referenced by GetTitleIDs().
std::unordered_map<int32_t, std::shared_ptr<objects::Tokusei> > libcomp::DefinitionManager::mTokuseiData private
Map of tokusei definitions by ID.
Definition at line 1280 of file DefinitionManager.h.
Referenced by GetAllTokuseiData(), and GetTokuseiData().
std::unordered_map<uint32_t, std::shared_ptr<objects::MiTriUnionSpecialData> > libcomp::DefinitionManager::mTriUnionSpecialData private
Map of special fusion definitions by ID.
Definition at line 1246 of file DefinitionManager.h.
Referenced by GetTriUnionSpecialData().
std::unordered_map<uint32_t, std::list<uint32_t> > libcomp::DefinitionManager::mTriUnionSpecialDataBySourceID private
Map of source demon IDs to special fusions they belong to.
Definition at line 1250 of file DefinitionManager.h.
Referenced by GetTriUnionSpecialData().
std::unordered_map<uint32_t, std::unordered_map<uint32_t, std::shared_ptr<objects::MiUraFieldTowerData> > > libcomp::DefinitionManager::mUraFieldTowerData private
Map of (Diaspora) ura field tower definitions by dungeon ID, then ID.
Definition at line 1254 of file DefinitionManager.h.
Referenced by GetUraFieldTowerData().
std::unordered_map<uint32_t, std::shared_ptr<objects::MiWarpPointData> > libcomp::DefinitionManager::mWarpPointData private
Map of warp point definitions by ID.
Definition at line 1258 of file DefinitionManager.h.
Referenced by GetWarpPointData().
std::unordered_map<uint32_t, std::shared_ptr<objects::MiZoneData> > libcomp::DefinitionManager::mZoneData private
Map of zone definitions by ID.
Definition at line 1262 of file DefinitionManager.h.
Referenced by GetZoneData().
The documentation for this class was generated from the following files:
DefinitionManager.h
DefinitionManager.cpp