COMP_hack: libcomp::ServerConstants Class Reference
libcomp::ServerConstants Class Reference
Static Accessor class for the initalization and retrieval of ServerConstants::Data.
#include <ServerConstants.h>
Classes
struct Data
Server side configurable constants data container.
Static Public Member Functions
static const Data & GetConstants ()
Get a constant reference to the server side constants data.
static bool Initialize (const String &filePath)
Initialize the server side constants from an XML file.
Static Private Member Functions
template<typename T >
static bool LoadDecimal (const std::string &value, T &prop)
Utility function to load a string from the constants read from the XML file and assign it to a decimal.
template<typename T >
static bool LoadInteger (const std::string &value, T &prop)
Utility function to load a string from the constants read from the XML file and assign it to an integer.
template<typename K , typename V >
static bool LoadIntegerMap (const std::unordered_map< std::string, std::string > &valueMap, std::unordered_map< K, V > &propMap)
Utility function to load a map of string to string pairs from the constants read from the XML file and convert to integer types.
static bool LoadKeyValueStrings (const tinyxml2::XMLElement *elem, std::unordered_map< std::string, std::string > &map)
Utility function to load key value string pairs from the constants read from the XML file.
static bool LoadString (const std::string &value, String &prop)
Utility function to load a string from the constants read from the XML file.
static bool LoadStringList (const tinyxml2::XMLElement *elem, std::list< String > &prop)
Utility function to load a list of strings from the constants read from the XML file.
template<typename T , std::size_t SIZE>
static bool ToIntegerArray (std::array< T, SIZE > &prop, std::list< String > values)
Utility function to load a list of strings into an array.
template<typename T >
static std::list< T > ToIntegerRange (const std::string &value, bool &success)
Utility function to load convert a string to a list of numeric ranges and return in a list.
template<typename T >
static bool ToIntegerSet (std::set< T > &prop, std::list< String > values)
Utility function to load a list of strings into a set.
Static Private Attributes
static Data sConstants = {}
Container for all server side constants.
Detailed Description
Static Accessor class for the initalization and retrieval of ServerConstants::Data.
Definition at line 51 of file ServerConstants.h.
Member Function Documentation
const ServerConstants::Data & ServerConstants::GetConstants () static
Get a constant reference to the server side constants data.
Returns
Reference to the server side constants data
Definition at line 1485 of file ServerConstants.cpp.
References sConstants.
bool ServerConstants::Initialize (const String & filePath) static
Initialize the server side constants from an XML file.
Parameters
filePath Path to the constants XML file
Returns
false if anything failed during initialization
Definition at line 45 of file ServerConstants.cpp.
References libcomp::ServerConstants::Data::ADJUSTMENT_ITEMS, libcomp::ServerConstants::Data::ADJUSTMENT_SKILLS, libcomp::ServerConstants::Data::API_ADMIN_LVL_CREATE_PROMO, libcomp::ServerConstants::Data::API_ADMIN_LVL_DELETE_ACCOUNT, libcomp::ServerConstants::Data::API_ADMIN_LVL_DELETE_PROMO, libcomp::ServerConstants::Data::API_ADMIN_LVL_GET_ACCOUNT, libcomp::ServerConstants::Data::API_ADMIN_LVL_GET_ACCOUNTS, libcomp::ServerConstants::Data::API_ADMIN_LVL_GET_PROMOS, libcomp::ServerConstants::Data::API_ADMIN_LVL_KICK_PLAYER, libcomp::ServerConstants::Data::API_ADMIN_LVL_MESSAGE_WORLD, libcomp::ServerConstants::Data::API_ADMIN_LVL_ONLINE, libcomp::ServerConstants::Data::API_ADMIN_LVL_POST_ITEMS, libcomp::ServerConstants::Data::API_ADMIN_LVL_UPDATE_ACCOUNT, libcomp::ServerConstants::Data::BARTER_COOLDOWNS, libcomp::String::C(), libcomp::ServerConstants::Data::CAMEO_MAP, libcomp::ServerConstants::Data::CLAN_FORM_MAP, libcomp::ServerConstants::Data::CLAN_LEVEL_SKILLS, libcomp::ServerConstants::Data::DEMON_BOOK_BONUS, libcomp::ServerConstants::Data::DEMON_CRYSTALS, libcomp::ServerConstants::Data::DEMON_FUSION_SKILLS, libcomp::ServerConstants::Data::DEMON_QUEST_XP, libcomp::ServerConstants::Data::DEPO_MAP_DEMON, libcomp::ServerConstants::Data::DEPO_MAP_ITEM, libcomp::ServerConstants::Data::DIGITALIZE_COOLDOWN, libcomp::ServerConstants::Data::DIGITALIZE_STAT_RATES, libcomp::ServerConstants::Data::ELEMENTAL_1_FLAEMIS, libcomp::ServerConstants::Data::ELEMENTAL_2_AQUANS, libcomp::ServerConstants::Data::ELEMENTAL_3_AEROS, libcomp::ServerConstants::Data::ELEMENTAL_4_ERTHYS, libcomp::ServerConstants::Data::EQUIP_MOD_EDIT_ITEMS, libcomp::ServerConstants::Data::FUSION_BOOST_SKILLS, libcomp::ServerConstants::Data::FUSION_BOOST_STATUSES, libcomp::ServerConstants::Data::GM_CMD_LVL_ADD_CP, libcomp::ServerConstants::Data::GM_CMD_LVL_ANNOUNCE, libcomp::ServerConstants::Data::GM_CMD_LVL_BAN, libcomp::ServerConstants::Data::GM_CMD_LVL_BATTLE_POINTS, libcomp::ServerConstants::Data::GM_CMD_LVL_BETHEL, libcomp::ServerConstants::Data::GM_CMD_LVL_COIN, libcomp::ServerConstants::Data::GM_CMD_LVL_CONTRACT, libcomp::ServerConstants::Data::GM_CMD_LVL_COUNTER, libcomp::ServerConstants::Data::GM_CMD_LVL_COWRIE, libcomp::ServerConstants::Data::GM_CMD_LVL_CRASH, libcomp::ServerConstants::Data::GM_CMD_LVL_DIGITALIZE_POINTS, libcomp::ServerConstants::Data::GM_CMD_LVL_EFFECT, libcomp::ServerConstants::Data::GM_CMD_LVL_ENCHANT, libcomp::ServerConstants::Data::GM_CMD_LVL_ENEMY, libcomp::ServerConstants::Data::GM_CMD_LVL_EVENT, libcomp::ServerConstants::Data::GM_CMD_LVL_EXPERTISE_EXTEND, libcomp::ServerConstants::Data::GM_CMD_LVL_EXPERTISE_SET, libcomp::ServerConstants::Data::GM_CMD_LVL_FAMILIARITY, libcomp::ServerConstants::Data::GM_CMD_LVL_FLAG, libcomp::ServerConstants::Data::GM_CMD_LVL_FUSION_GAUGE, libcomp::ServerConstants::Data::GM_CMD_LVL_GOTO, libcomp::ServerConstants::Data::GM_CMD_LVL_GRADE_POINTS, libcomp::ServerConstants::Data::GM_CMD_LVL_HELP, libcomp::ServerConstants::Data::GM_CMD_LVL_HOMEPOINT, libcomp::ServerConstants::Data::GM_CMD_LVL_INSTANCE, libcomp::ServerConstants::Data::GM_CMD_LVL_ITEM, libcomp::ServerConstants::Data::GM_CMD_LVL_KICK, libcomp::ServerConstants::Data::GM_CMD_LVL_KILL, libcomp::ServerConstants::Data::GM_CMD_LVL_LEVEL_UP, libcomp::ServerConstants::Data::GM_CMD_LVL_LNC, libcomp::ServerConstants::Data::GM_CMD_LVL_MAP, libcomp::ServerConstants::Data::GM_CMD_LVL_ONLINE, libcomp::ServerConstants::Data::GM_CMD_LVL_PENALTY_RESET, libcomp::ServerConstants::Data::GM_CMD_LVL_PLUGIN, libcomp::ServerConstants::Data::GM_CMD_LVL_POSITION, libcomp::ServerConstants::Data::GM_CMD_LVL_POST, libcomp::ServerConstants::Data::GM_CMD_LVL_QUEST, libcomp::ServerConstants::Data::GM_CMD_LVL_REPORTED, libcomp::ServerConstants::Data::GM_CMD_LVL_RESOLVE, libcomp::ServerConstants::Data::GM_CMD_LVL_REUNION, libcomp::ServerConstants::Data::GM_CMD_LVL_SCRAP, libcomp::ServerConstants::Data::GM_CMD_LVL_SKILL, libcomp::ServerConstants::Data::GM_CMD_LVL_SKILL_POINT, libcomp::ServerConstants::Data::GM_CMD_LVL_SLOT_ADD, libcomp::ServerConstants::Data::GM_CMD_LVL_SOUL_POINTS, libcomp::ServerConstants::Data::GM_CMD_LVL_SPAWN, libcomp::ServerConstants::Data::GM_CMD_LVL_SPEED, libcomp::ServerConstants::Data::GM_CMD_LVL_SPIRIT, libcomp::ServerConstants::Data::GM_CMD_LVL_SUPPORT, libcomp::ServerConstants::Data::GM_CMD_LVL_TICKER_MESSAGE, libcomp::ServerConstants::Data::GM_CMD_LVL_TITLE, libcomp::ServerConstants::Data::GM_CMD_LVL_TOKUSEI, libcomp::ServerConstants::Data::GM_CMD_LVL_VALUABLE, libcomp::ServerConstants::Data::GM_CMD_LVL_WORLD_TIME, libcomp::ServerConstants::Data::GM_CMD_LVL_XP, libcomp::ServerConstants::Data::GM_CMD_LVL_ZIOTITE, libcomp::ServerConstants::Data::GM_CMD_LVL_ZONE, libcomp::ServerConstants::Data::ITEM_BALM_OF_LIFE, libcomp::ServerConstants::Data::ITEM_BALM_OF_LIFE_DEMON, libcomp::ServerConstants::Data::ITEM_KREUZ, libcomp::ServerConstants::Data::ITEM_MACCA, libcomp::ServerConstants::Data::ITEM_MACCA_NOTE, libcomp::ServerConstants::Data::ITEM_MAG_PRESSER, libcomp::ServerConstants::Data::ITEM_MAGNETITE, libcomp::ServerConstants::Data::ITEM_RBLOODSTONE, libcomp::ServerConstants::Data::LEVELUP_STATUSES, LoadInteger(), LoadIntegerMap(), LoadKeyValueStrings(), LoadString(), LoadStringList(), libcomp::ServerConstants::Data::MAX_MOVE_INCREASE_SUM, libcomp::ServerConstants::Data::MENU_BARTER, libcomp::ServerConstants::Data::MENU_BAZAAR, libcomp::ServerConstants::Data::MENU_COMP_SHOP, libcomp::ServerConstants::Data::MENU_CULTURE, libcomp::ServerConstants::Data::MENU_DEMON_DEPO, libcomp::ServerConstants::Data::MENU_FUSION_KZ, libcomp::ServerConstants::Data::MENU_ITEM_DEPO, libcomp::ServerConstants::Data::MENU_ITIME, libcomp::ServerConstants::Data::MENU_REPAIR_KZ, libcomp::ServerConstants::Data::MENU_SHOP_BUY, libcomp::ServerConstants::Data::MENU_SHOP_REPAIR, libcomp::ServerConstants::Data::MENU_SHOP_SELL, libcomp::ServerConstants::Data::MENU_TRIFUSION, libcomp::ServerConstants::Data::MENU_TRIFUSION_KZ, libcomp::ServerConstants::Data::MENU_UB_RANKING, libcomp::ServerConstants::Data::MENU_WEB_GAME, libcomp::ServerConstants::Data::MITAMA_1_ARAMITAMA, libcomp::ServerConstants::Data::MITAMA_2_NIGIMITAMA, libcomp::ServerConstants::Data::MITAMA_3_KUSHIMITAMA, libcomp::ServerConstants::Data::MITAMA_4_SAKIMITAMA, libcomp::ServerConstants::Data::MITAMA_SET_BOOST, libcomp::ServerConstants::Data::QUEST_BONUS, libcomp::ServerConstants::Data::RATE_SCALING_ITEMS, libcomp::ServerConstants::Data::REUNION_EXTRACT_ITEMS, libcomp::ServerConstants::Data::ROLLBACK_PG_ITEMS, sConstants, libcomp::ServerConstants::Data::SKILL_ABS_DAMAGE, libcomp::ServerConstants::Data::SKILL_CAMEO, libcomp::ServerConstants::Data::SKILL_CLAN_FORM, libcomp::ServerConstants::Data::SKILL_CLOAK, libcomp::ServerConstants::Data::SKILL_CULTURE_SLOT_UP, libcomp::ServerConstants::Data::SKILL_CULTURE_UP, libcomp::ServerConstants::Data::SKILL_DCM, libcomp::ServerConstants::Data::SKILL_DEMON_FUSION, libcomp::ServerConstants::Data::SKILL_DEMON_FUSION_EXECUTE, libcomp::ServerConstants::Data::SKILL_DESPAWN, libcomp::ServerConstants::Data::SKILL_DESUMMON, libcomp::ServerConstants::Data::SKILL_DIASPORA_QUAKE, libcomp::ServerConstants::Data::SKILL_DIGITALIZE, libcomp::ServerConstants::Data::SKILL_DIGITALIZE_BREAK, libcomp::ServerConstants::Data::SKILL_DIGITALIZE_CANCEL, libcomp::ServerConstants::Data::SKILL_DURABILITY_DOWN, libcomp::ServerConstants::Data::SKILL_EQUIP_ITEM, libcomp::ServerConstants::Data::SKILL_EQUIP_MOD_EDIT, libcomp::ServerConstants::Data::SKILL_ESTOMA, libcomp::ServerConstants::Data::SKILL_EXPERT_CLASS_DOWN, libcomp::ServerConstants::Data::SKILL_EXPERT_FORGET, libcomp::ServerConstants::Data::SKILL_EXPERT_FORGET_ALL, libcomp::ServerConstants::Data::SKILL_EXPERT_RANK_DOWN, libcomp::ServerConstants::Data::SKILL_FAM_UP, libcomp::ServerConstants::Data::SKILL_GEM_COST, libcomp::ServerConstants::Data::SKILL_GENDER_RESTRICTED, libcomp::ServerConstants::Data::SKILL_HP_DEPENDENT, libcomp::ServerConstants::Data::SKILL_HP_MP_MIN, libcomp::ServerConstants::Data::SKILL_ITEM_FAM_UP, libcomp::ServerConstants::Data::SKILL_LIBERAMA, libcomp::ServerConstants::Data::SKILL_LNC_DAMAGE, libcomp::ServerConstants::Data::SKILL_MAX_DURABILITY_FIXED, libcomp::ServerConstants::Data::SKILL_MAX_DURABILITY_RANDOM, libcomp::ServerConstants::Data::SKILL_MINION_DESPAWN, libcomp::ServerConstants::Data::SKILL_MINION_SPAWN, libcomp::ServerConstants::Data::SKILL_MOOCH, libcomp::ServerConstants::Data::SKILL_MOUNT, libcomp::ServerConstants::Data::SKILL_PIERCE, libcomp::ServerConstants::Data::SKILL_RANDOM_ITEM, libcomp::ServerConstants::Data::SKILL_RANDOMIZE, libcomp::ServerConstants::Data::SKILL_RESPEC, libcomp::ServerConstants::Data::SKILL_REST, libcomp::ServerConstants::Data::SKILL_SLEEP_RESTRICTED, libcomp::ServerConstants::Data::SKILL_SPAWN, libcomp::ServerConstants::Data::SKILL_SPAWN_ZONE, libcomp::ServerConstants::Data::SKILL_SPECIAL_REQUEST, libcomp::ServerConstants::Data::SKILL_STAT_SUM_DAMAGE, libcomp::ServerConstants::Data::SKILL_STATUS_DIRECT, libcomp::ServerConstants::Data::SKILL_STATUS_LIMITED, libcomp::ServerConstants::Data::SKILL_STATUS_RANDOM, libcomp::ServerConstants::Data::SKILL_STATUS_RANDOM2, libcomp::ServerConstants::Data::SKILL_STATUS_RESTRICTED, libcomp::ServerConstants::Data::SKILL_STATUS_SCALE, libcomp::ServerConstants::Data::SKILL_STORE_DEMON, libcomp::ServerConstants::Data::SKILL_SUICIDE, libcomp::ServerConstants::Data::SKILL_SUMMON_DEMON, libcomp::ServerConstants::Data::SKILL_TAUNT, libcomp::ServerConstants::Data::SKILL_TRAESTO, libcomp::ServerConstants::Data::SKILL_TRAESTO_ARCADIA, libcomp::ServerConstants::Data::SKILL_TRAESTO_DSHINJUKU, libcomp::ServerConstants::Data::SKILL_TRAESTO_KAKYOJO, libcomp::ServerConstants::Data::SKILL_TRAESTO_NAKANO_BDOMAIN, libcomp::ServerConstants::Data::SKILL_TRAESTO_SOUHONZAN, libcomp::ServerConstants::Data::SKILL_WARP, libcomp::ServerConstants::Data::SKILL_XP_PARTNER, libcomp::ServerConstants::Data::SKILL_XP_SELF, libcomp::ServerConstants::Data::SKILL_ZONE_RESTRICTED, libcomp::ServerConstants::Data::SKILL_ZONE_RESTRICTED_ITEM, libcomp::ServerConstants::Data::SKILL_ZONE_TARGET_ALL, libcomp::ServerConstants::Data::SPIRIT_FUSION_BOOST, libcomp::String::Split(), libcomp::ServerConstants::Data::STATUS_BIKE, libcomp::ServerConstants::Data::STATUS_CLOAK, libcomp::ServerConstants::Data::STATUS_COMP_TUNING, libcomp::ServerConstants::Data::STATUS_DEATH, libcomp::ServerConstants::Data::STATUS_DEMON_ONLY, libcomp::ServerConstants::Data::STATUS_DEMON_QUEST_ACTIVE, libcomp::ServerConstants::Data::STATUS_DIGITALIZE, libcomp::ServerConstants::Data::STATUS_DIGITALIZE_COOLDOWN, libcomp::ServerConstants::Data::STATUS_MOUNT, libcomp::ServerConstants::Data::STATUS_MOUNT_SUPER, libcomp::ServerConstants::Data::STATUS_REUNION_XP_SAVE, libcomp::ServerConstants::Data::STATUS_SLEEP, libcomp::ServerConstants::Data::STATUS_STEALTH, libcomp::ServerConstants::Data::STATUS_SUMMON_SYNC_1, libcomp::ServerConstants::Data::STATUS_SUMMON_SYNC_2, libcomp::ServerConstants::Data::STATUS_SUMMON_SYNC_3, libcomp::ServerConstants::Data::SYNTH_SKILLS, libcomp::ServerConstants::Data::TEAM_STATUS_COOLDOWN, libcomp::ServerConstants::Data::TEAM_VALUABLES, ToIntegerArray(), ToIntegerSet(), libcomp::ServerConstants::Data::TOKUSEI_BIKE_BOOST, libcomp::ServerConstants::Data::TOKUSEI_MAGIC_CONTROL_COST, libcomp::ServerConstants::Data::TRIFUSION_SPECIAL_DARK, libcomp::ServerConstants::Data::TRIFUSION_SPECIAL_ELEMENTAL, libcomp::ServerConstants::Data::VA_ADD_ITEMS, libcomp::ServerConstants::Data::VALUABLE_DEMON_FORCE, libcomp::ServerConstants::Data::VALUABLE_DEVIL_BOOK_V1, libcomp::ServerConstants::Data::VALUABLE_DEVIL_BOOK_V2, libcomp::ServerConstants::Data::VALUABLE_DIGITALIZE_LV1, libcomp::ServerConstants::Data::VALUABLE_DIGITALIZE_LV2, libcomp::ServerConstants::Data::VALUABLE_FUSION_GAUGE, libcomp::ServerConstants::Data::VALUABLE_MATERIAL_TANK, and libcomp::ServerConstants::Data::ZONE_DEFAULT.
Referenced by libcomp::BaseServer::Initialize().
template<typename T > static bool libcomp::ServerConstants::LoadDecimal (const std::string & value, T & prop) inline static private
Utility function to load a string from the constants read from the XML file and assign it to a decimal.
Parameters
value Value assigned to a constant
prop Decimal reference to assign the value to
Returns
true on success, false on failure
Definition at line 842 of file ServerConstants.h.
References LoadString(), and libcomp::String::ToDecimal().
template<typename T > static bool libcomp::ServerConstants::LoadInteger (const std::string & value, T & prop) inline static private
Utility function to load a string from the constants read from the XML file and assign it to an integer.
Parameters
value Value assigned to a constant
prop Integer reference to assign the value to
Returns
true on success, false on failure
Definition at line 822 of file ServerConstants.h.
References LoadString(), and libcomp::String::ToInteger().
Referenced by Initialize(), LoadIntegerMap(), and ToIntegerRange().
template<typename K , typename V > static bool libcomp::ServerConstants::LoadIntegerMap (const std::unordered_map< std::string, std::string > & valueMap, std::unordered_map< K, V > & propMap) inline static private
Utility function to load a map of string to string pairs from the constants read from the XML file and convert to integer types.
Parameters
valueMap Value map assigned to a constant
propMap Integer map reference to assign the values to
Returns
true on success, false on failure
Definition at line 862 of file ServerConstants.h.
References LoadInteger().
Referenced by Initialize().
bool ServerConstants::LoadKeyValueStrings (const tinyxml2::XMLElement * elem, std::unordered_map< std::string, std::string > & map) static private
Utility function to load key value string pairs from the constants read from the XML file.
Parameters
elem Pointer to the pair list parent element
map String to string map to assign the value to
Returns
true on success, false on failure
Definition at line 1525 of file ServerConstants.cpp.
Referenced by Initialize().
bool ServerConstants::LoadString (const std::string & value, String & prop) static private
Utility function to load a string from the constants read from the XML file.
Parameters
value Value assigned to a constant
prop String reference to assign the value to
Returns
true on success, false on failure
Definition at line 1490 of file ServerConstants.cpp.
Referenced by Initialize(), LoadDecimal(), and LoadInteger().
bool ServerConstants::LoadStringList (const tinyxml2::XMLElement * elem, std::list< String > & prop) static private
Utility function to load a list of strings from the constants read from the XML file.
Parameters
elem Pointer to the string list parent element
prop List of strings reference to assign the value to
Returns
true on success, false on failure
Definition at line 1496 of file ServerConstants.cpp.
Referenced by Initialize().
template<typename T , std::size_t SIZE> static bool libcomp::ServerConstants::ToIntegerArray (std::array< T, SIZE > & prop, std::list< String > values) inline static private
Utility function to load a list of strings into an array.
Parameters
prop Array of integers to assign the value to
values List of strings reference to pull the values from
Returns
true on success, false on failure
Definition at line 755 of file ServerConstants.h.
Referenced by Initialize().
template<typename T > static std::list<T> libcomp::ServerConstants::ToIntegerRange (const std::string & value, bool & success) inline static private
Utility function to load convert a string to a list of numeric ranges and return in a list.
Parameters
value String of numeric ranges
success Output success indicator
Returns
List of converted numbers or empty if failure occurs
Definition at line 890 of file ServerConstants.h.
References LoadInteger(), and libcomp::String::Split().
template<typename T > static bool libcomp::ServerConstants::ToIntegerSet (std::set< T > & prop, std::list< String > values) inline static private
Utility function to load a list of strings into a set.
Parameters
prop Set of integers to assign the value to
values List of strings reference to pull the values from
Returns
true on success, false on failure
Definition at line 786 of file ServerConstants.h.
Referenced by Initialize().
Member Data Documentation
ServerConstants::Data ServerConstants::sConstants = {} static private
Container for all server side constants.
Definition at line 946 of file ServerConstants.h.
Referenced by GetConstants(), and Initialize().
The documentation for this class was generated from the following files:
ServerConstants.h
ServerConstants.cpp