COMP_hack: libcomp::Exception Class Reference
libcomp::Exception Class Reference
Base exception class.
#include <Exception.h>
Public Member Functions
Exception (const String &msg, const String &file, int line)
Construct a basic exception.
std::list< String > Backtrace () const
Retrieve a backtrace of the exception.
String File () const
Retrieve the file the exception occured in.
int Line () const
Retrieve the line number the exception occured on.
virtual void Log () const
Generate a log message for the exception.
String Message () const
Retrieve the message describing the exception.
Static Public Member Functions
static void RegisterSignalHandler ()
Register the SIGSEGV signal handler to catch crashes.
Private Attributes
std::list< String > mBacktrace
Backtrace information for the exception.
String mFile
File the exception occured in.
int mLine
Line number the exception occured on.
String mMessage
Message describing the exception.
Detailed Description
Base exception class.
Any application specific exceptions should be derived from this class. If an exception is not derived from this class (e.g. the bad_alloc exception), it should be caught and either handled or thrown again as an application exception using this class or any of it's derived classes. When constructing an exception, use the EXCEPTION macro for automatic insertation of the file and line the exception occured on.
Definition at line 56 of file Exception.h.
Constructor & Destructor Documentation
Exception::Exception (const String & msg, const String & file, int line)
Construct a basic exception.
Pass FILE as the file argument and LINE as the line argument. It is recommended you use the EXCEPTION macro instead.
Parameters
msg Message describing the exception.
file File the exception occured in.
line Line the exception occured on.
Definition at line 64 of file Exception.cpp.
References libcomp::IsMemoryManagerEnabled(), and mBacktrace.
Member Function Documentation
std::list< String > Exception::Backtrace () const
Retrieve a backtrace of the exception.
Returns
Backtrace of the exception.
Definition at line 368 of file Exception.cpp.
References mBacktrace.
Referenced by libcomp::Message::ExecuteImpl< Function >::ExecuteImpl(), Log(), libcomp::PacketException::Log(), RegisterSignalHandler(), and SignalHandler().
String Exception::File () const
Retrieve the file the exception occured in.
Returns
File the exception was thrown from.
Definition at line 350 of file Exception.cpp.
References baseLen, libcomp::String::Left(), libcomp::String::Length(), mFile, and libcomp::String::Mid().
Referenced by Log(), and libcomp::PacketException::Log().
int Exception::Line () const
Retrieve the line number the exception occured on.
Returns
Line number the exception was thrown from.
Definition at line 345 of file Exception.cpp.
References mLine.
Referenced by Log(), and libcomp::PacketException::Log().
void Exception::Log () const virtual
Generate a log message for the exception.
Derived exception classes should re-implement this function if they have more information related to the exception.
Reimplemented in libcomp::PacketException.
Definition at line 373 of file Exception.cpp.
References libcomp::String::Arg(), Backtrace(), File(), libcomp::String::Join(), Line(), and Message().
Referenced by libcomp::EncryptedConnection::PacketReceived(), and ToCP932Encoding().
String Exception::Message () const
Retrieve the message describing the exception.
Returns
Message describing the exception.
Definition at line 363 of file Exception.cpp.
References mMessage.
Referenced by Log(), and libcomp::PacketException::Log().
void Exception::RegisterSignalHandler () static
Register the SIGSEGV signal handler to catch crashes.
Definition at line 415 of file Exception.cpp.
References libcomp::String::Arg(), Backtrace(), libcomp::Log::GetSingletonPtr(), and SignalHandler().
Referenced by libcomp::Worker::Start().
Member Data Documentation
std::list<String> libcomp::Exception::mBacktrace private
Backtrace information for the exception.
Definition at line 116 of file Exception.h.
Referenced by Backtrace(), and Exception().
String libcomp::Exception::mFile private
File the exception occured in.
Definition at line 110 of file Exception.h.
Referenced by File().
int libcomp::Exception::mLine private
Line number the exception occured on.
Definition at line 107 of file Exception.h.
Referenced by Line().
String libcomp::Exception::mMessage private
Message describing the exception.
Definition at line 113 of file Exception.h.
Referenced by Message().
The documentation for this class was generated from the following files:
Exception.h
Exception.cpp