COMP_hack: libcomp::ReadOnlyPacket Class Reference
libcomp::ReadOnlyPacket Class Reference
Convenience class to read and write packet data.
#include <ReadOnlyPacket.h>
Public Member Functions
ReadOnlyPacket ()
Initialize a blank Packet object without any data.
ReadOnlyPacket (const ReadOnlyPacket &other)
Copy the packet data from another ReadOnlyPacket object.
ReadOnlyPacket (const ReadOnlyPacket &other, uint32_t start, uint32_t size)
Copy part of the packet data from another ReadOnlyPacket object.
ReadOnlyPacket (Packet &&other)
Move the packet data from a Packet object.
ReadOnlyPacket (const Packet &other)=delete
~ReadOnlyPacket ()
Destructor to clean-up the object (free the data).
void Allocate ()
Ensure the packet data buffer is allocated.
const char * ConstData () const
Return direct access to the underlying packet buffer.
String Dump () const
Generate a string that contains a hex dump of the packet.
void End ()
Set the current position to the end of the packet.
uint32_t Free () const
Return the number of bytes that may be added to the end of the packet.
void HexDump () const
Produce a hex dump of the packet in the log.
uint32_t Left () const
Return the number of bytes left to be read.
uint32_t Length () const
Returns the number of bytes in the packet.
ReadOnlyPacket & operator= (ReadOnlyPacket &other)
Copy the packet data from another ReadOnlyPacket object.
ReadOnlyPacket & operator= (ReadOnlyPacket &&other)=delete
Move the packet data from another ReadOnlyPacket object.
int16_t PeekS16 ()
Read a 16-bit signed integer in host byte order from the packet but do not advance the current position in the packet.
int16_t PeekS16Big ()
Read a 16-bit signed integer in big endian byte order from the packet but do not advance the current position in the packet.
int16_t PeekS16Little ()
Read a 16-bit signed integer in little endian byte order from the packet but do not advance the current position in the packet.
int32_t PeekS32 ()
Read a 32-bit signed integer in host byte order from the packet but do not advance the current position in the packet.
int32_t PeekS32Big ()
Read a 32-bit signed integer in big endian byte order from the packet but do not advance the current position in the packet.
int32_t PeekS32Little ()
Read a 32-bit signed integer in little endian byte order from the packet but do not advance the current position in the packet.
int8_t PeekS8 ()
Read a 8-bit signed integer from the packet but do not advance the current position in the packet.
uint16_t PeekU16 ()
Read a 16-bit unsigned integer in host byte order from the packet but do not advance the current position in the packet.
uint16_t PeekU16Big ()
Read a 16-bit unsigned integer in big endian byte order from the packet but do not advance the current position in the packet.
uint16_t PeekU16Little ()
Read a 16-bit unsigned integer in little endian byte order from the packet but do not advance the current position in the packet.
uint32_t PeekU32 ()
Read a 32-bit unsigned integer in host byte order from the packet but do not advance the current position in the packet.
uint32_t PeekU32Big ()
Read a 32-bit unsigned integer in big endian byte order from the packet but do not advance the current position in the packet.
uint32_t PeekU32Little ()
Read a 32-bit unsigned integer in little endian byte order from the packet but do not advance the current position in the packet.
uint8_t PeekU8 ()
Read a 8-bit unsigned integer from the packet but do not advance the current position in the packet.
std::vector< char > ReadArray (uint32_t sz)
Read sz bytes of data from the packet.
void ReadArray (void *buffer, uint32_t sz)
Read sz bytes of data from the packet into buffer.
double ReadDouble ()
Write a 64-bit double precision number from the packet and advance the current position in the packet.
float ReadFloat ()
Read a 32-bit floating point number from the packet and advance the current position in the packet.
int16_t ReadS16 ()
Read a 16-bit signed integer in host byte order from the packet and advance the current position in the packet.
int16_t ReadS16Big ()
Read a 16-bit signed integer in big endian byte order from the packet and advance the current position in the packet.
int16_t ReadS16Little ()
Read a 16-bit signed integer in little endian byte order from the packet and advance the current position in the packet.
int32_t ReadS32 ()
Read a 32-bit signed integer in host byte order from the packet and advance the current position in the packet.
int32_t ReadS32Big ()
Read a 32-bit signed integer in big endian byte order from the packet and advance the current position in the packet.
int32_t ReadS32Little ()
Read a 32-bit signed integer in little endian byte order from the packet and advance the current position in the packet.
int64_t ReadS64 ()
Read a 64-bit signed integer in host byte order from the packet and advance the current position in the packet.
int64_t ReadS64Big ()
Read a 64-bit signed integer in big endian byte order from the packet and advance the current position in the packet.
int64_t ReadS64Little ()
Read a 64-bit signed integer in little endian byte order from the packet and advance the current position in the packet.
int8_t ReadS8 ()
Read a 8-bit signed integer from the packet and advance the current position in the packet.
String ReadString (Convert::Encoding_t encoding)
Read the string str encoded with encoding from the packet.
String ReadString16 (Convert::Encoding_t encoding, bool trimNull=false)
Read the string str encoded with encoding from the packet.
String ReadString16Big (Convert::Encoding_t encoding, bool trimNull=false)
Read the string str encoded with encoding from the packet.
String ReadString16Little (Convert::Encoding_t encoding, bool trimNull=false)
Read the string str encoded with encoding from the packet.
String ReadString32 (Convert::Encoding_t encoding, bool trimNull=false)
Read the string str encoded with encoding from the packet.
String ReadString32Big (Convert::Encoding_t encoding, bool trimNull=false)
Read the string str encoded with encoding from the packet.
String ReadString32Little (Convert::Encoding_t encoding, bool trimNull=false)
Read the string str encoded with encoding from the packet.
uint16_t ReadU16 ()
Read a 16-bit unsigned integer in host byte order from the packet and advance the current position in the packet.
uint16_t ReadU16Big ()
Read a 16-bit unsigned integer in big endian byte order from the packet and advance the current position in the packet.
uint16_t ReadU16Little ()
Read a 16-bit unsigned integer in little endian byte order from the packet and advance the current position in the packet.
uint32_t ReadU32 ()
Read a 32-bit unsigned integer in host byte order from the packet and advance the current position in the packet.
uint32_t ReadU32Big ()
Read a 32-bit unsigned integer in big endian byte order from the packet and advance the current position in the packet.
uint32_t ReadU32Little ()
Read a 32-bit unsigned integer in little endian byte order from the packet and advance the current position in the packet.
uint64_t ReadU64 ()
Read a 64-bit unsigned integer in host byte order from the packet and advance the current position in the packet.
uint64_t ReadU64Big ()
Read a 64-bit unsigned integer in big endian byte order from the packet and advance the current position in the packet.
uint64_t ReadU64Little ()
Read a 64-bit unsigned integer in little endian byte order from the packet and advance the current position in the packet.
uint8_t ReadU8 ()
Read a 8-bit unsigned integer from the packet and advance the current position in the packet.
void Rewind ()
Rewind the current position to the beginning of the packet.
void Rewind (uint32_t bytes)
Rewind the current position by bytes.
void Seek (uint32_t pos)
Seek to pos bytes from the beginning of the packet.
uint32_t Size () const
Returns the number of bytes in the packet.
void Skip (uint32_t bytes)
Advance bytes from the current position.
uint32_t Tell () const
Return the current position in the packet.
Protected Member Functions
ReadOnlyPacket (uint32_t position, uint32_t size, uint8_t *pData, std::shared_ptr< PacketArray > dataRef)
Protected constructor for use by subclasses.
Protected Attributes
uint8_t * mData
Pointer to the packet data.
std::shared_ptr< PacketArray > mDataRef
Reference to the underlying buffer (which could be shared between read only packets).
uint32_t mPosition
Current position in the packet.
uint32_t mSize
Size of the packet.
Private Types
typedef std::array< uint8_t,
MAX_PACKET_SIZE > PacketArray
Friends
class PacketException
This class needs to directly access data in the Packet class.
Detailed Description
Convenience class to read and write packet data.
This class is designed to make it easy to read and write packet data. Strings can be converted between the internal Unicode format and Windows code pages. All integer numbers can be written in host byte order, big endian, or little endian. The packet data is usually read or written in sequantial order but you can use random access as well. Note that data is not inserted into the middle of the packet, it is instead overwritten with the new data. Here is some example code:
Packet p;
p.WriteU16Little(0x1234); // Code for this packet.
p.WriteBlank(4); // Number of items (blank for now).
// Initialize the item count to 0.
int count = 0;
// Loop through and write each item to the packet.
while(HaveItems())
{
    count++;
    p.WriteU32Little(NextItem());
}
// Return to where the item count should be, write the count, and return
// the current position back to the end of the packet.
p.Seek(2);
p.WriteU32Little(count);
p.End();
Definition at line 85 of file ReadOnlyPacket.h.
Member Typedef Documentation
typedef std::array<uint8_t, MAX_PACKET_SIZE> libcomp::ReadOnlyPacket::PacketArray private
Definition at line 88 of file ReadOnlyPacket.h.
Constructor & Destructor Documentation
ReadOnlyPacket::ReadOnlyPacket () explicit
Initialize a blank Packet object without any data.
Definition at line 50 of file ReadOnlyPacket.cpp.
ReadOnlyPacket::ReadOnlyPacket (const ReadOnlyPacket & other) explicit
Copy the packet data from another ReadOnlyPacket object.
Parameters
other ReadOnlyPacket object to copy the data from.
Definition at line 63 of file ReadOnlyPacket.cpp.
ReadOnlyPacket::ReadOnlyPacket (const ReadOnlyPacket & other, uint32_t start, uint32_t size) explicit
Copy part of the packet data from another ReadOnlyPacket object.
Parameters
other ReadOnlyPacket object to copy the data from.
start Number of bytes into the packet data.
size Size in bytes of the data to copy.
Definition at line 69 of file ReadOnlyPacket.cpp.
References mSize, and PACKET_EXCEPTION.
ReadOnlyPacket::ReadOnlyPacket (Packet && other) explicit
Move the packet data from a Packet object.
Parameters
other Packet object to move the data from.
Definition at line 80 of file ReadOnlyPacket.cpp.
libcomp::ReadOnlyPacket::ReadOnlyPacket (const Packet & other) explicit delete
ReadOnlyPacket::~ReadOnlyPacket ()
Destructor to clean-up the object (free the data).
Definition at line 93 of file ReadOnlyPacket.cpp.
ReadOnlyPacket::ReadOnlyPacket (uint32_t position, uint32_t size, uint8_t * pData, std::shared_ptr< PacketArray > dataRef) explicit protected
Protected constructor for use by subclasses.
Definition at line 57 of file ReadOnlyPacket.cpp.
Member Function Documentation
void ReadOnlyPacket::Allocate ()
Ensure the packet data buffer is allocated.
Definition at line 97 of file ReadOnlyPacket.cpp.
References mData, and mDataRef.
Referenced by libcomp::Packet::Clear(), libcomp::Packet::GrowPacket(), libcomp::Packet::Packet(), and libcomp::TcpConnection::RequestPacket().
const char * ReadOnlyPacket::ConstData () const
Return direct access to the underlying packet buffer.
Avoid using this function as modifying or deleting the buffer can cause bugs. With direct access, you must do your own bounds checking. An alternative is to use seek() or rewind() and then call readArray() to copy the data out of the packet.
Returns
Pointer to the packet data.
Definition at line 786 of file ReadOnlyPacket.cpp.
References mData.
Referenced by libcomp::TcpConnection::FlushOutgoingInside(), libcomp::EncryptedConnection::ParsePacket(), libcomp::ChannelConnection::PreparePackets(), and libcomp::ReadOnlyPacketStream::ReadOnlyPacketStream().
String ReadOnlyPacket::Dump () const
Generate a string that contains a hex dump of the packet.
Returns
String that contains the hex dump.
Definition at line 802 of file ReadOnlyPacket.cpp.
References libcomp::String::Arg(), libcomp::String::Join(), mData, mPosition, and mSize.
Referenced by HexDump().
void ReadOnlyPacket::End ()
Set the current position to the end of the packet.
This will set Tell() equal to Size().
Definition at line 750 of file ReadOnlyPacket.cpp.
References mPosition, and mSize.
Referenced by libcomp::Crypto::Blowfish::EncryptPacket().
uint32_t ReadOnlyPacket::Free () const
Return the number of bytes that may be added to the end of the packet.
Returns
Number of bytes that may be added to the end of the packet.
Definition at line 769 of file ReadOnlyPacket.cpp.
References mSize.
Referenced by libcomp::PacketStream::overflow().
void ReadOnlyPacket::HexDump () const
Produce a hex dump of the packet in the log.
Definition at line 792 of file ReadOnlyPacket.cpp.
References Dump().
Referenced by libcomp::ScriptEngine::Using().
uint32_t ReadOnlyPacket::Left () const
Return the number of bytes left to be read.
This is the number of bytes between the current position and the size of the packet.
Returns
Number of bytes left in the packet.
Definition at line 762 of file ReadOnlyPacket.cpp.
References mPosition, and mSize.
Referenced by libcomp::ChannelConnection::DecompressPacket(), libcomp::TcpConnection::FlushOutgoingInside(), libcomp::PacketStream::overflow(), libcomp::EncryptedConnection::ParseClientEncryptionStart(), libcomp::LobbyConnection::ParseExtensionConnection(), libcomp::EncryptedConnection::ParsePacket(), libcomp::EncryptedConnection::ParseServerEncryptionFinish(), libcomp::EncryptedConnection::ParseServerEncryptionStart(), ReadString(), and libcomp::DataSyncManager::SyncIncoming().
uint32_t ReadOnlyPacket::Length () const
Returns the number of bytes in the packet.
Returns
Number of bytes in the packet.
Definition at line 780 of file ReadOnlyPacket.cpp.
References mSize.
ReadOnlyPacket & ReadOnlyPacket::operator= (ReadOnlyPacket & other)
Copy the packet data from another ReadOnlyPacket object.
Parameters
other ReadOnlyPacket object to move the data from.
Definition at line 926 of file ReadOnlyPacket.cpp.
References mData, mDataRef, mPosition, and mSize.
ReadOnlyPacket& libcomp::ReadOnlyPacket::operator= (ReadOnlyPacket && other) delete
Move the packet data from another ReadOnlyPacket object.
Parameters
other ReadOnlyPacket object to move the data from.
int16_t ReadOnlyPacket::PeekS16 ()
Read a 16-bit signed integer in host byte order from the packet but do not advance the current position in the packet.
Useful for determining a length (e.g. of a string) or version of the packet before actually doing read code.
Returns
Value at the current position in the packet.
See Also
ReadS16
PeekS16Big
PeekS16Little
Definition at line 389 of file ReadOnlyPacket.cpp.
References mData, mPosition, mSize, and PACKET_EXCEPTION.
Referenced by PeekS16Big(), and PeekS16Little().
int16_t ReadOnlyPacket::PeekS16Big ()
Read a 16-bit signed integer in big endian byte order from the packet but do not advance the current position in the packet.
Useful for determining a length (e.g. of a string) or version of the packet before actually doing read code.
Returns
Value at the current position in the packet.
See Also
ReadS16
PeekS16
PeekS16Little
Definition at line 412 of file ReadOnlyPacket.cpp.
References PeekS16().
int16_t ReadOnlyPacket::PeekS16Little ()
Read a 16-bit signed integer in little endian byte order from the packet but do not advance the current position in the packet.
Useful for determining a length (e.g. of a string) or version of the packet before actually doing read code.
Returns
Value at the current position in the packet.
See Also
ReadS16
PeekS16
PeekS16Big
Definition at line 424 of file ReadOnlyPacket.cpp.
References PeekS16().
int32_t ReadOnlyPacket::PeekS32 ()
Read a 32-bit signed integer in host byte order from the packet but do not advance the current position in the packet.
Useful for determining a length (e.g. of a string) or version of the packet before actually doing read code.
Returns
Value at the current position in the packet.
See Also
ReadS32
PeekS32Big
PeekS32Little
Definition at line 447 of file ReadOnlyPacket.cpp.
References mData, mPosition, mSize, and PACKET_EXCEPTION.
Referenced by PeekS32Big(), and PeekS32Little().
int32_t ReadOnlyPacket::PeekS32Big ()
Read a 32-bit signed integer in big endian byte order from the packet but do not advance the current position in the packet.
Useful for determining a length (e.g. of a string) or version of the packet before actually doing read code.
Returns
Value at the current position in the packet.
See Also
ReadS32
PeekS32
PeekS32Little
Definition at line 470 of file ReadOnlyPacket.cpp.
References PeekS32().
int32_t ReadOnlyPacket::PeekS32Little ()
Read a 32-bit signed integer in little endian byte order from the packet but do not advance the current position in the packet.
Useful for determining a length (e.g. of a string) or version of the packet before actually doing read code.
Returns
Value at the current position in the packet.
See Also
ReadS32
PeekS32
PeekS32Big
Definition at line 482 of file ReadOnlyPacket.cpp.
References PeekS32().
int8_t ReadOnlyPacket::PeekS8 ()
Read a 8-bit signed integer from the packet but do not advance the current position in the packet.
Useful for determining a length (e.g. of a string) or version of the packet before actually doing read code.
Returns
Value at the current position in the packet.
See Also
ReadS8
Definition at line 355 of file ReadOnlyPacket.cpp.
References mData, mPosition, mSize, and PACKET_EXCEPTION.
uint16_t ReadOnlyPacket::PeekU16 ()
Read a 16-bit unsigned integer in host byte order from the packet but do not advance the current position in the packet.
Useful for determining a length (e.g. of a string) or version of the packet before actually doing read code.
Returns
Value at the current position in the packet.
See Also
ReadU16
PeekU16Big
PeekU16Little
Definition at line 372 of file ReadOnlyPacket.cpp.
References mData, mPosition, mSize, and PACKET_EXCEPTION.
Referenced by PeekU16Big(), and PeekU16Little().
uint16_t ReadOnlyPacket::PeekU16Big ()
Read a 16-bit unsigned integer in big endian byte order from the packet but do not advance the current position in the packet.
Useful for determining a length (e.g. of a string) or version of the packet before actually doing read code.
Returns
Value at the current position in the packet.
See Also
ReadU16
PeekU16
PeekU16Little
Definition at line 406 of file ReadOnlyPacket.cpp.
References PeekU16().
uint16_t ReadOnlyPacket::PeekU16Little ()
Read a 16-bit unsigned integer in little endian byte order from the packet but do not advance the current position in the packet.
Useful for determining a length (e.g. of a string) or version of the packet before actually doing read code.
Returns
Value at the current position in the packet.
See Also
ReadU16
PeekU16
PeekU16Big
Definition at line 418 of file ReadOnlyPacket.cpp.
References PeekU16().
uint32_t ReadOnlyPacket::PeekU32 ()
Read a 32-bit unsigned integer in host byte order from the packet but do not advance the current position in the packet.
Useful for determining a length (e.g. of a string) or version of the packet before actually doing read code.
Returns
Value at the current position in the packet.
See Also
ReadU32
PeekU32Big
PeekU32Little
Definition at line 430 of file ReadOnlyPacket.cpp.
References mData, mPosition, mSize, and PACKET_EXCEPTION.
Referenced by PeekU32Big(), and PeekU32Little().
uint32_t ReadOnlyPacket::PeekU32Big ()
Read a 32-bit unsigned integer in big endian byte order from the packet but do not advance the current position in the packet.
Useful for determining a length (e.g. of a string) or version of the packet before actually doing read code.
Returns
Value at the current position in the packet.
See Also
ReadU32
PeekU32
PeekU32Little
Definition at line 464 of file ReadOnlyPacket.cpp.
References PeekU32().
Referenced by libcomp::EncryptedConnection::ParseClientEncryptionStart(), and libcomp::EncryptedConnection::ParseServerEncryptionFinish().
uint32_t ReadOnlyPacket::PeekU32Little ()
Read a 32-bit unsigned integer in little endian byte order from the packet but do not advance the current position in the packet.
Useful for determining a length (e.g. of a string) or version of the packet before actually doing read code.
Returns
Value at the current position in the packet.
See Also
ReadU32
PeekU32
PeekU32Big
Definition at line 476 of file ReadOnlyPacket.cpp.
References PeekU32().
uint8_t ReadOnlyPacket::PeekU8 ()
Read a 8-bit unsigned integer from the packet but do not advance the current position in the packet.
Useful for determining a length (e.g. of a string) or version of the packet before actually doing read code.
Returns
Value at the current position in the packet.
See Also
ReadU8
Definition at line 338 of file ReadOnlyPacket.cpp.
References mData, mPosition, mSize, and PACKET_EXCEPTION.
std::vector< char > ReadOnlyPacket::ReadArray (uint32_t sz)
Read sz bytes of data from the packet.
After reading the data, the current position in the packet will advance by sz bytes.
Parameters
sz Number of bytes to read from the packet into the buffer.
Returns
Buffer the data was read into.
Definition at line 165 of file ReadOnlyPacket.cpp.
References mData, mPosition, mSize, PACKET_EXCEPTION, and Skip().
Referenced by ReadString(), ReadString16(), ReadString16Big(), ReadString16Little(), ReadString32(), ReadString32Big(), ReadString32Little(), libcomp::Packet::Split(), TEST(), and libcomp::ScriptEngine::Using().
void ReadOnlyPacket::ReadArray (void * buffer, uint32_t sz)
Read sz bytes of data from the packet into buffer.
After reading the data, the current position in the packet will advance by sz bytes.
Parameters
buffer Buffer to store the data that was read from the packet.
sz Number of bytes to read from the packet into the buffer.
Definition at line 193 of file ReadOnlyPacket.cpp.
References mData, mPosition, mSize, PACKET_EXCEPTION, and Skip().
double ReadOnlyPacket::ReadDouble ()
Write a 64-bit double precision number from the packet and advance the current position in the packet.
Returns
Value at the current position in the packet.
See Also
WriteDouble
Definition at line 731 of file ReadOnlyPacket.cpp.
References mData, mPosition, mSize, PACKET_EXCEPTION, and Skip().
float ReadOnlyPacket::ReadFloat ()
Read a 32-bit floating point number from the packet and advance the current position in the packet.
Returns
Value at the current position in the packet.
See Also
WriteFloat
Definition at line 712 of file ReadOnlyPacket.cpp.
References mData, mPosition, mSize, PACKET_EXCEPTION, and Skip().
int16_t ReadOnlyPacket::ReadS16 ()
Read a 16-bit signed integer in host byte order from the packet and advance the current position in the packet.
Returns
Value at the current position in the packet.
See Also
WriteS16
ReadS16Big
ReadS16Little
Definition at line 557 of file ReadOnlyPacket.cpp.
References mData, mPosition, mSize, PACKET_EXCEPTION, and Skip().
Referenced by ReadS16Big(), and ReadS16Little().
int16_t ReadOnlyPacket::ReadS16Big ()
Read a 16-bit signed integer in big endian byte order from the packet and advance the current position in the packet.
Returns
Value at the current position in the packet.
See Also
WriteS16Big
ReadS16
ReadS16Little
Definition at line 576 of file ReadOnlyPacket.cpp.
References ReadS16().
int16_t ReadOnlyPacket::ReadS16Little ()
Read a 16-bit signed integer in little endian byte order from the packet and advance the current position in the packet.
Returns
Value at the current position in the packet.
See Also
WriteS16Little
ReadS16
ReadS16Big
Definition at line 582 of file ReadOnlyPacket.cpp.
References ReadS16().
int32_t ReadOnlyPacket::ReadS32 ()
Read a 32-bit signed integer in host byte order from the packet and advance the current position in the packet.
Returns
Value at the current position in the packet.
See Also
WriteS32
ReadS32Big
ReadS32Little
Definition at line 619 of file ReadOnlyPacket.cpp.
References mData, mPosition, mSize, PACKET_EXCEPTION, and Skip().
Referenced by ReadS32Big(), and ReadS32Little().
int32_t ReadOnlyPacket::ReadS32Big ()
Read a 32-bit signed integer in big endian byte order from the packet and advance the current position in the packet.
Returns
Value at the current position in the packet.
See Also
WriteS32Big
ReadS32
ReadS32Little
Definition at line 638 of file ReadOnlyPacket.cpp.
References ReadS32().
int32_t ReadOnlyPacket::ReadS32Little ()
Read a 32-bit signed integer in little endian byte order from the packet and advance the current position in the packet.
Returns
Value at the current position in the packet.
See Also
WriteS32Little
ReadS32
ReadS32Big
Definition at line 644 of file ReadOnlyPacket.cpp.
References ReadS32().
Referenced by libcomp::ChannelConnection::DecompressPacket().
int64_t ReadOnlyPacket::ReadS64 ()
Read a 64-bit signed integer in host byte order from the packet and advance the current position in the packet.
Returns
Value at the current position in the packet.
See Also
WriteS64
ReadS64Big
ReadS64Little
Definition at line 681 of file ReadOnlyPacket.cpp.
References mData, mPosition, mSize, PACKET_EXCEPTION, and Skip().
Referenced by ReadS64Big(), and ReadS64Little().
int64_t ReadOnlyPacket::ReadS64Big ()
Read a 64-bit signed integer in big endian byte order from the packet and advance the current position in the packet.
Returns
Value at the current position in the packet.
See Also
WriteS64Big
ReadS64
ReadS64Little
Definition at line 700 of file ReadOnlyPacket.cpp.
References ReadS64().
int64_t ReadOnlyPacket::ReadS64Little ()
Read a 64-bit signed integer in little endian byte order from the packet and advance the current position in the packet.
Returns
Value at the current position in the packet.
See Also
WriteS64Little
ReadS64
ReadS64Big
Definition at line 706 of file ReadOnlyPacket.cpp.
References ReadS64().
int8_t ReadOnlyPacket::ReadS8 ()
Read a 8-bit signed integer from the packet and advance the current position in the packet.
Returns
Value at the current position in the packet.
See Also
PeekS8
WriteS8
Definition at line 507 of file ReadOnlyPacket.cpp.
References mData, mPosition, mSize, PACKET_EXCEPTION, and Skip().
String ReadOnlyPacket::ReadString (Convert::Encoding_t encoding)
Read the string str encoded with encoding from the packet.
The string should contain a null terminator.
Parameters
encoding String encoding used. Can be one of:
ENCODING_UTF8 (Unicode)
ENCODING_CP932 (Japanese)
ENCODING_CP1252 (US English)
Returns
The string that was read.
See Also
WriteString
ReadString16
ReadString32
Definition at line 216 of file ReadOnlyPacket.cpp.
References libcomp::Convert::FromEncoding(), Left(), ReadArray(), ReadU8(), and Rewind().
String ReadOnlyPacket::ReadString16 (Convert::Encoding_t encoding, bool trimNull = false)
Read the string str encoded with encoding from the packet.
The size of the string is determined by a 16-bit unsigned integer in host byte order that is read first. This size includes any null terminator.
Parameters
encoding String encoding used. Can be one of:
ENCODING_UTF8 (Unicode)
ENCODING_CP932 (Japanese)
ENCODING_CP1252 (US English)
trimNull When true the null terminator will be removed
Returns
The string that was read.
See Also
WriteString16
ReadString16Big
ReadString16Little
Definition at line 236 of file ReadOnlyPacket.cpp.
References libcomp::Convert::FromEncoding(), ReadArray(), and ReadU16().
String ReadOnlyPacket::ReadString16Big (Convert::Encoding_t encoding, bool trimNull = false)
Read the string str encoded with encoding from the packet.
The size of the string is determined by a 16-bit unsigned integer in big endian byte order that is read first. This size includes any null terminator.
Parameters
encoding String encoding used. Can be one of:
ENCODING_UTF8 (Unicode)
ENCODING_CP932 (Japanese)
ENCODING_CP1252 (US English)
trimNull When true the null terminator will be removed
Returns
The string that was read.
See Also
WriteString16
ReadString16
ReadString16Little
Definition at line 253 of file ReadOnlyPacket.cpp.
References libcomp::Convert::FromEncoding(), ReadArray(), and ReadU16Big().
String ReadOnlyPacket::ReadString16Little (Convert::Encoding_t encoding, bool trimNull = false)
Read the string str encoded with encoding from the packet.
The size of the string is determined by a 16-bit unsigned integer in little endian byte order that is read first. This size includes any null terminator.
Parameters
encoding String encoding used. Can be one of:
ENCODING_UTF8 (Unicode)
ENCODING_CP932 (Japanese)
ENCODING_CP1252 (US English)
trimNull When true the null terminator will be removed
Returns
The string that was read.
See Also
WriteString16
ReadString16
ReadString16Big
Definition at line 270 of file ReadOnlyPacket.cpp.
References libcomp::Convert::FromEncoding(), ReadArray(), and ReadU16Little().
Referenced by libcomp::DataSyncManager::SyncIncoming().
String ReadOnlyPacket::ReadString32 (Convert::Encoding_t encoding, bool trimNull = false)
Read the string str encoded with encoding from the packet.
The size of the string is determined by a 32-bit unsigned integer in host byte order that is read first. This size includes any null terminator.
Parameters
encoding String encoding used. Can be one of:
ENCODING_UTF8 (Unicode)
ENCODING_CP932 (Japanese)
ENCODING_CP1252 (US English)
trimNull When true the null terminator will be removed
Returns
The string that was read.
See Also
WriteString32
ReadString32Big
ReadString32Little
Definition at line 287 of file ReadOnlyPacket.cpp.
References libcomp::Convert::FromEncoding(), ReadArray(), and ReadU32().
String ReadOnlyPacket::ReadString32Big (Convert::Encoding_t encoding, bool trimNull = false)
Read the string str encoded with encoding from the packet.
The size of the string is determined by a 32-bit unsigned integer in big endian byte order that is read first. This size includes any null terminator.
Parameters
encoding String encoding used. Can be one of:
ENCODING_UTF8 (Unicode)
ENCODING_CP932 (Japanese)
ENCODING_CP1252 (US English)
trimNull When true the null terminator will be removed
Returns
The string that was read.
See Also
WriteString32
ReadString32
ReadString32Little
Definition at line 304 of file ReadOnlyPacket.cpp.
References libcomp::Convert::FromEncoding(), ReadArray(), and ReadU32Big().
Referenced by libcomp::EncryptedConnection::ParseClientEncryptionStart(), and libcomp::EncryptedConnection::ParseServerEncryptionFinish().
String ReadOnlyPacket::ReadString32Little (Convert::Encoding_t encoding, bool trimNull = false)
Read the string str encoded with encoding from the packet.
The size of the string is determined by a 32-bit unsigned integer in little endian byte order that is read first. This size includes any null terminator.
Parameters
encoding String encoding used. Can be one of:
ENCODING_UTF8 (Unicode)
ENCODING_CP932 (Japanese)
ENCODING_CP1252 (US English)
trimNull When true the null terminator will be removed
Returns
The string that was read.
See Also
WriteString32
ReadString32
ReadString32Big
Definition at line 321 of file ReadOnlyPacket.cpp.
References libcomp::Convert::FromEncoding(), ReadArray(), and ReadU32Little().
uint16_t ReadOnlyPacket::ReadU16 ()
Read a 16-bit unsigned integer in host byte order from the packet and advance the current position in the packet.
Returns
Value at the current position in the packet.
See Also
PeekU16
WriteU16
ReadU16Big
ReadU16Little
Definition at line 526 of file ReadOnlyPacket.cpp.
References mData, mPosition, mSize, PACKET_EXCEPTION, and Skip().
Referenced by ReadString16(), ReadU16Big(), and ReadU16Little().
uint16_t ReadOnlyPacket::ReadU16Big ()
Read a 16-bit unsigned integer in big endian byte order from the packet and advance the current position in the packet.
Returns
Value at the current position in the packet.
See Also
PeekU16Big
WriteU16Big
ReadU16
ReadU16Little
Definition at line 545 of file ReadOnlyPacket.cpp.
References ReadU16().
Referenced by ReadString16Big().
uint16_t ReadOnlyPacket::ReadU16Little ()
Read a 16-bit unsigned integer in little endian byte order from the packet and advance the current position in the packet.
Returns
Value at the current position in the packet.
See Also
PeekU16Little
WriteU16Little
ReadU16
ReadU16Big
Definition at line 551 of file ReadOnlyPacket.cpp.
References ReadU16().
Referenced by libcomp::EncryptedConnection::ParsePacket(), ReadString16Little(), and libcomp::DataSyncManager::SyncIncoming().
uint32_t ReadOnlyPacket::ReadU32 ()
Read a 32-bit unsigned integer in host byte order from the packet and advance the current position in the packet.
Returns
Value at the current position in the packet.
See Also
PeekU32
WriteU32
ReadU32Big
ReadU32Little
Definition at line 588 of file ReadOnlyPacket.cpp.
References mData, mPosition, mSize, PACKET_EXCEPTION, and Skip().
Referenced by ReadString32(), ReadU32Big(), and ReadU32Little().
uint32_t ReadOnlyPacket::ReadU32Big ()
Read a 32-bit unsigned integer in big endian byte order from the packet and advance the current position in the packet.
Returns
Value at the current position in the packet.
See Also
PeekU32Big
WriteU32Big
ReadU32
ReadU32Little
Definition at line 607 of file ReadOnlyPacket.cpp.
References ReadU32().
Referenced by libcomp::ChannelConnection::DecompressPacket(), libcomp::Crypto::Blowfish::DecryptPacket(), libcomp::EncryptedConnection::ParseClientEncryptionStart(), libcomp::LobbyConnection::ParseExtensionConnection(), libcomp::EncryptedConnection::ParsePacket(), libcomp::EncryptedConnection::ParseServerEncryptionStart(), and ReadString32Big().
uint32_t ReadOnlyPacket::ReadU32Little ()
Read a 32-bit unsigned integer in little endian byte order from the packet and advance the current position in the packet.
Returns
Value at the current position in the packet.
See Also
PeekU32Little
WriteU32Little
ReadU32
ReadU32Big
Definition at line 613 of file ReadOnlyPacket.cpp.
References ReadU32().
Referenced by ReadString32Little().
uint64_t ReadOnlyPacket::ReadU64 ()
Read a 64-bit unsigned integer in host byte order from the packet and advance the current position in the packet.
Returns
Value at the current position in the packet.
See Also
WriteU64
ReadU64Big
ReadU64Little
Definition at line 650 of file ReadOnlyPacket.cpp.
References mData, mPosition, mSize, PACKET_EXCEPTION, and Skip().
Referenced by ReadU64Big(), and ReadU64Little().
uint64_t ReadOnlyPacket::ReadU64Big ()
Read a 64-bit unsigned integer in big endian byte order from the packet and advance the current position in the packet.
Returns
Value at the current position in the packet.
See Also
WriteU64Big
ReadU64
ReadU64Little
Definition at line 669 of file ReadOnlyPacket.cpp.
References ReadU64().
uint64_t ReadOnlyPacket::ReadU64Little ()
Read a 64-bit unsigned integer in little endian byte order from the packet and advance the current position in the packet.
Returns
Value at the current position in the packet.
See Also
WriteU64Little
ReadU64
ReadU64Big
Definition at line 675 of file ReadOnlyPacket.cpp.
References ReadU64().
uint8_t ReadOnlyPacket::ReadU8 ()
Read a 8-bit unsigned integer from the packet and advance the current position in the packet.
Returns
Value at the current position in the packet.
See Also
PeekU8
WriteU8
Definition at line 488 of file ReadOnlyPacket.cpp.
References mData, mPosition, mSize, PACKET_EXCEPTION, and Skip().
Referenced by ReadString().
void ReadOnlyPacket::Rewind ()
Rewind the current position to the beginning of the packet.
Definition at line 139 of file ReadOnlyPacket.cpp.
References mPosition.
Referenced by libcomp::Crypto::Blowfish::DecryptPacket(), libcomp::Crypto::Blowfish::EncryptPacket(), libcomp::TcpConnection::FlushOutgoing(), libcomp::Packet::Packet(), libcomp::EncryptedConnection::ParseServerEncryptionStart(), libcomp::ChannelConnection::PreparePackets(), libcomp::ManagerPacket::ProcessMessage(), ReadString(), libcomp::Packet::Split(), TEST(), and libcomp::ScriptEngine::Using().
void ReadOnlyPacket::Rewind (uint32_t bytes)
Rewind the current position by bytes.
The range of this method should be from 0 bytes to Tell() bytes. If the value is outside of this range, a PacketException will be thrown.
Parameters
bytes Number of bytes to rewind the current position.
Definition at line 145 of file ReadOnlyPacket.cpp.
References mPosition, and PACKET_EXCEPTION.
void ReadOnlyPacket::Seek (uint32_t pos)
Seek to pos bytes from the beginning of the packet.
The position specified must be within the range of the data in the packet; otherwise, a PacketException will be thrown. The valid range is 0 bytes to Size() bytes (inclusive).
Parameters
pos Number of bytes from the start of the packet data.
Definition at line 107 of file ReadOnlyPacket.cpp.
References mPosition, and PACKET_EXCEPTION.
Referenced by libcomp::ChannelConnection::DecompressPacket(), libcomp::Crypto::Blowfish::EncryptPacket(), libcomp::EncryptedConnection::ParsePacket(), and libcomp::ChannelConnection::PreparePackets().
uint32_t ReadOnlyPacket::Size () const
Returns the number of bytes in the packet.
Returns
Number of bytes in the packet.
Definition at line 774 of file ReadOnlyPacket.cpp.
References mSize.
Referenced by libcomp::Crypto::Blowfish::DecryptPacket(), libcomp::Crypto::Blowfish::EncryptPacket(), libcomp::EncryptedConnection::GetCombinedPackets(), libcomp::PacketStream::PacketStream(), libcomp::EncryptedConnection::ParseClientEncryptionStart(), libcomp::EncryptedConnection::ParsePacket(), libcomp::EncryptedConnection::ParseServerEncryptionFinish(), libcomp::EncryptedConnection::ParseServerEncryptionStart(), libcomp::ChannelConnection::PreparePackets(), libcomp::ReadOnlyPacketStream::ReadOnlyPacketStream(), libcomp::TcpConnection::RequestPacket(), TEST(), and libcomp::ScriptEngine::Using().
void ReadOnlyPacket::Skip (uint32_t bytes)
Advance bytes from the current position.
This is essentially a seek from the current position instead of the beginning of the packet. The valid range of this method is from 0 bytes to Left() bytes (inclusive). If the value is outside this range, a PacketException will be thrown.
Parameters
bytes Number of bytes to advance the current position.
Definition at line 119 of file ReadOnlyPacket.cpp.
References mPosition, and PACKET_EXCEPTION.
Referenced by libcomp::Object::LoadPacket(), libcomp::EncryptedConnection::ParsePacket(), ReadArray(), ReadDouble(), ReadFloat(), ReadS16(), ReadS32(), ReadS64(), ReadS8(), ReadU16(), ReadU32(), ReadU64(), ReadU8(), libcomp::Packet::WriteArray(), libcomp::Packet::WriteBlank(), libcomp::Packet::WriteDouble(), libcomp::Packet::WriteFloat(), libcomp::Packet::WriteS16(), libcomp::Packet::WriteS32(), libcomp::Packet::WriteS64(), libcomp::Packet::WriteS8(), libcomp::Packet::WriteU16(), libcomp::Packet::WriteU32(), libcomp::Packet::WriteU64(), and libcomp::Packet::WriteU8().
uint32_t ReadOnlyPacket::Tell () const
Return the current position in the packet.
Returns
Current position in the packet.
Definition at line 756 of file ReadOnlyPacket.cpp.
References mPosition.
Referenced by libcomp::TcpConnection::FlushOutgoingInside(), libcomp::PacketStream::PacketStream(), libcomp::EncryptedConnection::ParsePacket(), libcomp::ReadOnlyPacketStream::ReadOnlyPacketStream(), and TEST().
Friends And Related Function Documentation
friend class PacketException friend
This class needs to directly access data in the Packet class.
Definition at line 92 of file ReadOnlyPacket.h.
Member Data Documentation
uint8_t* libcomp::ReadOnlyPacket::mData protected
Pointer to the packet data.
Definition at line 762 of file ReadOnlyPacket.h.
Referenced by Allocate(), libcomp::Packet::Clear(), libcomp::Packet::Compress(), ConstData(), libcomp::Packet::Data(), libcomp::Packet::Decompress(), libcomp::Packet::Direct(), Dump(), libcomp::Packet::operator=(), operator=(), libcomp::Packet::Packet(), libcomp::PacketException::PacketException(), PeekS16(), PeekS32(), PeekS8(), PeekU16(), PeekU32(), PeekU8(), ReadArray(), ReadDouble(), ReadFloat(), ReadS16(), ReadS32(), ReadS64(), ReadS8(), ReadU16(), ReadU32(), ReadU64(), ReadU8(), libcomp::Packet::Split(), libcomp::Packet::WriteArray(), libcomp::Packet::WriteBlank(), libcomp::Packet::WriteDouble(), libcomp::Packet::WriteFloat(), libcomp::Packet::WriteS16(), libcomp::Packet::WriteS32(), libcomp::Packet::WriteS64(), libcomp::Packet::WriteS8(), libcomp::Packet::WriteU16(), libcomp::Packet::WriteU32(), libcomp::Packet::WriteU64(), and libcomp::Packet::WriteU8().
std::shared_ptr<PacketArray> libcomp::ReadOnlyPacket::mDataRef protected
Reference to the underlying buffer (which could be shared between read only packets).
Definition at line 766 of file ReadOnlyPacket.h.
Referenced by Allocate(), libcomp::Packet::operator=(), and operator=().
uint32_t libcomp::ReadOnlyPacket::mPosition protected
Current position in the packet.
Definition at line 756 of file ReadOnlyPacket.h.
Referenced by libcomp::Packet::Clear(), libcomp::Packet::Compress(), libcomp::Packet::Decompress(), libcomp::Packet::Direct(), Dump(), End(), libcomp::Packet::EraseRight(), libcomp::Packet::GrowPacket(), Left(), libcomp::Packet::operator=(), operator=(), libcomp::Packet::Packet(), libcomp::PacketException::PacketException(), PeekS16(), PeekS32(), PeekS8(), PeekU16(), PeekU32(), PeekU8(), ReadArray(), ReadDouble(), ReadFloat(), ReadS16(), ReadS32(), ReadS64(), ReadS8(), ReadU16(), ReadU32(), ReadU64(), ReadU8(), Rewind(), Seek(), Skip(), libcomp::Packet::Split(), Tell(), libcomp::Packet::WriteArray(), libcomp::Packet::WriteBlank(), libcomp::Packet::WriteDouble(), libcomp::Packet::WriteFloat(), libcomp::Packet::WriteS16(), libcomp::Packet::WriteS32(), libcomp::Packet::WriteS64(), libcomp::Packet::WriteS8(), libcomp::Packet::WriteU16(), libcomp::Packet::WriteU32(), libcomp::Packet::WriteU64(), and libcomp::Packet::WriteU8().
uint32_t libcomp::ReadOnlyPacket::mSize protected
Size of the packet.
Definition at line 759 of file ReadOnlyPacket.h.
Referenced by libcomp::Packet::Clear(), libcomp::Packet::Compress(), libcomp::Packet::Decompress(), libcomp::Packet::Direct(), Dump(), End(), libcomp::Packet::EraseRight(), Free(), libcomp::Packet::GrowPacket(), Left(), Length(), libcomp::Packet::operator=(), operator=(), libcomp::Packet::Packet(), libcomp::PacketException::PacketException(), PeekS16(), PeekS32(), PeekS8(), PeekU16(), PeekU32(), PeekU8(), ReadArray(), ReadDouble(), ReadFloat(), ReadOnlyPacket(), ReadS16(), ReadS32(), ReadS64(), ReadS8(), ReadU16(), ReadU32(), ReadU64(), ReadU8(), Size(), and libcomp::Packet::Split().
The documentation for this class was generated from the following files:
ReadOnlyPacket.h
ReadOnlyPacket.cpp