COMP_hack: Sqrat::s64 Class Reference
Sqrat::s64 Class Reference
#include <SqratInt64.h>
Public Member Functions
s64 ()
s64 (int32_t value)
s64 (const s64 &other)
libcomp::String _tostring () const
void set (int64_t value)
int64_t value () const
int32_t valueTruncated () const
Static Public Member Functions
static SQInteger _add (HSQUIRRELVM vm)
static SQInteger _cmp (HSQUIRRELVM vm)
static SQInteger _div (HSQUIRRELVM vm)
static SQInteger _mod (HSQUIRRELVM vm)
static SQInteger _mul (HSQUIRRELVM vm)
static SQInteger _sub (HSQUIRRELVM vm)
static SQInteger equal (HSQUIRRELVM vm)
Private Attributes
int64_t mValue
Detailed Description
Definition at line 41 of file SqratInt64.h.
Constructor & Destructor Documentation
Sqrat::s64::s64 ()
Definition at line 34 of file SqratInt64.cpp.
References mValue.
Sqrat::s64::s64 (int32_t value)
Definition at line 39 of file SqratInt64.cpp.
Sqrat::s64::s64 (const s64 & other)
Definition at line 44 of file SqratInt64.cpp.
References mValue.
Member Function Documentation
SQInteger Sqrat::s64::_add (HSQUIRRELVM vm) static
Definition at line 102 of file SqratInt64.cpp.
References mValue.
Referenced by libcomp::ScriptEngine::Using< Sqrat::s64 >().
SQInteger Sqrat::s64::_cmp (HSQUIRRELVM vm) static
Definition at line 49 of file SqratInt64.cpp.
Referenced by libcomp::ScriptEngine::Using< Sqrat::s64 >().
SQInteger Sqrat::s64::_div (HSQUIRRELVM vm) static
Definition at line 213 of file SqratInt64.cpp.
References mValue.
Referenced by libcomp::ScriptEngine::Using< Sqrat::s64 >().
SQInteger Sqrat::s64::_mod (HSQUIRRELVM vm) static
Definition at line 260 of file SqratInt64.cpp.
References mValue.
Referenced by libcomp::ScriptEngine::Using< Sqrat::s64 >().
SQInteger Sqrat::s64::_mul (HSQUIRRELVM vm) static
Definition at line 176 of file SqratInt64.cpp.
References mValue.
Referenced by libcomp::ScriptEngine::Using< Sqrat::s64 >().
SQInteger Sqrat::s64::_sub (HSQUIRRELVM vm) static
Definition at line 139 of file SqratInt64.cpp.
References mValue.
Referenced by libcomp::ScriptEngine::Using< Sqrat::s64 >().
libcomp::String Sqrat::s64::_tostring () const
Definition at line 307 of file SqratInt64.cpp.
References libcomp::String::Arg().
Referenced by libcomp::ScriptEngine::Using< Sqrat::s64 >().
SQInteger Sqrat::s64::equal (HSQUIRRELVM vm) static
Definition at line 327 of file SqratInt64.cpp.
Referenced by libcomp::ScriptEngine::Using< Sqrat::s64 >().
void Sqrat::s64::set (int64_t value)
Definition at line 312 of file SqratInt64.cpp.
int64_t Sqrat::s64::value () const
Definition at line 317 of file SqratInt64.cpp.
int32_t Sqrat::s64::valueTruncated () const
Definition at line 322 of file SqratInt64.cpp.
Referenced by libcomp::ScriptEngine::Using< Sqrat::s64 >().
Member Data Documentation
int64_t Sqrat::s64::mValue private
Definition at line 44 of file SqratInt64.h.
Referenced by _add(), _div(), _mod(), _mul(), _sub(), and s64().
The documentation for this class was generated from the following files:
SqratInt64.h
SqratInt64.cpp