COMP_hack: libcomp::PacketException Class Reference
libcomp::PacketException Class Reference
Exception in reading to or writing from a Packet object.
#include <PacketException.h>
Public Member Functions
PacketException (const String &msg, const ReadOnlyPacket *pPacket, const String &file, int line)
Construct a packet exception.
std::list< String > Backtrace () const
Retrieve a backtrace of the exception.
String File () const
Retrieve the file the exception occured in.
Packet & GetPacket ()
Copy of the packet in which the exception occured.
const Packet & GetPacket () const
Immutable copy of the packet in which the exception occured.
int Line () const
Retrieve the line number the exception occured on.
virtual void Log () const
Log the exception.
String Message () const
Retrieve the message describing the exception.
Static Public Member Functions
static void RegisterSignalHandler ()
Register the SIGSEGV signal handler to catch crashes.
Private Attributes
Packet mPacket
Copy of the packet in which the exception occured.
Detailed Description
Exception in reading to or writing from a Packet object.
This class is thrown when bugs crop up in packet parsing or writing code. As a general rule of thumb no data being read from a packet should be trusted. Start by writing code to check the size of the packet. If the packet is not a fixed size, check for a minimum size before reading in any values that determine the dynamic size. Dynamic size values should be checked for sane values and that the calculated size of the packet is exactly the size of the packet. While a larger packet won't throw an exception, the code should not allow for extra data tacked on to the end of a packet. When writing packets, be aware of the maximum packet size (MAX_PACKET_SIZE). This is especially true when sending large packets like files to the console or a large number of action reports from mob kills.
Aside from sanity checking dynamic packet sizes, you should still sanity check all values in the packet. For example, if you receive a movement packet you should check the origin position is the last known location of the character and the destination is valid. The path between these two points should be checked for collisions. No time value for a movement packet should exceed 1/2 second and the distance should be calculated and used to determine the speed of the movement. This speed should be within the allowable range of the character or object being moved. The client should only be able to move their character or active demon (if one is summoned). Thus, the object UID should be compared to these two UID values. Keeping this in mind while parsing packets should help prevent packet exceptions and bugs in your code.
Like all exceptions, a packet exception will contain the backtrace as well as the file and line the exception was generated from. A copy of the packet is included in the exception to determine what went wrong in parsing or generation. The position in the packet will be retained for this purpose. To see the current state of the packet use the packet method or output it to the log using log.
Definition at line 70 of file PacketException.h.
Constructor & Destructor Documentation
PacketException::PacketException (const String & msg, const ReadOnlyPacket * pPacket, const String & file, int line)
Construct a packet exception.
It's better to use PACKET_EXCEPTION instead of throwing this constructor.
Parameters
msg Message describing the packet exception.
packet Packet that caused the exception.
file File the exception was thrown from.
line Line in the file the exception was thrown from.
Definition at line 32 of file PacketException.cpp.
References libcomp::ReadOnlyPacket::mData, mPacket, libcomp::ReadOnlyPacket::mPosition, libcomp::ReadOnlyPacket::mSize, and libcomp::Packet::WriteArray().
Member Function Documentation
std::list< String > Exception::Backtrace () const inherited
Retrieve a backtrace of the exception.
Returns
Backtrace of the exception.
Definition at line 368 of file Exception.cpp.
References libcomp::Exception::mBacktrace.
Referenced by libcomp::Message::ExecuteImpl< Function >::ExecuteImpl(), libcomp::Exception::Log(), Log(), libcomp::Exception::RegisterSignalHandler(), and SignalHandler().
String Exception::File () const inherited
Retrieve the file the exception occured in.
Returns
File the exception was thrown from.
Definition at line 350 of file Exception.cpp.
References baseLen, libcomp::String::Left(), libcomp::String::Length(), libcomp::Exception::mFile, and libcomp::String::Mid().
Referenced by libcomp::Exception::Log(), and Log().
Packet & PacketException::GetPacket ()
Copy of the packet in which the exception occured.
Returns
Copy of the packet.
Definition at line 45 of file PacketException.cpp.
References mPacket.
Referenced by Log().
const Packet & PacketException::GetPacket () const
Immutable copy of the packet in which the exception occured.
Returns
Copy of the packet.
Definition at line 51 of file PacketException.cpp.
References mPacket.
int Exception::Line () const inherited
Retrieve the line number the exception occured on.
Returns
Line number the exception was thrown from.
Definition at line 345 of file Exception.cpp.
References libcomp::Exception::mLine.
Referenced by libcomp::Exception::Log(), and Log().
void PacketException::Log () const virtual
Log the exception.
This will include a dump of the packet when the exception occured.
Reimplemented from libcomp::Exception.
Definition at line 57 of file PacketException.cpp.
References libcomp::String::Arg(), libcomp::Exception::Backtrace(), libcomp::Exception::File(), GetPacket(), libcomp::String::Join(), libcomp::Exception::Line(), and libcomp::Exception::Message().
String Exception::Message () const inherited
Retrieve the message describing the exception.
Returns
Message describing the exception.
Definition at line 363 of file Exception.cpp.
References libcomp::Exception::mMessage.
Referenced by libcomp::Exception::Log(), and Log().
void Exception::RegisterSignalHandler () static inherited
Register the SIGSEGV signal handler to catch crashes.
Definition at line 415 of file Exception.cpp.
References libcomp::String::Arg(), libcomp::Exception::Backtrace(), libcomp::Log::GetSingletonPtr(), and SignalHandler().
Referenced by libcomp::Worker::Start().
Member Data Documentation
Packet libcomp::PacketException::mPacket private
Copy of the packet in which the exception occured.
Definition at line 104 of file PacketException.h.
Referenced by GetPacket(), and PacketException().
The documentation for this class was generated from the following files:
PacketException.h
PacketException.cpp