COMP_hack: libcomp::Crypto::Blowfish Class Reference
libcomp::Crypto::Blowfish Class Reference
This class will encrypt and decrypt data using the blowfish algorithm.
#include <Crypto.h>
Public Member Functions
Blowfish ()
Encrypt and decrypt with the default Blowfish key.
Blowfish (const Blowfish &other)=delete
Copy not allowed.
~Blowfish ()
Free the blowfish key.
void Decrypt (void *pData, uint32_t dataSize)
Decrypt a data buffer with Blowfish.
void Decrypt (std::vector< char > &data, std::vector< char >::size_type realSize=0)
Decrypt a data buffer with Blowfish.
void DecryptCbc (uint64_t &initializationVector, std::vector< char > &data, std::vector< char >::size_type realSize=0)
Decrypt a data buffer with Blowfish and Cipher Block Chaining (CBC).
void DecryptCbc (std::vector< char > &data, std::vector< char >::size_type realSize=0)
Decrypt a data buffer with the default Blowfish key and Cipher Block Chaining (CBC) initialization vector (IV).
void DecryptPacket (Packet &p)
Decrypt a packet.
void Encrypt (void *pData, uint32_t dataSize)
Encrypt a data buffer with Blowfish.
void Encrypt (std::vector< char > &data)
Encrypt a data buffer with Blowfish.
void EncryptCbc (uint64_t &initializationVector, std::vector< char > &data)
Encrypt a data buffer with Blowfish and Cipher Block Chaining (CBC).
void EncryptCbc (std::vector< char > &data)
Encrypt a data buffer with the default Blowfish key and Cipher Block Chaining (CBC) initialization vector (IV).
void EncryptPacket (Packet &p)
Encrypt a packet.
Blowfish & operator= (const Blowfish &other)=delete
Copy not allowed.
void SetKey (const void *pData, size_t dataSize)
Set the blowfish key.
void SetKey (const std::vector< char > &key)
Set the blowfish key.
Private Attributes
BlowfishPrivate * d
Private data for the blowfish algorithm (the key).
Detailed Description
This class will encrypt and decrypt data using the blowfish algorithm.
Definition at line 232 of file Crypto.h.
Constructor & Destructor Documentation
Crypto::Blowfish::Blowfish ()
Encrypt and decrypt with the default Blowfish key.
See Also
Config::ENCRYPTED_FILE_KEY
Definition at line 1112 of file src/Crypto.cpp.
References libcomp::Config::ENCRYPTED_FILE_KEY.
Crypto::Blowfish::~Blowfish ()
Free the blowfish key.
Definition at line 1121 of file src/Crypto.cpp.
libcomp::Crypto::Blowfish::Blowfish (const Blowfish & other) delete
Copy not allowed.
Member Function Documentation
void Crypto::Blowfish::Decrypt (void * pData, uint32_t dataSize)
Decrypt a data buffer with Blowfish.
Parameters
pData Data to be decrypted.
dataSize Size of the data to be decrypted (in bytes).
Note
The data size should be a multiple of BLOWFISH_BLOCK_SIZE.
Definition at line 1176 of file src/Crypto.cpp.
References libcomp::BLOWFISH_BLOCK_SIZE.
void Crypto::Blowfish::Decrypt (std::vector< char > & data, std::vector< char >::size_type realSize = 0)
Decrypt a data buffer with Blowfish.
Parameters
data Data to be decrypted.
realSize Size to shrink the buffer to after decryption.
Definition at line 1193 of file src/Crypto.cpp.
References libcomp::BLOWFISH_BLOCK_SIZE.
void Crypto::Blowfish::DecryptCbc (uint64_t & initializationVector, std::vector< char > & data, std::vector< char >::size_type realSize = 0)
Decrypt a data buffer with Blowfish and Cipher Block Chaining (CBC).
Parameters
initializationVector Initial value to feed into the CBC algorithm.
data Data to be decrypted.
realSize Size to shrink the buffer to after decryption.
Definition at line 1258 of file src/Crypto.cpp.
References libcomp::BLOWFISH_BLOCK_SIZE.
Referenced by libcomp::Crypto::DecryptFile().
void Crypto::Blowfish::DecryptCbc (std::vector< char > & data, std::vector< char >::size_type realSize = 0)
Decrypt a data buffer with the default Blowfish key and Cipher Block Chaining (CBC) initialization vector (IV).
Parameters
data Data to be decrypted.
realSize Size to shrink the buffer to after decryption.
See Also
Config::ENCRYPTED_FILE_KEY
Config::ENCRYPTED_FILE_IV
Definition at line 1667 of file src/Crypto.cpp.
References libcomp::Config::ENCRYPTED_FILE_IV.
void Crypto::Blowfish::DecryptPacket (Packet & p)
Decrypt a packet.
Parameters
p The packet to decrypt.
Definition at line 1710 of file src/Crypto.cpp.
References libcomp::Packet::Data(), libcomp::ReadOnlyPacket::ReadU32Big(), libcomp::ReadOnlyPacket::Rewind(), and libcomp::ReadOnlyPacket::Size().
Referenced by libcomp::EncryptedConnection::ParsePacket().
void Crypto::Blowfish::Encrypt (void * pData, uint32_t dataSize)
Encrypt a data buffer with Blowfish.
Parameters
pData Data to be encrypted.
dataSize Size of the data to be encrypted (in bytes).
Note
The data size should be a multiple of BLOWFISH_BLOCK_SIZE.
Definition at line 1133 of file src/Crypto.cpp.
References libcomp::BLOWFISH_BLOCK_SIZE.
void Crypto::Blowfish::Encrypt (std::vector< char > & data)
Encrypt a data buffer with Blowfish.
Parameters
data Data to be encrypted. The size may change on return.
Definition at line 1150 of file src/Crypto.cpp.
References libcomp::BLOWFISH_BLOCK_SIZE.
void Crypto::Blowfish::EncryptCbc (uint64_t & initializationVector, std::vector< char > & data)
Encrypt a data buffer with Blowfish and Cipher Block Chaining (CBC).
Parameters
initializationVector Initial value to feed into the CBC algorithm.
data Data to be encrypted. The size may change on return.
Definition at line 1217 of file src/Crypto.cpp.
References libcomp::BLOWFISH_BLOCK_SIZE.
Referenced by libcomp::Crypto::EncryptFile().
void Crypto::Blowfish::EncryptCbc (std::vector< char > & data)
Encrypt a data buffer with the default Blowfish key and Cipher Block Chaining (CBC) initialization vector (IV).
Parameters
data Data to be encrypted. The size may change on return.
See Also
Config::ENCRYPTED_FILE_KEY
Config::ENCRYPTED_FILE_IV
Definition at line 1659 of file src/Crypto.cpp.
References libcomp::Config::ENCRYPTED_FILE_IV.
void Crypto::Blowfish::EncryptPacket (Packet & p)
Encrypt a packet.
Parameters
p The packet to encrypt.
Definition at line 1676 of file src/Crypto.cpp.
References libcomp::BLOWFISH_BLOCK_SIZE, libcomp::Packet::Data(), libcomp::ReadOnlyPacket::End(), libcomp::ReadOnlyPacket::Rewind(), libcomp::ReadOnlyPacket::Seek(), libcomp::ReadOnlyPacket::Size(), libcomp::Packet::WriteBlank(), and libcomp::Packet::WriteU32Big().
Referenced by libcomp::ChannelConnection::PreparePackets(), and libcomp::EncryptedConnection::PreparePackets().
Blowfish& libcomp::Crypto::Blowfish::operator= (const Blowfish & other) delete
Copy not allowed.
void Crypto::Blowfish::SetKey (const void * pData, size_t dataSize)
Set the blowfish key.
Parameters
pData Pointer to the buffer with the key.
dataSize Size in bytes of the key.
Definition at line 1127 of file src/Crypto.cpp.
Referenced by libcomp::TcpConnection::SetEncryptionKey().
void Crypto::Blowfish::SetKey (const std::vector< char > & key)
Set the blowfish key.
Parameters
key Blowfish key to use.
Definition at line 1654 of file src/Crypto.cpp.
Member Data Documentation
BlowfishPrivate* libcomp::Crypto::Blowfish::d private
Private data for the blowfish algorithm (the key).
Definition at line 352 of file Crypto.h.
The documentation for this class was generated from the following files:
Crypto.h
src/Crypto.cpp