COMP_hack: libcomp::ServerCommandLineParser Class Reference
libcomp::ServerCommandLineParser Class Reference
Class to handle parsing command line arguments for a server.
#include <ServerCommandLineParser.h>
Public Types
enum ArgumentType { ArgumentType::NONE, ArgumentType::OPTIONAL, ArgumentType::REQUIRED }
Public Member Functions
ServerCommandLineParser ()
virtual ~ServerCommandLineParser ()
std::vector< String > GetStandardArguments () const
virtual bool Parse (int argc, const char *const argv[])
Protected Member Functions
virtual bool Parse (const std::vector< String > &arguments)
virtual bool ParseStandardArguments (const std::vector< String > &arguments)
virtual void RegisterArgument (char shortName, const String &longName, ArgumentType argType, std::function< bool(Argument *, const String &)> handler)
Detailed Description
Class to handle parsing command line arguments for a server.
Definition at line 42 of file ServerCommandLineParser.h.
Member Enumeration Documentation
enum libcomp::ArgumentParser::ArgumentType strong inherited
Enumerator
NONE
OPTIONAL
REQUIRED
Definition at line 52 of file ArgumentParser.h.
Constructor & Destructor Documentation
ServerCommandLineParser::ServerCommandLineParser ()
Definition at line 34 of file ServerCommandLineParser.cpp.
References libcomp::String::Arg(), libcomp::ArgumentParser::NONE, libcomp::ArgumentParser::RegisterArgument(), libcomp::ArgumentParser::REQUIRED, and libcomp::String::ToInteger().
ServerCommandLineParser::~ServerCommandLineParser () virtual
Definition at line 71 of file ServerCommandLineParser.cpp.
Member Function Documentation
std::vector< String > ArgumentParser::GetStandardArguments () const inherited
Definition at line 262 of file ArgumentParser.cpp.
References libcomp::ArgumentParser::mStandardArguments.
bool ArgumentParser::Parse (int argc, const char *const argv[]) virtual inherited
Definition at line 51 of file ArgumentParser.cpp.
References libcomp::String::IsEmpty().
bool ArgumentParser::Parse (const std::vector< String > & arguments) protected virtual inherited
Definition at line 68 of file ArgumentParser.cpp.
References libcomp::String::Arg(), libcomp::String::At(), libcomp::String::IsEmpty(), libcomp::String::Left(), libcomp::String::Length(), libcomp::String::Matches(), libcomp::String::Mid(), libcomp::ArgumentParser::mLongParsers, libcomp::ArgumentParser::mShortParsers, libcomp::ArgumentParser::NONE, libcomp::ArgumentParser::OPTIONAL, libcomp::ArgumentParser::ParseStandardArguments(), libcomp::ArgumentParser::REQUIRED, and libcomp::String::ToUtf8().
bool ArgumentParser::ParseStandardArguments (const std::vector< String > & arguments) protected virtual inherited
Definition at line 254 of file ArgumentParser.cpp.
References libcomp::ArgumentParser::mStandardArguments.
Referenced by libcomp::ArgumentParser::Parse().
void ArgumentParser::RegisterArgument (char shortName, const String & longName, ArgumentType argType, std::function< bool(Argument *, const String &)> handler) protected virtual inherited
Definition at line 235 of file ArgumentParser.cpp.
References libcomp::ArgumentParser::Argument::argType, libcomp::ArgumentParser::Argument::handler, libcomp::String::IsEmpty(), libcomp::ArgumentParser::Argument::longName, libcomp::ArgumentParser::mArgumentParsers, libcomp::ArgumentParser::mLongParsers, libcomp::ArgumentParser::mShortParsers, and libcomp::ArgumentParser::Argument::shortName.
Referenced by ServerCommandLineParser().
The documentation for this class was generated from the following files:
ServerCommandLineParser.h
ServerCommandLineParser.cpp