COMP_hack: libcomp::ScriptEngine Class Reference
libcomp::ScriptEngine Class Reference
Represents a Sqrat based Squirrel virtual machine handler to facilitate script execution and bind Object instances to the VM.
#include <ScriptEngine.h>
Public Member Functions
ScriptEngine (bool useRawPrint=false)
Create the VM.
~ScriptEngine ()
Clean up the VM.
bool Eval (const String &source, const String &sourceName=String())
Evaluate a Squirrel script block as a string.
HSQUIRRELVM GetVM ()
Get the Sqrat VM.
bool Import (const std::string &module)
Import a Squirrel binding module into the virtual machine.
bool Include (const std::string &path)
Load an include file (triggeded by a script).
void RegisterModule (const std::string &module, const std::function< bool(ScriptEngine &, const std::string &module)> &func)
Register a script module that can be imported.
std::shared_ptr< ScriptEngine > Self ()
Get a pointer to the script engine.
std::shared_ptr< const
ScriptEngine > Self () const
Get a pointer to the script engine.
template<>
ScriptEngine & Using ()
template<>
ScriptEngine & Using ()
template<class T >
ScriptEngine & Using ()
Signifies that the templated type will be used in the VM instance.
template<>
ScriptEngine & Using ()
template<>
ScriptEngine & Using ()
template<>
ScriptEngine & Using ()
template<>
ScriptEngine & Using ()
template<>
ScriptEngine & Using ()
template<>
ScriptEngine & Using ()
template<>
ScriptEngine & Using ()
template<>
ScriptEngine & Using ()
template<>
ScriptEngine & Using ()
template<>
ScriptEngine & Using ()
Static Public Member Functions
static std::shared_ptr
< ScriptEngine > Self (HSQUIRRELVM vm)
Get a pointer to the script engine from a Squirrel handle.
Private Member Functions
template<class T , class A >
void Bind (const std::string &name, Sqrat::Class< T, A > &binding)
Utility function to complete the binding of an object via ScriptEngine::Using.
bool BindingExists (const std::string &name, bool lockBinding=false)
Check if an object has already been bound.
void InitializeBuiltins ()
Initialize the built-in script modules.
Private Attributes
std::set< std::string > mBindings
Bindings that have already been made to objects via ScriptEngine::Using.
std::set< std::string > mImports
Imports that have already been made.
bool mUseRawPrint
If the logging system should be used or not.
HSQUIRRELVM mVM
The Sqrat VM.
Static Private Attributes
static std::unordered_map
< std::string, std::function
< bool(ScriptEngine &, const
std::string &module)> > mModules
Map of functions to import a script module.
Detailed Description
Represents a Sqrat based Squirrel virtual machine handler to facilitate script execution and bind Object instances to the VM.
Definition at line 56 of file ScriptEngine.h.
Constructor & Destructor Documentation
ScriptEngine::ScriptEngine (bool useRawPrint = false)
Create the VM.
Parameters
useRawPrint Set this to not prefix messages with "SQUIRREL: ".
Definition at line 214 of file src/ScriptEngine.cpp.
References libcomp::String::Arg(), InitializeBuiltins(), mModules, mVM, ScriptImport(), ScriptInclude(), SquirrelErrorFunction(), SquirrelErrorFunctionRaw(), SquirrelPrintFunction(), SquirrelPrintFunctionRaw(), ToAccount(), ToAccountWorldData(), ToCharacter(), and ToDemon().
ScriptEngine::~ScriptEngine ()
Clean up the VM.
Definition at line 268 of file src/ScriptEngine.cpp.
References mVM.
Member Function Documentation
template<class T , class A > void libcomp::ScriptEngine::Bind (const std::string & name, Sqrat::Class< T, A > & binding) inline private
Utility function to complete the binding of an object via ScriptEngine::Using.
Parameters
name The name of the binding which should match a class name
binding The object binding
Definition at line 139 of file ScriptEngine.h.
References mBindings, and mVM.
bool ScriptEngine::BindingExists (const std::string & name, bool lockBinding = false) private
Check if an object has already been bound.
Parameters
name The name of the binding to check
lockBinding Optional parameter to mark the binding as known now instead of waiting until calling ScriptEngine::Bind. Useful for static functions or when circular references can occur.
Returns
true if it was bound already, false if it was not
Definition at line 323 of file src/ScriptEngine.cpp.
References mBindings.
bool ScriptEngine::Eval (const String & source, const String & sourceName = String())
Evaluate a Squirrel script block as a string.
Parameters
source Squirrel script block as a string
Returns
true on success, false on failure
Definition at line 273 of file src/ScriptEngine.cpp.
References libcomp::String::C(), mVM, NO_RETURN_VALUE, ONE_PARAM, RAISE_ERROR, and libcomp::String::Size().
Referenced by Include(), libcomp::ServerDataManager::LoadScript(), and TEST().
HSQUIRRELVM ScriptEngine::GetVM ()
Get the Sqrat VM.
Returns
The Sqrat VM
Definition at line 296 of file src/ScriptEngine.cpp.
References mVM.
Referenced by libcomp::ServerDataManager::LoadScript(), and TEST().
bool ScriptEngine::Import (const std::string & module)
Import a Squirrel binding module into the virtual machine.
Parameters
module Name of the module to import.
Returns
true if the module was imported, false otherwise.
Definition at line 382 of file src/ScriptEngine.cpp.
References libcomp::String::Arg(), mImports, and mModules.
bool ScriptEngine::Include (const std::string & path)
Load an include file (triggeded by a script).
Parameters
path Path to the script to include.
Returns
true if the script loaded, false otherwise.
Definition at line 334 of file src/ScriptEngine.cpp.
References libcomp::String::Arg(), Eval(), libcomp::Crypto::LoadFile(), and mUseRawPrint.
void ScriptEngine::InitializeBuiltins () private
Initialize the built-in script modules.
Definition at line 424 of file src/ScriptEngine.cpp.
References libcomp::Demon, RegisterModule(), and Using().
Referenced by ScriptEngine().
void ScriptEngine::RegisterModule (const std::string & module, const std::function< bool(ScriptEngine &, const std::string &module)> & func)
Register a script module that can be imported.
Parameters
module Name of the module to import.
func Function to call to import the module.
Definition at line 418 of file src/ScriptEngine.cpp.
References mModules.
Referenced by InitializeBuiltins().
std::shared_ptr< ScriptEngine > ScriptEngine::Self ()
Get a pointer to the script engine.
Returns
Pointer to the script engine.
Definition at line 301 of file src/ScriptEngine.cpp.
Referenced by ScriptImport(), ScriptInclude(), and Self().
std::shared_ptr< const ScriptEngine > ScriptEngine::Self () const
Get a pointer to the script engine.
Returns
Pointer to the script engine.
Definition at line 306 of file src/ScriptEngine.cpp.
std::shared_ptr< ScriptEngine > ScriptEngine::Self (HSQUIRRELVM vm) static
Get a pointer to the script engine from a Squirrel handle.
Parameters
vm Squirrel handle to the virtual machine.
Returns
Pointer to the script engine.
Definition at line 311 of file src/ScriptEngine.cpp.
References Self().
template<> ScriptEngine& libcomp::ScriptEngine::Using ()
Definition at line 43 of file DataSyncManager.cpp.
References libcomp::DataSyncManager::RemoveRecord(), libcomp::DataSyncManager::SyncOutgoing(), and libcomp::DataSyncManager::UpdateRecord().
template<> ScriptEngine& libcomp::ScriptEngine::Using ()
Definition at line 45 of file Randomizer.cpp.
template<class T > ScriptEngine& libcomp::ScriptEngine::Using ()
Signifies that the templated type will be used in the VM instance.
Implementations of this function are generated by objgen when the object is flagged as "scriptEnabled". Multiple calls to this function will not bind the object multiple times.
Returns
Reference back to the engine so they can be chained
Referenced by InitializeBuiltins(), libcomp::ServerDataManager::LoadScript(), and TEST().
template<> ScriptEngine& libcomp::ScriptEngine::Using ()
Definition at line 343 of file Object.cpp.
References libcomp::Object::IsValid().
template<> ScriptEngine& libcomp::ScriptEngine::Using ()
Definition at line 360 of file src/Database.cpp.
References libcomp::Database::Close(), libcomp::Database::DeleteSingleObject(), libcomp::Database::Execute(), libcomp::Database::Exists(), libcomp::Database::GetLastError(), libcomp::Database::InsertSingleObject(), libcomp::Database::IsOpen(), libcomp::Database::Open(), libcomp::Database::TableExists(), libcomp::Database::TableHasRows(), libcomp::Database::UpdateSingleObject(), and libcomp::Database::Use().
template<> ScriptEngine& libcomp::ScriptEngine::Using ()
Definition at line 400 of file PersistentObject.cpp.
References bool, libcomp::PersistentObject::Delete(), libcomp::PersistentObject::GetTypeHashByName(), libcomp::PersistentObject::GetUUID(), libcomp::PersistentObject::Insert(), libcomp::PersistentObject::LoadObjectByUUID(), libcomp::PersistentObject::LoadObjects(), libcomp::PersistentObject::Register(), and libcomp::PersistentObject::Update().
template<> ScriptEngine& libcomp::ScriptEngine::Using ()
Definition at line 433 of file DataStore.cpp.
References libcomp::DataStore::Exists(), and libcomp::DataStore::GetError().
template<> ScriptEngine& libcomp::ScriptEngine::Using ()
Definition at line 635 of file src/Packet.cpp.
References libcomp::Packet::WriteArray(), libcomp::Packet::WriteBlank(), and libcomp::Packet::WriteU16Little().
template<> ScriptEngine& libcomp::ScriptEngine::Using ()
Definition at line 781 of file BaseServer.cpp.
References libcomp::BaseServer::GetDataStore().
template<> ScriptEngine& libcomp::ScriptEngine::Using ()
Definition at line 895 of file ServerDataManager.cpp.
References libcomp::ServerScript::Instantiated, libcomp::ServerScript::Name, and libcomp::ServerScript::Type.
template<> ScriptEngine& libcomp::ScriptEngine::Using ()
Definition at line 940 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::HexDump(), libcomp::ReadOnlyPacket::ReadArray(), libcomp::ReadOnlyPacket::Rewind(), and libcomp::ReadOnlyPacket::Size().
template<> ScriptEngine& libcomp::ScriptEngine::Using ()
Definition at line 2119 of file ServerDataManager.cpp.
References libcomp::ServerDataManager::LoadData().
template<> ScriptEngine& libcomp::ScriptEngine::Using ()
Definition at line 2151 of file DefinitionManager.cpp.
References libcomp::DefinitionManager::GetDevilData(), and libcomp::DefinitionManager::LoadAllData().
Member Data Documentation
std::set<std::string> libcomp::ScriptEngine::mBindings private
Bindings that have already been made to objects via ScriptEngine::Using.
Definition at line 164 of file ScriptEngine.h.
Referenced by Bind(), and BindingExists().
std::set<std::string> libcomp::ScriptEngine::mImports private
Imports that have already been made.
Definition at line 167 of file ScriptEngine.h.
Referenced by Import().
std::unordered_map< std::string, std::function< bool(ScriptEngine &, const std::string &module)> > ScriptEngine::mModules static private
Map of functions to import a script module.
Definition at line 174 of file ScriptEngine.h.
Referenced by Import(), RegisterModule(), and ScriptEngine().
bool libcomp::ScriptEngine::mUseRawPrint private
If the logging system should be used or not.
Definition at line 170 of file ScriptEngine.h.
Referenced by Include().
HSQUIRRELVM libcomp::ScriptEngine::mVM private
The Sqrat VM.
Definition at line 161 of file ScriptEngine.h.
Referenced by Bind(), Eval(), GetVM(), ScriptEngine(), and ~ScriptEngine().
The documentation for this class was generated from the following files:
ScriptEngine.h
BaseServer.cpp
src/Database.cpp
DataStore.cpp
DataSyncManager.cpp
DefinitionManager.cpp
Object.cpp
src/Packet.cpp
PersistentObject.cpp
Randomizer.cpp
ReadOnlyPacket.cpp
src/ScriptEngine.cpp
ServerDataManager.cpp