COMP_hack: libcomp::DatabaseQueryImpl Class Reference
libcomp::DatabaseQueryImpl Class Reference abstract
Abstract base class to be implemented by specific database types to facilitate column binding and data retrieval.
#include <DatabaseQuery.h>
Public Member Functions
DatabaseQueryImpl ()
Create the query implementation.
virtual ~DatabaseQueryImpl ()
Clean up the query implementation.
int64_t AffectedRowCount () const
Get the count of affected rows from the last query execution.
virtual bool Bind (size_t index, const String &value)=0
Bind a string column value by its index.
virtual bool Bind (const String &name, const String &value)=0
Bind a string column value by its name.
virtual bool Bind (size_t index, const std::vector< char > &value)=0
Bind a blob column value by its index.
virtual bool Bind (const String &name, const std::vector< char > &value)=0
Bind a blob column value by its name.
virtual bool Bind (size_t index, const libobjgen::UUID &value)=0
Bind a UUID column value by its index.
virtual bool Bind (const String &name, const libobjgen::UUID &value)=0
Bind a UUID column value by its name.
virtual bool Bind (size_t index, int32_t value)=0
Bind a 32-bit integer column value by its index.
virtual bool Bind (const String &name, int32_t value)=0
Bind a 32-bit integer column value by its name.
virtual bool Bind (size_t index, int64_t value)=0
Bind a 64-bit integer column value by its index.
virtual bool Bind (const String &name, int64_t value)=0
Bind a 64-bit integer column value by its name.
virtual bool Bind (size_t index, float value)=0
Bind a float column value by its index.
virtual bool Bind (const String &name, float value)=0
Bind a float column value by its name.
virtual bool Bind (size_t index, double value)=0
Bind a double column value by its index.
virtual bool Bind (const String &name, double value)=0
Bind a double column value by its name.
virtual bool Bind (size_t index, bool value)=0
Bind a boolean column value by its index.
virtual bool Bind (const String &name, bool value)=0
Bind a boolean column value by its name.
virtual bool Bind (size_t index, const std::unordered_map< std::string, std::vector< char >> &values)
Bind a map column value by its index.
virtual bool Bind (const String &name, const std::unordered_map< std::string, std::vector< char >> &values)
Bind a map column value by its name.
virtual bool Execute ()=0
Execute a previously prepared query.
virtual bool GetRows (std::list< std::unordered_map< std::string, std::vector< char >>> &rows)
Get all of the query result's rows as bytes mapped by column name.
virtual bool GetValue (size_t index, String &value)=0
Get a string column value by its index.
virtual bool GetValue (const String &name, String &value)=0
Get a string column value by its name.
virtual bool GetValue (size_t index, std::vector< char > &value)=0
Get a blob column value by its index.
virtual bool GetValue (const String &name, std::vector< char > &value)=0
Get a blob column value by its name.
virtual bool GetValue (size_t index, libobjgen::UUID &value)=0
Get a UUID column value by its index.
virtual bool GetValue (const String &name, libobjgen::UUID &value)=0
Get a UUID column value by its name.
virtual bool GetValue (size_t index, int32_t &value)=0
Get a 32-bit integer column value by its index.
virtual bool GetValue (const String &name, int32_t &value)=0
Get a 32-bit integer column value by its name.
virtual bool GetValue (size_t index, int64_t &value)=0
Get a 64-bit integer column value by its index.
virtual bool GetValue (const String &name, int64_t &value)=0
Get a boolean column value by its name.
virtual bool GetValue (size_t index, float &value)=0
Get a float column value by its index.
virtual bool GetValue (const String &name, float &value)=0
Get a float column value by its name.
virtual bool GetValue (size_t index, double &value)=0
Get a double column value by its index.
virtual bool GetValue (const String &name, double &value)=0
Get a double column value by its name.
virtual bool GetValue (size_t index, bool &value)=0
Get a boolean column value by its index.
virtual bool GetValue (const String &name, bool &value)=0
Get a boolean column value by its name.
virtual bool IsValid () const =0
Check current query state validity.
virtual bool Next ()=0
Increment the query results to look at the next result set row.
virtual bool Prepare (const String &query)=0
Prepare a database query for execution based upon query text.
Protected Attributes
int64_t mAffectedRowCount
Represents the number of affected rows since the last sucessful call to Execute.
Detailed Description
Abstract base class to be implemented by specific database types to facilitate column binding and data retrieval.
See Also
DatabaseQuery
Definition at line 49 of file DatabaseQuery.h.
Constructor & Destructor Documentation
DatabaseQueryImpl::DatabaseQueryImpl ()
Create the query implementation.
Definition at line 33 of file DatabaseQuery.cpp.
DatabaseQueryImpl::~DatabaseQueryImpl () virtual
Clean up the query implementation.
Definition at line 37 of file DatabaseQuery.cpp.
Member Function Documentation
int64_t DatabaseQueryImpl::AffectedRowCount () const
Get the count of affected rows from the last query execution.
Returns
Number of affected rows
Definition at line 67 of file DatabaseQuery.cpp.
References mAffectedRowCount.
Referenced by libcomp::DatabaseQuery::AffectedRowCount().
virtual bool libcomp::DatabaseQueryImpl::Bind (size_t index, const String & value) pure virtual
Bind a string column value by its index.
Parameters
index The column's index
value The value to bind
Returns
true on success, false on failure
Implemented in libcomp::DatabaseQueryMariaDB, and libcomp::DatabaseQuerySQLite3.
Referenced by libcomp::DatabaseQuery::Bind().
virtual bool libcomp::DatabaseQueryImpl::Bind (const String & name, const String & value) pure virtual
Bind a string column value by its name.
Parameters
name The column's name
value The value to bind
Returns
true on success, false on failure
Implemented in libcomp::DatabaseQueryMariaDB, and libcomp::DatabaseQuerySQLite3.
virtual bool libcomp::DatabaseQueryImpl::Bind (size_t index, const std::vector< char > & value) pure virtual
Bind a blob column value by its index.
Parameters
index The column's index
value The value to bind
Returns
true on success, false on failure
Implemented in libcomp::DatabaseQueryMariaDB, and libcomp::DatabaseQuerySQLite3.
virtual bool libcomp::DatabaseQueryImpl::Bind (const String & name, const std::vector< char > & value) pure virtual
Bind a blob column value by its name.
Parameters
name The column's name
value The value to bind
Returns
true on success, false on failure
Implemented in libcomp::DatabaseQueryMariaDB, and libcomp::DatabaseQuerySQLite3.
virtual bool libcomp::DatabaseQueryImpl::Bind (size_t index, const libobjgen::UUID & value) pure virtual
Bind a UUID column value by its index.
Parameters
index The column's index
value The value to bind
Returns
true on success, false on failure
Implemented in libcomp::DatabaseQueryMariaDB, and libcomp::DatabaseQuerySQLite3.
virtual bool libcomp::DatabaseQueryImpl::Bind (const String & name, const libobjgen::UUID & value) pure virtual
Bind a UUID column value by its name.
Parameters
name The column's name
value The value to bind
Returns
true on success, false on failure
Implemented in libcomp::DatabaseQueryMariaDB, and libcomp::DatabaseQuerySQLite3.
virtual bool libcomp::DatabaseQueryImpl::Bind (size_t index, int32_t value) pure virtual
Bind a 32-bit integer column value by its index.
Parameters
index The column's index
value The value to bind
Returns
true on success, false on failure
Implemented in libcomp::DatabaseQueryMariaDB, and libcomp::DatabaseQuerySQLite3.
virtual bool libcomp::DatabaseQueryImpl::Bind (const String & name, int32_t value) pure virtual
Bind a 32-bit integer column value by its name.
Parameters
name The column's name
value The value to bind
Returns
true on success, false on failure
Implemented in libcomp::DatabaseQueryMariaDB, and libcomp::DatabaseQuerySQLite3.
virtual bool libcomp::DatabaseQueryImpl::Bind (size_t index, int64_t value) pure virtual
Bind a 64-bit integer column value by its index.
Parameters
index The column's index
value The value to bind
Returns
true on success, false on failure
Implemented in libcomp::DatabaseQueryMariaDB, and libcomp::DatabaseQuerySQLite3.
virtual bool libcomp::DatabaseQueryImpl::Bind (const String & name, int64_t value) pure virtual
Bind a 64-bit integer column value by its name.
Parameters
name The column's name
value The value to bind
Returns
true on success, false on failure
Implemented in libcomp::DatabaseQueryMariaDB, and libcomp::DatabaseQuerySQLite3.
virtual bool libcomp::DatabaseQueryImpl::Bind (size_t index, float value) pure virtual
Bind a float column value by its index.
Parameters
index The column's index
value The value to bind
Returns
true on success, false on failure
Implemented in libcomp::DatabaseQueryMariaDB, and libcomp::DatabaseQuerySQLite3.
virtual bool libcomp::DatabaseQueryImpl::Bind (const String & name, float value) pure virtual
Bind a float column value by its name.
Parameters
name The column's name
value The value to bind
Returns
true on success, false on failure
Implemented in libcomp::DatabaseQueryMariaDB, and libcomp::DatabaseQuerySQLite3.
virtual bool libcomp::DatabaseQueryImpl::Bind (size_t index, double value) pure virtual
Bind a double column value by its index.
Parameters
index The column's index
value The value to bind
Returns
true on success, false on failure
Implemented in libcomp::DatabaseQueryMariaDB, and libcomp::DatabaseQuerySQLite3.
virtual bool libcomp::DatabaseQueryImpl::Bind (const String & name, double value) pure virtual
Bind a double column value by its name.
Parameters
name The column's name
value The value to bind
Returns
true on success, false on failure
Implemented in libcomp::DatabaseQueryMariaDB, and libcomp::DatabaseQuerySQLite3.
virtual bool libcomp::DatabaseQueryImpl::Bind (size_t index, bool value) pure virtual
Bind a boolean column value by its index.
Parameters
index The column's index
value The value to bind
Returns
true on success, false on failure
Implemented in libcomp::DatabaseQueryMariaDB, and libcomp::DatabaseQuerySQLite3.
virtual bool libcomp::DatabaseQueryImpl::Bind (const String & name, bool value) pure virtual
Bind a boolean column value by its name.
Parameters
name The column's name
value The value to bind
Returns
true on success, false on failure
Implemented in libcomp::DatabaseQueryMariaDB, and libcomp::DatabaseQuerySQLite3.
bool DatabaseQueryImpl::Bind (size_t index, const std::unordered_map< std::string, std::vector< char >> & values) virtual
Bind a map column value by its index.
Parameters
index The column's index
values The value to bind
Returns
true on success, false on failure
Reimplemented in libcomp::DatabaseQueryMariaDB, and libcomp::DatabaseQuerySQLite3.
Definition at line 41 of file DatabaseQuery.cpp.
bool DatabaseQueryImpl::Bind (const String & name, const std::unordered_map< std::string, std::vector< char >> & values) virtual
Bind a map column value by its name.
Parameters
name The column's name
values The value to bind
Returns
true on success, false on failure
Reimplemented in libcomp::DatabaseQueryMariaDB, and libcomp::DatabaseQuerySQLite3.
Definition at line 50 of file DatabaseQuery.cpp.
virtual bool libcomp::DatabaseQueryImpl::Execute () pure virtual
Execute a previously prepared query.
See Also
DatabaseQueryImpl::Prepare
Returns
true on success, false on failure
Implemented in libcomp::DatabaseQueryMariaDB, and libcomp::DatabaseQuerySQLite3.
Referenced by libcomp::DatabaseQuery::Execute().
bool DatabaseQueryImpl::GetRows (std::list< std::unordered_map< std::string, std::vector< char >>> & rows) virtual
Get all of the query result's rows as bytes mapped by column name.
Parameters
rows Output map to insert a row with each column's bytes mapped by column name
Returns
true on success, false on failure
Reimplemented in libcomp::DatabaseQueryMariaDB, and libcomp::DatabaseQuerySQLite3.
Definition at line 59 of file DatabaseQuery.cpp.
Referenced by libcomp::DatabaseQuery::GetRows().
virtual bool libcomp::DatabaseQueryImpl::GetValue (size_t index, String & value) pure virtual
Get a string column value by its index.
Parameters
index The column's index
value Variable to bind the value to
Returns
true on success, false on failure
Implemented in libcomp::DatabaseQueryMariaDB, and libcomp::DatabaseQuerySQLite3.
Referenced by libcomp::DatabaseQuery::GetValue().
virtual bool libcomp::DatabaseQueryImpl::GetValue (const String & name, String & value) pure virtual
Get a string column value by its name.
Parameters
name The column's name
value Variable to bind the value to
Returns
true on success, false on failure
Implemented in libcomp::DatabaseQueryMariaDB, and libcomp::DatabaseQuerySQLite3.
virtual bool libcomp::DatabaseQueryImpl::GetValue (size_t index, std::vector< char > & value) pure virtual
Get a blob column value by its index.
Parameters
index The column's index
value Variable to bind the value to
Returns
true on success, false on failure
Implemented in libcomp::DatabaseQueryMariaDB, and libcomp::DatabaseQuerySQLite3.
virtual bool libcomp::DatabaseQueryImpl::GetValue (const String & name, std::vector< char > & value) pure virtual
Get a blob column value by its name.
Parameters
name The column's name
value Variable to bind the value to
Returns
true on success, false on failure
Implemented in libcomp::DatabaseQueryMariaDB, and libcomp::DatabaseQuerySQLite3.
virtual bool libcomp::DatabaseQueryImpl::GetValue (size_t index, libobjgen::UUID & value) pure virtual
Get a UUID column value by its index.
Parameters
index The column's index
value Variable to bind the value to
Returns
true on success, false on failure
Implemented in libcomp::DatabaseQueryMariaDB, and libcomp::DatabaseQuerySQLite3.
virtual bool libcomp::DatabaseQueryImpl::GetValue (const String & name, libobjgen::UUID & value) pure virtual
Get a UUID column value by its name.
Parameters
name The column's name
value Variable to bind the value to
Returns
true on success, false on failure
Implemented in libcomp::DatabaseQueryMariaDB, and libcomp::DatabaseQuerySQLite3.
virtual bool libcomp::DatabaseQueryImpl::GetValue (size_t index, int32_t & value) pure virtual
Get a 32-bit integer column value by its index.
Parameters
index The column's index
value Variable to bind the value to
Returns
true on success, false on failure
Implemented in libcomp::DatabaseQueryMariaDB, and libcomp::DatabaseQuerySQLite3.
virtual bool libcomp::DatabaseQueryImpl::GetValue (const String & name, int32_t & value) pure virtual
Get a 32-bit integer column value by its name.
Parameters
name The column's name
value Variable to bind the value to
Returns
true on success, false on failure
Implemented in libcomp::DatabaseQueryMariaDB, and libcomp::DatabaseQuerySQLite3.
virtual bool libcomp::DatabaseQueryImpl::GetValue (size_t index, int64_t & value) pure virtual
Get a 64-bit integer column value by its index.
Parameters
index The column's index
value Variable to bind the value to
Returns
true on success, false on failure
Implemented in libcomp::DatabaseQueryMariaDB, and libcomp::DatabaseQuerySQLite3.
virtual bool libcomp::DatabaseQueryImpl::GetValue (const String & name, int64_t & value) pure virtual
Get a boolean column value by its name.
Parameters
name The column's name
value Variable to bind the value to
Returns
true on success, false on failure
Implemented in libcomp::DatabaseQueryMariaDB, and libcomp::DatabaseQuerySQLite3.
virtual bool libcomp::DatabaseQueryImpl::GetValue (size_t index, float & value) pure virtual
Get a float column value by its index.
Parameters
index The column's index
value Variable to bind the value to
Returns
true on success, false on failure
Implemented in libcomp::DatabaseQueryMariaDB, and libcomp::DatabaseQuerySQLite3.
virtual bool libcomp::DatabaseQueryImpl::GetValue (const String & name, float & value) pure virtual
Get a float column value by its name.
Parameters
name The column's name
value Variable to bind the value to
Returns
true on success, false on failure
Implemented in libcomp::DatabaseQueryMariaDB, and libcomp::DatabaseQuerySQLite3.
virtual bool libcomp::DatabaseQueryImpl::GetValue (size_t index, double & value) pure virtual
Get a double column value by its index.
Parameters
index The column's index
value Variable to bind the value to
Returns
true on success, false on failure
Implemented in libcomp::DatabaseQueryMariaDB, and libcomp::DatabaseQuerySQLite3.
virtual bool libcomp::DatabaseQueryImpl::GetValue (const String & name, double & value) pure virtual
Get a double column value by its name.
Parameters
name The column's name
value Variable to bind the value to
Returns
true on success, false on failure
Implemented in libcomp::DatabaseQueryMariaDB, and libcomp::DatabaseQuerySQLite3.
virtual bool libcomp::DatabaseQueryImpl::GetValue (size_t index, bool & value) pure virtual
Get a boolean column value by its index.
Parameters
index The column's index
value Variable to bind the value to
Returns
true on success, false on failure
Implemented in libcomp::DatabaseQueryMariaDB, and libcomp::DatabaseQuerySQLite3.
virtual bool libcomp::DatabaseQueryImpl::GetValue (const String & name, bool & value) pure virtual
Get a boolean column value by its name.
Parameters
name The column's name
value Variable to bind the value to
Returns
true on success, false on failure
Implemented in libcomp::DatabaseQueryMariaDB, and libcomp::DatabaseQuerySQLite3.
virtual bool libcomp::DatabaseQueryImpl::IsValid () const pure virtual
Check current query state validity.
Returns
true on valid, false on invalid
Implemented in libcomp::DatabaseQueryMariaDB, and libcomp::DatabaseQuerySQLite3.
Referenced by libcomp::DatabaseQuery::IsValid().
virtual bool libcomp::DatabaseQueryImpl::Next () pure virtual
Increment the query results to look at the next result set row.
Returns
true on success, false on failure
Implemented in libcomp::DatabaseQueryMariaDB, and libcomp::DatabaseQuerySQLite3.
Referenced by libcomp::DatabaseQuery::Next().
virtual bool libcomp::DatabaseQueryImpl::Prepare (const String & query) pure virtual
Prepare a database query for execution based upon query text.
See Also
DatabaseQueryImpl::Execute
Parameters
query Query text to prepare
Returns
true on success, false on failure
Implemented in libcomp::DatabaseQueryMariaDB, and libcomp::DatabaseQuerySQLite3.
Referenced by libcomp::DatabaseQuery::Prepare().
Member Data Documentation
int64_t libcomp::DatabaseQueryImpl::mAffectedRowCount protected
Represents the number of affected rows since the last sucessful call to Execute.
Definition at line 383 of file DatabaseQuery.h.
Referenced by AffectedRowCount(), libcomp::DatabaseQuerySQLite3::Execute(), and libcomp::DatabaseQueryMariaDB::Execute().
The documentation for this class was generated from the following files:
DatabaseQuery.h
DatabaseQuery.cpp