COMP_hack: libcomp::DatabaseMariaDB Class Reference
libcomp::DatabaseMariaDB Class Reference
Represents a MariaDB database connection via the supplied config.
#include <DatabaseMariaDB.h>
Public Member Functions
DatabaseMariaDB (const std::shared_ptr< objects::DatabaseConfigMariaDB > &config)
Create a new MariaDB Database connection.
virtual ~DatabaseMariaDB ()
Close and clean up the database connection.
virtual bool ApplyMigration (const std::shared_ptr< BaseServer > &server, DataStore *pDataStore, const libcomp::String &migration, const libcomp::String &path)
Apply a database migration script.
virtual bool Close ()
Close dall database connections.
bool Close (MYSQL *&connection)
Close the specified database connection.
virtual bool DeleteObjects (std::list< std::shared_ptr< PersistentObject >> &objs)
Delete multiple PersistentObject instances from the database at once.
virtual bool DeleteSingleObject (std::shared_ptr< PersistentObject > &obj)
Delete one PersistentObject instance from the database.
virtual bool Execute (const String &query)
Prepare and execute a database query for execution based upon query text.
virtual bool Exists ()
Check if the database exists.
std::shared_ptr
< objects::DatabaseConfig > GetConfig () const
Get the database config.
virtual String GetLastError ()
Retrieve the last error raised by a database operation.
String GetLastError (MYSQL *pConnection)
Retrieve the last error raised by a database operation.
virtual bool InsertSingleObject (std::shared_ptr< PersistentObject > &obj)
Insert one PersistentObject instance into the database.
virtual bool IsOpen () const
Check if the connection to the database is open.
virtual std::list
< std::shared_ptr
< PersistentObject > > LoadObjects (size_t typeHash, DatabaseBind *pValue)
Load multiple PersistentObject instances from a single bound database column and value to select upon.
virtual std::shared_ptr
< PersistentObject > LoadSingleObject (size_t typeHash, DatabaseBind *pValue)
Load one PersistentObject instance from a single bound database column and value to select upon.
virtual bool Open ()
Open or create the database for use.
virtual DatabaseQuery Prepare (const String &query)
Prepare a database query for execution based upon query text.
bool ProcessChangeSet (const std::shared_ptr< DatabaseChangeSet > &changes)
Process one or many database changes as a single transaction.
std::list< libobjgen::UUID > ProcessTransactionQueue ()
Pop and process all transactions stored in the transaction queue.
bool QueueChangeSet (const std::shared_ptr< DatabaseChangeSet > &changes)
Queue a set of changes to execute during the next call to ProcessTransactionQueue.
void QueueDelete (std::shared_ptr< PersistentObject > obj, const libobjgen::UUID &uuid=NULLUUID)
Queue an object to delete during the next call to ProcessTransactionQueue.
void QueueInsert (std::shared_ptr< PersistentObject > obj, const libobjgen::UUID &uuid=NULLUUID)
Queue an object to insert during the next call to ProcessTransactionQueue.
void QueueUpdate (std::shared_ptr< PersistentObject > obj, const libobjgen::UUID &uuid=NULLUUID)
Queue an object to update during the next call to ProcessTransactionQueue.
virtual bool Setup (bool rebuild=false, const std::shared_ptr< BaseServer > &server={}, DataStore *pDataStore=nullptr, const std::string &migrationDirectory=std::string())
Setup the database schema and perform all validation steps.
virtual bool TableExists (const libcomp::String &table)
Check if a table exists.
virtual bool TableHasRows (const String &table)
Check if the supplied table name exists and has at least one row.
virtual bool UpdateSingleObject (std::shared_ptr< PersistentObject > &obj)
Update all fields on one PersistentObject instance in the database.
virtual bool Use ()
Use the database schema, keyspace, namespace, etc.
bool UsingDefaultDatabaseType ()
Check if the config is for the default database type.
bool VerifyAndSetupSchema (bool recreateTables=false)
Verify/create any missing tables based off of PersistentObject types used by the database as well as any utility tables needed.
Protected Member Functions
std::vector< std::shared_ptr
< libobjgen::MetaObject > > GetMappedObjects ()
Get the list of objects mapped to the current database type configured for the database.
std::shared_ptr< PersistentObject > LoadSingleObjectFromRow (size_t typeHash, DatabaseQuery &query)
Get a pointer to a new PersistentObject of the specified type populated with the current row being read from a database query.
virtual bool ProcessOperationalChangeSet (const std::shared_ptr< DBOperationalChangeSet > &changes)
Process an operational change set as a single transaction.
virtual bool ProcessStandardChangeSet (const std::shared_ptr< DBStandardChangeSet > &changes)
Process one or many standard database changes as a single transaction.
Protected Attributes
std::shared_ptr
< objects::DatabaseConfig > mConfig
Pointer to the config file used to configure the database connection.
String mError
Last error raised by a database related action.
Private Member Functions
bool ConnectToDatabase (MYSQL *&connection, const libcomp::String &databaseName)
Establish a connection to a MariaDB database.
MYSQL *& GetConnection (bool autoConnect)
Get a connection for the executing thread.
String GetVariableType (const std::shared_ptr< libobjgen::MetaVariable > var)
Get the MariaDB type represented by a MetaVariable type.
bool ProcessExplicitUpdate (const std::shared_ptr< DBExplicitUpdate > &update)
Process and explicit update to a single record, checking each column's state before and verifying it set to the expected value afterwards.
Private Attributes
std::mutex mConnectionLock
Mutex to lock access to the database connection map.
std::unordered_map
< std::thread::id, MYSQL * > mConnections
Pointers to the MariaDB representation of a database connection per thread.
Detailed Description
Represents a MariaDB database connection via the supplied config.
Definition at line 50 of file DatabaseMariaDB.h.
Constructor & Destructor Documentation
DatabaseMariaDB::DatabaseMariaDB (const std::shared_ptr< objects::DatabaseConfigMariaDB > & config)
Create a new MariaDB Database connection.
Parameters
config Pointer to a database configuration
Definition at line 53 of file DatabaseMariaDB.cpp.
DatabaseMariaDB::~DatabaseMariaDB () virtual
Close and clean up the database connection.
Definition at line 59 of file DatabaseMariaDB.cpp.
References Close().
Member Function Documentation
bool Database::ApplyMigration (const std::shared_ptr< BaseServer > & server, DataStore * pDataStore, const libcomp::String & migration, const libcomp::String & path) virtual inherited
Apply a database migration script.
Parameters
server Server to pass to the script.
pDataStore Data store to read the script from.
migration Name of the migration.
path Path to the script in the data store.
Returns
true if the migration was applied; false otherwise.
Definition at line 298 of file src/Database.cpp.
References libcomp::String::Arg(), and libcomp::DataStore::ReadFile().
Referenced by libcomp::DatabaseSQLite3::Setup(), and Setup().
bool DatabaseMariaDB::Close () virtual
Close dall database connections.
Returns
true on success, false on failure
Implements libcomp::Database.
Definition at line 69 of file DatabaseMariaDB.cpp.
References mConnectionLock, and mConnections.
Referenced by ConnectToDatabase(), TEST(), and ~DatabaseMariaDB().
bool DatabaseMariaDB::Close (MYSQL *& connection)
Close the specified database connection.
Parameters
connection Pointer to the connection to close
Returns
true on success, false on failure
Definition at line 83 of file DatabaseMariaDB.cpp.
References libcomp::String::Arg(), and ConnectionString().
bool DatabaseMariaDB::ConnectToDatabase (MYSQL *& connection, const libcomp::String & databaseName) private
Establish a connection to a MariaDB database.
Parameters
connection Pointer to database connection to connect with
databaseName Name of the database to connect to on the configured host
Returns
true if the connection succeeded, false if it did not
Definition at line 1394 of file DatabaseMariaDB.cpp.
References libcomp::String::Arg(), libcomp::String::C(), Close(), ConnectionString(), libcomp::String::IsEmpty(), and libcomp::Database::mConfig.
Referenced by GetConnection(), Open(), and Use().
bool DatabaseMariaDB::DeleteObjects (std::list< std::shared_ptr< PersistentObject >> & objs) virtual
Delete multiple PersistentObject instances from the database at once.
Parameters
objs List of ointers to the objects to delete
Returns
true on success, false on failure
Implements libcomp::Database.
Definition at line 619 of file DatabaseMariaDB.cpp.
References libcomp::Database::Execute(), and libcomp::String::Join().
Referenced by ProcessStandardChangeSet().
bool Database::DeleteSingleObject (std::shared_ptr< PersistentObject > & obj) virtual inherited
Delete one PersistentObject instance from the database.
Parameters
obj Pointer to the object to delete
Returns
true on success, false on failure
Definition at line 101 of file src/Database.cpp.
References libcomp::Database::DeleteObjects().
Referenced by libcomp::DatabaseSQLite3::ProcessOperationalChangeSet(), ProcessOperationalChangeSet(), and libcomp::ScriptEngine::Using().
bool Database::Execute (const String & query) virtual inherited
Prepare and execute a database query for execution based upon query text.
Queries that return results should not use this function since a query is not returned to retrieve the results from.
Parameters
query Query text to prepare and execute
Returns
true on success, false on error
Definition at line 48 of file src/Database.cpp.
References libcomp::DatabaseQuery::Execute(), and libcomp::Database::Prepare().
Referenced by libcomp::DatabaseSQLite3::DeleteObjects(), DeleteObjects(), libcomp::DatabaseSQLite3::ProcessOperationalChangeSet(), libcomp::DatabaseSQLite3::ProcessStandardChangeSet(), libcomp::DatabaseSQLite3::Setup(), Setup(), TEST(), libcomp::ScriptEngine::Using(), libcomp::DatabaseSQLite3::VerifyAndSetupSchema(), and VerifyAndSetupSchema().
bool DatabaseMariaDB::Exists () virtual
Check if the database exists.
Returns
true if it exists, false if it does not
Implements libcomp::Database.
Definition at line 121 of file DatabaseMariaDB.cpp.
References libcomp::String::Arg(), libcomp::DatabaseQuery::Execute(), GetLastError(), libcomp::DatabaseQuery::GetRows(), libcomp::Database::mConfig, libcomp::DatabaseQuery::Next(), and Prepare().
Referenced by Setup().
std::shared_ptr< objects::DatabaseConfig > Database::GetConfig () const inherited
Get the database config.
Returns
Pointer to the database config
Definition at line 58 of file src/Database.cpp.
References libcomp::Database::mConfig.
MYSQL *& DatabaseMariaDB::GetConnection (bool autoConnect) private
Get a connection for the executing thread.
Parameters
autoConnect true if the connection should be established before returning it, false if it should just return the conection reference
Returns
Reference to the executing thread's connection pointer
Definition at line 1460 of file DatabaseMariaDB.cpp.
References ConnectToDatabase(), libcomp::Database::mConfig, mConnectionLock, and mConnections.
Referenced by GetLastError(), Open(), Prepare(), ProcessOperationalChangeSet(), ProcessStandardChangeSet(), and Use().
String DatabaseMariaDB::GetLastError () virtual
Retrieve the last error raised by a database operation.
Returns
The last error that occurred
Reimplemented from libcomp::Database.
Definition at line 1517 of file DatabaseMariaDB.cpp.
References GetConnection().
Referenced by Exists(), InsertSingleObject(), LoadObjects(), ProcessExplicitUpdate(), ProcessOperationalChangeSet(), ProcessStandardChangeSet(), Setup(), and UpdateSingleObject().
String DatabaseMariaDB::GetLastError (MYSQL * pConnection)
Retrieve the last error raised by a database operation.
Parameters
pConnection Connection to get the error for.
Returns
The last error that occurred
Definition at line 1534 of file DatabaseMariaDB.cpp.
std::vector< std::shared_ptr< libobjgen::MetaObject > > Database::GetMappedObjects () protected inherited
Get the list of objects mapped to the current database type configured for the database.
Returns
List of pointers to object definitions with a source set to the current database type
Definition at line 282 of file src/Database.cpp.
References libcomp::PersistentObject::GetRegistry(), libcomp::Database::mConfig, and libcomp::Database::UsingDefaultDatabaseType().
Referenced by libcomp::DatabaseSQLite3::VerifyAndSetupSchema(), and VerifyAndSetupSchema().
String DatabaseMariaDB::GetVariableType (const std::shared_ptr< libobjgen::MetaVariable > var) private
Get the MariaDB type represented by a MetaVariable type.
Parameters
var Metadata variable containing a type to conver to a MariaDB type
Returns
Data type string representing a MariaDB type
Definition at line 1480 of file DatabaseMariaDB.cpp.
Referenced by VerifyAndSetupSchema().
bool DatabaseMariaDB::InsertSingleObject (std::shared_ptr< PersistentObject > & obj) virtual
Insert one PersistentObject instance into the database.
Parameters
obj Pointer to the object to insert
Returns
true on success, false on failure
Implements libcomp::Database.
Definition at line 415 of file DatabaseMariaDB.cpp.
References libcomp::String::Arg(), libcomp::DatabaseQuery::Bind(), libcomp::DatabaseQuery::Execute(), GetLastError(), libcomp::DatabaseQuery::IsValid(), libcomp::String::Join(), and Prepare().
Referenced by ProcessOperationalChangeSet(), and ProcessStandardChangeSet().
bool DatabaseMariaDB::IsOpen () const virtual
Check if the connection to the database is open.
Returns
true if it is open, false if it is not
Implements libcomp::Database.
Definition at line 109 of file DatabaseMariaDB.cpp.
References mConnections.
Referenced by Setup(), and TEST().
std::list< std::shared_ptr< PersistentObject > > DatabaseMariaDB::LoadObjects (size_t typeHash, DatabaseBind * pValue) virtual
Load multiple PersistentObject instances from a single bound database column and value to select upon.
Parameters
typeHash C++ type hash representing the object type to load
pValue Database specific agnostic binding
Returns
List of pointers to loaded objects from the query results
Implements libcomp::Database.
Definition at line 319 of file DatabaseMariaDB.cpp.
References libcomp::String::Arg(), libcomp::DatabaseBind::Bind(), libcomp::DatabaseQuery::Execute(), libcomp::DatabaseBind::GetColumn(), GetLastError(), libcomp::PersistentObject::GetRegisteredMetadata(), libcomp::DatabaseQuery::IsValid(), libcomp::Database::LoadSingleObjectFromRow(), libcomp::DatabaseQuery::Next(), and Prepare().
std::shared_ptr< PersistentObject > Database::LoadSingleObject (size_t typeHash, DatabaseBind * pValue) virtual inherited
Load one PersistentObject instance from a single bound database column and value to select upon.
This simply filters down the results of LoadObjects to the first record so it should be used only when the value being bound to is unique.
Parameters
typeHash C++ type hash representing the object type to load
pValue Database agnostic column binding
Returns
Pointer to the first loaded object from the query results
Definition at line 93 of file src/Database.cpp.
References libcomp::Database::LoadObjects().
Referenced by libcomp::DatabaseSQLite3::ProcessOperationalChangeSet(), and ProcessOperationalChangeSet().
std::shared_ptr< PersistentObject > Database::LoadSingleObjectFromRow (size_t typeHash, DatabaseQuery & query) protected inherited
Get a pointer to a new PersistentObject of the specified type populated with the current row being read from a database query.
Parameters
typeHash C++ type hash of object to load
query Current query to use results from
Returns
Pointer to the new object
Definition at line 249 of file src/Database.cpp.
References libcomp::PersistentObject::GetObjectByUUID(), libcomp::DatabaseQuery::GetValue(), libcomp::PersistentObject::New(), and libcomp::PersistentObject::Register().
Referenced by libcomp::DatabaseSQLite3::LoadObjects(), and LoadObjects().
bool DatabaseMariaDB::Open () virtual
Open or create the database for use.
Returns
true on success, false on failure
Implements libcomp::Database.
Definition at line 64 of file DatabaseMariaDB.cpp.
References ConnectToDatabase(), and GetConnection().
Referenced by TEST().
DatabaseQuery DatabaseMariaDB::Prepare (const String & query) virtual
Prepare a database query for execution based upon query text.
Parameters
query Query text to prepare
Returns
Prepared query
Implements libcomp::Database.
Definition at line 115 of file DatabaseMariaDB.cpp.
References GetConnection().
Referenced by Exists(), InsertSingleObject(), LoadObjects(), ProcessExplicitUpdate(), Setup(), TableExists(), TEST(), UpdateSingleObject(), and VerifyAndSetupSchema().
bool Database::ProcessChangeSet (const std::shared_ptr< DatabaseChangeSet > & changes) inherited
Process one or many database changes as a single transaction.
Parameters
changes Grouping of changes to apply to the database
Returns
true on success, false on failure
Definition at line 224 of file src/Database.cpp.
References libcomp::Database::ProcessOperationalChangeSet(), and libcomp::Database::ProcessStandardChangeSet().
Referenced by libcomp::Database::ProcessTransactionQueue(), and TEST().
bool DatabaseMariaDB::ProcessExplicitUpdate (const std::shared_ptr< DBExplicitUpdate > & update) private
Process and explicit update to a single record, checking each column's state before and verifying it set to the expected value afterwards.
Parameters
update Pointer to the explicit update
Returns
true if the the updated succeeded, false if it did not
Definition at line 1270 of file DatabaseMariaDB.cpp.
References libcomp::DatabaseQuery::AffectedRowCount(), libcomp::String::Arg(), libcomp::DatabaseQuery::Bind(), libcomp::DatabaseQuery::Execute(), GetLastError(), libcomp::DatabaseQuery::IsValid(), libcomp::String::Join(), and Prepare().
Referenced by ProcessOperationalChangeSet().
bool DatabaseMariaDB::ProcessOperationalChangeSet (const std::shared_ptr< DBOperationalChangeSet > & changes) protected virtual
Process an operational change set as a single transaction.
Parameters
changes Grouping of changes to apply to the database
Returns
true on success, false on failure
Implements libcomp::Database.
Definition at line 1142 of file DatabaseMariaDB.cpp.
References libcomp::String::Arg(), ConnectionString(), libcomp::DBOperationalChange::DBOP_DELETE, libcomp::DBOperationalChange::DBOP_EXPLICIT, libcomp::DBOperationalChange::DBOP_INSERT, libcomp::DBOperationalChange::DBOP_UPDATE, libcomp::Database::DeleteSingleObject(), GetConnection(), GetLastError(), libcomp::PersistentObject::GetTypeHashByName(), InsertSingleObject(), libcomp::Database::LoadSingleObject(), ProcessExplicitUpdate(), and UpdateSingleObject().
bool DatabaseMariaDB::ProcessStandardChangeSet (const std::shared_ptr< DBStandardChangeSet > & changes) protected virtual
Process one or many standard database changes as a single transaction.
Parameters
changes Grouping of changes to apply to the database
Returns
true on success, false on failure
Implements libcomp::Database.
Definition at line 1031 of file DatabaseMariaDB.cpp.
References libcomp::String::Arg(), ConnectionString(), DeleteObjects(), GetConnection(), GetLastError(), InsertSingleObject(), and UpdateSingleObject().
std::list< libobjgen::UUID > Database::ProcessTransactionQueue () inherited
Pop and process all transactions stored in the transaction queue.
Returns
List of all transaction group UUIDs that failed to process
Definition at line 183 of file src/Database.cpp.
References libcomp::Database::mTransactionLock, libcomp::Database::mTransactionQueue, and libcomp::Database::ProcessChangeSet().
bool Database::QueueChangeSet (const std::shared_ptr< DatabaseChangeSet > & changes) inherited
Queue a set of changes to execute during the next call to ProcessTransactionQueue.
Parameters
changes DatabaseChangeSet to queue for processing
Returns
true on success, false on failure
Definition at line 132 of file src/Database.cpp.
References libcomp::Database::mTransactionLock, and libcomp::Database::mTransactionQueue.
Referenced by libcomp::Database::QueueDelete(), libcomp::Database::QueueInsert(), and libcomp::Database::QueueUpdate().
void Database::QueueDelete (std::shared_ptr< PersistentObject > obj, const libobjgen::UUID & uuid = NULLUUID) inherited
Queue an object to delete during the next call to ProcessTransactionQueue.
Parameters
obj Pointer to the object to delete
uuid UUID used to group changes together
Definition at line 124 of file src/Database.cpp.
References libcomp::DatabaseChangeSet::Create(), and libcomp::Database::QueueChangeSet().
void Database::QueueInsert (std::shared_ptr< PersistentObject > obj, const libobjgen::UUID & uuid = NULLUUID) inherited
Queue an object to insert during the next call to ProcessTransactionQueue.
Parameters
obj Pointer to the object to insert
uuid UUID used to group changes together
Definition at line 108 of file src/Database.cpp.
References libcomp::DatabaseChangeSet::Create(), and libcomp::Database::QueueChangeSet().
void Database::QueueUpdate (std::shared_ptr< PersistentObject > obj, const libobjgen::UUID & uuid = NULLUUID) inherited
Queue an object to update during the next call to ProcessTransactionQueue.
Parameters
obj Pointer to the object to update
uuid UUID used to group changes together
Definition at line 116 of file src/Database.cpp.
References libcomp::DatabaseChangeSet::Create(), and libcomp::Database::QueueChangeSet().
bool DatabaseMariaDB::Setup (bool rebuild = false, const std::shared_ptr< BaseServer > & server = {}, DataStore * pDataStore = nullptr, const std::string & migrationDirectory = std::string()) virtual
Setup the database schema and perform all validation steps.
Parameters
rebuild Optional parameter to rebuild all tables used by this database during the verification step
server Server to pass to migration scripts (or null).
pDataStore Pointer to the data store for migrations (or null).
migrationDirectory Directory to look for migrations in.
Returns
true if it could be set up, false if it could not
Implements libcomp::Database.
Definition at line 145 of file DatabaseMariaDB.cpp.
References libcomp::Database::ApplyMigration(), libcomp::String::Arg(), libcomp::Database::Execute(), Exists(), GetLastError(), libcomp::DataStore::GetListing(), IsOpen(), libcomp::String::Left(), libcomp::Database::mConfig, Prepare(), TableExists(), Use(), and VerifyAndSetupSchema().
Referenced by TEST().
bool DatabaseMariaDB::TableExists (const libcomp::String & table) virtual
Check if a table exists.
Parameters
table Name of the table to check for.
Returns
true if the table exists, false otherwise.
Implements libcomp::Database.
Definition at line 1549 of file DatabaseMariaDB.cpp.
References libcomp::Database::mConfig, and Prepare().
Referenced by Setup().
bool Database::TableHasRows (const String & table) virtual inherited
Check if the supplied table name exists and has at least one row.
Parameters
table Name of the table to check
Returns
true if a row exists, false if it does not
Reimplemented in libcomp::DatabaseSQLite3.
Definition at line 63 of file src/Database.cpp.
References libcomp::DatabaseQuery::Execute(), libcomp::DatabaseQuery::GetValue(), libcomp::DatabaseQuery::IsValid(), libcomp::DatabaseQuery::Next(), and libcomp::Database::Prepare().
Referenced by libcomp::DatabaseSQLite3::TableHasRows(), and libcomp::ScriptEngine::Using().
bool DatabaseMariaDB::UpdateSingleObject (std::shared_ptr< PersistentObject > & obj) virtual
Update all fields on one PersistentObject instance in the database.
Parameters
obj Pointer to the object to update
Returns
true on success, false on failure
Implements libcomp::Database.
Definition at line 518 of file DatabaseMariaDB.cpp.
References libcomp::String::Arg(), libcomp::DatabaseQuery::Bind(), libcomp::DatabaseQuery::Execute(), GetLastError(), libcomp::DatabaseQuery::IsValid(), libcomp::String::Join(), and Prepare().
Referenced by ProcessOperationalChangeSet(), and ProcessStandardChangeSet().
bool DatabaseMariaDB::Use () virtual
Use the database schema, keyspace, namespace, etc.
Returns
true on success, false on failure
Implements libcomp::Database.
Definition at line 311 of file DatabaseMariaDB.cpp.
References ConnectToDatabase(), GetConnection(), and libcomp::Database::mConfig.
Referenced by Setup(), and TEST().
bool Database::UsingDefaultDatabaseType () inherited
Check if the config is for the default database type.
Non-default connections are only responsible for verifying the schema of their own tables where-as default database connections may also have additional tables to maintain.
Returns
true if the default database type is configured, false if it is not
Definition at line 244 of file src/Database.cpp.
References libcomp::Database::mConfig.
Referenced by libcomp::Database::GetMappedObjects(), and libcomp::DatabaseSQLite3::Setup().
bool DatabaseMariaDB::VerifyAndSetupSchema (bool recreateTables = false)
Verify/create any missing tables based off of PersistentObject types used by the database as well as any utility tables needed.
Tables with invalid schemas will be archived in case data migration needs to take place and a replacement will be built instead and missing indexes will be created should they not exist based off of of fields marked as lookup keys in their objgen definitions.
Parameters
recreateTables Optional parameter to archive and recreate all tables used by this database
Returns
true on success, false on failure
Definition at line 659 of file DatabaseMariaDB.cpp.
References libcomp::String::Arg(), libcomp::String::C(), libcomp::Database::Execute(), libcomp::DatabaseQuery::Execute(), libcomp::Database::GetMappedObjects(), libcomp::PersistentObject::GetTypeHashByName(), libcomp::DatabaseQuery::GetValue(), GetVariableType(), libcomp::String::IsEmpty(), libcomp::Database::mConfig, libcomp::PersistentObject::New(), libcomp::DatabaseQuery::Next(), Prepare(), libcomp::String::ToLower(), and libcomp::String::ToUtf8().
Referenced by Setup().
Member Data Documentation
std::shared_ptr<objects::DatabaseConfig> libcomp::Database::mConfig protected inherited
Pointer to the config file used to configure the database connection.
Definition at line 314 of file Database.h.
Referenced by ConnectToDatabase(), libcomp::Database::Database(), Exists(), libcomp::Database::GetConfig(), GetConnection(), libcomp::DatabaseSQLite3::GetFilepath(), libcomp::Database::GetMappedObjects(), libcomp::DatabaseSQLite3::Prepare(), libcomp::DatabaseSQLite3::Setup(), Setup(), TableExists(), Use(), libcomp::Database::UsingDefaultDatabaseType(), libcomp::DatabaseSQLite3::VerifyAndSetupSchema(), and VerifyAndSetupSchema().
std::mutex libcomp::DatabaseMariaDB::mConnectionLock private
Mutex to lock access to the database connection map.
Definition at line 173 of file DatabaseMariaDB.h.
Referenced by Close(), and GetConnection().
std::unordered_map<std::thread::id, MYSQL*> libcomp::DatabaseMariaDB::mConnections private
Pointers to the MariaDB representation of a database connection per thread.
References to the pointers in this collection are passed around for use throughout the class as they are not removed or modified until the database is closed.
Definition at line 179 of file DatabaseMariaDB.h.
Referenced by Close(), GetConnection(), and IsOpen().
String libcomp::Database::mError protected inherited
Last error raised by a database related action.
Definition at line 311 of file Database.h.
Referenced by libcomp::Database::GetLastError().
The documentation for this class was generated from the following files:
DatabaseMariaDB.h
DatabaseMariaDB.cpp