COMP_hack: libcomp::Database Class Reference
libcomp::Database Class Reference abstract
Abstract base class that represents a database to use for loading and modifying PersistentObject instances as well as utility tables by translating actions to database specific query syntax.
#include <Database.h>
Public Member Functions
Database (const std::shared_ptr< objects::DatabaseConfig > &config)
Create a new Database connection.
virtual ~Database ()
Close and clean up the database connection.
virtual bool ApplyMigration (const std::shared_ptr< BaseServer > &server, DataStore *pDataStore, const libcomp::String &migration, const libcomp::String &path)
Apply a database migration script.
virtual bool Close ()=0
Close the connection to the database.
virtual bool DeleteObjects (std::list< std::shared_ptr< PersistentObject >> &objs)=0
Delete multiple PersistentObject instances from the database at once.
virtual bool DeleteSingleObject (std::shared_ptr< PersistentObject > &obj)
Delete one PersistentObject instance from the database.
virtual bool Execute (const String &query)
Prepare and execute a database query for execution based upon query text.
virtual bool Exists ()=0
Check if the database is valid.
std::shared_ptr
< objects::DatabaseConfig > GetConfig () const
Get the database config.
virtual String GetLastError ()
Retrieve the last error raised by a database operation.
virtual bool InsertSingleObject (std::shared_ptr< PersistentObject > &obj)=0
Insert one PersistentObject instance into the database.
virtual bool IsOpen () const =0
Check if the connection to the database is open.
virtual std::list
< std::shared_ptr
< PersistentObject > > LoadObjects (size_t typeHash, DatabaseBind *pValue)=0
Load multiple PersistentObject instances from a single bound database column and value to select upon.
virtual std::shared_ptr
< PersistentObject > LoadSingleObject (size_t typeHash, DatabaseBind *pValue)
Load one PersistentObject instance from a single bound database column and value to select upon.
virtual bool Open ()=0
Open the connection to the database.
virtual DatabaseQuery Prepare (const String &query)=0
Prepare a database query for execution based upon query text.
bool ProcessChangeSet (const std::shared_ptr< DatabaseChangeSet > &changes)
Process one or many database changes as a single transaction.
std::list< libobjgen::UUID > ProcessTransactionQueue ()
Pop and process all transactions stored in the transaction queue.
bool QueueChangeSet (const std::shared_ptr< DatabaseChangeSet > &changes)
Queue a set of changes to execute during the next call to ProcessTransactionQueue.
void QueueDelete (std::shared_ptr< PersistentObject > obj, const libobjgen::UUID &uuid=NULLUUID)
Queue an object to delete during the next call to ProcessTransactionQueue.
void QueueInsert (std::shared_ptr< PersistentObject > obj, const libobjgen::UUID &uuid=NULLUUID)
Queue an object to insert during the next call to ProcessTransactionQueue.
void QueueUpdate (std::shared_ptr< PersistentObject > obj, const libobjgen::UUID &uuid=NULLUUID)
Queue an object to update during the next call to ProcessTransactionQueue.
virtual bool Setup (bool rebuild=false, const std::shared_ptr< BaseServer > &server={}, DataStore *pDataStore=nullptr, const std::string &migrationDirectory=std::string())=0
Setup the database schema and perform all validation steps.
virtual bool TableExists (const libcomp::String &table)=0
Check if a table exists.
virtual bool TableHasRows (const String &table)
Check if the supplied table name exists and has at least one row.
virtual bool UpdateSingleObject (std::shared_ptr< PersistentObject > &obj)=0
Update all fields on one PersistentObject instance in the database.
virtual bool Use ()=0
Use the database schema, keyspace, namespace, etc.
bool UsingDefaultDatabaseType ()
Check if the config is for the default database type.
Protected Member Functions
std::vector< std::shared_ptr
< libobjgen::MetaObject > > GetMappedObjects ()
Get the list of objects mapped to the current database type configured for the database.
std::shared_ptr< PersistentObject > LoadSingleObjectFromRow (size_t typeHash, DatabaseQuery &query)
Get a pointer to a new PersistentObject of the specified type populated with the current row being read from a database query.
virtual bool ProcessOperationalChangeSet (const std::shared_ptr< DBOperationalChangeSet > &changes)=0
Process an operational change set as a single transaction.
virtual bool ProcessStandardChangeSet (const std::shared_ptr< DBStandardChangeSet > &changes)=0
Process one or many standard database changes as a single transaction.
Protected Attributes
std::shared_ptr
< objects::DatabaseConfig > mConfig
Pointer to the config file used to configure the database connection.
String mError
Last error raised by a database related action.
Private Attributes
std::mutex mTransactionLock
Mutex to lock accessing the transaction queue.
std::unordered_map
< std::string, std::shared_ptr
< DBStandardChangeSet > > mTransactionQueue
Map of transaction pointers by UUID.
Detailed Description
Abstract base class that represents a database to use for loading and modifying PersistentObject instances as well as utility tables by translating actions to database specific query syntax.
The typeHash is used as a parameter to access object metadata to perform various tasks such as checking column data types and knowing what table name to use in a select statement.
Definition at line 54 of file Database.h.
Constructor & Destructor Documentation
Database::Database (const std::shared_ptr< objects::DatabaseConfig > & config)
Create a new Database connection.
Parameters
config Pointer to a database configuration
Definition at line 39 of file src/Database.cpp.
References mConfig.
Database::~Database () virtual
Close and clean up the database connection.
Definition at line 44 of file src/Database.cpp.
Member Function Documentation
bool Database::ApplyMigration (const std::shared_ptr< BaseServer > & server, DataStore * pDataStore, const libcomp::String & migration, const libcomp::String & path) virtual
Apply a database migration script.
Parameters
server Server to pass to the script.
pDataStore Data store to read the script from.
migration Name of the migration.
path Path to the script in the data store.
Returns
true if the migration was applied; false otherwise.
Definition at line 298 of file src/Database.cpp.
References libcomp::String::Arg(), and libcomp::DataStore::ReadFile().
Referenced by libcomp::DatabaseSQLite3::Setup(), and libcomp::DatabaseMariaDB::Setup().
virtual bool libcomp::Database::Close () pure virtual
Close the connection to the database.
Returns
true on success, false on failure
Implemented in libcomp::DatabaseMariaDB, and libcomp::DatabaseSQLite3.
Referenced by libcomp::ScriptEngine::Using().
virtual bool libcomp::Database::DeleteObjects (std::list< std::shared_ptr< PersistentObject >> & objs) pure virtual
Delete multiple PersistentObject instances from the database at once.
Parameters
objs List of ointers to the objects to delete
Returns
true on success, false on failure
Implemented in libcomp::DatabaseMariaDB, and libcomp::DatabaseSQLite3.
Referenced by DeleteSingleObject().
bool Database::DeleteSingleObject (std::shared_ptr< PersistentObject > & obj) virtual
Delete one PersistentObject instance from the database.
Parameters
obj Pointer to the object to delete
Returns
true on success, false on failure
Definition at line 101 of file src/Database.cpp.
References DeleteObjects().
Referenced by libcomp::DatabaseSQLite3::ProcessOperationalChangeSet(), libcomp::DatabaseMariaDB::ProcessOperationalChangeSet(), and libcomp::ScriptEngine::Using().
bool Database::Execute (const String & query) virtual
Prepare and execute a database query for execution based upon query text.
Queries that return results should not use this function since a query is not returned to retrieve the results from.
Parameters
query Query text to prepare and execute
Returns
true on success, false on error
Definition at line 48 of file src/Database.cpp.
References libcomp::DatabaseQuery::Execute(), and Prepare().
Referenced by libcomp::DatabaseSQLite3::DeleteObjects(), libcomp::DatabaseMariaDB::DeleteObjects(), libcomp::DatabaseSQLite3::ProcessOperationalChangeSet(), libcomp::DatabaseSQLite3::ProcessStandardChangeSet(), libcomp::DatabaseSQLite3::Setup(), libcomp::DatabaseMariaDB::Setup(), TEST(), libcomp::ScriptEngine::Using(), libcomp::DatabaseSQLite3::VerifyAndSetupSchema(), and libcomp::DatabaseMariaDB::VerifyAndSetupSchema().
virtual bool libcomp::Database::Exists () pure virtual
Check if the database is valid.
Returns
true if it exists, false if it does not
Implemented in libcomp::DatabaseMariaDB, and libcomp::DatabaseSQLite3.
Referenced by libcomp::ScriptEngine::Using().
std::shared_ptr< objects::DatabaseConfig > Database::GetConfig () const
Get the database config.
Returns
Pointer to the database config
Definition at line 58 of file src/Database.cpp.
References mConfig.
String Database::GetLastError () virtual
Retrieve the last error raised by a database operation.
Returns
The last error that occurred
Reimplemented in libcomp::DatabaseMariaDB.
Definition at line 53 of file src/Database.cpp.
References mError.
Referenced by libcomp::DatabaseSQLite3::InsertSingleObject(), libcomp::DatabaseSQLite3::LoadObjects(), libcomp::DatabaseSQLite3::ProcessExplicitUpdate(), libcomp::DatabaseSQLite3::Setup(), libcomp::DatabaseSQLite3::UpdateSingleObject(), and libcomp::ScriptEngine::Using().
std::vector< std::shared_ptr< libobjgen::MetaObject > > Database::GetMappedObjects () protected
Get the list of objects mapped to the current database type configured for the database.
Returns
List of pointers to object definitions with a source set to the current database type
Definition at line 282 of file src/Database.cpp.
References libcomp::PersistentObject::GetRegistry(), mConfig, and UsingDefaultDatabaseType().
Referenced by libcomp::DatabaseSQLite3::VerifyAndSetupSchema(), and libcomp::DatabaseMariaDB::VerifyAndSetupSchema().
virtual bool libcomp::Database::InsertSingleObject (std::shared_ptr< PersistentObject > & obj) pure virtual
Insert one PersistentObject instance into the database.
Parameters
obj Pointer to the object to insert
Returns
true on success, false on failure
Implemented in libcomp::DatabaseMariaDB, and libcomp::DatabaseSQLite3.
Referenced by libcomp::ScriptEngine::Using().
virtual bool libcomp::Database::IsOpen () const pure virtual
Check if the connection to the database is open.
Returns
true if it is open, false if it is not
Implemented in libcomp::DatabaseMariaDB, and libcomp::DatabaseSQLite3.
Referenced by libcomp::ScriptEngine::Using().
virtual std::list<std::shared_ptr<PersistentObject> > libcomp::Database::LoadObjects (size_t typeHash, DatabaseBind * pValue) pure virtual
Load multiple PersistentObject instances from a single bound database column and value to select upon.
Parameters
typeHash C++ type hash representing the object type to load
pValue Database specific agnostic binding
Returns
List of pointers to loaded objects from the query results
Implemented in libcomp::DatabaseMariaDB, and libcomp::DatabaseSQLite3.
Referenced by LoadSingleObject().
std::shared_ptr< PersistentObject > Database::LoadSingleObject (size_t typeHash, DatabaseBind * pValue) virtual
Load one PersistentObject instance from a single bound database column and value to select upon.
This simply filters down the results of LoadObjects to the first record so it should be used only when the value being bound to is unique.
Parameters
typeHash C++ type hash representing the object type to load
pValue Database agnostic column binding
Returns
Pointer to the first loaded object from the query results
Definition at line 93 of file src/Database.cpp.
References LoadObjects().
Referenced by libcomp::DatabaseSQLite3::ProcessOperationalChangeSet(), and libcomp::DatabaseMariaDB::ProcessOperationalChangeSet().
std::shared_ptr< PersistentObject > Database::LoadSingleObjectFromRow (size_t typeHash, DatabaseQuery & query) protected
Get a pointer to a new PersistentObject of the specified type populated with the current row being read from a database query.
Parameters
typeHash C++ type hash of object to load
query Current query to use results from
Returns
Pointer to the new object
Definition at line 249 of file src/Database.cpp.
References libcomp::PersistentObject::GetObjectByUUID(), libcomp::DatabaseQuery::GetValue(), libcomp::PersistentObject::New(), and libcomp::PersistentObject::Register().
Referenced by libcomp::DatabaseSQLite3::LoadObjects(), and libcomp::DatabaseMariaDB::LoadObjects().
virtual bool libcomp::Database::Open () pure virtual
Open the connection to the database.
Returns
true on success, false on failure
Implemented in libcomp::DatabaseMariaDB, and libcomp::DatabaseSQLite3.
Referenced by libcomp::ScriptEngine::Using().
virtual DatabaseQuery libcomp::Database::Prepare (const String & query) pure virtual
Prepare a database query for execution based upon query text.
Parameters
query Query text to prepare
Returns
Prepared query
Implemented in libcomp::DatabaseMariaDB, and libcomp::DatabaseSQLite3.
Referenced by Execute(), and TableHasRows().
bool Database::ProcessChangeSet (const std::shared_ptr< DatabaseChangeSet > & changes)
Process one or many database changes as a single transaction.
Parameters
changes Grouping of changes to apply to the database
Returns
true on success, false on failure
Definition at line 224 of file src/Database.cpp.
References ProcessOperationalChangeSet(), and ProcessStandardChangeSet().
Referenced by ProcessTransactionQueue(), and TEST().
virtual bool libcomp::Database::ProcessOperationalChangeSet (const std::shared_ptr< DBOperationalChangeSet > & changes) protected pure virtual
Process an operational change set as a single transaction.
Parameters
changes Grouping of changes to apply to the database
Returns
true on success, false on failure
Implemented in libcomp::DatabaseMariaDB, and libcomp::DatabaseSQLite3.
Referenced by ProcessChangeSet().
virtual bool libcomp::Database::ProcessStandardChangeSet (const std::shared_ptr< DBStandardChangeSet > & changes) protected pure virtual
Process one or many standard database changes as a single transaction.
Parameters
changes Grouping of changes to apply to the database
Returns
true on success, false on failure
Implemented in libcomp::DatabaseMariaDB, and libcomp::DatabaseSQLite3.
Referenced by ProcessChangeSet().
std::list< libobjgen::UUID > Database::ProcessTransactionQueue ()
Pop and process all transactions stored in the transaction queue.
Returns
List of all transaction group UUIDs that failed to process
Definition at line 183 of file src/Database.cpp.
References mTransactionLock, mTransactionQueue, and ProcessChangeSet().
bool Database::QueueChangeSet (const std::shared_ptr< DatabaseChangeSet > & changes)
Queue a set of changes to execute during the next call to ProcessTransactionQueue.
Parameters
changes DatabaseChangeSet to queue for processing
Returns
true on success, false on failure
Definition at line 132 of file src/Database.cpp.
References mTransactionLock, and mTransactionQueue.
Referenced by QueueDelete(), QueueInsert(), and QueueUpdate().
void Database::QueueDelete (std::shared_ptr< PersistentObject > obj, const libobjgen::UUID & uuid = NULLUUID)
Queue an object to delete during the next call to ProcessTransactionQueue.
Parameters
obj Pointer to the object to delete
uuid UUID used to group changes together
Definition at line 124 of file src/Database.cpp.
References libcomp::DatabaseChangeSet::Create(), and QueueChangeSet().
void Database::QueueInsert (std::shared_ptr< PersistentObject > obj, const libobjgen::UUID & uuid = NULLUUID)
Queue an object to insert during the next call to ProcessTransactionQueue.
Parameters
obj Pointer to the object to insert
uuid UUID used to group changes together
Definition at line 108 of file src/Database.cpp.
References libcomp::DatabaseChangeSet::Create(), and QueueChangeSet().
void Database::QueueUpdate (std::shared_ptr< PersistentObject > obj, const libobjgen::UUID & uuid = NULLUUID)
Queue an object to update during the next call to ProcessTransactionQueue.
Parameters
obj Pointer to the object to update
uuid UUID used to group changes together
Definition at line 116 of file src/Database.cpp.
References libcomp::DatabaseChangeSet::Create(), and QueueChangeSet().
virtual bool libcomp::Database::Setup (bool rebuild = false, const std::shared_ptr< BaseServer > & server = {}, DataStore * pDataStore = nullptr, const std::string & migrationDirectory = std::string()) pure virtual
Setup the database schema and perform all validation steps.
Parameters
rebuild Optional parameter to rebuild all tables used by this database during the verification step
server Server to pass to migration scripts (or null).
pDataStore Pointer to the data store for migrations (or null).
migrationDirectory Directory to look for migrations in.
Returns
true if it could be set up, false if it could not
Implemented in libcomp::DatabaseMariaDB, and libcomp::DatabaseSQLite3.
virtual bool libcomp::Database::TableExists (const libcomp::String & table) pure virtual
Check if a table exists.
Parameters
table Name of the table to check for.
Returns
true if the table exists, false otherwise.
Implemented in libcomp::DatabaseMariaDB, and libcomp::DatabaseSQLite3.
Referenced by libcomp::ScriptEngine::Using().
bool Database::TableHasRows (const String & table) virtual
Check if the supplied table name exists and has at least one row.
Parameters
table Name of the table to check
Returns
true if a row exists, false if it does not
Reimplemented in libcomp::DatabaseSQLite3.
Definition at line 63 of file src/Database.cpp.
References libcomp::DatabaseQuery::Execute(), libcomp::DatabaseQuery::GetValue(), libcomp::DatabaseQuery::IsValid(), libcomp::DatabaseQuery::Next(), and Prepare().
Referenced by libcomp::DatabaseSQLite3::TableHasRows(), and libcomp::ScriptEngine::Using().
virtual bool libcomp::Database::UpdateSingleObject (std::shared_ptr< PersistentObject > & obj) pure virtual
Update all fields on one PersistentObject instance in the database.
Parameters
obj Pointer to the object to update
Returns
true on success, false on failure
Implemented in libcomp::DatabaseMariaDB, and libcomp::DatabaseSQLite3.
Referenced by libcomp::ScriptEngine::Using().
virtual bool libcomp::Database::Use () pure virtual
Use the database schema, keyspace, namespace, etc.
Returns
true on success, false on failure
Implemented in libcomp::DatabaseMariaDB, and libcomp::DatabaseSQLite3.
Referenced by libcomp::ScriptEngine::Using().
bool Database::UsingDefaultDatabaseType ()
Check if the config is for the default database type.
Non-default connections are only responsible for verifying the schema of their own tables where-as default database connections may also have additional tables to maintain.
Returns
true if the default database type is configured, false if it is not
Definition at line 244 of file src/Database.cpp.
References mConfig.
Referenced by GetMappedObjects(), and libcomp::DatabaseSQLite3::Setup().
Member Data Documentation
std::shared_ptr<objects::DatabaseConfig> libcomp::Database::mConfig protected
Pointer to the config file used to configure the database connection.
Definition at line 314 of file Database.h.
Referenced by libcomp::DatabaseMariaDB::ConnectToDatabase(), Database(), libcomp::DatabaseMariaDB::Exists(), GetConfig(), libcomp::DatabaseMariaDB::GetConnection(), libcomp::DatabaseSQLite3::GetFilepath(), GetMappedObjects(), libcomp::DatabaseSQLite3::Prepare(), libcomp::DatabaseSQLite3::Setup(), libcomp::DatabaseMariaDB::Setup(), libcomp::DatabaseMariaDB::TableExists(), libcomp::DatabaseMariaDB::Use(), UsingDefaultDatabaseType(), libcomp::DatabaseSQLite3::VerifyAndSetupSchema(), and libcomp::DatabaseMariaDB::VerifyAndSetupSchema().
String libcomp::Database::mError protected
Last error raised by a database related action.
Definition at line 311 of file Database.h.
Referenced by GetLastError().
std::mutex libcomp::Database::mTransactionLock private
Mutex to lock accessing the transaction queue.
Definition at line 322 of file Database.h.
Referenced by ProcessTransactionQueue(), and QueueChangeSet().
std::unordered_map<std::string, std::shared_ptr<DBStandardChangeSet> > libcomp::Database::mTransactionQueue private
Map of transaction pointers by UUID.
Definition at line 319 of file Database.h.
Referenced by ProcessTransactionQueue(), and QueueChangeSet().
The documentation for this class was generated from the following files:
Database.h
src/Database.cpp