COMP_hack: libcomp::DataFile Class Reference
libcomp::DataFile Class Reference
#include <DataFile.h>
Public Types
enum Whence_t { Whence_t::BEGIN, Whence_t::CURRENT, Whence_t::END }
Public Member Functions
bool AtEOF () const
bool Close ()
bool Flush ()
libcomp::String GetPath () const
int64_t GetPosition () const
int64_t GetSize () const
bool IsOpen () const
bool Open (DataStore::FileMode_t mode=DataStore::FileMode_t::READ)
bool Read (void *pBuffer, uint32_t bufferSize)
std::vector< char > Read (uint32_t size)
void SetPath (const libcomp::String &path)
bool SetPosition (int64_t pos, Whence_t whence=Whence_t::BEGIN)
bool Write (const void *pBuffer, uint32_t bufferSize)
bool Write (const std::vector< char > &buffer)
Protected Member Functions
DataFile (const libcomp::String &path, DataStore::FileMode_t mode)
~DataFile ()
Private Attributes
PHYSFS_File * mFile
libcomp::String mPath
Friends
class DataStore
Detailed Description
Definition at line 41 of file DataFile.h.
Member Enumeration Documentation
enum libcomp::DataFile::Whence_t strong
Enumerator
BEGIN
CURRENT
END
Definition at line 58 of file DataFile.h.
Constructor & Destructor Documentation
DataFile::DataFile (const libcomp::String & path, DataStore::FileMode_t mode) protected
Definition at line 36 of file DataFile.cpp.
References Open(), and SetPath().
DataFile::~DataFile () protected
Definition at line 44 of file DataFile.cpp.
References Close().
Member Function Documentation
bool DataFile::AtEOF () const
Definition at line 127 of file DataFile.cpp.
References mFile.
bool DataFile::Close ()
Definition at line 80 of file DataFile.cpp.
References mFile.
Referenced by ~DataFile().
bool DataFile::Flush ()
Definition at line 97 of file DataFile.cpp.
References mFile.
libcomp::String DataFile::GetPath () const
Definition at line 107 of file DataFile.cpp.
References mPath.
int64_t DataFile::GetPosition () const
Definition at line 137 of file DataFile.cpp.
References mFile.
Referenced by SetPosition().
int64_t DataFile::GetSize () const
Definition at line 117 of file DataFile.cpp.
References mFile.
Referenced by SetPosition().
bool DataFile::IsOpen () const
Definition at line 49 of file DataFile.cpp.
References mFile.
Referenced by Open().
bool DataFile::Open (DataStore::FileMode_t mode = DataStore::FileMode_t::READ)
Definition at line 54 of file DataFile.cpp.
References libcomp::DataStore::APPEND, libcomp::String::C(), IsOpen(), mFile, mPath, libcomp::DataStore::READ, and libcomp::DataStore::WRITE.
Referenced by DataFile().
bool DataFile::Read (void * pBuffer, uint32_t bufferSize)
Definition at line 176 of file DataFile.cpp.
References mFile.
Referenced by Read().
std::vector< char > DataFile::Read (uint32_t size)
Definition at line 186 of file DataFile.cpp.
References Read().
void DataFile::SetPath (const libcomp::String & path)
Definition at line 112 of file DataFile.cpp.
References mPath.
Referenced by DataFile().
bool DataFile::SetPosition (int64_t pos, Whence_t whence = Whence_t::BEGIN)
Definition at line 147 of file DataFile.cpp.
References BEGIN, CURRENT, END, GetPosition(), GetSize(), and mFile.
bool DataFile::Write (const void * pBuffer, uint32_t bufferSize)
Definition at line 199 of file DataFile.cpp.
References mFile.
Referenced by Write().
bool DataFile::Write (const std::vector< char > & buffer)
Definition at line 209 of file DataFile.cpp.
References Write().
Friends And Related Function Documentation
friend class DataStore friend
Definition at line 43 of file DataFile.h.
Member Data Documentation
PHYSFS_File* libcomp::DataFile::mFile private
Definition at line 80 of file DataFile.h.
Referenced by AtEOF(), Close(), Flush(), GetPosition(), GetSize(), IsOpen(), Open(), Read(), SetPosition(), and Write().
libcomp::String libcomp::DataFile::mPath private
Definition at line 79 of file DataFile.h.
Referenced by GetPath(), Open(), and SetPath().
The documentation for this class was generated from the following files:
DataFile.h
DataFile.cpp