COMP_hack: libcomp::PersistentObject Class Reference
libcomp::PersistentObject Class Reference abstract
Base class of a all dynamically generated objects that persist in the database.
#include <PersistentObject.h>
Public Types
typedef std::unordered_map
< size_t, std::shared_ptr
< libobjgen::MetaObject > > TypeMap
Map of MetaObject definitions by the source object's C++ type hash.
Public Member Functions
PersistentObject ()
Create a persistent object with no UUID.
PersistentObject (const PersistentObject &other)
Override the copy constructor to still default the persistent members.
~PersistentObject ()
Clean up the object and remove it from the UUID cache.
bool Delete (const std::shared_ptr< Database > &db)
Deletes an existing record from the database.
virtual uint16_t GetDynamicSizeCount () const =0
Get the dynamic size count of the MetaObject definition.
virtual std::list
< libcomp::DatabaseBind * > GetMemberBindValues (bool retrieveAll=false, bool clearChanges=true)=0
Get database bindings for all or changed data members.
virtual std::shared_ptr
< libobjgen::MetaObject > GetObjectMetadata ()=0
Get the MetaObject definition associated to the object.
libobjgen::UUID GetUUID () const
Get the object's UUID.
std::string GetXml () const
Save the object into XML and return it as a string.
bool Insert (const std::shared_ptr< Database > &db)
Save a new record to the database.
bool IsDeleted ()
Check if the record is marked as deleted from the database.
virtual bool IsValid (bool recursive=true) const =0
Check if the object is currently in a valid state.
virtual bool Load (ObjectInStream &stream)=0
Load the object's data members from an ObjectInStream.
virtual bool Load (std::istream &stream, bool flat=false)=0
Load the object's data members from a standard input stream.
virtual bool Load (const tinyxml2::XMLDocument &doc, const tinyxml2::XMLElement &root)=0
Load the object's data members from an XML file.
virtual bool LoadDatabaseValues (DatabaseQuery &query)=0
Load the object from a successfully executed query.
virtual bool LoadPacket (libcomp::ReadOnlyPacket &p, bool flat=true)
Load the object's data members from a data packet.
virtual bool Save (ObjectOutStream &stream) const =0
Save the object's data members to an ObjectOutStream.
virtual bool Save (std::ostream &stream, bool flat=false) const =0
Save the object's data members to a standard output stream.
virtual bool Save (tinyxml2::XMLDocument &doc, tinyxml2::XMLElement &root, bool append=false) const =0
Save the object's data members to an XML file.
virtual bool SavePacket (libcomp::Packet &p, bool flat=true) const
Save the object's data members to a data packet.
bool SaveWithUUID (tinyxml2::XMLDocument &doc, tinyxml2::XMLElement &root, bool append=false) const
Save the object's data members to an XML file including the UUID.
void Unregister ()
Unregisters an object from the cache and marks it as deleted.
bool Update (const std::shared_ptr< Database > &db)
Update an existing record in the database.
Static Public Member Functions
static std::shared_ptr
< libobjgen::MetaObject > GetMetadataFromBytes (const char *bytes, size_t length)
Get the MetaObject definition from loading a byte array.
static std::shared_ptr
< PersistentObject > GetObjectByUUID (const libobjgen::UUID &uuid)
Retrieve an object by its UUID but do not load from the database.
template<class T >
static const std::shared_ptr
< libobjgen::MetaObject > GetRegisteredMetadata ()
Get the PersistentObject of the specified type's MetaObject definition.
static const std::shared_ptr
< libobjgen::MetaObject > GetRegisteredMetadata (size_t typeHash)
Get the PersistentObject of the specified type ID's MetaObject definition.
static TypeMap & GetRegistry ()
Get all PersistentObject derived class MetaObject definitions.
static size_t GetTypeHashByName (const std::string &name, bool &result)
Get the C++ type hash by the associated object type's name.
static size_t GetTypeHashByName (const std::string &name)
Get the C++ type hash by the associated object type's name.
static bool Initialize ()
Register all derived types in libcomp to the TypeMap.
template<class T >
static std::list
< std::shared_ptr< T > > LoadAll (const std::shared_ptr< Database > &db)
Retrieve all objects of the specified type by its UUID from the database.
static std::list
< std::shared_ptr< Object > > LoadBinaryData (std::istream &stream, const std::function< std::shared_ptr< Object >()> &objectAllocator)
Static utility function to build multiple objects from an input stream and a factory function.
template<class T >
static std::shared_ptr< T > LoadObjectByUUID (const std::shared_ptr< Database > &db, const libobjgen::UUID &uuid, bool reload=false, bool reportError=true)
Retrieve an object of the specified type by its UUID from the cache or database.
static std::shared_ptr
< PersistentObject > LoadObjectByUUID (size_t typeHash, const std::shared_ptr< Database > &db, const libobjgen::UUID &uuid, bool reload=false, bool reportError=false)
Retrieve an object of the specified type ID by its UUID from the cache or database.
template<class T >
static std::shared_ptr< T > New (bool doRegister=false)
Create a new instance of a PersistentObject of the specified type.
static std::shared_ptr
< PersistentObject > New (size_t typeHash)
Create a new instance of a PersistentObject of the specified type ID.
static bool Register (const std::shared_ptr< PersistentObject > &self, const libobjgen::UUID &pUuid=NULLUUID)
Register a derived class object to the cache and get a new UUID if not specified.
static bool SaveBinaryData (std::ostream &stream, const std::list< std::shared_ptr< Object >> &objs)
Static utliity function to save multiple objects to an output stream.
template<class T >
static std::list
< std::shared_ptr
< PersistentObject > > ToList (std::list< std::shared_ptr< T >> objList)
Convert a list of PersistentObject derived object pointers into a list of PersistentObject pointers.
Protected Member Functions
const tinyxml2::XMLElement * GetXmlChild (const tinyxml2::XMLElement &root, const std::string name) const
Utility function to get a child XML element from a parent node matching a specified name.
const std::list< const
tinyxml2::XMLElement * > GetXmlChildren (const tinyxml2::XMLElement &root, const std::string name) const
Utility function to get child XML elements from a parent node matching a specified name.
virtual std::unordered_map
< std::string, const
tinyxml2::XMLElement * > GetXmlMembers (const tinyxml2::XMLElement &root) const
Utility function to get child XML elements from a parent node.
virtual std::string GetXmlText (const tinyxml2::XMLElement &root) const
Utility function to get element text from an XML node.
bool SkipPadding (std::istream &stream, uint8_t count)
Utility function to skip padding bytes when reading from a datastream.
bool WritePadding (std::ostream &stream, uint8_t count) const
Utility function to write padding bytes when writing to a datastream.
Static Protected Member Functions
static std::shared_ptr
< PersistentObject > LoadObject (size_t typeHash, const std::shared_ptr< Database > &db, DatabaseBind *pValue)
Load an object from the database from a field database binding.
static std::shared_ptr
< PersistentObject > LoadObject (size_t typeHash, const std::shared_ptr< Database > &db)
Load an object from the database from a field database binding.
static std::list
< std::shared_ptr
< PersistentObject > > LoadObjects (size_t typeHash, const std::shared_ptr< Database > &db, DatabaseBind *pValue)
Load multiple objects from the database from a field database binding.
static std::list
< std::shared_ptr
< PersistentObject > > LoadObjects (size_t typeHash, const std::shared_ptr< Database > &db)
Load multiple objects from the database from a field database binding.
static void RegisterType (std::type_index type, const std::shared_ptr< libobjgen::MetaObject > &obj, const std::function< PersistentObject *()> &f)
Register a derived class type with a function to describe it to the database.
Protected Attributes
std::set< std::string > mDirtyFields
Set of fields that have been updated since the last save operation.
std::mutex mFieldLock
Mutex to lock accessing the object fields.
libobjgen::UUID mUUID
UUID associated to the object.
Static Protected Attributes
static bool sInitializationFailed = false
Static value to be set to true if any PersistentObject type fails to register itself at runtime.
Private Attributes
bool mDeleted
Indicator that the object has been deleted and should not be cached again.
std::weak_ptr< PersistentObject > mSelf
Pointer to object itself.
Static Private Attributes
static std::mutex mCacheLock
Mutex to lock accessing the cache.
static std::unordered_map
< std::string, std::weak_ptr
< PersistentObject > > sCached
Map of intantiated objects listed by their UUID.
static std::unordered_map
< size_t, std::function
< PersistentObject *()> > sFactory
Static map of functions to create an object by their C++ type hash.
static TypeMap sTypeMap
Static map of MetaObject definitions by the source object's C++ type hash.
static std::unordered_map
< std::string, size_t > sTypeNames
Static map of C++ type hashes by name.
Friends
class ScriptEngine
Detailed Description
Base class of a all dynamically generated objects that persist in the database.
Persistent objects are cached upon load or by explicitly registering them which will allow them to be retrieved via a generated UUID.
Definition at line 57 of file PersistentObject.h.
Member Typedef Documentation
typedef std::unordered_map<size_t, std::shared_ptr<libobjgen::MetaObject> > libcomp::PersistentObject::TypeMap
Map of MetaObject definitions by the source object's C++ type hash.
Definition at line 64 of file PersistentObject.h.
Constructor & Destructor Documentation
PersistentObject::PersistentObject ()
Create a persistent object with no UUID.
Definition at line 82 of file PersistentObject.cpp.
PersistentObject::PersistentObject (const PersistentObject & other)
Override the copy constructor to still default the persistent members.
Parameters
other The other object to copy
Definition at line 87 of file PersistentObject.cpp.
References mSelf.
PersistentObject::~PersistentObject ()
Clean up the object and remove it from the UUID cache.
Definition at line 95 of file PersistentObject.cpp.
References IsDeleted(), mCacheLock, mUUID, and sCached.
Member Function Documentation
bool PersistentObject::Delete (const std::shared_ptr< Database > & db)
Deletes an existing record from the database.
Parameters
db Database to load from
Returns
true on success, false on failure
Definition at line 351 of file PersistentObject.cpp.
References mSelf.
Referenced by libcomp::ScriptEngine::Using().
virtual uint16_t libcomp::Object::GetDynamicSizeCount () const pure virtual inherited
Get the dynamic size count of the MetaObject definition.
An object's dynamic size count can be thought of as the minimum size required to save an object of a given type.
Returns
MetaObject definition's dynamic size count
Implemented in libcomp::DynamicObject.
virtual std::list<libcomp::DatabaseBind*> libcomp::PersistentObject::GetMemberBindValues (bool retrieveAll = false, bool clearChanges = true) pure virtual
Get database bindings for all or changed data members.
Calling this will clear the set of fields marked as changed.
Parameters
retrieveAll Optional parameter to retrieve all data members instead of the default change only behavior
clearChanges Optional parameter to clear not clear all fields marked as changed
Returns
List of pointers to data member database binds
std::shared_ptr< libobjgen::MetaObject > PersistentObject::GetMetadataFromBytes (const char * bytes, size_t length) static
Get the MetaObject definition from loading a byte array.
Parameters
bytes Byte array of the definition
length Number of bytes in the array
Returns
Pointer to the MetaObject definition or nullptr on failure
Definition at line 303 of file PersistentObject.cpp.
std::shared_ptr< PersistentObject > PersistentObject::GetObjectByUUID (const libobjgen::UUID & uuid) static
Retrieve an object by its UUID but do not load from the database.
Parameters
uuid UUID to retrieve from the cache
Returns
Pointer to the cached object or nullptr if it doesn't exist
Definition at line 189 of file PersistentObject.cpp.
References mCacheLock, and sCached.
Referenced by LoadObjectByUUID(), libcomp::ObjectReference< T >::LoadReference(), libcomp::Database::LoadSingleObjectFromRow(), and libcomp::DataSyncManager::SyncIncoming().
virtual std::shared_ptr<libobjgen::MetaObject> libcomp::PersistentObject::GetObjectMetadata () pure virtual
Get the MetaObject definition associated to the object.
Returns
Pointer to the MetaObject defintion
template<class T > static const std::shared_ptr<libobjgen::MetaObject> libcomp::PersistentObject::GetRegisteredMetadata () inline static
Get the PersistentObject of the specified type's MetaObject definition.
Returns
Pointer to the MetaObject definition
Definition at line 236 of file PersistentObject.h.
Referenced by libcomp::DatabaseSQLite3::LoadObjects(), and libcomp::DatabaseMariaDB::LoadObjects().
const std::shared_ptr< libobjgen::MetaObject > PersistentObject::GetRegisteredMetadata (size_t typeHash) static
Get the PersistentObject of the specified type ID's MetaObject definition.
Parameters
typeHash C++ type hash representing the object type to load
Returns
Pointer to the MetaObject definition
Definition at line 297 of file PersistentObject.cpp.
References sTypeMap.
PersistentObject::TypeMap & PersistentObject::GetRegistry () static
Get all PersistentObject derived class MetaObject definitions.
Returns
Map of MetaObject definitions by the source object's C++ type
Definition at line 278 of file PersistentObject.cpp.
References sTypeMap.
Referenced by libcomp::Database::GetMappedObjects().
size_t PersistentObject::GetTypeHashByName (const std::string & name, bool & result) static
Get the C++ type hash by the associated object type's name.
Parameters
name Name of a persistent object type
result true if the type is registered, false if it is not
Returns
C++ type hash matching the supplied name
Definition at line 283 of file PersistentObject.cpp.
References sTypeNames.
Referenced by GetTypeHashByName(), libcomp::BaseServer::LoadDataFromFile(), libcomp::DatabaseSQLite3::ProcessOperationalChangeSet(), libcomp::DatabaseMariaDB::ProcessOperationalChangeSet(), libcomp::DataSyncManager::QueueOutgoing(), libcomp::DataSyncManager::SyncIncoming(), libcomp::ScriptEngine::Using(), libcomp::DatabaseSQLite3::VerifyAndSetupSchema(), and libcomp::DatabaseMariaDB::VerifyAndSetupSchema().
size_t PersistentObject::GetTypeHashByName (const std::string & name) static
Get the C++ type hash by the associated object type's name.
Parameters
name Name of a persistent object type
Returns
C++ type hash matching the supplied name
Definition at line 290 of file PersistentObject.cpp.
References GetTypeHashByName().
libobjgen::UUID PersistentObject::GetUUID () const
Get the object's UUID.
Returns
The object's UUID
Definition at line 109 of file PersistentObject.cpp.
References mUUID.
Referenced by SaveWithUUID(), libcomp::ObjectReference< T >::SetReference(), and libcomp::ScriptEngine::Using().
std::string Object::GetXml () const inherited
Save the object into XML and return it as a string.
Returns
An XML string for the object.
Definition at line 301 of file Object.cpp.
References libcomp::Object::Save().
const tinyxml2::XMLElement * Object::GetXmlChild (const tinyxml2::XMLElement & root, const std::string name) const protected inherited
Utility function to get a child XML element from a parent node matching a specified name.
Parameters
root Parent XML node
name Child element name to retrieve
Returns
First matching XML node child or nullptr if not found
See Also
Object::GetXmlChildren
Definition at line 78 of file Object.cpp.
References libcomp::Object::GetXmlChildren().
const std::list< const tinyxml2::XMLElement * > Object::GetXmlChildren (const tinyxml2::XMLElement & root, const std::string name) const protected inherited
Utility function to get child XML elements from a parent node matching a specified name.
Parameters
root Parent XML node
name Child element name to retrieve
Returns
List of matching XML node children or empty if not found
See Also
Object::GetXmlChild
Definition at line 85 of file Object.cpp.
Referenced by libcomp::Object::GetXmlChild().
std::unordered_map< std::string, const tinyxml2::XMLElement * > Object::GetXmlMembers (const tinyxml2::XMLElement & root) const protected virtual inherited
Utility function to get child XML elements from a parent node.
Parameters
root Parent XML node
Returns
Map of child members by element name
Definition at line 103 of file Object.cpp.
std::string Object::GetXmlText (const tinyxml2::XMLElement & root) const protected virtual inherited
Utility function to get element text from an XML node.
Parameters
root Parent XML node
Returns
Text contained in the node's element text
Definition at line 124 of file Object.cpp.
bool PersistentObject::Initialize () static
Register all derived types in libcomp to the TypeMap.
Persisted types needed in other databases should derive from this class to register their own as well.
Returns
true on success, false on failure
Definition at line 439 of file PersistentObject.cpp.
References libcomp::Clan, libcomp::Demon, libcomp::Item, RegisterType(), and sInitializationFailed.
bool PersistentObject::Insert (const std::shared_ptr< Database > & db)
Save a new record to the database.
Parameters
db Database to load from
Returns
true on success, false on failure
Definition at line 329 of file PersistentObject.cpp.
References mSelf.
Referenced by libcomp::ScriptEngine::Using().
bool PersistentObject::IsDeleted ()
Check if the record is marked as deleted from the database.
Returns
true if it is deleted, false if it is not
Definition at line 184 of file PersistentObject.cpp.
References mDeleted.
Referenced by ~PersistentObject().
virtual bool libcomp::Object::IsValid (bool recursive = true) const pure virtual inherited
Check if the object is currently in a valid state.
Parameters
recursive If references to other objects exist and recursive = true, IsValid will be run on those references as well
Returns
true if valid, false if invalid
Implemented in libcomp::DynamicObject.
Referenced by libcomp::ScriptEngine::Using().
virtual bool libcomp::Object::Load (ObjectInStream & stream) pure virtual inherited
Load the object's data members from an ObjectInStream.
Parameters
stream Byte stream containing data member values
Returns
true if loading was successful, false if it was not
Referenced by libcomp::Object::LoadPacket().
virtual bool libcomp::Object::Load (std::istream & stream, bool flat = false) pure virtual inherited
Load the object's data members from a standard input stream.
Parameters
stream Byte stream containing data member values
flat If references to non-persistent objects exist and flat = false those references' data members are specified in the stream as well
Returns
true if loading was successful, false if it was not
virtual bool libcomp::Object::Load (const tinyxml2::XMLDocument & doc, const tinyxml2::XMLElement & root) pure virtual inherited
Load the object's data members from an XML file.
Parameters
doc XML document containing the definition
root Root XML node of the definition
Returns
true if loading was successful, false if it was not
template<class T > static std::list<std::shared_ptr<T> > libcomp::PersistentObject::LoadAll (const std::shared_ptr< Database > & db) inline static
Retrieve all objects of the specified type by its UUID from the database.
Use sparingly.
Parameters
db Database to load from
Returns
List of pointers to all objects of the specified type
Definition at line 158 of file PersistentObject.h.
References LoadObjects().
std::list< std::shared_ptr< Object > > Object::LoadBinaryData (std::istream & stream, const std::function< std::shared_ptr< Object >()> & objectAllocator) static inherited
Static utility function to build multiple objects from an input stream and a factory function.
Parameters
stream Byte stream containing the object data
objectAllocator Factory function to build the objects
Returns
List of resulting objects built from the stream
Definition at line 148 of file Object.cpp.
References libcomp::ObjectInStream::dynamicSizes.
Referenced by libcomp::BinaryDataSet::Load().
virtual bool libcomp::PersistentObject::LoadDatabaseValues (DatabaseQuery & query) pure virtual
Load the object from a successfully executed query.
Parameters
query Database query that has executed to load from
Returns
true on success, false on failure
std::shared_ptr< PersistentObject > PersistentObject::LoadObject (size_t typeHash, const std::shared_ptr< Database > & db, DatabaseBind * pValue) static protected
Load an object from the database from a field database binding.
Parameters
typeHash C++ type hash representing the object type to load
db Database to load from
pValue Pointer to a field bound to a database column
Returns
Pointer to the object or nullptr if it doesn't exist
Definition at line 229 of file PersistentObject.cpp.
Referenced by LoadObject(), and LoadObjectByUUID().
std::shared_ptr< PersistentObject > PersistentObject::LoadObject (size_t typeHash, const std::shared_ptr< Database > & db) static protected
Load an object from the database from a field database binding.
Parameters
typeHash C++ type hash representing the object type to load
db Database to load from
Returns
Pointer to the object or nullptr if it doesn't exist
Definition at line 243 of file PersistentObject.cpp.
References LoadObject().
template<class T > static std::shared_ptr<T> libcomp::PersistentObject::LoadObjectByUUID (const std::shared_ptr< Database > & db, const libobjgen::UUID & uuid, bool reload = false, bool reportError = true) inline static
Retrieve an object of the specified type by its UUID from the cache or database.
Parameters
db Database to load from
uuid UUID of the object to load
reload Forces a reload from the DB if true
reportError If set to false the error will not be logged.
Returns
Pointer to the object or nullptr if it doesn't exist
Definition at line 182 of file PersistentObject.h.
Referenced by libcomp::DataSyncManager::SyncIncoming(), and libcomp::ScriptEngine::Using().
std::shared_ptr< PersistentObject > PersistentObject::LoadObjectByUUID (size_t typeHash, const std::shared_ptr< Database > & db, const libobjgen::UUID & uuid, bool reload = false, bool reportError = false) static
Retrieve an object of the specified type ID by its UUID from the cache or database.
Parameters
typeHash C++ type hash representing the object type to load
db Database to load from
uuid UUID of the object to load
reload Forces a reload from the DB if true
reportError If set to false the error will not be logged.
Returns
Pointer to the object or nullptr if it doesn't exist
Definition at line 202 of file PersistentObject.cpp.
References libcomp::String::Arg(), GetObjectByUUID(), LoadObject(), and sTypeMap.
std::list< std::shared_ptr< PersistentObject > > PersistentObject::LoadObjects (size_t typeHash, const std::shared_ptr< Database > & db, DatabaseBind * pValue) static protected
Load multiple objects from the database from a field database binding.
Parameters
typeHash C++ type hash representing the object type to load
db Database to load from
pValue Pointer to a field bound to a database column
Returns
List of pointers objects
Definition at line 249 of file PersistentObject.cpp.
Referenced by LoadAll(), LoadObjects(), and libcomp::ScriptEngine::Using().
std::list< std::shared_ptr< PersistentObject > > PersistentObject::LoadObjects (size_t typeHash, const std::shared_ptr< Database > & db) static protected
Load multiple objects from the database from a field database binding.
Parameters
typeHash C++ type hash representing the object type to load
db Database to load from
Returns
List of pointers objects
Definition at line 261 of file PersistentObject.cpp.
References LoadObjects().
bool Object::LoadPacket (libcomp::ReadOnlyPacket & p, bool flat = true) virtual inherited
Load the object's data members from a data packet.
Parameters
p Packet containing data member values
flat Specifies if the call to Load should be flat
Returns
true if loading was successful, false if it was not
Definition at line 53 of file Object.cpp.
References libcomp::Object::Load(), and libcomp::ReadOnlyPacket::Skip().
template<class T > static std::shared_ptr<T> libcomp::PersistentObject::New (bool doRegister = false) inline static
Create a new instance of a PersistentObject of the specified type.
Parameters
doRegister Register the pointer automatically on success.
Returns
Pointer to a new PersistentObject of the specified type
Definition at line 268 of file PersistentObject.h.
Referenced by libcomp::BaseServer::LoadDataFromFile(), libcomp::Database::LoadSingleObjectFromRow(), libcomp::DatabaseSQLite3::VerifyAndSetupSchema(), and libcomp::DatabaseMariaDB::VerifyAndSetupSchema().
std::shared_ptr< PersistentObject > PersistentObject::New (size_t typeHash) static
Create a new instance of a PersistentObject of the specified type ID.
Parameters
typeHash C++ type hash representing the object type to load
Returns
Pointer to a new PersistentObject of the specified type ID
Definition at line 323 of file PersistentObject.cpp.
References sFactory.
bool PersistentObject::Register (const std::shared_ptr< PersistentObject > & self, const libobjgen::UUID & pUuid = NULLUUID) static
Register a derived class object to the cache and get a new UUID if not specified.
Parameters
self Pointer to the object itself
uuid Optional predefined UUID to use if the record has a null value
Returns
true on success, false on failure
Definition at line 114 of file PersistentObject.cpp.
References libcomp::String::Arg(), mCacheLock, and sCached.
Referenced by libcomp::Database::LoadSingleObjectFromRow(), and libcomp::ScriptEngine::Using().
void PersistentObject::RegisterType (std::type_index type, const std::shared_ptr< libobjgen::MetaObject > & obj, const std::function< PersistentObject *()> & f) static protected
Register a derived class type with a function to describe it to the database.
Parameters
type C++ type representing the object type to load
obj MetaObject definition to register
f Function used to create a new object of the specified type
Definition at line 267 of file PersistentObject.cpp.
References sFactory, sTypeMap, and sTypeNames.
Referenced by Initialize().
virtual bool libcomp::Object::Save (ObjectOutStream & stream) const pure virtual inherited
Save the object's data members to an ObjectOutStream.
Parameters
stream Byte stream to save data member values to
Returns
true if saving was successful, false if it was not
Referenced by libcomp::Object::GetXml(), libcomp::Object::SavePacket(), and SaveWithUUID().
virtual bool libcomp::Object::Save (std::ostream & stream, bool flat = false) const pure virtual inherited
Save the object's data members to a standard output stream.
Parameters
stream Byte stream to save data member values to
flat If references to non-persistent objects exist and flat = false those references' data members will be saved in the stream as well
Returns
true if saving was successful, false if it was not
virtual bool libcomp::Object::Save (tinyxml2::XMLDocument & doc, tinyxml2::XMLElement & root, bool append = false) const pure virtual inherited
Save the object's data members to an XML file.
Parameters
doc XML document to save the definition to
root Root XML node to save the definition to
append true if the root node should be appended to, false if an object node should be added to the root then appended to
Returns
true if saving was successful, false if it was not
bool Object::SaveBinaryData (std::ostream & stream, const std::list< std::shared_ptr< Object >> & objs) static inherited
Static utliity function to save multiple objects to an output stream.
Parameters
stream Byte stream to save the object data to.
objs List of objects to save to the stream.
Returns
true if saving was successful, false if it was not
Definition at line 208 of file Object.cpp.
References libcomp::ObjectOutStream::dynamicSizes.
Referenced by libcomp::BinaryDataSet::Save().
bool Object::SavePacket (libcomp::Packet & p, bool flat = true) const virtual inherited
Save the object's data members to a data packet.
Parameters
p Packet to save data member values to
flat Specifies if the call to Save should be flat
Returns
true if saving was successful, false if it was not
Definition at line 69 of file Object.cpp.
References libcomp::Object::Save().
Referenced by libcomp::TcpConnection::QueueObject().
bool PersistentObject::SaveWithUUID (tinyxml2::XMLDocument & doc, tinyxml2::XMLElement & root, bool append = false) const
Save the object's data members to an XML file including the UUID.
Parameters
doc XML document to save the definition to
root Root XML node to save the definition to
append true if the root node should be appended to, false if an object node should be added to the root then appended to
Returns
true if saving was successful, false if it was not
Definition at line 362 of file PersistentObject.cpp.
References GetUUID(), and libcomp::Object::Save().
bool Object::SkipPadding (std::istream & stream, uint8_t count) protected inherited
Utility function to skip padding bytes when reading from a datastream.
Parameters
stream Byte stream being read from
count Number of bytes to skip
Returns
true if the stream is still good after skipping
Definition at line 319 of file Object.cpp.
template<class T > static std::list<std::shared_ptr<PersistentObject> > libcomp::PersistentObject::ToList (std::list< std::shared_ptr< T >> objList) inline static
Convert a list of PersistentObject derived object pointers into a list of PersistentObject pointers.
Parameters
objList List of PersistentObject derived object pointers
Returns
List of PersistentObject pointers
Definition at line 297 of file PersistentObject.h.
void PersistentObject::Unregister ()
Unregisters an object from the cache and marks it as deleted.
Once an object is marked as deleted, it will not be cached again.
Definition at line 171 of file PersistentObject.cpp.
References mCacheLock, mDeleted, mUUID, and sCached.
bool PersistentObject::Update (const std::shared_ptr< Database > & db)
Update an existing record in the database.
Parameters
db Database to load from
Returns
true on success, false on failure
Definition at line 340 of file PersistentObject.cpp.
References mSelf.
Referenced by libcomp::ScriptEngine::Using().
bool Object::WritePadding (std::ostream & stream, uint8_t count) const protected inherited
Utility function to write padding bytes when writing to a datastream.
Parameters
stream Byte stream being written to
count Number of bytes to write
Returns
true if the stream is still good after writing
Definition at line 327 of file Object.cpp.
Friends And Related Function Documentation
friend class ScriptEngine friend
Definition at line 59 of file PersistentObject.h.
Member Data Documentation
std::mutex PersistentObject::mCacheLock static private
Mutex to lock accessing the cache.
Definition at line 412 of file PersistentObject.h.
Referenced by GetObjectByUUID(), Register(), Unregister(), and ~PersistentObject().
bool libcomp::PersistentObject::mDeleted private
Indicator that the object has been deleted and should not be cached again.
Definition at line 428 of file PersistentObject.h.
Referenced by IsDeleted(), and Unregister().
std::set<std::string> libcomp::PersistentObject::mDirtyFields protected
Set of fields that have been updated since the last save operation.
Definition at line 404 of file PersistentObject.h.
std::mutex libcomp::Object::mFieldLock protected inherited
Mutex to lock accessing the object fields.
Definition at line 284 of file Object.h.
std::weak_ptr<PersistentObject> libcomp::PersistentObject::mSelf private
Pointer to object itself.
Definition at line 425 of file PersistentObject.h.
Referenced by Delete(), Insert(), PersistentObject(), and Update().
libobjgen::UUID libcomp::PersistentObject::mUUID protected
UUID associated to the object.
Definition at line 401 of file PersistentObject.h.
Referenced by GetUUID(), Unregister(), and ~PersistentObject().
std::unordered_map< std::string, std::weak_ptr< PersistentObject > > PersistentObject::sCached static private
Map of intantiated objects listed by their UUID.
Definition at line 409 of file PersistentObject.h.
Referenced by GetObjectByUUID(), Register(), Unregister(), and ~PersistentObject().
std::unordered_map< size_t, std::function< PersistentObject *()> > PersistentObject::sFactory static private
Static map of functions to create an object by their C++ type hash.
Definition at line 419 of file PersistentObject.h.
Referenced by New(), and RegisterType().
bool PersistentObject::sInitializationFailed = false static protected
Static value to be set to true if any PersistentObject type fails to register itself at runtime.
Definition at line 398 of file PersistentObject.h.
Referenced by Initialize().
PersistentObject::TypeMap PersistentObject::sTypeMap static private
Static map of MetaObject definitions by the source object's C++ type hash.
Definition at line 415 of file PersistentObject.h.
Referenced by GetRegisteredMetadata(), GetRegistry(), LoadObjectByUUID(), and RegisterType().
std::unordered_map< std::string, size_t > PersistentObject::sTypeNames static private
Static map of C++ type hashes by name.
Definition at line 422 of file PersistentObject.h.
Referenced by GetTypeHashByName(), and RegisterType().
The documentation for this class was generated from the following files:
PersistentObject.h
PersistentObject.cpp