COMP_hack: libcomp::DatabaseChangeSet Class Reference
libcomp::DatabaseChangeSet Class Reference abstract
Database change set grouped by a transaction UUID to be processed as one operation.
#include <DatabaseChangeSet.h>
Public Member Functions
DatabaseChangeSet ()
Create a new database change set.
DatabaseChangeSet (const libobjgen::UUID &uuid)
Create a new database change set.
virtual ~DatabaseChangeSet ()
Clean up the database change set.
virtual void Delete (const std::shared_ptr< PersistentObject > &obj)=0
Add an object for deletion to the change set.
const libobjgen::UUID GetTransactionUUID () const
Get the transaction UUID.
virtual void Insert (const std::shared_ptr< PersistentObject > &obj)=0
Add an object for insertion to the change set.
virtual void Update (const std::shared_ptr< PersistentObject > &obj)=0
Add an object for update to the change set.
Static Public Member Functions
static std::shared_ptr
< DatabaseChangeSet > Create (const libobjgen::UUID &uuid=NULLUUID)
Static builder for a new standard DatabaseChangeSet pointer.
Private Attributes
libobjgen::UUID mTransactionUUID
UUID used to group the transaction changes.
Detailed Description
Database change set grouped by a transaction UUID to be processed as one operation.
Definition at line 50 of file DatabaseChangeSet.h.
Constructor & Destructor Documentation
DatabaseChangeSet::DatabaseChangeSet ()
Create a new database change set.
Definition at line 37 of file DatabaseChangeSet.cpp.
DatabaseChangeSet::DatabaseChangeSet (const libobjgen::UUID & uuid)
Create a new database change set.
Parameters
uuid UUID of the grouped transaction changes
Definition at line 41 of file DatabaseChangeSet.cpp.
DatabaseChangeSet::~DatabaseChangeSet () virtual
Clean up the database change set.
Definition at line 46 of file DatabaseChangeSet.cpp.
Member Function Documentation
std::shared_ptr< DatabaseChangeSet > DatabaseChangeSet::Create (const libobjgen::UUID & uuid = NULLUUID) static
Static builder for a new standard DatabaseChangeSet pointer.
Parameters
uuid Optional UUID associated to the transaction
Returns
Pointer to a new DatabaseChangeSet
Definition at line 50 of file DatabaseChangeSet.cpp.
Referenced by libcomp::Database::QueueDelete(), libcomp::Database::QueueInsert(), libcomp::Database::QueueUpdate(), and TEST().
virtual void libcomp::DatabaseChangeSet::Delete (const std::shared_ptr< PersistentObject > & obj) pure virtual
Add an object for deletion to the change set.
Parameters
obj Pointer to the object to delete
Implemented in libcomp::DBOperationalChangeSet, and libcomp::DBStandardChangeSet.
const libobjgen::UUID DatabaseChangeSet::GetTransactionUUID () const
Get the transaction UUID.
Returns
UUID associated to the transaction
Definition at line 56 of file DatabaseChangeSet.cpp.
References mTransactionUUID.
virtual void libcomp::DatabaseChangeSet::Insert (const std::shared_ptr< PersistentObject > & obj) pure virtual
Add an object for insertion to the change set.
Parameters
obj Pointer to the object to insert
Implemented in libcomp::DBOperationalChangeSet, and libcomp::DBStandardChangeSet.
virtual void libcomp::DatabaseChangeSet::Update (const std::shared_ptr< PersistentObject > & obj) pure virtual
Add an object for update to the change set.
Parameters
obj Pointer to the object to update
Implemented in libcomp::DBOperationalChangeSet, and libcomp::DBStandardChangeSet.
Member Data Documentation
libobjgen::UUID libcomp::DatabaseChangeSet::mTransactionUUID private
UUID used to group the transaction changes.
Useful when tying a transaction back to a parent object the UUID belongs to.
Definition at line 105 of file DatabaseChangeSet.h.
Referenced by GetTransactionUUID().
The documentation for this class was generated from the following files:
DatabaseChangeSet.h
DatabaseChangeSet.cpp