COMP_hack: Sqrat::u64 Class Reference
Sqrat::u64 Class Reference
#include <SqratInt64.h>
Public Member Functions
u64 ()
u64 (int32_t value)
u64 (const u64 &other)
libcomp::String _tostring () const
void set (uint64_t value)
uint64_t value () const
int32_t valueTruncated () const
Static Public Member Functions
static SQInteger _add (HSQUIRRELVM vm)
static SQInteger _cmp (HSQUIRRELVM vm)
static SQInteger _div (HSQUIRRELVM vm)
static SQInteger _mod (HSQUIRRELVM vm)
static SQInteger _mul (HSQUIRRELVM vm)
static SQInteger _sub (HSQUIRRELVM vm)
static SQInteger equal (HSQUIRRELVM vm)
Private Attributes
uint64_t mValue
Detailed Description
Definition at line 67 of file SqratInt64.h.
Constructor & Destructor Documentation
Sqrat::u64::u64 ()
Definition at line 360 of file SqratInt64.cpp.
Sqrat::u64::u64 (int32_t value)
Definition at line 365 of file SqratInt64.cpp.
Sqrat::u64::u64 (const u64 & other)
Definition at line 370 of file SqratInt64.cpp.
References mValue.
Member Function Documentation
SQInteger Sqrat::u64::_add (HSQUIRRELVM vm) static
Definition at line 428 of file SqratInt64.cpp.
References mValue.
Referenced by libcomp::ScriptEngine::Using< Sqrat::u64 >().
SQInteger Sqrat::u64::_cmp (HSQUIRRELVM vm) static
Definition at line 375 of file SqratInt64.cpp.
Referenced by libcomp::ScriptEngine::Using< Sqrat::u64 >().
SQInteger Sqrat::u64::_div (HSQUIRRELVM vm) static
Definition at line 539 of file SqratInt64.cpp.
References mValue.
Referenced by libcomp::ScriptEngine::Using< Sqrat::u64 >().
SQInteger Sqrat::u64::_mod (HSQUIRRELVM vm) static
Definition at line 586 of file SqratInt64.cpp.
References mValue.
Referenced by libcomp::ScriptEngine::Using< Sqrat::u64 >().
SQInteger Sqrat::u64::_mul (HSQUIRRELVM vm) static
Definition at line 502 of file SqratInt64.cpp.
References mValue.
Referenced by libcomp::ScriptEngine::Using< Sqrat::u64 >().
SQInteger Sqrat::u64::_sub (HSQUIRRELVM vm) static
Definition at line 465 of file SqratInt64.cpp.
References mValue.
Referenced by libcomp::ScriptEngine::Using< Sqrat::u64 >().
libcomp::String Sqrat::u64::_tostring () const
Definition at line 633 of file SqratInt64.cpp.
References libcomp::String::Arg().
Referenced by libcomp::ScriptEngine::Using< Sqrat::u64 >().
SQInteger Sqrat::u64::equal (HSQUIRRELVM vm) static
Definition at line 653 of file SqratInt64.cpp.
Referenced by libcomp::ScriptEngine::Using< Sqrat::u64 >().
void Sqrat::u64::set (uint64_t value)
Definition at line 638 of file SqratInt64.cpp.
uint64_t Sqrat::u64::value () const
Definition at line 643 of file SqratInt64.cpp.
int32_t Sqrat::u64::valueTruncated () const
Definition at line 648 of file SqratInt64.cpp.
Referenced by libcomp::ScriptEngine::Using< Sqrat::u64 >().
Member Data Documentation
uint64_t Sqrat::u64::mValue private
Definition at line 70 of file SqratInt64.h.
Referenced by _add(), _div(), _mod(), _mul(), _sub(), and u64().
The documentation for this class was generated from the following files:
SqratInt64.h
SqratInt64.cpp