COMP_hack: libcomp::ManagerPacket Class Reference
libcomp::ManagerPacket Class Reference
Manager dedicated to handling messages of type libcomp::Message::Packet.
#include <ManagerPacket.h>
Public Member Functions
ManagerPacket (std::weak_ptr< libcomp::BaseServer > server)
Create a new manager.
virtual ~ManagerPacket ()
Cleanup the manager.
template<class T >
bool AddParser (CommandCode_t commandCode)
Adds a packet parser of the specified type to this manager to handle a specific command code.
std::shared_ptr
< libcomp::BaseServer > GetServer ()
Get the server that uses this manager.
virtual std::list
< libcomp::Message::MessageType > GetSupportedTypes () const
Get the different types of messages handled by the manager.
virtual bool ProcessMessage (const libcomp::Message::Message *pMessage)
Process a message from the queue.
Protected Member Functions
virtual bool ValidateConnectionState (const std::shared_ptr< libcomp::TcpConnection > &connection, CommandCode_t commandCode) const
Protected Attributes
std::unordered_map
< CommandCode_t,
std::shared_ptr< PacketParser > > mPacketParsers
Packet parser map by command code used to process messages.
std::weak_ptr
< libcomp::BaseServer > mServer
Pointer to the server that uses this manager.
Static Protected Attributes
static std::list
< libcomp::Message::MessageType > sSupportedTypes
Static list containing the packet message type to return via ManagerPacket::GetSupportedTypes.
Detailed Description
Manager dedicated to handling messages of type libcomp::Message::Packet.
Definition at line 51 of file ManagerPacket.h.
Constructor & Destructor Documentation
ManagerPacket::ManagerPacket (std::weak_ptr< libcomp::BaseServer > server)
Create a new manager.
Parameters
server Pointer to the server that uses this manager
Definition at line 42 of file ManagerPacket.cpp.
ManagerPacket::~ManagerPacket () virtual
Cleanup the manager.
Definition at line 47 of file ManagerPacket.cpp.
Member Function Documentation
template<class T > bool libcomp::ManagerPacket::AddParser (CommandCode_t commandCode) inline
Adds a packet parser of the specified type to this manager to handle a specific command code.
Parameters
commandCode Packet command code to handle
Returns
true if its a valid type and the command code is not already being handled, false otherwise
Definition at line 72 of file ManagerPacket.h.
References mPacketParsers.
std::shared_ptr< libcomp::BaseServer > ManagerPacket::GetServer ()
Get the server that uses this manager.
Returns
Pointer to the server that uses this manager
Definition at line 132 of file ManagerPacket.cpp.
References mServer.
std::list< libcomp::Message::MessageType > ManagerPacket::GetSupportedTypes () const virtual
Get the different types of messages handled by the manager.
Returns
List of message types handled by the manager
Implements libcomp::Manager.
Definition at line 52 of file ManagerPacket.cpp.
References sSupportedTypes.
bool ManagerPacket::ProcessMessage (const libcomp::Message::Message * pMessage) virtual
Process a message from the queue.
Parameters
pMessage Message to be processed
Returns
true on success, false on failure
Implements libcomp::Manager.
Definition at line 57 of file ManagerPacket.cpp.
References libcomp::String::Arg(), libcomp::Message::Packet::GetCommandCode(), libcomp::Message::Packet::GetConnection(), libcomp::Message::Packet::GetPacket(), mPacketParsers, libcomp::ReadOnlyPacket::Rewind(), and ValidateConnectionState().
bool ManagerPacket::ValidateConnectionState (const std::shared_ptr< libcomp::TcpConnection > & connection, CommandCode_t commandCode) const protected virtual
Definition at line 137 of file ManagerPacket.cpp.
Referenced by ProcessMessage().
Member Data Documentation
std::unordered_map<CommandCode_t, std::shared_ptr<PacketParser> > libcomp::ManagerPacket::mPacketParsers protected
Packet parser map by command code used to process messages.
Definition at line 104 of file ManagerPacket.h.
Referenced by AddParser(), and ProcessMessage().
std::weak_ptr<libcomp::BaseServer> libcomp::ManagerPacket::mServer protected
Pointer to the server that uses this manager.
Definition at line 107 of file ManagerPacket.h.
Referenced by GetServer().
std::list< libcomp::Message::MessageType > ManagerPacket::sSupportedTypes static protected
Initial value:
=
    { libcomp::Message::MessageType::MESSAGE_TYPE_PACKET }
Static list containing the packet message type to return via ManagerPacket::GetSupportedTypes.
Definition at line 100 of file ManagerPacket.h.
Referenced by GetSupportedTypes().
The documentation for this class was generated from the following files:
ManagerPacket.h
ManagerPacket.cpp