COMP_hack: libcomp::EncryptedConnection Class Reference
libcomp::EncryptedConnection Class Reference
Represents an encrypted network connection.
#include <EncryptedConnection.h>
Public Types
enum ConnectionStatus_t {
STATUS_NOT_CONNECTED = 0, STATUS_CONNECTING, STATUS_CONNECTED, STATUS_WAITING_ENCRYPTION,
STATUS_ENCRYPTED
}
Status of the connection.
enum Role_t { ROLE_SERVER = 0, ROLE_CLIENT }
Role the server is operating in.
Public Member Functions
EncryptedConnection (asio::io_service &io_service)
Create a new encrypted connection.
EncryptedConnection (asio::ip::tcp::socket &socket, const std::shared_ptr< Crypto::DiffieHellman > &diffieHellman)
Create a new encrypted connection.
virtual ~EncryptedConnection ()
Cleanup the connection object.
virtual bool Close ()
Close the connection to the remote host.
bool Connect (const String &host, uint16_t port=0, bool async=true)
Connect to the remote host (client role).
virtual void ConnectionSuccess ()
Called when a connection has been established.
void FlushOutgoing (bool closeConnection=false)
Send all queued packets to the remote host.
String GetName () const
Get the debug name for the connection.
String GetRemoteAddress () const
Get the address of the remote host.
Role_t GetRole () const
Get the role the connection is operating in.
ConnectionStatus_t GetStatus () const
Get the status of the connection.
virtual bool QueueObject (const Object &obj)
Queue an object to be packetized and sent.
virtual void QueuePacket (Packet &packet)
Queue a packet to be sent.
virtual void QueuePacket (ReadOnlyPacket &packet)
Queue a packet to be sent.
virtual void QueuePacketCopy (libcomp::Packet &packet)
Queue a copy of a packet to be sent.
bool RequestPacket (size_t size)
Start a receive request for more packet data.
virtual bool SendObject (const Object &obj, bool closeConnection=false)
Packetize and queue an object and then send all queued packets to the remote host.
virtual void SendPacket (Packet &packet, bool closeConnection=false)
Queue a packet and then send all queued packets to the remote host.
virtual void SendPacket (ReadOnlyPacket &packet, bool closeConnection=false)
Queue a packet and then send all queued packets to the remote host.
virtual void SendPacketCopy (libcomp::Packet &packet, bool closeConnection=false)
Queue a copy of a packet and then send all queued packets to the remote host.
void SetMessageQueue (const std::weak_ptr< MessageQueue< libcomp::Message::Message * >> &messageQueue)
Set the message queue for this connection.
void SetName (const String &name)
Set the debug name for the connection.
void SetServerConfig (const std::shared_ptr< objects::ServerConfig > &config)
Set the server configuration object.
Static Public Member Functions
static void BroadcastPacket (const std::list< std::shared_ptr< TcpConnection >> &connections, Packet &packet)
Send a packet to a list of connections.
static void BroadcastPacket (const std::list< std::shared_ptr< TcpConnection >> &connections, ReadOnlyPacket &packet)
Send a packet to a list of connections.
static String GenerateDiffieHellmanPublic (const std::shared_ptr< Crypto::DiffieHellman > &diffieHellman)
Generate the public key for the Diffie-Hellman key exchange.
static std::vector< char > GenerateDiffieHellmanSharedData (const std::shared_ptr< Crypto::DiffieHellman > &diffieHellman, const String &otherPublic)
Return the shared private from the Diffie-Hellman key exchange.
static String GetDiffieHellmanPrime (const std::shared_ptr< Crypto::DiffieHellman > &diffieHellman)
Get the prime used in the Diffie-Hellman key exchange.
Protected Types
typedef void(EncryptedConnection::* PacketParser_t)(libcomp::Packet &packet)
Type for a packet parsing function.
Protected Member Functions
virtual void Connect (const asio::ip::tcp::endpoint &endpoint, bool async=true)
Internal connect function to an ASIO end point.
virtual void ConnectionEncrypted ()
Called when the connection transitions into the encrypted state.
virtual void ConnectionFailed ()
Called if a connection attempt has failed.
virtual bool DecompressPacket (libcomp::Packet &packet, uint32_t &paddedSize, uint32_t &realSize, uint32_t &dataStart)
Decompress a packet.
virtual std::list< ReadOnlyPacket > GetCombinedPackets ()
Returns a list of packets that have been combined.
virtual uint32_t GetHeaderSize ()
Returns the size of the combined packet header.
virtual void PacketReceived (libcomp::Packet &packet)
Called after a packet has been received from the remote host.
virtual void PacketSent (ReadOnlyPacket &packet)
Called after a packet has been sent to the remote host.
void ParseClientEncryptionStart (libcomp::Packet &packet)
Parse the initial encryption packet from the server.
virtual bool ParseExtensionConnection (libcomp::Packet &packet)
Parse additional magic sequences.
void ParsePacket (libcomp::Packet &packet)
Parse incoming encrypted packet data.
void ParsePacket (libcomp::Packet &packet, uint32_t paddedSize, uint32_t realSize)
Parse an encrypted packet that has been fully received.
void ParseServerEncryptionFinish (libcomp::Packet &packet)
Parse the final client packet needed for encryption.
void ParseServerEncryptionStart (libcomp::Packet &packet)
Parse the initial packet from the client.
virtual void PreparePackets (std::list< ReadOnlyPacket > &packets)
Called to prepare packets before they are sent to the remote host.
void SendMessage (const std::function< libcomp::Message::Message *(const std::shared_ptr< libcomp::TcpConnection > &)> &messageAllocFunction)
Send a message to the message queue.
void SetEncryptionKey (const std::vector< char > &data)
Sets the Blowfish encryption key to be used.
void SetEncryptionKey (const void *pData, size_t dataSize)
Sets the Blowfish encryption key to be used.
virtual void SocketError (const libcomp::String &errorMessage=libcomp::String())
Report a socket error.
Protected Attributes
std::ofstream * mCaptureFile
File to save a capture to.
std::shared_ptr
< Crypto::DiffieHellman > mDiffieHellman
Diffie-Hellman key exchange data.
Crypto::Blowfish mEncryptionKey
Blowfish encryption key.
std::weak_ptr< MessageQueue
< libcomp::Message::Message * > > mMessageQueue
Shared pointer for the message queue for this connection.
ReadOnlyPacket mOutgoing
Packet being sent to the remote host.
std::mutex mOutgoingMutex
Mutex to ensure the outgoing packet code is executed from one thread.
std::list< ReadOnlyPacket > mOutgoingPackets
List of packets to be sent to the remote host.
PacketParser_t mPacketParser
Active parse being used for received packets.
bool mSendingPacket
Indicates if an outgoing packet is being sent.
std::shared_ptr
< objects::ServerConfig > mServerConfig
Server configuration.
ConnectionStatus_t mStatus
Status of the connection.
Detailed Description
Represents an encrypted network connection.
This connection will perform a Diffie-Hellman key exchange to negotiate a shared private. This shared private will then be used as a Blowfish key to encrypt all other packets.
Encryption Sequence
Encryption is initiated by the client sending an 8 byte magic sequence to the server. On receipt of this magic sequence the server will reply with a Diffie-Hellman base, prime, and server public. This packet starts with 4 bytes of 0 value followed by hex encoded strings of the base, prime, and server public (in that order). Each string begins with a 32-bit big endian value indicating the size of the string followed by the string data. There is no padding or zero byte on these strings.
When the client receives this packet from the server it will perform two tasks. First, it will generate a random number to use as the client private. This client private will be combined with the base and prime using the DH algorithm to generate the client public. This client public is sent to the server. This packet consists of just the client public in a hex encoded string using the same string format described above. Second, the client will use the server public in addition to the base, prime, and client private with the DH algorithm to generate the shared private (calculated by both parties). This shared private is used as the Blowfish key for the encryption of the packets described in the next section. At this point the client is in an encrypted state. New packets send by the client are in the format described in the next section.
When the server receives the client public it will use this to generate the same shared private value. The same procedure is used to transition into the encrypted state. At this point the server is in an encrypted state. New packets send by the client are in the format described in the next section.
Once in the encrypted state it is the responsibility of the client to initiate the communication flow with the first command packet.
Packet Protocol
Diagram of the Packet Protocol
All packets start with two sizes in 32-bit big endian format. These sizes indicate the padded size (size over the wire) used for encryption and the actual size of the decrypted data. These sizes are of the remaining data. Neither accounts for the 8 bytes consumed by the sizes.
The next set of data, the compression information, only appears in channel connections. The magic "gzip" and the magic "lv6\0" indicate the compression method and do not change. While the magic mentions "gzip" it's actually a raw zlib stream without the gzip format. The uncompressed and compressed sizes are in 32-bit little endian format. If the uncompressed and compressed sizes are equal, the data following the compression information is assumed to be uncompressed. Please note that if you are compressing a packet you should check the compressed size against the uncompressed size. If they are equal (or the compressed size is greater than the uncompressed size) the compressed data should be thrown away and the original uncompressed data should be used instead.
After the decryption and optional decompression stage, the remaining data is interpreted as a sequence of commands. Each command must have two sizes followed by the command code. Each command may have a number of command specific bytes following the command code. The number of command specific bytes is determined by the command size(s). The command sizes are in 16-bit big and little endian format. The command size is equal to the number of command specific bytes plus 4. This could be adding on the size of the command code and one of the sizes or both sizes but not the command code. Either way, it doesn't make much sense. The command code is in 16-bit little endian format and indicates what action should be taken on receipt of the command. The command code will indicate how to interpret the command specific bytes (if they exist for the given command).
The encrypted connection will send a libcomp::Message::Packet to the message queue provided by SetMessageQueue for each command parsed. The message object will provide the command code and the packet data will contain only the command specific data for that specific command.
Definition at line 129 of file EncryptedConnection.h.
Member Typedef Documentation
typedef void(EncryptedConnection::* libcomp::EncryptedConnection::PacketParser_t)(libcomp::Packet &packet) protected
Type for a packet parsing function.
This is used for the different encryption states to handle incoming packets.
Parameters
packet Packet that was received.
Definition at line 192 of file EncryptedConnection.h.
Member Enumeration Documentation
enum libcomp::TcpConnection::ConnectionStatus_t inherited
Status of the connection.
Enumerator
STATUS_NOT_CONNECTED
Not connected to remote system.
STATUS_CONNECTING
Connecting to a remote system.
STATUS_CONNECTED
Connected to a remote system.
STATUS_WAITING_ENCRYPTION
Waiting for encryption to complete.
STATUS_ENCRYPTED
Connection is established and encrypted.
Definition at line 68 of file TcpConnection.h.
enum libcomp::TcpConnection::Role_t inherited
Role the server is operating in.
Enumerator
ROLE_SERVER
Server role that can accept connections.
ROLE_CLIENT
Client role that will connect to a remote server.
Definition at line 59 of file TcpConnection.h.
Constructor & Destructor Documentation
EncryptedConnection::EncryptedConnection (asio::io_service & io_service)
Create a new encrypted connection.
Parameters
io_service ASIO service to manage this connection.
Definition at line 47 of file EncryptedConnection.cpp.
EncryptedConnection::EncryptedConnection (asio::ip::tcp::socket & socket, const std::shared_ptr< Crypto::DiffieHellman > & diffieHellman)
Create a new encrypted connection.
Parameters
socket Socket provided by the server for the new client.
diffieHellman Asymmetric encryption information.
Definition at line 53 of file EncryptedConnection.cpp.
EncryptedConnection::~EncryptedConnection () virtual
Cleanup the connection object.
Definition at line 60 of file EncryptedConnection.cpp.
References mCaptureFile.
Member Function Documentation
void TcpConnection::BroadcastPacket (const std::list< std::shared_ptr< TcpConnection >> & connections, Packet & packet) static inherited
Send a packet to a list of connections.
Parameters
connections List of connections to send the packet to.
packet Packet to send to the list of connections.
Definition at line 493 of file TcpConnection.cpp.
void TcpConnection::BroadcastPacket (const std::list< std::shared_ptr< TcpConnection >> & connections, ReadOnlyPacket & packet) static inherited
Send a packet to a list of connections.
Parameters
connections List of connections to send the packet to.
packet Packet to send to the list of connections.
Definition at line 501 of file TcpConnection.cpp.
bool EncryptedConnection::Close () virtual
Close the connection to the remote host.
Returns
true on success; false otherwise.
Reimplemented from libcomp::TcpConnection.
Definition at line 69 of file EncryptedConnection.cpp.
References libcomp::TcpConnection::Close(), and mMessageQueue.
bool TcpConnection::Connect (const String & host, uint16_t port = 0, bool async = true) inherited
Connect to the remote host (client role).
Parameters
host IP or DNS name of the remote host.
port Port of the remote host to connect to.
async If the connection should be asynchronous.
Returns
true on success; false otherwise.
Definition at line 71 of file TcpConnection.cpp.
References libcomp::String::Arg(), libcomp::TcpConnection::mSocket, and libcomp::String::ToUtf8().
void TcpConnection::Connect (const asio::ip::tcp::endpoint & endpoint, bool async = true) protected virtual inherited
Internal connect function to an ASIO end point.
Parameters
endpoint End point to connect to.
async If the connection should be asynchronous.
Definition at line 268 of file TcpConnection.cpp.
References libcomp::TcpConnection::HandleConnection(), libcomp::TcpConnection::mRemoteAddress, libcomp::TcpConnection::mSocket, libcomp::TcpConnection::mStatus, and libcomp::TcpConnection::STATUS_CONNECTING.
void EncryptedConnection::ConnectionEncrypted () protected virtual
Called when the connection transitions into the encrypted state.
Definition at line 143 of file EncryptedConnection.cpp.
References libcomp::String::Arg(), libcomp::TcpConnection::GetRemoteAddress(), mCaptureFile, mServerConfig, and SendMessage().
Referenced by ParseClientEncryptionStart(), and ParseServerEncryptionFinish().
void TcpConnection::ConnectionFailed () protected virtual inherited
Called if a connection attempt has failed.
Definition at line 438 of file TcpConnection.cpp.
Referenced by libcomp::TcpConnection::HandleConnection().
void EncryptedConnection::ConnectionSuccess () virtual
Called when a connection has been established.
Reimplemented from libcomp::TcpConnection.
Reimplemented in libcomp::LobbyConnection.
Definition at line 104 of file EncryptedConnection.cpp.
References libcomp::String::Arg(), libcomp::TcpConnection::GetRemoteAddress(), libcomp::TcpConnection::GetRole(), mPacketParser, ParseClientEncryptionStart(), ParseServerEncryptionStart(), libcomp::TcpConnection::RequestPacket(), libcomp::TcpConnection::ROLE_CLIENT, libcomp::TcpConnection::SendPacket(), SocketError(), and libcomp::Packet::WriteU32Big().
Referenced by libcomp::LobbyConnection::ConnectionSuccess().
bool EncryptedConnection::DecompressPacket (libcomp::Packet & packet, uint32_t & paddedSize, uint32_t & realSize, uint32_t & dataStart) protected virtual
Decompress a packet.
This base implementation does nothing as only some connections support this part of the protocol.
See Also
ChannelConnection
InternalConnection
LobbyConnection
Parameters
packet Packet to decompress.
paddedSize Over the wire size of the packet.
realSize Actual size of the packet.
dataStart Offset into the packet of where the compressed data is.
Returns
true on success; false otherwise.
Reimplemented in libcomp::ChannelConnection.
Definition at line 761 of file EncryptedConnection.cpp.
Referenced by ParsePacket().
void TcpConnection::FlushOutgoing (bool closeConnection = false) inherited
Send all queued packets to the remote host.
Parameters
closeConnection If the connection should be closed after the send queue has been emptied.
Definition at line 319 of file TcpConnection.cpp.
References libcomp::TcpConnection::FlushOutgoingInside(), libcomp::TcpConnection::GetCombinedPackets(), libcomp::TcpConnection::mOutgoing, libcomp::TcpConnection::PreparePackets(), and libcomp::ReadOnlyPacket::Rewind().
Referenced by libcomp::TcpConnection::SendObject(), and libcomp::TcpConnection::SendPacket().
String TcpConnection::GenerateDiffieHellmanPublic (const std::shared_ptr< Crypto::DiffieHellman > & diffieHellman) static inherited
Generate the public key for the Diffie-Hellman key exchange.
Parameters
diffieHellman Object that stores the DH key.
Returns
Public key to be used in the DH key exchange.
Definition at line 480 of file TcpConnection.cpp.
Referenced by ParseClientEncryptionStart(), and ParseServerEncryptionStart().
std::vector< char > TcpConnection::GenerateDiffieHellmanSharedData (const std::shared_ptr< Crypto::DiffieHellman > & diffieHellman, const String & otherPublic) static inherited
Return the shared private from the Diffie-Hellman key exchange.
Parameters
diffieHellman Object that stores the DH key.
otherPublic Public key from the other party.
Returns
Shared private data upon completion of the DH key exchange.
Definition at line 486 of file TcpConnection.cpp.
Referenced by ParseClientEncryptionStart(), and ParseServerEncryptionFinish().
std::list< ReadOnlyPacket > EncryptedConnection::GetCombinedPackets () protected virtual
Returns a list of packets that have been combined.
Returns
List of packet that have been combined.
Reimplemented from libcomp::TcpConnection.
Definition at line 839 of file EncryptedConnection.cpp.
References GetHeaderSize(), libcomp::TcpConnection::mOutgoingMutex, libcomp::TcpConnection::mOutgoingPackets, libcomp::TcpConnection::mSendingPacket, and libcomp::ReadOnlyPacket::Size().
String TcpConnection::GetDiffieHellmanPrime (const std::shared_ptr< Crypto::DiffieHellman > & diffieHellman) static inherited
Get the prime used in the Diffie-Hellman key exchange.
Parameters
diffieHellman Object that stores the DH key.
Returns
Prime to be used in the DH key exchange.
Definition at line 474 of file TcpConnection.cpp.
Referenced by ParseServerEncryptionStart(), and libcomp::TcpServer::Start().
uint32_t EncryptedConnection::GetHeaderSize () protected virtual
Returns the size of the combined packet header.
Returns
Size of the combined packet header.
Reimplemented in libcomp::ChannelConnection.
Definition at line 875 of file EncryptedConnection.cpp.
Referenced by GetCombinedPackets(), and PreparePackets().
String TcpConnection::GetName () const inherited
Get the debug name for the connection.
Definition at line 543 of file TcpConnection.cpp.
References libcomp::TcpConnection::mName.
Referenced by libcomp::TcpConnection::Close(), libcomp::TcpConnection::ConnectionSuccess(), libcomp::TcpConnection::SocketError(), and libcomp::TcpConnection::~TcpConnection().
String TcpConnection::GetRemoteAddress () const inherited
Get the address of the remote host.
Returns
Address of the remote host.
Definition at line 263 of file TcpConnection.cpp.
References libcomp::TcpConnection::mRemoteAddress.
Referenced by ConnectionEncrypted(), libcomp::LobbyConnection::ConnectionSuccess(), ConnectionSuccess(), libcomp::LobbyConnection::ParseExtensionConnection(), SocketError(), and libcomp::TcpConnection::SocketError().
TcpConnection::Role_t TcpConnection::GetRole () const inherited
Get the role the connection is operating in.
Returns
Role the connection is operating in.
Definition at line 253 of file TcpConnection.cpp.
References libcomp::TcpConnection::mRole.
Referenced by libcomp::LobbyConnection::ConnectionSuccess(), ConnectionSuccess(), libcomp::LobbyConnection::ParseExtensionConnection(), and SocketError().
TcpConnection::ConnectionStatus_t TcpConnection::GetStatus () const inherited
Get the status of the connection.
Returns
Status of the connection.
Definition at line 258 of file TcpConnection.cpp.
References libcomp::TcpConnection::mStatus.
Referenced by ParsePacket(), and SocketError().
void EncryptedConnection::PacketReceived (libcomp::Packet & packet) protected virtual
Called after a packet has been received from the remote host.
Parameters
packet Packet that was received.
Reimplemented from libcomp::TcpConnection.
Definition at line 772 of file EncryptedConnection.cpp.
References libcomp::Exception::Log(), mPacketParser, and SocketError().
void TcpConnection::PacketSent (ReadOnlyPacket & packet) protected virtual inherited
Called after a packet has been sent to the remote host.
Parameters
packet Packet that was sent to the remote host.
Definition at line 451 of file TcpConnection.cpp.
void EncryptedConnection::ParseClientEncryptionStart (libcomp::Packet & packet) protected
Parse the initial encryption packet from the server.
This is used when in the client role. This parser will take the reply from the server and extract the Diffie-Hellman base, prime, and server public. The connection will then generated the shared private and transition to the encrypted state. When this happens, ConnectionEncrypted will be called and a message will be added onto the libcomp::MessageQueue.
See Also
ConnectionEncrypted
SetMessageQueue
ParseServerEncryptionStart
ParseServerEncryptionFinish
Parameters
packet Incoming packet to parse.
Definition at line 272 of file EncryptedConnection.cpp.
References libcomp::Packet::Clear(), ConnectionEncrypted(), libcomp::Convert::ENCODING_UTF8, libcomp::TcpConnection::GenerateDiffieHellmanPublic(), libcomp::TcpConnection::GenerateDiffieHellmanSharedData(), libcomp::ReadOnlyPacket::Left(), libcomp::TcpServer::LoadDiffieHellman(), libcomp::TcpConnection::mDiffieHellman, mPacketParser, libcomp::TcpConnection::mStatus, ParsePacket(), libcomp::ReadOnlyPacket::PeekU32Big(), libcomp::ReadOnlyPacket::ReadString32Big(), libcomp::ReadOnlyPacket::ReadU32Big(), libcomp::TcpConnection::RequestPacket(), libcomp::TcpConnection::SendPacket(), libcomp::TcpConnection::SetEncryptionKey(), libcomp::ReadOnlyPacket::Size(), SocketError(), libcomp::TcpConnection::STATUS_ENCRYPTED, libcomp::TcpConnection::STATUS_WAITING_ENCRYPTION, and libcomp::Packet::WriteString32Big().
Referenced by ConnectionSuccess().
bool EncryptedConnection::ParseExtensionConnection (libcomp::Packet & packet) protected virtual
Parse additional magic sequences.
See the description in ParseServerEncryptionStart for what this additional magic sequences are for.
Parameters
packet Packet to parse.
Returns
true if the packet was parsed; false otherwise.
Reimplemented in libcomp::LobbyConnection.
Definition at line 470 of file EncryptedConnection.cpp.
Referenced by ParseServerEncryptionStart().
void EncryptedConnection::ParsePacket (libcomp::Packet & packet) protected
Parse incoming encrypted packet data.
This will buffer all incoming data. It will then peek at the first 8 bytes to determine the size of the packet. If a full packet is in the buffer it will call the other version of this function.
Parameters
packet Incoming packet data to parse.
Definition at line 551 of file EncryptedConnection.cpp.
References libcomp::Packet::Clear(), libcomp::TcpConnection::GetStatus(), libcomp::ReadOnlyPacket::ReadU32Big(), libcomp::TcpConnection::RequestPacket(), libcomp::ReadOnlyPacket::Size(), SocketError(), and libcomp::TcpConnection::STATUS_ENCRYPTED.
Referenced by ParseClientEncryptionStart(), and ParseServerEncryptionFinish().
void EncryptedConnection::ParsePacket (libcomp::Packet & packet, uint32_t paddedSize, uint32_t realSize) protected
Parse an encrypted packet that has been fully received.
This will first decrypt the packet. It will then decompress the packet if needed. Finally it will parse and split out each individual command. For each command, a libcomp::Message::Packet is generated and sent to the message queue set by SetMessageQueue.
See Also
SetMessageQueue
Parameters
packet Encrypted packet to parse.
paddedSize Over the wire size of the packet.
realSize Size of the packet after decryption.
Definition at line 607 of file EncryptedConnection.cpp.
References libcomp::ReadOnlyPacket::ConstData(), DecompressPacket(), libcomp::Crypto::Blowfish::DecryptPacket(), libcomp::ReadOnlyPacket::Left(), mCaptureFile, libcomp::TcpConnection::mEncryptionKey, mMessageQueue, libcomp::ReadOnlyPacket::ReadU16Little(), libcomp::ReadOnlyPacket::Seek(), libcomp::ReadOnlyPacket::Size(), libcomp::ReadOnlyPacket::Skip(), SocketError(), and libcomp::ReadOnlyPacket::Tell().
void EncryptedConnection::ParseServerEncryptionFinish (libcomp::Packet & packet) protected
Parse the final client packet needed for encryption.
This will parse the client public and generate the shared private. The shared private will then be used as the Blowfish key for future packets. The server will then transition into the encrypted state. When this happens, ConnectionEncrypted will be called and a message will be added onto the libcomp::MessageQueue.
See Also
ConnectionEncrypted
SetMessageQueue
ParseClientEncryptionStart
ParseServerEncryptionStart
Parameters
packet
Definition at line 477 of file EncryptedConnection.cpp.
References libcomp::Packet::Clear(), ConnectionEncrypted(), libcomp::Convert::ENCODING_UTF8, libcomp::TcpConnection::GenerateDiffieHellmanSharedData(), libcomp::ReadOnlyPacket::Left(), libcomp::TcpConnection::mDiffieHellman, mPacketParser, libcomp::TcpConnection::mStatus, ParsePacket(), libcomp::ReadOnlyPacket::PeekU32Big(), libcomp::ReadOnlyPacket::ReadString32Big(), libcomp::TcpConnection::RequestPacket(), libcomp::TcpConnection::SetEncryptionKey(), libcomp::ReadOnlyPacket::Size(), SocketError(), and libcomp::TcpConnection::STATUS_ENCRYPTED.
Referenced by ParseServerEncryptionStart().
void EncryptedConnection::ParseServerEncryptionStart (libcomp::Packet & packet) protected
Parse the initial packet from the client.
This will check for the encryption magic from the client. This will recognize two additional magic sequences for a ping and world connection request. These allow for a quick non-encrypted notification. The ping will send the client back the same magic sequence and close the connection. The world connection request will trigger an event that may connect back to the client. The port is encoded in the magic and the address is retrieved by the GetRemoteAddress function. For normal encrypted connections, the server will reply with the Diffie-Hellman base, prime, and the server public. It is then the responsibility of the client to perform two tasks. First, the client should use this information to generate the shared private. The shared private should be used as the Blowfish encryption key for future packets. Second, the client should reply to the server with it's client public in clear text. The server will parse this reply in the ParseServerEncryptionFinish function.
See Also
ParseClientEncryptionStart
ParseServerEncryptionFinish
Parameters
packet Incoming packet to parse.
Definition at line 409 of file EncryptedConnection.cpp.
References libcomp::Packet::Clear(), libcomp::Convert::ENCODING_UTF8, libcomp::TcpConnection::GenerateDiffieHellmanPublic(), libcomp::TcpConnection::GetDiffieHellmanPrime(), libcomp::ReadOnlyPacket::Left(), libcomp::TcpConnection::mDiffieHellman, mPacketParser, libcomp::TcpConnection::mStatus, ParseExtensionConnection(), ParseServerEncryptionFinish(), libcomp::ReadOnlyPacket::ReadU32Big(), libcomp::TcpConnection::RequestPacket(), libcomp::ReadOnlyPacket::Rewind(), libcomp::TcpConnection::SendPacket(), libcomp::ReadOnlyPacket::Size(), SocketError(), libcomp::TcpConnection::STATUS_WAITING_ENCRYPTION, libcomp::Packet::WriteBlank(), and libcomp::Packet::WriteString32Big().
Referenced by ConnectionSuccess().
void EncryptedConnection::PreparePackets (std::list< ReadOnlyPacket > & packets) protected virtual
Called to prepare packets before they are sent to the remote host.
This will combine commands into a single over the wire packet. It will then encrypt it. If the connection is not in the encrypted state it will not alter the packet data.
Parameters
packets List of packets to be sent to the remote host.
Reimplemented from libcomp::TcpConnection.
Reimplemented in libcomp::ChannelConnection.
Definition at line 803 of file EncryptedConnection.cpp.
References libcomp::Crypto::Blowfish::EncryptPacket(), GetHeaderSize(), libcomp::TcpConnection::mEncryptionKey, libcomp::TcpConnection::mOutgoing, libcomp::TcpConnection::mStatus, libcomp::TcpConnection::STATUS_ENCRYPTED, libcomp::TcpConnection::STATUS_NOT_CONNECTED, libcomp::Packet::WriteArray(), libcomp::Packet::WriteBlank(), libcomp::Packet::WriteU16Big(), and libcomp::Packet::WriteU16Little().
Referenced by libcomp::ChannelConnection::PreparePackets().
bool TcpConnection::QueueObject (const Object & obj) virtual inherited
Queue an object to be packetized and sent.
Note
This will not send the packet until SendPacket or FlushOutgoing is called.
Parameters
obj Object to be packetized.
Returns
true if the object could be packetized; false otherwise.
Definition at line 134 of file TcpConnection.cpp.
References libcomp::TcpConnection::QueuePacket(), and libcomp::Object::SavePacket().
Referenced by libcomp::TcpConnection::SendObject().
void TcpConnection::QueuePacket (Packet & packet) virtual inherited
Queue a packet to be sent.
Note
This will not send the packet until SendPacket or FlushOutgoing is called.
Parameters
packet Packet to send to the remote host.
Definition at line 114 of file TcpConnection.cpp.
Referenced by libcomp::TcpConnection::QueueObject(), libcomp::TcpConnection::QueuePacketCopy(), and libcomp::TcpConnection::SendPacket().
void TcpConnection::QueuePacket (ReadOnlyPacket & packet) virtual inherited
Queue a packet to be sent.
Note
This will not send the packet until SendPacket or FlushOutgoing is called.
Parameters
packet Packet to send to the remote host.
Definition at line 121 of file TcpConnection.cpp.
References libcomp::TcpConnection::mOutgoingMutex, and libcomp::TcpConnection::mOutgoingPackets.
void TcpConnection::QueuePacketCopy (libcomp::Packet & packet) virtual inherited
Queue a copy of a packet to be sent.
Note
This will not send the packet until SendPacket or FlushOutgoing is called.
Parameters
packet Packet to send to the remote host.
Definition at line 128 of file TcpConnection.cpp.
References libcomp::TcpConnection::QueuePacket().
bool TcpConnection::RequestPacket (size_t size) inherited
Start a receive request for more packet data.
The PacketReceived function will be called but it may return less bytes than requested.
Parameters
size Number of bytes requested.
Returns
true on success; false otherwise.
Definition at line 180 of file TcpConnection.cpp.
References libcomp::ReadOnlyPacket::Allocate(), libcomp::String::Arg(), libcomp::Packet::Data(), libcomp::TcpConnection::mReceivedPacket, libcomp::TcpConnection::mSocket, and libcomp::ReadOnlyPacket::Size().
Referenced by libcomp::LobbyConnection::ConnectionSuccess(), ConnectionSuccess(), ParseClientEncryptionStart(), ParsePacket(), ParseServerEncryptionFinish(), ParseServerEncryptionStart(), and SendMessage().
void EncryptedConnection::SendMessage (const std::function< libcomp::Message::Message *(const std::shared_ptr< libcomp::TcpConnection > &)> & messageAllocFunction) protected
Send a message to the message queue.
This takes a function because it may decide the message can't be sent. In this case it will save time by not calling the allocation function.
Parameters
messageAllocFunction Function that will construct the message.
Definition at line 233 of file EncryptedConnection.cpp.
References mMessageQueue, libcomp::TcpConnection::RequestPacket(), and SocketError().
Referenced by ConnectionEncrypted(), and libcomp::LobbyConnection::ParseExtensionConnection().
bool TcpConnection::SendObject (const Object & obj, bool closeConnection = false) virtual inherited
Packetize and queue an object and then send all queued packets to the remote host.
Parameters
obj Object to be packetized.
closeConnection If the connection should be closed after the send queue has been emptied.
Returns
true if the object could be packetized; false otherwise.
Definition at line 168 of file TcpConnection.cpp.
References libcomp::TcpConnection::FlushOutgoing(), and libcomp::TcpConnection::QueueObject().
void TcpConnection::SendPacket (Packet & packet, bool closeConnection = false) virtual inherited
Queue a packet and then send all queued packets to the remote host.
Parameters
packet Packet to send to the remote host.
closeConnection If the connection should be closed after the send queue has been emptied.
Definition at line 148 of file TcpConnection.cpp.
Referenced by libcomp::LobbyConnection::ConnectionSuccess(), ConnectionSuccess(), ParseClientEncryptionStart(), libcomp::LobbyConnection::ParseExtensionConnection(), ParseServerEncryptionStart(), and libcomp::TcpConnection::SendPacketCopy().
void TcpConnection::SendPacket (ReadOnlyPacket & packet, bool closeConnection = false) virtual inherited
Queue a packet and then send all queued packets to the remote host.
Parameters
packet Packet to send to the remote host.
closeConnection If the connection should be closed after the send queue has been emptied.
Definition at line 155 of file TcpConnection.cpp.
References libcomp::TcpConnection::FlushOutgoing(), and libcomp::TcpConnection::QueuePacket().
void TcpConnection::SendPacketCopy (libcomp::Packet & packet, bool closeConnection = false) virtual inherited
Queue a copy of a packet and then send all queued packets to the remote host.
Parameters
packet Packet to send to the remote host.
closeConnection If the connection should be closed after the send queue has been emptied.
Definition at line 161 of file TcpConnection.cpp.
References libcomp::TcpConnection::SendPacket().
void TcpConnection::SetEncryptionKey (const std::vector< char > & data) protected inherited
Sets the Blowfish encryption key to be used.
Parameters
data Blowfish encryption key.
Definition at line 461 of file TcpConnection.cpp.
Referenced by ParseClientEncryptionStart(), and ParseServerEncryptionFinish().
void TcpConnection::SetEncryptionKey (const void * pData, size_t dataSize) protected inherited
Sets the Blowfish encryption key to be used.
Parameters
pData Pointer to the buffer were the key resides.
dataSize Size of the encryption key data.
Definition at line 466 of file TcpConnection.cpp.
References libcomp::TcpConnection::mEncryptionKey, and libcomp::Crypto::Blowfish::SetKey().
void EncryptedConnection::SetMessageQueue (const std::weak_ptr< MessageQueue< libcomp::Message::Message * >> & messageQueue)
Set the message queue for this connection.
When a packet is parsed by the connection it will be sent as a libcomp::Message::Packet to the message queue set by this function.
Parameters
messageQueue Message queue to be used by the connection.
Definition at line 791 of file EncryptedConnection.cpp.
References mMessageQueue.
void TcpConnection::SetName (const String & name) inherited
Set the debug name for the connection.
Parameters
name Debug name to set.
Definition at line 548 of file TcpConnection.cpp.
References libcomp::TcpConnection::mName.
Referenced by libcomp::LobbyConnection::ParseExtensionConnection().
void EncryptedConnection::SetServerConfig (const std::shared_ptr< objects::ServerConfig > & config)
Set the server configuration object.
Parameters
config Server configuration object to use.
Definition at line 797 of file EncryptedConnection.cpp.
References mServerConfig.
void EncryptedConnection::SocketError (const libcomp::String & errorMessage = libcomp::String()) protected virtual
Report a socket error.
This should disconnect the connection.
Parameters
errorMessage Error message to report.
Reimplemented from libcomp::TcpConnection.
Definition at line 88 of file EncryptedConnection.cpp.
References libcomp::String::Arg(), libcomp::TcpConnection::GetRemoteAddress(), libcomp::TcpConnection::GetRole(), libcomp::TcpConnection::GetStatus(), mPacketParser, libcomp::TcpConnection::ROLE_CLIENT, libcomp::TcpConnection::SocketError(), and libcomp::TcpConnection::STATUS_NOT_CONNECTED.
Referenced by libcomp::LobbyConnection::ConnectionSuccess(), ConnectionSuccess(), libcomp::ChannelConnection::DecompressPacket(), PacketReceived(), ParseClientEncryptionStart(), ParsePacket(), ParseServerEncryptionFinish(), ParseServerEncryptionStart(), libcomp::ChannelConnection::PreparePackets(), and SendMessage().
Member Data Documentation
std::ofstream* libcomp::EncryptedConnection::mCaptureFile protected
File to save a capture to.
Definition at line 343 of file EncryptedConnection.h.
Referenced by ConnectionEncrypted(), ParsePacket(), libcomp::ChannelConnection::PreparePackets(), and ~EncryptedConnection().
std::shared_ptr<Crypto::DiffieHellman> libcomp::TcpConnection::mDiffieHellman protected inherited
Diffie-Hellman key exchange data.
Definition at line 354 of file TcpConnection.h.
Referenced by ParseClientEncryptionStart(), ParseServerEncryptionFinish(), and ParseServerEncryptionStart().
Crypto::Blowfish libcomp::TcpConnection::mEncryptionKey protected inherited
Blowfish encryption key.
Definition at line 357 of file TcpConnection.h.
Referenced by ParsePacket(), libcomp::ChannelConnection::PreparePackets(), PreparePackets(), and libcomp::TcpConnection::SetEncryptionKey().
std::weak_ptr<MessageQueue<libcomp::Message::Message*> > libcomp::EncryptedConnection::mMessageQueue protected
Shared pointer for the message queue for this connection.
Definition at line 337 of file EncryptedConnection.h.
Referenced by Close(), ParsePacket(), SendMessage(), and SetMessageQueue().
ReadOnlyPacket libcomp::TcpConnection::mOutgoing protected inherited
Packet being sent to the remote host.
Definition at line 386 of file TcpConnection.h.
Referenced by libcomp::TcpConnection::FlushOutgoing(), libcomp::TcpConnection::FlushOutgoingInside(), libcomp::ChannelConnection::PreparePackets(), PreparePackets(), and libcomp::TcpConnection::PreparePackets().
std::mutex libcomp::TcpConnection::mOutgoingMutex protected inherited
Mutex to ensure the outgoing packet code is executed from one thread.
Definition at line 377 of file TcpConnection.h.
Referenced by libcomp::TcpConnection::GetCombinedPackets(), GetCombinedPackets(), and libcomp::TcpConnection::QueuePacket().
std::list<ReadOnlyPacket> libcomp::TcpConnection::mOutgoingPackets protected inherited
List of packets to be sent to the remote host.
Definition at line 380 of file TcpConnection.h.
Referenced by libcomp::TcpConnection::GetCombinedPackets(), GetCombinedPackets(), and libcomp::TcpConnection::QueuePacket().
PacketParser_t libcomp::EncryptedConnection::mPacketParser protected
Active parse being used for received packets.
Definition at line 334 of file EncryptedConnection.h.
Referenced by libcomp::LobbyConnection::ConnectionSuccess(), ConnectionSuccess(), PacketReceived(), ParseClientEncryptionStart(), ParseServerEncryptionFinish(), ParseServerEncryptionStart(), and SocketError().
bool libcomp::TcpConnection::mSendingPacket protected inherited
Indicates if an outgoing packet is being sent.
Definition at line 383 of file TcpConnection.h.
Referenced by libcomp::TcpConnection::GetCombinedPackets(), and GetCombinedPackets().
std::shared_ptr<objects::ServerConfig> libcomp::EncryptedConnection::mServerConfig protected
Server configuration.
Definition at line 340 of file EncryptedConnection.h.
Referenced by ConnectionEncrypted(), and SetServerConfig().
ConnectionStatus_t libcomp::TcpConnection::mStatus protected inherited
Status of the connection.
Definition at line 360 of file TcpConnection.h.
Referenced by libcomp::TcpConnection::Close(), libcomp::TcpConnection::Connect(), libcomp::TcpConnection::FlushOutgoingInside(), libcomp::TcpConnection::GetStatus(), libcomp::TcpConnection::HandleConnection(), ParseClientEncryptionStart(), ParseServerEncryptionFinish(), ParseServerEncryptionStart(), libcomp::ChannelConnection::PreparePackets(), and PreparePackets().
The documentation for this class was generated from the following files:
EncryptedConnection.h
EncryptedConnection.cpp