COMP_hack: libcomp::DayCare Class Reference
libcomp::DayCare Class Reference
#include <DayCare.h>
Public Member Functions
DayCare (bool printDetails=true, std::function< void()> onDetain=0)
~DayCare ()
void CloseDoors (bool kill=false)
bool DetainMonsters (const std::string &path)
bool HaveChildren ()
bool IsRunning () const
bool LoadProcessXml (const std::string &xml)
void NotifyExit (pid_t pid, int status)
std::list< std::shared_ptr
< Child > > OrderChildren (const std::list< std::shared_ptr< Child >> &children)
void PrintStatus ()
void WaitForExit ()
Private Member Functions
bool LoadProcessDoc (tinyxml2::XMLDocument &doc)
Private Attributes
std::list< std::shared_ptr
< Child > > mChildren
std::mutex mChildrenShackles
bool mPrintDetails
bool mRunning
SpawnThread * mSpawnThread
WatchThread * mWatchThread
Detailed Description
Definition at line 47 of file DayCare.h.
Constructor & Destructor Documentation
DayCare::DayCare (bool printDetails = true, std::function< void()> onDetain = 0)
Definition at line 36 of file DayCare.cpp.
DayCare::~DayCare ()
Definition at line 43 of file DayCare.cpp.
References CloseDoors(), mSpawnThread, mWatchThread, and WaitForExit().
Member Function Documentation
void DayCare::CloseDoors (bool kill = false)
Definition at line 263 of file DayCare.cpp.
References mChildren, mChildrenShackles, mRunning, mSpawnThread, and libcomp::SpawnThread::RequestExit().
Referenced by ~DayCare().
bool DayCare::DetainMonsters (const std::string & path)
Definition at line 55 of file DayCare.cpp.
References LoadProcessDoc().
bool DayCare::HaveChildren ()
Definition at line 187 of file DayCare.cpp.
References mChildren, and mChildrenShackles.
Referenced by libcomp::WatchThread::Run().
bool DayCare::IsRunning () const
Definition at line 182 of file DayCare.cpp.
References mRunning.
Referenced by libcomp::WatchThread::Run().
bool DayCare::LoadProcessDoc (tinyxml2::XMLDocument & doc) private
Definition at line 79 of file DayCare.cpp.
References mChildren, mChildrenShackles, mSpawnThread, and libcomp::SpawnThread::QueueChild().
Referenced by DetainMonsters(), and LoadProcessXml().
bool DayCare::LoadProcessXml (const std::string & xml)
Definition at line 67 of file DayCare.cpp.
References LoadProcessDoc().
void DayCare::NotifyExit (pid_t pid, int status)
Definition at line 211 of file DayCare.cpp.
References mChildren, mChildrenShackles, mPrintDetails, mRunning, mSpawnThread, and libcomp::SpawnThread::QueueChild().
Referenced by libcomp::WatchThread::Run().
std::list< std::shared_ptr< Child > > DayCare::OrderChildren (const std::list< std::shared_ptr< Child >> & children)
Definition at line 245 of file DayCare.cpp.
References mChildren, and mChildrenShackles.
Referenced by libcomp::SpawnThread::Run().
void DayCare::PrintStatus ()
Definition at line 200 of file DayCare.cpp.
References mChildren, and mChildrenShackles.
void DayCare::WaitForExit ()
Definition at line 284 of file DayCare.cpp.
References mSpawnThread, mWatchThread, libcomp::WatchThread::WaitForExit(), and libcomp::SpawnThread::WaitForExit().
Referenced by ~DayCare().
Member Data Documentation
std::list<std::shared_ptr<Child> > libcomp::DayCare::mChildren private
Definition at line 77 of file DayCare.h.
Referenced by CloseDoors(), HaveChildren(), LoadProcessDoc(), NotifyExit(), OrderChildren(), and PrintStatus().
std::mutex libcomp::DayCare::mChildrenShackles private
Definition at line 78 of file DayCare.h.
Referenced by CloseDoors(), HaveChildren(), LoadProcessDoc(), NotifyExit(), OrderChildren(), and PrintStatus().
bool libcomp::DayCare::mPrintDetails private
Definition at line 72 of file DayCare.h.
Referenced by NotifyExit().
bool libcomp::DayCare::mRunning private
Definition at line 71 of file DayCare.h.
Referenced by CloseDoors(), IsRunning(), and NotifyExit().
SpawnThread* libcomp::DayCare::mSpawnThread private
Definition at line 74 of file DayCare.h.
Referenced by CloseDoors(), LoadProcessDoc(), NotifyExit(), WaitForExit(), and ~DayCare().
WatchThread* libcomp::DayCare::mWatchThread private
Definition at line 75 of file DayCare.h.
Referenced by WaitForExit(), and ~DayCare().
The documentation for this class was generated from the following files:
DayCare.h
DayCare.cpp