COMP_hack: libcomp::DBOperationalChangeSet Class Reference
libcomp::DBOperationalChangeSet Class Reference
Operational database change set consisting of inserts, updates, deletes or explicit updates which will be processed in the order they were added in.
#include <DatabaseChangeSet.h>
Public Member Functions
DBOperationalChangeSet ()
Create a new operational database change set.
DBOperationalChangeSet (const libobjgen::UUID &uuid)
Create a new operational database change set.
virtual ~DBOperationalChangeSet ()
Clean up the database change set.
void AddOperation (const std::shared_ptr< DBOperationalChange > &op)
Add either a standard or explicit operational change to the set.
virtual void Delete (const std::shared_ptr< PersistentObject > &obj)
Add an object for deletion to the change set.
std::list< std::shared_ptr
< DBOperationalChange > > GetOperations ()
Get the list of changes contained in the change set.
const libobjgen::UUID GetTransactionUUID () const
Get the transaction UUID.
virtual void Insert (const std::shared_ptr< PersistentObject > &obj)
Add an object for insertion to the change set.
virtual void Update (const std::shared_ptr< PersistentObject > &obj)
Add an object for update to the change set.
Static Public Member Functions
static std::shared_ptr
< DatabaseChangeSet > Create (const libobjgen::UUID &uuid=NULLUUID)
Static builder for a new standard DatabaseChangeSet pointer.
Private Attributes
std::list< std::shared_ptr
< DBOperationalChange > > mOperations
List of changes contained in the change set.
Detailed Description
Operational database change set consisting of inserts, updates, deletes or explicit updates which will be processed in the order they were added in.
Here is some normal usecase example code:
// Using objects::Item instance "item", objects::Inventory instance
// "inventory", related objects::Account instance "account" as well
// as database instance "db"
// Create the changeset
auto opChangeset = std::make_shared<libcomp::DBOperationalChangeSet>();
// Create an explicit update for the account, spending 5 CP. This
// assumes account has at least 5 CP in memory before attempting this logic
auto expl = std::make_shared<libcomp::DBExplicitUpdate>(account);
expl->SubtractFrom<int64_t>("CP", 5, acccount->GetCP() - 5);
// Add the update to the operation set
opChangeset->AddOperation(expl);
// Insert the item which has already been allocated a box slot
opChangeset->Insert(item);
// Update the inventory which has already had its box slot set in memory
opChangeset->Update(inventory);
// Process the 3 changes as an all or nothing operation in the order
// they were specified.
if(!db.ProcessChangeSet(opChangeset))
{
    // Handle any failure reporting here. If it fails, the account will
    // be in the state it was already in, the item will not be inserted
    // and the inventory will have reloaded with its current database values
}
Definition at line 424 of file DatabaseChangeSet.h.
Constructor & Destructor Documentation
DBOperationalChangeSet::DBOperationalChangeSet ()
Create a new operational database change set.
Definition at line 215 of file DatabaseChangeSet.cpp.
DBOperationalChangeSet::DBOperationalChangeSet (const libobjgen::UUID & uuid)
Create a new operational database change set.
Parameters
uuid UUID of the grouped transaction changes
Definition at line 219 of file DatabaseChangeSet.cpp.
DBOperationalChangeSet::~DBOperationalChangeSet () virtual
Clean up the database change set.
Definition at line 224 of file DatabaseChangeSet.cpp.
Member Function Documentation
void DBOperationalChangeSet::AddOperation (const std::shared_ptr< DBOperationalChange > & op)
Add either a standard or explicit operational change to the set.
Parameters
op Operational change to add to the change set
Definition at line 233 of file DatabaseChangeSet.cpp.
References mOperations.
std::shared_ptr< DatabaseChangeSet > DatabaseChangeSet::Create (const libobjgen::UUID & uuid = NULLUUID) static inherited
Static builder for a new standard DatabaseChangeSet pointer.
Parameters
uuid Optional UUID associated to the transaction
Returns
Pointer to a new DatabaseChangeSet
Definition at line 50 of file DatabaseChangeSet.cpp.
Referenced by libcomp::Database::QueueDelete(), libcomp::Database::QueueInsert(), libcomp::Database::QueueUpdate(), and TEST().
void DBOperationalChangeSet::Delete (const std::shared_ptr< PersistentObject > & obj) virtual
Add an object for deletion to the change set.
Parameters
obj Pointer to the object to delete
Implements libcomp::DatabaseChangeSet.
Definition at line 256 of file DatabaseChangeSet.cpp.
References libcomp::DBOperationalChange::DBOP_DELETE, and mOperations.
std::list< std::shared_ptr< DBOperationalChange > > DBOperationalChangeSet::GetOperations ()
Get the list of changes contained in the change set.
Returns
List of changes contained in the change set
Definition at line 228 of file DatabaseChangeSet.cpp.
References mOperations.
const libobjgen::UUID DatabaseChangeSet::GetTransactionUUID () const inherited
Get the transaction UUID.
Returns
UUID associated to the transaction
Definition at line 56 of file DatabaseChangeSet.cpp.
References libcomp::DatabaseChangeSet::mTransactionUUID.
void DBOperationalChangeSet::Insert (const std::shared_ptr< PersistentObject > & obj) virtual
Add an object for insertion to the change set.
Parameters
obj Pointer to the object to insert
Implements libcomp::DatabaseChangeSet.
Definition at line 238 of file DatabaseChangeSet.cpp.
References libcomp::DBOperationalChange::DBOP_INSERT, and mOperations.
void DBOperationalChangeSet::Update (const std::shared_ptr< PersistentObject > & obj) virtual
Add an object for update to the change set.
Parameters
obj Pointer to the object to update
Implements libcomp::DatabaseChangeSet.
Definition at line 247 of file DatabaseChangeSet.cpp.
References libcomp::DBOperationalChange::DBOP_UPDATE, and mOperations.
Member Data Documentation
std::list<std::shared_ptr<DBOperationalChange> > libcomp::DBOperationalChangeSet::mOperations private
List of changes contained in the change set.
Definition at line 462 of file DatabaseChangeSet.h.
Referenced by AddOperation(), Delete(), GetOperations(), Insert(), and Update().
The documentation for this class was generated from the following files:
DatabaseChangeSet.h
DatabaseChangeSet.cpp