COMP_hack: libcomp::DataSyncManager Class Reference
libcomp::DataSyncManager Class Reference
Manager to synchronize data between two or more servers.
#include <DataSyncManager.h>
Classes
class ObjectConfig
Container class for a specific object's synchronization configuration for the server.
Public Member Functions
DataSyncManager ()
Create a new DataSyncManager.
~DataSyncManager ()
Clean up the DataSyncManager.
template<class T >
std::shared_ptr< libcomp::Object > New ()
Helper function for quick creation of a record useful for ObjectConfig's BuildHandler property.
bool RegisterConnection (const std::shared_ptr< InternalConnection > &connection, std::set< std::string > types)
Register a new server connection and its sync types.
bool RemoveConnection (const std::shared_ptr< InternalConnection > &connection)
Remove a connection from the set of synchronized servers.
virtual bool RemoveRecord (const std::shared_ptr< libcomp::Object > &record, const libcomp::String &type)
Remove a specific record on the server if this is the master server for the type.
template<class D , class T >
void SyncComplete (const libcomp::String &type, const std::list< std::pair< std::shared_ptr< libcomp::Object >, bool >> &objs, const libcomp::String &source)
Helper function for performing a post record update operation useful for ObjectConfig's SyncCompleteHandler property.
bool SyncIncoming (libcomp::ReadOnlyPacket &p, const libcomp::String &source="")
Update all data read from the supplied packet on this server and relay to other servers if this is the master server for the type.
void SyncOutgoing ()
Build and send a synchronization request packet for all updated data in the queue.
bool SyncRecordRemoval (const std::shared_ptr< libcomp::Object > &record, const libcomp::String &type)
Perform a record removal and sync to the other servers immediately.
bool SyncRecordUpdate (const std::shared_ptr< libcomp::Object > &record, const libcomp::String &type)
Perform a record update and sync to the other servers immediately.
template<class D , class T >
int8_t Update (const libcomp::String &type, const std::shared_ptr< libcomp::Object > &obj, bool isRemove, const libcomp::String &source)
Helper function for updating a record useful for ObjectConfig's UpdateHandler property.
virtual bool UpdateRecord (const std::shared_ptr< libcomp::Object > &record, const libcomp::String &type)
Update a specific record on the server if this is the master server for the type.
Protected Member Functions
void QueueOutgoing (const libcomp::String &type, const std::shared_ptr< InternalConnection > &connection, const std::set< std::shared_ptr< libcomp::Object >> &updates, const std::set< std::shared_ptr< libcomp::Object >> &removes)
Build and queue a data sync request based upon the supplied type and record sets.
void WriteOutgoingRecord (libcomp::Packet &p, bool isPersistent, const libcomp::String &type, const std::shared_ptr< libcomp::Object > &record)
Write complete outgoing record packet to send from one record.
Protected Attributes
std::mutex mLock
Server lock for shared resources.
std::unordered_map
< std::string, std::shared_ptr
< ObjectConfig > > mRegisteredTypes
Map of registered synchronized types by name.
Static Protected Attributes
static const int8_t SYNC_FAILED = -1
Internal sync manager code indicating that the update handler failed to complete successfully.
static const int8_t SYNC_HANDLED = 1
Internal sync manager code indicating that the update handler completed without error and the record should NOT be queued for sync if applicable.
static const int8_t SYNC_UPDATED = 0
Internal sync manager code indicating that the update handler completed without error and the record should be queued for sync if applicable.
Private Member Functions
void WriteOutgoingRecords (libcomp::Packet &p, bool isPersistent, const std::set< std::shared_ptr< libcomp::Object >> &records)
Write outgoing records to the supplied packet as part of a sync operation.
Private Attributes
std::unordered_map
< std::shared_ptr
< InternalConnection >
, std::set< std::string > > mConnections
Map of all configurated server connections to their synchronized object types.
std::unordered_map
< std::string, std::set
< std::shared_ptr
< libcomp::Object > > > mOutboundRemoves
Map of all record removes queued for synchronization.
std::unordered_map
< std::string, std::set
< std::shared_ptr
< libcomp::Object > > > mOutboundUpdates
Map of all record inserts and updates queued for synchronization.
Detailed Description
Manager to synchronize data between two or more servers.
Definition at line 50 of file DataSyncManager.h.
Constructor & Destructor Documentation
DataSyncManager::DataSyncManager ()
Create a new DataSyncManager.
Definition at line 61 of file DataSyncManager.cpp.
DataSyncManager::~DataSyncManager ()
Clean up the DataSyncManager.
Definition at line 65 of file DataSyncManager.cpp.
Member Function Documentation
template<class T > std::shared_ptr<libcomp::Object> libcomp::DataSyncManager::New () inline
Helper function for quick creation of a record useful for ObjectConfig's BuildHandler property.
Returns
Pointer to a new record of the specified type
Definition at line 148 of file DataSyncManager.h.
void DataSyncManager::QueueOutgoing (const libcomp::String & type, const std::shared_ptr< InternalConnection > & connection, const std::set< std::shared_ptr< libcomp::Object >> & updates, const std::set< std::shared_ptr< libcomp::Object >> & removes) protected
Build and queue a data sync request based upon the supplied type and record sets.
Parameters
type Type name of the object being synchronized
connection Pointer to the connection to queue the packet on
updates Set of all inserts and updates that have been made
removes Set of all removes that have been made
Definition at line 579 of file DataSyncManager.cpp.
References libcomp::String::C(), libcomp::Convert::ENCODING_UTF8, libcomp::PersistentObject::GetTypeHashByName(), PACKET_DATA_SYNC, WriteOutgoingRecords(), libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteString16Little().
Referenced by SyncOutgoing().
bool DataSyncManager::RegisterConnection (const std::shared_ptr< InternalConnection > & connection, std::set< std::string > types)
Register a new server connection and its sync types.
Once registered, all updates will be queued up automatically when updated in the manager.
Parameters
connection Pointer to the connection
types Set of all types that should be sent to the connection when updated
Returns
false if the connection could not be registered for any reason
Definition at line 69 of file DataSyncManager.cpp.
References mConnections, and mLock.
bool DataSyncManager::RemoveConnection (const std::shared_ptr< InternalConnection > & connection)
Remove a connection from the set of synchronized servers.
Parameters
connection Pointer to the connection
Returns
true if the connection was removed successfully
Definition at line 90 of file DataSyncManager.cpp.
References mConnections, and mLock.
bool DataSyncManager::RemoveRecord (const std::shared_ptr< libcomp::Object > & record, const libcomp::String & type) virtual
Remove a specific record on the server if this is the master server for the type.
If it is not or the change needs to be relayed, queue the update to be sent to the other servers.
Parameters
record Pointer to the record being removed
type Type name of the object being removed
Returns
true if the record was queued for outgoing sync, false if no additional sync is necessary
Definition at line 534 of file DataSyncManager.cpp.
References libcomp::String::C(), mConnections, mLock, mOutboundRemoves, mRegisteredTypes, and SYNC_HANDLED.
Referenced by SyncRecordRemoval(), and libcomp::ScriptEngine::Using().
template<class D , class T > void libcomp::DataSyncManager::SyncComplete (const libcomp::String & type, const std::list< std::pair< std::shared_ptr< libcomp::Object >, bool >> & objs, const libcomp::String & source) inline
Helper function for performing a post record update operation useful for ObjectConfig's SyncCompleteHandler property.
Parameters
type Type name of the object being removed
objs List of pointers to the records being updated and a flag indicating if the object was being removed
source Identifier for the server sending the updates
Definition at line 184 of file DataSyncManager.h.
bool DataSyncManager::SyncIncoming (libcomp::ReadOnlyPacket & p, const libcomp::String & source = "")
Update all data read from the supplied packet on this server and relay to other servers if this is the master server for the type.
Parameters
p Packet to read incoming record updates from
source Identifier for the server sending the updates
Returns
true if the packet was read without issue
Definition at line 163 of file DataSyncManager.cpp.
References libcomp::String::Arg(), libcomp::Convert::ENCODING_UTF8, libcomp::PersistentObject::GetObjectByUUID(), libcomp::PersistentObject::GetTypeHashByName(), libcomp::String::IsEmpty(), libcomp::ReadOnlyPacket::Left(), libcomp::PersistentObject::LoadObjectByUUID(), mLock, mOutboundRemoves, mOutboundUpdates, mRegisteredTypes, libcomp::ReadOnlyPacket::ReadString16Little(), libcomp::ReadOnlyPacket::ReadU16Little(), SYNC_FAILED, and SYNC_UPDATED.
void DataSyncManager::SyncOutgoing ()
Build and send a synchronization request packet for all updated data in the queue.
One packet will be sent for each type assigned to each server connection.
Definition at line 106 of file DataSyncManager.cpp.
References libcomp::String::Arg(), mConnections, mLock, mOutboundRemoves, mOutboundUpdates, and QueueOutgoing().
Referenced by SyncRecordRemoval(), SyncRecordUpdate(), and libcomp::ScriptEngine::Using().
bool DataSyncManager::SyncRecordRemoval (const std::shared_ptr< libcomp::Object > & record, const libcomp::String & type)
Perform a record removal and sync to the other servers immediately.
Parameters
record Pointer to the record being removed
type Type name of the object being removed
Returns
true if the record was synced, false if no additional sync is necessary
Definition at line 567 of file DataSyncManager.cpp.
References RemoveRecord(), and SyncOutgoing().
bool DataSyncManager::SyncRecordUpdate (const std::shared_ptr< libcomp::Object > & record, const libcomp::String & type)
Perform a record update and sync to the other servers immediately.
Parameters
record Pointer to the record being updated
type Type name of the object being updated
Returns
true if the record was synced, false if no additional sync is necessary
Definition at line 522 of file DataSyncManager.cpp.
References SyncOutgoing(), and UpdateRecord().
template<class D , class T > int8_t libcomp::DataSyncManager::Update (const libcomp::String & type, const std::shared_ptr< libcomp::Object > & obj, bool isRemove, const libcomp::String & source) inline
Helper function for updating a record useful for ObjectConfig's UpdateHandler property.
Parameters
type Type name of the object being removed
obj Pointer to the record being updated
isRemove true if the change is a remove, false if it is an insert or an update
source Identifier for the server sending the updates
Returns
true if the update was performed without issue
Definition at line 163 of file DataSyncManager.h.
References SYNC_FAILED.
bool DataSyncManager::UpdateRecord (const std::shared_ptr< libcomp::Object > & record, const libcomp::String & type) virtual
Update a specific record on the server if this is the master server for the type.
If it is not or the change needs to be relayed, queue the update to be sent to the other servers.
Parameters
record Pointer to the record being updated
type Type name of the object being updated
Returns
true if the record was queued for outgoing sync, false if no additional sync is necessary
Definition at line 489 of file DataSyncManager.cpp.
References libcomp::String::C(), mConnections, mLock, mOutboundUpdates, mRegisteredTypes, and SYNC_HANDLED.
Referenced by SyncRecordUpdate(), and libcomp::ScriptEngine::Using().
void DataSyncManager::WriteOutgoingRecord (libcomp::Packet & p, bool isPersistent, const libcomp::String & type, const std::shared_ptr< libcomp::Object > & record) protected
Write complete outgoing record packet to send from one record.
Parameters
p Packet to write the changes to
isPersistent true if the object's UUID should be written to the packet, false if the entire object definition should be written instead
type Type name of the object being synchronized
record Record to write to the packet
Definition at line 601 of file DataSyncManager.cpp.
References libcomp::Convert::ENCODING_UTF8, PACKET_DATA_SYNC, libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteString16Little(), and libcomp::Packet::WriteU16Little().
void DataSyncManager::WriteOutgoingRecords (libcomp::Packet & p, bool isPersistent, const std::set< std::shared_ptr< libcomp::Object >> & records) private
Write outgoing records to the supplied packet as part of a sync operation.
Parameters
p Packet to write the changes to
isPersistent true if the object's UUID should be written to the packet, false if the entire object definition should be written instead
records Set of records to write to the packet
Definition at line 626 of file DataSyncManager.cpp.
References libcomp::Convert::ENCODING_UTF8, libcomp::Packet::WriteString16Little(), and libcomp::Packet::WriteU16Little().
Referenced by QueueOutgoing().
Member Data Documentation
std::unordered_map<std::shared_ptr<InternalConnection>, std::set<std::string> > libcomp::DataSyncManager::mConnections private
Map of all configurated server connections to their synchronized object types.
Definition at line 340 of file DataSyncManager.h.
Referenced by RegisterConnection(), RemoveConnection(), RemoveRecord(), SyncOutgoing(), and UpdateRecord().
std::mutex libcomp::DataSyncManager::mLock protected
Server lock for shared resources.
Definition at line 314 of file DataSyncManager.h.
Referenced by RegisterConnection(), RemoveConnection(), RemoveRecord(), SyncIncoming(), SyncOutgoing(), and UpdateRecord().
std::unordered_map<std::string, std::set<std::shared_ptr<libcomp::Object> > > libcomp::DataSyncManager::mOutboundRemoves private
Map of all record removes queued for synchronization.
Definition at line 335 of file DataSyncManager.h.
Referenced by RemoveRecord(), SyncIncoming(), and SyncOutgoing().
std::unordered_map<std::string, std::set<std::shared_ptr<libcomp::Object> > > libcomp::DataSyncManager::mOutboundUpdates private
Map of all record inserts and updates queued for synchronization.
Definition at line 331 of file DataSyncManager.h.
Referenced by SyncIncoming(), SyncOutgoing(), and UpdateRecord().
std::unordered_map<std::string, std::shared_ptr<ObjectConfig> > libcomp::DataSyncManager::mRegisteredTypes protected
Map of registered synchronized types by name.
Definition at line 311 of file DataSyncManager.h.
Referenced by RemoveRecord(), SyncIncoming(), and UpdateRecord().
const int8_t libcomp::DataSyncManager::SYNC_FAILED = -1 static protected
Internal sync manager code indicating that the update handler failed to complete successfully.
Definition at line 207 of file DataSyncManager.h.
Referenced by SyncIncoming(), and Update().
const int8_t libcomp::DataSyncManager::SYNC_HANDLED = 1 static protected
Internal sync manager code indicating that the update handler completed without error and the record should NOT be queued for sync if applicable.
Definition at line 203 of file DataSyncManager.h.
Referenced by RemoveRecord(), and UpdateRecord().
const int8_t libcomp::DataSyncManager::SYNC_UPDATED = 0 static protected
Internal sync manager code indicating that the update handler completed without error and the record should be queued for sync if applicable.
Definition at line 198 of file DataSyncManager.h.
Referenced by SyncIncoming().
The documentation for this class was generated from the following files:
DataSyncManager.h
DataSyncManager.cpp