COMP_hack: libcomp::DataStore Class Reference
libcomp::DataStore Class Reference
#include <DataStore.h>
Public Types
enum FileMode_t { FileMode_t::READ, FileMode_t::WRITE, FileMode_t::APPEND }
Public Member Functions
DataStore (const char *szProgram)
~DataStore ()
bool AddSearchPath (const libcomp::String &path, bool append=false)
bool AddSearchPaths (const std::list< libcomp::String > &paths)
bool CreateDirectory (const libcomp::String &path)
std::vector< char > DecryptFile (const libcomp::String &path)
bool Delete (const libcomp::String &path, bool recursive=false)
bool EncryptFile (const libcomp::String &path, const std::vector< char > &data)
bool Exists (const libcomp::String &path)
int64_t FileSize (const libcomp::String &path)
libcomp::String GetError ()
libcomp::String GetHash (const libcomp::String &path)
bool GetListing (const libcomp::String &path, std::list< libcomp::String > &files, std::list< libcomp::String > &dirs, std::list< libcomp::String > &symLinks, bool recursive=false, bool fullPath=false)
DataFile * Open (const libcomp::String &path, FileMode_t mode=FileMode_t::READ)
bool PrintListing (const libcomp::String &path, bool recursive=false, bool fullPath=false)
std::vector< char > ReadFile (const libcomp::String &path)
bool WriteFile (const libcomp::String &path, const std::vector< char > &data)
Detailed Description
Definition at line 41 of file DataStore.h.
Member Enumeration Documentation
enum libcomp::DataStore::FileMode_t strong
Enumerator
READ
WRITE
APPEND
Definition at line 57 of file DataStore.h.
Constructor & Destructor Documentation
DataStore::DataStore (const char * szProgram)
Definition at line 45 of file DataStore.cpp.
DataStore::~DataStore ()
Definition at line 57 of file DataStore.cpp.
Member Function Documentation
bool DataStore::AddSearchPath (const libcomp::String & path, bool append = false)
Definition at line 245 of file DataStore.cpp.
References libcomp::String::Arg(), libcomp::String::C(), and GetError().
Referenced by AddSearchPaths(), and libcomp::BaseServer::Initialize().
bool DataStore::AddSearchPaths (const std::list< libcomp::String > & paths)
Definition at line 71 of file DataStore.cpp.
References AddSearchPath(), libcomp::String::Arg(), and libcomp::String::C().
Referenced by libcomp::BaseServer::Initialize().
bool DataStore::CreateDirectory (const libcomp::String & path)
Definition at line 342 of file DataStore.cpp.
References libcomp::String::C().
std::vector< char > DataStore::DecryptFile (const libcomp::String & path)
Definition at line 392 of file DataStore.cpp.
References libcomp::Crypto::DecryptFile(), and ReadFile().
Referenced by libcomp::DefinitionManager::LoadBinaryData().
bool DataStore::Delete (const libcomp::String & path, bool recursive = false)
Definition at line 301 of file DataStore.cpp.
References libcomp::String::C(), and GetListing().
bool DataStore::EncryptFile (const libcomp::String & path, const std::vector< char > & data)
Definition at line 404 of file DataStore.cpp.
References libcomp::Crypto::EncryptFile(), and WriteFile().
bool DataStore::Exists (const libcomp::String & path)
Definition at line 279 of file DataStore.cpp.
References libcomp::String::C().
Referenced by libcomp::ScriptEngine::Using().
int64_t DataStore::FileSize (const libcomp::String & path)
Definition at line 284 of file DataStore.cpp.
References Open().
libcomp::String DataStore::GetError ()
Definition at line 66 of file DataStore.cpp.
Referenced by AddSearchPath(), and libcomp::ScriptEngine::Using().
libcomp::String DataStore::GetHash (const libcomp::String & path)
Definition at line 417 of file DataStore.cpp.
References ReadFile(), and libcomp::Crypto::SHA1().
bool DataStore::GetListing (const libcomp::String & path, std::list< libcomp::String > & files, std::list< libcomp::String > & dirs, std::list< libcomp::String > & symLinks, bool recursive = false, bool fullPath = false)
Definition at line 106 of file DataStore.cpp.
References libcomp::String::Arg(), libcomp::String::C(), and libcomp::String::Right().
Referenced by Delete(), libcomp::BaseServer::Initialize(), PrintListing(), libcomp::DatabaseSQLite3::Setup(), and libcomp::DatabaseMariaDB::Setup().
DataFile * DataStore::Open (const libcomp::String & path, FileMode_t mode = FileMode_t::READ)
Definition at line 265 of file DataStore.cpp.
Referenced by FileSize(), ReadFile(), and WriteFile().
bool DataStore::PrintListing (const libcomp::String & path, bool recursive = false, bool fullPath = false)
Definition at line 201 of file DataStore.cpp.
References libcomp::String::Arg(), and GetListing().
std::vector< char > DataStore::ReadFile (const libcomp::String & path)
Definition at line 347 of file DataStore.cpp.
References Open().
Referenced by libcomp::Database::ApplyMigration(), DecryptFile(), GetHash(), libcomp::DefinitionManager::LoadBinaryData(), and libcomp::DefinitionManager::LoadQmpFile().
bool DataStore::WriteFile (const libcomp::String & path, const std::vector< char > & data)
Definition at line 374 of file DataStore.cpp.
References Open(), and WRITE.
Referenced by EncryptFile().
The documentation for this class was generated from the following files:
DataStore.h
DataStore.cpp