COMP_hack: libcomp::Object Class Reference
libcomp::Object Class Reference abstract
Abstract base class that represents any object that can be defined via a MetaObject definition and corresonding value assignment that can be read via XML.
#include <Object.h>
Public Member Functions
Object ()
Create an object.
Object (const Object &other)
Explicitly defined copy constructor necessary due to removal of implicit constructor from non-copyable mutex member.
virtual ~Object ()
Clean up the object.
virtual uint16_t GetDynamicSizeCount () const =0
Get the dynamic size count of the MetaObject definition.
std::string GetXml () const
Save the object into XML and return it as a string.
virtual bool IsValid (bool recursive=true) const =0
Check if the object is currently in a valid state.
virtual bool Load (ObjectInStream &stream)=0
Load the object's data members from an ObjectInStream.
virtual bool Load (std::istream &stream, bool flat=false)=0
Load the object's data members from a standard input stream.
virtual bool Load (const tinyxml2::XMLDocument &doc, const tinyxml2::XMLElement &root)=0
Load the object's data members from an XML file.
virtual bool LoadPacket (libcomp::ReadOnlyPacket &p, bool flat=true)
Load the object's data members from a data packet.
virtual bool Save (ObjectOutStream &stream) const =0
Save the object's data members to an ObjectOutStream.
virtual bool Save (std::ostream &stream, bool flat=false) const =0
Save the object's data members to a standard output stream.
virtual bool Save (tinyxml2::XMLDocument &doc, tinyxml2::XMLElement &root, bool append=false) const =0
Save the object's data members to an XML file.
virtual bool SavePacket (libcomp::Packet &p, bool flat=true) const
Save the object's data members to a data packet.
Static Public Member Functions
static std::list
< std::shared_ptr< Object > > LoadBinaryData (std::istream &stream, const std::function< std::shared_ptr< Object >()> &objectAllocator)
Static utility function to build multiple objects from an input stream and a factory function.
static bool SaveBinaryData (std::ostream &stream, const std::list< std::shared_ptr< Object >> &objs)
Static utliity function to save multiple objects to an output stream.
Protected Member Functions
const tinyxml2::XMLElement * GetXmlChild (const tinyxml2::XMLElement &root, const std::string name) const
Utility function to get a child XML element from a parent node matching a specified name.
const std::list< const
tinyxml2::XMLElement * > GetXmlChildren (const tinyxml2::XMLElement &root, const std::string name) const
Utility function to get child XML elements from a parent node matching a specified name.
virtual std::unordered_map
< std::string, const
tinyxml2::XMLElement * > GetXmlMembers (const tinyxml2::XMLElement &root) const
Utility function to get child XML elements from a parent node.
virtual std::string GetXmlText (const tinyxml2::XMLElement &root) const
Utility function to get element text from an XML node.
bool SkipPadding (std::istream &stream, uint8_t count)
Utility function to skip padding bytes when reading from a datastream.
bool WritePadding (std::ostream &stream, uint8_t count) const
Utility function to write padding bytes when writing to a datastream.
Protected Attributes
std::mutex mFieldLock
Mutex to lock accessing the object fields.
Detailed Description
Abstract base class that represents any object that can be defined via a MetaObject definition and corresonding value assignment that can be read via XML.
Data can be save and loaded via byte streams and also added to and retrieved from packets.
See Also
DynamicObject
PersistentObject
Definition at line 97 of file Object.h.
Constructor & Destructor Documentation
Object::Object ()
Create an object.
Definition at line 40 of file Object.cpp.
Object::Object (const Object & other)
Explicitly defined copy constructor necessary due to removal of implicit constructor from non-copyable mutex member.
Parameters
other The other object to copy
Definition at line 44 of file Object.cpp.
Object::~Object () virtual
Clean up the object.
Definition at line 49 of file Object.cpp.
Member Function Documentation
virtual uint16_t libcomp::Object::GetDynamicSizeCount () const pure virtual
Get the dynamic size count of the MetaObject definition.
An object's dynamic size count can be thought of as the minimum size required to save an object of a given type.
Returns
MetaObject definition's dynamic size count
Implemented in libcomp::DynamicObject.
std::string Object::GetXml () const
Save the object into XML and return it as a string.
Returns
An XML string for the object.
Definition at line 301 of file Object.cpp.
References Save().
const tinyxml2::XMLElement * Object::GetXmlChild (const tinyxml2::XMLElement & root, const std::string name) const protected
Utility function to get a child XML element from a parent node matching a specified name.
Parameters
root Parent XML node
name Child element name to retrieve
Returns
First matching XML node child or nullptr if not found
See Also
Object::GetXmlChildren
Definition at line 78 of file Object.cpp.
References GetXmlChildren().
const std::list< const tinyxml2::XMLElement * > Object::GetXmlChildren (const tinyxml2::XMLElement & root, const std::string name) const protected
Utility function to get child XML elements from a parent node matching a specified name.
Parameters
root Parent XML node
name Child element name to retrieve
Returns
List of matching XML node children or empty if not found
See Also
Object::GetXmlChild
Definition at line 85 of file Object.cpp.
Referenced by GetXmlChild().
std::unordered_map< std::string, const tinyxml2::XMLElement * > Object::GetXmlMembers (const tinyxml2::XMLElement & root) const protected virtual
Utility function to get child XML elements from a parent node.
Parameters
root Parent XML node
Returns
Map of child members by element name
Definition at line 103 of file Object.cpp.
std::string Object::GetXmlText (const tinyxml2::XMLElement & root) const protected virtual
Utility function to get element text from an XML node.
Parameters
root Parent XML node
Returns
Text contained in the node's element text
Definition at line 124 of file Object.cpp.
virtual bool libcomp::Object::IsValid (bool recursive = true) const pure virtual
Check if the object is currently in a valid state.
Parameters
recursive If references to other objects exist and recursive = true, IsValid will be run on those references as well
Returns
true if valid, false if invalid
Implemented in libcomp::DynamicObject.
Referenced by libcomp::ScriptEngine::Using().
virtual bool libcomp::Object::Load (ObjectInStream & stream) pure virtual
Load the object's data members from an ObjectInStream.
Parameters
stream Byte stream containing data member values
Returns
true if loading was successful, false if it was not
Referenced by LoadPacket().
virtual bool libcomp::Object::Load (std::istream & stream, bool flat = false) pure virtual
Load the object's data members from a standard input stream.
Parameters
stream Byte stream containing data member values
flat If references to non-persistent objects exist and flat = false those references' data members are specified in the stream as well
Returns
true if loading was successful, false if it was not
virtual bool libcomp::Object::Load (const tinyxml2::XMLDocument & doc, const tinyxml2::XMLElement & root) pure virtual
Load the object's data members from an XML file.
Parameters
doc XML document containing the definition
root Root XML node of the definition
Returns
true if loading was successful, false if it was not
std::list< std::shared_ptr< Object > > Object::LoadBinaryData (std::istream & stream, const std::function< std::shared_ptr< Object >()> & objectAllocator) static
Static utility function to build multiple objects from an input stream and a factory function.
Parameters
stream Byte stream containing the object data
objectAllocator Factory function to build the objects
Returns
List of resulting objects built from the stream
Definition at line 148 of file Object.cpp.
References libcomp::ObjectInStream::dynamicSizes.
Referenced by libcomp::BinaryDataSet::Load().
bool Object::LoadPacket (libcomp::ReadOnlyPacket & p, bool flat = true) virtual
Load the object's data members from a data packet.
Parameters
p Packet containing data member values
flat Specifies if the call to Load should be flat
Returns
true if loading was successful, false if it was not
Definition at line 53 of file Object.cpp.
References Load(), and libcomp::ReadOnlyPacket::Skip().
virtual bool libcomp::Object::Save (ObjectOutStream & stream) const pure virtual
Save the object's data members to an ObjectOutStream.
Parameters
stream Byte stream to save data member values to
Returns
true if saving was successful, false if it was not
Referenced by GetXml(), SavePacket(), and libcomp::PersistentObject::SaveWithUUID().
virtual bool libcomp::Object::Save (std::ostream & stream, bool flat = false) const pure virtual
Save the object's data members to a standard output stream.
Parameters
stream Byte stream to save data member values to
flat If references to non-persistent objects exist and flat = false those references' data members will be saved in the stream as well
Returns
true if saving was successful, false if it was not
virtual bool libcomp::Object::Save (tinyxml2::XMLDocument & doc, tinyxml2::XMLElement & root, bool append = false) const pure virtual
Save the object's data members to an XML file.
Parameters
doc XML document to save the definition to
root Root XML node to save the definition to
append true if the root node should be appended to, false if an object node should be added to the root then appended to
Returns
true if saving was successful, false if it was not
bool Object::SaveBinaryData (std::ostream & stream, const std::list< std::shared_ptr< Object >> & objs) static
Static utliity function to save multiple objects to an output stream.
Parameters
stream Byte stream to save the object data to.
objs List of objects to save to the stream.
Returns
true if saving was successful, false if it was not
Definition at line 208 of file Object.cpp.
References libcomp::ObjectOutStream::dynamicSizes.
Referenced by libcomp::BinaryDataSet::Save().
bool Object::SavePacket (libcomp::Packet & p, bool flat = true) const virtual
Save the object's data members to a data packet.
Parameters
p Packet to save data member values to
flat Specifies if the call to Save should be flat
Returns
true if saving was successful, false if it was not
Definition at line 69 of file Object.cpp.
References Save().
Referenced by libcomp::TcpConnection::QueueObject().
bool Object::SkipPadding (std::istream & stream, uint8_t count) protected
Utility function to skip padding bytes when reading from a datastream.
Parameters
stream Byte stream being read from
count Number of bytes to skip
Returns
true if the stream is still good after skipping
Definition at line 319 of file Object.cpp.
bool Object::WritePadding (std::ostream & stream, uint8_t count) const protected
Utility function to write padding bytes when writing to a datastream.
Parameters
stream Byte stream being written to
count Number of bytes to write
Returns
true if the stream is still good after writing
Definition at line 327 of file Object.cpp.
Member Data Documentation
std::mutex libcomp::Object::mFieldLock protected
Mutex to lock accessing the object fields.
Definition at line 284 of file Object.h.
The documentation for this class was generated from the following files:
Object.h
Object.cpp