COMP_hack: libcomp::DatabaseQuerySQLite3 Class Reference
libcomp::DatabaseQuerySQLite3 Class Reference
SQLite3 database specific implementation of a query with binding and data retrieval functionality.
#include <DatabaseQuerySQLite3.h>
Public Member Functions
DatabaseQuerySQLite3 (sqlite3 *pDatabase, uint8_t maxRetryCount=3, uint16_t retryDelay=500)
Create a new SQLite3 database query.
virtual ~DatabaseQuerySQLite3 ()
Clean up the query.
int64_t AffectedRowCount () const
Get the count of affected rows from the last query execution.
virtual bool Bind (size_t index, const String &value)
Bind a string column value by its index.
virtual bool Bind (const String &name, const String &value)
Bind a string column value by its name.
virtual bool Bind (size_t index, const std::vector< char > &value)
Bind a blob column value by its index.
virtual bool Bind (const String &name, const std::vector< char > &value)
Bind a blob column value by its name.
virtual bool Bind (size_t index, const libobjgen::UUID &value)
Bind a UUID column value by its index.
virtual bool Bind (const String &name, const libobjgen::UUID &value)
Bind a UUID column value by its name.
virtual bool Bind (size_t index, int32_t value)
Bind a 32-bit integer column value by its index.
virtual bool Bind (const String &name, int32_t value)
Bind a 32-bit integer column value by its name.
virtual bool Bind (size_t index, int64_t value)
Bind a 64-bit integer column value by its index.
virtual bool Bind (const String &name, int64_t value)
Bind a 64-bit integer column value by its name.
virtual bool Bind (size_t index, float value)
Bind a float column value by its index.
virtual bool Bind (const String &name, float value)
Bind a float column value by its name.
virtual bool Bind (size_t index, double value)
Bind a double column value by its index.
virtual bool Bind (const String &name, double value)
Bind a double column value by its name.
virtual bool Bind (size_t index, bool value)
Bind a boolean column value by its index.
virtual bool Bind (const String &name, bool value)
Bind a boolean column value by its name.
virtual bool Bind (size_t index, const std::unordered_map< std::string, std::vector< char >> &values)
Bind a map column value by its index.
virtual bool Bind (const String &name, const std::unordered_map< std::string, std::vector< char >> &values)
Bind a map column value by its name.
virtual bool Execute ()
Execute a previously prepared query.
virtual bool GetRows (std::list< std::unordered_map< std::string, std::vector< char >>> &rows)
Get all of the query result's rows as bytes mapped by column name.
int GetStatus () const
Get the current status of the query as a SQLite3 defined integer status code.
virtual bool GetValue (size_t index, String &value)
Get a string column value by its index.
virtual bool GetValue (const String &name, String &value)
Get a string column value by its name.
virtual bool GetValue (size_t index, std::vector< char > &value)
Get a blob column value by its index.
virtual bool GetValue (const String &name, std::vector< char > &value)
Get a blob column value by its name.
virtual bool GetValue (size_t index, libobjgen::UUID &value)
Get a UUID column value by its index.
virtual bool GetValue (const String &name, libobjgen::UUID &value)
Get a UUID column value by its name.
virtual bool GetValue (size_t index, int32_t &value)
Get a 32-bit integer column value by its index.
virtual bool GetValue (const String &name, int32_t &value)
Get a 32-bit integer column value by its name.
virtual bool GetValue (size_t index, int64_t &value)
Get a 64-bit integer column value by its index.
virtual bool GetValue (const String &name, int64_t &value)
Get a boolean column value by its name.
virtual bool GetValue (size_t index, float &value)
Get a float column value by its index.
virtual bool GetValue (const String &name, float &value)
Get a float column value by its name.
virtual bool GetValue (size_t index, double &value)
Get a double column value by its index.
virtual bool GetValue (const String &name, double &value)
Get a double column value by its name.
virtual bool GetValue (size_t index, bool &value)
Get a boolean column value by its index.
virtual bool GetValue (const String &name, bool &value)
Get a boolean column value by its name.
virtual bool IsValid () const
Check current query state validity.
virtual bool Next ()
Increment the query results to look at the next result set row.
virtual bool Prepare (const String &query)
Prepare a database query for execution based upon query text.
Protected Attributes
int64_t mAffectedRowCount
Represents the number of affected rows since the last sucessful call to Execute.
Private Member Functions
std::string GetNamedBinding (const String &name) const
Helper function to format a named binding in the :NAME format.
size_t GetNamedBindingIndex (const String &name) const
Get the index of a named binding.
bool GetResultColumnIndex (const String &name, size_t &index) const
Get the index of the current result set's column by name.
Private Attributes
sqlite3 * mDatabase
Pointer to the SQLite3 database the query executes on.
bool mDidJustExecute
Indicator that Next() should be skipped the first time following execution to offset the need to call step (aka: Next()) to execute the query itself.
uint8_t mMaxRetryCount
Maximum number of retries allowed when executing the query.
std::vector< std::string > mResultColumnNames
Column names from the current result set.
std::vector< int > mResultColumnTypes
Column data types from the current result set represented as SQLite3 data type integers.
uint16_t mRetryDelay
Time in milliseconds to wait between execution attempts.
sqlite3_stmt * mStatement
Pointer to the SQLite3 representation of the query as a statement.
int mStatus
Current status of the query as a SQLite3 defined integer status code.
Detailed Description
SQLite3 database specific implementation of a query with binding and data retrieval functionality.
Definition at line 47 of file DatabaseQuerySQLite3.h.
Constructor & Destructor Documentation
DatabaseQuerySQLite3::DatabaseQuerySQLite3 (sqlite3 * pDatabase, uint8_t maxRetryCount = 3, uint16_t retryDelay = 500)
Create a new SQLite3 database query.
Parameters
pDatabase Pointer to the executing SQLite3 database
maxRetryCount Maximum number of retry attempts allowed when access to the DB during query execution returns as busy
retryDelay Delay in milliseconds between execution retry attempts
Definition at line 41 of file DatabaseQuerySQLite3.cpp.
DatabaseQuerySQLite3::~DatabaseQuerySQLite3 () virtual
Clean up the query.
Definition at line 49 of file DatabaseQuerySQLite3.cpp.
References mStatement.
Member Function Documentation
int64_t DatabaseQueryImpl::AffectedRowCount () const inherited
Get the count of affected rows from the last query execution.
Returns
Number of affected rows
Definition at line 67 of file DatabaseQuery.cpp.
References libcomp::DatabaseQueryImpl::mAffectedRowCount.
Referenced by libcomp::DatabaseQuery::AffectedRowCount().
bool DatabaseQuerySQLite3::Bind (size_t index, const String & value) virtual
Bind a string column value by its index.
Parameters
index The column's index
value The value to bind
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 118 of file DatabaseQuerySQLite3.cpp.
References libcomp::String::C(), IsValid(), mStatement, mStatus, and libcomp::String::Size().
Referenced by Bind().
bool DatabaseQuerySQLite3::Bind (const String & name, const String & value) virtual
Bind a string column value by its name.
Parameters
name The column's name
value The value to bind
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 127 of file DatabaseQuerySQLite3.cpp.
References Bind(), GetNamedBindingIndex(), IsValid(), and mStatus.
bool DatabaseQuerySQLite3::Bind (size_t index, const std::vector< char > & value) virtual
Bind a blob column value by its index.
Parameters
index The column's index
value The value to bind
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 139 of file DatabaseQuerySQLite3.cpp.
References IsValid(), mStatement, and mStatus.
bool DatabaseQuerySQLite3::Bind (const String & name, const std::vector< char > & value) virtual
Bind a blob column value by its name.
Parameters
name The column's name
value The value to bind
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 155 of file DatabaseQuerySQLite3.cpp.
References Bind(), GetNamedBindingIndex(), IsValid(), and mStatus.
bool DatabaseQuerySQLite3::Bind (size_t index, const libobjgen::UUID & value) virtual
Bind a UUID column value by its index.
Parameters
index The column's index
value The value to bind
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 168 of file DatabaseQuerySQLite3.cpp.
References Bind().
bool DatabaseQuerySQLite3::Bind (const String & name, const libobjgen::UUID & value) virtual
Bind a UUID column value by its name.
Parameters
name The column's name
value The value to bind
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 174 of file DatabaseQuerySQLite3.cpp.
References Bind().
bool DatabaseQuerySQLite3::Bind (size_t index, int32_t value) virtual
Bind a 32-bit integer column value by its index.
Parameters
index The column's index
value The value to bind
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 181 of file DatabaseQuerySQLite3.cpp.
References IsValid(), mStatement, and mStatus.
bool DatabaseQuerySQLite3::Bind (const String & name, int32_t value) virtual
Bind a 32-bit integer column value by its name.
Parameters
name The column's name
value The value to bind
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 188 of file DatabaseQuerySQLite3.cpp.
References Bind(), GetNamedBindingIndex(), IsValid(), and mStatus.
bool DatabaseQuerySQLite3::Bind (size_t index, int64_t value) virtual
Bind a 64-bit integer column value by its index.
Parameters
index The column's index
value The value to bind
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 200 of file DatabaseQuerySQLite3.cpp.
References IsValid(), mStatement, and mStatus.
bool DatabaseQuerySQLite3::Bind (const String & name, int64_t value) virtual
Bind a 64-bit integer column value by its name.
Parameters
name The column's name
value The value to bind
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 207 of file DatabaseQuerySQLite3.cpp.
References Bind(), GetNamedBindingIndex(), IsValid(), and mStatus.
bool DatabaseQuerySQLite3::Bind (size_t index, float value) virtual
Bind a float column value by its index.
Parameters
index The column's index
value The value to bind
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 219 of file DatabaseQuerySQLite3.cpp.
References IsValid(), mStatement, and mStatus.
bool DatabaseQuerySQLite3::Bind (const String & name, float value) virtual
Bind a float column value by its name.
Parameters
name The column's name
value The value to bind
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 227 of file DatabaseQuerySQLite3.cpp.
References Bind(), GetNamedBindingIndex(), IsValid(), and mStatus.
bool DatabaseQuerySQLite3::Bind (size_t index, double value) virtual
Bind a double column value by its index.
Parameters
index The column's index
value The value to bind
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 239 of file DatabaseQuerySQLite3.cpp.
References IsValid(), mStatement, and mStatus.
bool DatabaseQuerySQLite3::Bind (const String & name, double value) virtual
Bind a double column value by its name.
Parameters
name The column's name
value The value to bind
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 246 of file DatabaseQuerySQLite3.cpp.
References Bind(), GetNamedBindingIndex(), IsValid(), and mStatus.
bool DatabaseQuerySQLite3::Bind (size_t index, bool value) virtual
Bind a boolean column value by its index.
Parameters
index The column's index
value The value to bind
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 258 of file DatabaseQuerySQLite3.cpp.
References IsValid(), mStatement, and mStatus.
bool DatabaseQuerySQLite3::Bind (const String & name, bool value) virtual
Bind a boolean column value by its name.
Parameters
name The column's name
value The value to bind
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 266 of file DatabaseQuerySQLite3.cpp.
References Bind(), GetNamedBindingIndex(), IsValid(), and mStatus.
bool DatabaseQuerySQLite3::Bind (size_t index, const std::unordered_map< std::string, std::vector< char >> & values) virtual
Bind a map column value by its index.
Parameters
index The column's index
values The value to bind
Returns
true on success, false on failure
Todo:
Reimplemented from libcomp::DatabaseQueryImpl.
Definition at line 278 of file DatabaseQuerySQLite3.cpp.
bool DatabaseQuerySQLite3::Bind (const String & name, const std::unordered_map< std::string, std::vector< char >> & values) virtual
Bind a map column value by its name.
Parameters
name The column's name
values The value to bind
Returns
true on success, false on failure
Todo:
Reimplemented from libcomp::DatabaseQueryImpl.
Definition at line 288 of file DatabaseQuerySQLite3.cpp.
bool DatabaseQuerySQLite3::Execute () virtual
Execute a previously prepared query.
See Also
DatabaseQueryImpl::Prepare
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 66 of file DatabaseQuerySQLite3.cpp.
References IsValid(), libcomp::DatabaseQueryImpl::mAffectedRowCount, mDatabase, mDidJustExecute, mMaxRetryCount, mResultColumnNames, mResultColumnTypes, mRetryDelay, mStatement, and mStatus.
std::string DatabaseQuerySQLite3::GetNamedBinding (const String & name) const private
Helper function to format a named binding in the :NAME format.
Parameters
name Name of the binding
Returns
Formatted binding
Definition at line 609 of file DatabaseQuerySQLite3.cpp.
References libcomp::String::Arg(), and libcomp::String::ToUtf8().
Referenced by GetNamedBindingIndex().
size_t DatabaseQuerySQLite3::GetNamedBindingIndex (const String & name) const private
Get the index of a named binding.
Parameters
name Name of the binding
Returns
Index of the binding
Definition at line 603 of file DatabaseQuerySQLite3.cpp.
References GetNamedBinding(), and mStatement.
Referenced by Bind(), and GetValue().
bool DatabaseQuerySQLite3::GetResultColumnIndex (const String & name, size_t & index) const private
Get the index of the current result set's column by name.
Parameters
name Name of the column
index Variable to store the index in
Returns
true on success, false on failure
Definition at line 614 of file DatabaseQuerySQLite3.cpp.
References mResultColumnNames.
Referenced by GetValue().
bool DatabaseQuerySQLite3::GetRows (std::list< std::unordered_map< std::string, std::vector< char >>> & rows) virtual
Get all of the query result's rows as bytes mapped by column name.
Parameters
rows Output map to insert a row with each column's bytes mapped by column name
Returns
true on success, false on failure
Reimplemented from libcomp::DatabaseQueryImpl.
Definition at line 504 of file DatabaseQuerySQLite3.cpp.
References IsValid(), mStatement, mStatus, and Next().
int DatabaseQuerySQLite3::GetStatus () const
Get the current status of the query as a SQLite3 defined integer status code.
Returns
SQLite3 defined integer status code
Definition at line 598 of file DatabaseQuerySQLite3.cpp.
References mStatus.
bool DatabaseQuerySQLite3::GetValue (size_t index, String & value) virtual
Get a string column value by its index.
Parameters
index The column's index
value Variable to bind the value to
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 298 of file DatabaseQuerySQLite3.cpp.
References mResultColumnTypes, and mStatement.
Referenced by GetValue().
bool DatabaseQuerySQLite3::GetValue (const String & name, String & value) virtual
Get a string column value by its name.
Parameters
name The column's name
value Variable to bind the value to
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 318 of file DatabaseQuerySQLite3.cpp.
References GetResultColumnIndex(), and GetValue().
bool DatabaseQuerySQLite3::GetValue (size_t index, std::vector< char > & value) virtual
Get a blob column value by its index.
Parameters
index The column's index
value Variable to bind the value to
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 329 of file DatabaseQuerySQLite3.cpp.
References mResultColumnTypes, and mStatement.
bool DatabaseQuerySQLite3::GetValue (const String & name, std::vector< char > & value) virtual
Get a blob column value by its name.
Parameters
name The column's name
value Variable to bind the value to
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 349 of file DatabaseQuerySQLite3.cpp.
References GetResultColumnIndex(), and GetValue().
bool DatabaseQuerySQLite3::GetValue (size_t index, libobjgen::UUID & value) virtual
Get a UUID column value by its index.
Parameters
index The column's index
value Variable to bind the value to
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 361 of file DatabaseQuerySQLite3.cpp.
References GetValue(), and libcomp::String::ToUtf8().
bool DatabaseQuerySQLite3::GetValue (const String & name, libobjgen::UUID & value) virtual
Get a UUID column value by its name.
Parameters
name The column's name
value Variable to bind the value to
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 372 of file DatabaseQuerySQLite3.cpp.
References GetResultColumnIndex(), and GetValue().
bool DatabaseQuerySQLite3::GetValue (size_t index, int32_t & value) virtual
Get a 32-bit integer column value by its index.
Parameters
index The column's index
value Variable to bind the value to
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 384 of file DatabaseQuerySQLite3.cpp.
References mResultColumnTypes, and mStatement.
bool DatabaseQuerySQLite3::GetValue (const String & name, int32_t & value) virtual
Get a 32-bit integer column value by its name.
Parameters
name The column's name
value Variable to bind the value to
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 397 of file DatabaseQuerySQLite3.cpp.
References GetResultColumnIndex(), and GetValue().
bool DatabaseQuerySQLite3::GetValue (size_t index, int64_t & value) virtual
Get a 64-bit integer column value by its index.
Parameters
index The column's index
value Variable to bind the value to
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 408 of file DatabaseQuerySQLite3.cpp.
References mResultColumnTypes, and mStatement.
bool DatabaseQuerySQLite3::GetValue (const String & name, int64_t & value) virtual
Get a boolean column value by its name.
Parameters
name The column's name
value Variable to bind the value to
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 421 of file DatabaseQuerySQLite3.cpp.
References GetResultColumnIndex(), and GetValue().
bool DatabaseQuerySQLite3::GetValue (size_t index, float & value) virtual
Get a float column value by its index.
Parameters
index The column's index
value Variable to bind the value to
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 432 of file DatabaseQuerySQLite3.cpp.
References mResultColumnTypes, and mStatement.
bool DatabaseQuerySQLite3::GetValue (const String & name, float & value) virtual
Get a float column value by its name.
Parameters
name The column's name
value Variable to bind the value to
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 445 of file DatabaseQuerySQLite3.cpp.
References GetNamedBindingIndex(), GetResultColumnIndex(), and GetValue().
bool DatabaseQuerySQLite3::GetValue (size_t index, double & value) virtual
Get a double column value by its index.
Parameters
index The column's index
value Variable to bind the value to
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 456 of file DatabaseQuerySQLite3.cpp.
References mResultColumnTypes, and mStatement.
bool DatabaseQuerySQLite3::GetValue (const String & name, double & value) virtual
Get a double column value by its name.
Parameters
name The column's name
value Variable to bind the value to
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 469 of file DatabaseQuerySQLite3.cpp.
References GetNamedBindingIndex(), GetResultColumnIndex(), and GetValue().
bool DatabaseQuerySQLite3::GetValue (size_t index, bool & value) virtual
Get a boolean column value by its index.
Parameters
index The column's index
value Variable to bind the value to
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 480 of file DatabaseQuerySQLite3.cpp.
References mResultColumnTypes, and mStatement.
bool DatabaseQuerySQLite3::GetValue (const String & name, bool & value) virtual
Get a boolean column value by its name.
Parameters
name The column's name
value Variable to bind the value to
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 493 of file DatabaseQuerySQLite3.cpp.
References GetNamedBindingIndex(), GetResultColumnIndex(), and GetValue().
bool DatabaseQuerySQLite3::IsValid () const virtual
Check current query state validity.
Returns
true on valid, false on invalid
Implements libcomp::DatabaseQueryImpl.
Definition at line 591 of file DatabaseQuerySQLite3.cpp.
References mDatabase, mStatement, and mStatus.
Referenced by Bind(), Execute(), GetRows(), Next(), and Prepare().
bool DatabaseQuerySQLite3::Next () virtual
Increment the query results to look at the next result set row.
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 103 of file DatabaseQuerySQLite3.cpp.
References IsValid(), mDidJustExecute, mStatement, and mStatus.
Referenced by GetRows().
bool DatabaseQuerySQLite3::Prepare (const String & query) virtual
Prepare a database query for execution based upon query text.
See Also
DatabaseQueryImpl::Execute
Parameters
query Query text to prepare
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 57 of file DatabaseQuerySQLite3.cpp.
References libcomp::String::C(), IsValid(), libcomp::String::Length(), mDatabase, mStatement, and mStatus.
Member Data Documentation
int64_t libcomp::DatabaseQueryImpl::mAffectedRowCount protected inherited
Represents the number of affected rows since the last sucessful call to Execute.
Definition at line 383 of file DatabaseQuery.h.
Referenced by libcomp::DatabaseQueryImpl::AffectedRowCount(), Execute(), and libcomp::DatabaseQueryMariaDB::Execute().
sqlite3* libcomp::DatabaseQuerySQLite3::mDatabase private
Pointer to the SQLite3 database the query executes on.
Definition at line 143 of file DatabaseQuerySQLite3.h.
Referenced by Execute(), IsValid(), and Prepare().
bool libcomp::DatabaseQuerySQLite3::mDidJustExecute private
Indicator that Next() should be skipped the first time following execution to offset the need to call step (aka: Next()) to execute the query itself.
Definition at line 155 of file DatabaseQuerySQLite3.h.
Referenced by Execute(), and Next().
uint8_t libcomp::DatabaseQuerySQLite3::mMaxRetryCount private
Maximum number of retries allowed when executing the query.
Definition at line 158 of file DatabaseQuerySQLite3.h.
Referenced by Execute().
std::vector<std::string> libcomp::DatabaseQuerySQLite3::mResultColumnNames private
Column names from the current result set.
Definition at line 164 of file DatabaseQuerySQLite3.h.
Referenced by Execute(), and GetResultColumnIndex().
std::vector<int> libcomp::DatabaseQuerySQLite3::mResultColumnTypes private
Column data types from the current result set represented as SQLite3 data type integers.
Definition at line 168 of file DatabaseQuerySQLite3.h.
Referenced by Execute(), and GetValue().
uint16_t libcomp::DatabaseQuerySQLite3::mRetryDelay private
Time in milliseconds to wait between execution attempts.
Definition at line 161 of file DatabaseQuerySQLite3.h.
Referenced by Execute().
sqlite3_stmt* libcomp::DatabaseQuerySQLite3::mStatement private
Pointer to the SQLite3 representation of the query as a statement.
Definition at line 146 of file DatabaseQuerySQLite3.h.
Referenced by Bind(), Execute(), GetNamedBindingIndex(), GetRows(), GetValue(), IsValid(), Next(), Prepare(), and ~DatabaseQuerySQLite3().
int libcomp::DatabaseQuerySQLite3::mStatus private
Current status of the query as a SQLite3 defined integer status code.
Definition at line 150 of file DatabaseQuerySQLite3.h.
Referenced by Bind(), Execute(), GetRows(), GetStatus(), IsValid(), Next(), and Prepare().
The documentation for this class was generated from the following files:
DatabaseQuerySQLite3.h
DatabaseQuerySQLite3.cpp