COMP_hack: libcomp::DatabaseQueryMariaDB Class Reference
libcomp::DatabaseQueryMariaDB Class Reference
MariaDB database specific implementation of a query with binding and data retrieval functionality.
#include <DatabaseQueryMariaDB.h>
Public Member Functions
DatabaseQueryMariaDB (MYSQL *pDatabase)
Create a new MariaDB database query.
virtual ~DatabaseQueryMariaDB ()
Clean up the query.
int64_t AffectedRowCount () const
Get the count of affected rows from the last query execution.
virtual bool Bind (size_t index, const String &value)
Bind a string column value by its index.
virtual bool Bind (const String &name, const String &value)
Bind a string column value by its name.
virtual bool Bind (size_t index, const std::vector< char > &value)
Bind a blob column value by its index.
virtual bool Bind (const String &name, const std::vector< char > &value)
Bind a blob column value by its name.
virtual bool Bind (size_t index, const libobjgen::UUID &value)
Bind a UUID column value by its index.
virtual bool Bind (const String &name, const libobjgen::UUID &value)
Bind a UUID column value by its name.
virtual bool Bind (size_t index, int32_t value)
Bind a 32-bit integer column value by its index.
virtual bool Bind (const String &name, int32_t value)
Bind a 32-bit integer column value by its name.
virtual bool Bind (size_t index, int64_t value)
Bind a 64-bit integer column value by its index.
virtual bool Bind (const String &name, int64_t value)
Bind a 64-bit integer column value by its name.
virtual bool Bind (size_t index, float value)
Bind a float column value by its index.
virtual bool Bind (const String &name, float value)
Bind a float column value by its name.
virtual bool Bind (size_t index, double value)
Bind a double column value by its index.
virtual bool Bind (const String &name, double value)
Bind a double column value by its name.
virtual bool Bind (size_t index, bool value)
Bind a boolean column value by its index.
virtual bool Bind (const String &name, bool value)
Bind a boolean column value by its name.
virtual bool Bind (size_t index, const std::unordered_map< std::string, std::vector< char >> &values)
Bind a map column value by its index.
virtual bool Bind (const String &name, const std::unordered_map< std::string, std::vector< char >> &values)
Bind a map column value by its name.
virtual bool Execute ()
Execute a previously prepared query.
virtual bool GetRows (std::list< std::unordered_map< std::string, std::vector< char >>> &rows)
Get all of the query result's rows as bytes mapped by column name.
virtual bool GetValue (size_t index, String &value)
Get a string column value by its index.
virtual bool GetValue (const String &name, String &value)
Get a string column value by its name.
virtual bool GetValue (size_t index, std::vector< char > &value)
Get a blob column value by its index.
virtual bool GetValue (const String &name, std::vector< char > &value)
Get a blob column value by its name.
virtual bool GetValue (size_t index, libobjgen::UUID &value)
Get a UUID column value by its index.
virtual bool GetValue (const String &name, libobjgen::UUID &value)
Get a UUID column value by its name.
virtual bool GetValue (size_t index, int32_t &value)
Get a 32-bit integer column value by its index.
virtual bool GetValue (const String &name, int32_t &value)
Get a 32-bit integer column value by its name.
virtual bool GetValue (size_t index, int64_t &value)
Get a 64-bit integer column value by its index.
virtual bool GetValue (const String &name, int64_t &value)
Get a boolean column value by its name.
virtual bool GetValue (size_t index, float &value)
Get a float column value by its index.
virtual bool GetValue (const String &name, float &value)
Get a float column value by its name.
virtual bool GetValue (size_t index, double &value)
Get a double column value by its index.
virtual bool GetValue (const String &name, double &value)
Get a double column value by its name.
virtual bool GetValue (size_t index, bool &value)
Get a boolean column value by its index.
virtual bool GetValue (const String &name, bool &value)
Get a boolean column value by its name.
virtual bool IsValid () const
Check current query state validity.
virtual bool Next ()
Increment the query results to look at the next result set row.
virtual bool Prepare (const String &query)
Prepare a database query for execution based upon query text.
Protected Attributes
int64_t mAffectedRowCount
Represents the number of affected rows since the last sucessful call to Execute.
Private Member Functions
size_t GetNamedBindingIndex (const String &name)
Get the index of a named binding.
bool GetResultColumnIndex (const String &name, size_t &index) const
Get the index of the current result set's column by name.
MYSQL_BIND * PrepareBinding (size_t index, int type)
Create parameter bindings if they do not already exist and return the binding at the specified index.
Private Attributes
std::vector< MYSQL_BIND > mBindings
Bindings configured for all parameters passed into a query.
std::list< int64_t > mBufferBigInt
Buffer containing 64-bit int values for bound and selected values.
std::list< std::vector< char > > mBufferBlob
Buffer containing blob or string values for bound and selected values.
std::list< bool > mBufferBool
Buffer containing boolean values for bound and selected values.
std::list< double > mBufferDouble
Buffer containing double values for bound and selected values.
std::list< float > mBufferFloat
Buffer containing float values for bound and selected values.
std::list< int32_t > mBufferInt
Buffer containing 32-bit int values for bound and selected values.
std::list< unsigned long > mBufferLengths
Buffer containing length values for bound and selected values.
std::list< char > mBufferNulls
Buffer containing null specifiers for bound and selected values.
MYSQL * mDatabase
Pointer to the MariaDB database the query executes on.
std::vector< std::string > mParamNames
Param names pulled from the prepared statement to bind to.
std::vector< MYSQL_BIND > mResultBindings
Bindings configured to contain all results returned by a query.
std::vector< std::string > mResultColumnNames
Column names from the current result set.
std::vector< int > mResultColumnTypes
Column data types from the current result set represented as MariaDB data type integers.
MYSQL_STMT * mStatement
Pointer to the MariaDB representation of the query as a statement.
int mStatus
Current status of the query as a MariaDB defined integer status code.
Detailed Description
MariaDB database specific implementation of a query with binding and data retrieval functionality.
The connector for MariaDB is the same one used by MySQL which makes heavy use of buffer pointers for both input binding and output retrieval.
Definition at line 50 of file DatabaseQueryMariaDB.h.
Constructor & Destructor Documentation
DatabaseQueryMariaDB::DatabaseQueryMariaDB (MYSQL * pDatabase)
Create a new MariaDB database query.
Parameters
pDatabase Pointer to the executing MariaDB database
maxRetryCount Maximum number of retry attempts allowed when access to the DB during query execution returns as busy
retryDelay Delay in milliseconds between execution retry attempts
Definition at line 63 of file DatabaseQueryMariaDB.cpp.
DatabaseQueryMariaDB::~DatabaseQueryMariaDB () virtual
Clean up the query.
Definition at line 68 of file DatabaseQueryMariaDB.cpp.
References libcomp::String::Arg(), ConnectionString(), and mStatement.
Member Function Documentation
int64_t DatabaseQueryImpl::AffectedRowCount () const inherited
Get the count of affected rows from the last query execution.
Returns
Number of affected rows
Definition at line 67 of file DatabaseQuery.cpp.
References libcomp::DatabaseQueryImpl::mAffectedRowCount.
Referenced by libcomp::DatabaseQuery::AffectedRowCount().
bool DatabaseQueryMariaDB::Bind (size_t index, const String & value) virtual
Bind a string column value by its index.
Parameters
index The column's index
value The value to bind
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 373 of file DatabaseQueryMariaDB.cpp.
References libcomp::String::Data(), IsValid(), mBufferBlob, and PrepareBinding().
Referenced by Bind().
bool DatabaseQueryMariaDB::Bind (const String & name, const String & value) virtual
Bind a string column value by its name.
Parameters
name The column's name
value The value to bind
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 396 of file DatabaseQueryMariaDB.cpp.
References Bind(), GetNamedBindingIndex(), and IsValid().
bool DatabaseQueryMariaDB::Bind (size_t index, const std::vector< char > & value) virtual
Bind a blob column value by its index.
Parameters
index The column's index
value The value to bind
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 402 of file DatabaseQueryMariaDB.cpp.
References IsValid(), mBufferBlob, and PrepareBinding().
bool DatabaseQueryMariaDB::Bind (const String & name, const std::vector< char > & value) virtual
Bind a blob column value by its name.
Parameters
name The column's name
value The value to bind
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 424 of file DatabaseQueryMariaDB.cpp.
References Bind(), GetNamedBindingIndex(), and IsValid().
bool DatabaseQueryMariaDB::Bind (size_t index, const libobjgen::UUID & value) virtual
Bind a UUID column value by its index.
Parameters
index The column's index
value The value to bind
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 431 of file DatabaseQueryMariaDB.cpp.
References IsValid(), mBufferBlob, and PrepareBinding().
bool DatabaseQueryMariaDB::Bind (const String & name, const libobjgen::UUID & value) virtual
Bind a UUID column value by its name.
Parameters
name The column's name
value The value to bind
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 448 of file DatabaseQueryMariaDB.cpp.
References Bind(), and GetNamedBindingIndex().
bool DatabaseQueryMariaDB::Bind (size_t index, int32_t value) virtual
Bind a 32-bit integer column value by its index.
Parameters
index The column's index
value The value to bind
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 455 of file DatabaseQueryMariaDB.cpp.
References IsValid(), mBufferInt, and PrepareBinding().
bool DatabaseQueryMariaDB::Bind (const String & name, int32_t value) virtual
Bind a 32-bit integer column value by its name.
Parameters
name The column's name
value The value to bind
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 469 of file DatabaseQueryMariaDB.cpp.
References Bind(), GetNamedBindingIndex(), and IsValid().
bool DatabaseQueryMariaDB::Bind (size_t index, int64_t value) virtual
Bind a 64-bit integer column value by its index.
Parameters
index The column's index
value The value to bind
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 475 of file DatabaseQueryMariaDB.cpp.
References IsValid(), mBufferBigInt, and PrepareBinding().
bool DatabaseQueryMariaDB::Bind (const String & name, int64_t value) virtual
Bind a 64-bit integer column value by its name.
Parameters
name The column's name
value The value to bind
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 489 of file DatabaseQueryMariaDB.cpp.
References Bind(), GetNamedBindingIndex(), and IsValid().
bool DatabaseQueryMariaDB::Bind (size_t index, float value) virtual
Bind a float column value by its index.
Parameters
index The column's index
value The value to bind
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 495 of file DatabaseQueryMariaDB.cpp.
References IsValid(), mBufferFloat, and PrepareBinding().
bool DatabaseQueryMariaDB::Bind (const String & name, float value) virtual
Bind a float column value by its name.
Parameters
name The column's name
value The value to bind
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 509 of file DatabaseQueryMariaDB.cpp.
References Bind(), GetNamedBindingIndex(), and IsValid().
bool DatabaseQueryMariaDB::Bind (size_t index, double value) virtual
Bind a double column value by its index.
Parameters
index The column's index
value The value to bind
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 515 of file DatabaseQueryMariaDB.cpp.
References IsValid(), mBufferDouble, and PrepareBinding().
bool DatabaseQueryMariaDB::Bind (const String & name, double value) virtual
Bind a double column value by its name.
Parameters
name The column's name
value The value to bind
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 529 of file DatabaseQueryMariaDB.cpp.
References Bind(), GetNamedBindingIndex(), and IsValid().
bool DatabaseQueryMariaDB::Bind (size_t index, bool value) virtual
Bind a boolean column value by its index.
Parameters
index The column's index
value The value to bind
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 535 of file DatabaseQueryMariaDB.cpp.
References IsValid(), mBufferBool, and PrepareBinding().
bool DatabaseQueryMariaDB::Bind (const String & name, bool value) virtual
Bind a boolean column value by its name.
Parameters
name The column's name
value The value to bind
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 549 of file DatabaseQueryMariaDB.cpp.
References Bind(), GetNamedBindingIndex(), and IsValid().
bool DatabaseQueryMariaDB::Bind (size_t index, const std::unordered_map< std::string, std::vector< char >> & values) virtual
Bind a map column value by its index.
Parameters
index The column's index
values The value to bind
Returns
true on success, false on failure
Todo:
Reimplemented from libcomp::DatabaseQueryImpl.
Definition at line 555 of file DatabaseQueryMariaDB.cpp.
bool DatabaseQueryMariaDB::Bind (const String & name, const std::unordered_map< std::string, std::vector< char >> & values) virtual
Bind a map column value by its name.
Parameters
name The column's name
values The value to bind
Returns
true on success, false on failure
Todo:
Reimplemented from libcomp::DatabaseQueryImpl.
Definition at line 565 of file DatabaseQueryMariaDB.cpp.
bool DatabaseQueryMariaDB::Execute () virtual
Execute a previously prepared query.
See Also
DatabaseQueryImpl::Prepare
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 157 of file DatabaseQueryMariaDB.cpp.
References libcomp::String::Arg(), ConnectionString(), GetLastError(), IsValid(), libcomp::DatabaseQueryImpl::mAffectedRowCount, mBindings, mBufferBigInt, mBufferBlob, mBufferBool, mBufferDouble, mBufferFloat, mBufferInt, mBufferLengths, mBufferNulls, mDatabase, mResultBindings, mResultColumnNames, mResultColumnTypes, mStatement, and mStatus.
size_t DatabaseQueryMariaDB::GetNamedBindingIndex (const String & name) private
Get the index of a named binding.
Parameters
name Name of the binding
Returns
Index of the binding
Definition at line 902 of file DatabaseQueryMariaDB.cpp.
References mParamNames, and mStatus.
Referenced by Bind(), and GetValue().
bool DatabaseQueryMariaDB::GetResultColumnIndex (const String & name, size_t & index) const private
Get the index of the current result set's column by name.
Parameters
name Name of the column
index Variable to store the index in
Returns
true on success, false on failure
Definition at line 913 of file DatabaseQueryMariaDB.cpp.
References mResultColumnNames.
Referenced by GetValue().
bool DatabaseQueryMariaDB::GetRows (std::list< std::unordered_map< std::string, std::vector< char >>> & rows) virtual
Get all of the query result's rows as bytes mapped by column name.
Parameters
rows Output map to insert a row with each column's bytes mapped by column name
Returns
true on success, false on failure
Reimplemented from libcomp::DatabaseQueryImpl.
Definition at line 788 of file DatabaseQueryMariaDB.cpp.
References bool, libcomp::String::C(), GetValue(), IsValid(), libcomp::String::Length(), mResultColumnNames, mResultColumnTypes, mStatus, and Next().
bool DatabaseQueryMariaDB::GetValue (size_t index, String & value) virtual
Get a string column value by its index.
Parameters
index The column's index
value Variable to bind the value to
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 575 of file DatabaseQueryMariaDB.cpp.
References mResultBindings, and mResultColumnTypes.
Referenced by GetRows(), and GetValue().
bool DatabaseQueryMariaDB::GetValue (const String & name, String & value) virtual
Get a string column value by its name.
Parameters
name The column's name
value Variable to bind the value to
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 597 of file DatabaseQueryMariaDB.cpp.
References GetResultColumnIndex(), and GetValue().
bool DatabaseQueryMariaDB::GetValue (size_t index, std::vector< char > & value) virtual
Get a blob column value by its index.
Parameters
index The column's index
value Variable to bind the value to
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 608 of file DatabaseQueryMariaDB.cpp.
References mResultBindings, and mResultColumnTypes.
bool DatabaseQueryMariaDB::GetValue (const String & name, std::vector< char > & value) virtual
Get a blob column value by its name.
Parameters
name The column's name
value Variable to bind the value to
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 628 of file DatabaseQueryMariaDB.cpp.
References GetResultColumnIndex(), and GetValue().
bool DatabaseQueryMariaDB::GetValue (size_t index, libobjgen::UUID & value) virtual
Get a UUID column value by its index.
Parameters
index The column's index
value Variable to bind the value to
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 640 of file DatabaseQueryMariaDB.cpp.
References GetValue(), and libcomp::String::ToUtf8().
bool DatabaseQueryMariaDB::GetValue (const String & name, libobjgen::UUID & value) virtual
Get a UUID column value by its name.
Parameters
name The column's name
value Variable to bind the value to
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 651 of file DatabaseQueryMariaDB.cpp.
References GetResultColumnIndex(), and GetValue().
bool DatabaseQueryMariaDB::GetValue (size_t index, int32_t & value) virtual
Get a 32-bit integer column value by its index.
Parameters
index The column's index
value Variable to bind the value to
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 663 of file DatabaseQueryMariaDB.cpp.
References mResultBindings, and mResultColumnTypes.
bool DatabaseQueryMariaDB::GetValue (const String & name, int32_t & value) virtual
Get a 32-bit integer column value by its name.
Parameters
name The column's name
value Variable to bind the value to
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 677 of file DatabaseQueryMariaDB.cpp.
References GetResultColumnIndex(), and GetValue().
bool DatabaseQueryMariaDB::GetValue (size_t index, int64_t & value) virtual
Get a 64-bit integer column value by its index.
Parameters
index The column's index
value Variable to bind the value to
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 688 of file DatabaseQueryMariaDB.cpp.
References mResultBindings, and mResultColumnTypes.
bool DatabaseQueryMariaDB::GetValue (const String & name, int64_t & value) virtual
Get a boolean column value by its name.
Parameters
name The column's name
value Variable to bind the value to
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 702 of file DatabaseQueryMariaDB.cpp.
References GetResultColumnIndex(), and GetValue().
bool DatabaseQueryMariaDB::GetValue (size_t index, float & value) virtual
Get a float column value by its index.
Parameters
index The column's index
value Variable to bind the value to
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 713 of file DatabaseQueryMariaDB.cpp.
References mResultBindings, and mResultColumnTypes.
bool DatabaseQueryMariaDB::GetValue (const String & name, float & value) virtual
Get a float column value by its name.
Parameters
name The column's name
value Variable to bind the value to
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 727 of file DatabaseQueryMariaDB.cpp.
References GetNamedBindingIndex(), GetResultColumnIndex(), and GetValue().
bool DatabaseQueryMariaDB::GetValue (size_t index, double & value) virtual
Get a double column value by its index.
Parameters
index The column's index
value Variable to bind the value to
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 738 of file DatabaseQueryMariaDB.cpp.
References mResultBindings, and mResultColumnTypes.
bool DatabaseQueryMariaDB::GetValue (const String & name, double & value) virtual
Get a double column value by its name.
Parameters
name The column's name
value Variable to bind the value to
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 752 of file DatabaseQueryMariaDB.cpp.
References GetNamedBindingIndex(), GetResultColumnIndex(), and GetValue().
bool DatabaseQueryMariaDB::GetValue (size_t index, bool & value) virtual
Get a boolean column value by its index.
Parameters
index The column's index
value Variable to bind the value to
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 763 of file DatabaseQueryMariaDB.cpp.
References mResultBindings, and mResultColumnTypes.
bool DatabaseQueryMariaDB::GetValue (const String & name, bool & value) virtual
Get a boolean column value by its name.
Parameters
name The column's name
value Variable to bind the value to
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 777 of file DatabaseQueryMariaDB.cpp.
References GetNamedBindingIndex(), GetResultColumnIndex(), and GetValue().
bool DatabaseQueryMariaDB::IsValid () const virtual
Check current query state validity.
Returns
true on valid, false on invalid
Implements libcomp::DatabaseQueryImpl.
Definition at line 895 of file DatabaseQueryMariaDB.cpp.
References mDatabase, mStatement, and mStatus.
Referenced by Bind(), Execute(), GetRows(), Next(), and Prepare().
bool DatabaseQueryMariaDB::Next () virtual
Increment the query results to look at the next result set row.
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 350 of file DatabaseQueryMariaDB.cpp.
References libcomp::String::Arg(), ConnectionString(), GetLastError(), IsValid(), mDatabase, mStatement, and mStatus.
Referenced by GetRows().
bool DatabaseQueryMariaDB::Prepare (const String & query) virtual
Prepare a database query for execution based upon query text.
See Also
DatabaseQueryImpl::Execute
Parameters
query Query text to prepare
Returns
true on success, false on failure
Implements libcomp::DatabaseQueryImpl.
Definition at line 82 of file DatabaseQueryMariaDB.cpp.
References libcomp::String::Arg(), libcomp::String::C(), ConnectionString(), GetLastError(), IsValid(), mDatabase, mParamNames, mStatement, and mStatus.
MYSQL_BIND * DatabaseQueryMariaDB::PrepareBinding (size_t index, int type) private
Create parameter bindings if they do not already exist and return the binding at the specified index.
Parameters
index Index to retrieve a parameter binding in the collection from
type Binding type to set after retrieval
Returns
Pointer to the parameter binding at the specified index
Definition at line 925 of file DatabaseQueryMariaDB.cpp.
References mBindings, mBufferLengths, mBufferNulls, and mStatement.
Referenced by Bind().
Member Data Documentation
int64_t libcomp::DatabaseQueryImpl::mAffectedRowCount protected inherited
Represents the number of affected rows since the last sucessful call to Execute.
Definition at line 383 of file DatabaseQuery.h.
Referenced by libcomp::DatabaseQueryImpl::AffectedRowCount(), libcomp::DatabaseQuerySQLite3::Execute(), and Execute().
std::vector<MYSQL_BIND> libcomp::DatabaseQueryMariaDB::mBindings private
Bindings configured for all parameters passed into a query.
Definition at line 147 of file DatabaseQueryMariaDB.h.
Referenced by Execute(), and PrepareBinding().
std::list<int64_t> libcomp::DatabaseQueryMariaDB::mBufferBigInt private
Buffer containing 64-bit int values for bound and selected values.
Definition at line 170 of file DatabaseQueryMariaDB.h.
Referenced by Bind(), and Execute().
std::list<std::vector<char> > libcomp::DatabaseQueryMariaDB::mBufferBlob private
Buffer containing blob or string values for bound and selected values.
Definition at line 179 of file DatabaseQueryMariaDB.h.
Referenced by Bind(), and Execute().
std::list<bool> libcomp::DatabaseQueryMariaDB::mBufferBool private
Buffer containing boolean values for bound and selected values.
Definition at line 182 of file DatabaseQueryMariaDB.h.
Referenced by Bind(), and Execute().
std::list<double> libcomp::DatabaseQueryMariaDB::mBufferDouble private
Buffer containing double values for bound and selected values.
Definition at line 176 of file DatabaseQueryMariaDB.h.
Referenced by Bind(), and Execute().
std::list<float> libcomp::DatabaseQueryMariaDB::mBufferFloat private
Buffer containing float values for bound and selected values.
Definition at line 173 of file DatabaseQueryMariaDB.h.
Referenced by Bind(), and Execute().
std::list<int32_t> libcomp::DatabaseQueryMariaDB::mBufferInt private
Buffer containing 32-bit int values for bound and selected values.
Definition at line 167 of file DatabaseQueryMariaDB.h.
Referenced by Bind(), and Execute().
std::list<unsigned long> libcomp::DatabaseQueryMariaDB::mBufferLengths private
Buffer containing length values for bound and selected values.
Definition at line 188 of file DatabaseQueryMariaDB.h.
Referenced by Execute(), and PrepareBinding().
std::list<char> libcomp::DatabaseQueryMariaDB::mBufferNulls private
Buffer containing null specifiers for bound and selected values.
Definition at line 185 of file DatabaseQueryMariaDB.h.
Referenced by Execute(), and PrepareBinding().
MYSQL* libcomp::DatabaseQueryMariaDB::mDatabase private
Pointer to the MariaDB database the query executes on.
Definition at line 141 of file DatabaseQueryMariaDB.h.
Referenced by Execute(), IsValid(), Next(), and Prepare().
std::vector<std::string> libcomp::DatabaseQueryMariaDB::mParamNames private
Param names pulled from the prepared statement to bind to.
Definition at line 157 of file DatabaseQueryMariaDB.h.
Referenced by GetNamedBindingIndex(), and Prepare().
std::vector<MYSQL_BIND> libcomp::DatabaseQueryMariaDB::mResultBindings private
Bindings configured to contain all results returned by a query.
Definition at line 150 of file DatabaseQueryMariaDB.h.
Referenced by Execute(), and GetValue().
std::vector<std::string> libcomp::DatabaseQueryMariaDB::mResultColumnNames private
Column names from the current result set.
Definition at line 160 of file DatabaseQueryMariaDB.h.
Referenced by Execute(), GetResultColumnIndex(), and GetRows().
std::vector<int> libcomp::DatabaseQueryMariaDB::mResultColumnTypes private
Column data types from the current result set represented as MariaDB data type integers.
Definition at line 164 of file DatabaseQueryMariaDB.h.
Referenced by Execute(), GetRows(), and GetValue().
MYSQL_STMT* libcomp::DatabaseQueryMariaDB::mStatement private
Pointer to the MariaDB representation of the query as a statement.
Definition at line 144 of file DatabaseQueryMariaDB.h.
Referenced by Execute(), IsValid(), Next(), Prepare(), PrepareBinding(), and ~DatabaseQueryMariaDB().
int libcomp::DatabaseQueryMariaDB::mStatus private
Current status of the query as a MariaDB defined integer status code.
Definition at line 154 of file DatabaseQueryMariaDB.h.
Referenced by Execute(), GetNamedBindingIndex(), GetRows(), IsValid(), Next(), and Prepare().
The documentation for this class was generated from the following files:
DatabaseQueryMariaDB.h
DatabaseQueryMariaDB.cpp