COMP_hack: libcomp::ServerDataManager Class Reference
libcomp::ServerDataManager Class Reference
Manager class responsible for loading server specific files such as zones and script files.
#include <ServerDataManager.h>
Public Member Functions
ServerDataManager ()
Create a new ServerDataManager.
~ServerDataManager ()
Clean up the ServerDataManager.
void AppendPendingDrops ()
Merges all pending drops from APPEND drop sets into the the actual drop set and clears the set.
bool ApplyZonePartial (std::shared_ptr< objects::ServerZone > zone, uint32_t partialID)
Apply modifications from a zone partial to an instanced zone definition.
bool ExistsInInstance (uint32_t instanceID, uint32_t zoneID, uint32_t dynamicMapID)
Check if the supplied zone ID and dynamicMap ID exist in a specific instance definition.
const std::shared_ptr
< objects::AILogicGroup > GetAILogicGroup (uint16_t id)
Get an AI logic group by definition ID.
const std::shared_ptr
< ServerScript > GetAIScript (const libcomp::String &name)
Get an AI script by name.
const std::unordered_map
< uint32_t, std::set< uint32_t > > GetAllZoneIDs ()
Get all server zone defintion IDs with corresponding dynamic map IDs registered with the manager.
const std::set< uint32_t > GetAllZoneInstanceIDs ()
Get all server zone instance defintion IDs registered with the manager.
std::list< uint32_t > GetCompShopIDs () const
Get a list of all COMP shop definition IDs.
const std::shared_ptr
< objects::DemonFamiliarityType > GetDemonFamiliarityTypeData (int32_t id)
Get a demon familiarity type entry by definition ID.
const std::shared_ptr
< objects::DemonPresent > GetDemonPresentData (uint32_t id)
Get a demon present entry by definition ID.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::DemonQuestReward > > GetDemonQuestRewardData ()
Get all demon quest reward definitions.
const std::shared_ptr
< objects::DropSet > GetDropSetData (uint32_t id)
Get a drop set by definition ID.
const std::shared_ptr
< objects::Event > GetEventData (const libcomp::String &id)
Get an event by definition ID.
const std::list< std::pair
< uint32_t, uint32_t > > GetFieldZoneIDs ()
Get all field zone pairs of zone IDs and dynamic map IDs configured for the server.
const std::shared_ptr
< objects::DropSet > GetGiftDropSetData (uint32_t giftBoxID)
Get a drop set by gift box ID.
const std::shared_ptr
< ServerScript > GetScript (const libcomp::String &name)
Get a miscellaneous script by name.
const std::shared_ptr
< objects::ServerShop > GetShopData (uint32_t id)
Get a shop by definition ID.
std::set< uint32_t > GetStandardPvPVariantIDs (uint8_t type) const
Get all standard PvP variant IDs associated to a specific PvP type.
const std::shared_ptr
< objects::ServerZone > GetZoneData (uint32_t id, uint32_t dynamicMapID, bool applyPartials=false, std::set< uint32_t > extraPartialIDs={})
Get a server zone by definition ID.
const std::shared_ptr
< objects::ServerZoneInstance > GetZoneInstanceData (uint32_t id)
Get a server zone instance by definition ID.
const std::shared_ptr
< objects::ServerZoneInstanceVariant > GetZoneInstanceVariantData (uint32_t id)
Get a server zone instance variant by definition ID.
const std::shared_ptr
< objects::ServerZonePartial > GetZonePartialData (uint32_t id)
Get a server zone partial by definition ID.
bool LoadData (DataStore *pDataStore, DefinitionManager *definitionManager)
Load all server data defintions in the data store.
std::list< std::shared_ptr
< ServerScript > > LoadScripts (DataStore *pDataStore, const libcomp::String &path, bool &success, bool store=true)
Load all script files in the specified datastore and return them in a list.
bool VerifyPvPInstance (uint32_t instanceID, DefinitionManager *definitionManager)
Verify if the supplied instance is valid for being a PvP variant.
Static Public Member Functions
static void ApplyZonePartial (std::shared_ptr< objects::ServerZone > zone, const std::shared_ptr< objects::ServerZonePartial > &partial, bool positionReplace)
Apply modifications from a zone partial to an instanced zone definition.
Private Member Functions
template<class K , class T >
std::shared_ptr< T > GetObjectByID (K id, std::unordered_map< K, std::shared_ptr< T >> &data)
Get a server object by ID from the supplied map of the specified key and value type.
template<class T >
bool LoadObject (const tinyxml2::XMLDocument &doc, const tinyxml2::XMLElement *objNode, DefinitionManager *definitionManager=nullptr)
Load an object of the templated type from an XML node.
template<class T >
bool LoadObjects (gsl::not_null< DataStore * > pDataStore, const libcomp::String &datastorePath, DefinitionManager *definitionManager, bool recursive, bool fileOrPath)
Load all objects from files in a datastore path.
template<class T >
bool LoadObjectsFromFile (gsl::not_null< DataStore * > pDataStore, const libcomp::String &filePath, DefinitionManager *definitionManager=nullptr)
Load all objects from a specific file in a datastore path.
bool LoadScript (const libcomp::String &path, const libcomp::String &source)
Store a successfully loaded (non-AI) script.
bool LoadScripts (gsl::not_null< DataStore * > pDataStore, const libcomp::String &datastorePath, std::function< bool(ServerDataManager &, const libcomp::String &, const libcomp::String &)> handler)
Load all script files in the specified datastore.
bool TriggerIsAutoContext (const std::shared_ptr< objects::ServerZoneTrigger > &trigger)
Check if the supplied trigger starts in an auto-only context for actions.
bool ValidateActions (const std::list< std::shared_ptr< objects::Action >> &actions, const libcomp::String &source, bool autoContext, bool inEvent=false)
Check for any issues in an action set and report any found in the logs.
Private Attributes
std::unordered_map< uint16_t,
std::shared_ptr
< objects::AILogicGroup > > mAILogicGroups
Map of AI logic groups by definition ID.
std::unordered_map
< std::string, std::shared_ptr
< ServerScript > > mAIScripts
Map of AI scripts by name.
std::list< uint32_t > mCompShopIDs
List of all COMP shop definition IDs.
std::unordered_map< int32_t,
std::shared_ptr
< objects::DemonFamiliarityType > > mDemonFamiliarityTypeData
Map of demon familiarity type entries by definition ID.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::DemonPresent > > mDemonPresentData
Map of demon present entries by definition ID.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::DemonQuestReward > > mDemonQuestRewardData
Map of demon quest reward entries by definition ID.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::DropSet > > mDropSetData
Map of drop sets by definition ID.
std::unordered_map
< std::string, std::shared_ptr
< objects::Event > > mEventData
Map of events by definition ID.
std::list< std::pair< uint32_t,
uint32_t > > mFieldZoneIDs
List of zone ID to dynamic map ID pairs of field zones.
std::unordered_map< uint32_t,
uint32_t > mGiftDropSetLookup
Map of drop set defintion IDs by gift box ID.
std::unordered_map< uint32_t,
std::list< std::shared_ptr
< objects::ItemDrop > > > mPendingMergeDrops
Map of drop set definition IDs to drops loaded from APPEND drop sets.
std::unordered_map
< std::string, std::shared_ptr
< ServerScript > > mScripts
Map of miscellaneous (non-AI) scripts by name.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::ServerShop > > mShopData
Map of shops by definition ID.
std::unordered_map< uint8_t,
std::set< uint32_t > > mStandardPvPVariantIDs
std::unordered_map< uint32_t,
std::unordered_map< uint32_t,
std::shared_ptr
< objects::ServerZone > > > mZoneData
Map of server zone defintions by zone definition and dynamic map ID.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::ServerZoneInstance > > mZoneInstanceData
Map of server zone instance defintions by definition ID.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::ServerZoneInstanceVariant > > mZoneInstanceVariantData
Map of server zone instance variant defintions by definition ID.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::ServerZonePartial > > mZonePartialData
Map of server zone partial defintions by definition ID.
std::unordered_map< uint32_t,
std::set< uint32_t > > mZonePartialMap
Map of auto apply server zone partial defintion IDs mapped to directly on the definition by dynamic map ID.
Detailed Description
Manager class responsible for loading server specific files such as zones and script files.
Definition at line 90 of file ServerDataManager.h.
Constructor & Destructor Documentation
ServerDataManager::ServerDataManager ()
Create a new ServerDataManager.
Definition at line 78 of file ServerDataManager.cpp.
ServerDataManager::~ServerDataManager ()
Clean up the ServerDataManager.
Definition at line 82 of file ServerDataManager.cpp.
Member Function Documentation
void ServerDataManager::AppendPendingDrops ()
Merges all pending drops from APPEND drop sets into the the actual drop set and clears the set.
This should only be called once per server load.
Definition at line 824 of file ServerDataManager.cpp.
References libcomp::String::Arg(), mDropSetData, and mPendingMergeDrops.
Referenced by LoadData().
bool ServerDataManager::ApplyZonePartial (std::shared_ptr< objects::ServerZone > zone, uint32_t partialID)
Apply modifications from a zone partial to an instanced zone definition.
Unique IDs and NPCs/objects in the same spot that already exist on the definition will be replaced by the partial definition, including deletes. If the zone definition supplied for this function matches the pointer stored for the base definition, it will fail.
Parameters
zone Pointer to a zone definition to modify
partialID ID of the zone partial definition to apply to the zone
Returns
true if the modifications were successful, false if they were not or if the supplied zone definition is not a copy of the original
Definition at line 625 of file ServerDataManager.cpp.
References libcomp::String::Arg(), GetZoneData(), and GetZonePartialData().
Referenced by GetZoneData().
void ServerDataManager::ApplyZonePartial (std::shared_ptr< objects::ServerZone > zone, const std::shared_ptr< objects::ServerZonePartial > & partial, bool positionReplace) static
Apply modifications from a zone partial to an instanced zone definition.
Unique IDs and NPCs/objects in the same spot that already exist on the definition will be replaced by the partial definition, including deletes. The supplied zone being a copy must be checked before this point.
Parameters
zone Pointer to a zone definition to modify
partial Pointer to the zone partial definition to apply to the zone
positionReplace If true non-keyed objects at the same position will be replaced as we go. If false they will all be included.
Definition at line 666 of file ServerDataManager.cpp.
bool ServerDataManager::ExistsInInstance (uint32_t instanceID, uint32_t zoneID, uint32_t dynamicMapID)
Check if the supplied zone ID and dynamicMap ID exist in a specific instance definition.
Parameters
instanceID Definition ID of a zone instance
zoneID Zone ID to check
dynamicMapID Dynamic Map ID to check
Returns
true if it exists, false if it does not
Definition at line 279 of file ServerDataManager.cpp.
References GetZoneInstanceData().
const std::shared_ptr< objects::AILogicGroup > ServerDataManager::GetAILogicGroup (uint16_t id)
Get an AI logic group by definition ID.
Parameters
id Definition ID of an AI logic group
Returns
Pointer to the AI logic group matching the specified id
Definition at line 367 of file ServerDataManager.cpp.
References mAILogicGroups.
const std::shared_ptr< ServerScript > ServerDataManager::GetAIScript (const libcomp::String & name)
Get an AI script by name.
Parameters
name Name of the script to load
Returns
Pointer to the script definition
Definition at line 407 of file ServerDataManager.cpp.
References libcomp::String::C(), and mAIScripts.
const std::unordered_map< uint32_t, std::set< uint32_t > > ServerDataManager::GetAllZoneIDs ()
Get all server zone defintion IDs with corresponding dynamic map IDs registered with the manager.
Returns
Set of all zone definition IDs registered with the manager
Definition at line 248 of file ServerDataManager.cpp.
References mZoneData.
const std::set< uint32_t > ServerDataManager::GetAllZoneInstanceIDs ()
Get all server zone instance defintion IDs registered with the manager.
Returns
Set of all zone instance definition IDs registered with the manager
Definition at line 268 of file ServerDataManager.cpp.
References mZoneInstanceData.
std::list< uint32_t > ServerDataManager::GetCompShopIDs () const
Get a list of all COMP shop definition IDs.
Returns
List of COMP shop definition IDs
Definition at line 362 of file ServerDataManager.cpp.
References mCompShopIDs.
const std::shared_ptr< objects::DemonFamiliarityType > ServerDataManager::GetDemonFamiliarityTypeData (int32_t id)
Get a demon familiarity type entry by definition ID.
Parameters
id Definition ID of a demon familiarity type entry to load
Returns
Pointer to the demon familiarity type entry matching the specified id
Definition at line 373 of file ServerDataManager.cpp.
References mDemonFamiliarityTypeData.
const std::shared_ptr< objects::DemonPresent > ServerDataManager::GetDemonPresentData (uint32_t id)
Get a demon present entry by definition ID.
Parameters
id Definition ID of a demon present entry to load
Returns
Pointer to the demon present entry matching the specified id
Definition at line 379 of file ServerDataManager.cpp.
References mDemonPresentData.
std::unordered_map< uint32_t, std::shared_ptr< objects::DemonQuestReward > > ServerDataManager::GetDemonQuestRewardData ()
Get all demon quest reward definitions.
Returns
Map of all demon quest reward definitions by ID
Definition at line 385 of file ServerDataManager.cpp.
References mDemonQuestRewardData.
const std::shared_ptr< objects::DropSet > ServerDataManager::GetDropSetData (uint32_t id)
Get a drop set by definition ID.
Parameters
id Definition ID of a drop set to load
Returns
Pointer to the drop set matching the specified id
Definition at line 390 of file ServerDataManager.cpp.
References mDropSetData.
Referenced by GetGiftDropSetData().
const std::shared_ptr< objects::Event > ServerDataManager::GetEventData (const libcomp::String & id)
Get an event by definition ID.
Parameters
id Definition ID of an event to load
Returns
Pointer to the event matching the specified id
Definition at line 352 of file ServerDataManager.cpp.
References mEventData.
const std::list< std::pair< uint32_t, uint32_t > > ServerDataManager::GetFieldZoneIDs ()
Get all field zone pairs of zone IDs and dynamic map IDs configured for the server.
Returns
List of zone ID to dynamic map ID pairs of field zones
Definition at line 243 of file ServerDataManager.cpp.
References mFieldZoneIDs.
const std::shared_ptr< objects::DropSet > ServerDataManager::GetGiftDropSetData (uint32_t giftBoxID)
Get a drop set by gift box ID.
Parameters
giftBoxID Gift box ID of a drop set to load
Returns
Pointer to the drop set matching the specified id
Definition at line 395 of file ServerDataManager.cpp.
References GetDropSetData(), and mGiftDropSetLookup.
template<class K , class T > std::shared_ptr<T> libcomp::ServerDataManager::GetObjectByID (K id, std::unordered_map< K, std::shared_ptr< T >> & data) inline private
Get a server object by ID from the supplied map of the specified key and value type.
Parameters
id ID of the server object to retrieve from the map
data Map of server objects to retrieve by ID
Returns
Pointer to the matching server object, null if doesn't exist
Definition at line 338 of file ServerDataManager.h.
const std::shared_ptr< ServerScript > ServerDataManager::GetScript (const libcomp::String & name)
Get a miscellaneous script by name.
Parameters
name Name of the script to load
Returns
Pointer to the script definition
Definition at line 402 of file ServerDataManager.cpp.
References libcomp::String::C(), and mScripts.
const std::shared_ptr< objects::ServerShop > ServerDataManager::GetShopData (uint32_t id)
Get a shop by definition ID.
Parameters
id Definition ID of a shop to load
Returns
Pointer to the shop matching the specified id
Definition at line 357 of file ServerDataManager.cpp.
References mShopData.
std::set< uint32_t > ServerDataManager::GetStandardPvPVariantIDs (uint8_t type) const
Get all standard PvP variant IDs associated to a specific PvP type.
Parameters
type PvP type
Returns
Set of all variant IDs associated to the type
Definition at line 305 of file ServerDataManager.cpp.
References mStandardPvPVariantIDs.
const std::shared_ptr< objects::ServerZone > ServerDataManager::GetZoneData (uint32_t id, uint32_t dynamicMapID, bool applyPartials = false, std::set< uint32_t > extraPartialIDs = {})
Get a server zone by definition ID.
Parameters
id Definition ID of a zone to retrieve
dynamicMapID Dynamic map ID of the zone to retrieve
applyPartials If true, the definition will be re-instanced and have all self-applied ServerZonePartial definitions applied to it. If false, the normal definition will be returned.
extraPartialIDs If applying ServerZonePartial definitions, the IDs supplied will be loaded as well
Returns
Pointer to the server zone matching the specified id
Definition at line 86 of file ServerDataManager.cpp.
References ApplyZonePartial(), libcomp::String::Arg(), GetZonePartialData(), mZoneData, and mZonePartialMap.
Referenced by ApplyZonePartial().
const std::shared_ptr< objects::ServerZoneInstance > ServerDataManager::GetZoneInstanceData (uint32_t id)
Get a server zone instance by definition ID.
Parameters
id Definition ID of a zone instance to retrieve
Returns
Pointer to the server zone instance matching the specified id
Definition at line 262 of file ServerDataManager.cpp.
References mZoneInstanceData.
Referenced by ExistsInInstance(), and VerifyPvPInstance().
const std::shared_ptr< objects::ServerZoneInstanceVariant > ServerDataManager::GetZoneInstanceVariantData (uint32_t id)
Get a server zone instance variant by definition ID.
Parameters
id Definition ID of a zone instance variant to retrieve
Returns
Pointer to the server zone instance variant matching the specified id
Definition at line 299 of file ServerDataManager.cpp.
References mZoneInstanceVariantData.
const std::shared_ptr< objects::ServerZonePartial > ServerDataManager::GetZonePartialData (uint32_t id)
Get a server zone partial by definition ID.
Parameters
id Definition ID of a zone partial to retrieve
Returns
Pointer to the server zone partial matching the specified id
Definition at line 347 of file ServerDataManager.cpp.
References mZonePartialData.
Referenced by ApplyZonePartial(), and GetZoneData().
bool ServerDataManager::LoadData (DataStore * pDataStore, DefinitionManager * definitionManager)
Load all server data defintions in the data store.
Parameters
pDataStore Pointer to the datastore to load binary files from
definitionManager Pointer to the definition manager which will be loaded with any server side definitions. Loading of these definitions will be skipped if this is null.
Returns
true on success, false on failure
Definition at line 412 of file ServerDataManager.cpp.
References AppendPendingDrops(), LoadScript(), and LoadScripts().
Referenced by libcomp::ScriptEngine::Using().
template<class T > bool libcomp::ServerDataManager::LoadObject (const tinyxml2::XMLDocument & doc, const tinyxml2::XMLElement * objNode, DefinitionManager * definitionManager = nullptr) private
Load an object of the templated type from an XML node.
Parameters
doc XML document being loaded from
objNode XML node being loaded from
definitionManager Pointer to the definition manager which will be loaded with any server side definitions
Returns
true on success, false on failure
template<class T > bool libcomp::ServerDataManager::LoadObjects (gsl::not_null< DataStore * > pDataStore, const libcomp::String & datastorePath, DefinitionManager * definitionManager, bool recursive, bool fileOrPath) inline private
Load all objects from files in a datastore path.
Parameters
pDataStore Pointer to the datastore to use
datastorePath Path within the data store to load files from
definitionManager Pointer to the definition manager which will be loaded with any server side definitions
recursive If true sub-directories will be loaded from as well
fileOrPath If true and no files are found in the path, the path will be treated like a file path by appending ".xml"
Returns
true on success, false on failure
Definition at line 362 of file ServerDataManager.h.
References libcomp::String::Matches().
template<class T > bool libcomp::ServerDataManager::LoadObjectsFromFile (gsl::not_null< DataStore * > pDataStore, const libcomp::String & filePath, DefinitionManager * definitionManager = nullptr) inline private
Load all objects from a specific file in a datastore path.
Parameters
pDataStore Pointer to the datastore to use
filePath File path within the data store to load from
definitionManager Pointer to the definition manager which will be loaded with any server side definitions
Returns
true on success, false on failure
Definition at line 411 of file ServerDataManager.h.
References libcomp::String::Arg().
bool ServerDataManager::LoadScript (const libcomp::String & path, const libcomp::String & source) private
Store a successfully loaded (non-AI) script.
Parameters
path Path to the script file
source Source contained within the script file
Returns
true on success, false on failure
Definition at line 1792 of file ServerDataManager.cpp.
References libcomp::String::Arg(), libcomp::ScriptEngine::Eval(), libcomp::ScriptEngine::GetVM(), mAIScripts, mScripts, libcomp::ServerScript::Path, and libcomp::ScriptEngine::Using().
Referenced by LoadData(), and LoadScripts().
std::list< std::shared_ptr< ServerScript > > ServerDataManager::LoadScripts (DataStore * pDataStore, const libcomp::String & path, bool & success, bool store = true)
Load all script files in the specified datastore and return them in a list.
Parameters
pDataStore Pointer to the datastore to use
path Path within the data store to load scripts from
success Output result designating success or failure
store If false, scripts loaded by this function will be unloaded after they are gathered for the return results
Returns
List of pointers to server script definitions
Definition at line 589 of file ServerDataManager.cpp.
References LoadScript(), mAIScripts, and mScripts.
Referenced by LoadData().
bool ServerDataManager::LoadScripts (gsl::not_null< DataStore * > pDataStore, const libcomp::String & datastorePath, std::function< bool(ServerDataManager &, const libcomp::String &, const libcomp::String &)> handler) private
Load all script files in the specified datastore.
Parameters
pDataStore Pointer to the datastore to use
datastorePath Path within the data store to load scripts from
handler Function pointer to call upon successful load
Returns
true on success, false on failure
Definition at line 855 of file ServerDataManager.cpp.
References libcomp::String::Arg().
bool ServerDataManager::TriggerIsAutoContext (const std::shared_ptr< objects::ServerZoneTrigger > & trigger) private
Check if the supplied trigger starts in an auto-only context for actions.
Parameters
trigger Pointer to the trigger definition
Returns
true if the trigger is an auto-only type, false if it is not
Definition at line 2095 of file ServerDataManager.cpp.
bool ServerDataManager::ValidateActions (const std::list< std::shared_ptr< objects::Action >> & actions, const libcomp::String & source, bool autoContext, bool inEvent = false) private
Check for any issues in an action set and report any found in the logs.
Parameters
actions List of actions to validate
source Text descriptor of where the action is from
autoContext If true, player only actions should be handled differently
inEvent Specifies that the actions are a direct subset of an event (ex: EventPerformActions)
Returns
false if any critical errors were encountered
Definition at line 1965 of file ServerDataManager.cpp.
References libcomp::String::Arg().
bool ServerDataManager::VerifyPvPInstance (uint32_t instanceID, DefinitionManager * definitionManager)
Verify if the supplied instance is valid for being a PvP variant.
Parameters
instanceID ID of the instance to check
definitionManager Pointer to the definition manager to use when checking information for the instance zones
Definition at line 313 of file ServerDataManager.cpp.
References libcomp::String::Arg(), libcomp::DefinitionManager::GetZoneData(), and GetZoneInstanceData().
Member Data Documentation
std::unordered_map<uint16_t, std::shared_ptr<objects::AILogicGroup> > libcomp::ServerDataManager::mAILogicGroups private
Map of AI logic groups by definition ID.
Definition at line 555 of file ServerDataManager.h.
Referenced by GetAILogicGroup().
std::unordered_map<std::string, std::shared_ptr<ServerScript> > libcomp::ServerDataManager::mAIScripts private
Map of AI scripts by name.
Definition at line 585 of file ServerDataManager.h.
Referenced by GetAIScript(), LoadScript(), and LoadScripts().
std::list<uint32_t> libcomp::ServerDataManager::mCompShopIDs private
List of all COMP shop definition IDs.
Definition at line 551 of file ServerDataManager.h.
Referenced by GetCompShopIDs().
std::unordered_map<int32_t, std::shared_ptr< objects::DemonFamiliarityType> > libcomp::ServerDataManager::mDemonFamiliarityTypeData private
Map of demon familiarity type entries by definition ID.
Definition at line 559 of file ServerDataManager.h.
Referenced by GetDemonFamiliarityTypeData().
std::unordered_map<uint32_t, std::shared_ptr<objects::DemonPresent> > libcomp::ServerDataManager::mDemonPresentData private
Map of demon present entries by definition ID.
Definition at line 563 of file ServerDataManager.h.
Referenced by GetDemonPresentData().
std::unordered_map<uint32_t, std::shared_ptr<objects::DemonQuestReward> > libcomp::ServerDataManager::mDemonQuestRewardData private
Map of demon quest reward entries by definition ID.
Definition at line 567 of file ServerDataManager.h.
Referenced by GetDemonQuestRewardData().
std::unordered_map<uint32_t, std::shared_ptr<objects::DropSet> > libcomp::ServerDataManager::mDropSetData private
Map of drop sets by definition ID.
Definition at line 571 of file ServerDataManager.h.
Referenced by AppendPendingDrops(), and GetDropSetData().
std::unordered_map<std::string, std::shared_ptr<objects::Event> > libcomp::ServerDataManager::mEventData private
Map of events by definition ID.
Definition at line 544 of file ServerDataManager.h.
Referenced by GetEventData().
std::list<std::pair<uint32_t, uint32_t> > libcomp::ServerDataManager::mFieldZoneIDs private
List of zone ID to dynamic map ID pairs of field zones.
Definition at line 522 of file ServerDataManager.h.
Referenced by GetFieldZoneIDs().
std::unordered_map<uint32_t, uint32_t> libcomp::ServerDataManager::mGiftDropSetLookup private
Map of drop set defintion IDs by gift box ID.
Definition at line 579 of file ServerDataManager.h.
Referenced by GetGiftDropSetData().
std::unordered_map<uint32_t, std::list<std::shared_ptr<objects::ItemDrop> > > libcomp::ServerDataManager::mPendingMergeDrops private
Map of drop set definition IDs to drops loaded from APPEND drop sets.
These are loaded into the actual dropset by
Definition at line 576 of file ServerDataManager.h.
Referenced by AppendPendingDrops().
std::unordered_map<std::string, std::shared_ptr<ServerScript> > libcomp::ServerDataManager::mScripts private
Map of miscellaneous (non-AI) scripts by name.
Definition at line 582 of file ServerDataManager.h.
Referenced by GetScript(), LoadScript(), and LoadScripts().
std::unordered_map<uint32_t, std::shared_ptr<objects::ServerShop> > libcomp::ServerDataManager::mShopData private
Map of shops by definition ID.
Definition at line 548 of file ServerDataManager.h.
Referenced by GetShopData().
std::unordered_map<uint8_t, std::set<uint32_t> > libcomp::ServerDataManager::mStandardPvPVariantIDs private
Definition at line 532 of file ServerDataManager.h.
Referenced by GetStandardPvPVariantIDs().
std::unordered_map<uint32_t, std::unordered_map<uint32_t, std::shared_ptr<objects::ServerZone> > > libcomp::ServerDataManager::mZoneData private
Map of server zone defintions by zone definition and dynamic map ID.
Definition at line 519 of file ServerDataManager.h.
Referenced by GetAllZoneIDs(), and GetZoneData().
std::unordered_map<uint32_t, std::shared_ptr< objects::ServerZoneInstance> > libcomp::ServerDataManager::mZoneInstanceData private
Map of server zone instance defintions by definition ID.
Definition at line 526 of file ServerDataManager.h.
Referenced by GetAllZoneInstanceIDs(), and GetZoneInstanceData().
std::unordered_map<uint32_t, std::shared_ptr< objects::ServerZoneInstanceVariant> > libcomp::ServerDataManager::mZoneInstanceVariantData private
Map of server zone instance variant defintions by definition ID.
Definition at line 530 of file ServerDataManager.h.
Referenced by GetZoneInstanceVariantData().
std::unordered_map<uint32_t, std::shared_ptr< objects::ServerZonePartial> > libcomp::ServerDataManager::mZonePartialData private
Map of server zone partial defintions by definition ID.
Definition at line 536 of file ServerDataManager.h.
Referenced by GetZonePartialData().
std::unordered_map<uint32_t, std::set<uint32_t> > libcomp::ServerDataManager::mZonePartialMap private
Map of auto apply server zone partial defintion IDs mapped to directly on the definition by dynamic map ID.
Definition at line 540 of file ServerDataManager.h.
Referenced by GetZoneData().
The documentation for this class was generated from the following files:
ServerDataManager.h
ServerDataManager.cpp