COMP_hack: libcomp::Randomizer Class Reference
libcomp::Randomizer Class Reference
Static utility class used for improved random number generation.
#include <Randomizer.h>
Public Member Functions
template<>
float GetRandomDecimal (float minVal, float maxVal, uint8_t precision)
template<>
double GetRandomDecimal (double minVal, double maxVal, uint8_t precision)
Static Public Member Functions
template<class T >
static T GetEntry (const std::list< T > &dataset)
Get a random entry from the supplied list.
template<class T >
static T GetEntry (const std::set< T > &dataset)
Get a random entry from the supplied set.
template<class T >
static T GetRandomDecimal (T minVal, T maxVal, uint8_t precision)
Get a random decimal number of the templated type between the minimum and maximum values supplied.
template<class T >
static T GetRandomNumber (T minVal, T maxVal)
Get a random integer number of the templated type between the minimum and maximum values supplied.
template<class T >
static T GetRandomNumber64 (T minVal, T maxVal)
Get a random 64 bit integer number of the templated type between the minimum and maximum values supplied.
Static Private Member Functions
static void SeedRNG ()
Generate the random number seed value for the 32-bit and 64-bit generators if it has not been already.
Static Private Attributes
static thread_local std::mt19937 sGen
Thread specific 32-bit random number generator.
static thread_local std::mt19937_64 sGen64
Thread specific 65-bit random number generator.
Detailed Description
Static utility class used for improved random number generation.
Random number generation is handled on a per thread basis and is thus thread safe.
Definition at line 44 of file Randomizer.h.
Member Function Documentation
template<class T > static T libcomp::Randomizer::GetEntry (const std::list< T > & dataset) inline static
Get a random entry from the supplied list.
Parameters
List of entries to pull a random entry from
Returns
Random entry from the supplied list or the default value for the templated type if empty
Definition at line 99 of file Randomizer.h.
template<class T > static T libcomp::Randomizer::GetEntry (const std::set< T > & dataset) inline static
Get a random entry from the supplied set.
Parameters
Set of entries to pull a random entry from
Returns
Random entry from the supplied set or the default value for the templated type if empty
Definition at line 121 of file Randomizer.h.
template<> float libcomp::Randomizer::GetRandomDecimal (float minVal, float maxVal, uint8_t precision)
Definition at line 82 of file Randomizer.cpp.
template<class T > static T libcomp::Randomizer::GetRandomDecimal (T minVal, T maxVal, uint8_t precision) static
Get a random decimal number of the templated type between the minimum and maximum values supplied.
Parameters
minVal Minimum value that can be generated
maxVal Maximum value that can be generated
precision Number of decimal places to round by
Returns
Random decimal number between the minimum and maximum values
template<> double libcomp::Randomizer::GetRandomDecimal (double minVal, double maxVal, uint8_t precision)
Definition at line 93 of file Randomizer.cpp.
template<class T > static T libcomp::Randomizer::GetRandomNumber (T minVal, T maxVal) inline static
Get a random integer number of the templated type between the minimum and maximum values supplied.
Use GetRandomNumber64 for types uint64_t and int64_t.
Parameters
minVal Minimum value that can be generated
maxVal Maximum value that can be generated
Returns
Random number between the minimum and maximum values
Definition at line 56 of file Randomizer.h.
References SeedRNG(), and sGen.
template<class T > static T libcomp::Randomizer::GetRandomNumber64 (T minVal, T maxVal) inline static
Get a random 64 bit integer number of the templated type between the minimum and maximum values supplied.
Use GetRandomNumber instead for non-64 bit integers as this is significantly less performant.
Parameters
minVal Minimum value that can be generated
maxVal Maximum value that can be generated
Returns
Random number between the minimum and maximum values
Definition at line 73 of file Randomizer.h.
References SeedRNG(), and sGen64.
void Randomizer::SeedRNG () static private
Generate the random number seed value for the 32-bit and 64-bit generators if it has not been already.
Definition at line 62 of file Randomizer.cpp.
References libcomp::String::Data(), libcomp::Crypto::GenerateRandom(), sGen, and sGen64.
Referenced by GetRandomNumber(), and GetRandomNumber64().
Member Data Documentation
thread_local std::mt19937 Randomizer::sGen static private
Thread specific 32-bit random number generator.
Definition at line 144 of file Randomizer.h.
Referenced by GetRandomNumber(), and SeedRNG().
thread_local std::mt19937_64 Randomizer::sGen64 static private
Thread specific 65-bit random number generator.
Definition at line 147 of file Randomizer.h.
Referenced by GetRandomNumber64(), and SeedRNG().
The documentation for this class was generated from the following files:
Randomizer.h
Randomizer.cpp