COMP_hack: libcomp::Packet Class Reference
libcomp::Packet Class Reference
Convenience class to read and write packet data.
#include <Packet.h>
Public Member Functions
Packet ()
Initialize a blank Packet object without any data.
Packet (const Packet &other)
Copy the packet data from another Packet object into this one.
Packet (Packet &&other)
Move the packet data from another Packet object into this one.
Packet (const std::vector< char > &data)
Initialize a Packet object with data.
Packet (const void *pData, uint32_t sz)
Initialize a Packet object with pBuffer of size bytes.
~Packet ()
Destructor to clean-up the object (free the data).
void Allocate ()
Ensure the packet data buffer is allocated.
void Clear ()
Empty the packet.
int32_t Compress (int32_t sz)
Compress from the cursor position sz bytes.
const char * ConstData () const
Return direct access to the underlying packet buffer.
char * Data () const
Return direct access to the underlying packet buffer.
int32_t Decompress (int32_t sz)
Decompress from the cursor position sz bytes.
char * Direct (uint32_t sz)
Return direct access to the underlying packet buffer and set the packet size to sz bytes.
String Dump () const
Generate a string that contains a hex dump of the packet.
void End ()
Set the current position to the end of the packet.
void EraseRight ()
Erase all data after the current position effectively making the packet size equal to the current position.
uint32_t Free () const
Return the number of bytes that may be added to the end of the packet.
void HexDump () const
Produce a hex dump of the packet in the log.
uint32_t Left () const
Return the number of bytes left to be read.
uint32_t Length () const
Returns the number of bytes in the packet.
Packet & operator= (Packet &&other)
Move the packet data from another Packet object into this one.
int16_t PeekS16 ()
Read a 16-bit signed integer in host byte order from the packet but do not advance the current position in the packet.
int16_t PeekS16Big ()
Read a 16-bit signed integer in big endian byte order from the packet but do not advance the current position in the packet.
int16_t PeekS16Little ()
Read a 16-bit signed integer in little endian byte order from the packet but do not advance the current position in the packet.
int32_t PeekS32 ()
Read a 32-bit signed integer in host byte order from the packet but do not advance the current position in the packet.
int32_t PeekS32Big ()
Read a 32-bit signed integer in big endian byte order from the packet but do not advance the current position in the packet.
int32_t PeekS32Little ()
Read a 32-bit signed integer in little endian byte order from the packet but do not advance the current position in the packet.
int8_t PeekS8 ()
Read a 8-bit signed integer from the packet but do not advance the current position in the packet.
uint16_t PeekU16 ()
Read a 16-bit unsigned integer in host byte order from the packet but do not advance the current position in the packet.
uint16_t PeekU16Big ()
Read a 16-bit unsigned integer in big endian byte order from the packet but do not advance the current position in the packet.
uint16_t PeekU16Little ()
Read a 16-bit unsigned integer in little endian byte order from the packet but do not advance the current position in the packet.
uint32_t PeekU32 ()
Read a 32-bit unsigned integer in host byte order from the packet but do not advance the current position in the packet.
uint32_t PeekU32Big ()
Read a 32-bit unsigned integer in big endian byte order from the packet but do not advance the current position in the packet.
uint32_t PeekU32Little ()
Read a 32-bit unsigned integer in little endian byte order from the packet but do not advance the current position in the packet.
uint8_t PeekU8 ()
Read a 8-bit unsigned integer from the packet but do not advance the current position in the packet.
std::vector< char > ReadArray (uint32_t sz)
Read sz bytes of data from the packet.
void ReadArray (void *buffer, uint32_t sz)
Read sz bytes of data from the packet into buffer.
double ReadDouble ()
Write a 64-bit double precision number from the packet and advance the current position in the packet.
float ReadFloat ()
Read a 32-bit floating point number from the packet and advance the current position in the packet.
int16_t ReadS16 ()
Read a 16-bit signed integer in host byte order from the packet and advance the current position in the packet.
int16_t ReadS16Big ()
Read a 16-bit signed integer in big endian byte order from the packet and advance the current position in the packet.
int16_t ReadS16Little ()
Read a 16-bit signed integer in little endian byte order from the packet and advance the current position in the packet.
int32_t ReadS32 ()
Read a 32-bit signed integer in host byte order from the packet and advance the current position in the packet.
int32_t ReadS32Big ()
Read a 32-bit signed integer in big endian byte order from the packet and advance the current position in the packet.
int32_t ReadS32Little ()
Read a 32-bit signed integer in little endian byte order from the packet and advance the current position in the packet.
int64_t ReadS64 ()
Read a 64-bit signed integer in host byte order from the packet and advance the current position in the packet.
int64_t ReadS64Big ()
Read a 64-bit signed integer in big endian byte order from the packet and advance the current position in the packet.
int64_t ReadS64Little ()
Read a 64-bit signed integer in little endian byte order from the packet and advance the current position in the packet.
int8_t ReadS8 ()
Read a 8-bit signed integer from the packet and advance the current position in the packet.
String ReadString (Convert::Encoding_t encoding)
Read the string str encoded with encoding from the packet.
String ReadString16 (Convert::Encoding_t encoding, bool trimNull=false)
Read the string str encoded with encoding from the packet.
String ReadString16Big (Convert::Encoding_t encoding, bool trimNull=false)
Read the string str encoded with encoding from the packet.
String ReadString16Little (Convert::Encoding_t encoding, bool trimNull=false)
Read the string str encoded with encoding from the packet.
String ReadString32 (Convert::Encoding_t encoding, bool trimNull=false)
Read the string str encoded with encoding from the packet.
String ReadString32Big (Convert::Encoding_t encoding, bool trimNull=false)
Read the string str encoded with encoding from the packet.
String ReadString32Little (Convert::Encoding_t encoding, bool trimNull=false)
Read the string str encoded with encoding from the packet.
uint16_t ReadU16 ()
Read a 16-bit unsigned integer in host byte order from the packet and advance the current position in the packet.
uint16_t ReadU16Big ()
Read a 16-bit unsigned integer in big endian byte order from the packet and advance the current position in the packet.
uint16_t ReadU16Little ()
Read a 16-bit unsigned integer in little endian byte order from the packet and advance the current position in the packet.
uint32_t ReadU32 ()
Read a 32-bit unsigned integer in host byte order from the packet and advance the current position in the packet.
uint32_t ReadU32Big ()
Read a 32-bit unsigned integer in big endian byte order from the packet and advance the current position in the packet.
uint32_t ReadU32Little ()
Read a 32-bit unsigned integer in little endian byte order from the packet and advance the current position in the packet.
uint64_t ReadU64 ()
Read a 64-bit unsigned integer in host byte order from the packet and advance the current position in the packet.
uint64_t ReadU64Big ()
Read a 64-bit unsigned integer in big endian byte order from the packet and advance the current position in the packet.
uint64_t ReadU64Little ()
Read a 64-bit unsigned integer in little endian byte order from the packet and advance the current position in the packet.
uint8_t ReadU8 ()
Read a 8-bit unsigned integer from the packet and advance the current position in the packet.
void Rewind ()
Rewind the current position to the beginning of the packet.
void Rewind (uint32_t bytes)
Rewind the current position by bytes.
void Seek (uint32_t pos)
Seek to pos bytes from the beginning of the packet.
uint32_t Size () const
Returns the number of bytes in the packet.
void Skip (uint32_t bytes)
Advance bytes from the current position.
void Split (Packet &other, uint32_t sz)
Write sz bytes of packet data from the current position into the packet other.
uint32_t Tell () const
Return the current position in the packet.
void WriteArray (const std::vector< char > &data)
Copy the desired buffer into the packet.
void WriteArray (const void *pData, uint32_t sz)
Copy the desired buffer into the packet.
void WriteBlank (uint32_t count)
Write count blank bytes of value 0 into the packet.
void WriteDouble (double value)
Write a 64-bit double precision value to the packet.
void WriteFloat (float value)
Write a 32-bit floating point value to the packet.
void WriteGameTicks (uint64_t value)
Write a 32-bit integer value that represents the current game ticks.
template<typename T >
void WritePacketCode (T value)
Write the enumeration value to the packet as an unsigned 16-bit integer in little endian byte order.
void WriteS16 (int16_t value)
Write a signed 16-bit integer value to the packet in host byte order.
void WriteS16Big (int16_t value)
Write a signed 16-bit integer value to the packet in big endian byte order.
void WriteS16Little (int16_t value)
Write a signed 16-bit integer value to the packet in little endian byte order.
void WriteS32 (int32_t value)
Write a signed 32-bit integer value to the packet in host byte order.
void WriteS32Big (int32_t value)
Write a signed 32-bit integer value to the packet in big endian byte order.
void WriteS32Little (int32_t value)
Write a signed 32-bit integer value to the packet in little endian byte order.
void WriteS64 (int64_t value)
Write a signed 64-bit integer value to the packet in host byte order.
void WriteS64Big (int64_t value)
Write a signed 64-bit integer value to the packet in big endian byte order.
void WriteS64Little (int64_t value)
Write a signed 64-bit integer value to the packet in little endian byte order.
void WriteS8 (int8_t value)
Write a signed 8-bit integer value to the packet.
void WriteString (Convert::Encoding_t encoding, const String &str, bool nullTerminate=false)
Write the string str into the packet encoded with encoding.
void WriteString16 (Convert::Encoding_t encoding, const String &str, bool nullTerminate=false)
Write the string str into the packet encoded with encoding.
void WriteString16Big (Convert::Encoding_t encoding, const String &str, bool nullTerminate=false)
Write the string str into the packet encoded with encoding.
void WriteString16Little (Convert::Encoding_t encoding, const String &str, bool nullTerminate=false)
Write the string str into the packet encoded with encoding.
void WriteString32 (Convert::Encoding_t encoding, const String &str, bool nullTerminate=false)
Write the string str into the packet encoded with encoding.
void WriteString32Big (Convert::Encoding_t encoding, const String &str, bool nullTerminate=false)
Write the string str into the packet encoded with encoding.
void WriteString32Little (Convert::Encoding_t encoding, const String &str, bool nullTerminate=false)
Write the string str into the packet encoded with encoding.
void WriteU16 (uint16_t value)
Write an unsigned 16-bit integer value to the packet in host byte order.
void WriteU16Big (uint16_t value)
Write an unsigned 16-bit integer value to the packet in big endian byte order.
void WriteU16Little (uint16_t value)
Write an unsigned 16-bit integer value to the packet in little endian byte order.
void WriteU32 (uint32_t value)
Write an unsigned 32-bit integer value to the packet in host byte order.
void WriteU32Big (uint32_t value)
Write an unsigned 32-bit integer value to the packet in big endian byte order.
void WriteU32Little (uint32_t value)
Write an unsigned 32-bit integer value to the packet in little endian byte order.
void WriteU64 (uint64_t value)
Write an unsigned 64-bit integer value to the packet in host byte order.
void WriteU64Big (uint64_t value)
Write an unsigned 64-bit integer value to the packet in big endian byte order.
void WriteU64Little (uint64_t value)
Write an unsigned 64-bit integer value to the packet in little endian byte order.
void WriteU8 (uint8_t value)
Write an unsigned 8-bit integer value to the packet.
Protected Attributes
uint8_t * mData
Pointer to the packet data.
std::shared_ptr< PacketArray > mDataRef
Reference to the underlying buffer (which could be shared between read only packets).
uint32_t mPosition
Current position in the packet.
uint32_t mSize
Size of the packet.
Private Member Functions
void GrowPacket (uint32_t count)
Add count bytes to the size of the packet.
Friends
class PacketException
This class needs to directly access data in the Packet class.
Detailed Description
Convenience class to read and write packet data.
This class is designed to make it easy to read and write packet data. Strings can be converted between the internal Unicode format and Windows code pages. All integer numbers can be written in host byte order, big endian, or little endian. The packet data is usually read or written in sequantial order but you can use random access as well. Note that data is not inserted into the middle of the packet, it is instead overwritten with the new data. Here is some example code:
Packet p;
p.WriteU16Little(0x1234); // Code for this packet.
p.WriteBlank(4); // Number of items (blank for now).
// Initialize the item count to 0.
int count = 0;
// Loop through and write each item to the packet.
while(HaveItems())
{
    count++;
    p.WriteU32Little(NextItem());
}
// Return to where the item count should be, write the count, and return
// the current position back to the end of the packet.
p.Seek(2);
p.WriteU32Little(count);
p.End();
Definition at line 68 of file Packet.h.
Constructor & Destructor Documentation
Packet::Packet () explicit
Initialize a blank Packet object without any data.
Definition at line 51 of file src/Packet.cpp.
References Clear().
Packet::Packet (const Packet & other) explicit
Copy the packet data from another Packet object into this one.
Parameters
other Packet object to copy the data from.
Definition at line 57 of file src/Packet.cpp.
References libcomp::ReadOnlyPacket::Allocate(), libcomp::ReadOnlyPacket::mData, and libcomp::ReadOnlyPacket::mSize.
Packet::Packet (Packet && other) explicit
Move the packet data from another Packet object into this one.
Parameters
other Packet object to move the data from.
Definition at line 69 of file src/Packet.cpp.
References libcomp::ReadOnlyPacket::mPosition.
Packet::Packet (const std::vector< char > & data) explicit
Initialize a Packet object with data.
Parameters
data Buffer of packet data to initalize the object with.
Definition at line 81 of file src/Packet.cpp.
References libcomp::ReadOnlyPacket::Allocate(), Clear(), libcomp::ReadOnlyPacket::Rewind(), and WriteArray().
Packet::Packet (const void * pData, uint32_t sz) explicit
Initialize a Packet object with pBuffer of size bytes.
Parameters
pData Buffer of packet data to initalize the object with.
sz Number of bytes in the data buffer.
Definition at line 100 of file src/Packet.cpp.
References libcomp::ReadOnlyPacket::Allocate(), Clear(), libcomp::ReadOnlyPacket::Rewind(), and WriteArray().
Packet::~Packet ()
Destructor to clean-up the object (free the data).
Definition at line 119 of file src/Packet.cpp.
Member Function Documentation
void ReadOnlyPacket::Allocate () inherited
Ensure the packet data buffer is allocated.
Definition at line 97 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::mData, and libcomp::ReadOnlyPacket::mDataRef.
Referenced by Clear(), GrowPacket(), Packet(), and libcomp::TcpConnection::RequestPacket().
void Packet::Clear ()
Empty the packet.
This will set the size of the packet to zero and rewind the current position back to the beginning of the packet.
Definition at line 441 of file src/Packet.cpp.
References libcomp::ReadOnlyPacket::Allocate(), libcomp::ReadOnlyPacket::mData, libcomp::ReadOnlyPacket::mPosition, and libcomp::ReadOnlyPacket::mSize.
Referenced by Packet(), libcomp::TcpConnection::PacketReceived(), libcomp::EncryptedConnection::ParseClientEncryptionStart(), libcomp::LobbyConnection::ParseExtensionConnection(), libcomp::EncryptedConnection::ParsePacket(), libcomp::EncryptedConnection::ParseServerEncryptionFinish(), libcomp::EncryptedConnection::ParseServerEncryptionStart(), libcomp::ChannelConnection::PreparePackets(), and Split().
int32_t Packet::Compress (int32_t sz)
Compress from the cursor position sz bytes.
After the compression the current position will remain the same.
Parameters
sz Number of bytes to compress.
Returns
The compressed size or 0 if the compression failed.
Definition at line 569 of file src/Packet.cpp.
References libcomp::Compress::Compress(), libcomp::ReadOnlyPacket::mData, libcomp::ReadOnlyPacket::mPosition, libcomp::ReadOnlyPacket::mSize, and PACKET_EXCEPTION.
Referenced by libcomp::ChannelConnection::PreparePackets().
const char * ReadOnlyPacket::ConstData () const inherited
Return direct access to the underlying packet buffer.
Avoid using this function as modifying or deleting the buffer can cause bugs. With direct access, you must do your own bounds checking. An alternative is to use seek() or rewind() and then call readArray() to copy the data out of the packet.
Returns
Pointer to the packet data.
Definition at line 786 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::mData.
Referenced by libcomp::TcpConnection::FlushOutgoingInside(), libcomp::EncryptedConnection::ParsePacket(), libcomp::ChannelConnection::PreparePackets(), and libcomp::ReadOnlyPacketStream::ReadOnlyPacketStream().
char * Packet::Data () const
Return direct access to the underlying packet buffer.
Avoid using this function as modifying or deleting the buffer can cause bugs. With direct access, you must do your own bounds checking. An alternative is to use seek() or rewind() and then call readArray() to copy the data out of the packet.
Returns
Pointer to the packet data.
Definition at line 468 of file src/Packet.cpp.
References libcomp::ReadOnlyPacket::mData.
Referenced by libcomp::Crypto::Blowfish::DecryptPacket(), libcomp::Crypto::Blowfish::EncryptPacket(), libcomp::PacketStream::PacketStream(), and libcomp::TcpConnection::RequestPacket().
int32_t Packet::Decompress (int32_t sz)
Decompress from the cursor position sz bytes.
After the decompression the current position will remain the same.
Parameters
sz Number of bytes to decompress.
Returns
The uncompressed size or 0 if the decompression failed.
Definition at line 525 of file src/Packet.cpp.
References libcomp::Compress::Decompress(), libcomp::ReadOnlyPacket::mData, libcomp::ReadOnlyPacket::mPosition, libcomp::ReadOnlyPacket::mSize, and PACKET_EXCEPTION.
Referenced by libcomp::ChannelConnection::DecompressPacket().
char * Packet::Direct (uint32_t sz)
Return direct access to the underlying packet buffer and set the packet size to sz bytes.
Avoid using this function as modifying or deleting the buffer can cause bugs. With direct access, you must do your own bounds checking. An alternative is to use Seek() or Rewind() and then call ReadArray() or WriteArray() to copy the data out of or into the packet.
Parameters
sz Number of bytes to set the packet size to.
Returns
Pointer to the packet data.
Definition at line 474 of file src/Packet.cpp.
References libcomp::ReadOnlyPacket::mData, libcomp::ReadOnlyPacket::mPosition, libcomp::ReadOnlyPacket::mSize, and PACKET_EXCEPTION.
String ReadOnlyPacket::Dump () const inherited
Generate a string that contains a hex dump of the packet.
Returns
String that contains the hex dump.
Definition at line 802 of file ReadOnlyPacket.cpp.
References libcomp::String::Arg(), libcomp::String::Join(), libcomp::ReadOnlyPacket::mData, libcomp::ReadOnlyPacket::mPosition, and libcomp::ReadOnlyPacket::mSize.
Referenced by libcomp::ReadOnlyPacket::HexDump().
void ReadOnlyPacket::End () inherited
Set the current position to the end of the packet.
This will set Tell() equal to Size().
Definition at line 750 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::mPosition, and libcomp::ReadOnlyPacket::mSize.
Referenced by libcomp::Crypto::Blowfish::EncryptPacket().
void Packet::EraseRight ()
Erase all data after the current position effectively making the packet size equal to the current position.
Definition at line 461 of file src/Packet.cpp.
References libcomp::ReadOnlyPacket::mPosition, and libcomp::ReadOnlyPacket::mSize.
uint32_t ReadOnlyPacket::Free () const inherited
Return the number of bytes that may be added to the end of the packet.
Returns
Number of bytes that may be added to the end of the packet.
Definition at line 769 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::mSize.
Referenced by libcomp::PacketStream::overflow().
void Packet::GrowPacket (uint32_t count) private
Add count bytes to the size of the packet.
If this exceeds the maximum size of the packet, a PacketException will be thrown.
Parameters
count Number of bytes to add to the packet.
Definition at line 123 of file src/Packet.cpp.
References libcomp::ReadOnlyPacket::Allocate(), libcomp::ReadOnlyPacket::mPosition, libcomp::ReadOnlyPacket::mSize, and PACKET_EXCEPTION.
Referenced by WriteArray(), WriteBlank(), WriteDouble(), WriteFloat(), WriteS16(), WriteS32(), WriteS64(), WriteS8(), WriteU16(), WriteU32(), WriteU64(), and WriteU8().
void ReadOnlyPacket::HexDump () const inherited
Produce a hex dump of the packet in the log.
Definition at line 792 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::Dump().
Referenced by libcomp::ScriptEngine::Using().
uint32_t ReadOnlyPacket::Left () const inherited
Return the number of bytes left to be read.
This is the number of bytes between the current position and the size of the packet.
Returns
Number of bytes left in the packet.
Definition at line 762 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::mPosition, and libcomp::ReadOnlyPacket::mSize.
Referenced by libcomp::ChannelConnection::DecompressPacket(), libcomp::TcpConnection::FlushOutgoingInside(), libcomp::PacketStream::overflow(), libcomp::EncryptedConnection::ParseClientEncryptionStart(), libcomp::LobbyConnection::ParseExtensionConnection(), libcomp::EncryptedConnection::ParsePacket(), libcomp::EncryptedConnection::ParseServerEncryptionFinish(), libcomp::EncryptedConnection::ParseServerEncryptionStart(), libcomp::ReadOnlyPacket::ReadString(), and libcomp::DataSyncManager::SyncIncoming().
uint32_t ReadOnlyPacket::Length () const inherited
Returns the number of bytes in the packet.
Returns
Number of bytes in the packet.
Definition at line 780 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::mSize.
Packet & Packet::operator= (Packet && other)
Move the packet data from another Packet object into this one.
Parameters
other Packet object to move the data from.
Definition at line 613 of file src/Packet.cpp.
References libcomp::ReadOnlyPacket::mData, libcomp::ReadOnlyPacket::mDataRef, libcomp::ReadOnlyPacket::mPosition, and libcomp::ReadOnlyPacket::mSize.
int16_t ReadOnlyPacket::PeekS16 () inherited
Read a 16-bit signed integer in host byte order from the packet but do not advance the current position in the packet.
Useful for determining a length (e.g. of a string) or version of the packet before actually doing read code.
Returns
Value at the current position in the packet.
See Also
ReadS16
PeekS16Big
PeekS16Little
Definition at line 389 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::mData, libcomp::ReadOnlyPacket::mPosition, libcomp::ReadOnlyPacket::mSize, and PACKET_EXCEPTION.
Referenced by libcomp::ReadOnlyPacket::PeekS16Big(), and libcomp::ReadOnlyPacket::PeekS16Little().
int16_t ReadOnlyPacket::PeekS16Big () inherited
Read a 16-bit signed integer in big endian byte order from the packet but do not advance the current position in the packet.
Useful for determining a length (e.g. of a string) or version of the packet before actually doing read code.
Returns
Value at the current position in the packet.
See Also
ReadS16
PeekS16
PeekS16Little
Definition at line 412 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::PeekS16().
int16_t ReadOnlyPacket::PeekS16Little () inherited
Read a 16-bit signed integer in little endian byte order from the packet but do not advance the current position in the packet.
Useful for determining a length (e.g. of a string) or version of the packet before actually doing read code.
Returns
Value at the current position in the packet.
See Also
ReadS16
PeekS16
PeekS16Big
Definition at line 424 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::PeekS16().
int32_t ReadOnlyPacket::PeekS32 () inherited
Read a 32-bit signed integer in host byte order from the packet but do not advance the current position in the packet.
Useful for determining a length (e.g. of a string) or version of the packet before actually doing read code.
Returns
Value at the current position in the packet.
See Also
ReadS32
PeekS32Big
PeekS32Little
Definition at line 447 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::mData, libcomp::ReadOnlyPacket::mPosition, libcomp::ReadOnlyPacket::mSize, and PACKET_EXCEPTION.
Referenced by libcomp::ReadOnlyPacket::PeekS32Big(), and libcomp::ReadOnlyPacket::PeekS32Little().
int32_t ReadOnlyPacket::PeekS32Big () inherited
Read a 32-bit signed integer in big endian byte order from the packet but do not advance the current position in the packet.
Useful for determining a length (e.g. of a string) or version of the packet before actually doing read code.
Returns
Value at the current position in the packet.
See Also
ReadS32
PeekS32
PeekS32Little
Definition at line 470 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::PeekS32().
int32_t ReadOnlyPacket::PeekS32Little () inherited
Read a 32-bit signed integer in little endian byte order from the packet but do not advance the current position in the packet.
Useful for determining a length (e.g. of a string) or version of the packet before actually doing read code.
Returns
Value at the current position in the packet.
See Also
ReadS32
PeekS32
PeekS32Big
Definition at line 482 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::PeekS32().
int8_t ReadOnlyPacket::PeekS8 () inherited
Read a 8-bit signed integer from the packet but do not advance the current position in the packet.
Useful for determining a length (e.g. of a string) or version of the packet before actually doing read code.
Returns
Value at the current position in the packet.
See Also
ReadS8
Definition at line 355 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::mData, libcomp::ReadOnlyPacket::mPosition, libcomp::ReadOnlyPacket::mSize, and PACKET_EXCEPTION.
uint16_t ReadOnlyPacket::PeekU16 () inherited
Read a 16-bit unsigned integer in host byte order from the packet but do not advance the current position in the packet.
Useful for determining a length (e.g. of a string) or version of the packet before actually doing read code.
Returns
Value at the current position in the packet.
See Also
ReadU16
PeekU16Big
PeekU16Little
Definition at line 372 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::mData, libcomp::ReadOnlyPacket::mPosition, libcomp::ReadOnlyPacket::mSize, and PACKET_EXCEPTION.
Referenced by libcomp::ReadOnlyPacket::PeekU16Big(), and libcomp::ReadOnlyPacket::PeekU16Little().
uint16_t ReadOnlyPacket::PeekU16Big () inherited
Read a 16-bit unsigned integer in big endian byte order from the packet but do not advance the current position in the packet.
Useful for determining a length (e.g. of a string) or version of the packet before actually doing read code.
Returns
Value at the current position in the packet.
See Also
ReadU16
PeekU16
PeekU16Little
Definition at line 406 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::PeekU16().
uint16_t ReadOnlyPacket::PeekU16Little () inherited
Read a 16-bit unsigned integer in little endian byte order from the packet but do not advance the current position in the packet.
Useful for determining a length (e.g. of a string) or version of the packet before actually doing read code.
Returns
Value at the current position in the packet.
See Also
ReadU16
PeekU16
PeekU16Big
Definition at line 418 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::PeekU16().
uint32_t ReadOnlyPacket::PeekU32 () inherited
Read a 32-bit unsigned integer in host byte order from the packet but do not advance the current position in the packet.
Useful for determining a length (e.g. of a string) or version of the packet before actually doing read code.
Returns
Value at the current position in the packet.
See Also
ReadU32
PeekU32Big
PeekU32Little
Definition at line 430 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::mData, libcomp::ReadOnlyPacket::mPosition, libcomp::ReadOnlyPacket::mSize, and PACKET_EXCEPTION.
Referenced by libcomp::ReadOnlyPacket::PeekU32Big(), and libcomp::ReadOnlyPacket::PeekU32Little().
uint32_t ReadOnlyPacket::PeekU32Big () inherited
Read a 32-bit unsigned integer in big endian byte order from the packet but do not advance the current position in the packet.
Useful for determining a length (e.g. of a string) or version of the packet before actually doing read code.
Returns
Value at the current position in the packet.
See Also
ReadU32
PeekU32
PeekU32Little
Definition at line 464 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::PeekU32().
Referenced by libcomp::EncryptedConnection::ParseClientEncryptionStart(), and libcomp::EncryptedConnection::ParseServerEncryptionFinish().
uint32_t ReadOnlyPacket::PeekU32Little () inherited
Read a 32-bit unsigned integer in little endian byte order from the packet but do not advance the current position in the packet.
Useful for determining a length (e.g. of a string) or version of the packet before actually doing read code.
Returns
Value at the current position in the packet.
See Also
ReadU32
PeekU32
PeekU32Big
Definition at line 476 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::PeekU32().
uint8_t ReadOnlyPacket::PeekU8 () inherited
Read a 8-bit unsigned integer from the packet but do not advance the current position in the packet.
Useful for determining a length (e.g. of a string) or version of the packet before actually doing read code.
Returns
Value at the current position in the packet.
See Also
ReadU8
Definition at line 338 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::mData, libcomp::ReadOnlyPacket::mPosition, libcomp::ReadOnlyPacket::mSize, and PACKET_EXCEPTION.
std::vector< char > ReadOnlyPacket::ReadArray (uint32_t sz) inherited
Read sz bytes of data from the packet.
After reading the data, the current position in the packet will advance by sz bytes.
Parameters
sz Number of bytes to read from the packet into the buffer.
Returns
Buffer the data was read into.
Definition at line 165 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::mData, libcomp::ReadOnlyPacket::mPosition, libcomp::ReadOnlyPacket::mSize, PACKET_EXCEPTION, and libcomp::ReadOnlyPacket::Skip().
Referenced by libcomp::ReadOnlyPacket::ReadString(), libcomp::ReadOnlyPacket::ReadString16(), libcomp::ReadOnlyPacket::ReadString16Big(), libcomp::ReadOnlyPacket::ReadString16Little(), libcomp::ReadOnlyPacket::ReadString32(), libcomp::ReadOnlyPacket::ReadString32Big(), libcomp::ReadOnlyPacket::ReadString32Little(), Split(), TEST(), and libcomp::ScriptEngine::Using().
void ReadOnlyPacket::ReadArray (void * buffer, uint32_t sz) inherited
Read sz bytes of data from the packet into buffer.
After reading the data, the current position in the packet will advance by sz bytes.
Parameters
buffer Buffer to store the data that was read from the packet.
sz Number of bytes to read from the packet into the buffer.
Definition at line 193 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::mData, libcomp::ReadOnlyPacket::mPosition, libcomp::ReadOnlyPacket::mSize, PACKET_EXCEPTION, and libcomp::ReadOnlyPacket::Skip().
double ReadOnlyPacket::ReadDouble () inherited
Write a 64-bit double precision number from the packet and advance the current position in the packet.
Returns
Value at the current position in the packet.
See Also
WriteDouble
Definition at line 731 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::mData, libcomp::ReadOnlyPacket::mPosition, libcomp::ReadOnlyPacket::mSize, PACKET_EXCEPTION, and libcomp::ReadOnlyPacket::Skip().
float ReadOnlyPacket::ReadFloat () inherited
Read a 32-bit floating point number from the packet and advance the current position in the packet.
Returns
Value at the current position in the packet.
See Also
WriteFloat
Definition at line 712 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::mData, libcomp::ReadOnlyPacket::mPosition, libcomp::ReadOnlyPacket::mSize, PACKET_EXCEPTION, and libcomp::ReadOnlyPacket::Skip().
int16_t ReadOnlyPacket::ReadS16 () inherited
Read a 16-bit signed integer in host byte order from the packet and advance the current position in the packet.
Returns
Value at the current position in the packet.
See Also
WriteS16
ReadS16Big
ReadS16Little
Definition at line 557 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::mData, libcomp::ReadOnlyPacket::mPosition, libcomp::ReadOnlyPacket::mSize, PACKET_EXCEPTION, and libcomp::ReadOnlyPacket::Skip().
Referenced by libcomp::ReadOnlyPacket::ReadS16Big(), and libcomp::ReadOnlyPacket::ReadS16Little().
int16_t ReadOnlyPacket::ReadS16Big () inherited
Read a 16-bit signed integer in big endian byte order from the packet and advance the current position in the packet.
Returns
Value at the current position in the packet.
See Also
WriteS16Big
ReadS16
ReadS16Little
Definition at line 576 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::ReadS16().
int16_t ReadOnlyPacket::ReadS16Little () inherited
Read a 16-bit signed integer in little endian byte order from the packet and advance the current position in the packet.
Returns
Value at the current position in the packet.
See Also
WriteS16Little
ReadS16
ReadS16Big
Definition at line 582 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::ReadS16().
int32_t ReadOnlyPacket::ReadS32 () inherited
Read a 32-bit signed integer in host byte order from the packet and advance the current position in the packet.
Returns
Value at the current position in the packet.
See Also
WriteS32
ReadS32Big
ReadS32Little
Definition at line 619 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::mData, libcomp::ReadOnlyPacket::mPosition, libcomp::ReadOnlyPacket::mSize, PACKET_EXCEPTION, and libcomp::ReadOnlyPacket::Skip().
Referenced by libcomp::ReadOnlyPacket::ReadS32Big(), and libcomp::ReadOnlyPacket::ReadS32Little().
int32_t ReadOnlyPacket::ReadS32Big () inherited
Read a 32-bit signed integer in big endian byte order from the packet and advance the current position in the packet.
Returns
Value at the current position in the packet.
See Also
WriteS32Big
ReadS32
ReadS32Little
Definition at line 638 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::ReadS32().
int32_t ReadOnlyPacket::ReadS32Little () inherited
Read a 32-bit signed integer in little endian byte order from the packet and advance the current position in the packet.
Returns
Value at the current position in the packet.
See Also
WriteS32Little
ReadS32
ReadS32Big
Definition at line 644 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::ReadS32().
Referenced by libcomp::ChannelConnection::DecompressPacket().
int64_t ReadOnlyPacket::ReadS64 () inherited
Read a 64-bit signed integer in host byte order from the packet and advance the current position in the packet.
Returns
Value at the current position in the packet.
See Also
WriteS64
ReadS64Big
ReadS64Little
Definition at line 681 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::mData, libcomp::ReadOnlyPacket::mPosition, libcomp::ReadOnlyPacket::mSize, PACKET_EXCEPTION, and libcomp::ReadOnlyPacket::Skip().
Referenced by libcomp::ReadOnlyPacket::ReadS64Big(), and libcomp::ReadOnlyPacket::ReadS64Little().
int64_t ReadOnlyPacket::ReadS64Big () inherited
Read a 64-bit signed integer in big endian byte order from the packet and advance the current position in the packet.
Returns
Value at the current position in the packet.
See Also
WriteS64Big
ReadS64
ReadS64Little
Definition at line 700 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::ReadS64().
int64_t ReadOnlyPacket::ReadS64Little () inherited
Read a 64-bit signed integer in little endian byte order from the packet and advance the current position in the packet.
Returns
Value at the current position in the packet.
See Also
WriteS64Little
ReadS64
ReadS64Big
Definition at line 706 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::ReadS64().
int8_t ReadOnlyPacket::ReadS8 () inherited
Read a 8-bit signed integer from the packet and advance the current position in the packet.
Returns
Value at the current position in the packet.
See Also
PeekS8
WriteS8
Definition at line 507 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::mData, libcomp::ReadOnlyPacket::mPosition, libcomp::ReadOnlyPacket::mSize, PACKET_EXCEPTION, and libcomp::ReadOnlyPacket::Skip().
String ReadOnlyPacket::ReadString (Convert::Encoding_t encoding) inherited
Read the string str encoded with encoding from the packet.
The string should contain a null terminator.
Parameters
encoding String encoding used. Can be one of:
ENCODING_UTF8 (Unicode)
ENCODING_CP932 (Japanese)
ENCODING_CP1252 (US English)
Returns
The string that was read.
See Also
WriteString
ReadString16
ReadString32
Definition at line 216 of file ReadOnlyPacket.cpp.
References libcomp::Convert::FromEncoding(), libcomp::ReadOnlyPacket::Left(), libcomp::ReadOnlyPacket::ReadArray(), libcomp::ReadOnlyPacket::ReadU8(), and libcomp::ReadOnlyPacket::Rewind().
String ReadOnlyPacket::ReadString16 (Convert::Encoding_t encoding, bool trimNull = false) inherited
Read the string str encoded with encoding from the packet.
The size of the string is determined by a 16-bit unsigned integer in host byte order that is read first. This size includes any null terminator.
Parameters
encoding String encoding used. Can be one of:
ENCODING_UTF8 (Unicode)
ENCODING_CP932 (Japanese)
ENCODING_CP1252 (US English)
trimNull When true the null terminator will be removed
Returns
The string that was read.
See Also
WriteString16
ReadString16Big
ReadString16Little
Definition at line 236 of file ReadOnlyPacket.cpp.
References libcomp::Convert::FromEncoding(), libcomp::ReadOnlyPacket::ReadArray(), and libcomp::ReadOnlyPacket::ReadU16().
String ReadOnlyPacket::ReadString16Big (Convert::Encoding_t encoding, bool trimNull = false) inherited
Read the string str encoded with encoding from the packet.
The size of the string is determined by a 16-bit unsigned integer in big endian byte order that is read first. This size includes any null terminator.
Parameters
encoding String encoding used. Can be one of:
ENCODING_UTF8 (Unicode)
ENCODING_CP932 (Japanese)
ENCODING_CP1252 (US English)
trimNull When true the null terminator will be removed
Returns
The string that was read.
See Also
WriteString16
ReadString16
ReadString16Little
Definition at line 253 of file ReadOnlyPacket.cpp.
References libcomp::Convert::FromEncoding(), libcomp::ReadOnlyPacket::ReadArray(), and libcomp::ReadOnlyPacket::ReadU16Big().
String ReadOnlyPacket::ReadString16Little (Convert::Encoding_t encoding, bool trimNull = false) inherited
Read the string str encoded with encoding from the packet.
The size of the string is determined by a 16-bit unsigned integer in little endian byte order that is read first. This size includes any null terminator.
Parameters
encoding String encoding used. Can be one of:
ENCODING_UTF8 (Unicode)
ENCODING_CP932 (Japanese)
ENCODING_CP1252 (US English)
trimNull When true the null terminator will be removed
Returns
The string that was read.
See Also
WriteString16
ReadString16
ReadString16Big
Definition at line 270 of file ReadOnlyPacket.cpp.
References libcomp::Convert::FromEncoding(), libcomp::ReadOnlyPacket::ReadArray(), and libcomp::ReadOnlyPacket::ReadU16Little().
Referenced by libcomp::DataSyncManager::SyncIncoming().
String ReadOnlyPacket::ReadString32 (Convert::Encoding_t encoding, bool trimNull = false) inherited
Read the string str encoded with encoding from the packet.
The size of the string is determined by a 32-bit unsigned integer in host byte order that is read first. This size includes any null terminator.
Parameters
encoding String encoding used. Can be one of:
ENCODING_UTF8 (Unicode)
ENCODING_CP932 (Japanese)
ENCODING_CP1252 (US English)
trimNull When true the null terminator will be removed
Returns
The string that was read.
See Also
WriteString32
ReadString32Big
ReadString32Little
Definition at line 287 of file ReadOnlyPacket.cpp.
References libcomp::Convert::FromEncoding(), libcomp::ReadOnlyPacket::ReadArray(), and libcomp::ReadOnlyPacket::ReadU32().
String ReadOnlyPacket::ReadString32Big (Convert::Encoding_t encoding, bool trimNull = false) inherited
Read the string str encoded with encoding from the packet.
The size of the string is determined by a 32-bit unsigned integer in big endian byte order that is read first. This size includes any null terminator.
Parameters
encoding String encoding used. Can be one of:
ENCODING_UTF8 (Unicode)
ENCODING_CP932 (Japanese)
ENCODING_CP1252 (US English)
trimNull When true the null terminator will be removed
Returns
The string that was read.
See Also
WriteString32
ReadString32
ReadString32Little
Definition at line 304 of file ReadOnlyPacket.cpp.
References libcomp::Convert::FromEncoding(), libcomp::ReadOnlyPacket::ReadArray(), and libcomp::ReadOnlyPacket::ReadU32Big().
Referenced by libcomp::EncryptedConnection::ParseClientEncryptionStart(), and libcomp::EncryptedConnection::ParseServerEncryptionFinish().
String ReadOnlyPacket::ReadString32Little (Convert::Encoding_t encoding, bool trimNull = false) inherited
Read the string str encoded with encoding from the packet.
The size of the string is determined by a 32-bit unsigned integer in little endian byte order that is read first. This size includes any null terminator.
Parameters
encoding String encoding used. Can be one of:
ENCODING_UTF8 (Unicode)
ENCODING_CP932 (Japanese)
ENCODING_CP1252 (US English)
trimNull When true the null terminator will be removed
Returns
The string that was read.
See Also
WriteString32
ReadString32
ReadString32Big
Definition at line 321 of file ReadOnlyPacket.cpp.
References libcomp::Convert::FromEncoding(), libcomp::ReadOnlyPacket::ReadArray(), and libcomp::ReadOnlyPacket::ReadU32Little().
uint16_t ReadOnlyPacket::ReadU16 () inherited
Read a 16-bit unsigned integer in host byte order from the packet and advance the current position in the packet.
Returns
Value at the current position in the packet.
See Also
PeekU16
WriteU16
ReadU16Big
ReadU16Little
Definition at line 526 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::mData, libcomp::ReadOnlyPacket::mPosition, libcomp::ReadOnlyPacket::mSize, PACKET_EXCEPTION, and libcomp::ReadOnlyPacket::Skip().
Referenced by libcomp::ReadOnlyPacket::ReadString16(), libcomp::ReadOnlyPacket::ReadU16Big(), and libcomp::ReadOnlyPacket::ReadU16Little().
uint16_t ReadOnlyPacket::ReadU16Big () inherited
Read a 16-bit unsigned integer in big endian byte order from the packet and advance the current position in the packet.
Returns
Value at the current position in the packet.
See Also
PeekU16Big
WriteU16Big
ReadU16
ReadU16Little
Definition at line 545 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::ReadU16().
Referenced by libcomp::ReadOnlyPacket::ReadString16Big().
uint16_t ReadOnlyPacket::ReadU16Little () inherited
Read a 16-bit unsigned integer in little endian byte order from the packet and advance the current position in the packet.
Returns
Value at the current position in the packet.
See Also
PeekU16Little
WriteU16Little
ReadU16
ReadU16Big
Definition at line 551 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::ReadU16().
Referenced by libcomp::EncryptedConnection::ParsePacket(), libcomp::ReadOnlyPacket::ReadString16Little(), and libcomp::DataSyncManager::SyncIncoming().
uint32_t ReadOnlyPacket::ReadU32 () inherited
Read a 32-bit unsigned integer in host byte order from the packet and advance the current position in the packet.
Returns
Value at the current position in the packet.
See Also
PeekU32
WriteU32
ReadU32Big
ReadU32Little
Definition at line 588 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::mData, libcomp::ReadOnlyPacket::mPosition, libcomp::ReadOnlyPacket::mSize, PACKET_EXCEPTION, and libcomp::ReadOnlyPacket::Skip().
Referenced by libcomp::ReadOnlyPacket::ReadString32(), libcomp::ReadOnlyPacket::ReadU32Big(), and libcomp::ReadOnlyPacket::ReadU32Little().
uint32_t ReadOnlyPacket::ReadU32Big () inherited
Read a 32-bit unsigned integer in big endian byte order from the packet and advance the current position in the packet.
Returns
Value at the current position in the packet.
See Also
PeekU32Big
WriteU32Big
ReadU32
ReadU32Little
Definition at line 607 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::ReadU32().
Referenced by libcomp::ChannelConnection::DecompressPacket(), libcomp::Crypto::Blowfish::DecryptPacket(), libcomp::EncryptedConnection::ParseClientEncryptionStart(), libcomp::LobbyConnection::ParseExtensionConnection(), libcomp::EncryptedConnection::ParsePacket(), libcomp::EncryptedConnection::ParseServerEncryptionStart(), and libcomp::ReadOnlyPacket::ReadString32Big().
uint32_t ReadOnlyPacket::ReadU32Little () inherited
Read a 32-bit unsigned integer in little endian byte order from the packet and advance the current position in the packet.
Returns
Value at the current position in the packet.
See Also
PeekU32Little
WriteU32Little
ReadU32
ReadU32Big
Definition at line 613 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::ReadU32().
Referenced by libcomp::ReadOnlyPacket::ReadString32Little().
uint64_t ReadOnlyPacket::ReadU64 () inherited
Read a 64-bit unsigned integer in host byte order from the packet and advance the current position in the packet.
Returns
Value at the current position in the packet.
See Also
WriteU64
ReadU64Big
ReadU64Little
Definition at line 650 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::mData, libcomp::ReadOnlyPacket::mPosition, libcomp::ReadOnlyPacket::mSize, PACKET_EXCEPTION, and libcomp::ReadOnlyPacket::Skip().
Referenced by libcomp::ReadOnlyPacket::ReadU64Big(), and libcomp::ReadOnlyPacket::ReadU64Little().
uint64_t ReadOnlyPacket::ReadU64Big () inherited
Read a 64-bit unsigned integer in big endian byte order from the packet and advance the current position in the packet.
Returns
Value at the current position in the packet.
See Also
WriteU64Big
ReadU64
ReadU64Little
Definition at line 669 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::ReadU64().
uint64_t ReadOnlyPacket::ReadU64Little () inherited
Read a 64-bit unsigned integer in little endian byte order from the packet and advance the current position in the packet.
Returns
Value at the current position in the packet.
See Also
WriteU64Little
ReadU64
ReadU64Big
Definition at line 675 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::ReadU64().
uint8_t ReadOnlyPacket::ReadU8 () inherited
Read a 8-bit unsigned integer from the packet and advance the current position in the packet.
Returns
Value at the current position in the packet.
See Also
PeekU8
WriteU8
Definition at line 488 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::mData, libcomp::ReadOnlyPacket::mPosition, libcomp::ReadOnlyPacket::mSize, PACKET_EXCEPTION, and libcomp::ReadOnlyPacket::Skip().
Referenced by libcomp::ReadOnlyPacket::ReadString().
void ReadOnlyPacket::Rewind () inherited
Rewind the current position to the beginning of the packet.
Definition at line 139 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::mPosition.
Referenced by libcomp::Crypto::Blowfish::DecryptPacket(), libcomp::Crypto::Blowfish::EncryptPacket(), libcomp::TcpConnection::FlushOutgoing(), Packet(), libcomp::EncryptedConnection::ParseServerEncryptionStart(), libcomp::ChannelConnection::PreparePackets(), libcomp::ManagerPacket::ProcessMessage(), libcomp::ReadOnlyPacket::ReadString(), Split(), TEST(), and libcomp::ScriptEngine::Using().
void ReadOnlyPacket::Rewind (uint32_t bytes) inherited
Rewind the current position by bytes.
The range of this method should be from 0 bytes to Tell() bytes. If the value is outside of this range, a PacketException will be thrown.
Parameters
bytes Number of bytes to rewind the current position.
Definition at line 145 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::mPosition, and PACKET_EXCEPTION.
void ReadOnlyPacket::Seek (uint32_t pos) inherited
Seek to pos bytes from the beginning of the packet.
The position specified must be within the range of the data in the packet; otherwise, a PacketException will be thrown. The valid range is 0 bytes to Size() bytes (inclusive).
Parameters
pos Number of bytes from the start of the packet data.
Definition at line 107 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::mPosition, and PACKET_EXCEPTION.
Referenced by libcomp::ChannelConnection::DecompressPacket(), libcomp::Crypto::Blowfish::EncryptPacket(), libcomp::EncryptedConnection::ParsePacket(), and libcomp::ChannelConnection::PreparePackets().
uint32_t ReadOnlyPacket::Size () const inherited
Returns the number of bytes in the packet.
Returns
Number of bytes in the packet.
Definition at line 774 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::mSize.
Referenced by libcomp::Crypto::Blowfish::DecryptPacket(), libcomp::Crypto::Blowfish::EncryptPacket(), libcomp::EncryptedConnection::GetCombinedPackets(), libcomp::PacketStream::PacketStream(), libcomp::EncryptedConnection::ParseClientEncryptionStart(), libcomp::EncryptedConnection::ParsePacket(), libcomp::EncryptedConnection::ParseServerEncryptionFinish(), libcomp::EncryptedConnection::ParseServerEncryptionStart(), libcomp::ChannelConnection::PreparePackets(), libcomp::ReadOnlyPacketStream::ReadOnlyPacketStream(), libcomp::TcpConnection::RequestPacket(), TEST(), and libcomp::ScriptEngine::Using().
void ReadOnlyPacket::Skip (uint32_t bytes) inherited
Advance bytes from the current position.
This is essentially a seek from the current position instead of the beginning of the packet. The valid range of this method is from 0 bytes to Left() bytes (inclusive). If the value is outside this range, a PacketException will be thrown.
Parameters
bytes Number of bytes to advance the current position.
Definition at line 119 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::mPosition, and PACKET_EXCEPTION.
Referenced by libcomp::Object::LoadPacket(), libcomp::EncryptedConnection::ParsePacket(), libcomp::ReadOnlyPacket::ReadArray(), libcomp::ReadOnlyPacket::ReadDouble(), libcomp::ReadOnlyPacket::ReadFloat(), libcomp::ReadOnlyPacket::ReadS16(), libcomp::ReadOnlyPacket::ReadS32(), libcomp::ReadOnlyPacket::ReadS64(), libcomp::ReadOnlyPacket::ReadS8(), libcomp::ReadOnlyPacket::ReadU16(), libcomp::ReadOnlyPacket::ReadU32(), libcomp::ReadOnlyPacket::ReadU64(), libcomp::ReadOnlyPacket::ReadU8(), WriteArray(), WriteBlank(), WriteDouble(), WriteFloat(), WriteS16(), WriteS32(), WriteS64(), WriteS8(), WriteU16(), WriteU32(), WriteU64(), and WriteU8().
void Packet::Split (Packet & other, uint32_t sz)
Write sz bytes of packet data from the current position into the packet other.
If the number of bytes is less than left(), a PacketException will be thrown. If the other packet can't write sz bytes, a PacketException will be thrown. The other packet will be cleared and the current position will be reset to the beginning of the packet.
Parameters
other Packet to write the data into.
sz Number of bytes to copy into the other packet.
Definition at line 500 of file src/Packet.cpp.
References Clear(), libcomp::ReadOnlyPacket::mData, libcomp::ReadOnlyPacket::mPosition, libcomp::ReadOnlyPacket::mSize, PACKET_EXCEPTION, libcomp::ReadOnlyPacket::ReadArray(), and libcomp::ReadOnlyPacket::Rewind().
uint32_t ReadOnlyPacket::Tell () const inherited
Return the current position in the packet.
Returns
Current position in the packet.
Definition at line 756 of file ReadOnlyPacket.cpp.
References libcomp::ReadOnlyPacket::mPosition.
Referenced by libcomp::TcpConnection::FlushOutgoingInside(), libcomp::PacketStream::PacketStream(), libcomp::EncryptedConnection::ParsePacket(), libcomp::ReadOnlyPacketStream::ReadOnlyPacketStream(), and TEST().
void Packet::WriteArray (const std::vector< char > & data)
Copy the desired buffer into the packet.
Parameters
data Data to write into the packet.
Definition at line 174 of file src/Packet.cpp.
References GrowPacket(), libcomp::ReadOnlyPacket::mData, libcomp::ReadOnlyPacket::mPosition, and libcomp::ReadOnlyPacket::Skip().
Referenced by Packet(), libcomp::PacketException::PacketException(), libcomp::ChannelConnection::PreparePackets(), libcomp::EncryptedConnection::PreparePackets(), TEST(), libcomp::ScriptEngine::Using(), WriteString(), WriteString16(), WriteString16Big(), WriteString16Little(), WriteString32(), WriteString32Big(), and WriteString32Little().
void Packet::WriteArray (const void * pData, uint32_t sz)
Copy the desired buffer into the packet.
Parameters
pData Data to write into the packet.
sz Size (in bytes) of the data to write.
Definition at line 190 of file src/Packet.cpp.
References GrowPacket(), libcomp::ReadOnlyPacket::mData, libcomp::ReadOnlyPacket::mPosition, and libcomp::ReadOnlyPacket::Skip().
void Packet::WriteBlank (uint32_t count)
Write count blank bytes of value 0 into the packet.
Parameters
count Number of blank bytes to write.
Definition at line 159 of file src/Packet.cpp.
References GrowPacket(), libcomp::ReadOnlyPacket::mData, libcomp::ReadOnlyPacket::mPosition, and libcomp::ReadOnlyPacket::Skip().
Referenced by libcomp::Crypto::Blowfish::EncryptPacket(), libcomp::EncryptedConnection::ParseServerEncryptionStart(), libcomp::ChannelConnection::PreparePackets(), libcomp::EncryptedConnection::PreparePackets(), and libcomp::ScriptEngine::Using().
void Packet::WriteDouble (double value)
Write a 64-bit double precision value to the packet.
Parameters
value 64-bit double precision value to write.
Definition at line 432 of file src/Packet.cpp.
References GrowPacket(), libcomp::ReadOnlyPacket::mData, libcomp::ReadOnlyPacket::mPosition, and libcomp::ReadOnlyPacket::Skip().
void Packet::WriteFloat (float value)
Write a 32-bit floating point value to the packet.
Parameters
value 32-bit floating point value to write.
Definition at line 423 of file src/Packet.cpp.
References GrowPacket(), libcomp::ReadOnlyPacket::mData, libcomp::ReadOnlyPacket::mPosition, and libcomp::ReadOnlyPacket::Skip().
void libcomp::Packet::WriteGameTicks (uint64_t value)
Write a 32-bit integer value that represents the current game ticks.
This is a packet extension that calls Server::InternalToGameTicks() to convert the internal time of the server to the on-the-wire time format the client expects. You can call this method by hand and pass the value to WriteU32Little instead; this method is for convenience. Since this method requires access to Server class, this extension only works from within the channel server project.
Parameters
value 32-bit floating point value to write.
value Internal server time to convert and write into the packet.
template<typename T > void libcomp::Packet::WritePacketCode (T value) inline
Write the enumeration value to the packet as an unsigned 16-bit integer in little endian byte order.
Parameters
Enumeration to write into the packet.
See Also
WriteU16Little
Definition at line 459 of file Packet.h.
References WriteU16Little().
Referenced by libcomp::DataSyncManager::QueueOutgoing(), and libcomp::DataSyncManager::WriteOutgoingRecord().
void Packet::WriteS16 (int16_t value)
Write a signed 16-bit integer value to the packet in host byte order.
Parameters
value 16-bit signed integer to write.
See Also
WriteS16Big
WriteS16Little
Definition at line 318 of file src/Packet.cpp.
References GrowPacket(), libcomp::ReadOnlyPacket::mData, libcomp::ReadOnlyPacket::mPosition, and libcomp::ReadOnlyPacket::Skip().
Referenced by WriteS16Big(), and WriteS16Little().
void Packet::WriteS16Big (int16_t value)
Write a signed 16-bit integer value to the packet in big endian byte order.
Parameters
value 16-bit signed integer to write.
See Also
WriteS16
WriteS16Little
Definition at line 327 of file src/Packet.cpp.
References WriteS16().
void Packet::WriteS16Little (int16_t value)
Write a signed 16-bit integer value to the packet in little endian byte order.
Parameters
value 16-bit signed integer to write.
See Also
WriteS16
WriteS16Big
Definition at line 333 of file src/Packet.cpp.
References WriteS16().
void Packet::WriteS32 (int32_t value)
Write a signed 32-bit integer value to the packet in host byte order.
Parameters
value 32-bit signed integer to write.
See Also
WriteS32Big
WriteS32Little
Definition at line 360 of file src/Packet.cpp.
References GrowPacket(), libcomp::ReadOnlyPacket::mData, libcomp::ReadOnlyPacket::mPosition, and libcomp::ReadOnlyPacket::Skip().
Referenced by WriteS32Big(), and WriteS32Little().
void Packet::WriteS32Big (int32_t value)
Write a signed 32-bit integer value to the packet in big endian byte order.
Parameters
value 32-bit signed integer to write.
See Also
WriteS32
WriteS32Little
Definition at line 369 of file src/Packet.cpp.
References WriteS32().
void Packet::WriteS32Little (int32_t value)
Write a signed 32-bit integer value to the packet in little endian byte order.
Parameters
value 32-bit signed integer to write.
See Also
WriteS32
WriteS32Big
Definition at line 375 of file src/Packet.cpp.
References WriteS32().
Referenced by libcomp::ChannelConnection::PreparePackets().
void Packet::WriteS64 (int64_t value)
Write a signed 64-bit integer value to the packet in host byte order.
Parameters
value 64-bit signed integer to write.
See Also
WriteS64Big
WriteS64Little
Definition at line 402 of file src/Packet.cpp.
References GrowPacket(), libcomp::ReadOnlyPacket::mData, libcomp::ReadOnlyPacket::mPosition, and libcomp::ReadOnlyPacket::Skip().
Referenced by WriteS64Big(), and WriteS64Little().
void Packet::WriteS64Big (int64_t value)
Write a signed 64-bit integer value to the packet in big endian byte order.
Parameters
value 64-bit signed integer to write.
See Also
WriteS64
WriteS64Little
Definition at line 411 of file src/Packet.cpp.
References WriteS64().
void Packet::WriteS64Little (int64_t value)
Write a signed 64-bit integer value to the packet in little endian byte order.
Parameters
value 64-bit signed integer to write.
See Also
WriteS64
WriteS64Big
Definition at line 417 of file src/Packet.cpp.
References WriteS64().
void Packet::WriteS8 (int8_t value)
Write a signed 8-bit integer value to the packet.
Parameters
value 8-bit signed integer to write.
Definition at line 288 of file src/Packet.cpp.
References GrowPacket(), libcomp::ReadOnlyPacket::mData, libcomp::ReadOnlyPacket::mPosition, and libcomp::ReadOnlyPacket::Skip().
Referenced by libcomp::PacketStream::overflow().
void Packet::WriteString (Convert::Encoding_t encoding, const String & str, bool nullTerminate = false)
Write the string str into the packet encoded with encoding.
There is no size written before the string so using this function without a null terminator only makes sense if the string is of fixed size.
Parameters
encoding String encoding to use. Can be one of:
ENCODING_UTF8 (Unicode)
ENCODING_CP932 (Japanese)
ENCODING_CP1252 (US English)
str String to write into the packet.
nullTerminate If true, the string will end with a null terminator; otherwise, the string will not contain a null byte at the end.
See Also
ReadString
WriteString16
WriteString32
Definition at line 206 of file src/Packet.cpp.
References libcomp::Convert::ToEncoding(), and WriteArray().
void Packet::WriteString16 (Convert::Encoding_t encoding, const String & str, bool nullTerminate = false)
Write the string str into the packet encoded with encoding.
A 16-bit unsigned integer (host byte order) is written before the string to indicate the size of the string (including any null terminator).
Parameters
encoding String encoding to use. Can be one of:
ENCODING_UTF8 (Unicode)
ENCODING_CP932 (Japanese)
ENCODING_CP1252 (US English)
str String to write into the packet.
nullTerminate If true, the string will end with a null terminator; otherwise, the string will not contain a null byte at the end.
See Also
WriteString
WriteString16Big
WriteString16Little
Definition at line 246 of file src/Packet.cpp.
References libcomp::Convert::ToEncoding(), WriteArray(), and WriteU16().
void Packet::WriteString16Big (Convert::Encoding_t encoding, const String & str, bool nullTerminate = false)
Write the string str into the packet encoded with encoding.
A 16-bit unsigned integer (big endian byte order) is written before the string to indicate the size of the string (including any null terminator).
Parameters
encoding String encoding to use. Can be one of:
ENCODING_UTF8 (Unicode)
ENCODING_CP932 (Japanese)
ENCODING_CP1252 (US English)
str String to write into the packet.
nullTerminate If true, the string will end with a null terminator; otherwise, the string will not contain a null byte at the end.
See Also
WriteString
WriteString16
WriteString16Little
Definition at line 257 of file src/Packet.cpp.
References libcomp::Convert::ToEncoding(), WriteArray(), and WriteU16Big().
void Packet::WriteString16Little (Convert::Encoding_t encoding, const String & str, bool nullTerminate = false)
Write the string str into the packet encoded with encoding.
A 16-bit unsigned integer (little endian byte order) is written before the string to indicate the size of the string (including any null terminator).
Parameters
encoding String encoding to use. Can be one of:
ENCODING_UTF8 (Unicode)
ENCODING_CP932 (Japanese)
ENCODING_CP1252 (US English)
str String to write into the packet.
nullTerminate If true, the string will end with a null terminator; otherwise, the string will not contain a null byte at the end.
See Also
WriteString
WriteString16
WriteString16Big
Definition at line 268 of file src/Packet.cpp.
References libcomp::Convert::ToEncoding(), WriteArray(), and WriteU16Little().
Referenced by libcomp::DataSyncManager::QueueOutgoing(), libcomp::DataSyncManager::WriteOutgoingRecord(), and libcomp::DataSyncManager::WriteOutgoingRecords().
void Packet::WriteString32 (Convert::Encoding_t encoding, const String & str, bool nullTerminate = false)
Write the string str into the packet encoded with encoding.
A 32-bit unsigned integer (host byte order) is written before the string to indicate the size of the string (including any null terminator).
Parameters
encoding String encoding to use. Can be one of:
ENCODING_UTF8 (Unicode)
ENCODING_CP932 (Japanese)
ENCODING_CP1252 (US English)
str String to write into the packet.
nullTerminate If true, the string will end with a null terminator; otherwise, the string will not contain a null byte at the end.
See Also
WriteString
WriteString32Big
WriteString32Little
Definition at line 213 of file src/Packet.cpp.
References libcomp::Convert::ToEncoding(), WriteArray(), and WriteU32().
void Packet::WriteString32Big (Convert::Encoding_t encoding, const String & str, bool nullTerminate = false)
Write the string str into the packet encoded with encoding.
A 32-bit unsigned integer (big endian byte order) is written before the string to indicate the size of the string (including any null terminator).
Parameters
encoding String encoding to use. Can be one of:
ENCODING_UTF8 (Unicode)
ENCODING_CP932 (Japanese)
ENCODING_CP1252 (US English)
str String to write into the packet.
nullTerminate If true, the string will end with a null terminator; otherwise, the string will not contain a null byte at the end.
See Also
WriteString
WriteString32
WriteString32Little
Definition at line 224 of file src/Packet.cpp.
References libcomp::Convert::ToEncoding(), WriteArray(), and WriteU32Big().
Referenced by libcomp::EncryptedConnection::ParseClientEncryptionStart(), and libcomp::EncryptedConnection::ParseServerEncryptionStart().
void Packet::WriteString32Little (Convert::Encoding_t encoding, const String & str, bool nullTerminate = false)
Write the string str into the packet encoded with encoding.
A 32-bit unsigned integer (little endian byte order) is written before the string to indicate the size of the string (including any null terminator).
Parameters
encoding String encoding to use. Can be one of:
ENCODING_UTF8 (Unicode)
ENCODING_CP932 (Japanese)
ENCODING_CP1252 (US English)
str String to write into the packet.
nullTerminate If true, the string will end with a null terminator; otherwise, the string will not contain a null byte at the end.
See Also
WriteString
WriteString32
WriteString32Big
Definition at line 235 of file src/Packet.cpp.
References libcomp::Convert::ToEncoding(), WriteArray(), and WriteU32Little().
void Packet::WriteU16 (uint16_t value)
Write an unsigned 16-bit integer value to the packet in host byte order.
Parameters
value 16-bit unsigned integer to write.
See Also
WriteU16Big
WriteU16Little
Definition at line 297 of file src/Packet.cpp.
References GrowPacket(), libcomp::ReadOnlyPacket::mData, libcomp::ReadOnlyPacket::mPosition, and libcomp::ReadOnlyPacket::Skip().
Referenced by WriteString16(), WriteU16Big(), and WriteU16Little().
void Packet::WriteU16Big (uint16_t value)
Write an unsigned 16-bit integer value to the packet in big endian byte order.
Parameters
value 16-bit unsigned integer to write.
See Also
WriteU16
WriteU16Little
Definition at line 306 of file src/Packet.cpp.
References WriteU16().
Referenced by libcomp::ChannelConnection::PreparePackets(), libcomp::EncryptedConnection::PreparePackets(), and WriteString16Big().
void Packet::WriteU16Little (uint16_t value)
Write an unsigned 16-bit integer value to the packet in little endian byte order.
Parameters
value 16-bit unsigned integer to write.
See Also
WriteU16
WriteU16Big
Definition at line 312 of file src/Packet.cpp.
References WriteU16().
Referenced by libcomp::ChannelConnection::PreparePackets(), libcomp::EncryptedConnection::PreparePackets(), libcomp::ScriptEngine::Using(), libcomp::DataSyncManager::WriteOutgoingRecord(), libcomp::DataSyncManager::WriteOutgoingRecords(), WritePacketCode(), and WriteString16Little().
void Packet::WriteU32 (uint32_t value)
Write an unsigned 32-bit integer value to the packet in host byte order.
Parameters
value 32-bit unsigned integer to write.
See Also
WriteU32Big
WriteU32Little
Definition at line 339 of file src/Packet.cpp.
References GrowPacket(), libcomp::ReadOnlyPacket::mData, libcomp::ReadOnlyPacket::mPosition, and libcomp::ReadOnlyPacket::Skip().
Referenced by WriteString32(), WriteU32Big(), and WriteU32Little().
void Packet::WriteU32Big (uint32_t value)
Write an unsigned 32-bit integer value to the packet in big endian byte order.
Parameters
value 32-bit unsigned integer to write.
See Also
WriteU32
WriteU32Little
Definition at line 348 of file src/Packet.cpp.
References WriteU32().
Referenced by libcomp::EncryptedConnection::ConnectionSuccess(), libcomp::Crypto::Blowfish::EncryptPacket(), libcomp::LobbyConnection::ParseExtensionConnection(), and WriteString32Big().
void Packet::WriteU32Little (uint32_t value)
Write an unsigned 32-bit integer value to the packet in little endian byte order.
Parameters
value 32-bit unsigned integer to write.
See Also
WriteU32
WriteU32Big
Definition at line 354 of file src/Packet.cpp.
References WriteU32().
Referenced by WriteString32Little().
void Packet::WriteU64 (uint64_t value)
Write an unsigned 64-bit integer value to the packet in host byte order.
Parameters
value 64-bit unsigned integer to write.
See Also
WriteU64Big
WriteU64Little
Definition at line 381 of file src/Packet.cpp.
References GrowPacket(), libcomp::ReadOnlyPacket::mData, libcomp::ReadOnlyPacket::mPosition, and libcomp::ReadOnlyPacket::Skip().
Referenced by WriteU64Big(), and WriteU64Little().
void Packet::WriteU64Big (uint64_t value)
Write an unsigned 64-bit integer value to the packet in big endian byte order.
Parameters
value 64-bit unsigned integer to write.
See Also
WriteU64
WriteU64Little
Definition at line 390 of file src/Packet.cpp.
References WriteU64().
void Packet::WriteU64Little (uint64_t value)
Write an unsigned 64-bit integer value to the packet in little endian byte order.
Parameters
value 64-bit unsigned integer to write.
See Also
WriteU64
WriteU64Big
Definition at line 396 of file src/Packet.cpp.
References WriteU64().
void Packet::WriteU8 (uint8_t value)
Write an unsigned 8-bit integer value to the packet.
Parameters
value 8-bit unsigned integer to write.
Definition at line 279 of file src/Packet.cpp.
References GrowPacket(), libcomp::ReadOnlyPacket::mData, libcomp::ReadOnlyPacket::mPosition, and libcomp::ReadOnlyPacket::Skip().
Friends And Related Function Documentation
friend class PacketException friend
This class needs to directly access data in the Packet class.
Definition at line 72 of file Packet.h.
Member Data Documentation
uint8_t* libcomp::ReadOnlyPacket::mData protected inherited
Pointer to the packet data.
Definition at line 762 of file ReadOnlyPacket.h.
Referenced by libcomp::ReadOnlyPacket::Allocate(), Clear(), Compress(), libcomp::ReadOnlyPacket::ConstData(), Data(), Decompress(), Direct(), libcomp::ReadOnlyPacket::Dump(), operator=(), libcomp::ReadOnlyPacket::operator=(), Packet(), libcomp::PacketException::PacketException(), libcomp::ReadOnlyPacket::PeekS16(), libcomp::ReadOnlyPacket::PeekS32(), libcomp::ReadOnlyPacket::PeekS8(), libcomp::ReadOnlyPacket::PeekU16(), libcomp::ReadOnlyPacket::PeekU32(), libcomp::ReadOnlyPacket::PeekU8(), libcomp::ReadOnlyPacket::ReadArray(), libcomp::ReadOnlyPacket::ReadDouble(), libcomp::ReadOnlyPacket::ReadFloat(), libcomp::ReadOnlyPacket::ReadS16(), libcomp::ReadOnlyPacket::ReadS32(), libcomp::ReadOnlyPacket::ReadS64(), libcomp::ReadOnlyPacket::ReadS8(), libcomp::ReadOnlyPacket::ReadU16(), libcomp::ReadOnlyPacket::ReadU32(), libcomp::ReadOnlyPacket::ReadU64(), libcomp::ReadOnlyPacket::ReadU8(), Split(), WriteArray(), WriteBlank(), WriteDouble(), WriteFloat(), WriteS16(), WriteS32(), WriteS64(), WriteS8(), WriteU16(), WriteU32(), WriteU64(), and WriteU8().
std::shared_ptr<PacketArray> libcomp::ReadOnlyPacket::mDataRef protected inherited
Reference to the underlying buffer (which could be shared between read only packets).
Definition at line 766 of file ReadOnlyPacket.h.
Referenced by libcomp::ReadOnlyPacket::Allocate(), operator=(), and libcomp::ReadOnlyPacket::operator=().
uint32_t libcomp::ReadOnlyPacket::mPosition protected inherited
Current position in the packet.
Definition at line 756 of file ReadOnlyPacket.h.
Referenced by Clear(), Compress(), Decompress(), Direct(), libcomp::ReadOnlyPacket::Dump(), libcomp::ReadOnlyPacket::End(), EraseRight(), GrowPacket(), libcomp::ReadOnlyPacket::Left(), operator=(), libcomp::ReadOnlyPacket::operator=(), Packet(), libcomp::PacketException::PacketException(), libcomp::ReadOnlyPacket::PeekS16(), libcomp::ReadOnlyPacket::PeekS32(), libcomp::ReadOnlyPacket::PeekS8(), libcomp::ReadOnlyPacket::PeekU16(), libcomp::ReadOnlyPacket::PeekU32(), libcomp::ReadOnlyPacket::PeekU8(), libcomp::ReadOnlyPacket::ReadArray(), libcomp::ReadOnlyPacket::ReadDouble(), libcomp::ReadOnlyPacket::ReadFloat(), libcomp::ReadOnlyPacket::ReadS16(), libcomp::ReadOnlyPacket::ReadS32(), libcomp::ReadOnlyPacket::ReadS64(), libcomp::ReadOnlyPacket::ReadS8(), libcomp::ReadOnlyPacket::ReadU16(), libcomp::ReadOnlyPacket::ReadU32(), libcomp::ReadOnlyPacket::ReadU64(), libcomp::ReadOnlyPacket::ReadU8(), libcomp::ReadOnlyPacket::Rewind(), libcomp::ReadOnlyPacket::Seek(), libcomp::ReadOnlyPacket::Skip(), Split(), libcomp::ReadOnlyPacket::Tell(), WriteArray(), WriteBlank(), WriteDouble(), WriteFloat(), WriteS16(), WriteS32(), WriteS64(), WriteS8(), WriteU16(), WriteU32(), WriteU64(), and WriteU8().
uint32_t libcomp::ReadOnlyPacket::mSize protected inherited
Size of the packet.
Definition at line 759 of file ReadOnlyPacket.h.
Referenced by Clear(), Compress(), Decompress(), Direct(), libcomp::ReadOnlyPacket::Dump(), libcomp::ReadOnlyPacket::End(), EraseRight(), libcomp::ReadOnlyPacket::Free(), GrowPacket(), libcomp::ReadOnlyPacket::Left(), libcomp::ReadOnlyPacket::Length(), operator=(), libcomp::ReadOnlyPacket::operator=(), Packet(), libcomp::PacketException::PacketException(), libcomp::ReadOnlyPacket::PeekS16(), libcomp::ReadOnlyPacket::PeekS32(), libcomp::ReadOnlyPacket::PeekS8(), libcomp::ReadOnlyPacket::PeekU16(), libcomp::ReadOnlyPacket::PeekU32(), libcomp::ReadOnlyPacket::PeekU8(), libcomp::ReadOnlyPacket::ReadArray(), libcomp::ReadOnlyPacket::ReadDouble(), libcomp::ReadOnlyPacket::ReadFloat(), libcomp::ReadOnlyPacket::ReadOnlyPacket(), libcomp::ReadOnlyPacket::ReadS16(), libcomp::ReadOnlyPacket::ReadS32(), libcomp::ReadOnlyPacket::ReadS64(), libcomp::ReadOnlyPacket::ReadS8(), libcomp::ReadOnlyPacket::ReadU16(), libcomp::ReadOnlyPacket::ReadU32(), libcomp::ReadOnlyPacket::ReadU64(), libcomp::ReadOnlyPacket::ReadU8(), libcomp::ReadOnlyPacket::Size(), and Split().
The documentation for this class was generated from the following files:
Packet.h
src/Packet.cpp