COMP_hack: libcomp::DBStandardChangeSet Class Reference
libcomp::DBStandardChangeSet Class Reference
Standard database change set consisting of inserts, updates or deletes which will be processed in that order, NOT the order they were added in.
#include <DatabaseChangeSet.h>
Public Member Functions
DBStandardChangeSet ()
Create a new standard database change set.
DBStandardChangeSet (const libobjgen::UUID &uuid)
Create a new standard database change set.
virtual ~DBStandardChangeSet ()
Clean up the database change set.
virtual void Delete (const std::shared_ptr< PersistentObject > &obj)
Add an object for deletion to the change set.
std::list< std::shared_ptr
< PersistentObject > > GetDeletes () const
Get the change set deletes.
std::list< std::shared_ptr
< PersistentObject > > GetInserts () const
Get the change set inserts.
const libobjgen::UUID GetTransactionUUID () const
Get the transaction UUID.
std::list< std::shared_ptr
< PersistentObject > > GetUpdates () const
Get the change set updates.
virtual void Insert (const std::shared_ptr< PersistentObject > &obj)
Add an object for insertion to the change set.
virtual void Update (const std::shared_ptr< PersistentObject > &obj)
Add an object for update to the change set.
Static Public Member Functions
static std::shared_ptr
< DatabaseChangeSet > Create (const libobjgen::UUID &uuid=NULLUUID)
Static builder for a new standard DatabaseChangeSet pointer.
Private Attributes
std::list< std::shared_ptr
< PersistentObject > > mDeletes
Deletes associated to the change set.
std::list< std::shared_ptr
< PersistentObject > > mInserts
Inserts associated to the change set.
std::list< std::shared_ptr
< PersistentObject > > mUpdates
Updates associated to the change set.
Detailed Description
Standard database change set consisting of inserts, updates or deletes which will be processed in that order, NOT the order they were added in.
Here is some normal usecase example code:
// Using objects::Item instances "item1", "item2" and "item3" and database
// instance "db"
// Create a standard change set using the static create function
// This is equivalent to:
// auto changeset = std::make_shared<libcomp::DBStandardChangeSet>();
auto changeset = libcomp::DatabaseChangeSet::Create();
// Mark new object item1 as an insert
changeset->Insert(item1);
// Mark existing object item2 as an update
changeset->Update(item2);
// Mark existing object item3 as a delete
changeset->Delete(item3);
// Process all 3 at once as an all or nothing operation. It doesn't
// matter in this instance what order they are processed in as they
// do not have fields referencing one another but the order would be
// item1 inserted, item2 updated, item3 deleted
db.ProcessChangeSet(changeset);
Definition at line 137 of file DatabaseChangeSet.h.
Constructor & Destructor Documentation
DBStandardChangeSet::DBStandardChangeSet ()
Create a new standard database change set.
Definition at line 61 of file DatabaseChangeSet.cpp.
DBStandardChangeSet::DBStandardChangeSet (const libobjgen::UUID & uuid)
Create a new standard database change set.
Parameters
uuid UUID of the grouped transaction changes
Definition at line 65 of file DatabaseChangeSet.cpp.
DBStandardChangeSet::~DBStandardChangeSet () virtual
Clean up the database change set.
Definition at line 70 of file DatabaseChangeSet.cpp.
Member Function Documentation
std::shared_ptr< DatabaseChangeSet > DatabaseChangeSet::Create (const libobjgen::UUID & uuid = NULLUUID) static inherited
Static builder for a new standard DatabaseChangeSet pointer.
Parameters
uuid Optional UUID associated to the transaction
Returns
Pointer to a new DatabaseChangeSet
Definition at line 50 of file DatabaseChangeSet.cpp.
Referenced by libcomp::Database::QueueDelete(), libcomp::Database::QueueInsert(), libcomp::Database::QueueUpdate(), and TEST().
void DBStandardChangeSet::Delete (const std::shared_ptr< PersistentObject > & obj) virtual
Add an object for deletion to the change set.
Parameters
obj Pointer to the object to delete
Implements libcomp::DatabaseChangeSet.
Definition at line 92 of file DatabaseChangeSet.cpp.
References mDeletes.
std::list< std::shared_ptr< PersistentObject > > DBStandardChangeSet::GetDeletes () const
Get the change set deletes.
Returns
Deletes associated to the change set
Definition at line 111 of file DatabaseChangeSet.cpp.
References mDeletes.
std::list< std::shared_ptr< PersistentObject > > DBStandardChangeSet::GetInserts () const
Get the change set inserts.
Returns
Inserts associated to the change set
Definition at line 101 of file DatabaseChangeSet.cpp.
References mInserts.
const libobjgen::UUID DatabaseChangeSet::GetTransactionUUID () const inherited
Get the transaction UUID.
Returns
UUID associated to the transaction
Definition at line 56 of file DatabaseChangeSet.cpp.
References libcomp::DatabaseChangeSet::mTransactionUUID.
std::list< std::shared_ptr< PersistentObject > > DBStandardChangeSet::GetUpdates () const
Get the change set updates.
Returns
Updates associated to the change set
Definition at line 106 of file DatabaseChangeSet.cpp.
References mUpdates.
void DBStandardChangeSet::Insert (const std::shared_ptr< PersistentObject > & obj) virtual
Add an object for insertion to the change set.
Parameters
obj Pointer to the object to insert
Implements libcomp::DatabaseChangeSet.
Definition at line 74 of file DatabaseChangeSet.cpp.
References mInserts.
void DBStandardChangeSet::Update (const std::shared_ptr< PersistentObject > & obj) virtual
Add an object for update to the change set.
Parameters
obj Pointer to the object to update
Implements libcomp::DatabaseChangeSet.
Definition at line 83 of file DatabaseChangeSet.cpp.
References mUpdates.
Member Data Documentation
std::list<std::shared_ptr<PersistentObject> > libcomp::DBStandardChangeSet::mDeletes private
Deletes associated to the change set.
Definition at line 186 of file DatabaseChangeSet.h.
Referenced by Delete(), and GetDeletes().
std::list<std::shared_ptr<PersistentObject> > libcomp::DBStandardChangeSet::mInserts private
Inserts associated to the change set.
Definition at line 180 of file DatabaseChangeSet.h.
Referenced by GetInserts(), and Insert().
std::list<std::shared_ptr<PersistentObject> > libcomp::DBStandardChangeSet::mUpdates private
Updates associated to the change set.
Definition at line 183 of file DatabaseChangeSet.h.
Referenced by GetUpdates(), and Update().
The documentation for this class was generated from the following files:
DatabaseChangeSet.h
DatabaseChangeSet.cpp