COMP_hack: libcomp::TcpConnection Class Reference
libcomp::TcpConnection Class Reference
Class to manage a TCP/IP connection.
#include <TcpConnection.h>
Public Types
enum ConnectionStatus_t {
STATUS_NOT_CONNECTED = 0, STATUS_CONNECTING, STATUS_CONNECTED, STATUS_WAITING_ENCRYPTION,
STATUS_ENCRYPTED
}
Status of the connection.
enum Role_t { ROLE_SERVER = 0, ROLE_CLIENT }
Role the server is operating in.
Public Member Functions
TcpConnection (asio::io_service &io_service)
Create a new client connection.
TcpConnection (asio::ip::tcp::socket &socket, const std::shared_ptr< Crypto::DiffieHellman > &diffieHellman)
Create a new server connection.
virtual ~TcpConnection ()
Cleanup the connection object.
virtual bool Close ()
Close the connection to the remote host.
bool Connect (const String &host, uint16_t port=0, bool async=true)
Connect to the remote host (client role).
virtual void ConnectionSuccess ()
Called when a connection has been established.
void FlushOutgoing (bool closeConnection=false)
Send all queued packets to the remote host.
String GetName () const
Get the debug name for the connection.
String GetRemoteAddress () const
Get the address of the remote host.
Role_t GetRole () const
Get the role the connection is operating in.
ConnectionStatus_t GetStatus () const
Get the status of the connection.
virtual bool QueueObject (const Object &obj)
Queue an object to be packetized and sent.
virtual void QueuePacket (Packet &packet)
Queue a packet to be sent.
virtual void QueuePacket (ReadOnlyPacket &packet)
Queue a packet to be sent.
virtual void QueuePacketCopy (libcomp::Packet &packet)
Queue a copy of a packet to be sent.
bool RequestPacket (size_t size)
Start a receive request for more packet data.
virtual bool SendObject (const Object &obj, bool closeConnection=false)
Packetize and queue an object and then send all queued packets to the remote host.
virtual void SendPacket (Packet &packet, bool closeConnection=false)
Queue a packet and then send all queued packets to the remote host.
virtual void SendPacket (ReadOnlyPacket &packet, bool closeConnection=false)
Queue a packet and then send all queued packets to the remote host.
virtual void SendPacketCopy (libcomp::Packet &packet, bool closeConnection=false)
Queue a copy of a packet and then send all queued packets to the remote host.
void SetName (const String &name)
Set the debug name for the connection.
Static Public Member Functions
static void BroadcastPacket (const std::list< std::shared_ptr< TcpConnection >> &connections, Packet &packet)
Send a packet to a list of connections.
static void BroadcastPacket (const std::list< std::shared_ptr< TcpConnection >> &connections, ReadOnlyPacket &packet)
Send a packet to a list of connections.
static String GenerateDiffieHellmanPublic (const std::shared_ptr< Crypto::DiffieHellman > &diffieHellman)
Generate the public key for the Diffie-Hellman key exchange.
static std::vector< char > GenerateDiffieHellmanSharedData (const std::shared_ptr< Crypto::DiffieHellman > &diffieHellman, const String &otherPublic)
Return the shared private from the Diffie-Hellman key exchange.
static String GetDiffieHellmanPrime (const std::shared_ptr< Crypto::DiffieHellman > &diffieHellman)
Get the prime used in the Diffie-Hellman key exchange.
Protected Member Functions
virtual void Connect (const asio::ip::tcp::endpoint &endpoint, bool async=true)
Internal connect function to an ASIO end point.
virtual void ConnectionFailed ()
Called if a connection attempt has failed.
virtual std::list< ReadOnlyPacket > GetCombinedPackets ()
Returns a list of packets that have been combined.
virtual void PacketReceived (Packet &packet)
Called after a packet has been received from the remote host.
virtual void PacketSent (ReadOnlyPacket &packet)
Called after a packet has been sent to the remote host.
virtual void PreparePackets (std::list< ReadOnlyPacket > &packets)
Called to prepare packets before they are sent to the remote host.
void SetEncryptionKey (const std::vector< char > &data)
Sets the Blowfish encryption key to be used.
void SetEncryptionKey (const void *pData, size_t dataSize)
Sets the Blowfish encryption key to be used.
virtual void SocketError (const String &errorMessage=String())
Report a socket error.
Protected Attributes
std::shared_ptr
< Crypto::DiffieHellman > mDiffieHellman
Diffie-Hellman key exchange data.
Crypto::Blowfish mEncryptionKey
Blowfish encryption key.
ReadOnlyPacket mOutgoing
Packet being sent to the remote host.
std::mutex mOutgoingMutex
Mutex to ensure the outgoing packet code is executed from one thread.
std::list< ReadOnlyPacket > mOutgoingPackets
List of packets to be sent to the remote host.
bool mSendingPacket
Indicates if an outgoing packet is being sent.
ConnectionStatus_t mStatus
Status of the connection.
Private Member Functions
void FlushOutgoingInside (bool closeConnection=false)
Send all queued packets to the remote host.
void HandleConnection (asio::error_code errorCode)
Used to handle a connection error code.
void SendNextPacket ()
Sends the next packet in the queue to the remote device.
Private Attributes
String mName
Debug name for the connection.
Packet mReceivedPacket
Last received packet.
String mRemoteAddress
Cached address of the remote host.
Role_t mRole
Role of the connection.
asio::ip::tcp::socket mSocket
ASIO network socket for the connection.
Detailed Description
Class to manage a TCP/IP connection.
This class can operate in two roles: ROLE_SERVER and ROLE_Client. The role is only used by derived classes like EncryptedConnection.
Definition at line 53 of file TcpConnection.h.
Member Enumeration Documentation
enum libcomp::TcpConnection::ConnectionStatus_t
Status of the connection.
Enumerator
STATUS_NOT_CONNECTED
Not connected to remote system.
STATUS_CONNECTING
Connecting to a remote system.
STATUS_CONNECTED
Connected to a remote system.
STATUS_WAITING_ENCRYPTION
Waiting for encryption to complete.
STATUS_ENCRYPTED
Connection is established and encrypted.
Definition at line 68 of file TcpConnection.h.
enum libcomp::TcpConnection::Role_t
Role the server is operating in.
Enumerator
ROLE_SERVER
Server role that can accept connections.
ROLE_CLIENT
Client role that will connect to a remote server.
Definition at line 59 of file TcpConnection.h.
Constructor & Destructor Documentation
TcpConnection::TcpConnection (asio::io_service & io_service)
Create a new client connection.
Parameters
io_service ASIO service to manage this connection.
Definition at line 39 of file TcpConnection.cpp.
TcpConnection::TcpConnection (asio::ip::tcp::socket & socket, const std::shared_ptr< Crypto::DiffieHellman > & diffieHellman)
Create a new server connection.
Parameters
socket Socket provided by the server for the new client.
diffieHellman Asymmetric encryption information.
Definition at line 46 of file TcpConnection.cpp.
References mRemoteAddress, and mSocket.
TcpConnection::~TcpConnection () virtual
Cleanup the connection object.
Definition at line 63 of file TcpConnection.cpp.
References libcomp::String::Arg(), and GetName().
Member Function Documentation
void TcpConnection::BroadcastPacket (const std::list< std::shared_ptr< TcpConnection >> & connections, Packet & packet) static
Send a packet to a list of connections.
Parameters
connections List of connections to send the packet to.
packet Packet to send to the list of connections.
Definition at line 493 of file TcpConnection.cpp.
void TcpConnection::BroadcastPacket (const std::list< std::shared_ptr< TcpConnection >> & connections, ReadOnlyPacket & packet) static
Send a packet to a list of connections.
Parameters
connections List of connections to send the packet to.
packet Packet to send to the list of connections.
Definition at line 501 of file TcpConnection.cpp.
bool TcpConnection::Close () virtual
Close the connection to the remote host.
Returns
true on success; false otherwise.
Reimplemented in libcomp::EncryptedConnection.
Definition at line 95 of file TcpConnection.cpp.
References libcomp::String::Arg(), GetName(), mSocket, mStatus, and STATUS_NOT_CONNECTED.
Referenced by libcomp::EncryptedConnection::Close(), and SocketError().
bool TcpConnection::Connect (const String & host, uint16_t port = 0, bool async = true)
Connect to the remote host (client role).
Parameters
host IP or DNS name of the remote host.
port Port of the remote host to connect to.
async If the connection should be asynchronous.
Returns
true on success; false otherwise.
Definition at line 71 of file TcpConnection.cpp.
References libcomp::String::Arg(), mSocket, and libcomp::String::ToUtf8().
void TcpConnection::Connect (const asio::ip::tcp::endpoint & endpoint, bool async = true) protected virtual
Internal connect function to an ASIO end point.
Parameters
endpoint End point to connect to.
async If the connection should be asynchronous.
Definition at line 268 of file TcpConnection.cpp.
References HandleConnection(), mRemoteAddress, mSocket, mStatus, and STATUS_CONNECTING.
void TcpConnection::ConnectionFailed () protected virtual
Called if a connection attempt has failed.
Definition at line 438 of file TcpConnection.cpp.
Referenced by HandleConnection().
void TcpConnection::ConnectionSuccess () virtual
Called when a connection has been established.
Reimplemented in libcomp::EncryptedConnection, and libcomp::LobbyConnection.
Definition at line 442 of file TcpConnection.cpp.
References GetName().
Referenced by HandleConnection().
void TcpConnection::FlushOutgoing (bool closeConnection = false)
Send all queued packets to the remote host.
Parameters
closeConnection If the connection should be closed after the send queue has been emptied.
Definition at line 319 of file TcpConnection.cpp.
References FlushOutgoingInside(), GetCombinedPackets(), mOutgoing, PreparePackets(), and libcomp::ReadOnlyPacket::Rewind().
Referenced by SendObject(), and SendPacket().
void TcpConnection::FlushOutgoingInside (bool closeConnection = false) private
Send all queued packets to the remote host.
Parameters
closeConnection If the connection should be closed after the send queue has been emptied.
Definition at line 333 of file TcpConnection.cpp.
References libcomp::ReadOnlyPacket::ConstData(), libcomp::ReadOnlyPacket::Left(), mOutgoing, mSocket, mStatus, STATUS_NOT_CONNECTED, and libcomp::ReadOnlyPacket::Tell().
Referenced by FlushOutgoing().
String TcpConnection::GenerateDiffieHellmanPublic (const std::shared_ptr< Crypto::DiffieHellman > & diffieHellman) static
Generate the public key for the Diffie-Hellman key exchange.
Parameters
diffieHellman Object that stores the DH key.
Returns
Public key to be used in the DH key exchange.
Definition at line 480 of file TcpConnection.cpp.
Referenced by libcomp::EncryptedConnection::ParseClientEncryptionStart(), and libcomp::EncryptedConnection::ParseServerEncryptionStart().
std::vector< char > TcpConnection::GenerateDiffieHellmanSharedData (const std::shared_ptr< Crypto::DiffieHellman > & diffieHellman, const String & otherPublic) static
Return the shared private from the Diffie-Hellman key exchange.
Parameters
diffieHellman Object that stores the DH key.
otherPublic Public key from the other party.
Returns
Shared private data upon completion of the DH key exchange.
Definition at line 486 of file TcpConnection.cpp.
Referenced by libcomp::EncryptedConnection::ParseClientEncryptionStart(), and libcomp::EncryptedConnection::ParseServerEncryptionFinish().
std::list< ReadOnlyPacket > TcpConnection::GetCombinedPackets () protected virtual
Returns a list of packets that have been combined.
Returns
List of packet that have been combined.
Reimplemented in libcomp::EncryptedConnection.
Definition at line 526 of file TcpConnection.cpp.
References mOutgoingMutex, mOutgoingPackets, and mSendingPacket.
Referenced by FlushOutgoing().
String TcpConnection::GetDiffieHellmanPrime (const std::shared_ptr< Crypto::DiffieHellman > & diffieHellman) static
Get the prime used in the Diffie-Hellman key exchange.
Parameters
diffieHellman Object that stores the DH key.
Returns
Prime to be used in the DH key exchange.
Definition at line 474 of file TcpConnection.cpp.
Referenced by libcomp::EncryptedConnection::ParseServerEncryptionStart(), and libcomp::TcpServer::Start().
String TcpConnection::GetName () const
Get the debug name for the connection.
Definition at line 543 of file TcpConnection.cpp.
References mName.
Referenced by Close(), ConnectionSuccess(), SocketError(), and ~TcpConnection().
String TcpConnection::GetRemoteAddress () const
Get the address of the remote host.
Returns
Address of the remote host.
Definition at line 263 of file TcpConnection.cpp.
References mRemoteAddress.
Referenced by libcomp::EncryptedConnection::ConnectionEncrypted(), libcomp::LobbyConnection::ConnectionSuccess(), libcomp::EncryptedConnection::ConnectionSuccess(), libcomp::LobbyConnection::ParseExtensionConnection(), libcomp::EncryptedConnection::SocketError(), and SocketError().
TcpConnection::Role_t TcpConnection::GetRole () const
Get the role the connection is operating in.
Returns
Role the connection is operating in.
Definition at line 253 of file TcpConnection.cpp.
References mRole.
Referenced by libcomp::LobbyConnection::ConnectionSuccess(), libcomp::EncryptedConnection::ConnectionSuccess(), libcomp::LobbyConnection::ParseExtensionConnection(), and libcomp::EncryptedConnection::SocketError().
TcpConnection::ConnectionStatus_t TcpConnection::GetStatus () const
Get the status of the connection.
Returns
Status of the connection.
Definition at line 258 of file TcpConnection.cpp.
References mStatus.
Referenced by libcomp::EncryptedConnection::ParsePacket(), and libcomp::EncryptedConnection::SocketError().
void TcpConnection::HandleConnection (asio::error_code errorCode) private
Used to handle a connection error code.
Parameters
errorCode Error code that was encountered.
Definition at line 292 of file TcpConnection.cpp.
References ConnectionFailed(), ConnectionSuccess(), mRemoteAddress, mSocket, mStatus, STATUS_CONNECTED, and STATUS_NOT_CONNECTED.
Referenced by Connect().
void TcpConnection::PacketReceived (Packet & packet) protected virtual
Called after a packet has been received from the remote host.
Parameters
packet Packet that was received.
Reimplemented in libcomp::EncryptedConnection.
Definition at line 456 of file TcpConnection.cpp.
References libcomp::Packet::Clear().
void TcpConnection::PacketSent (ReadOnlyPacket & packet) protected virtual
Called after a packet has been sent to the remote host.
Parameters
packet Packet that was sent to the remote host.
Definition at line 451 of file TcpConnection.cpp.
void TcpConnection::PreparePackets (std::list< ReadOnlyPacket > & packets) protected virtual
Called to prepare packets before they are sent to the remote host.
Parameters
packets List of packets to be sent to the remote host.
Reimplemented in libcomp::EncryptedConnection, and libcomp::ChannelConnection.
Definition at line 513 of file TcpConnection.cpp.
References mOutgoing.
Referenced by FlushOutgoing().
bool TcpConnection::QueueObject (const Object & obj) virtual
Queue an object to be packetized and sent.
Note
This will not send the packet until SendPacket or FlushOutgoing is called.
Parameters
obj Object to be packetized.
Returns
true if the object could be packetized; false otherwise.
Definition at line 134 of file TcpConnection.cpp.
References QueuePacket(), and libcomp::Object::SavePacket().
Referenced by SendObject().
void TcpConnection::QueuePacket (Packet & packet) virtual
Queue a packet to be sent.
Note
This will not send the packet until SendPacket or FlushOutgoing is called.
Parameters
packet Packet to send to the remote host.
Definition at line 114 of file TcpConnection.cpp.
Referenced by QueueObject(), QueuePacketCopy(), and SendPacket().
void TcpConnection::QueuePacket (ReadOnlyPacket & packet) virtual
Queue a packet to be sent.
Note
This will not send the packet until SendPacket or FlushOutgoing is called.
Parameters
packet Packet to send to the remote host.
Definition at line 121 of file TcpConnection.cpp.
References mOutgoingMutex, and mOutgoingPackets.
void TcpConnection::QueuePacketCopy (libcomp::Packet & packet) virtual
Queue a copy of a packet to be sent.
Note
This will not send the packet until SendPacket or FlushOutgoing is called.
Parameters
packet Packet to send to the remote host.
Definition at line 128 of file TcpConnection.cpp.
References QueuePacket().
bool TcpConnection::RequestPacket (size_t size)
Start a receive request for more packet data.
The PacketReceived function will be called but it may return less bytes than requested.
Parameters
size Number of bytes requested.
Returns
true on success; false otherwise.
Definition at line 180 of file TcpConnection.cpp.
References libcomp::ReadOnlyPacket::Allocate(), libcomp::String::Arg(), libcomp::Packet::Data(), mReceivedPacket, mSocket, and libcomp::ReadOnlyPacket::Size().
Referenced by libcomp::LobbyConnection::ConnectionSuccess(), libcomp::EncryptedConnection::ConnectionSuccess(), libcomp::EncryptedConnection::ParseClientEncryptionStart(), libcomp::EncryptedConnection::ParsePacket(), libcomp::EncryptedConnection::ParseServerEncryptionFinish(), libcomp::EncryptedConnection::ParseServerEncryptionStart(), and libcomp::EncryptedConnection::SendMessage().
void libcomp::TcpConnection::SendNextPacket () private
Sends the next packet in the queue to the remote device.
bool TcpConnection::SendObject (const Object & obj, bool closeConnection = false) virtual
Packetize and queue an object and then send all queued packets to the remote host.
Parameters
obj Object to be packetized.
closeConnection If the connection should be closed after the send queue has been emptied.
Returns
true if the object could be packetized; false otherwise.
Definition at line 168 of file TcpConnection.cpp.
References FlushOutgoing(), and QueueObject().
void TcpConnection::SendPacket (Packet & packet, bool closeConnection = false) virtual
Queue a packet and then send all queued packets to the remote host.
Parameters
packet Packet to send to the remote host.
closeConnection If the connection should be closed after the send queue has been emptied.
Definition at line 148 of file TcpConnection.cpp.
Referenced by libcomp::LobbyConnection::ConnectionSuccess(), libcomp::EncryptedConnection::ConnectionSuccess(), libcomp::EncryptedConnection::ParseClientEncryptionStart(), libcomp::LobbyConnection::ParseExtensionConnection(), libcomp::EncryptedConnection::ParseServerEncryptionStart(), and SendPacketCopy().
void TcpConnection::SendPacket (ReadOnlyPacket & packet, bool closeConnection = false) virtual
Queue a packet and then send all queued packets to the remote host.
Parameters
packet Packet to send to the remote host.
closeConnection If the connection should be closed after the send queue has been emptied.
Definition at line 155 of file TcpConnection.cpp.
References FlushOutgoing(), and QueuePacket().
void TcpConnection::SendPacketCopy (libcomp::Packet & packet, bool closeConnection = false) virtual
Queue a copy of a packet and then send all queued packets to the remote host.
Parameters
packet Packet to send to the remote host.
closeConnection If the connection should be closed after the send queue has been emptied.
Definition at line 161 of file TcpConnection.cpp.
References SendPacket().
void TcpConnection::SetEncryptionKey (const std::vector< char > & data) protected
Sets the Blowfish encryption key to be used.
Parameters
data Blowfish encryption key.
Definition at line 461 of file TcpConnection.cpp.
Referenced by libcomp::EncryptedConnection::ParseClientEncryptionStart(), and libcomp::EncryptedConnection::ParseServerEncryptionFinish().
void TcpConnection::SetEncryptionKey (const void * pData, size_t dataSize) protected
Sets the Blowfish encryption key to be used.
Parameters
pData Pointer to the buffer were the key resides.
dataSize Size of the encryption key data.
Definition at line 466 of file TcpConnection.cpp.
References mEncryptionKey, and libcomp::Crypto::Blowfish::SetKey().
void TcpConnection::SetName (const String & name)
Set the debug name for the connection.
Parameters
name Debug name to set.
Definition at line 548 of file TcpConnection.cpp.
References mName.
Referenced by libcomp::LobbyConnection::ParseExtensionConnection().
void TcpConnection::SocketError (const String & errorMessage = String()) protected virtual
Report a socket error.
This should disconnect the connection.
Parameters
errorMessage Error message to report.
Reimplemented in libcomp::EncryptedConnection.
Definition at line 424 of file TcpConnection.cpp.
References libcomp::String::Arg(), Close(), GetName(), GetRemoteAddress(), and libcomp::String::IsEmpty().
Referenced by libcomp::EncryptedConnection::SocketError().
Member Data Documentation
std::shared_ptr<Crypto::DiffieHellman> libcomp::TcpConnection::mDiffieHellman protected
Diffie-Hellman key exchange data.
Definition at line 354 of file TcpConnection.h.
Referenced by libcomp::EncryptedConnection::ParseClientEncryptionStart(), libcomp::EncryptedConnection::ParseServerEncryptionFinish(), and libcomp::EncryptedConnection::ParseServerEncryptionStart().
Crypto::Blowfish libcomp::TcpConnection::mEncryptionKey protected
Blowfish encryption key.
Definition at line 357 of file TcpConnection.h.
Referenced by libcomp::EncryptedConnection::ParsePacket(), libcomp::ChannelConnection::PreparePackets(), libcomp::EncryptedConnection::PreparePackets(), and SetEncryptionKey().
String libcomp::TcpConnection::mName private
Debug name for the connection.
Definition at line 373 of file TcpConnection.h.
Referenced by GetName(), and SetName().
ReadOnlyPacket libcomp::TcpConnection::mOutgoing protected
Packet being sent to the remote host.
Definition at line 386 of file TcpConnection.h.
Referenced by FlushOutgoing(), FlushOutgoingInside(), libcomp::ChannelConnection::PreparePackets(), libcomp::EncryptedConnection::PreparePackets(), and PreparePackets().
std::mutex libcomp::TcpConnection::mOutgoingMutex protected
Mutex to ensure the outgoing packet code is executed from one thread.
Definition at line 377 of file TcpConnection.h.
Referenced by GetCombinedPackets(), libcomp::EncryptedConnection::GetCombinedPackets(), and QueuePacket().
std::list<ReadOnlyPacket> libcomp::TcpConnection::mOutgoingPackets protected
List of packets to be sent to the remote host.
Definition at line 380 of file TcpConnection.h.
Referenced by GetCombinedPackets(), libcomp::EncryptedConnection::GetCombinedPackets(), and QueuePacket().
Packet libcomp::TcpConnection::mReceivedPacket private
Last received packet.
Definition at line 367 of file TcpConnection.h.
Referenced by RequestPacket().
String libcomp::TcpConnection::mRemoteAddress private
Cached address of the remote host.
Definition at line 370 of file TcpConnection.h.
Referenced by Connect(), GetRemoteAddress(), HandleConnection(), and TcpConnection().
Role_t libcomp::TcpConnection::mRole private
Role of the connection.
Definition at line 364 of file TcpConnection.h.
Referenced by GetRole().
bool libcomp::TcpConnection::mSendingPacket protected
Indicates if an outgoing packet is being sent.
Definition at line 383 of file TcpConnection.h.
Referenced by GetCombinedPackets(), and libcomp::EncryptedConnection::GetCombinedPackets().
asio::ip::tcp::socket libcomp::TcpConnection::mSocket private
ASIO network socket for the connection.
Definition at line 350 of file TcpConnection.h.
Referenced by Close(), Connect(), FlushOutgoingInside(), HandleConnection(), RequestPacket(), and TcpConnection().
ConnectionStatus_t libcomp::TcpConnection::mStatus protected
Status of the connection.
Definition at line 360 of file TcpConnection.h.
Referenced by Close(), Connect(), FlushOutgoingInside(), GetStatus(), HandleConnection(), libcomp::EncryptedConnection::ParseClientEncryptionStart(), libcomp::EncryptedConnection::ParseServerEncryptionFinish(), libcomp::EncryptedConnection::ParseServerEncryptionStart(), libcomp::ChannelConnection::PreparePackets(), and libcomp::EncryptedConnection::PreparePackets().
The documentation for this class was generated from the following files:
TcpConnection.h
TcpConnection.cpp