COMP_hack: libcomp::String Class Reference
libcomp::String Class Reference
UTF-8 encoded string object.
#include <CString.h>
Classes
class StringData
Public Types
typedef uint32_t CodePoint
Unicode code point type.
Public Member Functions
String ()
Construct an empty string.
String (const String &other)
Perform a shallow copy of another string.
String (const std::string &str)
Construct a string from a UTF-8 encoded STL string object.
String (const char *szString)
Construct a string from a C-style UTF-8 encoded string.
String (const char *szString, size_t bytes)
Construct a string from a C-style UTF-8 encoded string.
String (const char *szString, size_t offset, size_t bytes)
Construct a string from a subsection of C-style UTF-8 encoded string.
String (size_t bytes, char character)
Create a string filled with an ASCII character.
String & Append (const String &other)
Append another string to the end of this one.
String Arg (const String &a) const
Replace the first argument of the string (%1) with the argument.
String Arg (int16_t a, int fieldWidth=0, int base=10, char fillChar= ' ')
Replace the first argument with a number.
String Arg (uint16_t a, int fieldWidth=0, int base=10, char fillChar= ' ')
Replace the first argument with a number.
String Arg (int32_t a, int fieldWidth=0, int base=10, char fillChar= ' ')
Replace the first argument with a number.
String Arg (uint32_t a, int fieldWidth=0, int base=10, char fillChar= ' ')
Replace the first argument with a number.
String Arg (int64_t a, int fieldWidth=0, int base=10, char fillChar= ' ')
Replace the first argument with a number.
String Arg (uint64_t a, int fieldWidth=0, int base=10, char fillChar= ' ')
Replace the first argument with a number.
String Arg (float a, int fieldWidth=0, int base=10, char fillChar= ' ')
Replace the first argument with a number.
String Arg (double a, int fieldWidth=0, int base=10, char fillChar= ' ')
Replace the first argument with a number.
CodePoint At (size_t position) const
Get a Unicode character at the desired position.
const char * C () const
Return a pointer to the string data for use in C-style string functions.
void Clear ()
Empty the string.
bool Contains (const String &other) const
Determine if a string contains the specified sub-string.
std::vector< char > Data (bool nullTerminate=true) const
Return a copy of the string data.
bool IsEmpty () const
Determine if the string is empty.
String Left (size_t length) const
Return a sub-string of the specified length starting from the beginning of the string.
String LeftJustified (size_t width, char fill= ' ', bool truncate=false) const
Return the string followed by filling until the desired width is met.
String LeftOf (const String &other) const
Get the text preceding a sub-string.
String LeftTrimmed () const
Remove all whitespace characters (as determined by std::isspace) from the beginning of the string.
size_t Length () const
Get the number of characters in the string.
bool Matches (const libcomp::String &expression) const
Determine if a string matches a regular expression.
bool Matches (const libcomp::String &expression, std::vector< libcomp::String > &matches) const
Determine if a string matches a regular expression.
String Mid (size_t position, size_t count=0) const
Get a substring.
bool operator!= (const char *szString) const
Compare the string to a C-style UTF-8 encoded string.
bool operator!= (const std::string &other) const
Compare the string to a UTF-8 encoded STL string object.
bool operator!= (const String &other) const
Compare the string to another string.
String & operator+= (const String &other)
Append another string to the end of this one.
bool operator== (const char *szString) const
Compare the string to a C-style UTF-8 encoded string.
bool operator== (const std::string &other) const
Compare the string to a UTF-8 encoded STL string object.
bool operator== (const String &other) const
Compare the string to another string.
String & Prepend (const String &other)
Prepend another string to the beginning of this one.
String Replace (const String &search, const String &replace) const
Replace all occurrences of substring with the given text.
String Right (size_t length) const
Return a sub-string of the specified length starting from the end of the string.
String RightJustified (size_t width, char fill= ' ', bool truncate=false) const
Return filling followed by the string until the desired width is met.
String RightOf (const String &other) const
Get the text following a sub-string.
String RightTrimmed () const
Remove all whitespace characters (as determined by std::isspace) from the end of the string.
size_t Size () const
Get the number of bytes in the string.
std::list< String > Split (const String &delimiter) const
Split a string by a delimiter.
template<typename T >
T ToDecimal (bool *pOK=nullptr) const
Convert the string to a decimal (float or double).
template<typename T >
T ToInteger (bool *pOK=nullptr) const
Convert the string to an integer.
String ToLower () const
Convert the string into uppercase.
String ToUpper () const
Convert the string into lowercase.
std::string ToUtf8 () const
Get the underlying string data as an STL string object.
String Trimmed () const
Remove all whitespace characters (as determined by std::isspace) from the beginning and end of the string.
void Truncate (size_t position)
Truncate the string to the given size.
Static Public Member Functions
static String FromCodePoint (CodePoint cp)
Convert a Unicode code point into a String object.
static bool IsReportingBadArguments ()
Get if argument errors will be reported.
static String Join (const std::list< String > &strings, const String &delimiter)
static void SetBadArgumentReporting (bool enabled)
Set if argument errors will be reported.
Private Member Functions
String (StringData *pData)
size_t CalculateLength (const std::string &str) const
void Detatch ()
Private Attributes
std::shared_ptr< StringData > d
Static Private Attributes
static bool mBadArgumentReporting = true
Related Functions
(Note that these are not member functions.)
bool operator!= (const char *szString, const String &other)
Compare a string to a C-style UTF-8 encoded string.
bool operator!= (const std::string &str, const String &other)
Compare a string to a UTF-8 encoded STL string object.
const String operator+ (const String &a, const String &b)
Concatenate two strings together.
bool operator< (const libcomp::String &a, const libcomp::String &b)
Operator to compare two strings (for sorting).
std::ostream & operator<< (::std::ostream &os, const String &str)
STL stream operator for a String object.
bool operator== (const char *szString, const String &other)
Compare a string to a C-style UTF-8 encoded string.
bool operator== (const std::string &str, const String &other)
Compare a string to a UTF-8 encoded STL string object.
Detailed Description
UTF-8 encoded string object.
Definition at line 47 of file CString.h.
Member Typedef Documentation
typedef uint32_t libcomp::String::CodePoint
Unicode code point type.
Definition at line 53 of file CString.h.
Constructor & Destructor Documentation
String::String ()
Construct an empty string.
Definition at line 90 of file CString.cpp.
Referenced by Arg(), FromCodePoint(), Join(), Left(), LeftTrimmed(), Mid(), Replace(), Right(), RightTrimmed(), Split(), ToLower(), ToUpper(), and Trimmed().
String::String (const String & other)
Perform a shallow copy of another string.
Parameters
other The string to copy.
Definition at line 94 of file CString.cpp.
String::String (const std::string & str)
Construct a string from a UTF-8 encoded STL string object.
Parameters
str UTF-8 encoded STL string object.
Definition at line 98 of file CString.cpp.
References CalculateLength(), and d.
String::String (const char * szString)
Construct a string from a C-style UTF-8 encoded string.
Parameters
szString C-style UTF-8 encoded string.
Definition at line 104 of file CString.cpp.
References CalculateLength(), and d.
String::String (const char * szString, size_t bytes)
Construct a string from a C-style UTF-8 encoded string.
Parameters
szString C-style UTF-8 encoded string.
bytes Number of bytes in the C-style string.
Definition at line 110 of file CString.cpp.
References CalculateLength(), and d.
String::String (const char * szString, size_t offset, size_t bytes)
Construct a string from a subsection of C-style UTF-8 encoded string.
Parameters
szString C-style UTF-8 encoded string.
offset Number of bytes until the beginning of the subsection of the C-style string.
bytes Number of bytes in the subsection of the C-style string.
Definition at line 116 of file CString.cpp.
References CalculateLength(), and d.
String::String (size_t bytes, char character)
Create a string filled with an ASCII character.
Parameters
bytes Number of bytes to fill.
character ASCII character to fill the string with.
Definition at line 123 of file CString.cpp.
References CalculateLength(), and d.
String::String (StringData * pData) private
Definition at line 449 of file CString.cpp.
Member Function Documentation
String & String::Append (const String & other)
Append another string to the end of this one.
Parameters
other String to append to the end of this one.
Returns
Reference to this string (to chain with other calls).
Definition at line 419 of file CString.cpp.
References d, and Detatch().
Referenced by operator+=(), and TEST().
String String::Arg (const String & a) const
Replace the first argument of the string (%1) with the argument.
All other arguments will be shifted down by 1. No argument number may be less than 1 or over 99. If an argument is used multiple times in the string, all instances will be replaced. If the argument is not found in the string, the string with all argument numbers shifted down one is returned and an error is reported to standard error if SetBadArgumentReporting is set.
Parameters
a Argument to place into the string.
Returns
String with the argument added.
Definition at line 585 of file CString.cpp.
References d, mBadArgumentReporting, and String().
Referenced by Sqrat::s64::_tostring(), Sqrat::u64::_tostring(), libcomp::TcpServer::AcceptHandler(), libcomp::DataStore::AddSearchPath(), libcomp::DataStore::AddSearchPaths(), libcomp::ServerDataManager::AppendPendingDrops(), libcomp::Database::ApplyMigration(), libcomp::ServerDataManager::ApplyZonePartial(), Arg(), libcomp::DatabaseMariaDB::Close(), libcomp::TcpConnection::Close(), libcomp::TcpConnection::Connect(), libcomp::EncryptedConnection::ConnectionEncrypted(), ConnectionString(), libcomp::LobbyConnection::ConnectionSuccess(), libcomp::EncryptedConnection::ConnectionSuccess(), libcomp::DatabaseMariaDB::ConnectToDatabase(), libcomp::BaseServer::CreateWorkers(), libcomp::DefinitionManager::LoadData< objects::MiDisassemblyData >(), libcomp::DefinitionManager::LoadData< objects::MiDynamicMapData >(), libcomp::DefinitionManager::LoadData< objects::MiEnchantData >(), libcomp::DefinitionManager::LoadData< objects::MiModificationData >(), libcomp::DefinitionManager::LoadData< objects::MiModificationExtRecipeData >(), libcomp::DefinitionManager::RegisterServerSideDefinition< objects::EnchantSetData >(), libcomp::DefinitionManager::RegisterServerSideDefinition< objects::EnchantSpecialData >(), libcomp::DefinitionManager::RegisterServerSideDefinition< objects::MiSStatusData >(), libcomp::DefinitionManager::RegisterServerSideDefinition< objects::Tokusei >(), libcomp::Crypto::DiffieHellman::DiffieHellman(), libcomp::Message::ConnectionClosed::Dump(), libcomp::Message::Encrypted::Dump(), libcomp::Message::WorldNotification::Dump(), libcomp::Message::Packet::Dump(), libcomp::Message::ExecuteImpl< Function >::Dump(), libcomp::ReadOnlyPacket::Dump(), libcomp::DatabaseQueryMariaDB::Execute(), libcomp::DatabaseMariaDB::Exists(), libcomp::DatabaseSQLite3::GetFilepath(), libcomp::DataStore::GetListing(), libcomp::DatabaseQuerySQLite3::GetNamedBinding(), libcomp::ServerDataManager::GetZoneData(), libcomp::Worker::HandleMessage(), libcomp::ScriptEngine::Import(), libcomp::ScriptEngine::Include(), libcomp::BaseServer::Initialize(), libcomp::BaseServer::InsertDataFromFile(), libcomp::DatabaseSQLite3::InsertSingleObject(), libcomp::DatabaseMariaDB::InsertSingleObject(), libcomp::DefinitionManager::LoadBinaryDataHeader(), libcomp::BaseServer::LoadDataFromFile(), libcomp::PersistentObject::LoadObjectByUUID(), libcomp::DatabaseSQLite3::LoadObjects(), libcomp::DatabaseMariaDB::LoadObjects(), libcomp::ServerDataManager::LoadObjectsFromFile(), libcomp::ServerDataManager::LoadScript(), libcomp::ServerDataManager::LoadScripts(), libcomp::Exception::Log(), libcomp::PacketException::Log(), libcomp::Log::LogMessage(), libcomp::DatabaseQueryMariaDB::Next(), libcomp::DatabaseSQLite3::Open(), libcomp::ArgumentParser::Parse(), libcomp::DatabaseQueryMariaDB::Prepare(), libcomp::DataStore::PrintListing(), libcomp::DefinitionManager::PrintLoadResult(), libcomp::DatabaseSQLite3::ProcessExplicitUpdate(), libcomp::DatabaseMariaDB::ProcessExplicitUpdate(), libcomp::ManagerPacket::ProcessMessage(), libcomp::DatabaseSQLite3::ProcessOperationalChangeSet(), libcomp::DatabaseMariaDB::ProcessOperationalChangeSet(), libcomp::DatabaseSQLite3::ProcessStandardChangeSet(), libcomp::DatabaseMariaDB::ProcessStandardChangeSet(), libcomp::BaseServer::ReadConfig(), libcomp::PersistentObject::Register(), libcomp::Exception::RegisterSignalHandler(), libcomp::TcpConnection::RequestPacket(), libcomp::ScriptEngine::ScriptEngine(), libcomp::ServerCommandLineParser::ServerCommandLineParser(), libcomp::ServerDataManager::LoadObject< objects::AILogicGroup >(), libcomp::ServerDataManager::LoadObject< objects::DemonFamiliarityType >(), libcomp::ServerDataManager::LoadObject< objects::DemonPresent >(), libcomp::ServerDataManager::LoadObject< objects::DemonQuestReward >(), libcomp::ServerDataManager::LoadObject< objects::DropSet >(), libcomp::ServerDataManager::LoadObject< objects::Event >(), libcomp::ServerDataManager::LoadObject< objects::ServerShop >(), libcomp::ServerDataManager::LoadObject< objects::ServerZone >(), libcomp::ServerDataManager::LoadObject< objects::ServerZoneInstance >(), libcomp::ServerDataManager::LoadObject< objects::ServerZoneInstanceVariant >(), libcomp::ServerDataManager::LoadObject< objects::ServerZonePartial >(), libcomp::BaseServer::ServerReady(), libcomp::DatabaseSQLite3::Setup(), libcomp::DatabaseMariaDB::Setup(), SignalHandler(), libcomp::EncryptedConnection::SocketError(), libcomp::TcpConnection::SocketError(), SquirrelErrorFunction(), SquirrelPrintFunction(), libcomp::TcpServer::Start(), libcomp::DataSyncManager::SyncIncoming(), libcomp::DataSyncManager::SyncOutgoing(), TEST(), libcomp::DatabaseSQLite3::UpdateSingleObject(), libcomp::DatabaseMariaDB::UpdateSingleObject(), libcomp::ServerDataManager::ValidateActions(), libcomp::DatabaseSQLite3::VerifyAndSetupSchema(), libcomp::DatabaseMariaDB::VerifyAndSetupSchema(), libcomp::ServerDataManager::VerifyPvPInstance(), libcomp::DatabaseQueryMariaDB::~DatabaseQueryMariaDB(), and libcomp::TcpConnection::~TcpConnection().
String String::Arg (int16_t a, int fieldWidth = 0, int base = 10, char fillChar = ' ')
Replace the first argument with a number.
Parameters
a Number to place into the first argument.
fieldWidth Minimum number of characters.
base Base of the number (8, 10 or 16).
fillChar Character to pad the value with.
Returns
String with the argument added.
Definition at line 617 of file CString.cpp.
References Arg(), and String().
String String::Arg (uint16_t a, int fieldWidth = 0, int base = 10, char fillChar = ' ')
Replace the first argument with a number.
Parameters
a Number to place into the first argument.
fieldWidth Minimum number of characters.
base Base of the number (8, 10 or 16).
fillChar Character to pad the value with.
Returns
String with the argument added.
Definition at line 628 of file CString.cpp.
References Arg(), and String().
String String::Arg (int32_t a, int fieldWidth = 0, int base = 10, char fillChar = ' ')
Replace the first argument with a number.
Parameters
a Number to place into the first argument.
fieldWidth Minimum number of characters.
base Base of the number (8, 10 or 16).
fillChar Character to pad the value with.
Returns
String with the argument added.
Definition at line 639 of file CString.cpp.
References Arg(), and String().
String String::Arg (uint32_t a, int fieldWidth = 0, int base = 10, char fillChar = ' ')
Replace the first argument with a number.
Parameters
a Number to place into the first argument.
fieldWidth Minimum number of characters.
base Base of the number (8, 10 or 16).
fillChar Character to pad the value with.
Returns
String with the argument added.
Definition at line 650 of file CString.cpp.
References Arg(), and String().
String String::Arg (int64_t a, int fieldWidth = 0, int base = 10, char fillChar = ' ')
Replace the first argument with a number.
Parameters
a Number to place into the first argument.
fieldWidth Minimum number of characters.
base Base of the number (8, 10 or 16).
fillChar Character to pad the value with.
Returns
String with the argument added.
Definition at line 661 of file CString.cpp.
References Arg(), and String().
String String::Arg (uint64_t a, int fieldWidth = 0, int base = 10, char fillChar = ' ')
Replace the first argument with a number.
Parameters
a Number to place into the first argument.
fieldWidth Minimum number of characters.
base Base of the number (8, 10 or 16).
fillChar Character to pad the value with.
Returns
String with the argument added.
Definition at line 672 of file CString.cpp.
References Arg(), and String().
String String::Arg (float a, int fieldWidth = 0, int base = 10, char fillChar = ' ')
Replace the first argument with a number.
Parameters
a Number to place into the first argument.
fieldWidth Minimum number of characters.
base Base of the number (8, 10 or 16).
fillChar Character to pad the value with.
Returns
String with the argument added.
Definition at line 690 of file CString.cpp.
References Arg(), and String().
String String::Arg (double a, int fieldWidth = 0, int base = 10, char fillChar = ' ')
Replace the first argument with a number.
Parameters
a Number to place into the first argument.
fieldWidth Minimum number of characters.
base Base of the number (8, 10 or 16).
fillChar Character to pad the value with.
Returns
String with the argument added.
Definition at line 702 of file CString.cpp.
References Arg(), and String().
String::CodePoint String::At (size_t position) const
Get a Unicode character at the desired position.
Parameters
position Number of characters into the string to get the character at.
Returns
The Unicode code point at the desired position or 0.
Definition at line 301 of file CString.cpp.
References d.
Referenced by libcomp::ArgumentParser::Parse(), TEST(), ToCP1252Encoding(), and ToCP932Encoding().
const char * String::C () const
Return a pointer to the string data for use in C-style string functions.
A null terminator will be added to the end of the buffer.
Returns
C-style string data.
Note
The pointer returned may be invalidated by further calls to other member functions that modify the object.
Definition at line 784 of file CString.cpp.
References d.
Referenced by libcomp::DataStore::AddSearchPath(), libcomp::DataStore::AddSearchPaths(), libcomp::DatabaseQuerySQLite3::Bind(), libcomp::DBExplicitUpdate::Bind(), libcomp::DatabaseMariaDB::ConnectToDatabase(), libcomp::DataStore::CreateDirectory(), libcomp::DataStore::Delete(), libcomp::Crypto::DiffieHellman::DiffieHellman(), libcomp::ScriptEngine::Eval(), libcomp::DataStore::Exists(), libcomp::Log::FileDelete(), libcomp::Log::FileExists(), libcomp::Log::FileMove(), libcomp::Crypto::GenDiffieHellman(), libcomp::Crypto::DiffieHellman::GenerateSecret(), libcomp::ServerDataManager::GetAIScript(), libcomp::DataStore::GetListing(), libcomp::DatabaseQueryMariaDB::GetRows(), libcomp::ServerDataManager::GetScript(), libcomp::ServerConstants::Initialize(), libcomp::BaseServer::InsertDataFromFile(), libcomp::BaseServer::LoadDataFromFile(), libcomp::Log::LogMessage(), LogToStandardOutput(), libcomp::DataFile::Open(), libcomp::DatabaseQuerySQLite3::Prepare(), libcomp::DatabaseQueryMariaDB::Prepare(), Var< libcomp::String >::push(), Var< const libcomp::String & >::push(), libcomp::DataSyncManager::QueueOutgoing(), libcomp::BaseServer::ReadConfig(), libcomp::DataSyncManager::RemoveRecord(), libcomp::Log::RotateLogs(), libcomp::Log::SetLogPath(), libcomp::Worker::Start(), TEST(), libcomp::DataSyncManager::UpdateRecord(), libcomp::DBExplicitUpdate::Verify(), and libcomp::DatabaseMariaDB::VerifyAndSetupSchema().
size_t String::CalculateLength (const std::string & str) const private
Definition at line 461 of file CString.cpp.
Referenced by String().
void String::Clear ()
Empty the string.
Definition at line 491 of file CString.cpp.
References d.
Referenced by GetDiffieHellmanPrime(), libcomp::Log::RotateLogs(), libcomp::Log::SetLogPath(), TEST(), and Truncate().
bool String::Contains (const String & other) const
Determine if a string contains the specified sub-string.
Parameters
other Sub-string to look for.
Returns
true if the sub-string is within the string.
Definition at line 496 of file CString.cpp.
References d.
std::vector< char > String::Data (bool nullTerminate = true) const
Return a copy of the string data.
Parameters
nullTerminate If the string data should be null terminated.
Returns
A copy of the string data.
Definition at line 772 of file CString.cpp.
References d.
Referenced by libcomp::DatabaseQueryMariaDB::Bind(), libcomp::Randomizer::SeedRNG(), and libcomp::Convert::ToEncoding().
void String::Detatch () private
Definition at line 453 of file CString.cpp.
References d.
Referenced by Append(), and Prepend().
String String::FromCodePoint (CodePoint cp) static
Convert a Unicode code point into a String object.
Parameters
cp Unicode code point to transform into a String object.
Returns
The Unicode code point wrapped in a String object.
Definition at line 846 of file CString.cpp.
References String().
Referenced by FromCP1252Encoding(), FromCP932Encoding(), and TEST().
bool String::IsEmpty () const
Determine if the string is empty.
Returns
true if the string is empty.
Definition at line 486 of file CString.cpp.
References d.
Referenced by libcomp::DatabaseMariaDB::ConnectToDatabase(), Join(), libcomp::Log::LogMessage(), LogToStandardOutput(), libcomp::ArgumentParser::Parse(), libcomp::ArgumentParser::RegisterArgument(), libcomp::Log::RotateLogs(), libcomp::Log::SetLogPath(), libcomp::TcpConnection::SocketError(), libcomp::TcpServer::Start(), libcomp::DataSyncManager::SyncIncoming(), TEST(), libcomp::DatabaseSQLite3::VerifyAndSetupSchema(), and libcomp::DatabaseMariaDB::VerifyAndSetupSchema().
bool String::IsReportingBadArguments () static
Get if argument errors will be reported.
This will report the error over the standard error stream.
Returns
true if argument errors will be reported.
See Also
SetBadArgumentReporting
Arg
Definition at line 789 of file CString.cpp.
References mBadArgumentReporting.
Referenced by TEST().
String String::Join (const std::list< String > & strings, const String & delimiter) static
Definition at line 799 of file CString.cpp.
References IsEmpty(), and String().
Referenced by libcomp::DatabaseSQLite3::DeleteObjects(), libcomp::DatabaseMariaDB::DeleteObjects(), libcomp::ReadOnlyPacket::Dump(), libcomp::Message::ExecuteImpl< Function >::ExecuteImpl(), libcomp::DatabaseSQLite3::InsertSingleObject(), libcomp::DatabaseMariaDB::InsertSingleObject(), libcomp::Exception::Log(), libcomp::PacketException::Log(), libcomp::DatabaseSQLite3::ProcessExplicitUpdate(), libcomp::DatabaseMariaDB::ProcessExplicitUpdate(), libcomp::DatabaseSQLite3::UpdateSingleObject(), and libcomp::DatabaseMariaDB::UpdateSingleObject().
String String::Left (size_t length) const
Return a sub-string of the specified length starting from the beginning of the string.
If the string is less than the length specified, the entire string is returned. This operates on characters, not bytes.
Parameters
length Max number of characters (not bytes) to extract.
Returns
The sub-string.
Definition at line 129 of file CString.cpp.
References d, and String().
Referenced by libcomp::Exception::File(), libcomp::ArgumentParser::Parse(), libcomp::DatabaseSQLite3::Setup(), libcomp::DatabaseMariaDB::Setup(), and Truncate().
String String::LeftJustified (size_t width, char fill = ' ', bool truncate = false) const
Return the string followed by filling until the desired width is met.
Parameters
width Desired length of the filled string.
fill Character to fill the rest of the string with.
truncate If longer strings should be truncated.
Returns
Copy of the string filled to the desired width.
Definition at line 193 of file CString.cpp.
References Length(), and Truncate().
String String::LeftOf (const String & other) const
Get the text preceding a sub-string.
Parameters
other Sub-string to look for. Text preceding a sub-string.
Definition at line 501 of file CString.cpp.
References d.
String String::LeftTrimmed () const
Remove all whitespace characters (as determined by std::isspace) from the beginning of the string.
Returns
Copy of the string with the whitespace removed.
Definition at line 525 of file CString.cpp.
References d, and String().
size_t String::Length () const
Get the number of characters in the string.
Returns
Number of characters in the string.
Definition at line 476 of file CString.cpp.
References d.
Referenced by libcomp::Crypto::DiffieHellman::DiffieHellman(), libcomp::Exception::File(), GetDiffieHellmanPrime(), libcomp::DatabaseQueryMariaDB::GetRows(), LeftJustified(), libcomp::ArgumentParser::Parse(), libcomp::DatabaseQuerySQLite3::Prepare(), RightJustified(), TEST(), ToCP1252Encoding(), and ToCP932Encoding().
bool String::Matches (const libcomp::String & expression) const
Determine if a string matches a regular expression.
Parameters
expression Regular expression to match.
Returns
true if the string matches, false otherwise.
Definition at line 714 of file CString.cpp.
References ToUtf8().
Referenced by libcomp::ServerDataManager::LoadObjects(), and libcomp::ArgumentParser::Parse().
bool String::Matches (const libcomp::String & expression, std::vector< libcomp::String > & matches) const
Determine if a string matches a regular expression.
Parameters
expression Regular expression to match.
matches The capture list. Index 0 is the full match.
Returns
true if the string matches, false otherwise.
Definition at line 727 of file CString.cpp.
References ToUtf8().
String String::Mid (size_t position, size_t count = 0) const
Get a substring.
Parameters
position Number of characters into the string to start at.
count Number of characters to extract or 0 for all.
Returns
Requested sub-string.
Definition at line 241 of file CString.cpp.
References d, and String().
Referenced by libcomp::Exception::File(), and libcomp::ArgumentParser::Parse().
bool String::operator!= (const char * szString) const
Compare the string to a C-style UTF-8 encoded string.
Parameters
szString C-style UTF-8 encoded string to compare to.
Returns
true if the string data does not match.
Definition at line 404 of file CString.cpp.
References d.
bool String::operator!= (const std::string & other) const
Compare the string to a UTF-8 encoded STL string object.
Parameters
other UTF-8 encoded STL string object to compare to.
Returns
true if the string data does not match.
Definition at line 409 of file CString.cpp.
References d.
bool String::operator!= (const String & other) const
Compare the string to another string.
Parameters
other String to compare to.
Returns
true if the string data does not match.
Definition at line 414 of file CString.cpp.
References d.
String & String::operator+= (const String & other)
Append another string to the end of this one.
Parameters
other String to append to the end of this one.
Returns
Reference to this string.
Definition at line 439 of file CString.cpp.
References Append().
bool String::operator== (const char * szString) const
Compare the string to a C-style UTF-8 encoded string.
Parameters
szString C-style UTF-8 encoded string to compare to.
Returns
true if the string data matches exactly.
Definition at line 389 of file CString.cpp.
References d.
bool String::operator== (const std::string & other) const
Compare the string to a UTF-8 encoded STL string object.
Parameters
other UTF-8 encoded STL string object to compare to.
Returns
true if the string data matches exactly.
Definition at line 394 of file CString.cpp.
References d.
bool String::operator== (const String & other) const
Compare the string to another string.
Parameters
other String to compare to.
Returns
true if the string data matches exactly.
Definition at line 399 of file CString.cpp.
References d.
String & String::Prepend (const String & other)
Prepend another string to the beginning of this one.
Parameters
other String to prepend to the beginning of this one.
Returns
Reference to this string (to chain with other calls).
Definition at line 429 of file CString.cpp.
References d, and Detatch().
Referenced by TEST().
String String::Replace (const String & search, const String & replace) const
Replace all occurrences of substring with the given text.
Parameters
search Substring to replace.
replace Text to replace the substring with.
Returns
Copy of the string with the substring replaces.
Definition at line 564 of file CString.cpp.
References d, and String().
Referenced by libcomp::Log::FileDelete(), libcomp::Log::FileExists(), libcomp::Log::FileMove(), and TEST().
String String::Right (size_t length) const
Return a sub-string of the specified length starting from the end of the string.
If the string is less than the length specified, the entire string is returned. This operates on characters, not bytes. This will count from the end of the string but will not reverse it.
Parameters
length Max number of characters (not bytes) to extract.
Returns
The sub-string.
Definition at line 161 of file CString.cpp.
References d, and String().
Referenced by libcomp::DataStore::GetListing().
String String::RightJustified (size_t width, char fill = ' ', bool truncate = false) const
Return filling followed by the string until the desired width is met.
Parameters
width Desired length of the filled string.
fill Character to fill the rest of the string with.
truncate If longer strings should be truncated.
Returns
Copy of the string filled to the desired width.
Definition at line 211 of file CString.cpp.
References Length(), and Truncate().
Referenced by libcomp::Crypto::GenDiffieHellman().
String String::RightOf (const String & other) const
Get the text following a sub-string.
Parameters
other Sub-string to look for. Text following a sub-string.
Definition at line 513 of file CString.cpp.
References d.
String String::RightTrimmed () const
Remove all whitespace characters (as determined by std::isspace) from the end of the string.
Returns
Copy of the string with the whitespace removed.
Definition at line 536 of file CString.cpp.
References d, and String().
void String::SetBadArgumentReporting (bool enabled) static
Set if argument errors will be reported.
This will report the error over the standard error stream.
Parameters
enable true if argument errors should be reported.
See Also
IsReportingBadArguments
Arg
Definition at line 794 of file CString.cpp.
References mBadArgumentReporting.
Referenced by TEST().
size_t String::Size () const
Get the number of bytes in the string.
Returns
Number of bytes in the string.
Definition at line 481 of file CString.cpp.
References d.
Referenced by libcomp::DatabaseQuerySQLite3::Bind(), libcomp::ScriptEngine::Eval(), libcomp::Log::LogMessage(), Var< libcomp::String >::push(), Var< const libcomp::String & >::push(), and TEST().
std::list< String > String::Split (const String & delimiter) const
Split a string by a delimiter.
Parameters
delimiter Sub-string to split the string by.
Returns
All components on either side of each instance of delimiter.
Definition at line 364 of file CString.cpp.
References d, and String().
Referenced by libcomp::ServerConstants::Initialize(), LogToStandardOutput(), SquirrelErrorFunction(), SquirrelErrorFunctionRaw(), SquirrelPrintFunction(), SquirrelPrintFunctionRaw(), TEST(), and libcomp::ServerConstants::ToIntegerRange().
template<typename T > T libcomp::String::ToDecimal (bool * pOK = nullptr) const inline
Convert the string to a decimal (float or double).
Parameters
pOK If not null, this will set the variable pointed by pOK to true if the string was converted or false if it was not.
Returns
0 if the conversion failed or the value is 0 or the value of the string represented as an integer.
Definition at line 574 of file CString.h.
References ToUtf8().
Referenced by libcomp::ServerConstants::LoadDecimal().
template<typename T > T libcomp::String::ToInteger (bool * pOK = nullptr) const inline
Convert the string to an integer.
Parameters
pOK If not null, this will set the variable pointed by pOK to true if the string was converted or false if it was not.
Returns
0 if the conversion failed or the value is 0 or the value of the string represented as an integer.
Note
This works with hex (0x prefix) and octal (0 prefix) as well.
Definition at line 480 of file CString.h.
References ToUtf8().
Referenced by libcomp::ServerConstants::LoadInteger(), and libcomp::ServerCommandLineParser::ServerCommandLineParser().
String String::ToLower () const
Convert the string into uppercase.
Returns
Copy of the string in uppercase.
Definition at line 762 of file CString.cpp.
References d, and String().
Referenced by libcomp::TcpServer::Start(), libcomp::DatabaseSQLite3::TableHasRows(), and libcomp::DatabaseMariaDB::VerifyAndSetupSchema().
String String::ToUpper () const
Convert the string into lowercase.
Returns
Copy of the string in lowercase.
Definition at line 752 of file CString.cpp.
References d, and String().
std::string String::ToUtf8 () const
Get the underlying string data as an STL string object.
Returns
The UTF-8 encoded string as an STL string object.
Definition at line 444 of file CString.cpp.
References d.
Referenced by libcomp::TcpConnection::Connect(), libcomp::DatabaseQuerySQLite3::GetNamedBinding(), libcomp::DatabaseQuerySQLite3::GetValue(), libcomp::DatabaseQueryMariaDB::GetValue(), libcomp::Crypto::HashPassword(), LogToStandardOutput(), Matches(), std::hash< libcomp::String >::operator()(), libcomp::ArgumentParser::Parse(), libcomp::TcpServer::Start(), TEST(), ToDecimal(), ToInteger(), libcomp::DatabaseSQLite3::VerifyAndSetupSchema(), and libcomp::DatabaseMariaDB::VerifyAndSetupSchema().
String String::Trimmed () const
Remove all whitespace characters (as determined by std::isspace) from the beginning and end of the string.
Returns
Copy of the string with the whitespace removed.
Definition at line 547 of file CString.cpp.
References d, and String().
void String::Truncate (size_t position)
Truncate the string to the given size.
Parameters
position Number of characters to truncate the string to.
Definition at line 229 of file CString.cpp.
References Clear(), and Left().
Referenced by LeftJustified(), RightJustified(), and TEST().
Friends And Related Function Documentation
bool operator!= (const char * szString, const String & other) related
Compare a string to a C-style UTF-8 encoded string.
Parameters
szString C-style UTF-8 encoded string to compare to.
other String object to compare to.
Returns
true if the string data does not match.
bool operator!= (const std::string & str, const String & other) related
Compare a string to a UTF-8 encoded STL string object.
Parameters
str String object to compare to.
other UTF-8 encoded STL string object to compare to.
Returns
true if the string data does not match.
const String operator+ (const String & a, const String & b) related
Concatenate two strings together.
Parameters
a First string to concatenate.
b Second string to concatenate.
Returns
The first string concatenated with the second.
bool operator< (const libcomp::String & a, const libcomp::String & b) related
Operator to compare two strings (for sorting).
Parameters
a First string to compare.
b Second string to compare.
Returns
true if b < a
std::ostream & operator<< (::std::ostream & os, const String & str) related
STL stream operator for a String object.
Parameters
os STL stream to add the string into.
str String to add into the STL stream.
Returns
Reference to the STL stream.
bool operator== (const char * szString, const String & other) related
Compare a string to a C-style UTF-8 encoded string.
Parameters
szString C-style UTF-8 encoded string to compare to.
other String object to compare to.
Returns
true if the string data matches exactly.
bool operator== (const std::string & str, const String & other) related
Compare a string to a UTF-8 encoded STL string object.
Parameters
str String object to compare to.
other UTF-8 encoded STL string object to compare to.
Returns
true if the string data matches exactly.
Member Data Documentation
std::shared_ptr<StringData> libcomp::String::d private
Definition at line 653 of file CString.h.
Referenced by Append(), Arg(), At(), C(), Clear(), Contains(), Data(), Detatch(), IsEmpty(), Left(), LeftOf(), LeftTrimmed(), Length(), Mid(), operator!=(), operator==(), Prepend(), Replace(), Right(), RightOf(), RightTrimmed(), Size(), Split(), String(), ToLower(), ToUpper(), ToUtf8(), and Trimmed().
bool String::mBadArgumentReporting = true static private
Definition at line 660 of file CString.h.
Referenced by Arg(), IsReportingBadArguments(), and SetBadArgumentReporting().
The documentation for this class was generated from the following files:
CString.h
CString.cpp