COMP_hack: libcomp::Message::ExecuteImpl< Function > Class Template Reference
libcomp::Message::ExecuteImpl< Function > Class Template Reference
Message that provides code to execute inside the worker.
#include <MessageExecute.h>
Public Types
using BindType_t = decltype(std::bind(std::declval< std::function< void(Function...)>>(), std::declval< Function >()...))
Public Member Functions
template<typename... Args>
ExecuteImpl (std::function< void(Function...)> f, Args &&...args)
Create the message.
virtual ~ExecuteImpl ()
Cleanup the message.
virtual libcomp::String Dump () const override
Dump the message for logging.
virtual MessageType GetType () const
Get the message's type.
virtual void Run ()
Execute the code contained in the message.
Private Attributes
libcomp::String mBacktrace
BindType_t mBind
Detailed Description
template<typename... Function>
class libcomp::Message::ExecuteImpl< Function >
Message that provides code to execute inside the worker.
Note
This is the implementation for a function with a specific signature.
Definition at line 63 of file MessageExecute.h.
Member Typedef Documentation
template<typename... Function> using libcomp::Message::ExecuteImpl< Function >::BindType_t = decltype(std::bind(std::declval<std::function<void(Function...)>>(), std::declval<Function>()...))
Definition at line 67 of file MessageExecute.h.
Constructor & Destructor Documentation
template<typename... Function> template<typename... Args> libcomp::Message::ExecuteImpl< Function >::ExecuteImpl (std::function< void(Function...)> f, Args &&... args) inline explicit
Create the message.
Definition at line 73 of file MessageExecute.h.
References libcomp::Exception::Backtrace(), libcomp::String::Join(), and libcomp::Message::ExecuteImpl< Function >::mBacktrace.
template<typename... Function> virtual libcomp::Message::ExecuteImpl< Function >::~ExecuteImpl () inline virtual
Cleanup the message.
Definition at line 83 of file MessageExecute.h.
Member Function Documentation
template<typename... Function> virtual libcomp::String libcomp::Message::ExecuteImpl< Function >::Dump () const inline override virtual
Dump the message for logging.
Returns
String representation of the message.
Implements libcomp::Message::Message.
Definition at line 92 of file MessageExecute.h.
References libcomp::String::Arg(), and libcomp::Message::ExecuteImpl< Function >::mBacktrace.
template<typename... Function> virtual MessageType libcomp::Message::ExecuteImpl< Function >::GetType () const inline virtual
Get the message's type.
Returns
The message's type.
Implements libcomp::Message::Message.
Definition at line 87 of file MessageExecute.h.
References libcomp::Message::MESSAGE_TYPE_SYSTEM.
template<typename... Function> virtual void libcomp::Message::ExecuteImpl< Function >::Run () inline virtual
Execute the code contained in the message.
Implements libcomp::Message::Execute.
Definition at line 98 of file MessageExecute.h.
References libcomp::Message::ExecuteImpl< Function >::mBind.
Member Data Documentation
template<typename... Function> libcomp::String libcomp::Message::ExecuteImpl< Function >::mBacktrace private
Definition at line 105 of file MessageExecute.h.
Referenced by libcomp::Message::ExecuteImpl< Function >::Dump(), and libcomp::Message::ExecuteImpl< Function >::ExecuteImpl().
template<typename... Function> BindType_t libcomp::Message::ExecuteImpl< Function >::mBind private
Definition at line 104 of file MessageExecute.h.
Referenced by libcomp::Message::ExecuteImpl< Function >::Run().
The documentation for this class was generated from the following file:
MessageExecute.h