COMP_hack: CryptSupport.h File Reference
CryptSupport.h File Reference
Support functions for older versions of OpenSSL.
#include <openssl/dh.h>
Functions
static const BIGNUM * DH_get0_g (const DH *dh)
static void DH_get0_key (const DH *dh, const BIGNUM **pub_key, const BIGNUM **priv_key)
static const BIGNUM * DH_get0_p (const DH *dh)
static void DH_get0_pqg (const DH *dh, const BIGNUM **p, const BIGNUM **q, const BIGNUM **g)
static const BIGNUM * DH_get0_priv_key (const DH *dh)
static const BIGNUM * DH_get0_pub_key (const DH *dh)
static const BIGNUM * DH_get0_q (const DH *dh)
static int DH_set0_key (DH *dh, BIGNUM *pub_key, BIGNUM *priv_key)
static int DH_set0_pqg (DH *dh, BIGNUM *p, BIGNUM *q, BIGNUM *g)
static int DH_set_length (DH *dh, long length)
Detailed Description
Support functions for older versions of OpenSSL.
Author
COMP Omega compo.nosp@m.mega.nosp@m.@tuta.nosp@m.nota.nosp@m..com
This file is part of the COMP_hack Library (libcomp).
Copyright (C) 2012-2020 COMP_hack Team compo.nosp@m.mega.nosp@m.@tuta.nosp@m.nota.nosp@m..com
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Definition in file CryptSupport.h.
Function Documentation
static const BIGNUM* DH_get0_g (const DH * dh) inline static
Definition at line 56 of file CryptSupport.h.
static void DH_get0_key (const DH * dh, const BIGNUM ** pub_key, const BIGNUM ** priv_key) inline static
Definition at line 90 of file CryptSupport.h.
static const BIGNUM* DH_get0_p (const DH * dh) inline static
Definition at line 46 of file CryptSupport.h.
Referenced by GetDiffieHellmanPrime().
static void DH_get0_pqg (const DH * dh, const BIGNUM ** p, const BIGNUM ** q, const BIGNUM ** g) inline static
Definition at line 35 of file CryptSupport.h.
Referenced by libcomp::Crypto::DiffieHellman::Generate(), libcomp::Crypto::DiffieHellman::GeneratePublic(), and libcomp::Crypto::DiffieHellman::GenerateSecret().
static const BIGNUM* DH_get0_priv_key (const DH * dh) inline static
Definition at line 104 of file CryptSupport.h.
static const BIGNUM* DH_get0_pub_key (const DH * dh) inline static
Definition at line 99 of file CryptSupport.h.
Referenced by libcomp::Crypto::DiffieHellman::GeneratePublic(), and libcomp::Crypto::DiffieHellman::GenerateSecret().
static const BIGNUM* DH_get0_q (const DH * dh) inline static
Definition at line 51 of file CryptSupport.h.
static int DH_set0_key (DH * dh, BIGNUM * pub_key, BIGNUM * priv_key) inline static
Definition at line 109 of file CryptSupport.h.
Referenced by libcomp::Crypto::DiffieHellman::DiffieHellman().
static int DH_set0_pqg (DH * dh, BIGNUM * p, BIGNUM * q, BIGNUM * g) inline static
Definition at line 61 of file CryptSupport.h.
Referenced by libcomp::Crypto::DiffieHellman::DiffieHellman().
static int DH_set_length (DH * dh, long length) inline static
Definition at line 130 of file CryptSupport.h.