COMP_hack: Log.cpp File Reference
Log.cpp File Reference
Routines to log messages to the console and/or a file.
#include "Log.h"
#include "EnumUtils.h"
#include <iostream>
#include <cassert>
#include <chrono>
#include <thread>
#include <cstdio>
#include <cstdlib>
#include <unistd.h>
#include <zlib.h>
Functions
static void LogToStandardOutput (LogComponent_t comp, Log::Level_t level, const String &msg, void *pUserData)
Log hook to send all log messages to standard output.
Variables
static EnumMap< LogComponent_t,
String > gLogComponentMapping
Mapping of log components to their string names.
static Log * gLogInst = nullptr
Detailed Description
Routines to log messages to the console and/or a file.
Author
COMP Omega compo.nosp@m.mega.nosp@m.@tuta.nosp@m.nota.nosp@m..com
This file is part of the COMP_hack Library (libcomp).
Copyright (C) 2012-2020 COMP_hack Team compo.nosp@m.mega.nosp@m.@tuta.nosp@m.nota.nosp@m..com
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Definition in file Log.cpp.
Function Documentation
static void LogToStandardOutput (LogComponent_t comp, Log::Level_t level, const String & msg, void * pUserData) static
Log hook to send all log messages to standard output.
This hook will color all log messages depending on their log level.
Parameters
level Numeric level representing the log level.
msg The message to write to standard output.
pUserData User defined data that was passed with the hook to Log::AddLogHook.
Definition at line 189 of file Log.cpp.
References libcomp::String::C(), libcomp::String::IsEmpty(), libcomp::Log::LOG_LEVEL_COUNT, libcomp::Log::LOG_LEVEL_CRITICAL, libcomp::String::Split(), and libcomp::String::ToUtf8().
Referenced by libcomp::Log::AddStandardOutputHook().
Variable Documentation
EnumMap<LogComponent_t, String> gLogComponentMapping static
Mapping of log components to their string names.
Definition at line 98 of file Log.cpp.
Referenced by libcomp::LogComponentToString(), and libcomp::StringToLogComponent().
Log* gLogInst = nullptr static
Definition at line 168 of file Log.cpp.
Referenced by libcomp::Log::GetSingletonPtr(), and libcomp::Log::MessageLoop().