COMP_hack: MemoryManager.cpp File Reference
MemoryManager.cpp File Reference
Memory manager to track usage for leak analysis.
#include "MemoryManager.h"
#include "Constants.h"
#include "Exception.h"
#include <zlib.h>
#include <regex_ext>
#include <execinfo.h>
#include <cxxabi.h>
#include <climits>
#include <cstdlib>
#include <exception>
#include <iomanip>
#include <mutex>
#include <sstream>
#include <signal.h>
Functions
static int compare_tree (rbtree_key left, rbtree_key right)
Compares two nodes in the red-black tree.
void operator delete (void *pData) noexcept
void operator delete (void *pData, size_t) noexcept
void * operator new (size_t size)
void * operator new[] (size_t size)
Variables
static MemoryManager * gManager = nullptr
Global pointer to the memory manager.
static bool gMemoryManagerEnabled = false
Indicates if the memory manager should be used.
Detailed Description
Memory manager to track usage for leak analysis.
Author
COMP Omega compo.nosp@m.mega.nosp@m.@tuta.nosp@m.nota.nosp@m..com
This file is part of the COMP_hack Library (libcomp).
Copyright (C) 2012-2020 COMP_hack Team compo.nosp@m.mega.nosp@m.@tuta.nosp@m.nota.nosp@m..com
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Definition in file MemoryManager.cpp.
Function Documentation
static int compare_tree (rbtree_key left, rbtree_key right) static
Compares two nodes in the red-black tree.
Parameters
left Node to compare.
right Node to compare.
Returns
Negative value if left < right, positive if left > right or 0 if equal.
Definition at line 78 of file MemoryManager.cpp.
Referenced by libcomp::MemoryManager::Allocate(), and libcomp::MemoryManager::Deallocate().
void operator delete (void * pData) noexcept
Definition at line 546 of file MemoryManager.cpp.
References libcomp::MemoryManager::Deallocate(), gManager, and gMemoryManagerEnabled.
void operator delete (void * pData, size_t) noexcept
Definition at line 559 of file MemoryManager.cpp.
References libcomp::MemoryManager::Deallocate(), gManager, and gMemoryManagerEnabled.
void* operator new (size_t size)
Definition at line 522 of file MemoryManager.cpp.
References libcomp::MemoryManager::Allocate(), gManager, and gMemoryManagerEnabled.
void* operator new[] (size_t size)
Definition at line 534 of file MemoryManager.cpp.
References libcomp::MemoryManager::Allocate(), gManager, and gMemoryManagerEnabled.
Variable Documentation
MemoryManager* gManager = nullptr static
Global pointer to the memory manager.
Definition at line 69 of file MemoryManager.cpp.
Referenced by libcomp::GetMemoryStats(), libcomp::InitMemoryManager(), operator delete(), operator new(), operator new[](), and libcomp::TriggerMemorySnapshot().
bool gMemoryManagerEnabled = false static
Indicates if the memory manager should be used.
Definition at line 66 of file MemoryManager.cpp.
Referenced by libcomp::InitMemoryManager(), libcomp::IsMemoryManagerEnabled(), operator delete(), operator new(), and operator new[]().