COMP_hack: libcomp::Convert Namespace Reference
libcomp::Convert Namespace Reference
Enumerations
enum Encoding_t { ENCODING_UTF8 = 0, ENCODING_CP932, ENCODING_CP1252 }
Valid string encodings.
Functions
String FromEncoding (Encoding_t encoding, const char *szString, int size=-1)
Convert a string from the specified encoding to a String.
String FromEncoding (Encoding_t encoding, const std::vector< char > &str)
Convert a string from the specified encoding to a String.
size_t SizeEncoded (Encoding_t encoding, const String &str, size_t align=0)
Determine the size of a String if it was converted to the specified encoding.
std::vector< char > ToEncoding (Encoding_t encoding, const String &str, bool nullTerminator=true)
Convert a String to the specified encoding.
Enumeration Type Documentation
enum libcomp::Convert::Encoding_t
Valid string encodings.
Enumerator
ENCODING_UTF8
ENCODING_CP932
ENCODING_CP1252
Definition at line 41 of file Convert.h.
Function Documentation
String libcomp::Convert::FromEncoding (Encoding_t encoding, const char * szString, int size = -1)
Convert a string from the specified encoding to a String.
Parameters
encoding Encoding to use. Can be one of:
ENCODING_UTF8 (Unicode)
ENCODING_CP932 (Japanese)
ENCODING_CP1252 (US English)
szString Pointer to the string to convert.
size Optional size of the buffer. If a valid size is not specified, it is assumed that the string is null terminated.
Returns
The converted string or an empty string if there was a conversion error.
See Also
libcomp::Convert::ToEncoding
libcomp::Convert::SizeEncoded
Definition at line 297 of file src/Convert.cpp.
References ENCODING_CP1252, ENCODING_CP932, FromCP1252Encoding(), and FromCP932Encoding().
Referenced by FromEncoding(), libcomp::ReadOnlyPacket::ReadString(), libcomp::ReadOnlyPacket::ReadString16(), libcomp::ReadOnlyPacket::ReadString16Big(), libcomp::ReadOnlyPacket::ReadString16Little(), libcomp::ReadOnlyPacket::ReadString32(), libcomp::ReadOnlyPacket::ReadString32Big(), libcomp::ReadOnlyPacket::ReadString32Little(), and TEST().
String libcomp::Convert::FromEncoding (Encoding_t encoding, const std::vector< char > & str)
Convert a string from the specified encoding to a String.
Parameters
encoding Encoding to use. Can be one of:
ENCODING_UTF8 (Unicode)
ENCODING_CP932 (Japanese)
ENCODING_CP1252 (US English)
str String data to convert.
size Optional size of the buffer. If a valid size is not specified, it is assumed that the string is null terminated.
Returns
The converted string or an empty string if there was a conversion error.
See Also
libcomp::Convert::ToEncoding
libcomp::Convert::SizeEncoded
Definition at line 322 of file src/Convert.cpp.
References FromEncoding().
size_t libcomp::Convert::SizeEncoded (Encoding_t encoding, const String & str, size_t align = 0)
Determine the size of a String if it was converted to the specified encoding.
If align is specified, the size will be rounded up to a multiple of align.
Parameters
encoding Encoding to use. Can be one of:
ENCODING_UTF8 (Unicode)
ENCODING_CP932 (Japanese)
ENCODING_CP1252 (US English)
str String that would be converted.
align Byte alignment to use when calculating the size of the string. For example a string of length 13 would return a length of 16 if align was set to 4.
Returns
The size of the string if it was converted to the desired encoding with the optional byte alignment.
Definition at line 345 of file src/Convert.cpp.
References ToEncoding().
Referenced by TEST().
std::vector< char > libcomp::Convert::ToEncoding (Encoding_t encoding, const String & str, bool nullTerminator = true)
Convert a String to the specified encoding.
Parameters
encoding Encoding to use. Can be one of:
ENCODING_UTF8 (Unicode)
ENCODING_CP932 (Japanese)
ENCODING_CP1252 (US English)
str String to convert.
nullTerminator Indicates if a null terminator should be added.
Returns
The converted string or an empty string if there was a conversion error.
See Also
libcomp::Convert::FromEncoding
libcomp::Convert::SizeEncoded
Definition at line 327 of file src/Convert.cpp.
References libcomp::String::Data(), ENCODING_CP1252, ENCODING_CP932, ToCP1252Encoding(), and ToCP932Encoding().
Referenced by SizeEncoded(), TEST(), libcomp::Packet::WriteString(), libcomp::Packet::WriteString16(), libcomp::Packet::WriteString16Big(), libcomp::Packet::WriteString16Little(), libcomp::Packet::WriteString32(), libcomp::Packet::WriteString32Big(), and libcomp::Packet::WriteString32Little().