COMP_hack: libcomp::Crypto Namespace Reference
libcomp::Crypto Namespace Reference
Encryption and Decryption functions.
Classes
class Blowfish
This class will encrypt and decrypt data using the blowfish algorithm.
struct BlowfishPrivate
class DiffieHellman
This class will perform a Diffie-Hellman-Merkle key exchange.
struct DiffieHellmanPrivate
Functions
bool DecryptFile (std::vector< char > &buffer)
Decrypt a file buffer.
std::vector< char > DecryptFile (const std::string &path)
Decrypt a file into a buffer.
bool EncryptFile (std::vector< char > &data)
Encrypt a file buffer.
bool EncryptFile (const std::string &path, const std::vector< char > &data)
Encrypt a file from a buffer.
String GenDiffieHellman (const String &g, const String &p, const String &a, int outputSize=-1)
Generate the result of the operation g^a % p.
String GenerateRandom (int sz=-1)
Generates random data to be used during key exchange.
uint32_t GenerateSessionKey ()
Generates a random value.
String HashPassword (const String &password, const String &salt)
Generate a password hash.
std::vector< char > LoadFile (const std::string &path, int requestedSize=-1)
Load a file into a buffer.
String MD5 (const std::vector< char > &data)
Generate a MD5 hash of the given data.
String SHA1 (const std::vector< char > &data)
Generate a SHA-1 hash of the given data.
Detailed Description
Encryption and Decryption functions.
Function Documentation
bool libcomp::Crypto::DecryptFile (std::vector< char > & buffer)
Decrypt a file buffer.
Parameters
buffer Buffer of the file to be decrypted.
Return values
true File was decrypted.
false File was not decrypted.
See Also
Decrypt::EncryptFile
Config::ENCRYPTED_FILE_MAGIC
Config::ENCRYPTED_FILE_KEY
Config::ENCRYPTED_FILE_IV
Definition at line 178 of file src/Crypto.cpp.
References libcomp::Crypto::Blowfish::DecryptCbc(), libcomp::Config::ENCRYPTED_FILE_MAGIC, and EncryptedFileHeader_t.
Referenced by libcomp::DataStore::DecryptFile(), DecryptFile(), and TEST().
std::vector< char > libcomp::Crypto::DecryptFile (const std::string & path)
Decrypt a file into a buffer.
Parameters
path Path to the file to be decrypted.
Returns
Buffer of the decrypted file. Will be empty if an error occurred.
See Also
Decrypt::EncryptFile
Config::ENCRYPTED_FILE_MAGIC
Config::ENCRYPTED_FILE_KEY
Config::ENCRYPTED_FILE_IV
Definition at line 215 of file src/Crypto.cpp.
References DecryptFile(), and LoadFile().
bool libcomp::Crypto::EncryptFile (std::vector< char > & data)
Encrypt a file buffer.
Parameters
buffer Buffer of the file to be encrypted.
Return values
true File was encrypted.
false File was not encrypted.
See Also
Decrypt::DecryptFile
Config::ENCRYPTED_FILE_MAGIC
Config::ENCRYPTED_FILE_KEY
Config::ENCRYPTED_FILE_IV
Definition at line 224 of file src/Crypto.cpp.
References libcomp::Crypto::Blowfish::EncryptCbc(), libcomp::Config::ENCRYPTED_FILE_MAGIC, and EncryptedFileHeader_t.
Referenced by libcomp::DataStore::EncryptFile(), and TEST().
bool libcomp::Crypto::EncryptFile (const std::string & path, const std::vector< char > & data)
Encrypt a file from a buffer.
Parameters
Path to the file to be written to.
data Data to be encrypted.
Return values
true File was encrypted.
false File was not encrypted.
See Also
Decrypt::DecryptFile
Config::ENCRYPTED_FILE_MAGIC
Config::ENCRYPTED_FILE_KEY
Config::ENCRYPTED_FILE_IV
Definition at line 241 of file src/Crypto.cpp.
References libcomp::Crypto::Blowfish::EncryptCbc(), libcomp::Config::ENCRYPTED_FILE_MAGIC, and EncryptedFileHeader_t.
String libcomp::Crypto::GenDiffieHellman (const String & g, const String & p, const String & a, int outputSize = -1)
Generate the result of the operation g^a % p.
Parameters
g Base number represented as a base-16 string.
p Prime number represented as a base-16 string.
a Secret number represented as a base-16 string.
outputSize Number of characters to output. Smaller values will be padded with zeros. Any value of 0 or less will disable output padding.
Returns
A base-16 string representing the operation g^a % p or an empty string if an error occured.
Definition at line 1007 of file src/Crypto.cpp.
References libcomp::String::C(), and libcomp::String::RightJustified().
Referenced by TEST().
String libcomp::Crypto::GenerateRandom (int sz = -1)
Generates random data to be used during key exchange.
The returned data will be a series of hex digits.
Parameters
sz Number of digits of random data to generate. If -1 is used, the default number of digits will be generated (80 digits).
Returns
The random data encoded as a base-16 string or an empty string if an error occured.
Definition at line 319 of file src/Crypto.cpp.
References EXCEPTION, libcomp::Platform::GetLastErrorString(), and LoadFile().
Referenced by libcomp::BaseServer::LoadDataFromFile(), libcomp::Randomizer::SeedRNG(), and TEST().
uint32_t libcomp::Crypto::GenerateSessionKey ()
Generates a random value.
This value is used to identify a login session when passing an authenticated user from the lobby server to the channel server.
Returns
Random value to identify a transitioning client or 0 if an error occured.
Definition at line 404 of file src/Crypto.cpp.
References LoadFile().
Referenced by TEST().
String libcomp::Crypto::HashPassword (const String & password, const String & salt)
Generate a password hash.
Parameters
password Clear text password to hash.
salt Salt to append to the password before hashing.
Returns
Hash for the given password.
Definition at line 1298 of file src/Crypto.cpp.
References libcomp::String::ToUtf8().
Referenced by libcomp::BaseServer::LoadDataFromFile(), and TEST().
std::vector< char > libcomp::Crypto::LoadFile (const std::string & path, int requestedSize = -1)
Load a file into a buffer.
Parameters
path Path to the file to be loaded.
requestedSize Number of bytes to read from the file. If this is negative, the entire file will be read.
Returns
The loaded file data or an empty vector if an error occured.
Definition at line 262 of file src/Crypto.cpp.
Referenced by DecryptFile(), GenerateRandom(), GenerateSessionKey(), libcomp::ScriptEngine::Include(), and TEST().
String libcomp::Crypto::MD5 (const std::vector< char > & data)
Generate a MD5 hash of the given data.
Parameters
data Data to generate the hash of.
Returns
MD5 hash string of the given data.
Definition at line 1345 of file src/Crypto.cpp.
Referenced by TEST().
String libcomp::Crypto::SHA1 (const std::vector< char > & data)
Generate a SHA-1 hash of the given data.
Parameters
data Data to generate the hash of.
Returns
SHA-1 hash string of the given data.
Definition at line 1322 of file src/Crypto.cpp.
Referenced by libcomp::DataStore::GetHash(), and TEST().