COMP_hack: rbtree.h File Reference
rbtree.h File Reference
Classes
struct rbtree_node
struct rbtree
Macros
#define rbtree_nil_value 0
Typedefs
typedef int(* compare_func)(rbtree_key left, rbtree_key right)
typedef void * rbtree_key
typedef void * rbtree_value
Enumerations
enum rbtree_node_color { RED, BLACK }
Functions
rbtree rbtree_create ()
void rbtree_delete (rbtree t, rbtree_key key, compare_func compare)
void rbtree_insert (rbtree t, rbtree_key key, rbtree_value value, compare_func compare)
rbtree_value rbtree_lookup (rbtree t, rbtree_key key, compare_func compare)
rbtree_value rbtree_take (rbtree t, rbtree_key key, compare_func compare)
Macro Definition Documentation
#define rbtree_nil_value 0
Definition at line 25 of file rbtree.h.
Referenced by rbtree_take().
Typedef Documentation
typedef int(* compare_func)(rbtree_key left, rbtree_key right)
Definition at line 42 of file rbtree.h.
typedef void* rbtree_key
Definition at line 22 of file rbtree.h.
typedef void* rbtree_value
Definition at line 23 of file rbtree.h.
Enumeration Type Documentation
enum rbtree_node_color
Enumerator
RED
BLACK
Definition at line 27 of file rbtree.h.
Function Documentation
rbtree rbtree_create ()
Definition at line 132 of file rbtree.c.
References verify_properties().
Referenced by libcomp::MemoryManager::Setup().
void rbtree_delete (rbtree t, rbtree_key key, compare_func compare)
Definition at line 278 of file rbtree.c.
References BLACK, delete_case1(), lookup_node(), maximum_node(), node_color(), replace_node(), and verify_properties().
void rbtree_insert (rbtree t, rbtree_key key, rbtree_value value, compare_func compare)
Definition at line 203 of file rbtree.c.
References insert_case1(), new_node(), RED, and verify_properties().
Referenced by libcomp::MemoryManager::Allocate().
rbtree_value rbtree_lookup (rbtree t, rbtree_key key, compare_func compare)
Definition at line 165 of file rbtree.c.
References lookup_node().
rbtree_value rbtree_take (rbtree t, rbtree_key key, compare_func compare)
Definition at line 303 of file rbtree.c.
References BLACK, delete_case1(), lookup_node(), maximum_node(), node_color(), rbtree_nil_value, replace_node(), and verify_properties().
Referenced by libcomp::MemoryManager::Deallocate().