COMP_hack: rbtree.c File Reference
rbtree.c File Reference
#include "rbtree.h"
#include <assert.h>
#include <stdlib.h>
Typedefs
typedef enum rbtree_node_color color
typedef rbtree_node node
Functions
static void delete_case1 (rbtree t, node n)
static void delete_case2 (rbtree t, node n)
static void delete_case3 (rbtree t, node n)
static void delete_case4 (rbtree t, node n)
static void delete_case5 (rbtree t, node n)
static void delete_case6 (rbtree t, node n)
static node grandparent (node n)
static void insert_case1 (rbtree t, node n)
static void insert_case2 (rbtree t, node n)
static void insert_case3 (rbtree t, node n)
static void insert_case4 (rbtree t, node n)
static void insert_case5 (rbtree t, node n)
static node lookup_node (rbtree t, void *key, compare_func compare)
static node maximum_node (node root)
static node new_node (void *key, void *value, color node_color, node left, node right)
color node_color (node n)
rbtree rbtree_create ()
void rbtree_delete (rbtree t, rbtree_key key, compare_func compare)
void rbtree_insert (rbtree t, rbtree_key key, rbtree_value value, compare_func compare)
rbtree_value rbtree_lookup (rbtree t, rbtree_key key, compare_func compare)
rbtree_value rbtree_take (rbtree t, rbtree_key key, compare_func compare)
static void replace_node (rbtree t, node oldn, node newn)
static void rotate_left (rbtree t, node n)
static void rotate_right (rbtree t, node n)
static node sibling (node n)
static node uncle (node n)
static void verify_properties (rbtree t)
Typedef Documentation
typedef enum rbtree_node_color color
Definition at line 21 of file rbtree.c.
typedef rbtree_node node
Definition at line 20 of file rbtree.c.
Function Documentation
void delete_case1 (rbtree t, node n) static
Definition at line 338 of file rbtree.c.
References delete_case2().
Referenced by delete_case3(), rbtree_delete(), and rbtree_take().
void delete_case2 (rbtree t, node n) static
Definition at line 344 of file rbtree.c.
References BLACK, delete_case3(), node_color(), RED, rotate_left(), rotate_right(), and sibling().
Referenced by delete_case1().
void delete_case3 (rbtree t, node n) static
Definition at line 355 of file rbtree.c.
References BLACK, delete_case1(), delete_case4(), node_color(), RED, and sibling().
Referenced by delete_case2().
void delete_case4 (rbtree t, node n) static
Definition at line 367 of file rbtree.c.
References BLACK, delete_case5(), node_color(), RED, and sibling().
Referenced by delete_case3().
void delete_case5 (rbtree t, node n) static
Definition at line 379 of file rbtree.c.
References BLACK, delete_case6(), node_color(), RED, rotate_left(), rotate_right(), and sibling().
Referenced by delete_case4().
void delete_case6 (rbtree t, node n) static
Definition at line 400 of file rbtree.c.
References BLACK, node_color(), RED, rotate_left(), rotate_right(), and sibling().
Referenced by delete_case5().
node grandparent (node n) static
Definition at line 55 of file rbtree.c.
Referenced by insert_case3(), insert_case4(), and insert_case5().
void insert_case1 (rbtree t, node n) static
Definition at line 236 of file rbtree.c.
References BLACK, and insert_case2().
Referenced by insert_case3(), and rbtree_insert().
void insert_case2 (rbtree t, node n) static
Definition at line 242 of file rbtree.c.
References BLACK, insert_case3(), and node_color().
Referenced by insert_case1().
void insert_case3 (rbtree t, node n) static
Definition at line 248 of file rbtree.c.
References BLACK, grandparent(), insert_case1(), insert_case4(), node_color(), RED, and uncle().
Referenced by insert_case2().
void insert_case4 (rbtree t, node n) static
Definition at line 258 of file rbtree.c.
References grandparent(), insert_case5(), rotate_left(), and rotate_right().
Referenced by insert_case3().
void insert_case5 (rbtree t, node n) static
Definition at line 268 of file rbtree.c.
References BLACK, grandparent(), RED, rotate_left(), and rotate_right().
Referenced by insert_case4().
node lookup_node (rbtree t, void * key, compare_func compare) static
Definition at line 150 of file rbtree.c.
Referenced by rbtree_delete(), rbtree_lookup(), and rbtree_take().
static node maximum_node (node root) static
Definition at line 331 of file rbtree.c.
Referenced by rbtree_delete(), and rbtree_take().
node new_node (void * key, void * value, color node_color, node left, node right) static
Definition at line 138 of file rbtree.c.
References node_color().
Referenced by rbtree_insert().
color node_color (node n)
Definition at line 97 of file rbtree.c.
References BLACK.
Referenced by delete_case2(), delete_case3(), delete_case4(), delete_case5(), delete_case6(), insert_case2(), insert_case3(), new_node(), rbtree_delete(), and rbtree_take().
rbtree rbtree_create ()
Definition at line 132 of file rbtree.c.
References verify_properties().
Referenced by libcomp::MemoryManager::Setup().
void rbtree_delete (rbtree t, rbtree_key key, compare_func compare)
Definition at line 278 of file rbtree.c.
References BLACK, delete_case1(), lookup_node(), maximum_node(), node_color(), replace_node(), and verify_properties().
void rbtree_insert (rbtree t, rbtree_key key, rbtree_value value, compare_func compare)
Definition at line 203 of file rbtree.c.
References insert_case1(), new_node(), RED, and verify_properties().
Referenced by libcomp::MemoryManager::Allocate().
rbtree_value rbtree_lookup (rbtree t, rbtree_key key, compare_func compare)
Definition at line 165 of file rbtree.c.
References lookup_node().
rbtree_value rbtree_take (rbtree t, rbtree_key key, compare_func compare)
Definition at line 303 of file rbtree.c.
References BLACK, delete_case1(), lookup_node(), maximum_node(), node_color(), rbtree_nil_value, replace_node(), and verify_properties().
Referenced by libcomp::MemoryManager::Deallocate().
void replace_node (rbtree t, node oldn, node newn) static
Definition at line 190 of file rbtree.c.
Referenced by rbtree_delete(), rbtree_take(), rotate_left(), and rotate_right().
void rotate_left (rbtree t, node n) static
Definition at line 169 of file rbtree.c.
References replace_node().
Referenced by delete_case2(), delete_case5(), delete_case6(), insert_case4(), and insert_case5().
void rotate_right (rbtree t, node n) static
Definition at line 180 of file rbtree.c.
References replace_node().
Referenced by delete_case2(), delete_case5(), delete_case6(), insert_case4(), and insert_case5().
node sibling (node n) static
Definition at line 61 of file rbtree.c.
Referenced by delete_case2(), delete_case3(), delete_case4(), delete_case5(), delete_case6(), and uncle().
node uncle (node n) static
Definition at line 69 of file rbtree.c.
References sibling().
Referenced by insert_case3().
void verify_properties (rbtree t) static
Definition at line 75 of file rbtree.c.
Referenced by rbtree_create(), rbtree_delete(), rbtree_insert(), and rbtree_take().