COMP_hack: ScriptEngine.cpp File Reference
src/ScriptEngine.cpp File Reference
Class to manage Squirrel scripting.
#include "ScriptEngine.h"
#include "BaseServer.h"
#include "Constants.h"
#include "Database.h"
#include "Crypto.h"
#include "DefinitionManager.h"
#include "Log.h"
#include "ServerDataManager.h"
#include <Account.h>
#include <AccountWorldData.h>
#include <BazaarData.h>
#include <BazaarItem.h>
#include <Character.h>
#include <Demon.h>
#include <RegisteredChannel.h>
#include <RegisteredWorld.h>
#include <cstdio>
#include <cstdarg>
#include <sqstdmath.h>
#include <sqstdstring.h>
#include <sqstdaux.h>
Functions
static bool ScriptImport (HSQUIRRELVM vm, const char *szModule)
static bool ScriptInclude (HSQUIRRELVM vm, const char *szPath)
static void SquirrelErrorFunction (HSQUIRRELVM vm, const SQChar *szFormat,...)
static void SquirrelErrorFunctionRaw (HSQUIRRELVM vm, const SQChar *szFormat,...)
static void SquirrelPrintFunction (HSQUIRRELVM vm, const SQChar *szFormat,...)
static void SquirrelPrintFunctionRaw (HSQUIRRELVM vm, const SQChar *szFormat,...)
static std::shared_ptr
< objects::Account > ToAccount (const std::shared_ptr< libcomp::PersistentObject > &obj)
static std::shared_ptr
< objects::AccountWorldData > ToAccountWorldData (const std::shared_ptr< libcomp::PersistentObject > &obj)
static std::shared_ptr
< objects::Character > ToCharacter (const std::shared_ptr< libcomp::PersistentObject > &obj)
static std::shared_ptr
< objects::Demon > ToDemon (const std::shared_ptr< libcomp::PersistentObject > &obj)
Variables
const SQBool NO_RETURN_VALUE = SQFalse
const SQInteger ONE_PARAM = 1
const SQBool RAISE_ERROR = SQTrue
Detailed Description
Class to manage Squirrel scripting.
Author
COMP Omega compo.nosp@m.mega.nosp@m.@tuta.nosp@m.nota.nosp@m..com
This file is part of the COMP_hack Library (libcomp).
Copyright (C) 2012-2020 COMP_hack Team compo.nosp@m.mega.nosp@m.@tuta.nosp@m.nota.nosp@m..com
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Definition in file src/ScriptEngine.cpp.
Function Documentation
static bool ScriptImport (HSQUIRRELVM vm, const char * szModule) static
Definition at line 96 of file src/ScriptEngine.cpp.
References libcomp::ScriptEngine::Self().
Referenced by libcomp::ScriptEngine::ScriptEngine().
static bool ScriptInclude (HSQUIRRELVM vm, const char * szPath) static
Definition at line 91 of file src/ScriptEngine.cpp.
References libcomp::ScriptEngine::Self().
Referenced by libcomp::ScriptEngine::ScriptEngine().
static void SquirrelErrorFunction (HSQUIRRELVM vm, const SQChar * szFormat, ...) static
Definition at line 131 of file src/ScriptEngine.cpp.
References libcomp::String::Arg(), and libcomp::String::Split().
Referenced by libcomp::ScriptEngine::ScriptEngine().
static void SquirrelErrorFunctionRaw (HSQUIRRELVM vm, const SQChar * szFormat, ...) static
Definition at line 186 of file src/ScriptEngine.cpp.
References libcomp::String::Split().
Referenced by libcomp::ScriptEngine::ScriptEngine().
static void SquirrelPrintFunction (HSQUIRRELVM vm, const SQChar * szFormat, ...) static
Definition at line 101 of file src/ScriptEngine.cpp.
References libcomp::String::Arg(), and libcomp::String::Split().
Referenced by libcomp::ScriptEngine::ScriptEngine().
static void SquirrelPrintFunctionRaw (HSQUIRRELVM vm, const SQChar * szFormat, ...) static
Definition at line 161 of file src/ScriptEngine.cpp.
References libcomp::String::Split().
Referenced by libcomp::ScriptEngine::ScriptEngine().
static std::shared_ptr<objects::Account> ToAccount (const std::shared_ptr< libcomp::PersistentObject > & obj) static
Definition at line 67 of file src/ScriptEngine.cpp.
Referenced by libcomp::ScriptEngine::ScriptEngine().
static std::shared_ptr<objects::AccountWorldData> ToAccountWorldData (const std::shared_ptr< libcomp::PersistentObject > & obj) static
Definition at line 73 of file src/ScriptEngine.cpp.
Referenced by libcomp::ScriptEngine::ScriptEngine().
static std::shared_ptr<objects::Character> ToCharacter (const std::shared_ptr< libcomp::PersistentObject > & obj) static
Definition at line 79 of file src/ScriptEngine.cpp.
Referenced by libcomp::ScriptEngine::ScriptEngine().
static std::shared_ptr<objects::Demon> ToDemon (const std::shared_ptr< libcomp::PersistentObject > & obj) static
Definition at line 85 of file src/ScriptEngine.cpp.
References libcomp::Demon.
Referenced by libcomp::ScriptEngine::ScriptEngine().
Variable Documentation
const SQBool NO_RETURN_VALUE = SQFalse
Definition at line 61 of file src/ScriptEngine.cpp.
Referenced by libcomp::ScriptEngine::Eval().
const SQInteger ONE_PARAM = 1
Definition at line 60 of file src/ScriptEngine.cpp.
Referenced by libcomp::ScriptEngine::Eval().
const SQBool RAISE_ERROR = SQTrue
Definition at line 62 of file src/ScriptEngine.cpp.
Referenced by libcomp::ScriptEngine::Eval().