COMP_hack: Crypto.cpp File Reference
src/Crypto.cpp File Reference
Encryption and decryption function implementations.
#include "Crypto.h"
#include "Config.h"
#include "Endian.h"
#include "Exception.h"
#include "Log.h"
#include "Packet.h"
#include "Platform.h"
#include <openssl/blowfish.h>
#include <openssl/bn.h>
#include <openssl/crypto.h>
#include <openssl/dh.h>
#include <openssl/md5.h>
#include <openssl/sha.h>
#include "CryptSupport.h"
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <cassert>
#include <fstream>
#include <iomanip>
#include <sstream>
#include <cstdio>
#include <cstdlib>
Classes
struct libcomp::Crypto::BlowfishPrivate
struct libcomp::Crypto::DiffieHellmanPrivate
Namespaces
libcomp
libcomp Includes
libcomp::Crypto
Encryption and Decryption functions.
Macros
#define INITIALIZER(f)
Functions
struct __attribute__ ((packed))
Header for an encrypted file.
static String GetDiffieHellmanPrime (const DH *pDiffieHellman)
INITIALIZER (InitDecrypt)
Setup the Blowfish key when the application starts.
Variables
EncryptedFileHeader_t
Detailed Description
Encryption and decryption function implementations.
Author
COMP Omega compo.nosp@m.mega.nosp@m.@tuta.nosp@m.nota.nosp@m..com
This file is part of the COMP_hack Library (libcomp).
Copyright (C) 2012-2020 COMP_hack Team compo.nosp@m.mega.nosp@m.@tuta.nosp@m.nota.nosp@m..com
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Definition in file src/Crypto.cpp.
Macro Definition Documentation
#define INITIALIZER (f)
Value:
static void f(void) __attribute__((constructor)); \
    static void f(void)
Definition at line 142 of file src/Crypto.cpp.
Function Documentation
struct __attribute__ ((packed))
Header for an encrypted file.
Magic to identify the file type.
Size (in bytes) of the file after decryption.
Definition at line 165 of file src/Crypto.cpp.
static String GetDiffieHellmanPrime (const DH * pDiffieHellman) static
Definition at line 1573 of file src/Crypto.cpp.
References libcomp::String::Clear(), DH_get0_p(), and libcomp::String::Length().
Referenced by libcomp::Crypto::DiffieHellman::Generate().
INITIALIZER (InitDecrypt)
Setup the Blowfish key when the application starts.
Definition at line 150 of file src/Crypto.cpp.
References libcomp::Config::ENCRYPTED_FILE_IV, libcomp::Config::ENCRYPTED_FILE_KEY, and libcomp::Config::ENCRYPTED_FILE_MAGIC.
Variable Documentation
EncryptedFileHeader_t
Definition at line 173 of file src/Crypto.cpp.
Referenced by libcomp::Crypto::DecryptFile(), and libcomp::Crypto::EncryptFile().