COMP_hack: Convert.cpp File Reference
src/Convert.cpp File Reference
Routines to convert strings between encodings.
#include "Convert.h"
#include "Endian.h"
#include "Exception.h"
#include "Log.h"
#include "LookupTableCP1252.h"
#include "LookupTableCP932.h"
#include <limits.h>
#include <stdint.h>
Macros
#define ARRAY_SIZE(arr) (sizeof(arr)/sizeof(arr[0]))
Functions
static String FromCP1252Encoding (const uint8_t *szString, int size)
Convert a CP-1252 encoded string to a String.
static String FromCP932Encoding (const uint8_t *szString, int size)
Convert a CP-932 encoded string to a String.
static std::vector< char > ToCP1252Encoding (const String &str, bool nullTerminator=true)
Convert the String to a CP-1252 encoded string.
static std::vector< char > ToCP932Encoding (const String &str, bool nullTerminator=true)
Convert the String to a CP-932 encoded string.
Detailed Description
Routines to convert strings between encodings.
Author
COMP Omega compo.nosp@m.mega.nosp@m.@tuta.nosp@m.nota.nosp@m..com
This file is part of the COMP_hack Library (libcomp).
Copyright (C) 2012-2020 COMP_hack Team compo.nosp@m.mega.nosp@m.@tuta.nosp@m.nota.nosp@m..com
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Definition in file src/Convert.cpp.
Macro Definition Documentation
#define ARRAY_SIZE (arr) (sizeof(arr)/sizeof(arr[0]))
Definition at line 41 of file src/Convert.cpp.
Referenced by ToCP932Encoding().
Function Documentation
static String FromCP1252Encoding (const uint8_t * szString, int size) static
Convert a CP-1252 encoded string to a String.
Parameters
szString The string to convert.
size Optional size of the string.
Returns
The converted string.
Definition at line 77 of file src/Convert.cpp.
References libcomp::String::FromCodePoint(), and LookupTableCP1252.
Referenced by libcomp::Convert::FromEncoding().
static String FromCP932Encoding (const uint8_t * szString, int size) static
Convert a CP-932 encoded string to a String.
Parameters
szString The string to convert.
size Optional size of the string.
Returns
The converted string.
Todo:
Consider throwing an exception as well (conversion exceptions should be enabled by a #define).
Definition at line 127 of file src/Convert.cpp.
References libcomp::String::FromCodePoint(), and LookupTableCP932.
Referenced by libcomp::Convert::FromEncoding().
static std::vector< char > ToCP1252Encoding (const String & str, bool nullTerminator = true) static
Convert the String to a CP-1252 encoded string.
Parameters
str String to convert.
nullTerminator Indicates if a null terminator should be added.
Returns
The converted string.
Definition at line 199 of file src/Convert.cpp.
References libcomp::String::At(), libcomp::String::Length(), and LookupTableCP1252.
Referenced by libcomp::Convert::ToEncoding().
static std::vector< char > ToCP932Encoding (const String & str, bool nullTerminator = true) static
Convert the String to a CP-932 encoded string.
Parameters
str String to convert.
nullTerminator Indicates if a null terminator should be added.
Returns
The converted string.
Definition at line 235 of file src/Convert.cpp.
References ARRAY_SIZE, libcomp::String::At(), libcomp::String::Length(), libcomp::Exception::Log(), and LookupTableCP932.
Referenced by libcomp::Convert::ToEncoding().