COMP_hack: String.cpp File Reference
String.cpp File Reference
Unicode string class unit tests.
#include <PushIgnore.h>
#include <gtest/gtest.h>
#include <PopIgnore.h>
#include <CString.h>
Functions
int main (int argc, char *argv[])
TEST (String, Length)
TEST (String, Size)
TEST (String, Compare)
TEST (String, Right)
TEST (String, Left)
TEST (String, Truncate)
TEST (String, Mid)
TEST (String, LeftJustified)
TEST (String, RightJustified)
TEST (String, Append)
TEST (String, Prepend)
TEST (String, Arguments)
TEST (String, ArgInt)
TEST (String, ToUpperLower)
TEST (String, Contains)
TEST (String, Trim)
TEST (String, Clear)
TEST (String, Split)
TEST (String, FromCodePoint)
TEST (String, At)
TEST (String, Replace)
TEST (String, ToInteger)
TEST (String, ArgUnderscoreBug)
Detailed Description
Unicode string class unit tests.
Author
COMP Omega compo.nosp@m.mega.nosp@m.@tuta.nosp@m.nota.nosp@m..com
This file is part of the COMP_hack Library (libcomp).
Copyright (C) 2016-2020 COMP_hack Team compo.nosp@m.mega.nosp@m.@tuta.nosp@m.nota.nosp@m..com
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Definition in file String.cpp.
Function Documentation
int main (int argc, char * argv[])
Definition at line 434 of file String.cpp.
TEST (String , Length)
Definition at line 35 of file String.cpp.
TEST (String , Size)
Definition at line 40 of file String.cpp.
TEST (String , Compare)
Definition at line 45 of file String.cpp.
TEST (String , Right)
Definition at line 66 of file String.cpp.
TEST (String , Left)
Definition at line 84 of file String.cpp.
TEST (String , Truncate)
Definition at line 102 of file String.cpp.
References libcomp::String::Truncate().
TEST (String , Mid)
Definition at line 137 of file String.cpp.
TEST (String , LeftJustified)
Definition at line 151 of file String.cpp.
TEST (String , RightJustified)
Definition at line 172 of file String.cpp.
TEST (String , Append)
Definition at line 193 of file String.cpp.
References libcomp::String::Append().
TEST (String , Prepend)
Definition at line 218 of file String.cpp.
References libcomp::String::Prepend().
TEST (String , Arguments)
Definition at line 230 of file String.cpp.
References libcomp::String::Arg(), libcomp::String::IsReportingBadArguments(), and libcomp::String::SetBadArgumentReporting().
TEST (String , ArgInt)
Definition at line 266 of file String.cpp.
TEST (String , ToUpperLower)
Definition at line 272 of file String.cpp.
TEST (String , Contains)
Definition at line 278 of file String.cpp.
TEST (String , Trim)
Definition at line 288 of file String.cpp.
TEST (String , Clear)
Definition at line 295 of file String.cpp.
References libcomp::String::Clear(), libcomp::String::IsEmpty(), libcomp::String::Length(), and libcomp::String::Size().
TEST (String , Split)
Definition at line 312 of file String.cpp.
References libcomp::String::Split().
TEST (String , FromCodePoint)
Definition at line 325 of file String.cpp.
References libcomp::String::FromCodePoint().
TEST (String , At)
Definition at line 352 of file String.cpp.
References libcomp::String::At().
TEST (String , Replace)
Definition at line 367 of file String.cpp.
References libcomp::String::Replace().
TEST (String , ToInteger)
Definition at line 374 of file String.cpp.
TEST (String , ArgUnderscoreBug)
Definition at line 423 of file String.cpp.
References libcomp::String::Arg(), and libcomp::String::ToUtf8().