COMP_hack: ScriptEngine.cpp File Reference
tests/ScriptEngine.cpp File Reference
Test the Squirrel scripting language interface.
#include <PushIgnore.h>
#include <gtest/gtest.h>
#include <sqrat.h>
#include <PopIgnore.h>
#include <Crypto.h>
#include <Log.h>
#include <Packet.h>
#include <ScriptEngine.h>
#include <TestObject.h>
#include <TestObjectA.h>
#include <TestObjectB.h>
#include <TestObjectC.h>
#include <TestObjectD.h>
#include <TestObjectE.h>
Functions
int main (int argc, char *argv[])
TEST (ScriptEngine, EvalCompileError)
TEST (ScriptEngine, EvalRuntimeError)
TEST (ScriptEngine, EvalPrint)
TEST (ScriptEngine, ReadOnlyPacket)
TEST (ScriptEngine, ReadWriteArray)
TEST (ScriptEngine, FunctionCall)
TEST (ScriptEngine, GeneratedObject)
TEST (ScriptEngine, ScriptA_ScriptB)
TEST (ScriptEngine, ServerA_ScriptB)
TEST (ScriptEngine, ServerA_ServerB)
TEST (ScriptEngine, ScriptA_ServerB)
TEST (ScriptEngine, CString)
TEST (ScriptEngine, DowncastChild)
TEST (ScriptEngine, GetObjectList)
TEST (ScriptEngine, SetObjectList)
TEST (ScriptEngine, SetBadObjectList)
TEST (ScriptEngine, GetObjectListProp)
TEST (ScriptEngine, SetObjectListProp)
TEST (ScriptEngine, SetBadObjectListProp)
TEST (ScriptEngine, ListOfIntegers)
TEST (ScriptEngine, Integer64)
Detailed Description
Test the Squirrel scripting language interface.
Author
COMP Omega compo.nosp@m.mega.nosp@m.@tuta.nosp@m.nota.nosp@m..com
This file is part of the COMP_hack Library (libcomp).
Copyright (C) 2016-2020 COMP_hack Team compo.nosp@m.mega.nosp@m.@tuta.nosp@m.nota.nosp@m..com
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Definition in file tests/ScriptEngine.cpp.
Function Documentation
int main (int argc, char * argv[])
Definition at line 1149 of file tests/ScriptEngine.cpp.
TEST (ScriptEngine , EvalCompileError)
Definition at line 45 of file tests/ScriptEngine.cpp.
References libcomp::Log::AddLogHook(), libcomp::Log::ClearHooks(), libcomp::ScriptEngine::Eval(), libcomp::Log::GetSingletonPtr(), and libcomp::Log::LOG_LEVEL_ERROR.
TEST (ScriptEngine , EvalRuntimeError)
Definition at line 70 of file tests/ScriptEngine.cpp.
References libcomp::Log::AddLogHook(), libcomp::Log::ClearHooks(), libcomp::ScriptEngine::Eval(), libcomp::Log::GetSingletonPtr(), and libcomp::Log::LOG_LEVEL_ERROR.
TEST (ScriptEngine , EvalPrint)
Definition at line 95 of file tests/ScriptEngine.cpp.
References libcomp::Log::AddLogHook(), libcomp::Log::ClearHooks(), libcomp::ScriptEngine::Eval(), libcomp::Log::GetSingletonPtr(), and libcomp::Log::LOG_LEVEL_INFO.
TEST (ScriptEngine , ReadOnlyPacket)
Definition at line 120 of file tests/ScriptEngine.cpp.
References libcomp::Log::AddLogHook(), libcomp::String::Clear(), libcomp::Log::ClearHooks(), libcomp::ScriptEngine::Eval(), libcomp::Log::GetSingletonPtr(), and libcomp::ScriptEngine::Using().
TEST (ScriptEngine , ReadWriteArray)
Definition at line 155 of file tests/ScriptEngine.cpp.
References libcomp::Log::AddLogHook(), libcomp::String::Clear(), libcomp::Log::ClearHooks(), libcomp::ScriptEngine::Eval(), libcomp::Log::GetSingletonPtr(), and libcomp::ScriptEngine::Using().
TEST (ScriptEngine , FunctionCall)
Definition at line 190 of file tests/ScriptEngine.cpp.
References libcomp::Log::AddLogHook(), libcomp::String::Clear(), libcomp::Log::ClearHooks(), libcomp::ScriptEngine::Eval(), libcomp::Log::GetSingletonPtr(), libcomp::ScriptEngine::GetVM(), and libcomp::ScriptEngine::Using().
TEST (ScriptEngine , GeneratedObject)
Definition at line 249 of file tests/ScriptEngine.cpp.
References libcomp::Log::AddLogHook(), libcomp::String::Clear(), libcomp::Log::ClearHooks(), libcomp::ScriptEngine::Eval(), libcomp::Log::GetSingletonPtr(), and libcomp::ScriptEngine::Using().
TEST (ScriptEngine , ScriptA_ScriptB)
Definition at line 289 of file tests/ScriptEngine.cpp.
References libcomp::Log::AddLogHook(), libcomp::String::Clear(), libcomp::Log::ClearHooks(), libcomp::ScriptEngine::Eval(), libcomp::Log::GetSingletonPtr(), libcomp::ScriptEngine::GetVM(), and libcomp::ScriptEngine::Using().
TEST (ScriptEngine , ServerA_ScriptB)
Definition at line 342 of file tests/ScriptEngine.cpp.
References libcomp::Log::AddLogHook(), libcomp::String::Clear(), libcomp::Log::ClearHooks(), libcomp::ScriptEngine::Eval(), libcomp::Log::GetSingletonPtr(), libcomp::ScriptEngine::GetVM(), and libcomp::ScriptEngine::Using().
TEST (ScriptEngine , ServerA_ServerB)
Definition at line 389 of file tests/ScriptEngine.cpp.
References libcomp::Log::AddLogHook(), libcomp::String::Clear(), libcomp::Log::ClearHooks(), libcomp::ScriptEngine::Eval(), libcomp::Log::GetSingletonPtr(), libcomp::ScriptEngine::GetVM(), and libcomp::ScriptEngine::Using().
TEST (ScriptEngine , ScriptA_ServerB)
Definition at line 437 of file tests/ScriptEngine.cpp.
References libcomp::Log::AddLogHook(), libcomp::String::Clear(), libcomp::Log::ClearHooks(), libcomp::ScriptEngine::Eval(), libcomp::Log::GetSingletonPtr(), libcomp::ScriptEngine::GetVM(), and libcomp::ScriptEngine::Using().
TEST (ScriptEngine , CString)
Definition at line 494 of file tests/ScriptEngine.cpp.
References libcomp::Log::AddLogHook(), libcomp::String::Clear(), libcomp::Log::ClearHooks(), libcomp::ScriptEngine::Eval(), libcomp::Log::GetSingletonPtr(), libcomp::ScriptEngine::GetVM(), and libcomp::ScriptEngine::Using().
TEST (ScriptEngine , DowncastChild)
Definition at line 545 of file tests/ScriptEngine.cpp.
References libcomp::Log::AddLogHook(), libcomp::String::Clear(), libcomp::Log::ClearHooks(), libcomp::ScriptEngine::Eval(), libcomp::Log::GetSingletonPtr(), libcomp::ScriptEngine::GetVM(), libcomp::String::Split(), and libcomp::ScriptEngine::Using().
TEST (ScriptEngine , GetObjectList)
Definition at line 608 of file tests/ScriptEngine.cpp.
References libcomp::Log::AddLogHook(), libcomp::String::C(), libcomp::String::Clear(), libcomp::Log::ClearHooks(), libcomp::ScriptEngine::Eval(), libcomp::Log::GetSingletonPtr(), libcomp::ScriptEngine::GetVM(), and libcomp::ScriptEngine::Using().
TEST (ScriptEngine , SetObjectList)
Definition at line 679 of file tests/ScriptEngine.cpp.
References libcomp::Log::AddLogHook(), libcomp::String::Clear(), libcomp::Log::ClearHooks(), libcomp::ScriptEngine::Eval(), libcomp::Log::GetSingletonPtr(), libcomp::ScriptEngine::GetVM(), and libcomp::ScriptEngine::Using().
TEST (ScriptEngine , SetBadObjectList)
Definition at line 746 of file tests/ScriptEngine.cpp.
References libcomp::Log::AddLogHook(), libcomp::String::Clear(), libcomp::Log::ClearHooks(), libcomp::ScriptEngine::Eval(), libcomp::Log::GetSingletonPtr(), libcomp::ScriptEngine::GetVM(), libcomp::String::Split(), and libcomp::ScriptEngine::Using().
TEST (ScriptEngine , GetObjectListProp)
Definition at line 803 of file tests/ScriptEngine.cpp.
References libcomp::Log::AddLogHook(), libcomp::String::C(), libcomp::String::Clear(), libcomp::Log::ClearHooks(), libcomp::ScriptEngine::Eval(), libcomp::Log::GetSingletonPtr(), libcomp::ScriptEngine::GetVM(), and libcomp::ScriptEngine::Using().
TEST (ScriptEngine , SetObjectListProp)
Definition at line 874 of file tests/ScriptEngine.cpp.
References libcomp::Log::AddLogHook(), libcomp::String::Clear(), libcomp::Log::ClearHooks(), libcomp::ScriptEngine::Eval(), libcomp::Log::GetSingletonPtr(), libcomp::ScriptEngine::GetVM(), and libcomp::ScriptEngine::Using().
TEST (ScriptEngine , SetBadObjectListProp)
Definition at line 941 of file tests/ScriptEngine.cpp.
References libcomp::Log::AddLogHook(), libcomp::String::Clear(), libcomp::Log::ClearHooks(), libcomp::ScriptEngine::Eval(), libcomp::Log::GetSingletonPtr(), libcomp::ScriptEngine::GetVM(), libcomp::String::Split(), and libcomp::ScriptEngine::Using().
TEST (ScriptEngine , ListOfIntegers)
Definition at line 998 of file tests/ScriptEngine.cpp.
References libcomp::Log::AddLogHook(), libcomp::String::Clear(), libcomp::Log::ClearHooks(), libcomp::ScriptEngine::Eval(), libcomp::Log::GetSingletonPtr(), libcomp::ScriptEngine::GetVM(), and libcomp::ScriptEngine::Using().
TEST (ScriptEngine , Integer64)
Definition at line 1065 of file tests/ScriptEngine.cpp.
References libcomp::Log::AddLogHook(), libcomp::String::Clear(), libcomp::Log::ClearHooks(), libcomp::ScriptEngine::Eval(), libcomp::Crypto::GenerateSessionKey(), libcomp::Log::GetSingletonPtr(), libcomp::ScriptEngine::GetVM(), and libcomp::ScriptEngine::Using().