COMP_hack: lobby::LobbyServer Class Reference
lobby::LobbyServer Class Reference
#include <LobbyServer.h>
Public Types
typedef std::unordered_map
< std::string, std::list
< std::shared_ptr
< libcomp::PersistentObject > > > PersistentObjectMap
Public Member Functions
LobbyServer (const char *szProgram, std::shared_ptr< objects::ServerConfig > config, std::shared_ptr< libcomp::ServerCommandLineParser > commandLine, bool unitTestMode)
Create a new lobby server.
virtual ~LobbyServer ()
Clean up the server.
libcomp::String CheckImportObject (const libcomp::String &objectType, const std::shared_ptr< libcomp::PersistentObject > &obj, const std::shared_ptr< libcomp::Database > &lobbyDB, const std::shared_ptr< libcomp::Database > &worldDB)
Check if an import object may be imported.
virtual void Cleanup ()
virtual void FinishInitialize ()
AccountManager * GetAccountManager ()
Get the account manager for the server.
std::shared_ptr
< objects::ServerConfig > GetConfig () const
std::shared_ptr< Database > GetDatabase (const EnumMap< objects::ServerConfig::DatabaseType_t, std::shared_ptr< objects::DatabaseConfig >> &configMap, bool performSetup, DataStore *pDataStore=nullptr, const std::string &migrationDirectory=std::string())
DataStore * GetDataStore ()
libcomp::String GetFakeAccountSalt (const libcomp::String &username)
Get the same fake salt for an account that does not exist.
LobbySyncManager * GetLobbySyncManager () const
Get a pointer to the data sync manager.
std::shared_ptr
< libcomp::Database > GetMainDatabase () const
Get the main database.
std::shared_ptr
< ManagerConnection > GetManagerConnection () const
Get the connection manager for the server.
virtual std::list
< libcomp::Message::MessageType > GetSupportedTypes () const
TimerManager * GetTimerManager ()
std::shared_ptr< lobby::World > GetWorldByConnection (std::shared_ptr< libcomp::InternalConnection > connection)
Get information about a connected world by its connection.
std::shared_ptr< lobby::World > GetWorldByID (uint8_t worldID)
Get a world by ID.
std::list< std::shared_ptr
< lobby::World > > GetWorlds () const
Get a list of pointers to the connected worlds.
libcomp::String ImportAccount (const libcomp::String &data, uint8_t worldID=0)
Import an account into the database.
virtual bool Initialize ()
Initialize the database connection and do anything else that can fail to execute that needs to be handled outside of a constructor.
virtual bool ProcessMessage (const libcomp::Message::Message *pMessage)
bool QueueWork (Function &&f, Args &&...args) const
const std::shared_ptr
< lobby::World > RegisterWorld (std::shared_ptr< lobby::World > &world)
Register a world with the connection manager.
void RemoveConnection (std::shared_ptr< TcpConnection > &connection)
void SendWorldList (const std::shared_ptr< libcomp::TcpConnection > &connection) const
Send the world list to either one or all client connections.
virtual void ServerReady ()
virtual void Shutdown ()
virtual int Start (bool delayReady=false)
Static Public Member Functions
static std::shared_ptr
< Crypto::DiffieHellman > GenerateDiffieHellman ()
static std::string GetConfigPath ()
static std::shared_ptr< Database > GetDatabase (objects::ServerConfig::DatabaseType_t dbType, const EnumMap< objects::ServerConfig::DatabaseType_t, std::shared_ptr< objects::DatabaseConfig >> &configMap)
static std::string GetDefaultConfigPath ()
static std::shared_ptr
< Crypto::DiffieHellman > LoadDiffieHellman (const String &prime)
static bool ReadConfig (std::shared_ptr< objects::ServerConfig > config, tinyxml2::XMLDocument &doc)
static bool ReadConfig (std::shared_ptr< objects::ServerConfig > config, libcomp::String filePath)
static void SetConfigPath (const std::string &path)
Protected Member Functions
void AcceptHandler (asio::error_code errorCode, asio::ip::tcp::socket &socket)
bool AssignMessageQueue (const std::shared_ptr< libcomp::EncryptedConnection > &connection)
virtual std::shared_ptr
< libcomp::TcpConnection > CreateConnection (asio::ip::tcp::socket &socket)
Create a connection to a newly active socket.
void CreateFirstAccount ()
Create the first account when none currently exist in the connected database via PromptCreateAccount.
void CreateWorkers ()
std::shared_ptr
< Crypto::DiffieHellman > GetDiffieHellman () const
virtual std::shared_ptr
< libcomp::Worker > GetNextConnectionWorker ()
bool InsertDataFromFile (const libcomp::String &filePath, const std::shared_ptr< Database > &db, const std::set< std::string > &specificTypes={})
bool LoadDataFromFile (const libcomp::String &filePath, PersistentObjectMap &records, bool registerRecords, const std::set< std::string > &specificTypes={})
void PromptCreateAccount ()
Prompt for and create an account via pre-populated or user entered values.
bool ResetRegisteredWorlds ()
Reset the values in the RegisteredWorld table, pulling World information from it before servers connect.
virtual int Run ()
void SetDiffieHellman (const std::shared_ptr< Crypto::DiffieHellman > &diffieHellman)
bool Setup ()
Setup the server based on the setup config file.
Protected Attributes
AccountManager * mAccountManager
Account manager for the server.
std::shared_ptr
< ServerCommandLineParser > mCommandLine
std::shared_ptr
< objects::ServerConfig > mConfig
std::list< std::shared_ptr
< TcpConnection > > mConnections
std::mutex mConnectionsLock
std::shared_ptr
< libcomp::Database > mDatabase
A shared pointer to the main database used by the server.
libcomp::DataStore mDataStore
std::unordered_map
< libcomp::String,
libcomp::String > mFakeSalts
Mapping of fake salts for usernames that do not exist.
std::mutex mFakeSaltsLock
Lock for the fake salts.
libcomp::Worker mMainWorker
std::shared_ptr
< ManagerConnection > mManagerConnection
Pointer to the manager in charge of connections.
libcomp::Worker mQueueWorker
asio::io_service mService
LobbySyncManager * mSyncManager
Data sync manager for the server.
libcomp::TimerManager mTimerManager
bool mUnitTestMode
Indicates the unit test database should be used.
std::list< std::shared_ptr
< libcomp::Worker > > mWorkers
Static Protected Attributes
static std::string sConfigPath
Detailed Description
Definition at line 51 of file LobbyServer.h.
Constructor & Destructor Documentation
LobbyServer::LobbyServer (const char * szProgram, std::shared_ptr< objects::ServerConfig > config, std::shared_ptr< libcomp::ServerCommandLineParser > commandLine, bool unitTestMode)
Create a new lobby server.
Parameters
szProgram First command line argument for the application.
config Pointer to a casted LobbyConfig that will contain properties every server has in addition to lobby specific ones.
unitTestMode Debug parameter to use in unit tests. Set to true to enable unit test mode.
Definition at line 55 of file LobbyServer.cpp.
LobbyServer::~LobbyServer () virtual
Clean up the server.
Definition at line 166 of file LobbyServer.cpp.
References mAccountManager, and mSyncManager.
Member Function Documentation
libcomp::String LobbyServer::CheckImportObject (const libcomp::String & objectType, const std::shared_ptr< libcomp::PersistentObject > & obj, const std::shared_ptr< libcomp::Database > & lobbyDB, const std::shared_ptr< libcomp::Database > & worldDB)
Check if an import object may be imported.
Parameters
objectType Type string for the object.
obj Object to check.
lobbyDB Database for the lobby.
worldDB Database for the world.
Returns
Error string or an empty string if the object is good.
Definition at line 784 of file LobbyServer.cpp.
References libcomp::String::Arg(), and libcomp::BaseServer::mConfig.
Referenced by ImportAccount().
std::shared_ptr< libcomp::TcpConnection > LobbyServer::CreateConnection (asio::ip::tcp::socket & socket) protected virtual
Create a connection to a newly active socket.
Parameters
socket A new socket connection.
Returns
Pointer to the newly created connection
Reimplemented from libcomp::BaseServer.
Definition at line 266 of file LobbyServer.cpp.
References libcomp::BaseServer::AssignMessageQueue(), libcomp::BaseServer::GetDiffieHellman(), and libcomp::BaseServer::LoadDiffieHellman().
void LobbyServer::CreateFirstAccount () protected
Create the first account when none currently exist in the connected database via PromptCreateAccount.
The user will also be prompted to create more accounts should they want to here.
Definition at line 295 of file LobbyServer.cpp.
References PromptCreateAccount().
Referenced by Initialize().
AccountManager * LobbyServer::GetAccountManager ()
Get the account manager for the server.
Returns
Account manager for the server.
Definition at line 535 of file LobbyServer.cpp.
References mAccountManager.
Referenced by lobby::ManagerConnection::RemoveClientConnection().
libcomp::String LobbyServer::GetFakeAccountSalt (const libcomp::String & username)
Get the same fake salt for an account that does not exist.
Returns
A fake salt for an account that does not exist.
Definition at line 581 of file LobbyServer.cpp.
References libcomp::Crypto::GenerateRandom(), mFakeSalts, and mFakeSaltsLock.
LobbySyncManager * LobbyServer::GetLobbySyncManager () const
Get a pointer to the data sync manager.
Returns
Pointer to the LobbySyncManager
Definition at line 540 of file LobbyServer.cpp.
References mSyncManager.
Referenced by lobby::AccountManager::DeleteCharacter().
std::shared_ptr< libcomp::Database > LobbyServer::GetMainDatabase () const
Get the main database.
Returns
Pointer to the main database
Definition at line 256 of file LobbyServer.cpp.
References mDatabase.
Referenced by lobby::AccountManager::DeleteCharacter(), lobby::AccountManager::DeleteKillTimeExceededCharacters(), lobby::AccountManager::GetOrCreateLogin(), ImportAccount(), lobby::AccountManager::SetCharacterOnAccount(), and SetWorldInfoFromPacket().
std::shared_ptr< ManagerConnection > LobbyServer::GetManagerConnection () const
Get the connection manager for the server.
Returns
Pointer to the connection manager.
Definition at line 261 of file LobbyServer.cpp.
References mManagerConnection.
std::shared_ptr< lobby::World > LobbyServer::GetWorldByConnection (std::shared_ptr< libcomp::InternalConnection > connection)
Get information about a connected world by its connection.
Parameters
connection Pointer to the world's connection.
Returns
Pointer to the connected world.
Definition at line 182 of file LobbyServer.cpp.
References mManagerConnection.
std::shared_ptr< lobby::World > LobbyServer::GetWorldByID (uint8_t worldID)
Get a world by ID.
Parameters
worldID ID of the world to load
Returns
Pointer to the matching world
Definition at line 177 of file LobbyServer.cpp.
References mManagerConnection.
Referenced by lobby::AccountManager::DeleteKillTimeExceededCharacters(), and ImportAccount().
std::list< std::shared_ptr< lobby::World > > LobbyServer::GetWorlds () const
Get a list of pointers to the connected worlds.
Returns
List of pointers to the connected worlds
Definition at line 172 of file LobbyServer.cpp.
References mManagerConnection.
Referenced by SendWorldList().
libcomp::String LobbyServer::ImportAccount (const libcomp::String & data, uint8_t worldID = 0)
Import an account into the database.
Parameters
data XML data for the account.
worldID ID of the world to import the characters into.
Returns
Error string or an empty string on success.
Definition at line 603 of file LobbyServer.cpp.
References libcomp::String::Arg(), libcomp::String::C(), CheckImportObject(), libcomp::DatabaseChangeSet::Create(), GetMainDatabase(), libcomp::PersistentObject::GetTypeHashByName(), GetWorldByID(), libcomp::String::IsEmpty(), libcomp::PersistentObject::LoadObjectByUUID(), and libcomp::PersistentObject::New().
bool LobbyServer::Initialize () virtual
Initialize the database connection and do anything else that can fail to execute that needs to be handled outside of a constructor.
This calls the BaseServer version as well to perform shared init steps.
Parameters
self Pointer to this server to be used as a reference in packet handling code.
Returns
true on success, false on failure
Reimplemented from libcomp::BaseServer.
Definition at line 64 of file LobbyServer.cpp.
References libcomp::Worker::AddManager(), CreateFirstAccount(), libcomp::BaseServer::GetDatabase(), libcomp::BaseServer::GetDataStore(), libcomp::Worker::GetMessageQueue(), lobby::LobbySyncManager::Initialize(), mAccountManager, libcomp::BaseServer::mConfig, mDatabase, libcomp::BaseServer::mMainWorker, mManagerConnection, libcomp::BaseServer::mService, mSyncManager, mUnitTestMode, libcomp::BaseServer::mWorkers, ResetRegisteredWorlds(), Setup(), and to_underlying().
void LobbyServer::PromptCreateAccount () protected
Prompt for and create an account via pre-populated or user entered values.
Todo:
Use a regular expression.
Todo:
Make this a better check for a valid email.
Definition at line 312 of file LobbyServer.cpp.
References libcomp::String::Contains(), libcomp::Crypto::GenerateRandom(), libcomp::Crypto::HashPassword(), libcomp::String::Length(), libcomp::BaseServer::mConfig, mDatabase, libcomp::String::ToInteger(), and libcomp::String::ToLower().
Referenced by CreateFirstAccount().
const std::shared_ptr< lobby::World > LobbyServer::RegisterWorld (std::shared_ptr< lobby::World > & world)
Register a world with the connection manager.
Parameters
world Pointer to the world to register
Returns
Pointer to the new registered server or nullptr on failure
See Also
ManagerConnection::RegisterWorld
Definition at line 188 of file LobbyServer.cpp.
References mManagerConnection.
Referenced by ResetRegisteredWorlds().
bool LobbyServer::ResetRegisteredWorlds () protected
Reset the values in the RegisteredWorld table, pulling World information from it before servers connect.
Returns
true on success, false on failure
Definition at line 545 of file LobbyServer.cpp.
References libcomp::String::Arg(), mDatabase, and RegisterWorld().
Referenced by Initialize().
void LobbyServer::SendWorldList (const std::shared_ptr< libcomp::TcpConnection > & connection) const
Send the world list to either one or all client connections.
Parameters
connection Optional pointer to a specific connection to send the world list to. If not specified, all connections will be broadcast to instead.
Definition at line 194 of file LobbyServer.cpp.
References libcomp::Convert::ENCODING_UTF8, GetWorlds(), mManagerConnection, libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteString16Little(), libcomp::Packet::WriteU16Little(), and libcomp::Packet::WriteU8().
bool LobbyServer::Setup () protected
Setup the server based on the setup config file.
Returns
true on success, false on failure or no work done
Definition at line 528 of file LobbyServer.cpp.
References libcomp::BaseServer::GetConfigPath(), libcomp::BaseServer::InsertDataFromFile(), and mDatabase.
Referenced by Initialize().
Member Data Documentation
AccountManager* lobby::LobbyServer::mAccountManager protected
Account manager for the server.
Definition at line 220 of file LobbyServer.h.
Referenced by GetAccountManager(), Initialize(), and ~LobbyServer().
std::shared_ptr<libcomp::Database> lobby::LobbyServer::mDatabase protected
A shared pointer to the main database used by the server.
Definition at line 211 of file LobbyServer.h.
Referenced by GetMainDatabase(), Initialize(), PromptCreateAccount(), ResetRegisteredWorlds(), and Setup().
std::unordered_map<libcomp::String, libcomp::String> lobby::LobbyServer::mFakeSalts protected
Mapping of fake salts for usernames that do not exist.
Definition at line 229 of file LobbyServer.h.
Referenced by GetFakeAccountSalt().
std::mutex lobby::LobbyServer::mFakeSaltsLock protected
Lock for the fake salts.
Definition at line 226 of file LobbyServer.h.
Referenced by GetFakeAccountSalt().
std::shared_ptr<ManagerConnection> lobby::LobbyServer::mManagerConnection protected
Pointer to the manager in charge of connections.
Definition at line 214 of file LobbyServer.h.
Referenced by GetManagerConnection(), GetWorldByConnection(), GetWorldByID(), GetWorlds(), Initialize(), RegisterWorld(), and SendWorldList().
LobbySyncManager* lobby::LobbyServer::mSyncManager protected
Data sync manager for the server.
Definition at line 223 of file LobbyServer.h.
Referenced by GetLobbySyncManager(), Initialize(), and ~LobbyServer().
bool lobby::LobbyServer::mUnitTestMode protected
Indicates the unit test database should be used.
Definition at line 217 of file LobbyServer.h.
Referenced by Initialize().
The documentation for this class was generated from the following files:
LobbyServer.h
LobbyServer.cpp