COMP_hack: lobby::AccountManager Class Reference
lobby::AccountManager Class Reference
Manages logged in user accounts.
#include <AccountManager.h>
Public Member Functions
AccountManager (LobbyServer *pServer)
Construct the account manager.
bool ChannelToChannelSwitch (const libcomp::String &username, int8_t channelID, uint32_t sessionKey)
Transitions the user login state from CHANNEL to CHANNEL_TO_CHANNEL, and update the session key.
ErrorCodes_t CompleteChannelLogin (const libcomp::String &username, int8_t worldID, int8_t channelID)
Transitions the user login state from LOBBY_TO_CHANNEL to CHANNEL, completing a sucessful channel login.
bool DeleteCharacter (const std::shared_ptr< objects::Account > &account, const std::shared_ptr< objects::Character > &character)
Delete a character by CID and update the Characters array on the account.
bool DeleteKillTimeExceededCharacters (uint8_t worldID)
Delete all characters with an exceeded kill time on a connected world.
bool EndWebGameSession (const libcomp::String &username)
Start any web-game session for the specified user.
void ExpireSession (const libcomp::String &username, const libcomp::String &sid)
Expire a session key.
std::list< std::shared_ptr
< objects::Character > > GetCharactersForDeletion (const std::shared_ptr< objects::Account > &account)
Get characters on an account with a KillTime that has passed.
std::shared_ptr
< objects::AccountLogin > GetUserLogin (const libcomp::String &username)
Get the current user login state independent of world.
std::list< libcomp::String > GetUsersInWorld (int8_t world, int8_t channel=-1)
Get all users in a given world (and optionally on a specific channel).
std::shared_ptr
< WebGameApiSession > GetWebGameApiSession (const libcomp::String &username, const libcomp::String &sessionID, const libcomp::String &clientAddress)
Get or create a web-game API session based upon a valid web-game session if one exists and matches the supplied values.
bool IsLoggedIn (const libcomp::String &username, int8_t &world)
Check if a user is logged in.
ErrorCodes_t LobbyLogin (const libcomp::String &username, const libcomp::String &sid, libcomp::String &sid2, int maxClients=0)
Transitions the user login state from LOBBY_WAIT to LOBBY.
ErrorCodes_t LobbyLogin (const libcomp::String &username, libcomp::String &sid2, int maxClients=0, const libcomp::String &machineUUID={})
Transitions the user login state from OFFLINE to LOBBY.
bool Logout (const libcomp::String &username)
Transitions the user to the OFFLINE state.
std::list< libcomp::String > LogoutUsersInWorld (int8_t world, int8_t channel=-1)
Log out all users in a given world (and optionally on a specific channel).
bool SetCharacterOnAccount (const std::shared_ptr< objects::Account > &account, const std::shared_ptr< objects::Character > &character)
Set a character on the specified account's character array and save it.
std::shared_ptr
< objects::AccountLogin > StartChannelLogin (const libcomp::String &username, const std::shared_ptr< objects::Character > &character)
Set the character associated to the supplied account in preparation for world communication and channel connection.
bool StartWebGameSession (const libcomp::String &username, const std::shared_ptr< objects::WebGameSession > &gameSession)
Start a web-game session for the specified user who is currently playing that remains valid until a remove request is received or the account leaves the channel.
ErrorCodes_t SwitchToChannel (const libcomp::String &username, int8_t worldID, int8_t channelID)
Transitions the user login state from LOBBY to LOBBY_TO_CHANNEL, set the supplied world and channel IDs and await world communication that the player has successfully entered the channel.
bool UpdateKillTime (const libcomp::String &username, uint8_t cid, std::shared_ptr< LobbyServer > &server)
Mark or clear a character by CID for deletion.
ErrorCodes_t WebAuthLogin (const libcomp::String &username, const libcomp::String &password, uint32_t clientVersion, libcomp::String &sid, bool checkPassword=true)
Transitions the user login state from OFFLINE to LOBBY_WAIT.
ErrorCodes_t WebAuthLoginApi (const libcomp::String &username, uint32_t clientVersion, libcomp::String &sid)
Transitions the user login state from OFFLINE to LOBBY_WAIT.
Protected Member Functions
void EraseLogin (const libcomp::String &username, bool updateDebugStatus=true)
This will remove a login entry for the account map.
std::shared_ptr
< objects::AccountLogin > GetOrCreateLogin (const libcomp::String &username)
Return the existing login object for the given username or create a new login object if one does not already exist.
void PrintAccounts () const
Print the status of the accounts managed by this object.
void UnregisterMachineClient (const libcomp::String &username)
Decrement the count associated to the login restricted machine UUID map.
void UpdateDebugStatus () const
Update the server debug state for systems configured to display it.
Private Attributes
std::mutex mAccountLock
Mutex to lock access to the account map.
std::unordered_map
< libcomp::String,
std::shared_ptr
< objects::AccountLogin > > mAccountMap
Map of accounts with associated login information.
std::unordered_map
< libcomp::String, int32_t > mMachineUUIDs
List of clients connected for each machine UUID.
LobbyServer * mServer
Pointer to the lobby server.
std::unordered_map
< libcomp::String,
std::shared_ptr
< WebGameApiSession > > mWebGameAPISessions
List of web-game API sessions by username.
std::unordered_map
< libcomp::String,
std::shared_ptr
< objects::WebGameSession > > mWebGameSessions
Map of account usernames associated to accounts to web-game sessions either pending or active for a character currently playing.
Detailed Description
Manages logged in user accounts.
Definition at line 58 of file AccountManager.h.
Constructor & Destructor Documentation
AccountManager::AccountManager (LobbyServer * pServer) explicit
Construct the account manager.
Parameters
Pointer to the lobby server this account manager is part of.
Note
The server must remain valid during any account manager request.
Definition at line 57 of file AccountManager.cpp.
Member Function Documentation
bool AccountManager::ChannelToChannelSwitch (const libcomp::String & username, int8_t channelID, uint32_t sessionKey)
Transitions the user login state from CHANNEL to CHANNEL_TO_CHANNEL, and update the session key.
Parameters
username Username of the account to update.
channelID ID of the channel the account was switched to.
sesssionKey New session key set by the world
Returns
true upon successful update, false if an error occurred
Note
This function is thread safe.
Definition at line 648 of file AccountManager.cpp.
References libcomp::String::Arg(), GetOrCreateLogin(), mAccountLock, mWebGameAPISessions, mWebGameSessions, and libcomp::String::ToLower().
ErrorCodes_t AccountManager::CompleteChannelLogin (const libcomp::String & username, int8_t worldID, int8_t channelID)
Transitions the user login state from LOBBY_TO_CHANNEL to CHANNEL, completing a sucessful channel login.
Parameters
username Username of the account to update.
worldID ID of the world the account was connected to.
channelID ID of the channel the account was connected to.
Returns
Error code indicating the success or failure of this operation. This function can return one of:
SUCCESS (change was valid and login information was updated)
SYSTEM_ERROR (some internal error occurred)
Note
This function is thread safe.
Definition at line 584 of file AccountManager.cpp.
References libcomp::String::Arg(), GetOrCreateLogin(), and mAccountLock.
bool AccountManager::DeleteCharacter (const std::shared_ptr< objects::Account > & account, const std::shared_ptr< objects::Character > & character)
Delete a character by CID and update the Characters array on the account.
This assumes the character has already been loaded and will not load them if they are not.
Parameters
account Pointer to the account to delete the character from.
character Pointer to the character to delete.
Returns
true if the character was deleted and the account was updated, false otherwise.
Definition at line 1199 of file AccountManager.cpp.
References libcomp::String::Arg(), lobby::LobbyServer::GetLobbySyncManager(), lobby::LobbyServer::GetMainDatabase(), mAccountLock, mServer, and libcomp::DataSyncManager::RemoveRecord().
Referenced by DeleteKillTimeExceededCharacters(), and UpdateKillTime().
bool AccountManager::DeleteKillTimeExceededCharacters (uint8_t worldID)
Delete all characters with an exceeded kill time on a connected world.
Parameters
worldID World ID to delete characters on
Returns
true if the process completed successfully, false if an error occurred
Definition at line 1048 of file AccountManager.cpp.
References libcomp::String::Arg(), DeleteCharacter(), lobby::LobbyServer::GetMainDatabase(), lobby::LobbyServer::GetWorldByID(), libcomp::PersistentObject::LoadAll(), libcomp::PersistentObject::LoadObjectByUUID(), and mServer.
bool AccountManager::EndWebGameSession (const libcomp::String & username)
Start any web-game session for the specified user.
Parameters
username Username of the account the session belongs to
Returns
true if the session existed and was removed, false if it did not
Definition at line 1367 of file AccountManager.cpp.
References libcomp::String::Arg(), mAccountLock, mWebGameAPISessions, mWebGameSessions, and libcomp::String::ToLower().
void AccountManager::EraseLogin (const libcomp::String & username, bool updateDebugStatus = true) protected
This will remove a login entry for the account map.
Accounts not in the map are considered OFFLINE.
Parameters
username Username of the account to remove from the login map.
updateDebugStatus Optional flag to update the debug status after removing the login information. Defaults to true.
Note
This function is NOT thread safe. You MUST lock access first!
Definition at line 856 of file AccountManager.cpp.
References mAccountMap, mWebGameAPISessions, mWebGameSessions, libcomp::String::ToLower(), UnregisterMachineClient(), and UpdateDebugStatus().
Referenced by LobbyLogin(), Logout(), LogoutUsersInWorld(), and WebAuthLogin().
void AccountManager::ExpireSession (const libcomp::String & username, const libcomp::String & sid)
Expire a session key.
If the session key is not matched or the account is not awaiting login anymore (LOBBY_WAIT state) this is ignored.
Parameters
username Username for account the session key was create for.
sid Session ID that has expired.
Note
This function is thread safe.
Definition at line 772 of file AccountManager.cpp.
References libcomp::String::Arg(), mAccountLock, mAccountMap, libcomp::String::ToLower(), UnregisterMachineClient(), and UpdateDebugStatus().
Referenced by Logout(), and WebAuthLogin().
std::list< std::shared_ptr< objects::Character > > AccountManager::GetCharactersForDeletion (const std::shared_ptr< objects::Account > & account)
Get characters on an account with a KillTime that has passed.
This assumes characters have already been loaded and will not load them if they are not.
Parameters
account Pointer to the account to gather deletes for.
Returns
List of pointers to characters to delete.
Definition at line 1179 of file AccountManager.cpp.
std::shared_ptr< objects::AccountLogin > AccountManager::GetOrCreateLogin (const libcomp::String & username) protected
Return the existing login object for the given username or create a new login object if one does not already exist.
Parameters
username Username for the login object to return.
Returns
The login object for the given username or null on error.
Note
This function is NOT thread safe. You MUST lock access first!
Definition at line 810 of file AccountManager.cpp.
References lobby::LobbyServer::GetMainDatabase(), mAccountMap, mServer, libcomp::String::ToLower(), and UpdateDebugStatus().
Referenced by ChannelToChannelSwitch(), CompleteChannelLogin(), LobbyLogin(), Logout(), StartChannelLogin(), SwitchToChannel(), and WebAuthLogin().
std::shared_ptr< objects::AccountLogin > AccountManager::GetUserLogin (const libcomp::String & username)
Get the current user login state independent of world.
Parameters
username Username for the account to login.
Returns
Pointer to the login state; null if it does not exist.
Definition at line 939 of file AccountManager.cpp.
References mAccountLock, mAccountMap, and libcomp::String::ToLower().
Referenced by lobby::ApiHandler::Admin_Online(), lobby::ApiHandler::Admin_PostItems(), and UpdateKillTime().
std::list< libcomp::String > AccountManager::GetUsersInWorld (int8_t world, int8_t channel = -1)
Get all users in a given world (and optionally on a specific channel).
Parameters
world World to get all users from.
channel Channel in the world to get all users from. If this is empty, all users in the world will be retrieved.
Returns
List of usernames in the world (and channel).
Definition at line 950 of file AccountManager.cpp.
References mAccountLock, and mAccountMap.
Referenced by lobby::ApiHandler::Admin_Online(), and LogoutUsersInWorld().
std::shared_ptr< WebGameApiSession > AccountManager::GetWebGameApiSession (const libcomp::String & username, const libcomp::String & sessionID, const libcomp::String & clientAddress)
Get or create a web-game API session based upon a valid web-game session if one exists and matches the supplied values.
Sessions created here last only as long as the game session exists.
Parameters
username Username of the account the session belongs to
sessionID Session ID supplied by the world server which changes each time a new web-game session is requested
clientAddress Base address of the client requesting the session used for prevention of two active sessions for the same user
Returns
Pointer to the web-game API session, null if the supplied values were not valid
Definition at line 1313 of file AccountManager.cpp.
References libcomp::String::Arg(), mAccountLock, mWebGameAPISessions, mWebGameSessions, and libcomp::String::ToLower().
bool AccountManager::IsLoggedIn (const libcomp::String & username, int8_t & world)
Check if a user is logged in.
Parameters
username Username for the account to check.
world World the user is logged into or -1 if they are in the lobby server.
Returns
true if the user is logged in; false otherwise.
Definition at line 918 of file AccountManager.cpp.
References mAccountLock, mAccountMap, and libcomp::String::ToLower().
Referenced by lobby::ApiHandler::Admin_KickPlayer().
ErrorCodes_t AccountManager::LobbyLogin (const libcomp::String & username, const libcomp::String & sid, libcomp::String & sid2, int maxClients = 0)
Transitions the user login state from LOBBY_WAIT to LOBBY.
This operation provides a session ID for the user to pass to a lobby server connection.
Parameters
username Username of the account to authenticate.
sid Session ID given by the web authentication.
sid2 Session ID to give back to the client.
maxClients Maximum number of clients that may be connected from the same machine. A value of 0 or less is an unlimited number.
Returns
Error code indicating the success or failure of this operation. This function can return one of:
SUCCESS (login was valid and a session ID was generated)
SYSTEM_ERROR (some internal error occurred)
BAD_USERNAME_PASSWORD
ACCOUNT_STILL_LOGGED_IN (account not in OFFLINE or LOBBY_WAIT)
Note
This function is thread safe.
Definition at line 257 of file AccountManager.cpp.
References libcomp::String::Arg(), libcomp::Crypto::GenerateRandom(), GetOrCreateLogin(), mAccountLock, and libcomp::String::ToLower().
ErrorCodes_t AccountManager::LobbyLogin (const libcomp::String & username, libcomp::String & sid2, int maxClients = 0, const libcomp::String & machineUUID = {})
Transitions the user login state from OFFLINE to LOBBY.
It is assumed the client version and the password hash has already been checked by the classic login packet handlers.
Parameters
username Username of the account to authenticate.
sid2 Session ID to give back to the client.
maxClients Maximum number of clients that may be connected from the same machine. A value of 0 or less is an unlimited number.
machineUUID Machine UUID used to limit multiclienting.
Returns
Error code indicating the success or failure of this operation. This function can return one of:
SUCCESS (login was valid and a session ID was generated)
SYSTEM_ERROR (some internal error occurred)
BAD_USERNAME_PASSWORD
ACCOUNT_STILL_LOGGED_IN (account not in OFFLINE or LOBBY_WAIT)
SERVER_FULL (too many accounts are online)
ACCOUNT_DISABLED (your account has been disabled/banned)
Note
This function is thread safe.
Todo:
Check if the server is full and return SERVER_FULL.
Definition at line 343 of file AccountManager.cpp.
References libcomp::String::Arg(), EraseLogin(), libcomp::Crypto::GenerateRandom(), GetOrCreateLogin(), mAccountLock, mMachineUUIDs, lobby::state(), libcomp::String::ToLower(), and UnregisterMachineClient().
bool AccountManager::Logout (const libcomp::String & username)
Transitions the user to the OFFLINE state.
Parameters
username Username of the account to log out.
Returns
true if the account was logged out; false otherwise.
Note
This function is thread safe.
Definition at line 697 of file AccountManager.cpp.
References libcomp::String::Arg(), lobby::config(), EraseLogin(), ExpireSession(), libcomp::BaseServer::GetConfig(), GetOrCreateLogin(), libcomp::BaseServer::GetTimerManager(), mAccountLock, mServer, mWebGameAPISessions, mWebGameSessions, libcomp::TimerManager::ScheduleEventIn(), and libcomp::String::ToLower().
Referenced by lobby::ManagerConnection::RemoveClientConnection().
std::list< libcomp::String > AccountManager::LogoutUsersInWorld (int8_t world, int8_t channel = -1)
Log out all users in a given world (and optionally on a specific channel).
This should only be called when a world or channel disconnects.
Parameters
world World to log out all users from.
channel Channel in the world to log out all users from. If this is empty, all users in the world will be logged out.
Returns
List of usernames that were logged out.
Definition at line 974 of file AccountManager.cpp.
References EraseLogin(), GetUsersInWorld(), mAccountLock, and UpdateDebugStatus().
void AccountManager::PrintAccounts () const protected
Print the status of the accounts managed by this object.
Note
This function is NOT thread safe. You MUST lock access first!
Definition at line 1390 of file AccountManager.cpp.
References libcomp::String::Arg(), mAccountMap, and lobby::state().
bool AccountManager::SetCharacterOnAccount (const std::shared_ptr< objects::Account > & account, const std::shared_ptr< objects::Character > & character)
Set a character on the specified account's character array and save it.
Parameters
account Pointer to the account to create the character on
character Pointer to the character to create
Returns
true if the character was created and the account was updated, false otherwise
Definition at line 1132 of file AccountManager.cpp.
References libcomp::String::Arg(), lobby::LobbyServer::GetMainDatabase(), mAccountLock, and mServer.
std::shared_ptr< objects::AccountLogin > AccountManager::StartChannelLogin (const libcomp::String & username, const std::shared_ptr< objects::Character > & character)
Set the character associated to the supplied account in preparation for world communication and channel connection.
Parameters
username Username of the account to set the character on.
character Pointer to the character to set on the account.
Returns
Pointer to the matching AccountLogin or null if it does not exist
Note
This function is thread safe.
Definition at line 494 of file AccountManager.cpp.
References libcomp::String::Arg(), GetOrCreateLogin(), and mAccountLock.
bool AccountManager::StartWebGameSession (const libcomp::String & username, const std::shared_ptr< objects::WebGameSession > & gameSession)
Start a web-game session for the specified user who is currently playing that remains valid until a remove request is received or the account leaves the channel.
Parameters
username Username of the account the session belongs to
gameSession Pointer to the session's definition
Returns
true if the session was started successfully, false if it was not
Definition at line 1281 of file AccountManager.cpp.
References libcomp::String::Arg(), mAccountLock, mAccountMap, mWebGameSessions, and libcomp::String::ToLower().
ErrorCodes_t AccountManager::SwitchToChannel (const libcomp::String & username, int8_t worldID, int8_t channelID)
Transitions the user login state from LOBBY to LOBBY_TO_CHANNEL, set the supplied world and channel IDs and await world communication that the player has successfully entered the channel.
A timeout should be used in conjunction with this to ensure the account does not get stuck.
Parameters
username Username of the account to update.
worldID ID of the world the account is being moved to.
channelID ID of the channel the account is being moved to.
Returns
Error code indicating the success or failure of this operation. This function can return one of:
SUCCESS (change was valid and login information was updated)
SYSTEM_ERROR (some internal error occurred)
Note
This function is thread safe.
Definition at line 534 of file AccountManager.cpp.
References libcomp::String::Arg(), GetOrCreateLogin(), and mAccountLock.
void AccountManager::UnregisterMachineClient (const libcomp::String & username) protected
Decrement the count associated to the login restricted machine UUID map.
If the account is not currently logged in, this will do nothing.
Parameters
username Username of the machine to lower the count for.
Note
This function is NOT thread safe. You MUST lock access first!
Definition at line 874 of file AccountManager.cpp.
References libcomp::String::Arg(), mAccountMap, mMachineUUIDs, and libcomp::String::ToLower().
Referenced by EraseLogin(), ExpireSession(), and LobbyLogin().
void AccountManager::UpdateDebugStatus () const protected
Update the server debug state for systems configured to display it.
Note
This function is NOT thread safe. You MUST lock access first!
Definition at line 1454 of file AccountManager.cpp.
References mAccountMap.
Referenced by EraseLogin(), ExpireSession(), GetOrCreateLogin(), and LogoutUsersInWorld().
bool AccountManager::UpdateKillTime (const libcomp::String & username, uint8_t cid, std::shared_ptr< LobbyServer > & server)
Mark or clear a character by CID for deletion.
This assumes the character has already been loaded and will not load them if they are not.
Parameters
username Username of the account that the character belongs to.
cid CID of the character to update.
server Pointer to the lobby server.
Returns
true if the character was updated, false otherwise.
Definition at line 995 of file AccountManager.cpp.
References lobby::config(), DeleteCharacter(), and GetUserLogin().
ErrorCodes_t AccountManager::WebAuthLogin (const libcomp::String & username, const libcomp::String & password, uint32_t clientVersion, libcomp::String & sid, bool checkPassword = true)
Transitions the user login state from OFFLINE to LOBBY_WAIT.
This operation provides a session ID for the user to pass to a lobby server connection. If the user does not login within a specified period of time the session ID is invalidated and the user transitions back to the OFFLINE state.
Parameters
username Username of the account to authenticate.
password Password of the account to authenticate.
clientVersion Client version converted into an integer.
sid Reference to a string to save the session ID into.
checkPassword Do not change this (used by API version).
Returns
Error code indicating the success or failure of this operation. This function can return one of:
SUCCESS (login was valid and a session ID was generated)
SYSTEM_ERROR (some internal error occurred)
BAD_USERNAME_PASSWORD
ACCOUNT_STILL_LOGGED_IN (account not in OFFLINE or LOBBY_WAIT)
SERVER_FULL (too many accounts are online)
WRONG_CLIENT_VERSION
ACCOUNT_DISABLED (your account has been disabled/banned)
Note
This function is thread safe.
Todo:
Check if the server is full and return SERVER_FULL.
Definition at line 61 of file AccountManager.cpp.
References libcomp::String::Arg(), lobby::config(), EraseLogin(), ExpireSession(), libcomp::Crypto::GenerateRandom(), libcomp::BaseServer::GetConfig(), GetOrCreateLogin(), libcomp::BaseServer::GetTimerManager(), libcomp::Crypto::HashPassword(), mAccountLock, mServer, libcomp::TimerManager::ScheduleEventIn(), lobby::state(), and libcomp::String::ToLower().
Referenced by lobby::LoginHandler::HandlePage(), and WebAuthLoginApi().
ErrorCodes_t AccountManager::WebAuthLoginApi (const libcomp::String & username, uint32_t clientVersion, libcomp::String & sid)
Transitions the user login state from OFFLINE to LOBBY_WAIT.
This operation provides a session ID for the user to pass to a lobby server connection. If the user does not login within a specified period of time the session ID is invalidated and the user transitions back to the OFFLINE state.
Parameters
username Username of the account to authenticate.
clientVersion Client version converted into an integer.
sid Reference to a string to save the session ID into.
Returns
Error code indicating the success or failure of this operation. This function can return one of:
SUCCESS (login was valid and a session ID was generated)
SYSTEM_ERROR (some internal error occurred)
BAD_USERNAME_PASSWORD
ACCOUNT_STILL_LOGGED_IN (account not in OFFLINE or LOBBY_WAIT)
SERVER_FULL (too many accounts are online)
WRONG_CLIENT_VERSION
ACCOUNT_DISABLED (your account has been disabled/banned)
Note
This function is thread safe.
The password is not required because it is assumed to have been checked by the API subsystem. Do NOT use this for normal logins.
Definition at line 250 of file AccountManager.cpp.
References WebAuthLogin().
Referenced by lobby::ApiHandler::Account_ClientLogin().
Member Data Documentation
std::mutex lobby::AccountManager::mAccountLock private
Mutex to lock access to the account map.
Definition at line 411 of file AccountManager.h.
Referenced by ChannelToChannelSwitch(), CompleteChannelLogin(), DeleteCharacter(), EndWebGameSession(), ExpireSession(), GetUserLogin(), GetUsersInWorld(), GetWebGameApiSession(), IsLoggedIn(), LobbyLogin(), Logout(), LogoutUsersInWorld(), SetCharacterOnAccount(), StartChannelLogin(), StartWebGameSession(), SwitchToChannel(), and WebAuthLogin().
std::unordered_map<libcomp::String, std::shared_ptr<objects::AccountLogin> > lobby::AccountManager::mAccountMap private
Map of accounts with associated login information.
Definition at line 415 of file AccountManager.h.
Referenced by EraseLogin(), ExpireSession(), GetOrCreateLogin(), GetUserLogin(), GetUsersInWorld(), IsLoggedIn(), PrintAccounts(), StartWebGameSession(), UnregisterMachineClient(), and UpdateDebugStatus().
std::unordered_map<libcomp::String, int32_t> lobby::AccountManager::mMachineUUIDs private
List of clients connected for each machine UUID.
Definition at line 428 of file AccountManager.h.
Referenced by LobbyLogin(), and UnregisterMachineClient().
LobbyServer* lobby::AccountManager::mServer private
Pointer to the lobby server.
Definition at line 408 of file AccountManager.h.
Referenced by DeleteCharacter(), DeleteKillTimeExceededCharacters(), GetOrCreateLogin(), Logout(), SetCharacterOnAccount(), and WebAuthLogin().
std::unordered_map<libcomp::String, std::shared_ptr<WebGameApiSession> > lobby::AccountManager::mWebGameAPISessions private
List of web-game API sessions by username.
Only valid for as long as there is a web-game session active
Definition at line 425 of file AccountManager.h.
Referenced by ChannelToChannelSwitch(), EndWebGameSession(), EraseLogin(), GetWebGameApiSession(), and Logout().
std::unordered_map<libcomp::String, std::shared_ptr< objects::WebGameSession> > lobby::AccountManager::mWebGameSessions private
Map of account usernames associated to accounts to web-game sessions either pending or active for a character currently playing.
Definition at line 420 of file AccountManager.h.
Referenced by ChannelToChannelSwitch(), EndWebGameSession(), EraseLogin(), GetWebGameApiSession(), Logout(), and StartWebGameSession().
The documentation for this class was generated from the following files:
AccountManager.h
AccountManager.cpp