COMP_hack: lobby::ManagerConnection Class Reference
lobby::ManagerConnection Class Reference
Class to handle messages pertaining to connecting to worlds or game clients.
#include <ManagerConnection.h>
Public Member Functions
ManagerConnection (std::weak_ptr< libcomp::BaseServer > server, asio::io_service *service, std::shared_ptr< libcomp::MessageQueue< libcomp::Message::Message * >> messageQueue)
Create a new manager.
virtual ~ManagerConnection ()
Clean up the manager.
const std::shared_ptr
< LobbyClientConnection > GetClientConnection (const libcomp::String &username) const
Get client connection by username.
const std::list
< std::shared_ptr
< libcomp::TcpConnection > > GetClientConnections () const
Get all client connections.
virtual std::list
< libcomp::Message::MessageType > GetSupportedTypes () const
Get the different types of messages handled by this manager.
std::shared_ptr< lobby::World > GetWorldByConnection (const std::shared_ptr< libcomp::InternalConnection > &connection) const
Get a registered world via its connection.
std::shared_ptr< lobby::World > GetWorldByID (uint8_t id) const
Get a registered world via its ID.
std::list< std::shared_ptr
< lobby::World > > GetWorlds () const
Get a list of registered worlds.
bool InitializeWorld (const std::shared_ptr< lobby::World > &world)
Request information about the world and send database connection information to the main DB.
virtual bool ProcessMessage (const libcomp::Message::Message *pMessage)
Process a message from the queue.
const std::shared_ptr
< lobby::World > RegisterWorld (std::shared_ptr< lobby::World > &world)
Register a world and remove previous entries.
void RemoveClientConnection (const std::shared_ptr< LobbyClientConnection > &connection)
Remove a client connection.
void RemoveWorld (std::shared_ptr< lobby::World > &world)
Remove a registered world when no longer needed.
void SetClientConnection (const std::shared_ptr< LobbyClientConnection > &connection)
Set an active client connection after its account has been detected.
Private Attributes
std::unordered_map
< libcomp::String,
std::shared_ptr
< LobbyClientConnection > > mClientConnections
Map of active client connections by account username.
std::shared_ptr
< libcomp::MessageQueue
< libcomp::Message::Message * > > mMessageQueue
Pointer to the message queue to use when connecting to world servers.
std::weak_ptr
< libcomp::BaseServer > mServer
Pointer to the server that uses this manager.
asio::io_service * mService
Pointer to the ASIO service to use to establish connections to world servers.
std::list< std::shared_ptr
< lobby::World > > mUnregisteredWorlds
List of pointers to unregistered worlds.
std::list< std::shared_ptr
< lobby::World > > mWorlds
List of pointers to registered worlds.
Static Private Attributes
static std::list
< libcomp::Message::MessageType > sSupportedTypes
Static list of supported message types for the manager.
Detailed Description
Class to handle messages pertaining to connecting to worlds or game clients.
Definition at line 48 of file ManagerConnection.h.
Constructor & Destructor Documentation
ManagerConnection::ManagerConnection (std::weak_ptr< libcomp::BaseServer > server, asio::io_service * service, std::shared_ptr< libcomp::MessageQueue< libcomp::Message::Message * >> messageQueue)
Create a new manager.
Parameters
server Pointer to the server that uses this manager
service Pointer to the ASIO service to use to establish connections to world servers
messageQueue Pointer to the message queue to use when connecting to world servers
Definition at line 51 of file ManagerConnection.cpp.
References mMessageQueue, mServer, and mService.
ManagerConnection::~ManagerConnection () virtual
Clean up the manager.
Definition at line 60 of file ManagerConnection.cpp.
Member Function Documentation
const std::shared_ptr< LobbyClientConnection > ManagerConnection::GetClientConnection (const libcomp::String & username) const
Get client connection by username.
Parameters
username Client account username
Returns
Pointer to the client connection
Definition at line 345 of file ManagerConnection.cpp.
References mClientConnections.
const std::list< std::shared_ptr< libcomp::TcpConnection > > ManagerConnection::GetClientConnections () const
Get all client connections.
Returns
List of pointers to all client connections
Definition at line 353 of file ManagerConnection.cpp.
References mClientConnections.
std::list< libcomp::Message::MessageType > ManagerConnection::GetSupportedTypes () const virtual
Get the different types of messages handled by this manager.
Returns
List of supported message types
Implements libcomp::Manager.
Definition at line 65 of file ManagerConnection.cpp.
References sSupportedTypes.
std::shared_ptr< lobby::World > ManagerConnection::GetWorldByConnection (const std::shared_ptr< libcomp::InternalConnection > & connection) const
Get a registered world via its connection.
Parameters
connection Pointer to the world's connection
Returns
Pointer to a registered world
Definition at line 201 of file ManagerConnection.cpp.
References mUnregisteredWorlds, and mWorlds.
Referenced by ProcessMessage(), and RegisterWorld().
std::shared_ptr< lobby::World > ManagerConnection::GetWorldByID (uint8_t id) const
Get a registered world via its ID.
Parameters
id The world's ID
Returns
Pointer to a registered world
Definition at line 184 of file ManagerConnection.cpp.
References mUnregisteredWorlds, and mWorlds.
Referenced by RegisterWorld().
std::list< std::shared_ptr< lobby::World > > ManagerConnection::GetWorlds () const
Get a list of registered worlds.
Returns
List of pointers to registered worlds
Definition at line 179 of file ManagerConnection.cpp.
References mWorlds.
bool ManagerConnection::InitializeWorld (const std::shared_ptr< lobby::World > & world)
Request information about the world and send database connection information to the main DB.
Parameters
world World to intialize
Returns
true on success, false on failure
Definition at line 163 of file ManagerConnection.cpp.
References mServer, and libcomp::Packet::WritePacketCode().
Referenced by ProcessMessage().
bool ManagerConnection::ProcessMessage (const libcomp::Message::Message * pMessage) virtual
Process a message from the queue.
Parameters
pMessage Message to be processed
Returns
true on success, false on failure
Implements libcomp::Manager.
Definition at line 70 of file ManagerConnection.cpp.
References libcomp::String::Arg(), libcomp::Message::CONNECTION_MESSAGE_CONNECTION_CLOSED, libcomp::Message::CONNECTION_MESSAGE_ENCRYPTED, libcomp::Message::CONNECTION_MESSAGE_WORLD_NOTIFICATION, libcomp::Message::WorldNotification::GetAddress(), libcomp::Message::Encrypted::GetConnection(), libcomp::Message::ConnectionClosed::GetConnection(), libcomp::Message::ConnectionMessage::GetConnectionMessageType(), libcomp::Message::WorldNotification::GetPort(), GetWorldByConnection(), InitializeWorld(), mMessageQueue, mServer, mUnregisteredWorlds, RemoveClientConnection(), and RemoveWorld().
const std::shared_ptr< lobby::World > ManagerConnection::RegisterWorld (std::shared_ptr< lobby::World > & world)
Register a world and remove previous entries.
This will fail if the world does not contain registered server information.
Parameters
world Pointer to the world to register
Returns
Pointer to the new registered server or nullptr on failure
Definition at line 224 of file ManagerConnection.cpp.
References GetWorldByConnection(), GetWorldByID(), mWorlds, and RemoveWorld().
void ManagerConnection::RemoveClientConnection (const std::shared_ptr< LobbyClientConnection > & connection)
Remove a client connection.
Parameters
connection Pointer to the client connection
Definition at line 383 of file ManagerConnection.cpp.
References libcomp::String::Arg(), lobby::LobbyServer::GetAccountManager(), lobby::AccountManager::Logout(), mClientConnections, mServer, and lobby::state().
Referenced by ProcessMessage().
void ManagerConnection::RemoveWorld (std::shared_ptr< lobby::World > & world)
Remove a registered world when no longer needed.
Parameters
world Pointer to the world to remove
Definition at line 287 of file ManagerConnection.cpp.
References libcomp::String::Arg(), mServer, mUnregisteredWorlds, and mWorlds.
Referenced by ProcessMessage(), and RegisterWorld().
void ManagerConnection::SetClientConnection (const std::shared_ptr< LobbyClientConnection > & connection)
Set an active client connection after its account has been detected.
Parameters
connection Pointer to the client connection
Definition at line 365 of file ManagerConnection.cpp.
References mClientConnections, and lobby::state().
Member Data Documentation
std::unordered_map<libcomp::String, std::shared_ptr<LobbyClientConnection> > lobby::ManagerConnection::mClientConnections private
Map of active client connections by account username.
Definition at line 171 of file ManagerConnection.h.
Referenced by GetClientConnection(), GetClientConnections(), RemoveClientConnection(), and SetClientConnection().
std::shared_ptr<libcomp::MessageQueue< libcomp::Message::Message*> > lobby::ManagerConnection::mMessageQueue private
Pointer to the message queue to use when connecting to world servers.
Definition at line 180 of file ManagerConnection.h.
Referenced by ManagerConnection(), and ProcessMessage().
std::weak_ptr<libcomp::BaseServer> lobby::ManagerConnection::mServer private
Pointer to the server that uses this manager.
Definition at line 161 of file ManagerConnection.h.
Referenced by InitializeWorld(), ManagerConnection(), ProcessMessage(), RemoveClientConnection(), and RemoveWorld().
asio::io_service* lobby::ManagerConnection::mService private
Pointer to the ASIO service to use to establish connections to world servers.
Definition at line 175 of file ManagerConnection.h.
Referenced by ManagerConnection().
std::list<std::shared_ptr<lobby::World> > lobby::ManagerConnection::mUnregisteredWorlds private
List of pointers to unregistered worlds.
Definition at line 167 of file ManagerConnection.h.
Referenced by GetWorldByConnection(), GetWorldByID(), ProcessMessage(), and RemoveWorld().
std::list<std::shared_ptr<lobby::World> > lobby::ManagerConnection::mWorlds private
List of pointers to registered worlds.
Definition at line 164 of file ManagerConnection.h.
Referenced by GetWorldByConnection(), GetWorldByID(), GetWorlds(), RegisterWorld(), and RemoveWorld().
std::list< libcomp::Message::MessageType > ManagerConnection::sSupportedTypes static private
Initial value:
=
    { libcomp::Message::MessageType::MESSAGE_TYPE_CONNECTION }
Static list of supported message types for the manager.
Definition at line 158 of file ManagerConnection.h.
Referenced by GetSupportedTypes().
The documentation for this class was generated from the following files:
ManagerConnection.h
ManagerConnection.cpp