COMP_hack: lobby::LobbySyncManager Class Reference
lobby::LobbySyncManager Class Reference
Lobby specific implementation of the DataSyncManager in charge of performing server side update operations.
#include <LobbySyncManager.h>
Public Member Functions
LobbySyncManager (const std::weak_ptr< LobbyServer > &server)
Create a new LobbySyncManager.
virtual ~LobbySyncManager ()
Clean up the LobbySyncManager.
bool Initialize ()
Initialize the LobbySyncManager after the server has been initialized.
std::shared_ptr< libcomp::Object > New ()
bool RegisterConnection (const std::shared_ptr< InternalConnection > &connection, std::set< std::string > types)
bool RemoveConnection (const std::shared_ptr< InternalConnection > &connection)
virtual bool RemoveRecord (const std::shared_ptr< libcomp::Object > &record, const libcomp::String &type)
void SyncComplete (const libcomp::String &type, const std::list< std::pair< std::shared_ptr< libcomp::Object >, bool >> &objs, const libcomp::String &source)
bool SyncIncoming (libcomp::ReadOnlyPacket &p, const libcomp::String &source="")
void SyncOutgoing ()
bool SyncRecordRemoval (const std::shared_ptr< libcomp::Object > &record, const libcomp::String &type)
bool SyncRecordUpdate (const std::shared_ptr< libcomp::Object > &record, const libcomp::String &type)
int8_t Update (const libcomp::String &type, const std::shared_ptr< libcomp::Object > &obj, bool isRemove, const libcomp::String &source)
template<class T >
int8_t Update (const libcomp::String &type, const std::shared_ptr< libcomp::Object > &obj, bool isRemove, const libcomp::String &source)
Server specific handler for explicit types of non-persistent records being updated.
virtual bool UpdateRecord (const std::shared_ptr< libcomp::Object > &record, const libcomp::String &type)
Protected Member Functions
void QueueOutgoing (const libcomp::String &type, const std::shared_ptr< InternalConnection > &connection, const std::set< std::shared_ptr< libcomp::Object >> &updates, const std::set< std::shared_ptr< libcomp::Object >> &removes)
void WriteOutgoingRecord (libcomp::Packet &p, bool isPersistent, const libcomp::String &type, const std::shared_ptr< libcomp::Object > &record)
Protected Attributes
std::mutex mLock
std::unordered_map
< std::string, std::shared_ptr
< ObjectConfig > > mRegisteredTypes
Static Protected Attributes
static const int8_t SYNC_FAILED
static const int8_t SYNC_HANDLED
static const int8_t SYNC_UPDATED
Private Member Functions
void SyncAccount (const std::shared_ptr< objects::Account > &account)
Sync the supplied account.
void SyncCharacter (const std::shared_ptr< objects::Character > &character, bool isRemove)
Sync the supplied character, should be used for all delete requests.
void SyncCharacterProgress (const std::shared_ptr< objects::CharacterProgress > &progress)
Sync the supplied character progress.
Private Attributes
std::weak_ptr< LobbyServer > mServer
Pointer to the lobby server.
Detailed Description
Lobby specific implementation of the DataSyncManager in charge of performing server side update operations.
Definition at line 54 of file LobbySyncManager.h.
Constructor & Destructor Documentation
LobbySyncManager::LobbySyncManager (const std::weak_ptr< LobbyServer > & server)
Create a new LobbySyncManager.
Parameters
server Pointer back to the channel server this belongs to.
Definition at line 50 of file LobbySyncManager.cpp.
Referenced by Initialize().
LobbySyncManager::~LobbySyncManager () virtual
Clean up the LobbySyncManager.
Definition at line 55 of file LobbySyncManager.cpp.
Member Function Documentation
bool LobbySyncManager::Initialize ()
Initialize the LobbySyncManager after the server has been initialized.
Returns
false if any errors were encountered and the server should be shut down.
Definition at line 59 of file LobbySyncManager.cpp.
References LobbySyncManager(), libcomp::DataSyncManager::mRegisteredTypes, and mServer.
Referenced by lobby::LobbyServer::Initialize().
void LobbySyncManager::SyncAccount (const std::shared_ptr< objects::Account > & account) private
Sync the supplied account.
Parameters
account Pointer to the account record to sync
Definition at line 144 of file LobbySyncManager.cpp.
References mServer, and libcomp::DataSyncManager::WriteOutgoingRecord().
void LobbySyncManager::SyncCharacter (const std::shared_ptr< objects::Character > & character, bool isRemove) private
Sync the supplied character, should be used for all delete requests.
Parameters
character Pointer to the character record to sync
isRemove true if the update is a remove, false if it is an insert or update
Definition at line 169 of file LobbySyncManager.cpp.
References mServer, and libcomp::DataSyncManager::QueueOutgoing().
void LobbySyncManager::SyncCharacterProgress (const std::shared_ptr< objects::CharacterProgress > & progress) private
Sync the supplied character progress.
Parameters
progress Pointer to the character progress record to sync
Definition at line 199 of file LobbySyncManager.cpp.
References libcomp::String::Arg(), libcomp::PersistentObject::GetObjectByUUID(), mServer, and libcomp::DataSyncManager::QueueOutgoing().
template<class T > int8_t lobby::LobbySyncManager::Update (const libcomp::String & type, const std::shared_ptr< libcomp::Object > & obj, bool isRemove, const libcomp::String & source)
Server specific handler for explicit types of non-persistent records being updated.
Parameters
type Type name of the object being updated
obj Pointer to the record definition
isRemove true if the record is being removed, false if it is either an insert or an update
source Source server identifier
Returns
Response codes matching the internal DataSyncManager set
Member Data Documentation
std::weak_ptr<LobbyServer> lobby::LobbySyncManager::mServer private
Pointer to the lobby server.
Definition at line 113 of file LobbySyncManager.h.
Referenced by Initialize(), SyncAccount(), SyncCharacter(), and SyncCharacterProgress().
The documentation for this class was generated from the following files:
LobbySyncManager.h
LobbySyncManager.cpp