COMP_hack: lobby::ApiHandler Class Reference
lobby::ApiHandler Class Reference
#include <ApiHandler.h>
Public Member Functions
ApiHandler (const std::shared_ptr< objects::LobbyConfig > &config, const std::shared_ptr< lobby::LobbyServer > &server)
virtual ~ApiHandler ()
virtual bool handlePost (CivetServer *pServer, struct mg_connection *pConnection)
void SetAccountManager (AccountManager *pManager)
Protected Member Functions
bool Account_ChangePassword (const JsonBox::Object &request, JsonBox::Object &response, const std::shared_ptr< ApiSession > &session)
bool Account_ClientLogin (const JsonBox::Object &request, JsonBox::Object &response, const std::shared_ptr< ApiSession > &session)
bool Account_GetCP (const JsonBox::Object &request, JsonBox::Object &response, const std::shared_ptr< ApiSession > &session)
bool Account_GetDetails (const JsonBox::Object &request, JsonBox::Object &response, const std::shared_ptr< ApiSession > &session)
bool Account_Register (const JsonBox::Object &request, JsonBox::Object &response, const std::shared_ptr< ApiSession > &session)
bool Admin_CreatePromo (const JsonBox::Object &request, JsonBox::Object &response, const std::shared_ptr< ApiSession > &session)
bool Admin_DeleteAccount (const JsonBox::Object &request, JsonBox::Object &response, const std::shared_ptr< ApiSession > &session)
bool Admin_DeletePromo (const JsonBox::Object &request, JsonBox::Object &response, const std::shared_ptr< ApiSession > &session)
bool Admin_GetAccount (const JsonBox::Object &request, JsonBox::Object &response, const std::shared_ptr< ApiSession > &session)
bool Admin_GetAccounts (const JsonBox::Object &request, JsonBox::Object &response, const std::shared_ptr< ApiSession > &session)
bool Admin_GetPromos (const JsonBox::Object &request, JsonBox::Object &response, const std::shared_ptr< ApiSession > &session)
bool Admin_KickPlayer (const JsonBox::Object &request, JsonBox::Object &response, const std::shared_ptr< ApiSession > &session)
bool Admin_MessageWorld (const JsonBox::Object &request, JsonBox::Object &response, const std::shared_ptr< ApiSession > &session)
bool Admin_Online (const JsonBox::Object &request, JsonBox::Object &response, const std::shared_ptr< ApiSession > &session)
bool Admin_PostItems (const JsonBox::Object &request, JsonBox::Object &response, const std::shared_ptr< ApiSession > &session)
bool Admin_UpdateAccount (const JsonBox::Object &request, JsonBox::Object &response, const std::shared_ptr< ApiSession > &session)
bool Auth_Token (const JsonBox::Object &request, JsonBox::Object &response, const std::shared_ptr< ApiSession > &session)
bool Authenticate (const JsonBox::Object &request, JsonBox::Object &response, const std::shared_ptr< ApiSession > &session)
std::shared_ptr
< libcomp::Database > GetDatabase () const
bool WebGame_GetCoins (const JsonBox::Object &request, JsonBox::Object &response, const std::shared_ptr< ApiSession > &session)
bool WebGame_Start (const JsonBox::Object &request, JsonBox::Object &response, const std::shared_ptr< ApiSession > &session)
bool WebGame_Update (const JsonBox::Object &request, JsonBox::Object &response, const std::shared_ptr< ApiSession > &session)
int64_t WebGameScript_GetCoins (const std::shared_ptr< ApiSession > &session)
std::shared_ptr
< libcomp::Database > WebGameScript_GetDatabase (const std::shared_ptr< ApiSession > &session, bool worldDB)
int64_t WebGameScript_GetSystemTime ()
void WebGameScript_SetResponse (JsonBox::Object *response, const libcomp::String &key, const libcomp::String &value)
bool WebGameScript_UpdateCoins (const std::shared_ptr< ApiSession > &session, int64_t coins, bool adjust)
Private Member Functions
std::shared_ptr< objects::Account > GetAccount (const JsonBox::Object &obj, JsonBox::Object &response)
bool GetWebGameSession (JsonBox::Object &response, const std::shared_ptr< ApiSession > &session, std::shared_ptr< objects::WebGameSession > &gameSession, std::shared_ptr< World > &world)
std::shared_ptr< World > GetWorld (const JsonBox::Object &obj, JsonBox::Object &response)
bool HaveUserLevel (JsonBox::Object &response, const std::shared_ptr< ApiSession > &session, uint32_t requiredLevel)
Private Attributes
AccountManager * mAccountManager
std::shared_ptr
< objects::LobbyConfig > mConfig
libcomp::DefinitionManager * mDefinitionManager
std::unordered_map
< libcomp::String,
std::shared_ptr
< libcomp::ServerScript > > mGameDefinitions
std::unordered_map
< libcomp::String,
std::function< bool(ApiHandler
&, const JsonBox::Object
&request, JsonBox::Object
&response, const
std::shared_ptr< ApiSession >
&session)> > mParsers
List of API parsers.
std::shared_ptr
< lobby::LobbyServer > mServer
std::unordered_map
< libcomp::String,
std::shared_ptr< ApiSession > > mSessions
Detailed Description
Definition at line 97 of file ApiHandler.h.
Constructor & Destructor Documentation
ApiHandler::ApiHandler (const std::shared_ptr< objects::LobbyConfig > & config, const std::shared_ptr< lobby::LobbyServer > & server)
Definition at line 75 of file ApiHandler.cpp.
References Account_ChangePassword(), Account_ClientLogin(), Account_GetCP(), Account_GetDetails(), Account_Register(), Admin_CreatePromo(), Admin_DeleteAccount(), Admin_DeletePromo(), Admin_GetAccount(), Admin_GetAccounts(), Admin_GetPromos(), Admin_KickPlayer(), Admin_MessageWorld(), Admin_Online(), Admin_PostItems(), Admin_UpdateAccount(), libcomp::String::Arg(), Auth_Token(), libcomp::DefinitionManager::LoadData(), mDefinitionManager, mGameDefinitions, mParsers, WebGame_GetCoins(), WebGame_Start(), and WebGame_Update().
Referenced by WebGame_Start().
ApiHandler::~ApiHandler () virtual
Definition at line 145 of file ApiHandler.cpp.
Member Function Documentation
bool ApiHandler::Account_ChangePassword (const JsonBox::Object & request, JsonBox::Object & response, const std::shared_ptr< ApiSession > & session) protected
Definition at line 263 of file ApiHandler.cpp.
References libcomp::Crypto::GenerateRandom(), GetDatabase(), libcomp::Crypto::HashPassword(), and libcomp::String::Matches().
Referenced by ApiHandler().
bool ApiHandler::Account_ClientLogin (const JsonBox::Object & request, JsonBox::Object & response, const std::shared_ptr< ApiSession > & session) protected
Definition at line 330 of file ApiHandler.cpp.
References ErrorCodeString(), GetDatabase(), mAccountManager, to_underlying(), libcomp::String::ToDecimal(), libcomp::String::ToUtf8(), and lobby::AccountManager::WebAuthLoginApi().
Referenced by ApiHandler().
bool ApiHandler::Account_GetCP (const JsonBox::Object & request, JsonBox::Object & response, const std::shared_ptr< ApiSession > & session) protected
Definition at line 206 of file ApiHandler.cpp.
References GetDatabase().
Referenced by ApiHandler().
bool ApiHandler::Account_GetDetails (const JsonBox::Object & request, JsonBox::Object & response, const std::shared_ptr< ApiSession > & session) protected
Definition at line 225 of file ApiHandler.cpp.
References GetDatabase().
Referenced by ApiHandler().
bool ApiHandler::Account_Register (const JsonBox::Object & request, JsonBox::Object & response, const std::shared_ptr< ApiSession > & session) protected
Definition at line 404 of file ApiHandler.cpp.
References libcomp::Crypto::GenerateRandom(), GetDatabase(), libcomp::Crypto::HashPassword(), libcomp::String::IsEmpty(), libcomp::String::Matches(), mConfig, and libcomp::String::ToLower().
Referenced by ApiHandler().
bool ApiHandler::Admin_CreatePromo (const JsonBox::Object & request, JsonBox::Object & response, const std::shared_ptr< ApiSession > & session) protected
Definition at line 1377 of file ApiHandler.cpp.
References GetDatabase(), libcomp::DefinitionManager::GetShopProductData(), HaveUserLevel(), libcomp::String::IsEmpty(), mDefinitionManager, and SVR_CONST.
Referenced by ApiHandler().
bool ApiHandler::Admin_DeleteAccount (const JsonBox::Object & request, JsonBox::Object & response, const std::shared_ptr< ApiSession > & session) protected
Definition at line 624 of file ApiHandler.cpp.
References GetDatabase(), HaveUserLevel(), SVR_CONST, and libcomp::String::ToLower().
Referenced by ApiHandler().
bool ApiHandler::Admin_DeletePromo (const JsonBox::Object & request, JsonBox::Object & response, const std::shared_ptr< ApiSession > & session) protected
Definition at line 1532 of file ApiHandler.cpp.
References libcomp::String::Arg(), GetDatabase(), HaveUserLevel(), libcomp::String::IsEmpty(), SVR_CONST, and libcomp::String::ToUtf8().
Referenced by ApiHandler().
bool ApiHandler::Admin_GetAccount (const JsonBox::Object & request, JsonBox::Object & response, const std::shared_ptr< ApiSession > & session) protected
Definition at line 567 of file ApiHandler.cpp.
References GetDatabase(), HaveUserLevel(), SVR_CONST, and libcomp::String::ToLower().
Referenced by ApiHandler().
bool ApiHandler::Admin_GetAccounts (const JsonBox::Object & request, JsonBox::Object & response, const std::shared_ptr< ApiSession > & session) protected
Definition at line 511 of file ApiHandler.cpp.
References GetDatabase(), HaveUserLevel(), and SVR_CONST.
Referenced by ApiHandler().
bool ApiHandler::Admin_GetPromos (const JsonBox::Object & request, JsonBox::Object & response, const std::shared_ptr< ApiSession > & session) protected
Definition at line 1320 of file ApiHandler.cpp.
References GetDatabase(), HaveUserLevel(), and SVR_CONST.
Referenced by ApiHandler().
bool ApiHandler::Admin_KickPlayer (const JsonBox::Object & request, JsonBox::Object & response, const std::shared_ptr< ApiSession > & session) protected
Definition at line 806 of file ApiHandler.cpp.
References GetAccount(), HaveUserLevel(), lobby::AccountManager::IsLoggedIn(), mAccountManager, mServer, SVR_CONST, libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS8(), libcomp::Packet::WriteString16Little(), and libcomp::Packet::WriteU32Little().
Referenced by ApiHandler().
bool ApiHandler::Admin_MessageWorld (const JsonBox::Object & request, JsonBox::Object & response, const std::shared_ptr< ApiSession > & session) protected
Definition at line 885 of file ApiHandler.cpp.
References GetWorld(), HaveUserLevel(), libcomp::String::IsEmpty(), SVR_CONST, libcomp::String::ToLower(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS8(), libcomp::Packet::WriteString16Little(), libcomp::Packet::WriteU16Little(), and libcomp::Packet::WriteU8().
Referenced by ApiHandler().
bool ApiHandler::Admin_Online (const JsonBox::Object & request, JsonBox::Object & response, const std::shared_ptr< ApiSession > & session) protected
Definition at line 989 of file ApiHandler.cpp.
References lobby::AccountManager::GetUserLogin(), lobby::AccountManager::GetUsersInWorld(), GetWorld(), HaveUserLevel(), libcomp::String::IsEmpty(), libcomp::PersistentObject::LoadObjectByUUID(), mAccountManager, mServer, SVR_CONST, libcomp::String::ToLower(), and libcomp::String::ToUtf8().
Referenced by ApiHandler().
bool ApiHandler::Admin_PostItems (const JsonBox::Object & request, JsonBox::Object & response, const std::shared_ptr< ApiSession > & session) protected
Definition at line 1179 of file ApiHandler.cpp.
References GetAccount(), libcomp::DefinitionManager::GetShopProductData(), lobby::AccountManager::GetUserLogin(), HaveUserLevel(), mAccountManager, mDefinitionManager, mServer, SVR_CONST, libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS64Little(), libcomp::Packet::WriteU16Little(), and libcomp::Packet::WriteU8().
Referenced by ApiHandler().
bool ApiHandler::Admin_UpdateAccount (const JsonBox::Object & request, JsonBox::Object & response, const std::shared_ptr< ApiSession > & session) protected
Definition at line 668 of file ApiHandler.cpp.
References libcomp::Crypto::GenerateRandom(), GetAccount(), GetDatabase(), libcomp::Crypto::HashPassword(), HaveUserLevel(), libcomp::String::Matches(), and SVR_CONST.
Referenced by ApiHandler().
bool ApiHandler::Auth_Token (const JsonBox::Object & request, JsonBox::Object & response, const std::shared_ptr< ApiSession > & session) protected
Definition at line 149 of file ApiHandler.cpp.
References libcomp::String::Arg(), libcomp::Crypto::GenerateRandom(), GetDatabase(), libcomp::String::ToLower(), and libcomp::String::ToUtf8().
Referenced by ApiHandler().
bool ApiHandler::Authenticate (const JsonBox::Object & request, JsonBox::Object & response, const std::shared_ptr< ApiSession > & session) protected
Definition at line 1936 of file ApiHandler.cpp.
References libcomp::Crypto::GenerateRandom(), libcomp::Crypto::HashPassword(), and libcomp::String::ToUtf8().
Referenced by handlePost().
std::shared_ptr< objects::Account > ApiHandler::GetAccount (const JsonBox::Object & obj, JsonBox::Object & response) private
Definition at line 2229 of file ApiHandler.cpp.
References GetDatabase(), and libcomp::String::ToLower().
Referenced by Admin_KickPlayer(), Admin_PostItems(), and Admin_UpdateAccount().
std::shared_ptr< libcomp::Database > ApiHandler::GetDatabase () const protected
Definition at line 1979 of file ApiHandler.cpp.
References libcomp::BaseServer::GetDatabase(), and mConfig.
Referenced by Account_ChangePassword(), Account_ClientLogin(), Account_GetCP(), Account_GetDetails(), Account_Register(), Admin_CreatePromo(), Admin_DeleteAccount(), Admin_DeletePromo(), Admin_GetAccount(), Admin_GetAccounts(), Admin_GetPromos(), Admin_UpdateAccount(), Auth_Token(), and GetAccount().
bool ApiHandler::GetWebGameSession (JsonBox::Object & response, const std::shared_ptr< ApiSession > & session, std::shared_ptr< objects::WebGameSession > & gameSession, std::shared_ptr< World > & world) private
Definition at line 2296 of file ApiHandler.cpp.
References mServer, and lobby::WebGameApiSession::webGameSession.
Referenced by WebGame_GetCoins(), WebGame_Start(), and WebGame_Update().
std::shared_ptr< World > ApiHandler::GetWorld (const JsonBox::Object & obj, JsonBox::Object & response) private
Definition at line 2261 of file ApiHandler.cpp.
References mServer.
Referenced by Admin_MessageWorld(), and Admin_Online().
bool ApiHandler::handlePost (CivetServer * pServer, struct mg_connection * pConnection) virtual
Definition at line 2001 of file ApiHandler.cpp.
References libcomp::String::Arg(), Authenticate(), libcomp::String::IsEmpty(), libcomp::String::Left(), MAX_PAYLOAD, libcomp::String::Mid(), mParsers, mServer, and mSessions.
bool ApiHandler::HaveUserLevel (JsonBox::Object & response, const std::shared_ptr< ApiSession > & session, uint32_t requiredLevel) private
Definition at line 2319 of file ApiHandler.cpp.
References libcomp::String::Arg(), and libcomp::String::ToUtf8().
Referenced by Admin_CreatePromo(), Admin_DeleteAccount(), Admin_DeletePromo(), Admin_GetAccount(), Admin_GetAccounts(), Admin_GetPromos(), Admin_KickPlayer(), Admin_MessageWorld(), Admin_Online(), Admin_PostItems(), and Admin_UpdateAccount().
void ApiHandler::SetAccountManager (AccountManager * pManager)
Definition at line 2224 of file ApiHandler.cpp.
References mAccountManager.
bool ApiHandler::WebGame_GetCoins (const JsonBox::Object & request, JsonBox::Object & response, const std::shared_ptr< ApiSession > & session) protected
Definition at line 1581 of file ApiHandler.cpp.
References libcomp::String::Arg(), libcomp::String::C(), GetWebGameSession(), and WebGameScript_GetCoins().
Referenced by ApiHandler().
bool ApiHandler::WebGame_Start (const JsonBox::Object & request, JsonBox::Object & response, const std::shared_ptr< ApiSession > & session) protected
Definition at line 1607 of file ApiHandler.cpp.
References ApiHandler(), libcomp::String::Arg(), GetWebGameSession(), mGameDefinitions, WebGameScript_GetCoins(), WebGameScript_GetDatabase(), WebGameScript_GetSystemTime(), WebGameScript_SetResponse(), and WebGameScript_UpdateCoins().
Referenced by ApiHandler().
bool ApiHandler::WebGame_Update (const JsonBox::Object & request, JsonBox::Object & response, const std::shared_ptr< ApiSession > & session) protected
Definition at line 1715 of file ApiHandler.cpp.
References libcomp::String::Arg(), libcomp::String::C(), and GetWebGameSession().
Referenced by ApiHandler().
int64_t ApiHandler::WebGameScript_GetCoins (const std::shared_ptr< ApiSession > & session) protected
Definition at line 1795 of file ApiHandler.cpp.
References WebGameScript_GetDatabase(), and lobby::WebGameApiSession::webGameSession.
Referenced by WebGame_GetCoins(), and WebGame_Start().
std::shared_ptr< libcomp::Database > ApiHandler::WebGameScript_GetDatabase (const std::shared_ptr< ApiSession > & session, bool worldDB) protected
Definition at line 1822 of file ApiHandler.cpp.
References mServer, and lobby::WebGameApiSession::webGameSession.
Referenced by WebGame_Start(), WebGameScript_GetCoins(), and WebGameScript_UpdateCoins().
int64_t ApiHandler::WebGameScript_GetSystemTime () protected
Definition at line 1849 of file ApiHandler.cpp.
Referenced by WebGame_Start().
void ApiHandler::WebGameScript_SetResponse (JsonBox::Object * response, const libcomp::String & key, const libcomp::String & value) protected
Definition at line 1866 of file ApiHandler.cpp.
References libcomp::String::C().
Referenced by WebGame_Start().
bool ApiHandler::WebGameScript_UpdateCoins (const std::shared_ptr< ApiSession > & session, int64_t coins, bool adjust) protected
Definition at line 1875 of file ApiHandler.cpp.
References mServer, WebGameScript_GetDatabase(), and lobby::WebGameApiSession::webGameSession.
Referenced by WebGame_Start().
Member Data Documentation
AccountManager* lobby::ApiHandler::mAccountManager private
Definition at line 217 of file ApiHandler.h.
Referenced by Account_ClientLogin(), Admin_KickPlayer(), Admin_Online(), Admin_PostItems(), and SetAccountManager().
std::shared_ptr<objects::LobbyConfig> lobby::ApiHandler::mConfig private
Definition at line 211 of file ApiHandler.h.
Referenced by Account_Register(), and GetDatabase().
libcomp::DefinitionManager* lobby::ApiHandler::mDefinitionManager private
Definition at line 218 of file ApiHandler.h.
Referenced by Admin_CreatePromo(), Admin_PostItems(), and ApiHandler().
std::unordered_map<libcomp::String, std::shared_ptr<libcomp::ServerScript> > lobby::ApiHandler::mGameDefinitions private
Definition at line 215 of file ApiHandler.h.
Referenced by ApiHandler(), and WebGame_Start().
std::unordered_map<libcomp::String, std::function<bool(ApiHandler&, const JsonBox::Object& request, JsonBox::Object& response, const std::shared_ptr<ApiSession>& session)> > lobby::ApiHandler::mParsers private
List of API parsers.
Definition at line 209 of file ApiHandler.h.
Referenced by ApiHandler(), and handlePost().
std::shared_ptr<lobby::LobbyServer> lobby::ApiHandler::mServer private
Definition at line 212 of file ApiHandler.h.
Referenced by Admin_KickPlayer(), Admin_Online(), Admin_PostItems(), GetWebGameSession(), GetWorld(), handlePost(), WebGameScript_GetDatabase(), and WebGameScript_UpdateCoins().
std::unordered_map<libcomp::String, std::shared_ptr<ApiSession> > lobby::ApiHandler::mSessions private
Definition at line 204 of file ApiHandler.h.
Referenced by handlePost().
The documentation for this class was generated from the following files:
ApiHandler.h
ApiHandler.cpp