COMP_hack: lobby Namespace Reference
lobby Namespace Reference
Namespaces
Parsers
Classes
class AccountManager
Manages logged in user accounts.
class ApiHandler
class ApiSession
class ClientState
class ImportHandler
class LobbyClientConnection
class LobbyServer
class LobbySyncManager
Lobby specific implementation of the DataSyncManager in charge of performing server side update operations.
class LoginHandler
class LoginHandlerThread
class ManagerClientPacket
Manager class responsible for handling client side packets.
class ManagerConnection
Class to handle messages pertaining to connecting to worlds or game clients.
class WebGameApiSession
class World
Associates a world connection to RegisteredWorld and its channels for the lobby.
Functions
static std::shared_ptr
< objects::LobbyConfig > config (libcomp::ManagerPacket *pPacketManager)
template<>
int8_t LobbySyncManager::Update< objects::Account > (const libcomp::String &type, const std::shared_ptr< libcomp::Object > &obj, bool isRemove, const libcomp::String &source)
template<>
int8_t LobbySyncManager::Update< objects::Character > (const libcomp::String &type, const std::shared_ptr< libcomp::Object > &obj, bool isRemove, const libcomp::String &source)
template<>
int8_t LobbySyncManager::Update< objects::CharacterProgress > (const libcomp::String &type, const std::shared_ptr< libcomp::Object > &obj, bool isRemove, const libcomp::String &source)
static ClientState * state (const std::shared_ptr< libcomp::TcpConnection > &connection)
Function Documentation
static std::shared_ptr<objects::LobbyConfig> lobby::config (libcomp::ManagerPacket * pPacketManager) inline static
Definition at line 72 of file LobbyClientConnection.h.
References libcomp::ManagerPacket::GetServer().
Referenced by lobby::AccountManager::Logout(), main(), NoWebAuthParse(), lobby::LoginHandler::SetConfig(), lobby::AccountManager::UpdateKillTime(), and lobby::AccountManager::WebAuthLogin().
template<> int8_t lobby::LobbySyncManager::Update< objects::Account > (const libcomp::String & type, const std::shared_ptr< libcomp::Object > & obj, bool isRemove, const libcomp::String & source)
Definition at line 94 of file LobbySyncManager.cpp.
template<> int8_t lobby::LobbySyncManager::Update< objects::Character > (const libcomp::String & type, const std::shared_ptr< libcomp::Object > & obj, bool isRemove, const libcomp::String & source)
Definition at line 110 of file LobbySyncManager.cpp.
template<> int8_t lobby::LobbySyncManager::Update< objects::CharacterProgress > (const libcomp::String & type, const std::shared_ptr< libcomp::Object > & obj, bool isRemove, const libcomp::String & source)
Definition at line 125 of file LobbySyncManager.cpp.
static ClientState* lobby::state (const std::shared_ptr< libcomp::TcpConnection > & connection) inline static
Definition at line 57 of file LobbyClientConnection.h.
Referenced by lobby::AccountManager::LobbyLogin(), NoWebAuthParse(), lobby::AccountManager::PrintAccounts(), lobby::ManagerConnection::RemoveClientConnection(), lobby::ManagerConnection::SetClientConnection(), lobby::LobbyClientConnection::SetClientState(), lobby::ManagerClientPacket::ValidateConnectionState(), and lobby::AccountManager::WebAuthLogin().