COMP_hack: world::ManagerConnection Class Reference
world::ManagerConnection Class Reference
Class to handle messages pertaining to connecting to the lobby or channels.
#include <ManagerConnection.h>
Public Member Functions
ManagerConnection (std::weak_ptr< libcomp::BaseServer > server)
Create a new manager.
virtual ~ManagerConnection ()
Clean up the manager.
std::shared_ptr
< libcomp::InternalConnection > GetLobbyConnection ()
Get a pointer to the lobby connection.
virtual std::list
< libcomp::Message::MessageType > GetSupportedTypes () const
Get the different types of messages handled by this manager.
bool LobbyConnected ()
Check if the lobby connection is currently active.
virtual bool ProcessMessage (const libcomp::Message::Message *pMessage)
Process a message from the queue.
void RemoveConnection (std::shared_ptr< libcomp::InternalConnection > &connection)
Remove a connection and any associated channel when no longer needed.
Private Attributes
std::shared_ptr
< libcomp::InternalConnection > mLobbyConnection
Pointer to the lobby connection after connecting.
std::weak_ptr
< libcomp::BaseServer > mServer
Pointer to the server that uses this manager.
Static Private Attributes
static std::list
< libcomp::Message::MessageType > sSupportedTypes
Static list of supported message types for the manager.
Detailed Description
Class to handle messages pertaining to connecting to the lobby or channels.
Definition at line 46 of file ManagerConnection.h.
Constructor & Destructor Documentation
ManagerConnection::ManagerConnection (std::weak_ptr< libcomp::BaseServer > server)
Create a new manager.
Parameters
server Pointer to the server that uses this manager
Definition at line 46 of file ManagerConnection.cpp.
ManagerConnection::~ManagerConnection () virtual
Clean up the manager.
Definition at line 51 of file ManagerConnection.cpp.
Member Function Documentation
std::shared_ptr< libcomp::InternalConnection > ManagerConnection::GetLobbyConnection ()
Get a pointer to the lobby connection.
Returns
Pointer to the lobby connection
Definition at line 124 of file ManagerConnection.cpp.
References mLobbyConnection.
std::list< libcomp::Message::MessageType > ManagerConnection::GetSupportedTypes () const virtual
Get the different types of messages handled by this manager.
Returns
List of supported message types
Implements libcomp::Manager.
Definition at line 56 of file ManagerConnection.cpp.
References sSupportedTypes.
bool ManagerConnection::LobbyConnected ()
Check if the lobby connection is currently active.
Returns
true if connected, false if not connected
Definition at line 129 of file ManagerConnection.cpp.
References mLobbyConnection.
Referenced by ProcessMessage().
bool ManagerConnection::ProcessMessage (const libcomp::Message::Message * pMessage) virtual
Process a message from the queue.
Parameters
pMessage Message to be processed
Returns
true on success, false on failure
Todo:
: verify this is in fact the lobby
Todo:
: if it's not this reacts horribly
Todo:
: if the lobby pointer is not set before a channel it will crash the world
Implements libcomp::Manager.
Definition at line 61 of file ManagerConnection.cpp.
References libcomp::Message::CONNECTION_MESSAGE_CONNECTION_CLOSED, libcomp::Message::CONNECTION_MESSAGE_ENCRYPTED, libcomp::Message::Encrypted::GetConnection(), libcomp::Message::ConnectionClosed::GetConnection(), libcomp::Message::ConnectionMessage::GetConnectionMessageType(), LobbyConnected(), mLobbyConnection, mServer, and RemoveConnection().
void ManagerConnection::RemoveConnection (std::shared_ptr< libcomp::InternalConnection > & connection)
Remove a connection and any associated channel when no longer needed.
This should always be a channel connection but should be called regardless.
Parameters
connection Pointer to an internal connection
Definition at line 134 of file ManagerConnection.cpp.
References libcomp::String::Arg(), world::WorldServer::GetChannel(), mLobbyConnection, mServer, to_underlying(), libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteU8().
Referenced by ProcessMessage().
Member Data Documentation
std::shared_ptr<libcomp::InternalConnection> world::ManagerConnection::mLobbyConnection private
Pointer to the lobby connection after connecting.
Definition at line 101 of file ManagerConnection.h.
Referenced by GetLobbyConnection(), LobbyConnected(), ProcessMessage(), and RemoveConnection().
std::weak_ptr<libcomp::BaseServer> world::ManagerConnection::mServer private
Pointer to the server that uses this manager.
Definition at line 98 of file ManagerConnection.h.
Referenced by ProcessMessage(), and RemoveConnection().
std::list< libcomp::Message::MessageType > ManagerConnection::sSupportedTypes static private
Initial value:
=
    { libcomp::Message::MessageType::MESSAGE_TYPE_CONNECTION }
Static list of supported message types for the manager.
Definition at line 95 of file ManagerConnection.h.
Referenced by GetSupportedTypes().
The documentation for this class was generated from the following files:
ManagerConnection.h
ManagerConnection.cpp