COMP_hack: world::AccountManager Class Reference
world::AccountManager Class Reference
Manages logged in user accounts.
#include <AccountManager.h>
Public Member Functions
AccountManager (const std::weak_ptr< WorldServer > &server)
Create a new account manager.
bool ChannelLogin (std::shared_ptr< objects::AccountLogin > login)
Update the supplied login, set the login state to CHANNEL and the character status to ONLINE.
bool ChannelSwitchPending (const libcomp::String &username, int8_t &channel)
Check if any existing channel switch signifier exists for the specified account.
void CleanupAccountWorldData ()
Perform all clean up operations related to each AccountWorldData entry with CleanupRequired currently flagged.
void CompleteLobbyLogin (const std::shared_ptr< objects::AccountLogin > &login, const std::shared_ptr< objects::ChannelLogin > &channelLogin=nullptr)
Complete the request to connect to a channel from the lobby.
bool DeleteCharacter (const std::shared_ptr< objects::Character > &character)
Delete a character requested from the lobby or otherwise marked for deletion by cleaning up all related character objects.
bool EndWebGameSession (const libcomp::String &username, bool notifyLobby, bool notifyChannel)
Start any web-game session for the specified user and notify the other servers as needed.
bool ExpireSession (const libcomp::String &username, uint32_t key)
Expire the user session and log out the account.
std::shared_ptr
< objects::WebGameSession > GetGameSession (const libcomp::String &username)
Get the current web-game session for the specified user.
std::shared_ptr
< objects::AccountLogin > GetUserLogin (const libcomp::String &username)
Get the current user login state independent of world.
void HandleChannelLogin (const std::shared_ptr< libcomp::InternalConnection > &requestConnection, uint32_t sessionKey, const libcomp::String &username)
Handle a request to complete a channel login.
void HandleLobbyLogin (const std::shared_ptr< objects::AccountLogin > &login)
Handle a request to connect to a channel from the lobby.
bool IsLoggedIn (const libcomp::String &username, int8_t &channel)
Check if a user is logged in.
bool LobbyLogin (std::shared_ptr< objects::AccountLogin > login)
Register the supplied login with the world if it has not been already.
std::shared_ptr
< objects::AccountLogin > LogoutUser (const libcomp::String &username, int8_t channel=-1)
Mark the user logged out of the given channel.
std::list< std::shared_ptr
< objects::AccountLogin > > LogoutUsersOnChannel (int8_t channel)
Log out all users on a given channel.
std::shared_ptr
< objects::ChannelLogin > PopChannelSwitch (const libcomp::String &username)
"Pop" any existing channel switch signifier from the manager for the specified account and return it
bool StartWebGameSession (const std::shared_ptr< objects::WebGameSession > &gameSession)
Start a web-game session for the specified user who is currently playing that remains valid until a remove request is received or the account leaves the channel.
bool SwitchChannel (std::shared_ptr< objects::AccountLogin > login, const std::shared_ptr< objects::ChannelLogin > &switchDef)
Transition the login from CHANNEL to CHANNEL_TO_CHANNEL and schedule a timeout.
Private Member Functions
void Cleanup (const std::shared_ptr< objects::AccountLogin > &login)
Utility function to free up references to an AccountLogin loaded by the world.
template<class T >
void Cleanup (const std::shared_ptr< T > &obj)
Utility function to free up references to a PersistentObject loaded by the world.
void PushChannelSwitch (const libcomp::String &username, const std::shared_ptr< objects::ChannelLogin > &switchDef)
"Push" a channel switch signifier to the manager for the specified account.
void UpdateSessionKey (std::shared_ptr< objects::AccountLogin > login)
Update the session key of the supplied login.
Private Attributes
std::unordered_map
< libcomp::String,
std::shared_ptr
< objects::AccountLogin > > mAccountMap
Map of account login information by username.
std::unordered_map
< libcomp::String,
std::shared_ptr
< objects::ChannelLogin > > mChannelSwitches
Map of account usernames associated to accounts set to switch channel upon next disconnect from a channel.
std::mutex mLock
Server lock for shared resources.
std::weak_ptr< WorldServer > mServer
Pointer back to theworld server this belongs to.
std::unordered_map
< libcomp::String,
std::shared_ptr
< objects::WebGameSession > > mWebGameSessions
Map of account usernames associated to accounts to web-game sessions either pending or active for a character currently playing.
Detailed Description
Manages logged in user accounts.
Definition at line 56 of file AccountManager.h.
Constructor & Destructor Documentation
AccountManager::AccountManager (const std::weak_ptr< WorldServer > & server)
Create a new account manager.
Parameters
server Pointer back to the world server this belongs to
Definition at line 69 of file AccountManager.cpp.
Member Function Documentation
bool AccountManager::ChannelLogin (std::shared_ptr< objects::AccountLogin > login)
Update the supplied login, set the login state to CHANNEL and the character status to ONLINE.
Also perform any "on login" actions.
Parameters
login Login information associated to the account.
Returns
true if the account was successfully updated; false if an error occurred.
Definition at line 134 of file AccountManager.cpp.
References libcomp::String::Arg(), libcomp::DatabaseChangeSet::Create(), mLock, and mServer.
Referenced by HandleChannelLogin().
bool AccountManager::ChannelSwitchPending (const libcomp::String & username, int8_t & channel)
Check if any existing channel switch signifier exists for the specified account.
Parameters
username Username of the account set to check
channel Output parameter to store the channel being switched to. If no channel switch is stored, this will not be set.
Returns
Pointer to the channel switch definition
Definition at line 935 of file AccountManager.cpp.
References mChannelSwitches, mLock, and libcomp::String::ToLower().
void AccountManager::Cleanup (const std::shared_ptr< objects::AccountLogin > & login) private
Utility function to free up references to an AccountLogin loaded by the world.
Parameters
login Pointer to the AcccountLogin to clean up
Definition at line 1427 of file AccountManager.cpp.
Referenced by DeleteCharacter(), LogoutUser(), and LogoutUsersOnChannel().
template<class T > void world::AccountManager::Cleanup (const std::shared_ptr< T > & obj) inline private
Utility function to free up references to a PersistentObject loaded by the world.
Parameters
login Pointer to the PersistentObject to clean up
Definition at line 274 of file AccountManager.h.
References libcomp::ObjectReference< class >::Unload().
void AccountManager::CleanupAccountWorldData ()
Perform all clean up operations related to each AccountWorldData entry with CleanupRequired currently flagged.
Definition at line 968 of file AccountManager.cpp.
References libcomp::String::Arg(), DeleteCharacter(), libcomp::PersistentObject::LoadObjectByUUID(), and mServer.
void AccountManager::CompleteLobbyLogin (const std::shared_ptr< objects::AccountLogin > & login, const std::shared_ptr< objects::ChannelLogin > & channelLogin = nullptr)
Complete the request to connect to a channel from the lobby.
If the server is configured for multiple channels, the request may have been relayed from the primary channel intead with the proper target channel and zone supplied.
Parameters
login Pointer to the AccountLogin request
channelLogin Optional parameter supplied by the primary channel when multiple channels are configured containing target login info
Definition at line 608 of file AccountManager.cpp.
References libcomp::String::Arg(), libcomp::Convert::ENCODING_UTF8, libcomp::PersistentObject::LoadObjectByUUID(), LobbyLogin(), mServer, PopChannelSwitch(), PushChannelSwitch(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS8(), and libcomp::Packet::WriteString16Little().
Referenced by HandleLobbyLogin().
bool AccountManager::DeleteCharacter (const std::shared_ptr< objects::Character > & character)
Delete a character requested from the lobby or otherwise marked for deletion by cleaning up all related character objects.
If the character is somehow still logged in, a disconnect request will be sent and the character will be marked for deletion for the next time this process runs.
Parameters
character Pointer to the character to delete
Returns
true if the delete was successful, false if the delete failed
Definition at line 1048 of file AccountManager.cpp.
References libcomp::String::Arg(), Cleanup(), libcomp::DatabaseChangeSet::Create(), and mServer.
Referenced by CleanupAccountWorldData().
bool AccountManager::EndWebGameSession (const libcomp::String & username, bool notifyLobby, bool notifyChannel)
Start any web-game session for the specified user and notify the other servers as needed.
Even if no currently active session exists, the other servers will be sent a remove request.
Parameters
username Username of the account the session belongs to
notifyLobby true if the lobby should be notified
notifyChannel true if the channel should be notified
Returns
true if the session existed and was removed, false if it did not
Definition at line 1361 of file AccountManager.cpp.
References libcomp::String::Arg(), GetUserLogin(), mLock, mServer, mWebGameSessions, libcomp::String::ToLower(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteString16Little(), and libcomp::Packet::WriteU8().
bool AccountManager::ExpireSession (const libcomp::String & username, uint32_t key)
Expire the user session and log out the account.
If the session key is not matched or the account has completed its channel login (CHANNEL state) this is ignored.
Parameters
username Username for account to check.
key Session key that has expired.
Returns
true if the session was expired, false if it was not
Definition at line 461 of file AccountManager.cpp.
References libcomp::String::Arg(), LogoutUser(), mAccountMap, mLock, mServer, and libcomp::String::ToLower().
std::shared_ptr< objects::WebGameSession > AccountManager::GetGameSession (const libcomp::String & username)
Get the current web-game session for the specified user.
Parameters
username Username of the account the session belongs to
Returns
Pointer to the game session, null if none exists
Definition at line 1350 of file AccountManager.cpp.
References mLock, mWebGameSessions, and libcomp::String::ToLower().
std::shared_ptr< objects::AccountLogin > AccountManager::GetUserLogin (const libcomp::String & username)
Get the current user login state independent of world.
Parameters
username Username for the account to login.
Returns
Pointer to the login state; null if it does not exist.
Definition at line 392 of file AccountManager.cpp.
References mAccountMap, mLock, and libcomp::String::ToLower().
Referenced by EndWebGameSession(), and HandleChannelLogin().
void AccountManager::HandleChannelLogin (const std::shared_ptr< libcomp::InternalConnection > & requestConnection, uint32_t sessionKey, const libcomp::String & username)
Handle a request to complete a channel login.
Parameters
requestConnection Pointer to the channel connection where the request came from
sessionKey Session key supplied to the channel from the client used for login validation
username Username of the account logging in
Definition at line 790 of file AccountManager.cpp.
References libcomp::String::Arg(), ChannelLogin(), libcomp::Convert::ENCODING_UTF8, GetUserLogin(), libcomp::String::Length(), mServer, PopChannelSwitch(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS8(), libcomp::Packet::WriteString16Little(), and libcomp::Packet::WriteU8().
void AccountManager::HandleLobbyLogin (const std::shared_ptr< objects::AccountLogin > & login)
Handle a request to connect to a channel from the lobby.
Parameters
login Pointer to the AccountLogin request
Definition at line 539 of file AccountManager.cpp.
References libcomp::String::Arg(), CompleteLobbyLogin(), libcomp::Convert::ENCODING_UTF8, mServer, libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS8(), and libcomp::Packet::WriteString16Little().
bool AccountManager::IsLoggedIn (const libcomp::String & username, int8_t & channel)
Check if a user is logged in.
Parameters
username Username for the account to check.
channel Channel the user is logged into or -1 if they are in the lobby server.
Returns
true if the user is logged in; false otherwise.
Definition at line 74 of file AccountManager.cpp.
References mAccountMap, mLock, and libcomp::String::ToLower().
bool AccountManager::LobbyLogin (std::shared_ptr< objects::AccountLogin > login)
Register the supplied login with the world if it has not been already.
Parameters
login Login information associated to the account.
Returns
true if the user was logged in; false if the user is already logged in.
Definition at line 94 of file AccountManager.cpp.
References libcomp::String::Arg(), mAccountMap, mLock, RNG, and libcomp::String::ToLower().
Referenced by CompleteLobbyLogin().
std::shared_ptr< objects::AccountLogin > AccountManager::LogoutUser (const libcomp::String & username, int8_t channel = -1)
Mark the user logged out of the given channel.
Parameters
username Username for the account to log out.
channel Channel the user is logged into or -1 if they are in the lobby server.
Returns
Pointer to the AccountLogin representing the logged out user, nullptr if they were not registered.
Definition at line 402 of file AccountManager.cpp.
References libcomp::String::Arg(), Cleanup(), mAccountMap, mLock, mServer, mWebGameSessions, libcomp::String::ToLower(), libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteString16Little().
Referenced by ExpireSession().
std::list< std::shared_ptr< objects::AccountLogin > > AccountManager::LogoutUsersOnChannel (int8_t channel)
Log out all users on a given channel.
This should only be called when a channel disconnects.
Parameters
channel Channel to log out all users from.
Returns
List of AccountLogins representing the logged out users.
Definition at line 509 of file AccountManager.cpp.
References Cleanup(), mAccountMap, and mLock.
std::shared_ptr< objects::ChannelLogin > AccountManager::PopChannelSwitch (const libcomp::String & username)
"Pop" any existing channel switch signifier from the manager for the specified account and return it
Parameters
username Username of the account set to switch channels
Returns
Pointer to the channel switch definition
Definition at line 951 of file AccountManager.cpp.
References mChannelSwitches, mLock, and libcomp::String::ToLower().
Referenced by CompleteLobbyLogin(), and HandleChannelLogin().
void AccountManager::PushChannelSwitch (const libcomp::String & username, const std::shared_ptr< objects::ChannelLogin > & switchDef) private
"Push" a channel switch signifier to the manager for the specified account.
The next logout request will pop this value and await a reconnect to the specified channel rather than log the account out.
Parameters
username Username of the account that will switch channels
switchDef Definition of the connection that will be moved to
Definition at line 928 of file AccountManager.cpp.
References mChannelSwitches, and libcomp::String::ToLower().
Referenced by CompleteLobbyLogin(), and SwitchChannel().
bool AccountManager::StartWebGameSession (const std::shared_ptr< objects::WebGameSession > & gameSession)
Start a web-game session for the specified user who is currently playing that remains valid until a remove request is received or the account leaves the channel.
Once it is created, the lobby will be notified. The channel will be notified after the lobby returns a success message.
Parameters
gameSession Pointer to the session's definition
Returns
true if the session was started successfully, false if it was not
Definition at line 1291 of file AccountManager.cpp.
References libcomp::String::Arg(), libcomp::Crypto::GenerateRandom(), mAccountMap, mLock, mServer, mWebGameSessions, libcomp::String::ToLower(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteString16Little(), and libcomp::Packet::WriteU8().
bool AccountManager::SwitchChannel (std::shared_ptr< objects::AccountLogin > login, const std::shared_ptr< objects::ChannelLogin > & switchDef)
Transition the login from CHANNEL to CHANNEL_TO_CHANNEL and schedule a timeout.
Parameters
login Login information associated to the account.
switchDef Definition of the connection that will be moved to
Returns
true if the update succeeded, false if it did not
Definition at line 332 of file AccountManager.cpp.
References libcomp::String::Arg(), mLock, mServer, PushChannelSwitch(), and UpdateSessionKey().
void AccountManager::UpdateSessionKey (std::shared_ptr< objects::AccountLogin > login) private
Update the session key of the supplied login.
The lobby must be notified of this update or the login information will become out of sync.
Parameters
login Pointer to the account login to update
Definition at line 923 of file AccountManager.cpp.
References RNG.
Referenced by SwitchChannel().
Member Data Documentation
std::unordered_map<libcomp::String, std::shared_ptr<objects::AccountLogin> > world::AccountManager::mAccountMap private
Map of account login information by username.
Definition at line 287 of file AccountManager.h.
Referenced by ExpireSession(), GetUserLogin(), IsLoggedIn(), LobbyLogin(), LogoutUser(), LogoutUsersOnChannel(), and StartWebGameSession().
std::unordered_map<libcomp::String, std::shared_ptr<objects::ChannelLogin> > world::AccountManager::mChannelSwitches private
Map of account usernames associated to accounts set to switch channel upon next disconnect from a channel.
Definition at line 292 of file AccountManager.h.
Referenced by ChannelSwitchPending(), PopChannelSwitch(), and PushChannelSwitch().
std::mutex world::AccountManager::mLock private
Server lock for shared resources.
Definition at line 300 of file AccountManager.h.
Referenced by ChannelLogin(), ChannelSwitchPending(), EndWebGameSession(), ExpireSession(), GetGameSession(), GetUserLogin(), IsLoggedIn(), LobbyLogin(), LogoutUser(), LogoutUsersOnChannel(), PopChannelSwitch(), StartWebGameSession(), and SwitchChannel().
std::weak_ptr<WorldServer> world::AccountManager::mServer private
Pointer back to theworld server this belongs to.
Definition at line 283 of file AccountManager.h.
Referenced by ChannelLogin(), CleanupAccountWorldData(), CompleteLobbyLogin(), DeleteCharacter(), EndWebGameSession(), ExpireSession(), HandleChannelLogin(), HandleLobbyLogin(), LogoutUser(), StartWebGameSession(), and SwitchChannel().
std::unordered_map<libcomp::String, std::shared_ptr< objects::WebGameSession> > world::AccountManager::mWebGameSessions private
Map of account usernames associated to accounts to web-game sessions either pending or active for a character currently playing.
Definition at line 297 of file AccountManager.h.
Referenced by EndWebGameSession(), GetGameSession(), LogoutUser(), and StartWebGameSession().
The documentation for this class was generated from the following files:
AccountManager.h
AccountManager.cpp