COMP_hack: world::WorldSyncManager Class Reference
world::WorldSyncManager Class Reference
World specific implementation of the DataSyncManager in charge of performing server side update operations.
#include <WorldSyncManager.h>
Public Member Functions
WorldSyncManager (const std::weak_ptr< WorldServer > &server)
Create a new WorldSyncManager.
virtual ~WorldSyncManager ()
Clean up the WorldSyncManager.
bool CleanUpCharacterLogin (int32_t worldCID, bool flushOutgoing=false)
Perform cleanup operations based upon a character logging off (or logging on) based upon world level data being synchronized.
template<class T >
void Expire (int32_t entryID, uint32_t expirationTime)
Expire the existing record with a matching entry ID and expiration time of the templated type.
std::shared_ptr
< objects::MatchEntry > GetMatchEntry (int32_t worldCID)
Get any existing match entry by world CID.
bool Initialize ()
Initialize the WorldSyncManager after the server has been initialized.
std::shared_ptr< libcomp::Object > New ()
std::shared_ptr
< objects::ChannelLogin > PopRelogin (int32_t worldCID)
Pop and return any valid instance relogin access.
bool PushRelogin (const std::shared_ptr< objects::ChannelLogin > &login, uint32_t instanceID)
Register relogin access to an instance a player should have access to if they log in again before a time-out period passes.
bool RegisterConnection (const std::shared_ptr< InternalConnection > &connection, std::set< std::string > types)
bool RemoveConnection (const std::shared_ptr< InternalConnection > &connection)
virtual bool RemoveRecord (const std::shared_ptr< libcomp::Object > &record, const libcomp::String &type)
virtual bool RemoveRecord (const std::shared_ptr< libcomp::Object > &record, const libcomp::String &type)
void StartPvPMatch (uint32_t time, uint8_t type)
Start (after rechecking) a new solo PvP match based upon the current entries in the queues of the specified type.
void StartTeamPvPMatch (uint32_t time, uint8_t type)
Start (after rechecking) a new team PvP match based upon the current entries in the queues of the specified type.
void SyncComplete (const libcomp::String &type, const std::list< std::pair< std::shared_ptr< libcomp::Object >, bool >> &objs, const libcomp::String &source)
template<class T >
void SyncComplete (const libcomp::String &type, const std::list< std::pair< std::shared_ptr< libcomp::Object >, bool >> &objs, const libcomp::String &source)
Server specific handler for an operation following explicit types of non-persistent records being synced.
void SyncExistingChannelRecords (const std::shared_ptr< libcomp::InternalConnection > &connection)
Send all existing sync records to the specified connection.
bool SyncIncoming (libcomp::ReadOnlyPacket &p, const libcomp::String &source="")
void SyncOutgoing ()
bool SyncRecordRemoval (const std::shared_ptr< libcomp::Object > &record, const libcomp::String &type)
bool SyncRecordUpdate (const std::shared_ptr< libcomp::Object > &record, const libcomp::String &type)
int8_t Update (const libcomp::String &type, const std::shared_ptr< libcomp::Object > &obj, bool isRemove, const libcomp::String &source)
template<class T >
int8_t Update (const libcomp::String &type, const std::shared_ptr< libcomp::Object > &obj, bool isRemove, const libcomp::String &source)
Server specific handler for explicit types of non-persistent records being updated.
virtual bool UpdateRecord (const std::shared_ptr< libcomp::Object > &record, const libcomp::String &type)
Protected Member Functions
void QueueOutgoing (const libcomp::String &type, const std::shared_ptr< InternalConnection > &connection, const std::set< std::shared_ptr< libcomp::Object >> &updates, const std::set< std::shared_ptr< libcomp::Object >> &removes)
void WriteOutgoingRecord (libcomp::Packet &p, bool isPersistent, const libcomp::String &type, const std::shared_ptr< libcomp::Object > &record)
Protected Attributes
std::mutex mLock
std::unordered_map
< std::string, std::shared_ptr
< ObjectConfig > > mRegisteredTypes
Static Protected Attributes
static const int8_t SYNC_FAILED
static const int8_t SYNC_HANDLED
static const int8_t SYNC_UPDATED
Private Member Functions
void AdjustSearchEntryCount (int32_t sourceCID, objects::SearchEntry::Type_t type, bool increment)
Update the number of search entries associated to a specific character for quick access operations later.
bool DeterminePvPMatch (uint8_t type, std::set< int32_t > updated={})
Determine if a solo PvP match of the specified type can be started and queue it to start if it is.
bool DetermineTeamPvPMatch (uint8_t type, std::set< int32_t > updated={})
Determine if a team PvP match of the specified type can be started and queue it to start if it is.
bool EndMatch (const std::shared_ptr< objects::PentalphaMatch > &match)
End the supplied PentalphaMatch by properly updating all participating players and closing out their match entries.
bool EndTournament (const std::shared_ptr< objects::UBTournament > &tournament)
End the supplied UBTournament by properly updating the rankings and send the results to the channels.
std::unordered_map< int32_t,
std::list< std::shared_ptr
< objects::MatchEntry > > > GetMatchEntryTeams (uint8_t type)
Get all match entries by their team ID (including no team).
bool PreparePvPMatch (std::shared_ptr< objects::PvPMatch > match)
Ready a supplied PvP match to send to the channels.
bool RecalculateTournamentRankings (const libobjgen::UUID &tournamentUID)
Recalculate all rankings for a spectific UBTournament.
bool RecalculateUBRankings ()
Recalculate all tournament independent UBResult rankings.
Private Attributes
std::unordered_map< uint8_t,
std::unordered_map< uint32_t,
std::shared_ptr
< objects::InstanceAccess > > > mInstanceAccess
Map of zone instance access records by channel ID then instance ID.
std::unordered_map< int32_t,
std::shared_ptr
< objects::MatchEntry > > mMatchEntries
Map of character CIDs to queued match entries.
uint32_t mNextMatchID
Next match ID to use for any matches prepared by the server.
std::shared_ptr
< objects::PentalphaMatch > mPentalphaMatch
Pointer to the currently active pentalpha match.
std::array< std::array
< std::shared_ptr
< objects::PvPMatch >, 2 >, 2 > mPvPPendingMatches
Pending PvP matches prepared by the primary channel with all necessary instance information and the correct channel set indexed by solo entries (0) or team (1) then PVP type.
std::array< std::array
< uint32_t, 2 >, 2 > mPvPReadyTimes
System timestamps for pending PvP ready times indexed by solo entries (0) or team (1) then PVP type.
std::unordered_map< int32_t,
std::pair< uint32_t,
std::shared_ptr
< objects::ChannelLogin > > > mRelogins
Map of world CIDs to ChannelLogin configurations associated to a zone instance ID which allows players to re-enter following an unexpected disconnect.
std::list< std::shared_ptr
< objects::SearchEntry > > mSearchEntries
List of all search entries registered with the server.
std::unordered_map< int32_t,
libcomp::EnumMap
< objects::SearchEntry::Type_t,
uint16_t > > mSearchEntryCounts
Map of character CIDs to registered search entry type counts used for quick access operations.
std::weak_ptr< WorldServer > mServer
Pointer to the channel server.
std::array< uint32_t, 3 > mUBRecalcMin
Lowest points required to cause a recalculation of the current top 10 UB total score, top total points and top all time points (in that index order)
std::shared_ptr
< objects::UBTournament > mUBTournament
Pointer to the currently active UB tournament.
Detailed Description
World specific implementation of the DataSyncManager in charge of performing server side update operations.
Definition at line 58 of file WorldSyncManager.h.
Constructor & Destructor Documentation
WorldSyncManager::WorldSyncManager (const std::weak_ptr< WorldServer > & server)
Create a new WorldSyncManager.
Parameters
server Pointer back to the channel server this belongs to.
Definition at line 64 of file WorldSyncManager.cpp.
References mPvPReadyTimes, and mUBRecalcMin.
Referenced by Initialize().
WorldSyncManager::~WorldSyncManager () virtual
Clean up the WorldSyncManager.
Definition at line 72 of file WorldSyncManager.cpp.
Member Function Documentation
void WorldSyncManager::AdjustSearchEntryCount (int32_t sourceCID, objects::SearchEntry::Type_t type, bool increment) private
Update the number of search entries associated to a specific character for quick access operations later.
This function is NOT thread safe and requires the caller to lock mutex access before calling.
Parameters
sourceCID CID of the character to update
type Type of search entry counts to update
increment true if the count should be increased, false if it should be decreased
Definition at line 1708 of file WorldSyncManager.cpp.
References mSearchEntryCounts.
bool WorldSyncManager::CleanUpCharacterLogin (int32_t worldCID, bool flushOutgoing = false)
Perform cleanup operations based upon a character logging off (or logging on) based upon world level data being synchronized.
Parameters
worldCID CID of the character logging off
flushOutgoing Optional parameter to send any updates done immediately
Returns
true if updates were performed during this operation
Definition at line 1295 of file WorldSyncManager.cpp.
References DeterminePvPMatch(), DetermineTeamPvPMatch(), mInstanceAccess, libcomp::DataSyncManager::mLock, mMatchEntries, mRelogins, mSearchEntries, mSearchEntryCounts, mServer, RemoveRecord(), libcomp::DataSyncManager::SyncOutgoing(), and libcomp::DataSyncManager::UpdateRecord().
bool WorldSyncManager::DeterminePvPMatch (uint8_t type, std::set< int32_t > updated = {}) private
Determine if a solo PvP match of the specified type can be started and queue it to start if it is.
This function is thread safe.
Parameters
type Type ID of the PvP match
updated Set of world CIDs that have just entered the queue to determine if the queue countdown needs to restart
Returns
true if the match can be started, false if it cannot
Definition at line 1744 of file WorldSyncManager.cpp.
References libcomp::String::Arg(), GetMatchEntryTeams(), libcomp::DataSyncManager::mLock, mPvPPendingMatches, mPvPReadyTimes, mServer, StartPvPMatch(), and libcomp::DataSyncManager::UpdateRecord().
Referenced by CleanUpCharacterLogin(), and StartPvPMatch().
bool WorldSyncManager::DetermineTeamPvPMatch (uint8_t type, std::set< int32_t > updated = {}) private
Determine if a team PvP match of the specified type can be started and queue it to start if it is.
This function is thread safe.
Parameters
type Type ID of the PvP match
updated Set of world CIDs that have just entered the queue to determine if the queue countdown needs to restart
Returns
true if the match can be started, false if it cannot
Definition at line 1830 of file WorldSyncManager.cpp.
References libcomp::String::Arg(), GetMatchEntryTeams(), libcomp::DataSyncManager::mLock, mPvPPendingMatches, mPvPReadyTimes, mServer, RemoveRecord(), StartTeamPvPMatch(), and libcomp::DataSyncManager::UpdateRecord().
Referenced by CleanUpCharacterLogin(), RemoveRecord(), and StartTeamPvPMatch().
bool WorldSyncManager::EndMatch (const std::shared_ptr< objects::PentalphaMatch > & match) private
End the supplied PentalphaMatch by properly updating all participating players and closing out their match entries.
Parameters
match Pointer to the PentalphaMatch to end
Returns
true if the match and all related entries were updated properly
Definition at line 1992 of file WorldSyncManager.cpp.
References libcomp::String::Arg(), mServer, RemoveRecord(), and libcomp::DataSyncManager::UpdateRecord().
Referenced by Initialize().
bool WorldSyncManager::EndTournament (const std::shared_ptr< objects::UBTournament > & tournament) private
End the supplied UBTournament by properly updating the rankings and send the results to the channels.
Parameters
tournament Pointer to the UBTournament to end
Returns
true if the tournament and all related entries were updated properly
Definition at line 2357 of file WorldSyncManager.cpp.
References libcomp::String::Arg(), mServer, RecalculateTournamentRankings(), RemoveRecord(), and libcomp::DataSyncManager::UpdateRecord().
Referenced by Initialize().
template<class T > void world::WorldSyncManager::Expire (int32_t entryID, uint32_t expirationTime)
Expire the existing record with a matching entry ID and expiration time of the templated type.
If either does not match, nothing will be expired.
Parameters
entryID Entry ID of the record
expirationTime Expiration time of the record
Referenced by world::WorldSyncManager::Update< objects::SearchEntry >().
std::shared_ptr< objects::MatchEntry > WorldSyncManager::GetMatchEntry (int32_t worldCID)
Get any existing match entry by world CID.
Parameters
worldCID World CID of the entry
Returns
Pointer to a match entry
Definition at line 1287 of file WorldSyncManager.cpp.
References libcomp::DataSyncManager::mLock, and mMatchEntries.
std::unordered_map< int32_t, std::list< std::shared_ptr< objects::MatchEntry > > > WorldSyncManager::GetMatchEntryTeams (uint8_t type) private
Get all match entries by their team ID (including no team).
This function is NOT thread safe and requires the caller to lock mutex access before calling.
Parameters
type Type ID of the PvP match
Returns
Map of team IDs to entries in that team
Definition at line 1975 of file WorldSyncManager.cpp.
References mMatchEntries.
Referenced by DeterminePvPMatch(), DetermineTeamPvPMatch(), StartPvPMatch(), and StartTeamPvPMatch().
bool WorldSyncManager::Initialize ()
Initialize the WorldSyncManager after the server has been initialized.
Returns
false if any errors were encountered and the server should be shut down.
Definition at line 76 of file WorldSyncManager.cpp.
References EndMatch(), EndTournament(), libcomp::PersistentObject::LoadAll(), mPentalphaMatch, libcomp::DataSyncManager::mRegisteredTypes, mServer, mUBTournament, RecalculateUBRankings(), libcomp::DataSyncManager::SyncOutgoing(), and WorldSyncManager().
std::shared_ptr< objects::ChannelLogin > WorldSyncManager::PopRelogin (int32_t worldCID)
Pop and return any valid instance relogin access.
If the stored access is not valid, it will just be removed.
Parameters
worldCID World CID to check access for
Returns
Pointer to an instance relogin configuration that allows the player to enter a still active instance
Definition at line 1227 of file WorldSyncManager.cpp.
References mInstanceAccess, libcomp::DataSyncManager::mLock, and mRelogins.
bool WorldSyncManager::PreparePvPMatch (std::shared_ptr< objects::PvPMatch > match) private
Ready a supplied PvP match to send to the channels.
This function is thread safe.
Parameters
match Pointer to an existing match that has not been started
Returns
true if the update succeeded, false if it did not
Definition at line 1952 of file WorldSyncManager.cpp.
References libcomp::DataSyncManager::mLock, and mNextMatchID.
Referenced by StartPvPMatch(), and StartTeamPvPMatch().
bool WorldSyncManager::PushRelogin (const std::shared_ptr< objects::ChannelLogin > & login, uint32_t instanceID)
Register relogin access to an instance a player should have access to if they log in again before a time-out period passes.
Parameters
login Pointer to the relogin access definition
instanceID Instance ID being given access
Returns
true if the access was set correctly, false if it was not
Definition at line 1258 of file WorldSyncManager.cpp.
References mInstanceAccess, libcomp::DataSyncManager::mLock, mRelogins, and libcomp::DataSyncManager::SyncRecordUpdate().
bool WorldSyncManager::RecalculateTournamentRankings (const libobjgen::UUID & tournamentUID) private
Recalculate all rankings for a spectific UBTournament.
This function is thread safe.
Parameters
tournamentUID UID of the tournament to recalculate
Returns
true if the rankings were updated, false if an error occurred
Definition at line 2166 of file WorldSyncManager.cpp.
References libcomp::String::Arg(), libcomp::DatabaseChangeSet::Create(), libcomp::DataSyncManager::mLock, mServer, mUBRecalcMin, and libcomp::DataSyncManager::UpdateRecord().
Referenced by EndTournament().
bool WorldSyncManager::RecalculateUBRankings () private
Recalculate all tournament independent UBResult rankings.
This function is thread safe.
Returns
true if the rankings were updated, false if an error occurred
Definition at line 2242 of file WorldSyncManager.cpp.
References libcomp::DatabaseChangeSet::Create(), libcomp::DataSyncManager::mLock, mServer, mUBRecalcMin, and libcomp::DataSyncManager::UpdateRecord().
Referenced by Initialize().
bool WorldSyncManager::RemoveRecord (const std::shared_ptr< libcomp::Object > & record, const libcomp::String & type) virtual
Definition at line 1165 of file WorldSyncManager.cpp.
References DetermineTeamPvPMatch(), libcomp::DataSyncManager::mLock, mMatchEntries, and mSearchEntries.
Referenced by CleanUpCharacterLogin(), DetermineTeamPvPMatch(), EndMatch(), EndTournament(), StartPvPMatch(), and StartTeamPvPMatch().
void WorldSyncManager::StartPvPMatch (uint32_t time, uint8_t type)
Start (after rechecking) a new solo PvP match based upon the current entries in the queues of the specified type.
Parameters
time Ready time that has been communicated as a countdown to each player in the queue. This helps in deciding if there are still enough players in the ready state to join the match.
type PvP match type to start
Definition at line 1463 of file WorldSyncManager.cpp.
References libcomp::String::Arg(), DeterminePvPMatch(), libcomp::Randomizer::GetEntry(), GetMatchEntryTeams(), libcomp::DataSyncManager::mLock, mPvPPendingMatches, mPvPReadyTimes, mServer, PreparePvPMatch(), RemoveRecord(), libcomp::DataSyncManager::SyncOutgoing(), and libcomp::DataSyncManager::SyncRecordUpdate().
Referenced by DeterminePvPMatch().
void WorldSyncManager::StartTeamPvPMatch (uint32_t time, uint8_t type)
Start (after rechecking) a new team PvP match based upon the current entries in the queues of the specified type.
Parameters
time Ready time that has been communicated as a countdown to each player in the queue. This helps in deciding if there are still enough players in the ready state to join the match.
type PvP match type to start
Definition at line 1582 of file WorldSyncManager.cpp.
References libcomp::String::Arg(), DetermineTeamPvPMatch(), GetMatchEntryTeams(), libcomp::DataSyncManager::mLock, mPvPPendingMatches, mPvPReadyTimes, mServer, PreparePvPMatch(), RemoveRecord(), libcomp::DataSyncManager::SyncOutgoing(), and libcomp::DataSyncManager::SyncRecordUpdate().
Referenced by DetermineTeamPvPMatch().
template<class T > void world::WorldSyncManager::SyncComplete (const libcomp::String & type, const std::list< std::pair< std::shared_ptr< libcomp::Object >, bool >> & objs, const libcomp::String & source)
Server specific handler for an operation following explicit types of non-persistent records being synced.
Parameters
type Type name of the object being updated
objs List of pointers to the records being updated and a flag indicating if the object was being removed
source Source server identifier
void WorldSyncManager::SyncExistingChannelRecords (const std::shared_ptr< libcomp::InternalConnection > & connection)
Send all existing sync records to the specified connection.
Parameters
connection Pointer to the connection
Definition at line 1396 of file WorldSyncManager.cpp.
References libcomp::String::Arg(), mInstanceAccess, libcomp::DataSyncManager::mLock, mMatchEntries, mPentalphaMatch, mSearchEntries, mServer, mUBTournament, and libcomp::DataSyncManager::QueueOutgoing().
Referenced by world::WorldServer::RegisterChannel().
template<class T > int8_t world::WorldSyncManager::Update (const libcomp::String & type, const std::shared_ptr< libcomp::Object > & obj, bool isRemove, const libcomp::String & source)
Server specific handler for explicit types of non-persistent records being updated.
Parameters
type Type name of the object being updated
obj Pointer to the record definition
isRemove true if the record is being removed, false if it is either an insert or an update
source Source server identifier
Returns
Response codes matching the internal DataSyncManager set
Member Data Documentation
std::unordered_map<uint8_t, std::unordered_map<uint32_t, std::shared_ptr<objects::InstanceAccess> > > world::WorldSyncManager::mInstanceAccess private
Map of zone instance access records by channel ID then instance ID.
Records are only stored here after they have an instance ID.
Definition at line 275 of file WorldSyncManager.h.
Referenced by CleanUpCharacterLogin(), PopRelogin(), PushRelogin(), and SyncExistingChannelRecords().
std::unordered_map<int32_t, std::shared_ptr<objects::MatchEntry> > world::WorldSyncManager::mMatchEntries private
Map of character CIDs to queued match entries.
Definition at line 285 of file WorldSyncManager.h.
Referenced by CleanUpCharacterLogin(), GetMatchEntry(), GetMatchEntryTeams(), RemoveRecord(), and SyncExistingChannelRecords().
uint32_t world::WorldSyncManager::mNextMatchID private
Next match ID to use for any matches prepared by the server.
Definition at line 309 of file WorldSyncManager.h.
Referenced by PreparePvPMatch().
std::shared_ptr<objects::PentalphaMatch> world::WorldSyncManager::mPentalphaMatch private
Pointer to the currently active pentalpha match.
Definition at line 288 of file WorldSyncManager.h.
Referenced by Initialize(), and SyncExistingChannelRecords().
std::array<std::array< std::shared_ptr<objects::PvPMatch>, 2>, 2> world::WorldSyncManager::mPvPPendingMatches private
Pending PvP matches prepared by the primary channel with all necessary instance information and the correct channel set indexed by solo entries (0) or team (1) then PVP type.
Definition at line 301 of file WorldSyncManager.h.
Referenced by DeterminePvPMatch(), DetermineTeamPvPMatch(), StartPvPMatch(), and StartTeamPvPMatch().
std::array<std::array<uint32_t, 2>, 2> world::WorldSyncManager::mPvPReadyTimes private
System timestamps for pending PvP ready times indexed by solo entries (0) or team (1) then PVP type.
Definition at line 295 of file WorldSyncManager.h.
Referenced by DeterminePvPMatch(), DetermineTeamPvPMatch(), StartPvPMatch(), StartTeamPvPMatch(), and WorldSyncManager().
std::unordered_map<int32_t, std::pair<uint32_t, std::shared_ptr<objects::ChannelLogin> > > world::WorldSyncManager::mRelogins private
Map of world CIDs to ChannelLogin configurations associated to a zone instance ID which allows players to re-enter following an unexpected disconnect.
Definition at line 281 of file WorldSyncManager.h.
Referenced by CleanUpCharacterLogin(), PopRelogin(), and PushRelogin().
std::list<std::shared_ptr<objects::SearchEntry> > world::WorldSyncManager::mSearchEntries private
List of all search entries registered with the server.
Definition at line 265 of file WorldSyncManager.h.
Referenced by CleanUpCharacterLogin(), RemoveRecord(), and SyncExistingChannelRecords().
std::unordered_map<int32_t, libcomp::EnumMap< objects::SearchEntry::Type_t, uint16_t> > world::WorldSyncManager::mSearchEntryCounts private
Map of character CIDs to registered search entry type counts used for quick access operations.
Definition at line 270 of file WorldSyncManager.h.
Referenced by AdjustSearchEntryCount(), and CleanUpCharacterLogin().
std::weak_ptr<WorldServer> world::WorldSyncManager::mServer private
Pointer to the channel server.
Definition at line 312 of file WorldSyncManager.h.
Referenced by CleanUpCharacterLogin(), DeterminePvPMatch(), DetermineTeamPvPMatch(), EndMatch(), EndTournament(), Initialize(), RecalculateTournamentRankings(), RecalculateUBRankings(), StartPvPMatch(), StartTeamPvPMatch(), and SyncExistingChannelRecords().
std::array<uint32_t, 3> world::WorldSyncManager::mUBRecalcMin private
Lowest points required to cause a recalculation of the current top 10 UB total score, top total points and top all time points (in that index order)
Definition at line 306 of file WorldSyncManager.h.
Referenced by RecalculateTournamentRankings(), RecalculateUBRankings(), and WorldSyncManager().
std::shared_ptr<objects::UBTournament> world::WorldSyncManager::mUBTournament private
Pointer to the currently active UB tournament.
Definition at line 291 of file WorldSyncManager.h.
Referenced by Initialize(), and SyncExistingChannelRecords().
The documentation for this class was generated from the following files:
WorldSyncManager.h
WorldSyncManager.cpp