COMP_hack: world::CharacterManager Class Reference
world::CharacterManager Class Reference
Manages world level character actions.
#include <CharacterManager.h>
Public Member Functions
CharacterManager (const std::weak_ptr< WorldServer > &server)
Create a new CharacterManager.
bool AddToParty (std::shared_ptr< objects::PartyCharacter > member, uint32_t partyID)
Add a party member to the specified party.
int32_t AddToTeam (int32_t worldCID, int32_t teamID)
Add a character to the specified team.
void ClanDisband (int32_t clanID, int32_t sourceCID=0, std::shared_ptr< libcomp::TcpConnection > requestConnection=nullptr)
Disband an existing clan.
bool ClanJoin (std::shared_ptr< objects::CharacterLogin > cLogin, int32_t clanID)
Add the specified character to an existing clan.
void ClanKick (std::shared_ptr< objects::CharacterLogin > cLogin, int32_t clanID, int32_t targetCID, std::shared_ptr< libcomp::TcpConnection > requestConnection)
Kick a character from a clan.
bool ClanLeave (std::shared_ptr< objects::CharacterLogin > cLogin, int32_t clanID, std::shared_ptr< libcomp::TcpConnection > requestConnection)
Remove the specified character from an existing clan.
void ConvertToTargetCIDPacket (libcomp::Packet &p, uint32_t cidOffset, size_t cidCount)
Insert space in a packet for a count denoted list of world CID targets and seek to the position of the first CID in the list.
std::list< std::shared_ptr
< objects::CharacterLogin > > GetActiveCharacters ()
Retrieve all currently active CharacterLogins.
std::shared_ptr
< objects::CharacterLogin > GetCharacterLogin (const libobjgen::UUID &uuid)
Retrieve a CharacterLogin registered with the server by UUID.
std::shared_ptr
< objects::CharacterLogin > GetCharacterLogin (int32_t worldCID)
Retrieve a CharacterLogin registered with the server by world CID.
std::shared_ptr
< objects::CharacterLogin > GetCharacterLogin (const libcomp::String &characterName)
Retrieve a CharacterLogin registered with the server by name.
std::shared_ptr
< objects::ClanInfo > GetClan (int32_t clanID)
Get the clan info associated to the specified clan ID.
std::shared_ptr
< objects::ClanInfo > GetClan (const libobjgen::UUID &uuid)
Get (and register if needed) the clan info associated to the specified clan UUID.
std::shared_ptr< objects::Party > GetParty (uint32_t partyID)
Get an active party by ID.
std::shared_ptr
< objects::PartyCharacter > GetPartyMember (int32_t worldCID)
Get an active or pending party member by CharacterLogin.
std::list< std::shared_ptr
< objects::CharacterLogin > > GetRelatedCharacterLogins (std::shared_ptr< objects::CharacterLogin > cLogin, uint8_t relatedTypes)
Retrieves characters related to the supplied CharacterLogin.
bool GetStatusPacket (libcomp::Packet &p, const std::shared_ptr< objects::CharacterLogin > &cLogin, uint8_t &updateFlags)
Builds a status packet associated to the supplied CharacterLogin to be sent to related characters.
std::shared_ptr< objects::Team > GetTeam (int32_t teamID)
Get an active team by ID.
size_t GetTeamMaxSize (int8_t category) const
Get the maximum team size for a specific team category.
void PartyDisband (uint32_t partyID, int32_t sourceCID=0, std::shared_ptr< libcomp::TcpConnection > requestConnection=nullptr)
Attempt to disband the specified party.
bool PartyJoin (std::shared_ptr< objects::PartyCharacter > member, const libcomp::String targetName, uint32_t partyID, std::shared_ptr< libcomp::TcpConnection > sourceConnection)
Attempt to have a party member join the specified party.
void PartyKick (std::shared_ptr< objects::CharacterLogin > cLogin, int32_t targetCID)
Attempt to kick a player from their current party.
void PartyLeaderUpdate (uint32_t partyID, int32_t sourceCID, std::shared_ptr< libcomp::TcpConnection > requestConnection, int32_t targetCID)
Attempt to set the leader of the specified party.
void PartyLeave (std::shared_ptr< objects::CharacterLogin > cLogin, std::shared_ptr< libcomp::TcpConnection > requestConnection)
Attempt to have a party member leave their current party.
bool PartyRecruit (std::shared_ptr< objects::PartyCharacter > member, const libcomp::String targetName, uint32_t partyID, std::shared_ptr< libcomp::TcpConnection > sourceConnection)
Attempt to have a party member join the specified party via a recruit request (which is the inverse of a join request)
void RecalculateClanLevel (int32_t clanID, bool sendUpdate=true)
Recalculate a clan's level based on a summation of each member's login points.
std::shared_ptr
< objects::CharacterLogin > RegisterCharacter (std::shared_ptr< objects::CharacterLogin > cLogin)
Register a CharacterLogin with the manager.
bool RequestChannelDisconnect (int32_t worldCID)
Match the supplied world CID with a registered character login and send a request to the channel they are currently logged into to disconnect that account.
void SendClanDetails (std::shared_ptr< objects::CharacterLogin > cLogin, std::shared_ptr< libcomp::TcpConnection > requestConnection, std::list< int32_t > memberIDs={})
Send clan level or clan member level details to the specified character.
void SendClanInfo (int32_t clanID, uint8_t updateFlags=0x07, const std::list< int32_t > &cids={})
Send clan information to specific members or all members to update channel side.
void SendClanMemberInfo (std::shared_ptr< objects::CharacterLogin > cLogin, uint8_t updateFlags=0x30)
Send clan member updates about the specified player character.
void SendPartyInfo (uint32_t partyID, const std::list< int32_t > &cids={})
Send base level info about the specified party ID to every member to act as a refresh for channel level drop rule and member info.
void SendPartyMember (std::shared_ptr< objects::PartyCharacter > member, uint32_t partyID, bool newParty, bool isRefresh, std::shared_ptr< libcomp::TcpConnection > sourceConnection)
Send party member information to the current players in the party.
void SendStatusToRelatedCharacters (const std::list< std::shared_ptr< objects::CharacterLogin >> &cLogins, uint8_t updateFlags, bool zoneRestrict=false)
Send packets containing CharacterLogin information about the supplied logins contextual to other related characters.
void SendTeamInfo (int32_t teamID, const std::list< int32_t > &cids={})
Send base level info about the specified team ID to every member to act as a refresh for any team info.
bool SendToCharacters (libcomp::Packet &p, const std::list< std::shared_ptr< objects::CharacterLogin >> &cLogins, uint32_t cidOffset)
Send a packet to the specified logins.
bool SendToRelatedCharacters (libcomp::Packet &p, int32_t worldCID, uint32_t cidOffset, uint8_t relatedTypes, bool includeSelf=false, bool zoneRestrict=false)
Send a packet to various characters related to the supplied world CID.
void TeamDisband (int32_t teamID, int32_t sourceCID=0, bool toDiaspora=false)
Attempt to disband the specified team.
bool TeamJoin (int32_t worldCID, int32_t teamID, std::shared_ptr< libcomp::TcpConnection > sourceConnection)
Attempt to have a character join the specified team.
void TeamKick (std::shared_ptr< objects::CharacterLogin > cLogin, int32_t targetCID, int32_t teamID)
Attempt to kick a player from a team.
void TeamLeaderUpdate (int32_t teamID, int32_t sourceCID, std::shared_ptr< libcomp::TcpConnection > requestConnection, int32_t targetCID)
Attempt to set the leader of the specified team.
void TeamLeave (std::shared_ptr< objects::CharacterLogin > cLogin)
Attempt to have a character leave their current team.
bool TeamZiotiteUpdate (int32_t teamID, const std::shared_ptr< objects::CharacterLogin > &source=nullptr, int32_t sZiotite=0, int8_t lZiotite=0)
Update the small and large ziotite values and refresh the related channels.
bool UnregisterCharacter (std::shared_ptr< objects::CharacterLogin > cLogin)
Unregister a CharacterLogin with the manager.
Private Member Functions
uint32_t CreateParty (std::shared_ptr< objects::PartyCharacter > member)
Create a new party and set the supplied member as the leader.
bool RemoveFromClan (std::shared_ptr< objects::CharacterLogin > cLogin, int32_t clanID)
Remove the supplied CharacterLogin from the specified clan.
bool RemoveFromParty (std::shared_ptr< objects::CharacterLogin > cLogin, uint32_t partyID)
Remove the supplied CharacterLogin from their current party.
bool RemoveFromTeam (std::shared_ptr< objects::CharacterLogin > cLogin, int32_t teamID)
Remove the supplied CharacterLogin from their current team.
Private Attributes
std::unordered_map< int32_t,
std::shared_ptr
< objects::CharacterLogin > > mCharacterCIDMap
Map of character login information by world CID.
std::unordered_map
< libcomp::String,
std::shared_ptr
< objects::CharacterLogin > > mCharacterMap
Map of character login information by UUID.
std::unordered_map
< libcomp::String, int32_t > mClanMap
Map of clan UUIDs to clan ID assigned when loaded on the server.
std::unordered_map< int32_t,
std::shared_ptr
< objects::ClanInfo > > mClans
Map of clan IDs to clans loaded on the server.
std::mutex mLock
Server lock for shared resources.
int32_t mMaxCID
Highest CID registered for a logged in character.
int32_t mMaxClanID
Highest clan ID registered with the server.
uint32_t mMaxPartyID
Highest party ID registered with the server.
int32_t mMaxTeamID
Highest team ID registered with the server.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::Party > > mParties
Map of party IDs to parties registered with the server.
std::unordered_map< int32_t,
std::shared_ptr
< objects::PartyCharacter > > mPartyCharacters
Map of party characters by world CID.
std::weak_ptr< WorldServer > mServer
Pointer back to theworld server this belongs to.
std::unordered_map< int32_t,
std::shared_ptr< objects::Team > > mTeams
Detailed Description
Manages world level character actions.
Definition at line 67 of file CharacterManager.h.
Constructor & Destructor Documentation
CharacterManager::CharacterManager (const std::weak_ptr< WorldServer > & server)
Create a new CharacterManager.
Parameters
server Pointer back to the world server this belongs to
Definition at line 48 of file CharacterManager.cpp.
References mMaxCID, mMaxClanID, mMaxPartyID, mMaxTeamID, and mParties.
Member Function Documentation
bool CharacterManager::AddToParty (std::shared_ptr< objects::PartyCharacter > member, uint32_t partyID)
Add a party member to the specified party.
Parameters
member Pointer to the party member to add
partyID ID of the party to add the member to
Returns
true on success, false on failure
Definition at line 484 of file CharacterManager.cpp.
References libcomp::String::Arg(), GetCharacterLogin(), mLock, mParties, mPartyCharacters, and TeamLeave().
Referenced by PartyJoin(), and PartyRecruit().
int32_t CharacterManager::AddToTeam (int32_t worldCID, int32_t teamID)
Add a character to the specified team.
Parameters
worldCID World CID of the character to add
teamID ID of the team to add the character to
Returns
ID of the team the character was added to
Definition at line 1657 of file CharacterManager.cpp.
References libcomp::String::Arg(), GetCharacterLogin(), GetTeam(), GetTeamMaxSize(), mLock, mMaxTeamID, and mTeams.
Referenced by TeamJoin().
void CharacterManager::ClanDisband (int32_t clanID, int32_t sourceCID = 0, std::shared_ptr< libcomp::TcpConnection > requestConnection = nullptr)
Disband an existing clan.
Parameters
clanID Clan instance ID
sourceCID World CID of the character requesting the disband. This is only checked when the requestConnection is specified as well
requestConnection Pointer to the connection requesting the change
Definition at line 1163 of file CharacterManager.cpp.
References libcomp::String::Arg(), libcomp::DatabaseChangeSet::Create(), GetCharacterLogin(), GetClan(), world::WorldServer::GetRelayPacket(), libcomp::PersistentObject::LoadObjectByUUID(), mClanMap, mClans, mLock, mServer, SendClanInfo(), SendToCharacters(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteS8().
bool CharacterManager::ClanJoin (std::shared_ptr< objects::CharacterLogin > cLogin, int32_t clanID)
Add the specified character to an existing clan.
Parameters
cLogin Pointer to the CharacterLogin to add to the clan
clanID Clan instance ID
Returns
true if the character joined successfully, false if they did not
Definition at line 993 of file CharacterManager.cpp.
References libcomp::String::Arg(), libcomp::DatabaseChangeSet::Create(), GetClan(), world::WorldServer::GetRelayPacket(), libcomp::PersistentObject::LoadObjectByUUID(), mLock, mServer, RecalculateClanLevel(), RELATED_CLAN, SendClanInfo(), SendClanMemberInfo(), and SendToRelatedCharacters().
void CharacterManager::ClanKick (std::shared_ptr< objects::CharacterLogin > cLogin, int32_t clanID, int32_t targetCID, std::shared_ptr< libcomp::TcpConnection > requestConnection)
Kick a character from a clan.
Parameters
cLogin Pointer to the CharacterLogin requesting the change
clanID Clan instance ID
targetCID World CID of the character to kick
requestConnection Pointer to the connection requesting the change
Definition at line 1266 of file CharacterManager.cpp.
References libcomp::String::Arg(), GetCharacterLogin(), GetRelatedCharacterLogins(), world::WorldServer::GetRelayPacket(), RELATED_CLAN, RemoveFromClan(), SendClanInfo(), SendToCharacters(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteS8().
bool CharacterManager::ClanLeave (std::shared_ptr< objects::CharacterLogin > cLogin, int32_t clanID, std::shared_ptr< libcomp::TcpConnection > requestConnection)
Remove the specified character from an existing clan.
Parameters
cLogin Pointer to the CharacterLogin to remove from the clan
clanID Clan instance ID
requestConnection Pointer to the connection requesting the change
Returns
true if the character was successfully removed, false if they were not
Definition at line 1085 of file CharacterManager.cpp.
References libcomp::Packet::Clear(), GetCharacterLogin(), GetClan(), GetRelatedCharacterLogins(), world::WorldServer::GetRelayPacket(), mServer, RecalculateClanLevel(), RELATED_CLAN, RemoveFromClan(), SendClanInfo(), SendToCharacters(), SendToRelatedCharacters(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteS8().
void CharacterManager::ConvertToTargetCIDPacket (libcomp::Packet & p, uint32_t cidOffset, size_t cidCount)
Insert space in a packet for a count denoted list of world CID targets and seek to the position of the first CID in the list.
Parameters
p Packet to convert
cidOffset Position in bytes after the packet code where the list of CIDs should be inserted
cidCount Number of CIDs that space needs to be allocated for
Definition at line 228 of file CharacterManager.cpp.
References libcomp::Packet::Left(), libcomp::Packet::ReadArray(), libcomp::Packet::Seek(), libcomp::Packet::WriteArray(), libcomp::Packet::WriteBlank(), and libcomp::Packet::WriteU16Little().
Referenced by SendPartyMember(), and SendToCharacters().
uint32_t CharacterManager::CreateParty (std::shared_ptr< objects::PartyCharacter > member) private
Create a new party and set the supplied member as the leader.
Parameters
member Party member to designate as the leader of a new party
Returns
The ID of a the new party, 0 upon failure
Definition at line 2160 of file CharacterManager.cpp.
References libcomp::String::Arg(), GetCharacterLogin(), mLock, mMaxPartyID, mParties, mPartyCharacters, and TeamLeave().
Referenced by PartyJoin(), and PartyRecruit().
std::list< std::shared_ptr< objects::CharacterLogin > > CharacterManager::GetActiveCharacters ()
Retrieve all currently active CharacterLogins.
Returns
List of pointers to active CharacterLogins
Definition at line 147 of file CharacterManager.cpp.
References mCharacterCIDMap, and mLock.
std::shared_ptr< objects::CharacterLogin > CharacterManager::GetCharacterLogin (const libobjgen::UUID & uuid)
Retrieve a CharacterLogin registered with the server by UUID.
Parameters
uuid UUID associated to the character
Returns
Pointer to the CharacterLogin registered with the server
Definition at line 108 of file CharacterManager.cpp.
References mCharacterMap, mLock, and RegisterCharacter().
Referenced by AddToParty(), AddToTeam(), ClanDisband(), ClanKick(), ClanLeave(), CreateParty(), GetCharacterLogin(), GetClan(), GetRelatedCharacterLogins(), PartyDisband(), PartyJoin(), PartyKick(), PartyLeaderUpdate(), PartyRecruit(), RequestChannelDisconnect(), SendClanDetails(), SendClanInfo(), SendPartyInfo(), SendPartyMember(), SendTeamInfo(), SendToRelatedCharacters(), TeamDisband(), TeamJoin(), TeamKick(), TeamLeaderUpdate(), and TeamZiotiteUpdate().
std::shared_ptr< objects::CharacterLogin > CharacterManager::GetCharacterLogin (int32_t worldCID)
Retrieve a CharacterLogin registered with the server by world CID.
Parameters
worldCID World CID associated to the character
Returns
Pointer to the CharacterLogin registered with the server
Definition at line 129 of file CharacterManager.cpp.
References mCharacterCIDMap, and mLock.
std::shared_ptr< objects::CharacterLogin > CharacterManager::GetCharacterLogin (const libcomp::String & characterName)
Retrieve a CharacterLogin registered with the server by name.
Parameters
characterName Name of the character
Returns
Pointer to the CharacterLogin registered with the server
Definition at line 137 of file CharacterManager.cpp.
References GetCharacterLogin(), and mServer.
std::shared_ptr< objects::ClanInfo > CharacterManager::GetClan (int32_t clanID)
Get the clan info associated to the specified clan ID.
Parameters
clanID Clan instance ID
Pointer to the related clan info or null if it does not exist
Definition at line 922 of file CharacterManager.cpp.
References mClans, and mLock.
Referenced by ClanDisband(), ClanJoin(), ClanLeave(), GetClan(), GetRelatedCharacterLogins(), RecalculateClanLevel(), RemoveFromClan(), SendClanDetails(), SendClanInfo(), and SendClanMemberInfo().
std::shared_ptr< objects::ClanInfo > CharacterManager::GetClan (const libobjgen::UUID & uuid)
Get (and register if needed) the clan info associated to the specified clan UUID.
Parameters
uuid UUID of the clan to retrieve
Pointer to the related clan info
Definition at line 935 of file CharacterManager.cpp.
References GetCharacterLogin(), GetClan(), libcomp::PersistentObject::GetObjectByUUID(), mClanMap, mClans, mLock, mMaxClanID, and mServer.
std::shared_ptr< objects::Party > CharacterManager::GetParty (uint32_t partyID)
Get an active party by ID.
Parameters
partyID ID of the party to retrieve
Returns
Pointer to the active party
Definition at line 459 of file CharacterManager.cpp.
References mLock, and mParties.
Referenced by PartyDisband(), PartyKick(), PartyLeaderUpdate(), PartyLeave(), SendPartyInfo(), and SendPartyMember().
std::shared_ptr< objects::PartyCharacter > CharacterManager::GetPartyMember (int32_t worldCID)
Get an active or pending party member by CharacterLogin.
Parameters
worldCID World CID of the party member info to retrieve
Returns
Pointer to the party member
Definition at line 471 of file CharacterManager.cpp.
References mLock, and mPartyCharacters.
Referenced by GetStatusPacket(), PartyJoin(), PartyRecruit(), and SendPartyMember().
std::list< std::shared_ptr< objects::CharacterLogin > > CharacterManager::GetRelatedCharacterLogins (std::shared_ptr< objects::CharacterLogin > cLogin, uint8_t relatedTypes)
Retrieves characters related to the supplied CharacterLogin.
Parameters
cLogin CharacterLogin to find related characters for
relatedTypes Flags indicating what types of related characters to send the packet to. Use the constants in the CharacterManager header to signify these.
Returns
List of pointers to the related CharacterLogins
Definition at line 283 of file CharacterManager.cpp.
References libcomp::String::Arg(), GetCharacterLogin(), GetClan(), mLock, mParties, mServer, mTeams, RELATED_CLAN, RELATED_FRIENDS, RELATED_PARTY, and RELATED_TEAM.
Referenced by ClanKick(), ClanLeave(), PartyKick(), PartyLeave(), SendToRelatedCharacters(), TeamKick(), and TeamLeave().
bool CharacterManager::GetStatusPacket (libcomp::Packet & p, const std::shared_ptr< objects::CharacterLogin > & cLogin, uint8_t & updateFlags)
Builds a status packet associated to the supplied CharacterLogin to be sent to related characters.
Parameters
p Packet to write the data to
cLogin CharacterLogin to send information about
updateFlags CharacterLogin packet specific flags indicating what is being sent. Information will be filtered out in this function as needed.
Returns
true if data was written, false if no data applied
Definition at line 410 of file CharacterManager.cpp.
References GetPartyMember(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteU8().
Referenced by SendStatusToRelatedCharacters().
std::shared_ptr< objects::Team > CharacterManager::GetTeam (int32_t teamID)
Get an active team by ID.
Parameters
teamID ID of the team to retrieve
Returns
Pointer to the active team
Definition at line 1635 of file CharacterManager.cpp.
References mLock, and mTeams.
Referenced by AddToTeam(), SendTeamInfo(), TeamDisband(), TeamJoin(), TeamKick(), TeamLeaderUpdate(), TeamLeave(), and TeamZiotiteUpdate().
size_t CharacterManager::GetTeamMaxSize (int8_t category) const
Get the maximum team size for a specific team category.
Parameters
category Team category that groups together types
Returns
Maximum number of team members the team can have
Definition at line 1642 of file CharacterManager.cpp.
Referenced by AddToTeam().
void CharacterManager::PartyDisband (uint32_t partyID, int32_t sourceCID = 0, std::shared_ptr< libcomp::TcpConnection > requestConnection = nullptr)
Attempt to disband the specified party.
All necessary packet communication is handled within.
Parameters
partyID ID of the party to disband
sourceCID Optional ID of character who is disbanding the party
requestConnection Optional parameter for the connection that sent the request
Definition at line 724 of file CharacterManager.cpp.
References libcomp::String::Arg(), GetCharacterLogin(), GetParty(), world::WorldServer::GetRelayPacket(), mLock, mParties, RemoveFromParty(), SendPartyInfo(), SendToCharacters(), libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteU16Little().
Referenced by PartyKick(), and PartyLeave().
bool CharacterManager::PartyJoin (std::shared_ptr< objects::PartyCharacter > member, const libcomp::String targetName, uint32_t partyID, std::shared_ptr< libcomp::TcpConnection > sourceConnection)
Attempt to have a party member join the specified party.
Parameters
member Pointer to the party member that will join. All necessary packet communication is handled within.
targetName Name of a character that sent a join request, can be left blank if joining directly
partyID ID of the party to add the member to
sourceConnection Connection associated to the member joining the party
Returns
true on success, false on failure
Definition at line 525 of file CharacterManager.cpp.
References AddToParty(), CreateParty(), GetCharacterLogin(), GetPartyMember(), world::WorldServer::GetRelayPacket(), libcomp::String::IsEmpty(), mServer, SendPartyMember(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteString16Little(), libcomp::Packet::WriteU16Little(), and libcomp::Packet::WriteU32Little().
void CharacterManager::PartyKick (std::shared_ptr< objects::CharacterLogin > cLogin, int32_t targetCID)
Attempt to kick a player from their current party.
All necessary packet communication is handled within.
Parameters
cLogin CharacterLogin of the character who sent the request
targetCID CID of the character being kicked
Definition at line 849 of file CharacterManager.cpp.
References libcomp::String::Arg(), GetCharacterLogin(), GetParty(), GetRelatedCharacterLogins(), PartyDisband(), RELATED_PARTY, RemoveFromParty(), SendPartyInfo(), SendToCharacters(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteU8().
void CharacterManager::PartyLeaderUpdate (uint32_t partyID, int32_t sourceCID, std::shared_ptr< libcomp::TcpConnection > requestConnection, int32_t targetCID)
Attempt to set the leader of the specified party.
All necessary packet communication is handled within.
Parameters
partyID ID of the party to update
sourceCID Optional ID of character who is setting the leader
requestConnection Optional parameter for the connection that sent the request
targetCID CID of the new leader to set
Definition at line 802 of file CharacterManager.cpp.
References GetCharacterLogin(), GetParty(), world::WorldServer::GetRelayPacket(), SendPartyInfo(), SendToCharacters(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteU16Little(), and libcomp::Packet::WriteU8().
Referenced by PartyLeave().
void CharacterManager::PartyLeave (std::shared_ptr< objects::CharacterLogin > cLogin, std::shared_ptr< libcomp::TcpConnection > requestConnection)
Attempt to have a party member leave their current party.
All necessary packet communication is handled within.
Parameters
member Pointer to the CharacterLogin representation of the party member leaving
requestConnection Optional parameter for the connection that sent the request
Definition at line 661 of file CharacterManager.cpp.
References GetParty(), GetRelatedCharacterLogins(), world::WorldServer::GetRelayPacket(), PartyDisband(), PartyLeaderUpdate(), RELATED_PARTY, RemoveFromParty(), SendPartyInfo(), SendToCharacters(), libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteU16Little().
bool CharacterManager::PartyRecruit (std::shared_ptr< objects::PartyCharacter > member, const libcomp::String targetName, uint32_t partyID, std::shared_ptr< libcomp::TcpConnection > sourceConnection)
Attempt to have a party member join the specified party via a recruit request (which is the inverse of a join request)
Parameters
member Pointer to the party member that will join. All necessary packet communication is handled within.
targetName Name of a character that sent a recruit request
partyID ID of the party to add the member to
sourceConnection Connection associated to the member joining the party
Returns
true on success, false on failure
Definition at line 602 of file CharacterManager.cpp.
References AddToParty(), CreateParty(), ENCODING_CP932, GetCharacterLogin(), GetPartyMember(), world::WorldServer::GetRelayPacket(), libcomp::String::IsEmpty(), SendPartyMember(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteString16Little(), and libcomp::Packet::WriteU16Little().
void CharacterManager::RecalculateClanLevel (int32_t clanID, bool sendUpdate = true)
Recalculate a clan's level based on a summation of each member's login points.
Every 10,000 points grants a new level starting at 20,000 and ending at 100,000.
Parameters
clanID Clan instance ID
sendUpdate If true and the level is changed by the calculation, it is broadcast to each logged in clan member.
Definition at line 1313 of file CharacterManager.cpp.
References libcomp::String::Arg(), GetClan(), libcomp::PersistentObject::LoadObjectByUUID(), mServer, and SendClanInfo().
Referenced by ClanJoin(), and ClanLeave().
std::shared_ptr< objects::CharacterLogin > CharacterManager::RegisterCharacter (std::shared_ptr< objects::CharacterLogin > cLogin)
Register a CharacterLogin with the manager.
Characters registered here will remain until the server restarts unless they are deleted.
Parameters
cLogin CharacterLogin to register
Returns
Pointer to the CharacterLogin registered with the server. null is never returned and the value sent back should always replace the value passed in to keep the servers in sync
Definition at line 60 of file CharacterManager.cpp.
References mCharacterCIDMap, mCharacterMap, mLock, and mMaxCID.
Referenced by GetCharacterLogin().
bool CharacterManager::RemoveFromClan (std::shared_ptr< objects::CharacterLogin > cLogin, int32_t clanID) private
Remove the supplied CharacterLogin from the specified clan.
Parameters
cLogin CharacterLogin to remove
clanID Clan instance ID
Returns
true on success, false if they were not in specified clan
Definition at line 2305 of file CharacterManager.cpp.
References libcomp::String::Arg(), libcomp::DatabaseChangeSet::Create(), GetClan(), mLock, and mServer.
Referenced by ClanKick(), and ClanLeave().
bool CharacterManager::RemoveFromParty (std::shared_ptr< objects::CharacterLogin > cLogin, uint32_t partyID) private
Remove the supplied CharacterLogin from their current party.
Parameters
cLogin CharacterLogin to remove
partyID ID of the party to remove the member from
Returns
true on success, false if they were not in a party
Definition at line 2277 of file CharacterManager.cpp.
References libcomp::String::Arg(), mLock, mParties, and mPartyCharacters.
Referenced by PartyDisband(), PartyKick(), and PartyLeave().
bool CharacterManager::RemoveFromTeam (std::shared_ptr< objects::CharacterLogin > cLogin, int32_t teamID) private
Remove the supplied CharacterLogin from their current team.
Parameters
cLogin CharacterLogin to remove
teamID ID of the team to remove the member from
Returns
true on success, false if they were not in the team
Definition at line 2382 of file CharacterManager.cpp.
References libcomp::String::Arg(), mLock, mServer, and mTeams.
Referenced by TeamDisband(), TeamKick(), and TeamLeave().
bool CharacterManager::RequestChannelDisconnect (int32_t worldCID)
Match the supplied world CID with a registered character login and send a request to the channel they are currently logged into to disconnect that account.
Parameters
worldCID World CID associated to the character
Returns
true if the request was sent, false if either no channel exists or no channel is has the character
Definition at line 164 of file CharacterManager.cpp.
References GetCharacterLogin(), mServer, libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteU32Little().
void CharacterManager::SendClanDetails (std::shared_ptr< objects::CharacterLogin > cLogin, std::shared_ptr< libcomp::TcpConnection > requestConnection, std::list< int32_t > memberIDs = {})
Send clan level or clan member level details to the specified character.
Parameters
cLogin Pointer to the CharacterLogin requesting the information
requestConnection Pointer to the connection requesting the change
memberIDs Optional list of member world CIDs being requested. If this is left empty, the clan level information will be sent instead.
Todo:
: determine how we should actually receive emblem patterns
Definition at line 1387 of file CharacterManager.cpp.
References libcomp::Convert::ENCODING_CP932, GetCharacterLogin(), GetClan(), world::WorldServer::GetRelayPacket(), mServer, libcomp::Packet::WriteBlank(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS64Little(), libcomp::Packet::WriteS8(), libcomp::Packet::WriteString16Little(), libcomp::Packet::WriteU16Little(), and libcomp::Packet::WriteU8().
void CharacterManager::SendClanInfo (int32_t clanID, uint8_t updateFlags = 0x07, const std::list< int32_t > & cids = {})
Send clan information to specific members or all members to update channel side.
Parameters
clanID Clan instance ID
updateFlags Flags specifying what information to send. Available options are: 0x01: Clan name 0x02: Clan emblem 0x04: Clan level 0x08: Indicates that the clan instance ID has updated (ex: joined or left) Defaults to name, emblem, level
cids Specific CIDs to send to, sends to all if empty
Definition at line 1499 of file CharacterManager.cpp.
References GetCharacterLogin(), GetClan(), SendToCharacters(), libcomp::Packet::WriteBlank(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS8(), libcomp::Packet::WriteString16Little(), and libcomp::Packet::WriteU8().
Referenced by ClanDisband(), ClanJoin(), ClanKick(), ClanLeave(), and RecalculateClanLevel().
void CharacterManager::SendClanMemberInfo (std::shared_ptr< objects::CharacterLogin > cLogin, uint8_t updateFlags = 0x30)
Send clan member updates about the specified player character.
Parameters
cLogin Pointer to the CharacterLogin to describe
updateFlags Flags specifying what information to send. Available options are: 0x01: Member specified status 0x02: Member zone 0x04: Member channel 0x08: Member message 0x10: Member login points 0x20: Member level Defaults to login points and level as the rest are sent via CharacterManager::SendStatusToRelatedCharacters
Definition at line 1580 of file CharacterManager.cpp.
References GetClan(), world::WorldServer::GetRelayPacket(), mServer, RELATED_CLAN, SendToRelatedCharacters(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS8(), and libcomp::Packet::WriteString16Little().
Referenced by ClanJoin().
void CharacterManager::SendPartyInfo (uint32_t partyID, const std::list< int32_t > & cids = {})
Send base level info about the specified party ID to every member to act as a refresh for channel level drop rule and member info.
Parameters
partyID ID of the party to update
cids Additional CIDs to send to, useful when removing members
Definition at line 890 of file CharacterManager.cpp.
References GetCharacterLogin(), GetParty(), SendToCharacters(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteU32Little(), and libcomp::Packet::WriteU8().
Referenced by PartyDisband(), PartyKick(), PartyLeaderUpdate(), PartyLeave(), and SendPartyMember().
void CharacterManager::SendPartyMember (std::shared_ptr< objects::PartyCharacter > member, uint32_t partyID, bool newParty, bool isRefresh, std::shared_ptr< libcomp::TcpConnection > sourceConnection)
Send party member information to the current players in the party.
Parameters
member Pointer to the new party member
partyID ID of the party
newParty true if the party was just created, false if it already existed
sourceConnection Optional parameter for the connection that sent the request
Definition at line 2207 of file CharacterManager.cpp.
References libcomp::Packet::Clear(), ConvertToTargetCIDPacket(), GetCharacterLogin(), GetParty(), GetPartyMember(), world::WorldServer::GetRelayPacket(), RELATED_PARTY, SendPartyInfo(), SendToRelatedCharacters(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteU32Little(), and libcomp::Packet::WriteU8().
Referenced by PartyJoin(), and PartyRecruit().
void CharacterManager::SendStatusToRelatedCharacters (const std::list< std::shared_ptr< objects::CharacterLogin >> & cLogins, uint8_t updateFlags, bool zoneRestrict = false)
Send packets containing CharacterLogin information about the supplied logins contextual to other related characters.
Parameters
cLogins CharacterLogins to send information about
updateFlags CharacterLogin packet specific flags indicating what is being sent. Information will be filtered out in this function as needed. For example if party information is being sent but the character is not in a party, that specific character's part information will not be sent. If the filtering results in no flags, no data will be sent.
zoneRestrict Optional parameter to restrict the characters being notified to ones in the same zone as the supplied CID. Defaults to false.
Definition at line 382 of file CharacterManager.cpp.
References GetStatusPacket(), RELATED_CLAN, RELATED_FRIENDS, RELATED_PARTY, and SendToRelatedCharacters().
void CharacterManager::SendTeamInfo (int32_t teamID, const std::list< int32_t > & cids = {})
Send base level info about the specified team ID to every member to act as a refresh for any team info.
Parameters
teamID ID of the team to update
cids Additional CIDs to send to, useful when removing members
Definition at line 2128 of file CharacterManager.cpp.
References GetCharacterLogin(), GetTeam(), SendToCharacters(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteU8().
Referenced by TeamDisband(), TeamJoin(), TeamKick(), TeamLeaderUpdate(), and TeamLeave().
bool CharacterManager::SendToCharacters (libcomp::Packet & p, const std::list< std::shared_ptr< objects::CharacterLogin >> & cLogins, uint32_t cidOffset)
Send a packet to the specified logins.
Parameters
p Packet to send
cLogins CharacterLogins to map channel connections to when sending the packet
cidOffset Position in bytes after the packet code where the list of CIDs should be inserted. If the value is larger than the packet, it will be appended to the end.
Returns
false if an error occurs
Definition at line 188 of file CharacterManager.cpp.
References ConvertToTargetCIDPacket(), mServer, libcomp::Packet::Size(), and libcomp::Packet::WriteS32Little().
Referenced by ClanDisband(), ClanKick(), ClanLeave(), PartyDisband(), PartyKick(), PartyLeaderUpdate(), PartyLeave(), SendClanInfo(), SendPartyInfo(), SendTeamInfo(), SendToRelatedCharacters(), TeamDisband(), TeamKick(), TeamLeaderUpdate(), TeamLeave(), and TeamZiotiteUpdate().
bool CharacterManager::SendToRelatedCharacters (libcomp::Packet & p, int32_t worldCID, uint32_t cidOffset, uint8_t relatedTypes, bool includeSelf = false, bool zoneRestrict = false)
Send a packet to various characters related to the supplied world CID.
Parameters
p Packet to send
worldCID World CID used to find related characters
cidOffset Position in bytes after the packet code where the list of CIDs should be inserted. If the value is larger than the packet, it will be appended to the end.
relatedTypes Flags indicating what types of related characters to send the packet to. Use the constants in the CharacterManager header to signify these.
includeSelf Optional parameter to include the character associated to the world CID. Defaults to false.
zoneRestrict Optional parameter to restrict the characters being retrieved to ones in the same zone as the supplied CID. Defaults to false.
Returns
false if an error occurs
Definition at line 245 of file CharacterManager.cpp.
References libcomp::String::Arg(), GetCharacterLogin(), GetRelatedCharacterLogins(), mServer, and SendToCharacters().
Referenced by ClanJoin(), ClanLeave(), SendClanMemberInfo(), SendPartyMember(), SendStatusToRelatedCharacters(), and TeamJoin().
void CharacterManager::TeamDisband (int32_t teamID, int32_t sourceCID = 0, bool toDiaspora = false)
Attempt to disband the specified team.
All necessary packet communication is handled within.
Parameters
teamID ID of the team to disband
sourceCID Optional ID of character who is disbanding the team
toDiaspora If true the team is being converted into a Diaspora team and should be notified as part of this
Definition at line 1830 of file CharacterManager.cpp.
References libcomp::String::Arg(), GetCharacterLogin(), world::WorldServer::GetRelayPacket(), GetTeam(), mLock, mTeams, RemoveFromTeam(), SendTeamInfo(), SendToCharacters(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteS8().
Referenced by TeamLeave().
bool CharacterManager::TeamJoin (int32_t worldCID, int32_t teamID, std::shared_ptr< libcomp::TcpConnection > sourceConnection)
Attempt to have a character join the specified team.
Parameters
worldCID World CID of the character to add
teamID ID of the team to add the character to
sourceConnection Connection associated to the character joining the team
Returns
true on success, false on failure
Definition at line 1724 of file CharacterManager.cpp.
References AddToTeam(), libcomp::Packet::Clear(), GetCharacterLogin(), world::WorldServer::GetRelayPacket(), GetTeam(), RELATED_TEAM, SendTeamInfo(), SendToRelatedCharacters(), TeamZiotiteUpdate(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS8(), and libcomp::Packet::WriteString16Little().
void CharacterManager::TeamKick (std::shared_ptr< objects::CharacterLogin > cLogin, int32_t targetCID, int32_t teamID)
Attempt to kick a player from a team.
All necessary packet communication is handled within.
Parameters
cLogin CharacterLogin of the character who sent the request
targetCID CID of the character being kicked
teamID ID of the team to update
Definition at line 1974 of file CharacterManager.cpp.
References GetCharacterLogin(), GetRelatedCharacterLogins(), world::WorldServer::GetRelayPacket(), GetTeam(), RELATED_TEAM, RemoveFromTeam(), SendTeamInfo(), SendToCharacters(), TeamZiotiteUpdate(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteS8().
void CharacterManager::TeamLeaderUpdate (int32_t teamID, int32_t sourceCID, std::shared_ptr< libcomp::TcpConnection > requestConnection, int32_t targetCID)
Attempt to set the leader of the specified team.
All necessary packet communication is handled within.
Parameters
teamID ID of the team to update
sourceCID Optional ID of character who is setting the leader
requestConnection Optional parameter for the connection that sent the request
targetCID CID of the new leader to set
Definition at line 1907 of file CharacterManager.cpp.
References GetCharacterLogin(), world::WorldServer::GetRelayPacket(), GetTeam(), SendTeamInfo(), SendToCharacters(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteS8().
Referenced by TeamLeave().
void CharacterManager::TeamLeave (std::shared_ptr< objects::CharacterLogin > cLogin)
Attempt to have a character leave their current team.
All necessary packet communication is handled within.
Parameters
cLogin Pointer to the CharacterLogin representation of the character leaving
Definition at line 1773 of file CharacterManager.cpp.
References libcomp::Packet::Clear(), GetRelatedCharacterLogins(), world::WorldServer::GetRelayPacket(), GetTeam(), RELATED_TEAM, RemoveFromTeam(), SendTeamInfo(), SendToCharacters(), TeamDisband(), TeamLeaderUpdate(), TeamZiotiteUpdate(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteS8().
Referenced by AddToParty(), and CreateParty().
bool CharacterManager::TeamZiotiteUpdate (int32_t teamID, const std::shared_ptr< objects::CharacterLogin > & source = nullptr, int32_t sZiotite = 0, int8_t lZiotite = 0)
Update the small and large ziotite values and refresh the related channels.
If no values are supplied, the teams will just be refreshed.
Parameters
teamID ID of the team to update
source Pointer to the player performing the update
sZiotite Amount of small ziotite to add
lZiotite Amount of large ziotite to add
Returns
true if the update was valid, false if it was not
Definition at line 2044 of file CharacterManager.cpp.
References libcomp::String::Arg(), GetCharacterLogin(), GetTeam(), mLock, SendToCharacters(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS8(), and libcomp::Packet::WriteU8().
Referenced by TeamJoin(), TeamKick(), and TeamLeave().
bool CharacterManager::UnregisterCharacter (std::shared_ptr< objects::CharacterLogin > cLogin)
Unregister a CharacterLogin with the manager.
This should only be used if the character is being deleted.
Parameters
cLogin CharacterLogin to unregister
Returns
true if the character was removed, false if they were not registered
Definition at line 83 of file CharacterManager.cpp.
References mCharacterCIDMap, mCharacterMap, and mLock.
Member Data Documentation
std::unordered_map<int32_t, std::shared_ptr<objects::CharacterLogin> > world::CharacterManager::mCharacterCIDMap private
Map of character login information by world CID.
Definition at line 582 of file CharacterManager.h.
Referenced by GetActiveCharacters(), GetCharacterLogin(), RegisterCharacter(), and UnregisterCharacter().
std::unordered_map<libcomp::String, std::shared_ptr<objects::CharacterLogin> > world::CharacterManager::mCharacterMap private
Map of character login information by UUID.
Definition at line 578 of file CharacterManager.h.
Referenced by GetCharacterLogin(), RegisterCharacter(), and UnregisterCharacter().
std::unordered_map<libcomp::String, int32_t> world::CharacterManager::mClanMap private
Map of clan UUIDs to clan ID assigned when loaded on the server.
Definition at line 597 of file CharacterManager.h.
Referenced by ClanDisband(), and GetClan().
std::unordered_map<int32_t, std::shared_ptr<objects::ClanInfo> > world::CharacterManager::mClans private
Map of clan IDs to clans loaded on the server.
Definition at line 594 of file CharacterManager.h.
Referenced by ClanDisband(), and GetClan().
std::mutex world::CharacterManager::mLock private
Server lock for shared resources.
Definition at line 614 of file CharacterManager.h.
Referenced by AddToParty(), AddToTeam(), ClanDisband(), ClanJoin(), CreateParty(), GetActiveCharacters(), GetCharacterLogin(), GetClan(), GetParty(), GetPartyMember(), GetRelatedCharacterLogins(), GetTeam(), PartyDisband(), RegisterCharacter(), RemoveFromClan(), RemoveFromParty(), RemoveFromTeam(), TeamDisband(), TeamZiotiteUpdate(), and UnregisterCharacter().
int32_t world::CharacterManager::mMaxCID private
Highest CID registered for a logged in character.
Definition at line 602 of file CharacterManager.h.
Referenced by CharacterManager(), and RegisterCharacter().
int32_t world::CharacterManager::mMaxClanID private
Highest clan ID registered with the server.
Definition at line 608 of file CharacterManager.h.
Referenced by CharacterManager(), and GetClan().
uint32_t world::CharacterManager::mMaxPartyID private
Highest party ID registered with the server.
Definition at line 605 of file CharacterManager.h.
Referenced by CharacterManager(), and CreateParty().
int32_t world::CharacterManager::mMaxTeamID private
Highest team ID registered with the server.
Definition at line 611 of file CharacterManager.h.
Referenced by AddToTeam(), and CharacterManager().
std::unordered_map<uint32_t, std::shared_ptr<objects::Party> > world::CharacterManager::mParties private
Map of party IDs to parties registered with the server.
The party ID 0 is used for characters awaiting a join request response
Definition at line 587 of file CharacterManager.h.
Referenced by AddToParty(), CharacterManager(), CreateParty(), GetParty(), GetRelatedCharacterLogins(), PartyDisband(), and RemoveFromParty().
std::unordered_map<int32_t, std::shared_ptr<objects::PartyCharacter> > world::CharacterManager::mPartyCharacters private
Map of party characters by world CID.
Definition at line 591 of file CharacterManager.h.
Referenced by AddToParty(), CreateParty(), GetPartyMember(), and RemoveFromParty().
std::weak_ptr<WorldServer> world::CharacterManager::mServer private
Pointer back to theworld server this belongs to.
Definition at line 574 of file CharacterManager.h.
Referenced by ClanDisband(), ClanJoin(), ClanLeave(), GetCharacterLogin(), GetClan(), GetRelatedCharacterLogins(), PartyJoin(), RecalculateClanLevel(), RemoveFromClan(), RemoveFromTeam(), RequestChannelDisconnect(), SendClanDetails(), SendClanMemberInfo(), SendToCharacters(), and SendToRelatedCharacters().
std::unordered_map<int32_t, std::shared_ptr<objects::Team> > world::CharacterManager::mTeams private
Definition at line 599 of file CharacterManager.h.
Referenced by AddToTeam(), GetRelatedCharacterLogins(), GetTeam(), RemoveFromTeam(), and TeamDisband().
The documentation for this class was generated from the following files:
CharacterManager.h
CharacterManager.cpp