COMP_hack Logger: LobbyConnection Class Reference
LobbyConnection Class Reference
Proxy connection between the logger and the lobby server.
#include <LobbyConnection.h>
Public Member Functions
LobbyConnection (LoggerServer *server, qintptr socketDescriptor, uint32_t clientID, QObject *parent=0)
Create a new lobby connection.
virtual ~LobbyConnection ()
Delete the connection.
Protected Slots
void clientLost ()
This method is called when the client closes the connection.
void clientReady ()
This method is called when new data has arrived from the client.
void sendClientHello ()
This method is called when the connection to the lobby server is opened.
void serverLost ()
This method is called when the lobby server closes the connection.
void serverReady ()
This method is called when new data has arrived from the lobby server.
Protected Member Functions
void decryptPacket (const BF_KEY *key, libcomp::Packet &p)
Decrypt a packet.
void encryptCustomPacket (const BF_KEY *key, libcomp::Packet &p)
Encrypt a packet that has been modified.
void encryptPacket (const BF_KEY *key, libcomp::Packet &p)
Encrypt a packet.
void exchangeKeys ()
Exchange encryption keys with the lobby server.
void logMessage (const QString &msg)
Log a message to the console and GUI.
void logPacket (libcomp::Packet &p, uint8_t source)
Log a packet to the capture file and send it to the live capgrep.
void parseStartGamePacket (libcomp::Packet &p)
Parse the start game packet, modify it to direct to the logger, and send the modified packet to the client.
virtual void run ()
This method is called when the connection thread starts executing.
QString timestamp () const
Generate a timestamp to be used in the log.
Private Types
enum ConnectionState { NotConnected = 0, Connected, ExchangeStarted, Encrypted }
State of the lobby connection.
Private Attributes
QFile mCaptureLog
File to write the capture log to.
QString mClientAddress
IP address of the client connection.
CryptData mClientCryptData
Crypto data for the connection to the client.
uint32_t mClientID
Unique lobby ID of this client connection.
uint8_t * mClientLoginPacket
Buffer to store the login packet before it is sent to the server.
uint32_t mClientLoginPacketSize
Size of the login packet that is waiting to be sent to the server.
QTcpSocket * mClientSocket
Connection to the client.
ConnectionState mClientState
Connection state for the connection to the client.
uint32_t mClientVer
Version of the client used (1.234U would be 1234).
libcomp::Packet mKeyExchangePacket
Generated packet to be sent to the client upon connection.
LoggerServer * mServer
Logger server this connection belongs to.
CryptData mServerCryptData
Crypto data for the connection to the target server.
QTcpSocket * mServerSocket
Connection to the target server.
ConnectionState mServerState
Connection state for the connection to the target server.
qintptr mSocketDescriptor
Socket descriptior of the client connection.
libcomp::String mUsername
Username used to log into the lobby server.
Detailed Description
Proxy connection between the logger and the lobby server.
Definition at line 44 of file LobbyConnection.h.
Member Enumeration Documentation
enum LobbyConnection::ConnectionState private
State of the lobby connection.
Enumerator
NotConnected
Socket is not connected.
Connected
Socket is connected awaiting data.
ExchangeStarted
Encryption key exchange has started.
Encrypted
Connection is encrypted and running normally.
Definition at line 161 of file LobbyConnection.h.
Constructor & Destructor Documentation
LobbyConnection::LobbyConnection (LoggerServer * server, qintptr socketDescriptor, uint32_t clientID, QObject * parent = 0)
Create a new lobby connection.
server LoggerServer this connection was made from.
socketDescriptor Netowrk socket for the connection.
clientID ID to identify this client in the log.
parent Parent object that this object belongs to. Should remain 0.
Definition at line 53 of file LobbyConnection.cpp.
Member Function Documentation
void LobbyConnection::clientLost () protected slot
This method is called when the client closes the connection.
The connection to the lobby server will be closed and the connection object will be deleted.
Definition at line 155 of file LobbyConnection.cpp.
References logMessage(), mCaptureLog, mClientID, mClientLoginPacket, mClientSocket, mClientState, mServerSocket, and NotConnected.
Referenced by clientReady(), run(), and serverLost().
void LobbyConnection::clientReady () protected slot
This method is called when new data has arrived from the client.
The data will be parsed and then sent to the lobby server.
Definition at line 323 of file LobbyConnection.cpp.
References clientLost(), Connected, libcomp::Packet::Data(), decryptPacket(), libcomp::Packet::Direct(), libcomp::Convert::ENCODING_UTF8, Encrypted, encryptPacket(), ExchangeStarted, libcomp::Crypto::GenDiffieHellman(), LoggerServer::jpAddress(), libcomp::Packet::Left(), logPacket(), mClientCryptData, mClientLoginPacket, mClientLoginPacketSize, mClientSocket, mClientState, mClientVer, mKeyExchangePacket, mServer, mServerCryptData, mServerSocket, mServerState, mUsername, libcomp::Packet::ReadArray(), libcomp::Packet::ReadString16Little(), libcomp::Packet::ReadString32Big(), libcomp::Packet::ReadU16Little(), libcomp::Packet::ReadU32Big(), libcomp::Packet::ReadU32Little(), libcomp::Packet::Rewind(), libcomp::Packet::Seek(), sendClientHello(), serverLost(), serverReady(), libcomp::Packet::Size(), libcomp::Packet::Skip(), libcomp::Packet::Tell(), LoggerServer::usAddress(), and LoggerServer::usVersion().
Referenced by run().
void LobbyConnection::decryptPacket (const BF_KEY * key, libcomp::Packet & p) protected
Decrypt a packet.
key Blowfish key to decrypt with.
p Packet to be decrypted.
Definition at line 239 of file LobbyConnection.cpp.
References libcomp::Packet::ReadArray(), libcomp::Packet::Rewind(), libcomp::Packet::Seek(), libcomp::Packet::Size(), and libcomp::Packet::WriteArray().
Referenced by clientReady(), and serverReady().
void LobbyConnection::encryptCustomPacket (const BF_KEY * key, libcomp::Packet & p) protected
Encrypt a packet that has been modified.
This method will adjust the sizes and padding of the packet as required.
key Blowfish key to encrypt with.
p Packet to be encrypted.
Definition at line 267 of file LobbyConnection.cpp.
References libcomp::Packet::ReadArray(), libcomp::Packet::Rewind(), libcomp::Packet::Size(), libcomp::Packet::WriteArray(), and libcomp::Packet::WriteU32Big().
Referenced by parseStartGamePacket().
void LobbyConnection::encryptPacket (const BF_KEY * key, libcomp::Packet & p) protected
Encrypt a packet.
key Blowfish key to encrypt with.
p Packet to be encrypted.
Definition at line 211 of file LobbyConnection.cpp.
References libcomp::Packet::ReadArray(), libcomp::Packet::Rewind(), libcomp::Packet::Seek(), libcomp::Packet::Size(), and libcomp::Packet::WriteArray().
Referenced by clientReady(), exchangeKeys(), and serverReady().
void LobbyConnection::logMessage (const QString & msg) protected
Log a message to the console and GUI.
msg Message to log.
Definition at line 742 of file LobbyConnection.cpp.
References LoggerServer::addLogMessage(), mServer, and timestamp().
Referenced by clientLost(), parseStartGamePacket(), and run().
void LobbyConnection::logPacket (libcomp::Packet & p, uint8_t source) protected
Log a packet to the capture file and send it to the live capgrep.
p Packet to log.
source Source of the packet. 0 if the packet came from the client, 1 if the packet came from the server.
Definition at line 756 of file LobbyConnection.cpp.
References libcomp::Packet::Data(), mCaptureLog, libcomp::Packet::ReadU32Big(), libcomp::Packet::Rewind(), and libcomp::Packet::Size().
Referenced by clientReady(), and serverReady().
void LobbyConnection::parseStartGamePacket (libcomp::Packet & p) protected
Parse the start game packet, modify it to direct to the logger, and send the modified packet to the client.
p Packet that contains the original start game data.
Definition at line 788 of file LobbyConnection.cpp.
References libcomp::String::C(), libcomp::Packet::Data(), libcomp::Convert::ENCODING_UTF8, encryptCustomPacket(), logMessage(), mClientCryptData, mClientID, mClientSocket, mServer, libcomp::Packet::ReadString16Little(), libcomp::Packet::ReadU32Little(), LoggerServer::registerChannelKey(), libcomp::Packet::Seek(), libcomp::Packet::Size(), libcomp::Packet::WriteBlank(), libcomp::Packet::WriteString16Little(), libcomp::Packet::WriteU16Big(), libcomp::Packet::WriteU16Little(), libcomp::Packet::WriteU32Little(), and libcomp::Packet::WriteU8().
Referenced by serverReady().
void LobbyConnection::sendClientHello () protected slot
This method is called when the connection to the lobby server is opened.
The client hello packet will be sent to the lobby server.
Definition at line 535 of file LobbyConnection.cpp.
References mServerSocket.
Referenced by clientReady().
void LobbyConnection::serverLost () protected slot
This method is called when the lobby server closes the connection.
The connection to the client will be closed and the connection object will be deleted.
Definition at line 542 of file LobbyConnection.cpp.
References clientLost().
Referenced by clientReady(), exchangeKeys(), and serverReady().
void LobbyConnection::serverReady () protected slot
This method is called when new data has arrived from the lobby server.
The data will be parsed and then sent to the client.
Definition at line 548 of file LobbyConnection.cpp.
References libcomp::Packet::Data(), decryptPacket(), libcomp::Packet::Direct(), Encrypted, encryptPacket(), exchangeKeys(), libcomp::Packet::Left(), logPacket(), mClientCryptData, mClientSocket, mServerCryptData, mServerSocket, mServerState, parseStartGamePacket(), libcomp::Packet::ReadU16Little(), libcomp::Packet::ReadU32Big(), libcomp::Packet::Rewind(), libcomp::Packet::Seek(), serverLost(), libcomp::Packet::Size(), libcomp::Packet::Skip(), and libcomp::Packet::Tell().
Referenced by clientReady().
QString LobbyConnection::timestamp () const protected
Generate a timestamp to be used in the log.
Returns
The timestamp string.
Definition at line 149 of file LobbyConnection.cpp.
Referenced by logMessage().
The documentation for this class was generated from the following files:
LobbyConnection.h
LobbyConnection.cpp