COMP_hack Logger: LoggerServer Class Reference
LoggerServer Class Reference
The logger server class manages all other server objects and communication between them and the GUI.
#include <LoggerServer.h>
Signals
void message (const QString &msg)
New message to be logged.
void packet (const QByteArray &p)
New packet to be sent to capgrep.
Public Member Functions
LoggerServer (QObject *parent=0)
Create a new LoggerServer object.
virtual ~LoggerServer ()
Delete the LoggerServer object.
void addLogMessage (const QString &msg)
Add a log message to the GUI (if running the GUI version).
void addPacket (const QByteArray &p)
Send a packet to the packet analyser capgrep.
QString capturePath () const
Get the capture directory path.
bool isChannelLogEnabled () const
Determine if channel connections will save a capture file.
bool isLobbyLogEnabled () const
Determine if lobby connections will save a capture file.
bool isWebAuthJPEnabled () const
Determine if the web authentication feature is enabled.
QString jpAddress () const
Retrieve the target JP lobby server address.
uint32_t jpVersion () const
Retrieve the expected JP client version.
QString jpWebAuth () const
Retrieve the target web authentication URL.
void registerChannelKey (uint32_t key, const QString &addr)
Add a channel login key and it's original address.
QString retrieveChannelKey (uint32_t key)
Retrive the original server address for the given channel login key.
void setAddressJP (const QString &addr)
Set the address of the target JP lobby server.
void setAddressUS (const QString &addr)
Set the address of the target US lobby server.
void setCapturePath (const QString &path)
Set the packet capture log path.
void setChannelLogEnabled (bool enabled)
Enable or disable the creation of capture files by channel connections.
void setLobbyLogEnabled (bool enabled)
Enable or disable the creation of capture files by lobby connections.
void setVersionJP (uint32_t ver)
Set the client version for the JP lobby server connection.
void setVersionUS (uint32_t ver)
Set the client version for the US lobby server connection.
void setWebAuthJP (const QString &url)
Set the URL of the target website.
void setWebAuthJPEnabled (bool enabled)
Enable or disable the web authentication feature.
void startServer ()
Start the server and listen for new client connections.
QString usAddress () const
Retrieve the target US lobby server address.
uint32_t usVersion () const
Retrieve the expected US client version.
Private Attributes
QString mAddressJP
Address of the target JP lobby server.
QString mAddressUS
Address of the target US lobby server.
QString mCapturePath
Path to the directory to store capture files.
QMap< uint32_t, QString > mChannelKeys
Mapping of channel keys to their target channel server address.
bool mChannelLogEnabled
Variable to store if channel connections will save a capture file.
ChannelServer * mChannelServer
Channel server object to manage channel connections.
bool mLobbyLogEnabled
Variable to store if lobby connections will save a capture file.
LobbyServer * mLobbyServer
Lobby server object to manage lobby connections.
uint32_t mVersionJP
Expected JP client version.
uint32_t mVersionUS
Expected US client version.
QString mWebAuthJP
URL of the target web authentication server.
bool mWebAuthJPEnabled
Variable to store if the web authentication feature is enabled.
WebAuthServer * mWebAuthServer
Web authentication server object to manage web auth connections.
Detailed Description
The logger server class manages all other server objects and communication between them and the GUI.
Definition at line 168 of file LoggerServer.h.
Constructor & Destructor Documentation
LoggerServer::LoggerServer (QObject * parent = 0)
Create a new LoggerServer object.
Parameters
parent Parent object. This may be left to it's default value.
Definition at line 117 of file LoggerServer.cpp.
References mAddressJP, mAddressUS, mChannelLogEnabled, mChannelServer, mLobbyLogEnabled, mLobbyServer, mVersionJP, mVersionUS, mWebAuthJP, mWebAuthJPEnabled, and mWebAuthServer.
Member Function Documentation
void LoggerServer::addLogMessage (const QString & msg)
Add a log message to the GUI (if running the GUI version).
Parameters
msg Message to log.
Definition at line 342 of file LoggerServer.cpp.
References message().
Referenced by WebAuthConnection::logMessage(), ChannelConnection::logMessage(), LobbyConnection::logMessage(), and startServer().
void LoggerServer::addPacket (const QByteArray & p)
Send a packet to the packet analyser capgrep.
The packet is only sent if there is a valid live mode connection to capgrep.
Parameters
p Packet to send to capgrep.
Definition at line 348 of file LoggerServer.cpp.
References packet().
Referenced by ChannelConnection::logPacket().
QString LoggerServer::capturePath () const
Get the capture directory path.
Returns
Path to the capture directory.
Definition at line 150 of file LoggerServer.cpp.
References mCapturePath.
Referenced by LobbyConnection::run(), and ChannelConnection::run().
bool LoggerServer::isChannelLogEnabled () const
Determine if channel connections will save a capture file.
Returns
true if channel connections will save a capture file, false otherwise.
Definition at line 298 of file LoggerServer.cpp.
References mChannelLogEnabled.
Referenced by ChannelConnection::run(), and Settings::Settings().
bool LoggerServer::isLobbyLogEnabled () const
Determine if lobby connections will save a capture file.
Returns
true if lobby connections will save a capture file, false otherwise.
Definition at line 284 of file LoggerServer.cpp.
References mLobbyLogEnabled.
Referenced by LobbyConnection::run(), and Settings::Settings().
bool LoggerServer::isWebAuthJPEnabled () const
Determine if the web authentication feature is enabled.
Returns
true if the web authentication feature is enabled, false otherwise.
Definition at line 270 of file LoggerServer.cpp.
References mWebAuthJPEnabled.
Referenced by Settings::Settings(), and MainWindow::startGame().
QString LoggerServer::jpAddress () const
Retrieve the target JP lobby server address.
Returns
IP address of the target JP lobby server.
Definition at line 330 of file LoggerServer.cpp.
References mAddressJP.
Referenced by LobbyConnection::clientReady(), and Settings::Settings().
uint32_t LoggerServer::jpVersion () const
Retrieve the expected JP client version.
Returns
Version of the JP client.
Definition at line 318 of file LoggerServer.cpp.
References mVersionJP.
Referenced by Settings::Settings().
QString LoggerServer::jpWebAuth () const
Retrieve the target web authentication URL.
Returns
URL of the target web authentication site.
Definition at line 336 of file LoggerServer.cpp.
References mWebAuthJP.
Referenced by WebAuthConnection::clientReady(), and Settings::Settings().
void LoggerServer::message (const QString & msg) signal
New message to be logged.
Parameters
msg Message to be logged.
Referenced by addLogMessage().
void LoggerServer::packet (const QByteArray & p) signal
New packet to be sent to capgrep.
Parameters
p Packet to send to capgrep.
Referenced by addPacket().
void LoggerServer::registerChannelKey (uint32_t key, const QString & addr)
Add a channel login key and it's original address.
If the key already exists, the old server address will be replaced with the new one.
Parameters
key Channel login key provided by the lobby server.
addr Address of the target channel server.
Definition at line 172 of file LoggerServer.cpp.
References mChannelKeys.
Referenced by LobbyConnection::parseStartGamePacket(), and ChannelConnection::rewriteServerSwitchPacket().
QString LoggerServer::retrieveChannelKey (uint32_t key)
Retrive the original server address for the given channel login key.
Parameters
key Channel login key provided by the lobby server.
Returns
The associated server address or an empty string if the key was not found.
Definition at line 162 of file LoggerServer.cpp.
References mChannelKeys.
Referenced by ChannelConnection::clientReady().
void LoggerServer::setAddressJP (const QString & addr)
Set the address of the target JP lobby server.
The address should be in the form: "lobby.server.ip.address. The port is assumed to be 10666.
Parameters
addr Address of the target JP lobby server.
Definition at line 254 of file LoggerServer.cpp.
References mAddressJP.
Referenced by Settings::saveAndClose().
void LoggerServer::setAddressUS (const QString & addr)
Set the address of the target US lobby server.
The address should be in the form: "lobby.server.ip.address. The port is assumed to be 10666.
Parameters
addr Address of the target US lobby server.
Definition at line 246 of file LoggerServer.cpp.
References mAddressUS.
Referenced by Settings::saveAndClose().
void LoggerServer::setCapturePath (const QString & path)
Set the packet capture log path.
Parameters
path Capture directory path to set.
Definition at line 156 of file LoggerServer.cpp.
References mCapturePath.
Referenced by MainWindow::init(), and main().
void LoggerServer::setChannelLogEnabled (bool enabled)
Enable or disable the creation of capture files by channel connections.
Parameters
enabled true if channel connections will save a capture file, false otherwise.
Definition at line 304 of file LoggerServer.cpp.
References mChannelLogEnabled.
Referenced by Settings::saveAndClose(), and MainWindow::startGame().
void LoggerServer::setLobbyLogEnabled (bool enabled)
Enable or disable the creation of capture files by lobby connections.
Parameters
enabled true if lobby connections will save a capture file, false otherwise.
Definition at line 290 of file LoggerServer.cpp.
References mLobbyLogEnabled.
Referenced by Settings::saveAndClose().
void LoggerServer::setVersionJP (uint32_t ver)
Set the client version for the JP lobby server connection.
This version is used to determine which client is connecting and which target lobby server should be used.
Parameters
ver Version of the JP client. The version is represented as an integer. For example, the client version 1.234 would have the integer representation 1.234.
Definition at line 238 of file LoggerServer.cpp.
References mVersionJP.
Referenced by Settings::saveAndClose(), and MainWindow::startGame().
void LoggerServer::setVersionUS (uint32_t ver)
Set the client version for the US lobby server connection.
This version is used to determine which client is connecting and which target lobby server should be used.
Parameters
ver Version of the US client. The version is represented as an integer. For example, the client version 1.234U would have the integer representation 1.234.
Definition at line 230 of file LoggerServer.cpp.
References mVersionUS.
Referenced by Settings::saveAndClose(), and MainWindow::startGame().
void LoggerServer::setWebAuthJP (const QString & url)
Set the URL of the target website.
The URL should be exactly as it appears in the webaccess.sdat file.
Parameters
addr URL of the target website.
Definition at line 262 of file LoggerServer.cpp.
References mWebAuthJP.
Referenced by Settings::saveAndClose().
void LoggerServer::setWebAuthJPEnabled (bool enabled)
Enable or disable the web authentication feature.
Parameters
enabled true if the web authentication feature should be enabled, false otherwise.
Definition at line 276 of file LoggerServer.cpp.
References mWebAuthJPEnabled.
Referenced by Settings::saveAndClose().
QString LoggerServer::usAddress () const
Retrieve the target US lobby server address.
Returns
IP address of the target US lobby server.
Definition at line 324 of file LoggerServer.cpp.
References mAddressUS.
Referenced by LobbyConnection::clientReady(), and Settings::Settings().
uint32_t LoggerServer::usVersion () const
Retrieve the expected US client version.
Returns
Version of the US client.
Definition at line 312 of file LoggerServer.cpp.
References mVersionUS.
Referenced by LobbyConnection::clientReady(), and Settings::Settings().
The documentation for this class was generated from the following files:
LoggerServer.h
LoggerServer.cpp