COMP_hack Logger: WebAuthConnection Class Reference
WebAuthConnection Class Reference
Proxy connection between the logger and the web authentication server.
#include <WebAuthConnection.h>
Public Member Functions
WebAuthConnection (LoggerServer *server, qintptr socketDescriptor, uint32_t clientID, QObject *parent=0)
Create a new web authentication connection.
virtual ~WebAuthConnection ()
Delete the connection.
Protected Slots
void clientLost ()
This method is called when the client closes the connection.
void clientReady ()
This method is called when new data has arrived from the client.
void parseRequest ()
Parse an HTTP request.
void peerVerifyError (const QSslError &error)
Handle any SSL peer verification errors.
void serverLost ()
This method is called when the web auth server closes the connection.
void serverReady ()
This method is called when new data has arrived from the web auth server.
void sslErrors (const QList< QSslError > &errors)
Handle any SSL errors that have occured.
Protected Member Functions
void logMessage (const QString &msg)
Log a message to the console and GUI.
virtual void run ()
This method is called when the connection thread starts executing.
QString timestamp () const
Generate a timestamp to be used in the log.
Private Attributes
QByteArray mBuffer
Buffer of the most recent HTTP request.
QString mClientAddress
IP address of the client connection.
uint32_t mClientID
Unique channel ID of this client connection.
QTcpSocket * mClientSocket
Connection to the client.
QStringList mHeaderKeys
List of HTTP headers in the order they occured.
QHash< QString, QString > mHeaders
Map of the HTTP headers and their values.
QString mHost
Host name of the target server.
QString mReqLine
Request line of the most recent HTTP request.
LoggerServer * mServer
Logger server this connection belongs to.
QSslSocket * mServerSocket
Connection to the target server.
qintptr mSocketDescriptor
Socket descriptior of the client connection.
Detailed Description
Proxy connection between the logger and the web authentication server.
Definition at line 45 of file WebAuthConnection.h.
Constructor & Destructor Documentation
WebAuthConnection::WebAuthConnection (LoggerServer * server, qintptr socketDescriptor, uint32_t clientID, QObject * parent = 0)
Create a new web authentication connection.
Parameters
server LoggerServer this connection was made from.
socketDescriptor Netowrk socket for the connection.
clientID ID to identify this client in the log.
parent Parent object that this object belongs to. Should remain 0.
Definition at line 43 of file WebAuthConnection.cpp.
Member Function Documentation
void WebAuthConnection::clientLost () protected slot
This method is called when the client closes the connection.
The connection to the web auth server will be closed and the connection object will be deleted.
Definition at line 104 of file WebAuthConnection.cpp.
References logMessage(), mClientID, and mServerSocket.
Referenced by run().
void WebAuthConnection::clientReady () protected slot
This method is called when new data has arrived from the client.
The data will be parsed and then sent to the web auth server.
Definition at line 131 of file WebAuthConnection.cpp.
References LoggerServer::jpWebAuth(), logMessage(), mBuffer, mClientSocket, mHeaderKeys, mHeaders, mHost, mReqLine, mServer, mServerSocket, parseRequest(), peerVerifyError(), serverLost(), serverReady(), and sslErrors().
Referenced by run().
void WebAuthConnection::logMessage (const QString & msg) protected
Log a message to the console and GUI.
Parameters
msg Message to log.
Definition at line 371 of file WebAuthConnection.cpp.
References LoggerServer::addLogMessage(), mServer, and timestamp().
Referenced by clientLost(), clientReady(), parseRequest(), peerVerifyError(), run(), and sslErrors().
void WebAuthConnection::peerVerifyError (const QSslError & error) protected slot
Handle any SSL peer verification errors.
Parameters
error Peer verification error.
Definition at line 90 of file WebAuthConnection.cpp.
References logMessage(), and mClientID.
Referenced by clientReady().
void WebAuthConnection::serverLost () protected slot
This method is called when the web auth server closes the connection.
The connection to the client will be closed and the connection object will be deleted.
Definition at line 385 of file WebAuthConnection.cpp.
References mClientSocket.
Referenced by clientReady().
void WebAuthConnection::serverReady () protected slot
This method is called when new data has arrived from the web auth server.
The data will be parsed and then sent to the client.
Definition at line 391 of file WebAuthConnection.cpp.
References mClientSocket, and mServerSocket.
Referenced by clientReady().
void WebAuthConnection::sslErrors (const QList< QSslError > & errors) protected slot
Handle any SSL errors that have occured.
Parameters
errors List of SSL errors.
Definition at line 80 of file WebAuthConnection.cpp.
References logMessage(), and mClientID.
Referenced by clientReady().
QString WebAuthConnection::timestamp () const protected
Generate a timestamp to be used in the log.
Returns
The timestamp string.
Definition at line 98 of file WebAuthConnection.cpp.
Referenced by logMessage().
The documentation for this class was generated from the following files:
WebAuthConnection.h
WebAuthConnection.cpp