COMP_hack Logger: Settings Class Reference
Settings Class Reference
User interface to change the logger settings.
#include <Settings.h>
Public Slots
void addClient ()
The user has clicked the add client button and should be presented with a dialog to select the directory where the client executable is located.
void removeClient ()
The user has clicked the remove client button and the client install should be removed from the list.
void saveAndClose ()
Save all settings in the dialog and close the window.
void selectedClient ()
The selection in the client list has changed and the remove client button should be enabled or disabled depending on if a client is selected in the list.
Signals
void clientListChanged (const QVariantMap &clientList)
Signal to notify the MainWindow of the updated client list.
Public Member Functions
Settings (LoggerServer *server, QWidget *parent=0)
Create the user interface widget.
Protected Attributes
LoggerServer * mServer
LoggerServer whose settings are to be changed.
Ui::Settings ui
The generated user interface class.
Detailed Description
User interface to change the logger settings.
Definition at line 40 of file Settings.h.
Constructor & Destructor Documentation
Settings::Settings (LoggerServer * server, QWidget * parent = 0)
Create the user interface widget.
Parameters
server Logger server to change the settings for.
parent Parent object. This should be left to it's default value because the settings interface is a dialog (window).
Definition at line 38 of file Settings.cpp.
References addClient(), LoggerServer::isChannelLogEnabled(), LoggerServer::isLobbyLogEnabled(), LoggerServer::isWebAuthJPEnabled(), LoggerServer::jpAddress(), LoggerServer::jpVersion(), LoggerServer::jpWebAuth(), removeClient(), saveAndClose(), selectedClient(), ui, LoggerServer::usAddress(), and LoggerServer::usVersion().
Member Function Documentation
void Settings::clientListChanged (const QVariantMap & clientList) signal
Signal to notify the MainWindow of the updated client list.
This signal is used to update the start game sub-menu.
Parameters
clientList Mapping of client names and their associated install path.
See Also
MainWindow::updateClientList
Referenced by saveAndClose().
The documentation for this class was generated from the following files:
Settings.h
Settings.cpp