COMP_hack: channel::AccountManager Class Reference
channel::AccountManager Class Reference
Manager to handle Account focused actions.
#include <AccountManager.h>
Public Member Functions
AccountManager (const std::weak_ptr< ChannelServer > &server)
Create a new AccountManager.
~AccountManager ()
Clean up the AccountManager.
void Authenticate (const std::shared_ptr< channel::ChannelClientConnection > &client)
Authenticate an account by its connection.
libcomp::String DumpAccount (channel::ClientState *state)
Dump the account and return it.
std::shared_ptr
< objects::CharacterLogin > GetActiveLogin (const libobjgen::UUID &characterUID)
Get an active CharacterLogin by world CID.
std::unordered_map< int32_t,
std::shared_ptr
< objects::CharacterLogin > > GetActiveLogins ()
Get all active CharacterLogins associated to the world.
void HandleLoginRequest (const std::shared_ptr< channel::ChannelClientConnection > &client, const libcomp::String &username, uint32_t sessionKey)
Request information from the world to log an account in by their username.
void HandleLoginResponse (const std::shared_ptr< channel::ChannelClientConnection > &client)
Respond to the game client with the result of the login request.
void HandleLogoutRequest (const std::shared_ptr< channel::ChannelClientConnection > &client, LogoutCode_t code, uint8_t channelIdx=0)
Handle the client's logout request.
bool IncreaseCP (const std::shared_ptr< objects::Account > &account, int64_t addAmount)
Increase the account's current CP balance.
void Logout (const std::shared_ptr< channel::ChannelClientConnection > &client, bool delay=false)
Log out a user by their connection.
std::shared_ptr
< objects::ChannelLogin > PrepareChannelChange (const std::shared_ptr< channel::ChannelClientConnection > &client, uint32_t zoneID, uint32_t dynamicMapID, uint8_t channelID)
Create a channel change ChannelLogin for the supplied client and save all logout information now.
void RequestDisconnect (const std::shared_ptr< channel::ChannelClientConnection > &client)
Request that a client disconnect from the server.
void SendCPBalance (const std::shared_ptr< channel::ChannelClientConnection > &client)
Send the account's current CP balance.
void UpdateLogins (std::list< std::shared_ptr< objects::CharacterLogin >> updates, std::list< std::shared_ptr< objects::CharacterLogin >> removes)
Update all registered CharacterLogins on the server.
Private Member Functions
bool InitializeCharacter (libcomp::ObjectReference< objects::Character > &character, channel::ClientState *state)
Create/load character data for use upon logging in.
bool InitializeNewCharacter (std::shared_ptr< objects::Character > character)
Create character data if not initialized.
bool LogoutCharacter (channel::ClientState *state)
Persist character data associated to a client that is logging out.
void WipeMember (tinyxml2::XMLElement *pElement, const std::string &field)
Delete a <member> from an object in the XML DOM.
Private Attributes
std::unordered_map< int32_t,
std::shared_ptr
< objects::CharacterLogin > > mActiveLogins
Map of all character logins active on the world by world CID.
std::unordered_map
< libcomp::String, int32_t > mCIDMap
Map of character UUIDs to world CID for any active login.
std::mutex mLock
Server lock for shared resources.
std::weak_ptr< ChannelServer > mServer
Pointer to the channel server.
Detailed Description
Manager to handle Account focused actions.
Definition at line 65 of file AccountManager.h.
Constructor & Destructor Documentation
AccountManager::AccountManager (const std::weak_ptr< ChannelServer > & server)
Create a new AccountManager.
Parameters
server Pointer back to the channel server this belongs to
Definition at line 78 of file AccountManager.cpp.
AccountManager::~AccountManager ()
Clean up the AccountManager.
Definition at line 83 of file AccountManager.cpp.
Member Function Documentation
void AccountManager::Authenticate (const std::shared_ptr< channel::ChannelClientConnection > & client)
Authenticate an account by its connection.
Parameters
client Pointer to the client connection
Definition at line 542 of file AccountManager.cpp.
References channel::state(), libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteU32Little().
Referenced by AuthenticateAccount().
libcomp::String AccountManager::DumpAccount (channel::ClientState * state)
Dump the account and return it.
This account data can then be imported into another server.
Parameters
state ClientState object for the account to dump.
Returns
Dump of the account or an empty string on error.
Definition at line 1973 of file AccountManager.cpp.
References channel::ClientState::GetAccountUID(), InitializeCharacter(), libcomp::PersistentObject::LoadObjectByUUID(), mServer, and WipeMember().
Referenced by DumpAccount().
std::shared_ptr< objects::CharacterLogin > AccountManager::GetActiveLogin (const libobjgen::UUID & characterUID)
Get an active CharacterLogin by world CID.
Parameters
characterUID Character UUID to retrieve
Returns
Pointer to the active CharacterLogin or null if no matching UID is active
Definition at line 618 of file AccountManager.cpp.
References mActiveLogins, mCIDMap, and mLock.
std::unordered_map< int32_t, std::shared_ptr< objects::CharacterLogin > > AccountManager::GetActiveLogins ()
Get all active CharacterLogins associated to the world.
Returns
Map of active CharacterLogins by world CID
Definition at line 612 of file AccountManager.cpp.
References mActiveLogins.
void AccountManager::HandleLoginRequest (const std::shared_ptr< channel::ChannelClientConnection > & client, const libcomp::String & username, uint32_t sessionKey)
Request information from the world to log an account in by their username.
Parameters
client Pointer to the client connection
username Username to log in with
sessionKey Session key to validate
Definition at line 87 of file AccountManager.cpp.
References libcomp::String::Arg(), libcomp::Convert::ENCODING_UTF8, mServer, channel::state(), and libcomp::Packet::WritePacketCode().
Referenced by LoginAccount().
void AccountManager::HandleLoginResponse (const std::shared_ptr< channel::ChannelClientConnection > & client)
Respond to the game client with the result of the login request.
Parameters
client Pointer to the client connection
Definition at line 132 of file AccountManager.cpp.
References libcomp::String::Arg(), EFFECT_CANCEL_LOGOUT, EFFECT_CANCEL_ZONEOUT, channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), libcomp::PersistentObject::GetObjectByUUID(), InitializeCharacter(), LogoutCharacter(), mServer, channel::ClientState::Register(), channel::state(), SVR_CONST, libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteString16Little(), and libcomp::Packet::WriteU32Little().
Referenced by HandleLoginResponse().
void AccountManager::HandleLogoutRequest (const std::shared_ptr< channel::ChannelClientConnection > & client, LogoutCode_t code, uint8_t channelIdx = 0)
Handle the client's logout request.
Parameters
client Pointer to the client connection
code Action being requested
channelIdx Index of the channel to connect to after logging out. This will only be used if the the logout code is LOGOUT_CODE_SWITCH.
Definition at line 281 of file AccountManager.cpp.
References channel::ChannelServer::GetServerTime(), channel::LOGOUT_CODE_QUIT, channel::LOGOUT_CODE_SWITCH, mServer, libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteString16Little(), and libcomp::Packet::WriteU32Little().
bool AccountManager::IncreaseCP (const std::shared_ptr< objects::Account > & account, int64_t addAmount)
Increase the account's current CP balance.
Parameters
account Pointer to the account to update
addAmount Amount of CP to add to the account
Returns
true if the amount was updated, false if it could not be updated
Definition at line 563 of file AccountManager.cpp.
References libcomp::String::Arg(), and mServer.
bool AccountManager::InitializeCharacter (libcomp::ObjectReference< objects::Character > & character, channel::ClientState * state) private
Create/load character data for use upon logging in.
Parameters
character Character to initialize
state Pointer to the client state the character belongs to
Returns
true on success, false on failure
Definition at line 655 of file AccountManager.cpp.
References libcomp::String::Arg(), libcomp::DatabaseChangeSet::Create(), channel::ClientState::GetAccountUID(), libcomp::PersistentObject::GetObjectByUUID(), channel::ClientState::GetObjectID(), InitializeNewCharacter(), mServer, libcomp::PersistentObject::New(), and channel::ClientState::SetObjectID().
Referenced by DumpAccount(), and HandleLoginResponse().
bool AccountManager::InitializeNewCharacter (std::shared_ptr< objects::Character > character) private
Create character data if not initialized.
Supported objects are as follows:
Character (limited fields)
CharacterProgress (only one per file)
Item (including starting equipment)
Demon (limited to COMP slots)
EntityStats (stats/level for character, level only for demon, must by linked via UID)
Expertise (must be linked via UID)
Hotbar (must be linked via UID)
Parameters
character Character to initialize
Returns
true on success, false on failure
Definition at line 1465 of file AccountManager.cpp.
References libcomp::PersistentObject::GetObjectByUUID(), mServer, and libcomp::PersistentObject::New().
Referenced by InitializeCharacter().
void AccountManager::Logout (const std::shared_ptr< channel::ChannelClientConnection > & client, bool delay = false)
Log out a user by their connection.
Parameters
client Pointer to the client connection
delay Optional parameter to perform the normal logout save actions but leave the connection open to be removed upon the connection actually closing
Definition at line 383 of file AccountManager.cpp.
References libcomp::String::Arg(), channel::ClientState::GetCharacterState(), channel::ClientState::GetWorldCID(), LogoutCharacter(), mServer, and channel::state().
Referenced by channel::ManagerConnection::RemoveClientConnection().
bool AccountManager::LogoutCharacter (channel::ClientState * state) private
Persist character data associated to a client that is logging out.
Parameters
state Pointer to the client state the character belongs to
Returns
true on success, false on failure
Definition at line 1822 of file AccountManager.cpp.
References libcomp::DatabaseChangeSet::Create(), and mServer.
Referenced by HandleLoginResponse(), Logout(), and PrepareChannelChange().
std::shared_ptr< objects::ChannelLogin > AccountManager::PrepareChannelChange (const std::shared_ptr< channel::ChannelClientConnection > & client, uint32_t zoneID, uint32_t dynamicMapID, uint8_t channelID)
Create a channel change ChannelLogin for the supplied client and save all logout information now.
The world communication must be handled elsewhere.
Parameters
client Pointer to the client connection
zoneID ID of the zone the player will enter on the other channel. If 0 the current character state will be used.
dynamicMapID Dynamic map ID of the zone the player will enter on the other channel. If 0 the current character state will be used.
channelID ID of the channel being moved to
Returns
Pointer to the channel change ChannelLogin
Definition at line 482 of file AccountManager.cpp.
References channel::ClientState::GetCharacterState(), channel::ClientState::GetZone(), LogoutCharacter(), mServer, and channel::state().
void AccountManager::RequestDisconnect (const std::shared_ptr< channel::ChannelClientConnection > & client)
Request that a client disconnect from the server.
Typically used following an initial logout request from the client.
Parameters
client Pointer to the client connection
Definition at line 470 of file AccountManager.cpp.
References libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteU32Little().
void AccountManager::SendCPBalance (const std::shared_ptr< channel::ChannelClientConnection > & client)
Send the account's current CP balance.
Parameters
client Pointer to the client connection
Definition at line 594 of file AccountManager.cpp.
References channel::ClientState::GetAccountUID(), mServer, channel::state(), and libcomp::Packet::WritePacketCode().
void AccountManager::UpdateLogins (std::list< std::shared_ptr< objects::CharacterLogin >> updates, std::list< std::shared_ptr< objects::CharacterLogin >> removes)
Update all registered CharacterLogins on the server.
Parameters
update List of updated CharacterLogins
removes List of removed CharacterLogins
Definition at line 636 of file AccountManager.cpp.
References mActiveLogins, mCIDMap, and mLock.
void AccountManager::WipeMember (tinyxml2::XMLElement * pElement, const std::string & field) private
Delete a <member> from an object in the XML DOM.
Parameters
pElement Object element to delete the <member> from.
field Name of the member field to delete.
Definition at line 1947 of file AccountManager.cpp.
Referenced by DumpAccount().
Member Data Documentation
std::unordered_map<int32_t, std::shared_ptr<objects::CharacterLogin> > channel::AccountManager::mActiveLogins private
Map of all character logins active on the world by world CID.
Definition at line 251 of file AccountManager.h.
Referenced by GetActiveLogin(), GetActiveLogins(), and UpdateLogins().
std::unordered_map<libcomp::String, int32_t> channel::AccountManager::mCIDMap private
Map of character UUIDs to world CID for any active login.
Definition at line 254 of file AccountManager.h.
Referenced by GetActiveLogin(), and UpdateLogins().
std::mutex channel::AccountManager::mLock private
Server lock for shared resources.
Definition at line 257 of file AccountManager.h.
Referenced by GetActiveLogin(), and UpdateLogins().
std::weak_ptr<ChannelServer> channel::AccountManager::mServer private
Pointer to the channel server.
Definition at line 260 of file AccountManager.h.
Referenced by DumpAccount(), HandleLoginRequest(), HandleLoginResponse(), HandleLogoutRequest(), IncreaseCP(), InitializeCharacter(), InitializeNewCharacter(), Logout(), LogoutCharacter(), PrepareChannelChange(), and SendCPBalance().
The documentation for this class was generated from the following files:
AccountManager.h
AccountManager.cpp