COMP_hack: channel::ZoneManager Class Reference
channel::ZoneManager Class Reference
Manager to handle zone focused actions.
#include <ZoneManager.h>
Public Member Functions
ZoneManager (const std::weak_ptr< ChannelServer > &server)
Create a new ZoneManager.
~ZoneManager ()
Clean up the ZoneManager.
bool AddEnemiesToZone (const std::list< std::shared_ptr< ActiveEntityState >> &eStates, const std::shared_ptr< Zone > &zone, bool staggerSpawn, bool asEncounter, const std::list< std::shared_ptr< objects::Action >> &defeatActions)
Add enemies (or allies) already created in the zone, prepare AI and fire spawn triggers.
bool AddEnemiesToZone (std::list< std::shared_ptr< ActiveEntityState >> eStates, const std::shared_ptr< Zone > &zone, bool staggerSpawn, bool asEncounter, const libcomp::String &defeatEventID)
Add enemies (or allies) already created in the zone, prepare AI and fire spawn triggers.
void BroadcastPacket (const std::shared_ptr< ChannelClientConnection > &client, libcomp::Packet &p, bool includeSelf=true)
Send a packet to every connection in the zone or all but the client specified.
void BroadcastPacket (const std::shared_ptr< Zone > &zone, libcomp::Packet &p)
Send a packet to every connection in the specified zone.
Point CollisionAdjust (const Point &src, const Point &collidePoint)
Adjust a destination point based on a source point and the point where it collides with the nearest zone geometry point.
bool CorrectClientPosition (const std::shared_ptr< ActiveEntityState > &eState, Point &dest)
Correct a client supplied entity position to ensure it does not move out of bounds.
uint8_t CorrectClientPosition (const std::shared_ptr< ActiveEntityState > &eState, Point &src, Point &dest, ServerTime &startTime, ServerTime &stopTime, bool isMove=false)
Correct a client supplied entity position to ensure it does not move out of bounds.
std::shared_ptr
< ActiveEntityState > CreateAlly (const std::shared_ptr< Zone > &zone, uint32_t demonID, uint32_t spotID, float x, float y, float rot)
Create an ally in the specified zone at set coordinates but do not add it to the zone yet.
std::shared_ptr
< ActiveEntityState > CreateEnemy (const std::shared_ptr< Zone > &zone, uint32_t demonID, uint32_t spawnID, uint32_t spotID, float x, float y, float rot)
Create an enemy (or ally) in the specified zone at set coordinates but do not add it to the zone yet.
uint8_t CreateInstance (const std::shared_ptr< objects::InstanceAccess > &access)
Create a zone instance with access granted for the supplied CIDs.
void EndInstanceTimer (const std::shared_ptr< ZoneInstance > &instance, const std::shared_ptr< ChannelClientConnection > &client, bool isSuccess, bool queue=false)
End the timer currently assigned to the supplied zone instance for a specific client and contextually process anything that should occur upon this action happening.
bool EnterZone (const std::shared_ptr< ChannelClientConnection > &client, uint32_t zoneID, uint32_t dynamicMapID)
Perform all zone entry setup and related actions for a player associated to the supplied client using the default starting point.
bool EnterZone (const std::shared_ptr< ChannelClientConnection > &client, uint32_t zoneID, uint32_t dynamicMapID, float xCoord, float yCoord, float rotation, bool forceLeave=false)
Perform all zone entry setup and related actions for a player associated to the supplied client using an explicit entry point.
void ExpireInstance (uint32_t instanceID, uint64_t timeOut)
Expire and remove an instance matching the supplied values.
void ExpireRentals (const std::shared_ptr< Zone > &zone)
Expire and inactivate bazaar markets and culture machines that are no longer active in the specified zone.
bool ExtendInstanceTimer (const std::shared_ptr< ZoneInstance > &instance, uint32_t seconds)
Extend the timer currently assigned to the supplied zone instance.
void FailPlasma (const std::shared_ptr< ChannelClientConnection > &client, int32_t plasmaID, int8_t pointID=0)
Fail the supplied client's current plasma minigame.
void FixCurrentPosition (const std::shared_ptr< ActiveEntityState > &eState, uint64_t fixUntil, uint64_t now=0)
Stop and fix an entity at their current position for the specified amount of time.
std::shared_ptr< Zone > GetCurrentZone (const std::shared_ptr< ChannelClientConnection > &client)
Get the zone associated to a client connection.
std::shared_ptr< Zone > GetCurrentZone (int32_t worldCID)
Get the zone associated to a character entity ID.
std::shared_ptr< Zone > GetExistingZone (uint32_t zoneID, uint32_t dynamicMapID, uint32_t instanceID=0)
Get a zone by definition ID, dynamic map ID and (optionally) instance ID.
std::shared_ptr< Zone > GetGlobalZone (uint32_t zoneID, uint32_t dynamicMapID)
Get a zone by definition ID and dynamic map ID.
std::shared_ptr< ZoneInstance > GetInstance (uint32_t instanceID)
Get a zone instance by ID.
std::shared_ptr
< objects::InstanceAccess > GetInstanceAccess (int32_t worldCID)
Get the zone instance access available to the supplied world CID.
std::shared_ptr< Zone > GetInstanceStartingZone (const std::shared_ptr< ZoneInstance > &instance)
Get or create the first zone in the supplied instance.
std::shared_ptr< Zone > GetInstanceZone (const std::shared_ptr< ZoneInstance > &instance, uint32_t zoneID, uint32_t dynamicMapID)
Get or create a zone in the supplied instance.
Point GetLinearPoint (float sourceX, float sourceY, float targetX, float targetY, float distance, bool away, const std::shared_ptr< Zone > &zone=nullptr)
Get a point directly away or directly towards two specified points.
bool GetLoginZone (const std::shared_ptr< objects::Character > &character, uint32_t &zoneID, uint32_t &dynamicMapID, int8_t &channelID, float &x, float &y, float &rot)
Get information about the correct zone and channel to log into for the supplied character.
bool GetMatchStartPosition (const std::shared_ptr< ChannelClientConnection > &client, const std::shared_ptr< Zone > &zone, float &x, float &y, float &rot)
Get the coordinates of a match starting point in the supplied zone for the client.
Point GetRandomPoint (float width, float height) const
Get a random point within the specified width and height representing a rectangular area in a zone.
Point GetRandomSpotPoint (const std::shared_ptr< objects::MiSpotData > &spot, const std::shared_ptr< objects::MiZoneData > &zoneData=nullptr)
Get a random point within the supplied zone spot.
std::list< Point > GetShortestPath (const std::shared_ptr< Zone > &zone, const Point &source, const Point &dest, float maxDistance=0.f)
Calculate the shortest path between the supplied source and destination points for the specified zone.
bool GetSpotPosition (uint32_t dynamicMapID, uint32_t spotID, float &x, float &y, float &rot) const
Get the X/Y coordinates and rotation of the center point of a spot.
std::list< std::shared_ptr
< ChannelClientConnection > > GetZoneConnections (const std::shared_ptr< ChannelClientConnection > &client, bool includeSelf=true)
Get a list of client connections in the zone.
std::list< std::shared_ptr
< objects::ServerZoneTrigger > > GetZoneTriggers (const std::shared_ptr< Zone > &zone, ZoneTrigger_t trigger)
Gather zone specific triggers.
void HandleDeathTimeOut (const std::shared_ptr< ZoneInstance > &instance, const std::shared_ptr< ChannelClientConnection > &client, uint64_t deathTime)
Handle instance specific death time-out scheduling and processing.
void HandleTimedActions (const WorldClock &clock, const WorldClockTime &lastTrigger)
Perform time-based actions depending on the current world clock time.
bool HandleZoneTriggers (const std::shared_ptr< Zone > &zone, const std::list< std::shared_ptr< objects::ServerZoneTrigger >> &triggers, const std::shared_ptr< ActiveEntityState > &entity=nullptr, const std::shared_ptr< ChannelClientConnection > &client=nullptr)
Handle zone specific actions from triggers for either the entire zone or one specific entity.
void InstanceGlobalZones ()
Instantiate all global zones the server is responsible for hosting.
void LeaveZone (const std::shared_ptr< ChannelClientConnection > &client, bool logOut, uint32_t newZoneID=0, uint32_t newDynamicMapID=0)
Remove a client connection from a zone.
bool LinearReposition (const std::shared_ptr< ActiveEntityState > &eState, float x, float y)
Move the supplied entity from its current position to the supplied x/y coordinates in their current zone.
void LoadGeometry ()
Load all QMP zone geometry files and prepare them to be bound to zones as they are instantiated.
Point MoveRelative (const std::shared_ptr< ActiveEntityState > &eState, float targetX, float targetY, float distance, bool away, uint64_t now, uint64_t endTime)
Set an entity's destination position at a distace directly away or directly towards the specified point.
bool MoveToInstance (const std::shared_ptr< ChannelClientConnection > &client, std::shared_ptr< objects::InstanceAccess > access=nullptr, bool diasporaEnter=false)
Move the supplied client to the starting zone of the instance they are entering.
bool MoveToLobby (const std::shared_ptr< ChannelClientConnection > &client)
Move the supplied client to the lobby zone of the zone they are currently in.
void MultiZoneBossKilled (const std::shared_ptr< Zone > &zone, ClientState *sourceState, const std::list< uint32_t > &types)
Perform any updates related to multi-zone bosses being killed.
void PopEntityForProduction (const std::shared_ptr< ChannelClientConnection > &client, int32_t entityID, int32_t type, bool queue=false)
Send a request to a client to prepare an entity for display.
void PopEntityForProduction (const std::list< std::shared_ptr< ChannelClientConnection >> &clients, int32_t entityID, int32_t type, bool queue=false)
Send a request to a list of clients to prepare an entity for display.
void PopEntityForZoneProduction (const std::shared_ptr< Zone > &zone, int32_t entityID, int32_t type)
Send a request to all clients in a zone to prepare an entity for display.
void RemoveEntities (const std::list< std::shared_ptr< ChannelClientConnection >> &clients, const std::list< int32_t > &entityIDs, int32_t removalMode=0, bool queue=false)
Send a request to the specified game clients to remove an entity.
void RemoveEntitiesFromZone (const std::shared_ptr< Zone > &zone, const std::list< int32_t > &entityIDs, int32_t removalMode=0, bool queue=false)
Send a request to all game clients in a zone to remove an entity.
void ScheduleEntityRemoval (uint64_t time, const std::shared_ptr< Zone > &zone, const std::list< int32_t > &entityIDs, int32_t removeMode=0)
Schedule the delayed removal of one or more entities in the specified zone.
void SendBazaarMarketData (const std::shared_ptr< Zone > &zone, const std::shared_ptr< BazaarState > &bState, uint32_t marketID)
Send information about the current market matching the supplied ID in a bazaar to clients in the same zone.
void SendCultureMachineData (const std::shared_ptr< Zone > &zone, const std::shared_ptr< CultureMachineState > &cmState)
Send information about the supplied culture machine state to clients in the same zone.
void SendDestinyBox (const std::shared_ptr< ChannelClientConnection > &client, bool eventMenu, bool queue=false)
Send the current state of the destiny box a client has access to.
void SendInstanceTimer (const std::shared_ptr< ZoneInstance > &instance, const std::shared_ptr< ChannelClientConnection > &client=nullptr, bool queue=false, uint32_t extension=0)
Send the timer currently assigned to the supplied zone instance to one or all clients currenctly connected to it.
void SendLootBoxData (const std::shared_ptr< ChannelClientConnection > &client, const std::shared_ptr< LootBoxState > &lState, const std::shared_ptr< ActiveEntityState > &eState, bool sendToAll, bool queue=false)
Send the details of a loot box in the specified client's zone to the client specified or all clients in that zone.
bool SendPopulateZoneData (const std::shared_ptr< ChannelClientConnection > &client)
Send data about entities that exist in a zone to a new connection and update any existing connections with information about the new one.
void SendToRange (const std::shared_ptr< ChannelClientConnection > &client, libcomp::Packet &p, bool includeSelf=true)
sends a packet to a specified range
void ShowDemonToZone (const std::shared_ptr< Zone > &zone, const std::shared_ptr< ChannelClientConnection > &client)
Send a request to all clients in a zone to show a demon entity and also relay any zone-in information to the source client.
void ShowEntity (const std::shared_ptr< ChannelClientConnection > &client, int32_t entityID, bool queue=false)
Send a request to a client to show an entity.
void ShowEntity (const std::list< std::shared_ptr< ChannelClientConnection >> &clients, int32_t entityID, bool queue=false)
Send a request to a list of client to show an entity.
void ShowEntityToZone (const std::shared_ptr< Zone > &zone, int32_t entityID)
Send a request to all clients in a zone to show an entity.
void ShowNPC (const std::shared_ptr< Zone > &zone, const std::list< std::shared_ptr< ChannelClientConnection >> &clients, const std::shared_ptr< NPCState > &npcState, bool queue=false)
Send data about the supplied NPC to the zone or supplied clients.
void ShowObject (const std::shared_ptr< Zone > &zone, const std::list< std::shared_ptr< ChannelClientConnection >> &clients, const std::shared_ptr< ServerObjectState > &objState, bool queue=false)
Send data about the supplied object NPC to the zone or supplied clients.
bool SpawnEnemy (const std::shared_ptr< Zone > &zone, uint32_t demonID, float x, float y, float rot, const libcomp::String &aiType="")
Spawn an enemy in the specified zone at set coordinates.
bool StartInstanceTimer (const std::shared_ptr< ZoneInstance > &instance)
Start the timer currently assigned to the supplied zone instance.
bool StartZoneEvent (const std::shared_ptr< Zone > &zone, const libcomp::String &eventID)
Start an event contextual to the supplied zone with no source entity.
bool StopInstanceTimer (const std::shared_ptr< ZoneInstance > &instance, uint64_t stopTime=false)
Stop the timer currently assigned to the supplied zone instance.
void SyncInstanceAccess (std::list< std::shared_ptr< objects::InstanceAccess >> updates, std::list< std::shared_ptr< objects::InstanceAccess >> removes)
Sync updates and removals to InstanceAccess definitions that belong to this server or any other one.
bool TriggerZoneActions (const std::shared_ptr< Zone > &zone, std::list< std::shared_ptr< ActiveEntityState >> entities, ZoneTrigger_t trigger, const std::shared_ptr< ChannelClientConnection > &client=nullptr)
Trigger specific zone actions for the specified zone for a set of source entities.
void UpdateActiveZoneStates ()
Updates the current states of entities in the zone.
void UpdateDeathTimeOut (ClientState *state, int32_t time, const std::shared_ptr< ChannelClientConnection > &client=nullptr)
Update the death time-out associated to the client and handle scheduling expiration and communication to the players.
bool UpdateDestinyBox (const std::shared_ptr< ZoneInstance > &instance, int32_t worldCID, const std::list< std::shared_ptr< objects::Loot >> &add, std::set< uint8_t > remove={})
Update the loot assigned to the destiny box assigned to a specific world CID.
bool UpdateGeometryElement (const std::shared_ptr< Zone > &zone, std::shared_ptr< objects::ServerObject > elemObject)
Update zone geometry information bound to a server object in the supplied zone.
bool UpdatePlasma (const std::shared_ptr< Zone > &zone, uint64_t now=0)
Update the specified zone's PlasmaSpawns.
bool UpdateSpawnGroups (const std::shared_ptr< Zone > &zone, bool refreshAll, uint64_t now=0, std::shared_ptr< objects::ActionSpawn > actionSource=nullptr)
Update the specified zone's spawns from SpawnLocationGroups or SpawnGroups directly updated at specific spots.
bool UpdateStaggeredSpawns (const std::shared_ptr< Zone > &zone, uint64_t now)
Update the specified zone's staggered spawns, showing them to the zone if any are ready.
void UpdateStatusEffectStates (const std::shared_ptr< Zone > &zone, uint32_t now, const std::list< std::shared_ptr< ActiveEntityState >> &entities)
Update the state of status effects in the supplied zone, adding and updating existing effects, expiring old effects and applying T-damage and regen to entities with applicable effects.
bool UpdateTrackedTeam (const std::shared_ptr< objects::Team > &team, const std::shared_ptr< Zone > &zone=nullptr)
Update any team specific entity tracking/state information.
bool UpdateTrackedZone (const std::shared_ptr< Zone > &zone, const std::shared_ptr< objects::Team > &team=nullptr)
Update any zone specific entity tracking/state information and if the zone is marked for tracking and fall back to team tracking only if the whole zone should not be tracked.
void Warp (const std::shared_ptr< ChannelClientConnection > &client, const std::shared_ptr< ActiveEntityState > &eState, float xPos, float yPos, float rot)
Warp an entity to the specified location immediately.
Static Public Member Functions
static std::list
< std::shared_ptr
< ActiveEntityState > > GetEntitiesInFoV (const std::list< std::shared_ptr< ActiveEntityState >> &entities, float x, float y, float rot, float maxAngle, bool useHitbox=false)
Filter the list of supplied entities to only those visible in the specified field of view.
static float GetPointToLineDistance (const Line &line, const Point &point)
Determine the shortest distance from a point to a line segment.
static float GetRandomRotation ()
Get a random rotation value (in radians)
static bool PointInPolygon (const Point &p, const std::list< Point > vertices, float overlapRadius=0.f)
Determine if the specified point is within a polygon defined by vertices.
static Point RotatePoint (const Point &p, const Point &origin, float radians)
Rotate a point around an origin point by the specified radians amount.
Private Member Functions
void AddDiasporaBases (const std::shared_ptr< Zone > &zone)
All all Diaspora bases defined in a zone from the variant.
void AddPvPBases (const std::shared_ptr< Zone > &zone, const std::shared_ptr< objects::PvPInstanceVariant > &variant)
All all PvP bases defined in a zone from the variant.
bool CanEnterRestrictedZone (const std::shared_ptr< ChannelClientConnection > &client, const std::shared_ptr< Zone > &zone)
Determine if the suppplied client has access to enter a restricted zone.
std::shared_ptr
< ActiveEntityState > CreateEnemy (const std::shared_ptr< Zone > &zone, uint32_t demonID, const std::shared_ptr< objects::Spawn > &spawn, float x, float y, float rot, bool asAlly=false)
Create an enemy (or ally) in the specified zone at set coordinates but do not add it to the zone yet.
std::shared_ptr< Zone > CreateZone (const std::shared_ptr< objects::ServerZone > &definition, const std::shared_ptr< ZoneInstance > &instance=nullptr)
Create a new zone based off of the supplied definition.
std::list< uint32_t > GetShortestPath (const std::shared_ptr< ZoneGeometry > &geometry, uint32_t sourceID, uint32_t destID)
Calculate the shortest path between the supplied source and destination Qmp points in the same zone geometry.
std::list< WorldClockTime > GetTriggerTimes (const std::list< std::shared_ptr< objects::ServerZoneTrigger >> &triggers)
Gather all world clock representations of the supplied time triggers.
std::shared_ptr< Zone > GetZone (uint32_t zoneID, uint32_t dynamicMapID, const std::shared_ptr< ChannelClientConnection > &client, uint32_t currentInstanceID=0)
Get a zone by zone definition ID.
void HandleDespawns (const std::shared_ptr< Zone > &zone)
Perform all necessary despawns for the supplied zone.
void HandleSpecialInstancePopulate (const std::shared_ptr< ChannelClientConnection > &client, const std::shared_ptr< Zone > &zone)
Handle all instance specific zone population actions such as entity hiding and timer updating.
bool IsGeometryDisabled (const std::shared_ptr< objects::ServerObject > &obj)
Determine if the server object supplied is in a state that would disabled geometry collision.
bool MoveToZoneChannel (const std::shared_ptr< ChannelClientConnection > &client, uint32_t zoneID, uint32_t dynamicMapID, const std::shared_ptr< objects::InstanceAccess > &toInstance, float x=0.f, float y=0.f, float rot=0.f)
Move the supplied client from the current channel to another based upon the zone being moved to.
bool RegisterTimeRestrictions (const std::shared_ptr< Zone > &zone, const std::shared_ptr< objects::ServerZone > &definition)
Register time restricted actions for a zone with the manager such as time conditional spawn groups or plasma.
bool RemoveInstance (uint32_t instanceID)
Remove a zone instance by unique ID if no characters have access and no characters are currently in any zone.
void RemoveZone (const std::shared_ptr< Zone > &zone, bool freezeOnly)
Remove and clean up all zone information for a specific zone.
void ScheduleInstanceAccessTimeOut (const std::shared_ptr< ZoneInstance > &instance)
Schedule instance access time-out and remove the instance if no player accesses it before then.
void ScheduleTimerExpiration (const std::shared_ptr< ZoneInstance > &instance)
Schedule the expiration of a zone instance timer.
bool SelectSpotAndLocation (bool useSpotID, uint32_t &spotID, const std::set< uint32_t > &spotIDs, std::shared_ptr< channel::ZoneSpotShape > &spot, std::shared_ptr< objects::SpawnLocation > &location, std::shared_ptr< DynamicMap > &dynamicMap, std::shared_ptr< objects::ServerZone > &zoneDef, std::list< std::shared_ptr< objects::SpawnLocation >> &locations)
Select a spot for a spawn group and get it's location.
void SendAccessMessage (const std::shared_ptr< objects::InstanceAccess > &access, bool joined, const std::shared_ptr< ChannelClientConnection > &client=nullptr)
Send InstanceAccess create or join messages to either one player or all players that have access to it.
void SendAllyData (const std::shared_ptr< AllyState > &allyState, const std::shared_ptr< ChannelClientConnection > &client, const std::shared_ptr< Zone > &zone, bool queue=false)
Send entity information about an ally in a zone.
void SendEnemyData (const std::shared_ptr< EnemyState > &enemyState, const std::shared_ptr< ChannelClientConnection > &client, const std::shared_ptr< Zone > &zone, bool queue=false)
Send entity information about an enemy in a zone.
void SendMultiZoneBossStatus (uint32_t groupID)
Send the current multi-zone boss statuses in the supplied group.
void UpdateStatusEffectStates (const std::shared_ptr< Zone > &zone, uint32_t now)
Update the state of status effects in the supplied zone, adding and updating existing effects, expiring old effects and applying T-damage and regen to entities with applicable effects.
bool ValidateBossGroup (const std::shared_ptr< EnemyState > &enemyState)
Determine if the supplied boss EnemyState is valid to add to a multi-zone boss group.
Private Attributes
std::set< uint32_t > mActiveTrackedZones
Set of IDs for all zones that are both active and configured for team, full zone or boss tracking.
std::set< uint32_t > mActiveZones
Set of all zones that should be considered active when updating states.
std::set< uint32_t > mAllTimeRestrictZones
Set of all zone IDs with at least one time restricted action bound to them.
std::unordered_map< uint32_t,
std::shared_ptr< DynamicMap > > mDynamicMaps
Map of dynamic map IDs to geometry information built from their corresponding binary definitions.
std::unordered_map< int32_t,
uint32_t > mEntityMap
Map of world CIDs to zone unique IDs.
std::unordered_map< uint32_t,
std::set< uint32_t > > mGlobalBossZones
Map of global boss group IDs to zones in that group on the server.
std::list< std::shared_ptr
< objects::ServerZoneTrigger > > mGlobalTimeTriggers
List of zone-detached global time triggers that fire independent of any zone.
std::unordered_map< uint32_t,
std::unordered_map< uint32_t,
uint32_t > > mGlobalZoneMap
Map of global zone definition IDs to map of zone unique IDs by dynamic map ID.
libcomp::Mutex mInstanceZoneLock
Server lock for creating or getting existing zones in an instance.
libcomp::Mutex mLock
Server lock for shared resources.
uint32_t mNextZoneID
Next available zone unique ID.
uint32_t mNextZoneInstanceID
Next available zone instance unique ID.
std::weak_ptr< ChannelServer > mServer
Pointer to the channel server.
std::map< WorldClockTime,
std::set< uint32_t > > mSpawnTimeRestrictZones
Map of times bound to zone IDs to register with the world for world time triggering.
std::set< uint32_t > mTimeRestrictUpdatedZones
Set of all zone IDs, active or not, that have had a time restricted update performed on them.
ServerTime mTrackingRefresh
Next server time that tracked zones will be refreshed during.
std::unordered_map
< std::string, std::shared_ptr
< ZoneGeometry > > mZoneGeometry
Map of QMP filenames to the geometry structures built from them.
std::unordered_map< int32_t,
std::shared_ptr
< objects::InstanceAccess > > mZoneInstanceAccess
Map of world CIDs to the zone instance access definitions.
std::unordered_map< uint32_t,
std::shared_ptr< ZoneInstance > > mZoneInstances
Map of zone instances by unique ID.
std::unordered_map< uint32_t,
std::shared_ptr< Zone > > mZones
Map of zones by unique ID.
Detailed Description
Manager to handle zone focused actions.
Definition at line 67 of file ZoneManager.h.
Constructor & Destructor Documentation
ZoneManager::ZoneManager (const std::weak_ptr< ChannelServer > & server)
Create a new ZoneManager.
Parameters
server Pointer back to the channel server this belongs to
Definition at line 157 of file ZoneManager.cpp.
ZoneManager::~ZoneManager ()
Clean up the ZoneManager.
Definition at line 163 of file ZoneManager.cpp.
References mZones.
Member Function Documentation
void ZoneManager::AddDiasporaBases (const std::shared_ptr< Zone > & zone) private
All all Diaspora bases defined in a zone from the variant.
Parameters
zone Pointer to the zone
Definition at line 8332 of file ZoneManager.cpp.
References libcomp::String::Arg(), GetSpotPosition(), and mServer.
Referenced by CreateZone().
bool ZoneManager::AddEnemiesToZone (const std::list< std::shared_ptr< ActiveEntityState >> & eStates, const std::shared_ptr< Zone > & zone, bool staggerSpawn, bool asEncounter, const std::list< std::shared_ptr< objects::Action >> & defeatActions)
Add enemies (or allies) already created in the zone, prepare AI and fire spawn triggers.
Spawns can optionally be staggered and/or created as a single encounter that will fire the supplied action source actions when defeated.
Parameters
eStates Pointer to enemy or ally states to add to the zone
zone Pointer to the zone where the entities should be added
staggerSpawn If true the spawns will be staggered as they appear, if false they will all appear at once
asEncounter If true the enemies will be created as an encounter and the supplied defeatActions will fire when the last one is defeated, if false they will be normal spawns
defeatActions List of defeat actions to fire when the enemies are killed, should the be spawned in as an encounter
Returns
true if the enemies were added successfully, false if an error occurred
Definition at line 3315 of file ZoneManager.cpp.
References libcomp::String::Arg(), channel::ChannelServer::GetServerTime(), mActiveZones, mServer, SendAllyData(), SendEnemyData(), and TriggerZoneActions().
Referenced by AddEnemiesToZone(), and UpdateSpawnGroups().
bool ZoneManager::AddEnemiesToZone (std::list< std::shared_ptr< ActiveEntityState >> eStates, const std::shared_ptr< Zone > & zone, bool staggerSpawn, bool asEncounter, const libcomp::String & defeatEventID)
Add enemies (or allies) already created in the zone, prepare AI and fire spawn triggers.
Spawns can optionally be staggered and/or created as a single encounter that will fire the supplied action source actions when defeated.
Parameters
eStates Pointer to enemy or ally states to add to the zone
zone Pointer to the zone where the entities should be added
staggerSpawn If true the spawns will be staggered as they appear, if false they will all appear at once
asEncounter If true the enemies will be created as an encounter and the supplied defeatEventID will fire when the last one is defeated, if false they will be normal spawns
defeatEventID Event ID to fire from an action when the encounter is defeated
Returns
true if the enemies were added successfully, false if an error occurred
Definition at line 3451 of file ZoneManager.cpp.
References AddEnemiesToZone(), libcomp::String::Arg(), and libcomp::String::IsEmpty().
void ZoneManager::AddPvPBases (const std::shared_ptr< Zone > & zone, const std::shared_ptr< objects::PvPInstanceVariant > & variant) private
All all PvP bases defined in a zone from the variant.
Parameters
zone Pointer to the zone
variant Pointer to the PvP instance variant
Definition at line 8188 of file ZoneManager.cpp.
References libcomp::String::Arg(), libcomp::Randomizer::GetEntry(), GetSpotPosition(), mServer, and RNG.
Referenced by CreateZone().
void ZoneManager::BroadcastPacket (const std::shared_ptr< ChannelClientConnection > & client, libcomp::Packet & p, bool includeSelf = true)
Send a packet to every connection in the zone or all but the client specified.
Parameters
client Client connection to use as the "source" connection
p Packet to send to the zone
includeSelf Optional parameter to include the connection being passed in when sending the packets. Defaults to true
Definition at line 3093 of file ZoneManager.cpp.
References GetZoneConnections().
Referenced by FailPlasma(), SendBazaarMarketData(), SendCultureMachineData(), SendMultiZoneBossStatus(), UpdateDeathTimeOut(), and UpdatePlasma().
void ZoneManager::BroadcastPacket (const std::shared_ptr< Zone > & zone, libcomp::Packet & p)
Send a packet to every connection in the specified zone.
Parameters
zone Pointer to the zone to send the packet to
p Packet to send to the zone
Definition at line 3105 of file ZoneManager.cpp.
bool ZoneManager::CanEnterRestrictedZone (const std::shared_ptr< ChannelClientConnection > & client, const std::shared_ptr< Zone > & zone) private
Determine if the suppplied client has access to enter a restricted zone.
Parameters
client Pointer to the client attempting to enter the zone
zone Pointer to the restricted zone
Definition at line 8441 of file ZoneManager.cpp.
References channel::ClientState::GetWorldCID(), and channel::state().
Referenced by EnterZone().
Point ZoneManager::CollisionAdjust (const Point & src, const Point & collidePoint)
Adjust a destination point based on a source point and the point where it collides with the nearest zone geometry point.
Parameters
src Source point
collidePoint Point where the path collides with geometry
Returns
Adjusted linear destination point
Definition at line 6878 of file ZoneManager.cpp.
References GetLinearPoint(), channel::Point::x, and channel::Point::y.
Referenced by CorrectClientPosition(), GetLinearPoint(), and GetRandomSpotPoint().
bool ZoneManager::CorrectClientPosition (const std::shared_ptr< ActiveEntityState > & eState, Point & dest)
Correct a client supplied entity position to ensure it does not move out of bounds.
No communication to the client takes place within.
Parameters
eState Pointer to the entity state
dest Destination point
Returns
true if the destination was corrected and should be communicated to the client
Definition at line 6743 of file ZoneManager.cpp.
uint8_t ZoneManager::CorrectClientPosition (const std::shared_ptr< ActiveEntityState > & eState, Point & src, Point & dest, ServerTime & startTime, ServerTime & stopTime, bool isMove = false)
Correct a client supplied entity position to ensure it does not move out of bounds.
No communication to the client takes place within.
Parameters
eState Pointer to the entity state
src Source movement point (ignored if not moving)
dest Destination point
startTime Server time representing when the position is starting to change (ignore if not moving)
stopTime Server time representing when the position is ending
isMove Designates if the entity is moving or not
Returns
0 if no change of note took place, 1 if the movement was rolled back, 2 if only the end point was corrected
Definition at line 6752 of file ZoneManager.cpp.
References CollisionAdjust(), channel::Point::GetDistance(), GetLinearPoint(), GetPointToLineDistance(), channel::Point::x, and channel::Point::y.
std::shared_ptr< ActiveEntityState > ZoneManager::CreateAlly (const std::shared_ptr< Zone > & zone, uint32_t demonID, uint32_t spotID, float x, float y, float rot)
Create an ally in the specified zone at set coordinates but do not add it to the zone yet.
Parameters
zone Pointer to the zone where the entity should be spawned
demonID Demon/enemy type ID to spawn
spotID Optional spot ID to add the enemy to
x X coordinate to render the ally at
y Y coordinate to render the ally at
rot Rotation to render the ally with
Returns
Pointer to the new ActiveEntityState
Definition at line 3208 of file ZoneManager.cpp.
References libcomp::String::Arg(), CreateEnemy(), GetRandomSpotPoint(), mServer, channel::Point::x, and channel::Point::y.
std::shared_ptr< ActiveEntityState > ZoneManager::CreateEnemy (const std::shared_ptr< Zone > & zone, uint32_t demonID, uint32_t spawnID, uint32_t spotID, float x, float y, float rot)
Create an enemy (or ally) in the specified zone at set coordinates but do not add it to the zone yet.
Parameters
zone Pointer to the zone where the entity should be spawned
demonID Demon/enemy type ID to spawn
spawnID Optional zone definition spawn ID
spotID Optional spot ID to add the enemy to
x X coordinate to render the enemy at
y Y coordinate to render the enemy at
rot Rotation to render the enemy with
Returns
Pointer to the new ActiveEntityState
Definition at line 3254 of file ZoneManager.cpp.
References libcomp::String::Arg(), GetRandomSpotPoint(), mServer, channel::Point::x, and channel::Point::y.
Referenced by CreateAlly(), SpawnEnemy(), and UpdateSpawnGroups().
std::shared_ptr< ActiveEntityState > ZoneManager::CreateEnemy (const std::shared_ptr< Zone > & zone, uint32_t demonID, const std::shared_ptr< objects::Spawn > & spawn, float x, float y, float rot, bool asAlly = false) private
Create an enemy (or ally) in the specified zone at set coordinates but do not add it to the zone yet.
Parameters
zone Pointer to the zone where the entity should be spawned
demonID Demon/enemy type ID to spawn
spawn Optional pointer to the entity's spawn definition
x X coordinate to render the enemy at
y Y coordinate to render the enemy at
rot Rotation to render the enemy with
asAlly Optional override to create an ally regardless of spawn category, defaults to false
Returns
Pointer to the new ActiveEntityState
Definition at line 4446 of file ZoneManager.cpp.
References libcomp::String::Arg(), mServer, and channel::state().
uint8_t ZoneManager::CreateInstance (const std::shared_ptr< objects::InstanceAccess > & access)
Create a zone instance with access granted for the supplied CIDs.
Parameters
access Pointer to the access definition
Returns
0 if it failed to create, 1 if it created local, 2 if a request was sent to the world to create the instance
Definition at line 1343 of file ZoneManager.cpp.
References libcomp::String::Arg(), mLock, mNextZoneInstanceID, mServer, mZoneInstanceAccess, mZoneInstances, ScheduleInstanceAccessTimeOut(), and SendAccessMessage().
std::shared_ptr< Zone > ZoneManager::CreateZone (const std::shared_ptr< objects::ServerZone > & definition, const std::shared_ptr< ZoneInstance > & instance = nullptr) private
Create a new zone based off of the supplied definition.
Parameters
definition Pointer to a zone definition
instance Optional pointer to the instance the zone will belong to
Returns
Pointer to a new zone
Definition at line 7776 of file ZoneManager.cpp.
References AddDiasporaBases(), AddPvPBases(), libcomp::String::Arg(), ExpireRentals(), GetSpotPosition(), IsGeometryDisabled(), mDynamicMaps, mLock, mNextZoneID, mServer, mZoneGeometry, mZones, RegisterTimeRestrictions(), channel::state(), UpdateGeometryElement(), UpdatePlasma(), and UpdateSpawnGroups().
Referenced by GetInstanceZone(), and InstanceGlobalZones().
void ZoneManager::EndInstanceTimer (const std::shared_ptr< ZoneInstance > & instance, const std::shared_ptr< ChannelClientConnection > & client, bool isSuccess, bool queue = false)
End the timer currently assigned to the supplied zone instance for a specific client and contextually process anything that should occur upon this action happening.
Both successes and failures are handled based upon actions like timer stop, timer expiration and zone change while the timer is still active.
Parameters
instance Pointer to a zone instance
client Pointer to the client the timer is ending for
isSuccess true if the reason the timer is being ended should be considered a success state
queue Optional parameter to queue the packets being sent
Definition at line 5727 of file ZoneManager.cpp.
References channel::ChannelClientConnection::BroadcastPacket(), libcomp::Convert::ENCODING_CP932, channel::ClientState::GetAccountUID(), channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), channel::ClientState::GetZone(), mServer, PACKET_DUNGEON_RECORDS_UPDATE, SendInstanceTimer(), channel::state(), channel::ClientState::ToClientTime(), UpdateDeathTimeOut(), libcomp::Packet::WriteFloat(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS8(), libcomp::Packet::WriteString16Little(), libcomp::Packet::WriteU32Little(), and libcomp::Packet::WriteU8().
Referenced by EnterZone(), HandleDeathTimeOut(), and StopInstanceTimer().
bool ZoneManager::EnterZone (const std::shared_ptr< ChannelClientConnection > & client, uint32_t zoneID, uint32_t dynamicMapID)
Perform all zone entry setup and related actions for a player associated to the supplied client using the default starting point.
Parameters
client Client connection for the player entering the zone
zoneID Definition ID of a zone to add the client to
dynamicMapID Dynamic Map ID of the zone to add the client to. if specified as 0, the first instance of the zone will be used
Returns
true if the player entered the zone properly, false if they did not
Definition at line 433 of file ZoneManager.cpp.
References mServer.
Referenced by HandleDeathTimeOut(), MoveToInstance(), MoveToLobby(), and StopInstanceTimer().
bool ZoneManager::EnterZone (const std::shared_ptr< ChannelClientConnection > & client, uint32_t zoneID, uint32_t dynamicMapID, float xCoord, float yCoord, float rotation, bool forceLeave = false)
Perform all zone entry setup and related actions for a player associated to the supplied client using an explicit entry point.
Parameters
client Client connection for the player entering the zone
zoneID Definition ID of a zone to add the client to
dynamicMapID Dynamic Map ID of the zone to add the client to. if specified as 0, the first instance of the zone will be used
xCoord X-coordinate to send character to.
yCoord Y-coordinate to send character to.
rotation Character rotation upon entering the zone.
forceLeave Optional param that when set to true will force a call to LeaveZone even if the zone they are moving to is the same
Returns
true if the player entered the zone properly, false if they did not
Definition at line 447 of file ZoneManager.cpp.
References libcomp::String::Arg(), CanEnterRestrictedZone(), EndInstanceTimer(), channel::ClientState::GetAccountUID(), channel::ClientState::GetCharacterState(), channel::ActiveEntityState::GetCoreStats(), channel::ClientState::GetDemonState(), GetInstanceAccess(), channel::ChannelServer::GetServerTime(), channel::CharacterManager::GetTDamagePacket(), channel::ClientState::GetWorldCID(), GetZone(), GetZoneTriggers(), LeaveZone(), mActiveTrackedZones, mActiveZones, mEntityMap, mLock, MoveToZoneChannel(), mServer, mTrackingRefresh, mZoneInstanceAccess, PointInPolygon(), SendAccessMessage(), StartInstanceTimer(), channel::state(), STATUS_IGNORE, SVR_CONST, TriggerZoneActions(), UpdateTrackedTeam(), libcomp::Packet::WriteFloat(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS8(), libcomp::Packet::WriteU32Little(), and libcomp::Packet::WriteU8().
void ZoneManager::ExpireInstance (uint32_t instanceID, uint64_t timeOut)
Expire and remove an instance matching the supplied values.
Parameters
instanceID ID of the instance to expire
timeOut Disconnect time out to check on the instance to make sure no one has reconnected
Definition at line 1547 of file ZoneManager.cpp.
References GetInstance(), and RemoveInstance().
Referenced by ScheduleInstanceAccessTimeOut().
void ZoneManager::ExpireRentals (const std::shared_ptr< Zone > & zone)
Expire and inactivate bazaar markets and culture machines that are no longer active in the specified zone.
Parameters
zone Pointer to a zone
Definition at line 2443 of file ZoneManager.cpp.
References libcomp::String::Arg(), libcomp::DatabaseChangeSet::Create(), ExpireRentals(), channel::ChannelServer::GetServerTime(), libcomp::PersistentObject::LoadObjectByUUID(), mServer, SendBazaarMarketData(), SendCultureMachineData(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteString16Little(), and libcomp::Packet::WriteU8().
Referenced by CreateZone(), and ExpireRentals().
bool ZoneManager::ExtendInstanceTimer (const std::shared_ptr< ZoneInstance > & instance, uint32_t seconds)
Extend the timer currently assigned to the supplied zone instance.
Only certain variants are valid. If the timer is successfully extended, the already assigned expiration event ID will be used
Parameters
instance Pointer to a zone instance
seconds Number of seconds the timer will be extended by
Returns
false if an error occurred
Definition at line 5054 of file ZoneManager.cpp.
References ScheduleTimerExpiration(), and SendInstanceTimer().
void ZoneManager::FailPlasma (const std::shared_ptr< ChannelClientConnection > & client, int32_t plasmaID, int8_t pointID = 0)
Fail the supplied client's current plasma minigame.
Parameters
client Pointer to the client connection
plasmaID Entity ID of the plasma currently being accessed
pointID Optional specifier of the point being accessed. If not specified, the current one will be found.
Definition at line 4282 of file ZoneManager.cpp.
References BroadcastPacket(), libcomp::Packet::Clear(), channel::ClientState::GetWorldCID(), channel::ClientState::GetZone(), mServer, channel::PlasmaState::SetPickResult(), channel::state(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteS8().
void ZoneManager::FixCurrentPosition (const std::shared_ptr< ActiveEntityState > & eState, uint64_t fixUntil, uint64_t now = 0)
Stop and fix an entity at their current position for the specified amount of time.
Parameters
eState Pointer to the entity to stop
fixUntil Server timestamp of when the entity can move again
now Current server time
Definition at line 2253 of file ZoneManager.cpp.
References channel::ChannelServer::GetServerTime(), channel::ChannelClientConnection::SendRelativeTimePacket(), libcomp::Packet::Size(), libcomp::Packet::WriteFloat(), libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteS32Little().
std::shared_ptr< Zone > ZoneManager::GetCurrentZone (const std::shared_ptr< ChannelClientConnection > & client)
Get the zone associated to a client connection.
Parameters
client Client connection connected to a zone
Returns
Pointer to a zone
Definition at line 383 of file ZoneManager.cpp.
Referenced by SendLootBoxData(), and SendPopulateZoneData().
std::shared_ptr< Zone > ZoneManager::GetCurrentZone (int32_t worldCID)
Get the zone associated to a character entity ID.
Parameters
worldCID World CID of the character associated to a client connection
Returns
Pointer to a zone
Definition at line 390 of file ZoneManager.cpp.
References mEntityMap, mLock, and mZones.
std::list< std::shared_ptr< ActiveEntityState > > ZoneManager::GetEntitiesInFoV (const std::list< std::shared_ptr< ActiveEntityState >> & entities, float x, float y, float rot, float maxAngle, bool useHitbox = false) static
Filter the list of supplied entities to only those visible in the specified field of view.
Parameters
entities List of entities to filter to visible only
x X coordinate of the FoV origin
y Y coordinate of the FoV origin
rot Rotation in radians for the center of the FoV
maxAngle Maximum angle in radians for either side of the FoV
useHitbox If true, the entities' hitboxes will be used to determine if they are in the FoV, even if the center point is not
Returns
Filtered list of entities visible
Definition at line 7265 of file ZoneManager.cpp.
References channel::ActiveEntityState::CorrectRotation(), RotatePoint(), channel::Point::x, and channel::Point::y.
Referenced by channel::SkillManager::ProcessSkillResult(), and channel::AIManager::Retarget().
std::shared_ptr< Zone > ZoneManager::GetExistingZone (uint32_t zoneID, uint32_t dynamicMapID, uint32_t instanceID = 0)
Get a zone by definition ID, dynamic map ID and (optionally) instance ID.
Parameters
zoneID Definition ID of a zone to retrieve
dynamicMapID Dynamic Map ID of the zone to retrieve
instanceID Instance ID of a zone to retrieve
Returns
Pointer to the zone associated to the supplied IDs
Definition at line 408 of file ZoneManager.cpp.
References GetInstance(), mGlobalZoneMap, mLock, and mZones.
Referenced by GetGlobalZone().
std::shared_ptr< Zone > ZoneManager::GetGlobalZone (uint32_t zoneID, uint32_t dynamicMapID)
Get a zone by definition ID and dynamic map ID.
Parameters
zoneID Definition ID of a zone to retrieve
dynamicMapID Dynamic Map ID of the zone to retrieve
Returns
Pointer to the zone associated to the supplied IDs
Definition at line 402 of file ZoneManager.cpp.
References GetExistingZone().
std::shared_ptr< ZoneInstance > ZoneManager::GetInstance (uint32_t instanceID)
Get a zone instance by ID.
Parameters
instanceID ID of the instance to retrieve
Returns
Pointer to the zone instance associated to the supplied ID
Definition at line 1557 of file ZoneManager.cpp.
References mLock, and mZoneInstances.
Referenced by ExpireInstance(), GetExistingZone(), HandleDeathTimeOut(), MoveToInstance(), ScheduleTimerExpiration(), and StopInstanceTimer().
std::shared_ptr< objects::InstanceAccess > ZoneManager::GetInstanceAccess (int32_t worldCID)
Get the zone instance access available to the supplied world CID.
Parameters
worldCID Character world CID
Returns
Pointer to the zone access, null if none exist
Definition at line 1564 of file ZoneManager.cpp.
References mLock, and mZoneInstanceAccess.
Referenced by EnterZone(), MoveToInstance(), and MoveToZoneChannel().
std::shared_ptr< Zone > ZoneManager::GetInstanceStartingZone (const std::shared_ptr< ZoneInstance > & instance)
Get or create the first zone in the supplied instance.
Parameters
instance Pointer ot the instance to get the zone from
Returns
Pointer to the zone, null if it failed to creat
Definition at line 1572 of file ZoneManager.cpp.
References GetInstanceZone().
Referenced by MoveToInstance(), and StopInstanceTimer().
std::shared_ptr< Zone > ZoneManager::GetInstanceZone (const std::shared_ptr< ZoneInstance > & instance, uint32_t zoneID, uint32_t dynamicMapID)
Get or create a zone in the supplied instance.
Useful for creating zones before anyone enters
Parameters
instance Pointer ot the instance to get the zone from
zoneID Zone definition ID to get
dynamicMapID Zone dynamic map ID to get
Returns
Pointer to the zone, null if it failed to create
Definition at line 7583 of file ZoneManager.cpp.
References libcomp::String::Arg(), CreateZone(), mInstanceZoneLock, mLock, mServer, and RemoveZone().
Referenced by GetInstanceStartingZone(), and GetZone().
Point ZoneManager::GetLinearPoint (float sourceX, float sourceY, float targetX, float targetY, float distance, bool away, const std::shared_ptr< Zone > & zone = nullptr)
Get a point directly away or directly towards two specified points.
Parameters
sourceX Point 1 X coordinate
sourceY Point 1 Y coordinate
targetX Point 2 X coordinate
targetY Point 2 Y coordinate
distance Distance to move
away true if the point calculated should be futher from the target point, false if it should be closer to it
zone Optional pointer to the zone to check against collision
Returns
X, Y coordinates at the specified point not adjusted for collisions
Definition at line 6674 of file ZoneManager.cpp.
References CollisionAdjust(), channel::Point::x, and channel::Point::y.
Referenced by CollisionAdjust(), CorrectClientPosition(), LinearReposition(), MoveRelative(), and UpdateSpawnGroups().
bool ZoneManager::GetLoginZone (const std::shared_ptr< objects::Character > & character, uint32_t & zoneID, uint32_t & dynamicMapID, int8_t & channelID, float & x, float & y, float & rot)
Get information about the correct zone and channel to log into for the supplied character.
Parameters
character Pointer to the character attempting to log in
zoneID Output parameter for the zone ID to log into
dynamicMapID Output parameter for the dynamic map ID to log into
channelID Output parameter for the channel to log into or -1 if the channel does not matter
x X coordinate for the zone login
y Y coordinate for the zone login
rot Rotation for the zone login (in radians)
Returns
true if the zone was determined correctly, false if it was not
Definition at line 7652 of file ZoneManager.cpp.
References GetSpotPosition(), mServer, and SVR_CONST.
bool ZoneManager::GetMatchStartPosition (const std::shared_ptr< ChannelClientConnection > & client, const std::shared_ptr< Zone > & zone, float & x, float & y, float & rot)
Get the coordinates of a match starting point in the supplied zone for the client.
Parameters
client Pointer to the client connection entering the match
zone Pointer to the zone the client is in
x Output parameter containing the starting position x coord
y Output parameter containing the starting position y coord
rot Output parameter containing the starting position rotation
Returns
true if the spot was found, false if it was not
Definition at line 1586 of file ZoneManager.cpp.
References libcomp::Randomizer::GetEntry(), GetRandomSpotPoint(), channel::ClientState::GetWorldCID(), channel::ClientState::GetZone(), mServer, channel::state(), channel::Point::x, and channel::Point::y.
Referenced by MoveToInstance().
float ZoneManager::GetPointToLineDistance (const Line & line, const Point & point) static
Determine the shortest distance from a point to a line segment.
Parameters
line Line segment to measure distance to
point Point to measure distance from
Returns
Shortest distance between the point and line
Definition at line 7181 of file ZoneManager.cpp.
References channel::Point::GetDistance(), channel::Point::x, and channel::Point::y.
Referenced by CorrectClientPosition(), and PointInPolygon().
Point ZoneManager::GetRandomPoint (float width, float height) const
Get a random point within the specified width and height representing a rectangular area in a zone.
Parameters
width Width of the area to generate a random point within
height Height of the area to generate a random point within
Returns
X, Y coordinates of the random point
Definition at line 6620 of file ZoneManager.cpp.
References RNG_DEC.
Referenced by GetRandomSpotPoint(), and UpdateSpawnGroups().
float ZoneManager::GetRandomRotation () static
Get a random rotation value (in radians)
Returns
Rotation value (in radians)
Definition at line 6669 of file ZoneManager.cpp.
References RNG_DEC.
Referenced by channel::AIManager::Follow(), channel::SkillManager::Spawn(), channel::SkillManager::SpawnZone(), UpdateSpawnGroups(), and channel::AIManager::Wander().
Point ZoneManager::GetRandomSpotPoint (const std::shared_ptr< objects::MiSpotData > & spot, const std::shared_ptr< objects::MiZoneData > & zoneData = nullptr)
Get a random point within the supplied zone spot.
Parameters
spot Pointer to the spot to get a random point within
zoneData Optional pointer to the zone definition that, when supplied, will force the random point chosen to be in the proper zone boundaries
Returns
X, Y coordinates of the random point
Definition at line 6626 of file ZoneManager.cpp.
References CollisionAdjust(), GetRandomPoint(), mLock, mZoneGeometry, RotatePoint(), and channel::Point::x.
Referenced by CreateAlly(), CreateEnemy(), GetMatchStartPosition(), UpdatePlasma(), and UpdateSpawnGroups().
std::list< Point > ZoneManager::GetShortestPath (const std::shared_ptr< Zone > & zone, const Point & source, const Point & dest, float maxDistance = 0.f)
Calculate the shortest path between the supplied source and destination points for the specified zone.
Parameters
zone Pointer to the zone
source Source point
dest Destination point
maxDistance Optional max distance for the path
Returns
List of the full shortest path (starting with the source and ending with the destination) or empty if no path is possible
Definition at line 6903 of file ZoneManager.cpp.
std::list< uint32_t > ZoneManager::GetShortestPath (const std::shared_ptr< ZoneGeometry > & geometry, uint32_t sourceID, uint32_t destID) private
Calculate the shortest path between the supplied source and destination Qmp points in the same zone geometry.
Path optimization between points is up to the caller to perform.
Parameters
geometry Pointer to a zone geometry definition
sourceID Source point ID
destID Destination point ID
Returns
List of the shortest path of points to move to in order
Definition at line 7073 of file ZoneManager.cpp.
bool ZoneManager::GetSpotPosition (uint32_t dynamicMapID, uint32_t spotID, float & x, float & y, float & rot) const
Get the X/Y coordinates and rotation of the center point of a spot.
Parameters
dynamicMapID Dynamic map ID of the zone containing the spot
spotID Spot ID to find the center of
x Default X position to use if the spot is not found, changes to the spot center X coordinate if found
y Default Y position to use if the spot is not found, changes to the spot center Y coordinate if found
rot Default rotation to use if the spot is not found, changes to the spot rotation if found
Returns
true if the spot was found, false it was not
Definition at line 6598 of file ZoneManager.cpp.
References mServer.
Referenced by AddDiasporaBases(), AddPvPBases(), CreateZone(), GetLoginZone(), and LeaveZone().
std::list< WorldClockTime > ZoneManager::GetTriggerTimes (const std::list< std::shared_ptr< objects::ServerZoneTrigger >> & triggers) private
Gather all world clock representations of the supplied time triggers.
Parameters
triggers List of pointers to time triggers
Returns
List of world clock representations
Definition at line 8848 of file ZoneManager.cpp.
References channel::WorldClockTime::Hour, channel::WorldClockTime::Min, channel::WorldClockTime::MoonPhase, channel::WorldClockTime::SystemHour, and channel::WorldClockTime::SystemMin.
Referenced by InstanceGlobalZones(), and RegisterTimeRestrictions().
std::shared_ptr< Zone > ZoneManager::GetZone (uint32_t zoneID, uint32_t dynamicMapID, const std::shared_ptr< ChannelClientConnection > & client, uint32_t currentInstanceID = 0) private
Get a zone by zone definition ID.
If the zone does not exist and is not a global zone, it will be created.
Parameters
zoneID Zone definition ID to get a zone for
dynamicMapID Dynamic Map ID of the zone to to get a zone for
client Pointer to the client connection to use to decide whether a new zone should be created if the zone is private
currentInstanceID Optional instance ID of the zone being moved from
Returns
Pointer to the new or existing zone
Definition at line 7484 of file ZoneManager.cpp.
References libcomp::String::Arg(), channel::ClientState::GetAccountUID(), GetInstanceZone(), mGlobalZoneMap, mLock, mServer, mZoneInstanceAccess, mZoneInstances, mZones, and channel::state().
Referenced by EnterZone().
std::list< std::shared_ptr< ChannelClientConnection > > ZoneManager::GetZoneConnections (const std::shared_ptr< ChannelClientConnection > & client, bool includeSelf = true)
Get a list of client connections in the zone.
Parameters
client Client connection to use as the "source" connection
includeSelf Optional parameter to include the connection being passed in as part of the return set. Defaults to true
Returns
List of client connections in the zone
Definition at line 3149 of file ZoneManager.cpp.
References mEntityMap, mLock, and mZones.
Referenced by BroadcastPacket(), SendPopulateZoneData(), SendToRange(), and Warp().
std::list< std::shared_ptr< objects::ServerZoneTrigger > > ZoneManager::GetZoneTriggers (const std::shared_ptr< Zone > & zone, ZoneTrigger_t trigger)
Gather zone specific triggers.
Parameters
zone Pointer to a zone
trigger Type of trigger to retrieve
Returns
List of pointers to the matching zone triggers
Definition at line 6467 of file ZoneManager.cpp.
References mServer.
Referenced by EnterZone(), and TriggerZoneActions().
void ZoneManager::HandleDeathTimeOut (const std::shared_ptr< ZoneInstance > & instance, const std::shared_ptr< ChannelClientConnection > & client, uint64_t deathTime)
Handle instance specific death time-out scheduling and processing.
Parameters
instance Pointer to a zone instance the entity is in
client Pointer to the client the death timer is active for
deathTime If supplied the death time assigned to the client will be checked and upon matching the client will be scheduled for instance removal. If not supplied, the death time assigned to the client will be used to schedule removal by calling this function again.
Definition at line 5633 of file ZoneManager.cpp.
References EndInstanceTimer(), EnterZone(), channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), GetInstance(), channel::ChannelServer::GetServerTime(), channel::ClientState::GetZone(), HandleDeathTimeOut(), mServer, and channel::state().
Referenced by HandleDeathTimeOut(), and UpdateDeathTimeOut().
void ZoneManager::HandleDespawns (const std::shared_ptr< Zone > & zone) private
Perform all necessary despawns for the supplied zone.
Parameters
zone Pointer to zone do perform despawns for
Definition at line 2747 of file ZoneManager.cpp.
References mServer, and RemoveEntitiesFromZone().
Referenced by UpdateActiveZoneStates().
void ZoneManager::HandleSpecialInstancePopulate (const std::shared_ptr< ChannelClientConnection > & client, const std::shared_ptr< Zone > & zone) private
Handle all instance specific zone population actions such as entity hiding and timer updating.
Parameters
client Pointer to the client connection entering the zone
zone Pointer to the zone the client is entering
Todo:
: determine why initial zone in VS chat is busted (along with other things if this is sent earlier)
Definition at line 2964 of file ZoneManager.cpp.
References channel::ClientState::GetCharacterState(), channel::ChannelServer::GetServerTime(), mServer, SendDestinyBox(), SendInstanceTimer(), ShowEntity(), channel::state(), SVR_CONST, libcomp::Packet::WriteFloat(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS8(), libcomp::Packet::WriteU32Little(), and libcomp::Packet::WriteU8().
Referenced by SendPopulateZoneData().
void ZoneManager::HandleTimedActions (const WorldClock & clock, const WorldClockTime & lastTrigger)
Perform time-based actions depending on the current world clock time.
Parameters
clock World clock set to the current time
lastTrigger Last time the zone time triggers were processed according to the server. Only events between this and the current clock will be executed.
Definition at line 4750 of file ZoneManager.cpp.
References libcomp::String::Arg(), channel::WorldClockTime::Hour, channel::WorldClockTime::IsSet(), mAllTimeRestrictZones, mGlobalTimeTriggers, channel::WorldClockTime::Min, mLock, channel::WorldClockTime::MoonPhase, mServer, mTimeRestrictUpdatedZones, mZones, channel::WorldClockTime::SystemHour, and channel::WorldClockTime::SystemMin.
Referenced by channel::ChannelServer::HandleClockEvents().
bool ZoneManager::HandleZoneTriggers (const std::shared_ptr< Zone > & zone, const std::list< std::shared_ptr< objects::ServerZoneTrigger >> & triggers, const std::shared_ptr< ActiveEntityState > & entity = nullptr, const std::shared_ptr< ChannelClientConnection > & client = nullptr)
Handle zone specific actions from triggers for either the entire zone or one specific entity.
Parameters
zone Pointer to a zone
triggers List of pointers to triggers from the zone
entity Optional pointer to the entity to trigger the actions for. If not specified the entire zone will be used (with no source).
client Optional pointer to the entity's client
Returns
true if at least one action trigger was fired, false if no action triggers were fired
Definition at line 6520 of file ZoneManager.cpp.
References channel::ActionOptions::AutoEventsOnly, and mServer.
Referenced by TriggerZoneActions().
void ZoneManager::InstanceGlobalZones ()
Instantiate all global zones the server is responsible for hosting.
This should be called only once, after a valid world connection has been established but before any clients connect.
Definition at line 304 of file ZoneManager.cpp.
References CreateZone(), GetTriggerTimes(), mGlobalBossZones, mGlobalTimeTriggers, mGlobalZoneMap, mLock, and mServer.
bool ZoneManager::IsGeometryDisabled (const std::shared_ptr< objects::ServerObject > & obj) private
Determine if the server object supplied is in a state that would disabled geometry collision.
Parameters
obj Pointer to a server object
Returns
true if the object is in a collision disabled state
Definition at line 8650 of file ZoneManager.cpp.
Referenced by CreateZone(), and UpdateGeometryElement().
void ZoneManager::LeaveZone (const std::shared_ptr< ChannelClientConnection > & client, bool logOut, uint32_t newZoneID = 0, uint32_t newDynamicMapID = 0)
Remove a client connection from a zone.
Parameters
client Client connection to remove from any associated zone
logOut If true, special logout actions will be performed
newZoneID ID of the next zone the client is moving to, used for retaining zone instances that are not being cleaned up
newDynamicMapID Dynamic map ID of the next zone the client is moving to
Definition at line 1006 of file ZoneManager.cpp.
References channel::ActiveEntityState::AddRemoveOpponent(), libcomp::String::Arg(), EFFECT_CANCEL_LOGOUT, EFFECT_CANCEL_ZONEOUT, channel::ClientState::GetBazaarState(), channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), channel::ChannelServer::GetServerTime(), GetSpotPosition(), channel::ClientState::GetWorldCID(), channel::ClientState::GetZone(), mActiveTrackedZones, mEntityMap, mLock, mServer, mTrackingRefresh, mZoneInstanceAccess, mZones, RemoveEntitiesFromZone(), RemoveInstance(), RemoveZone(), ScheduleInstanceAccessTimeOut(), SendBazaarMarketData(), channel::state(), TriggerZoneActions(), UpdateTrackedZone(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS8(), libcomp::Packet::WriteString16Little(), and libcomp::Packet::WriteU32Little().
Referenced by EnterZone(), and MoveToZoneChannel().
bool ZoneManager::LinearReposition (const std::shared_ptr< ActiveEntityState > & eState, float x, float y)
Move the supplied entity from its current position to the supplied x/y coordinates in their current zone.
If any collision is hit, the entity will be placed at the collision point. No movement for this entity will be communicated to the client so this is primarily useful in repositioning entities not yet in the zone.
Parameters
eState Pointer to the entity to reposition
x New X coordinate
y New Y coordinate
Returns
false if the entity hit a collision in the zone or could not be moved at all
Definition at line 3498 of file ZoneManager.cpp.
References GetLinearPoint(), channel::Point::x, and channel::Point::y.
void ZoneManager::LoadGeometry ()
Load all QMP zone geometry files and prepare them to be bound to zones as they are instantiated.
If a specific file fails to load, an error will be returned but the zone will still be accessible without server side collision support.
Definition at line 171 of file ZoneManager.cpp.
References channel::ZoneGeometryLoader::LoadQMP(), mDynamicMaps, mServer, mZoneGeometry, RotatePoint(), and channel::Point::x.
Point ZoneManager::MoveRelative (const std::shared_ptr< ActiveEntityState > & eState, float targetX, float targetY, float distance, bool away, uint64_t now, uint64_t endTime)
Set an entity's destination position at a distace directly away or directly towards the specified point.
Communicating that the move has taken place must be done elsewhere.
Parameters
eState Pointer to the entity state
targetX X coordinate to move relative to
targetY Y coordinate to move relative to
distance Distance to move
away true if the entity should move away from the point, false if it should move toward it
now Server time to use as the origin ticks
endTime Server time to use as the destination ticks
Returns
Point the entity will move to
Definition at line 6719 of file ZoneManager.cpp.
References GetLinearPoint().
bool ZoneManager::MoveToInstance (const std::shared_ptr< ChannelClientConnection > & client, std::shared_ptr< objects::InstanceAccess > access = nullptr, bool diasporaEnter = false)
Move the supplied client to the starting zone of the instance they are entering.
Parameters
client Pointer to the client connection entering the instance
access Pointer to the access definition, will be loaded from the client if not specified
diasporaEnter Optional indicator required to be set if the client is entering a Diaspora instance as it's entrance criteria is unique
Returns
true if the move was successful, false if it was not
Definition at line 1730 of file ZoneManager.cpp.
References libcomp::String::Arg(), EnterZone(), channel::ClientState::GetCharacterState(), GetInstance(), GetInstanceAccess(), GetInstanceStartingZone(), GetMatchStartPosition(), channel::ClientState::GetWorldCID(), channel::ClientState::GetZone(), MoveToZoneChannel(), mServer, and channel::state().
bool ZoneManager::MoveToLobby (const std::shared_ptr< ChannelClientConnection > & client)
Move the supplied client to the lobby zone of the zone they are currently in.
Parameters
client Pointer to the client connection to move
Returns
true if the move was successful, false if it was not
Definition at line 1822 of file ZoneManager.cpp.
References EnterZone(), channel::ClientState::GetZone(), mServer, and channel::state().
bool ZoneManager::MoveToZoneChannel (const std::shared_ptr< ChannelClientConnection > & client, uint32_t zoneID, uint32_t dynamicMapID, const std::shared_ptr< objects::InstanceAccess > & toInstance, float x = 0.f, float y = 0.f, float rot = 0.f) private
Move the supplied client from the current channel to another based upon the zone being moved to.
This will cause the client to log out upon success.
Parameters
client Pointer to the client connection
zoneID ID of the zone being entered
dynamicMapID ID of the dynamic map being entered
toInstance If supplied, the zone and dynamic map belong to an instance and the access should be used
x X coordinate to use in the new zone, ignored for instances
y Y coordinate to use in the new zone, ignored for instances
rot Rotation to use in the new zone (in radians), ignored for instances
Returns
true if the client was moved, false if they either didn't need to move or the move failed
Definition at line 4061 of file ZoneManager.cpp.
References libcomp::String::Arg(), channel::ClientState::GetAccountUID(), channel::ClientState::GetCharacterState(), GetInstanceAccess(), channel::ClientState::GetWorldCID(), channel::ClientState::GetZone(), LeaveZone(), mServer, SendAccessMessage(), channel::state(), libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteS8().
Referenced by EnterZone(), and MoveToInstance().
void ZoneManager::MultiZoneBossKilled (const std::shared_ptr< Zone > & zone, ClientState * sourceState, const std::list< uint32_t > & types)
Perform any updates related to multi-zone bosses being killed.
Parameters
zone Pointer to the zone the bosses were killed in
sourceState Pointer to the state of the player that killed the bosses
types List of enemy types for the bosses that
Definition at line 6360 of file ZoneManager.cpp.
References channel::ChannelClientConnection::BroadcastPacket(), channel::ClientState::GetCharacterState(), mGlobalBossZones, mLock, mZones, SendMultiZoneBossStatus(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteString16Little(), and libcomp::Packet::WriteU32Little().
bool ZoneManager::PointInPolygon (const Point & p, const std::list< Point > vertices, float overlapRadius = 0.f) static
Determine if the specified point is within a polygon defined by vertices.
Parameters
p Point to check
vertices List of points representing a polygon's vertices
overlapRadius Optional modifier to handle the point as a circle using this value as the radius and checking if it overlaps anywhere
Returns
true if the point is within the polygon, false if it is not
Definition at line 7208 of file ZoneManager.cpp.
References channel::Point::GetDistance(), GetPointToLineDistance(), channel::Point::x, and channel::Point::y.
Referenced by EnterZone(), and channel::SkillManager::ProcessSkillResult().
void ZoneManager::PopEntityForProduction (const std::shared_ptr< ChannelClientConnection > & client, int32_t entityID, int32_t type, bool queue = false)
Send a request to a client to prepare an entity for display.
Parameters
client Pointer to the client connection
entityID ID of the entity to prep
type Client-side entity type identifier
queue true if the message should be queued, false if it should send right away
Definition at line 2134 of file ZoneManager.cpp.
Referenced by PopEntityForZoneProduction(), SendAllyData(), SendEnemyData(), SendLootBoxData(), and SendPopulateZoneData().
void ZoneManager::PopEntityForProduction (const std::list< std::shared_ptr< ChannelClientConnection >> & clients, int32_t entityID, int32_t type, bool queue = false)
Send a request to a list of clients to prepare an entity for display.
Parameters
clients List of pointers to client connections
entityID ID of the entity to prep
type Client-side entity type identifier
queue true if the message should be queued, false if it should send right away
Definition at line 2149 of file ZoneManager.cpp.
References channel::ChannelClientConnection::BroadcastPacket(), libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteS32Little().
void ZoneManager::PopEntityForZoneProduction (const std::shared_ptr< Zone > & zone, int32_t entityID, int32_t type)
Send a request to all clients in a zone to prepare an entity for display.
Parameters
zone Pointer to the zone to prep to show entities to
entityID ID of the entity to prep
type Client-side entity type identifier
Definition at line 2142 of file ZoneManager.cpp.
References PopEntityForProduction().
Referenced by ShowDemonToZone().
bool ZoneManager::RegisterTimeRestrictions (const std::shared_ptr< Zone > & zone, const std::shared_ptr< objects::ServerZone > & definition) private
Register time restricted actions for a zone with the manager such as time conditional spawn groups or plasma.
Times registered with the manager are also registered with the server.
Parameters
zone Pointer to the zone to register
definition Pointer to the zone definition
Returns
true if any times were registered, false if no times were registered
Definition at line 8658 of file ZoneManager.cpp.
References GetTriggerTimes(), channel::WorldClockTime::Hour, mAllTimeRestrictZones, channel::WorldClockTime::Min, channel::WorldClockTime::MoonPhase, mServer, mSpawnTimeRestrictZones, channel::WorldClockTime::SystemHour, and channel::WorldClockTime::SystemMin.
Referenced by CreateZone().
void ZoneManager::RemoveEntities (const std::list< std::shared_ptr< ChannelClientConnection >> & clients, const std::list< int32_t > & entityIDs, int32_t removalMode = 0, bool queue = false)
Send a request to the specified game clients to remove an entity.
Parameters
clients List of pointers to client connections
entityIDs IDs of the entities to remove
removalMode Optional preset removal mode. See ZoneManager::RemoveEntitiesFromZone for options
queue true if the packet should be queued
Definition at line 2169 of file ZoneManager.cpp.
References channel::ChannelClientConnection::BroadcastPacket(), libcomp::Packet::Clear(), channel::ChannelClientConnection::FlushAllOutgoing(), libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteS32Little().
Referenced by RemoveEntitiesFromZone().
void ZoneManager::RemoveEntitiesFromZone (const std::shared_ptr< Zone > & zone, const std::list< int32_t > & entityIDs, int32_t removalMode = 0, bool queue = false)
Send a request to all game clients in a zone to remove an entity.
Parameters
zone Pointer to the zone to remove the entities from
entityIDs IDs of the entities to remove
removalMode Optional preset removal mode 0) Immediate removal 2) Store partner demon 3) Demon egg contract complete 4) Replacing enemy with lootable body 5) Replacing enemy with demon egg 6) Replacing enemy with gift box 7) Enemy despawn 8) Enemy running away upon skill hit recovery 12) Partner demon 2-way fusion 13) Lootable body despawn 15) Partner demon crystallized 16) Partner demon 3-way fusion Seen but not unknown (1, 10)
queue true if the packet should be queued
Definition at line 2162 of file ZoneManager.cpp.
References RemoveEntities().
Referenced by HandleDespawns(), LeaveZone(), and ScheduleEntityRemoval().
bool ZoneManager::RemoveInstance (uint32_t instanceID) private
Remove a zone instance by unique ID if no characters have access and no characters are currently in any zone.
Parameters
instanceID Unique ID of the instance to remove
Returns
true if the instance was removed, false it was not
Definition at line 8592 of file ZoneManager.cpp.
References libcomp::String::Arg(), mServer, mZoneInstanceAccess, mZoneInstances, and RemoveZone().
Referenced by ExpireInstance(), LeaveZone(), and SyncInstanceAccess().
void ZoneManager::RemoveZone (const std::shared_ptr< Zone > & zone, bool freezeOnly) private
Remove and clean up all zone information for a specific zone.
Parameters
zone Pointer to the zone
freezeOnly If true, the zone will only be frozen and removed from all affected cache data members, if false it will be fully removed
Definition at line 8535 of file ZoneManager.cpp.
References mActiveTrackedZones, mActiveZones, mAllTimeRestrictZones, mServer, mSpawnTimeRestrictZones, mTimeRestrictUpdatedZones, and mZones.
Referenced by GetInstanceZone(), LeaveZone(), and RemoveInstance().
Point ZoneManager::RotatePoint (const Point & p, const Point & origin, float radians) static
Rotate a point around an origin point by the specified radians amount.
Parameters
p Point to rotate
origin Origin point to rotate around
radians Number of radians to rotate around the origin
Returns
Transformed rotation point
Definition at line 4322 of file ZoneManager.cpp.
References channel::Point::x, and channel::Point::y.
Referenced by channel::AIManager::Follow(), GetEntitiesInFoV(), GetRandomSpotPoint(), and LoadGeometry().
void ZoneManager::ScheduleEntityRemoval (uint64_t time, const std::shared_ptr< Zone > & zone, const std::list< int32_t > & entityIDs, int32_t removeMode = 0)
Schedule the delayed removal of one or more entities in the specified zone.
Parameters
time Server time to schedule entity removal for
zone Pointer to the zone the entities belong to
entityIDs List of IDs associated to entities to remove
removeMode Optional parameter to modify the way the entity is removed in regards to the client
Definition at line 2291 of file ZoneManager.cpp.
References mServer, RemoveEntitiesFromZone(), and channel::state().
void ZoneManager::ScheduleInstanceAccessTimeOut (const std::shared_ptr< ZoneInstance > & instance) private
Schedule instance access time-out and remove the instance if no player accesses it before then.
Parameters
instance Pointer to the zone instance to update
Definition at line 7309 of file ZoneManager.cpp.
References ExpireInstance(), channel::ChannelServer::GetServerTime(), and mServer.
Referenced by CreateInstance(), and LeaveZone().
void ZoneManager::ScheduleTimerExpiration (const std::shared_ptr< ZoneInstance > & instance) private
Schedule the expiration of a zone instance timer.
Parameters
instance Pointer to the zone instance with a timer set
Definition at line 7323 of file ZoneManager.cpp.
References libcomp::String::Arg(), GetInstance(), channel::ChannelServer::GetServerTime(), mServer, and StopInstanceTimer().
Referenced by ExtendInstanceTimer(), and StartInstanceTimer().
bool ZoneManager::SelectSpotAndLocation (bool useSpotID, uint32_t & spotID, const std::set< uint32_t > & spotIDs, std::shared_ptr< channel::ZoneSpotShape > & spot, std::shared_ptr< objects::SpawnLocation > & location, std::shared_ptr< DynamicMap > & dynamicMap, std::shared_ptr< objects::ServerZone > & zoneDef, std::list< std::shared_ptr< objects::SpawnLocation >> & locations) private
Select a spot for a spawn group and get it's location.
Parameters
useSpotID If the spot ID should be used.
spotID Selected spot ID.
spot Selected spot.
location Location of the selected spot.
dynamicMap Dynamic map data for the zone.
zoneDef Definition for the zone.
locations Spawn locations.
Returns
true if the spot was found; false on error. Upon error the spotID is NOT cleared so it can be used for error reporting.
Note
This is called by UpdateSpawnGroups.
Definition at line 4017 of file ZoneManager.cpp.
References libcomp::Randomizer::GetEntry().
Referenced by UpdateSpawnGroups().
void ZoneManager::SendAccessMessage (const std::shared_ptr< objects::InstanceAccess > & access, bool joined, const std::shared_ptr< ChannelClientConnection > & client = nullptr) private
Send InstanceAccess create or join messages to either one player or all players that have access to it.
Parameters
access Pointer to the InstanceAccess
joined If true the join message will be sent, if false the create message will be sent
client Pointer to a client connection that has access to the instance. If null all players that have access to the instance will be sent the message instead
Definition at line 8480 of file ZoneManager.cpp.
References channel::EventOptions::AutoOnly, channel::ClientState::GetCharacterState(), mServer, channel::EventOptions::NoInterrupt, and channel::state().
Referenced by CreateInstance(), EnterZone(), MoveToZoneChannel(), and SyncInstanceAccess().
void ZoneManager::SendAllyData (const std::shared_ptr< AllyState > & allyState, const std::shared_ptr< ChannelClientConnection > & client, const std::shared_ptr< Zone > & zone, bool queue = false) private
Send entity information about an ally in a zone.
Parameters
allyState Ally state to use to report ally data to the clients
client Pointer to the client connection to send to if specified instead of the whole zone
zone Pointer to the zone where the ally exists
queue true if the message should be queued, false if it should send right away
Definition at line 2641 of file ZoneManager.cpp.
References channel::ChannelClientConnection::FlushAllOutgoing(), PopEntityForProduction(), libcomp::Packet::Seek(), ShowEntity(), libcomp::Packet::WriteFloat(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS8(), libcomp::Packet::WriteU32Little(), and libcomp::Packet::WriteU8().
Referenced by AddEnemiesToZone(), SendPopulateZoneData(), and UpdateStaggeredSpawns().
void ZoneManager::SendBazaarMarketData (const std::shared_ptr< Zone > & zone, const std::shared_ptr< BazaarState > & bState, uint32_t marketID)
Send information about the current market matching the supplied ID in a bazaar to clients in the same zone.
Parameters
zone Pointer to the zone to send the data to
bState Entity state of the bazaar
marketID Market ID to send information about
Definition at line 2414 of file ZoneManager.cpp.
References BroadcastPacket(), libcomp::Convert::ENCODING_CP932, libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteString16Little().
Referenced by ExpireRentals(), and LeaveZone().
void ZoneManager::SendCultureMachineData (const std::shared_ptr< Zone > & zone, const std::shared_ptr< CultureMachineState > & cmState)
Send information about the supplied culture machine state to clients in the same zone.
Parameters
zone Pointer to the zone to send the data to
cmState Culture machine state to send data about
Definition at line 2431 of file ZoneManager.cpp.
References BroadcastPacket(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteU8().
Referenced by ExpireRentals().
void ZoneManager::SendDestinyBox (const std::shared_ptr< ChannelClientConnection > & client, bool eventMenu, bool queue = false)
Send the current state of the destiny box a client has access to.
Parameters
client Pointer to the client connection
eventMenu true if the box is being viewed via the lotto event menu, false if it is being viewed normally
queue If true the packet will be queued instead of sent directly
Definition at line 6288 of file ZoneManager.cpp.
References channel::ClientState::GetWorldCID(), channel::ClientState::GetZone(), libcomp::Packet::Seek(), channel::state(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS8(), libcomp::Packet::WriteU16Little(), and libcomp::Packet::WriteU32Little().
Referenced by HandleSpecialInstancePopulate().
void ZoneManager::SendEnemyData (const std::shared_ptr< EnemyState > & enemyState, const std::shared_ptr< ChannelClientConnection > & client, const std::shared_ptr< Zone > & zone, bool queue = false) private
Send entity information about an enemy in a zone.
Parameters
enemyState Enemy state to use to report enemy data to the clients
client Pointer to the client connection to send to if specified instead of the whole zone
zone Pointer to the zone where the enemy exists
queue true if the message should be queued, false if it should send right away
Definition at line 2564 of file ZoneManager.cpp.
References channel::ChannelClientConnection::FlushAllOutgoing(), PopEntityForProduction(), SendMultiZoneBossStatus(), ShowEntity(), libcomp::Packet::WriteFloat(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS8(), libcomp::Packet::WriteU32Little(), and libcomp::Packet::WriteU8().
Referenced by AddEnemiesToZone(), SendPopulateZoneData(), SpawnEnemy(), and UpdateStaggeredSpawns().
void ZoneManager::SendInstanceTimer (const std::shared_ptr< ZoneInstance > & instance, const std::shared_ptr< ChannelClientConnection > & client = nullptr, bool queue = false, uint32_t extension = 0)
Send the timer currently assigned to the supplied zone instance to one or all clients currenctly connected to it.
Parameters
instance Pointer to a zone instance
client Optional pointer to the client that should be sent the timer information. If not specified the entire zone will be sent the information.
queue true if the message should be queued, false if it should send right away
extension Optional parameter to include as a one time "extension" already added to the timer sent for certain packets
Definition at line 5343 of file ZoneManager.cpp.
References channel::ChannelClientConnection::BroadcastPacket(), channel::ChannelServer::GetServerTime(), channel::ChannelClientConnection::SendRelativeTimePacket(), libcomp::Packet::Size(), channel::state(), libcomp::Packet::WriteBlank(), libcomp::Packet::WriteFloat(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS8(), libcomp::Packet::WriteU32Little(), and libcomp::Packet::WriteU8().
Referenced by EndInstanceTimer(), ExtendInstanceTimer(), HandleSpecialInstancePopulate(), and StartInstanceTimer().
void ZoneManager::SendLootBoxData (const std::shared_ptr< ChannelClientConnection > & client, const std::shared_ptr< LootBoxState > & lState, const std::shared_ptr< ActiveEntityState > & eState, bool sendToAll, bool queue = false)
Send the details of a loot box in the specified client's zone to the client specified or all clients in that zone.
Parameters
client Pointer to the client connection
lState Entity state of the loot box
eState Entity state of the entity that created the loot box, specified when the loot box is first created
sendToAll true if all clients in the zone should be sent the data false if just the supplied client should be sent to
queue true if the message should be queued, false if it should send right away
Definition at line 2317 of file ZoneManager.cpp.
References channel::ChannelClientConnection::FlushAllOutgoing(), GetCurrentZone(), mServer, PopEntityForProduction(), ShowEntity(), libcomp::Packet::WriteFloat(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS8(), and libcomp::Packet::WriteU32Little().
Referenced by SendPopulateZoneData().
void ZoneManager::SendMultiZoneBossStatus (uint32_t groupID) private
Send the current multi-zone boss statuses in the supplied group.
Parameters
groupID Multi-zone boss group to update
Definition at line 7435 of file ZoneManager.cpp.
References BroadcastPacket(), mGlobalBossZones, mLock, mZones, libcomp::Packet::WriteFloat(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS8(), and libcomp::Packet::WriteU32Little().
Referenced by MultiZoneBossKilled(), SendEnemyData(), and UpdateActiveZoneStates().
bool ZoneManager::SendPopulateZoneData (const std::shared_ptr< ChannelClientConnection > & client)
Send data about entities that exist in a zone to a new connection and update any existing connections with information about the new one.
Parameters
client Client connection that was added to a zone
Returns
true if the client is in a zone, false if they are not
Definition at line 1842 of file ZoneManager.cpp.
References EFFECT_CANCEL_ZONEOUT, channel::ClientState::GetCharacterState(), channel::ClientState::GetClientStringEncoding(), GetCurrentZone(), channel::ClientState::GetDemonState(), channel::ChannelServer::GetServerTime(), channel::ClientState::GetWorldCID(), GetZoneConnections(), HandleSpecialInstancePopulate(), mServer, PopEntityForProduction(), SendAllyData(), SendEnemyData(), SendLootBoxData(), ShowDemonToZone(), ShowEntity(), ShowEntityToZone(), ShowNPC(), ShowObject(), channel::MatchManager::SpectatingMatch(), channel::state(), TriggerZoneActions(), UpdateDeathTimeOut(), libcomp::Packet::WriteFloat(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS8(), libcomp::Packet::WriteString16Little(), libcomp::Packet::WriteU16Little(), libcomp::Packet::WriteU32Little(), and libcomp::Packet::WriteU8().
void ZoneManager::SendToRange (const std::shared_ptr< ChannelClientConnection > & client, libcomp::Packet & p, bool includeSelf = true)
sends a packet to a specified range
Parameters
client Client connection to use as the "source" connection
p Packet to send to the zone
includeSelf Optional parameter to include the connection being passed in when sending the packets. Defaults to true
Definition at line 3119 of file ZoneManager.cpp.
References channel::ClientState::GetCharacterState(), GetZoneConnections(), mServer, and channel::state().
void ZoneManager::ShowDemonToZone (const std::shared_ptr< Zone > & zone, const std::shared_ptr< ChannelClientConnection > & client)
Send a request to all clients in a zone to show a demon entity and also relay any zone-in information to the source client.
Parameters
zone Pointer to the zone to show the demon to
client Pointer to the source client connection
Definition at line 2101 of file ZoneManager.cpp.
References mServer, PopEntityForZoneProduction(), and ShowEntityToZone().
Referenced by SendPopulateZoneData().
void ZoneManager::ShowEntity (const std::shared_ptr< ChannelClientConnection > & client, int32_t entityID, bool queue = false)
Send a request to a client to show an entity.
Parameters
client Pointer to the client connection
entityID ID of the entity to show
queue true if the message should be queued, false if it should send right away
Definition at line 2079 of file ZoneManager.cpp.
Referenced by HandleSpecialInstancePopulate(), SendAllyData(), SendEnemyData(), SendLootBoxData(), SendPopulateZoneData(), ShowEntityToZone(), ShowNPC(), and ShowObject().
void ZoneManager::ShowEntity (const std::list< std::shared_ptr< ChannelClientConnection >> & clients, int32_t entityID, bool queue = false)
Send a request to a list of client to show an entity.
Parameters
clients List of pointers to client connections
entityID ID of the entity to show
queue true if the message should be queued, false if it should send right away
Definition at line 2124 of file ZoneManager.cpp.
References channel::ChannelClientConnection::BroadcastPacket(), libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteS32Little().
void ZoneManager::ShowEntityToZone (const std::shared_ptr< Zone > & zone, int32_t entityID)
Send a request to all clients in a zone to show an entity.
Parameters
zone Pointer to the zone to show the entities to
entityID ID of the entity to show
Definition at line 2087 of file ZoneManager.cpp.
References ShowEntity().
Referenced by SendPopulateZoneData(), and ShowDemonToZone().
void ZoneManager::ShowNPC (const std::shared_ptr< Zone > & zone, const std::list< std::shared_ptr< ChannelClientConnection >> & clients, const std::shared_ptr< NPCState > & npcState, bool queue = false)
Send data about the supplied NPC to the zone or supplied clients.
Parameters
zone Pointer to the zone the NPC exists in
clients List of pointers to client connections
npcState State of the NPC to show
queue true if the message should be queued, false if it should send right away
Definition at line 2195 of file ZoneManager.cpp.
References channel::ChannelClientConnection::BroadcastPacket(), channel::ChannelClientConnection::FlushAllOutgoing(), ShowEntity(), libcomp::Packet::WriteFloat(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS16Little(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteU32Little().
Referenced by SendPopulateZoneData().
void ZoneManager::ShowObject (const std::shared_ptr< Zone > & zone, const std::list< std::shared_ptr< ChannelClientConnection >> & clients, const std::shared_ptr< ServerObjectState > & objState, bool queue = false)
Send data about the supplied object NPC to the zone or supplied clients.
Parameters
zone Pointer to the zone the object NPC exists in
clients List of pointers to client connections
objState State of the object NPC to show
queue true if the message should be queued, false if it should send right away
Definition at line 2226 of file ZoneManager.cpp.
References channel::ChannelClientConnection::BroadcastPacket(), channel::ChannelClientConnection::FlushAllOutgoing(), ShowEntity(), libcomp::Packet::WriteFloat(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteU32Little(), and libcomp::Packet::WriteU8().
Referenced by SendPopulateZoneData().
bool ZoneManager::SpawnEnemy (const std::shared_ptr< Zone > & zone, uint32_t demonID, float x, float y, float rot, const libcomp::String & aiType = "")
Spawn an enemy in the specified zone at set coordinates.
Parameters
zone Pointer to the zone where the enemy should be spawned
demonID Demon/enemy type ID to spawn
x X coordinate to render the enemy at
y Y coordinate to render the enemy at
rot Rotation to render the enemy with
aiType Optional parameter to specify the type of AI script to bind to the enemy by its type name
Returns
true if the enemy was spawned, false if it was not
Definition at line 3179 of file ZoneManager.cpp.
References CreateEnemy(), mServer, SendEnemyData(), and TriggerZoneActions().
bool ZoneManager::StartInstanceTimer (const std::shared_ptr< ZoneInstance > & instance)
Start the timer currently assigned to the supplied zone instance.
Parameters
instance Pointer to a zone instance
Returns
false if an error occurred
Definition at line 4886 of file ZoneManager.cpp.
References channel::ChannelServer::GetServerTime(), mLock, ScheduleTimerExpiration(), and SendInstanceTimer().
Referenced by EnterZone().
bool ZoneManager::StartZoneEvent (const std::shared_ptr< Zone > & zone, const libcomp::String & eventID)
Start an event contextual to the supplied zone with no source entity.
Parameters
zone Pointer to the zone to start the event for
eventID ID of the event to start
Returns
true if the event started successfully, false if it did not
Definition at line 6545 of file ZoneManager.cpp.
References mServer.
bool ZoneManager::StopInstanceTimer (const std::shared_ptr< ZoneInstance > & instance, uint64_t stopTime = false)
Stop the timer currently assigned to the supplied zone instance.
Parameters
instance Pointer to a zone instance
stopTime Explicit stop time to use instead of the current server time. This is useful for making sure the stop time does not undershoot the actual expiration
Returns
false if an error occurred
Definition at line 5099 of file ZoneManager.cpp.
References channel::EventOptions::AutoOnly, EndInstanceTimer(), EnterZone(), GetInstance(), GetInstanceStartingZone(), channel::ChannelServer::GetServerTime(), mLock, mServer, and channel::EventOptions::NoInterrupt.
Referenced by ScheduleTimerExpiration().
void ZoneManager::SyncInstanceAccess (std::list< std::shared_ptr< objects::InstanceAccess >> updates, std::list< std::shared_ptr< objects::InstanceAccess >> removes)
Sync updates and removals to InstanceAccess definitions that belong to this server or any other one.
Parameters
updates List of updated InstanceAccess definitions
removes List of removed InstanceAccess definitions
Definition at line 4331 of file ZoneManager.cpp.
References mLock, mZoneInstanceAccess, mZoneInstances, RemoveInstance(), and SendAccessMessage().
bool ZoneManager::TriggerZoneActions (const std::shared_ptr< Zone > & zone, std::list< std::shared_ptr< ActiveEntityState >> entities, ZoneTrigger_t trigger, const std::shared_ptr< ChannelClientConnection > & client = nullptr)
Trigger specific zone actions for the specified zone for a set of source entities.
Parameters
zone Pointer to a zone
entities List of pointers to entities that will be used as source entities for each action
trigger Type of trigger to execute
client Pointer to the client to use for the executing action contexts
Returns
true if at least one action trigger was fired, false if no action triggers were fired
Definition at line 6397 of file ZoneManager.cpp.
References GetZoneTriggers(), and HandleZoneTriggers().
Referenced by AddEnemiesToZone(), EnterZone(), LeaveZone(), SendPopulateZoneData(), and SpawnEnemy().
void ZoneManager::UpdateActiveZoneStates ()
Updates the current states of entities in the zone.
Enemy AI is processed from here as well as updating the current state of moving entities.
Definition at line 4540 of file ZoneManager.cpp.
References channel::ChannelServer::GetServerTime(), HandleDespawns(), mActiveTrackedZones, mActiveZones, mGlobalBossZones, mLock, mServer, mTimeRestrictUpdatedZones, mTrackingRefresh, mZones, SendMultiZoneBossStatus(), channel::PerformanceTimer::Start(), UpdatePlasma(), UpdateSpawnGroups(), UpdateStaggeredSpawns(), UpdateStatusEffectStates(), UpdateTrackedTeam(), and UpdateTrackedZone().
Referenced by channel::ChannelServer::Tick().
void ZoneManager::UpdateDeathTimeOut (ClientState * state, int32_t time, const std::shared_ptr< ChannelClientConnection > & client = nullptr)
Update the death time-out associated to the client and handle scheduling expiration and communication to the players.
Parameters
state Pointer to state of the entity to time-out
time Time-out value to assign to the entity. If -1, the time-out will be cleared. If 0, the current value will be sent.
client Optional pointer to the client that should be sent the time-out packets. If not specified the entire zone will be sent the information.
Definition at line 5547 of file ZoneManager.cpp.
References BroadcastPacket(), channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), channel::ChannelServer::GetServerTime(), channel::ClientState::GetZone(), HandleDeathTimeOut(), mServer, libcomp::Packet::WriteFloat(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteU32Little().
Referenced by EndInstanceTimer(), and SendPopulateZoneData().
bool ZoneManager::UpdateDestinyBox (const std::shared_ptr< ZoneInstance > & instance, int32_t worldCID, const std::list< std::shared_ptr< objects::Loot >> & add, std::set< uint8_t > remove = {})
Update the loot assigned to the destiny box assigned to a specific world CID.
Parameters
instance Pointer to the instance the box belongs to
worldCID World CID that has access to the box
add List of pointers to loot to add
remove Optional set of slots to clear before adding loot
Returns
true if the updates occurred, false if they did not
Definition at line 6192 of file ZoneManager.cpp.
References channel::ChannelClientConnection::BroadcastPacket(), mServer, libcomp::Packet::Seek(), libcomp::Packet::Size(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteU16Little(), libcomp::Packet::WriteU32Little(), and libcomp::Packet::WriteU8().
bool ZoneManager::UpdateGeometryElement (const std::shared_ptr< Zone > & zone, std::shared_ptr< objects::ServerObject > elemObject)
Update zone geometry information bound to a server object in the supplied zone.
Parameters
zone Pointer to a zone
elemObject Pointer to a server object that may be bound to zone geometry
Returns
true if the geometry state was updated, false if it was not
Definition at line 6554 of file ZoneManager.cpp.
References IsGeometryDisabled(), and mServer.
Referenced by CreateZone().
bool ZoneManager::UpdatePlasma (const std::shared_ptr< Zone > & zone, uint64_t now = 0)
Update the specified zone's PlasmaSpawns.
Parameters
zone Pointer to the zone where the plasma should be updated
now Current server time
Returns
true if any plasma was spawned or despawned
Definition at line 4201 of file ZoneManager.cpp.
References BroadcastPacket(), GetRandomSpotPoint(), mServer, libcomp::Packet::WriteFloat(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS8(), channel::Point::x, and channel::Point::y.
Referenced by CreateZone(), and UpdateActiveZoneStates().
bool ZoneManager::UpdateSpawnGroups (const std::shared_ptr< Zone > & zone, bool refreshAll, uint64_t now = 0, std::shared_ptr< objects::ActionSpawn > actionSource = nullptr)
Update the specified zone's spawns from SpawnLocationGroups or SpawnGroups directly updated at specific spots.
Parameters
zone Pointer to the zone where the groups should be updated
refreshAll true if each group should be filled, false if only spawn groups with an elapsed refresh timer should be updated
now Current server time
actionSource Optional action source of the spawn
Returns
true if any enemy was spawned, false if no enemy was spawned
Definition at line 3523 of file ZoneManager.cpp.
References AddEnemiesToZone(), libcomp::String::Arg(), CreateEnemy(), libcomp::Randomizer::GetEntry(), GetLinearPoint(), GetRandomPoint(), GetRandomRotation(), GetRandomSpotPoint(), channel::ChannelServer::GetServerTime(), channel::ActionOptions::GroupID, mServer, SelectSpotAndLocation(), channel::state(), ValidateBossGroup(), and channel::Point::x.
Referenced by CreateZone(), and UpdateActiveZoneStates().
bool ZoneManager::UpdateStaggeredSpawns (const std::shared_ptr< Zone > & zone, uint64_t now)
Update the specified zone's staggered spawns, showing them to the zone if any are ready.
Parameters
zone Pointer to the zone
now Current server time
Returns
true if any enemy was spawned, false if no enemy was spawned
Definition at line 3996 of file ZoneManager.cpp.
References SendAllyData(), and SendEnemyData().
Referenced by UpdateActiveZoneStates().
void ZoneManager::UpdateStatusEffectStates (const std::shared_ptr< Zone > & zone, uint32_t now, const std::list< std::shared_ptr< ActiveEntityState >> & entities)
Update the state of status effects in the supplied zone, adding and updating existing effects, expiring old effects and applying T-damage and regen to entities with applicable effects.
Parameters
zone Pointer to the zone to update status effects for
now System time representing the current server time to use for event checking
entities List of pointers to entities to have their status effects updated
Definition at line 2793 of file ZoneManager.cpp.
References channel::ChannelClientConnection::BroadcastPackets(), EFFECT_CANCEL_DAMAGE, ENTITY_CALC_STAT_WORLD, channel::CharacterManager::GetTDamagePacket(), mServer, SVR_CONST, libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteU32Little().
Referenced by UpdateActiveZoneStates(), and UpdateStatusEffectStates().
void ZoneManager::UpdateStatusEffectStates (const std::shared_ptr< Zone > & zone, uint32_t now) private
Update the state of status effects in the supplied zone, adding and updating existing effects, expiring old effects and applying T-damage and regen to entities with applicable effects.
Parameters
zone Pointer to the zone to update status effects for
now System time representing the current server time to use for event checking
Definition at line 2783 of file ZoneManager.cpp.
References UpdateStatusEffectStates().
bool ZoneManager::UpdateTrackedTeam (const std::shared_ptr< objects::Team > & team, const std::shared_ptr< Zone > & zone = nullptr)
Update any team specific entity tracking/state information.
Parameters
team Pointer to the team being tracked
zone Optional pointer to the only zone the tracking information should be updated for
Returns
true if the team tracking was updated successfully, false if it did not apply
Definition at line 6146 of file ZoneManager.cpp.
References channel::ChannelClientConnection::BroadcastPacket(), channel::ClientState::GetCharacterState(), channel::ClientState::GetZone(), mServer, channel::state(), libcomp::Packet::WriteBlank(), libcomp::Packet::WriteFloat(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS8(), and libcomp::Packet::WriteU32Little().
Referenced by EnterZone(), UpdateActiveZoneStates(), and UpdateTrackedZone().
bool ZoneManager::UpdateTrackedZone (const std::shared_ptr< Zone > & zone, const std::shared_ptr< objects::Team > & team = nullptr)
Update any zone specific entity tracking/state information and if the zone is marked for tracking and fall back to team tracking only if the whole zone should not be tracked.
An example of a tracked zone is a Diaspora instance zone.
Parameters
zone Pointer to a zone to track
team Optional pointer to the team to track if the zone is not being tracked in itself
Returns
true if the zone (or team) tracking was updated successfully, false if it did not apply
Definition at line 6082 of file ZoneManager.cpp.
References channel::ChannelClientConnection::BroadcastPacket(), channel::ClientState::GetCharacterState(), channel::ClientState::GetWorldCID(), channel::state(), UpdateTrackedTeam(), libcomp::Packet::WriteFloat(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteU32Little().
Referenced by LeaveZone(), and UpdateActiveZoneStates().
bool ZoneManager::ValidateBossGroup (const std::shared_ptr< EnemyState > & enemyState) private
Determine if the supplied boss EnemyState is valid to add to a multi-zone boss group.
Parameters
enemyState Pointer to the boss EnemyState
Returns
true if the boss can be added, false if it cannot
Definition at line 7383 of file ZoneManager.cpp.
References libcomp::String::Arg(), mGlobalBossZones, mLock, and mZones.
Referenced by UpdateSpawnGroups().
void ZoneManager::Warp (const std::shared_ptr< ChannelClientConnection > & client, const std::shared_ptr< ActiveEntityState > & eState, float xPos, float yPos, float rot)
Warp an entity to the specified location immediately.
Parameters
client Pointer to the client connection to use for gathering zone information
eState Pointer to the state of the entity being warped
xPos X coordinate to warp the entity to
yPos Y coordinate to warp the entity to
rot Rotation to set at the target coordinates
Definition at line 4720 of file ZoneManager.cpp.
References channel::ChannelServer::GetServerTime(), GetZoneConnections(), channel::ChannelClientConnection::SendRelativeTimePacket(), libcomp::Packet::Size(), libcomp::Packet::WriteFloat(), libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteS32Little().
Member Data Documentation
std::set<uint32_t> channel::ZoneManager::mActiveTrackedZones private
Set of IDs for all zones that are both active and configured for team, full zone or boss tracking.
Definition at line 1399 of file ZoneManager.h.
Referenced by EnterZone(), LeaveZone(), RemoveZone(), and UpdateActiveZoneStates().
std::set<uint32_t> channel::ZoneManager::mActiveZones private
Set of all zones that should be considered active when updating states.
When a zone is removed from this set but not removed entirely, its AI etc will be frozen until a player enters the zone again.
Definition at line 1395 of file ZoneManager.h.
Referenced by AddEnemiesToZone(), EnterZone(), RemoveZone(), and UpdateActiveZoneStates().
std::set<uint32_t> channel::ZoneManager::mAllTimeRestrictZones private
Set of all zone IDs with at least one time restricted action bound to them.
Definition at line 1409 of file ZoneManager.h.
Referenced by HandleTimedActions(), RegisterTimeRestrictions(), and RemoveZone().
std::unordered_map<uint32_t, std::shared_ptr<DynamicMap> > channel::ZoneManager::mDynamicMaps private
Map of dynamic map IDs to geometry information built from their corresponding binary definitions.
Definition at line 1386 of file ZoneManager.h.
Referenced by CreateZone(), and LoadGeometry().
std::unordered_map<int32_t, uint32_t> channel::ZoneManager::mEntityMap private
Map of world CIDs to zone unique IDs.
Definition at line 1378 of file ZoneManager.h.
Referenced by EnterZone(), GetCurrentZone(), GetZoneConnections(), and LeaveZone().
std::unordered_map<uint32_t, std::set<uint32_t> > channel::ZoneManager::mGlobalBossZones private
Map of global boss group IDs to zones in that group on the server.
Definition at line 1389 of file ZoneManager.h.
Referenced by InstanceGlobalZones(), MultiZoneBossKilled(), SendMultiZoneBossStatus(), UpdateActiveZoneStates(), and ValidateBossGroup().
std::list<std::shared_ptr<objects::ServerZoneTrigger> > channel::ZoneManager::mGlobalTimeTriggers private
List of zone-detached global time triggers that fire independent of any zone.
Definition at line 1417 of file ZoneManager.h.
Referenced by HandleTimedActions(), and InstanceGlobalZones().
std::unordered_map<uint32_t, std::unordered_map<uint32_t, uint32_t> > channel::ZoneManager::mGlobalZoneMap private
Map of global zone definition IDs to map of zone unique IDs by dynamic map ID.
Definition at line 1366 of file ZoneManager.h.
Referenced by GetExistingZone(), GetZone(), and InstanceGlobalZones().
libcomp::Mutex channel::ZoneManager::mInstanceZoneLock private
Server lock for creating or getting existing zones in an instance.
Definition at line 1432 of file ZoneManager.h.
Referenced by GetInstanceZone().
libcomp::Mutex channel::ZoneManager::mLock private
Server lock for shared resources.
Definition at line 1429 of file ZoneManager.h.
Referenced by CreateInstance(), CreateZone(), EnterZone(), GetCurrentZone(), GetExistingZone(), GetInstance(), GetInstanceAccess(), GetInstanceZone(), GetRandomSpotPoint(), GetZone(), GetZoneConnections(), HandleTimedActions(), InstanceGlobalZones(), LeaveZone(), MultiZoneBossKilled(), SendMultiZoneBossStatus(), StartInstanceTimer(), StopInstanceTimer(), SyncInstanceAccess(), UpdateActiveZoneStates(), and ValidateBossGroup().
uint32_t channel::ZoneManager::mNextZoneID private
Next available zone unique ID.
Definition at line 1423 of file ZoneManager.h.
Referenced by CreateZone().
uint32_t channel::ZoneManager::mNextZoneInstanceID private
Next available zone instance unique ID.
Definition at line 1426 of file ZoneManager.h.
Referenced by CreateInstance().
std::weak_ptr<ChannelServer> channel::ZoneManager::mServer private
Pointer to the channel server.
Definition at line 1435 of file ZoneManager.h.
Referenced by AddDiasporaBases(), AddEnemiesToZone(), AddPvPBases(), CreateAlly(), CreateEnemy(), CreateInstance(), CreateZone(), EndInstanceTimer(), EnterZone(), ExpireRentals(), FailPlasma(), GetInstanceZone(), GetLoginZone(), GetMatchStartPosition(), GetSpotPosition(), GetZone(), GetZoneTriggers(), HandleDeathTimeOut(), HandleDespawns(), HandleSpecialInstancePopulate(), HandleTimedActions(), HandleZoneTriggers(), InstanceGlobalZones(), LeaveZone(), LoadGeometry(), MoveToInstance(), MoveToLobby(), MoveToZoneChannel(), RegisterTimeRestrictions(), RemoveInstance(), RemoveZone(), ScheduleEntityRemoval(), ScheduleInstanceAccessTimeOut(), ScheduleTimerExpiration(), SendAccessMessage(), SendLootBoxData(), SendPopulateZoneData(), SendToRange(), ShowDemonToZone(), SpawnEnemy(), StartZoneEvent(), StopInstanceTimer(), UpdateActiveZoneStates(), UpdateDeathTimeOut(), UpdateDestinyBox(), UpdateGeometryElement(), UpdatePlasma(), UpdateSpawnGroups(), UpdateStatusEffectStates(), and UpdateTrackedTeam().
std::map<WorldClockTime, std::set<uint32_t> > channel::ZoneManager::mSpawnTimeRestrictZones private
Map of times bound to zone IDs to register with the world for world time triggering.
Definition at line 1413 of file ZoneManager.h.
Referenced by RegisterTimeRestrictions(), and RemoveZone().
std::set<uint32_t> channel::ZoneManager::mTimeRestrictUpdatedZones private
Set of all zone IDs, active or not, that have had a time restricted update performed on them.
This can be thought of as temporarily "unfreezing" a zone if it is not currently active. Once the zone's updates have been performed, it is removed from this set.
Definition at line 1405 of file ZoneManager.h.
Referenced by HandleTimedActions(), RemoveZone(), and UpdateActiveZoneStates().
ServerTime channel::ZoneManager::mTrackingRefresh private
Next server time that tracked zones will be refreshed during.
Definition at line 1420 of file ZoneManager.h.
Referenced by EnterZone(), LeaveZone(), and UpdateActiveZoneStates().
std::unordered_map<std::string, std::shared_ptr<ZoneGeometry> > channel::ZoneManager::mZoneGeometry private
Map of QMP filenames to the geometry structures built from them.
Definition at line 1382 of file ZoneManager.h.
Referenced by CreateZone(), GetRandomSpotPoint(), and LoadGeometry().
std::unordered_map<int32_t, std::shared_ptr<objects::InstanceAccess> > channel::ZoneManager::mZoneInstanceAccess private
Map of world CIDs to the zone instance access definitions.
The moment a character enters the zone, they are removed from this map as they are not able to intentionally re-enter
Definition at line 1375 of file ZoneManager.h.
Referenced by CreateInstance(), EnterZone(), GetInstanceAccess(), GetZone(), LeaveZone(), RemoveInstance(), and SyncInstanceAccess().
std::unordered_map<uint32_t, std::shared_ptr<ZoneInstance> > channel::ZoneManager::mZoneInstances private
Map of zone instances by unique ID.
Definition at line 1369 of file ZoneManager.h.
Referenced by CreateInstance(), GetInstance(), GetZone(), RemoveInstance(), and SyncInstanceAccess().
std::unordered_map<uint32_t, std::shared_ptr<Zone> > channel::ZoneManager::mZones private
Map of zones by unique ID.
Definition at line 1361 of file ZoneManager.h.
Referenced by CreateZone(), GetCurrentZone(), GetExistingZone(), GetZone(), GetZoneConnections(), HandleTimedActions(), LeaveZone(), MultiZoneBossKilled(), RemoveZone(), SendMultiZoneBossStatus(), UpdateActiveZoneStates(), ValidateBossGroup(), and ~ZoneManager().
The documentation for this class was generated from the following files:
ZoneManager.h
ZoneManager.cpp