COMP_hack: channel::MatchManager Class Reference
channel::MatchManager Class Reference
Manager class used to handle all channel side match logic.
#include <MatchManager.h>
Public Member Functions
MatchManager (const std::weak_ptr< ChannelServer > &server)
Create a new MatchManager.
virtual ~MatchManager ()
Clean up the MatchManager.
bool AdvancePhase (const std::shared_ptr< Zone > &zone, int8_t to=-1, int8_t from=-1)
Advance the supplied zone's current phase.
bool CancelQueue (const std::shared_ptr< ChannelClientConnection > &client)
Remove the supplied client from the match queue.
bool CleanupPendingMatch (const std::shared_ptr< ChannelClientConnection > &client)
Remove the supplied client from their current match and end the match if configured to do so when no members exist.
void CompleteBaseCapture (int32_t entityID, int32_t baseID, uint32_t zoneID, uint32_t instanceID, uint64_t occupyStartTime)
Complete capturing a base in the instance and grant points if applicable.
void ConfirmMatch (const std::shared_ptr< ChannelClientConnection > &client, uint32_t matchID=0)
Confirm entrance into a currently ready match.
bool EndPvPMatch (uint32_t instanceID)
End the PvP match in the specified instance.
void EnterDiaspora (const std::shared_ptr< ChannelClientConnection > &client, const std::shared_ptr< Zone > &zone)
Notify all Diaspora entries that a player has joined or changed zones and send the new player match information.
void EnterPvP (const std::shared_ptr< ChannelClientConnection > &client, uint32_t instanceID)
Notify all PvP entries that a player has joined or changed zones and send the new player the PvP match info.
void EnterUltimateBattle (const std::shared_ptr< ChannelClientConnection > &client, const std::shared_ptr< Zone > &zone)
Notify all UB entries that a player has joined if they are a participant and send the new player match information.
void ExpirePvPAccess (uint32_t matchID)
Expire all pending invites to a PvP match.
std::shared_ptr
< objects::MatchEntry > GetMatchEntry (int32_t cid)
Get current match entry associated to a world CID.
std::shared_ptr
< objects::PentalphaMatch > GetPentalphaMatch (bool previous)
Get the currently active (or previous) Pentalpha Match.
std::shared_ptr< objects::PvPData > GetPvPData (const std::shared_ptr< ChannelClientConnection > &client, bool create=false)
Get or create the specified client's PvPData.
std::shared_ptr
< objects::UBTournament > GetUBTournament () const
Get the currently active Ultimate Battle Tournament.
void IncreaseBaseBonus (int32_t baseID, uint32_t zoneID, uint32_t instanceID, uint64_t occupyStartTime)
Increase a captured base's bonus in the instance and grant points if applicable.
bool JoinQueue (const std::shared_ptr< ChannelClientConnection > &client, int8_t type)
Queue the supplied client for a match of the specified type.
bool JoinUltimateBattleQueue (int32_t worldCID, const std::shared_ptr< Zone > &zone)
Queue the supplied client for the Ultimate Battle match in the specified zone.
bool LeaveBase (const std::shared_ptr< ChannelClientConnection > &client, int32_t baseID)
Request to stop capturing a PvP base in the instance.
void LeaveTeam (const std::shared_ptr< ChannelClientConnection > &client, int32_t teamID)
Request to leave the client's team.
void LeaveUltimateBattle (const std::shared_ptr< ChannelClientConnection > &client, const std::shared_ptr< Zone > &zone)
Notify all UB entries that a player has left if they are a participant.
std::shared_ptr
< objects::PentalphaEntry > LoadPentalphaData (const std::shared_ptr< ChannelClientConnection > &client, uint8_t idxFlags=0x03)
Load and cache all Pentalpha Match information associated to the client.
std::shared_ptr
< objects::UBResult > LoadUltimateBattleData (const std::shared_ptr< ChannelClientConnection > &client, uint8_t idxFlags=0x03, bool createMissing=false)
Load and cache all Ultimate Battle information associated to the client.
void PlayerKilled (const std::shared_ptr< ActiveEntityState > &entity, const std::shared_ptr< ZoneInstance > &instance)
Special match handler for any primary player entities that were killed during a match.
bool PvPInviteReply (const std::shared_ptr< ChannelClientConnection > &client, uint32_t matchID, bool accept)
Respond to a PvP invite with with either an acceptane or rejection.
void RejectPvPMatch (const std::shared_ptr< ChannelClientConnection > &client)
Reject entrance into a currently ready match.
bool RequestTeamPvPMatch (const std::shared_ptr< ChannelClientConnection > &client, uint32_t variantID, uint32_t instanceID)
Validate and request a custom PvP match formed from the player's current team.
bool ResetDiasporaBase (uint32_t zoneID, uint32_t instanceID, int32_t baseID, uint64_t resetTime)
Handler for Diaspora base automatic reset.
void SendDiasporaLocation (const std::shared_ptr< ChannelClientConnection > &client, uint32_t instanceID, bool enter, bool others=false)
Notify all Diaspora entries that a player has entered or left the instance.
void SendPvPLocation (const std::shared_ptr< ChannelClientConnection > &client, uint32_t instanceID, bool enter)
Notify all PvP entries that a player has entered or left the instance.
void SendUltimateBattleRankings (const std::shared_ptr< ChannelClientConnection > &client)
Notify the client of their current Ultimate Battle rank information.
void SendZiotite (const std::shared_ptr< objects::Team > &team, const std::shared_ptr< ChannelClientConnection > &client=nullptr)
Send the supplied team's ziotite values to the supplied client or the full team.
bool StartPvPBaseCapture (const std::shared_ptr< ChannelClientConnection > &client, int32_t baseID)
Request to start capturing a PvP base in the instance.
void StartPvPMatch (uint32_t instanceID)
Start the PvP match in the specified instance.
bool StartStopMatch (const std::shared_ptr< Zone > &zone, const std::shared_ptr< objects::Match > &match)
Start or stop a match associated to the supplied zone, its instance and other zones if they exist.
bool StartUltimateBattle (const std::shared_ptr< Zone > &zone)
Move the Ultimate Battle match in the supplied zone from the Pre-Match to Ready state and send out any queue/recruit notifications or remove the match if no one is currently attempting to enter.
bool StartUltimateBattleTimer (const std::shared_ptr< Zone > &zone, uint32_t duration, const libcomp::String &eventID, bool endPhase)
Start a new timer for an Ultimate Battle match.
bool ToggleDiasporaBase (const std::shared_ptr< Zone > &zone, int32_t baseID, int32_t sourceEntityID, bool capture)
Capture or reset a Diaspora base in the supplied zone.
void UltimateBattleBegin (uint32_t zoneID, uint32_t dynamicMapID, uint32_t instanceID)
Kick off the Ultimate Battle timer and begin the match.
void UltimateBattleQueue (uint32_t zoneID, uint32_t dynamicMapID, uint32_t instanceID)
Pending Ultimate Battle queue handler that notifies players in the lobby before the match begins and causes the match to start.
void UltimateBattleRecruit (uint32_t zoneID, uint32_t dynamicMapID, uint32_t instanceID)
Send a recruit request to players still waiting in the queue who were not selected for the initial set.
bool UltimateBattleSpectate (int32_t worldCID, const std::shared_ptr< Zone > &zone)
Register the supplied world CID as an Ultimate Battle spectator for the specified zone's match.
void UltimateBattleTick (uint32_t zoneID, uint32_t dynamicMapID, uint32_t instanceID)
Active Ultimate Battle "tick" handler that triggers actions for spawns and adjusts the gauge for non-UA matches.
void UpdateMatchEntries (const std::list< std::shared_ptr< objects::MatchEntry >> &updates, const std::list< std::shared_ptr< objects::MatchEntry >> &removes)
Synchronization handler for match queue entries that have been updated by the world server.
void UpdatePentalphaMatch (const std::shared_ptr< objects::PentalphaMatch > &match)
Set the active Pentalpha Match and reload all entry info.
void UpdatePvPMatches (const std::list< std::shared_ptr< objects::PvPMatch >> &matches)
Synchronization handler for PvP matches that have been updated (or created) by the world server.
int32_t UpdatePvPPoints (uint32_t instanceID, std::shared_ptr< ActiveEntityState > source, std::shared_ptr< ActiveEntityState > target, int32_t points)
Update PvP match points for a specific source and target entity.
int32_t UpdatePvPPoints (uint32_t instanceID, int32_t sourceID, int32_t targetID, uint8_t teamID, int32_t points, bool altMode)
Update PvP match points.
bool UpdateUBPoints (const std::shared_ptr< ChannelClientConnection > &client, int32_t adjust)
Update the supplied client's Ultimate Battle points for the current tournament.
void UpdateUBRankings (const std::list< std::shared_ptr< objects::UBResult >> &updated)
Synchronization handler for Ultimate Battle results that have been updated by the world server.
void UpdateUBTournament (const std::shared_ptr< objects::UBTournament > &tournament)
Set the active Ultimate Battle Tournament and reload all ranking information.
bool UpdateZiotite (const std::shared_ptr< objects::Team > &team, int32_t sZiotite, int8_t lZiotite, int32_t worldCID=0)
Update the small and large ziotite values for a team.
Static Public Member Functions
static bool InPvPTeam (const std::shared_ptr< ActiveEntityState > &entity)
Determine if the supplied entity is in a PvP team based upon the assigned faction group.
static bool PvPActive (const std::shared_ptr< ZoneInstance > &instance)
Determine if the supplied instance has an active PvP match being played.
static bool SpectatingMatch (const std::shared_ptr< ChannelClientConnection > &client, const std::shared_ptr< Zone > &zone)
Determine if the supplied client is spectating a zone's Ultimate Battle match.
Private Member Functions
bool CreatePvPInstance (const std::shared_ptr< objects::PvPMatch > &match)
Create a new PvP instance from the supplied match information.
void EndUltimateBattle (const std::shared_ptr< Zone > &zone)
Perform all end of match actions for an Ultimate Battle zone.
bool EndUltimateBattlePhase (const std::shared_ptr< Zone > &zone, bool matchOver)
Perform all end of phase actions for an Ultimate Battle zone for the current phase.
void FirePhaseTriggers (const std::shared_ptr< Zone > &zone, int8_t phase)
Fire phase triggers associated to the supplied zone and any of its related zones or instance.
void GetPvPTrophies (const std::shared_ptr< ZoneInstance > &instance)
Calculate and assign all trophies earned during an instance's PvP match to the entity statistics for that instance.
void QueueNextBaseBonus (int32_t baseID, const std::shared_ptr< Zone > &zone, uint64_t occupyStartTime)
Queue the next asynchronous base bonus increase in a match instance.
void QueuePendingPvPMatch (uint8_t type, uint32_t readyTime)
Create a PvPMatch with all pre-instance creation values and send it to the world to use if the match begins at the specified time.
void SendPhase (const std::shared_ptr< Zone > &zone, bool timerStart=false, const std::shared_ptr< ChannelClientConnection > &client=nullptr)
Notify all players in a match zone of the current phase.
void SendUltimateBattleMembers (const std::shared_ptr< Zone > &zone, const std::shared_ptr< ChannelClientConnection > &client=nullptr)
Notify players in an Ultimate Battle zone of the current match participants.
void SendUltimateBattleMemberState (const std::shared_ptr< Zone > &zone, const std::shared_ptr< ChannelClientConnection > &client=nullptr)
Notify players in an Ultimate Battle zone of the current match participant states.
bool ValidateMatchEntries (const std::list< std::shared_ptr< ChannelClientConnection >> &clients, int8_t teamCategory, bool isTeam, bool checkPenalties)
Determine if the supplied player clients are valid for match entry creation.
Static Private Member Functions
static bool IsPvPMatchEntry (const std::shared_ptr< objects::MatchEntry > &entry)
Determine if the supplied match entry is a PvP entry.
static bool MatchTeamsActive (const std::shared_ptr< ZoneInstance > &instance)
Determine if the supplied instance has active team members on both sides of a match.
Private Attributes
std::mutex mLock
Server lock for shared resources.
std::unordered_map< int32_t,
std::shared_ptr
< objects::MatchEntry > > mMatchEntries
Local channel server copy of all current match queue entrants that are synchronized with the world server.
std::unordered_map< uint32_t,
std::set< int32_t > > mPendingPvPInvites
Time limited map of system expiration times to world CIDs of players that have been sent PvP match invitations.
std::array< std::shared_ptr
< objects::PentalphaMatch >, 2 > mPentalphaMatches
Pointers to the current and previous Pentalpha Matches.
std::weak_ptr< ChannelServer > mServer
Pointer to the channel server.
std::array< std::array
< std::shared_ptr
< objects::UBResult >, 10 >, 4 > mUBRankings
Map of currently reported UB top 10 rankings in the following order: all time total, top points, previous tournament, current tournament.
std::shared_ptr
< objects::UBTournament > mUBTournament
Pointer to the current active UBTournament.
Detailed Description
Manager class used to handle all channel side match logic.
Definition at line 54 of file MatchManager.h.
Constructor & Destructor Documentation
MatchManager::MatchManager (const std::weak_ptr< ChannelServer > & server)
Create a new MatchManager.
Parameters
server Pointer back to the channel server this belongs to.
Definition at line 112 of file MatchManager.cpp.
MatchManager::~MatchManager () virtual
Clean up the MatchManager.
Definition at line 117 of file MatchManager.cpp.
Member Function Documentation
bool MatchManager::AdvancePhase (const std::shared_ptr< Zone > & zone, int8_t to = -1, int8_t from = -1)
Advance the supplied zone's current phase.
Parameters
zone Pointer to the zone with a match
to New phase to move to, defaults to "next phase"
from Phase to move from, defaults to "current phase"
Returns
true if the phase was updated, false if it was not
Definition at line 2801 of file MatchManager.cpp.
References EndUltimateBattle(), FirePhaseTriggers(), mLock, mServer, and SendPhase().
bool MatchManager::CancelQueue (const std::shared_ptr< ChannelClientConnection > & client)
Remove the supplied client from the match queue.
Parameters
client Pointer to the client connection
Definition at line 227 of file MatchManager.cpp.
References libcomp::String::Arg(), CleanupPendingMatch(), channel::ClientState::GetAccountUID(), GetMatchEntry(), channel::ClientState::GetWorldCID(), mServer, and channel::state().
bool MatchManager::CleanupPendingMatch (const std::shared_ptr< ChannelClientConnection > & client)
Remove the supplied client from their current match and end the match if configured to do so when no members exist.
Parameters
client Pointer to the client connection
Returns
true if the update occurred, false if it did not
Definition at line 892 of file MatchManager.cpp.
References GetMatchEntry(), channel::ClientState::GetWorldCID(), mLock, mMatchEntries, mServer, PvPInviteReply(), StartStopMatch(), and channel::state().
Referenced by CancelQueue(), ConfirmMatch(), and UltimateBattleBegin().
void MatchManager::CompleteBaseCapture (int32_t entityID, int32_t baseID, uint32_t zoneID, uint32_t instanceID, uint64_t occupyStartTime)
Complete capturing a base in the instance and grant points if applicable.
Parameters
entityID ID of the entity capturing the base
baseID Entity ID of the base to capture
zoneID Unique ID of the zone the entity is in
instanceID Unique ID of the instance the entity is in
occupyStartTime Start time of the entity's base occupation. If this does not match the value on the base, the capture will fail.
Definition at line 1901 of file MatchManager.cpp.
References channel::ClientState::GetCharacterState(), channel::ClientState::GetEntityClientState(), libcomp::Randomizer::GetEntry(), channel::ClientState::GetZone(), mServer, PvPActive(), QueueNextBaseBonus(), channel::state(), UpdatePvPPoints(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteS8().
Referenced by StartPvPBaseCapture().
void MatchManager::ConfirmMatch (const std::shared_ptr< ChannelClientConnection > & client, uint32_t matchID = 0)
Confirm entrance into a currently ready match.
Parameters
client Pointer to the client connection
matchID ID of the match sent to the client for UB matches
Definition at line 297 of file MatchManager.cpp.
References CleanupPendingMatch(), channel::ClientState::GetWorldCID(), mLock, mServer, PvPInviteReply(), channel::state(), libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteS8().
bool MatchManager::CreatePvPInstance (const std::shared_ptr< objects::PvPMatch > & match) private
Create a new PvP instance from the supplied match information.
Parameters
match Pointer to the PvP match definition
Returns
true if the match was created, false if was not
Definition at line 4058 of file MatchManager.cpp.
References libcomp::String::Arg(), channel::ChannelServer::GetExpirationInSeconds(), channel::ChannelServer::GetServerTime(), mServer, and StartPvPMatch().
Referenced by UpdatePvPMatches().
bool MatchManager::EndPvPMatch (uint32_t instanceID)
End the PvP match in the specified instance.
If the timer has not been stopped already, this will fail. All updates are performed here and results are then sent to the players still in the match.
Parameters
instanceID ID of the instance to stop the match in
Returns
true if the match was stopped, false if it was not
Definition at line 1101 of file MatchManager.cpp.
References libcomp::String::Arg(), channel::ChannelClientConnection::BroadcastPacket(), libcomp::DatabaseChangeSet::Create(), libcomp::Convert::ENCODING_CP932, GetPvPTrophies(), mServer, PvPActive(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS8(), libcomp::Packet::WriteString16Little(), and libcomp::Packet::WriteU16Little().
void MatchManager::EndUltimateBattle (const std::shared_ptr< Zone > & zone) private
Perform all end of match actions for an Ultimate Battle zone.
Parameters
zone Pointer to a zone with a match
Definition at line 4891 of file MatchManager.cpp.
References EndUltimateBattlePhase(), FirePhaseTriggers(), SendPhase(), and StartStopMatch().
Referenced by AdvancePhase(), LeaveUltimateBattle(), and UltimateBattleBegin().
bool MatchManager::EndUltimateBattlePhase (const std::shared_ptr< Zone > & zone, bool matchOver) private
Perform all end of phase actions for an Ultimate Battle zone for the current phase.
Parameters
zone Pointer to a zone with a match
matchOver If true the match ending actions will be performed as well such as registering UB points with the world
Returns
true if the phase was ended succesfully, false if an error occurred
Definition at line 4745 of file MatchManager.cpp.
References libcomp::String::Arg(), channel::ChannelClientConnection::BroadcastPacket(), libcomp::DatabaseChangeSet::Create(), channel::ClientState::GetCharacterState(), GetUBTournament(), channel::ClientState::GetWorldCID(), LoadUltimateBattleData(), mServer, channel::state(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS8(), and libcomp::Packet::WriteU32Little().
Referenced by EndUltimateBattle(), and StartUltimateBattleTimer().
void MatchManager::EnterDiaspora (const std::shared_ptr< ChannelClientConnection > & client, const std::shared_ptr< Zone > & zone)
Notify all Diaspora entries that a player has joined or changed zones and send the new player match information.
Parameters
client Pointer to the client connection
zone Pointer to the zone in the instance that is being entered
Definition at line 1650 of file MatchManager.cpp.
References libcomp::Convert::ENCODING_CP932, channel::ChannelServer::GetServerTime(), mServer, SendDiasporaLocation(), SendPhase(), libcomp::Packet::WriteFloat(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteString16Little(), and libcomp::Packet::WriteU32Little().
void MatchManager::EnterPvP (const std::shared_ptr< ChannelClientConnection > & client, uint32_t instanceID)
Notify all PvP entries that a player has joined or changed zones and send the new player the PvP match info.
Parameters
client Pointer to the client connection
instanceID ID of the instance the player should be in
Definition at line 1501 of file MatchManager.cpp.
References libcomp::Convert::ENCODING_CP932, channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), channel::ClientState::GetEntityClientState(), channel::ClientState::GetWorldCID(), channel::ClientState::GetZone(), InPvPTeam(), mServer, SendPvPLocation(), channel::state(), channel::ClientState::ToClientTime(), libcomp::Packet::WriteFloat(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS8(), libcomp::Packet::WriteString16Little(), and libcomp::Packet::WriteU8().
void MatchManager::EnterUltimateBattle (const std::shared_ptr< ChannelClientConnection > & client, const std::shared_ptr< Zone > & zone)
Notify all UB entries that a player has joined if they are a participant and send the new player match information.
If the player is spectator, they will be hidden and sent appropriate match information.
Parameters
client Pointer to the client connection
zone Pointer to the zone the player is entering
Definition at line 1699 of file MatchManager.cpp.
References channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), channel::ChannelServer::GetServerTime(), channel::ClientState::GetWorldCID(), mLock, mServer, SendPhase(), SendUltimateBattleMembers(), SendUltimateBattleMemberState(), channel::state(), UltimateBattleBegin(), and UltimateBattleTick().
void MatchManager::ExpirePvPAccess (uint32_t matchID)
Expire all pending invites to a PvP match.
Parameters
matchID Match ID to expire access to
Definition at line 859 of file MatchManager.cpp.
References libcomp::String::Arg(), mLock, mPendingPvPInvites, mServer, and PvPInviteReply().
Referenced by UpdatePvPMatches().
void MatchManager::FirePhaseTriggers (const std::shared_ptr< Zone > & zone, int8_t phase) private
Fire phase triggers associated to the supplied zone and any of its related zones or instance.
Parameters
zone Pointer to a zone with a match
phase Phase to fire triggers for
Definition at line 4944 of file MatchManager.cpp.
References mServer.
Referenced by AdvancePhase(), EndUltimateBattle(), StartStopMatch(), and UltimateBattleBegin().
std::shared_ptr< objects::MatchEntry > MatchManager::GetMatchEntry (int32_t cid)
Get current match entry associated to a world CID.
Parameters
cid World CID of the entry to retrieve
Returns
Pointer to the match entry or null if none exists
Definition at line 121 of file MatchManager.cpp.
References mLock, and mMatchEntries.
Referenced by CancelQueue(), CleanupPendingMatch(), JoinUltimateBattleQueue(), and ValidateMatchEntries().
std::shared_ptr< objects::PentalphaMatch > MatchManager::GetPentalphaMatch (bool previous)
Get the currently active (or previous) Pentalpha Match.
Parameters
previous If true the previous active match will be returned, if false the current active match will be returned
Returns
Pointer to a Pentalpha Match
Definition at line 3541 of file MatchManager.cpp.
References mLock, and mPentalphaMatches.
Referenced by LoadPentalphaData().
std::shared_ptr< objects::PvPData > MatchManager::GetPvPData (const std::shared_ptr< ChannelClientConnection > & client, bool create = false)
Get or create the specified client's PvPData.
Parameters
client Pointer to the client connection
create Optional parameter to create the data if it does not exist
Returns
Pointer to the PvPData, null if it was not created
Definition at line 1007 of file MatchManager.cpp.
References libcomp::DatabaseChangeSet::Create(), channel::ClientState::GetCharacterState(), mLock, mServer, and channel::state().
Referenced by ValidateMatchEntries().
void MatchManager::GetPvPTrophies (const std::shared_ptr< ZoneInstance > & instance) private
Calculate and assign all trophies earned during an instance's PvP match to the entity statistics for that instance.
Parameters
instance Pointer to the instance
Definition at line 4182 of file MatchManager.cpp.
References mServer.
Referenced by EndPvPMatch().
std::shared_ptr< objects::UBTournament > MatchManager::GetUBTournament () const
Get the currently active Ultimate Battle Tournament.
Returns
Pointer to the active Ultimate Battle Tournament
Definition at line 3388 of file MatchManager.cpp.
References mUBTournament.
Referenced by EndUltimateBattlePhase(), and LoadUltimateBattleData().
void MatchManager::IncreaseBaseBonus (int32_t baseID, uint32_t zoneID, uint32_t instanceID, uint64_t occupyStartTime)
Increase a captured base's bonus in the instance and grant points if applicable.
Parameters
baseID Entity ID of the base to increase
zoneID Unique ID of the zone the entity is in
instanceID Unique ID of the instance the base is in
occupyStartTime Start time of the entity's base occupation. If this does not match the value on the base, the increase will fail.
Definition at line 2020 of file MatchManager.cpp.
References mServer, PvPActive(), QueueNextBaseBonus(), and UpdatePvPPoints().
Referenced by QueueNextBaseBonus().
bool MatchManager::InPvPTeam (const std::shared_ptr< ActiveEntityState > & entity) static
Determine if the supplied entity is in a PvP team based upon the assigned faction group.
Parameters
entity Pointer to the entity to check
Returns
true if the entity is in a team, false if they are not
Definition at line 4044 of file MatchManager.cpp.
Referenced by EnterPvP(), MatchTeamsActive(), channel::ActionManager::UpdatePoints(), and UpdatePvPPoints().
bool MatchManager::IsPvPMatchEntry (const std::shared_ptr< objects::MatchEntry > & entry) static private
Determine if the supplied match entry is a PvP entry.
Parameters
entry Pointer to the MatchEntry to check
Returns
true if the entry is a PvP entry
Definition at line 5240 of file MatchManager.cpp.
Referenced by UpdateMatchEntries().
bool MatchManager::JoinQueue (const std::shared_ptr< ChannelClientConnection > & client, int8_t type)
Queue the supplied client for a match of the specified type.
Parameters
client Pointer to the client connection
type Match type to join
Definition at line 128 of file MatchManager.cpp.
References libcomp::String::Arg(), channel::ClientState::GetAccountUID(), channel::ClientState::GetWorldCID(), mServer, channel::state(), and ValidateMatchEntries().
bool MatchManager::JoinUltimateBattleQueue (int32_t worldCID, const std::shared_ptr< Zone > & zone)
Queue the supplied client for the Ultimate Battle match in the specified zone.
Parameters
worldCID World CID of the player to queue
zone Pointer to the zone with the pending match
Definition at line 777 of file MatchManager.cpp.
References GetMatchEntry(), mLock, mServer, libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteS32Little().
bool MatchManager::LeaveBase (const std::shared_ptr< ChannelClientConnection > & client, int32_t baseID)
Request to stop capturing a PvP base in the instance.
Parameters
client Pointer to the client connection
baseID Entity ID of the base to leave
Returns
true if the base capture cancel was valid
Definition at line 1860 of file MatchManager.cpp.
References channel::ClientState::GetCharacterState(), channel::ClientState::GetEventSourceEntityID(), channel::ClientState::GetZone(), mServer, channel::state(), libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteS32Little().
void MatchManager::LeaveTeam (const std::shared_ptr< ChannelClientConnection > & client, int32_t teamID)
Request to leave the client's team.
Parameters
client Pointer to the client connection
teamID ID of the team being left
Definition at line 404 of file MatchManager.cpp.
References channel::ClientState::GetWorldCID(), mServer, channel::state(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteU8().
void MatchManager::LeaveUltimateBattle (const std::shared_ptr< ChannelClientConnection > & client, const std::shared_ptr< Zone > & zone)
Notify all UB entries that a player has left if they are a participant.
Parameters
client Pointer to the client connection
zone Pointer to the zone the player is leaving
Definition at line 1763 of file MatchManager.cpp.
References EndUltimateBattle(), channel::ClientState::GetWorldCID(), mLock, SendUltimateBattleMembers(), and channel::state().
std::shared_ptr< objects::PentalphaEntry > MatchManager::LoadPentalphaData (const std::shared_ptr< ChannelClientConnection > & client, uint8_t idxFlags = 0x03)
Load and cache all Pentalpha Match information associated to the client.
Parameters
client Pointer to the client connection
idxFlags Flags indicating which information to load 0x01) Current match 0x02) Previous match
Returns
Pointer to the first requested entry, can be null
Definition at line 3996 of file MatchManager.cpp.
References channel::ClientState::GetCharacterState(), GetPentalphaMatch(), mServer, and channel::state().
std::shared_ptr< objects::UBResult > MatchManager::LoadUltimateBattleData (const std::shared_ptr< ChannelClientConnection > & client, uint8_t idxFlags = 0x03, bool createMissing = false)
Load and cache all Ultimate Battle information associated to the client.
Parameters
client Pointer to the client connection
idxFlags Flags indicating which information to load 0x01) Current results 0x02) All time results
createMissing If true, any missing record requested will be created
Returns
Pointer to the first requested result, can be null
Definition at line 3903 of file MatchManager.cpp.
References libcomp::DatabaseChangeSet::Create(), channel::ClientState::GetCharacterState(), GetUBTournament(), mServer, libcomp::PersistentObject::New(), and channel::state().
Referenced by EndUltimateBattlePhase(), SendUltimateBattleRankings(), and UpdateUBPoints().
bool MatchManager::MatchTeamsActive (const std::shared_ptr< ZoneInstance > & instance) static private
Determine if the supplied instance has active team members on both sides of a match.
Parameters
instance Pointer to the instance to check
Returns
true if both teams are active, false if at least one is not
Definition at line 5202 of file MatchManager.cpp.
References InPvPTeam().
Referenced by SendPvPLocation(), and StartPvPMatch().
void MatchManager::PlayerKilled (const std::shared_ptr< ActiveEntityState > & entity, const std::shared_ptr< ZoneInstance > & instance)
Special match handler for any primary player entities that were killed during a match.
This is responsible for doing things like scheduling auto-revival.
Parameters
entity Pointer to the player entity that was killed
instance Pointer to the instance the player was in when they were killed
Definition at line 2189 of file MatchManager.cpp.
References channel::ClientState::GetEntityClientState(), mServer, PvPActive(), and channel::state().
bool MatchManager::PvPActive (const std::shared_ptr< ZoneInstance > & instance) static
Determine if the supplied instance has an active PvP match being played.
Both pre and post timer active times will result in the match reporting as inactive.
Parameters
instance Pointer to the instance to check
Returns
true if the match is active, false if it is not
Definition at line 4038 of file MatchManager.cpp.
Referenced by CompleteBaseCapture(), EndPvPMatch(), IncreaseBaseBonus(), PlayerKilled(), QueueNextBaseBonus(), channel::ActionManager::UpdatePoints(), UpdatePvPPoints(), and channel::SkillManager::UpdatePvPStats().
bool MatchManager::PvPInviteReply (const std::shared_ptr< ChannelClientConnection > & client, uint32_t matchID, bool accept)
Respond to a PvP invite with with either an acceptane or rejection.
If the invite is rejected, the player's penalty count will be increased.
Parameters
client Pointer to the client connection
matchID Match ID to reply to
accept If true the invite is being accepted
Returns
true if the response was valid, false if it was not
Definition at line 949 of file MatchManager.cpp.
References libcomp::DBOperationalChangeSet::AddOperation(), libcomp::String::Arg(), channel::ClientState::GetAccountUID(), channel::ClientState::GetCharacterState(), channel::ClientState::GetWorldCID(), mLock, mPendingPvPInvites, mServer, and channel::state().
Referenced by CleanupPendingMatch(), ConfirmMatch(), ExpirePvPAccess(), and RejectPvPMatch().
void MatchManager::QueueNextBaseBonus (int32_t baseID, const std::shared_ptr< Zone > & zone, uint64_t occupyStartTime) private
Queue the next asynchronous base bonus increase in a match instance.
Parameters
baseID Entity ID of the base to update
zone Pointer to the zone the base is in
occupyStartTime Start time of the entity's base occupation
Definition at line 4921 of file MatchManager.cpp.
References IncreaseBaseBonus(), mServer, and PvPActive().
Referenced by CompleteBaseCapture(), and IncreaseBaseBonus().
void MatchManager::QueuePendingPvPMatch (uint8_t type, uint32_t readyTime) private
Create a PvPMatch with all pre-instance creation values and send it to the world to use if the match begins at the specified time.
Only one channel needs to handle this when new ready times are seen.
Parameters
type Standard PvP match type
readyTime Match ready time
Definition at line 4133 of file MatchManager.cpp.
References libcomp::String::Arg(), libcomp::Randomizer::GetEntry(), and mServer.
Referenced by UpdateMatchEntries().
void MatchManager::RejectPvPMatch (const std::shared_ptr< ChannelClientConnection > & client)
Reject entrance into a currently ready match.
Parameters
client Pointer to the client connection
Definition at line 383 of file MatchManager.cpp.
References PvPInviteReply(), channel::state(), and libcomp::Packet::WritePacketCode().
bool MatchManager::RequestTeamPvPMatch (const std::shared_ptr< ChannelClientConnection > & client, uint32_t variantID, uint32_t instanceID)
Validate and request a custom PvP match formed from the player's current team.
Parameters
client Pointer to the client connection
variantID ID of the variant to create
instanceID ID of the instance to create
Returns
true if the validation succeeded and the request was sent to the world server, false if the process failed
Definition at line 591 of file MatchManager.cpp.
References libcomp::String::Arg(), channel::ClientState::GetAccountUID(), libcomp::Randomizer::GetEntry(), channel::ClientState::GetWorldCID(), mServer, channel::state(), and ValidateMatchEntries().
bool MatchManager::ResetDiasporaBase (uint32_t zoneID, uint32_t instanceID, int32_t baseID, uint64_t resetTime)
Handler for Diaspora base automatic reset.
Parameters
zoneID Unique zone ID in the instance
instanceID ID of the zone instance the base is in
baseID Entity ID of the base
resetTime Timestamp that should match the capture time on the base. If it does not the operation will fail
Returns
true if the base was updated, false if it was not
Definition at line 2323 of file MatchManager.cpp.
References mServer, and ToggleDiasporaBase().
Referenced by ToggleDiasporaBase().
void MatchManager::SendDiasporaLocation (const std::shared_ptr< ChannelClientConnection > & client, uint32_t instanceID, bool enter, bool others = false)
Notify all Diaspora entries that a player has entered or left the instance.
Parameters
client Pointer to the client connection
instanceID ID of the instance affected
enter true if the instance is being entered, false if it is being left
others Optional parameter to perform the inverse notification to other members
Definition at line 3243 of file MatchManager.cpp.
References channel::ChannelClientConnection::BroadcastPacket(), libcomp::Convert::ENCODING_CP932, channel::ClientState::GetCharacterState(), channel::ClientState::GetWorldCID(), mServer, channel::state(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteString16Little(), and libcomp::Packet::WriteU32Little().
Referenced by EnterDiaspora().
void MatchManager::SendPhase (const std::shared_ptr< Zone > & zone, bool timerStart = false, const std::shared_ptr< ChannelClientConnection > & client = nullptr) private
Notify all players in a match zone of the current phase.
Parameters
zone Pointer to a zone with a match
timerStart Optional parameter to snap the timer reported to the full time instead of current time left for better client sync
client Pointer to client connection to send to instead of the entire zone
Definition at line 4974 of file MatchManager.cpp.
References channel::ChannelClientConnection::BroadcastPacket(), channel::ChannelServer::GetServerTime(), libcomp::Packet::WriteFloat(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteU32Little().
Referenced by AdvancePhase(), EndUltimateBattle(), EnterDiaspora(), EnterUltimateBattle(), and StartUltimateBattleTimer().
void MatchManager::SendPvPLocation (const std::shared_ptr< ChannelClientConnection > & client, uint32_t instanceID, bool enter)
Notify all PvP entries that a player has entered or left the instance.
Parameters
client Pointer to the client connection
instanceID ID of the instance affected
enter true if the instance is being entered, false if it is being left
Definition at line 3190 of file MatchManager.cpp.
References channel::ChannelClientConnection::BroadcastPacket(), libcomp::Convert::ENCODING_CP932, MatchTeamsActive(), mServer, libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS8(), and libcomp::Packet::WriteString16Little().
Referenced by EnterPvP().
void MatchManager::SendUltimateBattleMembers (const std::shared_ptr< Zone > & zone, const std::shared_ptr< ChannelClientConnection > & client = nullptr) private
Notify players in an Ultimate Battle zone of the current match participants.
This is also how the client acknowledges spectating.
Parameters
zone Pointer to a zone with a match
client Pointer to client connection to send to instead of the entire zone
Definition at line 5072 of file MatchManager.cpp.
References libcomp::Convert::ENCODING_CP932, channel::ClientState::GetWorldCID(), mServer, channel::state(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteString16Little(), and libcomp::Packet::WriteU32Little().
Referenced by EnterUltimateBattle(), and LeaveUltimateBattle().
void MatchManager::SendUltimateBattleMemberState (const std::shared_ptr< Zone > & zone, const std::shared_ptr< ChannelClientConnection > & client = nullptr) private
Notify players in an Ultimate Battle zone of the current match participant states.
Parameters
zone Pointer to a zone with a match
client Pointer to client connection to send to instead of the entire zone
Definition at line 5125 of file MatchManager.cpp.
References mServer, libcomp::Packet::WriteBlank(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS8(), libcomp::Packet::WriteU32Little(), and libcomp::Packet::WriteU8().
Referenced by EnterUltimateBattle(), and UltimateBattleTick().
void MatchManager::SendUltimateBattleRankings (const std::shared_ptr< ChannelClientConnection > & client)
Notify the client of their current Ultimate Battle rank information.
Parameters
client Pointer to the client connection
Definition at line 3309 of file MatchManager.cpp.
References channel::ClientState::GetClientStringEncoding(), LoadUltimateBattleData(), mServer, mUBRankings, channel::state(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS8(), libcomp::Packet::WriteString16Little(), and libcomp::Packet::WriteU32Little().
void MatchManager::SendZiotite (const std::shared_ptr< objects::Team > & team, const std::shared_ptr< ChannelClientConnection > & client = nullptr)
Send the supplied team's ziotite values to the supplied client or the full team.
Parameters
team Pointer to the team
client Optional parameter to send the update to only one client instead of the full team
Definition at line 566 of file MatchManager.cpp.
References channel::ChannelClientConnection::BroadcastPacket(), mServer, libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteS8().
Referenced by UpdateZiotite().
bool MatchManager::SpectatingMatch (const std::shared_ptr< ChannelClientConnection > & client, const std::shared_ptr< Zone > & zone) static
Determine if the supplied client is spectating a zone's Ultimate Battle match.
Parameters
client Pointer to the client connection
zone Pointer to the zone to check
Returns
true if they are configured to spectate, false if they are not
Definition at line 4050 of file MatchManager.cpp.
References channel::ClientState::GetWorldCID(), and channel::state().
Referenced by channel::ZoneManager::SendPopulateZoneData().
bool MatchManager::StartPvPBaseCapture (const std::shared_ptr< ChannelClientConnection > & client, int32_t baseID)
Request to start capturing a PvP base in the instance.
Parameters
client Pointer to the client connection
baseID Entity ID of the PvP base to capture
Returns
true if the base capture was valid
Definition at line 1802 of file MatchManager.cpp.
References CompleteBaseCapture(), channel::ClientState::GetCharacterState(), channel::ClientState::GetZone(), mServer, channel::state(), libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteS32Little().
void MatchManager::StartPvPMatch (uint32_t instanceID)
Start the PvP match in the specified instance.
Parameters
instanceID ID of the instance to start the match in
Definition at line 1049 of file MatchManager.cpp.
References libcomp::String::Arg(), MatchTeamsActive(), and mServer.
Referenced by CreatePvPInstance().
bool MatchManager::StartStopMatch (const std::shared_ptr< Zone > & zone, const std::shared_ptr< objects::Match > & match)
Start or stop a match associated to the supplied zone, its instance and other zones if they exist.
Ultimate Battle matches are restricted to only the supplied zone.
Parameters
zone Pointer to the zone to update Pointer to the match (or null) to set on the zone(s) and instance
Returns
true if the update was successful, false if nothing changed
Definition at line 2340 of file MatchManager.cpp.
References FirePhaseTriggers(), channel::ChannelServer::GetServerTime(), mLock, mServer, StartUltimateBattle(), and UltimateBattleQueue().
Referenced by CleanupPendingMatch(), EndUltimateBattle(), StartUltimateBattle(), and UltimateBattleRecruit().
bool MatchManager::StartUltimateBattle (const std::shared_ptr< Zone > & zone)
Move the Ultimate Battle match in the supplied zone from the Pre-Match to Ready state and send out any queue/recruit notifications or remove the match if no one is currently attempting to enter.
The match timer will not actually begin until the first player enters the zone.
Parameters
zone Pointer to the zone to update
Returns
true if the match started, false if it did not
Definition at line 2468 of file MatchManager.cpp.
References channel::ChannelClientConnection::BroadcastPacket(), libcomp::Randomizer::GetEntry(), channel::ChannelServer::GetServerTime(), mLock, mServer, StartStopMatch(), UltimateBattleBegin(), UltimateBattleRecruit(), UltimateBattleTick(), libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteS32Little().
Referenced by StartStopMatch(), and UltimateBattleQueue().
bool MatchManager::StartUltimateBattleTimer (const std::shared_ptr< Zone > & zone, uint32_t duration, const libcomp::String & eventID, bool endPhase)
Start a new timer for an Ultimate Battle match.
Parameters
zone Pointer to the zone with an active match
duration Duration of the timer
eventID ID of the event to fire when the timer expires
endPhase true if the phase is ending and the results should be sent, false if only the timer scheduling should be done
Returns
true if the timer was set, false if it was not
Definition at line 2761 of file MatchManager.cpp.
References libcomp::String::Arg(), EndUltimateBattlePhase(), channel::ChannelServer::GetServerTime(), mLock, and SendPhase().
bool MatchManager::ToggleDiasporaBase (const std::shared_ptr< Zone > & zone, int32_t baseID, int32_t sourceEntityID, bool capture)
Capture or reset a Diaspora base in the supplied zone.
Parameters
zone Pointer to the zone the base is in
baseID Entity ID of the base being toggled
sourceEntityID ID of the entity affecting the base
capture true if the base is being captured, false if it is being reset
Returns
true if the base was updated, false if it was not
Definition at line 2209 of file MatchManager.cpp.
References channel::ChannelServer::GetServerTime(), mLock, mServer, ResetDiasporaBase(), libcomp::Packet::WriteFloat(), libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteS32Little().
Referenced by ResetDiasporaBase().
void MatchManager::UltimateBattleBegin (uint32_t zoneID, uint32_t dynamicMapID, uint32_t instanceID)
Kick off the Ultimate Battle timer and begin the match.
If no members are currently there, the match will end instead.
Parameters
zoneID Definition ID of the zone to update
dynamicMapID Dynamic Map ID of the zone to update
instanceID Instance ID of the zone to update
Definition at line 2661 of file MatchManager.cpp.
References channel::ChannelClientConnection::BroadcastPacket(), CleanupPendingMatch(), EndUltimateBattle(), FirePhaseTriggers(), mLock, mServer, libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteS8().
Referenced by EnterUltimateBattle(), and StartUltimateBattle().
void MatchManager::UltimateBattleQueue (uint32_t zoneID, uint32_t dynamicMapID, uint32_t instanceID)
Pending Ultimate Battle queue handler that notifies players in the lobby before the match begins and causes the match to start.
Parameters
zoneID Definition ID of the zone with a match
dynamicMapID Dynamic Map ID of the zone with a match
instanceID Instance ID of the zone with a match
Definition at line 2931 of file MatchManager.cpp.
References channel::ChannelServer::GetServerTime(), mServer, StartUltimateBattle(), UltimateBattleQueue(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS8(), and libcomp::Packet::WriteU32Little().
Referenced by StartStopMatch(), and UltimateBattleQueue().
void MatchManager::UltimateBattleRecruit (uint32_t zoneID, uint32_t dynamicMapID, uint32_t instanceID)
Send a recruit request to players still waiting in the queue who were not selected for the initial set.
If the match is still full of players, the queue members will be notified accordingly.
Parameters
zoneID Definition ID of the zone to update
dynamicMapID Dynamic Map ID of the zone to update
instanceID Instance ID of the zone to update
Definition at line 2595 of file MatchManager.cpp.
References channel::ChannelClientConnection::BroadcastPacket(), mLock, mServer, RNG, StartStopMatch(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteS8().
Referenced by StartUltimateBattle().
bool MatchManager::UltimateBattleSpectate (int32_t worldCID, const std::shared_ptr< Zone > & zone)
Register the supplied world CID as an Ultimate Battle spectator for the specified zone's match.
The player still has to enter the zone after calling this.
Parameters
worldCID World CID of the player that will spectate
zone Pointer to the zone with an active or pending match
Returns
true if the player was registered successfully, false if they were not
Definition at line 2724 of file MatchManager.cpp.
References mLock, and mServer.
void MatchManager::UltimateBattleTick (uint32_t zoneID, uint32_t dynamicMapID, uint32_t instanceID)
Active Ultimate Battle "tick" handler that triggers actions for spawns and adjusts the gauge for non-UA matches.
Parameters
zoneID Definition ID of the zone with a match
dynamicMapID Dynamic Map ID of the zone with a match
instanceID Instance ID of the zone with a match
Definition at line 2998 of file MatchManager.cpp.
References channel::ChannelClientConnection::BroadcastPacket(), channel::ChannelServer::GetServerTime(), libcomp::String::IsEmpty(), mServer, SendUltimateBattleMemberState(), UltimateBattleTick(), libcomp::Packet::WriteFloat(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteU32Little().
Referenced by EnterUltimateBattle(), StartUltimateBattle(), and UltimateBattleTick().
void MatchManager::UpdateMatchEntries (const std::list< std::shared_ptr< objects::MatchEntry >> & updates, const std::list< std::shared_ptr< objects::MatchEntry >> & removes)
Synchronization handler for match queue entries that have been updated by the world server.
This is responsible for relaying packet information to the player when requests are sent to the world.
Parameters
updates List of pointers to match entry updates
removes List of pointers to match entry removes
Definition at line 3568 of file MatchManager.cpp.
References channel::ChannelServer::GetExpirationInSeconds(), IsPvPMatchEntry(), mLock, mMatchEntries, mServer, QueuePendingPvPMatch(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS16Little(), and libcomp::Packet::WriteS8().
void MatchManager::UpdatePentalphaMatch (const std::shared_ptr< objects::PentalphaMatch > & match)
Set the active Pentalpha Match and reload all entry info.
Parameters
match Pointer to the active Pentalpha Match
Definition at line 3548 of file MatchManager.cpp.
References libcomp::PersistentObject::LoadObjectByUUID(), mLock, mPentalphaMatches, and mServer.
void MatchManager::UpdatePvPMatches (const std::list< std::shared_ptr< objects::PvPMatch >> & matches)
Synchronization handler for PvP matches that have been updated (or created) by the world server.
This is responsible for preparing matches after the world has built or updated them.
Parameters
matches List of pointers to PvP match updates
Definition at line 3800 of file MatchManager.cpp.
References CreatePvPInstance(), ExpirePvPAccess(), channel::ChannelServer::GetExpirationInSeconds(), channel::ChannelServer::GetServerTime(), mLock, mPendingPvPInvites, mServer, channel::state(), channel::ClientState::ToClientTime(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteS8().
int32_t MatchManager::UpdatePvPPoints (uint32_t instanceID, std::shared_ptr< ActiveEntityState > source, std::shared_ptr< ActiveEntityState > target, int32_t points)
Update PvP match points for a specific source and target entity.
Parameters
instanceID ID of the instance where the match is taking place
source Pointer to the source of the point update
target Pointer to the target of the point update
points Number of points to add (or subtract)
Returns
Total number of points that were added
Definition at line 2062 of file MatchManager.cpp.
References channel::ClientState::GetCharacterState(), channel::ClientState::GetEntityClientState(), InPvPTeam(), and channel::state().
Referenced by CompleteBaseCapture(), and IncreaseBaseBonus().
int32_t MatchManager::UpdatePvPPoints (uint32_t instanceID, int32_t sourceID, int32_t targetID, uint8_t teamID, int32_t points, bool altMode)
Update PvP match points.
Parameters
instanceID ID of the instance where the match is taking place
sourceID Entity ID of the source of the point update
targetID Entity ID of the target of the point update
points Number of points to add (or subtract)
altMode Alternative point mode indicator that changes how the client displays the point notification
Returns
Total number of points that were added
Definition at line 2114 of file MatchManager.cpp.
References channel::ChannelClientConnection::BroadcastPacket(), mLock, mServer, PvPActive(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS8(), and libcomp::Packet::WriteU16Little().
bool MatchManager::UpdateUBPoints (const std::shared_ptr< ChannelClientConnection > & client, int32_t adjust)
Update the supplied client's Ultimate Battle points for the current tournament.
Parameters
client Pointer to the client connection
adjust Number of points to add
Returns
true if the update was valid, false if it was not
Definition at line 419 of file MatchManager.cpp.
References libcomp::DatabaseChangeSet::Create(), channel::ClientState::GetWorldCID(), channel::ClientState::GetZone(), LoadUltimateBattleData(), mLock, mServer, and channel::state().
void MatchManager::UpdateUBRankings (const std::list< std::shared_ptr< objects::UBResult >> & updated)
Synchronization handler for Ultimate Battle results that have been updated by the world server.
If none are specified, the entire ranking dataset will be reloaded
Parameters
updated List of pointers to UBResults
Definition at line 3415 of file MatchManager.cpp.
References mLock, mServer, mUBRankings, and mUBTournament.
Referenced by UpdateUBTournament().
void MatchManager::UpdateUBTournament (const std::shared_ptr< objects::UBTournament > & tournament)
Set the active Ultimate Battle Tournament and reload all ranking information.
Parameters
tournament Pointer to the active Ultimate Battle Tournament
Definition at line 3393 of file MatchManager.cpp.
References mLock, mUBTournament, and UpdateUBRankings().
bool MatchManager::UpdateZiotite (const std::shared_ptr< objects::Team > & team, int32_t sZiotite, int8_t lZiotite, int32_t worldCID = 0)
Update the small and large ziotite values for a team.
Updates set here will be sent to the world which has the final say for if the update was valid.
Parameters
team Pointer to the team to update
sZiotite Amount of small ziotite to add
lZiotite Amount of large ziotite to add
worldCID World CID of the player performing the update
Returns
true if the update was valid, false if it was not
Definition at line 487 of file MatchManager.cpp.
References mLock, mServer, SendZiotite(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS8(), and libcomp::Packet::WriteU8().
bool MatchManager::ValidateMatchEntries (const std::list< std::shared_ptr< ChannelClientConnection >> & clients, int8_t teamCategory, bool isTeam, bool checkPenalties) private
Determine if the supplied player clients are valid for match entry creation.
Parameters
clients Pointer to clients attempting to enter the queue
teamCategory Category of the type of team that would be created (even if the entry list is a solo player)
isTeam true if the clients are going to be part of a team, false if it is a solo entry
checkPenalties true if the number of PvP penalties that exist should be checked, assuming this is a PvP match request
Returns
true if the players validated, false if they did not
Definition at line 4610 of file MatchManager.cpp.
References libcomp::String::Arg(), GetMatchEntry(), GetPvPData(), channel::ClientState::GetZone(), and channel::state().
Referenced by JoinQueue(), and RequestTeamPvPMatch().
Member Data Documentation
std::mutex channel::MatchManager::mLock private
Server lock for shared resources.
Definition at line 736 of file MatchManager.h.
Referenced by AdvancePhase(), CleanupPendingMatch(), ConfirmMatch(), EnterUltimateBattle(), ExpirePvPAccess(), GetMatchEntry(), GetPentalphaMatch(), GetPvPData(), JoinUltimateBattleQueue(), LeaveUltimateBattle(), PvPInviteReply(), StartStopMatch(), StartUltimateBattle(), StartUltimateBattleTimer(), ToggleDiasporaBase(), UltimateBattleBegin(), UltimateBattleRecruit(), UltimateBattleSpectate(), UpdateMatchEntries(), UpdatePentalphaMatch(), UpdatePvPMatches(), UpdatePvPPoints(), UpdateUBPoints(), UpdateUBRankings(), UpdateUBTournament(), and UpdateZiotite().
std::unordered_map<int32_t, std::shared_ptr<objects::MatchEntry> > channel::MatchManager::mMatchEntries private
Local channel server copy of all current match queue entrants that are synchronized with the world server.
Definition at line 715 of file MatchManager.h.
Referenced by CleanupPendingMatch(), GetMatchEntry(), and UpdateMatchEntries().
std::unordered_map<uint32_t, std::set<int32_t> > channel::MatchManager::mPendingPvPInvites private
Time limited map of system expiration times to world CIDs of players that have been sent PvP match invitations.
Useful for expiring players who do not respond in time.
Definition at line 720 of file MatchManager.h.
Referenced by ExpirePvPAccess(), PvPInviteReply(), and UpdatePvPMatches().
std::array<std::shared_ptr<objects::PentalphaMatch>, 2> channel::MatchManager::mPentalphaMatches private
Pointers to the current and previous Pentalpha Matches.
Definition at line 730 of file MatchManager.h.
Referenced by GetPentalphaMatch(), and UpdatePentalphaMatch().
std::weak_ptr<ChannelServer> channel::MatchManager::mServer private
Pointer to the channel server.
Definition at line 733 of file MatchManager.h.
Referenced by AdvancePhase(), CancelQueue(), CleanupPendingMatch(), CompleteBaseCapture(), ConfirmMatch(), CreatePvPInstance(), EndPvPMatch(), EndUltimateBattlePhase(), EnterDiaspora(), EnterPvP(), EnterUltimateBattle(), ExpirePvPAccess(), FirePhaseTriggers(), GetPvPData(), GetPvPTrophies(), IncreaseBaseBonus(), JoinQueue(), JoinUltimateBattleQueue(), LeaveBase(), LeaveTeam(), LoadPentalphaData(), LoadUltimateBattleData(), PlayerKilled(), PvPInviteReply(), QueueNextBaseBonus(), QueuePendingPvPMatch(), RequestTeamPvPMatch(), ResetDiasporaBase(), SendDiasporaLocation(), SendPvPLocation(), SendUltimateBattleMembers(), SendUltimateBattleMemberState(), SendUltimateBattleRankings(), SendZiotite(), StartPvPBaseCapture(), StartPvPMatch(), StartStopMatch(), StartUltimateBattle(), ToggleDiasporaBase(), UltimateBattleBegin(), UltimateBattleQueue(), UltimateBattleRecruit(), UltimateBattleSpectate(), UltimateBattleTick(), UpdateMatchEntries(), UpdatePentalphaMatch(), UpdatePvPMatches(), UpdatePvPPoints(), UpdateUBPoints(), UpdateUBRankings(), and UpdateZiotite().
std::array<std::array<std::shared_ptr<objects::UBResult>, 10>, 4> channel::MatchManager::mUBRankings private
Map of currently reported UB top 10 rankings in the following order: all time total, top points, previous tournament, current tournament.
Definition at line 727 of file MatchManager.h.
Referenced by SendUltimateBattleRankings(), and UpdateUBRankings().
std::shared_ptr<objects::UBTournament> channel::MatchManager::mUBTournament private
Pointer to the current active UBTournament.
Definition at line 723 of file MatchManager.h.
Referenced by GetUBTournament(), UpdateUBRankings(), and UpdateUBTournament().
The documentation for this class was generated from the following files:
MatchManager.h
MatchManager.cpp