COMP_hack: channel::BazaarState Class Reference
channel::BazaarState Class Reference
Contains the state of an bazaar related to a channel.
#include <BazaarState.h>
Public Member Functions
BazaarState (const std::shared_ptr< objects::ServerBazaar > &bazaar)
Create a bazaar state.
virtual ~BazaarState ()
Clean up the bazaar state.
bool AddItem (ClientState *state, int8_t slot, int64_t itemID, int32_t price, std::shared_ptr< libcomp::DatabaseChangeSet > &dbChanges)
Add an item to the supplied client account's bazaar market.
bool BuyItem (std::shared_ptr< objects::BazaarItem > bItem)
Update the supplied BazaarItem to be marked as sold if no one else has already bought it.
std::shared_ptr
< objects::BazaarData > GetCurrentMarket (uint32_t marketID)
Get the current market associated to the supplied market ID.
std::shared_ptr
< objects::ServerBazaar > GetEntity ()
Get the entity.
void SetCurrentMarket (uint32_t marketID, const std::shared_ptr< objects::BazaarData > &data)
Set the current market mapped to the supplied market ID.
std::shared_ptr
< objects::BazaarItem > TryBuyItem (ClientState *state, uint32_t marketID, int8_t slot, int64_t itemID, int32_t price)
Get the item at the specified market that matches the requested information if it is currently available to purchase.
Static Public Member Functions
static bool DropItemFromMarket (ClientState *state, int8_t srcSlot, int64_t itemID, int8_t destSlot, std::shared_ptr< libcomp::DatabaseChangeSet > &dbChanges)
Drop an item from the supplied client account's bazaar market.
Private Member Functions
bool DropItem (ClientState *state, int8_t srcSlot, int64_t itemID, int8_t destSlot, std::shared_ptr< libcomp::DatabaseChangeSet > &dbChanges)
Drop an item from the supplied client account's bazaar market.
bool VerifyMarket (const std::shared_ptr< objects::BazaarData > &data)
Verify if the supplied bazaar market matches the current market assigned to its market ID.
Static Private Member Functions
static bool DropItemInternal (ClientState *state, int8_t srcSlot, int64_t itemID, int8_t destSlot, std::shared_ptr< libcomp::DatabaseChangeSet > &dbChanges)
Drop an item from the supplied client account's bazaar market.
Private Attributes
std::unordered_map< uint32_t,
std::shared_ptr
< objects::BazaarData > > mCurrentMarkets
Map of market IDs to account owned bazaar data representing an open market.
std::mutex mLock
Lock for shared resources.
Detailed Description
Contains the state of an bazaar related to a channel.
Definition at line 48 of file BazaarState.h.
Constructor & Destructor Documentation
BazaarState::BazaarState (const std::shared_ptr< objects::ServerBazaar > & bazaar)
Create a bazaar state.
Definition at line 49 of file BazaarState.cpp.
virtual channel::BazaarState::~BazaarState () inline virtual
Clean up the bazaar state.
Definition at line 59 of file BazaarState.h.
Member Function Documentation
bool BazaarState::AddItem (channel::ClientState * state, int8_t slot, int64_t itemID, int32_t price, std::shared_ptr< libcomp::DatabaseChangeSet > & dbChanges)
Add an item to the supplied client account's bazaar market.
This is thread safe and ensures the add is valid before anything is modified.
Parameters
state Pointer to the client state
slot Destination market slot for the item
itemID Client object ID of the item to add
price Price that the item should be sold for
dbChanges Output pointer to the DatabaseChangeSet to write all changes to
Returns
true on success, false on failure
Definition at line 71 of file BazaarState.cpp.
References libcomp::String::Arg(), channel::ClientState::GetAccountUID(), libcomp::PersistentObject::GetObjectByUUID(), channel::ClientState::GetObjectUUID(), mLock, and VerifyMarket().
bool BazaarState::BuyItem (std::shared_ptr< objects::BazaarItem > bItem)
Update the supplied BazaarItem to be marked as sold if no one else has already bought it.
Parameters
bItem Pointer to the item being purchased
Returns
true if the item can be bought, false if it cannot
Definition at line 219 of file BazaarState.cpp.
References mLock.
bool BazaarState::DropItem (ClientState * state, int8_t srcSlot, int64_t itemID, int8_t destSlot, std::shared_ptr< libcomp::DatabaseChangeSet > & dbChanges) private
Drop an item from the supplied client account's bazaar market.
This is thread safe and ensures the drop is valid before anything is modified.
Parameters
state Pointer to the client state
srcSlot Source market slot for the item
itemID Client object ID of the item to drop
destSlot Destination inventory slot for the item
dbChanges Output pointer to the DatabaseChangeSet to write all changes to
Returns
true on success, false on failure
Definition at line 249 of file BazaarState.cpp.
References DropItemInternal(), mLock, and VerifyMarket().
bool BazaarState::DropItemFromMarket (ClientState * state, int8_t srcSlot, int64_t itemID, int8_t destSlot, std::shared_ptr< libcomp::DatabaseChangeSet > & dbChanges) static
Drop an item from the supplied client account's bazaar market.
This is only thread safe if there is a BazaarState associated to the client. This function is responsible for stopping item drops for active markets.
Parameters
state Pointer to the client state
srcSlot Source market slot for the item
itemID Client object ID of the item to drop
destSlot Destination inventory slot for the item
dbChanges Output pointer to the DatabaseChangeSet to write all changes to
Returns
true on success, false on failure
Definition at line 134 of file BazaarState.cpp.
References DropItemInternal(), channel::ClientState::GetBazaarState(), and channel::ClientState::GetCurrentMenuShopID().
bool BazaarState::DropItemInternal (ClientState * state, int8_t srcSlot, int64_t itemID, int8_t destSlot, std::shared_ptr< libcomp::DatabaseChangeSet > & dbChanges) static private
Drop an item from the supplied client account's bazaar market.
This ensures the drop is valid before anything is modified.
Parameters
state Pointer to the client state
bState Pointer to the BazaarState to
srcSlot Source market slot for the item
itemID Client object ID of the item to drop
destSlot Destination inventory slot for the item
dbChanges Output pointer to the DatabaseChangeSet to write all changes to
Returns
true on success, false on failure
Definition at line 264 of file BazaarState.cpp.
References channel::ClientState::GetCharacterState(), libcomp::PersistentObject::GetObjectByUUID(), and channel::ClientState::GetObjectUUID().
Referenced by DropItem(), and DropItemFromMarket().
std::shared_ptr< objects::BazaarData > BazaarState::GetCurrentMarket (uint32_t marketID)
Get the current market associated to the supplied market ID.
Parameters
marketID ID of the market to retrieve
Returns
Pointer to the bazaar data representing the current market
Definition at line 54 of file BazaarState.cpp.
References mCurrentMarkets, and mLock.
Referenced by TryBuyItem().
std::shared_ptr<objects::ServerBazaar > channel::EntityState< objects::ServerBazaar >::GetEntity () inline inherited
Get the entity.
Returns
Pointer to the entity
Definition at line 59 of file EntityState.h.
Referenced by SetCurrentMarket(), and VerifyMarket().
void BazaarState::SetCurrentMarket (uint32_t marketID, const std::shared_ptr< objects::BazaarData > & data)
Set the current market mapped to the supplied market ID.
Parameters
marketID ID of the market to set
data Pointer to the bazaar data representing the current market
Definition at line 61 of file BazaarState.cpp.
References channel::EntityState< objects::ServerBazaar >::GetEntity(), mCurrentMarkets, and mLock.
std::shared_ptr< objects::BazaarItem > BazaarState::TryBuyItem (ClientState * state, uint32_t marketID, int8_t slot, int64_t itemID, int32_t price)
Get the item at the specified market that matches the requested information if it is currently available to purchase.
This is thread safe and should be followed up with a call to BuyItem upon success.
Parameters
state Pointer to the client state of the buyer
marketID Market ID for the item's market
slot Market slot where the item exists
itemID Client object ID of the item
price Price (in macca) that the buyer is expecting to pay
Returns
Pointer to the item that matches the requested information or nullptr if the request was not valid
Definition at line 165 of file BazaarState.cpp.
References libcomp::String::Arg(), GetCurrentMarket(), channel::ClientState::GetObjectUUID(), and mLock.
bool BazaarState::VerifyMarket (const std::shared_ptr< objects::BazaarData > & data) private
Verify if the supplied bazaar market matches the current market assigned to its market ID.
Parameters
data Pointer to the bazaar market to verify
Returns
true if the market matches, false if it does not
Definition at line 231 of file BazaarState.cpp.
References libcomp::String::Arg(), channel::EntityState< objects::ServerBazaar >::GetEntity(), and mCurrentMarkets.
Referenced by AddItem(), and DropItem().
Member Data Documentation
std::unordered_map<uint32_t, std::shared_ptr<objects::BazaarData> > channel::BazaarState::mCurrentMarkets private
Map of market IDs to account owned bazaar data representing an open market.
Definition at line 169 of file BazaarState.h.
Referenced by GetCurrentMarket(), SetCurrentMarket(), and VerifyMarket().
std::mutex channel::BazaarState::mLock private
Lock for shared resources.
Definition at line 172 of file BazaarState.h.
Referenced by AddItem(), BuyItem(), DropItem(), GetCurrentMarket(), SetCurrentMarket(), and TryBuyItem().
The documentation for this class was generated from the following files:
BazaarState.h
BazaarState.cpp