COMP_hack: channel::AllyState Class Reference
channel::AllyState Class Reference
Contains the state of an ally entity related to a channel as well as functionality to be used by the scripting engine for AI.
#include <AllyState.h>
Public Member Functions
AllyState ()
Create a new ally state.
virtual ~AllyState ()
Clean up the ally state.
size_t AddRemoveOpponent (bool add, int32_t opponentID)
Add or remove an opponent with the specified entity ID.
std::set< uint32_t > AddStatusEffects (const StatusEffectChanges &effects, libcomp::DefinitionManager *definitionManager, uint32_t now=0, bool queueChanges=true)
Add new status effects to the entity and activate them.
bool CanAct ()
Check if the entity is able to move or activate a skill.
std::set< uint32_t > CancelStatusEffects (uint8_t cancelFlags, const std::set< uint32_t > &keepEffects={})
Cancel existing status effects via cancel event flags.
std::set< uint32_t > CancelStatusEffects (uint8_t cancelFlags, bool &cancelled, const std::set< uint32_t > &keepEffects={})
Cancel existing status effects via cancel event flags.
bool CanMove (bool ignoreSkill=false)
Check if the entity is able to move.
virtual bool EntityIsSet () const
Check if the entity state has an entity set currently.
std::set< uint32_t > ExpireStatusEffects (const std::set< uint32_t > &effectTypes)
Expire existing status effects by effect type ID.
void ExpireStatusTimes (uint64_t now)
Expire any status times that have passed (including skill cooldowns)
std::shared_ptr< channel::AIState > GetAIState () const
Get the AIState of the entity.
virtual std::set< uint32_t > GetAllSkills (libcomp::DefinitionManager *definitionManager, bool includeTokusei)
Get all skills that the entity currently has available.
virtual std::shared_ptr
< objects::EntityStats > GetCoreStats ()
Get the core stats associated to the active entity.
int16_t GetCorrectValue (CorrectTbl tableID, std::shared_ptr< objects::CalculatedEntityState > calcState=nullptr)
Get the adjusted correct table value associated to the entity.
std::list< std::pair
< std::shared_ptr
< objects::StatusEffect >
, uint32_t > > GetCurrentStatusEffectStates (uint32_t now=0)
Get a snapshot of status effects currently on the entity with their corresponding expiration time which is based upon the supplied time for relative duration effects.
float GetDistance (float x, float y, bool squared=false)
Calculate the distance between the entity and the specified X and Y coordiates.
float GetDistance (std::shared_ptr< ActiveEntityState > other, bool squared=false)
Calculate the distance between this entity and another.
virtual std::shared_ptr
< objects::EnemyBase > GetEnemyBase () const
Get assigned entity as its EnemyBase representation or null if it does not apply.
std::shared_ptr< objects::Ally > GetEntity () const
Get the active entity.
libcomp::String GetEntityLabel () const
Get a label string formatted with the entity type, ID and demon type when applicable.
virtual const libobjgen::UUID GetEntityUUID ()
Get the entity UUID associated to the entity this state represents.
virtual int8_t GetGender ()
Get a numeric representation entity's gender.
uint32_t GetHitboxSize () const
Get the hitbox size for the current entity as defined by MiDevilData.
virtual int8_t GetLevel ()
Get the current level of the active entity.
virtual uint8_t GetLNCType ()
Get a numeric representation (also stored in constants) of the entity's current alignment.
float GetMovementSpeed (bool ignoreSkill=false, bool altSpeed=false)
Get the entity's adjusted movement speed.
int8_t GetNextActivatedAbilityID ()
Get the next activated ability ID from 0 to 127.
int16_t GetNRAChance (uint8_t nraIdx, CorrectTbl type, std::shared_ptr< objects::CalculatedEntityState > calcState=nullptr)
Get the entity's chance to null, reflect or absorb the specified affinity.
bool GetNRAShield (uint8_t nraIdx, CorrectTbl type, bool reduce)
Determine if the supplied NRA type/index effect shield is active on the entity and optionally decrease the effect by one if it is.
std::set< int32_t > GetOpponentIDs () const
Get the entity IDs of opponents this entity is in combat against.
const std::unordered_map
< uint32_t, std::shared_ptr
< objects::StatusEffect > > & GetStatusEffects () const
Get the current status effect map.
std::list< std::shared_ptr
< objects::StatusEffect > > GetStatusEffectsList ()
Get the list of current status effects.
int32_t GetWorldCID ()
Get the world CID associated to the entity.
std::shared_ptr< Zone > GetZone () const
Get the zone the entity currently exists in.
bool HasActiveEvent () const
Check if the entity is associated to a current event.
bool HasLineOfSight (std::shared_ptr< ActiveEntityState > other, uint64_t now=0)
Determine if the entity has line of sight to another, taking into account normal and one way barriers.
bool HasOpponent (int32_t opponentID=0)
Check if the entity has an opponent with the specified entity ID.
virtual bool HasSpecialTDamage ()
Check if the entity currently has active T-damage effects.
bool IsAlive () const
Check if the entity is currently alive.
virtual bool IsClientVisible ()
Check if the entity state is visible to any game client and should be included when sending entity definitions or movement actions.
bool IsLNCType (uint8_t lncType, bool invertFlag)
Check if the entity matches the supplied LNC type.
bool IsMounted ()
Check if the entity has a mount status indicating they are either a character or demon that is mounted.
bool IsMoving () const
Check if the entity is currently not at their destination position.
bool IsRotating () const
Check if the entity is currently not at their destination rotation.
void Move (float xPos, float yPos, uint64_t now)
Set the entity's destination position based on the supplied values and uses the current position values to set the origin.
uint8_t PopEffectTicks (uint32_t time, int32_t &hpTDamage, int32_t &mpTDamage, int32_t &tUpkeep, std::set< uint32_t > &added, std::set< uint32_t > &updated, std::set< uint32_t > &removed)
Pop effect events that have occurred past the specified time off the event mapping for the entity and their current zone.
virtual bool Ready (bool ignoreDisplayState=false)
Check if the entity state has everything needed to start being used.
virtual uint8_t RecalculateStats (libcomp::DefinitionManager *definitionManager, std::shared_ptr< objects::CalculatedEntityState > calcState=nullptr, std::shared_ptr< objects::MiSkillData > contextSkill=nullptr)
Recalculate the entity's stats, adjusted by equipment and effects.
void RefreshCurrentPosition (uint64_t now)
Update the entity's current position and rotation values based upon the source/destination ticks and the current time.
float RefreshKnockback (uint64_t time, float recoveryBoost, bool setValue=true)
Get or update the entity's current knockback value based on the last ticks associated to the value and the supplied time.
bool ResetUpkeep ()
Clear or reset any active skill upkeep costs timer.
void Rotate (float rot, uint64_t now)
Set the entity's destination rotation based on the supplied values and uses the current rotation values to set the origin.
bool SameFaction (std::shared_ptr< ActiveEntityState > other, bool ignoreGroup=false)
Check if the entity and another entity are in the same faction.
void SetAIState (const std::shared_ptr< channel::AIState > &aiState)
Set the AIState of the entity.
void SetEntity (const std::shared_ptr< objects::Ally > &entity, libcomp::DefinitionManager *definitionManager)
Set the active entity.
bool SetHPMP (int32_t hp, int32_t mp, bool adjust, bool canOverflow=false)
Set the HP and/or MP of the entity to either a specified or adjusted value.
bool SetHPMP (int32_t hp, int32_t mp, bool adjust, bool canOverflow, int32_t clenchChance, int32_t &hpAdjusted, int32_t &mpAdjusted)
Set the HP and/or MP of the entity to either a specified or adjusted value.
void SetStatusEffects (const std::list< std::shared_ptr< objects::StatusEffect >> &effects, libcomp::DefinitionManager *definitionManager)
Set the status effects currently on the entity.
void SetStatusEffectsActive (bool activate, libcomp::DefinitionManager *definitionManager, uint32_t now=0)
Activate or deactivate the entity's status effect states.
void SetZone (const std::shared_ptr< Zone > &zone, bool updatePrevious=true)
Set the entity's current zone.
bool SkillAvailable (uint32_t skillID)
Check if the entity has the supplied skill learned and not currently disabled.
bool StatusEffectActive (uint32_t effectType)
Determine if the supplied status effect is active on the entity.
uint32_t StatusEffectTimeLeft (uint32_t effectType)
Retrieve the time remaining on the supplied status effect.
void Stop (uint64_t now)
Stop the entity's movement based on the current postion information.
float UpdateKnockback (uint64_t now, float decrease, float recoveryBoost)
Refresh and then reduce the entity's knockback value.
bool UpdatePendingCombatants (int32_t entityID, uint64_t executeTime)
Update the entity's current pending combatants, removing any that are no longer valid and adding the supplied values if the time supplied is no later than the simultaneous hit window (100ms) of the earliest value already set.
Static Public Member Functions
static std::shared_ptr< AllyState > Cast (const std::shared_ptr< EntityStateObject > &obj)
Cast an EntityStateObject into an AllyState.
static float CorrectRotation (float rot)
Corrects rotation values that have exceeded the minimum or maximum allowed range.
Protected Member Functions
void ActivateStatusEffect (const std::shared_ptr< objects::StatusEffect > &effect, libcomp::DefinitionManager *definitionManager, uint32_t now, bool timeOnly)
Activate a status effect added to the entity's current status effect set.
void AdjustStats (const std::list< std::shared_ptr< objects::MiCorrectTbl >> &adjustments, libcomp::EnumMap< CorrectTbl, int32_t > &stats, std::shared_ptr< objects::CalculatedEntityState > calcState, bool baseMode)
Adjust the supplied correct table stat values based upon adjustments from equipment or status effects.
void ApplySkillCorrectTbls (const std::set< uint32_t > &skillIDs, libcomp::DefinitionManager *definitionManager, std::list< std::shared_ptr< objects::MiCorrectTbl >> &adjustments)
Apply a set of skill correct table value adjustments.
uint8_t CalculateLNCType (int16_t lncPoints) const
Calculate the numeric representation (also stored in constants) of the entity's alignment based off the supplied LNC point value.
uint8_t CompareAndResetStats (libcomp::EnumMap< CorrectTbl, int32_t > &stats, bool dependentBase)
Compare and set the entity's current stats and also keep track of if a change occurred.
uint8_t CompareAndResetStats (libcomp::EnumMap< CorrectTbl, int32_t > &stats)
Compare and set the entity's current stats and also keep track of if a change occurred.
void GetAdditionalCorrectTbls (libcomp::DefinitionManager *definitionManager, std::shared_ptr< objects::CalculatedEntityState > calcState, std::list< std::shared_ptr< objects::MiCorrectTbl >> &adjustments, std::shared_ptr< objects::MiSkillData > contextSkill=nullptr)
Get the correct table value adjustments from the entity's current skills and status effects.
std::set< uint32_t > GetAllEnemySkills (libcomp::DefinitionManager *definitionManager, bool includeTokusei)
Get all skills that the enemy or ally entity currently has available.
uint32_t GetCurrentExpiration (const std::shared_ptr< objects::StatusEffect > &effect, uint32_t nextTime, uint32_t now)
Calculate the relative or absolute expiration for an effect based upon the current system time and an absolute system time.
std::set< uint32_t > GetEffectiveTokuseiSkills (libcomp::DefinitionManager *definitionManager)
Get the set of skill IDs granted by effective tokusei.
bool IsIgnoreEffect (uint32_t effectType) const
Determine if the supplied status effect type can cause the entity to be ignored by AI entities.
uint8_t RecalculateDemonStats (libcomp::DefinitionManager *definitionManager, libcomp::EnumMap< CorrectTbl, int32_t > &stats, std::shared_ptr< objects::CalculatedEntityState > calcState, std::shared_ptr< objects::MiSkillData > contextSkill)
Recalculate a demon or enemy entity's stats.
uint8_t RecalculateEnemyStats (libcomp::DefinitionManager *definitionManager, std::shared_ptr< objects::CalculatedEntityState > calcState, std::shared_ptr< objects::MiSkillData > contextSkill)
Recalculate a entity's stats for an enemy or ally which have all types of state information in common.
void RegisterNextEffectTime ()
Register the entity's next effect event time with the current zone.
void RegisterStatusEffect (const std::shared_ptr< objects::StatusEffect > &effect, libcomp::DefinitionManager *definitionManager)
Set a status effect currently on the entity and register its cancel conditions.
void RemoveInactiveSwitchSkills ()
Remove any switch skills marked as active that are no longer available to the entity.
void RemoveStatusEffects (const std::set< uint32_t > &effectTypes)
Remove the set of supplied status effects from all registered collections.
void ResetAIIgnored ()
Reset the AIIgnored value on the entity based on their current state.
void SetNextEffectTime (uint32_t effectType, uint32_t time)
Set the next effect event time for a specified effect type for the entity's event map.
void UpdateNRAChances (libcomp::EnumMap< CorrectTbl, int32_t > &stats, std::shared_ptr< objects::CalculatedEntityState > calcState, const std::list< std::shared_ptr< objects::MiCorrectTbl >> &adjustments={})
Update the entity's calculated NRA chances for each affinity from base and equipment values.
Protected Attributes
std::shared_ptr< AIState > mAIState
Pointer to the AI state information bound to the entity.
bool mAlive
Signifies that the entity is alive.
std::unordered_map< uint8_t,
std::set< uint32_t > > mCancelConditions
Active effect type IDs mapped to cancel condition flags for quick access.
bool mCloaked
Signifies that the entity has the cloak status active.
std::shared_ptr< Zone > mCurrentZone
Pointer to the current zone the entity is in.
bool mEffectsActive
true if the status effects have been activated for the current zone
bool mInitialCalc
false if the entity has been assigned but never calculated
uint64_t mLastRefresh
Last timestamp the entity's state was refreshed.
std::mutex mLock
Server lock for shared resources.
int8_t mNextActivatedAbilityID
Next available activated ability ID.
std::map< uint32_t, std::set
< uint32_t > > mNextEffectTimes
Map of server system times mapped to the next event time associated to each active status effect.
uint32_t mNextRegenSync
Next system time when regen and timed damage will occur.
uint32_t mNextUpkeep
Next system time when skill upkeep costs will occur.
std::unordered_map< uint32_t,
libcomp::EnumMap< CorrectTbl,
std::set< uint8_t > > > mNRAShields
Map of effect type IDs to NRA types and NRA indexes.
std::set< int32_t > mOpponentIDs
Set of entity IDs representing opponents that the entity is currently fighting.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::MiStatusData > > mStatusEffectDefs
Map of active status effect definitions by effect type ID.
std::unordered_map< uint32_t,
std::shared_ptr
< objects::StatusEffect > > mStatusEffects
Map of active status effects by effect type ID.
std::set< uint32_t > mTimeDamageEffects
IDs of status effects currently active that deal time damage for quick access.
Detailed Description
Contains the state of an ally entity related to a channel as well as functionality to be used by the scripting engine for AI.
Definition at line 41 of file AllyState.h.
Constructor & Destructor Documentation
AllyState::AllyState ()
Create a new ally state.
Definition at line 64 of file AllyState.cpp.
virtual channel::AllyState::~AllyState () inline virtual
Clean up the ally state.
Definition at line 52 of file AllyState.h.
Member Function Documentation
void ActiveEntityState::ActivateStatusEffect (const std::shared_ptr< objects::StatusEffect > & effect, libcomp::DefinitionManager * definitionManager, uint32_t now, bool timeOnly) protected inherited
Activate a status effect added to the entity's current status effect set.
By activating an effect, it will be registered with the ActiveEntityState and its current zone via their absolute server time expiration in addition to setting any quick access properties on the entity.
Parameters
effect Pointer to the effect to activate
definitionManager Pointer to the DefinitionManager to use when determining how the effect behaves
now Current system timestamp to use when activating the effect
timeOnly true if only the time will be registered, should only be used if the expiration is being updated
Definition at line 1973 of file ActiveEntityState.cpp.
References EFFECT_CANCEL_DAMAGE, EFFECT_CANCEL_HIT, EFFECT_CANCEL_KNOCKBACK, libcomp::DefinitionManager::GetStatusData(), channel::ActiveEntityState::IsIgnoreEffect(), channel::ActiveEntityState::mAIState, channel::ActiveEntityState::mCloaked, channel::ActiveEntityState::mNextEffectTimes, channel::ActiveEntityState::mNRAShields, channel::ActiveEntityState::mStatusEffectDefs, channel::ActiveEntityState::mTimeDamageEffects, channel::NONE, channel::ActiveEntityState::ResetAIIgnored(), and SVR_CONST.
Referenced by channel::ActiveEntityState::AddStatusEffects(), and channel::ActiveEntityState::SetStatusEffectsActive().
size_t ActiveEntityState::AddRemoveOpponent (bool add, int32_t opponentID) inherited
Add or remove an opponent with the specified entity ID.
Parameters
add true if the opponent will be added, false if it will be removed
opponentID Entity ID of an opponent to add or remove
Returns
Number of opponents associated to the entity after the operation
Definition at line 1770 of file ActiveEntityState.cpp.
References channel::ActiveEntityState::mLock, and channel::ActiveEntityState::mOpponentIDs.
Referenced by channel::ZoneManager::LeaveZone().
std::set< uint32_t > ActiveEntityState::AddStatusEffects (const StatusEffectChanges & effects, libcomp::DefinitionManager * definitionManager, uint32_t now = 0, bool queueChanges = true) inherited
Add new status effects to the entity and activate them.
If there are status effects that are replaced by the application of the new ones they will be expired and returned.
Parameters
effects Map of status effects being changed
definitionManager Pointer to the DefinitionManager to use when determining how the effects behave
now Current system timestamp to use when activating the effects, defaults to the current time if not specified
queueChanges If true and the entity is in an effect active state, the effect inserts, updates and removes will be queued as the next entity time-based events to be processed by the next server tick. Set to false if the changes will be communicated by some other means
Returns
Set of expired effect IDs if any added effects cancel existing effects
Definition at line 903 of file ActiveEntityState.cpp.
References channel::ActiveEntityState::ActivateStatusEffect(), channel::ActiveEntityState::GetEntityUUID(), libcomp::DefinitionManager::GetStatusData(), channel::ActiveEntityState::mEffectsActive, channel::ActiveEntityState::mLock, channel::ActiveEntityState::mNextEffectTimes, channel::ActiveEntityState::mStatusEffects, channel::NONE, channel::ActiveEntityState::RegisterNextEffectTime(), channel::ActiveEntityState::RegisterStatusEffect(), and channel::ActiveEntityState::RemoveStatusEffects().
void ActiveEntityState::AdjustStats (const std::list< std::shared_ptr< objects::MiCorrectTbl >> & adjustments, libcomp::EnumMap< CorrectTbl, int32_t > & stats, std::shared_ptr< objects::CalculatedEntityState > calcState, bool baseMode) protected inherited
Adjust the supplied correct table stat values based upon adjustments from equipment or status effects.
Parameters
adjustments List of adjustments to the correct table values supplied
stats Output map parameter of base or calculated stats to adjust for the current entity
calcState Override CalculatedEntityState to use instead of the entity's default
baseMode If true only base stat correct table types will be adjusted, if false only the non-base stat correct table types will be adjusted and NRA values will be updated immediately.
Definition at line 2646 of file ActiveEntityState.cpp.
References channel::CharacterManager::AdjustStatBounds(), BASE_STATS, channel::TokuseiManager::CalculateAttributeValue(), FORCE_NUMERIC, channel::ActiveEntityState::GetCoreStats(), and SVR_CONST.
Referenced by channel::ActiveEntityState::RecalculateDemonStats().
void ActiveEntityState::ApplySkillCorrectTbls (const std::set< uint32_t > & skillIDs, libcomp::DefinitionManager * definitionManager, std::list< std::shared_ptr< objects::MiCorrectTbl >> & adjustments) protected inherited
Apply a set of skill correct table value adjustments.
Parameters
skillIDs Set of skill IDs on the entity
definitionManager Pointer to the DefinitionManager to use when determining how the skills behave
adjustments Output list parameter to add the adjustments to
Definition at line 3106 of file ActiveEntityState.cpp.
References libcomp::DefinitionManager::GetSkillData().
Referenced by channel::ActiveEntityState::GetAdditionalCorrectTbls().
uint8_t ActiveEntityState::CalculateLNCType (int16_t lncPoints) const protected inherited
Calculate the numeric representation (also stored in constants) of the entity's alignment based off the supplied LNC point value.
Parameters
lncPoints LNC points representing degrees of alignment
Returns
Numeric representation of the entity's current alignment
Definition at line 3302 of file ActiveEntityState.cpp.
bool ActiveEntityState::CanAct () inherited
Check if the entity is able to move or activate a skill.
Returns
true if the entity can act, false if it cannot
Definition at line 251 of file ActiveEntityState.cpp.
References channel::ActiveEntityState::CanMove(), channel::ActiveEntityState::mAlive, STATUS_HIT_STUN, and STATUS_KNOCKBACK.
std::set< uint32_t > ActiveEntityState::CancelStatusEffects (uint8_t cancelFlags, const std::set< uint32_t > & keepEffects = {}) inherited
Cancel existing status effects via cancel event flags.
The expire event will be queued up for processing on the next server tick unless effects are not active.
Parameters
cancelFlags Flags indicating conditions that can cause status effects to be cancelled. The set of valid status conditions are listed as constants on ActiveEntityState
keepEffects Optional set of status effects to keep
Returns
Set of cancelled status effect types that will not be queued
Definition at line 1372 of file ActiveEntityState.cpp.
std::set< uint32_t > ActiveEntityState::CancelStatusEffects (uint8_t cancelFlags, bool & cancelled, const std::set< uint32_t > & keepEffects = {}) inherited
Cancel existing status effects via cancel event flags.
The expire event will be queued up for processing on the next server tick unless effects are not active.
Parameters
cancelFlags Flags indicating conditions that can cause status effects to be cancelled. The set of valid status conditions are listed as constants on ActiveEntityState
cancelled Output parameter stating whether any effects were cancelled, independent of queuing
keepEffects Optional set of status effects to keep
Returns
Set of cancelled status effect types that will not be queued
Definition at line 1379 of file ActiveEntityState.cpp.
References channel::ActiveEntityState::ExpireStatusEffects(), channel::ActiveEntityState::mCancelConditions, and channel::ActiveEntityState::mLock.
bool ActiveEntityState::CanMove (bool ignoreSkill = false) inherited
Check if the entity is able to move.
Parameters
ignoreSkill Determines if all move conditions should be checked or just ones that don't pertain to a skill being used
Returns
true if the entity can move, false if it cannot
Definition at line 259 of file ActiveEntityState.cpp.
References channel::ActiveEntityState::GetCorrectValue(), channel::ActiveEntityState::mAlive, STATUS_CHARGING, STATUS_HIT_STUN, STATUS_IMMOBILE, STATUS_KNOCKBACK, and STATUS_RESTING.
Referenced by channel::ActiveEntityState::CanAct(), channel::ActiveEntityState::Move(), and channel::ActiveEntityState::Rotate().
std::shared_ptr< AllyState > AllyState::Cast (const std::shared_ptr< EntityStateObject > & obj) static
Cast an EntityStateObject into an AllyState.
Useful for script bindings.
Returns
Pointer to the casted AllyState
Definition at line 121 of file AllyState.cpp.
uint8_t ActiveEntityState::CompareAndResetStats (libcomp::EnumMap< CorrectTbl, int32_t > & stats, bool dependentBase) protected inherited
Compare and set the entity's current stats and also keep track of if a change occurred.
Parameters
stats Map of correct table IDs to calculated stats to set on the entity
dependentBase If true, only dependent stat base values will be checked and set. If false, final stats will be checked and set.
Returns
1 if the calculation resulted in a change to the stats that should be sent to the client, 2 if one of the changes should be communicated to the world (for party members etc), 0 if no change resulted from the recalculation
Definition at line 3371 of file ActiveEntityState.cpp.
References ENTITY_CALC_MOVE_SPEED, ENTITY_CALC_STAT_LOCAL, ENTITY_CALC_STAT_WORLD, and channel::ActiveEntityState::GetCoreStats().
Referenced by channel::ActiveEntityState::RecalculateDemonStats().
uint8_t channel::ActiveEntityState::CompareAndResetStats (libcomp::EnumMap< CorrectTbl, int32_t > & stats) protected inherited
Compare and set the entity's current stats and also keep track of if a change occurred.
Parameters
stats Map of correct table IDs to calculated stats to set on the entity
Returns
1 if the calculation resulted in a change to the stats that should be sent to the client, 2 if one of the changes should be communicated to the world (for party members etc), 0 if no change resulted from the recalculation
float ActiveEntityState::CorrectRotation (float rot) static inherited
Corrects rotation values that have exceeded the minimum or maximum allowed range.
Parameters
rot Original rotation value to correct
Returns
Equivalent but corrected rotation value
Definition at line 312 of file ActiveEntityState.cpp.
Referenced by channel::ZoneManager::GetEntitiesInFoV(), channel::SkillManager::ProcessSkillResult(), channel::ActiveEntityState::RefreshCurrentPosition(), and channel::ActiveEntityState::Rotate().
virtual bool channel::ActiveEntityStateImp< objects::Ally >::EntityIsSet () const inline virtual inherited
Check if the entity state has an entity set currently.
Under normal circumstances, this will always be true for all but partner demons.
Returns
true if an entity is set, otherwise false
Reimplemented from channel::ActiveEntityState.
Definition at line 1157 of file ActiveEntityState.h.
std::set< uint32_t > ActiveEntityState::ExpireStatusEffects (const std::set< uint32_t > & effectTypes) inherited
Expire existing status effects by effect type ID.
The expire event will be queued up for processing on the next server tick.
Parameters
effectTypes Set of effect type IDs to expire
Returns
Set of cancelled status effect types that will not be queued
Definition at line 1331 of file ActiveEntityState.cpp.
References channel::ActiveEntityState::mEffectsActive, channel::ActiveEntityState::mLock, channel::ActiveEntityState::mNextEffectTimes, channel::ActiveEntityState::mStatusEffects, channel::ActiveEntityState::RegisterNextEffectTime(), channel::ActiveEntityState::RemoveStatusEffects(), and channel::ActiveEntityState::SetNextEffectTime().
Referenced by channel::ActiveEntityState::CancelStatusEffects(), and channel::ActiveEntityState::GetNRAShield().
void ActiveEntityState::ExpireStatusTimes (uint64_t now) inherited
Expire any status times that have passed (including skill cooldowns)
Parameters
now Current timestamp of the server
Definition at line 579 of file ActiveEntityState.cpp.
Referenced by channel::SkillManager::Rest().
void ActiveEntityState::GetAdditionalCorrectTbls (libcomp::DefinitionManager * definitionManager, std::shared_ptr< objects::CalculatedEntityState > calcState, std::list< std::shared_ptr< objects::MiCorrectTbl >> & adjustments, std::shared_ptr< objects::MiSkillData > contextSkill = nullptr) protected inherited
Get the correct table value adjustments from the entity's current skills and status effects.
Parameters
definitionManager Pointer to the DefinitionManager to use when determining how the skills and effects behave
calcState Override CalculatedEntityState to use instead of the entity's default
adjustments Output list parameter to add the adjustments to
contextSkill Optional contextual skill to apply adjustments from. Essentially adjusts stats "while a skill is being used" which can vary between scenarios.
Definition at line 3038 of file ActiveEntityState.cpp.
References channel::ActiveEntityState::ApplySkillCorrectTbls(), libcomp::DefinitionManager::GetStatusData(), channel::ActiveEntityState::GetStatusEffects(), and libcomp::DefinitionManager::GetTokuseiData().
Referenced by channel::ActiveEntityState::RecalculateDemonStats().
std::shared_ptr< AIState > ActiveEntityState::GetAIState () const inherited
Get the AIState of the entity.
Returns
Pointer to the AIState of the entity or null if the entity is not AI controlled
Definition at line 607 of file ActiveEntityState.cpp.
References channel::ActiveEntityState::mAIState.
std::set< uint32_t > ActiveEntityState::GetAllEnemySkills (libcomp::DefinitionManager * definitionManager, bool includeTokusei) protected inherited
Get all skills that the enemy or ally entity currently has available.
Parameters
definitionManager Pointer to the definition manager to use for skill source definitions
includeTokusei false if tokusei skills should not be included
Returns
Set of all skill IDs the entity currently has available
Definition at line 3263 of file ActiveEntityState.cpp.
References channel::ActiveEntityState::GetEffectiveTokuseiSkills().
std::set< uint32_t > AllyState::GetAllSkills (libcomp::DefinitionManager * definitionManager, bool includeTokusei) virtual
Get all skills that the entity currently has available.
Parameters
definitionManager Pointer to the definition manager to use for skill source definitions
includeTokusei false if tokusei skills should not be included
Returns
Set of all skill IDs the entity currently has available
Reimplemented from channel::ActiveEntityState.
Definition at line 73 of file AllyState.cpp.
virtual std::shared_ptr<objects::EntityStats> channel::ActiveEntityStateImp< objects::Ally >::GetCoreStats () inline virtual inherited
Get the core stats associated to the active entity.
Returns
Pointer to the active entity's core stats
Reimplemented from channel::ActiveEntityState.
Definition at line 1139 of file ActiveEntityState.h.
int16_t ActiveEntityState::GetCorrectValue (CorrectTbl tableID, std::shared_ptr< objects::CalculatedEntityState > calcState = nullptr) inherited
Get the adjusted correct table value associated to the entity.
Parameters
tableID ID of the correct table value to retrieve
calcState Override CalculatedEntityState to use instead of the entity's default
Returns
Adjusted correct table value
Definition at line 152 of file ActiveEntityState.cpp.
Referenced by channel::ActiveEntityState::CanMove(), channel::ActiveEntityState::GetMovementSpeed(), channel::ActiveEntityState::PopEffectTicks(), and channel::ActiveEntityState::RefreshKnockback().
uint32_t ActiveEntityState::GetCurrentExpiration (const std::shared_ptr< objects::StatusEffect > & effect, uint32_t nextTime, uint32_t now) protected inherited
Calculate the relative or absolute expiration for an effect based upon the current system time and an absolute system time.
Parameters
effect Pointer to the effect to calculate the expiration of
nextTime Absolute system time to use when calculating the expiration
now Current system timestamp to use when activating the effect
Returns
Calculated expiration for the effect
Definition at line 2230 of file ActiveEntityState.cpp.
References channel::ActiveEntityState::mStatusEffectDefs, and channel::NONE.
Referenced by channel::ActiveEntityState::GetCurrentStatusEffectStates(), and channel::ActiveEntityState::SetStatusEffectsActive().
std::list< std::pair< std::shared_ptr< objects::StatusEffect >, uint32_t > > ActiveEntityState::GetCurrentStatusEffectStates (uint32_t now = 0) inherited
Get a snapshot of status effects currently on the entity with their corresponding expiration time which is based upon the supplied time for relative duration effects.
Parameters
now Current system timestamp to use for caculating relative duration expirations remaining, if nothing is specified, the current time will be used
Returns
List of current status effects paired with their expiration time remaining
Definition at line 1704 of file ActiveEntityState.cpp.
References channel::ActiveEntityState::GetCurrentExpiration(), channel::ActiveEntityState::mEffectsActive, channel::ActiveEntityState::mLock, channel::ActiveEntityState::mNextEffectTimes, and channel::ActiveEntityState::mStatusEffects.
Referenced by channel::ActiveEntityState::StatusEffectTimeLeft().
float ActiveEntityState::GetDistance (float x, float y, bool squared = false) inherited
Calculate the distance between the entity and the specified X and Y coordiates.
Parameters
x X coordinate to calculate the distance for
y Y coordinate to calculate the distance for
squared Optional parameter to return the distance squared for faster radius comparisons
Returns
Distance between the entity and the specified point
Definition at line 326 of file ActiveEntityState.cpp.
Referenced by channel::ActiveEntityState::GetDistance(), and channel::ActiveEntityState::Move().
float ActiveEntityState::GetDistance (std::shared_ptr< ActiveEntityState > other, bool squared = false) inherited
Calculate the distance between this entity and another.
Parameters
other Pointer to the other entity
squared Optional parameter to return the distance squared for faster radius comparisons
Returns
Distance between this entity and the other
Definition at line 333 of file ActiveEntityState.cpp.
References channel::ActiveEntityState::GetDistance().
std::set< uint32_t > ActiveEntityState::GetEffectiveTokuseiSkills (libcomp::DefinitionManager * definitionManager) protected inherited
Get the set of skill IDs granted by effective tokusei.
Parameters
definitionManager Pointer to the definition manager to use for tokusei definitions
Returns
Set of skill IDs granted by effective tokusei
Definition at line 3330 of file ActiveEntityState.cpp.
References libcomp::DefinitionManager::GetTokuseiData().
Referenced by channel::ActiveEntityState::GetAllEnemySkills().
std::shared_ptr< objects::EnemyBase > AllyState::GetEnemyBase () const virtual
Get assigned entity as its EnemyBase representation or null if it does not apply.
Returns
Pointer to the EnemyBase object
Reimplemented from channel::ActiveEntityState.
Definition at line 68 of file AllyState.cpp.
std::shared_ptr<objects::Ally > channel::ActiveEntityStateImp< objects::Ally >::GetEntity () const inline inherited
Get the active entity.
Returns
Pointer to the active entity
Definition at line 1125 of file ActiveEntityState.h.
libcomp::String ActiveEntityState::GetEntityLabel () const inherited
Get a label string formatted with the entity type, ID and demon type when applicable.
Used for logging.
Returns
Entity label string
Definition at line 124 of file ActiveEntityState.cpp.
References libcomp::String::Arg().
const libobjgen::UUID ActiveEntityState::GetEntityUUID () virtual inherited
Get the entity UUID associated to the entity this state represents.
Returns
Entity UUID or null UUID if not specified
Reimplemented in channel::CharacterState, and channel::DemonState.
Definition at line 159 of file ActiveEntityState.cpp.
Referenced by channel::ActiveEntityState::AddStatusEffects().
int8_t AllyState::GetGender () virtual
Get a numeric representation entity's gender.
The values are: 0) Male 1) Female 2) None/unspecified
Returns
Numeric representation of the entity's gender
Reimplemented from channel::ActiveEntityState.
Definition at line 110 of file AllyState.cpp.
uint32_t ActiveEntityState::GetHitboxSize () const inherited
Get the hitbox size for the current entity as defined by MiDevilData.
The value returned is not converted to relative server units.
Returns
Hitbox size
Definition at line 413 of file ActiveEntityState.cpp.
virtual int8_t channel::ActiveEntityStateImp< objects::Ally >::GetLevel () inline virtual inherited
Get the current level of the active entity.
Returns
Active entity's current level
Reimplemented from channel::ActiveEntityState.
Definition at line 1144 of file ActiveEntityState.h.
uint8_t AllyState::GetLNCType () virtual
Get a numeric representation (also stored in constants) of the entity's current alignment.
Returns
Numeric representation of the entity's current alignment
Reimplemented from channel::ActiveEntityState.
Definition at line 96 of file AllyState.cpp.
float ActiveEntityState::GetMovementSpeed (bool ignoreSkill = false, bool altSpeed = false) inherited
Get the entity's adjusted movement speed.
Parameters
ignoreSkill If true the current activated ability will be ignored for determining current speed state
altSpeed true if the alternate speed used for walking should be retrieved instead of the default run speed
Returns
Movement speed of the entity
Definition at line 371 of file ActiveEntityState.cpp.
References channel::ActiveEntityState::GetCorrectValue(), and channel::ChannelServer::GetServerTime().
Referenced by channel::ActiveEntityState::Move(), and channel::ActiveEntityState::Rotate().
int8_t ActiveEntityState::GetNextActivatedAbilityID () inherited
Get the next activated ability ID from 0 to 127.
Returns
The next activated ability ID for the client
Definition at line 1851 of file ActiveEntityState.cpp.
References channel::ActiveEntityState::mLock, and channel::ActiveEntityState::mNextActivatedAbilityID.
int16_t ActiveEntityState::GetNRAChance (uint8_t nraIdx, CorrectTbl type, std::shared_ptr< objects::CalculatedEntityState > calcState = nullptr) inherited
Get the entity's chance to null, reflect or absorb the specified affinity.
Parameters
nraIdx Correct table index for affinity NRA 1) Null 2) Reflect 3) Absorb Defines exist in the Constants header for each of these.
type Correct table type of the affinity to retrieve
calcState Override CalculatedEntityState to use instead of the entity's default
Returns
Integer representation of the chance to avoid affinity damage, 0 if the supplied values are invalid
Definition at line 1785 of file ActiveEntityState.cpp.
bool ActiveEntityState::GetNRAShield (uint8_t nraIdx, CorrectTbl type, bool reduce) inherited
Determine if the supplied NRA type/index effect shield is active on the entity and optionally decrease the effect by one if it is.
Parameters
nraIdx Correct table index for affinity NRA 1) Null 2) Reflect 3) Absorb Defines exist in the Constants header for each of these.
type Correct table type of the affinity to retrieve
reduce If true, the first matching NRA shield will be reduced by one
Returns
true if a shield effect existed, false if one did not
Definition at line 1806 of file ActiveEntityState.cpp.
References channel::ActiveEntityState::ExpireStatusEffects(), channel::ActiveEntityState::mLock, channel::ActiveEntityState::mNRAShields, and channel::ActiveEntityState::mStatusEffects.
std::set< int32_t > ActiveEntityState::GetOpponentIDs () const inherited
Get the entity IDs of opponents this entity is in combat against.
Returns
Set of opponent entity IDs
Definition at line 1758 of file ActiveEntityState.cpp.
References channel::ActiveEntityState::mOpponentIDs.
const std::unordered_map< uint32_t, std::shared_ptr< objects::StatusEffect > > & ActiveEntityState::GetStatusEffects () const inherited
Get the current status effect map.
Returns
Map of current status effects by type ID
Definition at line 834 of file ActiveEntityState.cpp.
References channel::ActiveEntityState::mStatusEffects.
Referenced by channel::ActiveEntityState::GetAdditionalCorrectTbls().
std::list< std::shared_ptr< objects::StatusEffect > > ActiveEntityState::GetStatusEffectsList () inherited
Get the list of current status effects.
Returns
List of status effects
Definition at line 840 of file ActiveEntityState.cpp.
References channel::ActiveEntityState::mLock, and channel::ActiveEntityState::mStatusEffects.
int32_t ActiveEntityState::GetWorldCID () inherited
Get the world CID associated to the entity.
Returns
World CID, 0 if not applicable
Definition at line 164 of file ActiveEntityState.cpp.
References channel::ClientState::GetEntityClientState(), channel::ClientState::GetWorldCID(), and channel::state().
std::shared_ptr< Zone > ActiveEntityState::GetZone () const inherited
Get the zone the entity currently exists in.
Returns
Pointer to the entity's current zone, nullptr if they are not currently in a zone
Definition at line 684 of file ActiveEntityState.cpp.
References channel::ActiveEntityState::mCurrentZone.
Referenced by channel::TokuseiManager::CalculateAttributeValue(), channel::SkillManager::ExecuteNormalSkill(), channel::SkillManager::FinalizeSkill(), channel::SkillManager::FinalizeSkillExecution(), channel::SkillManager::GetProcessingSkill(), channel::ActiveEntityState::HasLineOfSight(), channel::ActiveEntityState::PopEffectTicks(), channel::SkillManager::SendActivateSkill(), channel::SkillManager::SendCompleteSkill(), channel::SkillManager::SendExecuteSkill(), channel::SkillManager::SendExecuteSkillInstant(), and channel::ActiveEntityState::UpdatePendingCombatants().
bool ActiveEntityState::HasActiveEvent () const inherited
Check if the entity is associated to a current event.
Auto-only events do not apply here. This affects both types of player entities.
Returns
true if an event exists, false if one does not
Definition at line 170 of file ActiveEntityState.cpp.
References channel::ClientState::GetEntityClientState(), channel::ClientState::HasActiveEvent(), and channel::state().
bool ActiveEntityState::HasLineOfSight (std::shared_ptr< ActiveEntityState > other, uint64_t now = 0) inherited
Determine if the entity has line of sight to another, taking into account normal and one way barriers.
Parameters
other Pointer to the other entity
now Current timestamp of the server
Returns
true if the entity has line of sight
Definition at line 347 of file ActiveEntityState.cpp.
References channel::ChannelServer::GetServerTime(), channel::ActiveEntityState::GetZone(), and channel::ActiveEntityState::RefreshCurrentPosition().
bool ActiveEntityState::HasOpponent (int32_t opponentID = 0) inherited
Check if the entity has an opponent with the specified entity ID.
Parameters
opponentID Entity ID of an opponent to find or 0 to check for any
Returns
true if the entity ID is associated as an opponent to this entity
Definition at line 1763 of file ActiveEntityState.cpp.
References channel::ActiveEntityState::mLock, and channel::ActiveEntityState::mOpponentIDs.
bool ActiveEntityState::HasSpecialTDamage () virtual inherited
Check if the entity currently has active T-damage effects.
Returns
true if the entity has special T-damage effects, false if it does not
Reimplemented in channel::DemonState.
Definition at line 1675 of file ActiveEntityState.cpp.
Referenced by channel::ActiveEntityState::PopEffectTicks().
bool ActiveEntityState::IsAlive () const inherited
Check if the entity is currently alive.
Returns
true if the entity is alive, false if they are not
Definition at line 235 of file ActiveEntityState.cpp.
References channel::ActiveEntityState::mAlive.
virtual bool channel::ActiveEntityStateImp< objects::Ally >::IsClientVisible () inline virtual inherited
Check if the entity state is visible to any game client and should be included when sending entity definitions or movement actions.
Returns
true if the entity is visible, false if it is not
Reimplemented from channel::ActiveEntityState.
Definition at line 1162 of file ActiveEntityState.h.
bool ActiveEntityState::IsIgnoreEffect (uint32_t effectType) const protected inherited
Determine if the supplied status effect type can cause the entity to be ignored by AI entities.
Parameters
effectType Effect type to check
true if the effect is an ignore effect
Definition at line 2135 of file ActiveEntityState.cpp.
References SVR_CONST.
Referenced by channel::ActiveEntityState::ActivateStatusEffect(), channel::ActiveEntityState::RemoveStatusEffects(), and channel::ActiveEntityState::ResetAIIgnored().
bool ActiveEntityState::IsLNCType (uint8_t lncType, bool invertFlag) inherited
Check if the entity matches the supplied LNC type.
Parameters
lncType LNC tpe to compare to. This can be in two formats based upon the invertFlag parameter.
invertFlag If true compare using the inverted flag format
Returns
true if the LNC matches, false if it does not
Definition at line 2269 of file ActiveEntityState.cpp.
References channel::ActiveEntityState::GetLNCType().
bool ActiveEntityState::IsMounted () inherited
Check if the entity has a mount status indicating they are either a character or demon that is mounted.
Returns
true if the entity is mounted, false if it is not
Definition at line 2369 of file ActiveEntityState.cpp.
References channel::ActiveEntityState::StatusEffectActive(), and SVR_CONST.
bool ActiveEntityState::IsMoving () const inherited
Check if the entity is currently not at their destination position.
Returns
true if the entity is moving, false if they are not
Definition at line 240 of file ActiveEntityState.cpp.
bool ActiveEntityState::IsRotating () const inherited
Check if the entity is currently not at their destination rotation.
Returns
true if the entity is rotating, false if they are not
Definition at line 246 of file ActiveEntityState.cpp.
void ActiveEntityState::Move (float xPos, float yPos, uint64_t now) inherited
Set the entity's destination position based on the supplied values and uses the current position values to set the origin.
Communicating that the move has taken place must be done elsewhere.
Parameters
xPos X position to move to
yPos Y position to move to
now Server time to use as the origin ticks
Definition at line 181 of file ActiveEntityState.cpp.
References channel::ActiveEntityState::CanMove(), channel::ActiveEntityState::GetDistance(), and channel::ActiveEntityState::GetMovementSpeed().
uint8_t ActiveEntityState::PopEffectTicks (uint32_t time, int32_t & hpTDamage, int32_t & mpTDamage, int32_t & tUpkeep, std::set< uint32_t > & added, std::set< uint32_t > & updated, std::set< uint32_t > & removed) inherited
Pop effect events that have occurred past the specified time off the event mapping for the entity and their current zone.
Parameters
time System timestamp to use for comparing effect events that have passed
hpTDamage Output parameter to store the amount of HP time damage that should be dealt
mpTDamage Output parameter to store the amount of MP time damage that should be dealt
tUpkeep Output parameter to store skill upkeep cost that is being paid
added Output set to store the effect type IDs of newly added effects that have been queued since the specified time
updated Output set to store the effect type IDs of updated effects that have been queued since the specified time
removed Output set to store the effect type IDs of removed effects that have been queued since the specified time
Returns
Flag mask with the following flags: 1) At least one effect tick passed 2) Special T-damage effect occurred
Definition at line 1508 of file ActiveEntityState.cpp.
References channel::ActiveEntityState::GetCorrectValue(), channel::ActiveEntityState::GetZone(), channel::ActiveEntityState::HasSpecialTDamage(), channel::ActiveEntityState::mAlive, channel::ActiveEntityState::mEffectsActive, channel::ActiveEntityState::mLock, channel::ActiveEntityState::mNextEffectTimes, channel::ActiveEntityState::mNextRegenSync, channel::ActiveEntityState::mNextUpkeep, channel::ActiveEntityState::mStatusEffectDefs, channel::ActiveEntityState::mTimeDamageEffects, channel::ActiveEntityState::RegisterNextEffectTime(), channel::ActiveEntityState::RemoveStatusEffects(), and channel::ActiveEntityState::SetNextEffectTime().
virtual bool channel::ActiveEntityStateImp< objects::Ally >::Ready (bool ignoreDisplayState = false) inline virtual inherited
Check if the entity state has everything needed to start being used.
Parameters
ignoreDisplayState Optional parameter to ignore the display state of the entity and return true if the entity is at least set, defaults to false
Returns
true if the state is ready to use, otherwise false
Reimplemented from channel::ActiveEntityState.
Definition at line 1150 of file ActiveEntityState.h.
uint8_t ActiveEntityState::RecalculateDemonStats (libcomp::DefinitionManager * definitionManager, libcomp::EnumMap< CorrectTbl, int32_t > & stats, std::shared_ptr< objects::CalculatedEntityState > calcState, std::shared_ptr< objects::MiSkillData > contextSkill) protected inherited
Recalculate a demon or enemy entity's stats.
Parameters
definitionManager Pointer to the DefinitionManager to use when determining how effects and items interact with the entity
stats Map of correct table IDs to calculated stats to set on the entity. The values already in the map should be pre-dependent stat calculated values.
calcState Override CalculatedEntityState to use instead of the entity's default
contextSkill Contextual skill to apply adjustments from. Essentially adjusts stats "while a skill is being used" which can vary between scenarios.
Returns
1 if the calculation resulted in a change to the stats that should be sent to the client, 2 if one of the changes should be communicated to the world (for party members etc), 0 otherwise
Definition at line 3139 of file ActiveEntityState.cpp.
References channel::ActiveEntityState::AdjustStats(), channel::CharacterManager::CalculateDependentStats(), channel::ActiveEntityState::CompareAndResetStats(), channel::ActiveEntityState::GetAdditionalCorrectTbls(), channel::ActiveEntityState::GetCoreStats(), channel::ActiveEntityState::GetLevel(), channel::ActiveEntityState::mInitialCalc, and channel::ActiveEntityState::UpdateNRAChances().
Referenced by channel::ActiveEntityState::RecalculateEnemyStats().
uint8_t ActiveEntityState::RecalculateEnemyStats (libcomp::DefinitionManager * definitionManager, std::shared_ptr< objects::CalculatedEntityState > calcState, std::shared_ptr< objects::MiSkillData > contextSkill) protected inherited
Recalculate a entity's stats for an enemy or ally which have all types of state information in common.
Parameters
definitionManager Pointer to the DefinitionManager to use when determining how effects and items interact with the entity
calcState Override CalculatedEntityState to use instead of the entity's default
contextSkill Contextual skill to apply adjustments from. Essentially adjusts stats "while a skill is being used" which can vary between scenarios.
Returns
1 if the calculation resulted in a change to the stats that should be sent to the client, 2 if one of the changes should be communicated to the world (for party members etc), 0 otherwise
Definition at line 3192 of file ActiveEntityState.cpp.
References channel::ActiveEntityState::GetAllSkills(), channel::ActiveEntityState::GetCoreStats(), channel::ActiveEntityState::mAIState, and channel::ActiveEntityState::RecalculateDemonStats().
uint8_t AllyState::RecalculateStats (libcomp::DefinitionManager * definitionManager, std::shared_ptr< objects::CalculatedEntityState > calcState = nullptr, std::shared_ptr< objects::MiSkillData > contextSkill = nullptr) virtual
Recalculate the entity's stats, adjusted by equipment and effects.
Parameters
definitionManager Pointer to the DefinitionManager to use when determining how effects and items interact with the entity
calcState Override CalculatedEntityState to use instead of the entity's default. If a value is supplied for this, the entity's stats will not be updated as a result of the calculation, instead the supplied state will be updated to simulate "effective stats".
contextSkill Optional contextual skill to apply adjustments from. Essentially adjusts stats "while a skill is being used" which can vary between scenarios.
Returns
Flags indicating if the calculation resulted in a change that should be communicated to the client or world: 0x01) ENTITY_CALC_STAT_LOCAL = locallly visible stats were changed 0x02) ENTITY_CALC_STAT_WORLD = stats changed that are visible to the world 0x04) ENTITY_CALC_SKILL = skill set has changed (character only)
Reimplemented from channel::ActiveEntityState.
Definition at line 79 of file AllyState.cpp.
void ActiveEntityState::RefreshCurrentPosition (uint64_t now) inherited
Update the entity's current position and rotation values based upon the source/destination ticks and the current time.
If now matches the last refresh time, no work is done.
Parameters
now Current timestamp of the server
Definition at line 420 of file ActiveEntityState.cpp.
References channel::ActiveEntityState::CorrectRotation(), channel::ActiveEntityState::mLastRefresh, and channel::ActiveEntityState::mLock.
Referenced by channel::ActiveEntityState::HasLineOfSight().
float ActiveEntityState::RefreshKnockback (uint64_t time, float recoveryBoost, bool setValue = true) inherited
Get or update the entity's current knockback value based on the last ticks associated to the value and the supplied time.
If the value reaches or exceeds the maximum knockback resistance, the max value will be used and the last update tick will be cleared.
Parameters
time Timestamp from the server
recoveryBoost Recovery rate increase percentage
setValue Optional parameter to disable setting the value and only retrun the estimated value
Returns
Updated knockback value
Definition at line 617 of file ActiveEntityState.cpp.
References channel::ActiveEntityState::GetCorrectValue(), and channel::ActiveEntityState::mLock.
Referenced by channel::ActiveEntityState::UpdateKnockback().
void ActiveEntityState::RegisterNextEffectTime () protected inherited
Register the entity's next effect event time with the current zone.
Definition at line 2221 of file ActiveEntityState.cpp.
References channel::ActiveEntityState::mCurrentZone, channel::ActiveEntityState::mEffectsActive, and channel::ActiveEntityState::mNextEffectTimes.
Referenced by channel::ActiveEntityState::AddStatusEffects(), channel::ActiveEntityState::ExpireStatusEffects(), channel::ActiveEntityState::PopEffectTicks(), channel::ActiveEntityState::ResetUpkeep(), channel::ActiveEntityState::SetStatusEffects(), channel::ActiveEntityState::SetStatusEffectsActive(), and channel::ActiveEntityState::SetZone().
void ActiveEntityState::RegisterStatusEffect (const std::shared_ptr< objects::StatusEffect > & effect, libcomp::DefinitionManager * definitionManager) protected inherited
Set a status effect currently on the entity and register its cancel conditions.
Parameters
effect Pointer to a status effect to add to the entity
definitionManager Pointer to the DefinitionManager to use when determining how the effect behaves
Definition at line 2199 of file ActiveEntityState.cpp.
References libcomp::DefinitionManager::GetStatusData(), channel::ActiveEntityState::mCancelConditions, and channel::ActiveEntityState::mStatusEffects.
Referenced by channel::ActiveEntityState::AddStatusEffects(), and channel::ActiveEntityState::SetStatusEffects().
void ActiveEntityState::RemoveInactiveSwitchSkills () protected inherited
Remove any switch skills marked as active that are no longer available to the entity.
Definition at line 3318 of file ActiveEntityState.cpp.
void ActiveEntityState::RemoveStatusEffects (const std::set< uint32_t > & effectTypes) protected inherited
Remove the set of supplied status effects from all registered collections.
This function should not be called directly in place of being expired first.
Parameters
effectTypes Set of effect type IDs to remove
Definition at line 1880 of file ActiveEntityState.cpp.
References channel::ClientState::GetEntityClientState(), channel::ActiveEntityState::IsIgnoreEffect(), channel::ActiveEntityState::mAIState, channel::ActiveEntityState::mCancelConditions, channel::ActiveEntityState::mCloaked, channel::ActiveEntityState::mNRAShields, channel::ActiveEntityState::mStatusEffectDefs, channel::ActiveEntityState::mStatusEffects, channel::ActiveEntityState::mTimeDamageEffects, channel::ActiveEntityState::ResetAIIgnored(), channel::state(), and SVR_CONST.
Referenced by channel::ActiveEntityState::AddStatusEffects(), channel::ActiveEntityState::ExpireStatusEffects(), and channel::ActiveEntityState::PopEffectTicks().
void ActiveEntityState::ResetAIIgnored () protected inherited
Reset the AIIgnored value on the entity based on their current state.
Definition at line 2149 of file ActiveEntityState.cpp.
References channel::ActiveEntityState::IsIgnoreEffect(), and channel::ActiveEntityState::mStatusEffects.
Referenced by channel::ActiveEntityState::ActivateStatusEffect(), and channel::ActiveEntityState::RemoveStatusEffects().
bool ActiveEntityState::ResetUpkeep () inherited
Clear or reset any active skill upkeep costs timer.
Returns
true if an upkeep is active, false if there is no active upkeep
Definition at line 1680 of file ActiveEntityState.cpp.
References channel::ActiveEntityState::mLock, channel::ActiveEntityState::mNextUpkeep, channel::ActiveEntityState::RegisterNextEffectTime(), and channel::ActiveEntityState::SetNextEffectTime().
void ActiveEntityState::Rotate (float rot, uint64_t now) inherited
Set the entity's destination rotation based on the supplied values and uses the current rotation values to set the origin.
Communicating that the rotation has taken place must be done elsewhere.
Parameters
rot New rotation value to set
now Server time to use as the origin ticks
Definition at line 205 of file ActiveEntityState.cpp.
References channel::ActiveEntityState::CanMove(), channel::ActiveEntityState::CorrectRotation(), and channel::ActiveEntityState::GetMovementSpeed().
bool ActiveEntityState::SameFaction (std::shared_ptr< ActiveEntityState > other, bool ignoreGroup = false) inherited
Check if the entity and another entity are in the same faction.
Parameters
other Pointer to the other entity
ignoreGroup If true only the faction will be checked. If false the faction group will also be checked.
Returns
true if the entities are in the same faction
Definition at line 302 of file ActiveEntityState.cpp.
Referenced by channel::SkillManager::EvaluateTokuseiSkillCondition().
void ActiveEntityState::SetAIState (const std::shared_ptr< channel::AIState > & aiState) inherited
Set the AIState of the entity.
Parameters
Pointer to the AIState of the entity
Definition at line 612 of file ActiveEntityState.cpp.
References channel::ActiveEntityState::mAIState.
void channel::ActiveEntityStateImp< objects::Ally >::SetEntity (const std::shared_ptr< objects::Ally > & entity, libcomp::DefinitionManager * definitionManager) inherited
Set the active entity.
Parameters
entity Pointer to the active entity
definitionManager Pointer to the definition manager to use for definining entity definitions
bool ActiveEntityState::SetHPMP (int32_t hp, int32_t mp, bool adjust, bool canOverflow = false) inherited
Set the HP and/or MP of the entity to either a specified or adjusted value.
Use this instead of a raw EntityStats function to avoid conflicting updats running at the same time.
Parameters
hp Specified or adjusted HP value to apply
mp Specified or adjusted MP value to apply
adjust If true the supplied HP and MP values will be added to the current value instead of being set explicitly
canOverflow true if the entity can be changed from alive to dead and vice-versa
Returns
If adjust and canOverflow are both true, the returned value will be whether the entity's HP has overflowed. If one of those params is false, the returned value represents if the HP or MP were changed
Definition at line 701 of file ActiveEntityState.cpp.
bool ActiveEntityState::SetHPMP (int32_t hp, int32_t mp, bool adjust, bool canOverflow, int32_t clenchChance, int32_t & hpAdjusted, int32_t & mpAdjusted) inherited
Set the HP and/or MP of the entity to either a specified or adjusted value.
Use this instead of a raw EntityStats function to avoid conflicting updats running at the same time.
Parameters
hp Specified or adjusted HP value to apply
mp Specified or adjusted MP value to apply
adjust If true the supplied HP and MP values will be added to the current value instead of being set explicitly
canOverflow true if the entity can be changed from alive to dead and vice-versa
clenchChance Chance to survive a lethal hit from more than 1 starting HP, represented as a 2 decimal precision value (10000 = 100%)
hpAdjusted If not adjusting, this will be the HP damage dealt, otherwise it matches the value supplied
mpAdjusted If not adjusting, this will be the MP damage dealt, otherwise it matches the value supplied
Returns
If adjust and canOverflow are both true, the returned value will be whether the entity's HP has overflowed. If one of those params is false, the returned value represents if the HP or MP were changed
Definition at line 708 of file ActiveEntityState.cpp.
References channel::ActiveEntityState::GetCoreStats(), channel::ChannelServer::GetServerTime(), channel::ActiveEntityState::mAlive, channel::ActiveEntityState::mLock, RNG, and channel::ActiveEntityState::Stop().
void ActiveEntityState::SetNextEffectTime (uint32_t effectType, uint32_t time) protected inherited
Set the next effect event time for a specified effect type for the entity's event map.
The zone itself must be updated using RegisterNextEffectTime after each effect is set using this function.
Parameters
effectType Effect type ID to register an event for
time Absolute system time to register for the event
Definition at line 2167 of file ActiveEntityState.cpp.
References channel::ActiveEntityState::mNextEffectTimes.
Referenced by channel::ActiveEntityState::ExpireStatusEffects(), channel::ActiveEntityState::PopEffectTicks(), channel::ActiveEntityState::ResetUpkeep(), and channel::ActiveEntityState::SetStatusEffectsActive().
void ActiveEntityState::SetStatusEffects (const std::list< std::shared_ptr< objects::StatusEffect >> & effects, libcomp::DefinitionManager * definitionManager) inherited
Set the status effects currently on the entity.
Parameters
List of status effects currently on the entity
definitionManager Pointer to the DefinitionManager to use when determining how the effects behave
Definition at line 874 of file ActiveEntityState.cpp.
References channel::ActiveEntityState::mCancelConditions, channel::ActiveEntityState::mLock, channel::ActiveEntityState::mNextEffectTimes, channel::ActiveEntityState::mNextRegenSync, channel::ActiveEntityState::mNextUpkeep, channel::ActiveEntityState::mNRAShields, channel::ActiveEntityState::mStatusEffectDefs, channel::ActiveEntityState::mStatusEffects, channel::ActiveEntityState::mTimeDamageEffects, channel::ActiveEntityState::RegisterNextEffectTime(), and channel::ActiveEntityState::RegisterStatusEffect().
void ActiveEntityState::SetStatusEffectsActive (bool activate, libcomp::DefinitionManager * definitionManager, uint32_t now = 0) inherited
Activate or deactivate the entity's status effect states.
By activating effects, they will be registered with the ActiveEntityState and its current zone via their absolute server time expiration in addition to setting any quick access properties on the entity. By deactivating effects, they will be unregistered from the zone, the quick access properties will be cleared and the expiration time of relative effects will be updated.
Parameters
activate true if the effects will activated, else they will be deactivated
definitionManager Pointer to the DefinitionManager to use when determining how the effects behave
now Current system timestamp to use when activating the effects, defaults to the current time if not specified
Definition at line 1417 of file ActiveEntityState.cpp.
References channel::ActiveEntityState::ActivateStatusEffect(), channel::ActiveEntityState::EntityIsSet(), channel::ActiveEntityState::GetCurrentExpiration(), channel::ActiveEntityState::mCurrentZone, channel::ActiveEntityState::mEffectsActive, channel::ActiveEntityState::mLock, channel::ActiveEntityState::mNextEffectTimes, channel::ActiveEntityState::mNextRegenSync, channel::ActiveEntityState::mNextUpkeep, channel::ActiveEntityState::mStatusEffects, channel::ActiveEntityState::mTimeDamageEffects, channel::ActiveEntityState::RegisterNextEffectTime(), and channel::ActiveEntityState::SetNextEffectTime().
void ActiveEntityState::SetZone (const std::shared_ptr< Zone > & zone, bool updatePrevious = true) inherited
Set the entity's current zone.
Parameters
zone Pointer to the zone the entity has entered
updatePrevious true if the previous zone should be notified of the change, false if this is being handled elsewhere
Definition at line 689 of file ActiveEntityState.cpp.
References channel::ActiveEntityState::mCurrentZone, and channel::ActiveEntityState::RegisterNextEffectTime().
Referenced by channel::Zone::Cleanup().
bool ActiveEntityState::SkillAvailable (uint32_t skillID) inherited
Check if the entity has the supplied skill learned and not currently disabled.
Parameters
skillID ID of the skill to check
Returns
true if the skill is available, false if it is not
Definition at line 2264 of file ActiveEntityState.cpp.
bool ActiveEntityState::StatusEffectActive (uint32_t effectType) inherited
Determine if the supplied status effect is active on the entity.
Parameters
effectType Status effect type to look for
Returns
true if the status effect is active, false if it is not
Definition at line 853 of file ActiveEntityState.cpp.
References channel::ActiveEntityState::mLock, and channel::ActiveEntityState::mStatusEffects.
Referenced by channel::ActiveEntityState::IsMounted().
uint32_t ActiveEntityState::StatusEffectTimeLeft (uint32_t effectType) inherited
Retrieve the time remaining on the supplied status effect.
Parameters
effectType Status effect type to look for
Returns
Expiration time which is based upon the supplied time for relative duration effects
Definition at line 860 of file ActiveEntityState.cpp.
References channel::ActiveEntityState::GetCurrentStatusEffectStates().
void ActiveEntityState::Stop (uint64_t now) inherited
Stop the entity's movement based on the current postion information.
Communicating that the movement has stopped must be done elsewhere.
Parameters
now Server time to use as the origin ticks
Definition at line 223 of file ActiveEntityState.cpp.
Referenced by channel::ActiveEntityState::SetHPMP().
float ActiveEntityState::UpdateKnockback (uint64_t now, float decrease, float recoveryBoost) inherited
Refresh and then reduce the entity's knockback value.
If the value goes under zero, it will be set to zero.
Parameters
now Current timestamp of the server
decrease Value to decrease the knockback value by or -1.f to indicate a full decrease
recoveryBoost Recovery rate increase percentage
Definition at line 653 of file ActiveEntityState.cpp.
References channel::ActiveEntityState::mLock, and channel::ActiveEntityState::RefreshKnockback().
void ActiveEntityState::UpdateNRAChances (libcomp::EnumMap< CorrectTbl, int32_t > & stats, std::shared_ptr< objects::CalculatedEntityState > calcState, const std::list< std::shared_ptr< objects::MiCorrectTbl >> & adjustments = {}) protected inherited
Update the entity's calculated NRA chances for each affinity from base and equipment values.
NRA chances will further be modified for status effects within AdjustStats during the calculated stat mode.
Parameters
stats Map containing the base NRA values
calcState Override CalculatedEntityState to use instead of the entity's default
adjustments List of adjustments to the correct table values supplied by equipment
Definition at line 2974 of file ActiveEntityState.cpp.
Referenced by channel::ActiveEntityState::RecalculateDemonStats().
bool ActiveEntityState::UpdatePendingCombatants (int32_t entityID, uint64_t executeTime) inherited
Update the entity's current pending combatants, removing any that are no longer valid and adding the supplied values if the time supplied is no later than the simultaneous hit window (100ms) of the earliest value already set.
Once a value is added here, the corresponding pending skill can be queued to execute. If the value is not added, the skill should be retried again later.
Parameters
entityID ID of the entity that is attacking
executeTime Pending execution time of the skill if it were allowed to hit
Returns
true if the skill hit was added, false if it was not
Definition at line 503 of file ActiveEntityState.cpp.
References channel::ActiveEntityState::GetZone(), and channel::ActiveEntityState::mLock.
Member Data Documentation
std::shared_ptr<AIState> channel::ActiveEntityState::mAIState protected inherited
Pointer to the AI state information bound to the entity.
Definition at line 1098 of file ActiveEntityState.h.
Referenced by channel::ActiveEntityState::ActivateStatusEffect(), channel::ActiveEntityState::GetAIState(), channel::ActiveEntityState::RecalculateEnemyStats(), channel::ActiveEntityState::RemoveStatusEffects(), and channel::ActiveEntityState::SetAIState().
bool channel::ActiveEntityState::mAlive protected inherited
Signifies that the entity is alive.
Definition at line 1077 of file ActiveEntityState.h.
Referenced by channel::ActiveEntityState::CanAct(), channel::ActiveEntityState::CanMove(), channel::ActiveEntityState::IsAlive(), channel::ActiveEntityState::PopEffectTicks(), and channel::ActiveEntityState::SetHPMP().
std::unordered_map<uint8_t, std::set<uint32_t> > channel::ActiveEntityState::mCancelConditions protected inherited
Active effect type IDs mapped to cancel condition flags for quick access.
Definition at line 1047 of file ActiveEntityState.h.
Referenced by channel::ActiveEntityState::CancelStatusEffects(), channel::ActiveEntityState::RegisterStatusEffect(), channel::ActiveEntityState::RemoveStatusEffects(), and channel::ActiveEntityState::SetStatusEffects().
bool channel::ActiveEntityState::mCloaked protected inherited
Signifies that the entity has the cloak status active.
Definition at line 1083 of file ActiveEntityState.h.
Referenced by channel::ActiveEntityState::ActivateStatusEffect(), and channel::ActiveEntityState::RemoveStatusEffects().
std::shared_ptr<Zone> channel::ActiveEntityState::mCurrentZone protected inherited
Pointer to the current zone the entity is in.
Definition at line 1059 of file ActiveEntityState.h.
Referenced by channel::ActiveEntityState::GetZone(), channel::ActiveEntityState::RegisterNextEffectTime(), channel::ActiveEntityState::SetStatusEffectsActive(), and channel::ActiveEntityState::SetZone().
bool channel::ActiveEntityState::mEffectsActive protected inherited
true if the status effects have been activated for the current zone
Definition at line 1074 of file ActiveEntityState.h.
Referenced by channel::ActiveEntityState::AddStatusEffects(), channel::ActiveEntityState::ExpireStatusEffects(), channel::ActiveEntityState::GetCurrentStatusEffectStates(), channel::ActiveEntityState::PopEffectTicks(), channel::ActiveEntityState::RegisterNextEffectTime(), and channel::ActiveEntityState::SetStatusEffectsActive().
bool channel::ActiveEntityState::mInitialCalc protected inherited
false if the entity has been assigned but never calculated
Definition at line 1080 of file ActiveEntityState.h.
Referenced by channel::ActiveEntityState::RecalculateDemonStats().
uint64_t channel::ActiveEntityState::mLastRefresh protected inherited
Last timestamp the entity's state was refreshed.
Definition at line 1086 of file ActiveEntityState.h.
Referenced by channel::ActiveEntityState::RefreshCurrentPosition().
std::mutex channel::ActiveEntityState::mLock protected inherited
Server lock for shared resources.
Definition at line 1101 of file ActiveEntityState.h.
Referenced by channel::ActiveEntityState::AddRemoveOpponent(), channel::ActiveEntityState::AddStatusEffects(), channel::ActiveEntityState::CancelStatusEffects(), channel::ActiveEntityState::ExpireStatusEffects(), channel::ActiveEntityState::GetCurrentStatusEffectStates(), channel::ActiveEntityState::GetNextActivatedAbilityID(), channel::ActiveEntityState::GetNRAShield(), channel::ActiveEntityState::GetStatusEffectsList(), channel::ActiveEntityState::HasOpponent(), channel::ActiveEntityState::PopEffectTicks(), channel::ActiveEntityState::RefreshCurrentPosition(), channel::ActiveEntityState::RefreshKnockback(), channel::ActiveEntityState::ResetUpkeep(), channel::ActiveEntityState::SetHPMP(), channel::ActiveEntityState::SetStatusEffects(), channel::ActiveEntityState::SetStatusEffectsActive(), channel::ActiveEntityState::StatusEffectActive(), channel::ActiveEntityState::UpdateKnockback(), and channel::ActiveEntityState::UpdatePendingCombatants().
int8_t channel::ActiveEntityState::mNextActivatedAbilityID protected inherited
Next available activated ability ID.
Definition at line 1095 of file ActiveEntityState.h.
Referenced by channel::ActiveEntityState::GetNextActivatedAbilityID().
std::map<uint32_t, std::set<uint32_t> > channel::ActiveEntityState::mNextEffectTimes protected inherited
Map of server system times mapped to the next event time associated to each active status effect.
System effects are stored here as a 0. Actual effects will be stored here as reserved values 1 (inticating a new effect was added), 2 (indicating an efect has been updated) or 3 (indicating an effect has expired). Any other value stored will be an absolute system time when the regen, cost or T-Damage will be applied or the effect associated will be expired.
Definition at line 1056 of file ActiveEntityState.h.
Referenced by channel::ActiveEntityState::ActivateStatusEffect(), channel::ActiveEntityState::AddStatusEffects(), channel::ActiveEntityState::ExpireStatusEffects(), channel::ActiveEntityState::GetCurrentStatusEffectStates(), channel::ActiveEntityState::PopEffectTicks(), channel::ActiveEntityState::RegisterNextEffectTime(), channel::ActiveEntityState::SetNextEffectTime(), channel::ActiveEntityState::SetStatusEffects(), and channel::ActiveEntityState::SetStatusEffectsActive().
uint32_t channel::ActiveEntityState::mNextRegenSync protected inherited
Next system time when regen and timed damage will occur.
Definition at line 1089 of file ActiveEntityState.h.
Referenced by channel::ActiveEntityState::PopEffectTicks(), channel::ActiveEntityState::SetStatusEffects(), and channel::ActiveEntityState::SetStatusEffectsActive().
uint32_t channel::ActiveEntityState::mNextUpkeep protected inherited
Next system time when skill upkeep costs will occur.
Definition at line 1092 of file ActiveEntityState.h.
Referenced by channel::ActiveEntityState::PopEffectTicks(), channel::ActiveEntityState::ResetUpkeep(), channel::ActiveEntityState::SetStatusEffects(), and channel::ActiveEntityState::SetStatusEffectsActive().
std::unordered_map<uint32_t, libcomp::EnumMap<CorrectTbl, std::set<uint8_t> > > channel::ActiveEntityState::mNRAShields protected inherited
Map of effect type IDs to NRA types and NRA indexes.
This represents a 100% NRA result whenever a skill of the corresponding type is used which will decrease the effect stack until being cancelled out should it occur before the effect's expiration time.
Definition at line 1071 of file ActiveEntityState.h.
Referenced by channel::ActiveEntityState::ActivateStatusEffect(), channel::ActiveEntityState::GetNRAShield(), channel::ActiveEntityState::RemoveStatusEffects(), and channel::ActiveEntityState::SetStatusEffects().
std::set<int32_t> channel::ActiveEntityState::mOpponentIDs protected inherited
Set of entity IDs representing opponents that the entity is currently fighting.
If an entity is in this set, this entity should be in their set as well.
Definition at line 1064 of file ActiveEntityState.h.
Referenced by channel::ActiveEntityState::AddRemoveOpponent(), channel::ActiveEntityState::GetOpponentIDs(), and channel::ActiveEntityState::HasOpponent().
std::unordered_map<uint32_t, std::shared_ptr<objects::MiStatusData> > channel::ActiveEntityState::mStatusEffectDefs protected inherited
Map of active status effect definitions by effect type ID.
Definition at line 1039 of file ActiveEntityState.h.
Referenced by channel::ActiveEntityState::ActivateStatusEffect(), channel::ActiveEntityState::GetCurrentExpiration(), channel::ActiveEntityState::PopEffectTicks(), channel::ActiveEntityState::RemoveStatusEffects(), and channel::ActiveEntityState::SetStatusEffects().
std::unordered_map<uint32_t, std::shared_ptr<objects::StatusEffect> > channel::ActiveEntityState::mStatusEffects protected inherited
Map of active status effects by effect type ID.
Definition at line 1035 of file ActiveEntityState.h.
Referenced by channel::ActiveEntityState::AddStatusEffects(), channel::ActiveEntityState::ExpireStatusEffects(), channel::ActiveEntityState::GetCurrentStatusEffectStates(), channel::ActiveEntityState::GetNRAShield(), channel::ActiveEntityState::GetStatusEffects(), channel::ActiveEntityState::GetStatusEffectsList(), channel::ActiveEntityState::RegisterStatusEffect(), channel::ActiveEntityState::RemoveStatusEffects(), channel::ActiveEntityState::ResetAIIgnored(), channel::ActiveEntityState::SetStatusEffects(), channel::ActiveEntityState::SetStatusEffectsActive(), and channel::ActiveEntityState::StatusEffectActive().
std::set<uint32_t> channel::ActiveEntityState::mTimeDamageEffects protected inherited
IDs of status effects currently active that deal time damage for quick access.
Definition at line 1043 of file ActiveEntityState.h.
Referenced by channel::ActiveEntityState::ActivateStatusEffect(), channel::ActiveEntityState::PopEffectTicks(), channel::ActiveEntityState::RemoveStatusEffects(), channel::ActiveEntityState::SetStatusEffects(), and channel::ActiveEntityState::SetStatusEffectsActive().
The documentation for this class was generated from the following files:
AllyState.h
AllyState.cpp