COMP_hack: channel::ManagerConnection Class Reference
channel::ManagerConnection Class Reference
Class to handle messages pertaining to connecting to the world or game clients.
#include <ManagerConnection.h>
Public Member Functions
ManagerConnection (std::weak_ptr< libcomp::BaseServer > server)
Create a new manager.
virtual ~ManagerConnection ()
Clean up the manager.
void BroadcastPacketToClients (libcomp::Packet &packet)
Broadcast the supplied packet to each client connection stored.
std::list< std::shared_ptr
< ChannelClientConnection > > GatherWorldTargetClients (libcomp::ReadOnlyPacket &p, bool &success)
Read a list of world CIDs from the supplied packet and convert them to client connections.
std::list< std::shared_ptr
< ChannelClientConnection > > GetAllConnections ()
Get all client connections that currently exist.
const std::shared_ptr
< ChannelClientConnection > GetClientConnection (const libcomp::String &username)
Get client connection by username.
const std::shared_ptr
< ChannelClientConnection > GetEntityClient (int32_t id, bool worldID=false)
Get the client connection associated to the supplied entity ID.
std::list< std::shared_ptr
< ChannelClientConnection > > GetEntityClients (std::set< int32_t > ids, bool worldID=false)
Get all client connections associated to the supplied entity IDs.
std::list< std::shared_ptr
< ChannelClientConnection > > GetPartyConnections (const std::shared_ptr< ChannelClientConnection > &client, bool includeSelf, bool zoneRestrict)
Get all connections associated to the supplied connection's party currently on the channel, optionally restricted to the same zone.
virtual std::list
< libcomp::Message::MessageType > GetSupportedTypes () const
Get the different types of messages handled by this manager.
const std::shared_ptr
< libcomp::InternalConnection > GetWorldConnection () const
Get the world connection.
void HandleClientTimeouts (uint64_t now, uint16_t timeout)
Cycle through the current client connections and disconnect clients that not pinged the server for a while.
virtual bool ProcessMessage (const libcomp::Message::Message *pMessage)
Process a message from the queue.
void RemoveClientConnection (const std::shared_ptr< ChannelClientConnection > &client)
Remove a client connection.
void RequestWorldInfo ()
Send a request to the connected world for information to be handled once the response is received.
bool ScheduleClientTimeoutHandler (uint16_t timeout)
Schedule future server work to execute HandleClientTimeouts every 10 seconds.
void SetClientConnection (const std::shared_ptr< ChannelClientConnection > &client)
Set an active client connection after its account has been detected.
void SetWorldConnection (const std::shared_ptr< libcomp::InternalConnection > &worldConnection)
Set the world connection after establishing a connection.
Private Attributes
std::unordered_map
< libcomp::String,
std::shared_ptr
< ChannelClientConnection > > mClientConnections
Map of active client connections by account username.
std::mutex mLock
Server lock for shared resources.
std::weak_ptr
< libcomp::BaseServer > mServer
Pointer to the server that uses this manager.
std::shared_ptr
< libcomp::InternalConnection > mWorldConnection
Pointer to the world connection.
Static Private Attributes
static std::list
< libcomp::Message::MessageType > sSupportedTypes
Static list of supported message types for the manager.
Detailed Description
Class to handle messages pertaining to connecting to the world or game clients.
Definition at line 51 of file ManagerConnection.h.
Constructor & Destructor Documentation
ManagerConnection::ManagerConnection (std::weak_ptr< libcomp::BaseServer > server)
Create a new manager.
Parameters
server Pointer to the server that uses this manager
Definition at line 51 of file ManagerConnection.cpp.
ManagerConnection::~ManagerConnection () virtual
Clean up the manager.
Definition at line 56 of file ManagerConnection.cpp.
Member Function Documentation
void ManagerConnection::BroadcastPacketToClients (libcomp::Packet & packet)
Broadcast the supplied packet to each client connection stored.
Use sparingly!
Parameters
packet Packet to send
Definition at line 324 of file ManagerConnection.cpp.
References channel::ChannelClientConnection::BroadcastPacket(), mClientConnections, and mLock.
std::list< std::shared_ptr< ChannelClientConnection > > ManagerConnection::GatherWorldTargetClients (libcomp::ReadOnlyPacket & p, bool & success)
Read a list of world CIDs from the supplied packet and convert them to client connections.
Parameters
p Packet containing the connection list
success Output parameter which specifies that the packet was read was successful
Returns
List of client connections associated to the world CIDs in the packet
Definition at line 265 of file ManagerConnection.cpp.
References GetEntityClients().
std::list< std::shared_ptr< ChannelClientConnection > > ManagerConnection::GetAllConnections ()
Get all client connections that currently exist.
Returns
List of pointers to all client connections
Definition at line 220 of file ManagerConnection.cpp.
References mClientConnections, and mLock.
const std::shared_ptr< ChannelClientConnection > ManagerConnection::GetClientConnection (const libcomp::String & username)
Get client connection by username.
Parameters
username Client account username
Returns
Pointer to the client connection
Definition at line 143 of file ManagerConnection.cpp.
References mClientConnections, and mLock.
Referenced by GetEntityClient().
const std::shared_ptr< ChannelClientConnection > ManagerConnection::GetEntityClient (int32_t id, bool worldID = false)
Get the client connection associated to the supplied entity ID.
Parameters
id Entity ID or world ID associated to the client state to retrieve
worldID true if the ID is from the world, false if it is a local entity ID
Returns
Pointer to the client connection associated to the ID or nullptr if it does not exist
Definition at line 234 of file ManagerConnection.cpp.
References channel::ClientState::GetAccountUID(), GetClientConnection(), channel::ClientState::GetEntityClientState(), libcomp::PersistentObject::GetObjectByUUID(), and channel::state().
Referenced by GetEntityClients().
std::list< std::shared_ptr< ChannelClientConnection > > ManagerConnection::GetEntityClients (std::set< int32_t > ids, bool worldID = false)
Get all client connections associated to the supplied entity IDs.
Parameters
ids Entity IDs or world IDs associated to the client state to retrieve
worldID true if the IDs are from the world, false if they are local entity IDs
Returns
List of pointers to client connections associated to the IDs
Definition at line 248 of file ManagerConnection.cpp.
References GetEntityClient().
Referenced by GatherWorldTargetClients(), and GetPartyConnections().
std::list< std::shared_ptr< ChannelClientConnection > > ManagerConnection::GetPartyConnections (const std::shared_ptr< ChannelClientConnection > & client, bool includeSelf, bool zoneRestrict)
Get all connections associated to the supplied connection's party currently on the channel, optionally restricted to the same zone.
Parameters
client Pointer to the source client connection
includeSelf If true the source connection will be included in the returned set
zoneRestrict If true the connections will be restricted to only entities in the same zone
Returns
List of client connections in the same party
Definition at line 293 of file ManagerConnection.cpp.
References GetEntityClients(), channel::ClientState::GetZone(), and channel::state().
std::list< libcomp::Message::MessageType > ManagerConnection::GetSupportedTypes () const virtual
Get the different types of messages handled by this manager.
Returns
List of supported message types
Implements libcomp::Manager.
Definition at line 61 of file ManagerConnection.cpp.
References sSupportedTypes.
const std::shared_ptr< libcomp::InternalConnection > ManagerConnection::GetWorldConnection () const
Get the world connection.
Returns
Pointer to the world connection
Definition at line 133 of file ManagerConnection.cpp.
References mWorldConnection.
Referenced by RemoveClientConnection().
void ManagerConnection::HandleClientTimeouts (uint64_t now, uint16_t timeout)
Cycle through the current client connections and disconnect clients that not pinged the server for a while.
Parameters
now The current server time used to check for timeouts
timeout Time in seconds that needs to pass for a client connection to time out
Definition at line 354 of file ManagerConnection.cpp.
References libcomp::String::Arg(), mClientConnections, mLock, mWorldConnection, and libcomp::Packet::WritePacketCode().
bool ManagerConnection::ProcessMessage (const libcomp::Message::Message * pMessage) virtual
Process a message from the queue.
Parameters
pMessage Message to be processed.
Returns
true on success, false on failure
Implements libcomp::Manager.
Definition at line 66 of file ManagerConnection.cpp.
References libcomp::Message::CONNECTION_MESSAGE_CONNECTION_CLOSED, libcomp::Message::CONNECTION_MESSAGE_ENCRYPTED, libcomp::Message::Encrypted::GetConnection(), libcomp::Message::ConnectionClosed::GetConnection(), libcomp::Message::ConnectionMessage::GetConnectionMessageType(), mServer, mWorldConnection, RemoveClientConnection(), and RequestWorldInfo().
void ManagerConnection::RemoveClientConnection (const std::shared_ptr< ChannelClientConnection > & client)
Remove a client connection.
Parameters
client Pointer to the client connection
Definition at line 172 of file ManagerConnection.cpp.
References channel::ChannelServer::GetAccountManager(), GetWorldConnection(), channel::AccountManager::Logout(), mClientConnections, mLock, mServer, channel::state(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteString16Little(), and libcomp::Packet::WriteU32Little().
Referenced by ProcessMessage().
void ManagerConnection::RequestWorldInfo ()
Send a request to the connected world for information to be handled once the response is received.
Definition at line 119 of file ManagerConnection.cpp.
References mServer, mWorldConnection, libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteS8().
Referenced by ProcessMessage().
bool ManagerConnection::ScheduleClientTimeoutHandler (uint16_t timeout)
Schedule future server work to execute HandleClientTimeouts every 10 seconds.
Parameters
timeout Time in seconds that needs to pass for a client connection to time out
Returns
true if the work was scheduled, false if it was not
Definition at line 338 of file ManagerConnection.cpp.
References channel::ChannelServer::GetManagerConnection(), channel::ChannelServer::GetServerTime(), and mServer.
void ManagerConnection::SetClientConnection (const std::shared_ptr< ChannelClientConnection > & client)
Set an active client connection after its account has been detected.
Parameters
client Pointer to the client connection
Definition at line 151 of file ManagerConnection.cpp.
References mClientConnections, mLock, and channel::state().
void ManagerConnection::SetWorldConnection (const std::shared_ptr< libcomp::InternalConnection > & worldConnection)
Set the world connection after establishing a connection.
Parameters
worldConnection Pointer to the world connection
Definition at line 138 of file ManagerConnection.cpp.
References mWorldConnection.
Member Data Documentation
std::unordered_map<libcomp::String, std::shared_ptr<ChannelClientConnection> > channel::ManagerConnection::mClientConnections private
Map of active client connections by account username.
Definition at line 208 of file ManagerConnection.h.
Referenced by BroadcastPacketToClients(), GetAllConnections(), GetClientConnection(), HandleClientTimeouts(), RemoveClientConnection(), and SetClientConnection().
std::mutex channel::ManagerConnection::mLock private
Server lock for shared resources.
Definition at line 214 of file ManagerConnection.h.
Referenced by BroadcastPacketToClients(), GetAllConnections(), GetClientConnection(), HandleClientTimeouts(), RemoveClientConnection(), and SetClientConnection().
std::weak_ptr<libcomp::BaseServer> channel::ManagerConnection::mServer private
Pointer to the server that uses this manager.
Definition at line 211 of file ManagerConnection.h.
Referenced by ProcessMessage(), RemoveClientConnection(), RequestWorldInfo(), and ScheduleClientTimeoutHandler().
std::shared_ptr<libcomp::InternalConnection> channel::ManagerConnection::mWorldConnection private
Pointer to the world connection.
Definition at line 204 of file ManagerConnection.h.
Referenced by GetWorldConnection(), HandleClientTimeouts(), ProcessMessage(), RequestWorldInfo(), and SetWorldConnection().
std::list< libcomp::Message::MessageType > ManagerConnection::sSupportedTypes static private
Initial value:
=
    { libcomp::Message::MessageType::MESSAGE_TYPE_CONNECTION }
Static list of supported message types for the manager.
Definition at line 201 of file ManagerConnection.h.
Referenced by GetSupportedTypes().
The documentation for this class was generated from the following files:
ManagerConnection.h
ManagerConnection.cpp