COMP_hack: channel::ChannelSyncManager Class Reference
channel::ChannelSyncManager Class Reference
Channel specific implementation of the DataSyncManager in charge of performing server side update operations.
#include <ChannelSyncManager.h>
Public Member Functions
ChannelSyncManager (const std::weak_ptr< ChannelServer > &server)
Create a new ChannelSyncManager.
virtual ~ChannelSyncManager ()
Clean up the ChannelSyncManager.
libcomp::EnumMap
< objects::SearchEntry::Type_t,
std::list< std::shared_ptr
< objects::SearchEntry > > > GetSearchEntries () const
Get a map of all search entries by type.
std::list< std::shared_ptr
< objects::SearchEntry > > GetSearchEntries (objects::SearchEntry::Type_t type)
Get a list of all search entries of a specified type.
std::shared_ptr
< objects::EventCounter > GetWorldEventCounter (int32_t type)
Get the world level event counter of the specified type.
bool Initialize ()
Initialize the ChannelSyncManager after the world connection has been established.
std::shared_ptr< libcomp::Object > New ()
bool RegisterConnection (const std::shared_ptr< InternalConnection > &connection, std::set< std::string > types)
bool RemoveConnection (const std::shared_ptr< InternalConnection > &connection)
virtual bool RemoveRecord (const std::shared_ptr< libcomp::Object > &record, const libcomp::String &type)
void SyncComplete (const libcomp::String &type, const std::list< std::pair< std::shared_ptr< libcomp::Object >, bool >> &objs, const libcomp::String &source)
template<class T >
void SyncComplete (const libcomp::String &type, const std::list< std::pair< std::shared_ptr< libcomp::Object >, bool >> &objs, const libcomp::String &source)
Server specific handler for an operation following explicit types of non-persistent records being synced.
bool SyncIncoming (libcomp::ReadOnlyPacket &p, const libcomp::String &source="")
void SyncOutgoing ()
bool SyncRecordRemoval (const std::shared_ptr< libcomp::Object > &record, const libcomp::String &type)
bool SyncRecordUpdate (const std::shared_ptr< libcomp::Object > &record, const libcomp::String &type)
int8_t Update (const libcomp::String &type, const std::shared_ptr< libcomp::Object > &obj, bool isRemove, const libcomp::String &source)
template<class T >
int8_t Update (const libcomp::String &type, const std::shared_ptr< libcomp::Object > &obj, bool isRemove, const libcomp::String &source)
Server specific handler for explicit types of non-persistent records being updated.
virtual bool UpdateRecord (const std::shared_ptr< libcomp::Object > &record, const libcomp::String &type)
Protected Member Functions
void QueueOutgoing (const libcomp::String &type, const std::shared_ptr< InternalConnection > &connection, const std::set< std::shared_ptr< libcomp::Object >> &updates, const std::set< std::shared_ptr< libcomp::Object >> &removes)
void WriteOutgoingRecord (libcomp::Packet &p, bool isPersistent, const libcomp::String &type, const std::shared_ptr< libcomp::Object > &record)
Protected Attributes
std::mutex mLock
std::unordered_map
< std::string, std::shared_ptr
< ObjectConfig > > mRegisteredTypes
Static Protected Attributes
static const int8_t SYNC_FAILED
static const int8_t SYNC_HANDLED
static const int8_t SYNC_UPDATED
Private Attributes
std::unordered_map< int32_t,
std::shared_ptr
< objects::EventCounter > > mEventCounters
Map of world level event counters by type.
libcomp::EnumMap
< objects::SearchEntry::Type_t,
std::list< std::shared_ptr
< objects::SearchEntry > > > mSearchEntries
Map of all search entries on the world server by type.
std::weak_ptr< ChannelServer > mServer
Pointer to the channel server.
Detailed Description
Channel specific implementation of the DataSyncManager in charge of performing server side update operations.
Definition at line 52 of file ChannelSyncManager.h.
Constructor & Destructor Documentation
ChannelSyncManager::ChannelSyncManager (const std::weak_ptr< ChannelServer > & server)
Create a new ChannelSyncManager.
Parameters
server Pointer back to the channel server this belongs to.
Definition at line 91 of file ChannelSyncManager.cpp.
Referenced by Initialize().
ChannelSyncManager::~ChannelSyncManager () virtual
Clean up the ChannelSyncManager.
Definition at line 96 of file ChannelSyncManager.cpp.
Member Function Documentation
libcomp::EnumMap< objects::SearchEntry::Type_t, std::list< std::shared_ptr< objects::SearchEntry > > > ChannelSyncManager::GetSearchEntries () const
Get a map of all search entries by type.
Returns
Map of all search entries by type
Definition at line 222 of file ChannelSyncManager.cpp.
References mSearchEntries.
std::list< std::shared_ptr< objects::SearchEntry > > ChannelSyncManager::GetSearchEntries (objects::SearchEntry::Type_t type)
Get a list of all search entries of a specified type.
Returns
List of all search entries of a specified type
Definition at line 228 of file ChannelSyncManager.cpp.
References libcomp::DataSyncManager::mLock, and mSearchEntries.
std::shared_ptr< objects::EventCounter > ChannelSyncManager::GetWorldEventCounter (int32_t type)
Get the world level event counter of the specified type.
Returns
Pointer to the world level event counter, can be null
Definition at line 239 of file ChannelSyncManager.cpp.
References mEventCounters, and libcomp::DataSyncManager::mLock.
bool ChannelSyncManager::Initialize ()
Initialize the ChannelSyncManager after the world connection has been established.
Returns
false if any errors were encountered and the server should be shut down.
Definition at line 100 of file ChannelSyncManager.cpp.
References ChannelSyncManager(), mEventCounters, libcomp::DataSyncManager::mRegisteredTypes, mServer, and libcomp::DataSyncManager::RegisterConnection().
template<class T > void channel::ChannelSyncManager::SyncComplete (const libcomp::String & type, const std::list< std::pair< std::shared_ptr< libcomp::Object >, bool >> & objs, const libcomp::String & source)
Server specific handler for an operation following explicit types of non-persistent records being synced.
Parameters
type Type name of the object being updated
objs List of pointers to the records being updated and a flag indicating if the object was being removed
source Source server identifier
template<class T > int8_t channel::ChannelSyncManager::Update (const libcomp::String & type, const std::shared_ptr< libcomp::Object > & obj, bool isRemove, const libcomp::String & source)
Server specific handler for explicit types of non-persistent records being updated.
Parameters
type Type name of the object being updated
obj Pointer to the record definition
isRemove true if the record is being removed, false if it is either an insert or an update
source Identifier for the server sending the updates
Returns
Response codes matching the internal DataSyncManager set
Member Data Documentation
std::unordered_map<int32_t, std::shared_ptr<objects::EventCounter> > channel::ChannelSyncManager::mEventCounters private
Map of world level event counters by type.
Definition at line 127 of file ChannelSyncManager.h.
Referenced by GetWorldEventCounter(), and Initialize().
libcomp::EnumMap<objects::SearchEntry::Type_t, std::list<std::shared_ptr<objects::SearchEntry> > > channel::ChannelSyncManager::mSearchEntries private
Map of all search entries on the world server by type.
Definition at line 123 of file ChannelSyncManager.h.
Referenced by GetSearchEntries().
std::weak_ptr<ChannelServer> channel::ChannelSyncManager::mServer private
Pointer to the channel server.
Definition at line 130 of file ChannelSyncManager.h.
Referenced by Initialize().
The documentation for this class was generated from the following files:
ChannelSyncManager.h
ChannelSyncManager.cpp