COMP_hack: channel::FusionManager Class Reference
channel::FusionManager Class Reference
Manager class used to handle all demon fusion based actions.
#include <FusionManager.h>
Public Member Functions
FusionManager (const std::weak_ptr< ChannelServer > &server)
Create a new FusionManager.
virtual ~FusionManager ()
Clean up the FusionManager.
void EndExchange (const std::shared_ptr< channel::ChannelClientConnection > &client)
End any fusion based exchanges the player is a part of.
size_t GetMitamaIndex (uint32_t mitamaType, bool &found)
Get the mitama index of the supplied type that matches the FusionTables entries.
uint32_t GetResultDemon (const std::shared_ptr< ChannelClientConnection > &client, int64_t demonID1, int64_t demonID2, int64_t demonID3)
Calculate the resulting demon based upon the supplied demon IDs.
bool HandleFusion (const std::shared_ptr< ChannelClientConnection > &client, int64_t demonID1, int64_t demonID2, uint32_t costItemType=0)
Perform a normal 2-way fusion and respond to the client with the results.
bool HandleTriFusion (const std::shared_ptr< ChannelClientConnection > &client, int64_t demonID1, int64_t demonID2, int64_t demonID3, bool soloFusion)
Perform a tri-fusion and respond to the client with the results.
bool IsTriFusionValid (const std::shared_ptr< objects::Demon > &demon)
Determine if the supplied demon is valid to use for tri-fusion.
Private Member Functions
int8_t GetAdjustedLevelSum (uint8_t level1, uint8_t level2, int8_t finalLevelAdjust=0)
Sum up and average the demon levels supplied and optionally offset with a final adjustment value.
uint32_t GetElementalFuseResult (uint32_t elementalType, uint8_t otherRace, uint32_t otherType)
Get the demon type ID associated to an elemental to non-elemental fusion.
size_t GetElementalIndex (uint32_t elemType, bool &found)
Get the elemental index of the supplied type that matches the FusionTables entries.
uint32_t GetElementalType (size_t elementalIndex) const
Get the demon type ID associated to an elemental index from the manager.
uint32_t GetMitamaType (size_t mitamaIndex) const
Get the demon type ID associated to a mitama index from the manager.
size_t GetRaceIndex (uint8_t raceID, bool &found)
Get the race index of the supplied race that matches the FusionTables entries.
std::shared_ptr
< objects::MiDevilData > GetResultDemon (uint8_t race, int8_t adjustedLevelSum)
Get the resulting demon of an adjusted race level range.
int8_t ProcessFusion (const std::shared_ptr< ChannelClientConnection > &client, int64_t demonID1, int64_t demonID2, int64_t demonID3, uint32_t costItemType, std::shared_ptr< objects::Demon > &resultDemon)
Perform a two-way or tri-fusion based upon the supplied demon IDs.
uint32_t RankUpDown (uint8_t raceID, uint32_t demonType, bool up)
Determine the type of the demon directly above or directly below the supplied type in the fusion ranges by one rank.
Private Attributes
std::weak_ptr< ChannelServer > mServer
Pointer to the channel server.
Detailed Description
Manager class used to handle all demon fusion based actions.
Definition at line 47 of file FusionManager.h.
Constructor & Destructor Documentation
FusionManager::FusionManager (const std::weak_ptr< ChannelServer > & server)
Create a new FusionManager.
Parameters
server Pointer back to the channel server this belongs to.
Definition at line 70 of file FusionManager.cpp.
FusionManager::~FusionManager () virtual
Clean up the FusionManager.
Definition at line 75 of file FusionManager.cpp.
Member Function Documentation
void FusionManager::EndExchange (const std::shared_ptr< channel::ChannelClientConnection > & client)
End any fusion based exchanges the player is a part of.
If they are hosting a tri-fusion, all guests will be informed as well.
Parameters
client Pointer to the client in the exchange
Definition at line 1130 of file FusionManager.cpp.
References channel::ChannelClientConnection::BroadcastPacket(), channel::ClientState::GetCharacterState(), mServer, channel::state(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteS8().
int8_t FusionManager::GetAdjustedLevelSum (uint8_t level1, uint8_t level2, int8_t finalLevelAdjust = 0) private
Sum up and average the demon levels supplied and optionally offset with a final adjustment value.
Parameters
level1 Current level of the first demon
level2 Current level of the second demon
finalLevelAdjust Optional adjustment added at the end of the calculation
Returns
Calculated level
Definition at line 1783 of file FusionManager.cpp.
Referenced by GetResultDemon().
uint32_t FusionManager::GetElementalFuseResult (uint32_t elementalType, uint8_t otherRace, uint32_t otherType) private
Get the demon type ID associated to an elemental to non-elemental fusion.
Parameters
elementalType Elemental demon type
otherRace Race of the non-elemental demon
otherType Type of the non-elemental demon
Returns
Type ID of the result demon
Definition at line 1855 of file FusionManager.cpp.
References FUSION_ELEMENTAL_ADJUST, GetElementalIndex(), GetRaceIndex(), and RankUpDown().
Referenced by GetResultDemon().
size_t FusionManager::GetElementalIndex (uint32_t elemType, bool & found) private
Get the elemental index of the supplied type that matches the FusionTables entries.
Parameters
elemType Demon type to calculate
found Output parameter indicating if the index was found
Returns
Elemental index for the supplied type
Definition at line 1889 of file FusionManager.cpp.
References GetElementalType().
Referenced by GetElementalFuseResult(), and GetResultDemon().
uint32_t FusionManager::GetElementalType (size_t elementalIndex) const private
Get the demon type ID associated to an elemental index from the manager.
Parameters
elementalIndex Elemental index to retrieve
Returns
Type ID of the result demon
Definition at line 1829 of file FusionManager.cpp.
References SVR_CONST.
Referenced by GetElementalIndex(), and GetResultDemon().
size_t FusionManager::GetMitamaIndex (uint32_t mitamaType, bool & found)
Get the mitama index of the supplied type that matches the FusionTables entries.
Parameters
mitamaType Demon type to calculate
found Output parameter indicating if the index was found
Returns
Mitama index for the supplied type
Definition at line 1905 of file FusionManager.cpp.
References GetMitamaType().
Referenced by GetResultDemon(), IsTriFusionValid(), and ProcessFusion().
uint32_t FusionManager::GetMitamaType (size_t mitamaIndex) const private
Get the demon type ID associated to a mitama index from the manager.
Parameters
mitamaIndex Mitama index to retrieve
Returns
Type ID of the result demon
Definition at line 1842 of file FusionManager.cpp.
References SVR_CONST.
Referenced by GetMitamaIndex(), and GetResultDemon().
size_t FusionManager::GetRaceIndex (uint8_t raceID, bool & found) private
Get the race index of the supplied race that matches the FusionTables entries.
Parameters
otherRace Race to calculate
found Output parameter indicating if the index was found
Returns
Race index for the supplied race
Definition at line 1873 of file FusionManager.cpp.
References FUSION_RACE_MAP.
Referenced by GetElementalFuseResult(), and GetResultDemon().
uint32_t FusionManager::GetResultDemon (const std::shared_ptr< ChannelClientConnection > & client, int64_t demonID1, int64_t demonID2, int64_t demonID3)
Calculate the resulting demon based upon the supplied demon IDs.
Parameters
client Pointer to the client performing the fusion
demonID1 ID of the first demon being fused
demonID2 ID of the second demon being fused
demonID3 ID of the third demon being fused
Returns
Type ID of the demon that would be fused
Definition at line 416 of file FusionManager.cpp.
References libcomp::String::Arg(), channel::CharacterManager::ConvertIDToMaskValues(), FUSION_ELEMENTAL_MITAMA, FUSION_RACE_MAP, channel::ClientState::GetAccountUID(), GetAdjustedLevelSum(), channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), GetElementalFuseResult(), GetElementalIndex(), GetElementalType(), GetMitamaIndex(), GetMitamaType(), libcomp::PersistentObject::GetObjectByUUID(), channel::ClientState::GetObjectUUID(), GetRaceIndex(), mServer, RankUpDown(), channel::state(), SVR_CONST, TRIFUSION_FAMILY_MAP, and TRIFUSION_RACE_PRIORITY.
Referenced by ProcessFusion().
std::shared_ptr< objects::MiDevilData > FusionManager::GetResultDemon (uint8_t race, int8_t adjustedLevelSum) private
Get the resulting demon of an adjusted race level range.
Parameters
race Race of the demon to retrieve
adjustedLevelSum Level to use when checking level ranges
Returns
Pointer to the definition of the result demon
Definition at line 1790 of file FusionManager.cpp.
References libcomp::String::Arg(), and mServer.
bool FusionManager::HandleFusion (const std::shared_ptr< ChannelClientConnection > & client, int64_t demonID1, int64_t demonID2, uint32_t costItemType = 0)
Perform a normal 2-way fusion and respond to the client with the results.
Parameters
client Pointer to the client performing the fusion
demonID1 ID of the first demon being fused
demonID2 ID of the second demon being fused
costItemType Optional cost item type used to pay for the fusion, defaults to macca
Returns
true if the fusion succeeded, false if it did not
Definition at line 79 of file FusionManager.cpp.
References ProcessFusion(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteU32Little().
bool FusionManager::HandleTriFusion (const std::shared_ptr< ChannelClientConnection > & client, int64_t demonID1, int64_t demonID2, int64_t demonID3, bool soloFusion)
Perform a tri-fusion and respond to the client with the results.
Parameters
client Pointer to the client performing the fusion
demonID1 ID of the first demon being fused
demonID2 ID of the second demon being fused
demonID3 ID of the third demon being fused
soloFusion true if a solo fusion is being performed, false if it is a normal party based tri-fusion
Returns
true if the fusion succeeded, false if it did not
Definition at line 97 of file FusionManager.cpp.
References libcomp::String::Arg(), channel::ChannelClientConnection::BroadcastPacket(), libcomp::Packet::Clear(), libcomp::DatabaseChangeSet::Create(), channel::ClientState::GetAccountUID(), channel::ClientState::GetCharacterState(), libcomp::PersistentObject::GetObjectByUUID(), channel::ClientState::GetObjectUUID(), mServer, ProcessFusion(), RNG, libcomp::Packet::Seek(), libcomp::Packet::Size(), channel::state(), SVR_CONST, libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS64Little(), libcomp::Packet::WriteS8(), libcomp::Packet::WriteU16Little(), and libcomp::Packet::WriteU32Little().
bool FusionManager::IsTriFusionValid (const std::shared_ptr< objects::Demon > & demon)
Determine if the supplied demon is valid to use for tri-fusion.
Parameters
demon Pointer to the demon to check
Returns
true if they can be used for tri-fusion, false if they cannot
Definition at line 1921 of file FusionManager.cpp.
References GetMitamaIndex(), and mServer.
int8_t FusionManager::ProcessFusion (const std::shared_ptr< ChannelClientConnection > & client, int64_t demonID1, int64_t demonID2, int64_t demonID3, uint32_t costItemType, std::shared_ptr< objects::Demon > & resultDemon) private
Perform a two-way or tri-fusion based upon the supplied demon IDs.
Parameters
client Pointer to the client performing the fusion
demonID1 ID of the first demon being fused
demonID2 ID of the second demon being fused
demonID3 ID of the third demon being fused
costItemType Optional cost item type used to pay for the fusion, defaults to macca
resultDemon Output parameter to return the resulting demon in
Returns
Error code associated to the reason why any failure may have ocurred: 1 = Normal failure 0 = No failure -1 = Generic/criteria error -2 = Calculated fusion failed -3 = Supplied cost type is not valid -4 = Cost could not be paid
Definition at line 1224 of file FusionManager.cpp.
References libcomp::String::Arg(), libcomp::DatabaseChangeSet::Create(), FUSION_FAMILIARITY_BONUS, channel::ClientState::GetCharacterState(), GetMitamaIndex(), libcomp::PersistentObject::GetObjectByUUID(), channel::ClientState::GetObjectID(), channel::ClientState::GetObjectUUID(), GetResultDemon(), INHERITENCE_SKILL_MAP, mServer, libcomp::PersistentObject::New(), RNG, channel::ClientState::SetObjectID(), channel::state(), and SVR_CONST.
Referenced by HandleFusion(), and HandleTriFusion().
uint32_t FusionManager::RankUpDown (uint8_t raceID, uint32_t demonType, bool up) private
Determine the type of the demon directly above or directly below the supplied type in the fusion ranges by one rank.
Parameters
raceID Race of the demon to adjust
demonType Type of the demon to adjust
up true if checking higher, false if checking lower
Returns
Demon type directly above or below the supplied type
Definition at line 1942 of file FusionManager.cpp.
References mServer.
Referenced by GetElementalFuseResult(), and GetResultDemon().
Member Data Documentation
std::weak_ptr<ChannelServer> channel::FusionManager::mServer private
Pointer to the channel server.
Definition at line 223 of file FusionManager.h.
Referenced by EndExchange(), GetResultDemon(), HandleTriFusion(), IsTriFusionValid(), ProcessFusion(), and RankUpDown().
The documentation for this class was generated from the following files:
FusionManager.h
FusionManager.cpp