COMP_hack: channel::CharacterManager Class Reference
channel::CharacterManager Class Reference
Manager to handle Character focused actions.
#include <CharacterManager.h>
Public Member Functions
CharacterManager (const std::weak_ptr< ChannelServer > &server)
Create a new CharacterManager.
~CharacterManager ()
Clean up the CharacterManager.
bool AddMap (const std::shared_ptr< channel::ChannelClientConnection > &client, uint16_t mapID)
Add a map that the client character has obtained.
bool AddPlugin (const std::shared_ptr< channel::ChannelClientConnection > &client, uint16_t pluginID)
Add a fusion plugin that the client character has obtained.
bool AddRemoveItems (const std::shared_ptr< channel::ChannelClientConnection > &client, std::unordered_map< uint32_t, uint32_t > itemCounts, bool add, int64_t skillTargetID=0)
Add or remove items to a character's inventory.
bool AddRemoveOpponent (bool add, const std::shared_ptr< ActiveEntityState > &eState1, const std::shared_ptr< ActiveEntityState > &eState2)
Add or remove both supplied entities to the other's opponent set.
bool AddRemoveValuable (const std::shared_ptr< channel::ChannelClientConnection > &client, uint16_t valuableID, bool remove)
Add or remove a valuable that the client character has obtained.
bool AddStatusEffectImmediate (const std::shared_ptr< ChannelClientConnection > &client, const std::shared_ptr< ActiveEntityState > &eState, const StatusEffectChanges &effects)
Add one or more status effects to a client entity and immediately notify the zone instead of waiting for the queued change to be picked up by zone processing.
bool AddTitle (const std::shared_ptr< ChannelClientConnection > &client, int16_t titleID)
Add a specific title option to the player's character.
void ApplyTDamageSpecial (const std::shared_ptr< ActiveEntityState > &eState)
Apply special effects that occur as part of the normal regen synced "t-damage" processing that occurs every 10 seconds.
void CalculateCharacterBaseStats (const std::shared_ptr< objects::EntityStats > &cs)
Calculate the base stats of a character.
void CalculateDemonBaseStats (const std::shared_ptr< objects::Demon > &demon, std::shared_ptr< objects::EntityStats > ds=nullptr, std::shared_ptr< objects::MiDevilData > demonData=nullptr, bool setHPMP=true)
Calculate the base stats of a demon.
int32_t CalculateExpertiseGain (const std::shared_ptr< CharacterState > &cState, uint8_t expertiseID, float growthRate, uint16_t rateBoost=0, float multiplier=-1.0f)
Calculate how many expertise points would be gained for a specific character, expertise and growth rate.
uint64_t CalculateItemRemoval (const std::shared_ptr< channel::ChannelClientConnection > &client, uint32_t itemID, uint64_t amount, std::unordered_map< std::shared_ptr< objects::Item >, uint16_t > &stackAdjustItems)
Calculate the item updates needed to remove a number of items of a specific type.
bool CalculateMaccaPayment (const std::shared_ptr< channel::ChannelClientConnection > &client, uint64_t amount, std::list< std::shared_ptr< objects::Item >> &insertItems, std::unordered_map< std::shared_ptr< objects::Item >, uint16_t > &stackAdjustItems)
Calculate the item updates needed to pay a specified macca amount.
int8_t CalculateMagReduction (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::shared_ptr< objects::Demon > &demon)
Calculate the summoning mag reduction for a demon associated to their current player character.
bool CancelMount (ClientState *state)
Cancel the mount status effects on both the character and demon of the supplied ClientState.
void CancelStatusEffects (const std::shared_ptr< ChannelClientConnection > &client, uint8_t cancelFlags)
Cancel status effects associated to a client's character and demon based upon an action that affects both entities.
std::shared_ptr< objects::Demon > ContractDemon (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::shared_ptr< objects::MiDevilData > &demonData, int32_t sourceEntityID, uint16_t familiarity=0)
Create a demon and add it to the client character's COMP.
std::shared_ptr< objects::Demon > ContractDemon (const std::shared_ptr< objects::Character > &character, const std::shared_ptr< objects::MiDevilData > &demonData, uint16_t familiarity=0)
Create a demon and add it to a character's COMP.
bool CreateLootFromDrops (const std::shared_ptr< objects::LootBox > &box, const std::list< std::shared_ptr< objects::ItemDrop >> &drops, int16_t luck, bool minLast=false, float maccaRate=1.f, float magRate=1.f)
Create loot from drops based upon the supplied luck value (can be 0) and add them to the supplied loot box.
std::list< std::shared_ptr
< objects::Loot > > CreateLootFromDrops (const std::list< std::shared_ptr< objects::ItemDrop >> &drops, float maccaRate=1.f, float magRate=1.f)
Create loot from pre-filtered drops.
bool CultureItemPickup (const std::shared_ptr< channel::ChannelClientConnection > &client)
Retrieve the item associated to the client character's CultureData.
void DeleteDemon (const std::shared_ptr< objects::Demon > &demon, const std::shared_ptr< libcomp::DatabaseChangeSet > &changes)
Mark the supplied demon and its related data as deleted in the supplied changeset.
std::list< std::shared_ptr
< objects::ItemDrop > > DetermineDrops (const std::list< std::shared_ptr< objects::ItemDrop >> &drops, int16_t luck, bool minLast=false)
Filter a set of item drops based on drop rate and luck.
std::list< std::shared_ptr
< objects::DropSet > > DetermineDropSets (const std::list< uint32_t > &dropSetIDs, const std::shared_ptr< Zone > &zone, const std::shared_ptr< channel::ChannelClientConnection > &client, bool filter=true)
Get all dropsets from a list of IDs, filtering mutually exclusive sets as well as any applicable condition checks.
bool DigitalizeEnd (const std::shared_ptr< channel::ChannelClientConnection > &client)
End the digitalize state of a player character.
bool DigitalizeStart (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::shared_ptr< objects::Demon > &demon)
Enter a player character into the digitalize state using the supplied demon.
void EndExchange (const std::shared_ptr< channel::ChannelClientConnection > &client, int32_t outcome=1)
End the current exchange session for the client with various outcome types.
void EquipItem (const std::shared_ptr< channel::ChannelClientConnection > &client, int64_t itemID)
Equip or unequip an item matching the supplied ID on the client's character.
std::shared_ptr< objects::Demon > GenerateDemon (const std::shared_ptr< objects::MiDevilData > &demonData, uint16_t familiarity=0)
Create a demon.
std::shared_ptr< objects::Item > GenerateItem (uint32_t itemID, uint16_t stackSize)
Generate an item with the specified stack size.
bool GetActiveStatusesPacket (libcomp::Packet &p, int32_t entityID, const std::list< std::shared_ptr< objects::StatusEffect >> &active)
Build a packet containing a status effect add/update notification.
std::shared_ptr
< objects::DemonBox > GetDemonBox (ClientState *state, int8_t boxID)
Get the client's character or account owned demon box by ID.
void GetDemonPacketData (libcomp::Packet &p, const std::shared_ptr< channel::ChannelClientConnection > &client, const std::shared_ptr< objects::DemonBox > &box, int8_t slot)
Add data to a packet about a demon in a box.
uint32_t GetDemonPresent (uint32_t demonType, int8_t level, uint16_t familiarity, int8_t &rarity) const
Determine what item should be given as a demon specific present.
void GetEntityStatsPacketData (libcomp::Packet &p, const std::shared_ptr< objects::EntityStats > &coreStats, const std::shared_ptr< ActiveEntityState > &state, uint8_t format, libcomp::EnumMap< CorrectTbl, int32_t > coreBoosts={})
Add the core stat data from the supplied EntityStats instance and state object to a packet.
uint32_t GetExistingItemCount (const std::shared_ptr< objects::Character > &character, uint32_t itemID, std::shared_ptr< objects::ItemBox > box=nullptr)
Get the count of all item stacks in the specified box that match the supplied itemID.
std::list< std::shared_ptr
< objects::Item > > GetExistingItems (const std::shared_ptr< objects::Character > &character, uint32_t itemID, std::shared_ptr< objects::ItemBox > box=nullptr)
Get all items in the specified box that match the supplied itemID.
std::set< size_t > GetFreeSlots (const std::shared_ptr< ChannelClientConnection > &client, std::shared_ptr< objects::ItemBox > box=nullptr)
Get all the free slots within the supplied item box.
std::shared_ptr< objects::ItemBox > GetItemBox (ClientState *state, int8_t boxType, int64_t boxID)
Get the client's character or account owned item box by ID.
void GetItemDetailPacketData (libcomp::Packet &p, const std::shared_ptr< objects::Item > &item, uint8_t detailLevel=2)
Add data to a packet containing varying degrees of item details.
int32_t GetMaxExpertisePoints (const std::shared_ptr< objects::Character > &character)
Get the maximum number of expertise points available to the supplied characater.
bool GetRemovedStatusesPacket (libcomp::Packet &p, int32_t entityID, const std::set< uint32_t > &removed)
Build a packet containing a status effect removal notification.
uint16_t GetReunionRankTotal (const std::shared_ptr< objects::Demon > demon)
Get the total number of reunion ranks achieved by the supplied demon.
bool GetSynthOutcome (ClientState *synthState, const std::shared_ptr< objects::PlayerExchangeSession > &exchangeSession, uint32_t &outcomeItemType, std::list< int32_t > &successRates, int16_t *effectID=0, uint32_t *enchantSpecialID=0)
Determine various elements of the outcome of a synth exchange but do not perform the synth itself.
uint64_t GetTotalMacca (const std::shared_ptr< objects::Character > &character)
Get the total macca amount from the supplied character's inventory.
bool LearnSkill (const std::shared_ptr< channel::ChannelClientConnection > &client, int32_t entityID, uint32_t skillID)
Update the specified entity to learn a skill by ID.
void LevelUp (const std::shared_ptr< channel::ChannelClientConnection > &client, int8_t level, int32_t entityID)
Increase the level of a client's character or demon.
bool MitamaDemon (const std::shared_ptr< ChannelClientConnection > client, int64_t demonID, uint8_t growthType, uint8_t mitamaType)
Convert a demon into its upgraded mitama demon type.
void NotifyItemDistribution (const std::shared_ptr< ChannelClientConnection > &client, std::list< std::shared_ptr< objects::PostItem >> post)
Send post items not already "distributed" to the client and update them so they do not send a second time.
bool PayMacca (const std::shared_ptr< channel::ChannelClientConnection > &client, uint64_t amount)
Pay a specified macca amount.
uint8_t RecalculateStats (const std::shared_ptr< ActiveEntityState > &eState, std::shared_ptr< ChannelClientConnection > client=nullptr, bool updateSourceClient=true)
Recalculate the stats of an entity belonging to the supplied client and send any resulting changes to the zone (and world if applicable).
uint8_t RecalculateTokuseiAndStats (const std::shared_ptr< ActiveEntityState > &eState, std::shared_ptr< ChannelClientConnection > client)
Recalculate the tokusei and stats of an entity belonging to the supplied client and send any resulting changes to the zone (and world if applicable).
bool ReunionDemon (const std::shared_ptr< ChannelClientConnection > client, int64_t demonID, uint8_t growthType, uint32_t costItemType, bool replyToClient, bool force=false, int8_t forceRank=-1)
Perform reunion on the supplied client's partner demon if they match the supplied ID.
void ReviveCharacter (std::shared_ptr< ChannelClientConnection > client, int32_t revivalMode)
Revive the client's character (or demon) in a specific way.
void SendAutoRecovery (const std::shared_ptr< ChannelClientConnection > &client)
Send the client player's auto-recovery settings.
void SendCharacterData (const std::shared_ptr< ChannelClientConnection > &client)
Send updated character data to the game client.
void SendCharacterTitle (const std::shared_ptr< ChannelClientConnection > &client, bool includeSelf)
Send the character title to the client's current zone.
void SendCoinTotal (const std::shared_ptr< channel::ChannelClientConnection > &client, bool isUpdate)
Send the client character's current casino coin total.
void SendCowrieBethel (const std::shared_ptr< channel::ChannelClientConnection > &client)
Send the client character's current cowrie and bethel values.
void SendDemonBoxData (const std::shared_ptr< ChannelClientConnection > &client, int8_t boxID, std::set< int8_t > slots={})
Send information about the specified demon box to the client.
void SendDemonData (const std::shared_ptr< ChannelClientConnection > &client, int8_t boxID, int8_t slot, int64_t demonID)
Send updated data about a demon in a box to the game client.
void SendDevilBook (const std::shared_ptr< ChannelClientConnection > &client)
Send the client character's demonic compendium list.
void SendEntityStats (std::shared_ptr< ChannelClientConnection > client, int32_t entityID, bool includeSelf=true)
Send the stats of an entity that has been recalculated to the zone (and world if applicable).
void SendExpertiseExtension (const std::shared_ptr< channel::ChannelClientConnection > &client)
Send the character's current expertise extension amount.
void SendFusionGauge (const std::shared_ptr< channel::ChannelClientConnection > &client)
Send the player's fusion gauge to the client.
void SendInvokeStatus (const std::shared_ptr< ChannelClientConnection > &client, bool force, bool queue=false)
Send the client character's current Invoke event status.
void SendItemBoxData (const std::shared_ptr< ChannelClientConnection > &client, const std::shared_ptr< objects::ItemBox > &box)
Send information about the specified item box to the client.
void SendItemBoxData (const std::shared_ptr< ChannelClientConnection > &client, const std::shared_ptr< objects::ItemBox > &box, const std::list< uint16_t > &slots, bool adjustCounts=true)
Send information about the specified box slots to the client.
void SendLootItemData (const std::list< std::shared_ptr< ChannelClientConnection >> &clients, const std::shared_ptr< LootBoxState > &lState, bool queue=false)
Send the loot item data related to a loot box to one or more clients.
void SendMapFlags (const std::shared_ptr< ChannelClientConnection > &client)
Send the client character's obtained maps stored as an array of flags.
void SendMaterials (const std::shared_ptr< ChannelClientConnection > &client, std::set< uint32_t > updates={})
Send the client character's material container contents.
void SendMovementSpeed (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::shared_ptr< ActiveEntityState > &eState, bool diffOnly, bool queue=false)
Send the specified entity's non-battle movement speed to the client.
void SendOtherCharacterData (const std::list< std::shared_ptr< ChannelClientConnection >> &clients, ClientState *otherState)
Send updated character data to a different game client.
void SendOtherPartnerData (const std::list< std::shared_ptr< ChannelClientConnection >> &clients, ClientState *otherState)
Send updated data about the active demon of a different game client.
void SendPartnerData (const std::shared_ptr< ChannelClientConnection > &client)
Send updated data about the active demon of the game client.
void SendPluginFlags (const std::shared_ptr< ChannelClientConnection > &client)
Send the client character's obtained plugins stored as an array of flags.
void SendPvPCharacterInfo (const std::shared_ptr< channel::ChannelClientConnection > &client)
Send the client character's current PvP information.
void SendValuableFlags (const std::shared_ptr< ChannelClientConnection > &client)
Send the client character's obtained valuables stored as an array of flags.
void SetStatusIcon (const std::shared_ptr< channel::ChannelClientConnection > &client, int8_t icon=0)
Set the character's status icon and send to the game clients if it has changed.
void StoreDemon (const std::shared_ptr< channel::ChannelClientConnection > &client, bool updatePartyState=true, int32_t removeMode=2)
Return the current demon of the client's character to the COMP.
void SummonDemon (const std::shared_ptr< channel::ChannelClientConnection > &client, int64_t demonID, bool updatePartyState=true)
Summon the demon matching the supplied ID on the client's character.
bool UnequipItem (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::shared_ptr< objects::Item > &item)
Unequip the supplied item from the client's character.
int32_t UpdateBethel (const std::shared_ptr< channel::ChannelClientConnection > &client, int32_t bethel, bool adjust)
Update the character's bethel value for heir current Pentalpha match entry.
bool UpdateBP (const std::shared_ptr< channel::ChannelClientConnection > &client, int32_t points, bool isAdjust)
Update the player's current BP total.
bool UpdateCoinTotal (const std::shared_ptr< channel::ChannelClientConnection > &client, int64_t amount, bool isAdjust)
Update the player's casino coin total.
bool UpdateCowrieBethel (const std::shared_ptr< channel::ChannelClientConnection > &client, int32_t cowrie, const std::array< int32_t, 5 > &bethel)
Update the character's cowrie and bethel values independent of a match.
bool UpdateDigitalizePoints (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::unordered_map< uint8_t, int32_t > &pointMap, bool allowAdjust, bool validate=true)
Increase the digitalize XP points of one or more demon race for the supplied client.
bool UpdateDurability (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::shared_ptr< objects::Item > &item, int32_t points, bool isAdjust=true, bool updateMax=false, bool sendPacket=true)
Update the current or max durability of the supplied item by the specified amount.
bool UpdateDurability (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::unordered_map< std::shared_ptr< objects::Item >, int32_t > &items, bool isAdjust=true, bool updateMax=false, bool sendPacket=true)
Update the current or max durability of the supplied items by the specified amounts.
bool UpdateEventCounter (const std::shared_ptr< channel::ChannelClientConnection > &client, int32_t type, int32_t value, bool noSync=false)
Update or create a character assigned event counter.
bool UpdateExperience (const std::shared_ptr< channel::ChannelClientConnection > &client, int64_t xp, int32_t entityID)
Update the client's character or demon's experience and level up if the level threshold is passed.
void UpdateExpertise (const std::shared_ptr< channel::ChannelClientConnection > &client, uint32_t skillID, uint16_t rateBoost=0, float multiplier=-1.0f)
Update a client's character's expertise for a given skill.
void UpdateExpertisePoints (const std::shared_ptr< channel::ChannelClientConnection > &client, const std::list< std::pair< uint8_t, int32_t >> &pointMap, bool force=false)
Update a client's character's expertise for a set of expertise IDs.
void UpdateFamiliarity (const std::shared_ptr< channel::ChannelClientConnection > &client, int32_t familiarity, bool isAdjust=false, bool sendPacket=true)
Update the current partner demon's familiarity.
void UpdateFusionGauge (const std::shared_ptr< channel::ChannelClientConnection > &client, int32_t points, bool isAdjust)
Update the player's fusion gauge.
bool UpdateItems (const std::shared_ptr< channel::ChannelClientConnection > &client, bool validateOnly, std::list< std::shared_ptr< objects::Item >> &insertItems, std::unordered_map< std::shared_ptr< objects::Item >, uint16_t > stackAdjustItems, bool notifyClient=true)
Update or validate a set of item changes to be applied simultaneously, accounting for deletes that will clear up slots for inserts etc.
void UpdateLNC (const std::shared_ptr< channel::ChannelClientConnection > &client, int16_t lnc)
Update the client's character's LNC value.
bool UpdateRevivalXP (const std::shared_ptr< CharacterState > &cState, float lossPercent)
Calculate and update a character based how much XP is lost by reviving.
void UpdateSkillPoints (const std::shared_ptr< channel::ChannelClientConnection > &client, int32_t points)
Increase the client's character available skill points.
int32_t UpdateSoulPoints (const std::shared_ptr< channel::ChannelClientConnection > &client, int32_t points, bool isAdjust=false, bool applyRate=false)
Update the current partner demon's soul points.
bool UpdateStatusEffects (const std::shared_ptr< objects::Demon > &demon, const libobjgen::UUID &accountUID, bool queueSave)
Update the status effects active on a demon that is not currently summoned.
bool UpdateStatusEffects (const std::shared_ptr< ActiveEntityState > &eState, bool queueSave=false)
Update the status effects assigned directly on a character or demon entity from the current status effect states and save them to the database.
void UpdateWorldDisplayState (const std::set< std::shared_ptr< ActiveEntityState >> &entities)
Update the state of the supplied entities on the world server.
Static Public Member Functions
static void AdjustDemonBaseStats (const std::shared_ptr< objects::Demon > &demon, libcomp::EnumMap< CorrectTbl, int32_t > &stats, bool baseCalc, bool readOnly=false)
Adjust the base stats of a demon being calculated.
static void AdjustMitamaStats (const std::shared_ptr< objects::Demon > &demon, libcomp::EnumMap< CorrectTbl, int32_t > &stats, libcomp::DefinitionManager *definitionManager, uint8_t reunionMode, int32_t entityID=0, bool includeSetBonuses=true)
Adjust mitama specific stats of a demon being calculated.
static void AdjustStatBounds (libcomp::EnumMap< CorrectTbl, int32_t > &stats, bool limitMax)
Correct a map of calculated stat values to not exceed the maximum or minimum values possible.
static void CalculateDependentStats (libcomp::EnumMap< CorrectTbl, int32_t > &stats, int8_t level, bool isDemon)
Calculate the dependent stats (ex: max HP, close range damage) for a character or demon and update the values of a correct table map.
static void ConvertIDToMaskValues (uint16_t id, size_t &index, uint8_t &shiftVal)
Convert the supplied ID to its corresponding flag array index and shift value for use with fields stored as arrays of flags stored as single bytes.
static void FamiliarityBoostStats (uint16_t familiarity, libcomp::EnumMap< CorrectTbl, int32_t > &stats, std::shared_ptr< objects::MiDevilLVUpRateData > levelRate)
Apply demon familiarity boost to stats.
static libcomp::EnumMap
< CorrectTbl, int32_t > GetCharacterBaseStats (const std::shared_ptr< objects::EntityStats > &cs)
Retrieve a map of correct table indexes to corresponding stat values.
static libcomp::EnumMap
< CorrectTbl, int32_t > GetDemonBaseStats (const std::shared_ptr< objects::MiDevilData > &demonData)
Retrieve a map of correct table indexes to corresponding stat values for the supplied demon definition without any adjustments.
static libcomp::EnumMap
< CorrectTbl, int32_t > GetDemonBaseStats (const std::shared_ptr< objects::MiDevilData > &demonData, libcomp::DefinitionManager *definitionManager, uint8_t growthType, int8_t level)
Retrieve a map of correct table indexes to corresponding stat values for the supplied demon definition adjusted for current level and growth type.
static bool GetEntityRevivalPacket (libcomp::Packet &p, const std::shared_ptr< ActiveEntityState > &eState, int8_t action)
Write a revival action notification packet.
static int8_t GetFamiliarityRank (uint16_t familiarity)
Get a demon's familiarity rank from their current familiarity points.
static bool GetMitamaBonuses (const std::shared_ptr< objects::Demon > &demon, libcomp::DefinitionManager *definitionManager, std::unordered_map< uint8_t, uint8_t > &bonuses, std::set< uint32_t > &setBonuses, bool excludeTokusei)
Get all direct and set mitama bonuses for the supplied demon.
static std::list< int32_t > GetMitamaIndirectSetBonuses (const std::shared_ptr< objects::Demon > &demon, libcomp::DefinitionManager *definitionManager, bool exBonus, int8_t &magReduction)
Get all mitama set bonuses not covered by direct stat adjustments.
static void GetTDamagePacket (libcomp::Packet &p, int32_t entityID, int32_t hpGain, int32_t mpGain)
Write a t-damage notification packet, typically for regen.
static std::set< uint32_t > GetTraitSkills (const std::shared_ptr< objects::Demon > &demon, const std::shared_ptr< objects::MiDevilData > &demonData, libcomp::DefinitionManager *definitionManager)
Get all trait skill IDs on the supplied demon directly or from equipment.
static bool HasValuable (const std::shared_ptr< objects::Character > &character, uint16_t valuableID)
Determine if the specified character has the specified valuable.
static bool IsCPItem (const std::shared_ptr< objects::MiItemData > &itemData)
Check if the specified item definition belongs to a CP item.
static bool IsMitamaDemon (const std::shared_ptr< objects::MiDevilData > &devilData)
Check if the specified devil definition is a mitama'd type.
Static Private Member Functions
static void BoostStats (libcomp::EnumMap< CorrectTbl, int32_t > &stats, const std::shared_ptr< objects::MiDevilLVUpData > &data, int boostLevel)
Update the stats of a demon by a specified boost level determined by the demon's actual level.
Private Attributes
std::weak_ptr< ChannelServer > mServer
Pointer to the channel server.
Detailed Description
Manager to handle Character focused actions.
Definition at line 72 of file CharacterManager.h.
Constructor & Destructor Documentation
CharacterManager::CharacterManager (const std::weak_ptr< ChannelServer > & server)
Create a new CharacterManager.
Parameters
server Pointer back to the channel server this belongs to
Definition at line 129 of file CharacterManager.cpp.
CharacterManager::~CharacterManager ()
Clean up the CharacterManager.
Definition at line 134 of file CharacterManager.cpp.
Member Function Documentation
bool CharacterManager::AddMap (const std::shared_ptr< channel::ChannelClientConnection > & client, uint16_t mapID)
Add a map that the client character has obtained.
Parameters
client Pointer to the client connection
mapID ID representing both the map that was obtained and its byte shift position in the storage array
Returns
true if the map is valid and was either added or already obtained, false it was not
Definition at line 5833 of file CharacterManager.cpp.
References ConvertIDToMaskValues(), channel::ClientState::GetAccountUID(), channel::ClientState::GetCharacterState(), mServer, SendMapFlags(), and channel::state().
bool CharacterManager::AddPlugin (const std::shared_ptr< channel::ChannelClientConnection > & client, uint16_t pluginID)
Add a fusion plugin that the client character has obtained.
Parameters
client Pointer to the client connection
pluginID ID representing both the plugin that was obtained and its byte shift position in the storage array
Returns
true if the plugin is valid and was either added or already obtained, false it was not
Definition at line 5991 of file CharacterManager.cpp.
References ConvertIDToMaskValues(), channel::ClientState::GetAccountUID(), channel::ClientState::GetCharacterState(), mServer, SendPluginFlags(), and channel::state().
bool CharacterManager::AddRemoveItems (const std::shared_ptr< channel::ChannelClientConnection > & client, std::unordered_map< uint32_t, uint32_t > itemCounts, bool add, int64_t skillTargetID = 0)
Add or remove items to a character's inventory.
Parameters
client Pointer to the client connection containing the character
itemCounts Item type to quantity to add
add true if items should be added, false if they should be removed
skillTargetID Object ID of an item used for a skill. If this is specified for a remove command, it will be removed first
Returns
true if the items were added, false if one or more couldn't be added
Definition at line 2045 of file CharacterManager.cpp.
References libcomp::String::Arg(), libcomp::DatabaseChangeSet::Create(), EquipItem(), GenerateItem(), channel::ClientState::GetAccountUID(), channel::ClientState::GetCharacterState(), GetExistingItems(), libcomp::PersistentObject::GetObjectByUUID(), channel::ClientState::GetObjectID(), channel::ClientState::GetObjectUUID(), mServer, SendItemBoxData(), channel::state(), and SVR_CONST.
Referenced by ReviveCharacter().
bool CharacterManager::AddRemoveOpponent (bool add, const std::shared_ptr< ActiveEntityState > & eState1, const std::shared_ptr< ActiveEntityState > & eState2)
Add or remove both supplied entities to the other's opponent set.
If adding and either of the supplied entities is a player character or partner demon, both of those entities will be added instead.
Parameters
add true if the opponents should be added, false if they should be removed
eState1 Pointer to the primary entity to modify
eState2 Pointer ot the secondary entity to modify. If removing and this is not supplied, all entities will be removed from the primary entity
Returns
true if the update occurred without issue
Definition at line 6679 of file CharacterManager.cpp.
References channel::ChannelClientConnection::BroadcastPackets(), channel::COMBAT, channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), channel::ClientState::GetEntityClientState(), channel::SkillManager::GetMovementSpeeds(), channel::ChannelServer::GetServerTime(), PACKET_BATTLE_STOPPED, channel::SkillManager::SkillHasMoreUses(), channel::state(), libcomp::Packet::WriteFloat(), libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteS32Little().
Referenced by StoreDemon().
bool CharacterManager::AddRemoveValuable (const std::shared_ptr< channel::ChannelClientConnection > & client, uint16_t valuableID, bool remove)
Add or remove a valuable that the client character has obtained.
Parameters
client Pointer to the client connection
valuableID ID representing both the valuable that was obtained and its byte shift position in the storage array
remove true if the value should be removed instead of added
Returns
true if the valuable is valid and was either added, removed or already updated in the way requested, false it was not
Definition at line 5880 of file CharacterManager.cpp.
References ConvertIDToMaskValues(), channel::ClientState::GetAccountUID(), channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), LearnSkill(), mServer, SendValuableFlags(), channel::state(), SVR_CONST, and UpdateDigitalizePoints().
bool CharacterManager::AddStatusEffectImmediate (const std::shared_ptr< ChannelClientConnection > & client, const std::shared_ptr< ActiveEntityState > & eState, const StatusEffectChanges & effects)
Add one or more status effects to a client entity and immediately notify the zone instead of waiting for the queued change to be picked up by zone processing.
Useful when another packet is needed immediately after a status effect is added.
Parameters
client Pointer to the client connection
eState Pointer to the entity to add statuse effects to
effects Set of status effects to add
Returns
true if any effects were actually added
Definition at line 6440 of file CharacterManager.cpp.
References GetActiveStatusesPacket(), GetRemovedStatusesPacket(), and mServer.
Referenced by DigitalizeEnd(), and DigitalizeStart().
bool CharacterManager::AddTitle (const std::shared_ptr< ChannelClientConnection > & client, int16_t titleID)
Add a specific title option to the player's character.
Parameters
client Pointer to the client connection
titleID ID of the title to add
Returns
true if the title was added, false if it was not
Definition at line 6040 of file CharacterManager.cpp.
References ConvertIDToMaskValues(), channel::ClientState::GetCharacterState(), mServer, channel::state(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS16Little(), and libcomp::Packet::WriteS32Little().
void CharacterManager::AdjustDemonBaseStats (const std::shared_ptr< objects::Demon > & demon, libcomp::EnumMap< CorrectTbl, int32_t > & stats, bool baseCalc, bool readOnly = false) static
Adjust the base stats of a demon being calculated.
Parameters
demon Pointer to the demon being calculated
stats Reference to a correct table map
baseCalc When true, stats are being calculated to set directly on the demon. When false, stats are being calculated for when the demon is displayed as the active partner.
readOnly If true no values will be written directly to the demon
Definition at line 7480 of file CharacterManager.cpp.
Referenced by CalculateDemonBaseStats(), channel::CharacterState::Digitalize(), and channel::DemonState::RecalculateStats().
void CharacterManager::AdjustMitamaStats (const std::shared_ptr< objects::Demon > & demon, libcomp::EnumMap< CorrectTbl, int32_t > & stats, libcomp::DefinitionManager * definitionManager, uint8_t reunionMode, int32_t entityID = 0, bool includeSetBonuses = true) static
Adjust mitama specific stats of a demon being calculated.
Parameters
demon Pointer to the demon being calculated
stats Reference to a correct table map
definitionManager Pointer to the definition manager to use to retrieve stat information
reunionMode Adjust all reunion inreased stats (0), only base stats (1) or only non-base stats (2)
entityID ID of the demon entity if the one being calculated is summoned, defaults to unsummoned
includeSetBonuses Mitama set bonuses will be included in the calculation if true and ignored if false
Definition at line 7608 of file CharacterManager.cpp.
References channel::ClientState::GetCharacterState(), channel::ClientState::GetEntityClientState(), GetMitamaBonuses(), libcomp::DefinitionManager::GetMitamaReunionBonusData(), libcomp::DefinitionManager::GetMitamaUnionBonusData(), channel::state(), and SVR_CONST.
Referenced by CalculateDemonBaseStats(), channel::CharacterState::Digitalize(), and channel::DemonState::RecalculateStats().
void CharacterManager::AdjustStatBounds (libcomp::EnumMap< CorrectTbl, int32_t > & stats, bool limitMax) static
Correct a map of calculated stat values to not exceed the maximum or minimum values possible.
Parameters
stats Reference to a correct table map
limitMax If true, maximum stat limits will be adjusted as well
Definition at line 8049 of file CharacterManager.cpp.
Referenced by channel::ActiveEntityState::AdjustStats(), and CalculateDemonBaseStats().
void CharacterManager::ApplyTDamageSpecial (const std::shared_ptr< ActiveEntityState > & eState)
Apply special effects that occur as part of the normal regen synced "t-damage" processing that occurs every 10 seconds.
Parameters
eState Pointer to the entity that just applied regen
Definition at line 4220 of file CharacterManager.cpp.
References channel::ActiveEntityStateImp< T >::GetEntity(), mServer, and UpdateFamiliarity().
void CharacterManager::BoostStats (libcomp::EnumMap< CorrectTbl, int32_t > & stats, const std::shared_ptr< objects::MiDevilLVUpData > & data, int boostLevel) static private
Update the stats of a demon by a specified boost level determined by the demon's actual level.
Parameters
stats Reference to a correct table map containing stats that may or may not have already been boosted
data Pointer to the level up definition of a demon
boostLevel Boost level to use when calculating the stat increases
Definition at line 8551 of file CharacterManager.cpp.
Referenced by FamiliarityBoostStats(), and GetDemonBaseStats().
void CharacterManager::CalculateCharacterBaseStats (const std::shared_ptr< objects::EntityStats > & cs)
Calculate the base stats of a character.
Parameters
cs Pointer to the core stats of a character
Definition at line 7302 of file CharacterManager.cpp.
References CalculateDependentStats(), and GetCharacterBaseStats().
Referenced by UpdateExperience().
void CharacterManager::CalculateDemonBaseStats (const std::shared_ptr< objects::Demon > & demon, std::shared_ptr< objects::EntityStats > ds = nullptr, std::shared_ptr< objects::MiDevilData > demonData = nullptr, bool setHPMP = true)
Calculate the base stats of a demon.
Parameters
demon Pointer to the demon being calculated
ds Pointer to the core stats of a demon
demonData Pointer to the demon's definition
setHPMP If true, the current HP and MP will be set to the calculated max values
Definition at line 7318 of file CharacterManager.cpp.
References AdjustDemonBaseStats(), AdjustMitamaStats(), AdjustStatBounds(), CalculateDependentStats(), FamiliarityBoostStats(), GetDemonBaseStats(), and mServer.
Referenced by GenerateDemon(), ReunionDemon(), UpdateExperience(), and UpdateFamiliarity().
void CharacterManager::CalculateDependentStats (libcomp::EnumMap< CorrectTbl, int32_t > & stats, int8_t level, bool isDemon) static
Calculate the dependent stats (ex: max HP, close range damage) for a character or demon and update the values of a correct table map.
Parameters
stats Reference to a correct table map
level Current level of the character or demon
isDemon true if the entity is a demon, false if it is character
Todo:
: fix: close but not quite right
Definition at line 7966 of file CharacterManager.cpp.
Referenced by CalculateCharacterBaseStats(), CalculateDemonBaseStats(), channel::CharacterState::Digitalize(), channel::ActiveEntityState::RecalculateDemonStats(), and channel::CharacterState::RecalculateStats().
int32_t CharacterManager::CalculateExpertiseGain (const std::shared_ptr< CharacterState > & cState, uint8_t expertiseID, float growthRate, uint16_t rateBoost = 0, float multiplier = -1.0f)
Calculate how many expertise points would be gained for a specific character, expertise and growth rate.
Inactive expertise will always return 0.
Parameters
cState Pointer to the character state
expertiseID ID of the expertise to calculate
growthRate Growth rate to apply to the calculation, typically from a skill's growth data
rateBoost Optional flat value to add to the expertise rates for the calculation (before calculating final amount)
multiplier Expertise point multiplier, defaults to -1 to differentiate from explicitly being set to 1. If this is not set, the character's expertise acquisition rate will be used.
Returns
Expertise point gain, will never be negative
Definition at line 5173 of file CharacterManager.cpp.
References mServer.
Referenced by UpdateExpertise().
uint64_t CharacterManager::CalculateItemRemoval (const std::shared_ptr< channel::ChannelClientConnection > & client, uint32_t itemID, uint64_t amount, std::unordered_map< std::shared_ptr< objects::Item >, uint16_t > & stackAdjustItems)
Calculate the item updates needed to remove a number of items of a specific type.
Parameters
client Pointer to the client connection
itemID Item type to reduce
amount Amount to reduce the stacks by
stackAdjustItems Output map of items to adjust the stack size of including deletes listed with stack size 0
Returns
Amount that could not be removed
Definition at line 2533 of file CharacterManager.cpp.
References channel::ClientState::GetCharacterState(), GetExistingItems(), and channel::state().
Referenced by ReunionDemon().
bool CharacterManager::CalculateMaccaPayment (const std::shared_ptr< channel::ChannelClientConnection > & client, uint64_t amount, std::list< std::shared_ptr< objects::Item >> & insertItems, std::unordered_map< std::shared_ptr< objects::Item >, uint16_t > & stackAdjustItems)
Calculate the item updates needed to pay a specified macca amount.
Parameters
client Pointer to the client connection to pay macca
amount Amount of macca to pay
insertItems Output list of new items to insert
stackAdjustItems Output map of items to adjust the stack size of including deletes listed with stack size 0
Returns
true if the amount can be paid, false it cannot
Definition at line 2433 of file CharacterManager.cpp.
References GenerateItem(), channel::ClientState::GetCharacterState(), GetExistingItems(), channel::state(), and SVR_CONST.
Referenced by PayMacca(), and ReunionDemon().
int8_t CharacterManager::CalculateMagReduction (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::shared_ptr< objects::Demon > & demon)
Calculate the summoning mag reduction for a demon associated to their current player character.
Mag reduction is static from reunion bonuses but can also be increased mitama set bonuses as well as being further boosted by the current character's mitama set bonus boosting passive. Reduction cannot exceed 100.
Parameters
client Current client to retrieve demon information relative to
demon Demon to retrieve the reduction value for
Returns
Final combined summoning mag reduction
Definition at line 7865 of file CharacterManager.cpp.
References GetMitamaIndirectSetBonuses(), mServer, and SVR_CONST.
Referenced by GetDemonPacketData(), ReunionDemon(), SendDemonData(), and SendPartnerData().
bool CharacterManager::CancelMount (ClientState * state)
Cancel the mount status effects on both the character and demon of the supplied ClientState.
If the entity's are not mounted, no work will be done.
Parameters
state Pointer to the client state
Returns
true if the status effects existed and were cancelled
Definition at line 6583 of file CharacterManager.cpp.
References channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), GetRemovedStatusesPacket(), mServer, and SVR_CONST.
Referenced by CancelStatusEffects(), EquipItem(), and UpdateDurability().
void CharacterManager::CancelStatusEffects (const std::shared_ptr< ChannelClientConnection > & client, uint8_t cancelFlags)
Cancel status effects associated to a client's character and demon based upon an action that affects both entities.
Parameters
client Pointer to the client connection
cancelFlags Flags indicating conditions that can cause status effects to be cancelled. The set of valid status conditions are listed as constants on ActiveEntityState
Definition at line 6483 of file CharacterManager.cpp.
References CancelMount(), EFFECT_CANCEL_ZONEOUT, channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), GetRemovedStatusesPacket(), channel::ClientState::GetZone(), mServer, RecalculateTokuseiAndStats(), channel::state(), and SVR_CONST.
std::shared_ptr< objects::Demon > CharacterManager::ContractDemon (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::shared_ptr< objects::MiDevilData > & demonData, int32_t sourceEntityID, uint16_t familiarity = 0)
Create a demon and add it to the client character's COMP.
Parameters
client Pointer to the client connection
demonData Pointer to a demon's definition that represents the demon to create
sourceEntityID Entity ID of the demon egg used to contract the demon
familiarity Optional familiarity level on the contracted demon, defaults to 0
Returns
Pointer to the newly created demon
Definition at line 3688 of file CharacterManager.cpp.
References channel::ClientState::GetCharacterState(), mServer, SendDemonData(), channel::ClientState::SetObjectID(), channel::state(), libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteS32Little().
std::shared_ptr< objects::Demon > CharacterManager::ContractDemon (const std::shared_ptr< objects::Character > & character, const std::shared_ptr< objects::MiDevilData > & demonData, uint16_t familiarity = 0)
Create a demon and add it to a character's COMP.
Parameters
character Pointer to the character that should receive the demon
demonData Pointer to a demon's definition that represents the demon to create
familiarity Optional familiarity level on the contracted demon, defaults to 0
Returns
Pointer to the newly created demon
Definition at line 3725 of file CharacterManager.cpp.
References libcomp::DatabaseChangeSet::Create(), GenerateDemon(), and mServer.
void CharacterManager::ConvertIDToMaskValues (uint16_t id, size_t & index, uint8_t & shiftVal) static
Convert the supplied ID to its corresponding flag array index and shift value for use with fields stored as arrays of flags stored as single bytes.
Parameters
uint16_t ID to convert
index Output parameter that will be updated to the index of the flag array for the ID's corresponding byte
shiftVal Ouptput parameter that will be updated to the ID's mask position at the index in the flag array
Definition at line 5826 of file CharacterManager.cpp.
Referenced by channel::EventManager::AddDemonQuestRewards(), AddMap(), AddPlugin(), AddRemoveValuable(), AddTitle(), channel::SkillManager::DCM(), channel::EventManager::EvaluateCondition(), channel::EventManager::EvaluateQuestCondition(), channel::FusionManager::GetResultDemon(), HasValuable(), channel::EventManager::UpdateQuest(), and channel::CharacterState::UpdateQuestState().
bool CharacterManager::CreateLootFromDrops (const std::shared_ptr< objects::LootBox > & box, const std::list< std::shared_ptr< objects::ItemDrop >> & drops, int16_t luck, bool minLast = false, float maccaRate = 1.f, float magRate = 1.f)
Create loot from drops based upon the supplied luck value (can be 0) and add them to the supplied loot box.
Parameters
box Pointer to the loot box
drops List of pointers to the item drops to determine what should be added to the box
luck Current luck value to use when calculating drop chances
minLast Optional param to specify if the box needs at least one item in which case the last item will be used
maccaRate Optional param to scale macca dropped. Does not affect notes.
magRate Optional param to scale mag dropped. Does not affect pressers.
Returns
true if one or more item was added, false if none were
Definition at line 3006 of file CharacterManager.cpp.
References DetermineDrops().
std::list< std::shared_ptr< objects::Loot > > CharacterManager::CreateLootFromDrops (const std::list< std::shared_ptr< objects::ItemDrop >> & drops, float maccaRate = 1.f, float magRate = 1.f)
Create loot from pre-filtered drops.
Parameters
drops List of pointers to item drops
maccaRate Optional param to scale macca dropped. Does not affect notes.
magRate Optional param to scale mag dropped. Does not affect pressers.
Returns
List of pointers to converted Loot representations
Definition at line 3035 of file CharacterManager.cpp.
References libcomp::String::Arg(), mServer, RNG, and SVR_CONST.
bool CharacterManager::CultureItemPickup (const std::shared_ptr< channel::ChannelClientConnection > & client)
Retrieve the item associated to the client character's CultureData.
Parameters
client Pointer to the client connection
Returns
true if an item was retrieved, false if one was not
Definition at line 2687 of file CharacterManager.cpp.
References libcomp::String::Arg(), libcomp::DatabaseChangeSet::Create(), channel::ClientState::GetCharacterState(), GetFreeSlots(), mServer, RNG, SendItemBoxData(), channel::state(), SVR_CONST, libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteS8().
void CharacterManager::DeleteDemon (const std::shared_ptr< objects::Demon > & demon, const std::shared_ptr< libcomp::DatabaseChangeSet > & changes)
Mark the supplied demon and its related data as deleted in the supplied changeset.
If the demon is in a demon box, the box will be updated as well.
Parameters
demon Pointer to the demon that will be deleted
changes Pointer to the changeset to apply the changes to
Definition at line 8506 of file CharacterManager.cpp.
References libcomp::PersistentObject::GetObjectByUUID(), and mServer.
std::list< std::shared_ptr< objects::ItemDrop > > CharacterManager::DetermineDrops (const std::list< std::shared_ptr< objects::ItemDrop >> & drops, int16_t luck, bool minLast = false)
Filter a set of item drops based on drop rate and luck.
Parameters
drops List of pointers to the item drops to determine what should be "dropped"
luck Current luck value to use when calculating drop chances
minLast Optional param to specify if the set needs at least one item in which case the last item will be used
Returns
List of item drops that should be "dropped"
Definition at line 2954 of file CharacterManager.cpp.
References mServer, and RNG.
Referenced by CreateLootFromDrops().
std::list< std::shared_ptr< objects::DropSet > > CharacterManager::DetermineDropSets (const std::list< uint32_t > & dropSetIDs, const std::shared_ptr< Zone > & zone, const std::shared_ptr< channel::ChannelClientConnection > & client, bool filter = true)
Get all dropsets from a list of IDs, filtering mutually exclusive sets as well as any applicable condition checks.
Parameters
dropSetIDs List of dropset IDs to gather and filter
zone Zone the drops will be determined for
client Optional pointer to the client connection creating the drops (used when evaluating conditions)
filter Filters drops if true, defaults to true
Returns
List of valid drop set definitions
Definition at line 2882 of file CharacterManager.cpp.
References libcomp::Randomizer::GetEntry(), and mServer.
bool CharacterManager::DigitalizeEnd (const std::shared_ptr< channel::ChannelClientConnection > & client)
End the digitalize state of a player character.
Parameters
client Pointer to the client connection associated to the digitalized character
Returns
true if digitalization ended, false if was not active or could not be ended
Definition at line 7202 of file CharacterManager.cpp.
References AddStatusEffectImmediate(), libcomp::DatabaseChangeSet::Create(), channel::ClientState::GetCharacterState(), channel::ClientState::GetObjectID(), mServer, RecalculateTokuseiAndStats(), SendDemonBoxData(), channel::state(), SVR_CONST, libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteS64Little().
Referenced by DigitalizeStart().
bool CharacterManager::DigitalizeStart (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::shared_ptr< objects::Demon > & demon)
Enter a player character into the digitalize state using the supplied demon.
Parameters
client Pointer to the client connection associated to the character to digitalize
demon Pointer to the digitalize target demon
Returns
true if digitalization started, false if a failure occurred
Definition at line 7096 of file CharacterManager.cpp.
References AddStatusEffectImmediate(), DigitalizeEnd(), channel::ClientState::GetAccountUID(), channel::ClientState::GetCharacterState(), channel::ClientState::GetObjectID(), IsMitamaDemon(), mServer, RecalculateTokuseiAndStats(), channel::state(), SVR_CONST, UpdateStatusEffects(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteS64Little().
void CharacterManager::EndExchange (const std::shared_ptr< channel::ChannelClientConnection > & client, int32_t outcome = 1)
End the current exchange session for the client with various outcome types.
All exchange logic is handled elsewhere and the other participants must be notified via this function as well.
Parameters
client Client to notify of the end of an exchange
outcome Defaults to being ended by player, options are contextual to the exchange type
Definition at line 3609 of file CharacterManager.cpp.
References mServer, SetStatusIcon(), channel::state(), libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteS32Little().
void CharacterManager::EquipItem (const std::shared_ptr< channel::ChannelClientConnection > & client, int64_t itemID)
Equip or unequip an item matching the supplied ID on the client's character.
Parameters
client Pointer to the client connection containing the character
itemID Object ID matching an item in the character's item box
Definition at line 3217 of file CharacterManager.cpp.
References CancelMount(), libcomp::Packet::Clear(), channel::ClientState::GetAccountUID(), channel::ClientState::GetCharacterState(), GetEntityStatsPacketData(), libcomp::PersistentObject::GetObjectByUUID(), channel::ClientState::GetObjectID(), channel::ClientState::GetObjectUUID(), mServer, RecalculateStats(), SendFusionGauge(), channel::state(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS16Little(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS64Little(), libcomp::Packet::WriteU32Little(), and libcomp::Packet::WriteU8().
Referenced by AddRemoveItems(), and UnequipItem().
void CharacterManager::FamiliarityBoostStats (uint16_t familiarity, libcomp::EnumMap< CorrectTbl, int32_t > & stats, std::shared_ptr< objects::MiDevilLVUpRateData > levelRate) static
Apply demon familiarity boost to stats.
Parameters
familiarity Demon's current familiarity level
stats Reference to a correct table map
levelRate Level up rate to use for applying familiarity boosts
Definition at line 7455 of file CharacterManager.cpp.
References BoostStats(), and GetFamiliarityRank().
Referenced by CalculateDemonBaseStats(), channel::DemonState::RecalculateStats(), and SendDemonData().
std::shared_ptr< objects::Demon > CharacterManager::GenerateDemon (const std::shared_ptr< objects::MiDevilData > & demonData, uint16_t familiarity = 0)
Create a demon.
Parameters
demonData Pointer to a demon's definition that represents the demon to create
familiarity Optional default demon familiarity points
Returns
Pointer to the newly created demon
Definition at line 3780 of file CharacterManager.cpp.
References CalculateDemonBaseStats(), mServer, and libcomp::PersistentObject::New().
Referenced by ContractDemon().
std::shared_ptr< objects::Item > CharacterManager::GenerateItem (uint32_t itemID, uint16_t stackSize)
Generate an item with the specified stack size.
The stack size will not be checked for the maximum allowed value.
Parameters
itemID Item ID to generate an item from
stackSize Number of items in the stack to generate
Returns
Pointer to the generated item
Definition at line 2007 of file CharacterManager.cpp.
References mServer, and libcomp::PersistentObject::New().
Referenced by AddRemoveItems(), and CalculateMaccaPayment().
bool CharacterManager::GetActiveStatusesPacket (libcomp::Packet & p, int32_t entityID, const std::list< std::shared_ptr< objects::StatusEffect >> & active)
Build a packet containing a status effect add/update notification.
Parameters
p Packet to write the data to
entityID ID of the entity with the status effects
active List of status effects that have been changed
Returns
true if any status effects were supplied and the packet should be sent
Definition at line 6638 of file CharacterManager.cpp.
References libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteU32Little(), and libcomp::Packet::WriteU8().
Referenced by AddStatusEffectImmediate().
libcomp::EnumMap< CorrectTbl, int32_t > CharacterManager::GetCharacterBaseStats (const std::shared_ptr< objects::EntityStats > & cs) static
Retrieve a map of correct table indexes to corresponding stat values.
Parameters
cs Pointer to the core stats of a character
Returns
Map of correct table indexes to corresponding stat values
Definition at line 7922 of file CharacterManager.cpp.
Referenced by CalculateCharacterBaseStats(), and channel::CharacterState::RecalculateStats().
libcomp::EnumMap< CorrectTbl, int32_t > CharacterManager::GetDemonBaseStats (const std::shared_ptr< objects::MiDevilData > & demonData) static
Retrieve a map of correct table indexes to corresponding stat values for the supplied demon definition without any adjustments.
Parameters
demonData Pointer to the demon's definition
Returns
Map of correct table indexes to corresponding stat values
Definition at line 7384 of file CharacterManager.cpp.
Referenced by CalculateDemonBaseStats(), channel::CharacterState::Digitalize(), GetDemonBaseStats(), and channel::DemonState::RecalculateStats().
libcomp::EnumMap< CorrectTbl, int32_t > CharacterManager::GetDemonBaseStats (const std::shared_ptr< objects::MiDevilData > & demonData, libcomp::DefinitionManager * definitionManager, uint8_t growthType, int8_t level) static
Retrieve a map of correct table indexes to corresponding stat values for the supplied demon definition adjusted for current level and growth type.
Parameters
demonData Pointer to the demon's definition
definitionManager Pointer to the definition manager to use to retrieve growth information
growthType Demon growth type to calculate stats for
level Current level to calculate stats for
Returns
Map of correct table indexes to corresponding stat values
Definition at line 7399 of file CharacterManager.cpp.
References BoostStats(), GetDemonBaseStats(), and libcomp::DefinitionManager::GetDevilLVUpRateData().
std::shared_ptr< objects::DemonBox > CharacterManager::GetDemonBox (ClientState * state, int8_t boxID)
Get the client's character or account owned demon box by ID.
Parameters
client Pointer to the client connection containing the box
boxID Demon box ID to retrieve. 0 represents the COMP and anything higher is a depo box
Returns
Pointer to the demon box with the specified ID
Definition at line 1791 of file CharacterManager.cpp.
References channel::ClientState::GetCharacterState().
Referenced by SendDemonBoxData(), and SendDemonData().
void CharacterManager::GetDemonPacketData (libcomp::Packet & p, const std::shared_ptr< channel::ChannelClientConnection > & client, const std::shared_ptr< objects::DemonBox > & box, int8_t slot)
Add data to a packet about a demon in a box.
Parameters
p Packet to populate with demon data
client Current client to retrieve demon information from
box Demon box to populate information from
slot Demon box slot index to populate information from
Definition at line 8240 of file CharacterManager.cpp.
References CalculateMagReduction(), channel::ClientState::GetAccountUID(), channel::ChannelServer::GetExpirationInSeconds(), channel::ClientState::GetObjectID(), channel::state(), SVR_CONST, UpdateStatusEffects(), libcomp::Packet::WriteS16Little(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS64Little(), libcomp::Packet::WriteS8(), libcomp::Packet::WriteU32Little(), and libcomp::Packet::WriteU8().
Referenced by SendDemonBoxData().
uint32_t CharacterManager::GetDemonPresent (uint32_t demonType, int8_t level, uint16_t familiarity, int8_t & rarity) const
Determine what item should be given as a demon specific present.
Parameters
demonType Demon type
level Demon level
familiarity Demon current familiarity
rarity Output parameter to store the rarity level of the item if one is returned
Returns
Item type to give as a present or zero if none will be given
Definition at line 8132 of file CharacterManager.cpp.
References libcomp::Randomizer::GetEntry(), GetFamiliarityRank(), mServer, and RNG.
bool CharacterManager::GetEntityRevivalPacket (libcomp::Packet & p, const std::shared_ptr< ActiveEntityState > & eState, int8_t action) static
Write a revival action notification packet.
Parameters
p Packet to write the data to
eState Entity that has had a revival action performed on them
action Revival action that has taken place. The valid values are: -1) Revival done: Signifies that no other revival action will be sent following this one 1) Revive and wait: Revive the player character and wait for a "revival done" notification. This is typically followed with a zone change. 3) Normal: The entity has been revived by a skill or item 4) Accept revival: The entity is a character and is accepting revival from other players 5) Deny revival: The entity is a character and is not accepting revival from other players
Returns
false if the entity is not valid
Definition at line 1328 of file CharacterManager.cpp.
References libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS64Little(), and libcomp::Packet::WriteS8().
Referenced by ReviveCharacter().
void CharacterManager::GetEntityStatsPacketData (libcomp::Packet & p, const std::shared_ptr< objects::EntityStats > & coreStats, const std::shared_ptr< ActiveEntityState > & state, uint8_t format, libcomp::EnumMap< CorrectTbl, int32_t > coreBoosts = {})
Add the core stat data from the supplied EntityStats instance and state object to a packet.
Parameters
p Packet to populate with stat data
coreStats EntityStats pointer to the core stats of either a character or demon
state Pointer to the current state of the entity in a zone. If this parameter is supplied as null, only the core stats will be populated.
format Format to write the data in from the followin options: 0) Standard format used when intially describing a new entity 1) "Boost" format used when describing an entity that has leveled up or had its non-calculated stats adjusted 2) Recalc format used when stats have been recalculated caused by equipment or status effects being modified. 3) Recalc extended format
coreBoosts Core stat boosts active on an entity that is not not currently active (ex: familiarity boosts for COMP demons)
Definition at line 8362 of file CharacterManager.cpp.
References libcomp::Packet::WriteS16(), and libcomp::Packet::WriteS16Little().
Referenced by EquipItem(), ReunionDemon(), SendCharacterData(), SendDemonData(), SendEntityStats(), SendPartnerData(), and UpdateExperience().
uint32_t CharacterManager::GetExistingItemCount (const std::shared_ptr< objects::Character > & character, uint32_t itemID, std::shared_ptr< objects::ItemBox > box = nullptr)
Get the count of all item stacks in the specified box that match the supplied itemID.
Parameters
character Pointer to the character
itemID Item ID to find in the inventory
box Box to count items from
Returns
Total stack size of all matching items in the box
Definition at line 1962 of file CharacterManager.cpp.
References GetExistingItems().
std::list< std::shared_ptr< objects::Item > > CharacterManager::GetExistingItems (const std::shared_ptr< objects::Character > & character, uint32_t itemID, std::shared_ptr< objects::ItemBox > box = nullptr)
Get all items in the specified box that match the supplied itemID.
Parameters
character Pointer to the character
itemID Item ID to find in the inventory
box Box to return items for
Returns
List of pointers to the items of the matching ID
Definition at line 1936 of file CharacterManager.cpp.
Referenced by AddRemoveItems(), CalculateItemRemoval(), CalculateMaccaPayment(), GetExistingItemCount(), and GetTotalMacca().
int8_t CharacterManager::GetFamiliarityRank (uint16_t familiarity) static
Get a demon's familiarity rank from their current familiarity points.
Parameters
familiarity Demon's familiarity points
Returns
Converted familiarity rank from -3 to +4
Definition at line 4252 of file CharacterManager.cpp.
Referenced by FamiliarityBoostStats(), GetDemonPresent(), channel::EventManager::ResetDemonQuests(), SummonDemon(), and UpdateFamiliarity().
std::set< size_t > CharacterManager::GetFreeSlots (const std::shared_ptr< ChannelClientConnection > & client, std::shared_ptr< objects::ItemBox > box = nullptr)
Get all the free slots within the supplied item box.
Parameters
client Pointer to the client connection containing the box
box Box to return slots for, if null the inventory will be used
Returns
Set of all free slots in the box
Definition at line 1977 of file CharacterManager.cpp.
Referenced by CultureItemPickup().
std::shared_ptr< objects::ItemBox > CharacterManager::GetItemBox (ClientState * state, int8_t boxType, int64_t boxID)
Get the client's character or account owned item box by ID.
Parameters
client Pointer to the client connection containing the box
boxType Type of item box to retrieve
boxID Item box ID to retrieve by index
Returns
Pointer to the item box with the specified type and ID
Definition at line 1803 of file CharacterManager.cpp.
References libcomp::String::Arg(), and channel::ClientState::GetCharacterState().
void CharacterManager::GetItemDetailPacketData (libcomp::Packet & p, const std::shared_ptr< objects::Item > & item, uint8_t detailLevel = 2)
Add data to a packet containing varying degrees of item details.
Parameters
p Packet to populate with item data
item Pointer to the item
detailLevel Detail level to add to the packet ranging from 0 (least) to 2 (most). Defaults to 2.
Definition at line 8297 of file CharacterManager.cpp.
References libcomp::Packet::WriteBlank(), libcomp::Packet::WriteS16Little(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS8(), libcomp::Packet::WriteU16Little(), and libcomp::Packet::WriteU32Little().
Referenced by SendItemBoxData().
int32_t CharacterManager::GetMaxExpertisePoints (const std::shared_ptr< objects::Character > & character)
Get the maximum number of expertise points available to the supplied characater.
Parameters
character Pointer to the character
Returns
Maximum expertise points available to the character
Definition at line 5375 of file CharacterManager.cpp.
Referenced by UpdateExpertisePoints().
bool CharacterManager::GetMitamaBonuses (const std::shared_ptr< objects::Demon > & demon, libcomp::DefinitionManager * definitionManager, std::unordered_map< uint8_t, uint8_t > & bonuses, std::set< uint32_t > & setBonuses, bool excludeTokusei) static
Get all direct and set mitama bonuses for the supplied demon.
Parameters
demon Pointer to a demon
definitionManager Pointer to the definition manager to use to retrieve bonus information
bonuses Output variable to store direct bonus IDs (and counts)
setBonuses Output variable to store all active set bonuses
excludeTokusei If true, tokusei based set bonuses will be ignored
Returns
true if one or more bonus is active, false if no bonuses are active
Definition at line 7757 of file CharacterManager.cpp.
References libcomp::DefinitionManager::GetMitamaReunionSetBonusData().
Referenced by AdjustMitamaStats(), and GetMitamaIndirectSetBonuses().
std::list< int32_t > CharacterManager::GetMitamaIndirectSetBonuses (const std::shared_ptr< objects::Demon > & demon, libcomp::DefinitionManager * definitionManager, bool exBonus, int8_t & magReduction) static
Get all mitama set bonuses not covered by direct stat adjustments.
Parameters
demon Pointer to a demon
definitionManager Pointer to the definition manager to use to retrieve bonus information
exBonus Designates that the current character has the mitama set boost passive available
magReduction Output parameter designating additional mag reduction gained from set bonuses
Returns
List of tokusei IDs granted by set bonuses
Definition at line 7823 of file CharacterManager.cpp.
References GetMitamaBonuses(), and libcomp::DefinitionManager::GetMitamaReunionSetBonusData().
Referenced by CalculateMagReduction(), channel::CharacterState::Digitalize(), and channel::DemonState::UpdateDemonState().
bool CharacterManager::GetRemovedStatusesPacket (libcomp::Packet & p, int32_t entityID, const std::set< uint32_t > & removed)
Build a packet containing a status effect removal notification.
Parameters
p Packet to write the data to
entityID ID of the entity that had the status effects
active List of status effect IDs that have been removed
Returns
true if any status effects were supplied and the packet should be sent
Definition at line 6660 of file CharacterManager.cpp.
References libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteU32Little().
Referenced by AddStatusEffectImmediate(), CancelMount(), and CancelStatusEffects().
uint16_t CharacterManager::GetReunionRankTotal (const std::shared_ptr< objects::Demon > demon)
Get the total number of reunion ranks achieved by the supplied demon.
Parameters
demon Pointer to the demon
Returns
Total number of reunion ranks achieved
Definition at line 4136 of file CharacterManager.cpp.
References mServer.
Referenced by MitamaDemon().
bool CharacterManager::GetSynthOutcome (ClientState * synthState, const std::shared_ptr< objects::PlayerExchangeSession > & exchangeSession, uint32_t & outcomeItemType, std::list< int32_t > & successRates, int16_t * effectID = 0, uint32_t * enchantSpecialID = 0)
Determine various elements of the outcome of a synth exchange but do not perform the synth itself.
Supports demon crystallization as well as tarot and soul enchantment.
Parameters
synthState Pointer to the synth character's ClientState
exchangeSession Pointer to the synth exchange session
outcomeItemType Output parameter for the new item that will result from the synth, -1 for none
successRates Output parameter containing any success rates associated with the operation
effectID Output parameter only used by enchantment to contain the effect that will be applied
enchantSpecialID Output parameter only used by enchantment to contain the EnchantSpecialData ID
Returns
true if the calculation succeeded, false if an error occured
Definition at line 5540 of file CharacterManager.cpp.
References libcomp::String::Arg(), channel::ClientState::GetAccountUID(), channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), channel::ActiveEntityStateImp< T >::GetEntity(), IsCPItem(), mServer, and SVR_CONST.
void CharacterManager::GetTDamagePacket (libcomp::Packet & p, int32_t entityID, int32_t hpGain, int32_t mpGain) static
Write a t-damage notification packet, typically for regen.
If for whatever reason an entity's HP or MP needs to be "corrected", this seems to be the only way of communicating such to the client.
Parameters
p Packet to write the data to
entityID ID of the entity that has already had their HP or MP adjusted
hpGain HP value gained (can be negative)
mpGain MP value gained (can be negative)
Definition at line 1347 of file CharacterManager.cpp.
References libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteS32Little().
Referenced by channel::ZoneManager::EnterZone(), channel::SkillManager::ProcessSkillResultFinal(), and channel::ZoneManager::UpdateStatusEffectStates().
uint64_t CharacterManager::GetTotalMacca (const std::shared_ptr< objects::Character > & character)
Get the total macca amount from the supplied character's inventory.
Parameters
character Pointer to the character to calculate macca for
Returns
Total macca
Definition at line 2396 of file CharacterManager.cpp.
References GetExistingItems(), and SVR_CONST.
std::set< uint32_t > CharacterManager::GetTraitSkills (const std::shared_ptr< objects::Demon > & demon, const std::shared_ptr< objects::MiDevilData > & demonData, libcomp::DefinitionManager * definitionManager) static
Get all trait skill IDs on the supplied demon directly or from equipment.
Parameters
demon Pointer to a demon
demonData Pointer to the demon's definition
definitionManager Pointer to the definition manager to use to retrieve demon information
Returns
Set of active trait skill IDs
Definition at line 7892 of file CharacterManager.cpp.
References libcomp::DefinitionManager::GetDevilEquipmentItemData().
Referenced by channel::CharacterState::Digitalize(), and channel::DemonState::GetAllSkills().
bool CharacterManager::HasValuable (const std::shared_ptr< objects::Character > & character, uint16_t valuableID) static
Determine if the specified character has the specified valuable.
Parameters
character Pointer to the character to check
valuableID ID of the valuable to look for
Returns
true if the valuable has been obtained
Definition at line 5962 of file CharacterManager.cpp.
References ConvertIDToMaskValues().
Referenced by channel::SkillManager::DCM(), channel::EventManager::EvaluateCondition(), channel::CharacterState::GetDigitalizeAbilityLevel(), HandleBarter(), channel::CharacterState::RecalcEquipState(), UpdateFusionGauge(), and channel::DemonState::UpdateSharedState().
bool CharacterManager::IsCPItem (const std::shared_ptr< objects::MiItemData > & itemData) static
Check if the specified item definition belongs to a CP item.
Parameters
itemData Pointer to the item definition
Returns
true if the definition belongs to a CP item, false if it does not
Definition at line 3603 of file CharacterManager.cpp.
Referenced by GetSynthOutcome(), HandleCultureItem(), and HandleShopPurchase().
bool CharacterManager::IsMitamaDemon (const std::shared_ptr< objects::MiDevilData > & devilData) static
Check if the specified devil definition is a mitama'd type.
Parameters
devilData Pointer to the demon definition
Returns
true if the definition belongs to a mitama'd type, false if it does not
Definition at line 4213 of file CharacterManager.cpp.
Referenced by channel::CharacterState::Digitalize(), channel::SkillManager::Digitalize(), DigitalizeStart(), and UpdateDigitalizePoints().
bool CharacterManager::LearnSkill (const std::shared_ptr< channel::ChannelClientConnection > & client, int32_t entityID, uint32_t skillID)
Update the specified entity to learn a skill by ID.
Parameters
client Pointer to the client connection
entityID ID of the entity to learn the skill
skillID Skill ID to update the entity to learn
Returns
true if the skill was learned or is already learned, false if it failed
Definition at line 5433 of file CharacterManager.cpp.
References libcomp::DatabaseChangeSet::Create(), channel::ClientState::GetAccountUID(), channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), channel::ClientState::GetEntityState(), mServer, libcomp::PersistentObject::New(), RecalculateTokuseiAndStats(), channel::state(), SVR_CONST, libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteU32Little().
Referenced by AddRemoveValuable(), and UpdateDigitalizePoints().
void CharacterManager::LevelUp (const std::shared_ptr< channel::ChannelClientConnection > & client, int8_t level, int32_t entityID)
Increase the level of a client's character or demon.
Parameters
client Pointer to the client connection
level Number of levels to gain
entityID Character or demon ID to level up
Definition at line 5092 of file CharacterManager.cpp.
References channel::ClientState::GetEntityState(), channel::state(), and UpdateExperience().
bool CharacterManager::MitamaDemon (const std::shared_ptr< ChannelClientConnection > client, int64_t demonID, uint8_t growthType, uint8_t mitamaType)
Convert a demon into its upgraded mitama demon type.
Parameters
client Pointer to the client connection
demonID Object ID of the demon to convert
growthType New growth type to use for the demon
mitamaType Mitama type to use for the demon
Returns
true if the demon was converted successfully
Definition at line 4166 of file CharacterManager.cpp.
References libcomp::String::Arg(), libcomp::PersistentObject::GetObjectByUUID(), channel::ClientState::GetObjectUUID(), GetReunionRankTotal(), mServer, and channel::state().
void CharacterManager::NotifyItemDistribution (const std::shared_ptr< ChannelClientConnection > & client, std::list< std::shared_ptr< objects::PostItem >> post)
Send post items not already "distributed" to the client and update them so they do not send a second time.
Parameters
client Pointer to the client connection
post List of post items pending distribution
Definition at line 6224 of file CharacterManager.cpp.
References libcomp::DatabaseChangeSet::Create(), mServer, libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteS32Little().
bool CharacterManager::PayMacca (const std::shared_ptr< channel::ChannelClientConnection > & client, uint64_t amount)
Pay a specified macca amount.
Parameters
client Pointer to the client connection to pay macca
amount Amount of macca to pay
Returns
true if the amount was paid, false it was not
Definition at line 2418 of file CharacterManager.cpp.
References CalculateMaccaPayment(), channel::ClientState::GetCharacterState(), channel::state(), and UpdateItems().
uint8_t CharacterManager::RecalculateStats (const std::shared_ptr< ActiveEntityState > & eState, std::shared_ptr< ChannelClientConnection > client = nullptr, bool updateSourceClient = true)
Recalculate the stats of an entity belonging to the supplied client and send any resulting changes to the zone (and world if applicable).
Parameters
eState Pointer to the state of the entity being recalculated
client Optional pointer to the client connection. If not supplied but needed, it will be loaded from the entity ID
updateSourceClient true if the changes should be sent to the client itself as well, false if the client will be communicated about the changes later
Returns
1 if the calculation resulted in a change to the stats that should be sent to the client, 2 if one of the changes should be communicated to the world (for party members etc), 0 otherwise
Definition at line 802 of file CharacterManager.cpp.
References ENTITY_CALC_MOVE_SPEED, ENTITY_CALC_SKILL, ENTITY_CALC_STAT_LOCAL, ENTITY_CALC_STAT_WORLD, mServer, SendEntityStats(), SendMovementSpeed(), channel::state(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteU32Little().
Referenced by EquipItem(), RecalculateTokuseiAndStats(), ReunionDemon(), UpdateExperience(), and UpdateFamiliarity().
uint8_t CharacterManager::RecalculateTokuseiAndStats (const std::shared_ptr< ActiveEntityState > & eState, std::shared_ptr< ChannelClientConnection > client)
Recalculate the tokusei and stats of an entity belonging to the supplied client and send any resulting changes to the zone (and world if applicable).
Parameters
eState Pointer to the state of the entity being recalculated
client Pointer to the client connection of the entity
Returns
1 if the calculation resulted in a change to the stats that should be sent to the client, 2 if one of the changes should be communicated to the world (for party members etc), 0 otherwise
Definition at line 880 of file CharacterManager.cpp.
References mServer, and RecalculateStats().
Referenced by CancelStatusEffects(), DigitalizeEnd(), DigitalizeStart(), LearnSkill(), UpdateDurability(), and UpdateExpertisePoints().
bool CharacterManager::ReunionDemon (const std::shared_ptr< ChannelClientConnection > client, int64_t demonID, uint8_t growthType, uint32_t costItemType, bool replyToClient, bool force = false, int8_t forceRank = -1)
Perform reunion on the supplied client's partner demon if they match the supplied ID.
Parameters
client Pointer to the client connection
demonID Object ID of the demon currently summoned
growthType New growth type to use for the demon
costItemType Item type used for payment that must match the predefined types for the growth type
replyToClient If true the client will be sent a requested reunion reply
force If true only base validations will be performed, skipping costs and most growth type validations
forceRank Explicit rank to of the reunion bonuses to receive when forcing reunion to a normal type. This value cannot exceed the server configured maximum value.
Returns
true if the reunion succeeded, false if it did not
Definition at line 3841 of file CharacterManager.cpp.
References CalculateDemonBaseStats(), CalculateItemRemoval(), CalculateMaccaPayment(), CalculateMagReduction(), libcomp::DatabaseChangeSet::Create(), channel::ClientState::GetAccountUID(), channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), GetEntityStatsPacketData(), libcomp::PersistentObject::GetObjectByUUID(), channel::ClientState::GetObjectUUID(), mServer, RecalculateStats(), channel::state(), SVR_CONST, UpdateItems(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS64Little(), libcomp::Packet::WriteS8(), and libcomp::Packet::WriteU8().
void CharacterManager::ReviveCharacter (std::shared_ptr< ChannelClientConnection > client, int32_t revivalMode)
Revive the client's character (or demon) in a specific way.
Parameters
client Pointer to the client connection
revivalMode Specific revival mode to use. Types are listed in constants.
Definition at line 933 of file CharacterManager.cpp.
References AddRemoveItems(), libcomp::String::Arg(), libcomp::Packet::Clear(), channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), GetEntityRevivalPacket(), channel::ChannelServer::GetServerTime(), channel::ClientState::GetZone(), mServer, channel::state(), STATUS_IGNORE, SVR_CONST, UpdateRevivalXP(), UpdateWorldDisplayState(), channel::Point::x, and channel::Point::y.
void CharacterManager::SendAutoRecovery (const std::shared_ptr< ChannelClientConnection > & client)
Send the client player's auto-recovery settings.
Parameters
client Pointer to the client connection
Definition at line 1436 of file CharacterManager.cpp.
References channel::ClientState::GetCharacterState(), channel::state(), libcomp::Packet::WriteArray(), libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteU8().
void CharacterManager::SendCharacterData (const std::shared_ptr< ChannelClientConnection > & client)
Send updated character data to the game client.
Parameters
client Pointer to the client connection
Definition at line 138 of file CharacterManager.cpp.
References libcomp::Convert::ENCODING_CP932, channel::ClientState::GetCharacterState(), GetEntityStatsPacketData(), channel::ClientState::GetObjectID(), mServer, channel::state(), libcomp::Packet::WriteFloat(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS16(), libcomp::Packet::WriteS16Little(), libcomp::Packet::WriteS32(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS64Little(), libcomp::Packet::WriteS8(), libcomp::Packet::WriteString16Little(), libcomp::Packet::WriteU32(), libcomp::Packet::WriteU32Little(), and libcomp::Packet::WriteU8().
void CharacterManager::SendCharacterTitle (const std::shared_ptr< ChannelClientConnection > & client, bool includeSelf)
Send the character title to the client's current zone.
Parameters
client Pointer to the client connection containing the character
includeSelf true if the client should be sent the title as well, false if only the rest of the zone should be notified
Definition at line 1384 of file CharacterManager.cpp.
References channel::ClientState::GetCharacterState(), mServer, channel::state(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS16Little(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteU8().
void CharacterManager::SendCoinTotal (const std::shared_ptr< channel::ChannelClientConnection > & client, bool isUpdate)
Send the client character's current casino coin total.
Parameters
client Pointer to the client connection
isUpdate Signifies that the amount is not being sent due to initial character login
Definition at line 4513 of file CharacterManager.cpp.
References channel::ClientState::GetCharacterState(), channel::state(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteS64Little().
Referenced by UpdateCoinTotal().
void CharacterManager::SendCowrieBethel (const std::shared_ptr< channel::ChannelClientConnection > & client)
Send the client character's current cowrie and bethel values.
Parameters
client Pointer to the client connection
Definition at line 4723 of file CharacterManager.cpp.
References channel::ClientState::GetCharacterState(), channel::state(), libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteS32Little().
Referenced by UpdateCowrieBethel().
void CharacterManager::SendDemonBoxData (const std::shared_ptr< ChannelClientConnection > & client, int8_t boxID, std::set< int8_t > slots = {})
Send information about the specified demon box to the client.
Parameters
client Pointer to the client connection containing the box
boxID Demon box ID
slots Optional param to signify only specific slotss have been updated
Definition at line 1726 of file CharacterManager.cpp.
References channel::ClientState::GetCharacterState(), GetDemonBox(), GetDemonPacketData(), channel::ChannelServer::GetExpirationInSeconds(), channel::state(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS8(), and libcomp::Packet::WriteU8().
Referenced by DigitalizeEnd(), and StoreDemon().
void CharacterManager::SendDemonData (const std::shared_ptr< ChannelClientConnection > & client, int8_t boxID, int8_t slot, int64_t demonID)
Send updated data about a demon in a box to the game client.
Parameters
client Pointer to the client connection
boxID Demon box ID
slot Slot of the demon to send data for
demonID ID of the demon to send data for
Definition at line 644 of file CharacterManager.cpp.
References CalculateMagReduction(), FamiliarityBoostStats(), channel::ClientState::GetAccountUID(), channel::ClientState::GetCharacterState(), GetDemonBox(), channel::ClientState::GetDemonState(), GetEntityStatsPacketData(), channel::ChannelServer::GetExpirationInSeconds(), channel::ClientState::GetObjectID(), mServer, channel::state(), SVR_CONST, UpdateStatusEffects(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS16Little(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS64Little(), libcomp::Packet::WriteS8(), libcomp::Packet::WriteU16Little(), libcomp::Packet::WriteU32Little(), and libcomp::Packet::WriteU8().
Referenced by ContractDemon().
void CharacterManager::SendDevilBook (const std::shared_ptr< ChannelClientConnection > & client)
Send the client character's demonic compendium list.
Parameters
client Pointer to the client connection
Definition at line 6156 of file CharacterManager.cpp.
References channel::state(), libcomp::Packet::WriteArray(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS8(), and libcomp::Packet::WriteU16Little().
void CharacterManager::SendEntityStats (std::shared_ptr< ChannelClientConnection > client, int32_t entityID, bool includeSelf = true)
Send the stats of an entity that has been recalculated to the zone (and world if applicable).
Parameters
client Pointer to the client connection
entityID ID of the entity associated to the client to recalculate the stats of
includeSelf true if the packet should be sent to the source client as well
Definition at line 896 of file CharacterManager.cpp.
References channel::ClientState::GetEntityState(), GetEntityStatsPacketData(), mServer, channel::state(), libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteS32Little().
Referenced by RecalculateStats().
void CharacterManager::SendExpertiseExtension (const std::shared_ptr< channel::ChannelClientConnection > & client)
Send the character's current expertise extension amount.
Parameters
client Pointer to the client connection containing the character
Definition at line 5393 of file CharacterManager.cpp.
References channel::ClientState::GetCharacterState(), channel::state(), libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteS8().
void CharacterManager::SendFusionGauge (const std::shared_ptr< channel::ChannelClientConnection > & client)
Send the player's fusion gauge to the client.
Parameters
client Pointer to the client connection
Definition at line 4462 of file CharacterManager.cpp.
References channel::ClientState::GetCharacterState(), channel::state(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteU8().
Referenced by EquipItem(), and UpdateFusionGauge().
void CharacterManager::SendInvokeStatus (const std::shared_ptr< ChannelClientConnection > & client, bool force, bool queue = false)
Send the client character's current Invoke event status.
Parameters
client Pointer to the client connection
force If true, send the notification whether any cooldowns are active or not. If false, only send if a cooldown is active.
queue true if the packet should be queued, false if it should be sent right away
Definition at line 6171 of file CharacterManager.cpp.
References channel::ClientState::GetCharacterState(), channel::ChannelServer::GetExpirationInSeconds(), mServer, channel::state(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteS8().
void CharacterManager::SendItemBoxData (const std::shared_ptr< ChannelClientConnection > & client, const std::shared_ptr< objects::ItemBox > & box)
Send information about the specified item box to the client.
Parameters
client Pointer to the client connection containing the box
box Box to send information regarding
Definition at line 1835 of file CharacterManager.cpp.
Referenced by AddRemoveItems(), CultureItemPickup(), UpdateDurability(), and UpdateItems().
void CharacterManager::SendItemBoxData (const std::shared_ptr< ChannelClientConnection > & client, const std::shared_ptr< objects::ItemBox > & box, const std::list< uint16_t > & slots, bool adjustCounts = true)
Send information about the specified box slots to the client.
Parameters
client Pointer to the client connection containing the box
box Box to send information regarding
slots List of slots to send information about
adjustCounts Optional parameter to respond to any item counts that may have changed and notify the client accordingly. Defaults to true.
Definition at line 1846 of file CharacterManager.cpp.
References channel::ClientState::GetCharacterState(), GetItemDetailPacketData(), channel::ClientState::GetObjectID(), mServer, channel::ClientState::SetObjectID(), channel::state(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS64(), libcomp::Packet::WriteS64Little(), libcomp::Packet::WriteS8(), libcomp::Packet::WriteU16Little(), and libcomp::Packet::WriteU32().
void CharacterManager::SendLootItemData (const std::list< std::shared_ptr< ChannelClientConnection >> & clients, const std::shared_ptr< LootBoxState > & lState, bool queue = false)
Send the loot item data related to a loot box to one or more clients.
Parameters
clients List of clients to send the packet to
lState Pointer to the entity state of the loot box
queue true if the packet should be queued, false if it should be sent right away
Definition at line 3134 of file CharacterManager.cpp.
References channel::ClientState::GetCharacterState(), channel::ClientState::GetWorldCID(), libcomp::Packet::Seek(), libcomp::Packet::Size(), channel::state(), channel::ClientState::ToClientTime(), libcomp::Packet::WriteFloat(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS8(), libcomp::Packet::WriteU16Little(), and libcomp::Packet::WriteU32Little().
Referenced by channel::SkillManager::ScheduleFreeLoot().
void CharacterManager::SendMapFlags (const std::shared_ptr< ChannelClientConnection > & client)
Send the client character's obtained maps stored as an array of flags.
Parameters
client Pointer to the client connection
Definition at line 5865 of file CharacterManager.cpp.
References channel::ClientState::GetCharacterState(), channel::state(), libcomp::Packet::WriteArray(), libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteU16Little().
Referenced by AddMap().
void CharacterManager::SendMaterials (const std::shared_ptr< ChannelClientConnection > & client, std::set< uint32_t > updates = {})
Send the client character's material container contents.
Parameters
client Pointer to the client connection
updates If specified only the material types that match will be sent as an update, otherwise the full box set be sent
Definition at line 6112 of file CharacterManager.cpp.
References channel::ClientState::GetCharacterState(), mServer, channel::state(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteU32Little().
void CharacterManager::SendMovementSpeed (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::shared_ptr< ActiveEntityState > & eState, bool diffOnly, bool queue = false)
Send the specified entity's non-battle movement speed to the client.
Parameters
client Pointer to the client connection
eState Pointer to the entity
diffOnly true if the packet should only be sent if the speed is not equal to the entity's normal speed
queue true if the packet should be queued, false if it should be sent right away
Definition at line 1412 of file CharacterManager.cpp.
References libcomp::Packet::WriteFloat(), libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteS32Little().
Referenced by RecalculateStats().
void CharacterManager::SendOtherCharacterData (const std::list< std::shared_ptr< ChannelClientConnection >> & clients, ClientState * otherState)
Send updated character data to a different game client.
Parameters
clients List of pointers to the client connections to send the data to
otherState Pointer to the state of another client
Definition at line 303 of file CharacterManager.cpp.
References channel::ChannelClientConnection::BroadcastPacket(), libcomp::Convert::ENCODING_CP932, channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), libcomp::Packet::WriteBlank(), libcomp::Packet::WriteFloat(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS16Little(), libcomp::Packet::WriteS32(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS64Little(), libcomp::Packet::WriteS8(), libcomp::Packet::WriteString16Little(), libcomp::Packet::WriteU32Little(), and libcomp::Packet::WriteU8().
void CharacterManager::SendOtherPartnerData (const std::list< std::shared_ptr< ChannelClientConnection >> & clients, ClientState * otherState)
Send updated data about the active demon of a different game client.
Parameters
clients List of pointers to the client connections to send the data to
otherState Pointer to the state of another client
Definition at line 586 of file CharacterManager.cpp.
References channel::ChannelClientConnection::BroadcastPacket(), channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), libcomp::Packet::WriteFloat(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS16Little(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS64Little(), libcomp::Packet::WriteS8(), libcomp::Packet::WriteU16Little(), libcomp::Packet::WriteU32Little(), and libcomp::Packet::WriteU8().
Referenced by SummonDemon().
void CharacterManager::SendPartnerData (const std::shared_ptr< ChannelClientConnection > & client)
Send updated data about the active demon of the game client.
Parameters
client Pointer to the client connection
Definition at line 437 of file CharacterManager.cpp.
References CalculateMagReduction(), channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), GetEntityStatsPacketData(), channel::ChannelServer::GetExpirationInSeconds(), channel::ClientState::GetObjectID(), mServer, channel::state(), SVR_CONST, libcomp::Packet::WriteFloat(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS16Little(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS64Little(), libcomp::Packet::WriteS8(), libcomp::Packet::WriteU16Little(), libcomp::Packet::WriteU32Little(), and libcomp::Packet::WriteU8().
Referenced by SendPartnerData().
void CharacterManager::SendPluginFlags (const std::shared_ptr< ChannelClientConnection > & client)
Send the client character's obtained plugins stored as an array of flags.
Parameters
client Pointer to the client connection
Definition at line 6023 of file CharacterManager.cpp.
References channel::ClientState::GetCharacterState(), channel::state(), libcomp::Packet::WriteArray(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteU16Little().
Referenced by AddPlugin().
void CharacterManager::SendPvPCharacterInfo (const std::shared_ptr< channel::ChannelClientConnection > & client)
Send the client character's current PvP information.
Parameters
client Pointer to the client connection
Definition at line 4575 of file CharacterManager.cpp.
References channel::ClientState::GetCharacterState(), channel::state(), libcomp::Packet::WriteBlank(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteS8().
void CharacterManager::SendValuableFlags (const std::shared_ptr< ChannelClientConnection > & client)
Send the client character's obtained valuables stored as an array of flags.
Parameters
client Pointer to the client connection
Definition at line 5976 of file CharacterManager.cpp.
References channel::ClientState::GetCharacterState(), channel::state(), libcomp::Packet::WriteArray(), libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteU16Little().
Referenced by AddRemoveValuable().
void CharacterManager::SetStatusIcon (const std::shared_ptr< channel::ChannelClientConnection > & client, int8_t icon = 0)
Set the character's status icon and send to the game clients if it has changed.
Parameters
client Pointer to the client connection containing the character
icon Value of the new status icon to set
Definition at line 1356 of file CharacterManager.cpp.
References libcomp::Packet::Clear(), channel::ClientState::GetCharacterState(), mServer, channel::state(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteS8().
Referenced by EndExchange().
void CharacterManager::StoreDemon (const std::shared_ptr< channel::ChannelClientConnection > & client, bool updatePartyState = true, int32_t removeMode = 2)
Return the current demon of the client's character to the COMP.
Parameters
client Pointer to the client connection containing the character
updatePartyState true if the world should be updated with the character's new party state, false if it will be updated later
removeMode Zone removal mode to use when storing the demon
Definition at line 1640 of file CharacterManager.cpp.
References AddRemoveOpponent(), channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), channel::ClientState::GetPartyDemonPacket(), channel::ClientState::GetPartyID(), mServer, SendDemonBoxData(), channel::state(), SVR_CONST, and UpdateStatusEffects().
Referenced by SummonDemon().
void CharacterManager::SummonDemon (const std::shared_ptr< channel::ChannelClientConnection > & client, int64_t demonID, bool updatePartyState = true)
Summon the demon matching the supplied ID on the client's character.
Parameters
client Pointer to the client connection containing the character
demonID ID of the demon to summon
updatePartyState true if the world should be updated with the character's new party state, false if it will be updated later
Definition at line 1458 of file CharacterManager.cpp.
References channel::StatusEffectChange::Duration, channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), GetFamiliarityRank(), libcomp::PersistentObject::GetObjectByUUID(), channel::ClientState::GetObjectUUID(), channel::ClientState::GetPartyDemonPacket(), channel::ClientState::GetPartyID(), mServer, SendOtherPartnerData(), channel::state(), StoreDemon(), SVR_CONST, UpdateFamiliarity(), libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteS64Little().
bool CharacterManager::UnequipItem (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::shared_ptr< objects::Item > & item)
Unequip the supplied item from the client's character.
Unlike EquipItem, the item will not be toggled if it isn't equipped.
Parameters
client Pointer to the client connection containing the character
item Pointer to the item to unequip
Returns
true if the item was unequipped, false if it was not equipped to begin with
Definition at line 3344 of file CharacterManager.cpp.
References EquipItem(), channel::ClientState::GetCharacterState(), channel::ClientState::GetObjectID(), mServer, and channel::state().
Referenced by UpdateDurability(), and UpdateItems().
int32_t CharacterManager::UpdateBethel (const std::shared_ptr< channel::ChannelClientConnection > & client, int32_t bethel, bool adjust)
Update the character's bethel value for heir current Pentalpha match entry.
Parameters
client Pointer to the client connection
bethel Set or adjusted bethel value to update
adjust true if the point value should be adjusted via tokusei
Returns
Final point value added
Definition at line 4639 of file CharacterManager.cpp.
References channel::ClientState::GetCharacterState(), mServer, channel::state(), and UpdateCowrieBethel().
bool CharacterManager::UpdateBP (const std::shared_ptr< channel::ChannelClientConnection > & client, int32_t points, bool isAdjust)
Update the player's current BP total.
Parameters
client Pointer to the client connection
points Set or adjusted BP value to update
isAdjust true if the point value should be added to the current value, false if it should replace the curent value
Definition at line 4532 of file CharacterManager.cpp.
References channel::ClientState::GetAccountUID(), channel::ClientState::GetCharacterState(), mServer, channel::state(), libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteS32Little().
bool CharacterManager::UpdateCoinTotal (const std::shared_ptr< channel::ChannelClientConnection > & client, int64_t amount, bool isAdjust)
Update the player's casino coin total.
Parameters
client Pointer to the client connection
amount Set or adjusted coin amount to update
isAdjust true if the amount value should be added to the current value, false if it should replace the curent value
Definition at line 4476 of file CharacterManager.cpp.
References channel::ClientState::GetCharacterState(), mServer, SendCoinTotal(), and channel::state().
bool CharacterManager::UpdateCowrieBethel (const std::shared_ptr< channel::ChannelClientConnection > & client, int32_t cowrie, const std::array< int32_t, 5 > & bethel)
Update the character's cowrie and bethel values independent of a match.
Parameters
client Pointer to the client connection
cowrie Amount of cowrie to add
bethel Amount of bethel to add to each of the 5 types
Returns
true if the update succeeded, false if it did not
Definition at line 4668 of file CharacterManager.cpp.
References channel::ClientState::GetCharacterState(), mServer, SendCowrieBethel(), and channel::state().
Referenced by UpdateBethel().
bool CharacterManager::UpdateDigitalizePoints (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::unordered_map< uint8_t, int32_t > & pointMap, bool allowAdjust, bool validate = true)
Increase the digitalize XP points of one or more demon race for the supplied client.
If the race is not unlocked yet, the unlock criteria will be checked before adding any points.
Parameters
client Pointer to the client connection
pointMap Map of race IDs to points to add
allowAdjust If true, tokusei effects can increase the amount of points beinga added
validate Optional parameter to disable checking unlock criteria and current digitalize state level limits
Returns
true if an updateable digitalize race was supplied, false if they were all invalid or not unlockable
Definition at line 6864 of file CharacterManager.cpp.
References channel::ClientState::GetCharacterState(), IsMitamaDemon(), LearnSkill(), mServer, channel::state(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS8(), and libcomp::Packet::WriteU8().
Referenced by AddRemoveValuable().
bool CharacterManager::UpdateDurability (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::shared_ptr< objects::Item > & item, int32_t points, bool isAdjust = true, bool updateMax = false, bool sendPacket = true)
Update the current or max durability of the supplied item by the specified amount.
The item will be saved and the client will be notified only if a visible value is updated.
Parameters
client Pointer to the client connection
item Pointer to the item to adjust
points Durability points to adjust by
isAdjust true if the points supplied should be adjusted from the existing value, false if it should be explicitly set
updateMax true if the max durability is being updated, false if the current durability is being updated
sendPacket true if the client should be notified upon visible update, false if this will be handled elseswhere
Returns
true if visible durability was updated, false it was not
Definition at line 3369 of file CharacterManager.cpp.
bool CharacterManager::UpdateDurability (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::unordered_map< std::shared_ptr< objects::Item >, int32_t > & items, bool isAdjust = true, bool updateMax = false, bool sendPacket = true)
Update the current or max durability of the supplied items by the specified amounts.
The item will be saved and the client will be notified only if a visible value is updated.
Parameters
client Pointer to the client connection
items Map of pointers to the items to adjust to their point values to be adjusted by
isAdjust true if the points supplied should be adjusted from the existing value, false if it should be explicitly set
updateMax true if the max durability is being updated, false if the current durability is being updated
sendPacket true if the client should be notified upon visible update, false if this will be handled elseswhere
Returns
true if visible durability was updated, false it was not
Definition at line 3385 of file CharacterManager.cpp.
References libcomp::String::Arg(), CancelMount(), channel::ClientState::GetAccountUID(), channel::ClientState::GetCharacterState(), libcomp::PersistentObject::GetObjectByUUID(), mServer, RecalculateTokuseiAndStats(), SendItemBoxData(), channel::state(), UnequipItem(), UpdateExperience(), UpdateItems(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteU32Little().
bool CharacterManager::UpdateEventCounter (const std::shared_ptr< channel::ChannelClientConnection > & client, int32_t type, int32_t value, bool noSync = false)
Update or create a character assigned event counter.
Parameters
client Pointer to the client connection
type Type of event to update
value Value to add/assign to the counter
noSync Optional parameter to update the counter but not sync with the world. Useful for events that are not summed.
Returns
true if the update succeeded, false if it did not
Definition at line 4744 of file CharacterManager.cpp.
References libcomp::DatabaseChangeSet::Create(), channel::ClientState::GetAccountUID(), channel::ClientState::GetCharacterState(), mServer, and channel::state().
bool CharacterManager::UpdateExperience (const std::shared_ptr< channel::ChannelClientConnection > & client, int64_t xp, int32_t entityID)
Update the client's character or demon's experience and level up if the level threshold is passed.
XP can be reduced as well but cannot result in the entity leveling down.
Parameters
client Pointer to the client connection
xp Experience amount to add or remove
entityID Character or demon ID to gain experience
Returns
true if the update succeeded or nothing was done, false if an error occurred or the entity attempted to deduct more XP than the amount on the current level
Definition at line 4794 of file CharacterManager.cpp.
References libcomp::String::Arg(), CalculateCharacterBaseStats(), CalculateDemonBaseStats(), libcomp::Packet::Clear(), libcomp::DatabaseChangeSet::Create(), channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), channel::ClientState::GetEntityState(), GetEntityStatsPacketData(), channel::ClientState::GetObjectID(), mServer, RecalculateStats(), RNG_DEC, channel::state(), SVR_CONST, UpdateExpertisePoints(), UpdateFamiliarity(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS16Little(), libcomp::Packet::WriteS32(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS64(), libcomp::Packet::WriteS64Little(), libcomp::Packet::WriteS8(), and libcomp::Packet::WriteU32Little().
Referenced by LevelUp(), and UpdateDurability().
void CharacterManager::UpdateExpertise (const std::shared_ptr< channel::ChannelClientConnection > & client, uint32_t skillID, uint16_t rateBoost = 0, float multiplier = -1.0f)
Update a client's character's expertise for a given skill.
Parameters
client Pointer to the client connection
skillID Skill ID that will have it's corresponding expertise updated if it is enabled
rateBoost Optional flat value to add to the expertise rates for the skill (before calculating final amount)
multiplier Expertise point multiplier, defaults to -1 to differentiate from explicitly being set to 1. If this is not set, the character's expertise acquisition rate will be used.
Definition at line 5125 of file CharacterManager.cpp.
References libcomp::String::Arg(), CalculateExpertiseGain(), channel::ClientState::GetCharacterState(), mServer, channel::state(), and UpdateExpertisePoints().
void CharacterManager::UpdateExpertisePoints (const std::shared_ptr< channel::ChannelClientConnection > & client, const std::list< std::pair< uint8_t, int32_t >> & pointMap, bool force = false)
Update a client's character's expertise for a set of expertise IDs.
If an expertise is supplied that is not enabled it will still be updated.
Parameters
client Pointer to the client connection
pointMap Map of expertise IDs to points that will be added. The order the expertise are passed in is the order they will be processed in in case the limit is reached.
force If false, no updates will be performed should the matching expertise be locked or not created already.
Definition at line 5210 of file CharacterManager.cpp.
References libcomp::DatabaseChangeSet::Create(), channel::ClientState::GetAccountUID(), channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), GetMaxExpertisePoints(), mServer, RecalculateTokuseiAndStats(), channel::state(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteS8().
Referenced by UpdateExperience(), and UpdateExpertise().
void CharacterManager::UpdateFamiliarity (const std::shared_ptr< channel::ChannelClientConnection > & client, int32_t familiarity, bool isAdjust = false, bool sendPacket = true)
Update the current partner demon's familiarity.
Parameters
client Pointer to the client connection
familiarity Set or adjusted familiarity points to update the demon with
isAdjust true if the familiarity value should be added to the current value, false if it should replace the curent value
sendPacket true if the zone should be informed of the updated demon familiarity
Definition at line 4272 of file CharacterManager.cpp.
References CalculateDemonBaseStats(), channel::ClientState::GetAccountUID(), channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), GetFamiliarityRank(), mServer, RecalculateStats(), channel::state(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteU16Little().
Referenced by ApplyTDamageSpecial(), SummonDemon(), and UpdateExperience().
void CharacterManager::UpdateFusionGauge (const std::shared_ptr< channel::ChannelClientConnection > & client, int32_t points, bool isAdjust)
Update the player's fusion gauge.
Parameters
client Pointer to the client connection
points Set or adjusted fusion gauge points to update
isAdjust true if the points value should be added to the current value, false if it should replace the curent value
Definition at line 4428 of file CharacterManager.cpp.
References channel::ClientState::GetCharacterState(), HasValuable(), SendFusionGauge(), channel::state(), and SVR_CONST.
bool CharacterManager::UpdateItems (const std::shared_ptr< channel::ChannelClientConnection > & client, bool validateOnly, std::list< std::shared_ptr< objects::Item >> & insertItems, std::unordered_map< std::shared_ptr< objects::Item >, uint16_t > stackAdjustItems, bool notifyClient = true)
Update or validate a set of item changes to be applied simultaneously, accounting for deletes that will clear up slots for inserts etc.
Parameters
client Pointer to the client connection to apply the changes to
validateOnly true if the update should just be checked, false if the changes should actually be applied
insertItems List of new items to insert
stackAdjustItems Map of items to adjust the stack size of including deletes listed with stack size 0
notifyClient Optional parameter to not send the updated slot information to the client
Returns
true if the changes could be applied (or validated), false if they cannot
Definition at line 2566 of file CharacterManager.cpp.
References libcomp::String::Arg(), libcomp::DatabaseChangeSet::Create(), channel::ClientState::GetAccountUID(), channel::ClientState::GetCharacterState(), mServer, SendItemBoxData(), channel::state(), and UnequipItem().
Referenced by PayMacca(), ReunionDemon(), and UpdateDurability().
void CharacterManager::UpdateLNC (const std::shared_ptr< channel::ChannelClientConnection > & client, int16_t lnc)
Update the client's character's LNC value.
Parameters
client Pointer to the client connection containing the character
lnc LNC alignment value
Definition at line 3656 of file CharacterManager.cpp.
References channel::ClientState::GetAccountUID(), channel::ClientState::GetCharacterState(), mServer, channel::state(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS16Little(), and libcomp::Packet::WriteS32Little().
bool CharacterManager::UpdateRevivalXP (const std::shared_ptr< CharacterState > & cState, float lossPercent)
Calculate and update a character based how much XP is lost by reviving.
Parameters
cState Pointer to the character state
lossPercent Percentage of XP lost for their current level
Returns
true if XP was adjusted, false if it was not
Definition at line 1279 of file CharacterManager.cpp.
References mServer.
Referenced by ReviveCharacter().
void CharacterManager::UpdateSkillPoints (const std::shared_ptr< channel::ChannelClientConnection > & client, int32_t points)
Increase the client's character available skill points.
Parameters
client Pointer to the client connection
points Number of points to gain
Definition at line 5410 of file CharacterManager.cpp.
References channel::ClientState::GetAccountUID(), channel::ClientState::GetCharacterState(), mServer, channel::state(), libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteS32Little().
int32_t CharacterManager::UpdateSoulPoints (const std::shared_ptr< channel::ChannelClientConnection > & client, int32_t points, bool isAdjust = false, bool applyRate = false)
Update the current partner demon's soul points.
Parameters
client Pointer to the client connection
points Set or adjusted soul points to update the demon with
isAdjust true if the points value should be added to the current value, false if it should replace the curent value
applyRate If true the soul point rate will be used to adjust the amount gained
Returns
Adjusted SP amount gained or lossed (before limits are applied)
Definition at line 4359 of file CharacterManager.cpp.
References channel::ClientState::GetAccountUID(), channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), mServer, channel::state(), libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteS32Little().
bool CharacterManager::UpdateStatusEffects (const std::shared_ptr< objects::Demon > & demon, const libobjgen::UUID & accountUID, bool queueSave)
Update the status effects active on a demon that is not currently summoned.
Parameters
demon Pointer to an unsummoned demon
accountUID UID of the account the demon belongs to
queueSave When true, any updates that take place will be queued instead of saved immediately
Returns
true if the update completed without error
Definition at line 6262 of file CharacterManager.cpp.
References libcomp::DatabaseChangeSet::Create(), mServer, and channel::NONE.
Referenced by DigitalizeStart(), GetDemonPacketData(), SendDemonData(), and StoreDemon().
bool CharacterManager::UpdateStatusEffects (const std::shared_ptr< ActiveEntityState > & eState, bool queueSave = false)
Update the status effects assigned directly on a character or demon entity from the current status effect states and save them to the database.
Parameters
eState Pointer to the entity to save the status effects for
queueSave true if the save action should be queued, false if it should be done synchronously
Definition at line 6324 of file CharacterManager.cpp.
References libcomp::DatabaseChangeSet::Create(), channel::ActiveEntityStateImp< T >::GetEntity(), libcomp::PersistentObject::GetObjectByUUID(), and mServer.
void CharacterManager::UpdateWorldDisplayState (const std::set< std::shared_ptr< ActiveEntityState >> & entities)
Update the state of the supplied entities on the world server.
Parameters
entities List of pointers to entities to update on the world server. If the supplied entities are not associated to any others at a world server level, nothing will be sent.
Definition at line 7273 of file CharacterManager.cpp.
References channel::ClientState::GetEntityClientState(), and mServer.
Referenced by ReviveCharacter().
Member Data Documentation
std::weak_ptr<ChannelServer> channel::CharacterManager::mServer private
Pointer to the channel server.
Definition at line 1540 of file CharacterManager.h.
Referenced by AddMap(), AddPlugin(), AddRemoveItems(), AddRemoveValuable(), AddStatusEffectImmediate(), AddTitle(), ApplyTDamageSpecial(), CalculateDemonBaseStats(), CalculateExpertiseGain(), CalculateMagReduction(), CancelMount(), CancelStatusEffects(), ContractDemon(), CreateLootFromDrops(), CultureItemPickup(), DeleteDemon(), DetermineDrops(), DetermineDropSets(), DigitalizeEnd(), DigitalizeStart(), EndExchange(), EquipItem(), GenerateDemon(), GenerateItem(), GetDemonPresent(), GetReunionRankTotal(), GetSynthOutcome(), LearnSkill(), MitamaDemon(), NotifyItemDistribution(), RecalculateStats(), RecalculateTokuseiAndStats(), ReunionDemon(), ReviveCharacter(), SendCharacterData(), SendCharacterTitle(), SendDemonData(), SendEntityStats(), SendInvokeStatus(), SendItemBoxData(), SendMaterials(), SendPartnerData(), SetStatusIcon(), StoreDemon(), SummonDemon(), UnequipItem(), UpdateBethel(), UpdateBP(), UpdateCoinTotal(), UpdateCowrieBethel(), UpdateDigitalizePoints(), UpdateDurability(), UpdateEventCounter(), UpdateExperience(), UpdateExpertise(), UpdateExpertisePoints(), UpdateFamiliarity(), UpdateItems(), UpdateLNC(), UpdateRevivalXP(), UpdateSkillPoints(), UpdateSoulPoints(), UpdateStatusEffects(), and UpdateWorldDisplayState().
The documentation for this class was generated from the following files:
CharacterManager.h
CharacterManager.cpp