COMP_hack: channel::AIManager Class Reference
channel::AIManager Class Reference
Class to manage actions when triggering a spot or interacting with an object/NPC.
#include <AIManager.h>
Public Member Functions
AIManager ()
Create a new AIManager with no associated server.
AIManager (const std::weak_ptr< ChannelServer > &server)
Create a new AIManager.
~AIManager ()
Clean up the AIManager.
bool Chase (const std::shared_ptr< ActiveEntityState > &eState, int32_t targetEntityID, float minDistance=0.f, float maxDistance=0.f, bool interrupt=false, bool allowLazy=false)
Create a move command that chases a specified target in the same zone.
bool Circle (const std::shared_ptr< ActiveEntityState > &eState, float x, float y, bool interrupt=false, float distance=800.f)
Create a move command that causes the entity to retreat from a target point and circle them when far enough away.
void CombatSkillComplete (const std::shared_ptr< ActiveEntityState > &eState, const std::shared_ptr< objects::ActivatedAbility > &activated, const std::shared_ptr< objects::MiSkillData > &skillData, const std::shared_ptr< ActiveEntityState > &target, bool hit)
Handler for an AI controlled entity completing a skill responsible for timing post skill use actions.
void CombatSkillHit (const std::list< std::shared_ptr< ActiveEntityState >> &entities, const std::shared_ptr< ActiveEntityState > &source, const std::shared_ptr< objects::MiSkillData > &skillData)
Handler for any AI controlled entities that get hit by a combat skill from another entity.
bool Prepare (const std::shared_ptr< ActiveEntityState > &eState, const libcomp::String &aiType, uint16_t baseAIType=0)
Prepare an entity for AI control following the setting of all other necessary data.
bool QueueMoveCommand (const std::shared_ptr< ActiveEntityState > &eState, float x, float y, bool interrupt=false)
Queue a use move command on the specified AI controlled entity.
void QueueScriptCommand (const std::shared_ptr< AIState > &aiState, const libcomp::String &functionName, bool interrupt=false)
Queue a script command on the specified AIState.
bool QueueUseSkillCommand (const std::shared_ptr< ActiveEntityState > &eState, uint32_t skillID, int32_t targetEntityID, bool advance)
Queue a use skill command on the specified AI controlled entity.
void QueueWaitCommand (const std::shared_ptr< AIState > &aiState, uint32_t waitTime, bool interrupt=false)
Queue a wait command on the specified AIState.
bool Retreat (const std::shared_ptr< ActiveEntityState > &eState, float x, float y, float distance, bool interrupt=false)
Create a move command that causes the entity to retreat from a target point in a straight line up to a min distance.
bool StartEvent (const std::shared_ptr< ActiveEntityState > &eState, const libcomp::String &eventID)
Start an event with the supplied entity as the source entity.
void UpdateActiveStates (const std::shared_ptr< Zone > &zone, uint64_t now, bool isNight)
Update the AI state of all active AI controlled entities in the specified zone.
void UpdateAggro (const std::shared_ptr< ActiveEntityState > &eState, int32_t targetID)
Set or remove the aggro target on an AI controlled entity.
bool UseDiasporaQuake (const std::shared_ptr< ActiveEntityState > &source, uint32_t skillID, float delay)
Begin using a Diaspora quake skill from the supplied source entity.
Private Member Functions
void AddRemoveAggro (const std::shared_ptr< ActiveEntityState > &eState, int32_t targetID, bool remove)
Add or remove a specific entity ID from the aggro targets on the supplied entity.
bool CanRetrySkill (const std::shared_ptr< ActiveEntityState > &eState, const std::shared_ptr< objects::ActivatedAbility > &activated)
Determine if a skill that has already attempted activation can be used again.
bool CombatStaggerEnabled ()
Determine if combat stagger is enabled for the server to adjust timing of post charge and follow up attacks.
template<class T >
bool ExecuteScriptFunction (const std::shared_ptr< ActiveEntityState > &eState, const libcomp::String &functionName, uint64_t now, T &result)
Execute a function on the script bound to an entity's AI state and return the result.
bool Follow (const std::shared_ptr< ActiveEntityState > &eState, uint64_t now)
Determine any follow state specific logic for the supplied entity.
std::shared_ptr< AIMoveCommand > GetMoveCommand (const std::shared_ptr< ActiveEntityState > &eState, const Point &dest, float reduce=0.f, bool split=true, bool allowLazy=false)
Get a new move command from one point to another, calculating pathing and adjusting for collisions.
std::shared_ptr
< ActiveEntityState > GetSharedAggroEntity (const std::shared_ptr< ActiveEntityState > &eState)
Get the other entity that shares aggro with the supplied entity or null if none exists or the server is not configured to use shared aggro.
std::shared_ptr< AICommand > GetWaitCommand (uint32_t waitTime) const
Get a new wait command.
bool LazyPathingEnabled ()
Determine if the AI does not bother to navigate to a target that is not in direct line of sight.
void Move (const std::shared_ptr< ActiveEntityState > &eState, Point dest, uint64_t now)
Set the entity's destination position based on the supplied values and uses the current position values to set the origin.
bool PrepareSkillUsage (const std::shared_ptr< ActiveEntityState > &state)
Determine which skill the entity will use next based on their current state.
void RefreshSkillMap (const std::shared_ptr< ActiveEntityState > &eState, const std::shared_ptr< AIState > &aiState)
Refresh the skill map of the AIState if needed.
std::shared_ptr
< ActiveEntityState > Retarget (const std::shared_ptr< ActiveEntityState > &state, uint64_t now, bool isNight)
Clear an entity's AIState current target and find the next target to focus on.
uint8_t SkillAdvance (const std::shared_ptr< ActiveEntityState > &eState, const std::shared_ptr< objects::MiSkillData > &skillData, float distOverride=0.f)
Queue a command that will move the entity into range with its target.
bool SkillIsValid (const std::shared_ptr< objects::MiSkillData > &skillData)
Determine if a skill can be used at a base level.
bool UpdateEnemyState (const std::shared_ptr< ActiveEntityState > &eState, const std::shared_ptr< objects::EnemyBase > &eBase, uint64_t now, bool isNight)
Update the state of an enemy or ally, processing AI directly or queuing commands to be procssed on next update.
bool UpdateState (const std::shared_ptr< ActiveEntityState > &eState, uint64_t now, bool isNight)
Update the state of an entity, processing AI and performing other related actions.
void Wander (const std::shared_ptr< ActiveEntityState > &eState, const std::shared_ptr< objects::EnemyBase > &eBase)
Handle normal wander actions for the supplied AI controlled enemy based entity.
Private Attributes
std::weak_ptr< ChannelServer > mServer
Pointer to the channel server.
Static Private Attributes
static std::unordered_map
< std::string, std::shared_ptr
< libcomp::ScriptEngine > > sPreparedScripts
Static map of scripts that have been loaded and compiled by AI type name.
Detailed Description
Class to manage actions when triggering a spot or interacting with an object/NPC.
Definition at line 59 of file AIManager.h.
Constructor & Destructor Documentation
AIManager::AIManager ()
Create a new AIManager with no associated server.
This should not be used but is necessary for use with Sqrat.
Definition at line 114 of file AIManager.cpp.
AIManager::AIManager (const std::weak_ptr< ChannelServer > & server)
Create a new AIManager.
Parameters
server Pointer back to the channel server this belongs to.
Definition at line 118 of file AIManager.cpp.
AIManager::~AIManager ()
Clean up the AIManager.
Definition at line 123 of file AIManager.cpp.
Member Function Documentation
void AIManager::AddRemoveAggro (const std::shared_ptr< ActiveEntityState > & eState, int32_t targetID, bool remove) private
Add or remove a specific entity ID from the aggro targets on the supplied entity.
Parameters
eState Pointer to the entity state
targetID Entity ID representing the target entity
remove If true, remove the entity, otherwise add it
Definition at line 3002 of file AIManager.cpp.
References libcomp::String::Arg(), GetSharedAggroEntity(), and mServer.
Referenced by Retarget(), and UpdateAggro().
bool AIManager::CanRetrySkill (const std::shared_ptr< ActiveEntityState > & eState, const std::shared_ptr< objects::ActivatedAbility > & activated) private
Determine if a skill that has already attempted activation can be used again.
Parameters
eState Pointer to the entity state
activated Pointer to the skill's activation state
Returns
true if the skill can be reactivated, false if it cannot and should be cancelled
Definition at line 2559 of file AIManager.cpp.
Referenced by UpdateEnemyState(), and UpdateState().
bool AIManager::Chase (const std::shared_ptr< ActiveEntityState > & eState, int32_t targetEntityID, float minDistance = 0.f, float maxDistance = 0.f, bool interrupt = false, bool allowLazy = false)
Create a move command that chases a specified target in the same zone.
Parameters
eState Pointer to the entity state
targetEntityID Entity ID of the target to chase
minDistance Optional minimum distance needed before stopping, 0 to ignore
maxDistance Optional maximum distance allowed before stopping, 0 to ignore
interrupt If true the command will interrupt whatever the current command is
allowLazy If true and AILazyPathing is enabled, attempt to reach the destination via a linear path only. If false, navigate around obstacles via the shortest path.
Returns
true if the command was queued, false if it was not
Definition at line 849 of file AIManager.cpp.
References GetMoveCommand(), and mServer.
Referenced by Follow(), and SkillAdvance().
bool AIManager::Circle (const std::shared_ptr< ActiveEntityState > & eState, float x, float y, bool interrupt = false, float distance = 800.f)
Create a move command that causes the entity to retreat from a target point and circle them when far enough away.
If they are further away from the target than the designated distance, they will move in first.
Parameters
eState Pointer to the entity state
x X coordiate to circle
y Y coordiate to circle
interrupt If true the command will interrupt whatever the current command is
distance Distance to put between the entity and its target
Returns
true if the command was queued, false if it was not
Definition at line 925 of file AIManager.cpp.
References channel::Point::GetDistance(), mServer, RNG, channel::Point::x, and channel::Point::y.
Referenced by UpdateEnemyState().
void AIManager::CombatSkillComplete (const std::shared_ptr< ActiveEntityState > & eState, const std::shared_ptr< objects::ActivatedAbility > & activated, const std::shared_ptr< objects::MiSkillData > & skillData, const std::shared_ptr< ActiveEntityState > & target, bool hit)
Handler for an AI controlled entity completing a skill responsible for timing post skill use actions.
Parameters
eState Pointer to the entity state
activated Pointer to the skill's activation state
skillData Pointer to the definition of the skill being used
target Pointer to the primary target of the skill. Can be an ally or even the entity itself if a reflect occurred. The original target can be retrieved from the ActivatedAbility
hit true if the skill hit the target entity in a normal fasion (not avoided, NRA'd etc)
Definition at line 445 of file AIManager.cpp.
References libcomp::String::Arg(), libcomp::String::C(), libcomp::String::IsEmpty(), QueueWaitCommand(), RNG, STATUS_HIT_STUN, and STATUS_KNOCKBACK.
void AIManager::CombatSkillHit (const std::list< std::shared_ptr< ActiveEntityState >> & entities, const std::shared_ptr< ActiveEntityState > & source, const std::shared_ptr< objects::MiSkillData > & skillData)
Handler for any AI controlled entities that get hit by a combat skill from another entity.
This is executed immediately after a skill is processed and reported to the clients.
Parameters
entities List of pointers to AI controlled entities
source Pointer to the source of the skill. Can be an ally but is never the same entity being hit
skillData Pointer to the definition of the skill being used
Definition at line 377 of file AIManager.cpp.
References libcomp::String::Arg(), libcomp::String::C(), channel::AIUseSkillCommand::GetActivatedAbility(), libcomp::String::IsEmpty(), RNG, STATUS_RESTING, and UpdateAggro().
bool AIManager::CombatStaggerEnabled () private
Determine if combat stagger is enabled for the server to adjust timing of post charge and follow up attacks.
Returns
true if combat stagger is enabled, false if it is not
Definition at line 3100 of file AIManager.cpp.
References mServer.
Referenced by UpdateEnemyState(), and UpdateState().
template<class T > bool channel::AIManager::ExecuteScriptFunction (const std::shared_ptr< ActiveEntityState > & eState, const libcomp::String & functionName, uint64_t now, T & result) inline private
Execute a function on the script bound to an entity's AI state and return the result.
Parameters
eState Pointer to the AI controlled entity state
functionName Name of the script function to execute
now Current timestamp of the server
result Output parameter to store the script return result in
Returns
true if the function exists and returned a result, false if it did not
Definition at line 390 of file AIManager.h.
References libcomp::String::C().
Referenced by UpdateState().
bool AIManager::Follow (const std::shared_ptr< ActiveEntityState > & eState, uint64_t now) private
Determine any follow state specific logic for the supplied entity.
Parameters
eState Pointer to the entity with a follow entity
now Current timestamp of the server
Returns
true if follow specific actions were performed and the entity state has completed being updated, false otherwise
Definition at line 1759 of file AIManager.cpp.
References Chase(), FOLLOW_DISTANCE_CLOSE, FOLLOW_DISTANCE_FAR, FOLLOW_DISTANCE_MAX, channel::FOLLOWING, channel::ZoneManager::GetRandomRotation(), QueueMoveCommand(), QueueWaitCommand(), channel::ZoneManager::RotatePoint(), STATUS_WAITING, and UpdateAggro().
Referenced by UpdateEnemyState().
std::shared_ptr< AIMoveCommand > AIManager::GetMoveCommand (const std::shared_ptr< ActiveEntityState > & eState, const Point & dest, float reduce = 0.f, bool split = true, bool allowLazy = false) private
Get a new move command from one point to another, calculating pathing and adjusting for collisions.
Parameters
eState Pointer to the entity state to move
dest End point
reduce Reduces the final movement path by a set amount so the entity ends up that amount of units away
split If true, movements will be split into smaller segments to be more accurate to original movement. Disable for less important actions such as wandering with no target for less packet traffic.
allowLazy If true and AILazyPathing is enabled, attempt to reach the destination via a linear path only. If false, navigate around obstacles via the shortest path.
Returns
Pointer to the new move command
Definition at line 2882 of file AIManager.cpp.
References channel::Point::GetDistance(), LazyPathingEnabled(), mServer, channel::Point::x, and channel::Point::y.
Referenced by Chase(), QueueMoveCommand(), UpdateState(), and Wander().
std::shared_ptr< ActiveEntityState > AIManager::GetSharedAggroEntity (const std::shared_ptr< ActiveEntityState > & eState) private
Get the other entity that shares aggro with the supplied entity or null if none exists or the server is not configured to use shared aggro.
Parameters
eState Pointer to the entity state
Returns
Pointer to the other entity
Definition at line 3078 of file AIManager.cpp.
References channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), channel::ClientState::GetEntityClientState(), and channel::state().
Referenced by AddRemoveAggro(), and Retarget().
std::shared_ptr< AICommand > AIManager::GetWaitCommand (uint32_t waitTime) const private
Get a new wait command.
Parameters
waitTime Number of milliseconds the entity should wait when the command is processed
Returns
Pointer to the new move command
Definition at line 2994 of file AIManager.cpp.
Referenced by Prepare(), and QueueWaitCommand().
bool AIManager::LazyPathingEnabled () private
Determine if the AI does not bother to navigate to a target that is not in direct line of sight.
Only affects specific movement types.
Returns
true if lazy pathing is enabled, false if it is not
Definition at line 3107 of file AIManager.cpp.
References mServer.
Referenced by GetMoveCommand().
void AIManager::Move (const std::shared_ptr< ActiveEntityState > & eState, Point dest, uint64_t now) private
Set the entity's destination position based on the supplied values and uses the current position values to set the origin.
Communicating that the move has taken place must be done elsewhere.
Parameters
eState Pointer to the entity state
dest Position to move to
now Server time to use as the origin ticks
Definition at line 1842 of file AIManager.cpp.
References channel::Point::x, and channel::Point::y.
Referenced by UpdateState().
bool AIManager::Prepare (const std::shared_ptr< ActiveEntityState > & eState, const libcomp::String & aiType, uint16_t baseAIType = 0)
Prepare an entity for AI control following the setting of all other necessary data.
Parameters
eState Pointer to the entity state
aiType AI script type to bind to the entity
baseAIType Optional base AI type to default to. Setting this to a value with a bound AI script will override the supplied type.
Returns
true on sucess, false upon failure
Definition at line 127 of file AIManager.cpp.
References libcomp::String::Arg(), libcomp::String::C(), GetWaitCommand(), libcomp::String::IsEmpty(), mServer, sPreparedScripts, and channel::WANDERING.
bool AIManager::PrepareSkillUsage (const std::shared_ptr< ActiveEntityState > & state) private
Determine which skill the entity will use next based on their current state.
Parameters
eState Pointer to the entity state
Returns
true if a skill was selected, false if none can be used
Definition at line 2584 of file AIManager.cpp.
References libcomp::String::C(), libcomp::String::IsEmpty(), mServer, RefreshSkillMap(), RNG, SkillAdvance(), and SVR_CONST.
Referenced by UpdateEnemyState().
bool AIManager::QueueMoveCommand (const std::shared_ptr< ActiveEntityState > & eState, float x, float y, bool interrupt = false)
Queue a use move command on the specified AI controlled entity.
The shortest possible path will be used when creating the command.
Parameters
eState Pointer to the entity state
x X coordiate to move to
y Y coordiate to move to
interrupt If true the command will interrupt whatever the current command is
Returns
true if the command was queued, false if it was not
Definition at line 580 of file AIManager.cpp.
References GetMoveCommand().
Referenced by Follow().
void AIManager::QueueScriptCommand (const std::shared_ptr< AIState > & aiState, const libcomp::String & functionName, bool interrupt = false)
Queue a script command on the specified AIState.
Parameters
aiState Pointer to the AIState
functionName Name of the script function to be executed when the command is processed
interrupt If true the command will interrupt whatever the current command is
Definition at line 643 of file AIManager.cpp.
Referenced by UpdateState().
bool AIManager::QueueUseSkillCommand (const std::shared_ptr< ActiveEntityState > & eState, uint32_t skillID, int32_t targetEntityID, bool advance)
Queue a use skill command on the specified AI controlled entity.
Parameters
eState Pointer to the entity state
skillID Skill ID to use
targetEntityID Entity ID of the target to use the skill on
advance If true, a pre-skill movement command will be queued first
Returns
true if the skill queued correctly, false if it did not
Definition at line 600 of file AIManager.cpp.
References mServer, and SkillAdvance().
void AIManager::QueueWaitCommand (const std::shared_ptr< AIState > & aiState, uint32_t waitTime, bool interrupt = false)
Queue a wait command on the specified AIState.
Parameters
aiState Pointer to the AIState
waitTime Number of seconds the entity should wait when the command is processed
interrupt If true the command will interrupt whatever the current command is
Definition at line 653 of file AIManager.cpp.
References GetWaitCommand().
Referenced by CombatSkillComplete(), Follow(), UpdateEnemyState(), UpdateState(), and Wander().
void AIManager::RefreshSkillMap (const std::shared_ptr< ActiveEntityState > & eState, const std::shared_ptr< AIState > & aiState) private
Refresh the skill map of the AIState if needed.
Parameters
eState Pointer to the entity state to update
aiState Pointer to the AIState
Definition at line 2342 of file AIManager.cpp.
References channel::AI_SKILL_TYPES_ALLY, channel::AI_SKILL_TYPES_ENEMY, mServer, and SkillIsValid().
Referenced by PrepareSkillUsage().
std::shared_ptr< ActiveEntityState > AIManager::Retarget (const std::shared_ptr< ActiveEntityState > & state, uint64_t now, bool isNight) private
Clear an entity's AIState current target and find the next target to focus on.
Parameters
state Pointer to the AI controlled entity state
now Current timestamp of the server
isNight Night time indicator which affects targetting
Returns
Pointer to the entity being targeted
Definition at line 2075 of file AIManager.cpp.
References AddRemoveAggro(), channel::AGGRO, libcomp::String::Arg(), channel::ZoneManager::GetEntitiesInFoV(), libcomp::Randomizer::GetEntry(), GetSharedAggroEntity(), mServer, channel::NONE, RNG, STATUS_CHARGING, STATUS_IGNORE, and UpdateAggro().
Referenced by UpdateEnemyState(), and UpdateState().
bool AIManager::Retreat (const std::shared_ptr< ActiveEntityState > & eState, float x, float y, float distance, bool interrupt = false)
Create a move command that causes the entity to retreat from a target point in a straight line up to a min distance.
Only fails if something was invalid or the entity would not retreat further from the command.
Parameters
eState Pointer to the entity state
x X coordiate to retreat from
y Y coordiate to retreat from
interrupt If true the command will interrupt whatever the current command is
distance Distance to put between the entity and its target
Returns
true if the command was queued, false if it was not
Definition at line 892 of file AIManager.cpp.
References channel::Point::GetDistance(), and mServer.
Referenced by UpdateEnemyState().
uint8_t AIManager::SkillAdvance (const std::shared_ptr< ActiveEntityState > & eState, const std::shared_ptr< objects::MiSkillData > & skillData, float distOverride = 0.f) private
Queue a command that will move the entity into range with its target.
Parameters
eState Pointer to the entity state
skillData Pointer to the skill that will be used
distOverride Optional target distance to use as the minimum distance in place of the normal skill range
Returns
0 if the entity queued a move command to the target, 1 if the move was not possible, 2 if no move was needed
Definition at line 2014 of file AIManager.cpp.
References Chase().
Referenced by PrepareSkillUsage(), QueueUseSkillCommand(), and UpdateEnemyState().
bool AIManager::SkillIsValid (const std::shared_ptr< objects::MiSkillData > & skillData) private
Determine if a skill can be used at a base level.
Parameters
skillData Pointer to the skill definition
Returns
true if it is valid, false if it is not
Definition at line 2506 of file AIManager.cpp.
References mServer, and SVR_CONST.
Referenced by RefreshSkillMap().
bool AIManager::StartEvent (const std::shared_ptr< ActiveEntityState > & eState, const libcomp::String & eventID)
Start an event with the supplied entity as the source entity.
Parameters
eState Pointer to the entity state
eventID Event ID to start
Returns
true if the event started, false if it did not
Definition at line 663 of file AIManager.cpp.
References libcomp::String::Arg(), channel::EventOptions::AutoOnly, and mServer.
void AIManager::UpdateActiveStates (const std::shared_ptr< Zone > & zone, uint64_t now, bool isNight)
Update the AI state of all active AI controlled entities in the specified zone.
Parameters
zone Pointer to the zone to update
now Current server time
isNight Specifies that the server time is currently night which is between 1800 and 0599
Definition at line 304 of file AIManager.cpp.
References channel::ChannelClientConnection::FlushAllOutgoing(), channel::ChannelClientConnection::SendRelativeTimePacket(), libcomp::Packet::Size(), UpdateState(), libcomp::Packet::WriteFloat(), libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteS32Little().
void AIManager::UpdateAggro (const std::shared_ptr< ActiveEntityState > & eState, int32_t targetID)
Set or remove the aggro target on an AI controlled entity.
Parameters
eState Pointer to the entity state
targetID Entity ID representing the new AI target or -1 for no target
Definition at line 686 of file AIManager.cpp.
References AddRemoveAggro(), channel::AGGRO, libcomp::String::Arg(), channel::ChannelClientConnection::BroadcastPacket(), libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteS32Little().
Referenced by CombatSkillHit(), Follow(), Retarget(), and UpdateEnemyState().
bool AIManager::UpdateEnemyState (const std::shared_ptr< ActiveEntityState > & eState, const std::shared_ptr< objects::EnemyBase > & eBase, uint64_t now, bool isNight) private
Update the state of an enemy or ally, processing AI directly or queuing commands to be procssed on next update.
Parameters
eState Pointer to the entity state to update
eBase Pointer to the enemy base object from the entity
now Current timestamp of the server
isNight Night time indicator which affects targetting
Returns
true if the entity state should be communicated to the zone, false otherwise
Definition at line 1458 of file AIManager.cpp.
References CanRetrySkill(), Circle(), CombatStaggerEnabled(), Follow(), FOLLOW_DISTANCE_MAX, mServer, PrepareSkillUsage(), QueueWaitCommand(), Retarget(), Retreat(), RNG, SkillAdvance(), STATUS_CHARGING, STATUS_KNOCKBACK, UpdateAggro(), and Wander().
Referenced by UpdateState().
bool AIManager::UpdateState (const std::shared_ptr< ActiveEntityState > & eState, uint64_t now, bool isNight) private
Update the state of an entity, processing AI and performing other related actions.
Parameters
eState Pointer to the entity state to update
now Current timestamp of the server
isNight Night time indicator which affects targetting
Returns
true if the entity state should be communicated to the zone, false otherwise
Definition at line 1002 of file AIManager.cpp.
References channel::AGGRO, libcomp::String::Arg(), libcomp::String::C(), CanRetrySkill(), channel::COMBAT, CombatStaggerEnabled(), ExecuteScriptFunction(), channel::FOLLOWING, channel::AIUseSkillCommand::GetActivatedAbility(), GetMoveCommand(), channel::AIMoveCommand::GetTargetDistance(), channel::IDLE, libcomp::String::IsEmpty(), channel::MOVE, Move(), mServer, channel::NONE, QueueScriptCommand(), QueueWaitCommand(), Retarget(), channel::SCRIPTED, STATUS_CHARGING, STATUS_HIT_STUN, STATUS_IGNORE, STATUS_KNOCKBACK, STATUS_LOCKOUT, STATUS_RESTING, STATUS_WAITING, UpdateEnemyState(), channel::USE_SKILL, and channel::WANDERING.
Referenced by UpdateActiveStates().
bool AIManager::UseDiasporaQuake (const std::shared_ptr< ActiveEntityState > & source, uint32_t skillID, float delay)
Begin using a Diaspora quake skill from the supplied source entity.
Notifications will be sent to players in the zone that the skill has started and another when it hits.
Parameters
source Pointer to the source of the skill
skillID ID of the quake skill being used. The function ID of this skill must match the correct type
delay Delay from start to completion for the skill in seconds
Returns
true if the skill started properly, false if it did not
Definition at line 765 of file AIManager.cpp.
References libcomp::String::Arg(), channel::ChannelServer::GetServerTime(), mServer, SVR_CONST, libcomp::Packet::WriteFloat(), libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteS32Little().
void AIManager::Wander (const std::shared_ptr< ActiveEntityState > & eState, const std::shared_ptr< objects::EnemyBase > & eBase) private
Handle normal wander actions for the supplied AI controlled enemy based entity.
Parameters
eState Pointer to the entity state to update
eBase Pointer to the enemy base object from the entity
Definition at line 1863 of file AIManager.cpp.
References libcomp::String::Arg(), channel::Point::GetDistance(), GetMoveCommand(), channel::ZoneManager::GetRandomRotation(), mServer, QueueWaitCommand(), RNG, channel::Point::x, and channel::Point::y.
Referenced by UpdateEnemyState().
Member Data Documentation
std::weak_ptr<ChannelServer> channel::AIManager::mServer private
Pointer to the channel server.
Definition at line 481 of file AIManager.h.
Referenced by AddRemoveAggro(), Chase(), Circle(), CombatStaggerEnabled(), GetMoveCommand(), LazyPathingEnabled(), Prepare(), PrepareSkillUsage(), QueueUseSkillCommand(), RefreshSkillMap(), Retarget(), Retreat(), SkillIsValid(), StartEvent(), UpdateEnemyState(), UpdateState(), UseDiasporaQuake(), and Wander().
std::unordered_map< std::string, std::shared_ptr< libcomp::ScriptEngine > > AIManager::sPreparedScripts static private
Static map of scripts that have been loaded and compiled by AI type name.
Definition at line 478 of file AIManager.h.
Referenced by Prepare().
The documentation for this class was generated from the following files:
AIManager.h
AIManager.cpp