COMP_hack: channel::PlasmaState Class Reference
channel::PlasmaState Class Reference
Contains the state of an plasma spawn related to a channel.
#include <PlasmaState.h>
Public Member Functions
PlasmaState (const std::shared_ptr< objects::PlasmaSpawn > &plasma)
Create a plasma state based off of a server definition.
virtual ~PlasmaState ()
Clean up the plasma state.
bool CreatePoints ()
Create plasma points corresponding to each one required by the definition.
std::list< std::shared_ptr
< PlasmaPoint > > GetActivePoints ()
Get all active plasma points.
std::shared_ptr
< objects::PlasmaSpawn > GetEntity ()
Get the entity.
std::shared_ptr< PlasmaPoint > GetPoint (uint32_t pointID)
Get a plasma point corresponding to the point ID.
void GetPointStatusData (libcomp::Packet &p, uint32_t pointID, int32_t looterID=-1)
Write data to the supplied packet containing a specific point's status.
void GetPointStatusData (libcomp::Packet &p, std::list< uint32_t > pointIDs, int32_t looterID=-1)
Write data to the supplied packet containing specific points' statuses.
bool HasStateChangePoints (bool respawn, uint64_t now=0)
Check if there is plasma pending a hide or respawn update.
bool HideIfEmpty (const std::shared_ptr< PlasmaPoint > &point)
Hide the supplied plasma point if the point's loot box is empty.
bool IsActive (bool visible=false)
Determine if the plasma is marked as active or any points are not currently hidden.
std::shared_ptr< PlasmaPoint > PickPoint (uint32_t pointID, int32_t looterID)
Claim a point for a specific character and begin "picking" plasma.
std::list< std::shared_ptr
< PlasmaPoint > > PopHidePoints (uint64_t now=0)
Get a list of plasma points that have become hidden and prepare them to be hidden within the state.
std::list< std::shared_ptr
< PlasmaPoint > > PopRespawnPoints (uint64_t now=0)
Get a list of plasma points that have respawned and prepare them to be shown within the state.
bool SetLoot (uint32_t pointID, int32_t looterID, const std::shared_ptr< objects::LootBox > &loot)
Set the loot associated to a specific point.
std::shared_ptr< PlasmaPoint > SetPickResult (uint32_t pointID, int32_t looterID, int8_t result)
Update a plasma point with the result of the picking minigame.
void Toggle (bool enable, bool activation=false)
Enable/disable (or activate/deactivate) the plasma set.
Private Member Functions
void HidePoint (const std::shared_ptr< PlasmaPoint > &point)
Hide a point and set it up for respawn.
Private Attributes
bool mDeactivated
Indicates if the plasma set is deactivated and will not re-enable until it has been activated again.
bool mDisabled
Indicates if the plasma set is disabled and no points will spawn.
std::mutex mLock
Server lock for shared resources.
std::unordered_map< uint32_t,
uint64_t > mPointHides
Map of point IDs to server times when that point should be hidden to respawn later.
std::unordered_map< uint32_t,
uint64_t > mPointRespawns
Map of point IDs to server times when that point should be respawned.
std::unordered_map< uint32_t,
std::shared_ptr< PlasmaPoint > > mPoints
Map of points by definition ID.
Detailed Description
Contains the state of an plasma spawn related to a channel.
Definition at line 102 of file PlasmaState.h.
Constructor & Destructor Documentation
PlasmaState::PlasmaState (const std::shared_ptr< objects::PlasmaSpawn > & plasma)
Create a plasma state based off of a server definition.
Parameters
plasma Pointer to the server definition
Definition at line 106 of file PlasmaState.cpp.
References mDeactivated, and mDisabled.
virtual channel::PlasmaState::~PlasmaState () inline virtual
Clean up the plasma state.
Definition at line 114 of file PlasmaState.h.
Member Function Documentation
bool PlasmaState::CreatePoints ()
Create plasma points corresponding to each one required by the definition.
Returns
true if the points were created successfully
Definition at line 112 of file PlasmaState.cpp.
References channel::EntityState< objects::PlasmaSpawn >::GetEntity(), and mPoints.
std::list< std::shared_ptr< PlasmaPoint > > PlasmaState::GetActivePoints ()
Get all active plasma points.
Returns
List of all active plasma points
Definition at line 140 of file PlasmaState.cpp.
References mLock, and mPoints.
Referenced by IsActive().
std::shared_ptr<objects::PlasmaSpawn > channel::EntityState< objects::PlasmaSpawn >::GetEntity () inline inherited
Get the entity.
Returns
Pointer to the entity
Definition at line 59 of file EntityState.h.
Referenced by CreatePoints(), and HidePoint().
std::shared_ptr< PlasmaPoint > PlasmaState::GetPoint (uint32_t pointID)
Get a plasma point corresponding to the point ID.
Parameters
pointID ID of the point to retrieve
Returns
Pointer to the plasma point
Definition at line 132 of file PlasmaState.cpp.
References mLock, and mPoints.
void PlasmaState::GetPointStatusData (libcomp::Packet & p, uint32_t pointID, int32_t looterID = -1)
Write data to the supplied packet containing a specific point's status.
Parameters
p Packet to write to
pointID ID of the point to describe
looterID Optional parameter to retrive the character relative point state
Definition at line 421 of file PlasmaState.cpp.
void PlasmaState::GetPointStatusData (libcomp::Packet & p, std::list< uint32_t > pointIDs, int32_t looterID = -1)
Write data to the supplied packet containing specific points' statuses.
Parameters
p Packet to write to
pointIDs IDs of the points to describe
looterID Optional parameter to retrive the character relative point state
Definition at line 430 of file PlasmaState.cpp.
References mLock, mPoints, libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteS8().
bool PlasmaState::HasStateChangePoints (bool respawn, uint64_t now = 0)
Check if there is plasma pending a hide or respawn update.
Parameters
respawn true if points pending respawn should be retrieved, false if points pending hiding should be retrieved
now Current server time
Returns
true if a point in the specified state exists
Definition at line 192 of file PlasmaState.cpp.
References channel::ChannelServer::GetServerTime(), mDeactivated, mDisabled, mLock, mPointHides, mPointRespawns, and mPoints.
bool PlasmaState::HideIfEmpty (const std::shared_ptr< PlasmaPoint > & point)
Hide the supplied plasma point if the point's loot box is empty.
Parameters
point Pointer to the plasma point to hide
Returns
true if the point was empty and was marked as hidden, false if it was not empty
Definition at line 376 of file PlasmaState.cpp.
References HidePoint(), mLock, and mPoints.
void PlasmaState::HidePoint (const std::shared_ptr< PlasmaPoint > & point) private
Hide a point and set it up for respawn.
Parameters
point Pointer to the plasma point to hide
Definition at line 455 of file PlasmaState.cpp.
References channel::EntityState< objects::PlasmaSpawn >::GetEntity(), channel::ChannelServer::GetServerTime(), mDisabled, mPointHides, and mPointRespawns.
Referenced by HideIfEmpty(), PopHidePoints(), and SetPickResult().
bool PlasmaState::IsActive (bool visible = false)
Determine if the plasma is marked as active or any points are not currently hidden.
Parameters
visible If true, the plasma is only considered active if a single point is not currently hidden. If false, the plasma is only considered active if its deactivated parameter is not set.
Returns
true if active or points are not hidden, false otherwise
Definition at line 156 of file PlasmaState.cpp.
References GetActivePoints(), and mDeactivated.
std::shared_ptr< PlasmaPoint > PlasmaState::PickPoint (uint32_t pointID, int32_t looterID)
Claim a point for a specific character and begin "picking" plasma.
This is responsible for locking players out if they attempt to access the point after another player has already claimed it
Parameters
pointID ID of the point to pick
looterID ID of the character attempting to loot the point
Returns
Pointer to the point if the looter can pick it, null if they cannot
Definition at line 291 of file PlasmaState.cpp.
References mLock, and mPoints.
std::list< std::shared_ptr< PlasmaPoint > > PlasmaState::PopHidePoints (uint64_t now = 0)
Get a list of plasma points that have become hidden and prepare them to be hidden within the state.
Parameters
now Current server time
Returns
List of plasma points that have become hidden
Definition at line 262 of file PlasmaState.cpp.
References channel::ChannelServer::GetServerTime(), HidePoint(), mLock, mPointHides, and mPoints.
std::list< std::shared_ptr< PlasmaPoint > > PlasmaState::PopRespawnPoints (uint64_t now = 0)
Get a list of plasma points that have respawned and prepare them to be shown within the state.
Parameters
now Current server time
Returns
List of plasma points that have respawned
Definition at line 235 of file PlasmaState.cpp.
References channel::ChannelServer::GetServerTime(), mLock, mPointRespawns, and mPoints.
bool PlasmaState::SetLoot (uint32_t pointID, int32_t looterID, const std::shared_ptr< objects::LootBox > & loot)
Set the loot associated to a specific point.
Parameters
pointID ID of the point to update
looterID ID of the character who is updating the point. If this does not match the looter on the point already, nothing will be changed
loot Pointer to the generated loot for the point
Returns
true if the update was completed, otherwise false
Definition at line 398 of file PlasmaState.cpp.
References mLock, and mPoints.
std::shared_ptr< PlasmaPoint > PlasmaState::SetPickResult (uint32_t pointID, int32_t looterID, int8_t result)
Update a plasma point with the result of the picking minigame.
Parameters
pointID ID of the point to update
looterID ID of the character who is updating the point. If this does not match the looter on the point already, nothing will be changed
result Client supplied result of the minigame containing a positive value for a success or a negative for a failure. This represents the distance from the "goal" in the minigame with a negative being outside of the success area
Returns
Pointer to the point if the update was valid, null if it was not
Definition at line 318 of file PlasmaState.cpp.
References channel::ChannelServer::GetServerTime(), HidePoint(), mLock, mPointHides, and mPoints.
Referenced by channel::ZoneManager::FailPlasma().
void PlasmaState::Toggle (bool enable, bool activation = false)
Enable/disable (or activate/deactivate) the plasma set.
Enabling plasma causes it to appear in the zone on next server tick. Disabling plasma causes it to despawn on next server tick. Deactivated plasma will neither spawn nor despawn until it is activated again. For most non-time trigger processes, modifying if the plasma is active is the normal use case.
Parameters
enable If true the points will be enabled, if false they will be disabled and de-pop if active
activation If true the points will be activated or deactivated instead of enabled or disabled. Defaults to false.
Definition at line 168 of file PlasmaState.cpp.
References mDeactivated, mDisabled, mLock, mPointHides, and mPoints.
Member Data Documentation
bool channel::PlasmaState::mDeactivated private
Indicates if the plasma set is deactivated and will not re-enable until it has been activated again.
Definition at line 282 of file PlasmaState.h.
Referenced by HasStateChangePoints(), IsActive(), PlasmaState(), and Toggle().
bool channel::PlasmaState::mDisabled private
Indicates if the plasma set is disabled and no points will spawn.
Definition at line 285 of file PlasmaState.h.
Referenced by HasStateChangePoints(), HidePoint(), PlasmaState(), and Toggle().
std::mutex channel::PlasmaState::mLock private
Server lock for shared resources.
Definition at line 288 of file PlasmaState.h.
Referenced by GetActivePoints(), GetPoint(), GetPointStatusData(), HasStateChangePoints(), HideIfEmpty(), PickPoint(), PopHidePoints(), PopRespawnPoints(), SetLoot(), SetPickResult(), and Toggle().
std::unordered_map<uint32_t, uint64_t> channel::PlasmaState::mPointHides private
Map of point IDs to server times when that point should be hidden to respawn later.
Definition at line 278 of file PlasmaState.h.
Referenced by HasStateChangePoints(), HidePoint(), PopHidePoints(), SetPickResult(), and Toggle().
std::unordered_map<uint32_t, uint64_t> channel::PlasmaState::mPointRespawns private
Map of point IDs to server times when that point should be respawned.
Definition at line 274 of file PlasmaState.h.
Referenced by HasStateChangePoints(), HidePoint(), and PopRespawnPoints().
std::unordered_map<uint32_t, std::shared_ptr<PlasmaPoint> > channel::PlasmaState::mPoints private
Map of points by definition ID.
Definition at line 270 of file PlasmaState.h.
Referenced by CreatePoints(), GetActivePoints(), GetPoint(), GetPointStatusData(), HasStateChangePoints(), HideIfEmpty(), PickPoint(), PopHidePoints(), PopRespawnPoints(), SetLoot(), SetPickResult(), and Toggle().
The documentation for this class was generated from the following files:
PlasmaState.h
PlasmaState.cpp