COMP_hack: channel::SkillManager Class Reference
channel::SkillManager Class Reference
Manager to handle skill focused actions.
#include <SkillManager.h>
Public Member Functions
SkillManager (const std::weak_ptr< ChannelServer > &server)
Create a new SkillManager.
~SkillManager ()
Clean up the SkillManager.
bool ActivateSkill (const std::shared_ptr< ActiveEntityState > source, uint32_t skillID, int64_t activationObjectID, int64_t targetObjectID, uint8_t targetType, std::shared_ptr< SkillExecutionContext > ctx=0)
Activate the skill of an active entity.
bool BeginSkillExecution (std::shared_ptr< ProcessingSkill > pSkill, std::shared_ptr< SkillExecutionContext > ctx)
Begin executing a skill.
bool CancelSkill (const std::shared_ptr< ActiveEntityState > source, int8_t activationID, uint8_t cancelType=1)
Cancel the activated skill of an active entity.
bool CompleteSkillExecution (std::shared_ptr< ProcessingSkill > pSkill, std::shared_ptr< SkillExecutionContext > ctx, uint64_t syncTime)
Complete executing a skill.
bool DetermineNormalCosts (const std::shared_ptr< ActiveEntityState > &source, const std::shared_ptr< objects::MiSkillData > &skillData, int32_t &hpCost, int32_t &mpCost, uint16_t &bulletCost, std::unordered_map< uint32_t, uint32_t > &itemCosts, std::shared_ptr< objects::CalculatedEntityState > calcState=nullptr)
Determine how much a skill would cost to execute at a base level for any executing entity, not just a player entity.
bool ExecuteSkill (const std::shared_ptr< ActiveEntityState > source, int8_t activationID, int64_t targetObjectID, std::shared_ptr< SkillExecutionContext > ctx=0)
Execute the skill of an active entity.
bool FunctionIDMapped (uint16_t functionID)
Check if the supplied function ID is mapped to a special function within the skill manager.
bool PrepareFusionSkill (const std::shared_ptr< ChannelClientConnection > client, uint32_t &skillID, int32_t targetEntityID, int64_t mainDemonID, int64_t compDemonID)
Check fusion skill usage pre-skill validation and determine which one should be used.
void ProjectileHit (std::shared_ptr< ProcessingSkill > pSkill, std::shared_ptr< SkillExecutionContext > ctx)
Complete executing a skill with a projectile, simulating the effect of the projectile having just hit.
void ScheduleAutoCancel (const std::shared_ptr< ActiveEntityState > source, const std::shared_ptr< objects::ActivatedAbility > &activated)
Schedule automatic skill cancellation after a set amount of time as defined by the skill definition.
void SendFailure (const std::shared_ptr< ActiveEntityState > source, uint32_t skillID, const std::shared_ptr< ChannelClientConnection > client, uint8_t errorCode=13, int8_t activationID=-1)
Notify the client that a skill failed activation or execution.
bool SkillRestricted (const std::shared_ptr< ActiveEntityState > source, const std::shared_ptr< objects::MiSkillData > &skillData, int64_t activationObjectID=0, std::shared_ptr< SkillExecutionContext > ctx=nullptr)
Determine if the specified skill is locked from use on the supplied entity.
bool SkillZoneRestricted (uint32_t skillID, const std::shared_ptr< Zone > zone)
Determine if the specified skill is locked from use in the current zone.
bool TargetInRange (const std::shared_ptr< ActiveEntityState > source, const std::shared_ptr< objects::MiSkillData > &skillData, const std::shared_ptr< ActiveEntityState > &target)
Determine if the skill target supplied is in range for a specific skill.
bool TargetSkill (const std::shared_ptr< ActiveEntityState > source, int64_t targetObjectID)
Target/retarget the skill of a character or demon.
bool ValidateActivationItem (const std::shared_ptr< ActiveEntityState > source, const std::shared_ptr< objects::Item > &item)
Determine if the skill activation item supplied is valid for a specific source entity.
int8_t ValidateSkillTarget (const std::shared_ptr< ActiveEntityState > source, const std::shared_ptr< objects::MiSkillData > &skillData, const std::shared_ptr< ActiveEntityState > &target)
Determine if the skill target supplied is valid for a specific skill.
Static Public Member Functions
static std::pair< float, float > GetMovementSpeeds (const std::shared_ptr< ActiveEntityState > &source, const std::shared_ptr< objects::MiSkillData > &skillData)
Get the charge and post charge movement speeds for a skill for the supplied entity's current state.
static bool SkillHasMoreUses (const std::shared_ptr< objects::ActivatedAbility > &activated)
Determine if a skill has more uses pending.
Private Member Functions
bool ApplyNegotiationDamage (const std::shared_ptr< ActiveEntityState > &source, SkillTargetResult &target, const std::shared_ptr< channel::ProcessingSkill > &pSkill)
Determine if the supplied target should receive any negotation related effects from the skill used and apply them if applicable.
bool ApplyPrimaryCounter (const std::shared_ptr< ActiveEntityState > &source, const std::shared_ptr< channel::ProcessingSkill > &pSkill, bool guard)
Determine how the primary target reacts to being hit by a skill by either guarding, dodging or countering.
void ApplySecondaryCounter (const std::shared_ptr< ActiveEntityState > &source, SkillTargetResult &target, const std::shared_ptr< channel::ProcessingSkill > &pSkill)
Determine how non-primary targets react to being hit by a skill by either guarding or dodging.
bool ApplyZoneSpecificEffects (const std::shared_ptr< channel::ProcessingSkill > &pSkill)
After calculating the normal skill results during final processing zone specific changes are applied here.
bool CalculateDamage (const std::shared_ptr< ActiveEntityState > &source, const std::shared_ptr< channel::ProcessingSkill > &pSkill)
Calculate skill damage or healing using the correct formula.
int32_t CalculateDamage_MaxPercent (uint16_t mod, uint8_t &damageType, int32_t max)
Calculate skill damage or healing based on a max relative value.
int32_t CalculateDamage_Normal (const std::shared_ptr< ActiveEntityState > &source, SkillTargetResult &target, const std::shared_ptr< channel::ProcessingSkill > &pSkill, uint16_t mod, uint8_t &damageType, float resist, uint8_t critLevel, bool isHeal)
Calculate skill damage or healing using the default formula.
int32_t CalculateDamage_Percent (uint16_t mod, uint8_t &damageType, int32_t current)
Calculate skill damage or healing based on a percent value.
int32_t CalculateDamage_Static (uint16_t mod, uint8_t &damageType)
Calculate skill damage or healing based on a static value.
uint16_t CalculateOffenseValue (const std::shared_ptr< ActiveEntityState > &source, const std::shared_ptr< ActiveEntityState > &target, const std::shared_ptr< channel::ProcessingSkill > &pSkill)
Calculate and set the offense value of a damage dealing skill.
int8_t CalculateStatusEffectStack (int8_t minStack, int8_t maxStack) const
Get a random stack size for a status effect being applied.
bool Cameo (const std::shared_ptr< objects::ActivatedAbility > &activated, const std::shared_ptr< SkillExecutionContext > &ctx, const std::shared_ptr< ChannelClientConnection > &client)
Execute the "cameo" transformation skill.
bool Cloak (const std::shared_ptr< objects::ActivatedAbility > &activated, const std::shared_ptr< SkillExecutionContext > &ctx, const std::shared_ptr< ChannelClientConnection > &client)
Execute an entity cloaking skill.
bool DCM (const std::shared_ptr< objects::ActivatedAbility > &activated, const std::shared_ptr< SkillExecutionContext > &ctx, const std::shared_ptr< ChannelClientConnection > &client)
Execute the "demonic compendium memory" skill.
bool Despawn (const std::shared_ptr< objects::ActivatedAbility > &activated, const std::shared_ptr< SkillExecutionContext > &ctx, const std::shared_ptr< ChannelClientConnection > &client)
Execute an enemy despawning skill.
bool Desummon (const std::shared_ptr< objects::ActivatedAbility > &activated, const std::shared_ptr< SkillExecutionContext > &ctx, const std::shared_ptr< ChannelClientConnection > &client)
Execute a targeted spawn desummon skill.
bool DetermineCosts (std::shared_ptr< ActiveEntityState > source, std::shared_ptr< objects::ActivatedAbility > activated, const std::shared_ptr< ChannelClientConnection > client, std::shared_ptr< SkillExecutionContext > ctx)
Calculate and set the costs required to execute a skill.
bool Digitalize (const std::shared_ptr< objects::ActivatedAbility > &activated, const std::shared_ptr< SkillExecutionContext > &ctx, const std::shared_ptr< ChannelClientConnection > &client)
Execute a skill that results in digitalizing the player character.
bool DigitalizeBreak (const std::shared_ptr< objects::ActivatedAbility > &activated, const std::shared_ptr< SkillExecutionContext > &ctx, const std::shared_ptr< ChannelClientConnection > &client)
Execute a skill that forces the cancellation of all targets hit.
bool DigitalizeCancel (const std::shared_ptr< objects::ActivatedAbility > &activated, const std::shared_ptr< SkillExecutionContext > &ctx, const std::shared_ptr< ChannelClientConnection > &client)
Execute a digitalize state cancellation skill.
bool DirectStatus (const std::shared_ptr< objects::ActivatedAbility > &activated, const std::shared_ptr< SkillExecutionContext > &ctx, const std::shared_ptr< ChannelClientConnection > &client)
Execute a skill that always adds a specific status effect after the skill's execution.
bool EquipItem (const std::shared_ptr< objects::ActivatedAbility > &activated, const std::shared_ptr< SkillExecutionContext > &ctx, const std::shared_ptr< ChannelClientConnection > &client)
Execute the "equip item" skill.
bool Estoma (const std::shared_ptr< objects::ActivatedAbility > &activated, const std::shared_ptr< SkillExecutionContext > &ctx, const std::shared_ptr< ChannelClientConnection > &client)
Execute the aggro clearing "Estoma" skill.
int8_t EvaluateTokuseiSkillCondition (const std::shared_ptr< ActiveEntityState > &eState, const std::shared_ptr< objects::TokuseiSkillCondition > &condition, const std::shared_ptr< channel::ProcessingSkill > &pSkill, const std::shared_ptr< ActiveEntityState > &otherState)
Evaluate a TokuseiSkillCondition relative to the current skill and supplied entities.
int8_t EvaluateTokuseiSkillConditions (const std::shared_ptr< ActiveEntityState > &eState, const std::list< std::shared_ptr< objects::TokuseiSkillCondition >> &conditions, const std::shared_ptr< channel::ProcessingSkill > &pSkill, const std::shared_ptr< ActiveEntityState > &otherState)
Evaluate TokuseiSkillConditions relative to the current skill and supplied entities.
bool ExecuteNormalSkill (const std::shared_ptr< ChannelClientConnection > client, std::shared_ptr< objects::ActivatedAbility > activated, const std::shared_ptr< SkillExecutionContext > &ctx)
Execute a normal skill, not handled by a special handler.
bool ExecuteSkill (std::shared_ptr< ActiveEntityState > source, std::shared_ptr< objects::ActivatedAbility > activated, const std::shared_ptr< ChannelClientConnection > client, std::shared_ptr< SkillExecutionContext > ctx, bool delayedAuto=false)
Pay any costs related to and execute the skill of a character or demon.
bool FamiliarityUp (const std::shared_ptr< objects::ActivatedAbility > &activated, const std::shared_ptr< SkillExecutionContext > &ctx, const std::shared_ptr< ChannelClientConnection > &client)
Execute a familiarity boosting skill.
bool FamiliarityUpItem (const std::shared_ptr< objects::ActivatedAbility > &activated, const std::shared_ptr< SkillExecutionContext > &ctx, const std::shared_ptr< ChannelClientConnection > &client)
Execute a familiarity boosting skill from an item.
std::shared_ptr
< objects::ActivatedAbility > FinalizeSkill (const std::shared_ptr< SkillExecutionContext > &ctx, std::shared_ptr< objects::ActivatedAbility > activated)
Finalize a skill that has been activated and remove it from the entity if it does not have additional uses.
void FinalizeSkillExecution (const std::shared_ptr< ChannelClientConnection > client, const std::shared_ptr< SkillExecutionContext > &ctx, std::shared_ptr< objects::ActivatedAbility > activated)
Execute post execution steps like notifying the client that the skill has executed and updating any related expertises.
void Fizzle (const std::shared_ptr< SkillExecutionContext > &ctx)
Fizzle a skill that has already started processing and perform any necessary cleanup steps.
bool ForgetAllExpertiseSkills (const std::shared_ptr< objects::ActivatedAbility > &activated, const std::shared_ptr< SkillExecutionContext > &ctx, const std::shared_ptr< ChannelClientConnection > &client)
Execute a skill that causes all character expertise skills to be forgotten.
std::shared_ptr
< objects::ActivatedAbility > GetActivation (const std::shared_ptr< ActiveEntityState > source, int8_t activationID) const
Get the current or past special skill activation by ID.
float GetAffinityBoost (const std::shared_ptr< ActiveEntityState > eState, std::shared_ptr< objects::CalculatedEntityState > calcState, CorrectTbl boostType)
Get the specific affinity boost associated to the supplied entity.
std::shared_ptr
< objects::CalculatedEntityState > GetCalculatedState (const std::shared_ptr< ActiveEntityState > &eState, const std::shared_ptr< channel::ProcessingSkill > &pSkill, bool isTarget, const std::shared_ptr< ActiveEntityState > &otherState)
Get a CalculatedEntityState based upon the skill being executed and the state of the entity as either the source or a target of the skill.
uint8_t GetCritLevel (const std::shared_ptr< ActiveEntityState > &source, SkillTargetResult &target, const std::shared_ptr< channel::ProcessingSkill > &pSkill)
Get the critical level of a skill that is being calculated for damage and has already been determined as a hit.
int16_t GetEntityRate (const std::shared_ptr< ActiveEntityState > eState, std::shared_ptr< objects::CalculatedEntityState > calcState, bool taken)
Get the entity rate scaling correct table value associated to the the supplied entity from the other entity's calculated state.
std::unordered_map< uint8_t,
std::list< std::shared_ptr
< objects::ItemDrop > > > GetItemDrops (const std::shared_ptr< ActiveEntityState > &source, const std::shared_ptr< ActiveEntityState > &eState, const std::shared_ptr< ChannelClientConnection > &client, const std::shared_ptr< Zone > &zone, bool giftMode=false)
Gather drops for a specific enemy spawn from its own drops, global drops and demon family drops.
uint8_t GetNRAResult (SkillTargetResult &target, ProcessingSkill &skill, uint8_t effectiveAffinity)
Get the result of the skill target's null, reflect or absorb checks.
uint8_t GetNRAResult (SkillTargetResult &target, ProcessingSkill &skill, uint8_t effectiveAffinity, uint8_t &resultAffinity, bool effectiveOnly, bool reduceShields)
Get the result of the skill target's null, reflect or absorb checks.
std::shared_ptr< ProcessingSkill > GetProcessingSkill (std::shared_ptr< objects::ActivatedAbility > activated, std::shared_ptr< SkillExecutionContext > ctx)
Get a processing skill set with default values from the supplied ability and context.
SkillTargetResult * GetSelfTarget (const std::shared_ptr< ActiveEntityState > &source, std::list< SkillTargetResult > &targets, bool indirectDefault, bool autoCreate=true)
Get the skill target that hits the source entity or create it if it does not already exist.
uint32_t GetSummonSpeed (const std::shared_ptr< channel::ProcessingSkill > &pSkill, const std::shared_ptr< ChannelClientConnection > &client)
Determine the summon speed for the supplied client and the targeted demon in the COMP.
void GiveDemonPresent (const std::shared_ptr< ChannelClientConnection > &client, uint32_t demonType, uint32_t itemType, int8_t rarity, uint32_t skillID)
Give a demon present to the player character as the result of a familiarity adjusting skill.
bool HandleCounter (const std::shared_ptr< ActiveEntityState > &source, SkillTargetResult &target, const std::shared_ptr< channel::ProcessingSkill > &pSkill)
Execute or cancel the counter skill currently being used by the supplied target from being hit by the source entity.
void HandleDigitalizeXP (const std::shared_ptr< ActiveEntityState > source, const std::list< std::shared_ptr< ActiveEntityState >> &enemies, const std::shared_ptr< Zone > &zone)
Increase digitalize experience points for the supplied source's party based upon defeated enemies.
bool HandleDodge (const std::shared_ptr< ActiveEntityState > &source, SkillTargetResult &target, const std::shared_ptr< channel::ProcessingSkill > &pSkill)
Execute or cancel the dodge skill currently being used by the supplied target from being hit by the source entity.
void HandleDurabilityDamage (const std::shared_ptr< ActiveEntityState > entity, const std::shared_ptr< channel::ProcessingSkill > &pSkill)
Update item durability on the supplied entity if its entity is a character.
void HandleEncounterDefeat (const std::shared_ptr< ActiveEntityState > source, const std::shared_ptr< Zone > &zone, const std::unordered_map< uint32_t, uint32_t > &encounterGroups)
Handle all logic related to defeating an enemy encounter through combat or talk skill outcome.
void HandleFusionGauge (const std::shared_ptr< channel::ProcessingSkill > &pSkill)
If the skill is not a fusion skill and also an offensive action type, raise the fusion gauge.
bool HandleGuard (const std::shared_ptr< ActiveEntityState > &source, SkillTargetResult &target, const std::shared_ptr< channel::ProcessingSkill > &pSkill)
Execute or cancel the guard skill currently being used by the supplied target from being hit by the source entity.
void HandleKills (const std::shared_ptr< ActiveEntityState > source, const std::shared_ptr< Zone > &zone, const std::set< std::shared_ptr< ActiveEntityState >> killed)
Handle all logic related to kills that occurred from a skill's execution.
void HandleKillXP (const std::shared_ptr< objects::Enemy > &enemy, const std::shared_ptr< Zone > &zone)
Distribute all XP from a defeated enemy to each player that caused damage to it, adjusting for active party members and players still in the zone.
void HandleNegotiations (const std::shared_ptr< ActiveEntityState > source, const std::shared_ptr< Zone > &zone, const std::list< std::pair< std::shared_ptr< ActiveEntityState >, uint8_t >> talkDone)
Handle the outcome of a negotation ending from a skill's execution including things like creating demon eggs and gift boxes or running away.
void HandleRevives (const std::shared_ptr< Zone > &zone, const std::set< std::shared_ptr< ActiveEntityState >> revived, const std::shared_ptr< channel::ProcessingSkill > &pSkill)
Handle all logic related to revivals that occurred from a skill's execution.
bool HandleSkillInterrupt (const std::shared_ptr< ActiveEntityState > &source, SkillTargetResult &target, const std::shared_ptr< channel::ProcessingSkill > &pSkill)
Apply target skill interrupt based upon timing and state of the target entity's skill being charged or executed.
void HandleSkillLearning (const std::shared_ptr< ActiveEntityState > entity, const std::shared_ptr< channel::ProcessingSkill > &pSkill)
Update InheritedSkills on the supplied entity if its entity type is partner demon.
std::set< uint32_t > HandleStatusEffects (const std::shared_ptr< ActiveEntityState > &source, SkillTargetResult &target, const std::shared_ptr< channel::ProcessingSkill > &pSkill)
Handle all status effect application logic for a specific target.
bool IFramesEnabled ()
Determine if invincibility frames are enabled for the server to adjust skill timing.
void InterruptEvents (const std::set< int32_t > &worldCIDs)
Interrupt any active events associated to the supplied world CIDs as a result of being hit by a combat skill.
bool IsTalkSkill (const std::shared_ptr< objects::MiSkillData > &skillData, bool primaryOnly)
Determine if the supplied skill data will involve talk results either from a negotiation skill or a skill with negotiation damage.
bool Liberama (const std::shared_ptr< objects::ActivatedAbility > &activated, const std::shared_ptr< SkillExecutionContext > &ctx, const std::shared_ptr< ChannelClientConnection > &client)
Execute the aggro drawing "liberama" skill.
bool MinionDespawn (const std::shared_ptr< objects::ActivatedAbility > &activated, const std::shared_ptr< SkillExecutionContext > &ctx, const std::shared_ptr< ChannelClientConnection > &client)
Execute a minion despawning skill.
bool MinionSpawn (const std::shared_ptr< objects::ActivatedAbility > &activated, const std::shared_ptr< SkillExecutionContext > &ctx, const std::shared_ptr< ChannelClientConnection > &client)
Execute a minion spawning skill.
bool Mooch (const std::shared_ptr< objects::ActivatedAbility > &activated, const std::shared_ptr< SkillExecutionContext > &ctx, const std::shared_ptr< ChannelClientConnection > &client)
Execute the "Mooch" skill.
bool Mount (const std::shared_ptr< objects::ActivatedAbility > &activated, const std::shared_ptr< SkillExecutionContext > &ctx, const std::shared_ptr< ChannelClientConnection > &client)
Execute a demon riding skill.
bool ProcessSkillResult (std::shared_ptr< objects::ActivatedAbility > activated, std::shared_ptr< SkillExecutionContext > ctx)
Process the results of a skill.
void ProcessSkillResultFinal (const std::shared_ptr< channel::ProcessingSkill > &pSkill, std::shared_ptr< SkillExecutionContext > ctx)
Finalize skill processing and send the skill effect reports.
bool RandomItem (const std::shared_ptr< objects::ActivatedAbility > &activated, const std::shared_ptr< SkillExecutionContext > &ctx, const std::shared_ptr< ChannelClientConnection > &client)
Execute a random item granting skill.
bool Randomize (const std::shared_ptr< objects::ActivatedAbility > &activated, const std::shared_ptr< SkillExecutionContext > &ctx, const std::shared_ptr< ChannelClientConnection > &client)
Execute a skill that is requesting a random number.
bool Respec (const std::shared_ptr< objects::ActivatedAbility > &activated, const std::shared_ptr< SkillExecutionContext > &ctx, const std::shared_ptr< ChannelClientConnection > &client)
Execute a skill that causes all character skill points to be reset.
bool Rest (const std::shared_ptr< objects::ActivatedAbility > &activated, const std::shared_ptr< SkillExecutionContext > &ctx, const std::shared_ptr< ChannelClientConnection > &client)
Handle the "Rest" skill.
void ScheduleFreeLoot (uint64_t time, const std::shared_ptr< Zone > &zone, const std::list< int32_t > &lootEntityIDs, const std::set< int32_t > &worldCIDs)
Schedule the adjustment of who is a valid looter for one or more loot boxes.
void SendActivateSkill (const std::shared_ptr< channel::ProcessingSkill > &pSkill)
Notify the client that a skill has been activated.
void SendCompleteSkill (std::shared_ptr< objects::ActivatedAbility > activated, uint8_t mode)
Notify the client that a skill is complete.
void SendExecuteSkill (const std::shared_ptr< channel::ProcessingSkill > &pSkill)
Notify the client that a skill is executing.
void SendExecuteSkillInstant (const std::shared_ptr< channel::ProcessingSkill > &pSkill, uint8_t errorCode)
Notify the client that a skill is immediately executing without some normal prerequisite packets.
void SendFailure (std::shared_ptr< objects::ActivatedAbility > activated, const std::shared_ptr< ChannelClientConnection > client, uint8_t errorCode=0)
Notify the client that a skill failed activation or execution.
bool SetNRA (SkillTargetResult &target, ProcessingSkill &skill, bool reduceShields=true)
Set null, reflect or absorb on the skill target.
bool SetSkillCompleteState (const std::shared_ptr< channel::ProcessingSkill > &pSkill, bool executed)
Mark all information pertaining to a skill completing either through execution or cancellation with more uses available.
bool Spawn (const std::shared_ptr< objects::ActivatedAbility > &activated, const std::shared_ptr< SkillExecutionContext > &ctx, const std::shared_ptr< ChannelClientConnection > &client)
Execute a (non-zone specific) enemy spawning skill.
bool SpawnZone (const std::shared_ptr< objects::ActivatedAbility > &activated, const std::shared_ptr< SkillExecutionContext > &ctx, const std::shared_ptr< ChannelClientConnection > &client)
Execute a zone specific enemy spawning skill.
bool SpecialSkill (const std::shared_ptr< objects::ActivatedAbility > &activated, const std::shared_ptr< SkillExecutionContext > &ctx, const std::shared_ptr< ChannelClientConnection > &client)
Placeholder function for a skill actually handled outside of the SkillManager.
bool StoreDemon (const std::shared_ptr< objects::ActivatedAbility > &activated, const std::shared_ptr< SkillExecutionContext > &ctx, const std::shared_ptr< ChannelClientConnection > &client)
Execute the "store demon" skill.
bool SummonDemon (const std::shared_ptr< objects::ActivatedAbility > &activated, const std::shared_ptr< SkillExecutionContext > &ctx, const std::shared_ptr< ChannelClientConnection > &client)
Execute the "summon demon" skill.
bool ToggleSwitchSkill (const std::shared_ptr< ChannelClientConnection > client, std::shared_ptr< objects::ActivatedAbility > activated, const std::shared_ptr< SkillExecutionContext > &ctx)
Toggle a switch skill, not handled by a special handler.
bool Traesto (const std::shared_ptr< objects::ActivatedAbility > &activated, const std::shared_ptr< SkillExecutionContext > &ctx, const std::shared_ptr< ChannelClientConnection > &client)
Execute the skill "Traesto" which returns the user to a preset zone.
void UpdatePvPStats (const std::shared_ptr< channel::ProcessingSkill > &pSkill)
Update all PvP instance recorded statistics if the match is active.
bool XPUp (const std::shared_ptr< objects::ActivatedAbility > &activated, const std::shared_ptr< SkillExecutionContext > &ctx, const std::shared_ptr< ChannelClientConnection > &client)
Execute a skill that grants XP to the character or partner demon.
Private Attributes
std::weak_ptr< ChannelServer > mServer
Pointer to the channel server.
std::unordered_map< uint16_t,
std::function< bool(SkillManager
&, const std::shared_ptr
< objects::ActivatedAbility >
&, const std::shared_ptr
< SkillExecutionContext >
&, const std::shared_ptr
< ChannelClientConnection > &)> > mSkillEffectFunctions
Map of skill function IDs mapped to manager functions that perform special actions after the normal skill processing completes.
std::unordered_map< uint16_t,
std::function< bool(SkillManager
&, const std::shared_ptr
< objects::ActivatedAbility >
&, const std::shared_ptr
< SkillExecutionContext >
&, const std::shared_ptr
< ChannelClientConnection > &)> > mSkillFunctions
Map of skill function IDs mapped to manager functions that execute in place of the normal skill handler.
Detailed Description
Manager to handle skill focused actions.
Definition at line 115 of file SkillManager.h.
Constructor & Destructor Documentation
SkillManager::SkillManager (const std::weak_ptr< ChannelServer > & server)
Create a new SkillManager.
Parameters
server Pointer back to the channel server this belongs to
Definition at line 285 of file SkillManager.cpp.
References Cameo(), Cloak(), DCM(), Despawn(), Desummon(), Digitalize(), DigitalizeBreak(), DigitalizeCancel(), DirectStatus(), EquipItem(), Estoma(), FamiliarityUp(), FamiliarityUpItem(), ForgetAllExpertiseSkills(), Liberama(), MinionDespawn(), MinionSpawn(), Mooch(), Mount(), mSkillEffectFunctions, mSkillFunctions, RandomItem(), Randomize(), Respec(), Rest(), Spawn(), SpawnZone(), SpecialSkill(), StoreDemon(), SummonDemon(), SVR_CONST, Traesto(), and XPUp().
SkillManager::~SkillManager ()
Clean up the SkillManager.
Definition at line 343 of file SkillManager.cpp.
Member Function Documentation
bool SkillManager::ActivateSkill (const std::shared_ptr< ActiveEntityState > source, uint32_t skillID, int64_t activationObjectID, int64_t targetObjectID, uint8_t targetType, std::shared_ptr< SkillExecutionContext > ctx = 0)
Activate the skill of an active entity.
The client will have the charge information sent to it if there is a charge time, otherwise it will execute automatically.
Parameters
source Pointer of the entity that activated the skill
skillID ID of the skill to activate
activationObjectID ID of the object used as the activation target
targetObjectID ID of the object being targeted by the skill, typically only set for instant activation skills at this phase. If a call to ExecuteSkill is performed after activation, the supplied targetObjectID will override this value.
targetType Type of entity/object being targeted by the activationObjectID (and sometimes targetObjectID as well)
ctx Special execution state for the skill (ex: free cast, counter)
Returns
true if the skill was activated successfully, false otherwise
Definition at line 347 of file SkillManager.cpp.
References libcomp::String::Arg(), CancelSkill(), ExecuteSkill(), GetCalculatedState(), GetMovementSpeeds(), GetProcessingSkill(), channel::ChannelServer::GetServerTime(), GetSummonSpeed(), mServer, mSkillFunctions, ScheduleAutoCancel(), SendActivateSkill(), SendFailure(), SkillRestricted(), SkillZoneRestricted(), STATUS_CHARGING, STATUS_KNOCKBACK, STATUS_LOCKOUT, and SVR_CONST.
bool SkillManager::ApplyNegotiationDamage (const std::shared_ptr< ActiveEntityState > & source, SkillTargetResult & target, const std::shared_ptr< channel::ProcessingSkill > & pSkill) private
Determine if the supplied target should receive any negotation related effects from the skill used and apply them if applicable.
Parameters
source Pointer to the state of the source entity
target Skill targeted entity
pSkill Skill processing state of the skill being executed
Returns
true if the negotation has completed
Definition at line 7673 of file SkillManager.cpp.
References channel::SkillTargetResult::EntityState, FLAG1_DODGED, FLAG1_GUARDED, channel::SkillTargetResult::Flags1, GetCalculatedState(), channel::ActiveEntityStateImp< T >::GetEntity(), IsTalkSkill(), mServer, RNG, SVR_CONST, TALK_GIVE_ITEM, TALK_GIVE_ITEM_2, TALK_JOIN, TALK_JOIN_2, TALK_LEAVE, TALK_REJECT, TALK_RESPONSE_1, TALK_RESPONSE_4, channel::SkillTargetResult::TalkDone, and channel::SkillTargetResult::TalkFlags.
Referenced by ProcessSkillResultFinal().
bool SkillManager::ApplyPrimaryCounter (const std::shared_ptr< ActiveEntityState > & source, const std::shared_ptr< channel::ProcessingSkill > & pSkill, bool guard) private
Determine how the primary target reacts to being hit by a skill by either guarding, dodging or countering.
This assumes NRA has already been applied. Upon success a target for the entity will be added to the skill's targets list.
Parameters
source Pointer to the state of the source entity
pSkill Current skill processing state
guard If true, guard skills will be checked too, if false only dodge and counter will be checked
Returns
true if the skill was countered, false if it was not
Definition at line 5519 of file SkillManager.cpp.
References channel::SkillTargetResult::CalcState, channel::SkillTargetResult::EntityState, GetCalculatedState(), HandleCounter(), HandleDodge(), HandleGuard(), and channel::SkillTargetResult::PrimaryTarget.
Referenced by BeginSkillExecution(), ProcessSkillResult(), and ProjectileHit().
void SkillManager::ApplySecondaryCounter (const std::shared_ptr< ActiveEntityState > & source, SkillTargetResult & target, const std::shared_ptr< channel::ProcessingSkill > & pSkill) private
Determine how non-primary targets react to being hit by a skill by either guarding or dodging.
Countering cannot occur at this point. This assumes NRA has already been applied.
Parameters
source Pointer to the state of the source entity
target Skill targeted entity
pSkill Skill processing state of the skill
Definition at line 5573 of file SkillManager.cpp.
References channel::SkillTargetResult::EntityState, HandleDodge(), HandleGuard(), channel::SkillTargetResult::HitAbsorb, channel::SkillTargetResult::HitNull, and channel::SkillTargetResult::HitReflect.
Referenced by ProcessSkillResult().
bool SkillManager::ApplyZoneSpecificEffects (const std::shared_ptr< channel::ProcessingSkill > & pSkill) private
After calculating the normal skill results during final processing zone specific changes are applied here.
Parameters
pSkill Skill processing state of the skill being executed
Returns
true if any changes were applied, false if they were not
Definition at line 7359 of file SkillManager.cpp.
References channel::SkillTargetResult::Damage1, channel::SkillTargetResult::Damage1Type, DAMAGE_TYPE_GENERIC, DAMAGE_TYPE_HEALING, EFFECT_CANCEL_DAMAGE, EFFECT_CANCEL_DEATH, EFFECT_CANCEL_HIT, channel::SkillTargetResult::EffectCancellations, channel::SkillTargetResult::EntityState, FLAG1_LETHAL, FLAG1_REVIVAL, channel::SkillTargetResult::Flags1, channel::ClientState::GetCharacterState(), channel::ClientState::GetEntityClientState(), channel::SkillTargetResult::RecalcTriggers, and UpdatePvPStats().
Referenced by ProcessSkillResultFinal().
bool SkillManager::BeginSkillExecution (std::shared_ptr< ProcessingSkill > pSkill, std::shared_ptr< SkillExecutionContext > ctx)
Begin executing a skill.
If skill staggering is enabled and the target is already being attacked or is stunned, the source will be sent a retry request that will occur automatically for clients.
Parameters
pSkill Current skill processing state
ctx Special execution state for the skill false if the skill failed execution immediately, true if it succeeded or was queued
Definition at line 1915 of file SkillManager.cpp.
References ApplyPrimaryCounter(), libcomp::String::Arg(), channel::SkillTargetResult::CalcState, CancelSkill(), CompleteSkillExecution(), channel::SkillTargetResult::EntityState, FinalizeSkillExecution(), GetCalculatedState(), channel::ChannelServer::GetServerTime(), channel::SkillTargetResult::HitAbsorb, channel::SkillTargetResult::HitNull, channel::SkillTargetResult::HitReflect, mServer, channel::NONE, channel::SkillTargetResult::NRAAffinity, SendFailure(), SetNRA(), STATUS_HIT_STUN, SVR_CONST, and TargetInRange().
Referenced by ExecuteNormalSkill().
bool SkillManager::CalculateDamage (const std::shared_ptr< ActiveEntityState > & source, const std::shared_ptr< channel::ProcessingSkill > & pSkill) private
Calculate skill damage or healing using the correct formula.
Parameters
source Pointer to the entity that activated the skill
pSkill Pointer to the current skill processing state
Returns
true if the calculation succeeded, false otherwise
Definition at line 8532 of file SkillManager.cpp.
References channel::ProcessingSkill::Activated, libcomp::String::Arg(), channel::SkillTargetResult::AutoProtect, CalculateDamage_MaxPercent(), CalculateDamage_Normal(), CalculateDamage_Percent(), CalculateDamage_Static(), channel::SkillTargetResult::Damage1, channel::SkillTargetResult::Damage1Type, channel::SkillTargetResult::Damage2, channel::SkillTargetResult::Damage2Type, DAMAGE_EXPLICIT_SET, DAMAGE_TYPE_DRAIN, DAMAGE_TYPE_GENERIC, DAMAGE_TYPE_HEALING, channel::ProcessingSkill::Definition, channel::ProcessingSkill::EffectiveAffinity, channel::SkillTargetResult::EntityState, FLAG1_CRITICAL, FLAG1_PROTECT, FLAG1_WEAKPOINT, FLAG2_IMPOSSIBLE, FLAG2_INTENSIVE_BREAK, FLAG2_LIMIT_BREAK, channel::SkillTargetResult::Flags1, channel::SkillTargetResult::Flags2, channel::ProcessingSkill::FunctionID, GetCalculatedState(), GetCritLevel(), GetEntityRate(), GetNRAResult(), GetSelfTarget(), channel::SkillTargetResult::HitAbsorb, channel::SkillTargetResult::HitAvoided, mServer, channel::NONE, channel::SkillTargetResult::PrimaryTarget, channel::SkillTargetResult::PursuitAffinity, channel::SkillTargetResult::PursuitDamage, RES_OFFSET, RNG, SVR_CONST, channel::ProcessingSkill::Targets, channel::SkillTargetResult::TechnicalDamage, and channel::ProcessingSkill::WeaponAffinity.
Referenced by ProcessSkillResultFinal().
int32_t SkillManager::CalculateDamage_MaxPercent (uint16_t mod, uint8_t & damageType, int32_t max) private
Calculate skill damage or healing based on a max relative value.
Parameters
mod Base modifier damage value
damageType Type of damage being dealt
max Maximum value to calculate relative damage to
Returns
Raw calculated damage or healing (no cap applied)
Definition at line 9481 of file SkillManager.cpp.
References DAMAGE_TYPE_GENERIC.
Referenced by CalculateDamage().
int32_t SkillManager::CalculateDamage_Normal (const std::shared_ptr< ActiveEntityState > & source, SkillTargetResult & target, const std::shared_ptr< channel::ProcessingSkill > & pSkill, uint16_t mod, uint8_t & damageType, float resist, uint8_t critLevel, bool isHeal) private
Calculate skill damage or healing using the default formula.
Parameters
source Pointer to the entity that activated the skill
target Pointer to the entity that will receive damage
pSkill Pointer to the current skill processing state
mod Base modifier damage value
damageType Type of damage being dealt
resist Resistence to the skill affinity
critLevel Critical level adjustment. Valid values are: 0) No critical adjustment 1) Critical hit 2) Limit break
isHeal true if healing "damage" should be applied instead
Returns
Raw calculated damage or healing (no cap applied)
Definition at line 9214 of file SkillManager.cpp.
References channel::ProcessingSkill::BaseAffinity, BOOST_OFFSET, CalculateOffenseValue(), DAMAGE_TYPE_GENERIC, channel::ProcessingSkill::Definition, channel::ProcessingSkill::EffectiveAffinity, channel::ProcessingSkill::EffectiveDependencyType, channel::SkillTargetResult::EntityState, channel::ProcessingSkill::ExpertiseRankBoost, channel::ProcessingSkill::FunctionID, GetAffinityBoost(), GetCalculatedState(), GetEntityRate(), channel::SkillTargetResult::GuardModifier, mServer, channel::NONE, RNG_DEC, and SVR_CONST.
Referenced by CalculateDamage().
int32_t SkillManager::CalculateDamage_Percent (uint16_t mod, uint8_t & damageType, int32_t current) private
Calculate skill damage or healing based on a percent value.
Parameters
mod Base modifier damage value
damageType Type of damage being dealt
Returns
Raw calculated damage or healing (no cap applied)
Definition at line 9467 of file SkillManager.cpp.
References DAMAGE_TYPE_GENERIC.
Referenced by CalculateDamage().
int32_t SkillManager::CalculateDamage_Static (uint16_t mod, uint8_t & damageType) private
Calculate skill damage or healing based on a static value.
Parameters
mod Base modifier damage value
damageType Type of damage being dealt
Returns
Raw calculated damage or healing (no cap applied)
Definition at line 9454 of file SkillManager.cpp.
References DAMAGE_TYPE_GENERIC.
Referenced by CalculateDamage().
uint16_t SkillManager::CalculateOffenseValue (const std::shared_ptr< ActiveEntityState > & source, const std::shared_ptr< ActiveEntityState > & target, const std::shared_ptr< channel::ProcessingSkill > & pSkill) private
Calculate and set the offense value of a damage dealing skill.
Parameters
source Pointer to the state of the source entity
target Pointer to the state of the target entity
pSkill Pointer to the current skill processing state
Returns
Calculated offsense value of the skill
Definition at line 5429 of file SkillManager.cpp.
References libcomp::String::Arg(), channel::SkillExecutionContext::CounteredSkill, channel::ProcessingSkill::EffectiveDependencyType, channel::ProcessingSkill::ExecutionContext, GetCalculatedState(), channel::NONE, and channel::ProcessingSkill::OffenseValues.
Referenced by CalculateDamage_Normal().
int8_t SkillManager::CalculateStatusEffectStack (int8_t minStack, int8_t maxStack) const private
Get a random stack size for a status effect being applied.
Parameters
minStack Minimum size of the stack
maxStack Maximum size of the stack
Returns
Random stack size between the range or 0 if the range is invalid
Definition at line 9694 of file SkillManager.cpp.
References RNG.
Referenced by FamiliarityUp(), HandleStatusEffects(), Mooch(), and Rest().
bool SkillManager::Cameo (const std::shared_ptr< objects::ActivatedAbility > & activated, const std::shared_ptr< SkillExecutionContext > & ctx, const std::shared_ptr< ChannelClientConnection > & client) private
Execute the "cameo" transformation skill.
Parameters
activated Pointer to the activated ability instance
ctx Special execution state for the skill
client Pointer to the client connection that activated the skill, this will always fail if it is null
Definition at line 10262 of file SkillManager.cpp.
References channel::ClientState::GetCharacterState(), libcomp::Randomizer::GetEntry(), mServer, ProcessSkillResult(), SendFailure(), SpecialSkill(), channel::state(), and SVR_CONST.
Referenced by SkillManager().
bool SkillManager::CancelSkill (const std::shared_ptr< ActiveEntityState > source, int8_t activationID, uint8_t cancelType = 1)
Cancel the activated skill of an active entity.
Parameters
source Pointer of the entity that is cancelling the skill
activationID ID of the activated ability instance
cancelType Cancellation type to send to the client
Returns
true if the skill was cancelled successfully, false otherwise
Definition at line 967 of file SkillManager.cpp.
References libcomp::String::Arg(), GetActivation(), GetProcessingSkill(), mServer, mSkillFunctions, SendCompleteSkill(), SetSkillCompleteState(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS8(), and libcomp::Packet::WriteU32Little().
Referenced by ActivateSkill(), BeginSkillExecution(), Estoma(), HandleCounter(), HandleDodge(), HandleGuard(), HandleKills(), HandleSkillInterrupt(), ScheduleAutoCancel(), and SendFailure().
bool SkillManager::Cloak (const std::shared_ptr< objects::ActivatedAbility > & activated, const std::shared_ptr< SkillExecutionContext > & ctx, const std::shared_ptr< ChannelClientConnection > & client) private
Execute an entity cloaking skill.
Parameters
activated Pointer to the activated ability instance
ctx Special execution state for the skill
client Pointer to the client connection that activated the skill, this will always fail if it is null
Definition at line 10338 of file SkillManager.cpp.
References mServer, ProcessSkillResult(), SendFailure(), and SpecialSkill().
Referenced by SkillManager().
bool SkillManager::CompleteSkillExecution (std::shared_ptr< ProcessingSkill > pSkill, std::shared_ptr< SkillExecutionContext > ctx, uint64_t syncTime)
Complete executing a skill.
If the source has been killed or stunned and it is not a skill that ignores these, it will not execute but costs will still be paid as the skill has already been "shot" by now.
Parameters
pSkill Current skill processing state
ctx Special execution state for the skill
syncTime Accurate skill completion time, useful for server processing delay correction false if the skill failed execution immediately, true if it succeeded or was queued
Definition at line 2148 of file SkillManager.cpp.
References libcomp::String::Arg(), FinalizeSkill(), Fizzle(), channel::ChannelServer::GetServerTime(), mServer, and ProcessSkillResult().
Referenced by BeginSkillExecution().
bool SkillManager::DCM (const std::shared_ptr< objects::ActivatedAbility > & activated, const std::shared_ptr< SkillExecutionContext > & ctx, const std::shared_ptr< ChannelClientConnection > & client) private
Execute the "demonic compendium memory" skill.
Parameters
activated Pointer to the activated ability instance
ctx Special execution state for the skill
client Pointer to the client connection that activated the skill, this will always fail if it is null
Definition at line 10384 of file SkillManager.cpp.
References channel::CharacterManager::ConvertIDToMaskValues(), channel::ClientState::GetAccountUID(), channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), channel::CharacterManager::HasValuable(), mServer, ProcessSkillResult(), SendFailure(), SpecialSkill(), channel::state(), SVR_CONST, libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteU32Little().
Referenced by SkillManager().
bool SkillManager::Despawn (const std::shared_ptr< objects::ActivatedAbility > & activated, const std::shared_ptr< SkillExecutionContext > & ctx, const std::shared_ptr< ChannelClientConnection > & client) private
Execute an enemy despawning skill.
This mimics the behavior of the skill in other games as it was not originally released.
Parameters
activated Pointer to the activated ability instance
ctx Special execution state for the skill
client Pointer to the client connection that activated the skill, this will always fail if it is null
Definition at line 10485 of file SkillManager.cpp.
References ProcessSkillResult(), and SpecialSkill().
Referenced by SkillManager().
bool SkillManager::Desummon (const std::shared_ptr< objects::ActivatedAbility > & activated, const std::shared_ptr< SkillExecutionContext > & ctx, const std::shared_ptr< ChannelClientConnection > & client) private
Execute a targeted spawn desummon skill.
Parameters
activated Pointer to the activated ability instance
ctx Special execution state for the skill
client Pointer to the client connection that activated the skill, this will always fail if it is null
Definition at line 10511 of file SkillManager.cpp.
References libcomp::String::Arg(), mServer, ProcessSkillResult(), SpecialSkill(), and channel::state().
Referenced by SkillManager().
bool SkillManager::DetermineCosts (std::shared_ptr< ActiveEntityState > source, std::shared_ptr< objects::ActivatedAbility > activated, const std::shared_ptr< ChannelClientConnection > client, std::shared_ptr< SkillExecutionContext > ctx) private
Calculate and set the costs required to execute a skill.
Parameters
source Pointer to the state of the source entity
activated Pointer to the activated ability instance
client Pointer to the client connection, can be null if not coming from a player entity
ctx Special execution state for the skill
Returns
true if the skill can be paid, false if it cannot
Definition at line 2357 of file SkillManager.cpp.
References DetermineNormalCosts(), channel::ClientState::GetCharacterState(), libcomp::PersistentObject::GetObjectByUUID(), channel::ClientState::GetObjectUUID(), GetProcessingSkill(), channel::ClientState::GetZone(), mServer, SendFailure(), channel::state(), and SVR_CONST.
Referenced by ExecuteSkill().
bool SkillManager::DetermineNormalCosts (const std::shared_ptr< ActiveEntityState > & source, const std::shared_ptr< objects::MiSkillData > & skillData, int32_t & hpCost, int32_t & mpCost, uint16_t & bulletCost, std::unordered_map< uint32_t, uint32_t > & itemCosts, std::shared_ptr< objects::CalculatedEntityState > calcState = nullptr)
Determine how much a skill would cost to execute at a base level for any executing entity, not just a player entity.
Useful for AI determining skill usefullness. Determining if the costs CAN be paid must be handled elsewhere.
Parameters
source Pointer to the entity that would use the skill
skillData Pointer to the skill definition
hpCost Output parameter containing the HP cost, adjusted for tokusei
mpCost Output parameter containing the MP cost, adjusted for tokusei
bulletCost Output parameter containing how many bullets would be consumed by the skill
itemCosts Output parameter containing how many items would be consumed by the skill (type to count)
Returns
true if no errors were encountered in the costs, false if an error occurred
Definition at line 2632 of file SkillManager.cpp.
References libcomp::String::Arg(), and mServer.
Referenced by DetermineCosts().
bool SkillManager::Digitalize (const std::shared_ptr< objects::ActivatedAbility > & activated, const std::shared_ptr< SkillExecutionContext > & ctx, const std::shared_ptr< ChannelClientConnection > & client) private
Execute a skill that results in digitalizing the player character.
Parameters
activated Pointer to the activated ability instance
ctx Special execution state for the skill
client Pointer to the client connection that activated the skill, this will always fail if it is null
Definition at line 10576 of file SkillManager.cpp.
References channel::ClientState::GetCharacterState(), libcomp::PersistentObject::GetObjectByUUID(), channel::CharacterManager::IsMitamaDemon(), mServer, ProcessSkillResult(), SendFailure(), SpecialSkill(), and channel::state().
Referenced by SkillManager().
bool SkillManager::DigitalizeBreak (const std::shared_ptr< objects::ActivatedAbility > & activated, const std::shared_ptr< SkillExecutionContext > & ctx, const std::shared_ptr< ChannelClientConnection > & client) private
Execute a skill that forces the cancellation of all targets hit.
Parameters
activated Pointer to the activated ability instance
ctx Special execution state for the skill
client Pointer to the client connection that activated the skill, this will always fail if it is null
Definition at line 10701 of file SkillManager.cpp.
References channel::SkillTargetResult::EntityState, GetProcessingSkill(), channel::SkillTargetResult::HitAbsorb, channel::SkillTargetResult::HitAvoided, and mServer.
Referenced by SkillManager().
bool SkillManager::DigitalizeCancel (const std::shared_ptr< objects::ActivatedAbility > & activated, const std::shared_ptr< SkillExecutionContext > & ctx, const std::shared_ptr< ChannelClientConnection > & client) private
Execute a digitalize state cancellation skill.
Parameters
activated Pointer to the activated ability instance
ctx Special execution state for the skill
client Pointer to the client connection that activated the skill, this will always fail if it is null
Definition at line 10730 of file SkillManager.cpp.
References libcomp::String::Arg(), channel::ClientState::GetAccountUID(), channel::ClientState::GetCharacterState(), mServer, ProcessSkillResult(), SendFailure(), SpecialSkill(), and channel::state().
Referenced by SkillManager().
bool SkillManager::DirectStatus (const std::shared_ptr< objects::ActivatedAbility > & activated, const std::shared_ptr< SkillExecutionContext > & ctx, const std::shared_ptr< ChannelClientConnection > & client) private
Execute a skill that always adds a specific status effect after the skill's execution.
Parameters
activated Pointer to the activated ability instance
ctx Special execution state for the skill
client Pointer to the client connection that activated the skill, this will always fail if it is null
Definition at line 10768 of file SkillManager.cpp.
References channel::SkillTargetResult::EntityState, GetProcessingSkill(), mServer, and SVR_CONST.
Referenced by SkillManager().
bool SkillManager::EquipItem (const std::shared_ptr< objects::ActivatedAbility > & activated, const std::shared_ptr< SkillExecutionContext > & ctx, const std::shared_ptr< ChannelClientConnection > & client) private
Execute the "equip item" skill.
Parameters
activated Pointer to the activated ability instance
ctx Special execution state for the skill
client Pointer to the client connection that activated the skill, this will always fail if it is null
Definition at line 10834 of file SkillManager.cpp.
References FinalizeSkill(), mServer, ProcessSkillResult(), SendFailure(), and SpecialSkill().
Referenced by SkillManager().
bool SkillManager::Estoma (const std::shared_ptr< objects::ActivatedAbility > & activated, const std::shared_ptr< SkillExecutionContext > & ctx, const std::shared_ptr< ChannelClientConnection > & client) private
Execute the aggro clearing "Estoma" skill.
Parameters
activated Pointer to the activated ability instance
ctx Special execution state for the skill
client Pointer to the client connection that activated the skill, this will always fail if it is null
Definition at line 10876 of file SkillManager.cpp.
References CancelSkill(), channel::SkillTargetResult::EntityState, GetProcessingSkill(), mServer, and STATUS_RESTING.
Referenced by SkillManager().
int8_t SkillManager::EvaluateTokuseiSkillCondition (const std::shared_ptr< ActiveEntityState > & eState, const std::shared_ptr< objects::TokuseiSkillCondition > & condition, const std::shared_ptr< channel::ProcessingSkill > & pSkill, const std::shared_ptr< ActiveEntityState > & otherState) private
Evaluate a TokuseiSkillCondition relative to the current skill and supplied entities.
Parameters
eState Pointer to the entity the effect applies to
condition Pointer to the condition definition
pSkill Pointer to the current skill processing state
otherState Pointer to the source entity if a target is being calculated or the target in question if the source is being calculated. If the skill is still being checked validity, supplying no entity for this while calculating against the source is valid.
Returns
0 if the conditions evaluated to true, 1 if the conditions evaluated to false, -1 if the conditions cannot be evaluated yet
Definition at line 5183 of file SkillManager.cpp.
References channel::ProcessingSkill::BaseAffinity, channel::ProcessingSkill::Definition, channel::ProcessingSkill::EffectiveAffinity, channel::ProcessingSkill::EffectiveDependencyType, channel::ProcessingSkill::ExpertiseType, channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), channel::ClientState::GetEntityClientState(), channel::NONE, channel::ActiveEntityState::SameFaction(), channel::ProcessingSkill::SkillID, and channel::state().
Referenced by EvaluateTokuseiSkillConditions().
int8_t SkillManager::EvaluateTokuseiSkillConditions (const std::shared_ptr< ActiveEntityState > & eState, const std::list< std::shared_ptr< objects::TokuseiSkillCondition >> & conditions, const std::shared_ptr< channel::ProcessingSkill > & pSkill, const std::shared_ptr< ActiveEntityState > & otherState) private
Evaluate TokuseiSkillConditions relative to the current skill and supplied entities.
Parameters
eState Pointer to the entity the effect applies to
conditions List of points to the condition definitions
pSkill Pointer to the current skill processing state
otherState Pointer to the source entity if a target is being calculated or the target in question if the source is being calculated. If the skill is still being checked validity, supplying no entity for this while calculating against the source is valid.
Returns
0 if the conditions evaluated to true, 1 if the conditions evaluated to false, -1 if the conditions cannot be evaluated yet
Definition at line 5125 of file SkillManager.cpp.
References EvaluateTokuseiSkillCondition().
Referenced by GetCalculatedState().
bool SkillManager::ExecuteNormalSkill (const std::shared_ptr< ChannelClientConnection > client, std::shared_ptr< objects::ActivatedAbility > activated, const std::shared_ptr< SkillExecutionContext > & ctx) private
Execute a normal skill, not handled by a special handler.
Parameters
client Pointer to the client connection that activated the skill
activated Pointer to the activated ability instance
ctx Special execution state for the skill
Definition at line 2817 of file SkillManager.cpp.
References BeginSkillExecution(), GetProcessingSkill(), channel::ChannelServer::GetServerTime(), channel::ActiveEntityState::GetZone(), IFramesEnabled(), channel::NONE, SendFailure(), and STATUS_KNOCKBACK.
Referenced by ExecuteSkill().
bool SkillManager::ExecuteSkill (const std::shared_ptr< ActiveEntityState > source, int8_t activationID, int64_t targetObjectID, std::shared_ptr< SkillExecutionContext > ctx = 0)
Execute the skill of an active entity.
Parameters
source Pointer of the entity that is executing the skill
activationID ID of the activated ability instance
targetObjectID ID of the object being targeted by the skill
ctx Special execution state for the skill (ex: free cast, counter)
Returns
true if the skill was executed successfully, false otherwise
Definition at line 660 of file SkillManager.cpp.
References GetActivation(), channel::ChannelServer::GetServerTime(), mServer, SendFailure(), STATUS_KNOCKBACK, and STATUS_LOCKOUT.
Referenced by ActivateSkill(), HandleCounter(), HandleDodge(), and HandleGuard().
bool SkillManager::ExecuteSkill (std::shared_ptr< ActiveEntityState > source, std::shared_ptr< objects::ActivatedAbility > activated, const std::shared_ptr< ChannelClientConnection > client, std::shared_ptr< SkillExecutionContext > ctx, bool delayedAuto = false) private
Pay any costs related to and execute the skill of a character or demon.
Parameters
source Pointer to the state of the source entity
activated Pointer to the activated ability instance
client Pointer to the client connection, can be null if not coming from a player entity
ctx Special execution state for the skill
delayedAuto If true, the skill is being executed as the result of delayed auto-exection from an activation request
Returns
true if the skill was executed successfully, false otherwise
Definition at line 703 of file SkillManager.cpp.
References libcomp::String::Arg(), DetermineCosts(), ExecuteNormalSkill(), FinalizeSkill(), FinalizeSkillExecution(), channel::ClientState::GetAccountUID(), GetCalculatedState(), GetProcessingSkill(), channel::ChannelServer::GetServerTime(), mServer, mSkillFunctions, channel::NONE, SendCompleteSkill(), SendFailure(), SkillRestricted(), channel::state(), SVR_CONST, ToggleSwitchSkill(), and ValidateSkillTarget().
bool SkillManager::FamiliarityUp (const std::shared_ptr< objects::ActivatedAbility > & activated, const std::shared_ptr< SkillExecutionContext > & ctx, const std::shared_ptr< ChannelClientConnection > & client) private
Execute a familiarity boosting skill.
Parameters
activated Pointer to the activated ability instance
ctx Special execution state for the skill
client Pointer to the client connection that activated the skill, this will always fail if it is null
Definition at line 10935 of file SkillManager.cpp.
References CalculateStatusEffectStack(), channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), GiveDemonPresent(), mServer, ProcessSkillResult(), SendFailure(), SpecialSkill(), and channel::state().
Referenced by SkillManager().
bool SkillManager::FamiliarityUpItem (const std::shared_ptr< objects::ActivatedAbility > & activated, const std::shared_ptr< SkillExecutionContext > & ctx, const std::shared_ptr< ChannelClientConnection > & client) private
Execute a familiarity boosting skill from an item.
These work slightly different from the standard skill ones as they can adjust a delta percent instead of a fixed value.
Parameters
activated Pointer to the activated ability instance
ctx Special execution state for the skill
client Pointer to the client connection that activated the skill, this will always fail if it is null
Definition at line 11059 of file SkillManager.cpp.
References channel::ClientState::GetDemonState(), mServer, ProcessSkillResult(), SendFailure(), SpecialSkill(), and channel::state().
Referenced by SkillManager().
std::shared_ptr< objects::ActivatedAbility > SkillManager::FinalizeSkill (const std::shared_ptr< SkillExecutionContext > & ctx, std::shared_ptr< objects::ActivatedAbility > activated) private
Finalize a skill that has been activated and remove it from the entity if it does not have additional uses.
If the skill's execution results in additional uses remaining, make a copy of the instance to preserve execution values.
Parameters
ctx Special execution state for the skill
activated Pointer to the activated ability instance
Returns
Pointer to the ability instance being executed
Definition at line 10074 of file SkillManager.cpp.
References GetProcessingSkill(), channel::ActiveEntityState::GetZone(), SendCompleteSkill(), and SVR_CONST.
Referenced by CompleteSkillExecution(), EquipItem(), ExecuteSkill(), Fizzle(), ProcessSkillResultFinal(), and ToggleSwitchSkill().
void SkillManager::FinalizeSkillExecution (const std::shared_ptr< ChannelClientConnection > client, const std::shared_ptr< SkillExecutionContext > & ctx, std::shared_ptr< objects::ActivatedAbility > activated) private
Execute post execution steps like notifying the client that the skill has executed and updating any related expertises.
Parameters
client Pointer to the client connection that activated the skill
ctx Special execution state for the skill
activated Pointer to the activated ability instance
Definition at line 9871 of file SkillManager.cpp.
References EFFECT_CANCEL_SKILL, GetCalculatedState(), channel::ClientState::GetCharacterState(), channel::Point::GetDistance(), channel::ClientState::GetObjectID(), GetProcessingSkill(), GetSelfTarget(), channel::ChannelServer::GetServerTime(), channel::ActiveEntityState::GetZone(), mServer, SendExecuteSkill(), SetSkillCompleteState(), channel::state(), STATUS_LOCKOUT, SVR_CONST, channel::Point::x, and channel::Point::y.
Referenced by BeginSkillExecution(), ExecuteSkill(), Fizzle(), ProcessSkillResultFinal(), and ToggleSwitchSkill().
void SkillManager::Fizzle (const std::shared_ptr< SkillExecutionContext > & ctx) private
Fizzle a skill that has already started processing and perform any necessary cleanup steps.
Parameters
ctx Special execution state for the skill
Definition at line 12625 of file SkillManager.cpp.
References libcomp::String::Arg(), FinalizeSkill(), FinalizeSkillExecution(), and mServer.
Referenced by CompleteSkillExecution(), and ProcessSkillResult().
bool SkillManager::ForgetAllExpertiseSkills (const std::shared_ptr< objects::ActivatedAbility > & activated, const std::shared_ptr< SkillExecutionContext > & ctx, const std::shared_ptr< ChannelClientConnection > & client) private
Execute a skill that causes all character expertise skills to be forgotten.
Parameters
activated Pointer to the activated ability instance
ctx Special execution state for the skill
client Pointer to the client connection that activated the skill, this will always fail if it is null
Definition at line 11139 of file SkillManager.cpp.
References channel::ClientState::GetAccountUID(), channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), mServer, ProcessSkillResult(), SendFailure(), SpecialSkill(), and channel::state().
Referenced by SkillManager().
bool SkillManager::FunctionIDMapped (uint16_t functionID)
Check if the supplied function ID is mapped to a special function within the skill manager.
Skill function IDs that are not mapped will react like no function ID skills when processed.
Parameters
functionID Function ID to check
Returns
true if it is mapped, false if it is not
Definition at line 2811 of file SkillManager.cpp.
References mSkillEffectFunctions, and mSkillFunctions.
std::shared_ptr< objects::ActivatedAbility > SkillManager::GetActivation (const std::shared_ptr< ActiveEntityState > source, int8_t activationID) const private
Get the current or past special skill activation by ID.
Parameters
source Pointer to the skill source entity
activationID ID of the activation to retrieve
Returns
Pointer to the matching skill activation, null if it does not exist
Definition at line 2333 of file SkillManager.cpp.
References libcomp::String::Arg().
Referenced by CancelSkill(), and ExecuteSkill().
float SkillManager::GetAffinityBoost (const std::shared_ptr< ActiveEntityState > eState, std::shared_ptr< objects::CalculatedEntityState > calcState, CorrectTbl boostType) private
Get the specific affinity boost associated to the supplied entity.
Max affinity cap is applied to the value.
Parameters
eState Pointer to the entity
calcState Pointer to entity's calculated state
boostType CorrectTbl index of the boost type
Returns
Calculated boost level as a decimal
Definition at line 9193 of file SkillManager.cpp.
References mServer.
Referenced by CalculateDamage_Normal(), and HandleStatusEffects().
std::shared_ptr< objects::CalculatedEntityState > SkillManager::GetCalculatedState (const std::shared_ptr< ActiveEntityState > & eState, const std::shared_ptr< channel::ProcessingSkill > & pSkill, bool isTarget, const std::shared_ptr< ActiveEntityState > & otherState) private
Get a CalculatedEntityState based upon the skill being executed and the state of the entity as either the source or a target of the skill.
Parameters
eState Pointer to the entity to get a CalculatedEntityState for
pSkill Pointer to the current skill processing state
isTarget false if the entity is the source of the skill, false if the entity is a target
otherState Pointer to the source entity if a target is being calculated or the target in question if the source is being calculated. If the skill is still being checked validity, supplying no entity for this while calculating against the source is valid.
Returns
Pointer to the CalculatedEntityState to use relative to the supplied parameters. If the effects calculated for the entity do not differ from one already on the entity or used as the source execution context, the same one will be returned.
Definition at line 4966 of file SkillManager.cpp.
References channel::ProcessingSkill::Definition, EvaluateTokuseiSkillConditions(), mServer, channel::ProcessingSkill::SourceCalcStates, channel::ProcessingSkill::SourceExecutionState, and channel::ProcessingSkill::TargetCalcStates.
Referenced by ActivateSkill(), ApplyNegotiationDamage(), ApplyPrimaryCounter(), BeginSkillExecution(), CalculateDamage(), CalculateDamage_Normal(), CalculateOffenseValue(), ExecuteSkill(), FinalizeSkillExecution(), GetCritLevel(), GetProcessingSkill(), GetSummonSpeed(), HandleSkillInterrupt(), HandleStatusEffects(), ProcessSkillResult(), ProcessSkillResultFinal(), and SetSkillCompleteState().
uint8_t SkillManager::GetCritLevel (const std::shared_ptr< ActiveEntityState > & source, SkillTargetResult & target, const std::shared_ptr< channel::ProcessingSkill > & pSkill) private
Get the critical level of a skill that is being calculated for damage and has already been determined as a hit.
This should not be called if the skill fundamentally will never crit such as if it is a healing skill.
Parameters
source Pointer to the entity that activated the skill
target Pointer to the entity that will receive damage
pSkill Pointer to the current skill processing state
Returns
0 for no crit, 1 for normal crit, 2 for limit break
Definition at line 9104 of file SkillManager.cpp.
References channel::SkillTargetResult::EntityState, GetCalculatedState(), channel::SkillTargetResult::GuardModifier, and RNG.
Referenced by CalculateDamage().
int16_t SkillManager::GetEntityRate (const std::shared_ptr< ActiveEntityState > eState, std::shared_ptr< objects::CalculatedEntityState > calcState, bool taken) private
Get the entity rate scaling correct table value associated to the the supplied entity from the other entity's calculated state.
Parameters
eState Pointer to the entity in question
calcState Pointer to the other entity's calculated state
taken true if the damage taken rate should be retrieved, false if the damage dealt rate should be retrieved
Returns
Correct table value for the rate scaling
Definition at line 9178 of file SkillManager.cpp.
Referenced by CalculateDamage(), and CalculateDamage_Normal().
std::unordered_map< uint8_t, std::list< std::shared_ptr< objects::ItemDrop > > > SkillManager::GetItemDrops (const std::shared_ptr< ActiveEntityState > & source, const std::shared_ptr< ActiveEntityState > & eState, const std::shared_ptr< ChannelClientConnection > & client, const std::shared_ptr< Zone > & zone, bool giftMode = false) private
Gather drops for a specific enemy spawn from its own drops, global drops and demon family drops.
Parameters
source Pointer to the entity that activated the skill
eState Pointer to enemy which may or may not have spawn information (ex: GM created enemy)
client Pointer to the client connection related to the source, can be null for non-player entity sources
zone Pointer to the zone the entities belong to
giftMode true if the enemy's negotation gifts should be gathered instead of their normal drops
Returns
Map of drop set types to list of item drops from each different source
Definition at line 9707 of file SkillManager.cpp.
References mServer.
Referenced by HandleKills(), and HandleNegotiations().
std::pair< float, float > SkillManager::GetMovementSpeeds (const std::shared_ptr< ActiveEntityState > & source, const std::shared_ptr< objects::MiSkillData > & skillData) static
Get the charge and post charge movement speeds for a skill for the supplied entity's current state.
Parameters
source Pointer to the state of the source entity
skillData Pointer to the skill's definition
Returns
Charge and post charage movement speeds
Definition at line 1662 of file SkillManager.cpp.
References SVR_CONST.
Referenced by ActivateSkill(), and channel::CharacterManager::AddRemoveOpponent().
uint8_t SkillManager::GetNRAResult (SkillTargetResult & target, ProcessingSkill & skill, uint8_t effectiveAffinity) private
Get the result of the skill target's null, reflect or absorb checks.
Parameters
target Target to determine NRA for
skill Current skill processing state
effectiveAffinity Target specific affinity type for the skill
resultAffinity Output parameter containing the NRA affinity type if it occurs
Returns
NRA index value or 0 for none
Definition at line 9610 of file SkillManager.cpp.
References channel::SkillTargetResult::NRAAffinity.
Referenced by CalculateDamage(), and SetNRA().
uint8_t SkillManager::GetNRAResult (SkillTargetResult & target, ProcessingSkill & skill, uint8_t effectiveAffinity, uint8_t & resultAffinity, bool effectiveOnly, bool reduceShields) private
Get the result of the skill target's null, reflect or absorb checks.
Parameters
target Target to determine NRA for
skill Current skill processing state
effectiveAffinity Target specific affinity type for the skill
resultAffinity Output parameter containing the NRA affinity type if it occurs
effectiveOnly If true, only the supplied affinity will be checked, otherwise the dependency type and base affinities will be checked as well
reduceShields If true, any NRA shields will be consumed should they apply first
Returns
NRA index value or 0 for none
Definition at line 9617 of file SkillManager.cpp.
References channel::ProcessingSkill::BaseAffinity, channel::SkillTargetResult::CalcState, channel::ProcessingSkill::CanNRA, channel::ProcessingSkill::EffectiveDependencyType, channel::SkillTargetResult::EntityState, channel::NONE, NRA_OFFSET, and RNG.
std::shared_ptr< ProcessingSkill > SkillManager::GetProcessingSkill (std::shared_ptr< objects::ActivatedAbility > activated, std::shared_ptr< SkillExecutionContext > ctx) private
Get a processing skill set with default values from the supplied ability and context.
If the context already has a processing skill set, it will be returned instead.
Parameters
activated Pointer to the activated ability instance
ctx Special execution state for the skill
Returns
Pointer to a processing skill contextual to the values supplied
Definition at line 4765 of file SkillManager.cpp.
References GetCalculatedState(), channel::ActiveEntityState::GetZone(), mServer, channel::NONE, RES_OFFSET, and SVR_CONST.
Referenced by ActivateSkill(), CancelSkill(), DetermineCosts(), DigitalizeBreak(), DirectStatus(), Estoma(), ExecuteNormalSkill(), ExecuteSkill(), FinalizeSkill(), FinalizeSkillExecution(), Liberama(), ProcessSkillResult(), RandomItem(), SendFailure(), Traesto(), and XPUp().
SkillTargetResult * SkillManager::GetSelfTarget (const std::shared_ptr< ActiveEntityState > & source, std::list< SkillTargetResult > & targets, bool indirectDefault, bool autoCreate = true) private
Get the skill target that hits the source entity or create it if it does not already exist.
Parameters
source Pointer to the entity that activated the skill
targets List target results associated to the skill
indirectOnly If true and the target does not already exist, it will be created as an indirect target
autoCreate If true and the target does not exist, create it
Returns
Pointer to the skill target representing the source entity
Definition at line 9495 of file SkillManager.cpp.
References channel::SkillTargetResult::EntityState, and channel::SkillTargetResult::IndirectTarget.
Referenced by CalculateDamage(), FinalizeSkillExecution(), and ProcessSkillResultFinal().
uint32_t SkillManager::GetSummonSpeed (const std::shared_ptr< channel::ProcessingSkill > & pSkill, const std::shared_ptr< ChannelClientConnection > & client) private
Determine the summon speed for the supplied client and the targeted demon in the COMP.
Parameters
pSkill Current skill processing state
client Pointer to the client connection
Returns
Summon charge time in milliseconds, 0 on error
Definition at line 12876 of file SkillManager.cpp.
References GetCalculatedState(), channel::ClientState::GetCharacterState(), libcomp::PersistentObject::GetObjectByUUID(), channel::ClientState::GetObjectUUID(), mServer, and channel::state().
Referenced by ActivateSkill().
void SkillManager::GiveDemonPresent (const std::shared_ptr< ChannelClientConnection > & client, uint32_t demonType, uint32_t itemType, int8_t rarity, uint32_t skillID) private
Give a demon present to the player character as the result of a familiarity adjusting skill.
Parameters
client Pointer to the client connection
demonType Partner demon type
itemType Present item type
rarity Rarity level of the present being given
skillID ID of the skill that caused the present to be given
Definition at line 12598 of file SkillManager.cpp.
References mServer, libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteU32Little().
Referenced by FamiliarityUp(), and Mooch().
bool SkillManager::HandleCounter (const std::shared_ptr< ActiveEntityState > & source, SkillTargetResult & target, const std::shared_ptr< channel::ProcessingSkill > & pSkill) private
Execute or cancel the counter skill currently being used by the supplied target from being hit by the source entity.
Countering skills activate manually from the source and are actually executed in the middle of the skill being countered. The countering skill will have its CounteredSkill property set on the context and the skill being countered will have the countering skill added to its CounteringSkills list, since technically multiple skills can counter one.
Parameters
source Pointer to the state of the source entity
target Skill targeted entity
pSkill Skill processing state of the skill being countered
Returns
true if the skill was countered, false if it was not
Definition at line 5687 of file SkillManager.cpp.
References libcomp::String::Arg(), CancelSkill(), channel::SkillTargetResult::EntityState, ExecuteSkill(), FLAG1_GUARDED, channel::SkillTargetResult::Flags1, and channel::SkillTargetResult::HitAvoided.
Referenced by ApplyPrimaryCounter().
void SkillManager::HandleDigitalizeXP (const std::shared_ptr< ActiveEntityState > source, const std::list< std::shared_ptr< ActiveEntityState >> & enemies, const std::shared_ptr< Zone > & zone) private
Increase digitalize experience points for the supplied source's party based upon defeated enemies.
Points are granted at a flat rate and unlike XP are not shared with other parties that dealt damage.
Parameters
enemies List of pointers to enemies that have been killed
zone Pointer ot the zone where the enemies were killed
Definition at line 7164 of file SkillManager.cpp.
References channel::ClientState::GetCharacterState(), channel::ClientState::GetZone(), mServer, and channel::state().
Referenced by HandleKills().
bool SkillManager::HandleDodge (const std::shared_ptr< ActiveEntityState > & source, SkillTargetResult & target, const std::shared_ptr< channel::ProcessingSkill > & pSkill) private
Execute or cancel the dodge skill currently being used by the supplied target from being hit by the source entity.
Parameters
source Pointer to the state of the source entity
target Skill targeted entity
pSkill Skill processing state of the skill being dodged
Returns
true if the skill was dodged, false if it was not
Definition at line 5748 of file SkillManager.cpp.
References libcomp::String::Arg(), CancelSkill(), channel::SkillTargetResult::Damage1Type, channel::SkillTargetResult::Damage2Type, DAMAGE_TYPE_MISS, channel::SkillTargetResult::EntityState, ExecuteSkill(), FLAG1_DODGED, channel::SkillTargetResult::Flags1, and channel::SkillTargetResult::HitAvoided.
Referenced by ApplyPrimaryCounter(), and ApplySecondaryCounter().
void SkillManager::HandleDurabilityDamage (const std::shared_ptr< ActiveEntityState > entity, const std::shared_ptr< channel::ProcessingSkill > & pSkill) private
Update item durability on the supplied entity if its entity is a character.
This should be called for all source entities and only targets that have not avoided the hit.
Parameters
entity Pointer to the entity to update
pSkill Pointer to the current skill processing state
Todo:
: close but not quite right
Todo:
: needs more research
Definition at line 8258 of file SkillManager.cpp.
References channel::ActiveEntityStateImp< T >::GetEntity(), mServer, and SVR_CONST.
Referenced by ProcessSkillResultFinal().
void SkillManager::HandleEncounterDefeat (const std::shared_ptr< ActiveEntityState > source, const std::shared_ptr< Zone > & zone, const std::unordered_map< uint32_t, uint32_t > & encounterGroups) private
Handle all logic related to defeating an enemy encounter through combat or talk skill outcome.
Enemy despawn does not count as a defeat and should be handled separately. If the encounter is not actually defeated, nothing will be done.
Parameters
source Pointer to the source of the skill
zone Pointer to the zone where the skill was executed
encounterGroups Map of encounter IDs to spawn group ID
Definition at line 7218 of file SkillManager.cpp.
References channel::ActionOptions::GroupID, mServer, and channel::ActionOptions::NoEventInterrupt.
Referenced by HandleKills(), and HandleNegotiations().
void SkillManager::HandleFusionGauge (const std::shared_ptr< channel::ProcessingSkill > & pSkill) private
If the skill is not a fusion skill and also an offensive action type, raise the fusion gauge.
Parameters
pSkill Pointer to the current skill processing state
Definition at line 8385 of file SkillManager.cpp.
References channel::SkillTargetResult::EntityState, channel::ActiveEntityStateImp< T >::GetLevel(), channel::SkillTargetResult::GuardModifier, channel::SkillTargetResult::HitAbsorb, channel::SkillTargetResult::HitAvoided, mServer, and SVR_CONST.
Referenced by ProcessSkillResultFinal().
bool SkillManager::HandleGuard (const std::shared_ptr< ActiveEntityState > & source, SkillTargetResult & target, const std::shared_ptr< channel::ProcessingSkill > & pSkill) private
Execute or cancel the guard skill currently being used by the supplied target from being hit by the source entity.
Parameters
source Pointer to the state of the source entity
target Skill targeted entity
pSkill Skill processing state of the skill being guarded
Returns
true if the skill was guarded against, false if it was not
Definition at line 5603 of file SkillManager.cpp.
References libcomp::String::Arg(), CancelSkill(), channel::SkillTargetResult::EntityState, ExecuteSkill(), FLAG1_GUARDED, channel::SkillTargetResult::Flags1, channel::SkillTargetResult::GuardModifier, channel::SkillTargetResult::HitAvoided, channel::SkillTargetResult::HitNull, and SVR_CONST.
Referenced by ApplyPrimaryCounter(), and ApplySecondaryCounter().
void SkillManager::HandleKills (const std::shared_ptr< ActiveEntityState > source, const std::shared_ptr< Zone > & zone, const std::set< std::shared_ptr< ActiveEntityState >> killed) private
Handle all logic related to kills that occurred from a skill's execution.
Parameters
source Pointer to the source of the skill
zone Pointer to the zone where the skill was executed
killed Set of entities killed by the skill's execution
Definition at line 6241 of file SkillManager.cpp.
References libcomp::String::Arg(), CancelSkill(), channel::ChannelClientConnection::FlushAllOutgoing(), channel::ActiveEntityStateImp< T >::GetEntity(), channel::ClientState::GetEntityClientState(), libcomp::Randomizer::GetEntry(), GetItemDrops(), channel::ChannelServer::GetServerTime(), channel::ClientState::GetZone(), HandleDigitalizeXP(), HandleEncounterDefeat(), HandleKillXP(), mServer, RNG, ScheduleFreeLoot(), and channel::state().
Referenced by ProcessSkillResultFinal().
void SkillManager::HandleKillXP (const std::shared_ptr< objects::Enemy > & enemy, const std::shared_ptr< Zone > & zone) private
Distribute all XP from a defeated enemy to each player that caused damage to it, adjusting for active party members and players still in the zone.
Parameters
enemy Pointer to the enemy that was killed
zone Pointer ot the zone where the enemy was killed
Definition at line 6987 of file SkillManager.cpp.
References mServer.
Referenced by HandleKills().
void SkillManager::HandleNegotiations (const std::shared_ptr< ActiveEntityState > source, const std::shared_ptr< Zone > & zone, const std::list< std::pair< std::shared_ptr< ActiveEntityState >, uint8_t >> talkDone) private
Handle the outcome of a negotation ending from a skill's execution including things like creating demon eggs and gift boxes or running away.
Parameters
source Pointer to the source of the skill
zone Pointer to the zone where the skill was executed
talkDone List of entities that have finished negotiation with the skill source and their respective outcomes related to respons flags
Definition at line 7906 of file SkillManager.cpp.
References channel::ChannelClientConnection::FlushAllOutgoing(), channel::ActiveEntityStateImp< T >::GetEntity(), GetItemDrops(), channel::ChannelServer::GetServerTime(), HandleEncounterDefeat(), mServer, ScheduleFreeLoot(), TALK_GIVE_ITEM, TALK_GIVE_ITEM_2, TALK_JOIN, TALK_JOIN_2, TALK_LEAVE, and TALK_REJECT.
Referenced by ProcessSkillResultFinal().
void SkillManager::HandleRevives (const std::shared_ptr< Zone > & zone, const std::set< std::shared_ptr< ActiveEntityState >> revived, const std::shared_ptr< channel::ProcessingSkill > & pSkill) private
Handle all logic related to revivals that occurred from a skill's execution.
Parameters
zone Pointer to the zone where the skill was executed
revived Set of entities revived by the skill's execution
pSkill Skill processing state of the skill being executed
Definition at line 7266 of file SkillManager.cpp.
References libcomp::String::Arg(), channel::ClientState::GetEntityClientState(), mServer, and SVR_CONST.
Referenced by ProcessSkillResultFinal().
bool SkillManager::HandleSkillInterrupt (const std::shared_ptr< ActiveEntityState > & source, SkillTargetResult & target, const std::shared_ptr< channel::ProcessingSkill > & pSkill) private
Apply target skill interrupt based upon timing and state of the target entity's skill being charged or executed.
Parameters
source Pointer to the state of the source entity
target Skill targeted entity
pSkill Skill processing state of the skill being guarded
Returns
true if the target had a skill that was interrupted, false if they did not
Definition at line 5807 of file SkillManager.cpp.
References CancelSkill(), channel::SkillTargetResult::CanHitstun, EFFECT_CANCEL_DAMAGE, EFFECT_CANCEL_KNOCKBACK, channel::SkillTargetResult::EffectCancellations, channel::SkillTargetResult::EntityState, GetCalculatedState(), and mServer.
Referenced by ProcessSkillResultFinal().
void SkillManager::HandleSkillLearning (const std::shared_ptr< ActiveEntityState > entity, const std::shared_ptr< channel::ProcessingSkill > & pSkill) private
Update InheritedSkills on the supplied entity if its entity type is partner demon.
This should be called once for each entity touched by the processing skill, regardless of if anything happened to it.
Parameters
entity Pointer to the entity to update
pSkill Pointer to the current skill processing state
Definition at line 8162 of file SkillManager.cpp.
References libcomp::DatabaseChangeSet::Create(), channel::DemonState::GetLearningSkills(), mServer, libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteU32Little().
Referenced by ProcessSkillResultFinal().
std::set< uint32_t > SkillManager::HandleStatusEffects (const std::shared_ptr< ActiveEntityState > & source, SkillTargetResult & target, const std::shared_ptr< channel::ProcessingSkill > & pSkill) private
Handle all status effect application logic for a specific target.
Parameters
source Pointer to the state of the source entity
target Skill targeted entity
pSkill Skill processing state of the skill being executed
Returns
Set of status effects being applied that will be cancelled if the entity is killed as a result of the skill
Definition at line 5918 of file SkillManager.cpp.
References channel::SkillTargetResult::AddedStatuses, AIL_OFFSET, channel::SkillTargetResult::AilmentDamage, channel::SkillTargetResult::AilmentDamageTime, channel::SkillTargetResult::AilmentDamageType, BOOST_OFFSET, CalculateStatusEffectStack(), EFFECT_CANCEL_DEATH, channel::SkillTargetResult::EntityState, FLAG1_KNOCKBACK, channel::SkillTargetResult::Flags1, GetAffinityBoost(), GetCalculatedState(), libcomp::Randomizer::GetEntry(), mServer, NRA_OFFSET, RES_OFFSET, RNG, and SVR_CONST.
Referenced by ProcessSkillResultFinal().
bool SkillManager::IFramesEnabled () private
Determine if invincibility frames are enabled for the server to adjust skill timing.
Returns
true if I-frames are enabled, false if they are not
Definition at line 12941 of file SkillManager.cpp.
References mServer.
Referenced by ExecuteNormalSkill().
void SkillManager::InterruptEvents (const std::set< int32_t > & worldCIDs) private
Interrupt any active events associated to the supplied world CIDs as a result of being hit by a combat skill.
Parameters
worldCIDs List of player world CIDs
Definition at line 8442 of file SkillManager.cpp.
References mServer.
Referenced by ProcessSkillResultFinal().
bool SkillManager::IsTalkSkill (const std::shared_ptr< objects::MiSkillData > & skillData, bool primaryOnly) private
Determine if the supplied skill data will involve talk results either from a negotiation skill or a skill with negotiation damage.
Parameters
skillData Pointer to the skill's definition
primaryOnly If true, only skills that have a negotiation action type will return true. If false, skills that cause negotiation damage will also return true.
Returns
true if the skill is will involve talk results
Definition at line 12915 of file SkillManager.cpp.
Referenced by ApplyNegotiationDamage(), ProcessSkillResultFinal(), SkillRestricted(), and ValidateSkillTarget().
bool SkillManager::Liberama (const std::shared_ptr< objects::ActivatedAbility > & activated, const std::shared_ptr< SkillExecutionContext > & ctx, const std::shared_ptr< ChannelClientConnection > & client) private
Execute the aggro drawing "liberama" skill.
Parameters
activated Pointer to the activated ability instance
ctx Special execution state for the skill
client Pointer to the client connection that activated the skill, this will always fail if it is null
Definition at line 11216 of file SkillManager.cpp.
References channel::SkillTargetResult::EntityState, GetProcessingSkill(), and mServer.
Referenced by SkillManager().
bool SkillManager::MinionDespawn (const std::shared_ptr< objects::ActivatedAbility > & activated, const std::shared_ptr< SkillExecutionContext > & ctx, const std::shared_ptr< ChannelClientConnection > & client) private
Execute a minion despawning skill.
Parameters
activated Pointer to the activated ability instance
ctx Special execution state for the skill
client Pointer to the client connection that activated the skill, this will always fail if it is null
Definition at line 11243 of file SkillManager.cpp.
References ProcessSkillResult(), SendFailure(), and SpecialSkill().
Referenced by SkillManager().
bool SkillManager::MinionSpawn (const std::shared_ptr< objects::ActivatedAbility > & activated, const std::shared_ptr< SkillExecutionContext > & ctx, const std::shared_ptr< ChannelClientConnection > & client) private
Execute a minion spawning skill.
Parameters
activated Pointer to the activated ability instance
ctx Special execution state for the skill
client Pointer to the client connection that activated the skill, this will always fail if it is null
Definition at line 11288 of file SkillManager.cpp.
References libcomp::String::Arg(), libcomp::Randomizer::GetEntry(), channel::ActionOptions::GroupID, mServer, ProcessSkillResult(), SendFailure(), and SpecialSkill().
Referenced by SkillManager().
bool SkillManager::Mooch (const std::shared_ptr< objects::ActivatedAbility > & activated, const std::shared_ptr< SkillExecutionContext > & ctx, const std::shared_ptr< ChannelClientConnection > & client) private
Execute the "Mooch" skill.
Parameters
activated Pointer to the activated ability instance
ctx Special execution state for the skill
client Pointer to the client connection that activated the skill, this will always fail if it is null
Definition at line 11425 of file SkillManager.cpp.
References CalculateStatusEffectStack(), channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), GiveDemonPresent(), mServer, ProcessSkillResult(), SendFailure(), SpecialSkill(), and channel::state().
Referenced by SkillManager().
bool SkillManager::Mount (const std::shared_ptr< objects::ActivatedAbility > & activated, const std::shared_ptr< SkillExecutionContext > & ctx, const std::shared_ptr< ChannelClientConnection > & client) private
Execute a demon riding skill.
Parameters
activated Pointer to the activated ability instance
ctx Special execution state for the skill
client Pointer to the client connection that activated the skill, this will always fail if it is null
Definition at line 11540 of file SkillManager.cpp.
References channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), channel::ChannelServer::GetServerTime(), mServer, ProcessSkillResult(), SendFailure(), SpecialSkill(), channel::state(), and SVR_CONST.
Referenced by SkillManager().
bool SkillManager::PrepareFusionSkill (const std::shared_ptr< ChannelClientConnection > client, uint32_t & skillID, int32_t targetEntityID, int64_t mainDemonID, int64_t compDemonID)
Check fusion skill usage pre-skill validation and determine which one should be used.
Fusion skills are decided based upon the two demons involved, defaulting to the COMP demon if no special skill exists.
Parameters
client Pointer to the client connection belonging to the player activating the skill. Since non-player entities cannot use fusion skills, this is required unlike most other skill related processes.
skillID Current skill being used to execute the fusion skill which doubles as an output parameter for the context specific skill
targetEntityID ID of the entity being targeted when the skill is activated. Targeted fusion skills require a target is selected before charging starts.
mainDemonID Object ID of the demon that is currently summoned
compDemonID Object ID of the demon that is in the COMP
Returns
false if the fusion skill cannot be used for any reason
Definition at line 1707 of file SkillManager.cpp.
References channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), libcomp::PersistentObject::GetObjectByUUID(), channel::ClientState::GetObjectUUID(), channel::ChannelServer::GetServerTime(), channel::ClientState::GetZone(), mServer, channel::NONE, SendFailure(), channel::state(), SVR_CONST, and TargetInRange().
bool SkillManager::ProcessSkillResult (std::shared_ptr< objects::ActivatedAbility > activated, std::shared_ptr< SkillExecutionContext > ctx) private
Process the results of a skill.
If the skill involves a projectile this will be scheduled to execute after skill execution, otherwise it will execute immediately.
Parameters
activated Pointer to the activated ability instance
ctx Special execution state for the skill
Returns
true if the skill processed successfully, false otherwise
Definition at line 2884 of file SkillManager.cpp.
References channel::ProcessingSkill::Absorbed, ApplyPrimaryCounter(), ApplySecondaryCounter(), libcomp::String::Arg(), channel::SkillTargetResult::CalcState, channel::ActiveEntityState::CorrectRotation(), channel::ProcessingSkill::Definition, channel::ProcessingSkill::EffectiveSource, channel::SkillTargetResult::EntityState, Fizzle(), GetCalculatedState(), channel::ClientState::GetDemonState(), channel::ZoneManager::GetEntitiesInFoV(), channel::ClientState::GetEntityClientState(), channel::ClientState::GetPartyID(), GetProcessingSkill(), channel::ChannelServer::GetServerTime(), channel::SkillTargetResult::HitAbsorb, channel::SkillTargetResult::HitNull, channel::SkillTargetResult::HitReflect, mServer, channel::NONE, NRA_OFFSET, channel::SkillTargetResult::NRAAffinity, channel::ProcessingSkill::Nulled, channel::ZoneManager::PointInPolygon(), channel::ProcessingSkill::PrimaryTarget, SetNRA(), channel::state(), SVR_CONST, and channel::ProcessingSkill::Targets.
Referenced by Cameo(), Cloak(), CompleteSkillExecution(), DCM(), Despawn(), Desummon(), Digitalize(), DigitalizeCancel(), EquipItem(), FamiliarityUp(), FamiliarityUpItem(), ForgetAllExpertiseSkills(), MinionDespawn(), MinionSpawn(), Mooch(), Mount(), ProjectileHit(), RandomItem(), Randomize(), Respec(), Spawn(), SpawnZone(), StoreDemon(), SummonDemon(), Traesto(), and XPUp().
void SkillManager::ProcessSkillResultFinal (const std::shared_ptr< channel::ProcessingSkill > & pSkill, std::shared_ptr< SkillExecutionContext > ctx) private
Finalize skill processing and send the skill effect reports.
Parameters
pSkill Current skill processing state
ctx Special execution state for the skill
Todo:
: technically this has more spread than 0
Definition at line 3525 of file SkillManager.cpp.
References channel::ProcessingSkill::Absorbed, channel::ProcessingSkill::Activated, channel::SkillTargetResult::AddedStatuses, channel::SkillTargetResult::AilmentDamage, channel::SkillTargetResult::AilmentDamageTime, channel::SkillTargetResult::AilmentDamageType, ApplyNegotiationDamage(), channel::SkillExecutionContext::ApplyStatusEffects, ApplyZoneSpecificEffects(), libcomp::String::Arg(), channel::ChannelClientConnection::BroadcastPacket(), CalculateDamage(), channel::SkillTargetResult::CancelledStatuses, channel::SkillTargetResult::CanHitstun, channel::SkillTargetResult::CanKnockback, channel::SkillTargetResult::ClenchOverflow, channel::ProcessingSkill::CurrentZone, channel::SkillTargetResult::Damage1, channel::SkillTargetResult::Damage1Type, channel::SkillTargetResult::Damage2, channel::SkillTargetResult::Damage2Type, DAMAGE_EXPLICIT_SET, DAMAGE_TYPE_DRAIN, DAMAGE_TYPE_GENERIC, DAMAGE_TYPE_HEALING, DAMAGE_TYPE_MISS, DAMAGE_TYPE_NONE, channel::ProcessingSkill::Definition, EFFECT_CANCEL_DAMAGE, EFFECT_CANCEL_DEATH, EFFECT_CANCEL_HIT, EFFECT_CANCEL_KNOCKBACK, channel::SkillTargetResult::EffectCancellations, channel::ProcessingSkill::EffectiveSource, channel::SkillTargetResult::EntityState, channel::ProcessingSkill::ExecutionContext, FinalizeSkill(), FinalizeSkillExecution(), FLAG1_ABSORB, FLAG1_BLOCK_MAGIC, FLAG1_BLOCK_PHYS, FLAG1_CLENCH, FLAG1_GUARDED, FLAG1_KNOCKBACK, FLAG1_LETHAL, FLAG1_REFLECT_MAGIC, FLAG1_REFLECT_PHYS, FLAG1_REVIVAL, FLAG1_RUSH_MOVEMENT, FLAG2_BARRIER, FLAG2_CLENCH, FLAG2_INSTANT_DEATH, channel::SkillTargetResult::Flags1, channel::SkillTargetResult::Flags2, channel::ProcessingSkill::FunctionID, GetCalculatedState(), channel::ActiveEntityStateImp< T >::GetEntity(), channel::ClientState::GetEntityClientState(), GetSelfTarget(), channel::ChannelServer::GetServerTime(), channel::CharacterManager::GetTDamagePacket(), channel::ClientState::GetWorldCID(), channel::SkillTargetResult::GuardModifier, HandleDurabilityDamage(), HandleFusionGauge(), HandleKills(), HandleNegotiations(), HandleRevives(), HandleSkillInterrupt(), HandleSkillLearning(), HandleStatusEffects(), channel::ProcessingSkill::HardStrike, channel::SkillTargetResult::HitAbsorb, channel::SkillTargetResult::HitAvoided, channel::SkillTargetResult::HitNull, channel::SkillTargetResult::HitReflect, channel::SkillTargetResult::IndirectTarget, channel::ProcessingSkill::InPvP, InterruptEvents(), IsTalkSkill(), mServer, channel::NONE, channel::ProcessingSkill::Nulled, channel::ProcessingSkill::PrimaryTarget, channel::SkillTargetResult::PrimaryTarget, channel::SkillTargetResult::PursuitDamage, channel::SkillTargetResult::RecalcTriggers, channel::ProcessingSkill::Reflected, RNG, SendExecuteSkill(), channel::ChannelClientConnection::SendRelativeTimePacket(), libcomp::Packet::Size(), channel::ProcessingSkill::SkillID, channel::state(), STATUS_HIT_STUN, STATUS_IGNORE, STATUS_IMMOBILE, STATUS_KNOCKBACK, SVR_CONST, channel::SkillTargetResult::TalkFlags, channel::ProcessingSkill::Targets, channel::SkillTargetResult::TechnicalDamage, libcomp::Packet::WriteBlank(), libcomp::Packet::WriteFloat(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS8(), libcomp::Packet::WriteU16Little(), libcomp::Packet::WriteU32Little(), libcomp::Packet::WriteU8(), channel::Point::x, and channel::Point::y.
void SkillManager::ProjectileHit (std::shared_ptr< ProcessingSkill > pSkill, std::shared_ptr< SkillExecutionContext > ctx)
Complete executing a skill with a projectile, simulating the effect of the projectile having just hit.
Parameters
pSkill Current skill processing state
ctx Special execution state for the skill
Definition at line 2288 of file SkillManager.cpp.
References ApplyPrimaryCounter(), and ProcessSkillResult().
bool SkillManager::RandomItem (const std::shared_ptr< objects::ActivatedAbility > & activated, const std::shared_ptr< SkillExecutionContext > & ctx, const std::shared_ptr< ChannelClientConnection > & client) private
Execute a random item granting skill.
Parameters
activated Pointer to the activated ability instance
ctx Special execution state for the skill
client Pointer to the client connection that activated the skill, this will always fail if it is null
Definition at line 11726 of file SkillManager.cpp.
References channel::ClientState::GetCharacterState(), libcomp::Randomizer::GetEntry(), GetProcessingSkill(), mServer, ProcessSkillResult(), RNG, SendFailure(), SpecialSkill(), channel::state(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS8(), libcomp::Packet::WriteU16Little(), and libcomp::Packet::WriteU32Little().
Referenced by SkillManager().
bool SkillManager::Randomize (const std::shared_ptr< objects::ActivatedAbility > & activated, const std::shared_ptr< SkillExecutionContext > & ctx, const std::shared_ptr< ChannelClientConnection > & client) private
Execute a skill that is requesting a random number.
Parameters
activated Pointer to the activated ability instance
ctx Special execution state for the skill
client Pointer to the client connection that activated the skill, this will always fail if it is null
Definition at line 11815 of file SkillManager.cpp.
References mServer, ProcessSkillResult(), RNG, SpecialSkill(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS8(), and libcomp::Packet::WriteU32Little().
Referenced by SkillManager().
bool SkillManager::Respec (const std::shared_ptr< objects::ActivatedAbility > & activated, const std::shared_ptr< SkillExecutionContext > & ctx, const std::shared_ptr< ChannelClientConnection > & client) private
Execute a skill that causes all character skill points to be reset.
Parameters
activated Pointer to the activated ability instance
ctx Special execution state for the skill
client Pointer to the client connection that activated the skill, this will always fail if it is null
Definition at line 11856 of file SkillManager.cpp.
References libcomp::DatabaseChangeSet::Create(), channel::ClientState::GetAccountUID(), channel::ClientState::GetCharacterState(), mServer, ProcessSkillResult(), SendFailure(), SpecialSkill(), channel::state(), libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteS32Little().
Referenced by SkillManager().
bool SkillManager::Rest (const std::shared_ptr< objects::ActivatedAbility > & activated, const std::shared_ptr< SkillExecutionContext > & ctx, const std::shared_ptr< ChannelClientConnection > & client) private
Handle the "Rest" skill.
Parameters
activated Pointer to the activated ability instance
ctx Special execution state for the skill
client Pointer to the client connection that activated the skill, this will always fail if it is null
Definition at line 11960 of file SkillManager.cpp.
References CalculateStatusEffectStack(), channel::ActiveEntityState::ExpireStatusTimes(), channel::ChannelServer::GetServerTime(), mServer, and STATUS_RESTING.
Referenced by SkillManager().
void SkillManager::ScheduleAutoCancel (const std::shared_ptr< ActiveEntityState > source, const std::shared_ptr< objects::ActivatedAbility > & activated)
Schedule automatic skill cancellation after a set amount of time as defined by the skill definition.
If the skill is mutli-use, this should be called after each non-final execution.
Parameters
source Pointer to the entity using the skill
activated Pointer to the activated skill ability
Definition at line 2773 of file SkillManager.cpp.
References CancelSkill(), channel::ChannelServer::GetServerTime(), and mServer.
Referenced by ActivateSkill(), and SetSkillCompleteState().
void SkillManager::ScheduleFreeLoot (uint64_t time, const std::shared_ptr< Zone > & zone, const std::list< int32_t > & lootEntityIDs, const std::set< int32_t > & worldCIDs) private
Schedule the adjustment of who is a valid looter for one or more loot boxes.
Parameters
time Server time to schedule the adjustment for
zone Pointer to the zone the entities belong to
lootEntityIDs List of loot box IDs to adjust
worldCIDs Set of character world CIDs to add as valid looters
Definition at line 9848 of file SkillManager.cpp.
References channel::ChannelClientConnection::FlushAllOutgoing(), mServer, and channel::CharacterManager::SendLootItemData().
Referenced by HandleKills(), and HandleNegotiations().
void SkillManager::SendActivateSkill (const std::shared_ptr< channel::ProcessingSkill > & pSkill) private
Notify the client that a skill has been activated.
The client will notify the server when the specified charge time has elapsed for execution if applicable.
Parameters
pSkill Current skill processing state
Definition at line 12657 of file SkillManager.cpp.
References channel::ActiveEntityState::GetZone(), channel::ChannelClientConnection::SendRelativeTimePacket(), libcomp::Packet::WriteFloat(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS8(), libcomp::Packet::WriteU32Little(), and libcomp::Packet::WriteU8().
Referenced by ActivateSkill().
void SkillManager::SendCompleteSkill (std::shared_ptr< objects::ActivatedAbility > activated, uint8_t mode) private
Notify the client that a skill is complete.
Parameters
activated Pointer to the activated ability instance
mode Preset complete mode 0) Completed normally 1) Cancelled
Definition at line 12828 of file SkillManager.cpp.
References channel::ChannelClientConnection::BroadcastPacket(), channel::ActiveEntityState::GetZone(), channel::ChannelClientConnection::SendRelativeTimePacket(), libcomp::Packet::Size(), libcomp::Packet::WriteFloat(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS8(), libcomp::Packet::WriteU32Little(), and libcomp::Packet::WriteU8().
Referenced by CancelSkill(), ExecuteSkill(), and FinalizeSkill().
void SkillManager::SendExecuteSkill (const std::shared_ptr< channel::ProcessingSkill > & pSkill) private
Notify the client that a skill is executing.
Parameters
pSkill Current skill processing state
Definition at line 12713 of file SkillManager.cpp.
References channel::ActiveEntityState::GetZone(), SendExecuteSkillInstant(), channel::ChannelClientConnection::SendRelativeTimePacket(), libcomp::Packet::WriteBlank(), libcomp::Packet::WriteFloat(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS8(), libcomp::Packet::WriteU32Little(), and libcomp::Packet::WriteU8().
Referenced by FinalizeSkillExecution(), and ProcessSkillResultFinal().
void SkillManager::SendExecuteSkillInstant (const std::shared_ptr< channel::ProcessingSkill > & pSkill, uint8_t errorCode) private
Notify the client that a skill is immediately executing without some normal prerequisite packets.
Parameters
pSkill Current skill processing state
errorCode If the skill execution failed an error code will be supplied here.
Definition at line 12783 of file SkillManager.cpp.
References channel::ChannelClientConnection::BroadcastPacket(), channel::ActiveEntityState::GetZone(), channel::ChannelClientConnection::SendRelativeTimePacket(), libcomp::Packet::Size(), libcomp::Packet::WriteFloat(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteU32Little(), and libcomp::Packet::WriteU8().
Referenced by SendExecuteSkill(), and SendFailure().
void SkillManager::SendFailure (const std::shared_ptr< ActiveEntityState > source, uint32_t skillID, const std::shared_ptr< ChannelClientConnection > client, uint8_t errorCode = 13, int8_t activationID = -1)
Notify the client that a skill failed activation or execution.
Parameters
source Pointer of the entity that the skill failed for
skillID ID of the skill to activate
client Pointer to the client connection that should be sent the failure instead of the entire zone
errorCode Error code to send (defaults to generic, no message)
activationID ID of the activated ability instance (or -1 for none)
Definition at line 1059 of file SkillManager.cpp.
References channel::ChannelClientConnection::BroadcastPacket(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS8(), libcomp::Packet::WriteU32Little(), and libcomp::Packet::WriteU8().
Referenced by ActivateSkill(), BeginSkillExecution(), Cameo(), Cloak(), DCM(), DetermineCosts(), Digitalize(), DigitalizeCancel(), EquipItem(), ExecuteNormalSkill(), ExecuteSkill(), FamiliarityUp(), FamiliarityUpItem(), ForgetAllExpertiseSkills(), MinionDespawn(), MinionSpawn(), Mooch(), Mount(), PrepareFusionSkill(), RandomItem(), Respec(), SendFailure(), Spawn(), SpawnZone(), StoreDemon(), SummonDemon(), Traesto(), and XPUp().
void SkillManager::SendFailure (std::shared_ptr< objects::ActivatedAbility > activated, const std::shared_ptr< ChannelClientConnection > client, uint8_t errorCode = 0) private
Notify the client that a skill failed activation or execution.
Parameters
activated Pointer to the activated ability instance
client Pointer to the client connection, can be null if not coming from a player entity
errorCode Error code to send (defaults to generic, no message)
Definition at line 2304 of file SkillManager.cpp.
References CancelSkill(), GetProcessingSkill(), SendExecuteSkillInstant(), and SendFailure().
bool SkillManager::SetNRA (SkillTargetResult & target, ProcessingSkill & skill, bool reduceShields = true) private
Set null, reflect or absorb on the skill target.
Parameters
target Target to update with NRA flags
skill Current skill processing state
reduceShields If true, any NRA shields will be consumed should they apply first
Returns
true if the damage was reflected, otherwise false
Definition at line 9520 of file SkillManager.cpp.
References channel::ProcessingSkill::Activated, libcomp::String::Arg(), channel::SkillTargetResult::AutoProtect, channel::SkillTargetResult::CalcState, channel::ProcessingSkill::EffectiveAffinity, channel::ProcessingSkill::EffectiveDependencyType, channel::SkillTargetResult::EntityState, GetNRAResult(), channel::SkillTargetResult::HitAbsorb, channel::SkillTargetResult::HitAvoided, channel::SkillTargetResult::HitNull, channel::SkillTargetResult::HitReflect, channel::ProcessingSkill::InPvP, channel::SkillTargetResult::NRAAffinity, and channel::ProcessingSkill::SkillID.
Referenced by BeginSkillExecution(), and ProcessSkillResult().
bool SkillManager::SetSkillCompleteState (const std::shared_ptr< channel::ProcessingSkill > & pSkill, bool executed) private
Mark all information pertaining to a skill completing either through execution or cancellation with more uses available.
Parameters
pSkill Pointer to the skill being processed
executed true if the skill was executed, false if it is being cancelled
Returns
true if the skill can be used again, false if it cannot
Definition at line 10132 of file SkillManager.cpp.
References GetCalculatedState(), channel::ChannelServer::GetServerTime(), mServer, ScheduleAutoCancel(), SkillHasMoreUses(), and STATUS_LOCKOUT.
Referenced by CancelSkill(), and FinalizeSkillExecution().
bool SkillManager::SkillHasMoreUses (const std::shared_ptr< objects::ActivatedAbility > & activated) static
Determine if a skill has more uses pending.
Parameters
activated Pointer to the activated skill ability
Returns
true if the skill has more uses pending
Definition at line 1655 of file SkillManager.cpp.
Referenced by channel::CharacterManager::AddRemoveOpponent(), and SetSkillCompleteState().
bool SkillManager::SkillRestricted (const std::shared_ptr< ActiveEntityState > source, const std::shared_ptr< objects::MiSkillData > & skillData, int64_t activationObjectID = 0, std::shared_ptr< SkillExecutionContext > ctx = nullptr)
Determine if the specified skill is locked from use on the supplied entity.
Parameters
source Entity that is attempting to use the skill
skillData Pointer to the skill's definition
activationObjectID Optional ID of the object used as the activation target. If not specified, context specific checks will fail.
ctx Special execution state for the skill
Returns
true if the skill is restricted from being used
Definition at line 1087 of file SkillManager.cpp.
References channel::CharacterState::GetDigitalizeState(), channel::ActiveEntityStateImp< T >::GetEntity(), channel::ClientState::GetEntityClientState(), libcomp::PersistentObject::GetObjectByUUID(), channel::ClientState::GetObjectUUID(), IsTalkSkill(), mServer, channel::NONE, channel::state(), and SVR_CONST.
Referenced by ActivateSkill(), and ExecuteSkill().
bool SkillManager::SkillZoneRestricted (uint32_t skillID, const std::shared_ptr< Zone > zone)
Determine if the specified skill is locked from use in the current zone.
Parameters
skillID ID of the skill being checked
zone Pointer to the current zone
Returns
true if the skill is restricted from being used
Definition at line 1303 of file SkillManager.cpp.
References mServer.
Referenced by ActivateSkill().
bool SkillManager::Spawn (const std::shared_ptr< objects::ActivatedAbility > & activated, const std::shared_ptr< SkillExecutionContext > & ctx, const std::shared_ptr< ChannelClientConnection > & client) private
Execute a (non-zone specific) enemy spawning skill.
Parameters
activated Pointer to the activated ability instance
ctx Special execution state for the skill
client Pointer to the client connection that activated the skill, this will always fail if it is null
Definition at line 12013 of file SkillManager.cpp.
References libcomp::String::Arg(), libcomp::Randomizer::GetEntry(), channel::ZoneManager::GetRandomRotation(), channel::ActionOptions::GroupID, mServer, ProcessSkillResult(), SendFailure(), SpecialSkill(), and channel::Point::x.
Referenced by SkillManager().
bool SkillManager::SpawnZone (const std::shared_ptr< objects::ActivatedAbility > & activated, const std::shared_ptr< SkillExecutionContext > & ctx, const std::shared_ptr< ChannelClientConnection > & client) private
Execute a zone specific enemy spawning skill.
Parameters
activated Pointer to the activated ability instance
ctx Special execution state for the skill
client Pointer to the client connection that activated the skill, this will always fail if it is null
Definition at line 12168 of file SkillManager.cpp.
References libcomp::String::Arg(), channel::ZoneManager::GetRandomRotation(), channel::ActionOptions::GroupID, mServer, ProcessSkillResult(), SendFailure(), SpecialSkill(), and channel::Point::x.
Referenced by SkillManager().
bool SkillManager::SpecialSkill (const std::shared_ptr< objects::ActivatedAbility > & activated, const std::shared_ptr< SkillExecutionContext > & ctx, const std::shared_ptr< ChannelClientConnection > & client) private
Placeholder function for a skill actually handled outside of the SkillManager.
Parameters
activated Pointer to the activated ability instance
ctx Special execution state for the skill
client Pointer to the client connection that activated the skill, can be null for non-player entity sources
Definition at line 10240 of file SkillManager.cpp.
References channel::ChannelServer::GetServerTime().
Referenced by Cameo(), Cloak(), DCM(), Despawn(), Desummon(), Digitalize(), DigitalizeCancel(), EquipItem(), FamiliarityUp(), FamiliarityUpItem(), ForgetAllExpertiseSkills(), MinionDespawn(), MinionSpawn(), Mooch(), Mount(), RandomItem(), Randomize(), Respec(), SkillManager(), Spawn(), SpawnZone(), StoreDemon(), SummonDemon(), Traesto(), and XPUp().
bool SkillManager::StoreDemon (const std::shared_ptr< objects::ActivatedAbility > & activated, const std::shared_ptr< SkillExecutionContext > & ctx, const std::shared_ptr< ChannelClientConnection > & client) private
Execute the "store demon" skill.
Parameters
activated Pointer to the activated ability instance
ctx Special execution state for the skill
client Pointer to the client connection that activated the skill, this will always fail if it is null
Definition at line 12392 of file SkillManager.cpp.
References libcomp::String::Arg(), channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), channel::ClientState::GetObjectID(), mServer, ProcessSkillResult(), SendFailure(), SpecialSkill(), and channel::state().
Referenced by SkillManager().
bool SkillManager::SummonDemon (const std::shared_ptr< objects::ActivatedAbility > & activated, const std::shared_ptr< SkillExecutionContext > & ctx, const std::shared_ptr< ChannelClientConnection > & client) private
Execute the "summon demon" skill.
Parameters
activated Pointer to the activated ability instance
ctx Special execution state for the skill
client Pointer to the client connection that activated the skill, this will always fail if it is null
Definition at line 12310 of file SkillManager.cpp.
References libcomp::String::Arg(), channel::ClientState::GetAccountUID(), channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), libcomp::PersistentObject::GetObjectByUUID(), channel::ClientState::GetObjectUUID(), mServer, ProcessSkillResult(), SendFailure(), SpecialSkill(), channel::state(), and SVR_CONST.
Referenced by SkillManager().
bool SkillManager::TargetInRange (const std::shared_ptr< ActiveEntityState > source, const std::shared_ptr< objects::MiSkillData > & skillData, const std::shared_ptr< ActiveEntityState > & target)
Determine if the skill target supplied is in range for a specific skill.
Parameters
source Entity that is attempting to use the skill
skillData Pointer to the skill's definition
target Pointer to the targeted entity
Returns
true if the target entity is in range, false if it is not
Definition at line 1330 of file SkillManager.cpp.
References channel::ChannelServer::GetServerTime().
Referenced by BeginSkillExecution(), and PrepareFusionSkill().
bool SkillManager::TargetSkill (const std::shared_ptr< ActiveEntityState > source, int64_t targetObjectID)
Target/retarget the skill of a character or demon.
No response is sent to the clients from this request.
Parameters
source Pointer of the entity that activated the skill
targetObjectID ID of the object being targeted by the skill
Returns
true if the skill was targeted successfully, false otherwise
Definition at line 636 of file SkillManager.cpp.
bool SkillManager::ToggleSwitchSkill (const std::shared_ptr< ChannelClientConnection > client, std::shared_ptr< objects::ActivatedAbility > activated, const std::shared_ptr< SkillExecutionContext > & ctx) private
Toggle a switch skill, not handled by a special handler.
Parameters
client Pointer to the client connection that activated the skill
activated Pointer to the activated ability instance
ctx Special execution state for the skill
Definition at line 8480 of file SkillManager.cpp.
References FinalizeSkill(), FinalizeSkillExecution(), mServer, libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS8(), and libcomp::Packet::WriteU32Little().
Referenced by ExecuteSkill().
bool SkillManager::Traesto (const std::shared_ptr< objects::ActivatedAbility > & activated, const std::shared_ptr< SkillExecutionContext > & ctx, const std::shared_ptr< ChannelClientConnection > & client) private
Execute the skill "Traesto" which returns the user to a preset zone.
Parameters
activated Pointer to the activated ability instance
ctx Special execution state for the skill
client Pointer to the client connection that activated the skill, this will always fail if it is null
Definition at line 12450 of file SkillManager.cpp.
References channel::ClientState::GetCharacterState(), GetProcessingSkill(), mServer, ProcessSkillResult(), SendFailure(), SpecialSkill(), channel::state(), and SVR_CONST.
Referenced by SkillManager().
void SkillManager::UpdatePvPStats (const std::shared_ptr< channel::ProcessingSkill > & pSkill) private
Update all PvP instance recorded statistics if the match is active.
Parameters
pSkill Skill processing state of the skill being executed
Definition at line 7449 of file SkillManager.cpp.
References channel::SkillTargetResult::AddedStatuses, channel::SkillTargetResult::Damage1, channel::SkillTargetResult::Damage1Type, channel::SkillTargetResult::Damage2, channel::SkillTargetResult::Damage2Type, DAMAGE_TYPE_GENERIC, channel::SkillTargetResult::EntityState, FLAG1_LETHAL, channel::SkillTargetResult::Flags1, channel::ClientState::GetCharacterState(), channel::ClientState::GetEntityClientState(), channel::SkillTargetResult::IndirectTarget, mServer, channel::MatchManager::PvPActive(), and channel::state().
Referenced by ApplyZoneSpecificEffects().
bool SkillManager::ValidateActivationItem (const std::shared_ptr< ActiveEntityState > source, const std::shared_ptr< objects::Item > & item)
Determine if the skill activation item supplied is valid for a specific source entity.
Parameters
source Entity that is attempting to use the skill
item Pointer to the item used for skill activation
Returns
true if it is valid, false if it is not
Definition at line 1574 of file SkillManager.cpp.
References channel::ClientState::GetCharacterState(), channel::ClientState::GetEntityClientState(), mServer, and channel::state().
int8_t SkillManager::ValidateSkillTarget (const std::shared_ptr< ActiveEntityState > source, const std::shared_ptr< objects::MiSkillData > & skillData, const std::shared_ptr< ActiveEntityState > & target)
Determine if the skill target supplied is valid for a specific skill.
Parameters
source Entity that is attempting to use the skill
skillData Pointer to the skill's definition
target Pointer to the targeted entity
Returns
Skill error code or -1 if no error
Definition at line 1361 of file SkillManager.cpp.
References channel::ActiveEntityStateImp< T >::GetEntity(), channel::ClientState::GetEntityClientState(), channel::ClientState::GetZone(), IsTalkSkill(), and SVR_CONST.
Referenced by ExecuteSkill().
bool SkillManager::XPUp (const std::shared_ptr< objects::ActivatedAbility > & activated, const std::shared_ptr< SkillExecutionContext > & ctx, const std::shared_ptr< ChannelClientConnection > & client) private
Execute a skill that grants XP to the character or partner demon.
Parameters
activated Pointer to the activated ability instance
ctx Special execution state for the skill
client Pointer to the client connection that activated the skill, this will always fail if it is null
Definition at line 12544 of file SkillManager.cpp.
References channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), GetProcessingSkill(), mServer, ProcessSkillResult(), SendFailure(), SpecialSkill(), channel::state(), and SVR_CONST.
Referenced by SkillManager().
Member Data Documentation
std::weak_ptr<ChannelServer> channel::SkillManager::mServer private
Pointer to the channel server.
Definition at line 1421 of file SkillManager.h.
Referenced by ActivateSkill(), ApplyNegotiationDamage(), BeginSkillExecution(), CalculateDamage(), CalculateDamage_Normal(), Cameo(), CancelSkill(), Cloak(), CompleteSkillExecution(), DCM(), Desummon(), DetermineCosts(), DetermineNormalCosts(), Digitalize(), DigitalizeBreak(), DigitalizeCancel(), DirectStatus(), EquipItem(), Estoma(), ExecuteSkill(), FamiliarityUp(), FamiliarityUpItem(), FinalizeSkillExecution(), Fizzle(), ForgetAllExpertiseSkills(), GetAffinityBoost(), GetCalculatedState(), GetItemDrops(), GetProcessingSkill(), GetSummonSpeed(), GiveDemonPresent(), HandleDigitalizeXP(), HandleDurabilityDamage(), HandleEncounterDefeat(), HandleFusionGauge(), HandleKills(), HandleKillXP(), HandleNegotiations(), HandleRevives(), HandleSkillInterrupt(), HandleSkillLearning(), HandleStatusEffects(), IFramesEnabled(), InterruptEvents(), Liberama(), MinionSpawn(), Mooch(), Mount(), PrepareFusionSkill(), ProcessSkillResult(), ProcessSkillResultFinal(), RandomItem(), Randomize(), Respec(), Rest(), ScheduleAutoCancel(), ScheduleFreeLoot(), SetSkillCompleteState(), SkillRestricted(), SkillZoneRestricted(), Spawn(), SpawnZone(), StoreDemon(), SummonDemon(), ToggleSwitchSkill(), Traesto(), UpdatePvPStats(), ValidateActivationItem(), and XPUp().
std::unordered_map<uint16_t, std::function<bool(SkillManager&, const std::shared_ptr<objects::ActivatedAbility>&, const std::shared_ptr<SkillExecutionContext>&, const std::shared_ptr<ChannelClientConnection>&)> > channel::SkillManager::mSkillEffectFunctions private
Map of skill function IDs mapped to manager functions that perform special actions after the normal skill processing completes.
Definition at line 1435 of file SkillManager.h.
Referenced by FunctionIDMapped(), and SkillManager().
std::unordered_map<uint16_t, std::function<bool(SkillManager&, const std::shared_ptr<objects::ActivatedAbility>&, const std::shared_ptr<SkillExecutionContext>&, const std::shared_ptr<ChannelClientConnection>&)> > channel::SkillManager::mSkillFunctions private
Map of skill function IDs mapped to manager functions that execute in place of the normal skill handler.
Definition at line 1428 of file SkillManager.h.
Referenced by ActivateSkill(), CancelSkill(), ExecuteSkill(), FunctionIDMapped(), and SkillManager().
The documentation for this class was generated from the following files:
SkillManager.h
SkillManager.cpp