COMP_hack: channel::TokuseiManager Class Reference
channel::TokuseiManager Class Reference
Manages tokusei specific logic for the server and validates the definitions read at run time.
#include <TokuseiManager.h>
Public Member Functions
TokuseiManager (const std::weak_ptr< ChannelServer > &server)
Create a new TokuseiManager.
virtual ~TokuseiManager ()
Clean up the TokuseiManager.
bool AspectValueExists (const std::shared_ptr< ActiveEntityState > &eState, TokuseiAspectType type, double value)
Determine if the supplied value exists for a specified aspect type on an entity.
bool DeadTokuseiDisabled ()
Determine if the server is configured for tokusei to become inactive from a source after it has been killed.
bool EvaluateTokuseiCondition (const std::shared_ptr< ActiveEntityState > &eState, int32_t tokuseiID, const std::shared_ptr< objects::TokuseiCondition > &condition)
Evaluate a condition from a tokusei.
bool EvaluateTokuseiConditions (const std::shared_ptr< ActiveEntityState > &eState, const std::shared_ptr< objects::Tokusei > &tokusei)
Evaluate all conditions on a tokusei to determine if it should be active.
std::list< std::shared_ptr
< ActiveEntityState > > GetAllTokuseiEntities (const std::shared_ptr< ActiveEntityState > &eState)
Get all entities that could be affected by any other tokusei effect from another entity in the list, starting with the supplied entity.
std::unordered_map< int32_t,
double > GetAspectMap (const std::shared_ptr< ActiveEntityState > &eState, TokuseiAspectType type, std::shared_ptr< objects::CalculatedEntityState > calcState=nullptr)
Calculate the sum of all instances of a specific aspect's modifier values keyed on shared aspect value on the supplied entity.
std::unordered_map< int32_t,
double > GetAspectMap (const std::shared_ptr< ActiveEntityState > &eState, TokuseiAspectType type, std::set< int32_t > validKeys, std::shared_ptr< objects::CalculatedEntityState > calcState=nullptr)
Calculate the sum of all instances of a specific aspect's modifier values keyed on shared aspect value on the supplied entity.
double GetAspectSum (const std::shared_ptr< ActiveEntityState > &eState, TokuseiAspectType type, std::shared_ptr< objects::CalculatedEntityState > calcState=nullptr)
Calculate the sum of all instances of a specific aspect value on the supplied entity.
std::list< double > GetAspectValueList (const std::shared_ptr< ActiveEntityState > &eState, TokuseiAspectType type, std::shared_ptr< objects::CalculatedEntityState > calcState=nullptr)
Get the list of all aspect values on the supplied entity and type.
std::list< std::shared_ptr
< objects::Tokusei > > GetDirectTokusei (const std::shared_ptr< ActiveEntityState > &eState)
Get all tokusei originating from the supplied entity, active or not.
bool Initialize ()
Initialize the manager and validate the tokusei definitions loaded.
void RecalcTimedTokusei (WorldClock &clock)
Recalculate all time restricted tokusei based on the current world time.
std::unordered_map< int32_t, bool > Recalculate (const std::shared_ptr< ActiveEntityState > &eState, std::set< TokuseiConditionType > changes)
Recalculate the tokusei effects on the supplied entity and any related entities if any of the specified changes are triggers on the entity.
std::unordered_map< int32_t, bool > Recalculate (const std::shared_ptr< ActiveEntityState > &eState, bool recalcStats=false, std::set< int32_t > ignoreStatRecalc={})
Recalculate the tokusei effects on the supplied entity and any related entities.
std::unordered_map< int32_t, bool > Recalculate (const std::list< std::shared_ptr< ActiveEntityState >> &entities, bool recalcStats=false, std::set< int32_t > ignoreStatRecalc={})
Recalculate the tokusei effects on the supplied entities.
std::unordered_map< int32_t, bool > RecalculateParty (const std::shared_ptr< objects::Party > &party)
Recalculate the tokusei effects for all entities in a party on the channel.
void RemoveTrackingEntities (int32_t worldCID)
Unregister the world CID of a character that may have had time restricted tokusei associated to one or more entity.
void SendCostAdjustments (int32_t entityID, const std::shared_ptr< ChannelClientConnection > &client)
Send skill cost adjustments from tokusei for the specified entity to the client.
void UpdateDiasporaMinibossCount (const std::shared_ptr< Zone > &zone)
Update all entities affected by the DIASPORA_MINIBOSS_COUNT tokusei condition in the supplied zone.
void UpdateMovementDecay (const std::shared_ptr< ChannelClientConnection > &client, float distance)
Lower durability on all movement durability decay equipment.
Static Public Member Functions
static double CalculateAttributeValue (ActiveEntityState *eState, int32_t value, int32_t base, const std::shared_ptr< objects::TokuseiAttributes > &attributes, std::shared_ptr< objects::CalculatedEntityState > calcState=nullptr)
Calculate the value of an attribute driven tokusei value.
Private Member Functions
bool BuildWorldClockTime (std::shared_ptr< objects::TokuseiCondition > condition, WorldClockTime &time)
Convert a tokusei condition to a world clock time representation.
bool Compare (int32_t value, std::shared_ptr< objects::TokuseiCondition > condition, bool numericCompare) const
Compare the supplied value and condition value.
bool Compare (int32_t value1, int32_t value2, std::shared_ptr< objects::TokuseiCondition > condition, bool numericCompare) const
Compare the supplied two values.
bool GatherTimedTokusei (const std::shared_ptr< objects::Tokusei > &tokusei)
Gather all timed tokusei conditions and register their time representations with the manager and server.
void RecalcCostAdjustments (const std::shared_ptr< ActiveEntityState > &eState)
Recalculate skill cost adjustments from tokusei for the specified entity.
void SendCostAdjustments (int32_t entityID, std::list< std::shared_ptr< objects::ClientCostAdjustment >> &adjustments, const std::shared_ptr< ChannelClientConnection > &client)
Send skill cost adjustments from tokusei for the specified entity to the client.
Private Attributes
std::set< int32_t > mCostAdjustmentTokusei
Set of all tokusei with at least one cost adjustment aspect.
std::set< int32_t > mMoveDecayTokusei
Set of all tokusei with at least one movement decay aspect.
std::weak_ptr< ChannelServer > mServer
Pointer to the channel server.
std::unordered_map< uint32_t,
std::set< int32_t > > mStatusEffectTokusei
Quick access mapping of constant status effect IDs to their source tokusei IDs.
std::unordered_map< int32_t, bool > mTimedTokusei
Map of all tokusei effect IDs that have a time restriction to a boolean "active" indicator.
std::unordered_map< int32_t,
std::set< int32_t > > mTimedTokuseiEntities
Map of world CIDs to the set of related time restricted tokusei.
std::mutex mTimeLock
Server lock for time calculation.
Detailed Description
Manages tokusei specific logic for the server and validates the definitions read at run time.
Definition at line 64 of file TokuseiManager.h.
Constructor & Destructor Documentation
TokuseiManager::TokuseiManager (const std::weak_ptr< ChannelServer > & server)
Create a new TokuseiManager.
Parameters
server Pointer back to the channel server this belongs to.
Definition at line 78 of file TokuseiManager.cpp.
TokuseiManager::~TokuseiManager () virtual
Clean up the TokuseiManager.
Definition at line 83 of file TokuseiManager.cpp.
Member Function Documentation
bool TokuseiManager::AspectValueExists (const std::shared_ptr< ActiveEntityState > & eState, TokuseiAspectType type, double value)
Determine if the supplied value exists for a specified aspect type on an entity.
Parameters
eState Pointer to the tokusei source
type Aspect type to gather values from
value Value to check for
Returns
true if the value exists, false if it does not
Definition at line 1986 of file TokuseiManager.cpp.
References GetAspectValueList().
bool TokuseiManager::BuildWorldClockTime (std::shared_ptr< objects::TokuseiCondition > condition, WorldClockTime & time) private
Convert a tokusei condition to a world clock time representation.
Calling this function for multiple conditions will combine the times into a complex time representation.
Parameters
condition Pointer to the tokusei condition
time Output parameter to store the time in
Returns
true the time was adjusted correctly, false if an error occurred
Definition at line 2362 of file TokuseiManager.cpp.
References channel::WorldClockTime::Hour, channel::WorldClockTime::Min, and channel::WorldClockTime::MoonPhase.
Referenced by GatherTimedTokusei().
double TokuseiManager::CalculateAttributeValue (ActiveEntityState * eState, int32_t value, int32_t base, const std::shared_ptr< objects::TokuseiAttributes > & attributes, std::shared_ptr< objects::CalculatedEntityState > calcState = nullptr) static
Calculate the value of an attribute driven tokusei value.
Parameters
eState Pointer to the tokusei source
value Default value to use for the calculation
base Base value used for specific calculation types
attributes Pointer to the attribute definitions to use when calculating the value
calcState Override CalculatedEntityState to use instead of the entity's default
Returns
Calculated attribute value
Definition at line 1629 of file TokuseiManager.cpp.
References channel::ClientState::GetCharacterState(), channel::ActiveEntityState::GetCoreStats(), channel::ClientState::GetDemonState(), channel::ClientState::GetEntityClientState(), channel::ActiveEntityState::GetLevel(), channel::ClientState::GetWorldCID(), channel::ActiveEntityState::GetZone(), and channel::state().
Referenced by channel::ActiveEntityState::AdjustStats(), GetAspectMap(), GetAspectSum(), GetAspectValueList(), and RecalcCostAdjustments().
bool TokuseiManager::Compare (int32_t value, std::shared_ptr< objects::TokuseiCondition > condition, bool numericCompare) const private
Compare the supplied value and condition value.
Parameters
value LHS value to compare
condition Tokusei condition to use the comparator and RHS value from
numericCompare If false and a numeric comparator type is on the condition this will always return false
Returns
false if the condition does not evaluate to true
Definition at line 2410 of file TokuseiManager.cpp.
Referenced by EvaluateTokuseiCondition(), and RecalcTimedTokusei().
bool TokuseiManager::Compare (int32_t value1, int32_t value2, std::shared_ptr< objects::TokuseiCondition > condition, bool numericCompare) const private
Compare the supplied two values.
Parameters
value1 LHS value to compare
value2 RHS value to compare
condition Tokusei condition to use the comparator from
numericCompare If false and a numeric comparator type is on the condition this will always return false
Returns
false if the condition does not evaluate to true
Definition at line 2416 of file TokuseiManager.cpp.
bool TokuseiManager::DeadTokuseiDisabled ()
Determine if the server is configured for tokusei to become inactive from a source after it has been killed.
Returns
true if the tokusei should become inactive, false if they should stay active
Definition at line 2161 of file TokuseiManager.cpp.
References mServer.
Referenced by GetDirectTokusei().
bool TokuseiManager::EvaluateTokuseiCondition (const std::shared_ptr< ActiveEntityState > & eState, int32_t tokuseiID, const std::shared_ptr< objects::TokuseiCondition > & condition)
Evaluate a condition from a tokusei.
Parameters
eState Pointer to the tokusei source to evaluate the conditions for
tokuseiID ID of the source tokusei effect
condition Pointer to the condition to evaluate
Returns
true if the condition evaluates to true
Definition at line 1371 of file TokuseiManager.cpp.
References Compare(), channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), channel::CharacterState::GetDigitalizeState(), channel::ActiveEntityStateImp< T >::GetEntity(), channel::ClientState::GetEntityClientState(), channel::CharacterState::GetExpertiseRank(), channel::ClientState::GetWorldCID(), channel::ClientState::GetZone(), mServer, mTimedTokusei, and channel::state().
Referenced by EvaluateTokuseiConditions().
bool TokuseiManager::EvaluateTokuseiConditions (const std::shared_ptr< ActiveEntityState > & eState, const std::shared_ptr< objects::Tokusei > & tokusei)
Evaluate all conditions on a tokusei to determine if it should be active.
Parameters
eState Pointer to the tokusei source to evaluate the conditions for
tokusei Pointer to the tokusei to evaluate the conditions for
Returns
true if the condition set evaluates to true
Definition at line 1310 of file TokuseiManager.cpp.
References EvaluateTokuseiCondition().
Referenced by Recalculate().
bool TokuseiManager::GatherTimedTokusei (const std::shared_ptr< objects::Tokusei > & tokusei) private
Gather all timed tokusei conditions and register their time representations with the manager and server.
Parameters
tokusei Pointer to the tokusei definition
Returns
true if the tokusei was registered successfully, false if an error occurred
Definition at line 466 of file TokuseiManager.cpp.
References libcomp::String::Arg(), BuildWorldClockTime(), mServer, and mTimedTokusei.
Referenced by Initialize().
std::list< std::shared_ptr< ActiveEntityState > > TokuseiManager::GetAllTokuseiEntities (const std::shared_ptr< ActiveEntityState > & eState)
Get all entities that could be affected by any other tokusei effect from another entity in the list, starting with the supplied entity.
Parameters
eState Pointer to the primary entity to add to the list
Returns
List of entities that could affect one another via a tokusei
Definition at line 993 of file TokuseiManager.cpp.
References channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), channel::ClientState::GetEntityClientState(), channel::ClientState::GetWorldCID(), channel::ClientState::GetZone(), and channel::state().
Referenced by Recalculate().
std::unordered_map< int32_t, double > TokuseiManager::GetAspectMap (const std::shared_ptr< ActiveEntityState > & eState, TokuseiAspectType type, std::shared_ptr< objects::CalculatedEntityState > calcState = nullptr)
Calculate the sum of all instances of a specific aspect's modifier values keyed on shared aspect value on the supplied entity.
Parameters
eState Pointer to the tokusei source
type Aspect type to gather values from
calcState Override CalculatedEntityState to use instead of the entity's default
Returns
Map of calculated aspect modifier value sums by aspect value
Definition at line 1874 of file TokuseiManager.cpp.
std::unordered_map< int32_t, double > TokuseiManager::GetAspectMap (const std::shared_ptr< ActiveEntityState > & eState, TokuseiAspectType type, std::set< int32_t > validKeys, std::shared_ptr< objects::CalculatedEntityState > calcState = nullptr)
Calculate the sum of all instances of a specific aspect's modifier values keyed on shared aspect value on the supplied entity.
Parameters
eState Pointer to the tokusei source
type Aspect type to gather values from
validKeys Set of keys to keep from the overall set
calcState Override CalculatedEntityState to use instead of the entity's default
Returns
Map of calculated aspect modifier value sums by aspect value with a default value of zero
Definition at line 1882 of file TokuseiManager.cpp.
References CalculateAttributeValue(), and mServer.
double TokuseiManager::GetAspectSum (const std::shared_ptr< ActiveEntityState > & eState, TokuseiAspectType type, std::shared_ptr< objects::CalculatedEntityState > calcState = nullptr)
Calculate the sum of all instances of a specific aspect value on the supplied entity.
Parameters
eState Pointer to the tokusei source
type Aspect type to calculate the sum of
calcState Override CalculatedEntityState to use instead of the entity's default
Returns
Calculated aspect value sum
Definition at line 1831 of file TokuseiManager.cpp.
References CalculateAttributeValue(), and mServer.
std::list< double > TokuseiManager::GetAspectValueList (const std::shared_ptr< ActiveEntityState > & eState, TokuseiAspectType type, std::shared_ptr< objects::CalculatedEntityState > calcState = nullptr)
Get the list of all aspect values on the supplied entity and type.
Parameters
eState Pointer to the tokusei source
type Aspect type to gather values from
calcState Override CalculatedEntityState to use instead of the entity's default
Returns
List of all aspect values of the specified type
Definition at line 1942 of file TokuseiManager.cpp.
References CalculateAttributeValue(), and mServer.
Referenced by AspectValueExists().
std::list< std::shared_ptr< objects::Tokusei > > TokuseiManager::GetDirectTokusei (const std::shared_ptr< ActiveEntityState > & eState)
Get all tokusei originating from the supplied entity, active or not.
Parameters
eState Pointer to the entity
Returns
List of tokusei originating from the supplied entity, can contain duplicates
Definition at line 1045 of file TokuseiManager.cpp.
References DeadTokuseiDisabled(), channel::ActiveEntityStateImp< T >::GetEntity(), channel::ActiveEntityStateImp< T >::GetLevel(), mServer, and SVR_CONST.
Referenced by Recalculate().
bool TokuseiManager::Initialize ()
Initialize the manager and validate the tokusei definitions loaded.
Returns
false if any errors were encountered
Definition at line 87 of file TokuseiManager.cpp.
References libcomp::String::Arg(), GatherTimedTokusei(), mCostAdjustmentTokusei, mMoveDecayTokusei, mServer, and mStatusEffectTokusei.
Referenced by channel::ChannelServer::Initialize().
void TokuseiManager::RecalcCostAdjustments (const std::shared_ptr< ActiveEntityState > & eState) private
Recalculate skill cost adjustments from tokusei for the specified entity.
If the entity's data has already been sent to the client, the new costs will be sent too.
Parameters
eState Pointer to the entity to recalculate
Definition at line 2168 of file TokuseiManager.cpp.
References CalculateAttributeValue(), channel::ClientState::GetEntityClientState(), mCostAdjustmentTokusei, mServer, SendCostAdjustments(), channel::ClientState::SetCostAdjustments(), and channel::state().
Referenced by Recalculate().
void TokuseiManager::RecalcTimedTokusei (WorldClock & clock)
Recalculate all time restricted tokusei based on the current world time.
Parameters
clock World clock set to the current time
Definition at line 2000 of file TokuseiManager.cpp.
References Compare(), channel::ClientState::GetCharacterState(), channel::ClientState::GetEntityClientState(), channel::WorldClockTime::Hour, channel::WorldClockTime::Min, channel::WorldClockTime::MoonPhase, mServer, mTimedTokusei, mTimedTokuseiEntities, mTimeLock, Recalculate(), and channel::state().
Referenced by channel::ChannelServer::HandleClockEvents(), and channel::ChannelServer::ScheduleRecurringActions().
std::unordered_map< int32_t, bool > TokuseiManager::Recalculate (const std::shared_ptr< ActiveEntityState > & eState, std::set< TokuseiConditionType > changes)
Recalculate the tokusei effects on the supplied entity and any related entities if any of the specified changes are triggers on the entity.
Parameters
eState Pointer to the entity that has changed
changes Changes that could trigger a tokusei recalculation
Returns
Map of entity IDs to a true value if they have had their stats recalculated or false if only their tokusei sets and triggers were updated
Definition at line 583 of file TokuseiManager.cpp.
References channel::ClientState::GetCharacterState(), channel::ClientState::GetEntityClientState(), and channel::state().
Referenced by RecalcTimedTokusei(), Recalculate(), RecalculateParty(), and UpdateDiasporaMinibossCount().
std::unordered_map< int32_t, bool > TokuseiManager::Recalculate (const std::shared_ptr< ActiveEntityState > & eState, bool recalcStats = false, std::set< int32_t > ignoreStatRecalc = {})
Recalculate the tokusei effects on the supplied entity and any related entities.
Parameters
eState Pointer to the primary entity to recalculate
recalcStats false if the effect tokusei should be determined but the entities should not have their stats recalculated, true if both should occur
ignoreStateRecalc Set of entity IDs to ignore when recalculating stats
Returns
Map of entity IDs to a true value if they have had their stats recalculated or false if only their tokusei sets and triggers were updated
Definition at line 625 of file TokuseiManager.cpp.
References GetAllTokuseiEntities(), and Recalculate().
std::unordered_map< int32_t, bool > TokuseiManager::Recalculate (const std::list< std::shared_ptr< ActiveEntityState >> & entities, bool recalcStats = false, std::set< int32_t > ignoreStatRecalc = {})
Recalculate the tokusei effects on the supplied entities.
Parameters
entities List of pointers to the entities to recalculate
recalcStats false if the effect tokusei should be determined but the entities should not have their stats recalculated, true if both should occur
ignoreStateRecalc Set of entity IDs to ignore when recalculating stats
Returns
Map of entity IDs to a true value if they have had their stats recalculated or false if only their tokusei sets and triggers were updated
Definition at line 632 of file TokuseiManager.cpp.
References EvaluateTokuseiConditions(), channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), GetDirectTokusei(), channel::ClientState::GetEntityClientState(), channel::ClientState::GetWorldCID(), channel::StatusEffectChange::IsConstant, mServer, mStatusEffectTokusei, mTimedTokusei, mTimedTokuseiEntities, mTimeLock, RecalcCostAdjustments(), and channel::state().
std::unordered_map< int32_t, bool > TokuseiManager::RecalculateParty (const std::shared_ptr< objects::Party > & party)
Recalculate the tokusei effects for all entities in a party on the channel.
Parameters
party Pointer to the party which will have its entities recalculated
Returns
Map of entity IDs to a true value if they have had their stats recalculated or false if only their tokusei sets and triggers were updated
Definition at line 962 of file TokuseiManager.cpp.
References channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), channel::ClientState::GetEntityClientState(), Recalculate(), and channel::state().
void TokuseiManager::RemoveTrackingEntities (int32_t worldCID)
Unregister the world CID of a character that may have had time restricted tokusei associated to one or more entity.
Call this any time a player logs off just in case.
Parameters
worldCID World CID associated to a character
Definition at line 2074 of file TokuseiManager.cpp.
References mTimedTokuseiEntities, and mTimeLock.
void TokuseiManager::SendCostAdjustments (int32_t entityID, const std::shared_ptr< ChannelClientConnection > & client)
Send skill cost adjustments from tokusei for the specified entity to the client.
Parameters
entityID ID of the entity with cost adjustments
client Pointer to the client connection
Definition at line 2130 of file TokuseiManager.cpp.
References channel::ClientState::GetCostAdjustments(), and channel::state().
Referenced by RecalcCostAdjustments().
void TokuseiManager::SendCostAdjustments (int32_t entityID, std::list< std::shared_ptr< objects::ClientCostAdjustment >> & adjustments, const std::shared_ptr< ChannelClientConnection > & client) private
Send skill cost adjustments from tokusei for the specified entity to the client.
Parameters
entityID ID of the entity with cost adjustments
adjustments List of adjustments to send to the client
client Pointer to the client connection
Definition at line 2339 of file TokuseiManager.cpp.
References libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteU32Little(), and libcomp::Packet::WriteU8().
void TokuseiManager::UpdateDiasporaMinibossCount (const std::shared_ptr< Zone > & zone)
Update all entities affected by the DIASPORA_MINIBOSS_COUNT tokusei condition in the supplied zone.
Parameters
zone Pointer to the zone that was updated
Definition at line 2141 of file TokuseiManager.cpp.
References Recalculate().
void TokuseiManager::UpdateMovementDecay (const std::shared_ptr< ChannelClientConnection > & client, float distance)
Lower durability on all movement durability decay equipment.
Parameters
client Pointer to the client connection
distance Movement distance delta used to calculate how much the durability will lower by
Definition at line 2080 of file TokuseiManager.cpp.
References channel::ClientState::GetCharacterState(), mMoveDecayTokusei, mServer, and channel::state().
Member Data Documentation
std::set<int32_t> channel::TokuseiManager::mCostAdjustmentTokusei private
Set of all tokusei with at least one cost adjustment aspect.
Definition at line 357 of file TokuseiManager.h.
Referenced by Initialize(), and RecalcCostAdjustments().
std::set<int32_t> channel::TokuseiManager::mMoveDecayTokusei private
Set of all tokusei with at least one movement decay aspect.
Definition at line 360 of file TokuseiManager.h.
Referenced by Initialize(), and UpdateMovementDecay().
std::weak_ptr<ChannelServer> channel::TokuseiManager::mServer private
Pointer to the channel server.
Definition at line 366 of file TokuseiManager.h.
Referenced by DeadTokuseiDisabled(), EvaluateTokuseiCondition(), GatherTimedTokusei(), GetAspectMap(), GetAspectSum(), GetAspectValueList(), GetDirectTokusei(), Initialize(), RecalcCostAdjustments(), RecalcTimedTokusei(), Recalculate(), and UpdateMovementDecay().
std::unordered_map<uint32_t, std::set<int32_t> > channel::TokuseiManager::mStatusEffectTokusei private
Quick access mapping of constant status effect IDs to their source tokusei IDs.
Definition at line 345 of file TokuseiManager.h.
Referenced by Initialize(), and Recalculate().
std::unordered_map<int32_t, bool> channel::TokuseiManager::mTimedTokusei private
Map of all tokusei effect IDs that have a time restriction to a boolean "active" indicator.
Definition at line 349 of file TokuseiManager.h.
Referenced by EvaluateTokuseiCondition(), GatherTimedTokusei(), RecalcTimedTokusei(), and Recalculate().
std::unordered_map<int32_t, std::set<int32_t> > channel::TokuseiManager::mTimedTokuseiEntities private
Map of world CIDs to the set of related time restricted tokusei.
This set is updated entity direct tokusei only and does not require that the effect is ultimately marked as effective.
Definition at line 354 of file TokuseiManager.h.
Referenced by RecalcTimedTokusei(), Recalculate(), and RemoveTrackingEntities().
std::mutex channel::TokuseiManager::mTimeLock private
Server lock for time calculation.
Definition at line 363 of file TokuseiManager.h.
Referenced by RecalcTimedTokusei(), Recalculate(), and RemoveTrackingEntities().
The documentation for this class was generated from the following files:
TokuseiManager.h
TokuseiManager.cpp