COMP_hack: channel::Zone Class Reference
channel::Zone Class Reference
Represents a server zone containing client connections, objects, enemies, etc.
#include <Zone.h>
Public Member Functions
Zone (uint32_t id, const std::shared_ptr< objects::ServerZone > &definition)
Create a new zone.
~Zone ()
Clean up the zone.
void AddAlly (const std::shared_ptr< AllyState > &ally, uint64_t staggerTime=0)
Add an ally to the zone.
void AddBase (const std::shared_ptr< objects::EntityStateObject > &base)
Add a special zone base base to the zone.
void AddBazaar (const std::shared_ptr< BazaarState > &bazaar)
Add a bazaar to the zone.
bool AddConnection (const std::shared_ptr< ChannelClientConnection > &client)
Add a client connection to the zone and register its world CID.
void AddCultureMachine (const std::shared_ptr< CultureMachineState > &machine)
Add a culture machine to the zone.
void AddEnemy (const std::shared_ptr< EnemyState > &enemy, uint64_t staggerTime=0)
Add an enemy to the zone.
void AddLootBox (const std::shared_ptr< LootBoxState > &box, uint32_t bossGroupID=0)
Add a loot body to the zone.
void AddNPC (const std::shared_ptr< NPCState > &npc)
Add an NPC to the zone.
void AddObject (const std::shared_ptr< ServerObjectState > &object)
Add an object to the zone.
void AddPlasma (const std::shared_ptr< PlasmaState > &plasma)
Add a plasma grouping to the zone.
bool ClaimBossBox (int32_t id, int32_t looterID)
Mark a boss box as belonging to the specified entity if the box is not already claimed and the entity has not already claimed the box.
void Cleanup ()
Perform pre-deletion cleanup actions.
bool Collides (const Line &path, Point &point, Line &surface, std::shared_ptr< ZoneShape > &shape) const
Determines if the supplied path collides with anything in the zone's geometry.
bool Collides (const Line &path, Point &point) const
Determines if the supplied path collides with anythin in the zone's geometry.
void CreateEncounter (const std::list< std::shared_ptr< ActiveEntityState >> &entities, bool staggerSpawn, const std::list< std::shared_ptr< objects::Action >> &defeatActions)
Create an encounter from a group of entities and register them with the zone.
bool DiasporaMiniBossUpdated ()
Determine if the Diaspora mini-bosses for this zone have updated since the last time this function has been called.
bool EnableDisableSpawnGroup (uint32_t spawnGroupID, bool enable)
Enable or disable the supplied spawn group and also disable (or enable) any affected spawn location groups.
bool EncounterDefeated (uint32_t encounterID, std::list< std::shared_ptr< objects::Action >> &defeatActions)
Determine if an entity encounter has been defeated and clean up the encounter information for the zone.
const std::list
< std::shared_ptr
< ActiveEntityState > > GetActiveEntities ()
Get all active entities in the zone.
const std::list
< std::shared_ptr
< ActiveEntityState > > GetActiveEntitiesInRadius (float x, float y, double radius, bool useHitbox=false)
Get all active entities in the zone within a supplied radius.
const std::shared_ptr
< ActiveEntityState > GetActiveEntity (int32_t entityID)
Get an active entity in the zone by ID.
std::shared_ptr
< objects::EntityStateObject > GetActor (int32_t actorID)
Get an entity instance with a specified actor ID.
const std::list
< std::shared_ptr< AllyState > > GetAllies () const
Get all ally instances in the zone.
std::shared_ptr< AllyState > GetAlly (int32_t id)
Get an ally instance by it's ID.
std::set< int8_t > GetBaseRestrictedActionTypes ()
Get the set of all player action types restricted by uncaptured bases in the zone.
std::shared_ptr< BazaarState > GetBazaar (int32_t id)
Get a bazaar instance by it's ID.
const std::list
< std::shared_ptr< BazaarState > > GetBazaars () const
Get all bazaar instances in the zone.
const std::list
< std::shared_ptr< EnemyState > > GetBosses ()
Get all boss enemy instances in the zone.
std::list< std::shared_ptr
< ChannelClientConnection > > GetConnectionList ()
Get all client connections in the zone as a list.
std::unordered_map< int32_t,
std::shared_ptr
< ChannelClientConnection > > GetConnections ()
Get all client connections in the zone mapped by world CID.
std::shared_ptr
< CultureMachineState > GetCultureMachine (int32_t id)
Get a culture machine instance by it's ID.
const std::unordered_map
< uint32_t, std::shared_ptr
< CultureMachineState > > GetCultureMachines () const
Get all culture machine instances in the zone.
uint32_t GetDefinitionID ()
Get the defintion ID of the zone.
std::set< int32_t > GetDespawnEntities ()
Get the IDs of all entities in the zone marked for despawn.
std::shared_ptr
< DiasporaBaseState > GetDiasporaBase (int32_t id)
Get a Diaspora base instance by it's ID.
const std::list
< std::shared_ptr
< DiasporaBaseState > > GetDiasporaBases () const
Get all Diaspora base instances in the zone.
std::pair< uint8_t, uint8_t > GetDiasporaMiniBossCount ()
Get the number of living Diaspora base bound miniboss spawn location group encounters and maximum count for the phase.
std::set< uint32_t > GetDisabledSpawnGroups ()
Get all spawn groups in this zone that have been marked as disabled either due to time restrictions or manually.
const std::shared_ptr< DynamicMap > GetDynamicMap () const
Get the dynamic map information bound to the zone.
uint32_t GetDynamicMapID ()
Get the defintion dynamic map ID of the zone.
const std::list
< std::shared_ptr< EnemyState > > GetEnemies () const
Get all enemy instances in the zone.
std::list< std::shared_ptr
< ActiveEntityState > > GetEnemiesAndAllies (bool includeStaggered=false)
Get all enemy and ally instances in the zone.
std::shared_ptr< EnemyState > GetEnemy (int32_t id)
Get an enemy instance by it's ID.
std::shared_ptr
< objects::EntityStateObject > GetEntity (int32_t id)
Get an entity instance by it's ID.
bool GetFlagState (int32_t key, int32_t &value, int32_t worldCID)
Get the state of a zone flag.
std::unordered_map< int32_t,
std::unordered_map< int32_t,
int32_t > > GetFlagStates ()
Return the flag states for the zone.
int32_t GetFlagStateValue (int32_t key, int32_t nullDefault, int32_t worldCID)
Get the state of a zone flag, returning the null default if it does not exist.
const std::shared_ptr
< ZoneGeometry > GetGeometry () const
Get the geometry information bound to the zone.
std::shared_ptr< ZoneInstance > GetInstance () const
Get the instance the zone belongs to if one exists.
uint32_t GetInstanceID ()
Get the assigned instance ID of the zone or zero if it is not part of an instance.
InstanceType_t GetInstanceType () const
Get the instance variant the zone belongs to if one exists.
std::shared_ptr< LootBoxState > GetLootBox (int32_t id)
Get a loot box instance by it's ID.
const std::list
< std::shared_ptr
< LootBoxState > > GetLootBoxes () const
Get all loot box instances in the zone.
uint32_t GetNextRentalExpiration () const
Get the next entity rental expiration in system time.
std::shared_ptr< NPCState > GetNPC (int32_t id)
Get an NPC instance by it's ID.
const std::list
< std::shared_ptr< NPCState > > GetNPCs () const
Get all NPC instances in the zone.
std::shared_ptr< PlasmaState > GetPlasma (uint32_t id)
Get a plasma instance by it's definition ID.
const std::unordered_map
< uint32_t, std::shared_ptr
< PlasmaState > > GetPlasma () const
Get all plasma instances in the zone.
std::shared_ptr< PvPBaseState > GetPvPBase (int32_t id)
Get a PvP base instance by it's ID.
const std::list
< std::shared_ptr
< PvPBaseState > > GetPvPBases () const
Get all PvP base instances in the zone.
std::set< uint32_t > GetRespawnLocations (uint64_t now)
Get the set of spawn location groups that need to be respawned.
std::shared_ptr
< ServerObjectState > GetServerObject (int32_t id)
Get an object instance by it's ID.
const std::list
< std::shared_ptr
< ServerObjectState > > GetServerObjects () const
Get all object instances in the zone.
std::shared_ptr< objects::UBMatch > GetUBMatch () const
Get the current UBMatch associated to the zone if one exists.
std::list< std::shared_ptr
< ActiveEntityState > > GetUpdatedStatusEffectEntities (uint32_t now)
Get the list of entities that have had registered status effect event times that have passed since the specified time.
float GetXPMultiplier ()
Get the XP multiplier for the zone combined with any variant specific boosts.
bool GroupHasSpawned (uint32_t groupID, bool isLocation, bool aliveOnly)
Check if a spawn group/location group has ever been spawned in this zone or is currently spawned.
bool HasRespawns () const
Check if the zone has respawnable entities associated to it.
bool HasStaggeredSpawns (uint64_t now)
Check if the zone has staggered spawns ready.
uint16_t IncreasePvPBaseBonus (int32_t baseID, uint64_t occupyStartTime)
Update the bonus count on a PvP base.
void MarkDespawn (int32_t entityID)
Mark an entity for despawn in the zone.
bool MinionSpawned (const std::shared_ptr< ActiveEntityState > &eState, uint32_t slgID=0)
Determine if a minion has been spawned in the zone with an optional spawn location group.
int32_t OccupyPvPBase (int32_t baseID, int32_t occupierID, bool complete, uint64_t occupyStartTime=0)
Update the occupier (or owner) information of a PvP base in the zone.
void RemoveConnection (const std::shared_ptr< ChannelClientConnection > &client)
Remove a client connection from the zone and unregister its world CID.
void RemoveEntity (int32_t entityID, uint32_t spawnDelay=0)
Remove an entity from the zone.
void SetDynamicMap (const std::shared_ptr< DynamicMap > &map)
Set the dynamic map information bound to the zone.
void SetFlagState (int32_t key, int32_t value, int32_t worldCID)
Set the state of a zone flag.
void SetGeometry (const std::shared_ptr< ZoneGeometry > &geometry)
Set the geometry information bound to the zone.
void SetInstance (const std::shared_ptr< ZoneInstance > &instance)
Set the instance the zone belongs to.
uint32_t SetNextRentalExpiration ()
Set the next entity rental expiration in system time from the zone's bazaar markets and culture machines.
void SetNextStatusEffectTime (uint32_t time, int32_t entityID)
Set the next status effect event time associated to an entity in the zone.
bool SpawnedAtSpot (uint32_t spotID)
Check if an entity has ever spawned at the specified spot.
std::shared_ptr
< ActiveEntityState > StartStopCombat (int32_t entityID, uint64_t timeout, bool checkBefore=false)
Add or remove the supplied entity as a combatant in the zone.
std::unordered_map< size_t,
std::shared_ptr< objects::Loot > > TakeLoot (std::shared_ptr< objects::LootBox > lBox, std::set< int8_t > slots, size_t freeSlots, std::unordered_map< uint32_t, uint16_t > stacksFree={})
Take loot out of the specified loot box.
std::list< std::shared_ptr
< ActiveEntityState > > UpdateStaggeredSpawns (uint64_t now)
Get enemies or allies that should spawn past the supplied server time.
bool UpdateTimedSpawns (const WorldClock &clock, bool initializing=false)
Update all spawn groups and plasma states that have time restrictions based upon the supplie world clock time.
Static Public Member Functions
static bool TimeRestrictionActive (const WorldClock &clock, const std::shared_ptr< objects::SpawnRestriction > &restriction)
Determine based on the supplied clock time if a spawn restriction is active or not.
Private Member Functions
void AddSpawnedEntity (const std::shared_ptr< ActiveEntityState > &state, uint32_t spotID, uint32_t sgID, uint32_t slgID)
Register a new spawned entity to the zone stored spots and group field.
bool DisableSpawnGroups (const std::set< uint32_t > &spawnGroupIDs, bool initializing, bool deactivate)
Disable a set of spawn groups and update any spawn location groups that now have all groups disabled.
void EnableSpawnGroups (const std::set< uint32_t > &spawnGroupIDs, bool initializing, bool activate)
Enable a set of spawn groups and update any spawn location groups that previously had all groups disabled.
void RegisterEntityState (const std::shared_ptr< objects::EntityStateObject > &state)
Register an entity as one that currently exists in the zone.
void UnregisterEntityState (int32_t entityID)
Remove an entity that no longer exists in the zone by its ID.
Private Attributes
std::list< std::shared_ptr
< ActiveEntityState > > mActiveEntities
List of active entities in the zone.
std::unordered_map< int32_t,
std::shared_ptr
< objects::EntityStateObject > > mActors
Map of entities in the zone with a specified actor ID for used when referencing in actions or events.
std::unordered_map< int32_t,
std::shared_ptr
< objects::EntityStateObject > > mAllEntities
Map of entities in the zone by their ID.
std::list< std::shared_ptr
< AllyState > > mAllies
List of pointers to allies instantiated for the zone.
std::list< std::shared_ptr
< objects::EntityStateObject > > mBases
List of pointers to special zone bases instantiated for the zone.
std::list< std::shared_ptr
< BazaarState > > mBazaars
List of pointers to bazaars instantiated for the zone.
std::unordered_map< uint32_t,
std::set< int32_t > > mBossBoxGroups
Map of boss box group IDs to the boxes included.
std::unordered_map< uint32_t,
std::set< int32_t > > mBossBoxOwners
Map of boss box group IDs to entities that have claimed part of the group.
std::set< int32_t > mBossIDs
Set of all entity IDs for bosses in the zone.
std::unordered_map< int32_t,
std::shared_ptr
< ChannelClientConnection > > mConnections
Map of world CIDs to client connections.
std::unordered_map< uint32_t,
std::shared_ptr
< CultureMachineState > > mCultureMachines
Map of culture machine states by definition ID.
std::set< uint32_t > mDeactivatedSpawnGroups
Set of spawn group IDs that have been deactivated and will not re-enable until they have been activated again.
bool mDiasporaMiniBossUpdated
Flag indicating that Diaspora mini-boss spawn location groups have updated since the last call to DiasporaMiniBossUpdated.
std::set< uint32_t > mDisabledSpawnGroups
Set of spawn group IDs that have been disabled.
std::set< uint32_t > mDisabledSpawnLocationGroups
Set of spawn location group IDs where all associated groups are disabled.
std::shared_ptr< DynamicMap > mDynamicMap
Dynamic map information bound to the zone.
std::unordered_map< uint32_t,
std::list< std::shared_ptr
< objects::Action > > > mEncounterDefeatActions
Map of encounter IDs to defeat actions assigned when they were created.
std::unordered_map< uint32_t,
std::set< std::shared_ptr
< ActiveEntityState > > > mEncounters
Map of encounter IDs to entities that belong to that encounter.
std::list< std::shared_ptr
< EnemyState > > mEnemies
List of pointers to enemies instantiated for the zone.
std::unordered_map< int32_t,
std::unordered_map< int32_t,
int32_t > > mFlagStates
General use flags and associated values used for event sequences etc keyed on 0 for all characters or world CID if for a specific one.
std::shared_ptr< ZoneGeometry > mGeometry
Geometry information bound to the zone.
bool mHasRespawns
Quick reference flag to determine if the zone has respwa.
std::mutex mLock
Server lock for shared resources.
std::list< std::shared_ptr
< LootBoxState > > mLootBoxes
List of pointers to lootable boxes for the zone.
uint32_t mNextEncounterID
Next ID to use for encounters registered for the zone.
std::map< uint32_t, std::set
< int32_t > > mNextEntityStatusTimes
Map of system times to active entities with status effects that need handling at that time.
uint32_t mNextRentalExpiration
Next entity rental expiration time that will occur.
std::list< std::shared_ptr
< NPCState > > mNPCs
List of pointers to NPCs instantiated for the zone.
std::list< std::shared_ptr
< ServerObjectState > > mObjects
List of pointers to objects instantiated for the zone.
std::set< int32_t > mPendingDespawnEntities
Set of entity IDs waiting to despawn.
std::unordered_map< uint32_t,
std::shared_ptr< PlasmaState > > mPlasma
Map of plasma states by definition ID.
std::map< uint64_t, std::set
< uint32_t > > mRespawnTimes
Map of server times to spawn location group IDs that need to be respawned at that time.
std::unordered_map< uint32_t,
std::list< std::shared_ptr
< ActiveEntityState > > > mSpawnGroups
Map of spawn group IDs to pointers to entities created from that group.
std::unordered_map< uint32_t,
std::list< std::shared_ptr
< ActiveEntityState > > > mSpawnLocationGroups
Map of spawn location group IDs to pointers to entities created from the groups.
std::set< uint32_t > mSpotsSpawned
Set of all spot IDs that have had an enemy spawned.
std::map< uint64_t, std::list
< std::shared_ptr
< ActiveEntityState > > > mStaggeredSpawns
Map of server times to enemies or allies that exist in the zone but will not actually spawn until the time passes.
std::shared_ptr< ZoneInstance > mZoneInstance
Zone instance pointer for non-global zones.
Detailed Description
Represents a server zone containing client connections, objects, enemies, etc.
Definition at line 82 of file Zone.h.
Constructor & Destructor Documentation
Zone::Zone (uint32_t id, const std::shared_ptr< objects::ServerZone > & definition)
Create a new zone.
Parameters
id Unique server ID of the zone
definition Pointer to the ServerZone definition
Definition at line 132 of file Zone.cpp.
References DisableSpawnGroups(), and mHasRespawns.
Zone::~Zone ()
Clean up the zone.
Definition at line 171 of file Zone.cpp.
Member Function Documentation
void Zone::AddAlly (const std::shared_ptr< AllyState > & ally, uint64_t staggerTime = 0)
Add an ally to the zone.
Parameters
ally Pointer to the ally to add
staggerTime Optional server time specifying when the ally should be spawned into the zone. If 0, it will spawn immediately.
Definition at line 496 of file Zone.cpp.
References AddSpawnedEntity(), mAllies, mLock, mStaggeredSpawns, and RegisterEntityState().
Referenced by CreateEncounter().
void Zone::AddBase (const std::shared_ptr< objects::EntityStateObject > & base)
Add a special zone base base to the zone.
Parameters
base Pointer to the base to add
Definition at line 521 of file Zone.cpp.
References mBases, and RegisterEntityState().
void Zone::AddBazaar (const std::shared_ptr< BazaarState > & bazaar)
Add a bazaar to the zone.
Parameters
bazaar Pointer to the bazaar to add
Definition at line 527 of file Zone.cpp.
References mBazaars, and RegisterEntityState().
bool Zone::AddConnection (const std::shared_ptr< ChannelClientConnection > & client)
Add a client connection to the zone and register its world CID.
Parameters
client Pointer to a client connection to add
Returns
true if the connection was added without error
Definition at line 239 of file Zone.cpp.
References channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), channel::ClientState::GetWorldCID(), mActiveEntities, mConnections, mLock, RegisterEntityState(), and channel::state().
void Zone::AddCultureMachine (const std::shared_ptr< CultureMachineState > & machine)
Add a culture machine to the zone.
Parameters
machine Pointer to the machine to add
Definition at line 533 of file Zone.cpp.
References mCultureMachines, and RegisterEntityState().
void Zone::AddEnemy (const std::shared_ptr< EnemyState > & enemy, uint64_t staggerTime = 0)
Add an enemy to the zone.
Parameters
enemy Pointer to the enemy to add
staggerTime Optional server time specifying when the enemy should be spawned into the zone. If 0, it will spawn immediately.
Definition at line 544 of file Zone.cpp.
References AddSpawnedEntity(), GetUBMatch(), mBossIDs, mEnemies, mLock, mStaggeredSpawns, and RegisterEntityState().
Referenced by CreateEncounter().
void Zone::AddLootBox (const std::shared_ptr< LootBoxState > & box, uint32_t bossGroupID = 0)
Add a loot body to the zone.
Parameters
box Pointer to the loot box to add
bossGroupID Optional ID of the group to bind looting to for boss boxes
Definition at line 583 of file Zone.cpp.
References mBossBoxGroups, mLock, mLootBoxes, and RegisterEntityState().
void Zone::AddNPC (const std::shared_ptr< NPCState > & npc)
Add an NPC to the zone.
Parameters
npc Pointer to the NPC to add
Definition at line 599 of file Zone.cpp.
References mActors, mNPCs, and RegisterEntityState().
void Zone::AddObject (const std::shared_ptr< ServerObjectState > & object)
Add an object to the zone.
Parameters
object Pointer to the object to add
Definition at line 611 of file Zone.cpp.
References mActors, mObjects, and RegisterEntityState().
void Zone::AddPlasma (const std::shared_ptr< PlasmaState > & plasma)
Add a plasma grouping to the zone.
Parameters
plasma Pointer to the plasma to add
Definition at line 623 of file Zone.cpp.
References mPlasma, and RegisterEntityState().
void Zone::AddSpawnedEntity (const std::shared_ptr< ActiveEntityState > & state, uint32_t spotID, uint32_t sgID, uint32_t slgID) private
Register a new spawned entity to the zone stored spots and group field.
Parameters
state Pointer to the state of the spawned entity
spotID Spot ID being spawned into
sgID Spawn group ID being spawned from
slgID Spawn location group ID being spawned from
Definition at line 1889 of file Zone.cpp.
References GetDiasporaBases(), mActiveEntities, mDiasporaMiniBossUpdated, mRespawnTimes, mSpawnGroups, mSpawnLocationGroups, and mSpotsSpawned.
Referenced by AddAlly(), and AddEnemy().
bool Zone::ClaimBossBox (int32_t id, int32_t looterID)
Mark a boss box as belonging to the specified entity if the box is not already claimed and the entity has not already claimed the box.
Parameters
id Instance ID of the boss box.
looterID ID of the entity claiming the box
Returns
true if the box was claimed, false if it was not
Definition at line 823 of file Zone.cpp.
References GetLootBox(), mBossBoxGroups, mBossBoxOwners, and mLock.
void Zone::Cleanup ()
Perform pre-deletion cleanup actions.
Definition at line 1738 of file Zone.cpp.
References mActors, mAllEntities, mAllies, mBases, mBazaars, mBossIDs, mCultureMachines, mEncounterDefeatActions, mEncounters, mEnemies, mLock, mNPCs, mObjects, mPlasma, mSpawnGroups, mSpawnLocationGroups, mStaggeredSpawns, mZoneInstance, and channel::ActiveEntityState::SetZone().
bool Zone::Collides (const Line & path, Point & point, Line & surface, std::shared_ptr< ZoneShape > & shape) const
Determines if the supplied path collides with anything in the zone's geometry.
Parameters
path Line representing a path
point Output parameter to set where the intersection occurs
surface Output parameter to return the first line to be intersected by the path
shape Output parameter to return the first shape the path will collide with. This will always be the shape the surface belongs to
Returns
true if the line collides, false if it does not
Definition at line 1724 of file Zone.cpp.
References mGeometry.
Referenced by Collides().
bool Zone::Collides (const Line & path, Point & point) const
Determines if the supplied path collides with anythin in the zone's geometry.
Parameters
path Line representing a path
point Output parameter to set where the intersection occurs
Returns
true if the line collides, false if it does not
Definition at line 1731 of file Zone.cpp.
References Collides().
void Zone::CreateEncounter (const std::list< std::shared_ptr< ActiveEntityState >> & entities, bool staggerSpawn, const std::list< std::shared_ptr< objects::Action >> & defeatActions)
Create an encounter from a group of entities and register them with the zone.
DefeatActions will be retained until a check via EncounterDefeated is called.
Parameters
entities List of the entities to add to the encounter
staggerSpawn If true spawns will appear with a spawn stagger, if false they will all appear at once
defeatActions Optional list of defeat actions associted with the encounter. These actions will be returned when calling EncounterDefeated
Definition at line 1167 of file Zone.cpp.
References AddAlly(), AddEnemy(), channel::ChannelServer::GetServerTime(), mEncounterDefeatActions, mEncounters, mLock, and mNextEncounterID.
bool Zone::DiasporaMiniBossUpdated ()
Determine if the Diaspora mini-bosses for this zone have updated since the last time this function has been called.
Reset the flag if one has occurred.
Returns
true if and update has occurred, false one has not
Definition at line 1662 of file Zone.cpp.
References mDiasporaMiniBossUpdated, and mLock.
bool Zone::DisableSpawnGroups (const std::set< uint32_t > & spawnGroupIDs, bool initializing, bool deactivate) private
Disable a set of spawn groups and update any spawn location groups that now have all groups disabled.
Parameters
spawnGroupIDs Set of spawn group IDs to disable
initializing true if the zone is being setup, defaults to false
deactivate If true the group will be deactivated as well and cannot be re-enabled until it is reactivated
Returns
true if any enemies must be despawned after being disabled
Definition at line 2014 of file Zone.cpp.
References libcomp::String::Arg(), GetDefinitionID(), mDeactivatedSpawnGroups, mDisabledSpawnGroups, mDisabledSpawnLocationGroups, mPendingDespawnEntities, mRespawnTimes, and mSpawnGroups.
Referenced by EnableDisableSpawnGroup(), UpdateTimedSpawns(), and Zone().
bool Zone::EnableDisableSpawnGroup (uint32_t spawnGroupID, bool enable)
Enable or disable the supplied spawn group and also disable (or enable) any affected spawn location groups.
Parameters
spawnGroupID Spawn group ID to adjust
enable true if the group should be enabled, false if it should be disabled
Returns
true if any updates were performed that the zone manager needs to react to, false if none occurred or they can be processed later
Definition at line 1346 of file Zone.cpp.
References DisableSpawnGroups(), EnableSpawnGroups(), and mLock.
void Zone::EnableSpawnGroups (const std::set< uint32_t > & spawnGroupIDs, bool initializing, bool activate) private
Enable a set of spawn groups and update any spawn location groups that previously had all groups disabled.
Parameters
spawnGroupIDs Set of spawn group IDs to enable
initializing true if the zone is being setup, defaults to false
activate If false and the group is deactivated, it will not be re-enabled. If true, the group will be re-enabled no matter what.
Definition at line 1942 of file Zone.cpp.
References libcomp::String::Arg(), GetDefinitionID(), channel::ChannelServer::GetServerTime(), mDeactivatedSpawnGroups, mDisabledSpawnGroups, mDisabledSpawnLocationGroups, and mRespawnTimes.
Referenced by EnableDisableSpawnGroup(), and UpdateTimedSpawns().
bool Zone::EncounterDefeated (uint32_t encounterID, std::list< std::shared_ptr< objects::Action >> & defeatActions)
Determine if an entity encounter has been defeated and clean up the encounter information for the zone.
Parameters
encounterID ID of the encounter
defeatActions Output parameter to contain the encounter's defeat actions to fire if the encounter is defeated
Returns
true if the encounter has been defeated, false if at least one entity from the group is still alive
Definition at line 1223 of file Zone.cpp.
References mEncounterDefeatActions, mEncounters, and mLock.
const std::list< std::shared_ptr< ActiveEntityState > > Zone::GetActiveEntities ()
Get all active entities in the zone.
Returns
List of pointers to all active entities
Definition at line 651 of file Zone.cpp.
References mActiveEntities.
Referenced by GetActiveEntitiesInRadius().
const std::list< std::shared_ptr< ActiveEntityState > > Zone::GetActiveEntitiesInRadius (float x, float y, double radius, bool useHitbox = false)
Get all active entities in the zone within a supplied radius.
Parameters
x X coordinate of the center of the radius
y Y coordinate of the center of the radius
radius Radius to check for entities
useHitbox If true, the entities' hitboxes will be used to determine if they are in the radius, even if the center point is not
Returns
List of pointers to active entities in the radius
Definition at line 657 of file Zone.cpp.
References GetActiveEntities(), and channel::ChannelServer::GetServerTime().
const std::shared_ptr< ActiveEntityState > Zone::GetActiveEntity (int32_t entityID)
Get an active entity in the zone by ID.
Parameters
entityID ID of the active entity to retrieve
Returns
Pointer to the active entity or null if does not exist or is not active
Definition at line 646 of file Zone.cpp.
References GetEntity().
Referenced by MinionSpawned().
std::shared_ptr< objects::EntityStateObject > Zone::GetActor (int32_t actorID)
Get an entity instance with a specified actor ID.
Parameters
actorID Actor ID of the entity.
Returns
Pointer to the entity instance.
Definition at line 1042 of file Zone.cpp.
References mActors.
const std::list< std::shared_ptr< AllyState > > Zone::GetAllies () const
Get all ally instances in the zone.
Returns
List of all ally instances in the zone
Definition at line 696 of file Zone.cpp.
References mAllies.
Referenced by GetEnemiesAndAllies().
std::shared_ptr< AllyState > Zone::GetAlly (int32_t id)
Get an ally instance by it's ID.
Parameters
id Instance ID of the ally.
Returns
Pointer to the ally instance.
Definition at line 691 of file Zone.cpp.
References GetEntity().
std::set< int8_t > Zone::GetBaseRestrictedActionTypes ()
Get the set of all player action types restricted by uncaptured bases in the zone.
Returns
Set of restricted action types (and -1 for all items which is not an action type)
Definition at line 1605 of file Zone.cpp.
References GetDiasporaBases().
std::shared_ptr< BazaarState > Zone::GetBazaar (int32_t id)
Get a bazaar instance by it's ID.
Parameters
id Instance ID of the bazaar.
Returns
Pointer to the bazaar instance.
Definition at line 701 of file Zone.cpp.
References GetEntity().
const std::list< std::shared_ptr< BazaarState > > Zone::GetBazaars () const
Get all bazaar instances in the zone.
Returns
List of all bazaar instances in the zone
Definition at line 706 of file Zone.cpp.
References mBazaars.
const std::list< std::shared_ptr< EnemyState > > Zone::GetBosses ()
Get all boss enemy instances in the zone.
Returns
List of all boss enemy instances in the zone
Definition at line 753 of file Zone.cpp.
References GetEnemy(), and mBossIDs.
std::list< std::shared_ptr< ChannelClientConnection > > Zone::GetConnectionList ()
Get all client connections in the zone as a list.
Returns
List of all client connections in the zone
Definition at line 635 of file Zone.cpp.
References mConnections, and mLock.
std::unordered_map< int32_t, std::shared_ptr< ChannelClientConnection > > Zone::GetConnections ()
Get all client connections in the zone mapped by world CID.
Returns
Map of all client connections in the zone by world CID
Definition at line 630 of file Zone.cpp.
References mConnections.
std::shared_ptr< CultureMachineState > Zone::GetCultureMachine (int32_t id)
Get a culture machine instance by it's ID.
Parameters
id Instance ID of the culture machine.
Returns
Pointer to the culture machine instance.
Definition at line 711 of file Zone.cpp.
References GetEntity().
const std::unordered_map< uint32_t, std::shared_ptr< CultureMachineState > > Zone::GetCultureMachines () const
Get all culture machine instances in the zone.
Returns
List of all culture machine instances in the zone
Definition at line 717 of file Zone.cpp.
References mCultureMachines.
uint32_t Zone::GetDefinitionID ()
Get the defintion ID of the zone.
Returns
Defintion ID of the zone
Definition at line 175 of file Zone.cpp.
Referenced by DisableSpawnGroups(), and EnableSpawnGroups().
std::set< int32_t > Zone::GetDespawnEntities ()
Get the IDs of all entities in the zone marked for despawn.
Returns
Set of all entity IDs to despawn
Definition at line 1259 of file Zone.cpp.
References mLock, and mPendingDespawnEntities.
std::shared_ptr< DiasporaBaseState > Zone::GetDiasporaBase (int32_t id)
Get a Diaspora base instance by it's ID.
Parameters
id Instance ID of the Diaspora base.
Returns
Pointer to the Diaspora base instance.
Definition at line 722 of file Zone.cpp.
References GetEntity().
const std::list< std::shared_ptr< DiasporaBaseState > > Zone::GetDiasporaBases () const
Get all Diaspora base instances in the zone.
Returns
List of all Diaspora base instances in the zone
Definition at line 728 of file Zone.cpp.
References mBases.
Referenced by AddSpawnedEntity(), GetBaseRestrictedActionTypes(), GetDiasporaMiniBossCount(), and RemoveEntity().
std::pair< uint8_t, uint8_t > Zone::GetDiasporaMiniBossCount ()
Get the number of living Diaspora base bound miniboss spawn location group encounters and maximum count for the phase.
Returns
Number of living mini-boss encounters and maximum count for the current phase
Definition at line 1631 of file Zone.cpp.
References GetDiasporaBases(), and GroupHasSpawned().
std::set< uint32_t > Zone::GetDisabledSpawnGroups ()
Get all spawn groups in this zone that have been marked as disabled either due to time restrictions or manually.
Returns
Set of disabled spawn group IDs
Definition at line 1265 of file Zone.cpp.
References mDisabledSpawnGroups, and mLock.
const std::shared_ptr< DynamicMap > Zone::GetDynamicMap () const
Get the dynamic map information bound to the zone.
Returns
Dynamic map information bound to the zone
Definition at line 217 of file Zone.cpp.
References mDynamicMap.
uint32_t Zone::GetDynamicMapID ()
Get the defintion dynamic map ID of the zone.
Returns
Defintion dynamic map ID of the zone
Definition at line 180 of file Zone.cpp.
const std::list< std::shared_ptr< EnemyState > > Zone::GetEnemies () const
Get all enemy instances in the zone.
Returns
List of all enemy instances in the zone
Definition at line 748 of file Zone.cpp.
References mEnemies.
Referenced by GetEnemiesAndAllies().
std::list< std::shared_ptr< ActiveEntityState > > Zone::GetEnemiesAndAllies (bool includeStaggered = false)
Get all enemy and ally instances in the zone.
Parameters
includeStaggered Includes all entities pending spawn from being spawn staggered. Defaults to false.
Returns
List of all enemy and ally instances in the zone
Definition at line 771 of file Zone.cpp.
References GetAllies(), GetEnemies(), mAllies, mEnemies, mLock, and mStaggeredSpawns.
std::shared_ptr< EnemyState > Zone::GetEnemy (int32_t id)
Get an enemy instance by it's ID.
Parameters
id Instance ID of the enemy.
Returns
Pointer to the enemy instance.
Definition at line 743 of file Zone.cpp.
References GetEntity().
Referenced by GetBosses().
std::shared_ptr< objects::EntityStateObject > Zone::GetEntity (int32_t id)
Get an entity instance by it's ID.
Parameters
id Instance ID of the entity.
Returns
Pointer to the entity instance.
Definition at line 1029 of file Zone.cpp.
References mAllEntities, and mLock.
Referenced by GetActiveEntity(), GetAlly(), GetBazaar(), GetCultureMachine(), GetDiasporaBase(), GetEnemy(), GetLootBox(), GetNPC(), GetPvPBase(), GetServerObject(), and RemoveEntity().
bool Zone::GetFlagState (int32_t key, int32_t & value, int32_t worldCID)
Get the state of a zone flag.
Parameters
key Lookup key for the flag
value Output value for the flag if it exists
worldCID CID of the character the flag belongs to, 0 if it affects the entire instance
Returns
true if the flag exists, false if it does not
Definition at line 1508 of file Zone.cpp.
References mFlagStates, and mLock.
Referenced by GetFlagStateValue().
std::unordered_map< int32_t, std::unordered_map< int32_t, int32_t > > Zone::GetFlagStates ()
Return the flag states for the zone.
Returns
Flag states for the zone.
Definition at line 1531 of file Zone.cpp.
References mFlagStates, and mLock.
int32_t Zone::GetFlagStateValue (int32_t key, int32_t nullDefault, int32_t worldCID)
Get the state of a zone flag, returning the null default if it does not exist.
Parameters
key Lookup key for the flag
nullDefault Default value to return if the flag is not set
worldCID CID of the character the flag belongs to, 0 if it affects the entire instance
Returns
Value of the specified flag or the nullDefault value if it does not exist
Definition at line 1538 of file Zone.cpp.
References GetFlagState().
const std::shared_ptr< ZoneGeometry > Zone::GetGeometry () const
Get the geometry information bound to the zone.
Returns
Geometry information bound to the zone
Definition at line 191 of file Zone.cpp.
References mGeometry.
std::shared_ptr< ZoneInstance > Zone::GetInstance () const
Get the instance the zone belongs to if one exists.
Returns
Instance the zone belongs to
Definition at line 201 of file Zone.cpp.
References mZoneInstance.
Referenced by GetInstanceID().
uint32_t Zone::GetInstanceID ()
Get the assigned instance ID of the zone or zero if it is not part of an instance.
Returns
Instance ID of the zone
Definition at line 185 of file Zone.cpp.
References GetInstance().
InstanceType_t Zone::GetInstanceType () const
Get the instance variant the zone belongs to if one exists.
Returns
Instance variant the zone belongs to
Definition at line 206 of file Zone.cpp.
References mZoneInstance.
std::shared_ptr< LootBoxState > Zone::GetLootBox (int32_t id)
Get a loot box instance by it's ID.
Parameters
id Instance ID of the loot box.
Returns
Pointer to the loot box instance.
Definition at line 813 of file Zone.cpp.
References GetEntity().
Referenced by ClaimBossBox().
const std::list< std::shared_ptr< LootBoxState > > Zone::GetLootBoxes () const
Get all loot box instances in the zone.
Returns
List of all loot box instances in the zone
Definition at line 818 of file Zone.cpp.
References mLootBoxes.
uint32_t Zone::GetNextRentalExpiration () const
Get the next entity rental expiration in system time.
Returns
Next entity rental expiration in system time
Definition at line 1679 of file Zone.cpp.
References mNextRentalExpiration.
std::shared_ptr< NPCState > Zone::GetNPC (int32_t id)
Get an NPC instance by it's ID.
Parameters
id Instance ID of the NPC.
Returns
Pointer to the NPC instance.
Definition at line 1048 of file Zone.cpp.
References GetEntity().
const std::list< std::shared_ptr< NPCState > > Zone::GetNPCs () const
Get all NPC instances in the zone.
Returns
List of all NPC instances in the zone
Definition at line 974 of file Zone.cpp.
References mNPCs.
std::shared_ptr< PlasmaState > Zone::GetPlasma (uint32_t id)
Get a plasma instance by it's definition ID.
Parameters
id Definition ID of the plasma.
Returns
Pointer to the plasma instance.
Definition at line 979 of file Zone.cpp.
References mPlasma.
const std::unordered_map< uint32_t, std::shared_ptr< PlasmaState > > Zone::GetPlasma () const
Get all plasma instances in the zone.
Returns
List of all plasma instances in the zone
Definition at line 986 of file Zone.cpp.
References mPlasma.
std::shared_ptr< PvPBaseState > Zone::GetPvPBase (int32_t id)
Get a PvP base instance by it's ID.
Parameters
id Instance ID of the PvP base.
Returns
Pointer to the PvP base instance.
Definition at line 991 of file Zone.cpp.
References GetEntity().
Referenced by IncreasePvPBaseBonus(), and OccupyPvPBase().
const std::list< std::shared_ptr< PvPBaseState > > Zone::GetPvPBases () const
Get all PvP base instances in the zone.
Returns
List of all PvP base instances in the zone
Definition at line 996 of file Zone.cpp.
References mBases.
std::set< uint32_t > Zone::GetRespawnLocations (uint64_t now)
Get the set of spawn location groups that need to be respawned.
Parameters
now System time representing the current server time
Returns
Set of spawn location group IDs to respawn
Definition at line 1362 of file Zone.cpp.
References mLock, mRespawnTimes, and mSpawnLocationGroups.
std::shared_ptr< ServerObjectState > Zone::GetServerObject (int32_t id)
Get an object instance by it's ID.
Parameters
id Instance ID of the object.
Returns
Pointer to the object instance.
Definition at line 1053 of file Zone.cpp.
References GetEntity().
const std::list< std::shared_ptr< ServerObjectState > > Zone::GetServerObjects () const
Get all object instances in the zone.
Returns
List of all object instances in the zone
Definition at line 1011 of file Zone.cpp.
References mObjects.
std::shared_ptr< objects::UBMatch > Zone::GetUBMatch () const
Get the current UBMatch associated to the zone if one exists.
Returns
Pointer to the UBMatch or null if none exists
Definition at line 1674 of file Zone.cpp.
Referenced by AddEnemy().
std::list< std::shared_ptr< ActiveEntityState > > Zone::GetUpdatedStatusEffectEntities (uint32_t now)
Get the list of entities that have had registered status effect event times that have passed since the specified time.
Parameters
now System time representing the current server time
Returns
List of entities that have had registered status effect event times that have passed
Definition at line 1075 of file Zone.cpp.
References mAllEntities, mLock, and mNextEntityStatusTimes.
float Zone::GetXPMultiplier ()
Get the XP multiplier for the zone combined with any variant specific boosts.
Returns
XP multiplier for the zone
Definition at line 1556 of file Zone.cpp.
References mZoneInstance.
bool Zone::GroupHasSpawned (uint32_t groupID, bool isLocation, bool aliveOnly)
Check if a spawn group/location group has ever been spawned in this zone or is currently spawned.
Parameters
groupID Group ID of the spawn to check
aliveOnly Only count living entities in the group
Returns
true if the group has already been spawned or contains, a living entity, false otherwise
Definition at line 1107 of file Zone.cpp.
References mLock, mPendingDespawnEntities, mSpawnGroups, and mSpawnLocationGroups.
Referenced by GetDiasporaMiniBossCount().
bool Zone::HasRespawns () const
Check if the zone has respawnable entities associated to it.
Returns
true if the zone has respawnable entities associated to it
Definition at line 222 of file Zone.cpp.
References mHasRespawns.
bool Zone::HasStaggeredSpawns (uint64_t now)
Check if the zone has staggered spawns ready.
Parameters
now System time representing the current server time
Returns
true if the zone has staggered spawns ready
Definition at line 227 of file Zone.cpp.
References mLock, and mStaggeredSpawns.
uint16_t Zone::IncreasePvPBaseBonus (int32_t baseID, uint64_t occupyStartTime)
Update the bonus count on a PvP base.
Parameters
baseID Entity ID of the base in the zone
occupyStartTime Server timestamp of when the base was occupied. If this time does not match, the bonus will not update.
Returns
New bonus count or 0 if it did not update
Definition at line 953 of file Zone.cpp.
References GetPvPBase(), and mLock.
void Zone::MarkDespawn (int32_t entityID)
Mark an entity for despawn in the zone.
Once marked, it cannot be unmarked.
Parameters
entityID ID of the entity to mark for despawn
Definition at line 1271 of file Zone.cpp.
References mAllEntities, mLock, and mPendingDespawnEntities.
bool Zone::MinionSpawned (const std::shared_ptr< ActiveEntityState > & eState, uint32_t slgID = 0)
Determine if a minion has been spawned in the zone with an optional spawn location group.
Parameters
eState Pointer to the summoner entity
slgID Optional spawn location group ID
Returns
true if an entity has spawned, false one has not
Definition at line 1136 of file Zone.cpp.
References GetActiveEntity().
int32_t Zone::OccupyPvPBase (int32_t baseID, int32_t occupierID, bool complete, uint64_t occupyStartTime = 0)
Update the occupier (or owner) information of a PvP base in the zone.
Parameters
baseID Entity ID of the base in the zone
occupierID Entity ID of the occupier (or owner)
complete true if the occupier is canceling the request or has occupied it long enough to become the owner, false if the base occupation should start
occupyStartTime Optional parameter that needs to be specified when attempting to complete the occupation
Returns
Error code resulting from an invalid request or 0 upon success
Definition at line 863 of file Zone.cpp.
References channel::ClientState::GetCharacterState(), channel::ClientState::GetEntityClientState(), GetPvPBase(), channel::ChannelServer::GetServerTime(), channel::ClientState::GetZone(), mLock, and channel::state().
void Zone::RegisterEntityState (const std::shared_ptr< objects::EntityStateObject > & state) private
Register an entity as one that currently exists in the zone.
Parameters
state Pointer to an entity state in the zone
Definition at line 1016 of file Zone.cpp.
References mAllEntities, mLock, and channel::state().
Referenced by AddAlly(), AddBase(), AddBazaar(), AddConnection(), AddCultureMachine(), AddEnemy(), AddLootBox(), AddNPC(), AddObject(), and AddPlasma().
void Zone::RemoveConnection (const std::shared_ptr< ChannelClientConnection > & client)
Remove a client connection from the zone and unregister its world CID.
Parameters
client Pointer to a client connection to remove
Definition at line 263 of file Zone.cpp.
References channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), channel::ClientState::GetWorldCID(), mActiveEntities, mConnections, mFlagStates, mLock, mZoneInstance, channel::state(), and UnregisterEntityState().
void Zone::RemoveEntity (int32_t entityID, uint32_t spawnDelay = 0)
Remove an entity from the zone.
For player entities, use RemoveConnection instead.
Parameters
entityID ID of the entity to remove
spawnDelay Optional parameter to update spawn groups with a timed delay (in seconds) instead of right away, should the group be empty after the change
Definition at line 299 of file Zone.cpp.
References GetDiasporaBases(), channel::ActiveEntityState::GetEnemyBase(), GetEntity(), channel::ChannelServer::GetServerTime(), mActiveEntities, mAllEntities, mAllies, mBossBoxGroups, mBossBoxOwners, mBossIDs, mDiasporaMiniBossUpdated, mEncounters, mEnemies, mLock, mLootBoxes, mRespawnTimes, mSpawnGroups, mSpawnLocationGroups, mStaggeredSpawns, channel::state(), and UnregisterEntityState().
void Zone::SetDynamicMap (const std::shared_ptr< DynamicMap > & map)
Set the dynamic map information bound to the zone.
Parameters
map Dynamic maps information bound to the zone
Definition at line 234 of file Zone.cpp.
References mDynamicMap.
void Zone::SetFlagState (int32_t key, int32_t value, int32_t worldCID)
Set the state of a zone flag.
Parameters
key Lookup key for the flag
value Value to set for the flag
worldCID CID of the character the flag belongs to, 0 if it affects the entire instance
Definition at line 1550 of file Zone.cpp.
References mFlagStates, and mLock.
void Zone::SetGeometry (const std::shared_ptr< ZoneGeometry > & geometry)
Set the geometry information bound to the zone.
Parameters
geometry Geometry information bound to the zone
Definition at line 196 of file Zone.cpp.
References mGeometry.
void Zone::SetInstance (const std::shared_ptr< ZoneInstance > & instance)
Set the instance the zone belongs to.
Parameters
instance Instance the zone belongs to
Definition at line 212 of file Zone.cpp.
References mZoneInstance.
uint32_t Zone::SetNextRentalExpiration ()
Set the next entity rental expiration in system time from the zone's bazaar markets and culture machines.
Returns
Next entity rental expiration in system time
Definition at line 1684 of file Zone.cpp.
References mBazaars, mCultureMachines, mLock, and mNextRentalExpiration.
void Zone::SetNextStatusEffectTime (uint32_t time, int32_t entityID)
Set the next status effect event time associated to an entity in the zone.
Parameters
time Time of the next status effect event time
entityID ID of the entity with a status effect event at the specified time
Definition at line 1058 of file Zone.cpp.
References mLock, and mNextEntityStatusTimes.
bool Zone::SpawnedAtSpot (uint32_t spotID)
Check if an entity has ever spawned at the specified spot.
Parameters
spotID Spot ID of the spawn to check
Returns
true if an entity has ever spawned at the spot
Definition at line 1161 of file Zone.cpp.
References mLock, and mSpotsSpawned.
std::shared_ptr< ActiveEntityState > Zone::StartStopCombat (int32_t entityID, uint64_t timeout, bool checkBefore = false)
Add or remove the supplied entity as a combatant in the zone.
If the entity belongs to a player, both the character and demon will be added.
Parameters
entityID ID of the entity starting or stopping combat
timeout Server time for when combat will end or 0 for ending now
checkBefore If true the timestamp will be used to check if the entity can end combat at that time and no values will be changed.
Returns
Pointer to the entity if it was in the opposite state
Definition at line 1443 of file Zone.cpp.
References channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), channel::ClientState::GetEntityClientState(), mAllEntities, mLock, and channel::state().
std::unordered_map< size_t, std::shared_ptr< objects::Loot > > Zone::TakeLoot (std::shared_ptr< objects::LootBox > lBox, std::set< int8_t > slots, size_t freeSlots, std::unordered_map< uint32_t, uint16_t > stacksFree = {})
Take loot out of the specified loot box.
This should be the only way loot is removed from a box as it uses a mutex lock to ensure that the loot is not duplicated for two different people. This currently does NOT support splitting stacks within the loot box when the box being moved to becomes full.
Parameters
lBox Pointer to the loot box
slots Loot slots being requested or empty to request all
freeSlots Contextual number of free slots signifying how many loot items can be taken
stacksFree Contextual number of free stack slots used when determining how many items can be taken
Returns
Map of slot IDs to the loot taken
Definition at line 1564 of file Zone.cpp.
References mLock.
bool Zone::TimeRestrictionActive (const WorldClock & clock, const std::shared_ptr< objects::SpawnRestriction > & restriction) static
Determine based on the supplied clock time if a spawn restriction is active or not.
Parameters
clock World clock set to the current time
restriction Pointer to the spawn restriction to evaluate
Returns
true if the current time is valid for the restriction, false if it is not
Definition at line 1773 of file Zone.cpp.
References channel::WorldClock::Day, channel::WorldClockTime::Hour, channel::WorldClockTime::Min, channel::WorldClock::Month, channel::WorldClockTime::MoonPhase, channel::WorldClockTime::SystemHour, channel::WorldClockTime::SystemMin, and channel::WorldClock::WeekDay.
Referenced by channel::EventManager::GenerateDemonQuest(), and UpdateTimedSpawns().
void Zone::UnregisterEntityState (int32_t entityID) private
Remove an entity that no longer exists in the zone by its ID.
Parameters
entityID ID of an entity to remove
Definition at line 1022 of file Zone.cpp.
References mAllEntities, mLock, and mPendingDespawnEntities.
Referenced by RemoveConnection(), and RemoveEntity().
std::list< std::shared_ptr< ActiveEntityState > > Zone::UpdateStaggeredSpawns (uint64_t now)
Get enemies or allies that should spawn past the supplied server time.
Parameters
now System time representing the current server time
Returns
List of enemies or allies to spawn
Definition at line 1395 of file Zone.cpp.
References mAllies, mDisabledSpawnGroups, mEnemies, mLock, and mStaggeredSpawns.
bool Zone::UpdateTimedSpawns (const WorldClock & clock, bool initializing = false)
Update all spawn groups and plasma states that have time restrictions based upon the supplie world clock time.
Parameters
clock World clock set to the current time
initializing true if the zone is being setup, defaults to false
Returns
true if any updates were performed that the zone manager needs to react to, false if none occurred or they can be processed later
Definition at line 1280 of file Zone.cpp.
References DisableSpawnGroups(), EnableSpawnGroups(), mDeactivatedSpawnGroups, mLock, mPlasma, and TimeRestrictionActive().
Member Data Documentation
std::list<std::shared_ptr<ActiveEntityState> > channel::Zone::mActiveEntities private
List of active entities in the zone.
Definition at line 832 of file Zone.h.
Referenced by AddConnection(), AddSpawnedEntity(), GetActiveEntities(), RemoveConnection(), and RemoveEntity().
std::unordered_map<int32_t, std::shared_ptr<objects::EntityStateObject> > channel::Zone::mActors private
Map of entities in the zone with a specified actor ID for used when referencing in actions or events.
Definition at line 897 of file Zone.h.
Referenced by AddNPC(), AddObject(), Cleanup(), and GetActor().
std::unordered_map<int32_t, std::shared_ptr<objects::EntityStateObject> > channel::Zone::mAllEntities private
Map of entities in the zone by their ID.
Definition at line 893 of file Zone.h.
Referenced by Cleanup(), GetEntity(), GetUpdatedStatusEffectEntities(), MarkDespawn(), RegisterEntityState(), RemoveEntity(), StartStopCombat(), and UnregisterEntityState().
std::list<std::shared_ptr<AllyState> > channel::Zone::mAllies private
List of pointers to allies instantiated for the zone.
Definition at line 835 of file Zone.h.
Referenced by AddAlly(), Cleanup(), GetAllies(), GetEnemiesAndAllies(), RemoveEntity(), and UpdateStaggeredSpawns().
std::list<std::shared_ptr<objects::EntityStateObject> > channel::Zone::mBases private
List of pointers to special zone bases instantiated for the zone.
Definition at line 838 of file Zone.h.
Referenced by AddBase(), Cleanup(), GetDiasporaBases(), and GetPvPBases().
std::list<std::shared_ptr<BazaarState> > channel::Zone::mBazaars private
List of pointers to bazaars instantiated for the zone.
Definition at line 841 of file Zone.h.
Referenced by AddBazaar(), Cleanup(), GetBazaars(), and SetNextRentalExpiration().
std::unordered_map<uint32_t, std::set<int32_t> > channel::Zone::mBossBoxGroups private
Map of boss box group IDs to the boxes included.
Definition at line 881 of file Zone.h.
Referenced by AddLootBox(), ClaimBossBox(), and RemoveEntity().
std::unordered_map<uint32_t, std::set<int32_t> > channel::Zone::mBossBoxOwners private
Map of boss box group IDs to entities that have claimed part of the group.
Definition at line 884 of file Zone.h.
Referenced by ClaimBossBox(), and RemoveEntity().
std::set<int32_t> channel::Zone::mBossIDs private
Set of all entity IDs for bosses in the zone.
Definition at line 887 of file Zone.h.
Referenced by AddEnemy(), Cleanup(), GetBosses(), and RemoveEntity().
std::unordered_map<int32_t, std::shared_ptr<ChannelClientConnection> > channel::Zone::mConnections private
Map of world CIDs to client connections.
Definition at line 829 of file Zone.h.
Referenced by AddConnection(), GetConnectionList(), GetConnections(), and RemoveConnection().
std::unordered_map<uint32_t, std::shared_ptr<CultureMachineState> > channel::Zone::mCultureMachines private
Map of culture machine states by definition ID.
Definition at line 845 of file Zone.h.
Referenced by AddCultureMachine(), Cleanup(), GetCultureMachines(), and SetNextRentalExpiration().
std::set<uint32_t> channel::Zone::mDeactivatedSpawnGroups private
Set of spawn group IDs that have been deactivated and will not re-enable until they have been activated again.
Definition at line 921 of file Zone.h.
Referenced by DisableSpawnGroups(), EnableSpawnGroups(), and UpdateTimedSpawns().
bool channel::Zone::mDiasporaMiniBossUpdated private
Flag indicating that Diaspora mini-boss spawn location groups have updated since the last call to DiasporaMiniBossUpdated.
Definition at line 950 of file Zone.h.
Referenced by AddSpawnedEntity(), DiasporaMiniBossUpdated(), and RemoveEntity().
std::set<uint32_t> channel::Zone::mDisabledSpawnGroups private
Set of spawn group IDs that have been disabled.
Definition at line 917 of file Zone.h.
Referenced by DisableSpawnGroups(), EnableSpawnGroups(), GetDisabledSpawnGroups(), and UpdateStaggeredSpawns().
std::set<uint32_t> channel::Zone::mDisabledSpawnLocationGroups private
Set of spawn location group IDs where all associated groups are disabled.
Definition at line 924 of file Zone.h.
Referenced by DisableSpawnGroups(), and EnableSpawnGroups().
std::shared_ptr<DynamicMap> channel::Zone::mDynamicMap private
Dynamic map information bound to the zone.
Definition at line 934 of file Zone.h.
Referenced by GetDynamicMap(), and SetDynamicMap().
std::unordered_map<uint32_t, std::list<std::shared_ptr<objects::Action> > > channel::Zone::mEncounterDefeatActions private
Map of encounter IDs to defeat actions assigned when they were created.
Definition at line 866 of file Zone.h.
Referenced by Cleanup(), CreateEncounter(), and EncounterDefeated().
std::unordered_map<uint32_t, std::set<std::shared_ptr<ActiveEntityState> > > channel::Zone::mEncounters private
Map of encounter IDs to entities that belong to that encounter.
Definition at line 862 of file Zone.h.
Referenced by Cleanup(), CreateEncounter(), EncounterDefeated(), and RemoveEntity().
std::list<std::shared_ptr<EnemyState> > channel::Zone::mEnemies private
List of pointers to enemies instantiated for the zone.
Definition at line 848 of file Zone.h.
Referenced by AddEnemy(), Cleanup(), GetEnemies(), GetEnemiesAndAllies(), RemoveEntity(), and UpdateStaggeredSpawns().
std::unordered_map<int32_t, std::unordered_map<int32_t, int32_t> > channel::Zone::mFlagStates private
General use flags and associated values used for event sequences etc keyed on 0 for all characters or world CID if for a specific one.
Definition at line 928 of file Zone.h.
Referenced by GetFlagState(), GetFlagStates(), RemoveConnection(), and SetFlagState().
std::shared_ptr<ZoneGeometry> channel::Zone::mGeometry private
Geometry information bound to the zone.
Definition at line 931 of file Zone.h.
Referenced by Collides(), GetGeometry(), and SetGeometry().
bool channel::Zone::mHasRespawns private
Quick reference flag to determine if the zone has respwa.
Definition at line 946 of file Zone.h.
Referenced by HasRespawns(), and Zone().
std::mutex channel::Zone::mLock private
Server lock for shared resources.
Definition at line 953 of file Zone.h.
Referenced by AddAlly(), AddConnection(), AddEnemy(), AddLootBox(), ClaimBossBox(), Cleanup(), CreateEncounter(), DiasporaMiniBossUpdated(), EnableDisableSpawnGroup(), EncounterDefeated(), GetConnectionList(), GetDespawnEntities(), GetDisabledSpawnGroups(), GetEnemiesAndAllies(), GetEntity(), GetFlagState(), GetFlagStates(), GetRespawnLocations(), GetUpdatedStatusEffectEntities(), GroupHasSpawned(), HasStaggeredSpawns(), IncreasePvPBaseBonus(), MarkDespawn(), OccupyPvPBase(), RegisterEntityState(), RemoveConnection(), RemoveEntity(), SetFlagState(), SetNextRentalExpiration(), SetNextStatusEffectTime(), SpawnedAtSpot(), StartStopCombat(), TakeLoot(), UnregisterEntityState(), UpdateStaggeredSpawns(), and UpdateTimedSpawns().
std::list<std::shared_ptr<LootBoxState> > channel::Zone::mLootBoxes private
List of pointers to lootable boxes for the zone.
Definition at line 878 of file Zone.h.
Referenced by AddLootBox(), GetLootBoxes(), and RemoveEntity().
uint32_t channel::Zone::mNextEncounterID private
Next ID to use for encounters registered for the zone.
Definition at line 943 of file Zone.h.
Referenced by CreateEncounter().
std::map<uint32_t, std::set<int32_t> > channel::Zone::mNextEntityStatusTimes private
Map of system times to active entities with status effects that need handling at that time.
Definition at line 901 of file Zone.h.
Referenced by GetUpdatedStatusEffectEntities(), and SetNextStatusEffectTime().
uint32_t channel::Zone::mNextRentalExpiration private
Next entity rental expiration time that will occur.
Definition at line 940 of file Zone.h.
Referenced by GetNextRentalExpiration(), and SetNextRentalExpiration().
std::list<std::shared_ptr<NPCState> > channel::Zone::mNPCs private
List of pointers to NPCs instantiated for the zone.
Definition at line 872 of file Zone.h.
Referenced by AddNPC(), Cleanup(), and GetNPCs().
std::list<std::shared_ptr<ServerObjectState> > channel::Zone::mObjects private
List of pointers to objects instantiated for the zone.
Definition at line 875 of file Zone.h.
Referenced by AddObject(), Cleanup(), and GetServerObjects().
std::set<int32_t> channel::Zone::mPendingDespawnEntities private
Set of entity IDs waiting to despawn.
IDs are removed from this set when the entity is removed from the zone.
Definition at line 914 of file Zone.h.
Referenced by DisableSpawnGroups(), GetDespawnEntities(), GroupHasSpawned(), MarkDespawn(), and UnregisterEntityState().
std::unordered_map<uint32_t, std::shared_ptr<PlasmaState> > channel::Zone::mPlasma private
Map of plasma states by definition ID.
Definition at line 890 of file Zone.h.
Referenced by AddPlasma(), Cleanup(), GetPlasma(), and UpdateTimedSpawns().
std::map<uint64_t, std::set<uint32_t> > channel::Zone::mRespawnTimes private
Map of server times to spawn location group IDs that need to be respawned at that time.
Definition at line 905 of file Zone.h.
Referenced by AddSpawnedEntity(), DisableSpawnGroups(), EnableSpawnGroups(), GetRespawnLocations(), and RemoveEntity().
std::unordered_map<uint32_t, std::list<std::shared_ptr<ActiveEntityState> > > channel::Zone::mSpawnGroups private
Map of spawn group IDs to pointers to entities created from that group.
Keys are never removed from this group so one time spawns can be checked.
Definition at line 853 of file Zone.h.
Referenced by AddSpawnedEntity(), Cleanup(), DisableSpawnGroups(), GroupHasSpawned(), and RemoveEntity().
std::unordered_map<uint32_t, std::list<std::shared_ptr<ActiveEntityState> > > channel::Zone::mSpawnLocationGroups private
Map of spawn location group IDs to pointers to entities created from the groups.
Keys are never removed from this group so one time spawns can be checked.
Definition at line 858 of file Zone.h.
Referenced by AddSpawnedEntity(), Cleanup(), GetRespawnLocations(), GroupHasSpawned(), and RemoveEntity().
std::set<uint32_t> channel::Zone::mSpotsSpawned private
Set of all spot IDs that have had an enemy spawned.
Definition at line 869 of file Zone.h.
Referenced by AddSpawnedEntity(), and SpawnedAtSpot().
std::map<uint64_t, std::list<std::shared_ptr<ActiveEntityState> > > channel::Zone::mStaggeredSpawns private
Map of server times to enemies or allies that exist in the zone but will not actually spawn until the time passes.
Definition at line 910 of file Zone.h.
Referenced by AddAlly(), AddEnemy(), Cleanup(), GetEnemiesAndAllies(), HasStaggeredSpawns(), RemoveEntity(), and UpdateStaggeredSpawns().
std::shared_ptr<ZoneInstance> channel::Zone::mZoneInstance private
Zone instance pointer for non-global zones.
Definition at line 937 of file Zone.h.
Referenced by Cleanup(), GetInstance(), GetInstanceType(), GetXPMultiplier(), RemoveConnection(), and SetInstance().
The documentation for this class was generated from the following files:
Zone.h
Zone.cpp