COMP_hack: channel::ActionManager Class Reference
channel::ActionManager Class Reference
Class to manage actions when triggering a spot or interacting with an object/NPC.
#include <ActionManager.h>
Classes
struct ActionContext
Public Member Functions
ActionManager (const std::weak_ptr< ChannelServer > &server)
Create a new ActionManager.
~ActionManager ()
Clean up the ActionManager.
void BindAllActionTypes (const std::shared_ptr< libcomp::ScriptEngine > &engine)
Bind all action types to the supplied script engine.
void PerformActions (const std::shared_ptr< ChannelClientConnection > &client, const std::list< std::shared_ptr< objects::Action >> &actions, int32_t sourceEntityID, const std::shared_ptr< Zone > &zone=nullptr, ActionOptions options={})
Perform the list of actions on behalf of the client.
void SendStageEffect (const std::shared_ptr< ChannelClientConnection > &client, int32_t messageID, int8_t effectType, bool includeMessage, int32_t messageValue=0)
Send a stage effect notification to the client.
Static Public Member Functions
static libcomp::String GetActionName (objects::Action::ActionType_t type)
Get an action name by its type.
Private Member Functions
bool AddRemoveItems (ActionContext &ctx)
Add or remove items to the client character's inventory.
bool AddRemoveStatus (ActionContext &ctx)
Add or remove status effects to the client's character or partner demon.
bool CreateLoot (ActionContext &ctx)
Create one or more loot boxes at the specified location.
bool Delay (ActionContext &ctx)
Delay action execution or flag an action for delayed usage at a later time.
bool DisplayMessage (ActionContext &ctx)
Display a message for the client that no response is returned from.
template<class T >
std::shared_ptr< T > GetAction (ActionContext &ctx, bool requireClient, bool requireZone=true)
Get the action from the supplied context converted to the proper type.
std::set< int32_t > GetActionContextCIDs (const std::shared_ptr< objects::Action > &action, ActionContext &ctx, bool &failure, bool &preFiltered)
Get world CIDs associated to the action context of the supplied action.
bool GrantSkills (ActionContext &ctx)
Grant skills or skill points to the source client character or partner demon.
bool GrantXP (ActionContext &ctx)
Grant XP to the source client character and/or partner demon.
bool PlayBGM (ActionContext &ctx)
Play or stop a BGM for the client.
bool PlaySoundEffect (ActionContext &ctx)
Play a sound effect for the client.
bool PrepareTransformScript (ActionContext &ctx, std::shared_ptr< libcomp::ScriptEngine > engine)
Prepare the transformation script from the action on the supplied script engine.
bool RecordTimeTrial (ActionContext &ctx, uint32_t rewardItem, uint16_t rewardItemCount)
Move the current time trial results to the record set.
bool RunScript (ActionContext &ctx)
Execute a custom script to perform various types of actions.
bool SetHomepoint (ActionContext &ctx)
Set the homepoint for the client character.
bool SetNPCState (ActionContext &ctx)
Change the state of the source entity in the zone.
bool Spawn (ActionContext &ctx)
Spawn an enemy spawn group by ID in the client's current zone.
bool SpecialDirection (ActionContext &ctx)
Display a special direction effect for the client.
bool StageEffect (ActionContext &ctx)
Display a stage effect for the client that no response is returned from.
bool StartEvent (ActionContext &ctx)
Start an event sequence for the client.
bool TransformAction (ActionContext &ctx, std::shared_ptr< libcomp::ScriptEngine > engine)
Finish preparing and execute the tranformation script configured for the action.
bool UpdateCOMP (ActionContext &ctx)
Add/remove demons from the COMP and/or set the max slots available.
bool UpdateFlag (ActionContext &ctx)
Update flags related to character maps, valuables or plugins.
bool UpdateLNC (ActionContext &ctx)
Update the client character's LNC alignment.
bool UpdatePoints (ActionContext &ctx)
Update various point values associated to the client.
bool UpdateQuest (ActionContext &ctx)
Update a quest related to the current character.
bool UpdateZoneFlags (ActionContext &ctx)
Update one or more flags in the current zone.
bool UpdateZoneInstance (ActionContext &ctx)
Update the instance related to the current character.
bool VerifyClient (ActionContext &ctx, const libcomp::String &typeName)
Verify that the client is on the context and print an error message if it is not.
bool VerifyZone (ActionContext &ctx, const libcomp::String &typeName)
Verify that a zone is on the context and print an error message if one is not.
bool ZoneChange (ActionContext &ctx)
Perform the zone change action on behalf of the client.
Private Attributes
libcomp::EnumMap
< objects::Action::ActionType_t,
std::function< bool(ActionManager
&, ActionContext &)> > mActionHandlers
List of action parsers.
std::weak_ptr< ChannelServer > mServer
Pointer to the channel server.
Detailed Description
Class to manage actions when triggering a spot or interacting with an object/NPC.
Definition at line 88 of file ActionManager.h.
Constructor & Destructor Documentation
ActionManager::ActionManager (const std::weak_ptr< ChannelServer > & server)
Create a new ActionManager.
Parameters
server Pointer back to the channel server this belongs to.
Definition at line 119 of file ActionManager.cpp.
References AddRemoveItems(), AddRemoveStatus(), CreateLoot(), Delay(), DisplayMessage(), GrantSkills(), GrantXP(), mActionHandlers, PlayBGM(), PlaySoundEffect(), RunScript(), SetHomepoint(), SetNPCState(), Spawn(), SpecialDirection(), StageEffect(), StartEvent(), UpdateCOMP(), UpdateFlag(), UpdateLNC(), UpdatePoints(), UpdateQuest(), UpdateZoneFlags(), UpdateZoneInstance(), and ZoneChange().
ActionManager::~ActionManager ()
Clean up the ActionManager.
Definition at line 172 of file ActionManager.cpp.
Member Function Documentation
bool ActionManager::AddRemoveItems (ActionContext & ctx) private
Add or remove items to the client character's inventory.
Parameters
ctx ActionContext for the executing source information.
Return values
false The action list should stop after this action.
Definition at line 988 of file ActionManager.cpp.
References libcomp::String::Arg(), libcomp::DatabaseChangeSet::Create(), channel::ClientState::GetAccountUID(), channel::ClientState::GetCharacterState(), mServer, libcomp::PersistentObject::New(), RecordTimeTrial(), channel::state(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS8(), libcomp::Packet::WriteU16Little(), and libcomp::Packet::WriteU32Little().
Referenced by ActionManager().
bool ActionManager::AddRemoveStatus (ActionContext & ctx) private
Add or remove status effects to the client's character or partner demon.
Parameters
ctx ActionContext for the executing source information.
Return values
false The action list should stop after this action.
Definition at line 1399 of file ActionManager.cpp.
References channel::StatusEffectChange::Duration, channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), mServer, and channel::state().
Referenced by ActionManager().
void ActionManager::BindAllActionTypes (const std::shared_ptr< libcomp::ScriptEngine > & engine)
Bind all action types to the supplied script engine.
Parameters
engine ScriptEngine to bind to
Definition at line 532 of file ActionManager.cpp.
Referenced by PrepareTransformScript().
bool ActionManager::CreateLoot (ActionContext & ctx) private
Create one or more loot boxes at the specified location.
Parameters
ctx ActionContext for the executing source information.
Return values
false The action list should stop after this action.
Definition at line 3292 of file ActionManager.cpp.
References libcomp::String::Arg(), channel::ChannelClientConnection::FlushAllOutgoing(), channel::ChannelServer::GetServerTime(), mServer, channel::Point::x, and channel::Point::y.
Referenced by ActionManager().
bool ActionManager::Delay (ActionContext & ctx) private
Delay action execution or flag an action for delayed usage at a later time.
Parameters
ctx ActionContext for the executing source information.
Return values
false The action list should stop after this action.
Definition at line 3442 of file ActionManager.cpp.
References channel::ClientState::GetCharacterState(), channel::ChannelServer::GetServerTime(), channel::ActionOptions::GroupID, mServer, and channel::state().
Referenced by ActionManager().
bool ActionManager::DisplayMessage (ActionContext & ctx) private
Display a message for the client that no response is returned from.
Parameters
ctx ActionContext for the executing source information.
Return values
false The action list should stop after this action.
Definition at line 1960 of file ActionManager.cpp.
References libcomp::Packet::Seek(), libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteS32Little().
Referenced by ActionManager().
template<class T > std::shared_ptr<T> channel::ActionManager::GetAction (ActionContext & ctx, bool requireClient, bool requireZone = true) inline private
Get the action from the supplied context converted to the proper type.
If the action is configured with a transformation script, a transformed copy will be returned and set on the context.
Parameters
ctx ActionContext for the executing source information.
requireClient Check that the client is on the context if supplied and fail if it is not
requireZone Check that the action is taking place with a current zone. Nearly all actions require a zone.
Returns
true on success, false on failure
Definition at line 363 of file ActionManager.h.
References channel::ActionManager::ActionContext::Action, PrepareTransformScript(), TransformAction(), VerifyClient(), and VerifyZone().
std::set< int32_t > ActionManager::GetActionContextCIDs (const std::shared_ptr< objects::Action > & action, ActionContext & ctx, bool & failure, bool & preFiltered) private
Get world CIDs associated to the action context of the supplied action.
Parameters
action Pointer to the current action
ctx ActionContext for the executing source information.
failure Output parameter designating if a failure occurred
preFiltered Output parameter designating if the set was prefiltered or if it needs to be filtered still
Return values
Set of world CIDs
Definition at line 561 of file ActionManager.cpp.
References channel::ActionManager::ActionContext::Client, channel::ActionManager::ActionContext::CurrentZone, channel::ClientState::GetWorldCID(), mServer, channel::ActionManager::ActionContext::SourceEntityID, and channel::state().
Referenced by PerformActions().
libcomp::String ActionManager::GetActionName (objects::Action::ActionType_t type) static
Get an action name by its type.
Parameters
type Action type to retrieve the name of
Returns
Action name matching the type
Definition at line 474 of file ActionManager.cpp.
Referenced by PerformActions().
bool ActionManager::GrantSkills (ActionContext & ctx) private
Grant skills or skill points to the source client character or partner demon.
Parameters
ctx ActionContext for the executing source information.
Return values
false The action list should stop after this action.
Definition at line 1846 of file ActionManager.cpp.
References channel::ClientState::GetAccountUID(), channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), mServer, and channel::state().
Referenced by ActionManager().
bool ActionManager::GrantXP (ActionContext & ctx) private
Grant XP to the source client character and/or partner demon.
Parameters
ctx ActionContext for the executing source information.
Return values
false The action list should stop after this action.
Definition at line 1793 of file ActionManager.cpp.
References channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), mServer, and channel::state().
Referenced by ActionManager().
void ActionManager::PerformActions (const std::shared_ptr< ChannelClientConnection > & client, const std::list< std::shared_ptr< objects::Action >> & actions, int32_t sourceEntityID, const std::shared_ptr< Zone > & zone = nullptr, ActionOptions options = {})
Perform the list of actions on behalf of the client.
Parameters
client Client to perform the actions for.
actions List of actions to perform.
sourceEntityID ID of the entity performing the actions.
zone Pointer to the current zone the action is being performed in
options Optional parameters to modify action execution
Definition at line 176 of file ActionManager.cpp.
References channel::ActionManager::ActionContext::Action, libcomp::String::Arg(), channel::ActionOptions::AutoEventsOnly, channel::ActionManager::ActionContext::ChannelChanged, channel::ActionManager::ActionContext::Client, channel::ActionManager::ActionContext::CurrentZone, GetActionContextCIDs(), GetActionName(), channel::ClientState::GetCharacterState(), channel::ClientState::GetEntityClientState(), channel::ActionOptions::IncrementEventIndex, mActionHandlers, mServer, channel::NONE, channel::ActionManager::ActionContext::Options, channel::ActionManager::ActionContext::SourceEntityID, channel::state(), and to_underlying().
Referenced by UpdateZoneFlags().
bool ActionManager::PlayBGM (ActionContext & ctx) private
Play or stop a BGM for the client.
Parameters
ctx ActionContext for the executing source information.
Return values
false The action list should stop after this action.
Definition at line 2017 of file ActionManager.cpp.
References libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteS32Little().
Referenced by ActionManager().
bool ActionManager::PlaySoundEffect (ActionContext & ctx) private
Play a sound effect for the client.
Parameters
ctx ActionContext for the executing source information.
Return values
false The action list should stop after this action.
Definition at line 2045 of file ActionManager.cpp.
References libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteS32Little().
Referenced by ActionManager().
bool ActionManager::PrepareTransformScript (ActionContext & ctx, std::shared_ptr< libcomp::ScriptEngine > engine) private
Prepare the transformation script from the action on the supplied script engine.
Parameters
ctx ActionContext for the executing source information
engine Script engine to prepare the script for
Returns
true on success, false on failure
Definition at line 3771 of file ActionManager.cpp.
References channel::ActionManager::ActionContext::Action, libcomp::String::Arg(), BindAllActionTypes(), and mServer.
Referenced by GetAction().
bool ActionManager::RecordTimeTrial (ActionContext & ctx, uint32_t rewardItem, uint16_t rewardItemCount) private
Move the current time trial results to the record set.
Parameters
ctx ActionContext for the executing source information.
rewardItem Item obtained from the time trial
rewardItemCount Item count obtained form the time trial
Return values
false if the trial records were not updated
Definition at line 3678 of file ActionManager.cpp.
References channel::ActionManager::ActionContext::Action, libcomp::String::Arg(), channel::ActionManager::ActionContext::Client, channel::ClientState::GetAccountUID(), channel::ClientState::GetCharacterState(), mServer, channel::NONE, channel::state(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS8(), libcomp::Packet::WriteU16Little(), libcomp::Packet::WriteU32Little(), and libcomp::Packet::WriteU8().
Referenced by AddRemoveItems(), and UpdateFlag().
bool ActionManager::RunScript (ActionContext & ctx) private
Execute a custom script to perform various types of actions.
Parameters
ctx ActionContext for the executing source information.
Return values
false The action list should stop after this action.
Definition at line 3584 of file ActionManager.cpp.
References channel::FAIL, channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), channel::ClientState::GetEntityClientState(), channel::LOG_OFF, mServer, channel::state(), and channel::SUCCESS.
Referenced by ActionManager().
void ActionManager::SendStageEffect (const std::shared_ptr< ChannelClientConnection > & client, int32_t messageID, int8_t effectType, bool includeMessage, int32_t messageValue = 0)
Send a stage effect notification to the client.
Parameters
client Client to display the effect for
messageID ID of the effect message
effectType Effect type
includeMessage If true, the same message will print to the console as well
messageValue Optional message value to display inline in the message
Definition at line 443 of file ActionManager.cpp.
References libcomp::Packet::Clear(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteS8().
Referenced by StageEffect().
bool ActionManager::SetHomepoint (ActionContext & ctx) private
Set the homepoint for the client character.
Parameters
ctx ActionContext for the executing source information.
Return values
false The action list should stop after this action.
Definition at line 936 of file ActionManager.cpp.
References channel::ClientState::GetAccountUID(), channel::ClientState::GetCharacterState(), mServer, channel::state(), libcomp::Packet::WriteFloat(), libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteS32Little().
Referenced by ActionManager().
bool ActionManager::SetNPCState (ActionContext & ctx) private
Change the state of the source entity in the zone.
Parameters
ctx ActionContext for the executing source information.
Return values
false The action list should stop after this action.
Definition at line 2063 of file ActionManager.cpp.
References libcomp::String::Arg(), channel::ChannelClientConnection::BroadcastPacket(), mServer, libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteU8().
Referenced by ActionManager().
bool ActionManager::Spawn (ActionContext & ctx) private
Spawn an enemy spawn group by ID in the client's current zone.
Parameters
ctx ActionContext for the executing source information.
Return values
false The action list should stop after this action.
Definition at line 3265 of file ActionManager.cpp.
References mServer.
Referenced by ActionManager().
bool ActionManager::SpecialDirection (ActionContext & ctx) private
Display a special direction effect for the client.
Parameters
ctx ActionContext for the executing source information.
Return values
false The action list should stop after this action.
Definition at line 1998 of file ActionManager.cpp.
References libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteU8().
Referenced by ActionManager().
bool ActionManager::StageEffect (ActionContext & ctx) private
Display a stage effect for the client that no response is returned from.
Parameters
ctx ActionContext for the executing source information.
Return values
false The action list should stop after this action.
Definition at line 1984 of file ActionManager.cpp.
References SendStageEffect().
Referenced by ActionManager().
bool ActionManager::StartEvent (ActionContext & ctx) private
Start an event sequence for the client.
Parameters
ctx ActionContext for the executing source information.
Return values
false The action list should stop after this action.
Definition at line 734 of file ActionManager.cpp.
References channel::EventOptions::ActionGroupID, channel::EventOptions::AutoOnly, mServer, and channel::EventOptions::NoInterrupt.
Referenced by ActionManager().
bool ActionManager::TransformAction (ActionContext & ctx, std::shared_ptr< libcomp::ScriptEngine > engine) private
Finish preparing and execute the tranformation script configured for the action.
Parameters
ctx ActionContext for the executing source information
engine Script engine to execute the script using
Returns
true on success, false on failure
Definition at line 3806 of file ActionManager.cpp.
References channel::ActionManager::ActionContext::Action, channel::ActionManager::ActionContext::Client, channel::ActionManager::ActionContext::CurrentZone, channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), channel::ClientState::GetEntityClientState(), channel::ActionManager::ActionContext::SourceEntityID, and channel::state().
Referenced by GetAction().
bool ActionManager::UpdateCOMP (ActionContext & ctx) private
Add/remove demons from the COMP and/or set the max slots available.
Parameters
ctx ActionContext for the executing source information.
Return values
false The action list should stop after this action.
Definition at line 1559 of file ActionManager.cpp.
References libcomp::String::Arg(), libcomp::DatabaseChangeSet::Create(), channel::ClientState::GetAccountUID(), channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), mServer, channel::state(), libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteU8().
Referenced by ActionManager().
bool ActionManager::UpdateFlag (ActionContext & ctx) private
Update flags related to character maps, valuables or plugins.
Parameters
ctx ActionContext for the executing source information.
Return values
false The action list should stop after this action.
Definition at line 2199 of file ActionManager.cpp.
References libcomp::String::Arg(), mServer, and RecordTimeTrial().
Referenced by ActionManager().
bool ActionManager::UpdateLNC (ActionContext & ctx) private
Update the client character's LNC alignment.
Parameters
ctx ActionContext for the executing source information.
Return values
false The action list should stop after this action.
Definition at line 2272 of file ActionManager.cpp.
References mServer.
Referenced by ActionManager().
bool ActionManager::UpdatePoints (ActionContext & ctx) private
Update various point values associated to the client.
Parameters
ctx ActionContext for the executing source information.
Return values
false The action list should stop after this action.
Definition at line 2299 of file ActionManager.cpp.
References channel::ClientState::GetAccountUID(), channel::ClientState::GetCharacterState(), channel::ClientState::GetWorldCID(), channel::MatchManager::InPvPTeam(), mServer, channel::MatchManager::PvPActive(), channel::state(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS16Little(), libcomp::Packet::WriteS32Little(), libcomp::Packet::WriteS8(), and libcomp::Packet::WriteU32Little().
Referenced by ActionManager().
bool ActionManager::UpdateQuest (ActionContext & ctx) private
Update a quest related to the current character.
Parameters
ctx ActionContext for the executing source information.
Return values
false The action list should stop after this action.
Definition at line 2669 of file ActionManager.cpp.
References mServer.
Referenced by ActionManager().
bool ActionManager::UpdateZoneFlags (ActionContext & ctx) private
Update one or more flags in the current zone.
Parameters
ctx ActionContext for the executing source information.
Return values
false The action list should stop after this action.
Definition at line 2723 of file ActionManager.cpp.
References channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), channel::ClientState::GetEntityClientState(), mServer, PerformActions(), and channel::state().
Referenced by ActionManager().
bool ActionManager::UpdateZoneInstance (ActionContext & ctx) private
Update the instance related to the current character.
Parameters
ctx ActionContext for the executing source information.
Return values
false The action list should stop after this action.
Definition at line 2945 of file ActionManager.cpp.
References libcomp::String::Arg(), channel::ClientState::GetCharacterState(), channel::ClientState::GetEntityClientState(), channel::ClientState::GetWorldCID(), mServer, and channel::state().
Referenced by ActionManager().
bool ActionManager::VerifyClient (ActionContext & ctx, const libcomp::String & typeName) private
Verify that the client is on the context and print an error message if it is not.
Parameters
ctx ActionContext for the executing source information
typeName Name of the action type being verified
Returns
true if the client exists, false if it does not
Definition at line 3737 of file ActionManager.cpp.
References libcomp::String::Arg(), and channel::ActionManager::ActionContext::Client.
Referenced by GetAction().
bool ActionManager::VerifyZone (ActionContext & ctx, const libcomp::String & typeName) private
Verify that a zone is on the context and print an error message if one is not.
Parameters
ctx ActionContext for the executing source information
typeName Name of the action type being verified
Returns
true if a zone exists, false if it does not
Definition at line 3754 of file ActionManager.cpp.
References libcomp::String::Arg(), and channel::ActionManager::ActionContext::CurrentZone.
Referenced by GetAction().
bool ActionManager::ZoneChange (ActionContext & ctx) private
Perform the zone change action on behalf of the client.
If no zoneID is specified, they will be sent to their homepoint.
Parameters
ctx ActionContext for the executing source information.
Return values
false The action list should stop after this action.
Definition at line 770 of file ActionManager.cpp.
References libcomp::String::Arg(), channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), mServer, channel::state(), channel::Point::x, and channel::Point::y.
Referenced by ActionManager().
Member Data Documentation
libcomp::EnumMap<objects::Action::ActionType_t, std::function<bool(ActionManager&, ActionContext&)> > channel::ActionManager::mActionHandlers private
List of action parsers.
Definition at line 452 of file ActionManager.h.
Referenced by ActionManager(), and PerformActions().
std::weak_ptr<ChannelServer> channel::ActionManager::mServer private
Pointer to the channel server.
Definition at line 448 of file ActionManager.h.
Referenced by AddRemoveItems(), AddRemoveStatus(), CreateLoot(), Delay(), GetActionContextCIDs(), GrantSkills(), GrantXP(), PerformActions(), PrepareTransformScript(), RecordTimeTrial(), RunScript(), SetHomepoint(), SetNPCState(), Spawn(), StartEvent(), UpdateCOMP(), UpdateFlag(), UpdateLNC(), UpdatePoints(), UpdateQuest(), UpdateZoneFlags(), UpdateZoneInstance(), and ZoneChange().
The documentation for this class was generated from the following files:
ActionManager.h
ActionManager.cpp