COMP_hack: channel::ClientState Class Reference
channel::ClientState Class Reference
Contains the state of a game client currently connected to the channel.
#include <ClientState.h>
Public Member Functions
ClientState ()
Create a new client state.
virtual ~ClientState ()
Clean up the client state, removing it from the registry if it exists there.
const libobjgen::UUID GetAccountUID () const
Get the UID of the account associated to the client.
std::shared_ptr< BazaarState > GetBazaarState ()
Get the bazaar associated to the client account's open market if one exists and the client is currently in the same zone as the bazaar.
std::shared_ptr< CharacterState > GetCharacterState ()
Get the state of the character associated to the client.
int32_t GetClanID () const
Get the current clan ID associated to the logged in character.
libcomp::Convert::Encoding_t GetClientStringEncoding ()
Get the string encoding to use for this client.
std::list< std::shared_ptr
< objects::ClientCostAdjustment > > GetCostAdjustments (int32_t entityID)
Get a client entity's current cost adjustments.
int32_t GetCurrentMenuShopID (int32_t type=0) const
Get the shop ID of the state's current event if it is an "open menu" type, optionally matching a specified type only.
std::shared_ptr< DemonState > GetDemonState ()
Get the state of the active demon associated to the client.
std::shared_ptr
< ActiveEntityState > GetEntityState (int32_t entityID, bool readyOnly=true)
Get the entity state associated to an entity ID for this client.
int32_t GetEventSourceEntityID () const
Get the source entity ID of the state's current event if it exists.
int32_t GetLocalObjectID (const libobjgen::UUID &uuid)
Get the local object ID associated to a UUID associated to the client.
const libobjgen::UUID GetLocalObjectUUID (int32_t objectID)
Get the UUID associated to an object ID associated to the client.
int64_t GetObjectID (const libobjgen::UUID &uuid)
Get the object ID associated to a UUID associated to the client.
const libobjgen::UUID GetObjectUUID (int64_t objectID)
Get the UUID associated to an object ID associated to the client.
std::shared_ptr
< objects::PartyCharacter > GetPartyCharacter (bool includeDemon) const
Get a current party character representation from the .associated CharacterState.
void GetPartyCharacterPacket (libcomp::Packet &p) const
Populate the supplied packet with an internal CharacterLogin packet containing character information.
std::shared_ptr
< objects::PartyMember > GetPartyDemon () const
Get a current party demon representation from the associated DemonState.
void GetPartyDemonPacket (libcomp::Packet &p) const
Populate the supplied packet with an internal CharacterLogin packet containing partner demon information.
uint32_t GetPartyID () const
Get the current party ID associated to the logged in character.
int32_t GetTeamID () const
Get the current team ID associated to the logged in character.
int32_t GetUserLevel () const
Get the user level of the account associated to the client.
int32_t GetWorldCID () const
Get the current world CID associated to the logged in character.
std::shared_ptr< Zone > GetZone () const
Get the character's current zone.
bool HasActiveEvent () const
Check if the state has a current event associated to it.
bool IsMovementLocked (int32_t entityID)
Determine if the entity associated to the client has its movements locked based upon system processes or events being active.
bool Register ()
Registers the client state with the static entity map for access by other clients.
bool RewindStartTime (ServerTime time)
Moves the client state start time back to the supplied time if it is currently later.
std::list< std::shared_ptr
< objects::ClientCostAdjustment > > SetCostAdjustments (int32_t entityID, std::list< std::shared_ptr< objects::ClientCostAdjustment >> adjustments)
Set a client entity's cost adjustments and return the newly modified values.
bool SetObjectID (const libobjgen::UUID &uuid, int64_t objectID, bool allowReset=false)
Set the object ID associated a UUID associated to the client.
ClientTime ToClientTime (ServerTime time) const
Convert time relative to the server to time relative to the game client.
ServerTime ToServerTime (ClientTime time) const
Convert time relative to the game client to time relative to the server.
Static Public Member Functions
static ClientState * GetEntityClientState (int32_t id, bool worldID=false)
Get the client state associated to the supplied entity ID.
Private Attributes
std::shared_ptr< CharacterState > mCharacterState
State of the character associated to the client.
std::unordered_map< int32_t,
std::list< std::shared_ptr
< objects::ClientCostAdjustment > > > mCostAdjustments
Map of client entity IDs to cost adjustments.
std::shared_ptr< DemonState > mDemonState
State of the active demon associated to the client which will be set to an empty Demon pointer when one is not summoned.
std::unordered_map
< libcomp::String, int32_t > mLocalObjectIDs
Map of UUIDs to game client object IDs The IDs listed here are only relevant to this client.
std::unordered_map< int32_t,
libobjgen::UUID > mLocalObjectUUIDs
Map of game client object IDs to UUIDs The IDs listed here are only relevant to this client.
std::mutex mLock
Server lock for shared resources.
int32_t mNextLocalObjectID
Next available local object ID.
std::unordered_map
< libcomp::String, int64_t > mObjectIDs
Map of UUIDs to game client object IDs.
std::unordered_map< int64_t,
libobjgen::UUID > mObjectUUIDs
Map of game client object IDs to UUIDs.
ServerTime mStartTime
Current time of the server set upon creating the client state.
Static Private Attributes
static std::unordered_map
< bool, std::unordered_map
< int32_t, ClientState * > > sEntityClients
Static registry of all client states sorted as world (true) or local entity IDs (false) and their respective IDs.
static std::mutex sLock
Static lock for shared static resources.
Detailed Description
Contains the state of a game client currently connected to the channel.
Definition at line 64 of file ClientState.h.
Constructor & Destructor Documentation
ClientState::ClientState ()
Create a new client state.
Definition at line 57 of file ClientState.cpp.
ClientState::~ClientState () virtual
Clean up the client state, removing it from the registry if it exists there.
Definition at line 64 of file ClientState.cpp.
References GetWorldCID(), mCharacterState, mDemonState, sEntityClients, and sLock.
Member Function Documentation
const libobjgen::UUID ClientState::GetAccountUID () const
Get the UID of the account associated to the client.
Returns
UID of the account associated to the client
Definition at line 297 of file ClientState.cpp.
Referenced by channel::BazaarState::AddItem(), channel::CharacterManager::AddMap(), channel::CharacterManager::AddPlugin(), channel::ActionManager::AddRemoveItems(), channel::CharacterManager::AddRemoveItems(), channel::CharacterManager::AddRemoveValuable(), AllocatePoint(), channel::MatchManager::CancelQueue(), CombineStacks(), channel::EventManager::ContinueChannelChangeEvent(), channel::SkillManager::DCM(), DemonLockSet(), channel::SkillManager::DigitalizeCancel(), channel::CharacterManager::DigitalizeStart(), DismissDemon(), DropItem(), channel::AccountManager::DumpAccount(), channel::EventManager::EndDemonQuest(), channel::ZoneManager::EndInstanceTimer(), channel::ZoneManager::EnterZone(), channel::CharacterManager::EquipItem(), channel::SkillManager::ExecuteSkill(), channel::SkillManager::ForgetAllExpertiseSkills(), channel::CharacterManager::GetDemonPacketData(), channel::ManagerConnection::GetEntityClient(), channel::FusionManager::GetResultDemon(), channel::CharacterManager::GetSynthOutcome(), channel::ZoneManager::GetZone(), channel::ChatManager::GMCommand_Enchant(), channel::ChatManager::GMCommand_ExpertiseExtend(), channel::ChatManager::GMCommand_Homepoint(), channel::ChatManager::GMCommand_Resolve(), channel::ChatManager::GMCommand_SlotAdd(), channel::ChatManager::GMCommand_Spirit(), channel::ActionManager::GrantSkills(), HandleBarter(), HandleCultureItem(), channel::ChannelServer::HandleDemonQuestReset(), channel::ChatManager::HandleGMand(), HandleShopPurchase(), HandleShopSale(), channel::FusionManager::HandleTriFusion(), channel::AccountManager::InitializeCharacter(), channel::MatchManager::JoinQueue(), channel::CharacterManager::LearnSkill(), channel::ZoneManager::MoveToZoneChannel(), channel::EventManager::OpenMenu(), channel::MatchManager::PvPInviteReply(), channel::ActionManager::RecordTimeTrial(), channel::EventManager::RequestMenu(), channel::MatchManager::RequestTeamPvPMatch(), channel::SkillManager::Respec(), channel::CharacterManager::ReunionDemon(), SaveHotbarItems(), channel::AccountManager::SendCPBalance(), channel::CharacterManager::SendDemonData(), SendStateData(), channel::ActionManager::SetHomepoint(), SplitStack(), channel::EventManager::StartWebGame(), channel::SkillManager::SummonDemon(), channel::CharacterManager::UpdateBP(), channel::ActionManager::UpdateCOMP(), UpdateDemonSkill(), channel::CharacterManager::UpdateDurability(), channel::CharacterManager::UpdateEventCounter(), channel::CharacterManager::UpdateExpertisePoints(), channel::CharacterManager::UpdateFamiliarity(), channel::CharacterManager::UpdateItems(), channel::CharacterManager::UpdateLNC(), channel::ActionManager::UpdatePoints(), channel::EventManager::UpdateQuest(), channel::EventManager::UpdateQuestKillCount(), channel::CharacterManager::UpdateSkillPoints(), and channel::CharacterManager::UpdateSoulPoints().
std::shared_ptr< BazaarState > ClientState::GetBazaarState ()
Get the bazaar associated to the client account's open market if one exists and the client is currently in the same zone as the bazaar.
Returns
Pointer to the matching bazaar state, null if no match exists
Definition at line 111 of file ClientState.cpp.
References mCharacterState.
Referenced by channel::BazaarState::DropItemFromMarket(), channel::ZoneManager::LeaveZone(), and channel::EventManager::OpenMenu().
std::shared_ptr< CharacterState > ClientState::GetCharacterState ()
Get the state of the character associated to the client.
Returns
Pointer to the CharacterState
Definition at line 84 of file ClientState.cpp.
References mCharacterState.
Referenced by channel::Zone::AddConnection(), channel::CharacterManager::AddMap(), channel::CharacterManager::AddPlugin(), channel::ActionManager::AddRemoveItems(), channel::CharacterManager::AddRemoveItems(), channel::CharacterManager::AddRemoveOpponent(), channel::ActionManager::AddRemoveStatus(), channel::CharacterManager::AddRemoveValuable(), channel::CharacterManager::AddTitle(), channel::CharacterManager::AdjustMitamaStats(), AllocatePoint(), channel::SkillManager::ApplyZoneSpecificEffects(), channel::TokuseiManager::CalculateAttributeValue(), channel::CharacterManager::CalculateItemRemoval(), channel::CharacterManager::CalculateMaccaPayment(), channel::SkillManager::Cameo(), channel::CharacterManager::CancelMount(), channel::CharacterManager::CancelStatusEffects(), channel::ChannelSyncManager::Update< objects::StatusEffect >(), CombineStacks(), channel::MatchManager::CompleteBaseCapture(), channel::CharacterManager::ContractDemon(), channel::CharacterManager::CultureItemPickup(), channel::SkillManager::DCM(), channel::ActionManager::Delay(), DemonLockSet(), channel::SkillManager::DetermineCosts(), channel::SkillManager::Digitalize(), channel::SkillManager::DigitalizeCancel(), channel::CharacterManager::DigitalizeEnd(), channel::CharacterManager::DigitalizeStart(), DismissDemon(), DropItem(), channel::BazaarState::DropItemInternal(), channel::EventManager::EndDemonQuest(), channel::FusionManager::EndExchange(), channel::ZoneManager::EndInstanceTimer(), channel::MatchManager::EndUltimateBattlePhase(), channel::EventManager::EndWebGame(), channel::MatchManager::EnterPvP(), channel::MatchManager::EnterUltimateBattle(), channel::ZoneManager::EnterZone(), channel::CharacterManager::EquipItem(), channel::EventManager::EvaluateEventCondition(), channel::EventManager::EvaluateQuestCondition(), channel::EventManager::EvaluateQuestPhaseRequirements(), channel::TokuseiManager::EvaluateTokuseiCondition(), channel::SkillManager::EvaluateTokuseiSkillCondition(), ExtractReunionPoints(), channel::SkillManager::FamiliarityUp(), channel::SkillManager::FinalizeSkillExecution(), channel::SkillManager::ForgetAllExpertiseSkills(), channel::TokuseiManager::GetAllTokuseiEntities(), channel::CharacterManager::GetDemonBox(), channel::CharacterManager::GetItemBox(), channel::MatchManager::GetPvPData(), channel::FusionManager::GetResultDemon(), channel::AIManager::GetSharedAggroEntity(), channel::SkillManager::GetSummonSpeed(), channel::CharacterManager::GetSynthOutcome(), channel::ChatManager::GetTargetCharacterAccount(), channel::ChatManager::GMCommand_Bethel(), channel::ChatManager::GMCommand_Cowrie(), channel::ChatManager::GMCommand_Effect(), channel::ChatManager::GMCommand_Enchant(), channel::ChatManager::GMCommand_Enemy(), channel::ChatManager::GMCommand_Event(), channel::ChatManager::GMCommand_ExpertiseExtend(), channel::ChatManager::GMCommand_ExpertiseSet(), channel::ChatManager::GMCommand_Homepoint(), channel::ChatManager::GMCommand_Kill(), channel::ChatManager::GMCommand_LevelUp(), channel::ChatManager::GMCommand_PenaltyReset(), channel::ChatManager::GMCommand_Position(), channel::ChatManager::GMCommand_Skill(), channel::ChatManager::GMCommand_SlotAdd(), channel::ChatManager::GMCommand_Speed(), channel::ChatManager::GMCommand_Spirit(), channel::ChatManager::GMCommand_Tokusei(), channel::ChatManager::GMCommand_XP(), channel::ChatManager::GMCommand_Zone(), channel::ActionManager::GrantSkills(), channel::ActionManager::GrantXP(), HandleBarter(), HandleCultureItem(), channel::ZoneManager::HandleDeathTimeOut(), channel::SkillManager::HandleDigitalizeXP(), channel::ChatManager::HandleGMand(), channel::AccountManager::HandleLoginResponse(), HandleMitamaReset(), HandleMitamaReunion(), channel::EventManager::HandleNext(), channel::EventManager::HandleResponse(), HandleShopPurchase(), HandleShopSale(), channel::ZoneManager::HandleSpecialInstancePopulate(), channel::FusionManager::HandleTriFusion(), channel::EventManager::HandleTriFusion(), channel::EventManager::HandleWebGame(), InjectReunionPoints(), channel::CharacterManager::LearnSkill(), channel::MatchManager::LeaveBase(), channel::ZoneManager::LeaveZone(), channel::MatchManager::LoadPentalphaData(), channel::MatchManager::LoadUltimateBattleData(), channel::AccountManager::Logout(), channel::SkillManager::Mooch(), channel::SkillManager::Mount(), channel::ZoneManager::MoveToInstance(), channel::ZoneManager::MoveToZoneChannel(), channel::ZoneManager::MultiZoneBossKilled(), channel::Zone::OccupyPvPBase(), channel::CharacterManager::PayMacca(), channel::ActionManager::PerformActions(), channel::AccountManager::PrepareChannelChange(), channel::SkillManager::PrepareFusionSkill(), channel::FusionManager::ProcessFusion(), channel::MatchManager::PvPInviteReply(), channel::SkillManager::RandomItem(), channel::TokuseiManager::RecalcTimedTokusei(), channel::TokuseiManager::Recalculate(), channel::TokuseiManager::RecalculateParty(), channel::ActionManager::RecordTimeTrial(), channel::Zone::RemoveConnection(), channel::EventManager::ResetDemonQuests(), channel::SkillManager::Respec(), channel::CharacterManager::ReunionDemon(), channel::CharacterManager::ReviveCharacter(), channel::ActionManager::RunScript(), SaveHotbarItems(), channel::ZoneManager::SendAccessMessage(), channel::EventManager::SendActiveQuestList(), channel::CharacterManager::SendAutoRecovery(), channel::CharacterManager::SendCharacterData(), channel::CharacterManager::SendCharacterTitle(), channel::ChatManager::SendChatMessage(), SendClientReadyData(), channel::CharacterManager::SendCoinTotal(), channel::EventManager::SendCompletedQuestList(), channel::CharacterManager::SendCowrieBethel(), channel::CharacterManager::SendDemonBoxData(), channel::CharacterManager::SendDemonData(), SendDemonQuestData(), channel::MatchManager::SendDiasporaLocation(), SendEquipmentList(), channel::CharacterManager::SendExpertiseExtension(), channel::CharacterManager::SendFusionGauge(), SendHotbarData(), channel::CharacterManager::SendInvokeStatus(), channel::CharacterManager::SendItemBoxData(), channel::CharacterManager::SendLootItemData(), channel::CharacterManager::SendMapFlags(), channel::CharacterManager::SendMaterials(), channel::CharacterManager::SendOtherCharacterData(), channel::CharacterManager::SendOtherPartnerData(), channel::CharacterManager::SendPartnerData(), channel::CharacterManager::SendPluginFlags(), channel::ZoneManager::SendPopulateZoneData(), channel::CharacterManager::SendPvPCharacterInfo(), SendStateData(), channel::ChatManager::SendTellMessage(), channel::ZoneManager::SendToRange(), channel::CharacterManager::SendValuableFlags(), channel::ActionManager::SetHomepoint(), channel::CharacterManager::SetStatusIcon(), SplitStack(), channel::MatchManager::StartPvPBaseCapture(), channel::Zone::StartStopCombat(), channel::CharacterManager::StoreDemon(), channel::SkillManager::StoreDemon(), channel::CharacterManager::SummonDemon(), channel::SkillManager::SummonDemon(), channel::SkillManager::Traesto(), channel::ActionManager::TransformAction(), channel::EventManager::TransformEvent(), channel::CharacterManager::UnequipItem(), channel::CharacterManager::UpdateBethel(), channel::CharacterManager::UpdateBP(), channel::CharacterManager::UpdateCoinTotal(), channel::ActionManager::UpdateCOMP(), channel::CharacterManager::UpdateCowrieBethel(), channel::ZoneManager::UpdateDeathTimeOut(), channel::EventManager::UpdateDemonQuestCount(), UpdateDemonSkill(), channel::DemonState::UpdateDemonState(), channel::CharacterManager::UpdateDigitalizePoints(), channel::CharacterManager::UpdateDurability(), channel::CharacterManager::UpdateEventCounter(), channel::CharacterManager::UpdateExperience(), channel::CharacterManager::UpdateExpertise(), channel::CharacterManager::UpdateExpertisePoints(), channel::CharacterManager::UpdateFamiliarity(), channel::CharacterManager::UpdateFusionGauge(), channel::CharacterManager::UpdateItems(), channel::CharacterManager::UpdateLNC(), channel::TokuseiManager::UpdateMovementDecay(), channel::ActionManager::UpdatePoints(), channel::MatchManager::UpdatePvPPoints(), channel::SkillManager::UpdatePvPStats(), channel::EventManager::UpdateQuest(), channel::EventManager::UpdateQuestKillCount(), channel::EventManager::UpdateQuestTargetEnemies(), channel::CharacterManager::UpdateSkillPoints(), channel::CharacterManager::UpdateSoulPoints(), channel::ZoneManager::UpdateTrackedTeam(), channel::ZoneManager::UpdateTrackedZone(), channel::ActionManager::UpdateZoneFlags(), channel::ActionManager::UpdateZoneInstance(), channel::SkillManager::ValidateActivationItem(), channel::SkillManager::XPUp(), and channel::ActionManager::ZoneChange().
int32_t ClientState::GetClanID () const
Get the current clan ID associated to the logged in character.
Returns
Current character's clan ID
Definition at line 324 of file ClientState.cpp.
Referenced by channel::ChatManager::SendChatMessage().
libcomp::Convert::Encoding_t ClientState::GetClientStringEncoding ()
Get the string encoding to use for this client.
Returns
Encoding to use for strings
Todo:
: Return UTF-8 for US Client
Definition at line 78 of file ClientState.cpp.
Referenced by channel::EventManager::OpenMenu(), channel::ChatManager::SendChatMessage(), channel::ZoneManager::SendPopulateZoneData(), channel::ChatManager::SendTellMessage(), and channel::MatchManager::SendUltimateBattleRankings().
std::list< std::shared_ptr< objects::ClientCostAdjustment > > ClientState::GetCostAdjustments (int32_t entityID)
Get a client entity's current cost adjustments.
Parameters
entityID Entity ID associated to the client
Returns
List of adjustments that are currently applied to the entity
Definition at line 503 of file ClientState.cpp.
References mCostAdjustments, and mLock.
Referenced by channel::TokuseiManager::SendCostAdjustments().
int32_t ClientState::GetCurrentMenuShopID (int32_t type = 0) const
Get the shop ID of the state's current event if it is an "open menu" type, optionally matching a specified type only.
Parameters
type Optional required menu type to match against the event
Returns
Shop ID or 0 if not applicable
Definition at line 174 of file ClientState.cpp.
Referenced by channel::BazaarState::DropItemFromMarket(), HandleBarter(), HandleMitamaReset(), HandleShopPurchase(), HandleShopSale(), channel::EventManager::HandleWebGame(), and channel::EventManager::RequestMenu().
std::shared_ptr< DemonState > ClientState::GetDemonState ()
Get the state of the active demon associated to the client.
If there is no active demon, a state will still be returned but no demon will be set.
Returns
Pointer to the DemonState
Definition at line 89 of file ClientState.cpp.
References mDemonState.
Referenced by channel::Zone::AddConnection(), channel::CharacterManager::AddRemoveOpponent(), channel::ActionManager::AddRemoveStatus(), channel::CharacterManager::AddRemoveValuable(), channel::TokuseiManager::CalculateAttributeValue(), channel::CharacterManager::CancelMount(), channel::CharacterManager::CancelStatusEffects(), channel::SkillManager::DCM(), DismissDemon(), channel::ZoneManager::EndInstanceTimer(), channel::MatchManager::EnterPvP(), channel::MatchManager::EnterUltimateBattle(), channel::ZoneManager::EnterZone(), channel::EventManager::EvaluateCondition(), channel::EventManager::EvaluateEventCondition(), channel::EventManager::EvaluatePartnerCondition(), channel::EventManager::EvaluateQuestPhaseRequirements(), channel::TokuseiManager::EvaluateTokuseiCondition(), channel::SkillManager::EvaluateTokuseiSkillCondition(), ExtractReunionPoints(), channel::SkillManager::FamiliarityUp(), channel::SkillManager::FamiliarityUpItem(), channel::SkillManager::ForgetAllExpertiseSkills(), channel::TokuseiManager::GetAllTokuseiEntities(), channel::FusionManager::GetResultDemon(), channel::AIManager::GetSharedAggroEntity(), channel::CharacterManager::GetSynthOutcome(), channel::ChatManager::GMCommand_Effect(), channel::ChatManager::GMCommand_LevelUp(), channel::ChatManager::GMCommand_Position(), channel::ChatManager::GMCommand_Reunion(), channel::ChatManager::GMCommand_Skill(), channel::ChatManager::GMCommand_Speed(), channel::ChatManager::GMCommand_Tokusei(), channel::ChatManager::GMCommand_XP(), channel::ActionManager::GrantSkills(), channel::ActionManager::GrantXP(), HandleBarter(), HandleCultureItem(), channel::ZoneManager::HandleDeathTimeOut(), channel::AccountManager::HandleLoginResponse(), HandleMitamaReset(), HandleMitamaReunion(), channel::EventManager::HandleNext(), InjectReunionPoints(), channel::CharacterManager::LearnSkill(), channel::ZoneManager::LeaveZone(), channel::SkillManager::Mooch(), channel::SkillManager::Mount(), channel::SkillManager::PrepareFusionSkill(), channel::SkillManager::ProcessSkillResult(), channel::TokuseiManager::Recalculate(), channel::TokuseiManager::RecalculateParty(), channel::ZoneInstance::RefreshPlayerState(), channel::Zone::RemoveConnection(), channel::CharacterManager::ReunionDemon(), channel::CharacterManager::ReviveCharacter(), channel::ActionManager::RunScript(), channel::CharacterManager::SendDemonData(), channel::CharacterManager::SendOtherCharacterData(), channel::CharacterManager::SendOtherPartnerData(), channel::CharacterManager::SendPartnerData(), channel::ZoneManager::SendPopulateZoneData(), channel::Zone::StartStopCombat(), channel::CharacterManager::StoreDemon(), channel::SkillManager::StoreDemon(), channel::CharacterManager::SummonDemon(), channel::SkillManager::SummonDemon(), channel::ActionManager::TransformAction(), channel::EventManager::TransformEvent(), channel::ActionManager::UpdateCOMP(), channel::ZoneManager::UpdateDeathTimeOut(), UpdateDemonSkill(), channel::CharacterManager::UpdateExperience(), channel::CharacterManager::UpdateExpertisePoints(), channel::CharacterManager::UpdateFamiliarity(), channel::CharacterManager::UpdateSoulPoints(), channel::ActionManager::UpdateZoneFlags(), channel::SkillManager::XPUp(), and channel::ActionManager::ZoneChange().
ClientState * ClientState::GetEntityClientState (int32_t id, bool worldID = false) static
Get the client state associated to the supplied entity ID.
Parameters
id Entity ID or world ID associated to the client state to retrieve
worldID true if the ID is from the world, false if it is a local entity ID
Returns
Pointer to the client state associated to the ID or nullptr if it does not exist
Definition at line 421 of file ClientState.cpp.
References sEntityClients, and sLock.
Referenced by channel::CharacterState::ActionCooldownActive(), channel::CharacterManager::AddRemoveOpponent(), channel::CharacterManager::AdjustMitamaStats(), channel::SkillManager::ApplyZoneSpecificEffects(), channel::TokuseiManager::CalculateAttributeValue(), channel::MatchManager::CompleteBaseCapture(), channel::MatchManager::EnterPvP(), channel::EventManager::EvaluateCondition(), channel::TokuseiManager::EvaluateTokuseiCondition(), channel::SkillManager::EvaluateTokuseiSkillCondition(), channel::TokuseiManager::GetAllTokuseiEntities(), channel::ManagerConnection::GetEntityClient(), channel::CharacterState::GetEventCounter(), channel::AIManager::GetSharedAggroEntity(), channel::ActiveEntityState::GetWorldCID(), channel::SkillManager::HandleKills(), channel::SkillManager::HandleRevives(), channel::ActiveEntityState::HasActiveEvent(), channel::Zone::OccupyPvPBase(), channel::ActionManager::PerformActions(), channel::MatchManager::PlayerKilled(), channel::SkillManager::ProcessSkillResult(), channel::SkillManager::ProcessSkillResultFinal(), QueuePartyMemberInfo(), channel::TokuseiManager::RecalcCostAdjustments(), channel::TokuseiManager::RecalcTimedTokusei(), channel::TokuseiManager::Recalculate(), channel::TokuseiManager::RecalculateParty(), channel::CharacterState::RefreshActionCooldowns(), channel::ActiveEntityState::RemoveStatusEffects(), channel::ActionManager::RunScript(), channel::SkillManager::SkillRestricted(), channel::Zone::StartStopCombat(), channel::ActionManager::TransformAction(), channel::EventManager::TransformEvent(), channel::DemonState::UpdateDemonState(), channel::MatchManager::UpdatePvPPoints(), channel::SkillManager::UpdatePvPStats(), channel::DemonState::UpdateSharedState(), channel::CharacterManager::UpdateWorldDisplayState(), channel::ActionManager::UpdateZoneFlags(), channel::ActionManager::UpdateZoneInstance(), channel::SkillManager::ValidateActivationItem(), and channel::SkillManager::ValidateSkillTarget().
std::shared_ptr< ActiveEntityState > ClientState::GetEntityState (int32_t entityID, bool readyOnly = true)
Get the entity state associated to an entity ID for this client.
Parameters
entityID Entity ID associated to this client to retrieve
readyOnly Optional parameter to only return entities currently set, defaults to false
Returns
Pointer to the matching entity state, null if no match exists
Definition at line 94 of file ClientState.cpp.
References mCharacterState, mDemonState, and channel::state().
Referenced by IsMovementLocked(), channel::CharacterManager::LearnSkill(), channel::CharacterManager::LevelUp(), channel::CharacterManager::SendEntityStats(), and channel::CharacterManager::UpdateExperience().
int32_t ClientState::GetEventSourceEntityID () const
Get the source entity ID of the state's current event if it exists.
Returns
Entity ID or 0 if not applicable
Definition at line 166 of file ClientState.cpp.
Referenced by channel::MatchManager::LeaveBase().
int32_t ClientState::GetLocalObjectID (const libobjgen::UUID & uuid)
Get the local object ID associated to a UUID associated to the client.
If a zero is returned, the UUID is not registered.
Parameters
uuid UUID to retrieve the corresponding object ID from
Returns
Local object ID associated to a UUID
Definition at line 241 of file ClientState.cpp.
References mLocalObjectIDs, mLocalObjectUUIDs, mLock, and mNextLocalObjectID.
const libobjgen::UUID ClientState::GetLocalObjectUUID (int32_t objectID)
Get the UUID associated to an object ID associated to the client.
If a null UUID is returned, the object ID is not registered.
Parameters
objectID Object ID to retrieve the corresponding UUID from
Returns
UUID associated to an object ID contextual to the client
Definition at line 259 of file ClientState.cpp.
References mLocalObjectUUIDs, and mLock.
int64_t ClientState::GetObjectID (const libobjgen::UUID & uuid)
Get the object ID associated to a UUID associated to the client.
If a zero is returned, the UUID is not registered.
Parameters
uuid UUID to retrieve the corresponding object ID from
Returns
Object ID associated to a UUID
Definition at line 215 of file ClientState.cpp.
References mLock, and mObjectIDs.
Referenced by channel::CharacterManager::AddRemoveItems(), channel::CharacterManager::DigitalizeEnd(), channel::CharacterManager::DigitalizeStart(), channel::CharacterManager::EquipItem(), ExtractReunionPoints(), channel::SkillManager::FinalizeSkillExecution(), channel::CharacterManager::GetDemonPacketData(), channel::ChatManager::GMCommand_Reunion(), channel::AccountManager::InitializeCharacter(), InjectReunionPoints(), channel::FusionManager::ProcessFusion(), channel::EventManager::ResetDemonQuests(), channel::CharacterManager::SendCharacterData(), SendClientReadyData(), channel::CharacterManager::SendDemonData(), SendEquipmentList(), SendHotbarData(), channel::CharacterManager::SendItemBoxData(), channel::CharacterManager::SendPartnerData(), SendStateData(), channel::SkillManager::StoreDemon(), channel::CharacterManager::UnequipItem(), and channel::CharacterManager::UpdateExperience().
const libobjgen::UUID ClientState::GetObjectUUID (int64_t objectID)
Get the UUID associated to an object ID associated to the client.
If a null UUID is returned, the object ID is not registered.
Parameters
objectID Object ID to retrieve the corresponding UUID from
Returns
UUID associated to an object ID
Definition at line 229 of file ClientState.cpp.
References mLock, and mObjectUUIDs.
Referenced by channel::BazaarState::AddItem(), channel::CharacterManager::AddRemoveItems(), DemonLockSet(), channel::SkillManager::DetermineCosts(), DismissDemon(), DropItem(), channel::BazaarState::DropItemInternal(), channel::CharacterManager::EquipItem(), channel::FusionManager::GetResultDemon(), channel::SkillManager::GetSummonSpeed(), HandleCultureItem(), HandleMitamaReunion(), channel::EventManager::HandleResponse(), HandleShopSale(), channel::FusionManager::HandleTriFusion(), channel::CharacterManager::MitamaDemon(), channel::SkillManager::PrepareFusionSkill(), channel::FusionManager::ProcessFusion(), channel::CharacterManager::ReunionDemon(), SaveHotbarItems(), SendDemonQuestData(), channel::SkillManager::SkillRestricted(), channel::CharacterManager::SummonDemon(), channel::SkillManager::SummonDemon(), and channel::BazaarState::TryBuyItem().
std::shared_ptr< objects::PartyCharacter > ClientState::GetPartyCharacter (bool includeDemon) const
Get a current party character representation from the .associated CharacterState.
Parameters
includeDemon true if the demon state is set on the member variable of the party character
Returns
Pointer to a party character representation
Definition at line 334 of file ClientState.cpp.
References GetPartyDemon(), GetWorldCID(), and mCharacterState.
Referenced by GetPartyCharacterPacket(), and SendStateData().
void ClientState::GetPartyCharacterPacket (libcomp::Packet & p) const
Populate the supplied packet with an internal CharacterLogin packet containing character information.
Parameters
p Packet to populate
Definition at line 377 of file ClientState.cpp.
References GetPartyCharacter(), GetWorldCID(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteU8().
std::shared_ptr< objects::PartyMember > ClientState::GetPartyDemon () const
Get a current party demon representation from the associated DemonState.
Returns
Pointer to a party demon representation
Definition at line 360 of file ClientState.cpp.
References mDemonState.
Referenced by GetPartyCharacter(), GetPartyDemonPacket(), and SendStateData().
void ClientState::GetPartyDemonPacket (libcomp::Packet & p) const
Populate the supplied packet with an internal CharacterLogin packet containing partner demon information.
Parameters
p Packet to populate
Definition at line 385 of file ClientState.cpp.
References GetPartyDemon(), GetWorldCID(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteU8().
Referenced by channel::CharacterManager::StoreDemon(), and channel::CharacterManager::SummonDemon().
uint32_t ClientState::GetPartyID () const
Get the current party ID associated to the logged in character.
Returns
Current character's party ID
Definition at line 319 of file ClientState.cpp.
Referenced by channel::SkillManager::ProcessSkillResult(), channel::ChatManager::SendChatMessage(), SendStateData(), channel::CharacterManager::StoreDemon(), and channel::CharacterManager::SummonDemon().
int32_t ClientState::GetTeamID () const
Get the current team ID associated to the logged in character.
Returns
Current character's team ID
Definition at line 329 of file ClientState.cpp.
Referenced by channel::ChatManager::SendChatMessage(), SendStateData(), and channel::ChatManager::SendTeamChatMessage().
int32_t ClientState::GetUserLevel () const
Get the user level of the account associated to the client.
Returns
User level of the account associated to the client
Definition at line 302 of file ClientState.cpp.
Referenced by AuthenticateAccount(), and channel::ChatManager::HandleGMand().
int32_t ClientState::GetWorldCID () const
Get the current world CID associated to the logged in character.
Returns
Current character's world CID
Definition at line 308 of file ClientState.cpp.
Referenced by channel::Zone::AddConnection(), channel::TokuseiManager::CalculateAttributeValue(), channel::MatchManager::CancelQueue(), channel::ZoneManager::CanEnterRestrictedZone(), channel::MatchManager::CleanupPendingMatch(), channel::MatchManager::ConfirmMatch(), channel::MatchManager::EndUltimateBattlePhase(), channel::EventManager::EndWebGame(), channel::MatchManager::EnterPvP(), channel::MatchManager::EnterUltimateBattle(), channel::ZoneManager::EnterZone(), channel::EventManager::EvaluateCondition(), channel::EventManager::EvaluateEventCondition(), channel::TokuseiManager::EvaluateTokuseiCondition(), channel::ZoneManager::FailPlasma(), channel::ActionManager::GetActionContextCIDs(), channel::TokuseiManager::GetAllTokuseiEntities(), channel::ZoneManager::GetMatchStartPosition(), GetPartyCharacter(), GetPartyCharacterPacket(), GetPartyDemonPacket(), channel::ActiveEntityState::GetWorldCID(), channel::ChatManager::GMCommand_Instance(), channel::ChatManager::GMCommand_Ziotite(), channel::EventManager::HandleWebGame(), channel::MatchManager::JoinQueue(), channel::MatchManager::LeaveTeam(), channel::MatchManager::LeaveUltimateBattle(), channel::ZoneManager::LeaveZone(), channel::AccountManager::Logout(), channel::ZoneManager::MoveToInstance(), channel::ZoneManager::MoveToZoneChannel(), channel::SkillManager::ProcessSkillResultFinal(), channel::MatchManager::PvPInviteReply(), channel::TokuseiManager::Recalculate(), Register(), channel::Zone::RemoveConnection(), channel::MatchManager::RequestTeamPvPMatch(), channel::ChatManager::SendChatMessage(), channel::ZoneManager::SendDestinyBox(), channel::MatchManager::SendDiasporaLocation(), channel::CharacterManager::SendLootItemData(), channel::ZoneManager::SendPopulateZoneData(), SendStateData(), channel::ChatManager::SendTellMessage(), channel::MatchManager::SendUltimateBattleMembers(), channel::MatchManager::SpectatingMatch(), channel::ActionManager::UpdatePoints(), channel::ZoneManager::UpdateTrackedZone(), channel::MatchManager::UpdateUBPoints(), channel::ActionManager::UpdateZoneInstance(), and ~ClientState().
std::shared_ptr< Zone > ClientState::GetZone () const
Get the character's current zone.
Returns
Current character's zone
Definition at line 313 of file ClientState.cpp.
References mCharacterState.
Referenced by channel::CharacterManager::CancelStatusEffects(), channel::MatchManager::CompleteBaseCapture(), channel::EventManager::ContinueChannelChangeEvent(), channel::SkillManager::DetermineCosts(), channel::ZoneManager::EndInstanceTimer(), channel::MatchManager::EnterPvP(), channel::EventManager::EvaluateCondition(), channel::TokuseiManager::EvaluateTokuseiCondition(), channel::ZoneManager::FailPlasma(), channel::TokuseiManager::GetAllTokuseiEntities(), channel::ZoneManager::GetMatchStartPosition(), channel::ManagerConnection::GetPartyConnections(), channel::ChatManager::GMCommand_Event(), channel::ChatManager::GMCommand_Instance(), channel::ZoneManager::HandleDeathTimeOut(), channel::SkillManager::HandleDigitalizeXP(), channel::SkillManager::HandleKills(), channel::MatchManager::LeaveBase(), channel::ZoneManager::LeaveZone(), channel::ZoneManager::MoveToInstance(), channel::ZoneManager::MoveToLobby(), channel::ZoneManager::MoveToZoneChannel(), channel::Zone::OccupyPvPBase(), channel::EventManager::OpenMenu(), channel::AccountManager::PrepareChannelChange(), channel::SkillManager::PrepareFusionSkill(), channel::CharacterManager::ReviveCharacter(), channel::ChatManager::SendChatMessage(), channel::ZoneManager::SendDestinyBox(), channel::MatchManager::StartPvPBaseCapture(), channel::EventManager::StartWebGame(), channel::ZoneManager::UpdateDeathTimeOut(), channel::ZoneManager::UpdateTrackedTeam(), channel::MatchManager::UpdateUBPoints(), channel::MatchManager::ValidateMatchEntries(), and channel::SkillManager::ValidateSkillTarget().
bool ClientState::HasActiveEvent () const
Check if the state has a current event associated to it.
Auto-only events do not apply here
Returns
true if an event exists, false if one does not
Definition at line 158 of file ClientState.cpp.
Referenced by channel::ActiveEntityState::HasActiveEvent().
bool ClientState::IsMovementLocked (int32_t entityID)
Determine if the entity associated to the client has its movements locked based upon system processes or events being active.
Parameters
entityID Entity ID associated to this client to check
Returns
true if movement is locked, false if it is not
Definition at line 133 of file ClientState.cpp.
References GetEntityState().
bool ClientState::Register ()
Registers the client state with the static entity map for access by other clients.
Returns
true if the state was registered properly, otherwise false
Definition at line 191 of file ClientState.cpp.
References GetWorldCID(), mCharacterState, mDemonState, sEntityClients, and sLock.
Referenced by channel::AccountManager::HandleLoginResponse().
bool ClientState::RewindStartTime (ServerTime time)
Moves the client state start time back to the supplied time if it is currently later.
This is necessary to correct active timers in the client's starting zone but it should ONLY be called before the time has been communicated to the client (so before login completes).
Parameters
time Time to rewind to if start time is later
Returns
true if the time was rewound, false if it was not
Definition at line 408 of file ClientState.cpp.
References mStartTime.
std::list< std::shared_ptr< objects::ClientCostAdjustment > > ClientState::SetCostAdjustments (int32_t entityID, std::list< std::shared_ptr< objects::ClientCostAdjustment >> adjustments)
Set a client entity's cost adjustments and return the newly modified values.
If a cost adjustment was removed, a default cost will adjustment will be generated and returned.
Parameters
entityID Entity ID associated to the client
adjustments List of cost adjustments
Returns
List of adjustments that are now applied to the entity
Definition at line 430 of file ClientState.cpp.
References mCostAdjustments, and mLock.
Referenced by channel::TokuseiManager::RecalcCostAdjustments().
bool ClientState::SetObjectID (const libobjgen::UUID & uuid, int64_t objectID, bool allowReset = false)
Set the object ID associated a UUID associated to the client.
Parameters
uuid UUID to set the corresponding object ID for
objectID Object ID to map to the UUID
allowReset Optional parameter to allow the UUID to be cleared and registered again if it already exists
Returns
true if the UUID was registered, false if it was not
Definition at line 271 of file ClientState.cpp.
References mLock, mObjectIDs, and mObjectUUIDs.
Referenced by channel::CharacterManager::ContractDemon(), channel::AccountManager::InitializeCharacter(), channel::FusionManager::ProcessFusion(), channel::CharacterManager::SendItemBoxData(), and SplitStack().
ClientTime ClientState::ToClientTime (ServerTime time) const
Convert time relative to the server to time relative to the game client.
Parameters
time Time relative to the server
Returns
Time relative to the client
Definition at line 393 of file ClientState.cpp.
References mStartTime.
Referenced by channel::ZoneManager::EndInstanceTimer(), channel::MatchManager::EnterPvP(), SendClientReadyData(), channel::CharacterManager::SendLootItemData(), channel::ChannelClientConnection::SendRelativeTimePacket(), and channel::MatchManager::UpdatePvPMatches().
ServerTime ClientState::ToServerTime (ClientTime time) const
Convert time relative to the game client to time relative to the server.
Parameters
time Time relative to the client
Returns
Time relative to the server
Definition at line 403 of file ClientState.cpp.
References mStartTime.
Member Data Documentation
std::shared_ptr<CharacterState> channel::ClientState::mCharacterState private
State of the character associated to the client.
Definition at line 341 of file ClientState.h.
Referenced by GetBazaarState(), GetCharacterState(), GetEntityState(), GetPartyCharacter(), GetZone(), Register(), and ~ClientState().
std::unordered_map<int32_t, std::list< std::shared_ptr<objects::ClientCostAdjustment> > > channel::ClientState::mCostAdjustments private
Map of client entity IDs to cost adjustments.
Definition at line 363 of file ClientState.h.
Referenced by GetCostAdjustments(), and SetCostAdjustments().
std::shared_ptr<DemonState> channel::ClientState::mDemonState private
State of the active demon associated to the client which will be set to an empty Demon pointer when one is not summoned.
Definition at line 345 of file ClientState.h.
Referenced by GetDemonState(), GetEntityState(), GetPartyDemon(), Register(), and ~ClientState().
std::unordered_map<libcomp::String, int32_t> channel::ClientState::mLocalObjectIDs private
Map of UUIDs to game client object IDs The IDs listed here are only relevant to this client.
Definition at line 355 of file ClientState.h.
Referenced by GetLocalObjectID().
std::unordered_map<int32_t, libobjgen::UUID> channel::ClientState::mLocalObjectUUIDs private
Map of game client object IDs to UUIDs The IDs listed here are only relevant to this client.
Definition at line 359 of file ClientState.h.
Referenced by GetLocalObjectID(), and GetLocalObjectUUID().
std::mutex channel::ClientState::mLock private
Server lock for shared resources.
Definition at line 373 of file ClientState.h.
Referenced by GetCostAdjustments(), GetLocalObjectID(), GetLocalObjectUUID(), GetObjectID(), GetObjectUUID(), SetCostAdjustments(), and SetObjectID().
int32_t channel::ClientState::mNextLocalObjectID private
Next available local object ID.
Definition at line 370 of file ClientState.h.
Referenced by GetLocalObjectID().
std::unordered_map<libcomp::String, int64_t> channel::ClientState::mObjectIDs private
Map of UUIDs to game client object IDs.
Definition at line 348 of file ClientState.h.
Referenced by GetObjectID(), and SetObjectID().
std::unordered_map<int64_t, libobjgen::UUID> channel::ClientState::mObjectUUIDs private
Map of game client object IDs to UUIDs.
Definition at line 351 of file ClientState.h.
Referenced by GetObjectUUID(), and SetObjectID().
ServerTime channel::ClientState::mStartTime private
Current time of the server set upon creating the client state.
Definition at line 367 of file ClientState.h.
Referenced by RewindStartTime(), ToClientTime(), and ToServerTime().
std::unordered_map< bool, std::unordered_map< int32_t, ClientState * > > ClientState::sEntityClients static private
Static registry of all client states sorted as world (true) or local entity IDs (false) and their respective IDs.
Definition at line 335 of file ClientState.h.
Referenced by GetEntityClientState(), Register(), and ~ClientState().
std::mutex ClientState::sLock static private
Static lock for shared static resources.
Definition at line 338 of file ClientState.h.
Referenced by GetEntityClientState(), Register(), and ~ClientState().
The documentation for this class was generated from the following files:
ClientState.h
ClientState.cpp