COMP_hack: channel::EventManager Class Reference
channel::EventManager Class Reference
Manager class in charge of processing event sequences as well as quest phase progression and condition evaluation.
#include <EventManager.h>
Classes
struct EventContext
Public Member Functions
EventManager (const std::weak_ptr< ChannelServer > &server)
Create a new EventManager.
~EventManager ()
Clean up the EventManager.
bool ContinueChannelChangeEvent (const std::shared_ptr< ChannelClientConnection > &client)
Continue an event that was in progress when the supplied client changed from another channel to the current one.
int8_t EndDemonQuest (const std::shared_ptr< ChannelClientConnection > &client, int8_t failCode=2)
End the client's demon quest in success or failure.
void EndWebGame (const std::shared_ptr< ChannelClientConnection > &client, bool notifyWorld)
End any web-game session currently active for the client.
bool EvaluateEventConditions (const std::shared_ptr< Zone > &zone, const std::list< std::shared_ptr< objects::EventCondition >> &conditions, const std::shared_ptr< ChannelClientConnection > &client=nullptr)
Evaluate a list of event conditions for a client.
std::shared_ptr
< objects::DemonQuest > GenerateDemonQuest (const std::shared_ptr< CharacterState > &cState, const std::shared_ptr< objects::Demon > &demon)
Generate a demon quest for the supplied character and demon.
bool HandleEvent (const std::shared_ptr< ChannelClientConnection > &client, const libcomp::String &eventID, int32_t sourceEntityID, const std::shared_ptr< Zone > &zone=nullptr, EventOptions options={})
Handle a new event based upon the supplied ID, relative to an optional entity.
bool HandleEvent (const std::shared_ptr< ChannelClientConnection > &client, const std::shared_ptr< objects::EventInstance > &instance)
Handle an event instance by branching into the appropriate handler function after updating the character's overhead icon if needed.
bool HandleResponse (const std::shared_ptr< ChannelClientConnection > &client, int32_t responseID, int64_t objectID=-1)
React to a response based on the current event of a client.
int32_t InterruptEvent (const std::shared_ptr< ChannelClientConnection > &client)
Stop the client's current event and return the source entity ID if one existed.
std::shared_ptr
< objects::EventInstance > PrepareEvent (const libcomp::String &eventID, int32_t sourceEntityID)
Prepare a new event based upon the supplied ID, relative to an optional entity.
bool RequestMenu (const std::shared_ptr< ChannelClientConnection > &client, int32_t menuType, int32_t shopID=0, int32_t sourceEntityID=0, bool allowInsert=false)
Request an open menu event be started for the supplied client.
bool ResetDemonQuests (const std::shared_ptr< ChannelClientConnection > &client, uint32_t now, const std::shared_ptr< libcomp::DatabaseChangeSet > &changes)
Reset the quests available in from the demons in the COMP and set the demon quest daily count back to zero.
void SendActiveQuestList (const std::shared_ptr< ChannelClientConnection > &client)
Send the client's active quest list.
void SendCompletedQuestList (const std::shared_ptr< ChannelClientConnection > &client)
Send the client's completed quest list.
bool SetChannelLoginEvent (const std::shared_ptr< ChannelClientConnection > &client)
Set the supplied client's ChannelLogin active event and event index so the event chain can be continued when they arrive at the other channel server.
bool StartSystemEvent (const std::shared_ptr< ChannelClientConnection > &client, int32_t sourceEntityID)
Start a placeholder "system" event that does not end until explicitly requested.
void StartWebGame (const std::shared_ptr< ChannelClientConnection > &client, const libcomp::String &sessionID)
Start a pending web-game session with a session ID received from the world server.
bool UpdateDemonQuestCount (const std::shared_ptr< ChannelClientConnection > &client, objects::DemonQuest::Type_t questType, uint32_t targetType=0, int32_t increment=0)
Update the target count for the client's active demon quest if it matches the supplied quest type.
bool UpdateQuest (const std::shared_ptr< ChannelClientConnection > &client, int16_t questID, int8_t phase, bool forceUpdate=false, const std::unordered_map< int32_t, int32_t > &updateFlags={})
Start, update or complete a quest based upon the quest ID and phase supplied.
void UpdateQuestKillCount (const std::shared_ptr< ChannelClientConnection > &client, const std::unordered_map< uint32_t, int32_t > &kills)
Update the client's quest kill counts (normal and demon)
void UpdateQuestTargetEnemies (const std::shared_ptr< ChannelClientConnection > &client)
Update the registered set of enemy types that need to be killed to complete the current quests for the supplied client.
Private Member Functions
void AddDemonQuestRewards (const std::shared_ptr< CharacterState > &cState, const std::shared_ptr< objects::Demon > &demon, std::shared_ptr< objects::DemonQuest > &dQuest)
Calculate and add all rewards to the supplied demon quest.
bool Compare (int32_t value1, int32_t value2, int32_t value3, EventCompareMode compareMode, EventCompareMode defaultCompare=EventCompareMode::DEFAULT_COMPARE, uint16_t validCompareSetting=63)
Compare values using the supplied compare mode from an event condition.
bool Direction (EventContext &ctx)
Signify a direction to the player.
bool EndEvent (const std::shared_ptr< ChannelClientConnection > &client)
End the current event sequence.
bool EvaluateCondition (EventContext &ctx, const std::shared_ptr< ActiveEntityState > &eState, const std::shared_ptr< objects::EventConditionData > &condition, EventCompareMode compareMode=EventCompareMode::DEFAULT_COMPARE)
Evaluate a standard event condition.
bool EvaluateEventCondition (EventContext &ctx, const std::shared_ptr< objects::EventCondition > &condition)
Evaluate an event condition.
bool EvaluateEventConditions (EventContext &ctx, const std::list< std::shared_ptr< objects::EventCondition >> &conditions)
Evaluate a list of event conditions.
bool EvaluateFlagStates (const std::unordered_map< int32_t, int32_t > &flagStates, const std::shared_ptr< objects::EventFlagCondition > &condition)
Evaluate a set of flag states for a standard condition.
bool EvaluatePartnerCondition (const std::shared_ptr< ChannelClientConnection > &client, const std::shared_ptr< objects::EventCondition > &condition)
Evaluate a partner demon based event condition.
bool EvaluateQuestCondition (EventContext &ctx, const std::shared_ptr< objects::EventCondition > &condition)
Evaluate a quest based event condition.
bool EvaluateQuestConditions (EventContext &ctx, int16_t questID)
Evaluate each of the valid condition sets required to start a quest.
bool EvaluateQuestPhaseRequirements (const std::shared_ptr< ChannelClientConnection > &client, int16_t questID, int8_t phase)
Evaluate each of the requirements to complete the current quest phase.
bool ExNPCMessage (EventContext &ctx)
Send an extended NPC based message to the client.
template<class T >
std::shared_ptr< T > GetEvent (EventContext &ctx)
Get the event from the supplied context converted to the proper type.
bool HandleEvent (EventContext &ctx)
Handle an event instance by branching into the appropriate handler function after updating the character's overhead icon if needed.
void HandleNext (EventContext &ctx)
Progress or pop to the next sequential event if one exists.
bool HandleTriFusion (const std::shared_ptr< ChannelClientConnection > &client)
Execute the appropriate (party) tri-fusion event responses.
bool HandleWebGame (const std::shared_ptr< ChannelClientConnection > &client)
Handle all web-game setup steps if no session already exists.
bool ITime (EventContext &ctx)
Send the player an I-Time request.
bool Multitalk (EventContext &ctx)
Start a multitalk event clientside.
bool NPCMessage (EventContext &ctx)
Send an NPC based message to the client.
bool OpenMenu (EventContext &ctx)
Open a menu to the player representing various facilities and functions.
bool PerformActions (EventContext &ctx)
Perform one or many actions from the same types of options configured for object interaction.
bool PlayScene (EventContext &ctx)
Play an in-game cinematic clientside.
bool PrepareTransformScript (EventContext &ctx, std::shared_ptr< libcomp::ScriptEngine > engine)
Prepare the transformation script from the event on the supplied script engine.
bool Prompt (EventContext &ctx)
Prompt the player to choose from set options.
void SetEventStatus (const std::shared_ptr< ChannelClientConnection > &client)
Set the overhead status icon of the client entity to indicate they are involved in an event.
bool TransformEvent (EventContext &ctx, std::shared_ptr< libcomp::ScriptEngine > engine)
Finish preparing and execute the tranformation script configured for the event.
bool VerifyITime (EventContext &ctx, std::shared_ptr< objects::Event > e)
Verify if the supplied event can be executed in regards to the event entity's current I-Time state.
Private Attributes
std::weak_ptr< ChannelServer > mServer
Pointer to the channel server.
Detailed Description
Manager class in charge of processing event sequences as well as quest phase progression and condition evaluation.
Events include things like NPC dialogue, player choice prompts, cinematics and context sensitive menus. Events can be strung together and can progress as well as pop back to previous events much like a dialogue tree.
Definition at line 92 of file EventManager.h.
Constructor & Destructor Documentation
EventManager::EventManager (const std::weak_ptr< ChannelServer > & server)
Create a new EventManager.
Parameters
server Pointer back to the channel server this belongs to
Definition at line 128 of file EventManager.cpp.
EventManager::~EventManager ()
Clean up the EventManager.
Definition at line 133 of file EventManager.cpp.
Member Function Documentation
void EventManager::AddDemonQuestRewards (const std::shared_ptr< CharacterState > & cState, const std::shared_ptr< objects::Demon > & demon, std::shared_ptr< objects::DemonQuest > & dQuest) private
Calculate and add all rewards to the supplied demon quest.
Parameters
cState Pointer to the character state
demon Pointer to the demon with the quest
dQuest Pointer to the demon quest
Definition at line 3366 of file EventManager.cpp.
References channel::CharacterManager::ConvertIDToMaskValues(), libcomp::Randomizer::GetEntry(), mServer, RNG, and SVR_CONST.
Referenced by GenerateDemonQuest().
bool EventManager::Compare (int32_t value1, int32_t value2, int32_t value3, EventCompareMode compareMode, EventCompareMode defaultCompare = EventCompareMode::DEFAULT_COMPARE, uint16_t validCompareSetting = 63) private
Compare values using the supplied compare mode from an event condition.
Parameters
value1 First (or LHS) comparison value
value2 Second (or RHS) comparison value
value3 Third optional comparison value (mostly used for "between" comparisons)
compareMode Compare mode to use when evaluating the values
defaultCompare Default compare mode to use if the compareMode parameter evaluates to DEFAULT_COMPARE. If both equal this value the comparison automatically fails
validCompareSetting Valid comparison flags corresponding to the numeric values associated to EventCompareMode
Returns
true if the condition evalaultes to true, false if the condition evaluates to false or if an error occurred
Definition at line 1358 of file EventManager.cpp.
References libcomp::String::Arg().
Referenced by EvaluateCondition(), EvaluatePartnerCondition(), and EvaluateQuestCondition().
bool EventManager::ContinueChannelChangeEvent (const std::shared_ptr< ChannelClientConnection > & client)
Continue an event that was in progress when the supplied client changed from another channel to the current one.
Parameters
client Pointer to the client connection
Returns
true if an event was started, false if no event needed to be performed
Definition at line 538 of file EventManager.cpp.
References libcomp::String::Arg(), channel::EventManager::EventContext::AutoOnly, channel::EventManager::EventContext::Client, channel::EventManager::EventContext::CurrentZone, channel::EventManager::EventContext::EventInstance, channel::ClientState::GetAccountUID(), channel::ClientState::GetZone(), HandleNext(), channel::ActionOptions::IncrementEventIndex, mServer, channel::ActionOptions::NoEventInterrupt, PrepareEvent(), and channel::state().
bool EventManager::Direction (EventContext & ctx) private
Signify a direction to the player.
Parameters
ctx Execution context of the event
Returns
true on success, false on failure
Definition at line 4675 of file EventManager.cpp.
References channel::EventManager::EventContext::Client, libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteS32Little().
Referenced by HandleEvent().
int8_t EventManager::EndDemonQuest (const std::shared_ptr< ChannelClientConnection > & client, int8_t failCode = 2)
End the client's demon quest in success or failure.
If any costs are required to complete a quest, they will be paid here.
Parameters
client Pointer to the client
failCode Specifies how the quest should be notified to the player should it end in failure. Values include: 0) Successful completion 1) Quest has timed out 2) Quest has failed for a miscellaneous reason
Returns
Failure code matching the input parameter including any reasons why a requested success is actually a failure. If a non-zero value is returned, no update was performed
Definition at line 3803 of file EventManager.cpp.
References libcomp::DatabaseChangeSet::Create(), channel::ClientState::GetAccountUID(), channel::ClientState::GetCharacterState(), libcomp::PersistentObject::GetObjectByUUID(), mServer, channel::state(), SVR_CONST, UpdateQuestTargetEnemies(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS16Little(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteS8().
bool EventManager::EndEvent (const std::shared_ptr< ChannelClientConnection > & client) private
End the current event sequence.
Parameters
client Pointer to the client the event affects
Returns
true on success, false on failure
Definition at line 4789 of file EventManager.cpp.
References EndWebGame(), mServer, channel::state(), and libcomp::Packet::WritePacketCode().
Referenced by EndWebGame(), HandleEvent(), HandleNext(), HandleResponse(), and InterruptEvent().
void EventManager::EndWebGame (const std::shared_ptr< ChannelClientConnection > & client, bool notifyWorld)
End any web-game session currently active for the client.
Parameters
client Pointer to the client connection
notifyWorld Specifies if the world should be notified that the session is ending. Should only ever be false if the world requested that the session be ended
Definition at line 3994 of file EventManager.cpp.
References EndEvent(), channel::ClientState::GetCharacterState(), channel::ClientState::GetWorldCID(), mServer, channel::state(), SVR_CONST, libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteU8().
Referenced by EndEvent(), HandleResponse(), and StartWebGame().
bool EventManager::EvaluateCondition (EventContext & ctx, const std::shared_ptr< ActiveEntityState > & eState, const std::shared_ptr< objects::EventConditionData > & condition, EventCompareMode compareMode = EventCompareMode::DEFAULT_COMPARE) private
Evaluate a standard event condition.
Parameters
ctx Execution context of the event
eState Pointer to the evaluating entity state for the context. Can be null
condition Standard condition to evaluate
Returns
true if standard condition evaluates to true, otherwise false
Definition at line 1441 of file EventManager.cpp.
References libcomp::String::Arg(), channel::EventManager::EventContext::Client, Compare(), channel::CharacterManager::ConvertIDToMaskValues(), channel::EventManager::EventContext::CurrentZone, EVENT_COMPARE_NUMERIC, EVENT_COMPARE_NUMERIC2, channel::EventManager::EventContext::EventInstance, channel::ClientState::GetDemonState(), channel::ClientState::GetEntityClientState(), channel::ClientState::GetWorldCID(), channel::ClientState::GetZone(), channel::CharacterManager::HasValuable(), mServer, channel::NONE, and channel::state().
Referenced by EvaluateEventCondition(), and EvaluateQuestConditions().
bool EventManager::EvaluateEventCondition (EventContext & ctx, const std::shared_ptr< objects::EventCondition > & condition) private
Evaluate an event condition.
Parameters
ctx Execution context of the event
condition Event condition to evaluate
Returns
true if the event condition evaluates to true, otherwise false
Definition at line 922 of file EventManager.cpp.
References libcomp::String::Arg(), channel::EventManager::EventContext::Client, channel::EventManager::EventContext::CurrentZone, EvaluateCondition(), EvaluateFlagStates(), EvaluatePartnerCondition(), EvaluateQuestCondition(), channel::EventManager::EventContext::EventInstance, channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), channel::ClientState::GetWorldCID(), mServer, and channel::state().
Referenced by EvaluateEventConditions().
bool EventManager::EvaluateEventConditions (const std::shared_ptr< Zone > & zone, const std::list< std::shared_ptr< objects::EventCondition >> & conditions, const std::shared_ptr< ChannelClientConnection > & client = nullptr)
Evaluate a list of event conditions for a client.
Parameters
zone Zone to evaluate the conditions in
conditions Event conditions to evaluate
client Optional pointer to the client connection
Returns
true if the event conditions evaluate to true, otherwise false
Definition at line 1413 of file EventManager.cpp.
References channel::EventManager::EventContext::AutoOnly, channel::EventManager::EventContext::Client, channel::EventManager::EventContext::CurrentZone, and channel::EventManager::EventContext::EventInstance.
Referenced by HandleEvent(), HandleNext(), ITime(), and Prompt().
bool EventManager::EvaluateEventConditions (EventContext & ctx, const std::list< std::shared_ptr< objects::EventCondition >> & conditions) private
Evaluate a list of event conditions.
Parameters
ctx Execution context of the event
conditions Event conditions to evaluate
Returns
true if the event conditions evaluate to true, otherwise false
Definition at line 1427 of file EventManager.cpp.
References EvaluateEventCondition().
bool EventManager::EvaluateFlagStates (const std::unordered_map< int32_t, int32_t > & flagStates, const std::shared_ptr< objects::EventFlagCondition > & condition) private
Evaluate a set of flag states for a standard condition.
Parameters
flagStates Map of flag states to evaluate
condition Condition to evaluate
Returns
true if the flag states evaluate to true, otherwise false
Definition at line 1282 of file EventManager.cpp.
Referenced by EvaluateEventCondition(), and EvaluateQuestCondition().
bool EventManager::EvaluatePartnerCondition (const std::shared_ptr< ChannelClientConnection > & client, const std::shared_ptr< objects::EventCondition > & condition) private
Evaluate a partner demon based event condition.
Parameters
client Pointer to the client to evaluate contextually to
condition Event condition to evaluate
Returns
true if the event condition evaluates to true, otherwise false
Definition at line 1122 of file EventManager.cpp.
References Compare(), EVENT_COMPARE_NUMERIC, EVENT_COMPARE_NUMERIC2, channel::ClientState::GetDemonState(), and channel::state().
Referenced by EvaluateEventCondition().
bool EventManager::EvaluateQuestCondition (EventContext & ctx, const std::shared_ptr< objects::EventCondition > & condition) private
Evaluate a quest based event condition.
Parameters
ctx Execution context of the event
condition Event condition to evaluate
Returns
true if the event condition evaluates to true, otherwise false
Definition at line 1195 of file EventManager.cpp.
References channel::EventManager::EventContext::Client, Compare(), channel::CharacterManager::ConvertIDToMaskValues(), EvaluateFlagStates(), EvaluateQuestConditions(), EvaluateQuestPhaseRequirements(), EVENT_COMPARE_NUMERIC, channel::ClientState::GetCharacterState(), mServer, and channel::state().
Referenced by EvaluateEventCondition().
bool EventManager::EvaluateQuestConditions (EventContext & ctx, int16_t questID) private
Evaluate each of the valid condition sets required to start a quest.
Parameters
ctx Execution context of the event
questID ID of the quest being evaluated
Returns
true if the any of the condition sets all evaluated to true, false if no set's conditions all evaluated to true
Definition at line 874 of file EventManager.cpp.
References libcomp::String::Arg(), channel::EventManager::EventContext::CurrentZone, EvaluateCondition(), channel::EventManager::EventContext::EventInstance, and mServer.
Referenced by EvaluateQuestCondition().
bool EventManager::EvaluateQuestPhaseRequirements (const std::shared_ptr< ChannelClientConnection > & client, int16_t questID, int8_t phase) private
Evaluate each of the requirements to complete the current quest phase.
Parameters
client Pointer to the client to evaluate contextually to
questID ID of the quest to check
phase Current phase ID, acts as assurance that the right phase is being checked
Returns
true if all of the current phase's completion requirements have been met, false if any have not been met or the phase supplied is not the current phase
Definition at line 2677 of file EventManager.cpp.
References libcomp::String::Arg(), channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), mServer, channel::NONE, and channel::state().
Referenced by EvaluateQuestCondition().
bool EventManager::ExNPCMessage (EventContext & ctx) private
Send an extended NPC based message to the client.
Parameters
ctx Execution context of the event
Returns
true on success, false on failure
Definition at line 4427 of file EventManager.cpp.
References channel::EventManager::EventContext::Client, channel::EventManager::EventContext::EventInstance, libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS16Little(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteS8().
Referenced by HandleEvent().
std::shared_ptr< objects::DemonQuest > EventManager::GenerateDemonQuest (const std::shared_ptr< CharacterState > & cState, const std::shared_ptr< objects::Demon > & demon)
Generate a demon quest for the supplied character and demon.
Parameters
cState Pointer to the character state
demon Pointer to the demon that will have the quest
Returns
Pointer to the newly generated demon quest, null if an error occurred
Definition at line 2849 of file EventManager.cpp.
References AddDemonQuestRewards(), libcomp::String::Arg(), FUSION_RACE_MAP, libcomp::Randomizer::GetEntry(), mServer, RNG, SVR_CONST, and channel::Zone::TimeRestrictionActive().
template<class T > std::shared_ptr<T> channel::EventManager::GetEvent (EventContext & ctx) inline private
Get the event from the supplied context converted to the proper type.
If the event is configured with a transformation script, a transformed copy will be returned and set on the context.
Parameters
ctx Execution context of the event
Returns
true on success, false on failure
Definition at line 580 of file EventManager.h.
References channel::EventManager::EventContext::EventInstance, PrepareTransformScript(), TransformEvent(), and VerifyITime().
bool EventManager::HandleEvent (const std::shared_ptr< ChannelClientConnection > & client, const libcomp::String & eventID, int32_t sourceEntityID, const std::shared_ptr< Zone > & zone = nullptr, EventOptions options = {})
Handle a new event based upon the supplied ID, relative to an optional entity.
Parameters
client Pointer to the client the event affects, can be null
eventID ID of the event to handle
sourceEntityID Optional source of an event to focus on
zone Pointer to the zone where the event is executing. If the client is specified this will be overridden
options Optional parameters to modify event execution
Returns
true on success, false on failure
Definition at line 137 of file EventManager.cpp.
References channel::EventOptions::ActionGroupID, channel::EventOptions::AutoOnly, channel::EventManager::EventContext::AutoOnly, channel::EventManager::EventContext::Client, channel::EventManager::EventContext::CurrentZone, channel::EventManager::EventContext::EventInstance, channel::EventOptions::NoInterrupt, PrepareEvent(), channel::EventOptions::TransformScriptParams, and channel::EventManager::EventContext::TransformScriptParams.
Referenced by HandleEvent(), HandleNext(), HandleResponse(), ITime(), and RequestMenu().
bool EventManager::HandleEvent (const std::shared_ptr< ChannelClientConnection > & client, const std::shared_ptr< objects::EventInstance > & instance)
Handle an event instance by branching into the appropriate handler function after updating the character's overhead icon if needed.
Parameters
client Pointer to the client the event affects
instance Event instance to handle
Returns
true on success, false on failure
Definition at line 3929 of file EventManager.cpp.
References channel::EventManager::EventContext::AutoOnly, channel::EventManager::EventContext::Client, channel::EventManager::EventContext::CurrentZone, channel::EventManager::EventContext::EventInstance, and HandleEvent().
bool EventManager::HandleEvent (EventContext & ctx) private
Handle an event instance by branching into the appropriate handler function after updating the character's overhead icon if needed.
Parameters
ctx Execution context of the event
Returns
true on success, false on failure
Definition at line 4040 of file EventManager.cpp.
References libcomp::String::Arg(), channel::EventManager::EventContext::AutoOnly, channel::EventManager::EventContext::Client, Direction(), EndEvent(), EvaluateEventConditions(), channel::EventManager::EventContext::EventInstance, ExNPCMessage(), HandleNext(), ITime(), Multitalk(), NPCMessage(), OpenMenu(), PerformActions(), PlayScene(), Prompt(), SetEventStatus(), channel::state(), and to_underlying().
void EventManager::HandleNext (EventContext & ctx) private
Progress or pop to the next sequential event if one exists.
If no event is found, the event sequence is ended.
Parameters
ctx Execution context of the event
Definition at line 4193 of file EventManager.cpp.
References channel::EventOptions::ActionGroupID, libcomp::String::Arg(), channel::EventOptions::AutoOnly, channel::EventManager::EventContext::AutoOnly, channel::EventManager::EventContext::Client, channel::EventManager::EventContext::CurrentZone, EndEvent(), EvaluateEventConditions(), channel::EventManager::EventContext::EventInstance, channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), HandleEvent(), libcomp::String::IsEmpty(), mServer, channel::EventOptions::NoInterrupt, PrepareEvent(), and channel::state().
Referenced by ContinueChannelChangeEvent(), HandleEvent(), HandleResponse(), and PerformActions().
bool EventManager::HandleResponse (const std::shared_ptr< ChannelClientConnection > & client, int32_t responseID, int64_t objectID = -1)
React to a response based on the current event of a client.
Parameters
client Pointer to the client sending the response
responseID Value representing the player's response contextual to the current event type (or -1 for a menu "next" enable flag)
objectID Optional object ID selected as part of the client response
Returns
true on success, false on failure
Definition at line 296 of file EventManager.cpp.
References libcomp::String::Arg(), channel::EventManager::EventContext::AutoOnly, channel::EventManager::EventContext::Client, channel::EventManager::EventContext::CurrentZone, EndEvent(), EndWebGame(), channel::EventManager::EventContext::EventInstance, channel::ClientState::GetCharacterState(), libcomp::PersistentObject::GetObjectByUUID(), channel::ClientState::GetObjectUUID(), HandleEvent(), HandleNext(), mServer, channel::state(), and to_underlying().
bool EventManager::HandleTriFusion (const std::shared_ptr< ChannelClientConnection > & client) private
Execute the appropriate (party) tri-fusion event responses.
Parameters
client Pointer to the client the event affects
Returns
true on success, false on failure
Definition at line 4818 of file EventManager.cpp.
References channel::ChannelClientConnection::BroadcastPacket(), channel::ClientState::GetCharacterState(), mServer, channel::state(), libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteS32Little().
Referenced by OpenMenu().
bool EventManager::HandleWebGame (const std::shared_ptr< ChannelClientConnection > & client) private
Handle all web-game setup steps if no session already exists.
Parameters
client Pointer to the client the event affects
Returns
true if the session was already active, false if it was created
Definition at line 4879 of file EventManager.cpp.
References channel::ClientState::GetCharacterState(), channel::ClientState::GetCurrentMenuShopID(), channel::ClientState::GetWorldCID(), mServer, channel::state(), libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteU8().
Referenced by OpenMenu().
int32_t EventManager::InterruptEvent (const std::shared_ptr< ChannelClientConnection > & client)
Stop the client's current event and return the source entity ID if one existed.
Parameters
client Pointer to the client
Returns
Source entity ID of the interrupted event
Definition at line 208 of file EventManager.cpp.
References EndEvent(), and channel::state().
bool EventManager::ITime (EventContext & ctx) private
Send the player an I-Time request.
Parameters
ctx Execution context of the event
Returns
true on success, false on failure
Definition at line 4692 of file EventManager.cpp.
References libcomp::String::Arg(), channel::EventManager::EventContext::AutoOnly, channel::EventManager::EventContext::Client, channel::EventManager::EventContext::CurrentZone, EvaluateEventConditions(), channel::EventManager::EventContext::EventInstance, HandleEvent(), PrepareEvent(), RequestMenu(), SVR_CONST, libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS16Little(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteS8().
Referenced by HandleEvent().
bool EventManager::Multitalk (EventContext & ctx) private
Start a multitalk event clientside.
Parameters
ctx Execution context of the event
Returns
true on success, false on failure
Definition at line 4449 of file EventManager.cpp.
References channel::EventManager::EventContext::Client, channel::EventManager::EventContext::EventInstance, libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteS32Little().
Referenced by HandleEvent().
bool EventManager::NPCMessage (EventContext & ctx) private
Send an NPC based message to the client.
Parameters
ctx Execution context of the event
Returns
true on success, false on failure
Definition at line 4406 of file EventManager.cpp.
References channel::EventManager::EventContext::Client, channel::EventManager::EventContext::EventInstance, libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteS32Little().
Referenced by HandleEvent().
bool EventManager::OpenMenu (EventContext & ctx) private
Open a menu to the player representing various facilities and functions.
Parameters
ctx Execution context of the event
Returns
true on success, false on failure
Definition at line 4561 of file EventManager.cpp.
References channel::EventManager::EventContext::Client, channel::EventManager::EventContext::EventInstance, channel::ClientState::GetAccountUID(), channel::ClientState::GetBazaarState(), channel::ClientState::GetClientStringEncoding(), channel::ClientState::GetZone(), HandleTriFusion(), HandleWebGame(), mServer, channel::state(), SVR_CONST, libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteString16Little().
Referenced by HandleEvent(), RequestMenu(), and StartWebGame().
bool EventManager::PerformActions (EventContext & ctx) private
Perform one or many actions from the same types of options configured for object interaction.
Parameters
ctx Execution context of the event
Returns
true on success, false on failure
Definition at line 4649 of file EventManager.cpp.
References channel::ActionOptions::AutoEventsOnly, channel::EventManager::EventContext::AutoOnly, channel::EventManager::EventContext::Client, channel::EventManager::EventContext::CurrentZone, channel::EventManager::EventContext::EventInstance, channel::ActionOptions::GroupID, HandleNext(), channel::ActionOptions::IncrementEventIndex, mServer, and channel::ActionOptions::NoEventInterrupt.
Referenced by HandleEvent().
bool EventManager::PlayScene (EventContext & ctx) private
Play an in-game cinematic clientside.
Parameters
ctx Execution context of the event
Returns
true on success, false on failure
Definition at line 4543 of file EventManager.cpp.
References channel::EventManager::EventContext::Client, libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteS8().
Referenced by HandleEvent().
std::shared_ptr< objects::EventInstance > EventManager::PrepareEvent (const libcomp::String & eventID, int32_t sourceEntityID)
Prepare a new event based upon the supplied ID, relative to an optional entity.
Parameters
eventID ID of the event to handle
sourceEntityID Optional source of an event to focus on
Returns
Pointer to the new EventInstance or nullptr on failure
Definition at line 162 of file EventManager.cpp.
References libcomp::String::Arg(), and mServer.
Referenced by ContinueChannelChangeEvent(), HandleEvent(), HandleNext(), and ITime().
bool EventManager::PrepareTransformScript (EventContext & ctx, std::shared_ptr< libcomp::ScriptEngine > engine) private
Prepare the transformation script from the event on the supplied script engine.
Parameters
ctx Execution context of the event
engine Script engine to prepare the script for
Returns
true on success, false on failure
Definition at line 4925 of file EventManager.cpp.
References libcomp::String::Arg(), channel::EventManager::EventContext::EventInstance, and mServer.
Referenced by GetEvent().
bool EventManager::Prompt (EventContext & ctx) private
Prompt the player to choose from set options.
Parameters
ctx Execution context of the event
Returns
true on success, false on failure
Definition at line 4469 of file EventManager.cpp.
References channel::EventManager::EventContext::Client, EvaluateEventConditions(), channel::EventManager::EventContext::EventInstance, mServer, libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteS32Little().
Referenced by HandleEvent().
bool EventManager::RequestMenu (const std::shared_ptr< ChannelClientConnection > & client, int32_t menuType, int32_t shopID = 0, int32_t sourceEntityID = 0, bool allowInsert = false)
Request an open menu event be started for the supplied client.
Parameters
client Pointer to the client connection
menuType Type of menu being opened
shopID Optional shop ID of the menu being opened
sourceEntityID Optional source of an event to focus on
allowInsert If true the menu can be requested with an event currently active. If false an an active event causes a failure.
Returns
true if request was sent to the client, false otherwise
Definition at line 229 of file EventManager.cpp.
References libcomp::String::Arg(), channel::EventManager::EventContext::AutoOnly, channel::EventManager::EventContext::Client, channel::EventManager::EventContext::EventInstance, channel::ClientState::GetAccountUID(), channel::ClientState::GetCurrentMenuShopID(), HandleEvent(), OpenMenu(), and channel::state().
Referenced by ITime().
bool EventManager::ResetDemonQuests (const std::shared_ptr< ChannelClientConnection > & client, uint32_t now, const std::shared_ptr< libcomp::DatabaseChangeSet > & changes)
Reset the quests available in from the demons in the COMP and set the demon quest daily count back to zero.
The caller is responsible for actually saving the changes that are written to the supplied changeset.
Parameters
client Pointer to the client
now Current system time to be set on the CharacterProgress records when reseting the quests
changes Pointer to the changeset to apply the changes to
Returns
true if one or more demon had quests reset, false if only the time reset occurred
Definition at line 3736 of file EventManager.cpp.
References channel::ClientState::GetCharacterState(), channel::CharacterManager::GetFamiliarityRank(), channel::ClientState::GetObjectID(), channel::state(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS64Little(), and libcomp::Packet::WriteS8().
Referenced by channel::ChannelServer::HandleDemonQuestReset().
void EventManager::SendActiveQuestList (const std::shared_ptr< ChannelClientConnection > & client)
Send the client's active quest list.
Parameters
client Pointer to the client
Definition at line 2807 of file EventManager.cpp.
References channel::ClientState::GetCharacterState(), channel::state(), libcomp::Packet::WriteArray(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS16Little(), and libcomp::Packet::WriteS8().
Referenced by UpdateQuest().
void EventManager::SendCompletedQuestList (const std::shared_ptr< ChannelClientConnection > & client)
Send the client's completed quest list.
Parameters
client Pointer to the client
Definition at line 2833 of file EventManager.cpp.
References channel::ClientState::GetCharacterState(), channel::state(), libcomp::Packet::WriteArray(), libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteU16Little().
Referenced by UpdateQuest().
bool EventManager::SetChannelLoginEvent (const std::shared_ptr< ChannelClientConnection > & client)
Set the supplied client's ChannelLogin active event and event index so the event chain can be continued when they arrive at the other channel server.
Parameters
client Pointer to the client connection
Returns
true on success, false on failure
Definition at line 510 of file EventManager.cpp.
References channel::state().
void EventManager::SetEventStatus (const std::shared_ptr< ChannelClientConnection > & client) private
Set the overhead status icon of the client entity to indicate they are involved in an event.
Parameters
client Pointer to the client connection
Definition at line 4187 of file EventManager.cpp.
References mServer.
Referenced by HandleEvent(), and StartSystemEvent().
bool EventManager::StartSystemEvent (const std::shared_ptr< ChannelClientConnection > & client, int32_t sourceEntityID)
Start a placeholder "system" event that does not end until explicitly requested.
Useful for certain actions that lock the player in place until they automatically complete.
Parameters
client Pointer to the client the event affects
sourceEntityID Optional source of an event to focus on
Returns
true if the event was started, false if it could not
Definition at line 189 of file EventManager.cpp.
References SetEventStatus(), and channel::state().
void EventManager::StartWebGame (const std::shared_ptr< ChannelClientConnection > & client, const libcomp::String & sessionID)
Start a pending web-game session with a session ID received from the world server.
Session IDs are assumed to have been received only once both the world and lobby have accepted the channel's request as valid.
Parameters
client Pointer to the client connection
sessionID Session Id received from the world server
Definition at line 3948 of file EventManager.cpp.
References libcomp::String::Arg(), channel::EventManager::EventContext::AutoOnly, channel::EventManager::EventContext::Client, channel::EventManager::EventContext::CurrentZone, EndWebGame(), channel::EventManager::EventContext::EventInstance, channel::ClientState::GetAccountUID(), channel::ClientState::GetZone(), OpenMenu(), channel::state(), and SVR_CONST.
bool EventManager::TransformEvent (EventContext & ctx, std::shared_ptr< libcomp::ScriptEngine > engine) private
Finish preparing and execute the tranformation script configured for the event.
Parameters
ctx Execution context of the event
engine Script engine to execute the script using
Returns
true on success, false on failure
Definition at line 4960 of file EventManager.cpp.
References channel::EventManager::EventContext::Client, channel::EventManager::EventContext::CurrentZone, channel::EventManager::EventContext::EventInstance, channel::ClientState::GetCharacterState(), channel::ClientState::GetDemonState(), channel::ClientState::GetEntityClientState(), channel::state(), and channel::EventManager::EventContext::TransformScriptParams.
Referenced by GetEvent().
bool EventManager::UpdateDemonQuestCount (const std::shared_ptr< ChannelClientConnection > & client, objects::DemonQuest::Type_t questType, uint32_t targetType = 0, int32_t increment = 0)
Update the target count for the client's active demon quest if it matches the supplied quest type.
Parameters
client Pointer to the client
questType Type of quest required to perform the update
targetType Type of target that has changed. For item quests supplying no value will recalculate the count based on the current item counts in the inventory
increment Value to increase the target count by
Returns
true if any updates occurred
Definition at line 3664 of file EventManager.cpp.
References channel::ClientState::GetCharacterState(), mServer, PACKET_DEMON_QUEST_COUNT_UPDATE, channel::state(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS32Little(), and libcomp::Packet::WriteU32Little().
Referenced by UpdateQuestKillCount().
bool EventManager::UpdateQuest (const std::shared_ptr< ChannelClientConnection > & client, int16_t questID, int8_t phase, bool forceUpdate = false, const std::unordered_map< int32_t, int32_t > & updateFlags = {})
Start, update or complete a quest based upon the quest ID and phase supplied.
Restrictions are enforced to disallow skipping phases, etc.
Parameters
client Pointer to the client the quest is associated to
questID ID of the quest being updated
phase Phase to update the quest to. If 0 is supplied, the quest will be started. If -1 is supplied, the quest will be completed. Otherwise the quest will move to that phase.
forceUpdate Optional parameter to bypass quest state based restrictions and force the quest into the specified state
updateFlags Optional parameter to set flags on the next or current phase
Returns
true on success (or no phase update needed), false on failure
Definition at line 603 of file EventManager.cpp.
References libcomp::String::Arg(), channel::CharacterManager::ConvertIDToMaskValues(), libcomp::DatabaseChangeSet::Create(), channel::ClientState::GetAccountUID(), channel::ClientState::GetCharacterState(), mServer, SendActiveQuestList(), SendCompletedQuestList(), channel::state(), UpdateQuestTargetEnemies(), libcomp::Packet::WritePacketCode(), libcomp::Packet::WriteS16Little(), and libcomp::Packet::WriteS8().
void EventManager::UpdateQuestKillCount (const std::shared_ptr< ChannelClientConnection > & client, const std::unordered_map< uint32_t, int32_t > & kills)
Update the client's quest kill counts (normal and demon)
Parameters
client Pointer to the client with active kill quests
kills Map of demon types to the number killed
Definition at line 787 of file EventManager.cpp.
References channel::ClientState::GetAccountUID(), channel::ClientState::GetCharacterState(), mServer, channel::state(), UpdateDemonQuestCount(), libcomp::Packet::WriteArray(), libcomp::Packet::WritePacketCode(), and libcomp::Packet::WriteS16Little().
void EventManager::UpdateQuestTargetEnemies (const std::shared_ptr< ChannelClientConnection > & client)
Update the registered set of enemy types that need to be killed to complete the current quests for the supplied client.
Parameters
client Pointer to the client to update
Definition at line 2761 of file EventManager.cpp.
References channel::ClientState::GetCharacterState(), mServer, and channel::state().
Referenced by EndDemonQuest(), and UpdateQuest().
bool EventManager::VerifyITime (EventContext & ctx, std::shared_ptr< objects::Event > e) private
Verify if the supplied event can be executed in regards to the event entity's current I-Time state.
Parameters
ctx Execution context of the event
e Pointer to the event to be executed
Returns
true if the event can be executed, false if it is not valid
Definition at line 5003 of file EventManager.cpp.
References channel::EventManager::EventContext::Client, and channel::state().
Referenced by GetEvent().
Member Data Documentation
std::weak_ptr<ChannelServer> channel::EventManager::mServer private
Pointer to the channel server.
Definition at line 646 of file EventManager.h.
Referenced by AddDemonQuestRewards(), ContinueChannelChangeEvent(), EndDemonQuest(), EndEvent(), EndWebGame(), EvaluateCondition(), EvaluateEventCondition(), EvaluateQuestCondition(), EvaluateQuestConditions(), EvaluateQuestPhaseRequirements(), GenerateDemonQuest(), HandleNext(), HandleResponse(), HandleTriFusion(), HandleWebGame(), OpenMenu(), PerformActions(), PrepareEvent(), PrepareTransformScript(), Prompt(), SetEventStatus(), UpdateDemonQuestCount(), UpdateQuest(), UpdateQuestKillCount(), and UpdateQuestTargetEnemies().
The documentation for this class was generated from the following files:
EventManager.h
EventManager.cpp